### ISSUE TITLE
Let users launch more than one server in JupyterHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#100]
The JupyterHub control panel only lets each user launch a single server. 

I think we should let a user run multiple servers simultaneously. I think this will be quite common since they might want servers corresponding to different environments/packages.

It looks like JupyterHub is still adding support for this jupyterhub/jupyterhub#766

**Comment by yuvipanda** [comment]
All the API & backend work needed for this has been completed in JupyterHub 0.8 - there's no UI for it yet. From my understanding, we don't have anyone working on it right now (mostly from a priorities perspective!), so if anyone here has cycles to help out that'd be great! http://jupyterhub.readthedocs.io/en/latest/reference/rest.html#enabling-users-to-spawn-multiple-named-servers-via-the-api has a bit more info on the API.

**Comment by jlewi** [comment]
I think this would be a great feature so I'm adding it to our 0.2.0 backlog but as P2 because I don't know how realistic finding resources for it is.

/cc @ojarjur 
/cc @pdmack

**Comment by jlewi** [comment]
This is fixed in Kubeflow 0.5.
