### ISSUE TITLE
Serving path should support logging request input/output

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1000]
This will enable continuous training and skew detection etc.

**Comment by jlewi** [comment]
Should we do this in TF serving? Can we do it in a sidecar? Does ISTIO provide any relevant functionality?

**Comment by lluunn** [comment]
I think we can do in sidecar.
I remember some discussion that we should not do it in istio as they are very light weight. Will try to find them and propose a solution.

**Comment by lluunn** [comment]
TF Serving seems to support this: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/core/request_logger.h
Will investigate more.

**Comment by lluunn** [comment]
To do it in TF Serving, we need to implement [LogCollector](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/core/log_collector.h) for the backend (e.g. BigQuery)

**Comment by lluunn** [comment]
I think doing it with sidecar is better
1. it can be easily reused by other frameworks
1. it's easier to make progress (put code in kubeflow v.s. in tf serving)

Fluentd should already support logging to BQ, GCS etc. I will try using that.

**Comment by jlewi** [comment]
Closing this issue since initial PRs have been merged and we have issues filed for additional work.
