### ISSUE TITLE
Deployment Manager for GKE cannot update bootstrapperConfig

### ISSUE THREAD

**Issue by activatedgeek** [kubeflow/kubeflow#1003]
Updating the `bootstrapperConfig` (for instance adding new components to deploy with Kubeflow) and executing a `gcloud deployment-manager deployments update ...` will not deploy the newly added component.

The file in question is [cluster-kubeflow.yaml#L85](../blob/master/docs/gke/configs/cluster-kubeflow.yaml#L85).

**Comment by jlewi** [comment]
I think this is working as intended.

If we want to support making updates after the cluster is running we should be using GitOps.
See #971 

We should be pushing the ksonnet app to source control and that's what users should modify. Ideally we'd be running weave flux and it would auto sync.
