### ISSUE TITLE
TensorFlow 1.8 not included in stock Jupyter Images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1014]
We should fix this for 0.2

/assign jlewi

**Comment by ankushagarwal** [comment]
I released them but I forgot to add them to the list

https://pantheon.corp.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-1.8.0-notebook-cpu
https://pantheon.corp.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-1.8.0-notebook-gpu

**Comment by jlewi** [comment]
@ankushagarwal NP; #1015 is out for review.
