### ISSUE TITLE
Update PyTorch Image to officially released one

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/kubeflow#1020]
Update PytorchImage in https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet#L9 to the one in kubeflow public image repo

**Comment by johnugeorge** [comment]
If automatic release is not setup, we might have to manually release a build and update it in ksonnet

**Comment by kunmingg** [comment]
Will fix auto-release workflow.

**Comment by jlewi** [comment]
P0. Because we want this fixed before the next RC cut.

**Comment by kunmingg** [comment]
@johnugeorge New image at gcr.io/kubeflow-images-public/pytorch-operator:v20180619-2e19016
