### ISSUE TITLE
Use GKE auto-scaling when configuring node pools in the provided Deployment Manager configs

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#1033]
Right now the node pool sizes are statically configured [here](https://github.com/kubeflow/kubeflow/blob/master/docs/gke/configs/cluster.jinja#L141)

GKE auto-scaling can be useful for cases when one wants to schedule a training job and automatically provision and de-provision GPU nodes.

**Comment by ankushagarwal** [comment]
Making it configurable sounds reasonable.

**Comment by richardsliu** [comment]
https://github.com/kubeflow/kubeflow/pull/1273
