### ISSUE TITLE
Jupyter can't start pod; the default spawner image is way too old

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1041]
I got the following error when trying to start a notebook

```
kubectl logs jupyter-accounts-2egoogle-2ecom-3ajlewi-40google-2ecom
[FATAL tini (7)] Executing child process 'start-singleuser.sh' failed: 'Permission denied'
```
Notebook image is
image: gcr.io/kubeflow/tensorflow-notebook-cpu:latest
imageID: docker-pullable://gcr.io/kubeflow/tensorflow-notebook-cpu@sha256:964dbfa5d435aa61b2d3b90cf4c7992040b83d2dd9525fc3f518316b03f64b62

I didn't specify any image when I clicked spawn.

It looks like our default image used by the spawner is "latest" which is pointing to a very old image (even the registry is wrong).

We should probably be pinning to a specific image as our default image so we don't get broken by moving the latest tag.

We should fix this in 0.2.

@pdmack Could you take a look?

/assign @pdmack 

@kunmingg We should cherry pick thia after its fixed.

**Comment by kunmingg** [comment]
@pdmack Can get nightly release by:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

**Comment by jlewi** [comment]
Why do we need to push new images?

Can't we use one of the images already defined in kube_form_spawner.py
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/kubeform_spawner.py#L25

It looks like the default is set here:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/kubeform_spawner.py#L60

Can we just update that?

Ideally what we'd do is use python to get the latest version of TF with CPU image in the list of images specified here
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/kubeform_spawner.py#L17

This way we don't have to update the code in two places. Or we could do something like

```
  default_image = "tensorflow-1.8.0-notebook-cpu:v20180607-476e150e"
  tag = "v20180607-476e150e"
  other_images = [default_image]
  for tf_version in ["1.6", ....]:
     cpu_image = "tensorflow-{0}-notebook-cpu:{tag}".format(tf_version)
     if not cpu_image in other_images
      ...
  
   generate HTML from other_images
```

**Comment by pdmack** [comment]
Sorry, but why don't we just have mnemonic images for the default instead of updating dates and sha in code?

`gcr.io/kubeflow-images-public/tensorflow-notebook-cpu:latest`

In this case, our released TF 1.8 CPU.

**Comment by jlewi** [comment]
I don't want a release to break because someone decided to build a new image and tag it "latest".

The behavior of release X should never change; so all image references should be immutable.

If the default image is "latest" then every time we build a new image we are affecting all releases.
This could break old releases. For example, suppose in 0.2 we made changes to our Jupyter images that we're not backwards compatible with older version of JupyterHub in 0.1. 

Then an image tagged "latest" can't work for 0.2 and 0.1. So if we update "latest" to work with 0.2, we would no longer have a default image for 0.1. that works. So if a user was using 0.1. and not specifying an image they would find this behavior to suddenly and mysteriously be broken.

**Comment by pdmack** [comment]
I understand all that, but a new user who basically does "dealer's choice" by not explicitly specifying an image also has a smell. They are basically saying: I don't care which version of TF I'm getting. Even if it potentially doesn't run on their aged node CPU. It possibly serves as a canary to the project that there's either something wrong with that "latest" image (maybe nightlies as @kunmingg mentioned) or our infra has changed and there is perhaps a compat issue. In your particular case, the project velocity and the old default lead to an unsurprising result, and not worthy of further investigation. But at some point soon the project might have/want to start providing some stability assurances.

IMHO, this seems to me to be coming full circle back to the notion of potentially laying down the KF release tag in the NB images (e.g., v0.2.0-rc.0). A date and SHA is barely meaningful to us but I'm not sure what help it is at all for a new user.

**Comment by jlewi** [comment]
I have no objection to attaching a set of additional mutable labels e.g ":latest" or ":nightly" and letting users use them. I just don't think we should ever use them in a release without explicit user action. If a user wants to use latest they can enter that themselves. 

I think we could potentially use ":latest" in our nightly/dev environments to canary things. 

Regarding tagging images with release. I think that makes sense. I think the issue is that right now our build/release infrastructure doesn't make that easy. When we build an image we don't know what tag it will be assigned. Once we do know the tag and add it we would need to push a commit updating references to that image.

I'm not really expecting users to pay much attention to the image tag. My expectation is they mostly focus on the TF version and CPU vs. GPU. The tag is mostly for us.
