### ISSUE TITLE
nvidia-smi fails for TFJob's but not for similarly configured Job's

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1042]
Similarly configured Jobs and TFJobs running the nvidia-smi command succeed and fail respectively.

Running cluster with NVIDIA device plugin ds, via https://cloud.google.com/kubernetes-engine/docs/concepts/gpus (on GKE)

* Job, running nvidia-smi, successfully shows GPU device
https://gist.github.com/cwbeitel/c9e31349cb0cacd16268d2bf31fc0f1a#file-logs-txt-L1

* Job, running ls /usr/local, shows presence of /usr/local/nvidia
https://gist.github.com/cwbeitel/c9e31349cb0cacd16268d2bf31fc0f1a#file-logs-txt-L41

* TFJob, running ls /usr/local, /usr/local/nvidia is not present
https://gist.github.com/cwbeitel/c9e31349cb0cacd16268d2bf31fc0f1a#file-logs-txt-L162

* TFJob, running nvidia-smi, gives command not found
https://gist.github.com/cwbeitel/c9e31349cb0cacd16268d2bf31fc0f1a#file-logs-txt-L314

**Comment by jlewi** [comment]
It looks like for Job you are setting "limits" but in "TFJob" you are setting "requests"

I think you need to set limits not requests for GKE to properly configure GPU access for the pod.

**Comment by cwbeitel** [comment]
Brilliant. With that fix the nvidia-smi command runs and shows the available GPU.
