### ISSUE TITLE
Cross-Origin Resource Sharing with TF Jobs Dashboard

### ISSUE THREAD

**Issue by TheJaySmith** [kubeflow/kubeflow#1046]
Hello, 

Not sure if this is a localized issue or a larger issue but I went through these steps to deploy Kubeflow on GKE:

https://www.kubeflow.org/docs/started/getting-started-gke/#create-oauth-client-credentials

Was able to get it all deployed and working properly and he JupyterHub is working like a charm. I cannot deploy TFJobs.

When I hit "Deploy" nothing happens. I decided to dive deeper and checked and inspected the page and checked the JS console and saw this (withheld specific information). 

 https://accounts.google.com/o/oauth2/v2/auth?client_id=<withheld>: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://<namewithheld>.endpoints.<projectwithheld>.cloud.goog' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Looking at the actual call (tfjob), it appears to 401. 

Has anyone else seen this issue? Is there a workaround? Thanks!

**Comment by kkasravi** [comment]
Hi @TheJaySmith see #574 - there is a PR I'm working on with @swiftdiaries in the tf-operator repo
See [#688](https://github.com/kubeflow/tf-operator/pull/688)

You could dup this to #574. Thanks for taking the time to dig into the problem and open an issue.

**Comment by TheJaySmith** [comment]
Hello @kkasravi Thank's for the quick response!
Duplicate of #574
