### ISSUE TITLE
TFJob prototype's default TFVersion should be v1alpha2

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/kubeflow#1049]
TFOperator defaults to v1alpha2 but TFJob defaults to v1alpha1 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/prototypes/tf-job-operator.jsonnet#L12
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-job/tf-job.libsonnet#L47

Defaults should be same for consistency.

**Comment by jlewi** [comment]
As discussed may we should split up all.jsonnet and no longer have it.

**Comment by jlewi** [comment]
@johnugeorge https://github.com/kubeflow/tf-operator/blob/master/examples/v1alpha2/dist-mnist/tj_job_mnist.yaml looks like the v1alpha2 not the v1alpha1 spec. Is there something I'm missing?

**Comment by vmarkovtsev** [comment]
Hi, I am the unfortunate follower of the official codelabs on kubeflow, such as https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html

They mention the tf-job package, which is removed in this commit. What shall I install instead?
