### ISSUE TITLE
camelCase for some recently fixed params

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#1050]
These should be camelCase:
```
// @optionalParam AmbassadorServiceType string ClusterIP The service type for the API Gateway.
// @optionalParam AmbassadorImage string quay.io/datawire/ambassador:0.30.1 The image for the API Gateway.
// @optionalParam StatsdImage string quay.io/datawire/statsd:0.30.1 The image for the Stats and Monitoring.
```

**Comment by ashahba** [comment]
@jlewi I can work on this one if nobody has started doing anything on it yet.

**Comment by lluunn** [comment]
/assign @ashahba 
Thank you

**Comment by ashahba** [comment]
Thanks @lluunn 
I'll get a PR ready.

**Comment by jlewi** [comment]
@ashahba any progress on a PR? We'd like to cut an RC this week for 0.3.  #1541

**Comment by pdmack** [comment]
The ambassador ones got cleaned up by #1207 and #1324 I think.

**Comment by pdmack** [comment]
But [mxnet-job](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet#L9) and [weaveflux](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/weaveflux/prototypes/weaveflux.jsonnet#L6) need cleanup though.

**Comment by ashahba** [comment]
@jlewi I get the PR in today. Sorry for the delay.

**Comment by ashahba** [comment]
Hi @jlewi Here is what I think need to be changed, please let me know if that's more that what we need:

```
// @optionalParam image_gpu string mxjob/mxnet:gpu The docker image to use when using GPUs.
// @optionalParam num_schedulers number 1 The number of scheduler to use
// @optionalParam num_servers number 1 The number of servers to use
// @optionalParam num_workers number 1 The number of workers to use
// @optionalParam num_gpus number 0 The number of GPUs to attach to workers.
```
starting here:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet#L9

and
```
// @optionalParam giturl string null Your default git URL.
```
starting here:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/weaveflux/prototypes/weaveflux.jsonnet#L6

and
```
// @optionalParam testing_image string gcr.io/kubeflow-releasing/worker:latest The image where we run the workflow.
...
// @optionalParam prow_env string REPO_OWNER=kubeflow,REPO_NAME=kubeflow,PULL_BASE_SHA=master Self explanatory.
...
// @optionalParam extra_repos string kubeflow/testing@HEAD Append your repo here (; separated) if your image is not in kubeflow.
// @optionalParam extra_args string null args for your build_image.sh
```
starting here:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/automation/prototypes/release.jsonnet#L14

**Comment by ashahba** [comment]
Rest of parameters seem to have been already fixed 🙂
