### ISSUE TITLE
[gcp-click-to-deploy] Deploy click to deploy web app

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1056]
We should deploy the click to deploy web app. Maybe
deploy-gcp.kubeflow.org
Or 
deploy-gcp.kubeflow.dev

**Comment by ankushagarwal** [comment]
Isn't the click to deploy web app supposed to run locally to take advantage of local credentials for creating GCP resource?

**Comment by jlewi** [comment]
Its a client side web app. Deploying it is just an easy way for users to get access to the web app.

**Comment by lluunn** [comment]
@ankushagarwal have you started on this? Or I can help

**Comment by ankushagarwal** [comment]
@lluunn : Not started this. Feel free to take this issue.
