### ISSUE TITLE
pytorch jupyter notebooks?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1057]
With the PyTorch operator coming should we add better support for PyTorch to our notebooks.

I can think of a couple options

1. Add PyTorch to our existing Jupyter notebooks
1. Create a new set of PyTorch Jupyter images
1. Use someone elses images
1. Use the Kaggle image (assuming it supports PyTorch) #258 

/cc @johnugeorge 
/cc @pdmack

**Comment by pdmack** [comment]
Users can do `conda install pytorch torchvision -c pytorch` themselves in the current NB, right?

**Comment by ankushagarwal** [comment]
> With the PyTorch operator coming should we add better support for PyTorch to our notebooks.

Supporting \<framework\>'s operator should be orthogonal to supporting \<framework\> in our jupyter notebook.

+1 for @pdmack suggestion. Generally speaking our story for supporting a pip / python package in jupyter notebook should be `pip install` or `conda install`

**Comment by johnugeorge** [comment]
I agree in general. However, I feel that it would be a better user
experience if pytorch package is supported out of the box.

**Comment by jlewi** [comment]
I think we should try to provide a wholistic experience for other frameworks just like we do for TF.

So now that we are adding PyTorch support we should think about supporting it across the stack e.g
  - Notebooks
  - Training
  - Serving
  - Monitoring

**Comment by pdmack** [comment]
Regarding option 1, the name of the notebooks advertise TF 1.x. I don't know if that would be an impedance to pytorch users where the installed version is more or less unknown from just browsing image names.

**Comment by jlewi** [comment]
@pdmack Agreed but we could always rename the images.

For me the question is what's the right balance between the overhead of maintaining a set of container images, providing a container that has what you need to do things out of the box, and keeping image size tolerable.

I like the idea of building an uber, kitchen sync container like Kaggle. Mostly as an experiment to see whether customers find that extreme solution valuable.

**Comment by jlewi** [comment]
Also I think it would be really valuable if users could run any Kaggle solution right out of the box.

**Comment by pdmack** [comment]
What about that? A big, honkin' Kaggle image that we de-couple from the release cadence. Latest of all the frameworks, lightly curated, and loosely maintained. At least to start. Keep it out of the spawner defaults but promote it through docs, website. Make it clear that it's a long pull, other caveats, etc.

**Comment by pdmack** [comment]
FYI, just tried to build the kaggle image but ran out of room in my base dm. But, it's at least 59 minutes in and approaching 12 Gb in size.

**Comment by pdmack** [comment]
I'm skeptical that a multi-stage build with the Kaggle image would work but I'll have a look. But we could consider deriving a Kaggle build from our TF 1.8 image and adding in the missing parts. I'm guessing there's a good amount of overlap.

**Comment by pdmack** [comment]
Oh my...
```
kaggle/python latest cdc6ffe1b12c 2 months ago 16.8GB
```

https://gist.github.com/pdmack/6bea356917d6edbad0eccf46a27970eb

**Comment by pdmack** [comment]
```
Successfully built 178635b0097c
Successfully tagged kaggle/python-build:latest
real	119m34.774s
```

"gulp"
This was on a somewhat older Xeon CPU but it's a 24-way and has 48 Gb RAM.
`Intel(R) Xeon(R) CPU X5670  @ 2.93GHz`

**Comment by jlewi** [comment]
@pdmack This is pretty cool. Were you able to start Jupyter in the Kaggle image?

**Comment by pdmack** [comment]
No, it doesn't have `start-singleuser.sh` in place. Note that this wasn't the proposed multi-stage build or anything like that, just the upstream Dockerfile build. I supposed I could still look at that with doing a COPY of our /usr/local/bin/ scripts. But 2 hours for an almost 20Gb image? Do we want to go there?

**Comment by pdmack** [comment]
This is as far as I got reusing the kaggle docker image and adding our special sauce:
```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
    from notebook.notebookapp import (
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 40, in <module>
    ioloop.install()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

https://github.com/pdmack/kubeflow/tree/kaggle-nb-image

**Comment by jzf2101** [comment]
2c from the binder ecosystem- I've seen people install PyTorch and torchvision on binder after creating a conda environment using @soumith 's conda channel 

See example:

https://github.com/jrzech/reproduce-chexnet/blob/master/postBuild

**Comment by jlewi** [comment]
@pdmack Point taken.

Perhaps we should create an examples container intended to be used for running the examples. By definition, the image will contain the union of dependencies needed to run the Kubeflow examples. So it will grow over time until i) it becomes too large or ii) version conflicts.

By that definition it would make sense to start building an image with PyTorch and TF.

For 0.3 I'd like to be able to

- Offer Users Click To Deploy Kubeflow
- Dump user into Jupyter
- User walks through one or more Kubeflow codelab in JupyterLab
  
I'd like users to be able to do everything from JupyterLab; i.e. JupyterLab provides a notebook editor, basic text editor, and terminal which is sufficient for running the codelabs.

**Comment by jlewi** [comment]
Looks like @pdmack published a version of the image in
gcr.io/kubeflow-dev/kubeflow-kaggle-notebook:latest

**Comment by jlewi** [comment]
I retagged into gcr.io/kubeflow-images-public/kaggle-notebook:v20180629

I retagged it using Google Container Builder; trying to use gcloud container add tag choked.
Here's the GCB config
https://github.com/jlewi/kubeflow-dev/tree/master/kaggle-image

**Comment by jlewi** [comment]
Lets add PyTorch to our codelab notebook image see #1157 and then close this out.

**Comment by jlewi** [comment]
Anyone working on this?
Should we punt this to 0.5?

**Comment by carmine** [comment]
Move to 0.5.0, same priority.

**Comment by jlewi** [comment]
Downgrading to P2 since we are focusing on xgboost and TF.

I think a good next step would be to try to use some stock Jupyter images for PyTorch with the new notebook CR.

Ideally, we'd like existing jupyter images to just work so that we don't need to build custom images; see #2208. This should be more doable now that we no longer use JupyterHub.

**Comment by siddsuresh97** [comment]
Hello,
I'm new to contributing to open source. I would like to work on this issue. Could you help me on getting started?

**Comment by jlewi** [comment]
@siddsuresh97 Docs for creating custom Jupyter images are here
https://www.kubeflow.org/docs/notebooks/custom-notebook/

So I think if you were interested you could start by building a jupyter image suitable for PyTorch and making it work with Kubeflow. You could then publish it on DockerHub and provide instructions here or in kubeflow/website on how people could use it for PyTorch.

**Comment by DavidSpek** [comment]
@jlewi I was going through the Notebook issues and found this one. I created a PyTorch image based on the `jupyter/scipy-notebook` that seems to work. It also contains TensorFlow, not sure if that is an unnecessary combination or not (I don't work with either), but it can be easily removed if necessary. Hopefully this helps, otherwise I can do more testing if you specify what would need to be done. Here is the dockerfile:

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'tensorflow==2.3.0' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER $NB_UID

RUN conda config --system --append channels pytorch

RUN conda install --quiet --yes -c pytorch \
    'pytorch' \
    'torchvision' \
    'cpuonly' \
    && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Configure container startup
EXPOSE 8888
USER jovyan
ENTRYPOINT ["tini", "--"]
CMD ["sh","-c", "jupyter lab --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```
