### ISSUE TITLE
Figure out ksonnet repo organization

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#106]
We need to figure out how we want to organize our ksonnet registry in terms of [packages and prototypes](https://ksonnet.io/docs/concepts).

I think we have at least two different types of entities

- Individual components (e.g. JupyterHub, Argo, TensorFlow CRD, TF Serving, etc...)
- Stacks - collections of components

I think we will have multiple stacks which provide different collections of components; for example I could imagine a "Hadoop + TensorFlow" stack aimed at combining spark and TensorFlow components.

So my initial thought is that we should have individual ksonnet packages for each component and each stack.

We currently have 3 packages:

- Core
- tf-job
- tf-serving

However, these packages don't map to the entities mentioned above. If we were to follow the proposed model I think we would need to make the following changes

- Move TfJob CRD out of core and into tf-job
- Create a Package for JupyterHub
- Turn "Core" into a suitable stack maybe "Tensorflow" that reuses other packages.

I think the main issue with packages is that I don't think ksonnet provides a way to declare package dependencies. So users would have to manually install each package and its dependencies. This is fine as long as we have a small number of dependencies. This seems like a fixable issue though.

/cc @bryanl

**Comment by ankushagarwal** [comment]
Closing this as duplicate of #376
