### ISSUE TITLE
Simplify Image Tag management for releases

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1060]
Right now we tag our docker images with v${DATE}-${SHA}. There are two problems with this approach

1. This format isn't very informative for users
1. It's really cumbersome to update images as part of an RC

    * We need to build the images
    * Then create a PR to update the images in the ksonnet configs.

I propose we tag images with v${RELEASE} e.g. v0.2.0 and v.0.2.1 and this work as follows

1. The tags v0.2.0 will be mutable until a release candidate is promoted to actual release
    * As we cut RC's the tag for the upcoming release will be updated to point at the most recent RC
    * Once an RC is promoted to the actual release the tag is no longer mutated

1. When we cut the release branch; we update all the images to use the tag of the next release e.g. 0.2.1
     * This means we don't have to update the configs each time we cut a new image; we can just move the release tag (v0.2.1) to the new image

1. To provide an audit trail we use a simple YAML that maps immutable sha based images to tags
    e.g.

```
images:
   - image: gcr.io/some-image/image:sha256@abcd...
        tags: 
            - gcr.io/some-image/image:v0.2.0
```

1. We can use scripts to apply the tags to a given image
1. To push a new image as part of an RC we just need to move the tags by
   i. updating the YAML file
  ii.  rerunning scripts to reapply the tags

/cc @pdmack @kunmingg

**Comment by pdmack** [comment]
This sounds awesome!

**Comment by jlewi** [comment]
#1061 is an initial stab.

I think what we'll need some scripts to manage that YAML file for example

- Get the shas for the most recent tensorflow notebook images
- Apply some release tag to them
- Remove some release tag from some set of images.

**Comment by jlewi** [comment]
Closing this issue since we've committed a bunch of scripts to make this easier and there is no immediate follow on work.
