### ISSUE TITLE
IOError when importing MNIST data in the jupyter-notebook

### ISSUE THREAD

**Issue by jimmy-huang** [kubeflow/kubeflow#1067]
I am trying to set up kubeflow on minikube single-node cluster using KVM following the README instructions and behind a corporate proxy.  I am running the jupyter-hub on port 8100 using

kubectl port-forward tf-hub-0 8100:8000 --namespace=${NAMESPACE}

I am getting the following error IOError when I am trying to run any notebooks that tries to import external data, for example:

```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=False)

```

Error

```
/home/jovyan/.conda/envs/py2/lib/python2.7/httplib.pyc in connect(self)
   1253             "Connect to a host on a given (SSL) port."
   1254 
-> 1255             HTTPConnection.connect(self)
   1256 
   1257             if self._tunnel_host:

/home/jovyan/.conda/envs/py2/lib/python2.7/httplib.pyc in connect(self)
    819         """Connect to the host and port specified in __init__."""
    820         self.sock = self._create_connection((self.host,self.port),
--> 821                                            self.timeout, self.source_address)
    822 
    823         if self._tunnel_host:

/home/jovyan/.conda/envs/py2/lib/python2.7/socket.pyc in create_connection(address, timeout, source_address)
    573 
    574     if err is not None:
--> 575         raise err
    576     else:
    577         raise error("getaddrinfo returns an empty list")

IOError: [Errno socket error] [Errno 99] Cannot assign requested address
```

Any idea how to get around this or if this is related to proxy the jupyter-hub?  The minikube cluster and docker has been set up to go through the proxy already, but I don't know if kubeflow/jupyter needs additional configuration to run behind a proxy.

Environment
Ubuntu 16.04
Kubeflow v0.1.3
tensorflow-1.6.0-notebook-cpu:v20180419-0ad94c4e

**Comment by pdmack** [comment]
Can you try again with tip of master? i.e.,
``` 
VERSION=master
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow
```

**Comment by jimmy-huang** [comment]
@pdmack I get a the following error:

`$ ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow`
`ERROR Registry with name already exists`

I don't see a registry delete command, how do I update the existing registry?

**Comment by jimmy-huang** [comment]
I deleted the app and started over again with ks init, but now when I try to spawn the notebook, I get this error in the browser:
`Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: jupyter-jimmy)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.`

**Comment by jimmy-huang** [comment]
@pdmack I was able to get it back to working state after rebooting and start every back from beginning and tried master, and I am still getting the same error with master:

`IOError: [Errno socket error] [Errno 99] Cannot assign requested address`

**Comment by jimmy-huang** [comment]
I tried it and it didn't work, if I do kubectl describe pod tf-hub-0, I see the following:
jimmy@jimmy-dev:~/projects/faas/my-kubeflow$ kubectl describe pod tf-hub-0:

    Ports:         8000/TCP, 8081/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      jupyterhub
      -f
      /etc/config/jupyterhub_config.py
    State:          Running
      Started:      Tue, 26 Jun 2018 09:48:36 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      NOTEBOOK_ARGS:       --ip=127.0.0.1
      NOTEBOOK_PVC_MOUNT:  null
      CLOUD_NAME:          null
      REGISTRY:            gcr.io
      REPO_NAME:           kubeflow-images-public

And kubectrl describe pod jupyter-jimmy, I see the following:

    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      start-singleuser.sh
      --ip="0.0.0.0"
      --port=8888
      --allow-root

@pdmack , am I supposed to pass 127.0.0.1 to the jupyter-jimmy pod where it shows --ip="0.0.0.0" instead of the hub?  But I am not sure how to do that or which configuration I should set.

**Comment by pdmack** [comment]
A new jupyter-jimmy pod should get the changed ip arg.

**Comment by jimmy-huang** [comment]
I killed the pod jupyter-jimmy and tf-hub-0 and let it re-create, and jupyter-jimmy still doesn't pick up the new ip, are there other ways to set the ip?

**Comment by pdmack** [comment]
Talk to me.
Please describe your environment as much as you can.

**Comment by jimmy-huang** [comment]
@pdmack I sent you my setup information in email, hopefully it helps, thanks.
