### ISSUE TITLE
[gcp] GKE setup; do as much as possible in deploy.sh

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1068]
Our getting started instructions: https://www.kubeflow.org/docs/started/getting-started-gke/

Depend on a deploy.sh script; but there are still other steps in the process that user has to do manually.
Since we already have deploy.sh; why not move more of the commands into that script and try to infer sensible defaults using gcloud.

Specifically

1. deploy.sh can download the DM configs

1. deploy.sh can modify the DM configs
    * Set project and endpoints name
    * Set zone
    * Set email using gcloud auth config list

1. Create K8s resources including the bootstrapper

    * I think we should stop creating K8s resources with DM
    * We already issue kubectl commands in deploy.sh we might as well move any other resources there
    * Creating K8s resources in DM is weird because you probably don't want to update/manage ks resources using DM

1. Download the ksonnet app from the bootstrapper

     ```
     kubectl cp kubeflow-admin/kubeflow-bootstrapper-0:/opt/bootstrap/default ~/kf-app
     ```

1. deploy.sh can create clusterrolebindings to give user necessary K8s permissions
1. deploy.sh should trigger the creation of KF K8s resource creation (rather than having bootstrapper do this automatically)

   * I think its helpful if a user can see all the steps in deploy.sh 
   * Deploy.sh can trigger ks apply doing

   ```
   kubectl exec kubeflow-admin kubeflow-bootstrapper-0 cd /opt/bootstrapper/default && ks apply ...
   ```
   * We can have deploy.sh pass a bearer token to the bootstrapper so bootstrapper doesn't need elevated permissions

/cc @kunmingg @aronchick @ankushagarwal

**Comment by kunmingg** [comment]
Dependency: https://github.com/kubeflow/kubeflow/pull/1044?
