### ISSUE TITLE
Propose to re-include jupyter-tensorboard in notebook image

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1071]
The [jupyter-tensorboard extension](https://github.com/lspvic/jupyter_tensorboard) for Jupyter adds convenience in viewing training logs. Perhaps it should be re-included.

This requires logs written by training workers to be available via a filesystem path in the user's notebook pod, whether that work via NFS + PV or another approach.

One counter argument I can think of is that perhaps another pattern of logging is more standard, convenient, or a better practice.

/cc @pdmack @jlewi

**Comment by jlewi** [comment]
I think I would prefer a more complete/flexible solution for managing TensorBoard (kubeflow/tf-operator#447). I think the Jupyter tensorboard plugin is rather lmited.

- Why do users need to launch Jupyter just to launch tensorboard? 
- Running in the Jupyter pod limits you w.r.t to storage options and resources

Its possible the extension is useful in certain cases like when you are training in Jupyter and want to easily launch tensorboard in the same pod for the model you are training.
