### ISSUE TITLE
[gcp click-to-deploy] Click to deploy web app crashes

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#1072]
Repro instructions
```
cd components/gcp-click-to-deploy
npm install
npm start

# Open web ui
```

1.`hostname:` field is not editable
2. Clicking on `Create Deployment` crashes the web app

![image](https://user-images.githubusercontent.com/796949/41803514-81c5b71c-763e-11e8-9171-6aa2b6fe635e.png)

**Comment by yebrahim** [comment]
The outstanding PR https://github.com/kubeflow/kubeflow/pull/1054 already fixes this, but it was stuck on failing tests. I'm rerunning them now, will merge if they pass.

**Comment by yebrahim** [comment]
This shouldn't happen anymore now that the PR is merged, can you confirm and close the issue?
