### ISSUE TITLE
user_guide link is dead

### ISSUE THREAD

**Issue by lovejoy** [kubeflow/kubeflow#1075]
the link https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#troubleshooting in https://github.com/kubeflow/kubeflow/blob/master/README.md is dead now

**Comment by amsaha** [comment]
Actually, the user_guide.md link, https://github.com/kubeflow/kubeflow/blob/master/user_guide.md, is giving a 404 error.

**Comment by johnugeorge** [comment]
User guide is moved to website  https://www.kubeflow.org/docs/user_guide/
