### ISSUE TITLE
[Discussion] TF serving image: should we just keep Dockerfile for the latest TF version?

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1089]
We will still build, push, and test the images when a new TF version is released.
But what's the value of keeping Dockerfile parameterized to be able to build all the previous versions?

And we don't need to do image release when we release kubeflow, or nightly.

Also, TF Serving is actively updating Dockerfile recently: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

cc @jlewi @ankushagarwal @pdmack

**Comment by ankushagarwal** [comment]
> But what's the value of keeping Dockerfile parameterized to be able to build all the previous versions?

Don't see much value. 

> And we don't need to do image release when we release kubeflow, or nightly.

Yup. We should only build and push an image every time a tensorflow serving version is released. We should be doing it manually

Does tfserving build and push images to gcr or dockerhub? We can use their images directly if they do so.

**Comment by jlewi** [comment]
Do we have any logic/dependencies in the Dockerfiles that we might want to update independent of a TF version?

**Comment by lluunn** [comment]
https://hub.docker.com/r/tensorflow/serving/tags/

TF serving now maintains images

**Comment by lluunn** [comment]
I think we should
- cleanup infra for building and pushing images, e.g. images/releaser.
- make gcr.io/kubeflow-image-public mirror the tf serving docker hub 
- default using the latest version; e2e test using the latest version

**Comment by jlewi** [comment]
@lluunn Is TF serving publishing Docker images now? Can we get out of the business of publishing TF Serving docker images?

**Comment by lluunn** [comment]
Yes, yes.
We will change the default image to TF serving's, and cleanup the build/release infra.

**Comment by Ankk98** [comment]
I too think it is better to use TF serving's image as the default image.

**Comment by jlewi** [comment]
@lluunn Are we having problems with the TFServing images? #1321?

**Comment by lluunn** [comment]
using 1.8 cpu and 1.10 gpu #1370

**Comment by pdmack** [comment]
All sounds reasonable. I don't see anything in the Dockerfile that is specific to KF. #1321 not withstanding.

**Comment by lluunn** [comment]
We are using TF Serving's image now
