### ISSUE TITLE
Application Custom Resource for Kubeflow Deployments

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1106]
We should consider creating an [Application Resource](https://github.com/kubernetes-sigs/application) to describe a Kubeflow deployment.

At this point the Application Resource mostly provides meta information.

I think the immediate use cases for it would be

1. Use spec.assemblyPhase to report phase of the Kubeflow deployment
1. We could use the Application as the resource to associate with Kubernetes events related to the Kubeflow deployment.

Related issue #955

**Comment by jlewi** [comment]
A natural place for the relevant code would be in the bootstrapper
https://github.com/kubeflow/kubeflow/tree/master/bootstrap

There is an open PR to turn it into a server for managing ksonnet applications.
#1151 

We probably want to rename it to something like 

* manager
* appmanager
* appserver
* kfmanager

**Comment by lluunn** [comment]
cc @lluunn

**Comment by jlewi** [comment]
Punting this to 0.4.0 because we already have too many remaining issues in 0.3.0 and we want to be code complete in the next two weeks.

**Comment by jlewi** [comment]
@kkasravi is working on this; see #1633
