### ISSUE TITLE
Serving, Seldon, ServerLess and OpenFaas

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1116]
Opening this issue to cross reference issues in Seldon that are of interest to Kubeflow.
The corresponding Seldon issue is
SeldonIO/seldon-core#151

The idea of using a serverless framework like openfaas to make deploying models/ML infrastructure seems promising but I don't have much to add beyond that. 

Is there a core CUJ/experience we want to enable?

**Comment by bhack** [comment]
I like this idea.. Some of FAAS implementayion are also reasoning or offering workflows. Are we interested I.e. on workflow for preprocessing or other stages. 

I think that kubeless is the most k8s native approach but probably not the most popular. See also:

https://github.com/kubeless/kubeless/issues/342

**Comment by bhack** [comment]
A nice e2e tutorial https://github.com/dkozlov/openfaas-tensorflow-gpu

**Comment by bhack** [comment]
@jlewi Any internal contact with knative google team?

**Comment by jlewi** [comment]
Yes I've talked to them about their plans and the build CRD in particular.

is there something in particular you want to discuss?

**Comment by bhack** [comment]
I am just thinking about how this will fit also with preprocessing https://github.com/tensorflow/transform

**Comment by madfrog** [comment]
Code start may be a problem, not like just a piece of code, loading model, especially those big ones, will cost much time.

**Comment by alexellis** [comment]
Not sure if anyone will land here again, I guess OpenFaaS is the "most" "native" approach to answer the comment above, you can build and deploy Docker images without additional layers / runtimes.

Feel free to give it a try some time - https://github.com/alexellis/tensorflow-serving-openfaas
