### ISSUE TITLE
Make it easy to customizes PVs attached to Jupyter pods

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1125]
A common use case is users will want to attach a PV pointing at a shared filesystem to their Jupyter pods.

We should make it easy to customize Jupyter so that users can specify PVs that should be attached to all pods.

#56 is a general issue to make Jupyter pods more customizable.

**Comment by pdmack** [comment]
kubeflow#34

**Comment by jlewi** [comment]
#34 Is about adding a UI element that makes it possible to add specific PVs to a specific Jupyter pod.

This issue was about making it easy to configure Jupyter to attach a given set of PVs to all jupyter pods.
This is possible via the environment variable
KF_PVC_LIST
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/kubeform_spawner.py#L241

This is mapped to the disks prototype parameter
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub.libsonnet#L153

So this is fixed.
