### ISSUE TITLE
Problems upgrading services of type NodePort; spec.clusterIP: Invalid value: "": 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1145]
I notice that if I run ks apply on an existing component that has services I get errors like the following

```
ks apply default -c iap-ingress
ERROR handle object: merging object with existing state: Service "envoy" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable] 
```
I get the same error if I do ks show followed by kubectl apply

```
ks show default -c iap-ingress | kubectl apply -f -
ingress.extensions "envoy-ingress" unchanged
certificate.certmanager.k8s.io "envoy-ingress-tls" configured
serviceaccount "envoy" unchanged
clusterrolebinding.rbac.authorization.k8s.io "envoy" configured
clusterrole.rbac.authorization.k8s.io "envoy" configured
deployment.extensions "envoy" configured
deployment.extensions "iap-enabler" unchanged
configmap "envoy-config" created
service "whoami-app" unchanged
deployment.extensions "whoami-app" unchanged
The Service "envoy" is invalid: 
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```

Here is the output of ks show

```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: envoy
  name: envoy
  namespace: kubeflow
spec:
  ports:
  - name: envoy
    port: 8080
    targetPort: 8080
  selector:
    service: envoy
  type: NodePort
```

My conjecture is that this issue is specific to services with NodePort and is the result of 0.11 switching to using merge patching to try to preserve node ports:
https://github.com/ksonnet/ksonnet/releases

I suspect this is not a ksonnet issue.

Related issues:
   #980 - ks apply complains about optimistic locking

**Comment by jlewi** [comment]
I think this is coming from here
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/configure_envoy_for_iap.sh

**Comment by jlewi** [comment]
Actually that script doesn't seem to modify anything
Maybe its this one
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/setup_backend.sh

**Comment by jlewi** [comment]
Here's a related issue to fix this #942

setup_backend.sh is doing two things

1. Updating the backend service
1. Updating the Envoy config in each instance with the info needed for JWT validation

We should be able to move the update of the backend service into its own statefulset and have a single instance so we don't need the lock.

When it comes to updating the envoy config we can continue to run this in a side car (until #942 is fixed).

**Comment by jlewi** [comment]
Looks like BackendConfig doesn't support timeout yet
https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

**Comment by jlewi** [comment]
/priority p1
This is a pain point for users as it interferes with updates and things Argo CD.

**Comment by carmine** [comment]
/priority p2

Fix or "known issue" in release notes

**Comment by chrisheecho** [comment]
/remove-priority p2

Stablization item
