### ISSUE TITLE
Bare metal

### ISSUE THREAD

**Issue by bhack** [kubeflow/kubeflow#1148]
As a follow-up of https://github.com/kubeflow/kubeflow/issues/288#issuecomment-403248117 what we want to suggest for a kubeflow bare metal setup.

@paulbaumgart  https://github.com/kubernetes-incubator/kubespray/issues/2079 proposed 

This is the "official" kubernetes list of solutions https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by whillas** [comment]
Yeah, I'm trying it right now. Setup seems easy but getting access to the web UI is hard...?
