### ISSUE TITLE
Create Prometheus Component in Kubeflow Core.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1160]
Will integrate with stackdriver.
Support usage cases:

1. Fetch metrics from TF Serving. (https://github.com/kubeflow/kubeflow/issues/1036)
1. Fetch metrics from kf healthiness metrics_collector. (https://github.com/kubeflow/kubeflow/issues/1142)
1. Fetch metrics from Envoy to get network traffic metrics.

**Comment by kunmingg** [comment]
@lluunn 
@jlewi

**Comment by lluunn** [comment]
cc @ynqa

**Comment by lluunn** [comment]
https://cloud.google.com/monitoring/kubernetes-engine/prometheus

**Comment by jlewi** [comment]
#1204 was checked in. What is the remaining work?

Do we just need to document it?

**Comment by kunmingg** [comment]
Only docs needed, this one we can close.
