### ISSUE TITLE
tensorflow-serving-api does not support Python3

### ISSUE THREAD

**Issue by nkashy1** [kubeflow/kubeflow#117]
This affects kubeflow in the following ways:

1. This issue affects the kubeflow JupyterHub environment, as it currently only offers a Python3 kernel.

2. Our guide to calling models only works in Python2 environments.

Some possible solutions:

1. Publish Python3-capable `tensorflow-serving-api` to PyPI

2. Show how to directly use the [TensorFlow Serving protos](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/apis)

3. Write a RESTful wrapper around TensorFlow Serving [a la Cloud ML Engine](https://cloud.google.com/ml-engine/docs/online-predict) and expose this as a separate service on the kubernetes cluster

**Comment by nkashy1** [comment]
@elmiko : Since the `tensorflow-serving-api` classes are generated from `.proto` files, there shouldn't be any serious blockers. It seems to simply be a matter of changing how it's tagged on PyPI (based on the comment by @illagrenan on [here](https://github.com/tensorflow/serving/issues/700)).

On the plus side, it does seem as if there is some movement on that issue. :)

**Comment by ShahNewazKhan** [comment]
Checking for updates on this issue.
