### ISSUE TITLE
Extra packages in jupyterhub-image

### ISSUE THREAD

**Issue by wmuizelaar** [kubeflow/kubeflow#1175]
Hi,

Would it be possible to add the following python-packages to the hub-images as well?

- google-cloud (currently only google-cloud-storage available) (https://googlecloudplatform.github.io/google-cloud-python/)
- pandas-gbq (https://pandas-gbq.readthedocs.io/en/latest/)

Thanks,

Wietse

**Comment by jlewi** [comment]
Seems reasonable.

A PR would be very welcome.

If your blocked you could always create your own docker image derived from ours and then use that with JupyterHub.

/cc @wmuizelaar

**Comment by jlewi** [comment]
Yes.

But it should be in our nightly image builds
e.g. gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-cpu:v20180718-f5801b13

So it should be available to use and try out.
