### ISSUE TITLE
unable to spawn jupyter notebook - volume name is too long

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1177]
using IAP and a G suite account kam.d.kasravi@intel.com I get the following error when attempting to create the POD

Error: (422) Reason: error HTTP response headers: HTTPHeaderDict({'Audit-Id': '18fc2109-861e-4c94-943e-1946b9dbc2e5', 'Content-Type': 'application/json', 'Date': 'Wed, 11 Jul 2018 14:53:33 GMT', 'Content-Length': '942'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom\" is invalid: [spec.volumes[0].name: Invalid value: \"volume-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom\": must be no more than 63 characters, spec.containers[0].volumeMounts[0].name: Not found: \"volume-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom\"]","reason":"Invalid","details":{"name":"jupyter-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"volume-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom\": must be no more than 63 characters","field":"spec.volumes[0].name"},{"reason":"FieldValueNotFound","message":"Not found: \"volume-accounts-2egoogle-2ecom-3akam-2ed-2ekasravi-40intel-2ecom\"","field":"spec.containers[0].volumeMounts[0].name"}]},"code":422}

**Comment by jlewi** [comment]
It doesn't look like our existing spawner specifies a pattern for the pod name
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/kubeform_spawner.py

**Comment by jlewi** [comment]
It looks like kube spawner has an option
pod_name_template
http://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#module-kubespawner.spawner

**Comment by jlewi** [comment]
Need to wait for 0.2.2 I don't want to keep blocking 0.2.1

**Comment by jlewi** [comment]
Some suggestions

* Truncate pod name 
   * Ideally we'd use a deterministic hash of the full name to avoid conflicts but not sure if kube spawner
     makes that doable.

* Can we add a label for the username? Also truncated

**Comment by kkasravi** [comment]
I'll submit a PR with a config pod_name_template and pvc_name_template

Code to create the names is [here](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L215)
