### ISSUE TITLE
Public Docker image with TensorFlow Serving client

### ISSUE THREAD

**Issue by nkashy1** [kubeflow/kubeflow#118]
At least on gcr.io/kubeflow, but also having one on DockerHub would be valuable.

**Comment by carmark** [comment]
I own the `kubeflow` org on docker hub, and can contribute it if you need.

**Comment by aronchick** [comment]
That would be wonderful, thank you!

**Comment by aronchick** [comment]
Is there something that GCR isn't doing? It's just much easier, faster and
more feature rich for us.

**Comment by carmark** [comment]
;-(, GCR is blocked in China....

**Comment by nkashy1** [comment]
@carmark : That would be wonderful - I have a Dockerfile here as a start: https://github.com/nkashy1/kubeflow/blob/2feb62fea15d0a76b9235a71eabdee3df90697a6/components/k8s-model-server/inception-client/Dockerfile

It's part of this PR : https://github.com/google/kubeflow/pull/92


@carmark , @aronchick : Publishing on Docker Hub would make the image much more discoverable through tools like Kitematic (which a lot of people do use) anyway. In general I think it should be our policy to publish on both Docker Hub and GCR, no?
