### ISSUE TITLE
TFMA plots don't render in JupyterLab but they work with Jupyter

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1189]
See #1130 

We broke the javascript widgets when we moved to mounting PVs under /home/jovyan

We fixed this in #1130 for Jupyter but its still broken for JupyterLab.

There was a previous issue when we originally did this about problems with JupyterLab. 
We should dig up that issue to see if its relevant.

Notebook reports error

```
Error loading widget . could not find model
```

**Comment by jlewi** [comment]
Previous issue is #489 looks like it might be a different issue.

It looks like the fix for that issue #518 had a simple manual way of seeing if widgets were working

**Comment by jlewi** [comment]
@kkasravi said he was going to look into this and has some experience with TFMA.

**Comment by kkasravi** [comment]
Should have time tomorrow - will update

**Comment by kkasravi** [comment]
working on this now ...

**Comment by kkasravi** [comment]
I'm seeing `Error creating widget: could not find model` on the visuals, none render.

Steps to reproduce:
1. Bring up jupterhub, 
2. Run `kubectl port-forward tf-hub-0 8000`
3. open http://localhost:8000
4. open a terminal in jupyterlab

In the terminal in jupyterlab
$ source activate py2
$ jupyter nbextensions list
```
(py2) jovyan@jupyter-kam:~/work/model-analysis/examples/chicago_taxi$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/conda/envs/py2/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      tfma_widget_js/extension  enabled
      - Validating: OK
```
$ cd ~/work
$ git clone https://github.com/tensorflow/model-analysis
$ cd model-analysis
$ git fetch origin
$ git checkout tags/v0.9.0

Open `examples/chicago_taxi/chicago_taxi_tfma_local_playground.ipynb`
and run through the cells. 

Beginning on cell 14
```
# Show data sliced along feature column trip_start_hour.
tfma.view.render_slicing_metrics(
    tfma_result_1, slicing_column='trip_start_hour')
```
 I see
`Error creating widget: could not find model`

**Comment by jlewi** [comment]
Does model refer to something Jupyter related? Or does it refer to TF model?

**Comment by jlewi** [comment]
Looks like model refers to Jupyter e.g.

matplotlib/jupyter-matplotlib#38

**Comment by jlewi** [comment]
At the summit it was pointed out that extensions need to be written differently for jupyter and jupyterlab. But I'm not sure that's that's the same as a widget.

**Comment by kkasravi** [comment]
It may be related to this [issue](https://github.com/jupyter-widgets/ipywidgets/issues/2125#issuecomment-403231449) I'll get more info about the lab-manager

**Comment by jlewi** [comment]
Thanks @kkasravi 

I'm going to move this to 0.4. since we are finalizing 0.3.

**Comment by jasongrout** [comment]
Is this the codebase? https://github.com/tensorflow/model-analysis/tree/master/tensorflow_model_analysis/notebook/jupyter/js

If that is the code we are talking about, it may be pretty straightforward to look at an example widget generated by the widget cookiecutter and modify the above js code appropriately.

**Comment by jlewi** [comment]
Thanks @jasongrout

**Comment by mFat7y** [comment]
Hello,
Any updates on this issue? I'm facing a similar problem but with `sparkmagic` tool with JupyterLab. I use `manage_spark` magic to control the sessions using small UI widget. but when I reload notebook the page I get the same error (Error creating widget: could not find model) and I have to force reload the `sparkmagics` again to get it working.
