### ISSUE TITLE
Include eclipse-che in the Kubeflow stack

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#12]
I think we should investigate including eclipse-che in the Kubeflow stack.

Motivation:

I think ML requires an IDE/editor. For example, a lot of [TensorFlow models](https://github.com/tensorflow/models) are multi-file packages. So a notebook environment may not be sufficient if you want to work with these packages.

In addition, if your developing and building containers locally and pushing containers to the Cloud, pushing containers from your local machine to the Cloud can be a big bottleneck in the dev-test cycle. So if we can move development and container building into the cluster that can eliminate that bottleneck.

There's a couple reasons why I think eclipse-che is a great choice

- The UI is a web-app; so it should be performant when running on a remote cluster.
- Eclipse-che runs on [openshift](https://www.eclipse.org/che/docs/setup/openshift/index.html) so hopefully it can be ported to K8s without much difficulty
- Custom runtimes are a really nice feature for allowing users to run their code in customized Docker images that contain all the libraries they need.

**Comment by jlewi** [comment]
eclipse/che#7589 is tracking adding K8s support to

**Comment by yuvipanda** [comment]
I also am a fan of Eclipse Che, but note that these images also ship with https://github.com/jupyterlab/jupyterlab by default (I think), so that also works. You can check it out by replacing '/tree' with '/lab'. It's not production yet, ofc!

**Comment by jlewi** [comment]
Jupterlab is pretty cool. 

@foxish Does the existing effort to run Jupterhub on K8s include jupterlab?

**Comment by jlewi** [comment]
@yuvipanda Thanks for the pointer; juptyerlab worked just like you said it would; all I had to do was change the url to  http://localhost:8100/user/$USER/lab. This is really awesome.
