### ISSUE TITLE
"getting-started-gke" installer fails

### ISSUE THREAD

**Issue by mmatiaschek** [kubeflow/kubeflow#1201]
I had these issues on google cloud shell so i tried with a fresh install on Bash on Ubuntu on Windows, Ubuntu 16.04, and got the same problems.

1. [install and initialize gcloud](https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu)
2. install ksonnet v0.11.0 from github
3. [install kubeflow](https://www.kubeflow.org/docs/started/getting-started-gke/)

First issue with the kubeflow documentation/installer was that the tmp folder was not found, my workaround was to `mv /tmp/kubeflow-0.2.1/ /tmp/kubeflow-v0.2.1` and start again.
```
+ mv /tmp/kubeflow-v0.2.1 /mnt/c/Users/mmatiaschek/cmder/kubeflow_repo
mv: Aufruf von stat für '/tmp/kubeflow-v0.2.1' nicht möglich: Datei oder Verzeichnis nicht gefunden
$ mv /tmp/kubeflow-0.2.1/ /tmp/kubeflow-v0.2.1
$ curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/gke/deploy.sh | bash
```

**The next error was not recoverable for me, any help would be greatly appreciated!!**

```log
kubeflow exists
+ gcloud deployment-manager --project=*********** deployments update kubeflow --config=cluster-kubeflow.yaml
The fingerprint of the deployment is ***************==
Waiting for update [operation-1531486959504-570e118330a81-c859d6b5-78eef300]...
....failed.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1531486959504-570e118330a81-c859d6b5-78eef300]: errors:
- code: CONDITION_NOT_MET
  location: /deployments/kubeflow/resources/kubeflow-gpu-pool-v1->$.properties
  message: '"": domain: validation; keyword: properties; message: required property(ies)
    not found; missing: ["nodePoolId"]; required: ["clusterId","nodePoolId","zone"]'
```

**Comment by mmatiaschek** [comment]
it seem like kubectl 1.11.0 is buggy and responsible for the failed deployment.
1.10.5 seems to work.
A fix for the tmp issue would be nice.

**Comment by ankushagarwal** [comment]
@mmatiaschek : Do you know what the problem with ksonnet was? I've not had issues with 1.11.0

Regarding the `gcloud deployment-manager` error. Can you first delete the deployment and it's config directory and try again?

```
DEPLOYMENT_NAME=kubeflow
gcloud deployment-manager deployments delete --quiet \
 ${DEPLOYMENT_NAME} --project=${PROJECT}

KUBEFLOW_DM_DIR="${DEPLOYMENT_NAME}_deployment_manager_configs"
rm -rf ${KUBEFLOW_DM_DIR}
```

**Comment by jlewi** [comment]
0.2.2-rc.0 has been promoted to 0.2.2.

**Comment by mmatiaschek** [comment]
Thank you, it works... i still have some problems though, i will open another issue
