### ISSUE TITLE
Default service type for ModelServer should not be loadbalancer

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#121]
Currently the the default service type for ModelServer is set to LoadBalancer
https://github.com/google/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet#L43

In Cloud this can mean exposing the service publicly. I don't think this should be the default option. I think the default should be ClusterIP and we can expose a parameter to set it.

**Comment by nkashy1** [comment]
@jlewi : as per discussion on https://github.com/google/kubeflow/pull/92 , feel free to assign this to me. I will make the following changes:

1. Parametrize `modelService.spec.type` with default as `ClusterIP`.

2. Add instructions to `components/k8s-model-server/README.md` reflecting this. Add links to kubernetes service documentation describing various types: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types

3. Modify inception client container in https://github.com/google/kubeflow/pull/92 to run from kubernetes cluster (can be done by setting SERVICE_IP and CLUSTER_PORT to pod environment variables?)

4. Update exposition on https://github.com/google/kubeflow/pull/92

**Comment by nkashy1** [comment]
Roughshod solution here: https://github.com/google/kubeflow/pull/92

Will improve as I learn more about `ksonnet`.

**Comment by nkashy1** [comment]
Is there a simple way to run tests which verify that the deployment is not failing? Looked in [here](https://github.com/google/kubeflow/tree/master/testing) but nothing stood out to me.

**Comment by nkashy1** [comment]
Tested manually and no dice - even though I specified `service.type` as `ClusterIP` in `kubeflow/tf-serving/tf-serving.libsonnet`, GKE is still providing me with an external IP:

```
$ ks show default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: inception
  name: inception
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: inception
    spec:
      containers:
      - args:
        - /usr/bin/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=gs://inception-kf
        command:
        - /bin/sh
        - -c
        image: gcr.io/kubeflow/model-server:1.0
        imagePullPolicy: IfNotPresent
        name: inception
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inception
  name: inception
  namespace: default
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: inception
  type: LoadBalancer
```

I am using my own branch for the registry:
```
$ ks registry list
NAME      PROTOCOL URI
====      ======== ===
incubator github   github.com/ksonnet/parts/tree/master/incubator
kubeflow  github   github.com/nkashy1/kubeflow/tree/inception-client/kubeflow
```

Will dig into this more next week. I suspect my lack of understanding of ksonnet is the issue here.

**Comment by jlewi** [comment]
Make sure the files in vendor/kubeflow/... actually reflect your changes.
The easiest thing to do is to set up an app for testing like you would normally (i.e. install the packages) and create the components.

Then replace vendor/kubeflow with a symbolic link to the kubeflow directory in your Git repo. This way any changes will be automatically reflected.

**Comment by jlewi** [comment]
@nkashy1 What is the status of this?

**Comment by jlewi** [comment]
It looks like it is now using ClusterIP
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet
