### ISSUE TITLE
Error from server (NotFound): tfjobs.kubeflow.org "mycnnjob" not found

### ISSUE THREAD

**Issue by xqqcoder** [kubeflow/kubeflow#1217]
when I follow the user guide ,do the order "kubectl get -o yaml tfjobs ${CNN_JOB_NAME}", it happened

**Comment by jlewi** [comment]
Did you create the job named ${CNN_JOB_NAME}? Check that you are looking in the right namespace.

You can run the following command to get jobs in all namespaces.

```
kubectl get --all-namespaces=true tfjobs
```

**Comment by xqqcoder** [comment]
thank you, I add --namespace it works
