### ISSUE TITLE
[Test Failure] TFJob test failure; no module named py

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1218]
TFJob test is failing with

```
/usr/bin/python: No module named py
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1200/kubeflow-presubmit/2586/

Seems completely unrelated to that PR. 

Need to check whether its also failing @ HEAD.

**Comment by lluunn** [comment]
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kubeflow-e2e-gke-1165-660432b-2592-4d60?tab=workflow&nodeId=kubeflow-presubmit-kubeflow-e2e-gke-1165-660432b-2592-4d60-2156856773
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1165/kubeflow-presubmit/2592/

**Comment by jlewi** [comment]
For #1200 it looks like the test passed on retry which is very weird.

**Comment by lluunn** [comment]
Looking into this.

**Comment by lluunn** [comment]
Found pod: kubeflow-test-infra kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af-237888385

Logs:
/usr/bin/python: No module named py

describe pod

Environment:
```
Command:
      python
      -m
      py.test_runner
      test
      --cluster=e2e-21af

 PYTHONPATH:                      /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/kubeflow:/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/testing/py:/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/tf-operator
```

cannot exec into it: error: cannot exec into a container in a completed pod; current phase is Failed

**Comment by lluunn** [comment]
```
root@debug-worker-0:/# ls /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/tf-operator
Gopkg.lock  OWNERS     cmd                 docs      linter_config.json  py                     test
Gopkg.toml  README.md  dashboard           examples  pkg                 releasing.md           tf_job_design_doc.md
LICENSE     build      developer_guide.md  hack      prow_config.yaml    submit_release_job.sh  vendor
```
However, no `__init__.py`
```
root@debug-worker-0:/# ls /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/tf-operator/py -a
.        Pipfile.lock             deploy.py     py_checks.py     test_runner.py     tf_job_client.py
..       README.md                prow.py       release.py       test_util.py       util.py
Pipfile  build_and_push_image.py  prow_test.py  release_test.py  test_util_test.py  util_test.py
```

**Comment by lluunn** [comment]
https://github.com/kubeflow/tf-operator/blob/master/py/__init__.py

It's not deleted

**Comment by lluunn** [comment]
It's weird:
```
root@debug-worker-0:/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-e8f6cef-2600-21af/src/kubeflow/tf-operator/py# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../examples/tf_sample/tf_sample/__init__.py
	deleted:    __init__.py
	deleted:    ../test/workflows/app.lock
	deleted:    ../vendor/github.com/modern-go/reflect2/reflect2_amd64.s
```

`__init__.py` is somehow deleted

**Comment by lluunn** [comment]
So `__init__.py` should be there right after step checkout, but gone at step tfjob-test.
I will do a binary search to find which step deleted it.

**Comment by lluunn** [comment]
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kubeflow-e2e-gke-1224-a45247a-2608-9146?tab=workflow

![screenshot from 2018-07-17 10-32-29](https://user-images.githubusercontent.com/32310205/42835002-dd157d42-89ac-11e8-9e45-70063fb912f2.png)


  `__init__.py` is gone
```
root@debug-worker-0:/# ls /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-a45247a-2608-9146/src/kubeflow/tf-operator/py -a
.        Pipfile.lock             deploy.py     py_checks.py     test_runner.py     tf_job_client.py
..       README.md                prow.py       release.py       test_util.py       util.py
Pipfile  build_and_push_image.py  prow_test.py  release_test.py  test_util_test.py  util_test.py
```

**Comment by lluunn** [comment]
```
root@debug-worker-0:/# ls /mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-1296b1b-2610-cc8a/src/kubeflow/tf-operator/py -a
.        Pipfile.lock  build_and_push_image.py  prow_test.py  release_test.py  test_util_test.py  util_test.py
..       README.md     deploy.py                py_checks.py  test_runner.py   tf_job_client.py
Pipfile  __init__.py   prow.py                  release.py    test_util.py     util.py
```

It's there for this one http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kubeflow-e2e-gke-1224-1296b1b-2610-cc8a?tab=workflow

![screenshot from 2018-07-17 10-45-34](https://user-images.githubusercontent.com/32310205/42835813-94f55a6c-89ae-11e8-8d09-0da31af13e5f.png)

So looks like bootstraper deleted it somehow..?

**Comment by lluunn** [comment]
![screenshot from 2018-07-17 11-22-26](https://user-images.githubusercontent.com/32310205/42837726-b4464f34-89b3-11e8-9fea-ac6bf4e0fe37.png)

`__init__.py` is still there at the end of bootstrapper step...

**Comment by lluunn** [comment]
```
root@debug-worker-0:/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1224-1296b1b-2610-cc8a/src/kubeflow/testing# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    py/kubeflow/__init__.py
	deleted:    py/kubeflow/testing/__init__.py
	deleted:    py/kubeflow/tests/__init__.py

```

testing repo also got deleted.

**Comment by jlewi** [comment]
@lluunn Nice work!

**Comment by jlewi** [comment]
@lluunn Should we revert #1228?

**Comment by lluunn** [comment]
That one is not merged, it's closed.
