### ISSUE TITLE
Autoscaling for TF Serving

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1219]
- How do we leverage K8s autoscaling?
- Can we autoscale with custom metrics?
- We should have benchmark, https://github.com/kubeflow/kubebench/issues/30.

**Comment by bhack** [comment]
Can we handle this with [Replicaset](https://medium.freecodecamp.org/machine-learning-as-a-service-with-tensorflow-9929e9ce3801) + horizontal autoscaler? 
The custom metrics thread is at https://github.com/kubeflow/kubeflow/issues/1036

**Comment by lluunn** [comment]
might be useful: https://github.com/knative/serving

**Comment by bhack** [comment]
Near that topic see https://github.com/kubeflow/kubeflow/issues/1116
