### ISSUE TITLE
[GCP] deploy.sh - don't show error if deployment doesn't exist

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1222]
deploy.sh checks if the existing deployment exists. This ends up outputting an error when creating a new deployment.

```
+ gcloud deployment-manager --project=cloud-ml-dev deployments describe jlewi-kf-v0-2-2-rc-0
ERROR: (gcloud.deployment-manager.deployments.describe) ResponseError: code=404, message=The object 'projects/cloud-ml-dev/global/deployments/jlewi-kf-v0-2-2-rc-0' is not found.
+ exists=1
+ set -e
```

This will undoubtedly confuse users who don't realize that the ERROR is expected in the case the deployment doesn't exist. We should modify the script so that we don't print out the ERROR.

**Comment by amsaha** [comment]
Wouldn't echoing 
```bash
    echo ${DEPLOYMENT_NAME} does not exist. Creating it...
```
in the following `else` block enough? Removing the error message is a bit risky and also needs some bash code jugglery to achieve. 

```bash
if ${KUBEFLOW_DEPLOY}; then
  # Check if it already exists
  set +e
  gcloud deployment-manager --project=${PROJECT} deployments describe ${DEPLOYMENT_NAME}
  exists=$?
  set -e

  if [ ${exists} -eq 0 ]; then
    echo ${DEPLOYMENT_NAME} exists
    gcloud deployment-manager --project=${PROJECT} deployments update ${DEPLOYMENT_NAME} --config=${CONFIG_FILE}
  else
    # Run Deployment Manager
    ###### SUGGESTED CHANGE BEGIN #########
    echo ${DEPLOYMENT_NAME} does not exist. Creating it... 
    ###### SUGGESTED CHANGE END #########
    gcloud deployment-manager --project=${PROJECT} deployments create ${DEPLOYMENT_NAME} --config=${CONFIG_FILE}
  fi    
```

**Comment by jlewi** [comment]
How does this fix the error?

The problem is that

```
 gcloud deployment-manager --project=${PROJECT} deployments describe ${DEPLOYMENT_NAME}
```

outputs an ERROR to stderr if the deployment doesn't exist. We don't want the user to see that error because it will likely confuse them.

So what we want to do is redirect stderr somewhere else.

For example

```
gcloud deployment-manager --project=${PROJECT} deployments describe ${DEPLOYMENT_NAME} > /dev/null
```

But swallowing the error entirely is a little dangerous; its possible a different error than "doesn't exist" occurs and assuming its a doesn't exist error could lead to confusion.

So I think what we should do is capture the stderr in a file or variable and then use a REGEX or similar comparison to see if the error indicates that the deployment doesn't exist. If it doesn't than we can just print out an info message and continue.

If its another, unexpected error than we should surface that and probably terminate.

**Comment by amsaha** [comment]
My contention is that the error message is harmless and since the script does not stop there and continues with the execution the user should be okay with it, especially if we print an extra message at the end. 

Redirecting to a file, parsing the error message, and finally masking a specific message seems too much code. Also, if the gcloud error message changes, we would be back to square one.

**Comment by jlewi** [comment]
#1308 should fix this. The error is harmless but it will be very confusing to users. Especially when things go wrong and Kubeflow is not deployed correctly. In this case they will look at the output which shows an Error  and think that is the problem.

**Comment by jlewi** [comment]
Fixed by kfctl.sh

**Comment by jlewi** [comment]
#1308 is kfctl.sh
