### ISSUE TITLE
Rename TF-Hub to JupyterHub

### ISSUE THREAD

**Issue by activatedgeek** [kubeflow/kubeflow#1223]
This pod's name was a misnomer and should be corrected to avoid confusion with a product by the same name.

**Comment by pvsousalima** [comment]
Would a pod renaming fix it?

**Comment by jlewi** [comment]
@pvsousalima Sorry for the slow reply.

I think what we'd like to do is rename the stateful set. 
Specifically in this file
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub.libsonnet#L19

Replace TFHub with JupyterHub

Are you still willing to pick this up?

/assign @pvsousalima

**Comment by pvsousalima** [comment]
Hey @jlewi no problem! Yes, I am!

**Comment by pvsousalima** [comment]
@jlewi I will open the PR before tomorrow night! I had a flu situation going on here... 👍

**Comment by jlewi** [comment]
Thanks. Hope your feeling better.

**Comment by jlewi** [comment]
@pvsousalima How's this coming? Do you think you will be able to make progress?

**Comment by pvsousalima** [comment]
hey @jlewi I am very sorry for such late response, again I got better only yesterday and back to my normal work activities. Yes I will be able to make progress in such. 👍 Will go for the PR today!

**Comment by pvsousalima** [comment]
@jlewi I have pushed a PR that needs review. I didn't touch the tf-hub-lb only the Statefulset and it's correlated services including headless.
