### ISSUE TITLE
Remove ksonnet parameter cloud

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1227]
We no longer use the cloud ksonnet parameter so we should just get rid of it.

**Comment by jlewi** [comment]
It looks like we use it in the following places

jupyterhub - cloud is used to set the images. alibaba uses its own registry instead of gcr
ambassador - cloud is used to determine the isDashboardTls parameter

We should probably replace the use of cloud with more direct parameters; e.g. registry in the case of JupyterHub and isDashboardTls for ambassador

**Comment by lluunn** [comment]
Also TF serving: 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet#L103

**Comment by ashahba** [comment]
I can work on this one if not assigned or resolved yet.

**Comment by jlewi** [comment]
That would be great.
