### ISSUE TITLE
JupyterHub should not open up external IP by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#123]
By default JupyterHub config will open up an external IP address. We should not do that by default since its unsafe.

**Comment by s1113950** [comment]
I was looking to fix this issue, but am not sure it still exists. I deployed a `tf-hub` pod via the user guide instructions recently and see this in my pod listing:

`tf-hub-0               ClusterIP   None            <none>        80/TCP     2d` which shows no external IP. Maybe I'm missing something?

**Comment by lluunn** [comment]
I think it's fixed by #139

**Comment by jlewi** [comment]
There's a bug #203 that should be fixed by #232.

**Comment by jlewi** [comment]
Default is set to ClusterIP here
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/prototypes/all.jsonnet#L12
