### ISSUE TITLE
[openmpi]- NodeSelector not working.

### ISSUE THREAD

**Issue by karthikvadla** [kubeflow/kubeflow#1230]
As mentioned [here](https://github.com/kubeflow/kubeflow/tree/master/kubeflow/openmpi) in `GPU Training` section trying to use `--nodeSelector` to specify pool of nodes to launch my workloads. 

But `--nodeSelector` is not working as expected. 

```--nodeSelector=<nodeSelector>             Comma-delimited list of "key=value" pairs to select the worker nodes. e.g. "cloud.google.com/gke-accelerator=nvidia-tesla-k80" [default: null, type: string]```

Above description is bit **confusing**, mentioned type as `string` but when explaining written as comma -delimited list (Typo need to be corrected)

Tried as below.

if type is `array`
NODE_SELECTOR=`'["kubernetes.io/hostname=gke-x1", "kubernetes.io/hostname=gke-x2"]'` - It didn't honor, randomly picked up some nodes.

or 
if type is `string`
NODE_SELECTOR=`"kubernetes.io/hostname=gke-x1, gke-x2"`. It gave me below error

> level=error msg="find objects: RUNTIME ERROR: Index 1 out of bounds, not within [0, 1)\n\t/Users/kvadla/git-repo/mlt/examples/horovod_unet/mlt_app/unet-horovod-2e6fbba6-7e39-41f9-98b5-1f3241001e33/vendor/kubeflow/openmpi/util.libsonnet:14:46-81\tobject <anonymous>\n\t<std>:1222:30-34\tthunk from <thunk from <function <anonymous>>>\n\t<std>:1216:24-25\tthunk from <thunk <t> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1217:8-9\tfunction <anonymous>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t...\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:35-56\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<builtin>\tbuiltin function <$objectFlatMerge>\n\t<extvar:__ksonnet/components>:7:3-58\tobject <anonymous>\n\tDuring manifestation\t\n"
> make: *** [deploy] Error 1

Found out during discussion https://github.com/kubeflow/kubeflow/issues/838 
@everpeace

**Comment by everpeace** [comment]
/cc @jiezhang 
Would you mind taking a look at this??

**Comment by jiezhang** [comment]
If you're using gcloud, you can specify node labels this way:

```
gcloud container node-pools create ... --node-labels=node-type=gke
```

**Comment by jiezhang** [comment]
Looks like [NodeSelector](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2503) does not support IN operator. We need to support [Affinity](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2536) if you want "hostname IN (gke-x1, gke-x2)".

I'm closing this for now. Please open a feature request if you need the feature.

/close
