### ISSUE TITLE
TF-job package missing

### ISSUE THREAD

**Issue by kbmanseau** [kubeflow/kubeflow#1245]
I have been following the following blog post: https://kubernetes.io/blog/2017/12/introducing-kubeflow-composable/.

In the first step where you have to install a few packages I am having trouble with the tf-job part.

I get the following error: 

ERROR resolve registry library: GET https://api.github.com/repositories/112647343/contents/kubeflow/tf-job?ref=18305be18541b6dcaed1098638e84d603a1b04eb: 404 Not Found []

The first two packages worked with no issue (core, tf-serving)

When browsing to the following link in a browser, core and tf-job can be seen but not tf-job.
https://api.github.com/repositories/112647343/contents/kubeflow

**Comment by jlewi** [comment]
Please follow the getting started guide here
https://www.kubeflow.org/docs/started/getting-started/

The blog post is outdated. The code has been refactored since then.

**Comment by kbmanseau** [comment]
Okay thank you
