### ISSUE TITLE
Create a batch predict example

### ISSUE THREAD

**Issue by yixinshi** [kubeflow/kubeflow#1250]

**Comment by yixinshi** [comment]
Still working on the example. It will be using a faster_rcnn_nas object detection model with 150 images as the input, running on GPUs (P100). It runs locally but not yet in K8s. Working on the YAML file to start the job. Expect to complete today or by Tues next week (7/24)

**Comment by jlewi** [comment]
See also kubeflow/batch-predict#5

**Comment by jlewi** [comment]
@yixinshi Is this done?

**Comment by yixinshi** [comment]
yes, it's done

**Comment by amsaha** [comment]
@yixinshi what is the PR related to this? 

was some documentation added at https://www.kubeflow.org/docs/about/kubeflow/? If yes, could you refer that link in this issue and if not could you please add or at least point us to some readme in the patch that you submitted?
