### ISSUE TITLE
[gcp-click-to-deploy] Build the web app for production in the Docker build

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/kubeflow#1251]
We should not be using the dev server to serve the webapp in the [Dockerfile](https://github.com/kubeflow/kubeflow/blob/471de67fc4596fb6727f72332ab555ae10e307eb/components/gcp-click-to-deploy/Dockerfile#L5).

**Comment by yebrahim** [comment]
The create react app tool doesn't include a prod server, only a dev server for previewing changes.
The Dockerfile should instead do `npm run build`, which generates a deploy-ready production version of the app (minified, bundled... etc all the goodies), then use any npm installable static file server to serve the built files:

```
npm run build
npm i -g serve    # installs "serve", a static file server
serve -s build    # runs "serve" with the generated build directory as a parameter
```

Note: I'm not sure how npm is set up in the Dockerfile, so if the global install (`npm i -g serve`) command causes permissions issues, you can always just install locally using `npm i serve`, then use the local path: `./node_modules/.bin/serve -s build`.

**Comment by yebrahim** [comment]
Oh and I believe you want to use the right port. Using `serve` it would be: `serve -s build -p 3000`.

**Comment by jlewi** [comment]
Thanks.

**Comment by jlewi** [comment]
Removing this from 0.3 because its not critical to the release.
