### ISSUE TITLE
Include H20.AI packages in Kubeflow repository and document it.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1254]
H20.AI created ksonnet packages for Kubeflow.

It would be great to add them to the Kubeflow repository to make them more discoverable
https://github.com/h2oai/h2o-kubeflow/tree/master/h2o-kubeflow

It would also be good to add a Guide on our documentation page about using H20.AI with Kubeflow.

**Comment by jlewi** [comment]
@nkpng2k thoughts?

**Comment by jlewi** [comment]
@nkpng2k I think we should have a single H20.AI package. You can have multiple prototypes within the package. So you could have separate prototypes for Driverless and h20-3

**Comment by nkpng2k** [comment]
@jlewi Great! I will fork and make a pr. Hopefully sometime this week. At Next, so screen time is limited

**Comment by jlewi** [comment]
@nkpng2k I'm at next as well; ping me on slack if you want to meetup.

**Comment by pdmack** [comment]
Is there still interest in rebasing this and adding it to Kubeflow?

**Comment by nkpng2k** [comment]
@pdmack Yes, but will need some additional fiddling now and retesting. Will be working on it this week.

**Comment by jlewi** [comment]
@nkpng2k any interest in continuing to push this forward?

One thing to be aware of is that since ksonnet is going away we would need to use an alternative like kustomize to deploy the packages.

**Comment by nkpng2k** [comment]
Hi @jlewi,

We are going to look into adjusting our deployment process to include kustomize ... possibly another package. Is `kustomize` the recommended?

As soon as I am able to update the deployment process, I will let you know.
Thanks,
Nicholas

**Comment by jlewi** [comment]
@nkpng2k Yes kustomize is what I would recommend. You could add your manifest here:
https://github.com/kubeflow/manifest.

p.s DriverLess AI is really cool (saw another demo at OReilly AI). Any thoughts about how Kubeflow and Driverless AI might play together? Would you want to train on DriverLess and then deploy on Kubeflow?

**Comment by nkpng2k** [comment]
@jlewi thanks for the response, will be working on this, this week. As for how Driverless and Kubeflow might play together, I think deployment would be the lowest hanging fruit. I've got some other thoughts in mind, but early development, can't be placed in an open thread =)

Is the Kubeflow slack channel still a thing? Would be happy to pick your thoughts online. 

btw: https://github.com/kubeflow/manifest is going to 404 error
