### ISSUE TITLE
Make TF serving component more readable and extendable

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1264]
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet
It's currently not very readable, and adding other features will make it worse (e.g. request logging).

Some previous discussion in #376 .

Here are some example packages: https://github.com/ksonnet/parts/tree/master/incubator
From this I think the general pattern is for each component, define 
1. default [param](https://github.com/ksonnet/parts/blob/master/incubator/nginx/nginx.libsonnet#L8)
1. [base](https://github.com/ksonnet/parts/blob/master/incubator/nginx/nginx.libsonnet#L32)
1. different [extensions](https://github.com/ksonnet/parts/blob/master/incubator/nginx/nginx.libsonnet#L16)

We can utilize ksonnet [mixins](https://github.com/ksonnet/parts/blob/master/incubator/redis/redis.libsonnet#L3).

**Comment by jlewi** [comment]
Given #1229 I think the use case is to support things like injecting a config map and sidecar for request logging.

I think there are two patterns we should explore

1. Using custom admission controllers
1. Using overlays 
   * I think this was introduced by [kustomize](https://github.com/kubernetes-sigs/kustomize)
   * But I believe its supported in ksonnet with the "+" operator

**Comment by lluunn** [comment]
#1589 is the new pattern. We can improve on that
