### ISSUE TITLE
Deploy argo by default; add it to deploy.sh scripts

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1268]
to support pipelines

**Comment by jlewi** [comment]
@lluunn looks like you forgot to apply argo in non GKE case.

**Comment by lluunn** [comment]
Isn't this one: https://github.com/kubeflow/kubeflow/blob/master/scripts/deploy.sh#L72?

**Comment by jlewi** [comment]
You're correct; it applies all components.
