### ISSUE TITLE
JupyterHub users can't create pods on GKE

### ISSUE THREAD

**Issue by mmatiaschek** [kubeflow/kubeflow#1281]
My users get this error when trying to start a docker image via JupyterHub.
`Error: (422) Reason: error HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b79ba010-af2f-49a6-a606-eda454bb40a5', 'Content-Type': 'application/json', 'Date': 'Fri, 27 Jul 2018 13:45:12 GMT', 'Content-Length': '972'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod "jupyter-accounts-2egoogle-2ecom-3auser12-2ename123-40googlemail-2ecom" is invalid: [spec.volumes[0].name: Invalid value: "volume-accounts-2egoogle-2ecom-3auser12-2ename1234-40googlemail-2ecom": must be no more than 63 characters, spec.containers[0].volumeMounts[0].name: Not found: "volume-accounts-2egoogle-2ecom-3auser12-2ename1234-40googlemail-2ecom"]","reason":"Invalid","details":{"name":"jupyter-accounts-2egoogle-2ecom-3auser12-2ename1234-40googlemail-2ecom","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: "volume-accounts-2egoogle-2ecom-3auser12-2ename1234-40googlemail-2ecom": must be no more than 63 characters","field":"spec.volumes[0].name"},{"reason":"FieldValueNotFound","message":"Not found: "volume-accounts-2egoogle-2ecom-3auser12-2ename1234-40googlemail-2ecom"","field":"spec.containers[0].volumeMounts[0].name"}]},"code":422}`

related: Is it documented which roles users need to create jupyter pods on gke? Is `IAP-Secured Web App User` enough?

**Comment by jlewi** [comment]
That might help. I forgot we added a service account to the julyter pods to enable use of TFjob from juypyter.

Deploy.sh at Head will try to setup a Google cloud filestore. This might cause problems for you every if your project is old and has a legacy network. So you might not to comment out those steps in deploy.sh.

**Comment by jlewi** [comment]
Closing this issue as stale.
