### ISSUE TITLE
Katib apply fail with error: Field does not exist: modeldbDatabaseImage

### ISSUE THREAD

**Issue by banbanandroid** [kubeflow/kubeflow#1291]
version: kubeflow v0.2.2
ks version: 0.11.0
k8s version: v1.11.0

when follow the doc [katib README](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/README.md) , I apply katib with
```
ks apply default -c katib
```
and receive error:
```
ERROR find objects: RUNTIME ERROR: Field does not exist: modeldbDatabaseImage
        /root/kubeflow_ks_app/vendor/kubeflow/katib/modeldb.libsonnet:132:24-51 object <anonymous>
        <std>:1222:30-34        thunk from <thunk from <function <anonymous>>>
        <std>:1216:24-25        thunk from <thunk <t> from <function <anonymous>>>
        <builtin>       builtin function <type>
        <std>:1217:8-9  function <anonymous>
        <std>:1165:25-26        thunk from <thunk <ta> from <function <anonymous>>>
        <builtin>       builtin function <type>
        <std>:1167:29-31        thunk from <function <anonymous>>
        <builtin>       builtin function <primitiveEquals>
        <std>:1167:8-36 function <anonymous>

        <std>:1222:20-35        thunk from <function <anonymous>>
        <std>:1208:10-11        function <isContent>
        <std>:1165:25-26        thunk from <thunk <ta> from <function <anonymous>>>
        <builtin>       builtin function <type>
        <std>:1167:29-31        thunk from <function <anonymous>>
        <builtin>       builtin function <primitiveEquals>
        <std>:1167:8-36 function <anonymous>

        <std>:1222:10-36        function <anonymous>
        ...
        <builtin>       builtin function <type>
        <std>:1167:29-31        thunk from <function <anonymous>>
        <builtin>       builtin function <primitiveEquals>
        <std>:1167:8-36 function <anonymous>

        <std>:1218:35-56        function <anonymous>
        <builtin>       builtin function <flatMap>
        <std>:1222:20-35        thunk from <function <anonymous>>
        <std>:1208:10-11        function <isContent>
        <std>:1165:25-26        thunk from <thunk <ta> from <function <anonymous>>>
        <builtin>       builtin function <type>
        <std>:1167:29-31        thunk from <function <anonymous>>
        <builtin>       builtin function <primitiveEquals>
        <std>:1167:8-36 function <anonymous>

        <std>:1222:10-36        function <anonymous>
        <builtin>       builtin function <flatMap>
        <builtin>       builtin function <$objectFlatMerge>
        <extvar:__ksonnet/components>:(87:5)-(89:56)    object <anonymous>
        During manifestation
 ```
it seems that the default parameters with name modeldbDatabaseImage is not set, what is the image should kubeflow-v0.2.2 with component katib have?

I'm not sure if the mongo:3.4 is right, I just found it [here](https://github.com/kubeflow/katib/blob/master/examples/MinikubeDemo/manifests/modeldb/db/deployment.yaml), please give me an answer and may be this param-lost-error should be fixed

**Comment by fyuan1316** [comment]
i just met this problem, after fix the typo in katib's all.jsonnet , it worked for me. 
by the way, the image is mongo:3.4. i think you could get it work in two way：
1) set param 
> ks param set <_component-name_> modeldbDatabaseImage mongo:3.4 --env <_your-env-name_>
2) copy the jsonnet file from master branch (yes, it's already fixed), overwrite your local's.
the file path is "kubeflow/katib/prototypes/all.jsonnet"

**Comment by banbanandroid** [comment]
@fyuan1316 thx and it works

**Comment by opus111** [comment]
Hello, I just ran into the problem again, also following the tutorial for katib on GKE

https://www.kubeflow.org/docs/components/hyperparameter/

The prototype file on master does not seem to have any db variables

kubeflow/katib/prototypes/all.jsonnet

    ks apply ${KF_ENV} -c katib
    ERROR find objects: RUNTIME ERROR: Field does not exist: modeldbDatabaseImage
	/var/folders/6f/jxrrrmq94rvfqzzxjbpn8k3c0000gq/T/ksvendor410781056/kubeflow/katib/modeldb.libsonnet:132:24-51	object <anonymous>
	<std>:1245:30-34	thunk from <thunk from <function <anonymous>>>
	<std>:1239:24-25	thunk from <thunk <t> from <function <anonymous>>>
	<std>:1239:15-26	thunk <t> from <function <anonymous>>
	<std>:1240:8-9	function <anonymous> ....
