### ISSUE TITLE
JupyterHub login unauthorized (401)

### ISSUE THREAD

**Issue by AdrianLsk** [kubeflow/kubeflow#1296]
Ran deploy.sh according to GKE tutorial. Everything went smooth.

Following the [tutorial](https://www.kubeflow.org/docs/guides/components/jupyter/) for launching Jupyter Notebook, I went for the port-forwarding option, but got stuck and couldn't find any other similar issue.

http://127.0.0.1:8000/hub/login gives

![image](https://user-images.githubusercontent.com/4333307/43488573-7b005220-951a-11e8-8b2a-4a3ce25cabc9.png)

I get the same output for the LoadBalancer option. Any ideas, please?

**Comment by kunmingg** [comment]
You should have the url ```https://<deploy>.endpoints.<project>.cloud.goog``` up after run deploy.sh.
Can you try ```https://<deploy>.endpoints.<project>.cloud.goog/hub```?

**Comment by kunmingg** [comment]
It's your kubeflow service address hosted in your project, need to login with google.

**Comment by AdrianLsk** [comment]
@kunmingg indeed, that's working. It wasn't clear to me that I should use the ingress address when reading the docs. Thanks man!
