### ISSUE TITLE
Unable to get Jupyterhub API token

### ISSUE THREAD

**Issue by Silentphantom62** [kubeflow/kubeflow#1303]
Issue: Need API access to Jupyterhub to automate creating notebooks.

I setup following the minikube guide. https://www.kubeflow.org/docs/started/getting-started-minikube/

I tried fetching the API token from Tokens using _Request New Token button_ I get a 403.

![screen shot 2018-08-01 at 5 51 29 pm](https://user-images.githubusercontent.com/38120935/43556257-c7a1491a-95b3-11e8-9ff1-4cd73c50d3bc.png)

Also if I try the API:
curl -X GET http://<server-address.com>:<port>/hub/api/users
I get
{
    "status": 403,
    "message": "Forbidden"
}

How do I fix this or get the Token for authenticating to Jupterhub API?

**Comment by amsaha** [comment]
I suppose you took a look at https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/troubleshooting.md? There is some text around 403 ERROR.

**Comment by jlewi** [comment]
@Silentphantom62 I don't know if anyone has tried to use the JupyterHub REST API 
http://jupyterhub.readthedocs.io/en/latest/reference/rest.html

I would conjecture that the ability to generate API tokens is dependent on how you configure JupyterHub to do auth.

On GCP we generally bypass JupyterHub for auth since we use IAP. So in that case I'm not sure how JupyterHub could mint API tokens.

**Comment by Silentphantom62** [comment]
@amsaha The problem is that I don't know where I can get the token itself. The 403's in the mentioned URL are issues with invalid token.

@jlewi I want to use the REST API that you have mentioned. How can I configure Auth for The JupyterHub server that is spun up by kubeflow? I want some way to hit the JupyterHub endpoint via API and create users/notebooks. My setup currently is the getting started with minikube equivalent on bare metal.

**Comment by jlewi** [comment]
@Silentphantom62 I think you area breaking new ground here. Do you want to investigate and try to figure this out?

**Comment by Silentphantom62** [comment]
@jlewi I am trying to do it but honestly I am new to Kubeflow and Kubernetes and the documentation for Kubeflow isn't very helpful rightly because of the stage the project is in at the moment.

I have been trying to set this up https://github.com/kubeflow/kubeflow/tree/master/components/jupyterhub#github-oauth-setup
So that I can give it a try with github oath but I am stuck at the point where after my changes the jupyterhub page is timing out.

**Comment by jlewi** [comment]
I think you should look at the JuypterHub docs and especially the JupyterHub docs on K8s. We aren't doing much with JupyterHub other than bundling it with other services. So mostly this is a question of how to properly configure JupyterHub.

**Comment by jlewi** [comment]
/lifecycle stale.
With 0.5 we are no longer using JupyterHub.
