### ISSUE TITLE
CentralDashboard returns 404; Ambassador can't parse the route

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1306]
On master Ambassador shows the following error trying to parse the route for the central dashboard

```
2018-08-03 06:35:54 diagd 0.30.1 ERROR: k8s-dashboard-kubeflow.yaml.1: <RichStatus BAD error=k8s-dashboard-kubeflow.yaml: could not parse YAML hostname=ambassador-7d8f87f6dc-2mbk2 resolvedname=10.20.0.10 version=0.30.1>
```
As a result no mapping is defined and trying to access the central dashboard behind Ambassador gives a 404.

This is ksonnet/ksonnet#670

We should be able to workaround this.

**Comment by richardsliu** [comment]
Seems like this is fixed if the cluster is deployed using ks version 0.12+.

**Comment by jlewi** [comment]
Can we still implement a work around so that we don't have to require 0.12 just to fix this?
