### ISSUE TITLE
Use Istio 1.0

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1309]
We integrated istio for TF Serving with istio 0.7.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet#L17
https://www.kubeflow.org/docs/guides/components/istio/

Now that istio is 1.0, we should migrate to that.

**Comment by lluunn** [comment]
#1823 actually doesn't work: I set the traffic to v1:100,v2:0, but still see requests going to v2.

And the reason is that istio uses client-side proxy to route requests, but in this case the client (ambassador) service is not in istio mesh.

So I think options are:
- add one additional hop
- don't use ambassador

**Comment by lluunn** [comment]
Another option: ambassador supports percentage traffic routing:
https://www.getambassador.io/reference/canary

**Comment by jlewi** [comment]
@lluunn Can you clarify the scope of this issue?

Is this issue just about changing the version of ISTIO from 0.7 to 1.0? Or is it more involved then that?

What work remains on this issue?

**Comment by lluunn** [comment]
I think we can close this one and file separate issues.
My original thought was only to change Istio version from 0.7 to 1.0, which is done now.

We have #1844 for rollout.
Filed #1907 for jwt validation.
