### ISSUE TITLE
deployment script should test the default zone.

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1323]
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml#L30

us-central1-a does not have Intel Haswell.
We need that for AVX2: #1083 

However, the test doesn't fail because the test project's default zone overwrites it to us-east1-d

**Comment by jlewi** [comment]
/assign @jlewi

This will be fixed by #1308 

We don't actually use the default value in cluster-kubeflow.yaml because our deployment scripts overwrite that based on ZONE.

#1308 fixes this by changing the value in cluster-kubeflow.yaml to make it clear that the value will get overwritten.
