### ISSUE TITLE
Reusability and composability of steps in our E2E tests

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1325]
Our E2E tests often have subgraphs/steps that we'd like to reuse across different E2E tests.
To date we've largely followed one of two approaches

1. We either copy/paste the code between multiple workflows

    * e.g. [tf-operator/workflows](https://github.com/kubeflow/tf-operator/blob/master/test/workflows/components/workflows.libsonnet) & [kubeflow/workflows](https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/workflows.libsonnet)

2. We create a single workflow and parameterize it it with conditionals e.g. [kubeflow/workflows](https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/workflows.libsonnet) is used for minikube and GKE.

Both of these approaches have drawbacks and it would be nice to come up with better patterns of reuse among our E2E tests. Specifically, we'd like to make it easy to define and reuse steps or DAGS across E2E tests.

Example: We'd like to define the steps/dag to deploy Kubeflow and make it easy to reuse that across all component tests that need to deploy Kubeflow.

I think we can leverage

  * Argo [Nested Workflows](https://github.com/argoproj/argo/blob/master/examples/nested-workflow.yaml)
 *  ksonnet to make this more reusable.

In a ".libsonnet" file we can define Argo DAGs corresponding to specific functions e.g.
  * Deploy Kubeflow
  * Teardown Kubeflow
  * Run a particular test (e.g TFJob test)

The libsonnet file can then be imported into individual E2E tests and the DAG can be used as a nested workflow.

If needed we can take advantage of ksonnet features (e.g. late binding) to make it easy to override parameters.

**Comment by jlewi** [comment]
I might take a stab at defining a workflow to run deploy Kubeflow using kfctl.sh based on #1308.

**Comment by lluunn** [comment]
+1
