### ISSUE TITLE
[Proposal] Kubeflow Base Images and Supporting Vendors

### ISSUE THREAD

**Issue by tmckayus** [kubeflow/kubeflow#1326]
This is a proposal originally drafted by Jeremy Lewi with contributions from others, it may still need more eyes and refinement before we consider it final.

The goal is to create a set of guidelines for supporting multiple distros as base images in kubeflow components.

https://docs.google.com/document/d/1B3LumU7u9dJA0ElM37KlPeSHJzSSpLV1l52E9ZmbJvo/edit#heading=h.alaoz7uek0k7

**Comment by jlewi** [comment]
@tmckayus Can you open up an issue in kubeflow/community and close this one? 
Current process is to use kubeflow/community for proposals.

**Comment by tmckayus** [comment]
@jlewi, certainly! thanks

**Comment by tmckayus** [comment]
Moved to https://github.com/kubeflow/community/issues/165
