### ISSUE TITLE
Error generating tensorboard

### ISSUE THREAD

**Issue by 372046933** [kubeflow/kubeflow#1330]
Executing the following command three times in a row.
`ks generate tensorboard tb` sometimes succeeds without complaining about `--logDir`.

```
➜  kubeflow_ks_app ks generate tensorboard tb
ERROR failed to instantiate prototype "io.ksonnet.pkg.tensorboard". The following required parameters are missing:
--logDir=<logDir> The path containing your TF events files. [type: string] 
➜  kubeflow_ks_app ks generate tensorboard tb
ERROR failed to instantiate prototype "io.ksonnet.pkg.tensorboard". The following required parameters are missing:
--logDir=<logDir> The path containing your TF events files. [type: string] 
➜  kubeflow_ks_app ks generate tensorboard tb
INFO Writing component at '/home/tx/Downloads/kubeflow_ks_app/components/tb.jsonnet' ```

**Comment by jlewi** [comment]
Can you check components.params?

I suspect the earlier runs created any entry for tb and because of that it might not throw an error on the subsequent runs.

Might be worth look at GitHub issues for ksonnet to see if this is a known issue.

**Comment by 372046933** [comment]
I produced the error by successively sending three commands very fast.

**Comment by jlewi** [comment]
@372046933 Thanks. Were you running ks in multiple threads/processes simultaneously?

**Comment by 372046933** [comment]
Nope, it seems that sometimes `ks generate tensorboard` failed to check `--logDir`
