### ISSUE TITLE
PS still running after tfjob is complete.

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/kubeflow#1334]
Hi,
I have an issue that the PS pod keeps running after the tfjob is complete, even after several days.
kubectl get pods returns
'''
trainer-180804-004108-master-0                0/1       Completed   0          4d
trainer-180804-004108-ps-0                    1/1       Running     0          4d
trainer-180804-004108-worker-0                0/1       Completed   0          4d
'''

And, kubectl get tfjob returns
'''
  tfReplicaStatuses:
    MASTER:
      succeeded: 1
    PS:
      active: 1
    Worker:
      succeeded: 1
'''

**Comment by jlewi** [comment]
Refiled kubeflow/tf-operator#774
