### ISSUE TITLE
Multi-model serving workflow support

### ISSUE THREAD

**Issue by xinzhangcmu** [kubeflow/kubeflow#1337]
(For additional context see the [user survey](https://docs.google.com/document/d/1dbV9PK2Hkp9XqVI71K6jA7LW2CZbfbIyoZl-ZIn9ymM/edit#))

# Real-world Scenario

ML developers for an online design company are developing computer vision models to automatically tag a picture with different categories of labels reflecting “design styles”, to facilitate designers as their references. Applicable labels are classified into several (say, 20) mutual-exclusive categories, such as country style, brand style, industry style, season style, etc. For each picture to be tagged, the AI inference process should tag the picture with one label from each category, resulting each picture with 20 labels.

After algorithmic trial and error, the ML developers decided to use one dedicated model to handle the labels for each category, resulting in 20 different models in total. Given the business nature, for a given picture, the inference process includes invoking each model in serial, outputting one label from one category at each model invocation.

Even though these models will be executed sequentially and share the same GPU one after another in time, AFAIK current Kubeflow implementation automatically wraps each TensorFlow saved model as an independent service which will require multiple GPUs independently. Unfortunately, this causes a waste of the scarce GPU resources (not enough GPUs to allocate to these 20 models). This problem led to end users not using Kubeflow for serving, but to write a customized script or Java program as an overarching single service on Kubernetes, which internally invokes the models  sequentially on the same GPU.

# Problem Statement

We ran into cases where multiple trained models are needed to collectively serve a single user-level request; more specifically:

1. These models need to be executed in a pre-defined workflow with mutual-dependency and ordering to serve a particular service request

2. Sometimes certain models to be executed sequentially can share the same GPU resource to save the GPU resource.

# Possible Directions
- Define an orchestration framework so that developers can configure a workflow designating how multiple related models can be invoked in concert at service level.
- For models that should/can be executed sequentially on the same GPU, Kubernetes may automatically wrap them into a single service with multiple containers (one per model)?

**Comment by jlewi** [comment]
@xinzhangcmu Can you clarify whether this is online inference or batch inference?

**Comment by cliveseldon** [comment]
Certainly with seldon-core one can create a graph of required models to serve the request.
The latest [ksonnet prototypes for Seldon](https://www.kubeflow.org/docs/guides/components/seldon/) have several examples templates.   
Consult [the seldon docs](https://github.com/SeldonIO/seldon-core/blob/master/docs/crd/readme.md) for more details.

**Comment by jlewi** [comment]
@lluunn Any particular reason you added this to 0.4? Its not clear yet what the work is and 0.3 is already pretty oversubscribed.

**Comment by xinzhangcmu** [comment]
@jlewi it's both online and batch, but mostly batch

**Comment by jlewi** [comment]
For batch have you looked at using Apache Beam and our batch-predict support?

Using Apache Beam you could write a pipeline that consists of a sequence of DoFns where each DoFn does predictions using one model.

There are two potential difficulties.

1. We need to prevent fusing so that we only load 1 model at a time.
2. The Data flow runner can't use GPUs.

For 1. You could break it up into a sequence of batch prediction jobs orchestrated with Argo.

For 2. You can use the local runner and run on a single node using GPUs. Or you could combine dataflow with TFServing. You would use TFserving to deploy 1 or more replicas of a model using GPUs.  You could then use Dataflow to send RPCs to these models to do inference.

**Comment by cliveseldon** [comment]
You can send batch requests to Seldon and scale easily via the manifest and its replicas setting.

**Comment by chrisheecho** [comment]
This is in the top of the wish/blocker list
