### ISSUE TITLE
TfJob controllers are not namespace scoped so tests aren't isolated

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#134]
Controller claims jobs in all namespaces, but our tests are trying to reuse clusters by deploying in different namespaces. 

So our tests aren't isolated. 

Possible fixes

1. Run each E2E test in a separate cluster
1. Run add options to controller so it only claims jobs in a given namespace.

**Comment by jlewi** [comment]
I suspect this might be causing TFJob test flakes where we see  simple job test occasionally timing out waiting for a TFJob to finish. See for example #602

**Comment by jlewi** [comment]
@ankushagarwal This is fixed by #894 correct?

**Comment by ankushagarwal** [comment]
Yes.
