### ISSUE TITLE
Need to update glide's ksonnet version to ^0.11.0

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1340]
ks prototype in current master rely in ks version >= 0.11.0, but https://github.com/kubeflow/kubeflow/blob/master/bootstrap/glide.lock contains an older ks version which will trigger error for ambassador component.

**Comment by kunmingg** [comment]
@abhi-g 
@activatedgeek

**Comment by kunmingg** [comment]
@jlewi

**Comment by jlewi** [comment]
Seems reasonable to upgrade to 0.11. I don't know that we want to upgrade to 0.12 yet.
