### ISSUE TITLE
Jupyter notebook Connection failed because Ambassador doesn't enable websockets

### ISSUE THREAD

**Issue by fyuan1316** [kubeflow/kubeflow#1344]
### version: kubeflow v0.2.2

when create a py2 or py3 notebook, receive error message:

> ### Connection failed 
> A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.`

in chrome console , there 's more details:
>WebSocket connection to 'ws://150.109.69.83:31758/user/test/api/kernels/e064f45c-5e72-4814-82c2-f01c3dd48796/channels?session_id=d1b557af758946b0b55d61dcc9380cdc' failed: Error during WebSocket handshake: Unexpected response code: 403

![image](https://user-images.githubusercontent.com/42265657/43948179-b1c00e6e-9cbc-11e8-8491-1aa95b294d26.png)

**Comment by jlewi** [comment]
Thanks for the report and the fix.

I'm curious why we haven't run into this before. My conjecture is that most people don't access Jupyter through Ambassador. On GKE I think we might be redirecting to JupyterHub before going through Ambassador.

**Comment by Aravinviju** [comment]
Hi Whats the Fix for this?
I'm not sure where to find it!
I'm facing the same issue.

Any help would be of great help!

Thanks
Arav
