### ISSUE TITLE
GKE version "foo" is unsupported.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1348]
Currently in our deployment manager config we use GKE version "1.9.7-gke.3" as default, which recently got removed by GKE and not available any more.
Will remove GKE version from deployment manager config (when deploy, DM will use GKE's current default version), since GKE's version update and deprecate is quite frequent. To avoid this error happening again.    
Leave one conditional version for stackdriver which requires ^1.10. Should remove once ^1.10 becomes default.

**Comment by kunmingg** [comment]
@richardsliu @jlewi 
This currently blocks all e2e tests.

**Comment by jlewi** [comment]
I don't think we we want to upgrade the major version by default; we've seen breaking changes when moving from 1.9.7 to 1.10. So we should only upgrade the patch level. 
e.g. from 1.9.7-gke.3 to 1.9.7-gke.5
but not from 1.9.7 to 1.10

**Comment by jlewi** [comment]
I think what we should do is

1. Have a default value in cluster-kubeflow.yaml
2. Check during project initialization if its valid
3. If its not valid change the default with a log message to a supported version.

**Comment by sarahmaddox** [comment]
Hallo @kunmingg I'm getting this error at the moment.  I'm using Kubeflow v0.2.2

What I ran:
export KUBEFLOW_VERSION=0.2.2
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/gke/deploy.sh | bash

Error:
- code: RESOURCE_ERROR
  location: /deployments/sarahmaddox-kubeflow-gcp/resources/sarahmaddox-kubeflow-gcp
  message: '{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Master
    version \"1.9.6-gke.1\" is unsupported.","status":"INVALID_ARGUMENT","statusMessage":"Bad
    Request","requestPath":"https://container.googleapis.com/v1/projects/ml-writers/zones/us-central1-c/clusters","httpMethod":"POST"}}'

Can you tell me how I can work around this problem until it's fixed? It's blocking my deployment, and I can't figure out where to reset the version.

**Comment by jlewi** [comment]
@sarahmaddox  try the following

```
export KUBEFLOW_VERSION=0.2.2
export KUBEFLOW_DEPLOY=false
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/gke/deploy.sh | bash
```

Then look in the directory `${DEPLOYMENT_NAME}__deployment_manager_configs` and look for cluster.jinja

and change this line
https://github.com/kubeflow/kubeflow/blob/v0.2-branch/scripts/gke/deployment_manager_configs/cluster.jinja#L81

To

```
initialClusterVersion: 1.9.7-gke.5
```

Then rerun deploy.sh to deploy it.

**Comment by kunmingg** [comment]
@lluunn

**Comment by sarahmaddox** [comment]
Thanks @jlewi I've tried that but am still getting the error. I'll wait until this issue is fixed for v0.2 then try the end-to-end process again.

**Comment by jlewi** [comment]
@lluunn I've merged #1355 

Lets make the following changes as well

1. Change `master` to `v0.2-branch in deploy.sh 
https://github.com/kubeflow/kubeflow/blob/v0.2-branch/scripts/deploy.sh#L9

1. Lets verify deploy.sh is reentrant
1. Lets tag it 0.2.3
1. Lets update the docs on the 0.2 branch

**Comment by AdrianLsk** [comment]
I had the same issue. Worked for me, thanks!

**Comment by jlewi** [comment]
We've published a new RC with the fix. You can try

```
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v0.2.3-rc.0/scripts/gke/deploy.sh | bash
```

**Comment by sarahmaddox** [comment]
Thanks! That worked - the deploy script ran to completion and my K8s resources are visible to kubectl and in the Kubernetes Engine console.

**Comment by jlewi** [comment]
/assign @richardsliu 

@richardsliu Looks like the only thing left to do is update the docs on the 0.2 branch.

**Comment by jlewi** [comment]
I just checked 0.2.4 and it is working.
