### ISSUE TITLE
Prow agent to automatically cherry-pick PRs onto release branches

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1363]
I thick prow has an agent  that will take care of cherry-picking PRs that are annotated onto release branches.

We should look into using that to simplify our release management.

**Comment by jlewi** [comment]
Related issue in Kubernetes about managing Cherry picks
kubernetes/test-infra#1795

**Comment by chrisheecho** [comment]
not essential for the product itself but should be p1 or p0 for Q1 2019, so that we can improve overall velocity.
