### ISSUE TITLE
Unify API of kubeflow go pkg to serve both deploy web app and cmd line tool.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1373]
We have been developing [deploy app](https://github.com/kubeflow/kubeflow/tree/master/components/gcp-click-to-deploy) and [deploy script](https://github.com/kubeflow/kubeflow/tree/master/scripts) individually for a while:

Current problem:
1. Configs / features are not in sync, we need consistent user experience (through consistent config).
2. As we adding more features / components to kubeflow, bash scripts become hard to dev / maintain / test.

What we want:
1. turn [deploy script](https://github.com/kubeflow/kubeflow/tree/master/scripts) into cmd line tool (or a kubectl plugin).
2. make go pkg have unified API which can serve both deploy app and cmd line tool, so we can reuse code & config, prevent further inconsistency.

**Comment by jlewi** [comment]
I think we already making progress on this with kfctl.
Duplicate of #2870
