### ISSUE TITLE
The testing/install_minikube.sh script assumes the host OS is Ubuntu.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#1383]
This can easily be fixed so that users of other systems (e.g. Debian) can use that script

**Comment by jlewi** [comment]
@Ark-kun Do you mean for deploying Kubeflow on minikube? There is work in progress to update our scripts; kfctl.sh to better support minikube. I don't know that we want folks to start using testing/install_minikube.sh for that.
