### ISSUE TITLE
GKE Deploy fails in European Zone as no NVIDIA GPUs available

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kubeflow#1389]
The core error seems to be

```
type \"nvidia-tesla-k80\" does not exist in zone europe-west4-b\ngoroutine 131398674
```
Full trace:

```
+ gcloud deployment-manager --project=kubeflow-testing-213813 deployments create kubeflow-testing --config=cluster-kubeflow.yaml
The fingerprint of the deployment is uhkZZ-qMmAJDKd0-Ya9F_w==
Waiting for create [operation-1534744332224-573d782be4600-1322585d-8ace48b9]...
........................................................................................................failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1534744332224-573d782be4600-1322585d-8ace48b9]: errors:
- code: RESOURCE_ERROR
  location: /deployments/kubeflow-testing/resources/kubeflow-testing-gpu-pool-v1
  message: '{"ResourceType":"container.v1.nodePool","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Accelerator
    type \"nvidia-tesla-k80\" does not exist in zone europe-west4-b\ngoroutine 131398674
    [running]:\nruntime/debug.Stack(0x5436440, 0x0, 0x0)\n\tthird_party/go/gc/src/runtime/debug/stack.go:24
    +0xa7\ngoogle3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).createErr(0x543f500,
    0x2d)\n\tcloud/kubernetes/engine/common/error_desc.go:199 +0x26\ngoogle3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).WithMsg(0x543f500,
    0x2e12b4b, 0x2d, 0xc018107ce8, 0x2, 0x2, 0x23, 0xc018107d08)\n\tcloud/kubernetes/engine/common/error_desc.go:142
    +0x99\ngoogle3/cloud/kubernetes/engine/common/clients/gce/gce.(*authedClient).validateAcceleratorAvailability(0xc00b63cd20,
    0x310c800, 0xc010bf92f0, 0xc006c5d4a0, 0xc004ff1f60, 0x17, 0xc006c7fde0, 0xe,
    0xc007a63538, 0x1, ...)\n\tcloud/kubernetes/engine/common/clients/gce/gce.go:3844
    +0x35f\ngoogle3/cloud/kubernetes/engine/common/clients/gce/gce.(*authedClient).validateCommon.func1(0x574b61,
    0x54c299)\n\tcloud/kubernetes/engine/common/clients/gce/gce.go:2864 +0x6b3\ngoogle3/cloud/kubernetes/engine/common/errors.CollectFns.func1(0xc00f6f1c20,
    0xc00b605ce0)\n\tcloud/kubernetes/engine/common/errors.go:160 +0x27\ncreated by
    google3/cloud/kubernetes/engine/common/errors.CollectFns\n\tcloud/kubernetes/engine/common/errors.go:160
    +0x82\n.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/kubeflow-testing-213813/zones/europe-west4-b/clusters/kubeflow-testing/nodePools","httpMethod":"POST"}}'
```

**Comment by jlewi** [comment]
Sorry about that.

I think the solution is to modify the deployment manager configs to disable GPUs before deploying.

I'd suggest trying it out with master.
https://master.kubeflow.org/docs/started/getting-started-gke/#quickstart-deploying-kubeflow-on-gke

After running `generate` but before calling `apply` modify the deployment manager configs.
Try setting gpu-pool-max-nodes nodes to 0 here:
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml#L48

If that doesn't work; you can delete the GPU node pool defined here
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster.jinja#L114

**Comment by dformoso** [comment]
Hi all,

The same thing happens when deploying in the Australia region. It errors out on GPUs, particularly the 'nvidia-tesla-k80' and Intel Haswell CPUs. Do you have any ideas on how to best refactor for this? I could give it a go. I tried setting gpu-pool-max-nodes nodes to 0 and it didn't fix it.

**Comment by ofaz** [comment]
Hey all - hope this is of some assistance. 

@jlewi I ran into the same issue described here and I was able to overcome it by utilising the second method - I commented out the GPU node pool as defined in the` cluster.jinja` file. I had attempted to use your first method, of setting `gpu-pool-max-nodes` to 0 however that throws the error:
`message: '{"ResourceType":"container.v1.nodePool","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Node_pool_autoscaling.max_node_count
    must be greater than 0.","status":"INVALID_ARGUMENT",`

**Comment by jlewi** [comment]
Thanks @ofaz 

This should be fixed at head. 
https://github.com/kubeflow/kubeflow/blob/41050ef854948600ef7f922f2a3c295b60b1f7c0/deployment/gke/deployment_manager_configs/cluster.jinja#L115

We no longer add the GPU node pool if max gpu nodes is 0.

The change isn't on the 0.3 branch
https://github.com/kubeflow/kubeflow/blob/dddba26893846041b7cee25ee6121e02a04bd503/scripts/gke/deployment_manager_configs/cluster.jinja#L116

**Comment by ofaz** [comment]
@jlewi awesome! Thank you mate.
