### ISSUE TITLE
Update 0.2 blog with new deployment script

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/kubeflow#1390]
@jlewi should we update the [0.2 blog](https://www.kubeflow.org/blog/announcing_kubeflow_0.2/) with the new script from [1311](https://github.com/kubeflow/kubeflow/pull/1311)

"curl https://raw.githubusercontent.com/kubeflow/kubeflow/v0.2.3-rc.0/scripts/gke/deploy.sh | bash"

**Comment by jlewi** [comment]
@chrisheecho Yes but we can use the following now

```
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v0.2.3/scripts/gke/deploy.sh | bash
```

**Comment by sarahmaddox** [comment]
This issue was moved to kubeflow/website#215
