### ISSUE TITLE
JupyterHub Version Mismatch

### ISSUE THREAD

**Issue by tlkh** [kubeflow/kubeflow#1393]
> **Important TLDR**
> Earlier today I struggled with a version mismatch between JupyterHub and Jupyter Notebook created from the JupyterHub, where I could reproduce the error multiple times on a clean install. 
>Amazingly in the last hour as I am attempting to replicate the issue, it is now unreproducible despite the version mismatch. I have been unable to isolate the precise cause of why I experience the error.
>Despite this, I wish to describe the situation and also make some arguments as to allowing the end-user to fix the version of JupyterHub they would like to deploy.
> In addition, I think we can leave this issue up as a reference in case somebody else experiences the same problem, as I managed to resolve it.

Earlier today, I can reproduce the error multiple times by simply installing Kubeflow on a brand new Minikube node in a VM, across about two hours before I managed to resolve it for myself. I used v0.2.2, as installed using `ks`, and it threw an Redirect Loop error when starting a Jupyter Notebook from the JupyterHub spawner.

I used the image `gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-cpu:v0.2.1` and other images from Docker Hub, e.g. `jupyter/scipy-notebook`, and the same error occurred.
```
Redirect loop detected. Notebook has jupyterhub version 0.9.1, but the Hub expects 0.9.0-dev. Try installing jupyterhub==0.9.0-dev in the user environment if you continue to have problems.
```
I was only able to address the problem by editing the configuration of the Stateful Set `tf-hub`, changing the command used as the entry point into the `tf-hub-0` container as it is created:
```
"name": "tf-hub",
"image": "gcr.io/kubeflow/jupyterhub-k8s:v20180531-3bb991b1",
"command": [
    "/bin/bash",
    "-c",
    "pip3 install jupyterhub==0.9.1 && jupyterhub -f /etc/config/jupyterhub_config.py"
],
```
This forcefully fixes the version of JupyterHub to a compatible one.

Amazingly in the last hour as I am attempting to replicate the issue, it is now unreproducible despite the version mismatch still being present. I have been unable to isolate the precise cause of why I experience the error.

However, I feel that it is still extremely important to give users option to control the exact version of JupyterHub they are using for the following reasons:

- it will allow users to use newer images from Docker Hub, which might have some forward compatibility issues like that I experienced.
- it will allow users to upgrade JupyterHub without needing for the version packed with Kubeflow to be updated (with the caveat that the user might knowingly introduce some issues)
- if users require an older version of JupyterHub for compatibility reasons with certain packages

Thanks for reading!

**Comment by jlewi** [comment]
I checked as well  with 0.2.4 and  I was able to launch a notebook.

I used:
notebook image: gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-cpu:v0.2.1
JupyterHub image: gcr.io/kubeflow/jupyterhub-k8s:v20180531-3bb991b1

Users can customize the JupyterHub image if they want by setting the parameter in their JupyterHub prototype.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/prototypes/jupyterhub.jsonnet#L9

The 0.3 scripts will make this a bit easier.

**Comment by MatthiasHertel** [comment]
@jlewi 

I used exactly the versions you mentioned ... 

```
matthias in ~/projekt/ml/mlaas-ba/gcloud-kubeflow/kubeflow/kubeflow_app/ks_app on gcloud-kubeflow ● ● λ ks param list jupyterhub
COMPONENT  PARAM                   VALUE
=========  =====                   =====
jupyterhub accessLocalFs           'false'
jupyterhub cloud                   'null'
jupyterhub disks                   'null'
jupyterhub gcpSecretName           'user-gcp-sa'
jupyterhub image                   'gcr.io/kubeflow/jupyterhub-k8s:v20180531-3bb991b1'
...
```

and in dropdown menu on the hub i used:
![image](https://user-images.githubusercontent.com/8426566/50387833-33b1cf80-0706-11e9-9f24-da32b41fb1b8.png)


and i got still an version mismatch:

![image](https://user-images.githubusercontent.com/8426566/50387837-4e844400-0706-11e9-899b-f75190e4e280.png)
