### ISSUE TITLE
Kubernetes API server removed support for the root /proxy paths in v1.10 (deprecated since v1.2)

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#1398]
See https://github.com/kubernetes/kubernetes/pull/59884, https://github.com/kubernetes/kubernetes/commit/687c651dfd0793d53299b27c5472d69ef4c4c44f, https://github.com/kubernetes/kubernetes/issues/59885,

We'll need to fix our URLs otherwise they would stop working once we upgrade to 1.10.

**Comment by jlewi** [comment]
@Ark-kun What URls in Kubeflow are using /proxy?

**Comment by jlewi** [comment]
@Ark-kun Which README.md?

**Comment by Ark-kun** [comment]
@jlewi This one: https://github.com/kubeflow/kubeflow/blob/master/testing/README.md#accessing-argo-ui

**Comment by jbottum** [comment]
@Ark-kun this issue / request seems old.   Is there an another path to build and support the needed environment?
