### ISSUE TITLE
Don't use DM for IAM policy management

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1401]
Right now our DM config [cluster.jinja](
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster.jinja#L161)

Adds a bunch of IAM role bindings.

This creates two problems

1. The optimistic locking on setting IAM roles can block DM creation. It also makes deleting deployments really complicated because we need to do an update before doing a delete.
1. it requires give the DM service account the ability to set project IAM which significantly escalates its permission.

We could create a separate DM resource to set IAM roles; this would partially address #1 but #2.

I think to avoid granting the DM elevated permissions we should stop using DM to create appropriate role bindings.

We would still like to be declarative though in the way we manage role bindings.

I think there's a couple ways to do this

1. During the generate phase of kfctl we could create add and remove shell scripts that would call out to gcloud add-iam-policy-binding and gcloud remov-iam-policy-binding

1. We could define an IAM policy patch in JSON/YAML and then create a python script to apply it.

**Comment by kunmingg** [comment]
Agree, current IAM role manage logic is fragile.

**Comment by ankushagarwal** [comment]
IAM management is problematic in DM, but I don't think that either #1 or #2 is a good idea because we will end up creating our own deployment manager for declaratively managing IAM configs.

**Comment by jlewi** [comment]
@ankushagarwal is that duplication less desirable than the current situation?

In particular, granting DM ability to set IAM policies seems highly undesirable. 

In current situation, we need to create our own delete wrapper because we can't issue a DM delete without issuing an update first.  This has a bunch of drawbacks; including 
   * not being able to easily delete via U
   * If a DM is partially deleted eg. cluster is deleted; doing an update will recreate the resources before doing the delete.

We already need to implement our own delete script to properly clean up the policy bindings.
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/delete_role_bindings.py

**Comment by ankushagarwal** [comment]
I guess it makes sense if we have already added code to manage IAM policies outside of DM.

**Comment by ankushagarwal** [comment]
FYI I've started taking a stab at this : https://github.com/kubeflow/kubeflow/pull/1408/

I'm going with suggestion #2
