### ISSUE TITLE
Seldon cluster needs imagePullSecrets

### ISSUE THREAD

**Issue by inc0** [kubeflow/kubeflow#1402]
Currently it's impossible to use seldon prototype with private registry. There is no way to specify imagePullSecrets as parameter.

**Comment by cliveseldon** [comment]
I'll take a look at updating the prototypes

**Comment by cliveseldon** [comment]
imagePullSecrets can be specified in the PodTemplateSpec part of the SeldonDeployment. Would this not solve the issue?

**Comment by cliveseldon** [comment]
There is a PR now with imagePullSecret in the prototypes to make this easier : #1431 
As said, you can simply add the imagePullSecrets to your spec but this PR would show examples.
