### ISSUE TITLE
Central UI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#141]
Kubeflow's UI consists of multiple independent UI's corresponding to different components; e.g.

- TFJob's UI
- TensorBoard
- K8s Dashboard
- JupyterHub
- ArgoUI

All of which will be accessible via a reverse proxy (#11). 

It would be nice if we had a simple UI that could serve as a main landing page. This could be a very simple page that would just have links that pointed at the individual UI components.

**Comment by swiftdiaries** [comment]
I would like to work on this, if it's not already taken.

**Comment by jlewi** [comment]
Please do thank you.

@wbuchwalter  @jimexist have been leading up our UI efforts to date so please coordinate with them and add them as reviewers on any PRs.

**Comment by Jimexist** [comment]
@jlewi what's the current status regarding ArgoUI? I don't see concrete code yet in tensorflow/k8s

**Comment by Jimexist** [comment]
also where would this piece of code reside?

**Comment by jlewi** [comment]
@Jimexist Argo isn't included yet; but it would be pretty straightforward to turn the libsonnet file used by our tests into a prototype in our registry (see #21).

**Comment by jlewi** [comment]
Closing this in favor of more specific issues with label area/front-end
/close

**Comment by mongoose54** [comment]
Is there any progress on creating a centralized UI ? As @jlewi mentioned that would be extremely helpful for newcomers?
