### ISSUE TITLE
istio 1.0 for kubeflow metrics

### ISSUE THREAD

**Issue by zehni** [kubeflow/kubeflow#1413]
Hello, 

I am currently serving ML models on kubeflow in the default namespace. I have been trying to get metrics using istio 1.0, but it seems that [1309](https://github.com/kubeflow/kubeflow/issues/1309) shows that kubeflow is not ready yet for istio 1.0

I have tried installing istio 0.7 and apply the steps explained [here](https://www.kubeflow.org/docs/guides/components/istio/) but it doesn't seem to finish the installation due to errors from the installation files of the injector. 

I am a bit new to the world of kubernetes, kubeflow etc .. so is there a page of documentation or someone who has a tutorial on how would this work with istio 0.7

Thank you

**Comment by jlewi** [comment]
What are the errors?

**Comment by zehni** [comment]
```
nlhfd-lt1889:istio-0.7.1 zehni.khairullah$ cat install/kubernetes/istio-sidecar-injector.yaml | \
>      ./install/kubernetes/webhook-patch-ca-bundle.sh > \
>      install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
Error from server (NotFound): configmaps "extension-apiserver-authentication" not found
```
I know that this is configmap is called within the `webhook-patch-ca-bundle.sh` as follows

`export CA_BUNDLE=$(kubectl get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n')`

However, I don't know where to find this file to install it

**Comment by jlewi** [comment]
@lluunn Is ISTIO 1.0 now supported?

**Comment by jlewi** [comment]
I don't think #1309 has anything to do with installing ISTIO. The issue in #1309 is that if we want to split traffic to models using ISTIO then the client sending the requests has to be inside the service mesh.

**Comment by lluunn** [comment]
https://www.kubeflow.org/docs/guides/components/istio/

The instruction here is updated for Istio 1.0
