### ISSUE TITLE
standardize remaining <component>.{jsonnet,libsonnet} files

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1414]
jupyterhub.{[jsonnet](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/prototypes/jupyterhub.jsonnet),[libsonnet](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub.libsonnet)} allows one to easily add, update or remove resources or parts of resources. For example if one wanted to add imagePullSecrets to jupyterhub's HubStatefulSet one would do:

```
local jupyterhub = import "kubeflow/core/jupyterhub.libsonnet";
local updated = jupyterhub + {
  HubStatefulSet+: {
     spec+: {
       template+: {
         spec+: {
          imagePullSecrets: [
            {name: "mySecret",},
          ],
        },
      },
    },
  },
};
updated.all(updatedParams).list
```

This pattern should be standardized in the other components

**Comment by jlewi** [comment]
@kkasravi Do you want to start a style guide 
https://github.com/kubeflow/kubeflow/tree/master/docs_dev

So we can begin to document best practices?

**Comment by kkasravi** [comment]
@jlewi I'll include the style guide in this PR
