### ISSUE TITLE
kfctl.sh unable to find component ambassador

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1429]
I ran kfctl.sh at head

```
kfctl.sh init jlewi-0825 --platform gke 
kfctl.sh generate all
```
and got the error.

```
+ ks param set ambassador cloud
ERROR unable to find component ambassador    
```

I think @abhi-g reported similar issues when working on #1387 and thought the problem was due to using negative integers as defaults in the JupyterHub prototype. But it looks like something else may be going on here.

presubmits passed in #1387 so not sure why it would pass there and not in other places; only difference is in the test we run

```
kfctl.sh generate platform
kfctl.sh generate k8s
```

and not all.

**Comment by jlewi** [comment]
```
ks component list
COMPONENT
=========
ambassador
argo
centraldashboard
jupyterhub
pytorch-operator
spartakus
tf-job-operator
```

So the component is there.

Parameters are in the components/params.libsonnet

```
    ambassador: {
      ambassadorImage: "quay.io/datawire/ambassador:0.37.0",
      ambassadorServiceType: "ClusterIP",
      cloud: "null",
      name: "ambassador",
      statsdExporterImage: "prom/statsd-exporter:v0.6.0",
      statsdImage: "quay.io/datawire/statsd:0.37.0",
    },
```

**Comment by jlewi** [comment]
This appears to be related to the fact that we delete the environment 

After running `kfctl.sh generate k8s` I could reproduce the problem if I tried to set the parameter. But if I then added an environment the command succeeded.

```
ks param set ambassador cloud
ERROR unable to find component ambassador          
$ ks env add default
INFO Using context "jlewi-0823" from kubeconfig file "/home/jlewi/.kube/config" 
INFO Creating environment "default" with namespace "kubeflow", pointing to cluster at address "https://35.232.196.152" 
$ ks param set ambassador cloud
ERROR unable to find component ambassador  
```

I then removed the environment again and trying to set the parameter failed.

```
ks param set ambassador cloud
ERROR unable to find component ambassador          
```

So looks like an issue with not having an environment. I think we need to add the environment in customizeKsApp and then remove it again.

**Comment by jlewi** [comment]
Actually I it looks like the command 

```
ks param set ambassador cloud
```

Might be invalid; i.e. it is missing a value.

I just retried at HEAD using platform "gcp" (not gke) and it seemed to work. So the error seems to be dependent on the cloud value. Which could explain why tests are passing.

**Comment by abhi-g** [comment]
It looks like ambassador section in params.libsonnet has "cloud" : "null".

Looking through the kfctl.sh script, the createEnv() function sets KUBEFLOW_CLOUD into the generated env.sh. This happens within the specific platform types: "minikube", "ack", & "gcp". If the specified platform is not exactly one of those, the "cloud" : "null" would probably get generated into the components. This explains why your initial command might not have set it:
kfctl.sh init jlewi-0825 **--platform gke** 

Possibly we can change the script for the gcp section to work either with "gcp" or "gke"?

**Comment by 372046933** [comment]
@jlewi Maybe you mean KUBEFLOW_CLOUD

**Comment by 372046933** [comment]
`ks env add --api-spec=version:$K8S_VERSION default` has to be executed manually.

**Comment by jlewi** [comment]
@372046933 yes.
