### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by ewilderj** [kubeflow/kubeflow#143]
As a community, it is great practice for us to have a code of conduct.

**Comment by sfabel** [comment]
+1

How about we adopt this one: [CNCF Community Code of Conduct v1.0](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)

**Comment by ewilderj** [comment]
We have recently done some work at Google on a template code of conduct, which is a version of the [Contributor Covenant](http://contributor-covenant.org/) (which CNCF as many others are based on), and informed by our experiences with Kubernetes, etc.The main thing it adds is a conflict resolution policy. I suggest we could start with that and see if it meets our needs.

**Comment by jlewi** [comment]
Thanks @ewilderj. It looks like the convenant provides instructions on adding it to our project.

**Comment by jlewi** [comment]
Code of conduct has been added to kubeflow/community
https://github.com/kubeflow/community/blob/master/CODE_OF_CONDUCT.md
