### ISSUE TITLE
[gcp] VM account should have GCS read only scope to support pulling from GCR

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1432]
Our DM configs should add readonly scope to the VM service account so that we can pull private images.

https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster.jinja#L24

We should include
https://www.googleapis.com/auth/devstorage.read_only

**Comment by sarahmaddox** [comment]
Confirmation: I've just successfully pulled a container into GKE from GCR, after manually adjusting the OAuth settings in cluster.jinja as described in this issue. 

Before making that change, I reliably received the following error in GKE:
ImagePullBackOff rpc error: code = Unknown desc = unauthorized: authentication required: ErrImagePull
Failed to pull image "gcr.io/ml-writers/sarahmaddox-kf-gcp-train:1535231259": rpc error: code = Unknown desc = unauthorized: authentication required

After making the change to the cluster.jinja file, the image pull works.

**Comment by jlewi** [comment]
Applications that need read/write access to GCS storage should use the "-user" service account
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster.jinja#L43

And not the VM service account.

We only want to give the VM service account read access as a convenience for pulling private GCR images.

**Comment by jlewi** [comment]
The fix was pushed in v0.2.5
https://github.com/kubeflow/kubeflow/releases/tag/v0.2.5
