### ISSUE TITLE
Update CentralUI image used at head and 0.3 branch

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1435]
We committed a number of improvements to the central UI.

We need to update the docker image used at head in order to test out these changes.

**Comment by jlewi** [comment]
@swiftdiaries Are we continuously building the central UI image? If we have an updated image can you create a PR to update the image used in ksonnet?

**Comment by swiftdiaries** [comment]
I don't think we are building it continuously. I'll get a PR in to fix that.
