### ISSUE TITLE
What's the function of tfReplicaType: Master ?

### ISSUE THREAD

**Issue by lxl910915** [kubeflow/kubeflow#1442]
Why and when kubeflow removed Master?
In a doc, we see: The master only acts as the chief and doesn't do any training. When master started and intilized, how master waits ps and worker to completed?

**Comment by gaocegege** [comment]
Master now is replaced by chief.

**Comment by jlewi** [comment]
Earlier versions of TensorFlow used "Master" to indicate the process that coordinates distributed training. TensorFlow then changed to calling this "Chief".

We added "Chief" to be consistent with TensorFlow terminology; but we've kept "Master" for backwards compatibility with older versions of TF.

**Comment by johnugeorge** [comment]
As @jlewi said,  Master type is still kept for backwards compatibility. https://github.com/kubeflow/tf-operator/blob/master/pkg/apis/tensorflow/v1alpha2/types.go#L135

**Comment by lxl910915** [comment]
@johnugeorge 
You mean tf_job only need to contain ps and worker ? no "Master", and no "Chief" ?
