### ISSUE TITLE
[Proposal] GPU stats monitoring for Kubeflow through a Prometheus exporter

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#1448]
This is a proposal doc for a Prometheus exporter that publishes stats like GPU duty cycle, GPU utilization rates for better visibility into GPUs while training / serving. 

https://docs.google.com/document/d/1Qbyav8viMb2MQbcD5tJVQs2zPYFjbfU3U2-7DqVGdXU/edit?usp=sharing

This can also then be exposed on a Grafana dashboard as shown here: https://github.com/swiftdiaries/nvidia_gpu_prometheus_exporter. But that is optional. 

Would love to get some feedback and comments :-)

**Comment by swiftdiaries** [comment]
Would the #wg-machine-learning be a good place to start off? @vishh Or perhaps the #wg-resource-mgmt?

**Comment by sfabel** [comment]
@jlewi - FWIW, NVIDIA has a 
[Prometheus Exporter](https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm).

**Comment by vishh** [comment]
If you choose to work with the k8s community on this, I'd recommend
starting with an email to #wg-resource-mgmt mailing list.

**Comment by swiftdiaries** [comment]
Thank you for the reply :)

**Comment by RenaudWasTaken** [comment]
Hi!

Have you taken a look at https://github.com/NVIDIA/gpu-monitoring-tools ?
In this case the DCGM exporter looks a bit like what you are looking for.

**Comment by RenaudWasTaken** [comment]
We also have a "DCGM only" exporter available here:
https://github.com/NVIDIA/deepops/blob/release-18.08/services/dcgm-exporter.yml

The label selector for that exporter is "NVIDIAGPU". e.g: If you want to deploy it:
```
kubectl label nodes <gpu-node-name> hardware-type=NVIDIAGPU
kubectl create -f services/dcgm-exporter.yml
```

**Comment by flx42** [comment]
cc @dholt who wrote the second dcgm exporter

**Comment by swiftdiaries** [comment]
Hey @RenaudWasTaken and @flx42 
Thanks for the pointers, I'll take a look at this.
Sidenote: DeepOps looks really cool!
