### ISSUE TITLE
PVC created but not added to volume list

### ISSUE THREAD

**Issue by clkao** [kubeflow/kubeflow#145]
Even though per-user PVC is allocated, they are not added to `jupyterHubConfigMap` nor `jupyterHubConfigMapWithVolumes`.

**Comment by jlewi** [comment]
Why do you expect them to be added to ConfigMap and ConfigMapWithVolumes? The PVC is autogenerated by I think the spawner so that each notebook gets a new persistent volume for any data.

jupyterHubConfigMapWithVolumes is about attaching extra additional volumes.
