### ISSUE TITLE
Does CentralUi need ClusterScope?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1450]
See #1213 

We'd like to be able to scope Kubeflow to a particular namespace to better support multi-tenant environments.

It looks like CentralUI is creating a ClusterRole right now. Do we need ClusterScope? Could we use a namespace scoped role?

/cc @swiftdiaries

**Comment by swiftdiaries** [comment]
If Kubeflow components (Argo, job-operator, jupyter) are deployed to same namespace then CentralUI doesn't need ClusterScope. A namespaced scope should be good enough.

**Comment by jlewi** [comment]
@swiftdiaries Until proven otherwise, I think we can assume central dashboard is in the same name space as the other components.

So lets replace the cluster scoped role with a namespace scoped role.

**Comment by swiftdiaries** [comment]
Sounds good 👍  Will get a PR in with the change.

**Comment by swiftdiaries** [comment]
Closing because a PR has already been submitted and merged for this.
/close
