### ISSUE TITLE
Can we scope SeldonCore to a namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1452]
See kubeflow/kubeflow#1213
and kubeflow/tf-operator#759

We'd like to be able to scope Kubeflow to a particular namespace to better support multi-tenant environments.

It looks like SeldonCore is using ClusterRoles; could we add options to our ksonnet package to scope it to a particular namespace and use namespace scoped Roles?

/cc @cliveseldon

**Comment by cliveseldon** [comment]
The ClusterRole is there to allow the Operator (ClusterManager) to create the CRD if it does not exist.
Its quite restrictive in just being able to created CRDs.
Other than that we use RoleBindings.

**Comment by jlewi** [comment]
@cliveseldon If the CRD already exists; do we still need the cluster role?

In particular, if we create the CRD when we deploy Kubeflow, then it will be created using the user permissions of the user deploying Kubeflow which is likely a cluster admin.

**Comment by cliveseldon** [comment]
Yes, if the CRD already exists we don't need the ClusterRole I think.
So, what does this imply? There is an initial setup in kubeflow core for
all CRDs that could be used?

**Comment by jlewi** [comment]
There's some debate about this but I prefer to have the CRD created by the k8s manifest (ksonnet package) rather than relying on the controller to create them.

**Comment by jlewi** [comment]
This is what we do for TFjob:
https://github.com/kubeflow/kubeflow/blob/679d284a3c52904c6841aded08b8f977fcc47fc5/kubeflow/core/tf-job-operator.libsonnet#L44

See kubeflow/tf-operator#710 for discussion about whether controller should create CRD or not.

**Comment by cliveseldon** [comment]
ok. Actually this is how it is done already. So maybe its a simple change
to simply not add the ClusterRole and ClusterRoleBinding! I'll look into it.

**Comment by jlewi** [comment]
Thanks. I think we are targeting this for 0.4. not 0.3.; i.e for 0.4 I think we want to have a good story for how to install deploy Kubeflow scoped to a namespace.

So not super urgent.

**Comment by chrisheecho** [comment]
@cliveseldon is this something that Seldon folks are interested in helping for 0.4 release?

**Comment by jlewi** [comment]
@cliveseldon Any movement on this? If not perhaps we can punt to 0.5?

**Comment by cliveseldon** [comment]
Will try to look over next few days.
