### ISSUE TITLE
Use a separate / dedicated repository for our ksonnet registry

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1454]
I think we should move our ksonnet packages into a separate repoistory e.g. kubeflow/packages or kubeflow/registry.

There's a couple reasons for doing this

1. We'd like to clearly separate the ksonnet packages from any actual code (e.g. bootstrapper, kfctl, etc...)
1. Users don't  need to pull the non ksonnet files in order to use the ksonnet packages
    * So we want to keep the repository small (no source code)
1. We want a name that makes it clear its our "packages" and not the components themselves (e.g. Katib).

What should we call this?

* kubeflow/registry
* kubeflow/packages

**Comment by lluunn** [comment]
But sometimes when we change the ksonnet, we need to change the test code as well. Then they will be in different repo?

**Comment by jlewi** [comment]
@lluunn That's a good question. I think it might be reasonable to include some of the test code in the repo (e.g the E2E test definitions themselves).

**Comment by chrisheecho** [comment]
/remove-priority p1
/priority p2

As no eng resource assigned. Need design doc perhaps or flesh out the thoughts here?

**Comment by jlewi** [comment]
obsolete since we are getting rid of ksonnet.
