### ISSUE TITLE
Spawner UI for GPU type selection

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#1457]
Currently we have no way to allow users to specify a particular class of GPU from the JupyterHub spawner. It appears we would need to [set the nodeSelector](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#clusters-containing-different-types-of-nvidia-gpus) in the notebook pod spec.

/assign

/cc @jlewi 
/cc @willingc 
/cc @yuvipanda

**Comment by jlewi** [comment]
@vishh Does K8s have plans to allow different resource types (e.g. nvidia.com/v100) corresponding to different GPU types? That seems preferable to using the node selector.  I did a quick github search in Kubernetes but couldn't find any issues.

**Comment by vishh** [comment]
@jlewi No, that's not the plan as of now. We want to enable heterogeneity without compromising portability. Selecting based on HW type is just one of the use cases. Imagine wanting to select HW based on available memory or some properties like special instructions for example. Node Selectors offer that flexibility for those who need it, while the simple resource type that exists today mostly works (presumably) for most users who do not have much heterogeneity in their cluster.

**Comment by vishh** [comment]
We are also working with Nvidia on standardizing Node label keys & values for GPUs. Until that is complete, I'd recommend plumbing just a generic serialized Node Selector json field for this use case.

**Comment by pdmack** [comment]
I won't be able to get to this for 0.4.0

**Comment by jlewi** [comment]
@ioandr @vkoukis FYI; something to think about in terms of future improvements to the jupyter spawner UI / web app in 0.5.
