### ISSUE TITLE
A small problem, Error validate kubeflow-core

### ISSUE THREAD

**Issue by asdfsx** [kubeflow/kubeflow#1462]
I try to deploy kubeflow-core v0.2.4 to minikube as described below. 
```
$ ks pkg install kubeflow/core@v0.2.4
$ ks generate kubeflow-core kubeflow-core
$ ks apply default -c kubeflow-core
```
The deploy successed.

but when I try to use `validate`, I got the following error
```
$ ks validate default 
...
INFO Validating deployments mykubeflow.ambassador
ERROR Error in deployments mykubeflow.ambassador: validation failure list:
spec.template.spec.containers.resources.limits.cpu in body must be of type string: "integer"
INFO Validating services mykubeflow.k8s-dashboard
...
ERROR validation failed
```

I solve this problem by modify `kubeflow/core/ambassador.libsonnet`，change the flowing line
```
cpu: 1,
```
to
```
cpu: "1",
```

**Comment by jlewi** [comment]
@asdfsx Did you every get this resolved? Sorry we left you hanging. You can always turn to kubeflow.slack.com for help if we're unresponsive on GitHub issues.

If you're still having trouble; I'd suggest trying 0.3 which we just released last week.

**Comment by jlewi** [comment]
@asdfsx hopefully things are working. If not please reopen this issue or file a new one describing the latest problems.
