### ISSUE TITLE
Is it possible to run kubeflow on federation cluster?

### ISSUE THREAD

**Issue by cruxyoung** [kubeflow/kubeflow#1463]
Just wondering if it is possible to run kubeflow on a federation cluster consisting of on-premise cluster and cloud cluster?

**Comment by jlewi** [comment]
I don't see why not. It would be great to try it out and report any issues you run into.

Do you have a specific use case? e.g. train in the cloud serve on prem?

**Comment by cruxyoung** [comment]
I tried to install kubeflow on a federation deployed by kubefed. The federation cluster consists of a GCE cluster and a AWS cluster deployed by kops. 

But then I got this error:
![image](https://user-images.githubusercontent.com/14368415/45133626-accdfb00-b1d9-11e8-8e8d-88fde45b6b0d.png)

It seems that the apiversion is too old.

Then I do:
![image](https://user-images.githubusercontent.com/14368415/45133658-d5ee8b80-b1d9-11e8-806e-d6168ad9237f.png)

The Kubernetes version used by kubefed is 1.9.0/alpha3. Is it because ClusterRoleBinding is not supported by this version yet?

**Comment by jlewi** [comment]
I'm pretty sure ClusterRoleBinding was introduced before K8s 1.9. I see it in the docs for 1.7
https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#clusterrolebinding-v1beta1-rbac

Do your clusters have RBAC enabled? If RBAC isn't enabled that might explain why ClusterRoleBinding isn't defined.
