### ISSUE TITLE
Katib deployment does not have hyperband included

### ISSUE THREAD

**Issue by 372046933** [kubeflow/kubeflow#1464]
If I follow the instruction in https://master.kubeflow.org/docs/guides/components/hyperparameter/, Katib suggestion algorithm does not include hyperband. Which differs from https://github.com/kubeflow/katib/blob/master/examples/MinikubeDemo/deploy.sh on https://github.com/kubeflow/katib/blob/master/examples/MinikubeDemo.md

**Comment by 372046933** [comment]
Currently, only https://github.com/kubeflow/katib/blob/master/scripts/deploy.sh works. But it uses `katib` namespcace instead of `kubeflow` on kubeflow.org's guide

**Comment by YujiOshima** [comment]
The StudyJob Controller and metrics collector are not included in `gcr.io/kubeflow-images-public` registry.
We will fix it by https://github.com/kubeflow/kubeflow/pull/1400 .
Then I will update katib template in kubeflow repo.
