### ISSUE TITLE
Document Requirements/Best Practices for Operators

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1471]
We should create a document to capture features/requirements/best practices that we'd like all our operators to support so that we have consistency

Here's some initial suggestions

1. Operators should be level based 
1. Operators should have certain common conditions (e.g. Succeeded and Failed)
1. If the Job Spec is invalid this should be reported in the status (see kubeflow/tf-operator#815)
1. Operator logs should be in json format with a field containing the job in "namespace.name" format
    * see https://github.com/kubeflow/tf-operator/blob/master/pkg/logger/logger.go
1. Support a Job TTL (kubeflow/tf-operator#718)
1. It should be possible to scope the operator to one or more namespaces
    * See kubeflow/tf-operator#759
1. CRD should be defined as its own K8s resource (e.g. ksonnet package) and not installed by default
    by operator
     * Operator could check it exists and maybe create the CRD
     * See kubeflow/tf-operator#710

Open questions

* Should we define common events that the operators should emit?
* Should we export common metrics to prometheus?
* E2E testing?
* Support for gang scheduling / kube arbitrator?

/cc @richardsliu @gaocegege @ScorpioCPH @everpeace @johnugeorge @rongou

**Comment by rongou** [comment]
I haven't been keeping track, but what happened to the effort to unify all the training operators? It's probably much easier to ensure consistency if it's a single code base that supports the different training jobs.

**Comment by johnugeorge** [comment]
Yes, I am trying to keep the behavior consistent across operators.  Currently, except 3) pytorch repo is at par with tf. 

btwn for 4) logger package is shared across the operators.

**Comment by rongou** [comment]
I guess what I'm asking is, does it make sense to have a single operator (for example, `TrainingOperator`) that understands tensorflow, pytorch, parameter servers, horovod/mpi, etc. Or would that make it too complicated and hard to use?

**Comment by gaocegege** [comment]
@rongou 

We have a proposal for this idea: https://docs.google.com/document/d/1mSJaLtBgR04dvOnroADh4x8wNV1o-oPpf8CnmOPbNks/edit#heading=h.2fkzp8exzv8x

While we do not apply it.

**Comment by chrisheecho** [comment]
Eng: Want, PM:Need

**Comment by jlewi** [comment]
@chrisheecho @carmine Should we bump this down to P2? For 0.4. I think the focus is on getting TFJob/PyTorch operators to beta and I don't think that's blocked on this issue.
