### ISSUE TITLE
Document maturity / support of various Kubeflow components

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1472]
The number of components in Kubeflow is growing rapidly.

* Arena
* Argo
* Chainer
* Central UI
* Fairing
* Katib
* KubeBench
* JupyterHub
* 2 MPI operators
* Seldon
* TF Serving
* TF Training
   * TFJobs UI

Not all of these components have the same level of maturity and commitment

With 0.4.0 we should try to come up with a way to clearly communicate this to users. In particular, I think we need to figure out how to distinguish components which we will continue to support in subsequent releases (this doesn't necessarily mean in backwards compatible way) vs. experimental components that might be removed due to lack of ongoing investment.

**Comment by chrisheecho** [comment]
Eng:Want PM:Need

**Comment by jlewi** [comment]
I'm punting this to 0.5.

This is going to be blocked on some other discussions and I don't think there is sufficient traction to get anything done in time for 0.4

**Comment by carmine** [comment]
Agreed.
