### ISSUE TITLE
simplify tensorboard as separate aws, gcp prototypes

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1477]
the tensorboard.{libsonnet, jsonnet} files will be used for this

1. Show how the use of k.libsonnet simplifies creation and modification of manifests in tensorboard.{libsonnet, jsonnet}
2. Show the pattern exposed in k.libsonnet

**Comment by jlewi** [comment]
I think we will also eventually want to move tensorboard out of the core package and into a separate package; perhaps a single package for TensorFlow? Not sure whether it makes sense to do that as part of this issue. There are a bunch of issues related to the ksonnet organization.

Bunch of issues related to ksonnet structure.
See also #564 Simplify TFJob spec (by getting rid of .libsonnet file)
See also #376 patterns for creating ksonnet prototypes
See also #42 split up core package

**Comment by jlewi** [comment]
Should we change the title to reflect that issue is just about TensorBoard?
