### ISSUE TITLE
deploy.sh of v0.2.5 failed to deploy katib

### ISSUE THREAD

**Issue by 372046933** [kubeflow/kubeflow#1478]
`ks generate katib katib`
`ks show default -c katib`
Below are the errors of previous commands

ERROR find objects: RUNTIME ERROR: Field does not exist: modeldbDatabaseImage
        /home/tx/Downloads/kubeflow_ks_app/vendor/kubeflow/katib/modeldb.libsonnet:132:24-51    object <anonymous>
 

It can be fixed by adding `modeldbDatabaseImage: "mongo:3.4"` to  `components/params.libsonnet`

**Comment by jlewi** [comment]
Thanks for the bug report.

Looks like this is fixed on master:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/prototypes/all.jsonnet

Do folks thinks this worth a patch release?

**Comment by 372046933** [comment]
Great, thanks a million.
