### ISSUE TITLE
New image release for pytorch operator

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/kubeflow#1479]
With v1alpha2 changes, Pytorch operator needs a new image release.  build_image.sh is already updated(https://github.com/kubeflow/pytorch-operator/blob/master/build_image.sh#L26)

Is nightly image release happening for pytorch-operator?
https://github.com/kubeflow/kubeflow/tree/master/releasing/pytorch-operator

/assign @ankushagarwal @kunmingg

**Comment by johnugeorge** [comment]
Can you help? I would need a image release inorder to make v1alpha2 as the default pytorch job version?

**Comment by ankushagarwal** [comment]
I'll get to this today.

**Comment by ankushagarwal** [comment]
Created 
gcr.io/kubeflow-images-public/pytorch-operator:84d07df
gcr.io/kubeflow-images-public/pytorch-dist-sendrecv-test:1.0
gcr.io/kubeflow-images-public/pytorch-dist-mnist_test:1.0
