### ISSUE TITLE
No prototype names matched 'kubeflow-core'

### ISSUE THREAD

**Issue by sucanthudu** [kubeflow/kubeflow#1492]
When i tried to run this
ks generate kubeflow-core kubeflow-core i got 
ERROR No prototype names matched 'kubeflow-core'
Please help me out to solve this issue

**Comment by pdmack** [comment]
[These](https://v0-2.kubeflow.org/docs/started/getting-started/#quick-start) are the latest instructions for the 0.2 series (not `master`). Please remove any existing kubeflow artifacts before retrying:
`rm -fr kubeflow_ks_app  kubeflow_repo`
