### ISSUE TITLE
Doesn't work with k8s 1.10

### ISSUE THREAD

**Issue by techgnosis** [kubeflow/kubeflow#1518]
I'm running k8s on GKE. When I install Kubeflow 0.2.5 on 1.9.7 it works great. When I try to install Kubeflow 0.2.5 on 1.10.x the Envoy containers get in a crash loop looking for /etc/envoy/envoy-config.json.

**Comment by kunmingg** [comment]
You can try deploy using latest master, there's a problem in Kubeflow 0.2.5 with k8s 1.10.x

**Comment by jlewi** [comment]
This should be fixed with 0.3
