### ISSUE TITLE
migrate bootstraper from glide to dep 

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1520]
I am hitting some error when building locally with `glide install -v`
https://github.com/Masterminds/glide/issues/975

I will try to migrate to dep.
Other kubeflow repos also use dep https://github.com/kubeflow/tf-operator/issues/556

cc @kunmingg

**Comment by lluunn** [comment]
My `dep init` never finished.
similar to https://github.com/golang/dep/issues/1991

**Comment by r2d4** [comment]
The dockerfiles look like they will need to change also

**Comment by kunmingg** [comment]
Yeah can instead generate name from hash(Gopkg.lock)

**Comment by kunmingg** [comment]
Now we use go modules
