### ISSUE TITLE
Nodeport not accesible

### ISSUE THREAD

**Issue by PhilippeBarb** [kubeflow/kubeflow#1525]
Hello and sorry for my bad english :(

I create a deployment with yaml file 

`---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: nginx
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
         - name: nginx
           image: nginx
           ports:
             - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx 
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    name: nginx      `

I can made a curl on pod's ip but not with ip_cluster:30080

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

In advance very thanks

Philippe

**Comment by PhilippeBarb** [comment]
Other info 

 microk8s.kubectl get services
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
nginx       NodePort    10.152.183.221   <none>        3000:30500/TCP   2h

 microk8s.kubectl get pods

 kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
nginx-578687d985-cxcjw   1/1       Running   0          2h
nginx-578687d985-tknf5   1/1       Running   0          2h

**Comment by kunmingg** [comment]
Nodeport is accessible from any node within cluster.
