### ISSUE TITLE
Directory ${KFAPP} already exists

### ISSUE THREAD

**Issue by shimpel** [kubeflow/kubeflow#1530]
Hi,

I´m tried to install kubeflow according to your guide:
https://www.kubeflow.org/docs/started/getting-started/

If I run ${KUBEFLOW_REPO}/scripts/kfctl.sh init ${KFAPP} --platform none
the script finishes with exit code 1 with the error message_
Directory /etc/kubeflow already exists.

The directory did not exist before I ran the script.
The scripts creates the directory /etc/kubeflow but there is only env.sh in it.

**Comment by andreyvelich** [comment]
Hi,

Can you show me your ${KFAPP} variable?
After creating folder with env.sh file you need to run this commands from the folder with env.sh file.
${KUBEFLOW_REPO}/scripts/kfctl.sh generate k8s
${KUBEFLOW_REPO}/scripts/kfctl.sh apply k8s

**Comment by shimpel** [comment]
Hi,

I entered an absolut path for the directory because I missunderstood the manual:
"${KFAPP} The name of a directory to store your configs. "
I entered /etc/kubeflow for ${KFAPP}.
If I just enter the name of the new folder "kubeflow" everthing is working.

**Comment by Niuxiaotong** [comment]
form:https://www.kubeflow.org/docs/started/getting-started/
${KFAPP} the name for the kubeflow deployment (shouldn’t be a path). A directory with the name will be created under pwd when you run init, and that is where kubeflow configurations will be stored.
The ksonnet app will be created in the directory ${KFAPP}/ks_app
--
[root@k8s01 ~]# kubeflowsrc/scripts/kfctl.sh init kfapp --platform none
[root@k8s01 ~]# ls
anaconda-ks.cfg  bin  kfapp  kubeadm.yaml  kubeflowsrc
--
commod will create a directory named kfapp that in your commod.
