### ISSUE TITLE
Explore usage of the spark-operator within kubeflow

### ISSUE THREAD

**Issue by foxish** [kubeflow/kubeflow#155]
This is the work captured under https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.
The advantage of using and deploying this operator is the same k8s-style declarative semantics, wrapped over Spark.
I'm wondering if we could also make it more generic - to be able to launch spark jobs against any cluster and not just k8s.

cc/ @liyinan926

**Comment by foxish** [comment]
The goal is to supply users with a basic operator to use spark/k8s, and a couple of simple examples of running SparkML for real use-cases.

**Comment by mattf** [comment]
cc @tmckayus

**Comment by foxish** [comment]
cc/ @holdenk @texasmichelle who are exploring this item as well.

**Comment by holdenk** [comment]
I think this could be really great if we got some serving logic integrated as well. I'll do some more poking on this in my own branch of the other repo :)

**Comment by liyinan926** [comment]
@holdenk @texasmichelle any update or plan on this?

**Comment by TheJaySmith** [comment]
Howdy, just wanted to touch base and see if we have this on the roadmap

**Comment by jayunit100** [comment]
also curious about this, and specifically wether spark (or other ETL/large data set tools for that matter) are going to be major parts of what kubeflow packages.... So far i've always seen kubeflow as more of a data science platform, rather then a core data engineering one.

**Comment by holdenk** [comment]
So I think Datascientists and ML Engineers still need tools to do large-scale data prep, so while Spark can indeed be used for ML on it's own -- I imagine it will often be used as part of a pipeline along with other ML tools.

**Comment by holdenk** [comment]
Similar to the comments expressed in https://github.com/kubeflow/kubeflow/issues/2381#issuecomment-460903272

**Comment by Jeffwan** [comment]
For most of data scientist, their entrypoint is Jupyter Notebook or TFJob in kubeflow, for data engineers, their entrypoint will be spark-job.

**Comment by kyprifog** [comment]
I find this discussion intriguing.  I guess the question I would ask, is if kubeflow isn't the tool for this (which I can see arguments for why thats the case), then what is something like that which can be used that still deploys and manages spark jobs on kubernetes and allows for easy interoperation with kubeflow.  Does the spark-on-k8s operator sufficiently fill this niche?

**Comment by skonto** [comment]
> I'm wondering if we could also make it more generic - to be able to launch spark jobs against any cluster and not just k8s.

Coming a bit late to the discussion, if that path is followed then this become more like a generic operator but with that comes a extra complexity. I think if you remove all the k8s specific deps there is not much left...

**Comment by talgos1** [comment]
Hi, any updates with this one? do we have examples of running spark-operator as KFP operator ?

**Comment by Talador12** [comment]
There is a spark operator in the contributor section of the manifests repo, but this should become more of a common approach
https://github.com/kubeflow/manifests/tree/master/contrib/spark/spark-operator
