### ISSUE TITLE
"Patching IAM bindings" halt during deployment.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1559]
log tail:

{"filename":"app/ksServer.go:805","level":"info","msg":"Deployment is done","time":"2018-09-18T23:36:34Z"}
{"filename":"app/ksServer.go:817","level":"info","msg":"Patching IAM bindings...","time":"2018-09-18T23:36:34Z"}

**Comment by kunmingg** [comment]
related: https://github.com/kubeflow/kubeflow/pull/1550

**Comment by lluunn** [comment]
"Cannot get current policy: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\nMore details:\nReason: authError, Message: Request had invalid authentication credentials.\n","time":"2018-09-19T00:05:48Z
