### ISSUE TITLE
Change the tfbatch predict to support Dataflow runner on GCP

### ISSUE THREAD

**Issue by yixinshi** [kubeflow/kubeflow#1560]
Currently it only supports local runner.

**Comment by jlewi** [comment]
@yixinshi Can we get this fixed this week so we can include it in 0.3?

**Comment by jlewi** [comment]
@yixinshi Any update on this?

What is the work needed to support the Dataflow runner?

**Comment by jlewi** [comment]
Moving to 0.4.0 since we are finalizing 0.3.
