### ISSUE TITLE
Deploy kfctl.sh apply k8s : Service "ambassador" is invalid  ?

### ISSUE THREAD

**Issue by yylin1** [kubeflow/kubeflow#1566]
I am trying to execute the deployment kubeflow script in my kubernetes GPU Cluster, but an error occurred in the last step.

## set up and deploy Kubeflow
```
${KUBEFLOW_REPO}/scripts/kfctl.sh init ${KFAPP} --platform none
cd ${KFAPP}
${KUBEFLOW_REPO}/scripts/kfctl.sh generate k8s
${KUBEFLOW_REPO}/scripts/kfctl.sh apply k8s
```

> Previously in my Cluster environment, I have previously implemented kubeflow v0.2.2. Is it likely to be affected by the environment?

Problem : 

```bash=
$ {KUBEFLOW_REPO}/scripts/kfctl.sh apply k8s
·
·
kubernetesversion: v1.11.2
path: default
destination:
  server: https://1xx.1xx.xx.xx:8443
  namespace: kubeflow
targets: []
libraries: {}'
+ RESULT=0
+ set -e
+ '[' 0 -eq 0 ']'
+ echo environment default already exists
environment default already exists
+ ks apply default -c ambassador
ERROR handle object: patching object from cluster: merging object with existing state: Service "ambassador" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

```

**Comment by yylin1** [comment]
I try kubeflow v0.2.5 Deploy 

## Quick start
```
export KUBEFLOW_VERSION=0.2.5
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/deploy.sh | bash
````

## Error message 
What's problem in my environment?
```
ERROR initializing helm HTTP client: normalizing Helm repository URL: "" is an invalid scheme for Helm repository
```

**Comment by jlewi** [comment]
Which version of ksonnet are you using?

```
ERROR initializing helm HTTP client: normalizing Helm repository URL: "" is an invalid scheme for Helm repository
```

Kubeflow doesn't use Helm so I'm not sure where this is coming from. The only thing I can think of is that    this is a ksonnet issue because its trying and failing to setup its support for using helm.

Can you try ksonnet 0.11 if you aren't already using that?

**Comment by yylin1** [comment]
Hi @jlewi   
my environment list : 
```
$ ks version                                                                                 
ksonnet version: 0.12.0-rc1
jsonnet version: v0.10.0
client-go version:
```

### First Proble : master 
Deploy I am try ` KUBEFLOW_TAG=master`
```
ERROR handle object: patching object from cluster: merging object with existing state: Service "ambassador" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

Second Problem : v0.2 
---
I try to use kubeflow Deploy v0.2 script 
```
ERROR initializing helm HTTP client: normalizing Helm repository URL: "" is an invalid scheme for Helm repository
```
> ksonnet version: 0.12.0-rc1

**Comment by yylin1** [comment]
I try again, Deploy kubeflow  v0.2.2 is OK.

```
export KUBEFLOW_VERSION=0.2.2
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/deploy.sh | bash
```

kubeflow v0.2.5 have Helm repository problem?

**Comment by jlewi** [comment]
Any particular reason you are using 0.12-rc1? I think there is a 0.12 version.

**Comment by yylin1** [comment]
@jlewi 
It is recommended to use v0.11 or higher in kubeflow = master
Maybe ksonnest uploads 0.12-rc1 in the environment, try to trun to v0.12 version ?

**Comment by jlewi** [comment]
Another user is reporting hitting this on slack.
User reports 

```
ks registry list
```
returns no registries.

So maybe the issue here is that the ks registry add command didn't succeed and that causes problems.

Can you see if `ks registry list` returns any registries; if not can you try adding one?

**Comment by yylin1** [comment]
Sorry @jlewi  reply late for you,

ks version has not changed v0.12-rc1
I don't know why, try again and Deploy successfully in these days.
My GPU Cluster & minikube try is okay. 

script 
```
export KUBEFLOW_VERSION=0.2.5
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/deploy.sh | bash
```
info.
```
$ ks registry list
NAME      OVERRIDE PROTOCOL URI
====      ======== ======== ===
incubator          github   github.com/ksonnet/parts/tree/master/incubator
kubeflow           fs       /Users/yylin/kubeflow/ha-kubeflow/kubeflow_repo/kubeflow
```

Convenient for users script kubeflow master &  v0.2 which suggest deploy now ?

**Comment by surabhikannan** [comment]
still facing this issue in 
_ks version_
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

_kubectl version_
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}


_kubeflow version_ v0.3.0

**Comment by nikan1996** [comment]
Any solution here?

**Comment by nikan1996** [comment]
I get the same problem
**ks version**
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**kubeflow version** 
v0.3.0

**Comment by solovyevt** [comment]
Double that, experiencing the same issue.

**Comment by yylin1** [comment]
@jomach 
Check the environment ksonnect version. And clean old kubeflow data, restart deploy kubeflow. 

@solovyevt 
Try clean and remove kubeflow, restart kubeflow.

I'm try minikube is not problem.
