### ISSUE TITLE
E2E Solution for GitHub Issue Summarization On Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#157]
@hamelsmu published a great [blog post](https://hackernoon.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8) about using sequence to sequence models to summarize GitHub issues.

It would be great to turn this into an E2E solution using Kubeflow that highlights the benefit of using Kubeflow and K8s for data science.

There are lots of reasons why I think this blog post would make for a fantastic E2E solution

   * Text summarization has a lot of applications 
   * It uses GitHub data which is a very rich dataset 
   * Training and preprocessing take enough time (~30 minutes and ~1 hour respectively) that I think it makes sense to run these as K8s jobs but not so much time to be a barrier.

Here's a stab at what an E2E solution might look like
   * Entrypoint would be a notebook (based on the [one in the blogpost](https://github.com/hamelsmu/Seq2Seq_Tutorial/blob/master/notebooks/Tutorial.ipynb)). 
   * Notebook would walk through the various steps but instead of (or in addition) to running code directly in the notebook 

I think there's quite a bit of work to be done but I think we can split this into tasks

- [ ] Setup a shared Kubeflow cluster and Cloud project for dev team to use
- [ ] Create a Docker image to be used with Jupyter with all dependencies installed
- [ ] Refactor the notebook into libraries with suitable main functions so that relevant steps (preprocessing and training) steps can be invoked in K8s Jobs and TFJobs
- [ ] Build docker image (using [Argo](https://applatix.com/open-source/argo/) to be used by TFJob, TFServing, etc...
- [ ] Create a model server using TFServing
- [ ] Create a web app to serve as the front end
- [ ] Create ksonnet component for deploy the model and web app

**Comment by hamelsmu** [comment]
This is an excellent idea!  I assume you will have to build the Docker Container from scratch, but if you can just layer on top of an existing one I am hosting a Docker Image on DockerHub with all the dependencies for the seq2seq tutorial, which is [here](https://hub.docker.com/r/hamelsmu/seq2seq_tutorial/).

**Comment by yupbank** [comment]
add a TFServing CRD ? since right now tensorflow/serving can serve multiple models with multiple version.  Replica  tensorflow/serving containers is kind of brutal force..

**Comment by jlewi** [comment]
@yupbank Do you want to open up a separate issue about a TFServing CRD. Do we need a TFServing CRD for this issue?

**Comment by yupbank** [comment]
yeah... i'll do it..

**Comment by texasmichelle** [comment]
@hamelsmu Just to be clear - are you ok with us using the code from your blog post as-is for this?

**Comment by hamelsmu** [comment]
Yes please go for it!  Everything is open source and you can do anything
you want with it!

**Comment by jlewi** [comment]
Thanks @hamelsmu 

@ankushagarwal is working on pieces of this.

@vicaire also has an Argo workflow to do some pieces.

@texasmichelle Thanks for opening up the all individual issues. Do you want to close this issue and open up a copy of it in kubeflow/examples?

**Comment by texasmichelle** [comment]
Created [kubeflow/examples #14](https://github.com/kubeflow/examples/issues/14), so this one can be closed.

**Comment by jlewi** [comment]
Duplicate of kubeflow/examples#14
