### ISSUE TITLE
central dashboard image build workflow doesn't work

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1575]
Building the central dashboard images in our Argo release workflow is taking over 3 hours.

We experienced similar issues with our Jupyter image builds (#1132) and the conjecture it was related to having insufficient resources.

Here's a graph of the resource usage (neither requests or limits were set for the pod)
![cpuusage](https://user-images.githubusercontent.com/777219/45769533-c23d1f00-bbf4-11e8-966e-411480eab708.png)

CPU usage for both containers (main and dind) is pretty small. Memoray usage is large ~11GB on the main container.

Logs for the main container don't give any indication of progress

```
+ sleep 3
+ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
+ docker build -f /mnt/test-data-volume/kubeflow-presubmit-dashboard-release-1565-e1722f0-3384-48a5/src/kubeflow/kubeflow/components/centraldashboard/Dockerfile -t gcr.io/kubeflow-ci/centraldashboard:latest .
```

dind container logs are similarly unhelpful

```
time="2018-09-19T14:01:34.414878302Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
time="2018-09-19T14:01:34.418024269Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2018-09-19T14:01:34.664084373Z" level=info msg="libcontainerd: new containerd process, pid: 23"
time="2018-09-19T14:01:35.782073278Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2018-09-19T14:01:35.782854046Z" level=info msg="Loading containers: start."
time="2018-09-19T14:01:35.792158060Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nip: can't find device 'br_netfilter'\nbr_netfilter           24576  0 \nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
time="2018-09-19T14:01:35.797057046Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE\nnf_nat_ipv4            16384  1 iptable_nat\nnf_nat                 24576  3 xt_nat,nf_nat_masquerade_ipv4,nf_nat_ipv4\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
time="2018-09-19T14:01:35.801947735Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
time="2018-09-19T14:01:35.947442620Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2018-09-19T14:01:36.017184952Z" level=info msg="Loading containers: done."
time="2018-09-19T14:01:36.330135463Z" level=info msg="Docker daemon" commit=f4ffd25 graphdriver(s)=overlay2 version=17.10.0-ce
time="2018-09-19T14:01:36.330374735Z" level=info msg="Daemon has completed initialization"
time="2018-09-19T14:01:36.347356924Z" level=info msg="API listen on [::]:2375"
time="2018-09-19T14:01:36.347353837Z" level=info msg="API listen on /var/run/docker.sock"
```

See also:
#1132 Building Jupyter images takes over 4 hours
#1574 Problems with image auto release

**Comment by jlewi** [comment]
In #1565 I added the JupyterHub docker image build workflow so we could have something to compare against. Here's a running workflow
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-notebook-release-1565-e3ff9af-3394-568c?tab=workflow&nodeId=kubeflow-presubmit-tf-notebook-release-1565-e3ff9af-3394-568c-1437075175

We clearly see log output (e.g. pulling docker base image.) So something else is going on with the centraldashboard image.

**Comment by jlewi** [comment]
It looks like centraldashboard is using multistage Docker build but Jupyter images doesn't use mult-stage build.

I wonder if that's a problem?

One workaround might be to use GCB rather than calling docker build.

We could probably do that just by changing the build script to one like this.
https://github.com/kubeflow/chainer-operator/blob/master/scripts/build.sh

**Comment by swiftdiaries** [comment]
Yes, I added in a multi-stage build to reduce the size of the image. Cool, I'll change the build_image.sh  so that it uses GCB.

**Comment by jlewi** [comment]
This fixed:
sample postsubmit run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/744
