### ISSUE TITLE
PyTorch and TFJob v1beta1 API

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1584]
In 0.4.0 the PyTorch and TFJob API's should be beta quality with an eye towards 1.0 in the spring.

There is an open issue kubeflow/tf-operator#742 to do an API review with Kubernetes.

**Comment by jlewi** [comment]
@richardsliu What are the next steps here?

/assign @richardsliu

**Comment by jlewi** [comment]
From @richardsliu 


> I sent out the initial version of the v1beta1 APIs, would like to get some feedback from Johnu. 

> After that, the next steps are:
1. Get an API review from k8s team,
2. Implement the v1beta1 APIs (for TF and Pytorch),
3. Implement the v1beta1 controllers (TF and Pytorch) which uses the new APIs,
4. Create some sort of script to migrate users from v1alpha2 to v1beta1.

@richardsliu Should we split this up into finer grained issues reflecting the above?

**Comment by jlewi** [comment]
Talked to @richardsliu 
So TF is done.
@johnugeorge working on PyTorch.

**Comment by jlewi** [comment]
For PyTorch the work is

1. Update the controller to use v1beta1
1. Update the ksonnet package.

**Comment by johnugeorge** [comment]
APIS are merged.  Working on the other items now. 

I will raise PR soon

**Comment by jlewi** [comment]
Thanks @johnugeorge

**Comment by richardsliu** [comment]
@johnugeorge Is there anything left to do for Pytorch?

**Comment by johnugeorge** [comment]
Only thing left is to create and add new pytorch image to ksonet.  I will add it soon.   Rest all items are completed

**Comment by johnugeorge** [comment]
@jlewi All changes are merged. We can close this now.

**Comment by jlewi** [comment]
Woo Hoo!
Thanks @johnugeorge
