### ISSUE TITLE
deploying kubeflow with bootstrapper failed

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/kubeflow#1586]
The result of my deployment is different from the result of the website https://www.kubeflow.org/docs/started/getting-started-minikube/.

when i enter commands:
 kubectl -n kubeflow get svc

Terminal display:
No resources found

**Comment by kunmingg** [comment]
minikube?
Master branch is less stable, can you try with 0.2 release branch? 
https://v0-2.kubeflow.org/docs/started/getting-started-minikube/

**Comment by jlewi** [comment]
If you're using 0.2 I would suggest not using the bootstrapper;

1. Setup minikube following the instructions on that page
1. Once minikube is setup follow the [generic instructions](https://v0-2.kubeflow.org/docs/started/getting-started/) for deploying Kubeflow  

The bootstrapper approach had some architectural issues and we are moving away from it in 0.3.

See #1459 
See #1430 

Looks like we need to get the docs updated to reflect this.
