### ISSUE TITLE
Envoy unable to read config

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1588]
Saw error message from envoy pod:
external/envoy/source/server/server.cc:71] error initializing configuration '/etc/envoy/envoy-config.json': unable to read file: /etc/envoy/envoy-config.json

@abhi-g

**Comment by jlewi** [comment]
@kunmingg What was the context in which this error appeared? Did envoy end up recovering?

Which envoy were you looking at? Is this the Ambassador envoy instance or the envoy we use to do JWT checking for IAP?

**Comment by kunmingg** [comment]
https://github.com/kubeflow/kubeflow/pull/1595
This one fix it.
Root cause is IAM leftovers from previous deployment.

**Comment by kunmingg** [comment]
@connected-bsamadi 
There are one more issue can could cause it:
https://github.com/kubeflow/kubeflow/issues/1807

Can you retry with latest master?
Will include fix in v0.3.2
