### ISSUE TITLE
ksonnet component for Seldon.io deployment

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#159]
We'd like to add a ksonnet component for Seldon.io's [CRD for model prediction](https://github.com/SeldonIO/seldon-core/blob/master/docs/crd/readme.md). 

This would enable Kubeflow users to serve all kinds of [models](https://github.com/SeldonIO/seldon-core).

The Deployment is way more powerful then that though since it allows prediction to be described as a graph of microservices.

To get started we need a componet like the one for [TFJob](https://github.com/google/kubeflow/blob/master/kubeflow/core/tf-job.libsonnet) to deploy the Seldon.io CRD.

An open question is whether we should also deploy the Seldon API front end which does oauth or we should rely on the generic reverse proxy solution we are building in Kubeflow (#11)

It would be great if after deploying Kubeflow, users could just load up the [Seldon notebooks](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/kubectl_demo_gcp.ipynb) and run them.

@cliveseldon @ahousley

**Comment by cliveseldon** [comment]
This sounds good. I suggest we initially try to rely on the consistent reverse proxy solution in Kubeflow so everything is consistent and deploy just the core operator for the Seldon deployment CRD.

**Comment by cliveseldon** [comment]
We have a [Jupyter Notebook](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/ksonnet_ambassador_minikube.ipynb) that uses a ksonnet registry to deploy seldon-core along with examples showing endpoints exposed via Ambassador (rather than our current API server)

Be great to get feedback and decide on next steps. Creating a notebook example that uses your Ambassador setup would be good. Would this type of thing go into kubeflow-examples repo?

@jlewi @aronchick

**Comment by jlewi** [comment]
This is fantastic. I'd love to see this turned into an E2E example running on Kubeflow 

Here's what I think would be great to see

1. User deploys Kubeflow which includes 
      * SeldonCore
      * Ambassador
      * A secure identity aware proxy (e.g. IAP on GCP or oauth2_proxy on non GCP)
2. User runs one of our example notebook that trains a model (xgboost or scikits)
3. User builds the container for deployment using Argo to run docker build on the cluster
4. User deploys that model using Seldon (following the notebook named above)
      * This should setup a route the reverse proxy
5. User can send predictions from either outside or inside

@puneith Has started working on an xgboost example #163 so perhaps we could use that?

@dynamicwebpaige Do you have ideas for a scikits model?

/cc @puneith @dynamicwebpaige

**Comment by cliveseldon** [comment]
Sounds like a good plan. Need to understand how Argo could wrap the runtime inference part following the [seldon wrappers](https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/readme.md). We provide a example docker image to wrap any python model.

**Comment by dynamicwebpaige** [comment]
Agreed with Jeremy - it would be great to have an E2E KubeFlow example, using scikit-learn.

A methodology I've seen recommended for deploying such models: pickle it with a schema.json and a score.py (that includes an init and a run function), and package all that up as a container that you can call as a web service. 

This approach is quite slow, though; and pickle-ing models isn't a Python best practice -- so would definitely be open to alternative suggestions, if y'all've got 'em!

Ref: https://docs.microsoft.com/en-us/azure/machine-learning/preview/tutorial-classifying-iris-part-3

**Comment by cliveseldon** [comment]
We have created an initial end-to-end example at https://github.com/SeldonIO/kubeflow-seldon-example which illustrates training on kubeflow and deployment on seldon-core with Argo workflows for a Tensorflow and scikit-learn model. A notebook illustrates REST and gRPC prediction as well as modifying the deployment to run A-B tests as well as Multi-armed bandits.

Can discuss how this can be included in kubeflow examples for further iteration.

**Comment by jlewi** [comment]
I think it would be great if
1. We could add the ksonnet configs to deploy Seldon core to kubeflow/kubeflow - 
    * This prevents users from having to do a 2nd registry add command
    * We can discuss whether it makes sense to add it to the core Kubeflow package and include it by default or make it a separate package
    * The best way to organize the registry is still very much an open question
      https://github.com/kubeflow/kubeflow/issues/106

For the example repo we have a couple options
1. we could put it in kubeflow/examples - 
    * The current thinking is to have all E2E examples for easier discoverability by users in one repo
       and also to facilitate maintenance e.g. test infrastructure
    * Each example will correspond to its own top level directory 

2. Since its already in its own repository, I'd be fine having it in a separate repository in Kubeflow and we can decide over time whether we like that better or worse than 1 repo for all examples.

3. Leaving it SeldonIO is another option.
