### ISSUE TITLE
Bootstrap cmd app doesn't get a token that is used in the ksServer.go

### ISSUE THREAD

**Issue by monkey3199** [kubeflow/kubeflow#1590]
[ksServer.go:650](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/ksServer.go)
[server.go:256](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/server.go)

In order to run ksServer.Apply(ctx context.Context, req ApplyRequest) in ksServer.go, 'req' must have Token. But func processFile() in server.go doesn't allocate the value of token. As the request doesn't have token, func Apply in ksServer.go must drop the request with some log("No token specified in request; dropping request.")

How can I put the token in the bootstrapper?

**Comment by jlewi** [comment]
Can you explain what it is you are trying to do using the bootstrapper/ksServer?

At this point this is largely an internal library and we aren't expecting it to be consumed directly by users?

/cc @kunmingg

**Comment by kunmingg** [comment]
@monkey3199 
```ksServer.go``` expect user come from 2 ways:
1. from web app, where user will log in and make request with their token.
2. from cmd line, and user also have gcloud sdk installed so can generate the token they need to make request.

Auth token will only generated per request, it shouldn't exist in a file which would be a security concern.

**Comment by monkey3199** [comment]
According to bootstrap quickstart(https://github.com/kubeflow/kubeflow/tree/master/bootstrap), I launched the bootstrapper.
`kubectl create -f bootstrapper.yaml`
Bootstrapper executed function processFile in server.go. In this function, it called ksServer.Apply without any token in request.
`if opt.Apply {
		req := ApplyRequest{
			Name:        appName,
			Environment: "default",
			Components:  make([]string, 0),
		}

		for _, component := range appConfigFile.App.Components {
			req.Components = append(req.Components, component.Name)
		}

		if err := ksServer.Apply(ctx, req); err != nil {
			log.Errorf("Failed to apply app %v; Error: %v", appName, err)
			return err
		}
	}`
And then, the request dropped in ksServer.go like below.
`if token == "" {
		log.Infof("No token specified in request; dropping request.")
	}`

@kunmingg Is this way different from your second option using cmd line that you mentioned?
