### ISSUE TITLE
Kubebench-job default param mainJobConfig points to a wrong path

### ISSUE THREAD

**Issue by xyhuang** [kubeflow/kubeflow#1596]
the example config should be located at tf-cnn/tf-cnn-dummy.yaml

**Comment by jlewi** [comment]
What's the priority for this issue?
Will need to fix it in 0.3 or can it wait for 0.4?

**Comment by xyhuang** [comment]
sorry about the late response. I just fixed this in #1693, it would be nice if possible to include the fix in 0.3.
