### ISSUE TITLE
E2E test to verify kfctl can setup a new project properly

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1616]
We'd like to verify that kfctl can probably deploy Kubeflow in a fresh GCP project (i.e. one that doesn't have any of the required APIs enabled). 

kfctl should have options and logic to properly initialize API's and perform one time setup.

In #1564 we added the flag to our E2E tests to skip initializing the project on each run because

  * It uses up limited quota
  * Makes the test run longer
  * Doesn't actually verify we can setup an unitialized project

So we should create a suitable E2E test that creates a fresh GCP project and deploys Kubeflow in that and verifies its working as intended.

**Comment by jlewi** [comment]
@chrisheecho Do you still think this P0? Should we downgrade to P1 or P2?

**Comment by ashahba** [comment]
I like to work on this one to learn more about the test framework.

**Comment by jlewi** [comment]
@ashahba Any update on this? Do you think we can still get this done as part of 0.4?

**Comment by carmine** [comment]
@ashahba  - still interested?
