### ISSUE TITLE
[GCP] Click to deploy doesn't create any K8s resources when version is 0.2.5

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1631]
I used the click to deploy app and specified version "0.2.5" in the UI
The app ran successfully and showed 

```
Deployment is done, your kubeflow app url should be ready within 15 minutes:
```

However the URL didn't work. The cluster was created as was the namespace but no resources were created within the **kubeflow** namespace.

```
kubectl -n kubeflow get all
```

What are proper version values?

/assign @kunmingg

**Comment by kunmingg** [comment]
The version fields accept tags & commit hash.
I assume any commit after Sep. 19 should work.
