### ISSUE TITLE
Add TFJob CRD creation to ksonnet components

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#164]
tensorflow/k8s#345 separated out creation of the custom resource definition from the controller.
So we will need to update the ksonnet component for the TFJob controller to create the CRD.

**Comment by jlewi** [comment]
@gaocegege Do you mind taking this as a follow up to your PR?

**Comment by gaocegege** [comment]
I'd glad to, althrough I am not familiar with ksonnet. I will have a try.
