### ISSUE TITLE
Changing access_mode of the PVC

### ISSUE THREAD

**Issue by gracechristina** [kubeflow/kubeflow#1645]
I want to attach multiple PVCs to a single-user pod in jupyterhub. However, this means that I need to modify the accessModes to ReadWriteMany. However, kubespawner will create PVC with a default access mode of ReadWriteOnce. I understand that we are not able to change PVC access mode if PVC already exists. How do we change this in the ksonnet during PVC creation? Thank you for the help! :)

**Comment by inc0** [comment]
Multiple PVC to single pod is ok with ReadWriteOnce. ReadWriteMany is required if you want to add single PVC to multiple pods.
