### ISSUE TITLE
Setup prow for the new org

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#165]
Now that we've moved from google/kubeflow to kubeflow/kubeflow we need to setup Prow for the new organization

- [X] Step 1; PR to add kubeflow/kubeflow to prow configs; kubernetes/test-infra#6513
- [X] Step 2; Setup GitHub prow webhook for the org
- [X]  Step 3; Add k8s robot to kubeflow org
- [ ]  Step 4: Setup PR dashboard
- [X] Step 5: Grant write access to Gubernator GCS bucket to kubeflow-testing service account 

See also #38

**Comment by gaocegege** [comment]
Cool, and will tensorflow/k8s be moved to kubeflow, too?

**Comment by jlewi** [comment]
See https://github.com/tensorflow/k8s/issues/350

**Comment by jlewi** [comment]
Invitation to add k8s robot has been sent.

**Comment by jlewi** [comment]
periodic tests are triggering
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubeflow-periodic/80/?log#log

So seems like an issue with the webhook.

**Comment by jlewi** [comment]
kubernetes/test-infra#6513 is submitted but presubmits don't appear to be triggering.

GitHub is reporting that webhook events are being delivered.

**Comment by jlewi** [comment]
@krzyzacy can you check the prow logs to see if the web hook events are being processed?

**Comment by krzyzacy** [comment]
is there some fake PR I can trigger?

**Comment by jlewi** [comment]
You can use
https://github.com/kubeflow/kubeflow/pull/128

**Comment by jlewi** [comment]
Problem was the auto config update for prow had failed so our changes hadn't been picked. Prow has been updated and our tests are now being triggered.

**Comment by jlewi** [comment]
Closing this issue even the PR dashboard isn't setup. We can own up a separate issue as needed if we want that.
