### ISSUE TITLE
[gcp] Click to deploy needs to get a valid master version for GKE by calling get-server-config

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1653]
See #1359 

GKE deprecates patch versions pretty quickly. So the app should call get-server-config to get a current supported minor version e.g. 1.10.x-gke-y  and set it in the DM config.

/assign @kunmingg

**Comment by kunmingg** [comment]
related 
https://github.com/kubeflow/kubeflow/pull/1654

**Comment by jlewi** [comment]
I think #1763 fixes this issue by pinning to a minor version and not a patch version.
