### ISSUE TITLE
kfctl.sh delete doesn't check/change kubectl context before issuing delete

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1669]
I don't think kfctl.sh delete verifies that kubectl is pointing at the right cluster before it issues a delete.

We should add a check and verify that we are pointing at the same cluster as the ksonnet app before deleting the namespace.

Here's some code to try to do that in bash.
https://github.com/kubeflow/testing/blob/master/deployment/redeploy_app.sh#L84

**Comment by chrisheecho** [comment]
Eng:Want PM:Need

**Comment by jlewi** [comment]
I'll leave this as P1 for now but it likely won't make it unless someone steps up take this.

It might also be easier to implement this as part of turning kfctl.sh into a kfctl go binary.

**Comment by jlewi** [comment]
Downgrading to P2. 

Since we plan on switching to a cli #1419 I think it makes sense to invest in that and then fix it in the CLI rather than updating kfctl.sh.
