### ISSUE TITLE
Use oauth2_proxy to authenticate to K8s Dashboard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#167]
We would like to make the K8s dashboard readily available to Kubeflow users.

In #166 we added Ambassador as a reverse proxy and a route to direct traffic to the K8s dashboard. The K8s dashboard however requires users to login using kubeconfig file or by providing an access token.

I  think a better solution would be to run K8s dashboard behind oauth2_proxy so that we could obtain a bearer token through the OAuth web flow and then provide that to the dashboard in the Authorization header.

**Comment by jlewi** [comment]
We should figure out a good solution for exposing basic metrics like CPU/Mem/RAM utilization to users.

I would be happy with a solution that treats this as a K8s distribution specific problem that we solve by providing links to docs for different K8s solutions.

**Comment by bhack** [comment]
@jlewi Who can take care of a fork finally? Seems nobody has enough power. Check https://github.com/bitly/oauth2_proxy/issues/594

**Comment by bhack** [comment]
On the Istio side https://github.com/istio/istio/issues/467

**Comment by bhack** [comment]
@jlewi I meant that the upstream it is quite stalled and I don't know if it is reliable if some security problem will emerge. Seems redhat/openshift is try to maintain its own version but it is not a "mainstream fork". I don't know if you can play a role with google and other partners to maintain it or if you have an alternative solution.
As we have adopted Ambassador see also 
https://github.com/datawire/ambassador/issues/28

**Comment by bhack** [comment]
A fork was proposed again https://github.com/bitly/oauth2_proxy/issues/628
