### ISSUE TITLE
[v0.3.0-rc.1] "/" doesn't redirect to the centraldasbhoard UI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1670]
When I deploy the central dasbhoard UI this is what I see.

![centralui](https://user-images.githubusercontent.com/777219/46251148-e1f7f280-c3ff-11e8-809d-4aa0fd191e1b.png)

If I click on layout and go to the page
https://jlewi-0929-iap-fix.endpoints.cloud-ml-dev.cloud.goog/layout.html

I see the expected central dashboard UI.

/assign @swiftdiaries 

Related to #1541 0.3 RC

/priority p1
/area 0.3.0

**Comment by jlewi** [comment]
I think this was fixed in #1676; we just need to update the image on the 0.3 branch

**Comment by richardsliu** [comment]
This is done.
