### ISSUE TITLE
[v0.3.0-rc.1] Only TF 1.8 CPU shows up in the list of prepopulated Jupyter images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1671]
With v0.3.0-rc.1 in Jupyter I only see TF 1.8 in the list of prepropulated Jupyter images

![screenshot from 2018-09-29 17-30-53](https://user-images.githubusercontent.com/777219/46251639-7f0d5800-c40d-11e8-9d94-ad1d5e9aa9f1.png)

/cc @pdmack 

Related to #1541 0.3 release

**Comment by jlewi** [comment]
There's a list of images in the HTML in kubeform_spawner.py

````
 <table style="width: 100%;">
        <tr>
            <td style="width: 30%;"><label for='image'>Image</label></td>
            <td style="width: 70%;"><input value="{0}/{1}/tensorflow-1.8.0-notebook-cpu:v0.3.0" list="image" name="image" placeholder='repo/image:tag' style="width: 100%;">
            <datalist id="image">
              <option value="{0}/{1}/tensorflow-1.4.1-notebook-cpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.4.1-notebook-gpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.5.1-notebook-cpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.5.1-notebook-gpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.6.0-notebook-cpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.6.0-notebook-gpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.7.0-notebook-cpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.7.0-notebook-gpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.8.0-notebook-cpu:v0.3.0">
              <option value="{0}/{1}/tensorflow-1.8.0-notebook-gpu:v0.3.0">
            </datalist>
            </td>
        </tr>
        </table>
````

But it looks like they aren't showing up; only the default image is.

**Comment by jlewi** [comment]
@tlkh Thanks.

You can see #1630 and #34 for plans about improving the Jupyter UX and potentially getting rid of JupyterHub.

**Comment by richardsliu** [comment]
For v0.3 release let's just fix the HTML. For the future plan we can continue the discussion in #1630 .

**Comment by pdmack** [comment]
> except in Safari, where that element is not supported

Yeah, we knew that exception from the start. Safari is woefully behind on some HTML5 elements. Felt it was an acceptable exclusion given all the other browsers available.
