### ISSUE TITLE
Failed to deploy tfjob through postman call tf-operator-dashboard interface

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/kubeflow#1673]
I try to use postman to call the tf-operator-dashboard interface to deploy tfjob, related commands are as follow:

Method: POST
URL: http://<localhost:tf-operator port>/tfjobs/api/tfjob
Parameters body:

		{
            "kind": "TFJob",
            "apiVersion": "kubeflow.org/v1alpha2",
            "metadata": {
                "name": "testpostman6",
                "namespace": "kubeflow"
            },
            "spec": {
                "tfReplicaSpecs": {
                    "PS": {
                        "replicas": 1,
                        "template": {
                            "spec": {
                            	"serviceAccount": "tf-job-dashboard",
                                "containers": [
                                    {
                                        "name": "tensorflow",
                                        "image": "tensorflow:v2",
                                        "command": [
                                            "python",
                                            "/home/work/mnist_tf.py"
                                        ],
                                        "resources": {}
                                    }
                                ],
                                "restartPolicy": "OnFailure"
                            }
                        }
                    }
                }
            }
        }

Postman response:

Status: 500 Internal Server Error

namespaces "kubeflow" is forbidden: User "system:serviceaccount:kubeflow:tf-job-dashboard" cannot get namespaces in the namespace "kubeflow"{
  "metadata": {
   "name": "testpostman6",
   "namespace": "kubeflow",
   "selfLink": "/apis/kubeflow.org/v1alpha2/namespaces/kubeflow/tfjobs/testpostman6",
   "uid": "5462b88d-c47a-11e8-b107-a0369fb2cebe",
   "resourceVersion": "2960806",
   "generation": 1,
   "creationTimestamp": "2018-09-30T06:30:31Z"
  },
  "spec": {
   "tfReplicaSpecs": {
    "PS": {
     "replicas": 1,
     "template": {
      "metadata": {
       "creationTimestamp": null
      },
      "spec": {
       "containers": [
        {
         "name": "tensorflow",
         "image": "tensorflow:v2",
         "command": [
          "python",
          "/home/work/mnist_tf.py"
         ],
         "resources": {}
        }
       ],
       "restartPolicy": "OnFailure",
       "serviceAccount": "tf-job-dashboard"
      }
     }
    }
   }
  },
  "status": {
   "conditions": null,
   "tfReplicaStatuses": null
  }
 }

What puzzles me is why postman returns the error code 500, but tfjob is running in kubernetes.

**Comment by jlewi** [comment]
I would recommend using the K8s API to submit TFJobs programmatically and not use the dashboard API. The latter is meant for internal use 

Which version of Kubeflow are you using. I think the issue with namespaces and the dashboard was fixed in
kubeflow/tf-operator#701 and should be in 0.3.
