### ISSUE TITLE
Additions to the Jupyter hub containers

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1679]
Should we add gcsfuse to the Jupyter notebook containers?

I've been using NFS to store my workspace in case the notebook container crashes which has worked fine until something went wrong with NFS, re-deployed the cluster, and NFS was wiped 😬 (theres no trombone emoji...), GCS or another storage solution that won't be inadvertently wiped  seems like an important solution for storing things you wouldn't ever want to automatically wipe (and that you want to be able to use like a local FS, e.g. a diverse library of model code, i.e. in the use case where jhub is your primary IDE) whereas automatically formatting a scratch volume seems fine.

Also should we add back in tensorhub? Being able to launch tensorboard from the notebook is awfully convenient.

cc @pdmack

**Comment by ai4life** [comment]
also would be nice if you upgraded to jupyterlab-hub

**Comment by pdmack** [comment]
tensorboard is its own prototype atm. Used to be in the notebook but it was deliberately broken out into its own component.

re: gcsfuse, have you looked at https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/google-cloud-filestore-pv.libsonnet yet as a possible solution?
Maybe @kkasravi has better info there.
