### ISSUE TITLE
Accessing custom metrics in our Python model

### ISSUE THREAD

**Issue by bbarn3y** [kubeflow/kubeflow#1681]
We are using Seldon to wrap our Python model images and we deploy these images with Kubeflow seldon serving. We also have seldon-core-analytics set up on our Kubernetes cluster and we can get and see the default Prometheus metrics using Grafana.

However, we need to extend these default metrics with our own metrics defined in the model and if possible these new metrics should behave the same way as the default ones meaning that they should be queriable and visualizable by Grafana. 

We're thinking about extending seldon-core Python Wrapper's Flask REST endpoint with our own route for querying custom metrics. How could we set this up in a way that makes these custom metrics accessible in Grafana? How can we tell seldon-core-analytics' Prometheus to scrape our custom metrics?

**Comment by jlewi** [comment]
If you're considering extending seldon-core you might want to open an issue in the GitHub SeldonIO repo. That's where the Seldon development happens. 

Kubeflow is just providing a ksonnet package for Seldon and integrating it with some of our other services.

/cc @cliveseldon

**Comment by bbarn3y** [comment]
Thank you, I'll do that!
