### ISSUE TITLE
Argo UI doesn't work behind ambassador

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1694]
Using: argoproj/argoui:v2.1.1

We currently add a reverse proxy route to Ambassador for the Argo UI but when I tried it I just get a blank screen. Using port-forward to the Argo pod works.

I see some javascript errors:

```
GET http://localhost:8080/main.ac6e091ac4a22318d76f.js net::ERR_ABORTED 404 (Not Found)
localhost/:1 Refused to execute script from 'http://localhost:8080/main.ac6e091ac4a22318d76f.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
   * localhost:8080 is mapped via port-forwarding to Ambassador port 80

This looks like it might an issue with Argo not being proxy aware e.g. the URL

```
http://localhost:8080/main.ac6e091ac4a22318d76f.js 
```
Looks wrong; I think it should be

```
http://localhost:8080/argo/main.ac6e091ac4a22318d76f.js 
```

I found this issue on using a reverse proxy with Argo.
https://github.com/argoproj/argo/issues/716

Looks like we might need to explicitly set some parameter to control the base URL.

/cc @alexmt

**Comment by TimZaman** [comment]
Still an issue? I installed kubeflow last week with the tutorial, and visiting `https://XXX.cloud.goog/argo/` gives me (console):

```GET https://kubeflow2.endpoints.kubeflowtest-225221.cloud.goog/main.f6e517525a3ff95bf2c8.js net::ERR_ABORTED 404```
