### ISSUE TITLE
[testing] Add storage for verbose logs of test jobs

### ISSUE THREAD

**Issue by inc0** [kubeflow/kubeflow#1698]
In OpenStack CI system we had disk space where we could dump logs. This allowed us to easily examine failures and add very verbose logging. Do you think we could build infra for something like that for Kubeflow (for example over google drive?). What I'm thinking about is something to extend of

`for pod in $(kubectl get po -o name); do kubectl describe $pod; done > pods.log` and more like that for any command we can think of.

And then save all files like that to google drive somewhere (with url linked to CI output somewhere)

**Comment by inc0** [comment]
We can use Argo's artifacts to save things to google cloud storage. Flow would be -> on every test dump any log you can think of to txt file -> save it in predefined dir -> tar.gz whole dir -> set it up as argo artifact -> upload to gcs for easier debugging of job

**Comment by jlewi** [comment]
STDOUT/STDERR are already logged in stackdriver. 
https://github.com/kubeflow/testing

There's an NFS mount attached to all pods as well but right now we garbage collect that at the end of each run because we were running out of space.

**Comment by inc0** [comment]
Stderr of main process isn't enoug (or we'll make it super cluttered). I was thinking of adding easy hooks to log whatever, including stuff like kubectl logs <<every pod ran>>. Important thing is to keep it somewhere and make it readable (ideally with browser, but download tar.gz shouldn't be too bad as well).
