### ISSUE TITLE
jsonnet test is failing but no jsonnet files changed in the PR.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1707]
Here's a PR
https://github.com/kubeflow/kubeflow/pull/1703

And presubmit
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1703/kubeflow-presubmit/3673/

That failed with error

```
ERROR : /mnt/test-data-volume/kubeflow-presubmit-unittests-1703-68b0e79-3673-71f5/src/kubeflow/kubeflow/kubeflow/katib/prototypes/all.jsonnet is not formatted
```

But that file wasn't modified in the PR.
The only files modified were in
components/gcp-click-to-deploy/src

It looks like our test doesn't only consider the files changed in the PR.
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/test_jsonnet_formatting.py#L50

**Comment by richardsliu** [comment]
The formatting error has been fixed. My theory is that this is caused by updating the test worker image. https://github.com/kubeflow/testing/pull/201 updated the jsonnet version.
