### ISSUE TITLE
 Unable to install Kubeflow on a exising 2 node ubuntu cluster; Docs need to be fixed

### ISSUE THREAD

**Issue by prateek1192** [kubeflow/kubeflow#1711]
I am following the https://www.kubeflow.org/docs/started/getting-started/ to set up kubeflow on an already exiting Kubernetes cluster.

The documentation says that

${KFAPP} The name of a directory to store your configs. This directory will be created when you run init. 
As such I give my directory as /home/prateek/conf

To make sure that the directory is not present already I do a rm on that directory. But i get the error as

prateek@deepc06:~/kubeflow$ rm -rf /home/prateek/conf/
prateek@deepc06:~/kubeflow$ ${KUBEFLOW_REPO}/scripts/kfctl.sh init ${KFAPP} --platform none
+ COMMAND=init
+ WHAT=/home/prateek/conf
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname /home/prateek/kubeflow/scripts/kfctl.sh
++ cd /home/prateek/kubeflow/scripts
++ pwd
+ DIR=/home/prateek/kubeflow/scripts
+ source /home/prateek/kubeflow/scripts/util.sh
+ source /home/prateek/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/prateek/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' init == init ']'
+ DEPLOYMENT_NAME=/home/prateek/conf
+ [[ 4 -gt 0 ]]
+ case $1 in
+ shift
+ [[ 3 -gt 0 ]]
+ case $1 in
+ shift
+ [[ 2 -gt 0 ]]
+ case $1 in
+ shift
+ PLATFORM=none
+ shift
+ [[ 0 -gt 0 ]]
+ mkdir -p /home/prateek/conf
+ cd /home/prateek/conf
+ createEnv
+ echo PLATFORM=none
++ cd /home/prateek/kubeflow/scripts/..
++ pwd
+ DEFAULT_KUBEFLOW_REPO=/home/prateek/kubeflow
+ KUBEFLOW_REPO=
+ echo KUBEFLOW_REPO=/home/prateek/kubeflow
+ echo KUBEFLOW_VERSION=master
++ pwd
+ echo KUBEFLOW_KS_DIR=/home/prateek/conf/ks_app
+ echo KUBEFLOW_DOCKER_REGISTRY=
+ echo K8S_NAMESPACE=kubeflow
+ case "$PLATFORM" in
+ echo KUBEFLOW_CLOUD=null
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=/home/prateek/kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/prateek/conf/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' -z /home/prateek/conf ']'
+ '[' -d /home/prateek/conf ']'
+ echo Directory /home/prateek/conf already exists
Directory /home/prateek/conf already exists
+ exit 1

So the error is the directory already exists. Notice How i removed the directory before starting the script.

**Comment by jcurlier** [comment]
I think the documentation should be updated... I believe this is the name of the folder, not the path, and it is also the name of the Kubernetes cluster that will be created later...

**Comment by prateek1192** [comment]
Is there any ETA on this ?

**Comment by ashahba** [comment]
@prateek1192 I did a small update to the docs, I'll review your logs and see add more improvements.
Sorry for the late response here.

**Comment by ashahba** [comment]
Looks like the above PR was merged to address paths vs directory names a bit more for end users.

We should be able to close this ticket once we hear from @prateek1192

**Comment by jlewi** [comment]
Thanks @ashahba.

@prateek1192 if you're still having problems feel free to reopen this issue or a new one.
