### ISSUE TITLE
Seldon doesn't deploy deployment in namespace different from namespace of CRD

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1712]
I deployed Seldon controller in namespace kubeflow using v0.3.0-rc.3 

I created a Seldon deployment in namespace gh-public; no pods were created. It looks to me like Seldon controller is only monitoring the kubeflow namespace. 

When I created a deployment in the namespace Kubeflow it was deployed.

@cliveseldon Are there options I need to set so that the deployment CRD monitors all namespaces? There is an issue (#1452) to make it possible to only watch a particular namespace.

**Comment by jlewi** [comment]
I confirmed that if I deploy the controller in the other namespace then the svc and model get created in that namespace.

**Comment by cliveseldon** [comment]
Yes the present focus is that seldon is installed on a per namespace basis and manages deployments just in that namespace.
The custom resource definition is "namespaced" so the API calls in our operator are all namespaced in operation.

**Comment by jlewi** [comment]
I think we'll need to figure out what to do as part of multi-user CUJ.
Ideally we don't have to deploy the seldon controller in every namespace.

I think this might have been fixed in the latest releases of Seldon.

/cc @ahousley @cliveseldon

**Comment by cliveseldon** [comment]
Yes, the latest version of Seldon in kubeflow master has a parameter for this.
```
@optionalParam singleNamespace string true Whether to limit seldon to a single namespace
```

Can we make sure its in 0.5?
