### ISSUE TITLE
TF data validation and tfma are in 1.9 images but not 1.10

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1718]
The imports

failed in 
gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu:v0.3.0

but succeeded in
gcr.io/kubeflow-images-public/tensorflow-1.9.0-notebook-cpu:v0.3.0

But we should be installing TFMA in 1.10 as well

**Comment by pdmack** [comment]
Just did a local build and it's there...?
```
INFO|2018-10-08T15:35:20|build_image.py|46| Successfully built b73b8396f7b2
[root@dell-r730-005 components]# docker run -P -it --rm gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu:latest /bin/bash
root@31a284976789:~# source activate py2
(py2) root@31a284976789:~# pip list | grep tensorflow
tensorflow                         1.10.1
tensorflow-data-validation         0.9.0
tensorflow-metadata                0.9.0
tensorflow-model-analysis          0.9.2
tensorflow-serving-api             1.11.0
tensorflow-transform               0.9.0
```

**Comment by richardsliu** [comment]
It should be there: https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/versions/1.10.1/version-config.json

**Comment by jlewi** [comment]
Confirmed its not working in a PY2 kernel in

```
 image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu:v0.3.0
    imageID: docker-pullable://gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu@sha256:bd3d2ae9a4e07b2b58910e99a26676ab31f4ba5ae2a633fbde5ce8dee8b63024
```

![notebook](https://user-images.githubusercontent.com/777219/46672780-28321c00-cb8d-11e8-8d75-0decad06acbc.png)

**Comment by jlewi** [comment]
Postsubmit built the images successfully:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/822/

Need to retag them 0.3.1 and get them onto the v0.3-branch
