### ISSUE TITLE
Permission denied errors when pip (un)installing without --user in new nb images

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1722]
When attempting to modify a python package that shipped as part of the base conda environment, e.g. pip uninstalling pandas in the py2 environment, a permission denied error is seen, e.g.

> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: ‘/opt/conda/envs/py2/lib/python2.7/site-packages/pandas-0.23.2.dist-info/INSTALLER’

I and others (https://github.com/kubeflow/examples/pull/252#discussion_r222690517) observed this across various versions of the stock notebook containers (i.e. the ones that are offered as options in the spawner drop-down).

cc @pdmack

**Comment by pdmack** [comment]
Got more details? I'm not seeing this with v0.3.0.
```
# docker run -P -it --rm gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu:v0.3.0 /bin/bash
root@e7358d5da8ca:~# su jovyan
jovyan@e7358d5da8ca:~$ source /opt/conda/bin/activate /opt/conda/envs/py2
(py2) jovyan@e7358d5da8ca:~$ pip uninstall pandas
Uninstalling pandas-0.23.4:
  Would remove:
    /opt/conda/envs/py2/lib/python2.7/site-packages/pandas-0.23.4.dist-info/*
    /opt/conda/envs/py2/lib/python2.7/site-packages/pandas/*
Proceed (y/n)? y
  Successfully uninstalled pandas-0.23.4
```

**Comment by cwbeitel** [comment]
If that's the same with the other containers post 0.3 then the issue must be resolved, I was seeing this in `gcr.io/kubeflow-images-public/tensorflow-1.8.0-notebook-cpu:v0.2.1` and I believe in `gcr.io/kubeflow-images-public/tensorflow-1.6.0-notebook-cpu:v0.2.1`. I'm not seeing the issue with `gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-cpu:v0.3.0` either.
