### ISSUE TITLE
RE: Certificate issue with ambassador.

### ISSUE THREAD

**Issue by kavemun** [kubeflow/kubeflow#1724]
Hi got the error trying to deploy kubeflow on a Kubernetes cluster.
looks like some certificate issues with ambassador.

+ ks env add default --namespace kubeflow
INFO Using context "kubeflow" from kubeconfig file "/home/user/.kube/config" 
Please enter Username: user
Please enter Password: ********
INFO Creating environment "default" with namespace "kubeflow", pointing to "version:v1.8.0" cluster at address "https://XXX.XXX.X.XX" 
+ ks apply default -c ambassador
Please enter Username: XXXXXXX
Please enter Password: *************
ERROR handle object: patching object from cluster: merging object with existing state: Get https://XXX.XXX.X.XXX/api/v1/namespaces/kubeflow/services/ambassador: x509: certificate signed by unknown authority 

Suggestion but I think the documents are insufficient to get someone started on kubeflow?

Thanks

**Comment by jlewi** [comment]
I don't think this is an ambassador issue.

It looks like ksonnet is trying to connect to your K8s master and I think it's promoting you for username and password to access your master.

Does kubectl work?

If it does you could run
Ks show and pipe the output to kubectl

**Comment by jlewi** [comment]
What platform (e.g. minikube) are you using to run K8s?

**Comment by jlewi** [comment]
But how are you running Kubernetes? Are you using a Cloud's managed offering? Are you running on prem?

It looks like the information to connect to your cluster (e.g. username and password isn't stored in your .kubec/config file).

It looks like ksonnet has command line options to set this e.g.


```
ks apply --username=${USER} --password=${PASS} --insecure-skip-tls-verify default -c ambassador
```

**Comment by kavemun** [comment]
on prem, I am playing around with the config now, but not much success yet

**Comment by kavemun** [comment]
after I set the insecure-skip-tls-verify =true by doing :-
kubectl config set-cluster $CLUSTER_NAME --server=http://$MASTER_IP --insecure-skip-tls-verify=true

I get the following error instead:-
+ ks env add default --namespace kubeflow
INFO Using context "ignite" from kubeconfig file "/home/user/.kube/config" 
INFO Creating environment "default" with namespace "kubeflow", pointing to "version:v1.8.0" cluster at address "http://10.60.1.24" 
+ ks apply default -c ambassador
ERROR handle object: patching object from cluster: merging object with existing state: Get http://10.60.1.24/api/v1/namespaces/kubeflow/services/ambassador: dial tcp 10.60.1.24:80: connect: connection refused

My .kube/config is as follows:-

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://10.60.1.24
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: mykubeflow
    user: ""
  name: ignite
- context:
    cluster: ""
    user: ""
  name: kubeflow-ctx
current-context: ignite
kind: Config
preferences: {}
users: []

**Comment by jlewi** [comment]
Did you try doing 

```
ks show default -c ambassador > ambassador.yaml
kubectl apply -f ambassador.yaml
```

The issue appears to be with ksonnet and/or kubectl not being able to connect to your K8s master.

So if kubectl works then its likely an issue with ksonnet not picking up the config in order to be able to connect to your master.

**Comment by kavemun** [comment]
I think it's the latter, kubectl, not picking up the config on my K8s. I'll debug a little more  on this when i have the time.

**Comment by jlewi** [comment]
@kavemun were you able to resolve this?

**Comment by saiakhil2012** [comment]
@kavemun were you able to solve this? or is there a workaround to make it work for now?
