### ISSUE TITLE
Unable to use -x option with  mca_base_env_list

### ISSUE THREAD

**Issue by gautamkmr** [kubeflow/kubeflow#1729]
Sometime its hard to just stick with mca_base_env_list but rather depends on -x option

If we use both it gives error which is pretty obvious to understand 

ERROR: You have attempted to pass environment variables to Open MPI
with both the "-x" method and by setting the MCA parameter "mca_base_env_list".

But can be set up mechanism to have both or at least a better way to use it ?

**Comment by jlewi** [comment]
@everpeace do you know the answer?

**Comment by everpeace** [comment]
@gautamkmr Hi, as you recognized, openmpi package automatically injects predefined `mca_base_env_list` at `~/.openmpi/mca-params.conf`.

contents of `mca-params.conf`: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/openmpi/assets/mca-params.conf
code injecting the file to homedir in container: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/openmpi/assets/init.sh#L54-L56


So, you could edit (or even delete) this file to tune parameters.

**Comment by gautamkmr** [comment]
@everpeace Thanks for the comment. Yes deleting/editing makes perfect sense. However creating such changes requires editing the kubeflow repo itself. This sort of break the steps towards automation. 
For now I managed to get around of it by using 'sh -c' option while keeping the mca-params file as it is. 
Do you think its better solution or do you have any other suggestion ? 

Thanks for the help.

**Comment by everpeace** [comment]
@gautamkmr 

> However creating such changes requires editing the kubeflow repo itself.

ah, you're right.  `~/.openmpi/mca-params` can't be deleted from entire cluster because the file is injected in all the master and workers. `exec` option only affects the master pod.

> Do you think its better solution or do you have any other suggestion?

Sorry, I don't think so.  


By the way, do you have any idea how to fix openmpi package to solve the issue??

**Comment by gautamkmr** [comment]
> By the way, do you have any idea how to fix openmpi package to solve the issue??

https://github.com/kubeflow/kubeflow/pull/671 jiezhang@ do you think we can get rid of mca-params? 
I think going forward user will most like use '-x' option to pass the parameter,  So either we get rid of this or we need to fix the openmpi package itself.  What do you think?

**Comment by erik78se** [comment]
How can I know which of many mca-params.conf is used?

I'm not able to remove this file to get rig of this problem.

Looking for help here.
