### ISSUE TITLE
Support request/response logging 

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1731]
related to:
- using istio 1.0 #1309
- #1714 removes the http proxy in the new TF serving template. We will add istio integration and support request/response logging

https://istio.io/docs/tasks/telemetry/fluentd/#configure-istio

**Comment by jlewi** [comment]
/priority p1

This would be nice to have and it would be good to figure out how much we can leverage from ISTIO.

**Comment by cliveseldon** [comment]
We'd be interested to use this for Seldon as well along with Zipkin for tracing.

**Comment by lluunn** [comment]
Just found out Istio might not support this
https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/
https://github.com/istio/istio/issues/4210

No request.body

cc @bhupc

**Comment by jlewi** [comment]
Should we punt this to 0.5? We've explored various ideas but I don't think we have anything concrete planned at this point.

**Comment by jlewi** [comment]
I'm downgrading to P2 because I don't think this will be part of one of our critical CUJs for 0.5.
