### ISSUE TITLE
Test for download.sh and kfctl.sh

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1735]
We have a test for download.sh here:
https://github.com/kubeflow/kubeflow/blob/master/scripts/download_test.py

And we have a test for kfctl generate here
https://github.com/kubeflow/kubeflow/blob/master/scripts/kfctl_generate_test.sh

We should combine these and make run them on pre & postsubmits.

We want to run kfctl generate platform and k8s for GCP after running download.sh to ensure we properly download all the files used by kfctl.sh

**Comment by ashahba** [comment]
I can work on this if no one started on it yet.

**Comment by jlewi** [comment]
@ashahba any update on this?

Do you think we will get this done by Dec 17 which is when we want to cut the 0.4 RC?

Does it make sense to wait until we switch to a go based CLI #1419 ? In which case should we punt to 05?

**Comment by ashahba** [comment]
Sorry @jlewi for missing the notes.
I can certainly try to get it in for `0.4 RC`.

**Comment by jlewi** [comment]
@ashahba Any update? If you haven't started; I would suggest we prioritize the move to the go based implementation #1419 as that might change how things work.

**Comment by jlewi** [comment]
Obsolete since we are moving to kfctl go binary.
