### ISSUE TITLE
[docs] download.sh pulls from master instead of based on version tag

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1738]
I'm guessing in https://www.kubeflow.org/docs/started/getting-started-gke/ under "Deploy Kubeflow on Kubernetes Engine" the command

```bash
curl https://raw.githubusercontent.com/kubeflow/kubeflow/master/scripts/download.sh | bash
```

was probably meant to be a function of `KUBEFLOW_TAG`.

cc @sarahmaddox

**Comment by cwbeitel** [comment]
The script does the following at startup

```bash
if [ ! -z "${KUBEFLOW_VERSION}" ]; then
	KUBEFLOW_TAG=v${KUBEFLOW_VERSION}
fi

KUBEFLOW_TAG=${KUBEFLOW_TAG:-master}
```

suggesting the user should set KUBEFLOW_VERSION in their environment before running the script instead of KUBEFLOW_TAG (if the script is to be used as currently written).

**Comment by jlewi** [comment]
Thanks @cwbeitel
