### ISSUE TITLE
Create a repository for examples: kubeflow/examples

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#174]
I think we should create a repository where we can start hosting E2E examples.

Right now we have a couple E2E examples in various states of development

  *  https://github.com/cwbeitel/kubeflow-rl - Using TensorFlow Agents for RL
  * #157 GitHub Issue Summarization
  * #163 XGB example
  * Hot Dog Or Not - Kubeflow Kubecon 2017 demo

/cc @puneith @cwbeitel

**Comment by puneith** [comment]
@jlewi Why do you think we need a separate repo and not Kubeflow be that place?

**Comment by cwbeitel** [comment]
I have some additional examples in progress to add.

Would love to have them under e2e test. But for some examples you may want to do progressive testing to speed things up / cache previous runs. Such as with Bazel. That could be a mod to the way kubeflow runs tests or could be a reason to have a separate repo.

**Comment by jlewi** [comment]
@puneith Because examples will be in various states of development and should probably be separate from the core code.

For the most part, this repo corresponds to our ksonnet registry.

**Comment by jlewi** [comment]
Another reason for moving examples into their own repository is that it will probably be a different group of folks working on the examples then the folks working on our core ksonnet components.

**Comment by puneith** [comment]
I agree with that model.

**Comment by gaocegege** [comment]
Vote for separate repo 👍

**Comment by elsonrodriguez** [comment]
I could go either way, but my doc fixes have included ksonnet changes. Managing two separate repos for things that are tied together may be painful.

**Comment by jlewi** [comment]
@elsonrodriguez I think the fact that writing examples requires modifying our core ksonnet components is an indication of other problems

  * immaturity/limitations of the ksonnet templates
       * e.g. I think in some of your changes you had to add parameters to the TF serving component to allow more flexibility
  * version compatibility issues because we haven't started creating tagged releases yet
       * By March we should have a 0.1 branch for ksonnet registry and our examples should be written against that.

**Comment by jlewi** [comment]
Lets give a separate repo a shot and then adapt as need be.

I think the main priority now is getting more examples that illustrate Kubeflow so velocity is the primary motivation. With a separate repo we can easily start giving a different set of folks write access and moving the ball forward. 

@elsonrodriguez If you want to take the lead on an inception example I'm happy to make you an approver.

**Comment by jlewi** [comment]
Created the repo:
https://github.com/kubeflow/examples

Created a team examples-approvers and gave it write access to the repo.
I seeded the team with some devrel folks from Google and Microsoft(@wbuchwalter) who've contributed to Kubeflow.

**Comment by elsonrodriguez** [comment]
@jlewi Sure, I can take the current inception example and rework/port it over.
