### ISSUE TITLE
the variable of ENVIRONMENT

### ISSUE THREAD

**Issue by davidstack** [kubeflow/kubeflow#1741]
when install chainer-job,i find a variable ENVIRONMENT，but i can't find the definition of ENVIRONMENT, what‘s  the mean of ENVIRONMENT? tks

`cd ${KSONNET_APP}

ks pkg install kubeflow/chainer-job

ks generate chainer-operator chainer-operator

ks apply ${ENVIRONMENT} -c chainer-operator`

**Comment by jlewi** [comment]
@everpeace do you know the answer?

**Comment by davidstack** [comment]
@everpeace  tks!
