### ISSUE TITLE
No deployment directory found in https://github.com/kubeflow/kubeflow/archive/v0.3.0.tar.gz

### ISSUE THREAD

**Issue by kavemun** [kubeflow/kubeflow#1743]
When following instructions in [Getting Started Minikube](https://www.kubeflow.org/docs/started/getting-started-minikube/)  download.sh script is trying to copy deployment folder from temp after untar, but it cannot be found.

+ cp -r /tmp/tmp.kubeflow-repo-PcTY/kubeflow-0.3.0/deployment ./
cp: cannot stat '/tmp/tmp.kubeflow-repo-PcTY/kubeflow-0.3.0/deployment': No such file or directory

**Comment by jlewi** [comment]
It looks like you are pulling download.sh from the master branch

```
export KUBEFLOW_TAG=v0.3.0
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
```

You can see here that on the v0.3 branch we don't copy deployment
https://github.com/kubeflow/kubeflow/blob/v0.3-branch/scripts/download.sh

**Comment by kavemun** [comment]
okay got it. i copied that line from github and somehow it copies an escape character in the curly braces and returned me 404 instead. latest tag seems to work. thanks
