### ISSUE TITLE
[GKE] GKE guide Central UI does not work 

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/kubeflow#1744]
Google Cloud Platform (Kubernetes Engine)
If you followed the guide for Kubernetes Engine, Kubeflow will be deployed with IAP and the web UIs will be accessible at

https://<name>.endpoints.<project>.cloud.goog/

Above instruction doesn't seem to work for me for some reason. 
name = kubeflow
project = gcp-emea-ml

https://kubeflow.endpoints.gcp-emea-ml.cloud.goog/

running this command kubectl -n kubeflow get all gets the following.

```
chrisheecho@cloudshell:~ (gcp-emea-ml)$ kubectl -n kubeflow get all
NAME                                   READY     STATUS    RESTARTS   AGE
pod/ambassador-7fb86f6bc5-29m5v        3/3       Running   0          3h
pod/ambassador-7fb86f6bc5-dm9xn        3/3       Running   0          3h
pod/ambassador-7fb86f6bc5-nshfq        3/3       Running   0          3h
pod/centraldashboard-f8d7d97fb-x587p   1/1       Running   0          3h
pod/tf-hub-0                           1/1       Running   0          3h
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/ambassador         ClusterIP   10.27.246.141   <none>        80/TCP     3h
service/ambassador-admin   ClusterIP   10.27.241.46    <none>        8877/TCP   3h
service/centraldashboard   ClusterIP   10.27.255.16    <none>        80/TCP     3h
service/k8s-dashboard      ClusterIP   10.27.252.217   <none>        443/TCP    3h
service/statsd-sink        ClusterIP   10.27.243.32    <none>        9102/TCP   3h
service/tf-hub-0           ClusterIP   None            <none>        8000/TCP   3h
service/tf-hub-lb          ClusterIP   10.27.254.243   <none>        80/TCP     3h
NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ambassador         3         3         3            3           3h
deployment.apps/centraldashboard   1         1         1            1           3h
NAME                                         DESIRED   CURRENT   READY     AGE
replicaset.apps/ambassador-7fb86f6bc5        3         3         3         3h
replicaset.apps/centraldashboard-f8d7d97fb   1         1         1         3h
NAME                      DESIRED   CURRENT   AGE
```

any advice in debugging this?

**Comment by richardsliu** [comment]
Did you configure the oauth client credentials with authorized domains? Make sure the authorized redirect URI matches with your desired endpoint.

**Comment by jlewi** [comment]
@chrisheecho What was the exact failure mode?

There are troubleshooting instructions here:
https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/

**Comment by richardsliu** [comment]
@chrisheecho Actually it doesn't look like the deployment finished successfully, a lot of the components are missing. Do you have output logs from your installation?

**Comment by connected-bsamadi** [comment]
Hey @richardsliu and @jlewi. 
This is what I get with kubectl -n kubeflow get all:

https://gist.github.com/connected-bsamadi/01ab408f8f6c36265d60df60e92ebee0

With ks show default -c ambassador, I get the following:
https://gist.github.com/connected-bsamadi/dff2a2ed46bd9f9a122d8c5bca47edf1

Here are logs of jyputerhub-0 and envoy pods:
https://gist.github.com/connected-bsamadi/21fabab6d755133e5a70ab44263da93e
https://gist.github.com/connected-bsamadi/e3c9ddcbb6cd0b31797a60c6692b2345

When I deploy Kubeflow to GKE, all the Workloads and Services are green. I sometimes can see the central dashboard but if I refresh I get the "This site can’t be reached" error.

**Comment by jlewi** [comment]
@connected-bsamadi 

What is the HTTP error code you are getting when you see ""This site can’t be reached" is it a 502? (If you're using Chrome you can use the developer tools console to see the error code).

Your central dashboard pod looks healthy. 

When you get the error "This site can't be reached"; do you see pods crashing/restarting? 

When that happens can you try connecting directly to the central UI pod using kubectl port-forward and seeing if that works.

**Comment by connected-bsamadi** [comment]
@jlewi I don't get any error message on the console. It's empty. 
In the browser, I get the following:
This site can’t be reached
kubeflow.endpoints.ontario-2018.cloud.goog unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED

**Comment by connected-bsamadi** [comment]
On my cellphone, I get
kubeflow.endpoints.ontario-2018.cloud.goog's server IP address could not be found
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by jlewi** [comment]
I suspect a problem with the ingress; most likely SSL certificate related.

Try the following

```
curl -I kubeflow.endpoints.ontario-2018.cloud.goog
```

And also do

```
kubectl describe ingress
```

**Comment by jlewi** [comment]
Also probably easier to debug/troubleshoot on https://kubeflow.slack.com

**Comment by jlewi** [comment]
We troubleshooted this in slack. It looks like @connected-bsamadi is hitting LetsEncrypt certificate limits

```
 "textPayload": "certificates controller: Re-queuing item \"kubeflow/envoy-ingress-tls\" due to error processing: error getting certificate from acme server: acme: urn:ietf:params:acme:error:rateLimited: Error finalizing order :: too many certificates already issued for exact set of domains: kubeflow.endpoints.ontario-2018.cloud.goog: see https://letsencrypt.org/docs/rate-limits/",
```

This error comes from the cert-manager pod logs.

Some potential work arounds

1. Use a different deployment name
1. Don't use LetsEncrypt; purchase a cert and upload it manually

**Comment by jlewi** [comment]
Closing as stale.
