### ISSUE TITLE
TFMA Dependency

### ISSUE THREAD

**Issue by zlcnju** [kubeflow/kubeflow#1745]
Related to:  [1576](https://github.com/kubeflow/kubeflow/issues/1576)

>I think it's not elegant idea to just modify install_tfma to no. 
It  is easy to add TFMA_VERSION and pip install the Specified version when build image. And this not only benefits the people use tf<1.9 with tfma,  and will make it easy when tfma dependecy changes.

**Comment by jlewi** [comment]
I agree any interest in picking this up?

**Comment by zlcnju** [comment]
@jlewi i will pick it up

**Comment by jlewi** [comment]
This has been fixed.
