### ISSUE TITLE
Error Creating Object: Pod in version "v1" cannot be handled as a Pod

### ISSUE THREAD

**Issue by gautamkmr** [kubeflow/kubeflow#1748]
I am trying to setup volume/volumemounts using ksonnet 

My PersistentVolume: nfs-data
My PersistentVolumeClaim: nfs-external 

In order to use this claim I follow https://github.com/kubeflow/kubeflow/issues/838 
1. Open the file
 CWD/vendor/kubeflow/openmpi\@XXXXXXXXXX/workloads.libsonnet . and in each Volume, VolumeMounts section add the below lines
    ###
       ] + params.volumes,
    ### 
       ] + params.volumeMounts,
    ### 
       ] + params.volumeMounts,

2. ks generate openmpi ${COMPONENT} --image ${IMAGE} --secret ${SECRET} --workers ${WORKERS} --gpu ${GPU} --exec "${EXEC}"

3. ks param set ${COMPONENT} volumes '[{ "name": "efs-pvc", "persistentVolumeClaim": { "claimName": " nfs-external" }}]'

4. ks apply default

    It returns following **error** 

INFO Applying configmaps horovod-benchmarks.openmpi-assets 
INFO Applying services horovod-benchmarks.openmpi 
INFO Applying serviceaccounts horovod-benchmarks.openmpi 
INFO Applying clusterrolebindings openmpi         
INFO Applying pods horovod-benchmarks.openmpi-master 
INFO Applying pods horovod-benchmarks.openmpi-worker-0 
INFO Creating non-existent pods horovod-benchmarks.openmpi-worker-0 
**ERROR handle object: creating object: creating object: Pod in version "v1" cannot be handled as a Pod: v1.Pod: Spec: v1.PodSpec: HostNetwork: ReadBool: expect t or f, but found ", error found in #10 byte of ...|Network":"false","ho|..., bigger context ...|sPolicy":"ClusterFirstWithHostNet","hostNetwork":"false","hostname":"openmpi-worker-0","restartPolic|...**

**Comment by gautamkmr** [comment]
@everpeace Any help?

**Comment by everpeace** [comment]
@gautamkmr it looks like normal yaml formatting error, not relates to `volumes`.

the error says

```
HostNetwork: ReadBool: expect t or f, but found "
```

your yaml is 
(error message kindly output your yaml though...)

```
"hostNetwork":"false"
```

the value MUST NOT be string as error said but MUST be boolean, i.e. `false` (without double quotation).

**Comment by everpeace** [comment]
by the way, I think released openmpi package doesn't set `hostNetwork` attribute.  Where does this come from?

**Comment by gautamkmr** [comment]
@everpeace  Thanks, actually I was using a custom version of kubeflow and realized it later.
