### ISSUE TITLE
kfctl generate k8s env.sh: No such file or directory

### ISSUE THREAD

**Issue by tlkh** [kubeflow/kubeflow#1749]
Hi everyone, on a fresh machine/minikube setup I am getting this error (which I have never encountered before). This is using the latest `0.3.0` release, by following the instructions on [https://www.kubeflow.org/docs/started/getting-started/](https://www.kubeflow.org/docs/started/getting-started/).

`
kubeflow/scripts/kfctl.sh: line 174: env.sh: No such file or directory
`

Below is the full output log (I included the `init` command; error is on the last output line of `generate k8s`):

```
nvaitc@nvaitc-DGX-Station:~$ ${KUBEFLOW_REPO}/scripts/kfctl.sh init ${KFAPP} --platform none+ COMMAND=init
+ WHAT=dgxkf
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname kubeflow/scripts/kfctl.sh
++ cd kubeflow/scripts
++ pwd
+ DIR=/home/nvaitc/kubeflow/scripts
+ source /home/nvaitc/kubeflow/scripts/util.sh
+ source /home/nvaitc/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/nvaitc/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' init == init ']'
+ DEPLOYMENT_NAME=dgxkf
+ '[' init '!=' '' ']'
+ case $1 in
+ shift
+ '[' dgxkf '!=' '' ']'
+ case $1 in
+ shift
+ '[' --platform '!=' '' ']'
+ case $1 in
+ shift
+ PLATFORM=none
+ shift
+ '[' '' '!=' '' ']'
+ mkdir -p dgxkf
+ cd dgxkf
+ createEnv
+ echo PLATFORM=none
++ cd /home/nvaitc/kubeflow/scripts/..
++ pwd
+ DEFAULT_KUBEFLOW_REPO=/home/nvaitc/kubeflow
+ KUBEFLOW_REPO=kubeflow
+ echo KUBEFLOW_REPO=kubeflow
+ echo KUBEFLOW_VERSION=master
++ pwd
+ echo KUBEFLOW_KS_DIR=/home/nvaitc/dgxkf/ks_app
+ echo KUBEFLOW_DOCKER_REGISTRY=
+ echo K8S_NAMESPACE=kubeflow
+ case "$PLATFORM" in
+ echo KUBEFLOW_CLOUD=null
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/nvaitc/dgxkf/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' -z dgxkf ']'
+ '[' -d dgxkf ']'
+ '[' -z none ']'
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/nvaitc/dgxkf/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' none == gcp ']'
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/nvaitc/dgxkf/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' -z init ']'
+ '[' -z dgxkf ']'
+ check_install ks
+ which ks
+ check_install kubectl
+ which kubectl
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/nvaitc/dgxkf/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' init == generate ']'
+ '[' init == apply ']'
+ '[' init == delete ']'

nvaitc@nvaitc-DGX-Station:~$ ${KUBEFLOW_REPO}/scripts/kfctl.sh generate k8s
+ COMMAND=generate
+ WHAT=k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname kubeflow/scripts/kfctl.sh
++ cd kubeflow/scripts
++ pwd
+ DIR=/home/nvaitc/kubeflow/scripts
+ source /home/nvaitc/kubeflow/scripts/util.sh
+ source /home/nvaitc/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/nvaitc/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' generate == init ']'
+ source env.sh
kubeflow/scripts/kfctl.sh: line 174: env.sh: No such file or directory
```

**Comment by jlewi** [comment]
What directory are you running in?

You need to cd to ${KFAPP} and run the kfctl commands from there.

**Comment by lluunn** [comment]
@r2d4 Matt could you explain a bit on what's the issue here and why removing statsd fixes this?

**Comment by r2d4** [comment]
@lluunn Sorry I meant a different bug! https://github.com/kubeflow/kubeflow/issues/1651
Apologies for the noise, I updated the PR to point to the right bug.

**Comment by lluunn** [comment]
ah I see

**Comment by ashahba** [comment]
Does it make sense to add a nice message and instruct the user to do something like `cd ${KFAPP}` prior to running `generate`? and also have `kfctl.sh` to check where `generate` is being called from and it not from the right directory instruct the user and stop processing rather than just complaining about file not found 🙂 
I think that'll be helpful as a user stand point.

If yes, feel free to assign it to me and I work on it.

**Comment by TimZaman** [comment]
Still an issue

**Comment by scttl** [comment]
This same error is also seen whenever a user attempts to run something like `kfctl.sh help` prior to having run `init` (reasonably likely for a new user trying to figure out what the command and its arguments do).

**Comment by ashahba** [comment]
Thanks @scttl 
The usage/help was slightly improved a bit during this PR: #1923 and on `master` it reads:
```
$ ./kfctl.sh help
usage: kfctl <command> <what>
where command is one of
init - initialize something
apply  -- apply some config
delete - delete some components

what is one of
project - the GCP project
platform - platform resources (e.g. GCP, minikube); basically non K8s resources
k8s - kubernetes resources
help - print this message
```
but it's not part of latest release `v0.3.4` but it'll be in `v0.3.5` 🤞 

Even the above help message could use some improvements, but an updated cli is on the way.

**Comment by aronchick** [comment]
Part of the weirdness here is the instructions say to set $KFAPP which seems and, if it's not set, the setup scripts fail in weird ways (e.g. because you can't cd to a directory that doesn't exist). We should really get out of this habit.

**Comment by guo897654050** [comment]
@tlkh i also meet this problem ,how to solve this problem

**Comment by tlkh** [comment]
> @tlkh i also meet this problem ,how to solve this problem

Seems it can be a directory issue if you manually `cd` wrongly somehow. Try restarting from scratch and follow the instructions more carefully.
