### ISSUE TITLE
Add gofmt and golangci-lint presubmits

### ISSUE THREAD

**Issue by r2d4** [kubeflow/kubeflow#1764]
For the go code in the repository

**Comment by jlewi** [comment]
Does the go linter have an easy way to output a junit file? If it does then it should be easy to surface the results in prow? 

We could ask the K8s engprod team what they do.

**Comment by r2d4** [comment]
There is this https://github.com/jstemmer/go-junit-report, I believe K8s has its own converter from `go test` to junit.

**Comment by jlewi** [comment]
Looks like there's an issue open in golangci-lint golangci/golangci-lint#373

**Comment by jlewi** [comment]
In kubeflow/tf-operator
We use Travis and gometlinter in kubeflow/tf-operator. If you're interested in picking that up it would be super impactful.

I think it would be better to use Prow but I think getting golint checks done is important enough that if it means starting with Travis and switching to Prow later that would be fine with me.

**Comment by jlewi** [comment]
It looks like prow has a plugin in to do golint checks.
https://prow.k8s.io/plugins

**Comment by scottilee** [comment]
@jlewi can this be closed?

**Comment by jlewi** [comment]
I think we can close this since we are now using the golint plugin.
Its not quite the same as a gofmt status check but I think its a good starting point.
