### ISSUE TITLE
Enable TPU in GKE

### ISSUE THREAD

**Issue by dsdinter** [kubeflow/kubeflow#1766]
It would be great to be able to leverage TPUs in our Kubeflow cluster if deploying in GKE.
I can work on that feature as I enabled that option already in my local version.
Believe we just need to modify the below two files within deployment_manager_configs:
cluster-kubeflow.yaml -> Add boolean option "tpu: false"
cluster.jinja -> Add settings to enable TPU and IP Aliases if tpu: true

**Comment by jlewi** [comment]
That would be great!
