### ISSUE TITLE
create a notebook controller that can replace jupyterhub and uses k8 native auth

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1769]
using metacontroller create a controller which takes a CRD that spawns a jupyter notebook for a user. Vet the design first, and demo the implementation. 

See related discussion #1630

**Comment by jlewi** [comment]
@kkasravi I think a CRD for managing notebooks would be great do you want to take a stab at this?

/unassign @jlewi 

Related to #1630 do we need jupyterhub?

**Comment by jlewi** [comment]
@kkasravi You're planning on tackling this; this week right?

**Comment by kkasravi** [comment]
@jlewi yes, i'll probably ping you tomorrow on the istio stuff
