### ISSUE TITLE
Feature Request + Help Wanted: Attach PVs to TFJob components

### ISSUE THREAD

**Issue by carmat88** [kubeflow/kubeflow#1782]
Hello Folks! After having followed the [introduction tutorial to Kubeflow](https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..%2Findex#0) on codelab, we are trying to deploy on a local k8s cluster by customizing it. In particular we would like to replace the training container with one of ours and thus apply the _tf-job_ component with a different image. However, in order to do so we would need to mount some host folders within the customized container image. Usually one could achieve this via the docker run command (passing some arguments), but as you can imagine this is not possible when using ksonnet (specifically the command `ks generate` and `ks apply`).

On the documentation page for the [TensorFlow Training](https://www.kubeflow.org/docs/guides/components/tftraining/), there is a section about "_Customizing the TFJob_" which says that:

> Typically you will want to change the following values
> 
> 1. Change the image to point to the docker image containing your code
> 2. Change the number and types of replicas
> 3. Change the resources (requests and limits) assigned to each resource
> 4. Set any environment variables
>5. **Attach PV’s if you want to use PVs for storage.**

And we are indeed interested in point n°5. However we are not really sure how to achieve this at the jsonnet level. There seems to be a similar effort for the _openmpi_ component done by another user (here is the issue: https://github.com/kubeflow/kubeflow/issues/838), but we reckon that a one-to-one solution cannot be directly applied to the _tf-job_ component/prototype.

Therefore, we are wondering if you could point us to any further documentation or existing examples where one attaches PV to a tf-job component. If none exists, then we would like to request to consider this as a default option for the tf-job prototype. We think this may be a very useful and relevant feature in particular when there is a local database within the cluster (mounted as a PV) to be used as input for training.

What do you think about it? Are we missing anything? Many thanks!

Cheers.

**Comment by jlewi** [comment]
You can just modify the TFJob spec. The TFJob spec contains PodTemplateSpec's which allow you to specify persistent volumes in order to mount volumes.

You can use ksonnet like this
https://github.com/kubeflow/examples/blob/master/github_issue_summarization/ks-kubeflow/components/tfjob-pvc-v1alpha2.jsonnet#L20

Or you could just write your own YAML file for TFJob spec and just use kubectl

**Comment by carmat88** [comment]
Hej @jlewi ! Great, that's all very clear. Thanks for further explaining it and for pointing us to the above link. It would be cool and useful to "toggle" this on/off by implementing a new flag for the _tf-job_ prototype. We'll try to fiddle with the TFJob spec as you suggested. Cheers!

**Comment by jlewi** [comment]
Glad to hear it.

We might add more command line options to the TFJob prototype. The problem is that everyone wants/needs different parameters. So figuring out which ones to add is tough. So we've been making it easier for users to modify the spec.
