### ISSUE TITLE
Errors when starting kubeflow with minikube

### ISSUE THREAD

**Issue by Nick-Harvey** [kubeflow/kubeflow#1802]
I'm attempting to get kubeflow up and running on my local machine and after examining the logs I'm getting several "Container not found in pod" errors

**Setup**
Machine: Macbook Pro 32GB RAM
VM details: Minikube via virtualbox, 8vcpu / 16gb ram / 50G disk
Kubeflow_tag: master 
Install process:  https://www.kubeflow.org/docs/started/getting-started-minikube/ 

**Symptoms** 
The quickstart script completes and I can access the dashboard via localhost. However, the kubernetes dashboard is inaccessible and throws a `upstream request timeout`, Can't seem to create TFjobs or JupyterHub resources 

**Errors**
`Oct 16 18:57:35 minikube kubelet[2980]: W1016 18:57:34.987929    2980 pod_container_deletor.go:77] Container "e7f5400864e0cfc0167e750e6e2aafb5c120a03b87f453b11f0b82ced96eacce" not found in pod's containers
Oct 16 18:57:35 minikube kubelet[2980]: W1016 18:57:35.116079    2980 pod_container_deletor.go:77] Container "6019dbdbd71559a80925af8a8e2904ee2c438fd99ffdceec8c6c5cefeff79000" not found in pod's containers
Oct 16 18:57:37 minikube kubelet[2980]: W1016 18:57:37.033395    2980 pod_container_deletor.go:77] Container "8c48edd6e5a6230ea216dd9dbdb42373076cf17d63462ceacc72befec9bc51fc" not found in pod's containers
Oct 16 18:57:37 minikube kubelet[2980]: W1016 18:57:37.917549    2980 container.go:393] Failed to create summary reader for "/system.slice/run-r8b92596a868b4e2c942dc273076bddf8.scope": none of the resources are being tracked.
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.894452    2980 pod_container_deletor.go:77] Container "877a1571b6be539a93b4f36185e2c3f01e2bf13568b1b605b7df2671ad1ba606" not found in pod's containers
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.928842    2980 pod_container_deletor.go:77] Container "d691ab9df4438044d7013b2c892af05296842b759206c6bf7ffefe1e3824ec30" not found in pod's containers
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.934061    2980 pod_container_deletor.go:77] Container "5ea08b59d45e3d8ef85c61629c3adec987a6b80418facdff39a3fb1f79906e33" not found in pod's containers
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.945325    2980 pod_container_deletor.go:77] Container "f52b92be48d9b693b7b73bf80d3acecd3fd8098c54eac03ae7f09ba2b10a24d1" not found in pod's containers
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.972235    2980 pod_container_deletor.go:77] Container "18098ac0707dd7408b0910db81431d983dd7214884a765eb45658dedf34a364e" not found in pod's containers
Oct 16 18:57:46 minikube kubelet[2980]: W1016 18:57:46.975970    2980 pod_container_deletor.go:77] Container "8923db20f87d55914772032bccf05e706d341957192d6d035339e8125ea92db0" not found in pod's containers
Oct 16 18:57:55 minikube kubelet[2980]: I1016 18:57:55.142852    2980 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-mlhfl" (UniqueName: "kubernetes.io/secret/4ffbed4c-d175-11e8-b6c9-08002753d444-default-token-mlhfl") pod "vizier-db-cc59bc8bd-67rk8" (UID: "4ffbed4c-d175-11e8-b6c9-08002753d444")
Oct 16 18:57:55 minikube kubelet[2980]: I1016 18:57:55.142902    2980 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-49d1ff78-d175-11e8-b6c9-08002753d444" (UniqueName: "kubernetes.io/host-path/4ffbed4c-d175-11e8-b6c9-08002753d444-pvc-49d1ff78-d175-11e8-b6c9-08002753d444") pod "vizier-db-cc59bc8bd-67rk8" (UID: "4ffbed4c-d175-11e8-b6c9-08002753d444")
Oct 16 18:58:05 minikube kubelet[2980]: W1016 18:58:05.784783    2980 pod_container_deletor.go:77] Container "be2b8951ab376fd817bd77d8d783e64c8ab7583bb2902ba49b4c30f8802b944d" not found in pod's containers
Oct 16 19:03:45 minikube kubelet[2980]: E1016 19:03:45.651941    2980 remote_runtime.go:278] ContainerStatus "d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65
Oct 16 19:03:45 minikube kubelet[2980]: E1016 19:03:45.651986    2980 kuberuntime_container.go:385] ContainerStatus for d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65 error: rpc error: code = Unknown desc = Error: No such container: d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65
Oct 16 19:03:45 minikube kubelet[2980]: E1016 19:03:45.651996    2980 kuberuntime_manager.go:873] getPodContainerStatuses for pod "tf-job-operator-v1alpha2-6566f45db-xbnn6_kubeflow(4065cbc9-d175-11e8-b6c9-08002753d444)" failed: rpc error: code = Unknown desc = Error: No such container: d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65
Oct 16 19:03:45 minikube kubelet[2980]: E1016 19:03:45.652010    2980 generic.go:241] PLEG: Ignoring events for pod tf-job-operator-v1alpha2-6566f45db-xbnn6/kubeflow: rpc error: code = Unknown desc = Error: No such container: d058921793e13ca59d223840c0bfcb0eff4163c8ffb8b1cb90d9c6b44fd14a65
Oct 16 19:12:16 minikube kubelet[2980]: I1016 19:12:16.950844    2980 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-60c4f34f-d177-11e8-b6c9-08002753d444" (UniqueName: "kubernetes.io/host-path/60c8dd9d-d177-11e8-b6c9-08002753d444-pvc-60c4f34f-d177-11e8-b6c9-08002753d444") pod "jupyter-admin" (UID: "60c8dd9d-d177-11e8-b6c9-08002753d444")
Oct 16 19:12:16 minikube kubelet[2980]: I1016 19:12:16.955799    2980 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "jupyter-notebook-token-zvf6f" (UniqueName: "kubernetes.io/secret/60c8dd9d-d177-11e8-b6c9-08002753d444-jupyter-notebook-token-zvf6f") pod "jupyter-admin" (UID: "60c8dd9d-d177-11e8-b6c9-08002753d444")
Oct 16 19:12:35 minikube kubelet[2980]: W1016 19:12:35.052714    2980 pod_container_deletor.go:77] Container "311859051f3c3d97560076b479ac07710303749d5352caf730af2ff362bac6b7" not found in pod's containers`

**Comment by r2d4** [comment]
Thanks for opening the issue @Nick-Harvey! 

* Can you make sure the pods are all running with `kubectl get po --all-namespaces`? 
* How are you trying to access the kubernetes dashboard in minikube? You should be able to run `minikube dashboard` to port-forward the dashboard to localhost.
* What version of minikube are you running?

**Comment by Nick-Harvey** [comment]
So I found the issue. My virtualbox setup was broken and I wasn't aware until I did some deep-dive into minikube. Long story short, I re-installed virtualbox & minikube and things are working just fine.
