### ISSUE TITLE
JupyterHub component -- issues with python envir/paths & installed libs

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#1803]
This is with KF v0.3.0, and the TF 1.7 CPU notebook image.
If I use the py2 kernel in a notebook:

![image](https://user-images.githubusercontent.com/115093/47044058-1976d680-d144-11e8-8104-1bbdd6aa3785.png)

The result is a situation where the notebook environment is py2, but the python in the path is py3.6. 

So if from the notebook the user shells out to run some script, or do a 'pip install', they are actually using py3.

![image](https://user-images.githubusercontent.com/115093/47043999-f0564600-d143-11e8-9854-a9974bd49e8e.png)

Also, via 'pip list', it doesn't seem like the py2 version has `tensorflow-transform` or `tensorflow-model-analysis` installed (not sure they run in py3), and IIRC, the py3 version didn't have `tensorflow-serving-api` installed.

**Comment by jlewi** [comment]
TFX components don't work with Python 3.

See #1718 for TFMA/TF.DV right now its only in 1.9.

**Comment by jlewi** [comment]
Anyone familiar with jupyter kernels? Is there a way to set the path when we change the kernel?

/cc @ojarjur @pdmack 
/cc @willingc

**Comment by amygdala** [comment]
@ojarjur how do you tell them?  
Almost no one reads the docs :), so if the info is not in the notebook itself, do you feel that they catch it? I'm guessing a lot of people won't realize to do that.  And then the errors will be mystifying, as they'll be left wondering why they did a 'pip install' and they still don't have the lib.

IMO it's much better just to make this kind of thing work out of the box, and not expect the user to know do an additional step. 
Colab has figured out how to do it -- could we ask them?

**Comment by jlewi** [comment]
Thanks @ojarjur 

@amygdala Yes that's a known issue right now its only in the 1.9 TF image. See #1718. We are working on getting this fixed.

**Comment by amygdala** [comment]
Is this an issue for the widgets as well?  In a TF 10.1 image I had to 
`/opt/conda/envs/py2/bin/pip install tensorflow-model-analysis` , and that seemed successful, but no plots are rendered.

**Comment by jlewi** [comment]
@amygdala TFMA should already be installed and the widgets should be working; which image were you using? see #1718

**Comment by amygdala** [comment]
Someone just hit this issue again, and reported that changing the conda envir worked, e.g:
```
%%bash
source activate py2
pip install ...
```

Maybe we should re-open this bug?
