### ISSUE TITLE
flaky configure_envoy_for_iap.sh

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1807]
Some times activate service account failed with ```There was a problem refreshing your current auth tokens: invalid_grant: Invalid JWT: No valid verifier found for issuer.```
Need to retry.

**Comment by jlewi** [comment]
#1847 added retry logic to activate the service account. I think this should fix the issue where service accounts don't work immediately.

@kunmingg Is there more work to do here or can we close this issue?

**Comment by kunmingg** [comment]
It's fixed
