### ISSUE TITLE
Not able to build from source: Makefile:17: recipe for target 'presubmit' failed

### ISSUE THREAD

**Issue by tech509201941** [kubeflow/kubeflow#1812]
I want to build kubeflow from source and deploy it in a container.
I used the setup instructions from over here:
https://www.kubeflow.org/docs/started/getting-started/

This is my docker container:

```
FROM ubuntu:16.04

ARG DOCKER_HOST=tcp://localhost:2375

RUN apt-get update
RUN apt-get install sudo
RUN sudo apt-get install -y curl gnupg apt-transport-https ca-certificates software-properties-common curl git bash make python wget autoconf

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ls

RUN wget https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz && tar xvfz go1.11.1.linux-amd64.tar.gz && sudo chown -R root:root ./go && sudo mv go /usr/local && . env/.profile && . env/.bash_profile

RUN cd .. && chmod -R +x app && cd app
RUN make && sudo make install

RUN bash

RUN ./scripts/kfctl.sh init kfapp_config --platform none
RUN ./scripts/kfctl.sh generate k8s
RUN ./scripts/kfctl.sh apply k8s
```

Everythings works except the "RUN make && sudo make install" part.
It fails with:

```
(...)
Boilerplate header is wrong for: /usr/src/app/bootstrap/cmd/bootstrap/app/options/options.go
Boilerplate header is wrong for: /usr/src/app/bootstrap/version/version.go
Makefile:17: recipe for target 'presubmit' failed
make: *** [presubmit] Error 1
The command '/bin/sh -c make && sudo make install' returned a non-zero code: 2
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

If I skip the making of the source, I encounter the following error at the part "RUN ./scripts/kfctl.sh init kfapp_config --platform none":

```
(...)
+ check_install ks
+ which ks
+ echo 'You don'\''t have ks installed. Please install ks.'
You don't have ks installed. Please install ks.
+ exit 1
The command '/bin/sh -c ./scripts/kfctl.sh init kfapp_config --platform none' returned a non-zero code: 1
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

Does anyone has an idea on how to address this issue?
Thanks a lot :)

**Comment by r2d4** [comment]
Are you running https://github.com/kubeflow/kubeflow/blob/master/Makefile?

```
all: presubmit

presubmit:
	@echo ">> checking file boilerplate"
	@./build/check_boilerplate.sh

TAG?=$(shell git rev-parse HEAD)
.PHONY: all presubmit
```

This is only running the boilerplate check and not used anywhere AFAIK. It should be safe to remove.

**Comment by tech509201941** [comment]
Hi r2d4,

you're right, I am trying to build from source on basis of the  makefile that is provided within the official github repo.

Unfortunately, I already tried to skip the make install process step but than occurs this error:
```
(...)
+ check_install ks
+ which ks
+ echo 'You don'\''t have ks installed. Please install ks.'
You don't have ks installed. Please install ks.
+ exit 1
The command '/bin/sh -c ./scripts/kfctl.sh init kfapp_config --platform none' returned a non-zero code: 1
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

So how do I install "ks "without building it via the makefile?
Thanks a lot :)

**Comment by r2d4** [comment]
ks is the ksonnet binary. You can download it from their release page. https://github.com/ksonnet/ksonnet/releases/tag/v0.11.0

ksonnet is a requirement for generating the configuration for deploying the kubeflow cluster.

**Comment by jlewi** [comment]
@tech509201941 What do you mean by build Kubeflow from source and run in a container.

Kubeflow is a collection of microservices deployed on Kubernetes. Running those microservices in a single container is not supported.

**Comment by r2d4** [comment]
/close

The makefile was removed, you should use kfctl.sh.
