### ISSUE TITLE
upgrade cloud-endpoints-controller to use metacontroller/metacontroller:v0.3.0

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1824]
see PR #1820

**Comment by kkasravi** [comment]
A complication is that cloud-endpoints is based on an image that was [uploaded](https://console.cloud.google.com/gcr/images/enisoc-kubernetes/GLOBAL/metacontroller@sha256:18561c63e1c5380ac5bbaabefa933e484bdb499f10b61071506f9a0070bc65f6/details?tab=info) last year 12-5-2017 and uses CRD's that no longer exist: lambacontrollers, initializercontrollers

@jlewi  would you know if the source for cloud-endpoints-controller is https://github.com/danisla/cloud-endpoints-controller ? 

It looks like the repo has been updated to work with the latest metacontroller. I can upgrade and test if this is the source repo. Alternatively I could look at replacing it with our own controller

**Comment by danisla** [comment]
The latest version of the cloud-endpoints-controller supports the CompositeController
