### ISSUE TITLE
create a self-serve component for data-scientists

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1842]
- [x] have all infra-components in a common namespace like 'kubeflow'
- [x] provide a CRD and controller so a datascientist can create one or more protected namespaces 
- [x] protected namespaces created by the data scientist allow 
  - [ ] jupyter notebooks to be run
  - [ ] tf-jobs to be run
  - [ ] tf-serving to be run 
  - [x] is secure such that only the data scientist can see it

**Comment by jlewi** [comment]
Chatted with @kkasravi about this.

This will allow users to spin up their own, isolated namespace for resources like notebooks, TFJobs, and models.

This is really great. So I'm tagging it P1 for 0.4.0

**Comment by kkasravi** [comment]
/cc @jlewi 

(fixing assignments)
