### ISSUE TITLE
Tooling to convert notebook to docker container

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1857]
We need tooling to convert a notebook into a docker container with a suitable entry point.

This is to support training and deploying models from Jupyter.

There are a number of approaches currently being explored
  * kubeflow/fairing - Uses metaparticle
   * r2d4 is exploring an approach based on modifying tarballs corresponding to Docker images and just adding a layer with the new file
   * @qimingj has done some work using Kaniko to build containers in cluster

/assign @r2d4

**Comment by jlzhao27** [comment]
s2i might be a good option here especially for dynamic languages like python: https://github.com/openshift/source-to-image

**Comment by jlewi** [comment]
@r2d4 It looks like you submitted; https://github.com/kubeflow/fairing/pull/9.

What are the next steps here?

**Comment by r2d4** [comment]
We need to cut a release, publish the the pip, and install it in our default notebook images in kubeflow. 

The repository should be working by itself now so any feedback would be appreciated!

**Comment by jlewi** [comment]
@r2d4 Any update on this? Should this be part of the 0.4 release process?

Would it be easier from a release perspective if our Jupyter images did a pip install using an http link to the fairing source? Then our Docker images could pin a specific version of the fairing lib pretty easily and we can cut out the step of publishing a pip package. (Though we might still want to publish a pip package).

**Comment by r2d4** [comment]
Yes to 0.4

Yes to http link. We can also publish a pip package but it will be much easier for us to reference by commit SHA and source.

**Comment by r2d4** [comment]
Closed by https://github.com/kubeflow/kubeflow/pull/2038
