### ISSUE TITLE
Jupyter widget to deploy and train models

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1858]
We'd like a Jupyter widget that gives a user a UI for training and deploying models directly from a notebook.

/cc @r2d4 @qimingj

**Comment by chrisheecho** [comment]
+1!

**Comment by charlesa101** [comment]
+1

**Comment by jlewi** [comment]
Anyone working on this?
Should we punt to 0.5?

**Comment by jlewi** [comment]
I'm going to downgrade this to P2 based on the CUJ:
http://bit.ly/cuj_train_deploy_notebook
