### ISSUE TITLE
Remove OpenMPI package in 0.5.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1859]
See comment:
https://github.com/kubeflow/kubeflow/issues/778#issuecomment-429847288

Current thinking is that MPI Job is a preferable solution to the OpenMPI ksonnet package. In 0.4.0 we want to start pointing users at MPIJob. In 0.5.0 we should plan on removing the package.

@everpeace WDYT? This is just my interpretation of your comment.

**Comment by everpeace** [comment]
SGTM.

**Comment by jiezhang** [comment]
We ended up not using openmpi package at Uber and instead built custom scheduler using Kubernetes Go client. I'm okay with removing the package.

**Comment by jlewi** [comment]
@jiezhang Can you share more about why you made that decision?
