### ISSUE TITLE
Docs for using ModelDB to track models using the API

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1861]
Related:
   kubeflow/examples#81

ModelDB has a lot of great features for model tracking
See screen cast on kubeflow/katib

In 0.4.0; I'd like to have docs on www.kubeflow.org that tell users how they can leverage ModelDB to track models by using the Python light API to load model data into Katib.

/cc @mpvartak
/cc @garganubhav

**Comment by jlewi** [comment]
Anyone working on this? If not should we punt to 0.5?

**Comment by mpvartak** [comment]
FYI, opened a PR this AM to make modeldb an independent package in KubeFlow
so it can be used from any component, not just Katib.

https://github.com/kubeflow/kubeflow/pull/2050

We can work on docs depending on the timeline for 0.4.0. What's the close
date for new patches?

**Comment by jlewi** [comment]
@garganubhav Any update on this?

**Comment by garganubhav** [comment]
done, plz review.
