### ISSUE TITLE
Disallow TFJob names with . (hangs on startup)

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#1870]
Two TensorFlow training jobs with identical configs except for difference in job name, "smokey-the-smoketest-etc" and "smokey-the-smoke.test-etc" - the former works fine, the latter hangs after:

```bash
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
```

perhaps because an address of the from `grpc://smokey-the-smoke.test-j1026-0013-b522-master-msse-0:2222` is not valid?

Should the inclusion of a `.` in a job name then cause a TFJob failure on startup with an error describing this issue, automatically format job names to be valid (e.g. convert . to -), or do nothing?

**Comment by gaocegege** [comment]
I think the name should follow [a-z]([-a-z0-9]*[a-z0-9], which is the convention in k8s. Then . should not be accepted by k8s. Could you create such a TFJob named `a.b`?

**Comment by jlewi** [comment]
If the job name is invalid it should never be created. What is the proper way to handle this kind of validation with CRDs?
