### ISSUE TITLE
Error from server (Forbidden): error when creating "deploy_crd.yaml": clusterroles.rbac.authorization.k8s.io "tf-job-operator" is forbidden

### ISSUE THREAD

**Issue by bbarnes52** [kubeflow/kubeflow#188]
Error from server (Forbidden): error when creating "deploy_crd.yaml": clusterroles.rbac.authorization.k8s.io "tf-job-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["tfjobs"], APIGroups:["kubeflow.org"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["*"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["*"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["*"]}] user=&{bgb@google.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]

I have already run `kubectl create clusterrolebinding default-admin --clusterrole=cluster-admin --user=bgb@google.com`

**Comment by jlewi** [comment]
deploy_crd.yaml is deprecated and has been removed; please use ksonnet.

Can you check your clusterrolebinding and default-admin privileges? The error message looks like an issue with [privilege escalation prevention](https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping)

**Comment by bbarnes52** [comment]
Moved to ksonnet.

Here's output of kubectl get clusterrolebindings:
kubectl get clusterrolebindings
NAME                                           AGE
cluster-admin                                  2h
default-admin                                  5m
event-exporter-rb                              2h
gce:beta:kubelet-certificate-bootstrap         2h
gce:beta:kubelet-certificate-rotation          2h
heapster-binding                               2h
kube-apiserver-kubelet-api-admin               2h
kubelet-cluster-admin                          2h
npd-binding                                    2h
system:basic-user                              2h
system:controller:attachdetach-controller      2h
system:controller:certificate-controller       2h
system:controller:cronjob-controller           2h
system:controller:daemon-set-controller        2h
system:controller:deployment-controller        2h
system:controller:disruption-controller        2h
system:controller:endpoint-controller          2h
system:controller:generic-garbage-collector    2h
system:controller:horizontal-pod-autoscaler    2h
system:controller:job-controller               2h
system:controller:namespace-controller         2h
system:controller:node-controller              2h
system:controller:persistent-volume-binder     2h
system:controller:pod-garbage-collector        2h
system:controller:replicaset-controller        2h
system:controller:replication-controller       2h
system:controller:resourcequota-controller     2h
system:controller:route-controller             2h
system:controller:service-account-controller   2h
system:controller:service-controller           2h
system:controller:statefulset-controller       2h
system:controller:ttl-controller               2h
system:discovery                               2h
system:kube-controller-manager                 2h
system:kube-dns                                2h
system:kube-dns-autoscaler                     2h
system:kube-scheduler                          2h
system:node                                    2h
system:node-proxier                            2h

**Comment by bbarnes52** [comment]
I am a bit confused by the docs - I know it assumes I have a cluster up and running, but what is unclear to me is, do I need to follow any of the steps here: https://github.com/tensorflow/k8s? E.g. what additional steps are required (beyond just spinning up a cluster and pointing kubectl at it) before I can complete the kubeflow quickstart successfully?

**Comment by jlewi** [comment]
No you don't need to complete  https://github.com/tensorflow/k8s kubectl takes care of all that.
