### ISSUE TITLE
create cluster-admin role for kubeflow:default service account so that it can create a tfjob

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#1882]
Somewhere in the setup config, we need to add:

`kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=kubeflow:default`

so that this is true:

`kubectl auth can-i -n kubeflow --as=system:serviceaccount:kubeflow:default create tfjobs`

**Comment by jlewi** [comment]
This is working as intended we want to run as least privilege.

The correct fix is to use a service account which has the appropriate TFJob RBAC permissions.

**Comment by etheleon** [comment]
I was not able to install kubeflow pipelines until I ran 

```
kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=kubeflow:default
```

**Comment by jlewi** [comment]
I'm going to close this out since I think the issue is stale; hopefully the issue is fixed by the latest version of kfctl.sh.
