### ISSUE TITLE
Dashboard cannot list tf jobs

### ISSUE THREAD

**Issue by matthen** [kubeflow/kubeflow#1883]
I followed the instructions to install 0.3 here:  https://v0-3.kubeflow.org/docs/started/getting-started-gke/ 

When I visit https://kubeflow.endpoints.PROJECT.cloud.goog/tfjobs/ui/#/ - I see *"There are no TFJobs to display"*. The logs for the `tf-job-dashboard` container have this error:

```
ERROR: logging before flag.Parse: W1029 05:04:06.118584 1 api_handler.go:127] failed to list TFJobs under all namespace(s): tfjobs.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow:tf-job-dashboard" cannot list tfjobs.kubeflow.org at the cluster scope: Unknown user "system:serviceaccount:kubeflow:tf-job-dashboard"
```

It looks like the service account exists:

```
$ kubectl get --namespace kubeflow  serviceaccount tf-job-operator
NAME              SECRETS   AGE
tf-job-operator   1         3d
```

Do I need to manually give permissions somewhere?

**Comment by matthen** [comment]
Thanks, that fixed it

**Comment by GitHub007Dra** [comment]
![image](https://user-images.githubusercontent.com/36945182/57605845-25bbf880-759a-11e9-8488-27908d577a65.png)

i have the same problem ..   plz  i need u help..
