### ISSUE TITLE
openmpi: resources for openmpi-controller are not configurable which breaks the multitenant use-case

### ISSUE THREAD

**Issue by AndriiNeverov** [kubeflow/kubeflow#1889]
The fix I which worked for me locally seemed to be quite simple:

1) add to containers#name: "openmpi-controller" the same thing as in  containers#name: "openmpi-job"

`resources: std.mergePatch($.resources(params, role), $.customResources(params, role)),`

2) adjust

`resources(params, role)::
    if role == ROLE_WORKER then {`

**Comment by jlewi** [comment]
@AndriiNeverov Do you want to submit a patch for this?
