### ISSUE TITLE
Delete components/tf-controller

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#189]
This directory should no longer be needed because we now use ksonnet.

**Comment by jlewi** [comment]
@nanliu interested?

**Comment by gaocegege** [comment]
BTW, do we need to set tensorflow/k8s as submodule in this repo?

**Comment by jlewi** [comment]
@gaocegege  see #190

**Comment by pdmack** [comment]
Closed by #216 no? Issue number should have been in the PR commit.
