### ISSUE TITLE
Deploy same components in click-to-deploy as kfctl

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/kubeflow#1892]
Standardize what we consider default core components and deploy the same way whether using kfctl or click-to-deploy. 

Example: argo is included in [kfctl](https://github.com/kubeflow/kubeflow/blob/v0.3.2/scripts/kfctl.sh#L236), but missing from click-to-deploy.

**Comment by kunmingg** [comment]
components config now synced on version v0.3.2

**Comment by texasmichelle** [comment]
Nice - that was fast. Thanks!!
