### ISSUE TITLE
[gcp] KsServer should support groups

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1894]
In the code here:
https://github.com/kubeflow/kubeflow/blob/af513c2da51cc0f589638e47234ca3b412dd646f/bootstrap/cmd/bootstrap/app/gcpUtils.go#L158

We are hardcoding whether we think an account is a user or group based on the name "google-kubeflow-support"

Instead we should rely on the user telling us this. E.g. in the config where user specifices users/group to grant access to the deployment they should include whether e.g. identity is a user, group or service account.

**Comment by jlewi** [comment]
I think we should punt to 0.5.

**Comment by carmine** [comment]
this may be a p2 vs p1 (agree that hardcoded isn't ideal, so leaving p1 for now)
