### ISSUE TITLE
Kubernetes Engine for Kubeflow Quickstart Guide - Proposed Fixes

### ISSUE THREAD

**Issue by IMBurbank** [kubeflow/kubeflow#1898]
I experienced a number of minor-bugs and unclear sections while completing this [quick-start guide](https://www.kubeflow.org/docs/started/getting-started-gke/).

The purpose of this issue is to detail my experiences throughout the process, and then make a few proposals for improving the guide.

## Process

Here's how the tutorial went for me on a relatively fresh GCP project. 

Note: steps to enable required API's aren't clear in the tutorial, but I didn't run into API issues as I've previously enabled all that were needed.

#### Set the consent screen and OAuthID

![01_consent_screen](https://user-images.githubusercontent.com/21133719/47811431-642f4b80-dd0b-11e8-9ce5-e75742806860.png)
![02_oauthid](https://user-images.githubusercontent.com/21133719/47811442-67c2d280-dd0b-11e8-866c-b803cae60f63.png)

#### Export Client ID & Secret

```bash
export CLIENT_ID=<CLIENT_ID from OAuth page>
export CLIENT_SECRET=<CLIENT_SECRET from OAuth page>
```

### Deploy Kubeflow on Kubernetes Engine

***Moving to cloud shell***

Instructions aren't clear on which coding environment should be used for this quickstart, but use of `gcloud` commands in `kfctl.sh` makes the cloud shell look like the most likely candidate.

***(Not listed) Boost Cloud Shell***

![03_boost_cloud_shell](https://user-images.githubusercontent.com/21133719/47811682-f59ebd80-dd0b-11e8-85c2-6e6294d7f352.png)

#### Set environmental variables (which variables to export is currently unclear in guide)

```bash
export PROJECT=stackoverflow-title-picker
export KUBEFLOW_REPO=$HOME/kubeflow
export KUBEFLOW_TAG=v0.3.1
export KFAPP=ks-kubeflow
```

#### Download Kubeflow

```bash
mkdir ${KUBEFLOW_REPO}
cd ${KUBEFLOW_REPO}
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
```

***Error: Directory KUBEFLOW_REPO already exists***

First error. Seven commands in this quickstart section call ${KUBEFLOW_REPO} as a variable, but the download script throws an error if KUBEFLOW_REPO is exported as an environmental variable.

```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   856  100   856    0     0   1104      0 --:--:-- --:--:-- --:--:--  1104
+ '[' '!' -z '' ']'
+ KUBEFLOW_TAG=v0.3.1
+ '[' -d /home/bassmanburbank/kubeflow ']'
+ echo Directory /home/bassmanburbank/kubeflow already exists
Directory /home/bassmanburbank/kubeflow already exists
+ exit 1
```

***Fix: unset KUBEFLOW_REPO***

```bash
unset KUBEFLOW_REPO

# Choose a variable that won't clash
export KUBEFLOW_DIR=$HOME/kubeflow

# This time the download will work
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
```

#### Init KFAPP

```bash
# Using KUBEFLOW_DIR variable to avoid previous naming collision
${KUBEFLOW_DIR}/scripts/kfctl.sh init ${KFAPP} --platform gcp --project ${PROJECT}
```

***Error: Ksonnet not installed***

Installing Ksonnet seems obvious, but it isn't mentioned as a pre-req anywhere in this guide. After reading issues [like this](https://github.com/kubeflow/kubeflow/issues/1854#issuecomment-433093130) making it clear that no initial cluster is to be started in this method (which I'd previously assumed would be needed after doing other tutorials), I reran this tutorial determined to follow instructions without adding any of my own steps that might derail the guide.

***Fix: Install Ksonnet***

```bash
export KS_VER=0.12.0
export KS_DIST=linux_amd64
export KS_PKG=ks_${KS_VER}_${KS_DIST}

mkdir ${HOME}/bin
curl -Lk https://github.com/ksonnet/ksonnet/releases/download/v${KS_VER}/${KS_PKG}.tar.gz \
	| tar xzv -C $HOME/bin/ ${KS_PKG}/ks --strip=1

export PATH=$PATH:${HOME}/bin/
ks version
```

```
ksonnet version: 0.12.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

```bash
# Init KFAPP now works
${KUBEFLOW_DIR}/scripts/kfctl.sh init ${KFAPP} --platform gcp --project ${PROJECT}
cd ${KFAPP}
```

#### Generate/Apply Platform

```bash
${KUBEFLOW_DIR}/scripts/kfctl.sh generate platform
${KUBEFLOW_DIR}/scripts/kfctl.sh apply platform
```

***Error: ImportError: No module named yaml***

Error and  python version used

```bash
~/kubeflow/ks-kubeflow
+ '[' -f /home/bassmanburbank/kubeflow/ks-kubeflow/gcp_config/network.yaml ']'
+ '[' -f /home/bassmanburbank/kubeflow/ks-kubeflow/gcp_config/gcfs.yaml ']'
+ python /home/bassmanburbank/kubeflow/scripts/gke/iam_patch.py --action=add --project=stackoverflow-title-picker --iam_bindings_file=/home/bassmanburbank/kubeflow/ks-kubeflow/gcp_config/iam_bindings.yaml
Traceback (most recent call last):
  File "/home/bassmanburbank/kubeflow/scripts/gke/iam_patch.py", line 17, in <module>
    import yaml
ImportError: No module named yaml
bassmanburbank@cloudshell:~/kubeflow/ks-kubeflow (stackoverflow-title-picker)$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
```

***Fix: Install python module pyyaml***

```bash
pip install pyyaml --user
```

```bash
# Re-apply platform - will now work
${KUBEFLOW_DIR}/scripts/kfctl.sh apply platform
```

#### Generate/Apply k8s

```bash
# Using my exported variable KUBEFLOW_DIR to avoid previous naming collision
${KUBEFLOW_DIR}/scripts/kfctl.sh generate k8s
${KUBEFLOW_DIR}/scripts/kfctl.sh apply k8s
```

***Error: RBAC issues***

```bash
+ ks apply default -c ambassador
INFO Applying services kubeflow.ambassador
INFO Creating non-existent services kubeflow.ambassador
INFO Applying services kubeflow.statsd-sink
INFO Creating non-existent services kubeflow.statsd-sink
INFO Applying services kubeflow.ambassador-admin
INFO Creating non-existent services kubeflow.ambassador-admin
INFO Applying roles kubeflow.ambassador
INFO Creating non-existent roles kubeflow.ambassador
ERROR handle object: creating object: creating object: roles.rbac.authorization.k8s.io "ambassador" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["create"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["update"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["patch"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["secrets"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["secrets"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["secrets"], Verbs:["watch"]}] user=&{BassManBurbank@gmail.com  [system:authenticated] map[user-assertion.cloud.google.com:[AGKDXmpUha/tPit787y7BaWMAxh0kDE/qTZX6fhduzR4k+8HdOZ9S4jEqXCi+UtSiKqbiuccR35lWgC5D3QmLcf2fpezPGteL5csXPcNtht1q+VEQ64fzoenyU5q0SD4MI+zwRQBbNzC9m5Vqk1M9W6AFlRZJAAsm2BQ94D5GmOm2Lk3v9gUOto2DjXQWa+fH3UC2a8eB5/lXvoZJLDvTemJRgxMmvUlrSa+jitfBJ3pIQ==]]} ownerrules=[PolicyRule{APIGroups:["authorization.k8s.io"], Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/openapi" "/openapi/*" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/"], Verbs:["get"]}] ruleResolutionErrors=[]
```

***Fix: Create `clusterrolebinding`***

This also touches on an [related issue](https://github.com/kubernetes/kube-state-metrics/pull/564/files) that GCP identity is case-sensitive while the `gcloud info` returned is lowercase. So if a user (like myself, for some reason) added capital letters to their email during the original setup, the standard method of getting the username through `$(gcloud config get-value account)` will not work. I imaging it will have to be grep'd from the IAM info. Here, I added it manually.

```bash
kubectl create clusterrolebinding kf-admin \
      --clusterrole=cluster-admin --user=BassManBurbank@gmail.com
```

```bash
# Re-Apply k8s
${KUBEFLOW_DIR}/scripts/kfctl.sh apply k8s
```

#### Almost There

```bash
kubectl -n kubeflow get  all
```

```
service/vizier-suggestion-random                 ClusterIP   10.63.243.215   <none>        6789/TCP         1m
service/whoami-app                               ClusterIP   10.63.250.86    <none>        80/TCP           44s

NAME                                                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ambassador                               3         3         3            3           2m
deployment.apps/argo-ui                                  1         1         1            1           1m
deployment.apps/centraldashboard                         1         1         1            1           2m
deployment.apps/cert-manager                             1         1         1            1           56s
deployment.apps/cloud-endpoints-controller               1         1         1            1           1m
deployment.apps/envoy                                    3         3         3            0           43s
deployment.apps/iap-enabler                              1         1         1            0           43s
deployment.apps/kube-metacontroller                      1         1         1            1           1m
deployment.apps/modeldb-backend                          1         1         1            1           1m
deployment.apps/modeldb-db                               1         1         1            1           1m
deployment.apps/modeldb-frontend                         1         1         1            1           1m
deployment.apps/pytorch-operator                         1         1         1            0           33s
deployment.apps/spartakus-volunteer                      1         1         1            1           1m
deployment.apps/studyjob-controller                      1         1         1            1           1m
deployment.apps/tf-job-dashboard                         1         1         1            1           1m
deployment.apps/tf-job-operator-v1alpha2                 1         1         1            1           1m
deployment.apps/vizier-core                              1         1         1            1           1m
deployment.apps/vizier-db                                1         1         1            1           1m
deployment.apps/vizier-suggestion-bayesianoptimization   1         1         1            1           1m
deployment.apps/vizier-suggestion-grid                   1         1         1            1           1m
deployment.apps/vizier-suggestion-hyperband              1         1         1            1           1m
deployment.apps/vizier-suggestion-random                 1         1         1            1           1m
deployment.apps/whoami-app                               1         1         1            0           43s
deployment.apps/workflow-controller                      1         1         1            1           1m

NAME                                                                DESIRED   CURRENT   READY     AGE
replicaset.apps/ambassador-7fb86f6bc5                               3         3         3         2m
replicaset.apps/argo-ui-7b6585d85d                                  1         1         1         1m
replicaset.apps/centraldashboard-f8d7d97fb                          1         1         1         2m
replicaset.apps/cert-manager-798d77c76                              1         1         1         56s
replicaset.apps/cloud-endpoints-controller-b55c586b6                1         1         1         1m
replicaset.apps/envoy-79ff8d86b                                     3         3         0         43s
replicaset.apps/iap-enabler-6565b855d6                              1         1         0         43s
replicaset.apps/kube-metacontroller-6d567f9fb4                      1         1         1         1m
replicaset.apps/modeldb-backend-69dfc464df                          1         1         1         1m
replicaset.apps/modeldb-db-6cf5bb764                                1         1         1         1m
replicaset.apps/modeldb-frontend-74b66f8dc8                         1         1         1         1m
replicaset.apps/pytorch-operator-76f89745c                          1         1         0         33s
replicaset.apps/spartakus-volunteer-b8bff585f                       1         1         1         1m
replicaset.apps/studyjob-controller-68f5948984                      1         1         1         1m
replicaset.apps/tf-job-dashboard-7cddcdf9c4                         1         1         1         1m
replicaset.apps/tf-job-operator-v1alpha2-6566f45db                  1         1         1         1m
replicaset.apps/vizier-core-d74cbfd98                               1         1         1         1m
replicaset.apps/vizier-db-cc59bc8bd                                 1         1         1         1m
replicaset.apps/vizier-suggestion-bayesianoptimization-788df66688   1         1         1         1m
replicaset.apps/vizier-suggestion-grid-76c648b78                    1         1         1         1m
replicaset.apps/vizier-suggestion-hyperband-5df8cf7bc8              1         1         1         1m
replicaset.apps/vizier-suggestion-random-65b9fd7c48                 1         1         1         1m
replicaset.apps/whoami-app-b7fb9f875                                1         1         0         43s
replicaset.apps/workflow-controller-59c7967f59                      1         1         1         1m

NAME                      DESIRED   CURRENT   AGE
statefulset.apps/tf-hub   1         1         2m

NAME                          DESIRED   SUCCESSFUL   AGE
job.batch/ingress-bootstrap   1         0            43s
```

***Error: envoy-ingress endpoint***

Incorrect endpoint.  Per quickstart instructions:

> - `<name>` and `<project>` must have the same values as set in the next step when you run the deployment script.
> - The deployment uses “kubeflow” by default for <name> but you can configure this with the environment variable DEPLOYMENT_NAME.

I didn't set a DEPLOYMENT_NAME variable, but `ktctl.sh apply k8s` created an envoy-ingress endpoint with the name `ks-kubeflow` instead of `kubeflow`

![04_envoy_error](https://user-images.githubusercontent.com/21133719/47817438-4669e280-dd1b-11e8-9a82-3fcfff0836b5.png)

***Fix: Update OAuth client ID web app***

Use `ks-kubeflow` instead of the originally recommended `kubeflow` for <name>

![05_updated_oauth](https://user-images.githubusercontent.com/21133719/47817796-37cffb00-dd1c-11e8-8278-b2bd50fdd9f5.png)

```bash
# Re-apply k8s
${KUBEFLOW_DIR}/scripts/kfctl.sh apply k8s
```

***Troubleshooting: envoy-ingress endpoint***

envoy-ingress endpoint URI can be clicked to login to service, but asterisk `*` at end of URI causes a `404` error.

```
https://ks-kubeflow.endpoints.stackoverflow-title-picker.cloud.goog/*
```

![06_no_ingress](https://user-images.githubusercontent.com/21133719/47818962-bfb70480-dd1e-11e8-9164-2a66b020c5a3.png)

I get a `404` error when I click through to the endpoint.

![07_404_error](https://user-images.githubusercontent.com/21133719/47819052-f5f48400-dd1e-11e8-9b5e-b818d9bf3406.png)

***Troubleshooting tip: Remove asterisk***

But, if I remove the asterisk, I'm redirected to the dashboard

![08_success](https://user-images.githubusercontent.com/21133719/47819079-06a4fa00-dd1f-11e8-8324-8a83fd6a28d6.png)

The asterisk seems to be there by design, but this also seems like useful additional information for the troubleshooting page `404` section.

## Proposals

- Add mention that no pre-existing cluster is required (i.e. no `gcloud containers clusters create` step from other tutorials)
- Update default <name> description during `consent screen` step to `ks-kubeflow`. (I named KFAPP `ks-kubeflow` and haven't checked whether this <name> comes from the APP, or if it is `ks-kubeflow` by default)
- Add step to move to cloud shell (and enable boost mode)
- Add Ksonnet as prereq at beginning of quickstart
- Change variable name KUBEFLOW_REPO in instructions - or in scripts - to avoid error
- Check for/install needed python modules (such as `pyyaml`) in scripts, list as pre-reqs or at least add mention to the quickstart [troubleshooting page](https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/)
- Add requirement for a `cluster-admin` user `clusterrolebinding`
- Change method to get username for IAM roles to a case-sensitive method, or add a section to the troubleshooting page mentioning the possible case-mismatch. 
- In troubleshooting 404 sections - explain what KUBEFLOW_FQDN is
- Add envoy-ingress `404` error (remove asterisk?) mention to troubleshooting page `404` section

I'm happy to put this into a PR if the proposed changes are acceptable.

**Comment by jlewi** [comment]
It might be helpful to split this up into separate issues. 

The KUBEFLOW_REPO issue in the docs looks like #1871 and might be fixed.

**Comment by jlewi** [comment]
download.sh complaining about directory already exists was fixed in #1873 on master; but it hasn't been cherry-picked onto 0.3.

**Comment by jlewi** [comment]
Adding ksonnet as a prerequisite to the docs seems like a good idea. A PR would be fantastic.

kfctl.sh should check if ks and other dependencies are installed and if not provide users with an error;
https://github.com/kubeflow/kubeflow/blob/v0.3-branch/scripts/kfctl.sh#L204

**Comment by jlewi** [comment]
That sounds great.

Any of the options for pyyaml seem reasonable to me.

I think the long term fix here is replacing kfctl.sh with a go binary (#1419).

**Comment by jlewi** [comment]
We also provide a click to deploy app now but need to add it to the docs; kubeflow/website#278. This avoids the need to install anything locally and thus bypasses a lot of these issues.

**Comment by jlewi** [comment]
@IMBurbank it looks like most of the issues in your most recent [comment](https://github.com/kubeflow/kubeflow/issues/1898#issuecomment-439517322)

Is there more work to be done? Or can we close this issue?

**Comment by IMBurbank** [comment]
Sorry for the delay, just getting back into the swing of things after the break. 

I plan to put in one more PR, but the changes will only impact documentation in the [kubeflow/website](https://github.com/kubeflow/website) repo. I don't think it's necessary to keep this open to track the doc changes. I'll refer back to this issue when I create the PR.

**Comment by jlewi** [comment]
Thanks.

**Comment by jlewi** [comment]
@IMBurbank is there another issue tracking your proposed fixes? Lets have an issue open to track this changes; either this one or another one.

**Comment by IMBurbank** [comment]
There isn't another open issue for tracking these. I'll get a PR in tonight to close this out.
