### ISSUE TITLE
Figure out Istio installation in Kubeflow

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1909]
We probably have to checkin the manifest.

https://www.kubeflow.org/docs/guides/components/istio/

**Comment by lluunn** [comment]
Things to configure:
- sidecar injection policy: I think we should label the kubeflow namespace so that sidecar is auto injected if we add proper annotation to the deployment
- egress: we should allow egress traffic to load model from GCS/S3. However, this needs to know the IP of the cluster, so differs from cluster to cluster, see https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly
- Istio ingressgateway: 
  - We want the gateway to sit behind ingress, so it should be NodePort instead of LoadBalancer. 
  - Maybe change the name
  - We will need some configuration setup for JWT validation later

**Comment by jlewi** [comment]
@lluunn What is the remaining work to be done to close out this issue?
