### ISSUE TITLE
Running Kubeflow on OpenShift without Admin Privileges

### ISSUE THREAD

**Issue by rummens** [kubeflow/kubeflow#1915]
Hi there,

I've got a few questions regarding Kubeflow on OpenShift. I stumbled across this instructions (https://opensource.com/article/18/6/kubeflow) to install everything but it requires admin Privileges at the last step to change some security settings. This is an issue, since we cannot grant KubeFlow cluster admin privs on our company cluster. 

So is there a way to install and run Kubeflow without the admin privs? If not why are these security changes required? Are they required only for installation or all the time?

Is there a plan for the future to remove this restriction?

Any while I am asking, is Kubeflow running on openshift container engine?

Thanks for any answer
Kind Regards
Marcel

**Comment by pdmack** [comment]
That article is now somewhat out of date and the latest installation instructions are [here](https://www.kubeflow.org/docs/started/getting-started/). I need to refresh some of the troubleshooting details for OpenShift itself.

Having said that, you will need cluster-admin privileges to deploy various components from Kubeflow. There are various operators and CRD which require ClusterRole. I believe that RoleBindings can be used in place of the ClusterRoleBindings but I need to do some more testing of that to prove it out.

**Comment by rummens** [comment]
Thanks for the reply but I cannot find any instructions for OpenShift on this page or am I missing something?

If I understand you correct, Admin Privs are only requried for the setup of Kubeflow . Once that is done, it can work without them?

Cheers
Marcel

**Comment by pdmack** [comment]
Correct, just for the initial setup. However, "initial setup" is a little elastic when it comes to Kubeflow. It's a toolkit and you can choose (or not) to make use of various components.

Sorry [this](https://www.kubeflow.org/docs/guides/troubleshooting/#openshift) is the link.

**Comment by apurva3000** [comment]
Is it possible to run this without the cluster-admin privs in future ? We have an openshift cluster running in our organization and I happen to be a normal user, without any admin privs. Now, we really want to try KubeFlow but are unable to do so.

**Comment by hexerei** [comment]
@pdmack the OpenShift setup documentation is more on project level. For initial kubeflow installation you would also have to run following command to allow the installing user to create resources on the OpenShift cluster:

`$ oadm policy add-cluster-role-to-user cluster-admin myuser`

**Comment by blsaws** [comment]
@pdmack I'm trying the commands you referenced in the last link you provided, but they are not solving the problem for me, except for pod tf-hub-0 which after restart, is now running.

The ambassador and modeldb-db pods are still failing with the same errors as before the 'oc adm policy add-scc-to-user' commands. Maybe modedb-db (mongodb) requires another command?

modeldb-db error:
2018-12-09T01:56:17.999+0000 I STORAGE  [initandlisten] exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating

ambassador error:
[2018-12-09 01:19:43.751][52][critical][main] source/server/server.cc:78] error initializing configuration '/ambassador/envoy-1.json': cannot bind '0.0.0.0:80': Permission denied

**Comment by durandom** [comment]
@blsaws I granted any-uid basically cluster wide 
```
oc adm policy add-scc-to-group anyuid system:authenticated
```
And after a while all pods came up successfull. Although I saw the same errors you've pasted. I had to manually kill the ambassador pods.

**Comment by dimm0** [comment]
I'm getting requests from users to install Kubeflow in our cluster, and so far the only way to install it is by creating an app with cluster-wide permissions.
I understand creating CRDs will require cluster admin, but in that case there should be a way to deploy certain components at cluster-level, and then give users permissions to create the needed workflow in their namespaces. Currently it's all-in-one. (I'm running in kubernetes, not openshift)

**Comment by zmhassan** [comment]
## Problem
Whenever users want to try kubeflow tf-operator they have to request cluster-admin access. This may limit chances for adoption. 

## Proposed solution
There currently is a technology called Operator Lifecycle Manager which is an operator that manages the install, upgrade and deployment of Operators. Initially the cluster-admin would setup the infrastructure but once its setup the user should be able to request tf-operator to be deployed to their namespace without needing to get cluster-admin access.

## Demo
I have a demo of this working and i would like to engage the community on their thoughts. Some end users may want to build workers with custom optimized  tensorflow wheel files. I would like to try that as well.

When Can I demo this to the community?

**Comment by dimm0** [comment]
Any updates?

**Comment by lluunn** [comment]
@dimm0 We are working on multi-user support in 0.6 (Q2).
Basically, after admin deploying Kubeflow, a (non-admin) new user should first create a "profile", and then some controller will create a namespace a bunch of resources in that namespace. That user will only have access in his/her own namespace.
Is this what you are looking for?

**Comment by dimm0** [comment]
Yes

**Comment by suredream** [comment]
Any timeline for 0.6?

**Comment by lluunn** [comment]
0.6 is for Q2, end of June

**Comment by dimm0** [comment]
Why is this closed? Is function implemented?

**Comment by rummens** [comment]
Sorry I cleaned up my Issue List, must have accidentally clicked on the close button.

**Comment by apurva3000** [comment]
Any update on this ?

**Comment by davidparks21** [comment]
Hi, I'm a user under the k8s cluster dimm0 manages. We have built v0.6.0-rc1 here but the installation procedure still seems to require cluster-wide admin privileges from what we can tell. Any update on whether the ability to install to a namespace made it into v0.6.0-rc1, and if so how we go about enabling that?

Related issue: https://github.com/kubeflow/kubeflow/issues/3509

Thanks!
David

**Comment by richardsliu** [comment]
@davidparks21 Looks like this is a different feature request. V0.6.0 introduces multi-user profiles which allow non-admin users to create resources in their own namespaces, but the initial installation still has to be done with cluster-admin privileges.

Please also see https://github.com/kubeflow/kubeflow/issues/3623, which is about allowing the controller to access a set of namespaces in the cluster. This is also not supported yet (likely coming in 0.7).
