### ISSUE TITLE
ksonnet env should override params

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1924]
currently many libsonnet files have the following
```
    local params = _env + _params,
```

however this should be switched to 
```
    local params = _params + _env,
```
so that env values override param values

**Comment by jlewi** [comment]
@kkasravi Can you explain the issue? Its not clear to my why env should override parameters? I would actually not expect env to contain parameters that would also be defined in params. So I wouldn't expect the order to matter.
