### ISSUE TITLE
feature request: include 'google-api-python-client' in the JH images

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#1932]
It would be useful to bundle the `google-api-python-client` lib in the JupyterHub images.
E.g. for writing scripts that connect to GCP products like CMLE.

**Comment by jlewi** [comment]
We do install the newer google-cloud library
https://github.com/kubeflow/kubeflow/blob/bf94de1c209483f84196802a8e26f5fc12b75aab/components/tensorflow-notebook-image/requirements.txt#L18

**Comment by lluunn** [comment]
Do you mean adding to notebook images?
Hub doesn't need to do anything other than spawning notebook I think?
