### ISSUE TITLE
Add GPU Support for k8s-model-server on Kubeflow

### ISSUE THREAD

**Issue by bkungfoo** [kubeflow/kubeflow#194]
As a feature request, adding GPU support for TF-serving in Kubeflow can help speed up batch predictions that can take a long time to run on a CPU-only machine. Unfortunately, existing docker images, such as the one from the TF-serving repository, do not build correctly (or are not well-maintained): https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

It would be good to have kubeflow maintain a working GPU docker image that can be deployed with the k8s-model-server.

**Comment by DjangoPeng** [comment]
Cool! It's very helpful to speed up the inferencing and prediction work.

**Comment by flx42** [comment]
It's @flx42 :)

**Comment by jlewi** [comment]
As part of this issue we should create an Argo workflow to build and test this Docker image as in #214.

**Comment by jlewi** [comment]
Opened up:

#291 E2E test for TFServing with GPUs.
#292 Add GPU support to ksonnet packages.
