### ISSUE TITLE
Deployment failure: ERROR reading app configuration: Current app uses unsupported spec version '0.3.0' 

### ISSUE THREAD

**Issue by smartnose** [kubeflow/kubeflow#1944]
Trying out by following the official docs 'Getting Started': https://www.kubeflow.org/docs/started/getting-started/
Hitting a deployment issue on Ubuntu + Minikube (but not Mac + Minikube)

Versions:
Minikube: 1.8.0
ks: ks_0.12.0_linux_amd64
kubeflow: 0.3.1
ubuntu: 16.04

Followed the instructions to the letter (I think), but getting the following error message:
ERROR reading app configuration: Current app uses unsupported spec version '0.3.0' (this client only supports [>= 0.0.1 <= 0.2.0])

**Comment by jlewi** [comment]
I'm curious how you created the ksonnet application? 

If you followed the getting started instructions, you should be using your locally installed version of `ks` to create the ksonnet app. So I'm not sure how you ended up with a v0.13 app (0.3.0) if you created it with 0.12.

The only thing I can think of is if the minikube scripts are somehow downloading a different version of ks and using that to create the app and then a later part of the script uses the locally installed version.

@smartnose 

> net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

Seems like ksonnet is having problems trying to connect to your K8s master.

@hackenzheng @smartnose were you ever able to get past these problems?
