### ISSUE TITLE
Add e2etest for katib

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#1946]
Since we are installing katib by default, we need to make sure that the component works end to end. 

This will prevent issues like https://github.com/kubeflow/kubeflow/issues/1903 where the manifests are out of date and examples do not work properly.

**Comment by jlewi** [comment]
@richardsliu I assume this won't make it to 0.4? We will need to move it to 0.5?

**Comment by jlewi** [comment]
I'm tagging this into project 0.4 and 0.5.

Ideally we'd get this fixed and cherry picked onto the 0.4 branch so we know whether Katib is working in 0.4.
