### ISSUE TITLE
Cant spawn notebook server: ImagePullBackOff server

### ISSUE THREAD

**Issue by GdMacmillan** [kubeflow/kubeflow#1948]
I followed this guide to build a custom image:
[Customize docker image](https://github.com/kubeflow/kubeflow/tree/master/components/jupyterhub)

After pushing to google cloud registry, I'm unable to start a custom jupyterhub notebook server. It works when i let the spawner use the default image. The gcr repository has the same project name as the kubeflow app. We followed the quick start to get kubeflow running.

Does anyone know what the heck I'm doing wrong?
### Logs
`kubectl -n kubeflow logs jupyter-a-2e0-2espin-40gmail-2ecom`
Error from server (BadRequest): container "notebook" in pod "jupyter-a-2e0-2espin-40gmail-2ecom" is waiting to start: trying and failing to pull image

### Describe pod
`kubectl -n kubeflow describe pod jupyter-a-2e0-2espin-40gmail-2ecom`
Name:         jupyter-a-2e0-2espin-40gmail-2ecom
Namespace:    kubeflow
Node:         gke-hpakf-default-pool-5a22193e-tkz1/10.142.0.2
Start Time:   Tue, 13 Nov 2018 13:40:08 -0700
Labels:       app=jupyterhub
              component=singleuser-server
              heritage=jupyterhub
Annotations:  hub.jupyter.org/username: accounts.google.com:a.0.spin@gmail.com
Status:       Pending
IP:           10.52.3.42
Containers:
  notebook:
    Container ID:
    Image:         gcr.io/optfit-kaggle/jupyterhub-k8s:v20181112-87e2661a
    Image ID:
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      start-singleuser.sh
      --ip="0.0.0.0"
      --port=8888
      --allow-root
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     500m
      memory:  1Gi
    Environment:
      JUPYTERHUB_API_TOKEN:            7c39034a0d7e47188cc881193abb916e
      JPY_API_TOKEN:                   7c39034a0d7e47188cc881193abb916e
      JUPYTERHUB_CLIENT_ID:            jupyterhub-user-accounts.google.com%3Aa.0.spin%40gmail.com
      JUPYTERHUB_HOST:
      JUPYTERHUB_OAUTH_CALLBACK_URL:   /user/accounts.google.com%3Aa.0.spin@gmail.com/oauth_callback
      JUPYTERHUB_USER:                 accounts.google.com:a.0.spin@gmail.com
      JUPYTERHUB_API_URL:              http://tf-hub-0:8081/hub/api
      JUPYTERHUB_BASE_URL:             /
      JUPYTERHUB_SERVICE_PREFIX:       /user/accounts.google.com%3Aa.0.spin@gmail.com/
      MEM_GUARANTEE:                   1Gi
      CPU_GUARANTEE:                   500m
      GOOGLE_APPLICATION_CREDENTIALS:  /var/run/secrets/sa/user-gcp-sa.json
    Mounts:
      /home/jovyan from volume-a-2e0-2espin-40gmail-2ecom (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jupyter-notebook-token-bpfrg (ro)
      /var/run/secrets/sa from user-gcp-sa (rw)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  volume-a-2e0-2espin-40gmail-2ecom:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-a-2e0-2espin-40gmail-2ecom
    ReadOnly:   false
  user-gcp-sa:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  user-gcp-sa
    Optional:    false
  jupyter-notebook-token-bpfrg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jupyter-notebook-token-bpfrg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                       From                                           Message
  ----     ------   ----                      ----                                           -------
  Normal   BackOff  5m16s (x1378 over 5h25m)  kubelet, gke-hpakf-default-pool-5a22193e-tkz1  Back-off pulling image "gcr.io/optfit-kaggle/jupyterhub-k8s:v20181112-87e2661a"
  Warning  Failed   11s (x1400 over 5h25m)    kubelet, gke-hpakf-default-pool-5a22193e-tkz1  Error: ImagePullBackOff

### Ksonnet version
`ks version`
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

### kubernetes version
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jlewi** [comment]
Closing as obsolete.
