### ISSUE TITLE
Error deploying Kubeflow using kfctl.sh with --platform gcp

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#1949]
I was following kubeflow quick start https://www.kubeflow.org/docs/started/getting-started/
with following commands 
```
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform gcp
cd ${KFAPP}
${KUBEFLOW_SRC}/scripts/kfctl.sh generate k8s
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
```

I got 
```
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/var/folders/gh/c2y98znj15bgzc6pzm6vf7_8009q7y/T/ksonnet-mergepatch281316199": no matches for kind "BackendConfig" in version "cloud.google.com/v1beta1"
```
Did I miss anything? Do I need to configure IAP?

kubeflow version v0.3.1
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.7", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-11-02T23:07:38Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by IronPan** [comment]
Looks like BackendConfig is only available >1.10.5-gke.3?
https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

**Comment by IronPan** [comment]
I tried the 1.11.2-gke.15 and it worked fine. 

Can we please have good document on the deployment? This is critical for pipeline deployment to rely on it. 

Some of the missing piece I see are 

- what parameters are available?  --platform gcp is not mentioned in the document
- what GKE version is supported?
- I need to create a clusterrolebinding to bind my google account to cluster admin to deploy. It's not mentioned in the doc. 

cc @vicaire

**Comment by jlewi** [comment]
@IronPan It looks like in your original issue. You didn't run the generate & apply steps for the platform steps.

If you don't run those steps then you would need to setup all the GCP infrastructure (e.g GKE cluster) yourself.

As @kunmingg mentions above the recommendation is to follow our GCP instructions so that kfctl creates all the GCP infrastructure.

**Comment by IronPan** [comment]
Thanks guys I think it works after I switch to use the instruction here 
https://www.kubeflow.org/docs/started/getting-started-gke/#deploy-kubeflow-on-kubernetes-engine
