### ISSUE TITLE
Increase rate limit for installing kubeflow packages

### ISSUE THREAD

**Issue by bbarnes52** [kubeflow/kubeflow#195]
Trying to install kubeflow packages with ksonnet twice in the same hour yields rate limit errors:

ERROR GET https://api.github.com/repos/kubeflow/kubeflow/contents/kubeflow/tf-serving/prototypes?ref=3c969e873d7d619b72017ab103545b612464bcdc: 403 API rate limit of 60 still exceeded until 2018-02-01 16:24:27 -0800 PST, not making remote request. [rate reset in 39m58s]

This limit seems excessively low to me, makes it very challenging to create a new environment to troubleshoot, for example.

**Comment by gaocegege** [comment]
Ksonnet support GitHub Token to solve it. The PR is https://github.com/ksonnet/ksonnet/pull/201 and the doc is here: https://github.com/ksonnet/ksonnet/blob/master/docs/troubleshooting.md#github-rate-limiting-errors

**Comment by gaocegege** [comment]
Thanks for your issue and I think we could add the rate limit solution into our doc.
