### ISSUE TITLE
Create a pipelines ksonnet package

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1965]
We should create a ksonnet package to deploy kubeflow.

There's a ksonnet package here:
https://github.com/kubeflow/pipelines/tree/master/ml-pipeline/ml-pipeline

So we just need to copy or move it to our main registry.

/assign @IronPan

**Comment by jlewi** [comment]
#1973 added a pipeline registry
#1981 added pipelines to kfctl.sh

@IronPan Is there more to do here?

**Comment by IronPan** [comment]
Fixed by 
https://github.com/kubeflow/kubeflow/pull/1973
https://github.com/kubeflow/kubeflow/pull/1981

**Comment by IronPan** [comment]
@jlewi I think that's it. Marked this as completed
