### ISSUE TITLE
Deploy pipelines as part of kfctl.sh

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1966]
We'd like to deploy pipelines using kfctl.sh

Once #1965 is fixed, we just need to add the appropriate ksonnet commands to kfctl.sh

This should largely be the commands in 
https://github.com/kubeflow/pipelines/blob/master/ml-pipeline/kf_deploy.sh

**Comment by jlewi** [comment]
#1981was submitted.

@IronPan is there more to do here?

**Comment by IronPan** [comment]
This can be closed as the work is done and tested by 
https://github.com/kubeflow/kubeflow/pull/1981
