### ISSUE TITLE
Integrate pipelines into Kubeflow click to deploy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1967]
We'd like to be able to deploy pipelines with Kubeflow click to deploy web app.

I think this is blocked on #1965 (create a pipelines ksonnet package).

Once we have that package I think we'll need to 

1. Cherry pick it onto the 0.3 branch
    * We should probably cherry pick the fix to #1966 (kfctl.sh support) as well
1. Create a new RC
1. Update the click to deploy app to use the new release

Alternatively, rather than cherry picking it onto 0.3 we could create an early RC for 0.4.

**Comment by IronPan** [comment]
The code change is done by https://github.com/kubeflow/kubeflow/pull/1981

I think @kunmingg is helping out with new RC.

**Comment by jlewi** [comment]
@kunmingg Any update on this?

**Comment by IronPan** [comment]
@jlewi @kunmingg 
I'm initiating a release for Pipeline and hopefully can get v0.13 release by tomorrow. 

Once that's done we just need to bump the version for pipeline in kubeflow core and SDK in jupyter image. I think that is all the changes needed from pipeline

**Comment by jlewi** [comment]
@IronPan @kunmingg Can we close this issue? Is there more work to be done?

**Comment by kunmingg** [comment]
v0.3.4 available now
