### ISSUE TITLE
Install pipelines SDK in Jupyter images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1968]
We should install the pipelines SDK in our Jupyter images so that pipelines can be used.

/assign @qimingj

**Comment by qimingj** [comment]
Basically we need to install KFP SDK on all images (probably https://github.com/kubeflow/kubeflow/tree/76107ff3aa7f9fde6fd7f15f2ec0a69a35874efa/components/tensorflow-notebook-image).

We are finalizing a few things in SDK and I will cut a new release later this week or early next week. Then we can start the integration.

What's the release cadence of these images?

**Comment by IronPan** [comment]
@jlewi could you confirm this the right place to pip install the DSL?
https://github.com/kubeflow/kubeflow/blob/76107ff3aa7f9fde6fd7f15f2ec0a69a35874efa/components/tensorflow-notebook-image/Dockerfile

The SDK release is currently part of pipeline deployment. So the release process would be
1. cut a pipeline release 2. update the jupyter dockerfile and ks registry 3. cut a kubeflow release

does that sounds right?

**Comment by abhi-g** [comment]
@qimingj we can cherry pick into the v0.3.4 patch release

**Comment by kunmingg** [comment]
@IronPan 
here defines available images when start new notebook.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/ui/default/config.yaml
Can edit it once post-submit of https://github.com/kubeflow/kubeflow/pull/2008 is done

**Comment by IronPan** [comment]
I saw that the new notebook images are created with tag v-base-b5bfe47-920
Feel free to create a new release. Close this for now

**Comment by jlewi** [comment]
https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-1.11.0-notebook-cpu@sha256:d570b9351103056c2ea6b9509f27577c8a5f7a43803018852b28fb17f929f66a/details?tab=info
