### ISSUE TITLE
Make https://hub.docker.com/r/kubeflow/jupyterhub/ a community resource

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#197]
The repo is currently owned by:  @carmark has agreed to make it a community resource once we're ready.

Once we have gsuite setup for kubeflow.org we should create an appropriate group with appropriate members and ask xuelei to share the docker hub repo with it.

**Comment by gaocegege** [comment]
FYI Lei Xue's GitHub ID is @carmark

**Comment by carmark** [comment]
@gaocegege Thanks.
@jlewi Could u please use the github ID instead of email?

**Comment by jlewi** [comment]
Sorry didn't know your GitHub id.

**Comment by carmark** [comment]
NP, thanks.

**Comment by jlewi** [comment]
@carmark How does DockerHub permissions work? I don't suppose it uses GoogleGroups?

**Comment by jlewi** [comment]
Can we use a service account to automate pushing to DockerHub?

**Comment by carmark** [comment]
@jlewi Yeah, we may create one service account to do that, and create some automate building on docker hub based on the Dockerfile.  I can setup it if you think is all right.

**Comment by jlewi** [comment]
@carmark So my thinking is that we should use prow to trigger Argo workflows and use the Argo workflow to build and push Docker images. 

I think the advantage of using Argo over DockerHub or GCB is that its K8s native. Its also easier to add E2E testing of the image before pushing it. 

What do you think?

If we do it this way how do we authenticate to DockerHub? Do we use a service account with secret key?

We will use a K8s cluster in GCP project kubeflow-ci for our continuous builds. Its not fully setup yet; see kubeflow/testing#18.

In the meantime is there anything on the DockerHub side to be done?

**Comment by carmark** [comment]
@jlewi It is better to test before pushing the docker hub, I can not agree any more.  If we do that as this way, we need a service account which has a username and password, and then I will set the permission on that account.  So the work on DockerHub is simple, I can do that anytime.

**Comment by jlewi** [comment]
The Argo workflow for building the images is here
https://github.com/kubeflow/kubeflow/tree/master/releasing/releaser

But we probably don't want to add it directly to that Argo workflow because those images won't be tested yet.

I think the next steps would be

1. Create a DockerHub account "kubeflow-releaser"
2. Create a simple script to pull a list of our images and push them to DockerHub
 
@carmark Do you think you could work on this?

For the email account for the DockerHub account you could use "release-team@kubeflow.org" This is a google group that will be used for folks who manage releases and have access to our release infrastructure.

If you message me with your email I will add you.

**Comment by jlewi** [comment]
@carmark Is [kubeflow](https://hub.docker.com/u/kubeflow/) a single user? Is that the correct way to manage docker images for a project? Should we be using an organization.

**Comment by carmark** [comment]
Hi @jlewi 
The [kubeflow](https://hub.docker.com/u/kubeflow/) is a organization, and there are some users in it.

**Comment by jlewi** [comment]
@carmark Could you add me as an admin? My dockerhub id is jlewigoogle

**Comment by jlewi** [comment]
I was added as an owner.

So I think the next thing to do is to figure out how to setup robot accounts to build and push the images.

**Comment by jlewi** [comment]
Closing this out because kubeflow is an org in DockerHub and we can add users as needed.
