### ISSUE TITLE
[gcp-click-to-deploy]: migrate frontend configs & logics to backend 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#1971]
To allow more diversity among different kubeflow versions:
* Backend should determine the [config of deployed ks apps](https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/manifest/kf_app.yaml#L12) by kubeflow version user choose.
* Backend should determine the set of APIs to enable by kubeflow version user choose, and take care the enabling logic.

**Comment by kunmingg** [comment]
Here is create body:
https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L464

**Comment by jlewi** [comment]
@kunmingg What is the status of this? Will this be in 0.4 or should we move this to 0.5?

**Comment by jlewi** [comment]
@kunmingg Any update on this?

**Comment by kunmingg** [comment]
Moved to 0.5.0.

**Comment by kunmingg** [comment]
Will covered by new deployment API effort. 
Remove from v0.5.0
