### ISSUE TITLE
TFServing template needs to convert numGpus from string to int

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1972]
Here
https://github.com/kubeflow/kubeflow/blob/41050ef854948600ef7f922f2a3c295b60b1f7c0/kubeflow/tf-serving/tf-serving-template.libsonnet#L15

We compare numGpus to a string. This check will fail if numGpus is an integer.

We should be converting numGpus to an int always (since parameters can be strings) and then use integer comparison.

**Comment by lluunn** [comment]
I thought ksonnet params are always string type?

**Comment by jlewi** [comment]
@lluunn It depends on how the parameters are set; if they are set via `ks param set` they will be string. But user could also directly edit params.jsonnet and then it might be an int.

**Comment by lluunn** [comment]
ah I see, will fix this
