### ISSUE TITLE
e2e test for http-proxy

### ISSUE THREAD

**Issue by yupbank** [kubeflow/kubeflow#198]
Follow up of this https://github.com/kubeflow/kubeflow/pull/183

To Do
  - [x] ksonnet template
  - [ ] E2E tests
  - [x] Documentation explaining how to use it
  - [ ] Discussion of the API

**Comment by jlewi** [comment]
/assign @lluunn 

@lluunn Do we have E2E tests yet for the http proxy?

**Comment by lluunn** [comment]
not yet for the http proxy

**Comment by jlewi** [comment]
@lluunn @yupbank Any update? Do we have E2E tests yet for the HTTP Proxy?

**Comment by yupbank** [comment]
hey.. sorry, i was struggling with the argo + prow and log dashboard.. maybe @lluunn can do this easier than me ? i can definitely learn from what @lluunn did to know how the how testing setup easily

**Comment by lluunn** [comment]
Sure I will add the test.

**Comment by jlewi** [comment]
I closed #567 since it hadn't been updated in a while. We can reopen it or create a new PR when ready.
