### ISSUE TITLE
Missing scope in CRD spec?

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1985]
I was trying [Gitop deployment](https://www.kubeflow.org/docs/guides/gitops-for-kubeflow/),
and got error when applying:

```
KIND                      NAME                                    STATUS     HEALTH   HOOK  OPERATIONMSG
CustomResourceDefinition  pytorchjobs.kubeflow.org                OutOfSync  Missing        error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
CustomResourceDefinition  studyjobs.kubeflow.org                  OutOfSync  Missing        error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
CustomResourceDefinition  tfjobs.kubeflow.org                     OutOfSync  Missing        error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
```

**Comment by lluunn** [comment]
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

Seems there should be a scope field in CRD spec, but not sure how we didn't get error.
Maybe because I am using k8s 1.11 here.

**Comment by lluunn** [comment]
Similar to #1524

**Comment by jlewi** [comment]
@lluunn Are you deploying from master branch?

Any idea why are tests aren't catching this?

**Comment by jlewi** [comment]
For pytorch looks like we might not be setting scope;
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pytorch-job/pytorch-operator.libsonnet

I suspect we might have been relying on the default value but with 1.11 things change.
