### ISSUE TITLE
Installation woes - ./kfctl.sh: line 189: env.sh: No such file or directory

### ISSUE THREAD

**Issue by magick93** [kubeflow/kubeflow#1993]
Hello

I previously ran into the issue described on https://github.com/kubeflow/kubeflow/issues/1530 - but then tried using a relative folder, and was able to successfully run `${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none`. 

However, the next command again failed with a `No such file or directory` error.

```
./kfctl.sh generate k8s
+ COMMAND=generate
+ WHAT=k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname ./kfctl.sh
++ cd .
++ pwd
+ DIR=/home/anton/git/kubeflow/scripts
+ source /home/anton/git/kubeflow/scripts/util.sh
+ source /home/anton/git/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/anton/git/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' generate == init ']'
+ source env.sh
./kfctl.sh: line 189: env.sh: No such file or directory
```

However, in the actually a `env.sh` file:

```
↵ 1  ~/git/kubeflow/scripts                                                                                      9.4.0 ⬢  0.17 L  0.53G RAM  18:34    25.11.18 
 ❯ cd kubeflow 
 ✓  ~/git/kubeflow/scripts/kubeflow                                                                               9.4.0 ⬢  0.08 L  0.54G RAM  18:34    25.11.18 
 ❯ ls
env.sh
```

**Comment by janvdvegt** [comment]
After a lot of struggles I got it to run by manually cloning the repository, setting the KUBEFLOW_SRC with an absolute path and KFAPP with a relative path and running everything from the shared folder one above both KUBEFLOW_SRC and KFAPP.

**Comment by dsdinter** [comment]
Hi,
I believe you missed to change directory to run the next command from ${KFAPP} hence the error not finding env.sh

https://www.kubeflow.org/docs/started/getting-started/#kubeflow-quick-start
"
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none
cd ${KFAPP}
${KUBEFLOW_SRC}/scripts/kfctl.sh generate k8s
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
"

Can you try again following the instructions? Feel free to raise an issue if something needs to be updated in the documentation, so we can make the instructions more intuitive.


Thanks.

**Comment by janvdvegt** [comment]
I found out what the problem is, the KUBEFLOW_SRC variable needs to be the absolute path while KFAPP doesn't need to be.
