### ISSUE TITLE
ksonnet runtime error Seldon

### ISSUE THREAD

**Issue by janvdvegt** [kubeflow/kubeflow#2001]
After installing and deploying kubeflow core to GCP, I am trying to install seldon core. After installing the component using:

`ks generate seldon seldon`

When I apply or show the manifest I get a RUNTIME ERROR:

	ERROR find objects: RUNTIME ERROR: Unexpected type array, expected object
	<std>:1182:5-33	builtin function <objectHasEx>
	vendor/kubeflow/application/application.libsonnet:192:12-46	object <anonymous>
	vendor/kubeflow/application/application.libsonnet:(188:32)-(197:13)	function <anonymous>
	<std>:235:50-62	function <anonymous>
	<std>:762:38-46	thunk from <thunk from <function <aux>>>
	<std>:815:34-35	function <anonymous>
	<std>:762:24-47	thunk from <function <aux>>
	<std>:762:9-57	function <aux>
	<std>:763:5-28	function <anonymous>
	<std>:815:5-46	function <anonymous>
	vendor/kubeflow/application/application.libsonnet:247:20-75	object <anonymous>
	vendor/kubeflow/application/application.libsonnet:148:43-49	thunk from <object <anonymous>>
	<std>:232:22-25	thunk from <function <anonymous>>
	<std>:232:13-26	function <anonymous>

	vendor/kubeflow/application/application.libsonnet:148:22-50	object <anonymous>
	During manifestation`

This happens regardless whether I use the newest seldon version or the older one. When the component is installed, the show or apply actions also do not work for other components.

**Comment by cliveseldon** [comment]
Can you point to the docs and version of kubeflow you are using so we can debug?

You could try to [install seldon directly](https://github.com/SeldonIO/seldon-core/blob/master/docs/install.md) until we can get to the bottom of this.

**Comment by janvdvegt** [comment]
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

Following this guide: https://www.kubeflow.org/docs/started/getting-started-gke/ however the download script is not functional for me so I cloned the repository directly. I'm using the master version. Thank you for helping!

**Comment by janvdvegt** [comment]
I removed the component and installed it via that guide and I'm having the exact same issue.

**Comment by cliveseldon** [comment]
OK. This might be a ksonnet version change. If you could see if it works for 0.12 ksonnet?

**Comment by janvdvegt** [comment]
With ksonnet version 0.13.1 the ksonnet example from the Seldon core repo is working, I deleted my GKP cluster and reinitialized it, let me see if I can get it working in kubeflow now.

**Comment by cliveseldon** [comment]
Very strange. Hope you can isolate the differences so we can fix this.

**Comment by dsdinter** [comment]
@janvdvegt can you try by checking out Kubeflow tag **v0.3.1** to see if that fixes the issue?

**Comment by janvdvegt** [comment]
Yeah I will try that now

**Comment by janvdvegt** [comment]
That does fix the issue @dsdinter also with ksonnet 0.13.1

**Comment by dsdinter** [comment]
Great, feel free to close this issue if you believe is solved.

Thanks.

**Comment by janvdvegt** [comment]
Well I would like to use the newer versions of Kubeflow together with seldon if possible and I assume I'm not alone in that?

**Comment by dsdinter** [comment]
Thanks, I can confirm the issue happens with master after generating the Seldon component.
@cliveseldon @kkasravi I tested and seems the error has been introduced by #1829

**Comment by kkasravi** [comment]
@janvdvegt ks 0.13.1 should be fine.
The error is related to generating an Application CR. 
I'll submit a PR.  Let me find a workaround.
Which version of kubeflow are you on?

**Comment by janvdvegt** [comment]
I'm on master again now

**Comment by kkasravi** [comment]
opened #2006

@janvdvegt thanks for finding this. 
I'll close both issues when the PR is merged.

**Comment by kkasravi** [comment]
> Do we know why as that change to the seldon prototype seems similar to many other changes made by this PR?

kubeflow used to import namespace via params - it's actuall
