### ISSUE TITLE
Expose ArgoCD UI server behind Ambassador proxy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2005]
We should expose ArgoCD behind the Ambassador reverse proxy.

Hopefully this is just a matter of adding an appropriate annotation to the K8s service.

One complication is that I think Ambassador in 0.3 might only be configured to monitor the namespace its deployed in. I think @kkasravi fixed this on master so in 0.4 it should be able to monitor all namespaces.

**Comment by jlewi** [comment]
I gave this a quick shot adding an ambassador mapping. I ended up getting and endless stream of 307s. I think this is because ArgoCD by default redirects from http to https. 

So I think we need to disable that.

**Comment by jlewi** [comment]
See #1990 we can disable SSL.

**Comment by jlewi** [comment]
Setting `--insecure` fixed the redirect issue now I'm getting 404s; probably need to do what we do for Argo UI and set the base href.

@andreyvelich @jessesuen Does ArgoCD have the same environment variable for setting the base href.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L161
?

**Comment by jlewi** [comment]
I don't see such an environment variable
https://github.com/argoproj/argo-cd/search?q=HREF&unscoped_q=HREF

**Comment by jlewi** [comment]
Here are the command line:
https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-server/commands/root.go#L86

Maybe its the flag static assets
https://cs-demo-1103.endpoints.code-search-demo.cloud.goog/main.e40bef37656604b12627.js

**Comment by jessesuen** [comment]
@jlewi argo-cd-ui doesn't support setting a different base href. Are you trying to use a sub-path as a base? I think we may be able to do a quick patch.

**Comment by jessesuen** [comment]
@alexmt thinks the fix is more involved. I've filed an issue for this: https://github.com/argoproj/argo-cd/issues/906. We can probably do in a v0.11.X patch release. v0.11 will be releasing next week.

**Comment by andreyvelich** [comment]
@jessesuen  After your patch we can use the same env variable (`BASE_HREF`) that we have here: 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L161 ?

**Comment by alexmt** [comment]
@andreyvelich, yes . Lets use same env variable to control base ref

**Comment by alexmt** [comment]
@andreyvelich . Most of argo cd settings are configured using cli flags, so I had to use flag for consistency. Take a look at PR https://github.com/argoproj/argo-cd/pull/930/files ( [ingress.md](https://github.com/argoproj/argo-cd/blob/a54ceb87bb73532473a857ba0c7408a7fdf34d8c/docs/ingress.md#ui-base-path) describes introduced flag ) . Please let me know if you need any changes

**Comment by andreyvelich** [comment]
@alexmt It is ok, thanks.
We can add this setting inside container commands (https://github.com/kubeflow/examples/blob/master/code_search/demo/cs-demo-1103/k8s_specs/argo_cd.yaml#L398), just like you in [ingress.md](https://github.com/argoproj/argo-cd/blob/a54ceb87bb73532473a857ba0c7408a7fdf34d8c/docs/ingress.md#ui-base-path)
