### ISSUE TITLE
Seems to be an issue in kfctl.sh re existence of dir ${DEPLOYMENT_NAME} 

### ISSUE THREAD

**Issue by blsaws** [kubeflow/kubeflow#2009]
The script creates dir ${DEPLOYMENT_NAME} then fails if it exists, a few lines later...
main() {
  if [ "${COMMAND}" == "init" ]; then
    DEPLOYMENT_NAME=${WHAT}
    parseArgs $*
    mkdir -p ${DEPLOYMENT_NAME}
    # Most commands expect to be executed from the app directory
    cd ${DEPLOYMENT_NAME}
    createEnv
    source ${ENV_FILE}
    # TODO(jlewi): Should we default to directory name?
    # TODO(jlewi): This doesn't work if user doesn't provide name we will end up
    # interpreting parameters as the name. To fix this we need to check name doesn't start with --
    if [ -z "${DEPLOYMENT_NAME}" ]; then
      echo "name must be provided"
      echo "usage: kfctl init <name>"
      exit 1
    fi
    if [ -d ${DEPLOYMENT_NAME} ]; then
      echo "Directory ${DEPLOYMENT_NAME} already exists"
      exit 1
fi

**Comment by jlewi** [comment]
After creating the directory ${DEPLOYMENT_NAME} we cd into that directory.

So when we check if the directory exists we are in the newly created directory.

So I wouldn't expect this to actually cause the script to fail. The check for the directory exists should be spurious and can probably be deleted.

@blsaws What was the actual failure mode that you observed? Can you provide the full output of running kfctl.sh so we can see the commands run and results.

**Comment by blsaws** [comment]
Thanks for your help. The failure is that the script exits.
Here is the script output of '${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none', which I am running from /home/bryan/test/ after these initial setup commands: 
export WORK_DIR=$(pwd)
  export KUBEFLOW_SRC=$WORK_DIR/kubeflow
  mkdir ${KUBEFLOW_SRC}
  cd ${KUBEFLOW_SRC}
  export KUBEFLOW_TAG=v0.3.1
  curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
cd $WORK_DIR
export KFAPP=${KUBEFLOW_SRC}/config
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none
+ COMMAND=init
+ WHAT=/home/bryan/test/kubeflow/config
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname /home/bryan/test/kubeflow/scripts/kfctl.sh
++ cd /home/bryan/test/kubeflow/scripts
++ pwd
+ DIR=/home/bryan/test/kubeflow/scripts
+ source /home/bryan/test/kubeflow/scripts/util.sh
+ source /home/bryan/test/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/bryan/test/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' init == init ']'
+ DEPLOYMENT_NAME=/home/bryan/test/kubeflow/config
+ '[' init '!=' '' ']'
+ case $1 in
+ shift
+ '[' /home/bryan/test/kubeflow/config '!=' '' ']'
+ case $1 in
+ shift
+ '[' --platform '!=' '' ']'
+ case $1 in
+ shift
+ PLATFORM=none
+ shift
+ '[' '' '!=' '' ']'
+ mkdir -p /home/bryan/test/kubeflow/config
+ cd /home/bryan/test/kubeflow/config
+ createEnv
+ echo PLATFORM=none
++ cd /home/bryan/test/kubeflow/scripts/..
++ pwd
+ DEFAULT_KUBEFLOW_REPO=/home/bryan/test/kubeflow
+ KUBEFLOW_REPO=
+ echo KUBEFLOW_REPO=/home/bryan/test/kubeflow
+ echo KUBEFLOW_VERSION=master
++ pwd
+ echo KUBEFLOW_KS_DIR=/home/bryan/test/kubeflow/config/ks_app
+ echo KUBEFLOW_DOCKER_REGISTRY=
+ echo K8S_NAMESPACE=kubeflow
+ case "$PLATFORM" in
+ echo KUBEFLOW_CLOUD=null
+ source env.sh
++ PLATFORM=none
++ KUBEFLOW_REPO=/home/bryan/test/kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/bryan/test/kubeflow/config/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
+ '[' -z /home/bryan/test/kubeflow/config ']'
+ '[' -d /home/bryan/test/kubeflow/config ']'
+ echo Directory /home/bryan/test/kubeflow/config already exists
Directory /home/bryan/test/kubeflow/config already exists
+ exit 1

**Comment by jlewi** [comment]
I think one problem is you are setting KFAPP to be a path

```
export KFAPP=${KUBEFLOW_SRC}/config
```

KFAPP should just be the name of your deployment e.g. "my-kubeflow"

kfctl.sh will create the directory "my-kubeflow" in the current directory to store all the configs.
