### ISSUE TITLE
Argo UI not working

### ISSUE THREAD

**Issue by janvdvegt** [kubeflow/kubeflow#2021]
I can submit Argo workflows and they are working, however when I am portforwarding to the Argo UI pod I am getting a blank screen. The source shows:

```<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Argo</title>
    <base href="/argo/">
    <link href="https://fonts.googleapis.com/css?family=Heebo:300,400,500,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="assets/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="assets/favicon/favicon-16x16.png" sizes="16x16">
</head>

<body>
    <div id="app"></div>
<script type="text/javascript" src="main.f6e517525a3ff95bf2c8.js"></script></body>

</html>
```

My Chrome browser throws a Javascript error `Uncaught SyntaxError: Unexpected token <` due to the fact that the Javascript script it is loading is the same as the root index page (which is HTML). This is with a two days old master of kubeflow.

**Comment by jlewi** [comment]
If you're port-forwarding to the Argo UI then Kubeflow likely isn't involved here. So its probably an issue/question with Argo. Did you take a look at argoproj/argo to see if anyone is reporting similar issues?

/cc @jessesuen

**Comment by andreyvelich** [comment]
You can access to ArgoUI only using Ambassador right now. 
You can have a look at this: https://github.com/argoproj/argo/issues/716#issuecomment-433213190. 

If you want to access ArgoUI without Ambassador, you need to delete this environment variable (https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L161) from ArgoUI deployment in Argo Package.

**Comment by jlewi** [comment]
Looks like the BASE_HREF isn't set for me.

```
  - env:
    - name: ARGO_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: IN_CLUSTER
      value: "true"
```

**Comment by jlewi** [comment]
I misspoke. I was looking at an old cluster. When I looked at a cluster for master the Argo UI was working behind Ambassador.

**Comment by jlewi** [comment]
@janvdvegt Were you using a 0.3 cluster? I think the answer is this will work in 0.4.

**Comment by andrewgdavis** [comment]
from an argo deployment today:
```
    Environment:
      ARGO_NAMESPACE:  kubeflow (v1:metadata.namespace)
      IN_CLUSTER:      true
      BASE_HREF:       /argo/  
```
`BASE_HREF:       /argo/`     <------- causes an empty page to be rendered, but logs are ok

so to be clear:  
  Is ambassador is now a requirement to access the argo-ui?

**Comment by andreyvelich** [comment]
@andrewgdavis You can access to argo-ui without ambassador. 
Just delete this environment: 
```BASE_HREF: /argo/ ```

**Comment by jlewi** [comment]
@andrewgdavis Yes by default Argo is configured to work behind the Ambassador reverse proxy so you need to access it through ambassador otherwise the http paths won't be correct. Alternatively as @andreyvelich mentions you can change the Argo config so its not configured to work behind Ambassador in which case you can bypass ambassador.

I'm going to close this; please reopen if your question hasn't been answered.
