### ISSUE TITLE
bootstrap golang modules 

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2022]
- Move from glide to go modules (golang 1.11.2)
- Define a multistage build docker file (move Dockerfile.build into Dockerfile) that uses the gomodule cache
- Remove unused script start.sh
- Upgrade debug.sh, dlv.sh to use go modules
- Upgrade kubectl to v1.12.2
- Upgrade ksonnet to v0.13.1

**Comment by jlewi** [comment]
Is this an issue a duplicate of #2024?

It seems like most of the discussion to figure out next steps is happening in #2024?

**Comment by kunmingg** [comment]
@kkasravi 
Seems like ks module is more of a components instance than components prototype.
How can we make ks module reusable for all users that might have various parameter sets?

**Comment by kkasravi** [comment]
@kunmingg 

Could I ask you to post your question above in #2024?
I'll answer it there so we're consolidating all design questions in that issue.
I'll rename this to 'ksonnet module migration'. 
This issue/PR will reference the actual implementation.

**Comment by kunmingg** [comment]
@kkasravi 
done, thanks!
