### ISSUE TITLE
Auto-scaling for Seldon serving?

### ISSUE THREAD

**Issue by sasvaritoni** [kubeflow/kubeflow#2029]
Does Kubeflow provide any support for automatic scaling of Seldon components?

I would like to take advantage of the features provided by the Kubernetes Horizontal Pod Autoscaler (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) e.g. on a component generated with serve-simple-v1alpha2.
Can this be setup for Seldon deployments with Kubeflow?

**Comment by cliveseldon** [comment]
There is an [open issue](https://github.com/SeldonIO/seldon-core/issues/277) for this on the seldon-core repo. Feel free to add your comments there as well.

**Comment by sasvaritoni** [comment]
Indeed, I did not notice that...
So i think we can close this one here.

**Comment by Jeffwan** [comment]
I hasn't try Seldon yet but I am interested in this problem. 
Looks like there's extra setting for Seldon deployment?  Why HPA cannot work out-of-box?  @sasvaritoni

**Comment by jlewi** [comment]
Duplicate of SeldonIO/seldon-core#277

**Comment by sasvaritoni** [comment]
@Jeffwan 

In the [Seldon issue ](https://github.com/SeldonIO/seldon-core/issues/277) mentioned above, there is an in depth explanation why it's not straightforward to apply the autoscaler.

**Comment by damitkwr** [comment]
@jlewi 

Seldon now supports auto-scaling as per [https://github.com/SeldonIO/seldon-core/issues/277](this commit and closed issue). Can we re-open this issue and integrate the seldon-core autoscaler option into the template?

**Comment by damitkwr** [comment]
@cliveseldon @jlewi Can we label this so we can have an example for auto-scaling from Kubeflow on the next release?

**Comment by cliveseldon** [comment]
Yes. Please do.

**Comment by damitkwr** [comment]
@sasvaritoni  Can you label since I don't have access?

**Comment by sasvaritoni** [comment]
@damitkwr  I think I don't have permissions to add a label either, at least I am not able to find it...
