### ISSUE TITLE
Use of NTeract

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#2065]
Should we augment the default Jupyter notebook in KF with Nteract?

https://github.com/nteract

**Comment by jlewi** [comment]
My understanding is that NTeract is a REACT based front-end to Jupyter. So we should be able to make it work.

I'm unclear about whether existing Jupyter widgets would work. If that's the case then we would need to continue to support the existing Jupyter front end.

My initial guess is that this is P2. 

For Jupyter I think higher priority items are

* Giving each user their own namespace
* Using ISTIO to restrict access to a user's notebook
* Replacing JupyterHub with a simpler web app that uses the CRD (probably a blocker to above items)

/priority p2
/cc @pdmack

**Comment by pdmack** [comment]
Nteract makes papermill too. Always thought that would be interesting in the ecosystem.
