### ISSUE TITLE
Issue while deploying kubeflow on GKE using command line- killed message in Cloud Shell

### ISSUE THREAD

**Issue by pdcoded** [kubeflow/kubeflow#2075]
## Describe the bug
Executing ../${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s command crashing after some time with “Killed” message.

## How to Reproduce ::
Following this documentation for deploying kubeflow:
https://www.kubeflow.org/docs/started/getting-started-gke/#deploy-kubeflow-on-kubernetes-engine

Here is the screenshot 
<img width="777" alt="screenshot 2018-12-11 at 6 28 04 pm" src="https://user-images.githubusercontent.com/9830931/49802390-c3549700-fd72-11e8-8ea7-06769b921f8f.png">

## Configurations Used 
Kubeflow version: v0.3.4
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

--

**Comment by rohitsroch** [comment]
I am also getting same problem, 
Running:    `ks apply default -c ambassador`  crashing !
Also, even crashing for other components **katib, tf-job-operator** etc. with the same message

**Comment by oquere** [comment]
Same issue for me too !!!

**Comment by jlewi** [comment]
This is a common trip up point; if using cloud shell you need to be in boosted mode otherwise you won't have enough resources.

Does anyone know if its possible to detect if you are running in boosted mode in cloud shell?

**Comment by pdcoded** [comment]
Thanks @jlewi, @oquere  -it's resolved after using boost mode. I am closing the issue for now

**Comment by rohitsroch** [comment]
Thanks @pdcoded , @jlewi, @oquere , what I would like to do, is contribute updated codelab  documentation for mnist example with lastest kssonet & kubeflow version. as this https://www.kubeflow.org/docs/guides/gke/gcp-e2e/ doc is not updated
