### ISSUE TITLE
no persistent volumes available for this claim and no storage class is set; minio and pipelines

### ISSUE THREAD

**Issue by dpaks** [kubeflow/kubeflow#2076]
Client Version: v1.13.0, GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: v1.13.0, GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
OS: Ubuntu 18
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
argo: v2.2.1
kubeflow: v0.3.4
Env: A single node cluster using kubeadm

After issuing `${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s`, I happen to see that few of the pods are in PENDING state. On examination, I found that they were waiting for persistent volumes.

> Name:          minio-pv-claim
> Namespace:     kubeflow
> StorageClass:
> Status:        Pending
> Volume:
> Labels:        app.kubernetes.io/deploy-manager=ksonnet
>                ksonnet.io/component=pipeline
> Annotations:   ksonnet.io/managed:
>                  {"pristine":"H4sIAAAAAAAA/yyOsU4rMRBF+/cZt948SLstBRUCUYQCUUy8FzRae8Z4vKGI9t+RI7qjM6Oje4VUPbGFumHG5YgJq9qCGS/DRqf1k+et8CGLFkwo7LJIF8xXZDkzx...
> Finalizers:    [kubernetes.io/pvc-protection]
> Capacity:
> Access Modes:
> VolumeMode:    Filesystem
> Events:
>   Type       Reason         Age                   From                         Message
>   ----       ------         ----                  ----                         -------
>   Normal     FailedBinding  89s (x743 over 3h6m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
> Mounted By:  minio-d79b65988-rgfw6

I created a default persistent volume like this: kubectl create -f https://k8s.io/examples/pods/storage/pv-volume.yaml but to no avail.

Can you help me resolve this issue?

**Comment by jlewi** [comment]
@IronPan @paveldournov 

Looks like the pod in question is related to pipelines and minio.

@dpaks Can you define a default storage class for your cluster? 
https://kubernetes.io/docs/concepts/storage/storage-classes/

I think what's happening is various Kubeflow components (in this case pipelines) need to provision durable storage (e.g. a persistent disk) so that data isn't lost if pods get preempted. My guess is your cluster doesn't have a default storage class defined so you need to define one.

**Comment by royxue** [comment]
@jlewi 
Agree with you. the default storage class is needed. and if @dpaks you are using the hostpath for PV, you probably should manually create the PV as there is no provisioner.

**Comment by dpaks** [comment]
@jlewi @royxue 
True that. I use hostpath and I had to manually create PVs to overcome this issue. Sorry for the late response.

An example:
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/xxx/datastore"

**Comment by royxue** [comment]
👍 
This can be closed ;)
