### ISSUE TITLE
Deployment web UI link to Cloud Shell gives error during cloudshell_open

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#2078]
Upon clicking the "Cloud Shell" button from the deploy.kubeflow.cloud UI (with v0.3.4 and us-east1-d and of course "Skip IAP" checked) I observe the following error in the Cloud Shell:

```bash
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
Could not find conda environment: env
You can list all discoverable environments with `conda info --envs`.

chris_w_beitel@cloudshell:~$ cloudshell_open --repo_url "https://source.developers.google.com/p/kubeflow-rl/r/kubeflow-rl-kubeflow-config" --dir "v0.3.4/kubeflow/kf_util" --page "editor" --tutorial "conn.md"
Cloning into 'kubeflow-rl-kubeflow-config'...
fatal: remote error: Forbidden
cd-ing into kubeflow-rl-kubeflow-config/v0.3.4/kubeflow/kf_util
bash: cd: kubeflow-rl-kubeflow-config/v0.3.4/kubeflow/kf_util: No such file or directory
Tutorial file conn.md does not exist or is not a file
```

The first part about conda has to do with my Cloud Shell .bash_profile and probably isn't related.

**Comment by jlewi** [comment]
@kunmingg Do you know what's going on here?

**Comment by kunmingg** [comment]
Seems cloud shell cannot clone from source repo.
Permission issue?

**Comment by kunmingg** [comment]
@cwbeitel
Any info of how to reproduce would be helpful, thanks!
Is this the first time you try cloud shell?

**Comment by amalts** [comment]
@kunmingg 
I'm also facing the same issue.

**Steps to reproduce:**

Go to https://deploy.kubeflow.cloud/#/deploy](https://deploy.kubeflow.cloud/#/deploy)
Click on "Create Deployment"
Click on "Cloud Shell" as given in the instructions

**Error**:
```
cloudshell_open --repo_url "https://source.developers.google.com/p/kubeflow-pipeline-spike/r/kubeflow-pipeline-spike-kubeflow-config" --dir "v0.3.5/kubeflow/kf_util"-
-page "editor" --tutorial "conn.md"
Cloning into 'kubeflow-pipeline-spike-kubeflow-config'...
warning: You appear to have cloned an empty repository.
cd-ing into kubeflow-pipeline-spike-kubeflow-config/v0.3.5/kubeflow/kf_util
-bash: cd: kubeflow-pipeline-spike-kubeflow-config/v0.3.5/kubeflow/kf_util: No such file or directory
Tutorial file conn.md does not exist or is not a file
```

**Comment by kunmingg** [comment]
@amalts 
Sorry to hear that, you can port-forward to ambassador pod directly to access the service UI.
Alternatively, we'll support basic auth for non-IAP users soon: https://github.com/kubeflow/kubeflow/issues/2094
