### ISSUE TITLE
Being able to deploy Kubeflow in private GKE cluster

### ISSUE THREAD

**Issue by dsdinter** [kubeflow/kubeflow#2086]
At the moment it is not possible to deploy Kubeflow in a private cluster as some images are pulled from remote registries (e.g., Dockerhub, quay.io). We should be able to somehow mirror these images in gcr.io to be able to pull them from private GKE clusters.
There is a [solution](https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring) for Docker Hub public images but we should be able to support other public repositories as well.

**Comment by dsdinter** [comment]
In the interim you can follow the below steps to deploy in a private GKE cluster including the ML Pipeline component (Thanks @IronPan!):
```shell
### Set ${KUBEFLOW_SRC} path and GCP ${PROJECT} with your own values

mkdir ${KUBEFLOW_SRC}
cd ${KUBEFLOW_SRC}
export KUBEFLOW_TAG=v0.3.4
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash

KFAPP=kubeflow
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform gcp --project ${PROJECT}
cd ${KFAPP}
${KUBEFLOW_SRC}/scripts/kfctl.sh generate platform

##### Set private cluster #####

${KUBEFLOW_SRC}/scripts/kfctl.sh apply platform
${KUBEFLOW_SRC}/scripts/kfctl.sh generate k8s
```
[Create](https://www.kubeflow.org/docs/started/getting-started-gke/#create-oauth-client-credentials) an OAuth client ID
```shell
export CLIENT_ID=<CLIENT_ID from OAuth page>
export CLIENT_SECRET=<CLIENT_SECRET from OAuth page>
ks param set ambassador statsdImage gcr.io/ml-pipeline/kubeflow/statsd:0.37.0
ks param set ambassador ambassadorImage gcr.io/ml-pipeline/kubeflow/ambassador:0.37.0
ks param set argo workflowControllerImage gcr.io/ml-pipeline/kubeflow/workflow-controller:v2.2.0
sed -i '' "s,mysql:5.6,gcr.io/ml-pipeline/kubeflow/mysql:5.6," vendor/kubeflow/pipeline/mysql.libsonnet
sed -i '' "s,minio:RELEASE.2018-02-09T22-40-05Z,gcr.io/ml-pipeline/kubeflow/minio:RELEASE.2018-02-09T22-40-05Z," vendor/kubeflow/pipeline/minio.libsonnet

${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
```

**Comment by IronPan** [comment]
I am not sure for people who are using private cluster, how comfortable it would be to set up the IAP. 
I guess it would expose an public site?

In case you don't want to expose it, once can provide fake client id/secret
export CLIENT_ID=foo
export CLIENT_SECRET=bar

**Comment by dsdinter** [comment]
Good point @IronPan, I updated the code snipped to avoid exposing UI even through IAP.

**Comment by IronPan** [comment]
There is a parameter in JH to set authentication method. set it to null seems working
`ks param set jupyterhub jupyterHubAuthenticator null`

**Comment by jlewi** [comment]
You need some way to connect to your cluster. The two methods are

1. kubectl port-forward
1. IAP

In both cases there is a public ip address. In case 1 it will be the public ip address of the GKE master.

With IAP it will be the public IP address of the LB.

So at a high level security is roughly equivalent. In both cases, you can restrict access to certain IP ranges (e.g. via authorized networks for GKE master or Cloud Firewall rules for ingress).

With IAP users also need to have the appropriate IAM role in order to be able to access Kubeflow.

**Comment by jlewi** [comment]
I forgot we have instructions for private clusters here:
https://www.kubeflow.org/docs/guides/gke/private-clusters/

**Comment by IronPan** [comment]
Thanks. the doc is a bit old. We would need to update or create new instruction when the feature is ready.

**Comment by IronPan** [comment]
Here are the TODO items I can see so far
- Mirroring the docker image to be accessible by private cluster
- Dynamically allocate master Ipv4 CIDR Block
- Verify IAP works in private IP cluster
- Documentation

**Comment by jlewi** [comment]
@IronPan Are you working on this? 

It seems like most of the items listed above can be performed by having the user customize their Kubeflow; possibly with the help of some scripts.

For mirroring the images can we provide users

  * A script to replicate Docker images to their own GCR registry
     * Does this script help: https://github.com/kubeflow/kubeflow/blob/af000bb6e159eecd77f24e1ef6c277804245efde/releasing/sync_images.py?
  * A script to update the ksonnet components to use those images
     * Can we update our existing script https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/use_gcr_for_all_images.sh ?

  * Do we need to dynamically allocate a master IPV4 CIDR? Can we start by providing instructions on how users can select an approprite CIDR block

  * For IAP what changes when we use private IP?

    * The only thing I can think of is we will need to change how we get the SSL certificate. 
    * I think we need to move to using [Managed SSL certificates](https://blog.collaborizm.com/how-to-use-google-managed-ssl-certificates-on-gke-7a56fc514ef8

**Comment by IronPan** [comment]
Yes I agree we should start by having user customize the deployment. I'll spend some time on this by this week.

**Comment by shalberd** [comment]
Not only that, but in in private cluster, period. I realize this is Google, but there are industrial ML applications that want no exposure to the cloud at all.

**Comment by jlewi** [comment]
@IronPan Any update?

**Comment by jlewi** [comment]
We need to update the instructions https://www.kubeflow.org/docs/gke/private-clusters/ to work with Kubeflow 0.5.

Here's some work I forsee

* We need to update the instructions to use kfctl
* We should figure out a solution for generating a certificate for the endpoint since certmanager won't work
  * Simplest option is to use a self-signed certificate using kube-rsa ([example](https://github.com/kubeflow/testing/blob/4015767bf9f42a5abe8fe246966f34412cce0377/py/kubeflow/testing/create_kf_instance.py#L292))

  * If we upgrade to GKE 1.12 or later we should be able to use a managed certificate

* We will need to update the scripts for sync'ing the issues.

**Comment by jlewi** [comment]
Update: Instructions have been updated. I need to do another pass through the instructions now that some PRs have been merged. Once those updated instructions are merged we should be able to close this.

**Comment by jlewi** [comment]
kubeflow/website#382 is merged so marking this fixed.
