### ISSUE TITLE
Specify whether to use COS or Ubuntu nodes in the GKE cluster created by Kubeflow setup scripts

### ISSUE THREAD

**Issue by iankoulski** [kubeflow/kubeflow#2088]
It would be great to be able to specify some of the finer-grained parameters of the GKE cluster used by Kubeflow. 
-- Worker node OS: COS or Ubuntu
-- Worker node size
-- For private clusters, specify master authorized networks

**Comment by jlewi** [comment]
@iankoulski Can't you do all of that by modifying the deployment manager configs that are created during the deployment process?

See https://www.kubeflow.org/docs/started/getting-started-gke/
