### ISSUE TITLE
Central dashboard should be left handed navigating bar

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2093]
We'd like the central dashboard to be a left handed navigation bar. On the right panel we'd like to eventually show different cards e.g. "quick launch a notebook."

Related issue: #2092 fix color scheme for central dashboard

We should come up with some form of mocks to look at it before making the changes.

**Comment by cwbeitel** [comment]
What if you made the pipelines UI the primary UI? You could embed the notebook spawner UI within a notebooks section without linking out to another page.
