### ISSUE TITLE
Support basic username/password login with ambassador

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2094]
See https://github.com/kubeflow/kubeflow/issues/11#issuecomment-370548446

We'd like users to be able to login to Kubeflow using username & password.

The goal is to provide a secure way for users trying out Kubeflow to get started without dealing with setting up OIDC.

We have consistently seen users get tripped up trying to create CLIENT ID's in order to setup OIDC (e.g. creating OAuth clients to enable IAP on GCP).

To provide a simpler getting started experience (e.g. for tutorials) we'd like to allow users to enable username/password authentication.

Creating an IAM system is an explicit non-goal. So we will not provide support for features for managing large numbers of users. For that we should direct users at setting up OIDC (see #11 
)

Per [comment](https://github.com/kubeflow/kubeflow/issues/11#issuecomment-370548446) the desired behavior is

   1. User tries to access Kubeflow at https://<mydomain>
   1. if they are not logged in they are redirected to login with username/password
   1. username gets stored in a header of the request so that it can be used by apps to identify user
   1. password is stored encrypted in a config map

**Comment by kunmingg** [comment]
@kkasravi 
https://www.getambassador.io/reference/services/auth-service/
I think we can take some existing basic ones like:
https://github.com/goji/httpauth
https://github.com/datawire/ambassador-auth-httpbasic

and implement features we need:
1. cookie-based auth
2. login page for all unauthorized traffic

**Comment by kkasravi** [comment]
@kunmingg thanks
I was going to start with [https://github.com/datawire/ambassador-auth-httpbasic](https://github.com/datawire/ambassador-auth-httpbasic)

**Comment by kunmingg** [comment]
@kkasravi 
Thanks!

I create 3 sub issues:
https://github.com/kubeflow/kubeflow/issues/2147
https://github.com/kubeflow/kubeflow/issues/2148
https://github.com/kubeflow/kubeflow/issues/2149

So we can track in details.

**Comment by jlewi** [comment]
@kunmingg Do we have a separate issue to track deployment of basic auth with kfctl? If not should we just  use this issue to track that?

Do we already have ksonnet packages for deploying the respective components or do we still need that?

I think @kkasravi is about to submit his initial PR for a go binary for kfctl. My suggestion would be to go directly to the GoBinary and not use kfctl.sh.

We will need the go binary for click to deploy integration.

**Comment by jlewi** [comment]
Looks like we have an issue #2472 to deploy basic auth with kfctl. 

@kunmingg Should we close this issue out since we have created more specific issues for the remaining work?

**Comment by kunmingg** [comment]
Sure
