### ISSUE TITLE
[gcp-click-to-deploy] Web app should support configuring basic auth

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2095]
See #2094 
We want to support basic auth with Ambassador because creating an OAuth client trips up too many users getting started.

This issue track adding the necessary features (e.g. UI improvements) to the click to deploy app to allow username/password auth to be selected and configured during deployment.

**Comment by kkasravi** [comment]
Hi @kunmingg I'm working on #2094, let me know if you're doing related auth changes for gcp-click-to-deploy.

Thanks
Kam

**Comment by kunmingg** [comment]
@kkasravi That's great! Will integrate once basic auth ready.

**Comment by jlewi** [comment]
@kunmingg What's the current status of this? I think you mentioned this is in staging? I think users also need to specify the commit they want to deploy since basic auth isn't on the 0.4 branch?

**Comment by kunmingg** [comment]
@jlewi 
Haven't push to staging, will update staging this afternoon and close this PR.

**Comment by jlewi** [comment]
@kunmingg What is the remaining work here?

I just checked deploy.kubeflow.cloud and I don't see an option to use basic auth?

I  checked staging and it looks like the default version is a particular hash and when I click skip IAP it gives me an option to supply username and password.

**Comment by kunmingg** [comment]
@jlewi 
One optional remaining work is update instruction text.
Will roll out this feature with v0.5 once release available.

**Comment by kunmingg** [comment]
Will close as it's already alive on staging
