### ISSUE TITLE
Add Argo package to our ksonnet registry

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#21]
https://applatix.com/open-source/argo/

This looks like it could be very useful for

- Decoratively describing pipelines/workflows
- Building containers from notebooks
  
We should create an Argo package in our Ksonnet registry to make it easy to deploy Argo with Kubeflow.

We should be able to use the libsonnet files in our test infrastructure as a starting point.

**Comment by vishh** [comment]
We need automated builds as part of CI.
That is different from a user journey of moving from interactive to batch training. 
Can we have separate issues for both?

**Comment by jessesuen** [comment]
Let us (argo) know we can be of help in any way with this effort. We took your feedback to heart and are implementing both DAG dependency based execution of tasks, as well as the ability to create/apply/patch/delete any k8s resource in steps (including CRDs).

**Comment by jlewi** [comment]
Thats fantastic thank you.

**Comment by jlewi** [comment]
Filed kubeflow/issues#87 to track overall CUJ per comment from @vishh.

Lets narrow the scope of this issue to adding Argo to our ksonnet registry.

**Comment by jlewi** [comment]
Are test infra already uses ksonnet to deploy Argo
https://github.com/google/kubeflow/blob/master/testing/test-infra/components/argo.libsonnet
It should be straightforward to turn this into a component in our registry.

**Comment by jlewi** [comment]
We need an E2E test for the component.

**Comment by jlewi** [comment]
Opened up a new issue for the test. Closing this one.
