### ISSUE TITLE
0.4 blog post

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2102]
Once 0.4 is cut (#2098) we should publish a blog post.

I believe Josh has a Google doc with a draft for the blog post.

**Comment by jlewi** [comment]
Here is the 0.4 planning doc which had a draft announcement.
https://docs.google.com/document/d/13vBugi1eHND9WFDtasEhvY8BkFJ8MUfahTFsVG13_LU/edit?ts=5bf0b38a#bookmark=id.q03ck78tvot5

**Comment by jlewi** [comment]
We also had this pre-release blog post in early December
https://medium.com/kubeflow/kubeflow-0-4-release-update-whats-coming-c55820e28915

**Comment by jbottum** [comment]
> Once 0.4 is cut (#2098) we should publish a blog post.
> 
> I believe Josh has a Google doc with a draft for the blog post.

I am thinking that we have promoted 0.4 in the release candidate announcement.    IMO, the 0.4 GA announcements needs new content.    We might want to consider promoting the Kubeflow User Survey in the Kubeflow 0.4 release and maybe some upcoming events.     Would like to get others opinions i.e. should we keep it clean to 0.4 or mix in other topics...

**Comment by jlewi** [comment]
Published:
https://medium.com/kubeflow/kubeflow-0-4-release-enhancements-for-machine-learning-productivity-d77c54df07a9
