### ISSUE TITLE
Add jsonnet unit test for tensorflow serving component

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#2103]
#2067 Meet some problems in deploying tensorflow serving components. I think we need to add unit tests for these jsonnet files.

**Comment by jlewi** [comment]
@Jeffwan I think @kkasravi added a bunch of unittests recently; are we still missing unittests for this?

**Comment by Jeffwan** [comment]
@jlewi Let me have a check. Recently get stuck on some work and did spend time on it.

**Comment by Jeffwan** [comment]
@jlewi TF-serving actually has corresponding UTs, the problem was there's no test cases for GCP and AWS specific logic. I'd like to add both of them. I notice cloud provider related code in under prototype which is not testable? Looks like UTs are against libsonnet files. The structure is different from Tensorboard that cloud provider has its own libsonnet file.
