### ISSUE TITLE
Publish Docker images to DockerHub in addition to gcr.io

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#211]
gcr.io is unfortunately blocked in China. So we should probably publish all our Docker images to DockerHub as well.

See #197 for getting ownership of kubeflow in Dockerhub.

**Comment by s1113950** [comment]
@jlewi I'll take this one on

**Comment by s1113950** [comment]
I'm in the process of getting my cla good to go (Intel, same team as @elsonrodriguez ), but should have the PR good to go by about EOD

**Comment by jlewi** [comment]
What is your thinking in terms of how you will do this?

- Will our release pipelines just push to both locations?
- Will you run a sync job that will automatically sync all images from one registry to the other?

I think it would be nice if there was an easy way to mirror a docker registry.

**Comment by s1113950** [comment]
My first idea was just to modify the release pipeline to push to both locations (I've been editing the various Makefiles to do this). Long-term, a sync job or a way to mirror the registries would be my preferred approach as well. 

It looks like we could do the sync relatively easily though? I found this https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring. Do you think I should go this route from the beginning or stick with pushing to both places for now?

I also had a question regarding getting kubeflow ownership; I see that it's a public repo but I was unable to push to it. What's the process for getting that to be a community repo or getting permissions to push to it?

**Comment by s1113950** [comment]
Take a look at https://github.com/kubeflow/kubeflow/pull/222 and let me know what you think @jlewi

**Comment by jlewi** [comment]
If you're willing, I'd much prefer the mirroring route.

I think https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring is mostly about a mirror of DockerHub in GCR to make fetching images from GCP more efficient. So one option would be to make DockerHub the source of truth and then rely on GCR mirror to make it efficient on GCP.

But I don't think that will work very well for our release/test infra since the mirror has a 30 minute delay. 

How difficult would it be to write a simple script that would list images using the Docker registry API and then push missing images from one repo to the other? It surprises me that no such tooling exists.

Regarding community ownership, we're in the process of setting up Gsuite for kubeflow.org. At which point we can create GCP projects in kubeflow.org for all our test/release infrastructure and easily share them with community members.

@lluunn is working on building images using Argo. I think the direction we want to go is to trigger Docker images as part of pre/post submits by using Prow to launch Argo.

**Comment by s1113950** [comment]
This tool exists: https://hub.docker.com/r/stefanhudelmaier/docker-registry-to-registry-sync/ but it doesn't work with dockerhub so we would have to fix that bug at the bottom of the page or wait until it's fixed to use it...

Maybe we could leverage this from openshift?
https://github.com/redhat-cop/openshift-toolkit/tree/master/disconnected_registry

Doing more research it seems there are quite a few different solutions, but many of them sync local to remote rather than remote to remote.

Or I could wait until @lluunn is done with the Argo stuff?

**Comment by jlewi** [comment]
The Argo work wouldn't solve this problem.

The openshift script looks promising. Seems like it should be easy to modify. 

Your call if you want to just go with your PR for pushing to two locations for now I think that's fine.

FWIW there's a python client library for Docker registry here:
https://github.com/google/containerregistry

**Comment by s1113950** [comment]
🤔 maybe go with my PR for now and I could file another ticket for a more long-term solution?

**Comment by s1113950** [comment]
^^^ because I'm not sure what the best long-term syncing solution would be right now, and maybe it would become clearer later/after KubeCon?

**Comment by jlewi** [comment]
See also #197 

I think the next steps would be

1. Create a DockerHub account "kubeflow-releaser"
1. Create a simple script to pull a list of our images and push them to DockerHub
@carmark Do you think you could work on this?

For the email account for the DockerHub account you could use "release-team@kubeflow.org" This is a google group that will be used for folks who manage releases and have access to our release infrastructure.

If you message me with your email I will add you.

**Comment by carmark** [comment]
sure, I can do that in this week.

BTW, my email account is carmark.dlut@gmail.com

Regards,
-Lei

2018年3月7日 下午10:33，"Jeremy Lewi" <notifications@github.com>写道：

**Comment by carmark** [comment]
@jlewi All of images under gcr.io/kubeflow were moved to hub.docker.com/r/kubeflow.

**Comment by jlewi** [comment]
@carmark Thank you.

Can you explain the Docker Hub setup? Is Kubeflow a DockerHub organization? Who are the owners?

How can we authenticate to DockerHub and push these images as part of our release process?

**Comment by carmark** [comment]
@jlewi 

Kubeflow on Dockerhub is a organization, there are two owners, one is me and the other is kuebflowteam(email is release-team@)

We may push the image to dockerhub with two ways:
* build the image by ourselves, and push it to dockerhub with username and password
* provide a Dockerfile, and make a automative build on Dockerhub when there is a commit added

I am not sure whether the Dockerfile can be build in Dockerhub, but it may be more security.  When we have a new release, create a new branch named `release-version` and a new docker image is built.

What do you think of it?

**Comment by jlewi** [comment]
I think it would be best if we could find a good way to automate the pushes to DockerHub. Does DockerHub not support OAuth or some other recommended approach for CI/CD tools?

**Comment by TheJaySmith** [comment]
I would be happy to help find a way to automate this. To my knowledge, there are tools already that exist that allow for GCR and DockerHub to sync.

**Comment by jlewi** [comment]
@TheJaySmith WIll GCR's dockerhub mirror work in this case? Isn't that only for GCR to create a mirror of DockerHub.

Are you actually planning on doing any work for this in the next couple weeks?

**Comment by TheJaySmith** [comment]
@jlewi Yep. Let me get past this next week and I will write something. I found a few existing open source tools that sync git repos so I can likely use that to help.

**Comment by TheJaySmith** [comment]
Is the DockerHub profile still being maintained? If so, can we share access? I have a script to sync gcr.io and dockerhub and want to get that started.

**Comment by jlewi** [comment]
I changed the permission of kubeflowteam to be a dev not an owner.

@TheJaySmith Can you create a new account with a name that makes it clear its a robot account. e.g.
kubeflow-robot.

**Comment by jlewi** [comment]
@TheJaySmith any progress update on this?

**Comment by TheJaySmith** [comment]
I couldn't create kubeflow-robot as it doesn't allow special characters and someone already made kubeflowrobot. 

That being said #1548

**Comment by jlewi** [comment]
@TheJaySmith can we create a different account for our robot?

**Comment by TheJaySmith** [comment]
@jlewi kubeflowrobot is now good to go (managed to get the password to it)

**Comment by jlewi** [comment]
Is anyone interested in signing up and committing to getting this done as part of 0.4?

**Comment by TheJaySmith** [comment]
what additional changes are you wanting? We did integrate the HubSync tool to sync images from GCR to DockerHub so it is good to go. I will integrate it into a Cloud Function or something like that to run weekly.

**Comment by jlewi** [comment]
The goal of this issue is to sync all our docker images to Docker Hub.  So its not just a question of getting some scripts written to do the work, its actually getting everything deployed and maintaining it to ensure images are properly sync'd.

This includes figuring out how to surface monitoring and other information so that we know when the sync breaks and our images are no longer being sync'd.

**Comment by TheJaySmith** [comment]
Ah, good points. Some of it probably needs some human touch just to verify after the sync. Maybe testing the images too.

**Comment by jlewi** [comment]
It seems like we now have two scripts

https://github.com/kubeflow/kubeflow/tree/master/releasing/hubsync
https://github.com/kubeflow/kubeflow/blob/master/releasing/sync_images.py

@cheyang Any thoughts on reconciling these?
