### ISSUE TITLE
master head: cloud-endpoints controller not respond to newly created CRD 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2125]
cloud-endpoints controller didn't create GCP cloud endpoint when a CRD instance is created.
How to reproduce:
check out latest master head, deploy with kfctl.

Seems [master head image](https://github.com/kubeflow/kubeflow/blob/b705cff7a3d2517e32a36b34ea48786a704ff26d/kubeflow/gcp/cloud-endpoints.libsonnet) is different with [v0.3 image](https://github.com/kubeflow/kubeflow/blob/v0.3-branch/kubeflow/core/cloud-endpoints.libsonnet)

Might caused by breaking API change or bugs in new version of cloud-endpoints controller

**Comment by kunmingg** [comment]
@abhi-g

**Comment by gabrielwen** [comment]
this is fixed in #2120

**Comment by abhi-g** [comment]
Awesome! Thanks for the quick fix.
