### ISSUE TITLE
Update ksonnet package for Katib

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/kubeflow#2126]
We need to update ksonnet package for Katib since Katib supports Pytorch jobs.

**Comment by johnugeorge** [comment]
One more fix is remaining 
https://github.com/kubeflow/katib/issues/294

**Comment by andreyvelich** [comment]
@johnugeorge Alright, I can wait until it will be merged.

**Comment by jlewi** [comment]
@andreyvelich Any update on this we want to cut the RC today?

**Comment by andreyvelich** [comment]
@jlewi I will make it today
