### ISSUE TITLE
Need: User facing website for Kubeflow that details how to choose a stack

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#213]
Just start with a proposal on info architecture

**Comment by jlewi** [comment]
@aronchick What is a stack in this case? By user facing website do you mean creating an actual docs website (as opposed to a bunch of md files in GitHub repositories)?

**Comment by aronchick** [comment]
"stack" in this case would be a complete(-ish) end to end something. So, if
you want to run tf.transform + jupyter + tf crd + tf serving, you choose
install these <n> things in the following way. Then same deal with XGBoost,
etc.

We would let the community add whatever makes sense and/or someone wants to
own the docs for.

Yes, I think we would create actually end to end docs.

**Comment by ewilderj** [comment]
the work is being done in the kubeflow/website repo
the relevant project plan is in https://docs.google.com/document/d/1XUGnLVCyqVLN62VWqk-o_FLhRU1L4b7VRcwP8QgFst4/edit#

**Comment by abhi-g** [comment]
Deployment setup issues are being tracked tracked https://github.com/kubeflow/website/projects/1
and are labeled priority/p0.

**Comment by sarahmaddox** [comment]
@abhi-g Do you think we can close this issue now, and split out the remaining tasks from https://github.com/kubeflow/website/projects/1 into separate issues where relevant?

**Comment by abhi-g** [comment]
I think we can close this.
