### ISSUE TITLE
Can kubeflow run a job using multi-nodes' resources ?

### ISSUE THREAD

**Issue by Hirosora** [kubeflow/kubeflow#2130]
We are looking for a distributed system on which we can run our  machine learning job. We wish each job can use multi-nodes' hardware resources. 

Could you please tell me if kubeflow can meets our request ? Thank you !

**Comment by jlewi** [comment]
This will depend on the framework you are using. Some frameworks like PyTorch and TensorFlow can run distributed across multiple-machines and use multiple resources on the machine such as GPUs.

Hope that answers your question. If not it might help to provide more details about what you are trying to do.

**Comment by akrupien** [comment]
I'd argue this does not answer the question. Is KubeFlow capable of multi machine distribution? Or is it restricted to one node?
