### ISSUE TITLE
[gcp-click-to-deploy] cleanup: remove ks and kubectl from Dockerfile

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2132]
In the https://github.com/kubeflow/kubeflow/blob/master/bootstrap/Dockerfile

There should no longer be any need to install kubectl and ks CLIs.

This is a remnant of when the container was intended to provide an interactive environment for delivering the various CLIs to the user.

But now the intended purpose of this docker image is to run the bootstrap/kfctl web server.

So we can remove the CLIs.

/cc @kunmingg @kkasravi

**Comment by r2d4** [comment]
Some other things that should be removed

- dlv
- vim

Possibly a longer term goal is to convert the build into a multi-stage build so that we could remove
- go
- apt-get
- wget
as well as have a smaller footprint

**Comment by stpabhi** [comment]
@jlewi I have submitted #2164 for the same.

**Comment by jlewi** [comment]
Thanks @stpabhi; is this fixed by #2164 or is there more to do?

**Comment by kunmingg** [comment]
Closing this one to clear v0.5.0 issues, let's use new issues to track follow up requests.
