### ISSUE TITLE
Create changelog for 0.4 release

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2133]
We should update the changlog
https://github.com/kubeflow/kubeflow/blob/master/CHANGELOG.md

with the changes in 0.4

Do we need to wait for the RC to be cut? Or can we update the CHANGELOG.md and then start curating it into something readable and then update it with additional changes?

**Comment by r2d4** [comment]
Fixed with https://github.com/kubeflow/kubeflow/pull/2150
