### ISSUE TITLE
initialization script does not correctly detect ks installation when aliased

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#2136]
The script uses which to check if ks is installed however on my machine (for example):

> `hkarau@hkarau-glaptop:~/repos/predict-pr-comments/kf_app$ type -a ks`
> ks is /home/hkarau/bin/ks
> hkarau@hkarau-glaptop:~/repos/predict-pr-comments/kf_app$ echo $?
> 0

And

> `hkarau@hkarau-glaptop:~/repos/predict-pr-comments/kf_app$ which ks`
> `hkarau@hkarau-glaptop:~/repos/predict-pr-comments/kf_app$ echo $?`
> 1

**Comment by jlewi** [comment]
@holdenk Is this fixed by your PRs? Are the fixes just on master or are they also on the 0.4 branch? If they aren't on the 0.4 branch do you want to submit cherry picks to add them to the 0.4 branch?
