### ISSUE TITLE
Consistency in naming package/prototype/image names across operators

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/kubeflow#2140]
Naming conventions of packages/prototypes/images across operators are not consistent.  

For tf-operator installation, 

 ks pkg install **kubeflow/tf-training**
 ks generate **tf-job-operator** tf-job-operator

TF public images are in **gcr.io/kubeflow-images-public/tf_operator**

While for pytorch operator installation ,

  ks pkg install **kubeflow/pytorch-job**
  ks generate **pytorch-operator** pytorch-operator

Pytorch public images are in **gcr.io/kubeflow-images-public/pytorch-operator**

@richardsliu @jlewi

**Comment by jlewi** [comment]
@johnugeorge 
What is the priority for this issue? Can you please set it using /priority?
Can you add appropriate labels as well using /area?

**Comment by jlewi** [comment]
Closing this issue since ksonnet is going away.
