### ISSUE TITLE
Feast (Feature Store) and Kubeflow

### ISSUE THREAD

**Issue by woop** [kubeflow/kubeflow#2141]
At [GOJEK](https://www.gojek.io/) we've recently open sourced a software project called [Feast](https://github.com/gojek/feast), an internal Feature Store for managing, storing, and discovering features for machine learning. The software was jointly developed by GOJEK and Google, and the first release is currently running in production at GOJEK. We are open sourcing the software because we've seen many teams face the same challenges with features as we have, and we'd love to get feedback from the community both on what we have built, and what we are planning to build.

Feast is meant to be deployed on Kubernetes, and we believe it can fit naturally within the Kubeflow ecosystem. We'd love to start a discussion on how we can integrate Feast with Kubeflow!

**Comment by jlewi** [comment]
This is fantastic.

Do folks think we should create a package in Kubeflow for Feast in 0.5?

@woop Does feast support ingestion to non GCP datastores? I think its just using Beam so I'd imagine any Beam sink would work?

Instructions for creating packages
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md

**Comment by woop** [comment]
> This is fantastic.
> 
> Do folks think we should create a package in Kubeflow for Feast in 0.5?

If the community is keen, we'd be willing to maintain a package for Feast in Kubeflow. 

> @woop Does feast support ingestion to non GCP datastores? I think its just using Beam so I'd imagine any Beam sink would work?
> 

We currently support Redis and Bigtable for feature serving, and BigQuery as a feature warehouse. The ingestion code (Beam) should be pretty straightforward to extend for other types of stores though. We'd like to add an open source warehouse as an alternative to BigQuery, since that would allow us to have standalone "Minikube" deployments. We haven't decided on which database to use for that though, so suggestions are welcome.

> Instructions for creating packages
> https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md

Thanks!

**Comment by jlewi** [comment]
I think it would be very cool to create an example based on Feast with the GitHub dataset. 

An interesting idea would be if we could build a model to identify issues that need attention. We could plug it into gubernator.
https://k8s-gubernator.appspot.com

That's a non-trivial amount of work but I have an intern coming this summer.

/cc @hamelhu

**Comment by woop** [comment]
> @woop Any thoughts on next steps here?

@jlewi I think using any kind of open dataset makes sense. Based on your suggestion: On which aspects of the GitHub issue would you be training a model to identify the ones that need attention? Feels like that would be quite hard.

For Feast we have been focusing on implementing it internally for new projects, so our integration with Kubeflow is still pending. Our focus now is on completing our e2e tests for Feast, as well as documentation and other infra (pypi, releases, charts). After that we can merge the e2e tests with ones that exist for Kubeflow. 

Out of curiousity, are there any public streams available on Pub/Sub?

**Comment by jlewi** [comment]
> @jlewi I think using any kind of open dataset makes sense. Based on your suggestion: On which aspects of the GitHub issue would you be training a model to identify the ones that need attention? Feels like that would be quite hard.

The PR dashboard uses a simple heuristic right now. So my idea was that we start by computing a set of features like

- Time since issue created
- Time since issue last comment
- GitHub id of creator
- GitHub id of last commentor
- Repo

And then just training a simple classifier to predict whether a given issue needs attention from a given user.

> Out of curiousity, are there any public streams available on Pub/Sub?

Off-hand none that I know of.

In terms of integrating Feast into Kubeflow some items that come to mind

* Package (ksonnet or kustomize) for Feast
  * If you have a helm package we might be able to start with that
* Does Feast have any UIs that would need to be integrated into our central dashboard?
* What would a simple example illustrating Feast look like?
  * Is there a simple example of loading features into Feast and querying for those features?

**Comment by woop** [comment]
> > @jlewi I think using any kind of open dataset makes sense. Based on your suggestion: On which aspects of the GitHub issue would you be training a model to identify the ones that need attention? Feels like that would be quite hard.
> 
> The PR dashboard uses a simple heuristic right now. So my idea was that we start by computing a set of features like
> 
> * Time since issue created
> * Time since issue last comment
> * GitHub id of creator
> * GitHub id of last commentor
> * Repo
> 
> And then just training a simple classifier to predict whether a given issue needs attention from a given user.

Which feature/label would you use to indicate the need for attention? 

> > Out of curiousity, are there any public streams available on Pub/Sub?
> 
> Off-hand none that I know of.

Actually, there is a stream! Thanks to @tims for pointing it out. [NYC taxi data pub/sub stream](https://cloud.google.com/blog/products/gcp/learn-real-time-processing-with-a-new-public-data-stream-and-google-cloud-dataflow-codelab).

This might be a good alternative to GitHub data, at least for the real-time use case.

> 
> In terms of integrating Feast into Kubeflow some items that come to mind
> 
> * Package (ksonnet or kustomize) for Feast
>   
>   * If you have a helm package we might be able to start with that
> * Does Feast have any UIs that would need to be integrated into our central dashboard?
> * What would a simple example illustrating Feast look like?
>   
>   * Is there a simple example of loading features into Feast and querying for those features?

Good points. There is a UI, although we aren't actively developing it out since they Python SDK is a faster way to release the same features. There is no need to have the UI as part of the central dashboard.

Our goal is to have the minimum amount of steps required to get Feast deployed and a client connected (Helm, pip), data loaded, and then used for both training and serving. Using some Kubeflow components for the training and serving would make for a strong showcase.

**Comment by jlewi** [comment]
Moving to 0.6 because 0.5 is already oversubscribed.

**Comment by woop** [comment]
Just bumping this. Here is a demonstration of using Kubeflow, Fairing, and Feast together (from KubeCon): https://github.com/gabrielwen/LinearModel/blob/master/feast-taxi-job.ipynb

**Comment by chrisrana** [comment]
Hey Guys,
So far my understanding was that Feast is limited GCP only.
I am trying to understand the discussion in this tickets.
Is it possible to use feast without Google Cloud.
I want to use it in AWS cloud for ML/AI use case.

**Comment by jlewi** [comment]
@gabrielwen @woop Does FEAST support any datastores that work on other clouds?

@chrisrana You might want to open an issue in gojek/feast about support for other clouds.

**Comment by woop** [comment]
> @gabrielwen @woop Does FEAST support any datastores that work on other clouds?
> 
> @chrisrana You might want to open an issue in gojek/feast about support for other clouds.

Hi @chrisrana & @jlewi: Feast 0.1 does not support non-GCP cloud providers. Primarily because of the dependency right now on BigQuery.

However, we are currently working on a decomposition for Feast as part of Feast 0.2. This would decouple our ingestion logic from our databae "population" logic. What this means is that it would be a lot simpler to add new datastores. In fact, our plans are to not have a distinction between the warehouse and serving stores.

Feast 0.2 is planned to be released in the next 1.5 months. After that we are planning to release 0.3 which will bring about a range of new functionalities.

**Comment by woop** [comment]
An update on Feast development and our roadmap going forward:

We are releasing Feast 0.2 in about two weeks time (early September), so development is on track. The release will complete the decomposition of data ingestion from feature stores, which will make it a lot easier to add new store types.

After 0.2 we will immediately start development on Feast 0.3. Feast 0.3 will focus on improving the user experience and stabilizing touch points with users (ingestion, serving). We are aiming to have Feast 0.3 done by the end of September. After that we are hoping to work on fully integrating Feast into Kubeflow for the 0.7 release.

We'd like to know from the Kubeflow community what they would like to see in order for integration to take place. Judging from feedback in this thread, the following requirements come to mind:

* Addition of non-GCP stores: Currently we only support BigQuery for feature warehousing. The addition of a non-GCP store seems like a hard requirement. This is something that we can possibly target for the 0.7 release.
* Deployment integration with Kubeflow: Users should be able to deploy Feast as a component with Kubeflow.
* End-to-end example with Kubeflow: This would demonstrate an end-to-end ML use case by enhancing an existing Kubeflow example with Feast. 

@jlewi @gabrielwen @aronchick anything else we can try to add?

**Comment by jlewi** [comment]
Seems like a good list to me.

**Comment by raghav20** [comment]
When is it gonna be done ?

**Comment by woop** [comment]
> When is it gonna be done ?

Hi @raghav20. We are finishing off some of the final components now and adding the necessary tests and packaging. You can see our progress on the 0.3.0 project in GitHub: https://github.com/gojek/feast/projects/1

**Comment by ShashankBlr** [comment]
@woop What's the status of 3 requirements which you listed in your message on Aug 19? Which of these features will be part of 0.7? Looking forward to see End-to-End example with Kubeflow.

**Comment by woop** [comment]
Hi @ShashankBlr.

Thank you for your interest in the project!

Feast 0.3 won't be included in KF 0.7. I believe the timelines were too tight. We will aim for the next release. Feast 0.3 will have an initial release out very soon. 

In terms of the requirements above:

- The open source warehouse store won't be in 0.3, but we have a lot of demand for it so we will pick it up after the 0.3 release.
- We also have somebody working on a Kustomize installation for Feast. This will allow us to easily package the installation with Kubeflow. That can be tracked over here: https://github.com/gojek/feast/issues/258
- In terms of an end-to-end notebook. The Kubeflow team had a hackathon with us two weeks ago where we kicked off development of that. It will be released with Feast 0.3. @zhilingc and @gabrielwen are working on that in their free time.

Super excited to be sharing that with the KF community once its ready!

**Comment by axsaucedo** [comment]
[Nudge for stalebot] We would be interested on this integration. Is there a design document somewhere so we could get a bit more insight on what has been discussed for this integration? Or is the implementation to be followed based on the jupyter notebook?

**Comment by woop** [comment]
> We would be interested on this integration.

[feast.dev](https://feast.dev) is a good place to start.

Currently the `docker compose` and `helm` installation with the Jupyter notebook will get you up and running with Feast 0.4. We had a contributor pick up the Kustomize component, but unfortunately it seems to have [gone stale](https://github.com/gojek/feast/issues/258).

On the to-do list for the Feast team is still
* RFC of the integration between Kubeflow and Feast
* Comprehensive e2e example with Kubeflow
* Open source store implementation (remove GCP dependency)
* (and now) https://github.com/gojek/feast/issues/258

**Comment by SaiKiranBurle** [comment]
Hello, is Feast still on track to be integrated into KubeFlow? Any idea what version of KubeFlow/Feast you are targeting?

**Comment by woop** [comment]
Hi @SaiKiranBurle,

Thanks for the interest!

Front and center for us is on-prem and multi-cloud support since not having that would be a deal breaker for integration with Kubeflow. We are directing most of our attention and resources towards either making data sources easier to add, or actually adding those data sources. You can find out more by looking
- [Feast 0.5 Roadmap](https://github.com/gojek/feast/issues/527)
- [#482: Adding a Batch Store](https://github.com/gojek/feast/issues/482)
- [#402: Factoring out storage interfaces](https://github.com/gojek/feast/issues/402)

Once we are able to support on-prem use cases then we just need to complete an e2e example, an RFC proposal, and submit a PR for the actual shared installation.

All this being said, Feast plays well with Kubeflow right now. You can install and run them both from the same cluster, and in fact that is what we are doing.

It's still important for us to fully join this community, so thank you for being so patient :)

**Comment by manasjain0699** [comment]
can I deploy feast on Kubernetes  without helm

**Comment by woop** [comment]
> can I deploy feast on Kubernetes without helm

Yes you can. Have a look at our [docker compose](https://github.com/feast-dev/feast/blob/master/infra/docker-compose/docker-compose.yml) installation for an installation that is purely docker based

**Comment by manasjain0699** [comment]
Hello whoop thanks for reply but i want the Yaml File Of each service is it possible?

**Comment by woop** [comment]
> Hello whoop thanks for reply but i want the Yaml File Of each service is it possible?

@manasjain0699 is there anything preventing you from using Helm to generate the YAML files once off, and then just using those YAML files in the future instead of Helm?

**Comment by ACodingfreak** [comment]
Just bumping up
Is FEAST integration into Kubeflow available in latest release?

**Comment by rimolive** [comment]
@ACodingfreak You can find in the docs how to use Feast with Kubeflow. https://www.kubeflow.org/docs/external-add-ons/feast/introduction/#how-to-use-feast-with-kubeflow
