### ISSUE TITLE
Unable to spawn Jupyterhub notebook on AKS

### ISSUE THREAD

**Issue by laurentgrangeau** [kubeflow/kubeflow#2144]
When trying to spawn a new notebook server on AKS cloud, it takes forever to spawn and I'm unable to connect to the desired notebook.

**Comment by jlewi** [comment]
Can you provide the output of `kubectl describe pods <JUPYTER POD>"

/cc @Jeffwan  (resident AWS expert)

**Comment by jlewi** [comment]
A is for Azure.

/cc @aronchick
