### ISSUE TITLE
[gcp-click-to-deploy] isolate each request into it's own container.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2152]
Deploy service backend should have one container per request to process all actions.
This provide container level isolation. 
Each container should exit after all actions successfully done.

**Comment by jlewi** [comment]
/assign @jlewi 

I will try to make some progress on this in the next sprint.

**Comment by jlewi** [comment]
Bump to P0 because this is blocking deploying 0.6 with click to deploy.

**Comment by jlewi** [comment]
A number of PRs have been committed; #3534 has a draft PR with a bunch of the ongoing development work.

The next steps are

1. Refactor gcp.go to fetch the information from KfDef spec

    *  Make KfDef a member of Gcp as opposed to embedding it
    * Add backfill logic for the Gcp plugin
    * Add methods that allow the web app to set the token source

1. Modify kustomize.go

    * Provide a method for injecting the RestConfig
    * Change the methods for building the RestConfig to allow injecting the token source

**Comment by jlewi** [comment]
Making steady progress on this.
I have working code in #3534 ; I'm in the process of splitting that up into individual PRs and getting them merged.

Currently waiting on #3594 after which can send out more PRs.

We don't plan on blocking releasing 0.6.X on this issue.

This issue is still P0 though because people won't be to deploy 0.6 with click to deploy until its fixed.

**Comment by jlewi** [comment]
@kunmingg and @gabrielwen will work on getting  the updated backend deployed this week.

/assign @gabrielwen @kunmingg

**Comment by gabrielwen** [comment]
Now we have deployed new backend to staging and taking traffic.

@kunmingg is this issue considered resolved?

**Comment by jlewi** [comment]
@gabrielwen Lets close this once its in production.

**Comment by jlewi** [comment]
I believe it is in staging and we are just waiting on adding garbage collection for old statefulsets before deploying in production.

**Comment by jlewi** [comment]
This has been deployed in staging and production so marking this as fixed.
