### ISSUE TITLE
File issues based on https://derekmferguson.wixsite.com/ml4nonmath

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2155]
https://derekmferguson.wixsite.com/ml4nonmath

The author spent a lot of time trying out Kubeflow and writing up his problems. Lets try to capture it and turn it into action items.

1. [Cleaning up Kubeflow K8s resources is difficult](https://derekmferguson.wixsite.com/ml4nonmath/single-post/2018/12/18/Kubeflow-Unboxing---Part-5---Installing-034-with-kfctlsh)

    * This should already be fixed in 0.3 because in 0.3 we install all resources in the namespace so you can just delete the namespace
    * He was trying to clean up all the resources from a 0.2 install; 0.2 used the default namespace.

1. [Gotchas around kfctl.sh](https://derekmferguson.wixsite.com/ml4nonmath/single-post/2018/12/18/Kubeflow-Unboxing---Part-5---Installing-034-with-kfctlsh)

     * The gotchas are basically related to the fact that you have to download the SRC and then run kfctl.sh from the source
     * I think #1419 will go along way to address this because we can ship a single go boundary rather then depending on the user downloading an unpacking a set of shell scripts.
     * deploy.kubeflow.cloud also provides a solution for folks who can use GCP.

1. [Friction getting a PVC for Jupyter](https://derekmferguson.wixsite.com/ml4nonmath/single-post/2018/12/18/Kubeflow-Unboxing---Part-6---Jupyter-Notebooks-for-Real) 

     * Jupyter wouldn't start because it needs PVC and assumes a default storage class is present
     * Cluster didn't have a default storage class
     * User had difficulty creating one

     * The simple work around is to disable PVC by setting [notebookPVCMount](https://github.com/kubeflow/kubeflow/blob/5823eca40f29687e24447f4717f5f21437ad75be/kubeflow/core/prototypes/jupyterhub.jsonnet#L12)
      * That means data would be lost if pods were preempted. This seems reasonable for users just kicking the tires; although we should try to message that to prevent users from being surprised. 
             * Could we provide a warning in the spawner UI?
       * We could have kfctl test if the cluster has a storage class defined and if not disable it.

1. [Port-forward command to Ambassador](https://derekmferguson.wixsite.com/ml4nonmath/single-post/2018/12/18/Kubeflow-Unboxing---Part-6---Jupyter-Notebooks-for-Real)

    * kubectl now supports port-forwarding to a service so that should simplify things. Not sure what else we could do.

**Comment by jlewi** [comment]
Filed issues for the above. 

Does anyone else want to do another pass through the blog and see if I missed anything?

**Comment by kunmingg** [comment]
Support [reuse existing cluster](https://derekmferguson.wixsite.com/ml4nonmath/single-post/2018/12/16/Kubeflow-Unboxing---Part-2---Kubeflow-itself) could be a useful feature.
Sometimes users don't have a reserved cluster for kubeflow only.

**Comment by jlewi** [comment]
@kunmingg Are there specific features missing for requsing an existing cluster? If users want to install Kubeflow on an existing cluster can't they just set platform to none and follow the getting started guide
https://www.kubeflow.org/docs/started/getting-started/?

**Comment by kunmingg** [comment]
@jlewi 
if platform == none, then we might not have things like IAM update and IAP utils.
Should we support following use case?

For existing GKE user, who try kubeflow for the first time, want to deploy kubeflow to their existing GKE cluster and have GCP features configured properly.

**Comment by jlewi** [comment]
@kunmingg I would like to support the use case where users install on their existing GKE clusters better; but I think we need more feedback from users about what the desired behavior is in that case.
