### ISSUE TITLE
Jupyter spawner UI should provide a warning if pod isn't backed by durable storage

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2156]
Context: see #2155 

Using PVC is a barrier to kicking the tires on Kubeflow. So we want to make it possible to deploy Kubeflow without using durable storage backing the Jupyter pod.

The spawner UI should provide a clear warning so that users don't get surprised if their pod gets preempted and their data is lost.

**Comment by kimwnasptd** [comment]
@jlewi yes we are working on it, here's a draft of what we where thinking. We will add it to the PR
![none-pvc](https://user-images.githubusercontent.com/11134742/52234458-6389f080-28ca-11e9-83a7-8aaeb5abfb3e.png)

**Comment by ioandr** [comment]
@jlewi this issue is also fixed by #2357

**Comment by ioandr** [comment]
The above warning is shown to users when no Volumes are provided in the Notebook form. 

We should consider whether the app should provide this warning after checking the `storageClass` of the K8s cluster, which is not the case right now.

**Comment by jlewi** [comment]
Marking this as fixed.

There is a follow on issue #2157 to disable the New PVC option if there is no default storage class defined.
