### ISSUE TITLE
Notebook manager UI should disable New PVC option if no default storage class is defined.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2157]
Context: #2155 

Creating a PVC to back Jupyter pods can be a major friction point for new users just kicking the tires. 

As #2155 shows users may not realize they can just disable PVC.

We can configure kfctl to test if a cluster has a default storage class and if not disable the use of PVC with jupyter by default.

**Comment by jlewi** [comment]
Rather than doing this in kfctl; perhaps we should just do this in the jupyter spawner app?

**Comment by jlewi** [comment]
according to @vkoukis, @kimwnasptd might already have implemented this in the new web app.

**Comment by kimwnasptd** [comment]
The webapp provides a warning only when the user chooses to **not** use a PVC. It doesn't currently take any action based on storage class.

I think we should check if a default storage class is set. If not, then don't allow users to *create new* PVCs, but allow them to use existing ones.

What do you think @jlewi ?

**Comment by jlewi** [comment]
@kimwnasptd I think that makes sense.

I'm going to move this to 0.6 because we already have too many issues in 0.5

**Comment by kimwnasptd** [comment]
ACK, although it shouldn't be a large one so I'll try to make a PR in the next days
/assign kimwnasptd
