### ISSUE TITLE
Docs: The reference to the deployer app should be higher in the page

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#2169]
The link to the KF deployer application is near the bottom of the deployment page https://www.kubeflow.org/docs/started/getting-started-gke/ 

It is hard to discover and is easy to miss, though it is the first deployment method we should recommend for GKE. Please move the deployer app section to the top of the page.

**Comment by sarahmaddox** [comment]
The page is now better organized and highlights the deployment UI:
https://www.kubeflow.org/docs/started/getting-started-gke/#deploy-kubeflow-on-gke-using-the-ui

/close
