### ISSUE TITLE
Docs: referenced version of KF is not the latest

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#2170]
Pages like https://www.kubeflow.org/docs/started/getting-started-gke/ refer to version 0.3.4 as the latest, while the latest is 0.3.5. We also need a more automated way to update the documentation when the new "dot" release is published.

**Comment by jlewi** [comment]
The version is set here:
https://github.com/kubeflow/website/blob/master/themes/kf/layouts/shortcodes/kf-stable-tag.html

@paveldournov do you want to send me a PR updating it to 0.3.5?

/assign @paveldournov

**Comment by paveldournov** [comment]
Done

**Comment by jlewi** [comment]
Fixed by kubeflow/website#380
