### ISSUE TITLE
Jupyter CR should create ISTIO Virtual Service

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2172]
See design doc: http://bit.ly/kf_jupyter_design_doc

We will use ISTIO to route traffic to individual jupyter notebooks.

To support this the Jupyter custom resource should create the ISTIO virtual service and define the appropriate route.

**Comment by jlewi** [comment]
@gabrielwen Are you working on this? IIUC I think getting the Jupyter CR to create the virtual service rules to set up the reverse proxy routes is one of the last blockers to using ISTIO instead of Ambassador (#2978)?

**Comment by gabrielwen** [comment]
/assign @gabrielwen 

yes: #3104

**Comment by gabrielwen** [comment]
/close

#3104 creates ISTIO virtual services.
