### ISSUE TITLE
Jupyter CR should define Authorization policy by creating ServiceRole and ServiceRoleBinding resources

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2173]
See: http://bit.ly/kf_jupyter_design_doc

To support multi-user jupyter the Jupyter CR should define ISTIO authorization policies that restrict who can access each Jupyter instance.

**Comment by lluunn** [comment]
Should we do it at the namespace level?

The Profile controller creates the ServiceRole and binds to the user, so that only this user can access services in this namespace.

@jlewi @kkasravi WDYT?

**Comment by kkasravi** [comment]
makes sense, is the profile controller being rewritten in golang yet?

**Comment by lluunn** [comment]
not yet, WIP I just started

**Comment by lluunn** [comment]
I want to add a flag, useIstio, to determine whether controller should create serviceRole etc.
But seems kubebuilder doesn't have a good way to add flags.
https://github.com/kubernetes-sigs/kubebuilder/issues/611

**Comment by lluunn** [comment]
Seems Istio doesn't have go client library: https://github.com/istio/istio/issues/8772
Not sure if we can manage Istio resources (create, watch) in our controller...

cc @jlewi

**Comment by lluunn** [comment]
We might need https://github.com/istio/api/pull/764

**Comment by lluunn** [comment]
some reference: https://github.com/banzaicloud/istio-operator/blob/master/pkg/controller/istio/istio_controller.go

**Comment by jlewi** [comment]
Moving to 0.6 because this hasn't been started yet.

**Comment by kunmingg** [comment]
Should we update issue based on previous discussions?

**Comment by jlewi** [comment]
@kunmingg Yes; if you have information please add it.

@gabrielwen I think you mentioned on Friday that fixing the Jupyter CR to work with ISTIO is one of the last blockers to using ISTIO. Is that this issue? Or are there other relevant issues?

**Comment by jlewi** [comment]
I think #2172 is the issue to get the Jupyter CR to rely on ISTIO to create the reverse proxy rules using Virtual Service. I think #2172 is blocking replacing Ambassador with ISTIO.

This issue is likely relevant for multi-user and isolating jupyter but not blocking replacing Ambassador with ISTIO.

**Comment by kunmingg** [comment]
Should we combine this with https://github.com/kubeflow/kubeflow/issues/2172?
I feel Jupyter CR shouldn't need to update auth policy for individual notebooks if we have namespace-scope auth policy.

**Comment by lluunn** [comment]
We are doing it in profile controller.

**Comment by lluunn** [comment]
dup of #2979
