### ISSUE TITLE
Install profiles CR by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2177]
Context: 
CUJ: http://bit.ly/kubeflow_cuj_multi_user
Design doc: http://bit.ly/kf_jupyter_design_doc

To support multi-user Kubeflow I think we will want to install the profiles CR by default in Kubeflow deployments.

We should probably do this in the go based implementation of kctfl (#1419) and not bother with kfctl.sh on the premise that we will be using the go based binary in 0.5.

**Comment by kkasravi** [comment]
the profiles component is now being installed in kfctl (golang)
