### ISSUE TITLE
Web app to create/delete Profile CRs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2178]
Context:
CUJ: http://bit.ly/kubeflow_cuj_multi_user
Design doc: http://bit.ly/kf_jupyter_design_doc

We'd like to use the profiles resource to create namespaces for different users/teams to consume Kubeflow in.

We might eventually want to provide a UI based experience for creating/deleting these resources.

This seems low priority to me so I'm marking it p2.

**Comment by jlewi** [comment]
Moving to 0.6 because to my knowledge no one is working on this.

**Comment by vkoukis** [comment]
@jlewi We'll pick this up as it aligns nicely with having a single, Web-based UI for Kubeflow
