### ISSUE TITLE
Issue installing Kubeflow 0.3.5 using kfctl

### ISSUE THREAD

**Issue by shinytang6** [kubeflow/kubeflow#2184]
l followed the guide from [https://www.kubeflow.org/docs/started/getting-started-minikube/](https://www.kubeflow.org/docs/started/getting-started-minikube/)

The installation gets stuck when running `${KUBEFLOW_SRC}/scripts/kfctl.sh apply all`.(wait for almost two hours)

![image](https://user-images.githubusercontent.com/22241503/50500916-6dc8fb80-0a8f-11e9-94cd-4fe133026019.png)

Am l missing something or not?

**Comment by jlewi** [comment]
Its waiting for your ambassador pods and jupyter pods to start. See here:
https://github.com/kubeflow/kubeflow/blob/76107ff3aa7f9fde6fd7f15f2ec0a69a35874efa/scripts/util-minikube.sh#L34

Can you look at your pods and see what state they are in? Most likely they are not getting scheduled from some reason.

**Comment by shinytang6** [comment]
![image](https://user-images.githubusercontent.com/22241503/50522588-ae179080-0b06-11e9-864e-4fcc778ccc0f.png)

emmm, is there something wrong?

**Comment by Ark-kun** [comment]
@IronPan I wonder why @shinytang6 has ImagePullBackoff error in the persistentagent pod.

**Comment by IronPan** [comment]
It's not easy to tell what was happening. All pipeline images are pulled from same gcr in same project. They should either be all succeed or all failed. @shinytang6 Do those pipeline pods eventually run successfully?
