### ISSUE TITLE
kfctl.sh should check the name of the deployment is < 25 characters on GCP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2189]
On GCP the kubeflow app name created by kfctl.sh is used to name the deployment as well as service accounts.

Service accounts have the form ${KFAPP}-${SUFFIX}.

Service account names must be <=30.

Therefore kfctl.sh should verify the KFAPP name is <= 25 characters to allow room for the suffix.

**Comment by jlewi** [comment]
We should also disallow "." because "." can't be used in deployment names.

**Comment by jcastill** [comment]
Is this patch good enough? I have the following results when I ran it:

Test 1:

$ ./kfctl.sh  init directory_name_contains.txt --platform none
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ GKE_API_VERSION=v1beta1
+++ dirname ./kfctl.sh
++ cd .
++ pwd
+ DIR=/home/jcastill/codigo/kubeflow/scripts
+ source /home/jcastill/codigo/kubeflow/scripts/util.sh
+ source /home/jcastill/codigo/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/jcastill/codigo/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+  4 -lt 2 
+ COMMAND=init
+ WHAT=directory_name_contains.txt
+ shift
+ shift
+ main --platform none
+ '[' init == init ']'
+ DEPLOYMENT_NAME=directory_name_contains.txt
+ parseArgs --platform none
+  2 -gt 0 
+ case $1 in
+ shift
+ PLATFORM=none
+ shift
+  0 -gt 0 
+ '[' none == gcp ']'
+ '[' -z directory_name_contains.txt ']'
+ '[' 27 -gt 25 ']'
+ echo 'Name directory_name_contains.txt should not be longer than 25 characters'
Name directory_name_contains.txt should not be longer than 25 characters
+ exit 1


Test 2:

$ ./kfctl.sh  init dir_name_contains_. --platform none
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ GKE_API_VERSION=v1beta1
+++ dirname ./kfctl.sh
++ cd .
++ pwd
+ DIR=/home/jcastill/codigo/kubeflow/scripts
+ source /home/jcastill/codigo/kubeflow/scripts/util.sh
+ source /home/jcastill/codigo/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/jcastill/codigo/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+  4 -lt 2 
+ COMMAND=init
+ WHAT=dir_name_contains_.
+ shift
+ shift
+ main --platform none
+ '[' init == init ']'
+ DEPLOYMENT_NAME=dir_name_contains_.
+ parseArgs --platform none
+  2 -gt 0 
+ case $1 in
+ shift
+ PLATFORM=none
+ shift
+  0 -gt 0 
+ '[' none == gcp ']'
+ '[' -z dir_name_contains_. ']'
+ '[' 19 -gt 25 ']'
+  dir_name_contains_. == *.* 
+ echo 'Name should not contain '\.'\'
Name should not contain '.'
+ exit 1

**Comment by jlewi** [comment]
That looks look good; want to submit a PR?

I'm on the fence about whether we should always apply the limit or only in the case platform is GCP.
