### ISSUE TITLE
Deploy script fails with unsupported k8s version 1.9.6-gke.6

### ISSUE THREAD

**Issue by alzindiq** [kubeflow/kubeflow#2193]
When running this [deployment script](https://github.com/kubeflow/kubeflow/blob/v0.2.7/scripts/gke/deploy.sh), I get: 

ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1546277056037-57e54aea64088-7cd718c2-cc1c5fc3]: errors:
- code: RESOURCE_ERROR
  location: /deployments/kubeflow/resources/kubeflow
  message: '{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"**Master
    version \"1.9.7-gke.6\" is unsupported**.","status":"INVALID_ARGUMENT","statusMessage":"Bad
    Request","requestPath":"https://container.googleapis.com/v1/projects/mydev/zones/europe-west1-b/clusters","httpMethod":"POST"}}'

The value in [cluster.jinja](https://github.com/kubeflow/kubeflow/blob/v0.2.7/scripts/gke/deployment_manager_configs/cluster.jinja) is in the list of supported master versions:

gcloud container get-server-config 
validMasterVersions:
- 1.11.5-gke.5
- 1.11.5-gke.4
- 1.11.4-gke.13
- 1.11.4-gke.12
- 1.11.3-gke.24
- 1.11.3-gke.23
- 1.11.2-gke.26
- 1.11.2-gke.25
- 1.10.11-gke.1
- 1.10.9-gke.7
- 1.10.9-gke.5
- 1.10.7-gke.13
- 1.10.7-gke.11
- 1.10.6-gke.13
validNodeVersions:
- 1.11.5-gke.5
- 1.11.5-gke.4
- 1.11.4-gke.13
- 1.11.4-gke.12
- 1.11.4-gke.8
- 1.11.3-gke.24
- 1.11.3-gke.23
- 1.11.3-gke.18
- 1.11.2-gke.26
- 1.11.2-gke.25
- 1.11.2-gke.20
- 1.11.2-gke.18
- 1.11.2-gke.15
- 1.11.2-gke.9
- 1.10.11-gke.1
- 1.10.9-gke.7
- 1.10.9-gke.5
- 1.10.9-gke.3
- 1.10.9-gke.0
- 1.10.7-gke.13
- 1.10.7-gke.11
- 1.10.7-gke.9
- 1.10.7-gke.6
- 1.10.7-gke.2
- 1.10.7-gke.1
- 1.10.6-gke.13
- 1.10.6-gke.11
- 1.10.6-gke.9
- 1.10.6-gke.6
- 1.10.6-gke.4
- 1.10.6-gke.3
- 1.10.6-gke.2
- 1.10.6-gke.1
- 1.10.5-gke.4
- 1.10.5-gke.3
- 1.10.5-gke.2
- 1.10.5-gke.0
- 1.10.4-gke.3
- 1.10.4-gke.2
- 1.10.4-gke.0
- 1.10.2-gke.4
- 1.10.2-gke.3
- 1.10.2-gke.1
- 1.9.7-gke.11
- 1.9.7-gke.7
- **1.9.7-gke.6**
- 1.9.7-gke.5
- 1.9.7-gke.4
- 1.9.7-gke.3
- 1.9.7-gke.1
- 1.9.7-gke.0
- 1.9.6-gke.2
- 1.9.6-gke.1
- 1.9.3-gke.0
- 1.8.12-gke.3
- 1.8.12-gke.2
- 1.8.12-gke.1
- 1.8.12-gke.0
- 1.8.10-gke.2
- 1.8.10-gke.0
- 1.8.9-gke.1
- 1.8.8-gke.0
- 1.7.15-gke.0
- 1.7.12-gke.2
- 1.6.13-gke.1

**Comment by jlewi** [comment]
1.9.7-gke.6 is not in the support master version. It is a support Node version but the list of supported master versions is much smaller.

@alzindiq There are two ways to fix this

1. You can edit the jinja file and select one of the supported master versions.
1. You can switch to using 0.3 [instructions](https://www.kubeflow.org/docs/started/getting-started-gke/) or 0.4.

**Comment by alzindiq** [comment]
Thanks a lot @jlewi! Option 1 works great!
