### ISSUE TITLE
Seeing kubeflow usage statistics

### ISSUE THREAD

**Issue by armandmcqueen** [kubeflow/kubeflow#2195]
Is the anonymous usage data available to the public anywhere?

**Comment by jlewi** [comment]
The usage data isn't publicly available. If someone was interested in analyzing and generating public reports from the data access could probably be granted. 

Maybe someone from the pm community?

**Comment by aronchick** [comment]
We should really have at least a graph of usage - the usage is contributed by the community, and will help in building out our public backlog.

**Comment by armandmcqueen** [comment]
@aronchick @jlewi @abhi-g 

Any progress on that? Is there any way that we can contribute to push this forward? Some data about usage could help anyone who is trying to make an argument for using/contributing to Kubeflow.

**Comment by abhi-g** [comment]
sorry haven't had a chance to make much progress on this yet.. But I
understand the priority on this.. Will update soon.

**Comment by armandmcqueen** [comment]
Bump. We'd really like to see this data. Let us know if we can contribute to move this forward.

**Comment by jlewi** [comment]
We're pretty swamped right now getting the 0.5 release out so not getting a lot of attention right now.
