### ISSUE TITLE
rest_api_port support by tf-serving

### ISSUE THREAD

**Issue by wfchair** [kubeflow/kubeflow#2197]
tf-serving-deployment-aws prototype added support to rest_api_port , but tf-serving not yet.
If we use nfs volume for tfserving data, we have to use tf-serving.
Would you like also to add rest_api_port support into tf-serving prototype?

https://github.com/kubeflow/kubeflow/blob/583d5af66a4ebfbd45792fc29656e09842e69359/kubeflow/tf-serving/tf-serving.libsonnet#L121

**Comment by jlewi** [comment]
Did you consider using ksonnet to override the parameters inside your generated component? One of the advantages of using ksonnet is that authors of the template don't need to explicitly expose everything as a a parameter in order for you to change them. 

You should be able to use a mixin to set the command line arguments like we do here for the environment variables:
https://github.com/kubeflow/kubeflow/blob/583d5af66a4ebfbd45792fc29656e09842e69359/kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet#L40

If you'd like to submit a PR to expose port I think that would be valuable.

/cc @lluunn
