### ISSUE TITLE
ksonnet installation of core giving 404

### ISSUE THREAD

**Issue by cpedrinaci** [kubeflow/kubeflow#2201]
While doing a manual install I'm hitting an issue trying to install the core component on v0.3.5:

```bash 
$ ks pkg install kubeflow/core

ERROR resolving package metadata: kubeflow/core: GET https://api.github.com/repos/kubeflow/kubeflow/contents/kubeflow/core/parts.yaml?ref=83a408a7db5e2d88b321aefaeeb627d4604b65f0: 404 Not Found []
```

Other components can be installed apparently but not core.
I have tried using different versions of the registry and I keep getting the same problem so this may well be a local issue but given that I can install other packages I find it weird.. 
Any ideas what may be going on?

Note: A registry describe does list core as one of the available packages 

```bash
$ ks registry describe kubeflow

REGISTRY NAME:
kubeflow

URI:
https://github.com/kubeflow/kubeflow/tree/v0.3.5/kubeflow

PROTOCOL:
github

PACKAGES:
  argo
  automation
  chainer-job
  core
...
```

**Comment by jlewi** [comment]
I think when you install the package you need to specify the branch or sha you want otherwise it defaults to master.

e.g.

```
ks pkg install kubeflow/core@v0.3-branch
```

The core package has been renamed to common on 0.4 and master.

**Comment by jwwandy** [comment]
I also met this issue and @jlewi's suggestion works for me.

**Comment by cpedrinaci** [comment]
Thanks @jlewi that worked
