### ISSUE TITLE
Create a script to update kubeflow repository with newer component image tags

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#2206]
See https://bit.ly/2F7o4gM  for the release process proposal.

Currently updating component image tags require manual steps prior to each release. We need to automate this process so we can run e2e tests on latest component builds. 

The script should do the following:
 For each core component:
   - tf-operator
   - pytorch-operator
   - katib
   - centraldashboard
   - Jupyter notebooks
1. Find the latest "green" Docker image on gcr.io.
2. Use a script like [this one](https://github.com/kubeflow/kubeflow/blob/master/releasing/update_component.sh) to update the version on kubeflow/kubeflow
3. Create a PR using a tool like [hub](https://github.com/github/hub). An example can be found [here](https://github.com/kubeflow/examples/blob/master/code_search/docker/ks/update_index.sh#L63).

The script can either be run as a daily cron job, or automatically triggered from postsubmits.

**Comment by jlewi** [comment]
Next steps

1. Verify cron jobs are running successfully.

1. The PRs created don't satisfy the CLA check because the author is not kubeflow-bot. We should try to fix that by configuring the email.

**Comment by jlewi** [comment]
Looks like the cron job ran successfully and created a PR.

https://github.com/kubeflow/kubeflow/pull/3149

**Comment by jlewi** [comment]
Earlier PR was merged #3144

**Comment by jlewi** [comment]
Marking this as fixed since we filed #3155.
