### ISSUE TITLE
Kfctl requires zone to be specified. Could be potentially automatically inferred.

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#2209]
kfctl init requires that zone be specified manually with the command. It would be helpful to infer it automatically and yet allow the user to override it with the flag if needed.

**Comment by jlewi** [comment]
@abhi-g Is there more work to be done here or can we close this? Do we need to cherry pick the fix onto the 0.4 branch?

**Comment by abhi-g** [comment]
We can close this. This has already been cherrypicked into 0.4

Abhishek
