### ISSUE TITLE
Create a bot to auto-approve certain types of PRs

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#2213]
We have a number of PRs that do not need manual review and approval. Examples include:
- Cherry pick PRs to release branches
- Auto-generated PRs to update component tags (see https://github.com/kubeflow/kubeflow/issues/2206)

We should consider creating a bot that automatically approves these PRs.

**Comment by jlewi** [comment]
What priority is this? Should we try to do this as part of 0.5?
