### ISSUE TITLE
Serving R models using kubeflow

### ISSUE THREAD

**Issue by chennupushkar** [kubeflow/kubeflow#2223]
Can we server R models using kubeflow?

**Comment by aronchick** [comment]
Sure thing! There are two serving packages to do so. You can use Seldon (https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/r.md) or you can package your R as an ONNX file and use TensorRT (https://github.com/onnx/onnx-tensorrt).

**Comment by chennupushkar** [comment]
Thanks for you response.Which one Seldon or ONNX/TensorRT has wide adoption for Kubeflow? Can you please suggest?
Thanks,Pushkar
    On Monday, January 7, 2019, 12:34:25 PM PST, David Aronchick <notifications@github.com> wrote:  
 
 
Sure thing! There are two serving packages to do so. You can use Seldon (https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/r.md) or you can package your R as an ONNX file and use TensorRT (https://github.com/onnx/onnx-tensorrt).

**Comment by jlewi** [comment]
Seldon contributors are very active in Kubeflow. 

But really I think there are bigger differences which affect which solution is the right use case for you.

Seldon provides a custom resource that makes it easy to express inference as a graph of microservices. 

Providing a model server is just one piece of Seldon; and Seldon Core can be used with other model servers so I think it could be used with TensorRT.

NVIDIA's TensorRT inference server is particularly valuable if you are trying to leverage GPUs.

**Comment by ahousley** [comment]
Hi @chennupushkar, did you make any progress with Seldon Core? Please let me know if we can help.

Also, here are the new docs for serving R models: https://docs.seldon.io/projects/seldon-core/en/latest/R/README.html
