### ISSUE TITLE
Unify the kubeflow project image location

### ISSUE THREAD

**Issue by chenzhiwei** [kubeflow/kubeflow#2226]
Kubeflow project includes many docker images, but they are in different locations.

Can we put them into a unified location?

And we can also use same logic to build and publish images, such as `Makefile`.

This will make the images are easy to maintain.

There are following works and I am working on first one:

1. Unify the image dockerfiles

    Makes the dockerfiles can build both amd64 and ppc64le docker images.

    * https://github.com/kubeflow/tf-operator/pull/893
    * ~~https://github.com/kubeflow/pipelines/pull/562~~
    * ~~https://github.com/kubeflow/pipelines/pull/567~~
    * ~~https://github.com/kubeflow/tf-operator/pull/892~~
2. Unify the image build logics

    * `make build-image` to build image
    * `make build-image-ppc64le` to build ppc64le image
    * `make push-image` to push image to registry
    * `make mirror-image` to mirror image

3. Unify the image locations

**Comment by jlewi** [comment]
Thanks for helping out. 

Can you elaborate on what you are working on? Which Dockerfiles are you planning on refactoring?

**Comment by chenzhiwei** [comment]
@jlewi I just updated the issue to include the related PRs, and will also include new PRs when available. My plan is first to make all docker images are buildable by makefile, then unify the location. There are two alternatives: `docker.io/kubeflow` and `gcr.io/kubeflow-images-public`.

**Comment by jlewi** [comment]
I'd like to support both docker and gcr.io and possibly others. It would be great to setup the ability to automatically mirror our docker images across registries.

There's been a long standing issue to fix this. see #211. Would love to find someone willing to drive that.

**Comment by gyliu513** [comment]
@dreamryx

**Comment by dreamryx** [comment]
I will continue the work.  The dockerfiles of related image are list as below:

| image/dockerfile | repo |
| ------ | ------ |
centraldashboard | kubeflow
ambassador | ambassador-envoy
jupyterhub-k8s | kubeflow
vizier-core | katib
vizier-core-rest | katib
studyjobcontroller | katib
metricscollector | katib
suggestion-random | katib
suggestion-grid | katib
suggestion-hyperband | katib
suggestion-bayesianoptimization | katib
katib-ui | katib
metacontroller | kubeflow
pytorch-operator | pytorch-operator

**Comment by gyliu513** [comment]
we are still working for this.

**Comment by jlewi** [comment]
@gyliu513 What are the next steps?

**Comment by gyliu513** [comment]
@jlewi we are now working for multi-arch support at https://github.com/kubeflow/kubeflow/issues/2633 , and will resume this after https://github.com/kubeflow/kubeflow/issues/2633 finished, hope it is OK.
