### ISSUE TITLE
Move troubleshooting guide into user_guide

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#223]
Following the instruction for user_guide.md, saw the following error.
I am on google cloud GKE

my-kubeflow ks apply ${KF_ENV} -c kubeflow-core

INFO  Updating services kubeflow.k8s-dashboard
INFO  Updating services kubeflow.tf-hub-0
INFO  Updating services kubeflow.tf-hub-0
INFO  Updating clusterrolebindings ambassador
INFO  Updating roles kubeflow.jupyter-role
INFO  Creating non-existent roles kubeflow.jupyter-role
ERROR Error updating roles kubeflow.jupyter-role: roles.rbac.authorization.k8s.io "jupyter-role" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]}] user=&{blad@blah.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger-2.0.0.pb-v1"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger.json"], Verbs:["get"]}] ruleResolutionErrors=[]

Saw [this change](https://github.com/kubeflow/kubeflow/pull/82/files), and followed the following and it worked. 
Should we add it back to the doc?

-### Google Kubernetes Engine	
-	
-[Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/) is a managed environment for deploying Kubernetes applications powered by Google Cloud.	
-If you're using Google Kubernetes Engine, prior to creating the manifests, you must grant your own user the requisite RBAC role to create/edit other RBAC roles.	
-	
-```commandline	
-kubectl create clusterrolebinding default-admin --clusterrole=cluster-admin --user=user@gmail.com	
-```

**Comment by jlewi** [comment]
The relevant information is in the [troubleshooting guide](https://github.com/kubeflow/kubeflow#troubleshooting) in our README.md 

The fact that the information is not in our user_guide seems undesirable.

I suggest moving the troubleshooting guide into the user_guide.

On the main page we should update the troubleshooting information to just be a link to the relevant section in the user_guide.

**Comment by fxue** [comment]
I can take a stab at this.

**Comment by fxue** [comment]
[Pull request](https://github.com/kubeflow/kubeflow/pull/234) out for review.
