### ISSUE TITLE
Docs/Example for Jupyter Custom Resource

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2232]
We need docs and an example for using the new Jupyter custom resource to create notebooks.

This will be useful for the folks working on the new web app to spawn notebooks #1995.

/cc @vkoukis @ioandr

**Comment by vkoukis** [comment]
ACK. We will work on documenting how to spawn the new Jupyter CR as part of implementing #1995.
/cc @kimwnasptd who will be joining our team and working on this along with @ioandr .

**Comment by sarahmaddox** [comment]
Hallo @vkoukis @ioandr @kimwnasptd how are you doing with docs/example for the new Jupyter UI? If you'd like to pass me any material you have, I'm happy to work on a doc. I've created
https://github.com/kubeflow/website/issues/561 for the website update.
