### ISSUE TITLE
[Design] Doc for how application CRD will be used in Kubeflow?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2233]
Background:
#2024  - Discussion on composability
#2154 - Fix application CRD

In 0.4 @kkasravi added an application custom resource for Kubeflow.

I think we'd like to continue in the direction of splitting up Kubeflow into a set of applications (e.g. pipelines, tf-job-operator, Katib). For that I think we want each application to have its own Application CR describing it.

I think we need a doc/proposal though laying out how we plan to use Application CR's.

@kkasravi Do you want to take a stab at this?

**Comment by jlewi** [comment]
This is relates to #1472 understanding the maturity of each component.

**Comment by jlewi** [comment]
Adding this to the landing page CUJ.

I think our initial use case for application CRs is

* Monitoring Kubeflow
* Getting events about Kubeflow deployment and applications

Both of these relate to the landing page; i.e. the landing page would like to show Kubeflow events which might depend on grouping events by application.

**Comment by jlewi** [comment]
0.5 is already highly oversubscribed. I'm moving this to 0.6.

**Comment by jlewi** [comment]
@kkasravi and I have been working on a doc. Hope to share more broadly soon.

**Comment by kkasravi** [comment]
The document is here https://docs.google.com/document/d/11vAkC25uNvm2z2smLUPmySZS16fjud6M2GFN6W-hYW8/edit#heading=h.ss1azctmy08s

closing this issue
