### ISSUE TITLE
seldon gRPC

### ISSUE THREAD

**Issue by sathiez** [kubeflow/kubeflow#2239]
When I use seldon gRPC I can able to send reques to ambassador 

Ambassador log:
**ACCESS [2019-01-08T09:27:41.888Z] "POST /seldon.protos.Seldon/Predict HTTP/2" 200 - 55 0 4 4 "-" "grpc-python/1.17.1 grpc-c/7.0.0 (manylinux; chttp2; gizmo)" "100435d4-e6cb-4ee8-8358-09d3c062068c" "192.168.1.246:80" "10.103.147.139:5001"**

But unable to reach model. I get the following error in client side,

**status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "{"created":"@1546944550.267361879","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"","grpc_status":2}"**

how to solve this error?

**Comment by cliveseldon** [comment]
There is a issue opened by @sathiez [here](https://github.com/SeldonIO/seldon-core/issues/365#issuecomment-453078073)
