### ISSUE TITLE
Go based implementation of Jupyter CR?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2269]
The Jupyter custom resource is currently implemented as a lambda using jsonnet and meta controller.

Should we replace this with a GoBased implementation of the lambda and continue to use meta controller?

We need to add more functionality to the CR e.g.

* Create ISTIO resources (#2172)

Furthermore, the ISTIO resources might vary depending on whether we want to validate the JWT or not (http://bit.ly/kf_jupyter_design_doc).

I think implementing this in Go might make the code easier to test and maintain in the long term?

@kkasravi What do you think?

Do we have a good example of a lambda for a CR that we could copy? I think the pipelines time has implemented a CR
https://github.com/kubeflow/pipelines/tree/master/backend/src/crd/controller/viewer

Not sure if its using metacontroller.

**Comment by kkasravi** [comment]
I believe they used [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime).
AFAIK metacontroller doesn't do golang.

We have a few choices for a lambda CR

1. Migrate the jsonnet hooks to use controller-runtime in a similar way
2. Use kubebuilder which also leverages controller-runtime
3. Migrate the hook(s) to use kubeless golang hooks
4. Extend meta-controller to include golang

**Comment by jlewi** [comment]
controller-runtime seems like a good choice. Any reason not to go with that and be consistent with kubeflow/pipelines?

**Comment by kkasravi** [comment]
Not that I can think of. Would a good first case be profiles?

**Comment by stpabhi** [comment]
We can use kubebuilder to generate the boilerplate code.

**Comment by lluunn** [comment]
@kkasravi @jlewi I can take a stab at this one if you haven't started (or the profile one)

**Comment by kimwnasptd** [comment]
Hi everyone, we've noticed with @ioandr that one issue with the current UX using JupyterHub is that when a user spawns a Notebook they don't get any feedback for the underlying Pod's status. Specifically, they would just wait for the Pod to start but wouldn't be notified if an error with the Pod's scheduling would occur.
We believe it could help if the Pod's status was mapped in the Notebook's CR. Then we could in turn show it and inform the user from the UI. Any thoughts on this @jlewi @lluunn ?

**Comment by lluunn** [comment]
Yeah I think we can relay the pod status to notebook CR's status

**Comment by lluunn** [comment]
Filed #2417 for followup
