### ISSUE TITLE
Go based implementation of the profiles custom resource?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2270]
Currently the profiles custom controller is implemented using metacontroller with the sync function implemented in jsonnet.

Should we switch to a go based implementation? I think the primary reason for switching to go would be that it has a much higher ceiling; i.e. if we want to do more complicated things either; we won't find ourselves limited by jsonnet. It should also be easier to write unittests.

@kkasravi WDYT

**Comment by lluunn** [comment]
Agree that we just need one controller, profile, and it will create the namespace+role+rolebinding.

@kkasravi I can take on this you haven't started?
