### ISSUE TITLE
Can't paste into terminal within JupyterLab behind IAP

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#2273]
When copying text externally, such as the name of a python package one wants to install, then attempting to paste this into the terminal:
(1) This works fine with JupyterLab accessed via port forward without IAP enabled,
(2) This does not work with JupyterLab accessed via IAP,

It is worth noting that this same issue occurs for JupyterLab instances spawned via mybinder.org's [Try Jupyter](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab%2Ftree%2Fdemo%2FLorenz.ipynb) service and thus may be a problem more general than solely the concerns of Kubeflow.

**Comment by jlewi** [comment]
Has anyone else observed this?

I've always found copy-paste behavior in JupyterLab to be finicky but haven't associated any differences with IAP.
