### ISSUE TITLE
GCP secrets are not created unless oAuth credentials are provided

### ISSUE THREAD

**Issue by DanSanche** [kubeflow/kubeflow#2284]
I noticed the [code to create GCP service account secrets](https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/util.sh#L204) comes after a line that checks for oAuth environment variables. This seems unnecessary, because everything works fine if I provide fake values for the oAuth id and secret. Was this intentional?

This is likely causing people to run into issues like #1949 and #1950 which are hard to diagnose without looking at the code

**Comment by DanSanche** [comment]
Opened PR here: https://github.com/kubeflow/kubeflow/pull/2313

**Comment by jlewi** [comment]
@DanSanche Can we close this issue? Does this warrant a cherry-pick onto the 0.4 branch?

**Comment by DanSanche** [comment]
Yes, sorry this is good to close. I opened and merged a 0.4 cherry-pick PR here: https://github.com/kubeflow/kubeflow/pull/2324
