### ISSUE TITLE
4.1 deployment fails iap-enabler 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#2287]
Just deployed the latest kf 4.1 build using the one click deployment with IAP enabled. erring out on:

iap-enabler | 0 of 1 updated replicas available - CrashLoopBackOff
-- | --

Error logs as follows: 
[
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "1k1whrrg11gi4it",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:34:12Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:34:49.189776760Z"
 },
 {
   "textPayload": "\n",
   "insertId": "1k1whrrg11gi4is",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:34:12Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:34:49.189776760Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "1k1whrrg11gi4ij",
   "resource": {
     "type": "container",
     "labels": {
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2"
     }
   },
   "timestamp": "2019-01-16T02:34:12Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:34:49.189776760Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "kjdxeyfzqyl7a",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:31:18Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:31:49.143115719Z"
 },
 {
   "textPayload": "\n",
   "insertId": "kjdxeyfzqyl76",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:31:18Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:31:49.143115719Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "kjdxeyfzqyl6p",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:31:18Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:31:49.143115719Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "qdc4yefzn2by0",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:29:43Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "\n",
   "insertId": "qdc4yefzn2bxz",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:29:43Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "qdc4yefzn2bxq",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:29:43Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "qdc4yefzn2bxk",
   "resource": {
     "type": "container",
     "labels": {
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2"
     }
   },
   "timestamp": "2019-01-16T02:28:54Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "\n",
   "insertId": "qdc4yefzn2bxj",
   "resource": {
     "type": "container",
     "labels": {
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019"
     }
   },
   "timestamp": "2019-01-16T02:28:54Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "qdc4yefzn2bxa",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:28:54Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:29:49.117885570Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "ldezrdf1pvsz8",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:28:18Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:28:49.177587782Z"
 },
 {
   "textPayload": "\n",
   "insertId": "ldezrdf1pvsz7",
   "resource": {
     "type": "container",
     "labels": {
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019"
     }
   },
   "timestamp": "2019-01-16T02:28:18Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:28:49.177587782Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "ldezrdf1pvsyy",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:28:17Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:28:49.177587782Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "1xdilbefzrfhiz",
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:27:10Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:27:49.090494607Z"
 },
 {
   "textPayload": "\n",
   "insertId": "1xdilbefzrfhiy",
   "resource": {
     "type": "container",
     "labels": {
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2"
     }
   },
   "timestamp": "2019-01-16T02:27:10Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:27:49.090494607Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "1xdilbefzrfhip",
   "resource": {
     "type": "container",
     "labels": {
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "zone": "us-central1-a",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap"
     }
   },
   "timestamp": "2019-01-16T02:27:09Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:27:49.090494607Z"
 },
 {
   "textPayload": "Your active configuration is: [default]\n",
   "insertId": "1t7us4rfzpjno5",
   "resource": {
     "type": "container",
     "labels": {
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap"
     }
   },
   "timestamp": "2019-01-16T02:26:38Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:26:49.137332039Z"
 },
 {
   "textPayload": "\n",
   "insertId": "1t7us4rfzpjno3",
   "resource": {
     "type": "container",
     "labels": {
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019",
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054"
     }
   },
   "timestamp": "2019-01-16T02:26:38Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q",
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:26:49.137332039Z"
 },
 {
   "textPayload": "Activated service account credentials for: [kubeflow-demo-2019-admin@chavoshi-dev-2.iam.gserviceaccount.com]\n",
   "insertId": "1t7us4rfzpjnnn",
   "resource": {
     "type": "container",
     "labels": {
       "container_name": "iap",
       "namespace_id": "kubeflow",
       "instance_id": "2231077818443443054",
       "pod_id": "iap-enabler-6565b855d6-8lhx9",
       "zone": "us-central1-a",
       "project_id": "chavoshi-dev-2",
       "cluster_name": "kubeflow-demo-2019"
     }
   },
   "timestamp": "2019-01-16T02:26:37Z",
   "severity": "ERROR",
   "labels": {
     "container.googleapis.com/pod_name": "iap-enabler-6565b855d6-8lhx9",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "kubeflow",
     "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-5rq8q"
   },
   "logName": "projects/chavoshi-dev-2/logs/iap",
   "receiveTimestamp": "2019-01-16T02:26:49.137332039Z"
 }
]

**Comment by jlewi** [comment]
Looks like the code is stuck here;
https://github.com/kubeflow/kubeflow/blob/d9f82d2fefb36e5b46447413fd20786f8fb4cb4c/kubeflow/gcp/configure_envoy_for_iap.sh#L34

@kunmingg I suspect the code is swallowing the error from gcloud activate service account because we do `&&`

```
gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} && break || sleep 10`
```

I suspect if we did something like

```
gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}  
RESULT=$?

if [ "${RESULT}" -eq 0 ]; then
  break
fi
sleep 10
```
@kunmingg  this looks like issue #1807 

@SinaChavoshi Can you try deleting the pod and seeing what happens?

And when you fetch logs its typically much more readable if you format them as a table e.g. 

```
gcloud --project=${PROJECT} logging read --format="table(timestamp, textPayload)" ...
```

**Comment by SinaChavoshi** [comment]
I have already delete the instance however after redeploy this issue did not repro.

**Comment by kunmingg** [comment]
@jlewi 
I feel it might caused by new service account's freeze window (roughly 1 minute).
Under some cases the freeze window might be much longer than we expected. And block follow up actions.

**Comment by jlewi** [comment]
@kunmingg But it looks like the script is stuck in a retry loop. @SinaChavoshi did you wait longer than a minute?

**Comment by jlewi** [comment]
@kunmingg; the other possibility is that this is an instance of the insufficient permissions issue (#953). I think as mentioned above we might be swallowing the error message outputted by gcloud which is why we aren't seeing that particular error message.

Can we make the fix mentioned in https://github.com/kubeflow/kubeflow/issues/2287#issuecomment-454806514
just to eliminate that as a possibility in the future?

**Comment by Radhika108** [comment]
Does not work on  the free tier of Google Cloud

**Comment by hilliao** [comment]
I am using the $300 promotional credit to create IAP enabled Kubeflow. Last error at https://deploy.kubeflow.cloud/#/deploy is 

> 2019-08-13 22:07:00.343: Could not redirect to Kubeflow Dashboard at: https://kubeflow-2.endpoints.[project ID].cloud.goog/

Upon inspecting Kubernetes engine > workloads > iap-enabler, I found failed iap-enabler deployment which has failed pod iap-enabler-778889874f-2qtfn. _Running kubectl  --namespace istio-system logs iap-enabler-778889874f-2qtfn_ returns the following:

> disable_usage_reporting = true
> project = [...]
> [metrics]
> environment = github_docker_image
> 
> Your active configuration is: [default]
> node port is 31380
> fetching backends info with envoy-ingress: {"k8s-be-31380--3b1d5b52ed97ad8b":"HEALTHY","k8s-be-32705--3b1d5b52ed97ad8b":"HEALTHY"}
> backend name is k8s-be-31380--3b1d5b52ed97ad8b
> Waiting for backend id PROJECT=[...] NAMESPACE=istio-system SERVICE=istio-ingressgateway filter=name\~k8s-be-31380--3b1d5b52ed97ad8b
> BACKEND_ID=5395562060905042186
> patch JWT audience: /projects/398383548982/global/backendServices/5395562060905042186
> policy.authentication.istio.io/ingress-jwt not patched
> Clearing lock on service annotation
> service/istio-ingressgateway not patched
> Sat Sep 14 04:59:14 UTC 2019 WARN: Backend check failed, restarting container.


If it is a problem in the free or trial tier, creating the Kubeflow with "Login with username password" instead of IAP would succeed and redirect you to the Kubeflow dashboard. I tested it and saw the Kubeflow dashboard login page right after deployment succeeded.

**Comment by kierenj** [comment]
I'm not on free tier - am using OAuth - but I see exactly the same as the above. Is there a recommende way forward - or is there something I can do to diagnose?
