### ISSUE TITLE
[Question/bug] JupyterLab via IAP gives "Error 413 (Request Entity too Large)"; GCP_IAP_XSRF_NONCE cookies

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#2289]
Kubeflow v0.3.5 was deployed with via kfctl.sh (with IAP enabled) as described here: https://www.kubeflow.org/docs/started/getting-started-gke/.

For the past several days the Kubeflow dashboard, pipelines dashboard, and tfjob dashboard, and JupyterHub have all been accessible. Now I see the Kubeflow dashboard remains accessible but linking over to any other of these services gives the error listed in the subject. Update: I now see this for the main dashboard as well.

The user pod I was using for JupyterLab is still accessible via kubectl exec.

I'm guessing re-deploying would fix it. But maybe this is resulting from a bug that can be fixed. @jlewi or whoever else let me know if there are specific logs that you would like shared.

**Comment by cwbeitel** [comment]
I tried accessing the dashboard again via the public url (${deployment}.endpoints.${project}.cloud.goog) from another device and all of the above worked without error. Upon re-starting the device that was showing the error the error was no longer shown / all of the above worked.

**Comment by cwbeitel** [comment]
That's a good suggestion.

I observed this again today. After a period of 1-2 hours of displaying the above message the issue went away without my restarting the device or browser in case that's relevant.

Also to clarify what I as describing initially was an outage that appeared to be specific to one device and to be resolved by re-starting that device but that may have just been a timing coincidence.

**Comment by ediphy-azorab** [comment]
We've been getting this on our internal systems - it appears to be an issue with google's IAP leaving lots of `GCP_IAP_XSRF_NONCE_{...}` cookies, which eventually build up until the IAP starts rejecting requests.

Your cause may be the same.

**Comment by cwbeitel** [comment]
@ediphy-azorab Thank you for sharing!

**Comment by DanCech** [comment]
Ended up here looking for a solution to the same issue, and can confirm that I am also seeing tons of `GCP_IAP_XSRF_NONCE_{...}` cookies when I get the 413 error.

**Comment by jlewi** [comment]
Thanks @DanCech and @ediphy-azorab for digging into this.

So is the workaround to just delete the GCP_IAP_XSRF_NONCE cookies?

Is it JupyterLab that is returning the 413 error? So other URls like the central dashboard are accessible but only the jupyter lab endpoint hits this issue?

**Comment by ediphy-azorab** [comment]
It's google's proxy that returns the 413, so there's no way to prevent it at the jupyterlab end. Clearing the cookies is the only workaround I'm aware of.
