### ISSUE TITLE
Add script to export inception into SaveModel from checkpoints

### ISSUE THREAD

**Issue by yupbank** [kubeflow/kubeflow#229]
Since the model-serving is very sensitive with the `signature_def`.

While the existing public exported savedModel is kind of a blackbox. Or maybe there are some code related to `gs://kubeflow-models/inception` @vishh

**Comment by jlewi** [comment]
What is the larger goal here with inception?

If we're planning on turning this into an E2E example using inception, then I suggest we create an issue for this in kubeflow/examples and start putting code into that repo. Including a script to export the model if one is needed.


/cc @elsonrodriguez

**Comment by elsonrodriguez** [comment]
Yeah, this is something that's lacking.

I have an example for mnist here: https://github.com/elsonrodriguez/examples/tree/e2e/e2e (specifically https://github.com/elsonrodriguez/examples/blob/e2e/e2e/export.py

It's being reworked to use Estimator here, which is a bit simpler: https://github.com/elsonrodriguez/examples/blob/a10a7d6d67056b8deece53d3db364b672369d29b/e2e/model.py#L155

**Comment by jlewi** [comment]
Duplicate of kubeflow/examples#4
