### ISSUE TITLE
Sending predictions through TF-Serving returns 404's when using IAP

### ISSUE THREAD

**Issue by Youki** [kubeflow/kubeflow#2302]
Tried tf-serving examples shown in [this page](https://www.kubeflow.org/docs/guides/components/tfserving_new/). When I send a REST request through ingress and IAP, I got a following error with 90+% probability while it works fine with 10-% probability.

Error:
```
$ python iap_request.py https://kubeflow-app.endpoints.yaboo-sandbox.cloud.goog/tfserving/models/mnist/ $IAP_CLIENT_ID
/usr/local/google/home/yaboo/Packages/anaconda3/envs/mlpipeline/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
404 page not found
```

Success:
```
$ python iap_request.py https://kubeflow-app.endpoints.yaboo-sandbox.cloud.goog/tfserving/models/mnist $IAP_CLIENT_ID
/usr/local/google/home/yaboo/Packages/anaconda3/envs/mlpipeline/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{
 "model_version_status": [
  {
   "version": "1",
   "state": "AVAILABLE",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  }
 ]
}
```

**Comment by jlewi** [comment]
You could also kubectl port-foward to the TFServing REST port and then send requests to your local port.

**Comment by Youki** [comment]
@jlewi Thanks for the comment. The problem only happens when I send prediction requests through IAP from a node outside of a k8s cluster. There was no error when I used port-forward to TF-Serving Pods/Service.

**Comment by jlewi** [comment]
Thanks @Youki. This means it could either be an issue with IAP or Ambassador.

The next time you observe this problem could you try deleting the Ambassador pods.

```
kubectl delete pods -l service=ambassador
```

One possibility is that some Ambassador instances didn't load the route to the model which is why you get the 404 sometimes.

**Comment by Youki** [comment]
This issue is not reproducible any more with v0.4.1. So, I will close this issue.
