### ISSUE TITLE
Using Cloud Filestore - kfctl.sh apply locks the cloud shell screen and crashes after 5-10 min

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#2309]
_From @SinaChavoshi on January 17, 2019 21:47_

I manually created a file store, then following the instructions on "Configure Kubeflow to mount the Cloud Filestore volume" . When running 

${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s 

screen hangs for 5-10 min then crashes with 
+ echo environment default already exists
environment default already exists
+ ks apply default -c ambassador
/home/chavoshi/kubeflow_src/scripts/kfctl.sh: line 213:  1284 Killed                  ks apply default -c ambassador

_Copied from original issue: kubeflow/website#424_

**Comment by jlewi** [comment]
If you're running in Cloud Shell are you using boosted mode?

**Comment by jlewi** [comment]
@SInaChavoshi?
