### ISSUE TITLE
multiple deployments in the same project appear to make envoy pods crashloop

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#2310]
Multiple (differently named) deployments in the same project -- created via the launcher UI -- appear to cause the envoy pods to crash for any deployments after the first one.  This was observed with 'non-IAP' clusters -- I don't know if IAP clusters see the same.

It's not a case of needing to wait it out for a few mins.  For me these pods never recover.
I have been able to repro repeatedly.

The error looks like this:
```
% kubectl logs -n kubeflow envoy-79ff8d86b-z2snp envoy
[2019-01-22 00:19:44.400][1][info][main] external/envoy/source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2019-01-22 00:19:44.400][1][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/envoy/envoy-config.json': unable to read file: /etc/envoy/envoy-config.json
```

**Comment by jlewi** [comment]
I think multiple deployments is a red-hrring.

@amygdala Can you provide the logs for the iap container in the envoy pod e.g.

```
kubectl logs ${POD} yaml
```

I suspect what's happening here is that the envoy config is generated by the iap sidecar container and its not getting created because IAP is disabled.

**Comment by jlewi** [comment]
Anyone interested in looking into a short term fix?

Long term we are moving to ISTIO and basic auth for non IAP setup.

**Comment by jlewi** [comment]
@amygdala Actually the pods in question shouldn't matter if you aren't using IAP. The sole purpose of thoe pods is to validate JWTs from IAP but since you don't have IAP enabled you don't need them.

So you can just ignore them.

If you are using kfctl.sh (but I don't think you are) you could just remove the component or using kubectl

```
 kubectl delete deploy envoy
```

**Comment by jlewi** [comment]
@amygdala You could be right about multiple deployments. I suspect we have a bit of a hack in the way we disable non-iap and we end up reusing some value that could be causing this issue.

**Comment by amygdala** [comment]
Now I'm not as sure about the 'multiple deployments' diagnosis.  Today, without any pre-existing deployments in my project, I'm still always seeing the envoy pods crash-looping, and so have not been able to get an IAP deployment up and running properly-- 4 tries so far, and waiting >1hr each time to see if it corrects itself.  
(This is using the web launcher to deploy v0.4.1; I've been trying to particularly use IAP for something I'm testing).

It's the same error as before: the pod's envoy container shows:
```
[2019-02-19 00:55:56.176][1][info][main] external/envoy/source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2019-02-19 00:55:56.177][1][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/envoy/envoy-config.json': unable to read file: /etc/envoy/envoy-config.json
```
and the iap one just repeats:
```
Waiting for backend id PROJECT=aju-dev-demos NAMESPACE=kubeflow SERVICE=envoy filter=name~k8s-be-30352-...
```

**Comment by amygdala** [comment]
update: okay, I think the root cause was a 'backend services' (in this case loadbalancer) quota issue. The GCP project default is apparently 5, and each (GKE) KF deployment (through the launcher) uses 3.  So it makes sense that a second deployment into the same project would have issues and that many of us would hit this.  So in one sense this is WAI (and this issue is now mislabeled).  However, we should probably think about how to better surface the quota error so that our users aren't blocked. Or at least add it to a troubleshooting section.

(In my case, I had some 'orphaned' load balancers that were not fronting anything and appeared to be from previous KF deployments, so we should double check that deleting the deployment does clean up the backend reliably.  )
