### ISSUE TITLE
tf-serving how to add volumes/volumeMounts 

### ISSUE THREAD

**Issue by fboylu** [kubeflow/kubeflow#2319]
What is the suggested way to add new volumeMounts and volumes parameters to tf-serving deployments? I don't see these as optional parameters. Thank you.

**Comment by lluunn** [comment]
We don't support it now.
Could you describe your use case? Is it that the model is located at some local disk?

https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet#L158
In our legacy template, there is a way to a NFS volume. Will that work for you?
https://github.com/kubeflow/kubeflow/issues/2321

**Comment by fboylu** [comment]
Correct, my model is hosted on [blobfuse](https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse). any work arounds to try?

**Comment by lluunn** [comment]
For now, you can modify your ks app directly to add the volume.

There are two ways:
1. edit the prototype directly, which should be in vendor/kubeflow/tf-serving/XXX.libsonnet in the ksonnet app. This will affect all of your tf-serving component in your ks app.

2. After generating a component, your should have a jsonnet as components/XXX.jsonnet in your ks app. edit the component, using ksonnet mixin. Example: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet#L26-L57 This part is adding environment variable and volume. This won't affect other tf serving components in the ks app

**Comment by fboylu** [comment]
I am trying 1. above and modified the file. I am getting 

tf-serving-template.libsonnet:120:31-36 Unknown variable: False

                  "readOnly": False,

from the volumes I added. Any ideas what the problem would be?

**Comment by fboylu** [comment]
closed by mistake sorry, let me know if any ideas on the error. thanks.

**Comment by lluunn** [comment]
Try making it a string, "false"

**Comment by fboylu** [comment]
I got the below but then changed to ReadOnly instead of readOnly and it worked. 
ERROR handle object: creating object: creating object: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Volumes: []v1.Volume: v1.Volume.VolumeSource: FlexVolume: v1.FlexVolumeSource.ReadOnly: ReadBool: expect t or f, but found ", error found in #10 byte of ...|eadOnly":"false","se|..., bigger context ...|ttps=true","tmppath":"/tmp/blobfuse"},"readOnly":"false","secretRef":{"name":"blobfusecreds"}},"name|...

However container is taking long time to stand up, still waiting on that, will let you know.

**Comment by fboylu** [comment]
I had an issue with secrets, it worked after resolving that. thank you.
