### ISSUE TITLE
kubeflow 有没有中文社区

### ISSUE THREAD

**Issue by zyxcambridge** [kubeflow/kubeflow#2325]
kubeflow 有没有中文社区

**Comment by jlewi** [comment]
I was told this translates to something along the lines of is there a Chinese community for Kubeflow.

/cc @gaocegege @kunmingg @fxue

**Comment by gaocegege** [comment]
We recommend using English in the community.

As for this question, 我们在 Kubeflow 的 Slack 中有一个中国的 channel，除此之外，我们还有一个微信群。你可以通过 https://kubeflow.slack.com/messages/C93HYNM9C/details/ 给出的信息加入微信群。

/close

**Comment by zyxcambridge** [comment]
> We recommend using English in the community.
> 
> As for this question, 我们在 Kubeflow 的 Slack 中有一个中国的 channel，除此之外，我们还有一个微信群。你可以通过 https://kubeflow.slack.com/messages/C93HYNM9C/details/ 给出的信息加入微信群。
> 
> /close

I
  Don't have an @google.com, @caicloud.io, or @microsoft.com email address? 
Contact your Workspace Administrator for an invitation.
my gmail is  zyxcambridge@gmail.com

**Comment by richardsliu** [comment]
@zyxcambridge You can add me on wechat and I'll invite you to the group. My wechat id is richardsliu, same as my github id.

**Comment by gaocegege** [comment]
@zyxcambridge You could register via this link: https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

**Comment by goldwinner** [comment]
> @zyxcambridge You could register via this link: https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

这个链接已经失效，有更新吗？

**Comment by momomobinx** [comment]
> @zyxcambridge You could register via this link: https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

Link failure

**Comment by gaocegege** [comment]
https://kubeflow.slack.com/join/shared_invite/zt-n73pfj05-l206djXlXk5qdQKs4o1Zkg#/
