### ISSUE TITLE
CUJ: #kfonprem kubeflow on-premise journey

### ISSUE THREAD

**Issue by ddutta** [kubeflow/kubeflow#2327]
This is a central tracker for issues related to onprem kubeflow deployments.
The user journey should be defined by user type:
1. IT Operator
2. Data Engineer
3. Data Scientist

Several entities (e.g. enterprises) will need to run workloads on Kubeflow on premises. In these environments, infrastructure is typically managed by the IT teams. Thus, we need to support this persona. While there is some similarlity with the general CUJ, our aim is to capture the IT operator’s pain points explicitly and address them.

The most critical action items are centered around adding docs, examples that are on-prem specific. In addition we will identify the changes required in various modules to make the life of the IT operator easy.

This is very much a WIP and we'd love to get feedback to make the experience more wholistic for onprem.

**Comment by swiftdiaries** [comment]
Initial draft: https://docs.google.com/presentation/d/1fb6QgFNZ2B1DUUMpOKSEy1RqsJjUIv6hkrr-iq9D6i0/edit?usp=sharing

**Comment by carmine** [comment]
@ddutta - great start. I've requested edit access so that I can make suggestions, etc.
