### ISSUE TITLE
Parallelism Support Needed for Custom (Statistical) ML Models

### ISSUE THREAD

**Issue by phatlast96** [kubeflow/kubeflow#2334]
Sometimes, statistical ML models work better than Neural Networks like time-series forecasting. In those cases, parallelism is needed for preprocessing, training, and inference.

It would be great if there's support for distributed computing like [Dask](https://dask.org/) (or even support **to use** Dask within Kubeflow) without having to use Pytorch nor Tensorflow.

**Comment by aronchick** [comment]
This is a cool idea - I'd love to see someone build a Dask package/pipeline step.

**Comment by govindKAG** [comment]
This would be sweet!
