### ISSUE TITLE
Unable to download after pod starts

### ISSUE THREAD

**Issue by john-cr** [kubeflow/kubeflow#2345]
When starting a new tfjob the pod is unable to connect to the internet for the first 5-10 seconds. This means that if the job downloads data before starting to train it will fail intermittently. I'm not sure if this is an issue with kubeflow or another kubernetes component, but it took me a while to figure out when I built a simple prototype using the keras datasets

**Comment by jlewi** [comment]
This isn't an issue with TFJob or Kubeflow. Neither of these components should affect the internet connectivity of your pods.

I don't know that I've ever observed this particular failure mode. So it might be particular to your Kubernetes setup. How are you running Kubernetes?

Did you consider adding backoff and retry to your code using the retrying python package?

**Comment by john-cr** [comment]
I am running Kubernetes in minikube. Adding the retry fixed the issue but it still seems strange the internet connectivity took so long to come up

**Comment by jlewi** [comment]
@john-cr glad that worked. You might consider following up with the minikube folks if you want to pursue timing further.
