### ISSUE TITLE
Run on Kubeflow/Kubernetes button for GitHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2356]
It would be great to have a button that people could affix to GitHub repos to deploy an example on Kubeflow.

Something like what floydhub has:
https://github.com/floydhub/examples

I'm not sure anything about this would really need to be Kubeflow specific; it might be sufficient to have a button `Run on Kubernetes` that would make it easy to deploy ksonnet/helm/yaml manifests on a user's cluster.

I think we just need a webapp we could redirect to that would take the link to the manifest and then get information about the user's cluster to deploy it on. 

The click to deploy web app might be a good starting point.
https://github.com/kubeflow/kubeflow/tree/master/components/gcp-click-to-deploy

Related #2288 

/cc @hamelsmu @aronchick

**Comment by jlewi** [comment]
I wonder if someone has already created something like this for Kubernetes we could reuse?

**Comment by jlewi** [comment]
kubernetes/kubernetes#31208

IBM/Scalable-WordPress-deployment-on-Kubernetes#1

/cc @animeshsingh

**Comment by animeshsingh** [comment]
@jlewi we have definitely implemented this for IBM Cloud Kubernetes clusters, using the IBM DevOps toolchain pipeline (Jenkins under the covers). Is the idea that we redirect to a particular public cloud provider? Also  we are looking at examples in Kubeflow repository which can be pushed to Kubeflow deployments, given users give the URL and creds?
