### ISSUE TITLE
Tryout running Jupyter with TF 2.0 using stock TensorFlow images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2358]
TF 2.0 is coming soon. The nightly builds of TF should be TF 2.0.
https://hub.docker.com/r/tensorflow/tensorflow/tags

TF docker images include jupyter and start it by default. It would be great to see if we could just run these images on Kubeflow rather than having to build custom images (see also #2208).

Previously one of the reasons we had to customize the docker images was because we were using JupyterHub and we had to install JupyterHub in the images. But with the new Jupyter CR hopefully stock jupyter should just work.

It would be great to try this out and figure out where things break.

Here's a sample spec for the jupyter CR:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/test_app/components/jupyter.jsonnet

It should be straightforward to modify that to use the nightly build of TF.

**Comment by zabbasi** [comment]
@jlewi please assign this to me.

**Comment by zabbasi** [comment]
@lluunn FYI: 
Did some experiments and it turns out Jupyter CR fails to launch notebook using TF 2.0 Jupyter image. 
1- Locally tested TF 2.0 latest image using docker: 
```
 docker run -it --rm -v $(realpath ~/notebooks):/tf/notebooks -p 8888:8888 tensorflow/tensorflow:latest-py3-jupyter
 ``` 
which could successfully launch notebook. 

2- Run TF 2.0 image in kubernetes as follows which could again launch notebook successfully:
``` kubectl run tftest --image=tensorflow/tensorflow:latest-py3-jupyter
``` 
3- When the image in kubeflow, it fails to start Kernel by error: ```
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```
the is resolved by first uninstalling and then installing prompt toolkit in the container:
pip uninstall prompt-toolkit
pip install prompt-toolkit

**Comment by lluunn** [comment]
error msg same as in #1721, not sure if it's related though

**Comment by zabbasi** [comment]
Tryout was successful. 
Tested kubeflow notebook-controller to deploy a jupyter notebook using:
 1-  tensorflow nightly image (tensorflow/tensorflow:nightly-py3-jupyter)
2-  a modified version of the following  Jupyter CR spec https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/test_app/components/jupyter.jsonnet 
 where the container spec is set as follows:
```
 "spec": {
        "containers": [
          {
            "image": "tensorflow/tensorflow:nightly-py3-jupyter",
            "name": "notebook",
            args: [
              "jupyter",
              "notebook",
              "--LabApp.token=''",
              "--LabApp.allow_remote_access='True'",
              "--LabApp.allow_root='True'",
              "--LabApp.ip='*'",
              "--LabApp.base_url=/" + env.namespace + "/" + params.name + "/",
              "--port=8888",
              "--no-browser",
              "--notebook-dir=/tf",
              "--allow-root"
            ],
            env: [
              {
                name: "JUPYTER_ENABLE_LAB",
                value: "fale",
              },
            ],
...
```
As a result notebook is successfully launched. Note TF version in the above image was 1.13.0-dev20190215

@jlewi  @lluunn please close the issue if everything is good.

**Comment by jlewi** [comment]
@zabbasi Were you able to get this working without specifying all the command line arguments? Can you provide the spec for the Jupyter resource that you got working.

**Comment by zabbasi** [comment]
@jlewi  updated the comments.

**Comment by jlewi** [comment]
@zabbasi Is there any more work to do here? Are we confident TF 2.0 is working with KF 0.5?

**Comment by shkr** [comment]
I started a jupyter hub server, on kubeflow-0.5.1 on gcp, tensorflow-1.3 gpu works fine, but 2.0 returns missing libcublas error.

**Comment by zabbasi** [comment]
@shkr can you please copy here the code you tried to run on 2.0? was it Python 2 or 3? Did you just try to import tensorflow?

**Comment by shkr** [comment]
I just tried to import tensorflow

**Comment by shkr** [comment]
Currently, I have just reverted to tensorflow 1.13 gpu on kubeflow. But tensorflow 2.0 is how I want to implement new models, but it is not possible to develop it on kubeflow right now.

**Comment by zabbasi** [comment]
@shkr  Which kernel was it? (Python 2 or 3)
Will test it and come back to you.

**Comment by shkr** [comment]
python3

**Comment by zabbasi** [comment]
![image](https://user-images.githubusercontent.com/9967553/58274780-6fe66c00-7d48-11e9-8ab4-d73afd14b3fd.png)

fixed it (tag wan not pointing to the latest)

**Comment by zabbasi** [comment]
![image](https://user-images.githubusercontent.com/9967553/58274914-bb991580-7d48-11e9-9be6-cc3dac6c5459.png)
 @shkr

**Comment by jlewi** [comment]
@karthikv2k @pdmack Any interest in picking this up?

I think the goal is to figure out how we can make it easy for our users to use stock TF images with our Jupyter setup.

It looks like @zabbasi got stock TF images working see [comment](https://github.com/kubeflow/kubeflow/issues/2358#issuecomment-464170252) but had to modify some of the flags.

At a minimum, should we document that?

I guess the next option would be to add an option in the jupyter spawner UI to set args in the notebook resource as needed. It might be nice if there was a way in the UI to prepopulate the command with the appropriate args but then let the user customize it further.

/cc @kimwnasptd

**Comment by shkr** [comment]
@zabbasi Thank you! I will try out 2.0 now :-)

**Comment by jlewi** [comment]
Closing in favor of #3725
