### ISSUE TITLE
[Dashboard v1][Tracker][Redesign] Landing Page v1

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2359]
## General Idea
Create a landing page that provides all existing functionality while also starting to offer some basic help and information. This is a tracker issue. I will be adding these features!

## Features
Tentative list of features being added:
- Create a responsive and a11y enabled **sidebar**
  - Move links to a sidebar
  - Add link for Home
  - Add Kubeflow Logo
- Create a **Main View**
  - Either contains the page (**`Dashboard`** / **`Activity`**)
  - Or an Iframe view which loads all the help links!
- Contains a **_header toolbar_** (*in **Main View***)
  - Ability to swap between **Dashboard** and **Activity**

## Backend
Goals:
- Provide REST APIs to expose:
  - Namespaces
  - Build information
  - Any relevant metrics?

### Dashboard
- `paper-card` that contains action items to many of the common actions needed to be performed on the cluster
- Possibly a chart :)

**Comment by jlewi** [comment]
@avdaredevil is actually working on this and has a PR pending.

**Comment by avdaredevil** [comment]
Added some info on the backend info

**Comment by jlewi** [comment]
@avdaredevil what is the remaining work on this issue? 

* Do we need to publish a docker image for the new app? Or are you just reusing the existing central dashboard image?

* Do we need to update the ksonnet component used to deploy it
  
  * We currently use this component to deploy the central dashboard:
    https://github.com/kubeflow/kubeflow/blob/master/kubeflow/common/centraldashboard.libsonnet

* Integrate the new dashboard into the kfctl go binary
   * I think the list of packages installed by default is defined in go here:
    https://github.com/kubeflow/kubeflow/blob/32aa25460d884dc73407ca6651535366ae41bf66/bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go#L63

**Comment by jlewi** [comment]
#2540 updated the image to 
gcr.io/kubeflow-images-public/centraldashboard:v20190222-v0.4.0-rc.1-152-g1de09b7a

But it looks like that image doesn't exist

**Comment by sarahmaddox** [comment]
In iframing the docs into the UI, please see issue https://github.com/kubeflow/kubeflow/issues/2546

**Comment by jlewi** [comment]
@avdaredevil @prodonjs what is the remaining work before we can close out this issue?

**Comment by prodonjs** [comment]
We have PR #2667 which should be in place by EoD 3/12 which surfaces events from the selected namespace in the cluster. That will close #2615 and that should be the only major landing page related item left.

**Comment by avdaredevil** [comment]
Additionally I am also planning on getting the support for collapsible sidebar on iframe views #2678 by EOD 3/12

**Comment by avdaredevil** [comment]
Delayed by a day because of the Kubeflow Contributor Summit.

**Comment by jlewi** [comment]
@avdaredevil @prodonjs It looks like #2576 reverted the Docker image 
https://github.com/kubeflow/kubeflow/blob/b42734af7845087b6bd42e36d01422cb34ec8aa0/kubeflow/common/prototypes/centraldashboard.jsonnet#L6

To an older value 
gcr.io/kubeflow-images-public/centraldashboard:v20190301-v0.4.0-rc.1-183-g07eecd2f

Can we fix this?

**Comment by prodonjs** [comment]
We have two PRs that should get merged today that wrap up the dashboard
work. We can build the new container image on the latter of those and then
bump that comment. Since that's an optional parameter, what is the default
behavior when Kubeflow is being deployed? Does it build a new container
from master?

**Comment by avdaredevil** [comment]
We made it! @prodonjs! 🎉
