### ISSUE TITLE
Batching Configurations for TF serving in Kubeflow

### ISSUE THREAD

**Issue by bkungfoo** [kubeflow/kubeflow#236]
The TF serving repo has a special batching capability in it. It might be worth investigating whether we can use this capability to tune batch sizes based on latency requirements, etc. and add it into the ksonnet config files.

Batching for TF serving can be found here: https://github.com/tensorflow/serving/tree/master/tensorflow_serving/batching 

It looks like some work has been done on this as well, so it's just a matter of creating a conf file with batching parameters in it.
https://github.com/tensorflow/serving/issues/344

**Comment by bkungfoo** [comment]
I'd like to add that some of the batching parameters can be directly set at the command line (enable batching = true/false, gpu fraction, session parallelism), which should be easy to implement. Others require a batching config file.

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L331

**Comment by jlewi** [comment]
It looks like the conf file can be set via ```batching_parameters_file``` so we could create a config map for it.
