### ISSUE TITLE
Re-enable click_deploy_test

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2364]
https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml#L6

I think it's not being run:
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master

@kunmingg mentioned the cluster might need more quota.

**Comment by kunmingg** [comment]
An easy approach is to make e2e test clean up before each run, we can reuse what prober test is doing today:
https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy_app.py#L363

**Comment by lluunn** [comment]
It looks like it should be running in kubeflow-ci/kubeflow-testing cluster:
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/click_deploy_test.jsonnet#L192

@kunmingg If it's quota problem, shouldn't the test still be run, and then failed?

**Comment by kunmingg** [comment]
Let's setup a dedicated cluster for it.
Will double check periodic test config, maybe some PRs break the periodic test config

**Comment by lluunn** [comment]
<img width="720" alt="screen shot 2019-02-04 at 14 41 35" src="https://user-images.githubusercontent.com/32310205/52242318-366a1d80-288b-11e9-9102-d6c2c4e5c3e4.png">

The log shows: the container main in pod XXX is not available: Bad Request

**Comment by lluunn** [comment]
manually launched the workflow. Saw:

CreateContainerConfigError: secrets "kubeflow-oauth" not found

**Comment by lluunn** [comment]
The plan is to deploy to a new project (kubflow_ci_bootstrap or something under kubeflow.org) so that quotas/resources are easier to cleanup.

**Comment by lluunn** [comment]
Created project: kubeflow-ci-deployment

**Comment by lluunn** [comment]
<img width="652" alt="screen shot 2019-02-07 at 10 42 28" src="https://user-images.githubusercontent.com/32310205/52434809-14f47600-2ac5-11e9-978b-0fef3ac890b9.png">

Still failing:
```
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: finding go.opencensus.io v0.18.1-0.20181204023538-aab39bd6a98b
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: error loading module requirements
+ result=1
+ set -e
+ [[ 1 -eq 0 ]]
+ echo Command failed: /mnt/test-data-volume/kubeflow-periodic-master-deployapp-736-7f63/src/github.com/kubeflow/kubeflow/bootstrap
/build_image.sh /mnt/test-data-volume/kubeflow-periodic-master-deployapp-736-7f63/src/github.com/kubeflow/kubeflow/bootstrap/Docker
file gcr.io/kubeflow-ci/bootstrapper kubeflow-periodic-master-deployapp-736-7f63
Command failed: /mnt/test-data-volume/kubeflow-periodic-master-deployapp-736-7f63/src/github.com/kubeflow/kubeflow/bootstrap/build_
image.sh /mnt/test-data-volume/kubeflow-periodic-master-deployapp-736-7f63/src/github.com/kubeflow/kubeflow/bootstrap/Dockerfile gc
r.io/kubeflow-ci/bootstrapper kubeflow-periodic-master-deployapp-736-7f63
+ echo 'command didn'\''t succeed'
+ exit 1
```

The cleanup also failed:
```
+ kubectl delete namespace kubeflow-periodic-master-deployapp-736-7f63
Error from server (NotFound): namespaces "kubeflow-periodic-master-deployapp-736-7f63" not found
```

**Comment by lluunn** [comment]
Verify the error is the same when building locally. The problem is one dependency needs hg to clone

**Comment by lluunn** [comment]
<img width="1080" alt="screen shot 2019-02-07 at 15 28 24" src="https://user-images.githubusercontent.com/32310205/52449688-146fd580-2aed-11e9-8760-58a6a4cd0d02.png">

Now the error is this line:
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/ksServer.go#L1176

While it's waiting for the deployment manager, got an error `read: connection reset by peer`
@kunmingg have you seen this before?

The deployment succeeded eventually
<img width="463" alt="screen shot 2019-02-07 at 15 30 43" src="https://user-images.githubusercontent.com/32310205/52449780-5ac53480-2aed-11e9-8495-3b19ecc567d4.png">

**Comment by lluunn** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/kubeflow-periodic-master/756
it's passing now, but now shown on testgrid,
will fix in https://github.com/kubeflow/testing/issues/301
