### ISSUE TITLE
Remove --packages and --components from 'kfctl generate' (golang)

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2365]
These CLI parameters are only used internally and should not be exposed at the CLI level.

**Comment by jlewi** [comment]
How/where do they get used?

**Comment by kkasravi** [comment]
they were used to set/get components and packages in the app.yaml using viper. But they should not be exposed at the CLI level. Also viper is buggy on marshal, unmarshal of certain types of golang structs like map[string][]string or []NameValue so I've moved away from viper for marshalling/unmarshalling and now use github.com/ghodss/yaml. This is also used in a number of k8 tools.

**Comment by kkasravi** [comment]
fixed in #2294
