### ISSUE TITLE
Replace CfgFile *viper.Viper in KsApp with a struct and move to group.go in kfctl (golang)

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2368]
CfgFile *viper.Viper is used to fetch certain parameters held in app.yaml that can stored in a struct and made available within the KfApp interface via a Getter method.

**Comment by jlewi** [comment]
I don't have reason to like or not like Viper. I've never used viper which is why I was asking about it.

According to https://github.com/spf13/viper
its a `configuration solution`

so I'm fine with it if you think its preferable.

**Comment by kkasravi** [comment]
fixed in #2294
