### ISSUE TITLE
add the gcp platform to kfctl (golang)

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2370]
the gcp platform needs to do what the bash script does:
- create gcp_configs
- create k8s_specs
- create ks_app

create service account, create deployment...

**Comment by jlewi** [comment]
@kkasravi I think you're planning on picking this up?

/assign @kkasravi

**Comment by kkasravi** [comment]
@jlewi I'll pick this up if Ebi isn't able to.

**Comment by jlewi** [comment]
Reopening because #2440 is only a partial fix. There is more work to get GCP full working.

/assign @gabrielwen

**Comment by kunmingg** [comment]
@gabrielwen 
Can we close this one?

**Comment by jlewi** [comment]
Should we close this in favor of more specific issues.

We have the following issues for E2E tests.

#2610 is an E2E test for the go binary
#2343 E2E test with basic auth.
