### ISSUE TITLE
"pip install --upgrade pip" is usually a bad practice since it's known to have caused issues.

### ISSUE THREAD

**Issue by ashahba** [kubeflow/kubeflow#2375]
We should stick with a specific version of `pip` and only upgrade periodically in order to avoid unwanted breakage.

**Comment by jlewi** [comment]
@ashahba What is this in reference to? i.e where are we doing `pip install --upgrade pip`.

Can you attach a priority and labels to this issue using "/priority & /label"

/assign @ashahba

**Comment by ashahba** [comment]
@jlewi Here is one instance: https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile#L114

**Comment by ashahba** [comment]
Closing the ticket now that the fix is merged.
