### ISSUE TITLE
[Click To Deploy] Take a query argument that specifies the list of Kubeflow versions to display

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2377]
We'd like the click to deploy web app to take a query argument that can be used to control which Kubeflow versions are listed in the drop down box.

This would make it easy for us to test new versions of Kubeflow with the click to deploy app before they have rolled out.

/assign @avdaredevil

**Comment by jlewi** [comment]
@kunmingg @IronPan Is this already done? I believe this is already available in staging and we are just waiting to push it to prod?

**Comment by kunmingg** [comment]
It's been working well on staging.
Will push to prod this afternoon.

**Comment by jlewi** [comment]
@kunmingg Is this in prod? Can we mark this as fixed?

**Comment by avdaredevil** [comment]
Is there anything needed from my side @kunmingg / @jlewi?

**Comment by kunmingg** [comment]
It's alive in prod since last week, example: https://github.com/kubeflow/pipelines/releases
Close it.
