### ISSUE TITLE
I am installing kubeflow and got this error，no matches for kind "Application" in version "app.k8s.io/v1beta1"，need help

### ISSUE THREAD

**Issue by 13567436138** [kubeflow/kubeflow#2380]
INFO Applying customresourcedefinitions applications.app.k8s.io 
INFO Creating non-existent customresourcedefinitions applications.app.k8s.io 
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch753566743": no matches for kind "Application" in version "app.k8s.io/v1beta1"

**Comment by kkasravi** [comment]
You probably had a different version of this CRD installed. 

If you do a `kubectl get crds` you should get a list of CRDS. You should look for all app.k8s.io/v1beta1 CRDS. Make sure any applications.app.k8s.io are deleted.

**Comment by jlewi** [comment]
Is this a Duplicate of #1933?

@13567436138 How did you install Kubeflow? Can you provide steps to reproduce this issue? Our tests on GKE don't seem to hit this issue so I suspect the issue is specific to non-GKE installs.

**Comment by 13567436138** [comment]
I follow the instruction from install document

**Comment by 13567436138** [comment]
you should try

      ks show default -c metacontroller -c application > default.yaml
      kubectl apply --validate=false -f default.yaml
application has a dependency on metacontroller. This is what kfctl.sh is doing on master.

this solve my problem
from issues/1933
https://github.com/kubeflow/kubeflow/issues/1933

**Comment by cyrilthank** [comment]
> ks show default -c metacontroller -c application > default.yaml

on microk8s can you please share what would be the equivalent of this
requesting since i am getting 

cyril@tensorflowextended:~$ ks show default -c metacontroller -c application > default.yaml
ks: command not found
