### ISSUE TITLE
[kfctl go] Need a minimal release process

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2383]
We will need a minimal release process for the kfctl go binary.

I think we can close this issue when we have instructions for how to build and release the kfctl go binary as part of a release.

We will need this for 0.5 since we want to include kfctl.

**Comment by jlewi** [comment]
I think a minimal release process would be 

1. E2E workflow to build and test go binary
2. E2E test should copy the binary to GCS
    * Presubmits should use a bucket in kubeflow-ci
    * Postsubmits should use a public bucket (perhaps in project gcr.io/kubeflow-images-public)

**Comment by gabrielwen** [comment]
1. Seems like we have E2E test ready.
1. What is the connection between presubmit and kubeflow-ci bucket?

**Comment by jlewi** [comment]
It looks like Darwin requires its own build.

**Comment by jlewi** [comment]
We should modify the makefile to determine the architecture and set the name in the file appropriately.
This is what we do in minikube
https://github.com/kubeflow/kubeflow/blob/3fa97bc61e7b4b1eeb0062a8cbc98920e9da43d5/scripts/setup-minikube.sh#L14

But I don't see how we are inferring its OSX.
