### ISSUE TITLE
Integrate test_flake8.py into CI system

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2388]
#2247 added a test for flakes related to python3.

We should integrate this into our CI system.

To do that we could just add it to the unittests workflow.

We just need to add a step here:
https://github.com/kubeflow/kubeflow/blob/01519e72ebfc520bab037159e6afecc7b1620845/testing/workflows/components/unit_tests.jsonnet#L109

/cc @cclauss

**Comment by bikramnehra** [comment]
@jlewi you can assign this to me

**Comment by bikramnehra** [comment]
https://github.com/kubeflow/kubeflow/pull/2403 merged.

This can be closed now

**Comment by lluunn** [comment]
thanks!
