### ISSUE TITLE
[Dashboard v1] Immediate fixes for new dashboard

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2390]
Child of #2359

## Overview
Things to achieve:
- [x] Remove the reliance of RawGit CDN in PR #2361.
- [x] Clean up unused polymer properties
- [x] Merge layout and index branches in the codebase to work off of one UI
- [x] Change round menu items to match `paper-item` spec
- [x] Make build version slightly brighter (waiting on mocks from @ajayalfred)
- [x] Add the quick links section (waiting on mocks from @ajayalfred)

cc: @jlewi, @yebrahim 
/assign @avdaredevil

**Comment by avdaredevil** [comment]
PR Merged!

**Comment by abhi-g** [comment]
fixes #2093
