### ISSUE TITLE
Recommended setup for different K8s Solutions

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#240]
There are probably different best practices for configuring Kubeflow on different K8s solutions.

For example, it looks like a shared posix compliant filesystem is very useful; e.g. for making files available to Docker Builds (see https://github.com/kubeflow/example-seldon).

I think on AKS PDs can be mounted ReadWriteMany (@wbuchwalter @dynamicwebpaige true?) but on GCP PDs can't be mounted ReadWriteMany so the current solution involves NFS. 

I think the user guide should have Cloud specific instructions to explain how to best setup Kubeflow for different K8s distributions; this way each example doesn't need to do it?

Some things that we might want to explain for each Cloud

- [ ] How to access/search logs
- [ ] How to setup credentials to access Cloud services like storage
- [ ] What to use for an object store
- [ ] What to use for a shared posix compliant filesystem
- [ ] How to setup secure ingress to the cluster

others?

Lets use this issue as an uber tracking bug and create individual issues for specific clouds that can be assigned to appropriate owners.

Here's an initial list of K8s distributions (this is based solely on people already involved with Kubeflow who might be willing to pick up this issue; happy to add others.)

- [ ] AKS
- [ ] Canonical
- [ ] GKE
- [ ] Minikube
- [ ] OpenShift

/cc  @wbuchwalter @dynamicwebpaige @lachie83 @kubeflow/red-hat @sfabel

**Comment by lachie83** [comment]
@jlewi AKS managed-disk backed PDs CANNOT be mounted ReadWriteMany. AzureFile backed PDs CAN be mounted ReadWriteMany.

**Comment by inc0** [comment]
For on-prem you have few options:
1. NFS, obviously
2. Ceph - CephFS for RW, bare rados block device for RO (datasets for example) - more performance and such. There is also Rados GW as nfs backend, but I haven't tried that
3. GlusterFS - never tried that.

I'd go for Ceph tbh and allow to configure where use RW and where use RO

**Comment by jlewi** [comment]
@lachie83 Thanks.

@inc0 SGTM.

**Comment by bhack** [comment]
EFS on AWS. What do you of https://blog.riseml.com/accelerating-io-bound-deep-learning-e0e3f095fd0?

**Comment by jlewi** [comment]
Closing this issue.

We've started adding specific guides as part of our website. And I've opened up more specific bugs and we can continue to open more specific bugs as needed.
