### ISSUE TITLE
Friction log for OpenShift 3.11

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#2402]
https://docs.google.com/document/d/16sU5oM4f1yQQ0QiUOLce2RT619mrWGNZDkT4oIHK_6U/edit?usp=sharing

Living doc to enumerate and identify distinct issues/PR for Kubeflow improvements on OpenShift. Many of the workarounds are not best practices but can hopefully help developers to unblock.

**Comment by shalberd** [comment]
is this appliable for v0.5, too?
