### ISSUE TITLE
kfctl.sh delete all timeout failed to delete namespace; problems deleting minio

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2408]
The log snippet parsed below. 
There are issues such as https://github.com/kubernetes/kubernetes/issues/60807 describing the similar thing. 

It happens in pipeline prow test that when test finish and want to do full delete, it's stuck in this step 
https://github.com/kubeflow/kubeflow/blob/master/scripts/kfctl.sh#L487
The test job is killed by prow after 2h timeout. However the cluster is not deleted and cause resource leak.

A short term mitigation is to skip delete namespace in GCP platform. 

To further debug and diagnose cluster problems, use '\''kubectl cluster-info dump'\''.' '[^\.0-9]*\([\.0-9]\+\)'
+ MASTER=35.226.133.205
+ echo MASTER=35.226.133.205
MASTER=35.226.133.205
+ [[ 35.226.133.205 != \3\5\.\2\2\6\.\1\3\3\.\2\0\5 ]]
+ echo 'kubectl context matches ks environment default'
kubectl context matches ks environment default
+ set +e
+ kubectl delete ns/kubeflow
namespace "kubeflow" deleted
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   23m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   23m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   23m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   24m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   25m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   26m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   26m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   26m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   26m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   26m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   27m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   28m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   29m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   30m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   30m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   30m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   30m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   30m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   31m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   32m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   33m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   33m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   33m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   33m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   33m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   34m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   34m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   34m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10
+ kubectl get ns/kubeflow
NAME       STATUS        AGE
kubeflow   Terminating   34m
+ echo 'namespace kubeflow not yet deleted. sleeping 10 seconds...'
namespace kubeflow not yet deleted. sleeping 10 seconds...
+ sleep 10

**Comment by jlewi** [comment]
@IronPan if the namespace isn't being deleted this usually means something is blocking the delete.

My hunch is that its related to the storage options you are adding related to pipelines. Kubernetes has some options to protect storage deletion
https://kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/

**Comment by IronPan** [comment]
It might be related. The cluster uses in-cluster PD. I see a pod is stuck 
```
$ kubectl get po -n kubeflow
NAME                     READY     STATUS        RESTARTS   AGE
minio-6fb75bb849-nwl9n   0/1       Terminating   0          8h
```

And by describing the pod i got 
```
$ kubectl describe po minio-6fb75bb849-nwl9n -n kubeflow
Name:                      minio-6fb75bb849-nwl9n
Namespace:                 kubeflow
Priority:                  0
PriorityClassName:         <none>
Node:                      gke-e2e-9b40778-5477-default-pool-76d3b514-vg42/10.128.0.56
Start Time:                Tue, 05 Feb 2019 13:02:50 -0800
Labels:                    app=minio
                           app.kubernetes.io/name=e2e-9b40778-5477
                           pod-template-hash=2963166405
Annotations:               <none>
Status:                    Terminating (lasts 8h)
Termination Grace Period:  30s
IP:                        10.16.1.30
Controlled By:             ReplicaSet/minio-6fb75bb849
Containers:
  minio:
    Container ID:  docker://5aad814b05761758ab6bb89ab7be68603a29225290e688310abac347cbd72d40
    Image:         minio/minio:RELEASE.2018-02-09T22-40-05Z
    Image ID:      docker-pullable://minio/minio@sha256:9e0f80305b619edb1a02bec03201b2b0e2dceda4c8694a2819197a73076be9e0
    Port:          9000/TCP
    Host Port:     0/TCP
    Args:
      server
      /data
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      MINIO_ACCESS_KEY:  minio
      MINIO_SECRET_KEY:  minio123
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6fsxk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfs-pvc
    ReadOnly:   false
  default-token-6fsxk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6fsxk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

The PVC is, however deleted
```
$ kubectl get pvc --all-namespaces
No resources found.
```

**Comment by IronPan** [comment]
I'm not sure how it ends up in that state. Based on the storage protection link that you mentioned, the PVC should be 'terminating' before pod is deleted.

**Comment by jlewi** [comment]
Can you provide the spec of the pod?  minio-6fb75bb849-nwl9n

I think kfctl timing out if the namespace doesn't get deleted is WAI. I think we need to figure out how to properly clean up minio and pipelines.

Its possible we need to explicitly delete the corresponding deployment before deleting the PVC.

**Comment by jlewi** [comment]
@IronPan You might want to try to figure out manually the proper set of steps to ensure proper deletion; i.e. figure out which kubectl commands to issue in which order.

You might want to delete all the deployments etc... mounting the PD before trying to delete the PD. You might be hitting delete protection on the PD.
https://github.com/kubeflow/testing/blob/master/playbook.md#deleting-and-recreating-the-nfs-share

**Comment by jlewi** [comment]
obsolete; kfctl.sh is no longer used.
