### ISSUE TITLE
Heptio is discontinuing ksonnet.

### ISSUE THREAD

**Issue by bmv3cg** [kubeflow/kubeflow#2412]
Vmware  has decided to discontinue kssonet as heptio acquisition is closed. This will impact the kubeflow installation. 

https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/

We need to think about an alternate installation mechanism for kubernetes.

**Comment by pbrzostowski** [comment]
Yea, that's unexpected. Anyway, there is a new approach in Kubernetes SIGs repo. I didn't have time to play around it yet though...

https://github.com/kubernetes-sigs/kustomize

It is fairly new, but maybe will getting shape and will make a perfect fit here.

**Comment by govindKAG** [comment]
Kustomize certainly seems like the way to go. It's been getting a lot of traction. Also unlike ksonnet, kustomize only uses yaml which can't hurt either.

**Comment by kkasravi** [comment]
this link in the kubernetes slack channel suggests kubecfg + jsonnet 

https://kubernetes.slack.com/archives/C6JLE4L9X/p1549490495318200?thread_ts=1549466594.310000&cid=C6JLE4L9X

according to guslees

```
With `kubecfg`, you can just use the "natural" jsonnet `{myobj: k8s obj}` structure, which imports really nicely into other jsonnet.  When you want to compose them, you can nest them too: `{componentA: {myobj: k8s obj}, componentB: {otherobj: k8s obj}}`, and so on.
```

**Comment by tomstockton** [comment]
Is a helm chart not a viable alternative?  Excuse my ignorance if not!

**Comment by kkasravi** [comment]
we will work towards {helm, kustomize, jsonnet}. Good article that summarizes pros/cons https://blog.argoproj.io/the-state-of-kubernetes-configuration-management-d8b06c1205

**Comment by jlewi** [comment]
Here's the doc I wrote advocating for Kustomize as the default configuration manager
http://bit.ly/kf-kustomize

There's also this thread in the mailing list
https://groups.google.com/forum/#!topic/kubeflow-discuss/Zg14_Ok7XH4

**Comment by y4roslav** [comment]
>Here's the doc I wrote advocating for Kustomize as the default configuration manager ...

@jlewi is there roadmap/project to move toward it? I want to participate.

**Comment by jlewi** [comment]
With 0.6 we have moved to kustomize.
