### ISSUE TITLE
Deploy single mysql instance 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2422]
Currently both Katib and Pipeline deploys mysql instances. Ideally kubeflow should deploy a single mysql instance that shared across all components.

**Comment by IronPan** [comment]
I've seen a concrete issue that when user deploy kubeflow on a K8s cluster without setting up storageclass, user would set up the PV manually. 
Katib mysql and Pipeline mysql would have conflict on claiming the PV resource and result in unexpected behavior.

**Comment by zhenghuiwang** [comment]
@richardsliu thanks for looping me in. Could you give some links on how mysql is used in Katib?

@IronPan could you give references in Pipeline? A headsup, I'm thinking about making mysql a default storage solution for saving metadata of models, datasets etc. Spawning a single mysql instance could be the first step.

**Comment by swiftdiaries** [comment]
One way would be to move MySQL and Minio out of the individual components (Katib and Pipelines) and into the common package. 
That way we have one single instance -> single PVC -> single Volume.

**Comment by jlewi** [comment]
@IronPan Isn't this just a matter of letting users customize things how they want? Does pipelines have options to use an existing SQL instance rather than deploy its own? If it does then can't a user configure pipelines to either use its own or share an instance.

**Comment by IronPan** [comment]
@jlewi I think @swiftdiaries pointed out the ideal state for KF as a whole - Single metadata and artifact management. The user should be able to customize things, and ideally user only manage and customize one instance of mysql and one instance of artifact store.

@zhenghuiwang and @neuromage are working on merging the metadata management which would helped moving forward to a unified story.

**Comment by IronPan** [comment]
@zhenghuiwang FYI here are reference for pipeline
- schema definition https://github.com/kubeflow/pipelines/tree/master/backend/src/apiserver/model. it uses go based library GORM to initialize the DB. 
- Ksonnet entry https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pipeline/mysql.libsonnet. 

There is an on-going effort to support data persistence, upgrade, and data migration. It should be useful for the metadata store.

**Comment by naseemkullah** [comment]
Is the end user already able to configure this with `MYSQL_SERVICE_HOST` value in pipeline and `MYSQL_HOST` value in katib ?

I am working on a helm chart (https://github.com/helm/charts/pull/13454) and would like to use just one instance of mysql for kubeflow.

**Comment by naseemkullah** [comment]
Also feel we should be able to add a password for pipeline mysql:

https://github.com/kubeflow/kubeflow/issues/3248

**Comment by xaniasd** [comment]
I'd like to chime in if I may. Apart from Katib and pipelines, other components deploy a database as well, namely metadata and modeldb. So we can end up with 4 databases, all with insecure configuration. For deployment scenarios where a managed database service is available and a preferred option, this means 4 insecure database servers deployed for no reason at all. And if we stick to this pattern, future components with a database backend will make matters worse.

My suggestion would be to rework all these components to assume an existing database as *base* layer and add overlays as needed (and make the latter use secure defaults). This setup would be less opinionated and therefore supporting many more deployment scenarios. 

Happy to help further with this.

**Comment by ShrikanthSingh** [comment]
Without knowing anything about the kubeflow resources I deleted both MySQL and Minio of them to free up some bounded pvc. But this resulted in losing all the sample pipelines, runs, experiment also produces errors while submitting any runs to the kubeflow. Can anyone help me with recovering those files or should I configure a fresh pipeline to the cluster ?
