### ISSUE TITLE
tf.transform libraries in our notebooks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#244]
tf.Transform is a library for feature processing.
https://github.com/tensorflow/transform

We should add it to our Jupyter notebook images so that people can run it.

I think it requires Beam so this probably means installing the Apache Beam library as well.

**Comment by katsiapis** [comment]
Transform already specifies it's requirements https://github.com/tensorflow/transform/blob/master/setup.py#L24 (except for Tensorflow for now, so that it plays nicely with both CPU and GPU).

**Comment by kkasravi** [comment]
@jlewi i would like to pick this up. I have a good understanding of how ksonnet is used in kubeflow and know beam by way of integrating a beam runner

**Comment by jlewi** [comment]
Fantastic.

**Comment by jlewi** [comment]
@kkasravi I sent you an invite to the Kubeflow org. If you accept you should be able to trigger tests and I think I can assign the issue to you.

**Comment by kkasravi** [comment]
@jlewi done

Question: will we be replacing tf-job with argo's equivalent (but without the build steps)? Because I have most of this in place and argo is already on master.

**Comment by jlewi** [comment]
I don't understand the question. TFJob and Argo serve very different purposes in my mind. TFJob is about executing TF jobs particularly distributed jobs. Argo is about managing workflows. So the overlap isn't obvious to me.

**Comment by kkasravi** [comment]
@jlewi i was referring to the example-seldon repo which defines 4 workflows: 2 for training and 2 for serving. The TF training one uses the argo Workflow to first build and push the code and then run the TFJob (https://github.com/kubeflow/example-seldon/blob/master/workflows/training-tf-mnist-workflow.yaml#L62) unless you're thinking that both serving and training should be done using seldon's CRD.

**Comment by jlewi** [comment]
So a workflow might look as follows

1. Build a Docker image that contains the code you want + any dependencies (e.g. TF.Transform)
1. Run a preprocessing job using TF.Transform
1. Run a TFJob to train a model

TF.Transform uses Apache Beam so in step 2 we would be invoking a python program that submits the beam job and waits for it to finish. Depending on the Beam runner we are using that job will do a variety of things.
  - If we are using the Dataflow runner on GCP then the job just makes an RPC to the Dataflow service which will start and manage a bunch of Dataflow workers
  - For the non-GCP case we can run it using the DirectPipelineRunner in which case it will run non-distributed in the pod created by Argo.
  - When other Beam runners become available (e.g Flink) we can run that runner on K8s and run the job using it.

Does that answer your question?

/cc @vicaire

**Comment by kkasravi** [comment]
yes thanks. I'll get going on it.

**Comment by jlewi** [comment]
@kkasravi Any update on this? Do you have an ETA?

**Comment by jlewi** [comment]
tf.transform  & Apache Beam don't support Python 3 yet.
https://issues.apache.org/jira/browse/BEAM-1251

Our notebooks however are currently Python 2.
So we will probably need to build a Python 2 version.

**Comment by jlewi** [comment]
@kkasravi Can you let me know if you're working on this? There's some other work blocked on it and some others that might be able to pick it up.

**Comment by jlewi** [comment]
/assign @ojarjur 

after discussion with @kkasravi @ojarjur is going to pick this up.

@ojarjur new Jupyter images are available at 
gcr.io/kubeflow-images-staging/tensorflow-notebook-cpu:v20180301-pr317

**Comment by jlewi** [comment]
@ojarjur  I rebuilt the image and this one appears to work
gcr.io/kubeflow-images-staging/tensorflow-notebook-cpu:v20180301-1838-pr317-1932b26-f88d"

And I can launch Python2 kernels
