### ISSUE TITLE
Fork homebrew-core under kubeflow for kfctl 

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2444]
Distributing kfctl will be done using `brew`. We will distribute the binary and plugins.
This requires that we fork [homebrew-core](https://github.com/Homebrew/homebrew-core) under kubeflow as described [here](https://docs.brew.sh/Formula-Cookbook#push).
Only owners of kubeflow can fork into kubeflow - thus this request.

**Comment by jlewi** [comment]
Is it not possible to just publish a go binary that users download like we do for linux? What's the advantage of using brew?

I assume that's something akin to apt.

**Comment by kkasravi** [comment]
it's probably mac's most popular package manager and also works on linux. 
Doing a `brew list` on my mac shows what brew has installed

```
$ ☞  brew list
argo		fish		jemalloc	kubeval		mercurial	pipenv		torsocks
bash		gdbm		jq		libffi		msgpack		python		unibilium
bash-completion	gettext		jsonnet		libidn2		neovim		python3		vim
bats-core	git		kops		libtermkey	node		python@2	wget
bazel		git-crypt	ks		libunistring	oniguruma	readline	xz
cmake		glib		kubecfg		libuv		openssl		ruby		yarn
coreutils	glide		kubectx		libvterm	parallel	socat
dep		gnu-sed		kubeless	libyaml		pcre		sqlite
faas-cli	go		kubernetes-cli	lua		pcre2		sshfs
findutils	icu4c		kubernetes-helm	luajit		perl		telepresence
```

It also takes care of upgrades, reinstallation of earlier versions, cleanup, etc.
There are other mac package installers like ports for for CLI tool installation it's the way to go

**Comment by jlewi** [comment]
Ok I forked it.
Can you please set up the repo?
https://github.com/kubeflow/homebrew-cask

E.g add OWNERs files and update the README please?

**Comment by kkasravi** [comment]
yep, will do.

**Comment by jlewi** [comment]
I gave the ci-bots access. To that repo.

I also made you and @ashahba admins.

**Comment by kkasravi** [comment]
thanks @jlewi - As I dig more into homebrew-cask, I've realized that we just need homebrew-core. 
Homebrew has a variety of separate repos/frameworks to install different kinds of commands.

- homebrew-cask is for native mac os applications - eg applications that are installed under mac's /Applications folder and also present a GUI. 
- brew is for CLI apps like kubectl, git, vim, bash, jq, jsonnet, ks, ... it is also much easier to setup. According to the [documentation](https://docs.brew.sh/Formula-Cookbook#push) we fork the homebrew-core repo and push a PR. 

My bad for not doing more due diligence on this. This is what kustomize [submitted](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kustomize.rb) to install the kustomize CLI. Ours will look similar. 

Could I ask you to fork [homebrew-core](https://github.com/Homebrew/homebrew-core) and delete [homebrew-cask](https://github.com/Homebrew/homebrew-cask)? I've updated the description for this issue to reflect what we need to do. Sorry for having you fork the wrong repo.

**Comment by jlewi** [comment]
Done.

**Comment by kkasravi** [comment]
yay!

**Comment by jlewi** [comment]
@kkasravi Is there more work to be done on this issue? Are we going to be using home-brew with 0.5 or should we push this to 0.6?

**Comment by rbq** [comment]
I wanted to try out Kubeflow 0.5 and therefore created a formula. Pull request to Homebrew is linked in the earlier issue #2413. Would you like me to create a pull request for kubeflow/homebrew-core, too?

**Comment by kkasravi** [comment]
@rbq thank you! Yes please submit a PR to home-core
@jlewi I think both 0.5.X and 0.6

**Comment by rbq** [comment]
For kfctl to be accepted into the main Homebrew repository [it must be possible for users to build it](https://github.com/Homebrew/homebrew-core/pull/39588#discussion_r284646505). This issue should be revisited once the source code becomes available.

**Comment by SMillerDev** [comment]
Just found this issue through the homebrew-core proposal. If you want to distribute something to homebrew without it passing the requirements for core a tap could be useful: https://docs.brew.sh/Taps

**Comment by jlewi** [comment]
@rbq Do you meant he source for kfctl? Because the source for kfctl is available. It lives here
https://github.com/kubeflow/kubeflow/tree/master/bootstrap

For a various legacy reason we haven't moved it into master/kfctl yet

**Comment by rbq** [comment]
I tried to create [a tap (macOS binary only)](https://github.com/rbq/homebrew-kubeflow), this seems to work:

```sh
brew install rbq/homebrew-kubeflow/kfctl
```
