### ISSUE TITLE
Add kustomize support to kfctl

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2445]
Doc:
http://bit.ly/2RwMP8q

The immediate need is kfctl(go) needs to support installing ISTIO see #2052.
We currently install ISTIO using its YAML manifest. 
We could either add support to kfctl for installing YAML or we could just 

1. Add support for kustomize
1. Turn YAML manifests into kustomize packages by adding kustomize files 

To add support for kustomize we need to implement the KfApp interface for kustomize
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/cmd/kfctl#kfapp-interface

See also #2351

**Comment by lluunn** [comment]
cc

**Comment by jlewi** [comment]
@kkasravi I know you've been working on this. Any update on what the remaining blockers are?

**Comment by kkasravi** [comment]
@jlewi 

> @kkasravi I know you've been working on this. Any update on what the remaining blockers are?

- Delete isn't implemented but I will leverage labels that kustomize applies.
- A few remaining .jsonnet conversions for GCP (see below)
  - basic-auth-ingress.jsonnet
  - metric-collector.jsonnet
  - prometheus.jsonnet

deploy to GCP works using the following
```
kfctl init ~/kubeflow --skip-init-gcp-project --platform gcp --project constant-cubist-173123 --package-manager kustomize@pull/13
cd ~/kubeflow
kfctl generate all
kfctl apply all
```

I'll update the complete list here as well as the breakdown between @swiftdiaries  and myself.
We can put priorities on the remaining ones if you would like.
