### ISSUE TITLE
Single CRD for third party viewers - Tensorboard, Notebook etc

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2452]
We should have a single CRD for third party viewers such as tensorboard and notebook. 

This ensure we have parity horizontal features for all viewer - versioning, access control, TTL, etc. 

The existing [viewer CRD](https://github.com/kubeflow/kubeflow/pull/2416/files) might be a good place to start with. But it might need to move to kubeflow core repo instead for better share-ability. 

Also some suggestions from @lluunn:
"I think we should use kubebuilder, it's the new controller tool supported by google. Also it generates kustomize manifest (we are moving to kustomize)"

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller
this one is already using Kubebuilder

cc @kkasravi @jlewi

**Comment by jlewi** [comment]
From @neuromage 

> Under the hood, kubebuilder uses controller-runtime libraries, which is what the viewer CRD is built on as well.
