### ISSUE TITLE
Change jupyter images to work with the new jupyter CR

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2458]
See discussion in #2456

We are waiting on a resolution to #2456 but some things to consider

1. Per discussion in #2456 we may want to encode an entrypoint and args in the Dockerfile so they don't need to be specified in the Jupyter CR

/cc @zabbasi

**Comment by ioandr** [comment]
Any update on this?

**Comment by zabbasi** [comment]
addressed in the following PRs:
https://github.com/kubeflow/kubeflow/pull/2611
https://github.com/kubeflow/kubeflow/pull/2606
https://github.com/kubeflow/kubeflow/pull/2591
https://github.com/kubeflow/kubeflow/pull/2517
