### ISSUE TITLE
Execute kfctl-delete-storage even when kfctl-delete failed

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2465]
Currently if "kfctl-delete" failed, "kfctl-delete-storage" will be skipped and cause disk resource leak.
Would be nice to execute "kfctl-delete-storage" even when kfctl-delete failed.
Example:
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kfctl-beta-2447-0c1503a-5646-99fc?tab=workflow

Follow up of https://github.com/kubeflow/kubeflow/issues/2401

**Comment by kunmingg** [comment]
One more storage leak need fix is:
add delete storage option in https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/delete_deployment.sh

**Comment by jlewi** [comment]
@kunmingg should we rely on the cron job cleanup-ci to delete leaked resources?
