### ISSUE TITLE
Provide a list of required docs for the documentation card on the new landing page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#2468]
Child of https://github.com/kubeflow/kubeflow/issues/2359

The new landing page (bit.ly/kf-landing-page-cuj) includes a card listing important docs.

We need:

a) A list of the important docs to include.

b) A short URL for each doc in the list, so that we can add redirects in the Kubeflow docs. The redirects will give us a shorter URL that's easier to read, and will also protect us against changes in the doc set - when we remove/merge/add a doc, we can just adjust the URL.

For example, the actual URL for the getting-started guide is:
https://www.kubeflow.org/docs/started/getting-started
We can provide a short link like this:
https://www.kubeflow.org/info/get-started

**Comment by sarahmaddox** [comment]
/cc @avdaredevil 
/assign @ajayalfred 

@ajayalfred I just had a chat with AP about the latest dashboard design. Do you still want a "documentation" card on the dashboard? If not, do you want any doc links in the "get started" card? I recommend having at least a link to the getting-started guide somewhere.

**Comment by ajayalfred** [comment]
We won't have a documentation card, but we would like to include doc links in the "Getting started" card. Please do suggest links for this card because at the moment we haven't identified any content.

**Comment by abhi-g** [comment]
Please see the list of links on the Getting Started Section of the website. I think they are good candidates to add:  https://www.kubeflow.org/docs/started/

**Comment by abhi-g** [comment]
Also, see https://www.kubeflow.org/docs/examples/resources/
