### ISSUE TITLE
kfctl: support deploy with basic auth

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2472]
User should be able to deploy cluster with go binary while provide username/password to later access their kubeflow service

**Comment by jlewi** [comment]
@kunmingg @gabrielwen who is planning on working on this?

**Comment by gabrielwen** [comment]
@kunmingg added both of configs for me and I'm gonna use them on go kfctl.

**Comment by kunmingg** [comment]
Config entry used by ktctl:
https://github.com/kubeflow/kubeflow/pull/2482
