### ISSUE TITLE
Cloud NFS PVC needs to specify volumeName with k8s 1.11

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2475]
Here's a PV and PVC spec for Cloud NFS.
https://github.com/jlewi/community/blob/6448276eb77ea06f971dbec470565b0b3088c349/devstats/k8s_manifests/nfs_pvc.yaml

This was based on our ksonnet prototype 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/google-cloud-filestore-pv.libsonnet

On K8s 1.10 and kubeflow-testing this pattern appears to work.

But on K8s 1.11 the PVC was giving me the error

```
storageclass.storage.k8s.io "nfs-storage" not found
```

I fixed this by modifying the PVC to use the field `storageClassName` (instead of the annotation) and setting the field `volumeName`.

Here's the fixed manifest.
https://github.com/jlewi/community/blob/ed9b1673febd88e31d4baf76c6053a303d4eeed0/devstats/k8s_manifests/nfs_pvc.yaml

I think we will need to update our ksonnet prototype to make the same changes.

**Comment by zabbasi** [comment]
#2710

**Comment by jlewi** [comment]
#2710 didn't fix the issue. We need to set storageClassName on the volume as well.
We will need to cherry pick the fix onto the v0.5-branch.

**Comment by jlewi** [comment]
Fixed by #3268
