### ISSUE TITLE
Stop deploying JupyterHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2498]
The new webapp for jupyter is now being deployed on master.

So we can go ahead and remove JupyterHub and delete all the related ksonnet packages and code.

**Comment by khoward** [comment]
with jupyterhub going away, where are filestore disks defined? in the notebooks component?

**Comment by jlewi** [comment]
@khoward The Jupyter web app allows you to attach PVs and PVCs to your pods.

**Comment by jlewi** [comment]
This is fixed by #2798.
The config files no longer specify the JupyterHub component
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_iap.yaml
