### ISSUE TITLE
kfctl installs istio

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2507]
We have done it for click-to-deploy app, should extend to kfctl.

cc @kunmingg

**Comment by jlewi** [comment]
@lluunn Is this work currently blocked?

**Comment by lluunn** [comment]
yeah, waiting for Kam's fixes.

**Comment by kunmingg** [comment]
@lluunn 
Any update?

**Comment by jlewi** [comment]
@lluunn After #2755 what is the remaining work?

**Comment by lluunn** [comment]
need testing to make sure it works

**Comment by lluunn** [comment]
tested locally. With #2839, the endpoint is up and I can see the dashboard.

**Comment by jlewi** [comment]
@lluunn Can we close this issue? Do we have an issue for adding an E2E test for Kubeflow using ISTIO?

**Comment by lluunn** [comment]
filed #2891 for e2e test
