### ISSUE TITLE
kubeflow presubmit random test failure with "Unexpected error when reading response body" error.

### ISSUE THREAD

**Issue by ashahba** [kubeflow/kubeflow#2509]
Here is one instance:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2447/kubeflow-presubmit/5788/

It's possible that we are running into this issue:
https://github.com/kubernetes/kubernetes/issues/61551

**Comment by jlewi** [comment]
@ashahba Can you identify which step in the test is issuing the request and having problems?
