### ISSUE TITLE
Batch Prediction using GPUs with local runner

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#251]
Using GPUs for batch prediction could be really valuable.

There's a couple of different ways we could support this.

1. If we use a framework like Spark or Flink running on a K8s cluster with GPU nodes then the workers should be able to directly use the GPUs.

2. If we run Spark/Flink/Dataflow external to K8s such that the workers don't have direct access to GPUs then we could deploy TFServing on a K8s cluster with GPUs and then the workers could send batches of requests to the model to do inference.

**Comment by jlewi** [comment]
Some things to investigate

- TFServing currently doesn't support multi GPUs but you can potentially work around this by running 1 container per GPU.

- NVIDIA has [TensorRT](https://developer.nvidia.com/tensorrt) to optimize nets for GPUs
  - But this only supports a subset of TF graphs.

- NVIDIA has [GRE](https://developer.nvidia.com/gre)

**Comment by ankushagarwal** [comment]
With the new [integration](https://developers.googleblog.com/2018/03/tensorrt-integration-with-tensorflow.html) between TensorRT and TensorFlow 1.7, TensorRT optimizes compatible sub-graphs and let's TensorFlow execute the rest.

**Comment by jlewi** [comment]
@yixinshi How's this going?

**Comment by yixinshi** [comment]
I think I will start with a container image of Tf-serving as the base image for batch prediction. Then optimize it to use TensorFlow RT and/or GRE.

**Comment by jlewi** [comment]
P1 because we'd like to have this in our 0.2 release. However, we will probably only support local beam runner for GPUs in 0.2.

**Comment by jlewi** [comment]
@yixinshi What is the likelihood this will make 0.2?

**Comment by bhack** [comment]
Is tensorflow serving compilable with TensorRT? https://github.com/tensorflow/serving/issues/864

**Comment by jlewi** [comment]
@yixinshi Can we close this issue? I think batch prediction with GPUs and local runner is working now?
