### ISSUE TITLE
Some kubeflow presubmit tests hang indefinitely.

### ISSUE THREAD

**Issue by ashahba** [kubeflow/kubeflow#2510]
Currently this build have been running for over a week:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2447/kubeflow-presubmit/5591/
and I have no idea what's caused the hang and when it's going to release the resources.

**Comment by jlewi** [comment]
@ashahba Have you looked at the readme in kubeflow/testing for info on how to debug test failures to try to nail down where the problem is happening?
