### ISSUE TITLE
openshift 3.11 routes ok, but stylesheets and fonts from Web

### ISSUE THREAD

**Issue by shalberd** [kubeflow/kubeflow#2524]
I was able to install Kubeflow on OKD 3.11 on a node with Web Access.

When I access ambassador and centraldashboard from another Windows client in another network that has access to the OKD node via firewall rules, but has no Web Access, I get messages in the browser status bar
regarding TLS handshakes with maxcdn.bootstrapcdn.com
fonts.googleapis etc.

Is it possible to run and access Kubeflow on a computer with no Web access? Why the dependency to googleapis, bootstrapcdn, why no internal fonts and css and javascript?

**Comment by jlewi** [comment]
@avdaredevil WDYT?

**Comment by avdaredevil** [comment]
I'll make sure to internalize font's later
