### ISSUE TITLE
the tf-operator pod state has been CrashLoopBackOff, the _logs_ is "python: can't open file '/home/mnist-with-summary/[image]mnist-with-summaries.py': [ Errno 2] No such file or directory",

### ISSUE THREAD

**Issue by Chris-Paul-Li** [kubeflow/kubeflow#2529]
The trouble to ask, the tf-operator pod state has been CrashLoopBackOff, the result of the _logs_ is "python: can't open file '/home/mnist-with-summary/[image]mnist-with-summaries.py': [ Errno 2] No such file or directory", the file and path name are definitely no problem, and they are placed in the shared directory of nfs. _describe_ the results of this pod as shown below, what are you willing to do? Is it because the docker container is not started? ? ?

`kubectl -n kubeflow describe pod tfjob-pod`
**Events:
  Type     Reason                 Age               From                                 Message
  ----     ------                 ----              ----                                 -------
  Normal   Scheduled              48s               default-scheduler                    Successfully assigned mnist-master-0 to k8s-node-vm8o4o-ev15h9pjqd
  Normal   SuccessfulMountVolume  47s               kubelet, k8s-node-vm8o4o-ev15h9pjqd  MountVolume.SetUp succeeded for volume "default-token-pt7pz"
  Normal   SuccessfulMountVolume  47s               kubelet, k8s-node-vm8o4o-ev15h9pjqd  MountVolume.SetUp succeeded for volume "tfevent-volume"
  Normal   Pulled                 4s (x4 over 47s)  kubelet, k8s-node-vm8o4o-ev15h9pjqd  Container image "registry.aliyuncs.com/kubeflow-images-public/tensorflow-1.12.0-notebook-cpu:v0.4.0" already present on machine
  Normal   Created                4s (x4 over 47s)  kubelet, k8s-node-vm8o4o-ev15h9pjqd  Created container
  Normal   Started                4s (x4 over 47s)  kubelet, k8s-node-vm8o4o-ev15h9pjqd  Started container
  Warning  BackOff                3s (x5 over 45s)  kubelet, k8s-node-vm8o4o-ev15h9pjqd  Back-off restarting failed container
  Warning  FailedSync             3s (x5 over 45s)  kubelet, k8s-node-vm8o4o-ev15h9pjqd  Error syncing pod
**

**Comment by jlewi** [comment]
Can you please provide the full spec for your TFJob?

It looks like the problem is you have configured your job to run the program `/home/mnist-with-summary/[image]mnist-with-summaries.py` but this code is not in your docker image.

It looks like you are using one of the published Jupyter notebook images `registry.aliyuncs.com/kubeflow-images-public/tensorflow-1.12.0-notebook-cpu:v0.4.0`.

What is it you are trying to do and what are the steps you are following?
