### ISSUE TITLE
kfctl (golang) Remove hard dependency on GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2535]
Won't google.DefaultClient automatically use GOOGLE_APPLICATION_CRENDETIALS if its defined?

Will users need to download a service account and set GOOGLE_APPLICATION_CREDENTIALS?

The desired behavior is that it automatically uses the credentials cached in the home directory created by gcloud. If a user sets GOOGLE_APPLICATION_CREDENTIALS then those should be used.

My expectation is that the go client libraries will automatically try a variety of methods (including the 2 I listed above) to get credentials. So our code

**Comment by jlewi** [comment]
We create a DefaultClient here
https://github.com/kubeflow/kubeflow/blob/6fa88b7cf38430d17e35f968abbe0ea9d2272475/bootstrap/pkg/client/gcp/gcp.go#L275

Which should be reading the credentials from the gcloud .config file if GOOGLE_APPLICATION_CREDENTIALS isn't set.

That didn't seem to be the case when I tried basic auth and the release demo:
http://bit.ly/05_mid_release_demo

I'll debug further.

**Comment by jlewi** [comment]
I suspect this might be a question of needing to run

```
 gcloud auth application-default login
```

Looking at the GCP Go client code it looks like it checks the file

```
.config/gcloud/application_default_credentials.json
```

**Comment by gabrielwen** [comment]
I think the root cause is not just `DefaultClient` but [DefaultTokenSource](https://github.com/golang/oauth2/blob/HEAD/google/default.go#L43), which we also use in other places.  Let me do some testing and see if we could remove `DefaultTokenSource`.

**Comment by gabrielwen** [comment]
So it seems we have several options:
### Without `gcloud` as dependency
- We download service account credential file as set with `GOOGLE_APPLICATION_CREDENTIALS`.
- We download user oauth secrets and supply as input to application: [doc](https://cloud.google.com/docs/authentication/end-user)
### With `gcloud` as dependency
- User needs to run `gcloud auth login` and `gcloud auth application-default login` to have `application_default_credentials.json`.

In any case it doesn't seem to have a proper way of avoiding manual process.  Discussed with @kunmingg , we think it is ok to make `gcloud` as required when platform is `gcp`.  And just like `kubectl`, `gcloud` will be the central control to auth related operations.

In this case, I don't think we need to change our codes as both `DefaultClient` and `DefaultTokenSource` will run 3-ways credentials: `GOOGLE_APPLICATION_CREDENTIALS` -> `application_default_credentials.json` -> `default (?)`.

@jlewi , @kkasravi : what do you folks think?

**Comment by jlewi** [comment]
@gabrielwen That seems good to me.  What is the error message a user sees if they don't run `gcloud auth login` and/or `gcloud auth application-default login`?

Can we detect if a user doesn't have a credential and provide an error message that mentions the different approaches they can use?

**Comment by jlewi** [comment]
I confirmed by running the E2E test locally #2705 that we don't need to set `GOOGLE_APPLICATION_CREDENTIALS`.

If we need to improve the log message we can open up  a new issue.
