### ISSUE TITLE
install-kubeflow.sh fails with error  "merging object with existing state: unable to recognize ..."

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#2545]
_From @sachin-ac on February 16, 2019 0:20_

When following the quick start, I am having issues with the following step
**kubeflow-tools/install-kubeflow.sh**

Seeing below error:

INFO Applying customresourcedefinitions applications.app.k8s.io
INFO Creating non-existent customresourcedefinitions applications.app.k8s.io
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch883366293": no matches for kind "Application" in version "app.k8s.io/v1beta1"

_Copied from original issue: kubeflow/website#487_

**Comment by JasonLee925** [comment]
https://github.com/kubeflow/kubeflow/issues/1933#issuecomment-455058113

i done this and the problem solved.
