### ISSUE TITLE
Don't iframe the docs into the new Kubeflow UI

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#2546]
Referring to PR https://github.com/kubeflow/kubeflow/pull/2361

Hallo @avdaredevil and @abhi-g I'd like to discuss the question of iframing the docs into the Kubeflow UI. I'd prefer not to iframe the doc site into the UI, as I think the experience is on the whole confusing and aesthetically unappealing. The doc website is designed as a standalone site. When iframed into the Kubeflow UI, we have double (and slightly different) branding and doubled/trebled navigation elements.

It may make sense for the Kubeflow webapps all to be iframed into the UI (I don't want to discuss that issue) but I think it makes a better experience for the docs to be left as a separate website, with links going from the various UI elements to the relevant doc page for contextual help.

People are used to having a separate doc site. If the docs are integrated, we need a fully contextual doc config which pops up exactly the right content at each phase of the UI.

**Comment by abhi-g** [comment]
I agree that making docs site open in a separate tab is more desirable
experience for the users. AP, please let us know if we need any further
input from UX on this.

Abhishek

**Comment by avdaredevil** [comment]
The sidebar in the dashboard will hide eventually when navigating to the external links, however, we don't want the user experience to change drastically if people are already used to working in a different way. I have no strong opinion either way. I'll make the change on Monday unless @ajayalfred has something to add.

Thanks @sarahmaddox

**Comment by abhi-g** [comment]
Thanks AP.

Abhishek

**Comment by ajayalfred** [comment]
I agree with Sarah's suggestion. Traditionally (looking at other product examples) help docs is an external site in a new tab. I think it's safe to follow the same convention and not iframe docs.

**Comment by avdaredevil** [comment]
/assign @prodonjs 
Jason's change will include this update.

**Comment by prodonjs** [comment]
@avdaredevil Is this issue resolved? We still load the **Kubeflow Docs** link from the sidenav inside the iframe, but if a user clicks the **Open docs** link from the main landing page it goes to a new tab. I don't think we've addressed that behavior in any previous change so let me know if it needs to be addressed.

**Comment by avdaredevil** [comment]
Since we have completed the sidebar change, this issue is not up in the air, as there are no confusing UI experiences or duplicated sidebars, though I'll defer to @ajayalfred to make that decision.

**Comment by ajayalfred** [comment]
We agreed (on a different git issue) to not iframe KF docs, but to link out to the page.

**Comment by prodonjs** [comment]
While we're at it, does it make sense to rename the sidebar link to "Documentation" or something to that effect? It seems redundant to have the Kubeflow logo and then say "Kubeflow docs" as a link.

**Comment by ajayalfred** [comment]
"Documentation" sounds good to me. Good suggestion.
