### ISSUE TITLE
IAP component should use cert-manager to get a signed certificate

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#255]
Currently the dev.kubeflow.org app uses a self-signed certificate for https. 

We can use https://github.com/jetstack/cert-manager to provision a valid certificate.

**Comment by jlewi** [comment]
There's an example of using the predecessor kube-lego in kubeflow/reporting (but not with IAP).

I think IAP creates some challenges because we need a way to not have IAP reject the well known ACME challenge.

**Comment by ankushagarwal** [comment]
Reading up on the [ACME challenge](https://letsencrypt.org/how-it-works/)

```
For example, the CA might give the agent a choice of either:

1 Provisioning a DNS record under example.com, or
2 Provisioning an HTTP resource under a well-known URI on https://example.com/
```

If we go with #1, IAP should not be involved at all

**Comment by jlewi** [comment]
@danisla pointed out that doing #2 is fairly straightforward.

We just create a separate ingress using the same IP and hostname to serve the ACME challenge. This will use the same loadbalancer but create a different GCP backend service. IAP is enabled per backend service. So we simply don't enable IAP on this backend service.

**Comment by jlewi** [comment]
Here's a ksonnet component for using kube-lego
https://github.com/kubeflow/reporting/blob/master/collector-app/components/kube_lego.libsonnet

We can probably start with that but we should upgrade to cert-manager.
