### ISSUE TITLE
IAP enabler issue: same NodePort port number

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2550]
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/setup_backend.sh#L30

I ran into a situation that there are two backend services with the same port number.
BACKEND_ID=7586477182690125543 9050688055668560594

And then this [line](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/setup_backend.sh#L56) 
failed because the second number is not a command
```
/var/shared/healthz.env: line 2: 9050688055668560594: command not found
```

cc @jlewi 

Wondering if there is a more robust way to determine the backendID

**Comment by jlewi** [comment]
I think the backend id is specified in the annotations on the ingress.

**Comment by lluunn** [comment]
hit this again.

**Comment by jlewi** [comment]
@lluunn Will ISTIO fix this issue? i.e when we switch to ISTIO do we still need to run configure_envoy_for_iap.sh (see #2587) which is the script that is having problems detecting the correct backend?

**Comment by lluunn** [comment]
We still need to run https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/setup_backend.sh#L47
to get the backend ID for jwt validation.
So switching to Istio will not fix this.

**Comment by gabrielwen** [comment]
this deployment crashes because of it: [link](https://pantheon.corp.google.com/kubernetes/pod/us-east1-b/kf-v0-5-n00/kubeflow/envoy-69bf97959c-f5dd8?project=kubeflow-ci-deployment&container_summary_list_tablesize=10&tab=details&duration=PT1H&service_list_datatablesize=20)

**Comment by gabrielwen** [comment]
@lluunn 
there are no backend service IDs in annotations, but we do have their names in annotations.  maybe a better approach is to extract backend name from annotations and use it for `gcloud backend-services list`.

See example:
```bash
NODE_PORT=$(kubectl --namespace=${NAMESPACE} get svc ${SERVICE} -o jsonpath='{.spec.ports[0].nodePort}')
echo node port is $NODE_PORT

BACKENDS=$(kubectl --namespace=${NAMESPACE} get ingress ${SERVICE}-ingress -o jsonpath='{.metadata.annotations.ingress\.kubernetes\.io/backends}')
echo backends are $BACKENDS

BACKEND_NAME=$(echo $BACKENDS | grep -o "k8s-be-${NODE_PORT}--[0-9a-z]\+")
echo backend name is $BACKEND_NAME

BACKEND_ID=$(gcloud compute --project=${PROJECT} backend-services list --filter=${BACKEND_NAME} --format='value(id)')
echo backend ID is $BACKEND_ID
```
