### ISSUE TITLE
Update TFDV and TFMA versions in Jupyter images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2551]
There are specific versions of the TFMA and TFDV libraries that should be installed in our jupyter images based on the TF version.

TFMA versions are listed here:
https://github.com/tensorflow/model-analysis#compatible-versions

TFDV versions are listed here
https://github.com/tensorflow/data-validation#compatible-versions

For TF 1.10 we are installing the correct  versions
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/versions/1.10.1/version-config.json

For TF 1.11 and TF 1.12 we are not installing TFMA and TFDV (probably because the TFDV and TFMA packages were released after we first cut the image).
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/versions/1.11.0/version-config.json

We should update these files to include the corresponding TFDV and TFMA.

**Comment by jlewi** [comment]
Looks like we should also start building a TF 1.13 image.

**Comment by zabbasi** [comment]
> Looks like we should also start building a TF 1.13 image.

Could not find 1.13 whl url.

**Comment by zabbasi** [comment]
addressed in [this pr](https://github.com/kubeflow/kubeflow/pull/2666)

**Comment by zabbasi** [comment]
> Looks like we should also start building a TF 1.13 image.

#2730
