### ISSUE TITLE
http://testing-argo.kubeflow.org/workflows doesn't load

### ISSUE THREAD

**Issue by ryan-williams** [kubeflow/kubeflow#2554]
Clicking the link in the README, I'm not sure if I need to authenticate or something, but after a minute or so of a loading animation, I see:

![](https://cl.ly/2964e886943e/Screen%20Shot%202019-02-25%20at%2011.12.06%20PM.png)

**Comment by jlewi** [comment]
This should be fixed but its a known issue. The K8s master doesn't support pagination so when there are too many workflows the UI becomes unresponsive.
