### ISSUE TITLE
Create a new repo for kustomize packages

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2559]
Packages in the repo will be downloaded as part of kustomize build.

**Comment by jlewi** [comment]
I think we decided to call it `manifests` for now. Although I guess we could rename/move it later.

**Comment by jlewi** [comment]
New repo setup.
https://github.com/kubeflow/community/blob/master/repository-setup.md

**Comment by jlewi** [comment]
Repo is setup with the exception of setting up prow.
