### ISSUE TITLE
[Dashboard v1] Getting started card on has no content

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2562]
## About
Getting Started Card | Problem
--- | ---
![image](https://user-images.githubusercontent.com/5303018/53456555-be9f9680-39e3-11e9-8a6b-17e6d8ff0ea0.png) | There is no content available for these, and currently this card is hidden. Any relevant content would help, since this card will otherwise never show and be tested.

_**Note:** I see this card being used for navigation and actions done within the dashboard or view. Is this a correct assumption_

/assign @sarahmaddox 
/assign @abhi-g 
/assign @ajayalfred 
/assign @avdaredevil 

/cc @jlewi

**Comment by sarahmaddox** [comment]
See also https://github.com/kubeflow/kubeflow/issues/2468

It seems useful to me to add getting-started links to the card.

/unassign

**Comment by jlewi** [comment]
Lets get the central dasbhoard working and then come back to this.

We might need to punt this until 0.6.

**Comment by ajayalfred** [comment]
@abhi-g sent me some documentation links that can go in the card. I'll mockup what that looks like and send it to you AP. Sorry it's taken a little longer than expected.

**Comment by avdaredevil** [comment]
@ajayalfred I'll implement this as soon as you update this issue. Thanks!

**Comment by ajayalfred** [comment]
![image](https://user-images.githubusercontent.com/2425179/53906676-64fd2480-4000-11e9-896d-0b55255b3d44.png)

**Comment by ajayalfred** [comment]
How does this card content look?

**Comment by abhi-g** [comment]
Thanks Ajay. This looks good. 

Once we make progress on our 0.5 release and Fairing has got some example notebooks for data scientists, we can think about creating another section for Getting Started for Data Scientists.

**Comment by avdaredevil** [comment]
If either @abhi-g or @ajayalfred could also send me the intended behavior for all the other quick shortcuts, that would help me add more items to the current list (2 items)

**Comment by ajayalfred** [comment]
What clarification do you need for the intended behavior? The idea with quick shortcuts is to jump to the respective page in the respective product directly from the dashboard. If the product is iFramed then it's open in the same tab, if not it's opened in a new tab.

Anything missing?

**Comment by avdaredevil** [comment]
I'm talking about the target addresses for _Quick Shortcuts_ not _Getting Started_. I do not know where they should land
