### ISSUE TITLE
kfctl: populate the manifests repo with converted kustomize packages that have been converted from ksonnet

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2566]
begin with Jupyter, Profiles

**Comment by jlewi** [comment]
@swiftdiaries @kkasravi How's this issue coming? What packages remain? Should we close it out in favor of more specific issues?

**Comment by jlewi** [comment]
@swiftdiaries @kkasravi ping?

**Comment by hougangliu** [comment]
@jlewi nearly all packages done! since we need support [multiple overlays](https://github.com/kubeflow/kubeflow/pull/3108), @kkasravi is still working and test it.

**Comment by kkasravi** [comment]
@jlewi @hougangliu @swiftdiaries I've also checked in a test-suite under manifests/tests as part of [PR34](https://github.com/kubeflow/manifests/pull/34). 
Calling the test-suite is 
```
cd manifests/tests
make all
```
There is 1 failing test that I'm looking at. 

@swiftdiaries did you have prow setup to call a manifest test? Perhaps I can integrate this into your prow job?

**Comment by swiftdiaries** [comment]
I'm going to setup prow for manifests so that we have pre-submits that trigger this test.

**Comment by kkasravi** [comment]
awesome-thank you!

**Comment by jlewi** [comment]
@kkasravi @swiftdiaries What is the remaining work to do to close this issue? 

Can we close this issue and open up more fine grained issues related to the remaining manifests that need to be converted?

**Comment by kkasravi** [comment]
yes, closing
