### ISSUE TITLE
clean up role binding after presubmit tests.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2570]
Error in presubmit project:
```ERROR: (gcloud.projects.set-iam-policy) INVALID_ARGUMENT: The number of members in the policy (1,510) is larger than the maximum allowed size 1,500.```
Currently after each test, service accounts are recycled but bindings are still there.

We need to clean bindings as well.

**Comment by jlewi** [comment]
Can we do a quick manual cleanup to get the tests fixed?

And then perhaps we can add it to the cleanup ci script:
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py

**Comment by kunmingg** [comment]
@jlewi 
should be good for next 10 presubmit tests.

**Comment by jlewi** [comment]
Here's the current iam policy.
In case we end up deleting roles we shouldn't this should help us recover.

[kubeflow-ci.iam-policy.yaml.txt](https://github.com/kubeflow/kubeflow/files/2917243/kubeflow-ci.iam-policy.yaml.txt)
