### ISSUE TITLE
presubmit error: ImportError: cannot import name tf_job_client

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2574]
from https://github.com/kubeflow/kubeflow/pull/2404
```
from py import tf_job_client
ImportError: cannot import name tf_job_client
```

Seems related to https://github.com/kubeflow/tf-operator/pull/945?

**Comment by lluunn** [comment]
seems temporary fix by #2555

**Comment by lluunn** [comment]
We still need a proper fix and revert #2555 
/cc @richardsliu 
/assign @zabbasi

**Comment by jlewi** [comment]
Is a proper fix to #2555 just editing the PYTHONPATH to include the new py directory in the tf-operator repository?

**Comment by lluunn** [comment]
And also update test files' import

**Comment by lluunn** [comment]
I still see presubmit failing with 
```
from py import tf_job_client
ImportError: cannot import name tf_job_client
```

**Comment by lluunn** [comment]
maybe this line needs change: https://github.com/kubeflow/kubeflow/blob/f5dc02168240a6b4d4cf661adccc05d126fcb27d/testing/workflows/components/kfctl_test.jsonnet#L177

**Comment by jlewi** [comment]
@zabbasi Is this fixed?

**Comment by lluunn** [comment]
This is fixed
