### ISSUE TITLE
Automate image builds of Jupyter UI

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#2578]
We need to update the jupyter-web-app's image in gcr to include the changes made in [this PR](https://github.com/kubeflow/kubeflow/pull/2490), in order to redirect to the correct URL for the notebook.

**Comment by jlewi** [comment]
@kimwnasptd Are we not building and pushing the jupyter image on postsubmit?

**Comment by kimwnasptd** [comment]
By taking a look [here](https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/jupyter-web-app?gcrImageListsize=30) the image was build only twice including the one done by hand (I guess?) yesterday. 
My mentioned PR changed two .js files in the `components/jupyter-web-app` dir. Is there a process/mechanism looking for changes under the components dir that builds the new images automatically?

**Comment by jlewi** [comment]
We should define an E2E test that builds the image automatically.

Some instructions here
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

On presubmit the image should be pushed to gcr.io/kubeflow-ci.
On postsubmt the image should be pushed to gcr.io/kubeflow-images-public

I would suggest using GCB to build the images (that seems to work better than using Docker in Docker or Kaniko).

The mnist jsonnet workflow might be a good place to start.
https://github.com/kubeflow/examples/blob/master/test/workflows/components/mnist.jsonnet

We probably just need the steps to checkout the repos and build the image using GCB.

**Comment by jlewi** [comment]
@kimwnasptd I believe we updated the notebook manager image. Is this issue now tracking automating builds of the notebook manager UI? If so should we update the title to reflect that?
