### ISSUE TITLE
[click-to-deploy app] Load test with multiple projects 

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#2580]
Current [load test](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy_app.py#L378) for click-to-deploy app doesn't generate enough load due to the API quota limit for a single project.

We need to

- Auto generate dozens of projects.
- Send requests to click-to-deploy to deploy KF to all these projects at the same time.

**Comment by zhenghuiwang** [comment]
/cc @jlewi @kunmingg 

I created 30 projects at folder `kf-gcp`: `kf-load-test-project1`, `kf-load-test-project2`...`kf-load-test-project30` using https://github.com/kubeflow/testing/pull/325

I ran 20 deployments (10 project X 2 deployment per project) in for 1-click-deployment staging simultaneously using https://github.com/kubeflow/kubeflow/pull/2648. Here are the logs for the final result
```
......
INFO|2019-03-13T15:54:13|test_deploy_app.py|301| IAP is ready for https://kubeflow2.endpoints.kf-load-test-project10.cloud.goog!
INFO|2019-03-13T15:54:13|test_deploy_app.py|553| 2 out of 2 deployments succeed for project kf-load-test-project10
INFO|2019-03-13T15:54:13|test_deploy_app.py|562| 19 out of 20 deployments succeed in total
INFO|2019-03-13T15:54:13|test_deploy_app.py|410| Clean up project resource (source repo, backend service and deployment)
...
```
The only failed deployment is due to `envoy` keeps failing.

**Comment by kunmingg** [comment]
Thanks!
