### ISSUE TITLE
Central dashboard doesn't render; lots of 404s

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2582]
I just deployed from master: commit: v0.4.0-rc.1-173-g3ea53cc2

central dashboard is using image gcr.io/kubeflow-images-public/centraldashboard:v20190223-v0.4.0-rc.1-152-g1de09b7a

The central dashboard returns lots of 404s; e.g. 

```
Request URL: http://localhost:8080/bower_components/webcomponentsjs/webcomponents-loader.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Thu, 28 Feb 2019 21:44:56 GMT
X-Content-Type-Options: nosniff
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: grafana_sess=966a5e96be9fe5ca; username-localhost-8888="2|1:0|10:1551052659|23:username-localhost-8888|44:Y2QxYWZlMTQ5NTBiNDYzMmJkODMxNDI0YWViZDBkMDk=|0f74ad55be44f4423db404ea3caa7c25def927e7b83451481bcba055e926cba5"; _xsrf=2|4c7b12ff|c4c1e9217e46a4da7c01ef53b10c91fe|1551052659
Host: localhost:8080
Referer: http://localhost:8080/
```

**Comment by jlewi** [comment]
Reopening: we need to

1. Update the ksonnet to point to a newly updated image.
1. Verify everything is working.

**Comment by jlewi** [comment]
Looks like #2576 already updated the ksonnet.
https://github.com/kubeflow/kubeflow/blob/020950dcfd36b18891e85f7d156c1237712e9a4b/kubeflow/common/prototypes/centraldashboard.jsonnet#L6

So we just need to verify that its working.

**Comment by jlewi** [comment]
Launch a job to update the auto-deployed ci cluster

```
```

**Comment by jlewi** [comment]
Now deployed at:
https://kf-vmaster-n01.endpoints.kubeflow-ci.cloud.goog/

**Comment by avdaredevil** [comment]
I do not have access to this: @jlewi

**Comment by prodonjs** [comment]
I believe this is resolved now correct?

**Comment by avdaredevil** [comment]
Still don't have access, but I believe the dashboard works, closing. Feel free to open @jlewi if I am mistaken.

Thanks

/close
