### ISSUE TITLE
[kfctl] Implements 3 way merge to CreateResourceFromFile or shell out to kubectl

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#2585]
Currently we implement `CreateResourceFromFile` in an elementary way such that:
- If deploying resource is there and we are not able to patch it, we try to delete and re-create it.
- If it's not there, we simply create it with `POST`.

We should at least consider:
- If the resource is there, we should take a look at config and see if we need to update it or just leave it as it is.

**Comment by gabrielwen** [comment]
Related to #2370

**Comment by jlewi** [comment]
I think we can shell out to `kubectl apply` if need be.

We definetly want the scripts to be re-entrant.

**Comment by gabrielwen** [comment]
As discussed, we should:
- Check if `kubectl` exists, if it does, shell out to `kubectl apply`
- If it doesn't, should we bail out or give a warning message that it might not work perfectly?

**Comment by jlewi** [comment]
@gabrielwen is this P1 or P2?

**Comment by gabrielwen** [comment]
let's put it as P2 first.

**Comment by jlewi** [comment]
Moving to 0.6 since its P2.
