### ISSUE TITLE
[kfctl] Consolidate kubeconfig and kfctl API calls

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#2586]
Currently we mixed uses of kubeconfig and cluster info from GCP.  Instead, in kfctl we should:
- Remove dependency of kubeconfig file from both kfctl CLI and Click-to-Deploy app.
- Add optionally kubeconfig support for kfctl CLI.  If user has both `gcloud` and `kubectl` installed, we help create cluster/context entry in user's local kubeconfig file.

**Comment by gabrielwen** [comment]
Relates to #2370

**Comment by gabrielwen** [comment]
Relates to #2535

**Comment by jlewi** [comment]
What is click to deploy currently doing to get credentials to talk to the K8s master?

I think in click to deploy the incoming request with have an OAuth token which can just be forwarded to the K8s master.

With the CLI, I think we might need to depend on gcloud. Even if we are using the go client libraries the user would typically do `gcloud auth login` to setup the credentials that Go client libraries will use. So I think depending on gcloud is ok in the CLI setting.

We might need to think about how we make that pluggable so it can support CLI as well as click to deploy.

**Comment by gabrielwen** [comment]
Right, I think click to deploy has an OAuth token.

I'm reading [this GoDoc](https://godoc.org/golang.org/x/oauth2/google), seems like we might be able to get auth token in CLI as well.  Would this be more feasible that we unify auth process by passing around auth tokens?  This also helps fix #2535

**Comment by jlewi** [comment]
is this blocking for 0.5? Or should we punt it to 0.6 at this point?

**Comment by gabrielwen** [comment]
it's not blocking.  I have some functions submitted for this but let's put it to 0.6
