### ISSUE TITLE
jupyter web app should provide status of notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2588]
Here's a screen shot of the Jupyter spawner after creating a new notebook

My notebook shows up but there is no indication of the status (e.g. pending, starting, running) etc...

We should expose that info in the UI

![jupyterspawner](https://user-images.githubusercontent.com/777219/53606365-7614e400-3b6f-11e9-8ffb-35e2ef9b44e9.png)

**Comment by lluunn** [comment]
depend on https://github.com/kubeflow/kubeflow/issues/2417 to add status to notebook CR.

https://github.com/kubeflow/kubeflow/pull/2558 is adding Ready condition when no error.

**Comment by jlewi** [comment]
@kimwnasptd @vkoukis @lluunn Any thoughts on what we could do for 0.5 so that users know when their pod is ready?

Could we work on updating the UI to show a status based on the Jupyter resource conditions? Maybe we could just report the most recent condition of the resource. 

This way once #2417 is fixed the status will be reported.

**Comment by vkoukis** [comment]
@jlewi 
> Could we work on updating the UI to show a status based on the Jupyter resource conditions? Maybe we could just report the most recent condition of the resource.

If I understand correctly, you propose the Notebooks UI shows  the latest status of instances of `Notebook` objects, as reported by the K8s API. I agree completely. Yes, the Notebooks UI manages `Notebook` instances: It creates, deletes them, and shows as much information as it can about them, in a user-friendly way.

We also went over this as part of today's community meeting: We agreed e2e status reporting is an important part of 0.5, and will have great impact in overall UX. So if @lluunn can have #2723 ready so #2417 can close, then we will have the UI side reporting it in a user-friendly way in 0.5, we will close this issue, and we should be good to go.

**Comment by lluunn** [comment]
#2723 is fixed now

**Comment by kimwnasptd** [comment]
Thank you @lluunn ! We'll move forward with our part ASAP.

**Comment by jlewi** [comment]
@kimwnasptd Do you have an ETA?
