### ISSUE TITLE
jupyter turn off token authentication

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2593]
I tried launching the following jupyter images using the new notebook manager and jupyter CR.

gcr.io/kubeflow-images-public/tensorflow-1.12.0-notebook-cpu:v-base-d635ca8-1180
tensorflow/tensorflow:nightly-py3-jupyter

When I tried accessing it over a web browser see screenshot below.

It looks like we need to disable token authentication

![jupyter](https://user-images.githubusercontent.com/777219/53618346-cad05300-3b9f-11e9-873d-e8e6b0394b6a.png)

**Comment by jlewi** [comment]
According to:
https://stackoverflow.com/questions/41159797/how-to-disable-password-request-for-a-jupyter-notebook-session

maybe we just need to use flags

```
--NotebookApp.token='' --NotebookApp.password=''
```

**Comment by jlewi** [comment]
@zabbasi can we close this issue?

**Comment by zabbasi** [comment]
done. https://github.com/kubeflow/kubeflow/pull/2591
