### ISSUE TITLE
Evaluate integrating the inference-model-manager into kubeflow, kfctl

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2594]
The [inference-model-manager](https://github.com/IntelAI/inference-model-manager) (IMM) dynamically deploys and scales inference endpoints.  It integrates with OpenVINO and Tensorflow Serving.

The model-manager provides an authorization model to secure inference endpoints where authentication is provided by dex. Tenants are grouped by namespace. 

We should evaluate whether we can integrate this framework into kubeflow as a component (most likely a kustomize component).
Part of the evaluation needs to determine:

1. Is the tenant namespace created by the inference-model-manager compatible or complementary to the Profiles namespace?
2. Are the secure endpoints that IMM deploys compatible with our istio integration?
3. Is the dex part of IMM optional? Does it conflict with a Profile Group or set of users that have access to kubeflow? Does dex work with kubeflow's current platforms gcp, minikube? 
4. There is an open issue (#2192) to grant kubeflow users access to cloud resources by using gcp serviceaccounts (as well as other IAM cloud provider credentials). How does this work with IMM tenants and credentials? 
5. How is IMM reconciled with the recent [Kubeflow Metadata Management Proposal](https://docs.google.com/document/d/104jv0BvQJ3unVEufmHVhJWgUAqJOk2CwsCpk5H5vYug/edit#)

**Comment by jlewi** [comment]
I only skimmed the inference-model-manager docs. Can you explain why that's a platform similar to GCP as opposed to a microservice deployed in the cluster akin to Seldon?

Might make for a good demo at the weekly meeting.

**Comment by kkasravi** [comment]
@jlewi yes i think you're right, i'll see if everything can be done within a kustomize component.
