### ISSUE TITLE
kfctl kustomize implement Apply and Delete methods

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2599]
Kustomize.Apply will need to do something similar to kubectl apply -f output.yaml
Kustomize.Delete will need to delete all resources including CRDs, ClusterRoles, ClusterRoleBindings and PVs. 

Apply can use k8utils.go CreateResourceFromFile
Delete should probably look for labels. Ksonnet.Delete should be referenced.

**Comment by swiftdiaries** [comment]
/assign @swiftdiaries 
I'll pick this one up

**Comment by swiftdiaries** [comment]
This is done. For now, the YAML built using kustomize is piped out to kubectl.
Link: https://github.com/swiftdiaries/kubeflow/commit/a0ef6bb14e879893e80c1af00333ab9d78b63cc8

**Comment by swiftdiaries** [comment]
I'll create a PR as soon as #2548 is merged because this is based off of that

**Comment by swiftdiaries** [comment]
I guess this is already done.
We can re-visit if it's warranted.

/cc @kkasravi 
/close
