### ISSUE TITLE
[bug] TFJob dashboard UI not showing up through Ambassador reverse proxy

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

> Tried the ambassador reverse proxy to connect to the TFJob dashboard. Got an empty page.

![screen shot 2018-02-16 at 7 41 01 pm](https://user-images.githubusercontent.com/23024031/36335889-64819324-1351-11e8-8cf8-308a5d8903d1.png)

**What you expected to happen**:

> Wanted the TFJob dashboard. Shown below.

![screen shot 2018-02-16 at 7 46 33 pm](https://user-images.githubusercontent.com/23024031/36336003-249d52a6-1352-11e8-8722-d14000b115d5.png)

**How to reproduce it (as minimally and precisely as possible)**:
```commandline
ks init my-kubeflow
cd my-kubeflow
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/master/kubeflow
ks pkg install kubeflow/core
ks pkg install kubeflow/tf-job
NAMESPACE=kubeflow
kubectl create namespace ${NAMESPACE}
ks generate core kubeflow-core --name=kubeflow-core --namespace=${NAMESPACE}
ks param set kubeflow-core cloud gke --env=cloud
KF_ENV=cloud
ks apply ${KF_ENV} -c kubeflow-core
PORT=4004
PODNAME=`kubectl get pods --namespace ${NAMESPACE} --selector="service=ambassador" -o \
jsonpath='{.items[0].metadata.name}'`
kubectl port-forward --namespace=${NAMESPACE} $PODNAME ${PORT}:80
```

Then open [http://127.0.0.1:4004/tfjobs/ui/](http://127.0.0.1:4004/tfjobs/ui/) in your browser.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by jlewi** [comment]
Is this the same problem as kubeflow/tf-operator#323

**Comment by swiftdiaries** [comment]
Yes. It's the same.
