### ISSUE TITLE
[Golang profile controller] fix permission leak when namespace exists.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2601]
When a namespace ```ns1``` created by admin1,
user1 can get permission by creating profile called ```ns1```.
We should identify this case and fix it.

**Comment by lluunn** [comment]
cc

**Comment by kunmingg** [comment]
Remove from 0.5.0 as we are not likely to ship it in this release.
Todo:
add to 0.6.0 once tag is created.

**Comment by kunmingg** [comment]
@gabrielwen
