### ISSUE TITLE
[GCP] kfctl create named context and set namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2604]
The kfctl go binary when running on GCP should do the equivalent of the following
https://github.com/kubeflow/kubeflow/blob/76230712d80805251f2ac54d66b0f02838de1c79/scripts/gke/util.sh#L156

Specifically it should create a context named after the KfApp and set the namespace to be the namespace where kubeflow is deployed.

**Comment by kunmingg** [comment]
@gabrielwen 
Can we close this one?

**Comment by gabrielwen** [comment]
not yet, we haven't implemented this one.  but I think this is at lower priority.

**Comment by jlewi** [comment]
I think we should try to include it in 0.5.X.
One of the first things users will do is try to run kubectl commands to see if kubeflow is deployed correctly.
e.g. kubectl get ingress is a good way to get the endpoint for Kubeflow.

**Comment by jlewi** [comment]
It looks like we are calling `get-credentials` here
https://github.com/kubeflow/kubeflow/blob/3fa97bc61e7b4b1eeb0062a8cbc98920e9da43d5/bootstrap/pkg/kfapp/gcp/gcp.go#L423
