### ISSUE TITLE
ksonnet error while following "Using Your Own Domain" instructions

### ISSUE THREAD

**Issue by ryan-williams** [kubeflow/kubeflow#2608]
Following [these instructions](https://www.kubeflow.org/docs/gke/custom-domain/):

```
cd ${KFAPP}/ks_app
ks delete default -c cloud-endpoints
ks component rm cloud-endpoints
```

seems to work, and makes changes that look reasonable (to my untrained eye). Then:

```
ks param set iap-ingress hostname ${FQDN}
ks apply default -c iap-ingress
```

The first command succeeds, but the second fails:

```
ERROR find objects: RUNTIME ERROR: Value non indexable: *jsonnet.valueNull
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:169:26-43	thunk from <object <anonymous>>
	<std>:1182:21-22	thunk from <function <anonymous>>
	<std>:1182:5-33	function <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:169:12-52	object <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:175:19-23	object <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:221:20-33	object <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:224:10-14	object <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:226:16-25	object <anonymous>
	$KFAPP/ks_app/vendor/kubeflow/application/application.libsonnet:(219:34)-(227:13)	function <anonymous>
	<std>:235:50-62	function <anonymous>

	During manifestation
```

Not sure what's useful to debug this. I can upload my `$KFAPP` dir if it would be useful. 

Otherwise, maybe there's a simple fix / something about the example commands is out-of-date?

**Comment by lluunn** [comment]
Yeah it's hard to tell from the log.

The error seems related to a component that imports application.libsonnet.
If you only care about iap-ingress component, you can try remove the component that import application.libsonnet. I remember even if you only apply iap-ingress component, ks still tries rendering all components.

**Comment by ryan-williams** [comment]
Interesting! [Here is my ks_app dir](https://github.com/ryan-williams/ks_app-dbg). 

I don't have enough context yet to understand your other suggestions, but will work on that 😄

**Comment by jlewi** [comment]
I did the following and was able to get it to work.

```
ks component rm application
ks show default -c iap-ingress
```
I think ksonnet tries to evaluate all the components even if only processing one component; as a result we see cases like this where unrelated issues cause errors.

I think in this case something is going wrong with the way the application component is trying to walk the list of components to generate meta information. Removing the application component should be fine and you should be able to apply the ksonnet components directly. 

Although once you remove the application resource I don't think you can use `kfctl.sh` to apply the components. 

/cc @kkasravi
