### ISSUE TITLE
[kfctl] Need E2E test for go binary

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2610]
We need to create a version of our E2E test which uses the new kfctl go binary.

**Comment by kunmingg** [comment]
We need presubmit test covering kfctl for basic auth & IAP path.
@jlewi and @gabrielwen have coming PRs for it.

**Comment by jlewi** [comment]
After #2705 is merged here is some follow on work.

* We need to actually extend the E2E workflow will the validation steps we currently run in kfctl_test
  * e.g. Try submitting a TFJob

* kfctl delete is failing;
  * Delete is failing because `kfctl delete` expects a kubeconfig file and there is none. 

* As a result we will be leaking deployments in the project `kubeflow-ci-deployment`
  * We will need to setup GC'ing of resources in that project.

**Comment by jlewi** [comment]
The test is deployed and running.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-master/1112425585537191937
