### ISSUE TITLE
JupyterLab not working in latest notebook images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#262]
When I start a fresh notebook and try to navigate to "/lab" I get

```
Cannot find template: "index.html"
In ""
```

I rebuilt the Docker images last week.

This is using
gcr.io/kubeflow/tensorflow-notebook-cpu:v20180213-6d6843ac

**Comment by jlewi** [comment]
It doesn't look like we changed the version of JupyterHub or JupyterLab.

Using the older image
gcr.io/kubeflow/tensorflow-notebook-cpu:8fbc341245695e482848ac3c2034a99f7c1e5763

It starts just fine.

**Comment by jlewi** [comment]
Looks like jupyterlab/jupyterlab#3758

**Comment by jlewi** [comment]
```
import jupyterlab
jupyterlab.__version__
0.24.1
```

**Comment by jlewi** [comment]
If I pip install jupyterlab the version is  '0.31.8'.

**Comment by jlewi** [comment]
I looked at the pod logs for the hub and the actual pod and I didn't see any errors.

**Comment by cwbeitel** [comment]
Currently I see this error with gcr.io/kubeflow/tensorflow-notebook-cpu but not with gcr.io/kubeflow-images-staging/tensorflow-notebook-cpu (JupyterLab starts fine with the latter).

**Comment by jlewi** [comment]
That's correct. The images in gcr.io/kubeflow are outdated. You should use the images in gcr.io/kubeflow-images-staging.
