### ISSUE TITLE
Notebook controller should check if child resources already exist

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2621]
E.g. for notebook controller, it should check whether the underlying statefulset already exists.

Maybe we can use annotation to determine whether the statefulset is generated by a notebook

cc @kunmingg

**Comment by jlewi** [comment]
@lluunn Is there more work  to be done for the jupyter controller?

/cc @zabbasi

**Comment by lluunn** [comment]
The scenario is that when I create a notebook called A, controller will create a statesulset called A.
What happen if there is already a statefulset A (not a notebook).

The TODO is to configure what's the desired behavior and implement that.
This is not common though, so I think P2 is fine.

**Comment by jlewi** [comment]
Got it thanks.
