### ISSUE TITLE
Any plan to enable https support for kubeflow UI

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/kubeflow#2623]
Now I can access the kubeflow UI via ambassador using `http`, but this is not secure, any plan to enable kubeflow UI support `https`?

**Comment by gyliu513** [comment]
FYI @jlewi any comments for this?

**Comment by jlewi** [comment]
You need to setup an auth proxy in front of ambassador.

In 0.5 we are adding support for basic auth over https. You can also use things like Dex to integrate with OIDC providers.

The release demo http://bit.ly/05_mid_release_demo 
has some instructions but I'm not sure its functional yet.

**Comment by jlewi** [comment]
I would also expect the platform(GCP,Azure, openshift,...) owners to provide a default setup that does the correct thing.

On GCP we deploy Kubeflow behind https and secure it with IAP; the mechanics are platform specific. So its up to the platform owners to provide a plugin that does the right thing on their platform.
