### ISSUE TITLE
Jupyter notebooks on GPU nodes.

### ISSUE THREAD

**Issue by llegolas** [kubeflow/kubeflow#2624]
In order to make jupyper notebook pods utilize GPUs  on openshift I needed to modify jupyter_config.py like this:
```
--- jupyter_config.py   2019-03-05 09:27:04.161988578 +0200
+++ jupyter_config_GPU.py       2019-03-05 09:28:56.953993982 +0200
@@ -13,6 +13,7 @@
 from importlib.util import spec_from_file_location, module_from_spec
 from jhub_remote_user_authenticator.remote_user_auth import \
     RemoteUserAuthenticator
+from kubernetes import client
 
 SERVICE_ACCOUNT_SECRET_MOUNT = '/var/run/secrets/sa'
 
@@ -57,20 +58,33 @@
 if env_gid:
     c.KubeSpawner.singleuser_fs_gid = int(env_gid)
 access_local_fs = os.environ.get('ACCESS_LOCAL_FS')
-if access_local_fs == 'true':
-    def modify_pod_hook(spawner, pod):
-        pod.spec.containers[0].lifecycle = {
-            'postStart': {
-                'exec': {
-                    'command': [
-                        'ln', '-s', '/mnt/local-notebooks',
-                        '/home/jovyan/local-notebooks'
-                    ]
-                }
-            }
-        }
-        return pod
-    c.KubeSpawner.modify_pod_hook = modify_pod_hook
+#if access_local_fs == 'true':
+#    def modify_pod_hook(spawner, pod):
+#        pod.spec.containers[0].lifecycle = {
+#            'postStart': {
+#                'exec': {
+#                    'command': [
+#                        'ln', '-s', '/mnt/local-notebooks',
+#                        '/home/jovyan/local-notebooks'
+#                    ]
+#                }
+#            }
+#        }
+#        return pod
+#
+#    c.KubeSpawner.modify_pod_hook = modify_pod_hook
+
+def modify_pod_hook(spawner, pod):
+    pod.spec.containers[0].security_context = client.V1SecurityContext(
+        capabilities=client.V1Capabilities(
+            drop=['ALL']
+        ),
+        se_linux_options=client.V1SELinuxOptions(
+            type='nvidia_container_t'
+        )
+    )
+    return pod 
+c.KubeSpawner.modify_pod_hook = modify_pod_hook
 
 ###################################################
 # Persistent volume options

```
I know it is ugly and there could be condition if the additional resources from the GUI are adding anvidia.com/GPU. 
I'm also not sure if this will be needed in GCP but can it be considered?

**Comment by jlewi** [comment]
Thanks @llegolas 

@pdmack So it looks like certain settings need to be injected. Any idea on how we should do this in 0.5 with the new jupyter setup?

@lluunn Has created a generic admission controller for injecting environment variables and secrets.

We could potentially modify/copy that to support setting other settings.

**Comment by pdmack** [comment]
Yes, OpenShift GPU support has adopted a particular best practice around the use of selinux in the securityContext as opposed to allowing a GPU container to have elevated privilege. I like the admission controller approach.

**Comment by shalberd** [comment]
I see your code above, but I do not understand what you mean by injecting the setting when starting the notebook in 0.5, e.g. using base image tensorflow-1.13.1-notebook-gpu 

The Nvidia Device Plugin deamonset in openShift 3.11 should need those settings:
--security-opt=no-new-privileges --cap-drop=ALL \
--security-opt label=type:nvidia_container_t

I tried running code without these settings and it fails:
´´´
import tensorflow as tf;
print(tf.__version__);
print(tf.test.is_built_with_cuda());
print(tf.test.is_gpu_available());
´´´
error:
´´´
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/opt/conda/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/opt/conda/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-cd12e2fe8838> in <module>
----> 1 import tensorflow as tf;
      2 print(tf.__version__);
      3 print(tf.test.is_built_with_cuda());
      4 print(tf.test.is_gpu_available());

/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

/opt/conda/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
´´´

**Comment by llegolas** [comment]
@shalberd this looks like problem with python and the libs available in the image not directly related to  openshift or k8s.
jupyter_config.py is loaded from configmap named jupiter-config within the kubeflow namespace.
You have to delete jupyter-0 pod after edit so it gets picked up.

**Comment by shalberd** [comment]
Thank you, @llegolas, I will do so and try another image as well, that is because, as you suggested, the image itself might be missing libs:

https://github.com/kubeflow/kubeflow/issues/3094

**Comment by shalberd** [comment]
Legolas' tip and a different image together worked great. 
```
import tensorflow as tf;
print(tf.__version__);
print(tf.test.is_built_with_cuda());
print(tf.test.is_gpu_available());

1.12.0
True
True
```
Now of course it would be great to have this custom-injected via mentioned admission controller. Is anything planned in that regard?
