### ISSUE TITLE
Discussion: Eventing model/solution

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#263]
Given that training can take a really long time, we should figure out how to fire events at different stages that can be consumed by other tools. Ideally, we'd have a package that ran for on-prem deployments, and then could also use cloud event providers.

**Comment by jlewi** [comment]
Closing this issue because eventing is being discussed in the context of Argo and Pipelines. We can open up more specific issues as needed to figure out how to integrate various components with them.
