### ISSUE TITLE
kfctl apply failed for invalid spec.version when installing CRD tfjobs.kubeflow.org

### ISSUE THREAD

**Issue by irhawks** [kubeflow/kubeflow#2634]
I'm initializing a kubeflow testing environment following offical getting started guide <https://www.kubeflow.org/docs/started/getting-started/>. Here are the commands (just copy them from the webpage):

```
export KUBEFLOW_SRC=$(pwd)/kubeflow

mkdir ${KUBEFLOW_SRC}
cd ${KUBEFLOW_SRC}
export KUBEFLOW_TAG=v0.4.1

curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash

export KFAPP=kfapp
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none
cd ${KFAPP}
${KUBEFLOW_SRC}/scripts/kfctl.sh generate k8s
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
```

However, an errors raised when running last line `${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s`. The following is the log:

```
# ${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ GKE_API_VERSION=v1beta1
+ GCP_DEFAULT_ZONE=us-east1-d
+++ dirname /root/ceph/rencx/node01/kubeflow/scripts/kfctl.sh
++ cd /root/ceph/rencx/node01/kubeflow/scripts
...
+ ks apply default -c centraldashboard
INFO Applying services kubeflow.centraldashboard  
INFO Applying serviceaccounts kubeflow.centraldashboard 
INFO Applying roles kubeflow.centraldashboard     
INFO Applying deployments kubeflow.centraldashboard 
+ ks apply default -c tf-job-operator
ERROR handle object: patching object from cluster: merging object with existing state: CustomResourceDefinition.apiextensions.k8s.io "tfjobs.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions 
```

My cluster configuration:

- kubernetes v1.13.4: installing with kubeadm
- ksonnet version: 0.13.1
- jsonnet version: v0.11.2
- client-go version: kubernetes-1.10.4
- kubeflow version: v0.4.1

**Comment by irhawks** [comment]
#2487

**Comment by johnugeorge** [comment]
Have you previously installed tf-job-operator ?   Can you paste output of `kubectl get crd ` ?

**Comment by richardsliu** [comment]
This sometimes can happen if the same ksonnet app is being reused. Have you tried to start from a fresh deployment? Basically change KFAPP to some other value and try the scripts again.

**Comment by irhawks** [comment]
Thank you. I think @richardsliu is right. I have checked tf-job-crd and the error disappeared after deleting kubeflow and CRD tfjobs.kubeflow.org and redo the official installation guide.

And I have reproduced this error with installing kubeflow v0.4.1 (in this new cluster) after ksonnet previous v0.3.1 (old artifacts).
