### ISSUE TITLE
Provide a  build option that will create a versioned package for k8 libraries

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2636]
Currently in kfctl we load package managers ksonnet and kustomize. Their APIs are built against different, non-overlapping kubernetes versions: 1.10.4 and 1.13.4 respectively. They also use different k8s.io/client-go and sigs.k8s.io/controller-runtime libraries. In order to load kustomize within kfctl (along with ksonnet) we need to use golang package versioning for the following kubernetes libraries: 
- k8s.io
           |___ api-kubernetes v1.13.4
           |___ apiextensions-apiserver v1.13.4
           |___ apimachinery v1.13.4
           |___ cliet-go v10.0.0
- sigs.k8s.io
           |___ controller-runtime v0.1.10
           |___ kustomize v2.0.2

We need to provide golang package versioning for these libraries despite the fact that kubernetes has yet to move to golang modules. Updating these libraries to use golang modules is straight-forward and can be done using local git clones. Background information on how this is done can be found [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

Currently a build artifact was hand built and checked into PR #2548 as bootstrap/hack/v2.zip.
This build artifact holds versioned packages for the above libraries. This hand-built artifact needs to be removed and replaced with a golang tool such as [mod](https://github.com/marwan-at-work/mod) that can do this algorithmically and as part of building kfctl.  

The  [mod](https://github.com/marwan-at-work/mod) tool needs to be modified in the following ways:
1. Update literal references to versioned packages as found [here](https://github.com/kubernetes/api/blob/kubernetes-1.13.4/apps/v1/generated.pb.go#L62) and [here](https://github.com/kubernetes/api/blob/kubernetes-1.13.4/apps/v1/generated.pb.go#L63).
2. Move a subset of libraries tagged as [+incompatible] (https://groups.google.com/forum/#!topic/golang-codereviews/t-xcPhCn3FI) within the go.mod file, instead of all of them.
3. Create a local archive of these versioned packages 
4. Update go.mod files that reference the versioned packages with a replace directive pointing to the the local archive location. 

Urgency:
This is not a blocking issue for 0.5 since the prebuilt artifact has been integrated into the kfctl build process. However for 0.5+ we should create this tool so subsequent changes in versioned packages (eg moving to k8s.io/api@kubernetes-1.14.0 for example) are trivial and require simple edits of the Makefile.

**Comment by jlewi** [comment]
@kkasravi Any update on this? I thought you had come up with a solution?

**Comment by kkasravi** [comment]
Our current v2.zip has frozen versions of 

k8s.io
|___ api-kubernetes v1.13.4
|___ apiextensions-apiserver v1.13.4
|___ apimachinery v1.13.4
|___ cliet-go v10.0.0
sigs.k8s.io
|___ controller-runtime v0.1.10
|___ kustomize v2.0.2

If we wanted to move to a later version of kubernetes (say 1.14.1) - we would need to complete the mod tool as described above.
