### ISSUE TITLE
Error in application component

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2642]
#2608
#2622

Both issues have error when trying to apply (or show) application component generated from kfctl.

cc @kkasravi

**Comment by lluunn** [comment]
I just tried ks generate, and then immediate ks show.
It worked fine.
So I think it's kfctl's problem

**Comment by lluunn** [comment]
Seems that when application.libsonnet [doing](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/application/application.libsonnet#L207)
 `std.filterMap(clusterScope, byResource, tuples)`
some resource in iap-ingress component failed

**Comment by lluunn** [comment]
the problem should be in cloudendpoint component, because if I commented out this line it works fine.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/iap.libsonnet#L1029

**Comment by lluunn** [comment]
So the problem is the hostname I passed in is not cloud endpoint's format, and one component in iap-ingress is empty, and causes error.

**Comment by kkasravi** [comment]
thanks @lluunn
