### ISSUE TITLE
Connect to external MySQL/PostGres DB from Jupyter

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/kubeflow#265]
Easily usable connectors for popular DBs

**Comment by jlewi** [comment]
Chris can you provide more detail? What DBs are you looking to use? How are you looking to use them? For example, do you want to use them with TensorFlow?

**Comment by aronchick** [comment]
Chris and I were discussing this HN article (
https://news.ycombinator.com/item?id=16354989), and he volunteered to
create the issues. Basically, we're looking to address some of these
comments:

- How you connect to a DB server (particularly if it's not in your cluster)
- https://news.ycombinator.com/item?id=16356396
- Particularly in re: PostgreSQL -
https://news.ycombinator.com/item?id=16356059
- Further thoughts here - https://news.ycombinator.com/item?id=16071612

There's just a lot of simplification we can do and/or examples we can show
to help people get started.

**Comment by bhack** [comment]
Have we any affinity with https://github.com/Microsoft/DLWorkspace/blob/master/docs/deployment/database/Readme.md?

**Comment by jlewi** [comment]
I'm scoping this issue to connecting to SQL databases from Jupyter.
This distinguishes it from connecting from say TensorFlow in TFJobs which might require first class support in TF.

I suspect this is largely a matter of documenting the right process; e.g.

- Create a service to point at the DB which lives outside the cluster
- Use secrets to provide credentials.
