### ISSUE TITLE
Central Dashboard Label is spelled incorrectly

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2652]
/assign @jlewi 

The label is misspelled as `/area centraldashbosard` hence it hasn't been used much. Not sure if we can fix it, but made sense to bring it up in case it can be resolved. Thanks!

Link: https://github.com/kubeflow/kubeflow/labels/area%2Fcentraldashbosard

**Comment by jlewi** [comment]
Fixed.

Labels can also be specified here.
https://github.com/kubeflow/testing/blob/master/label_sync/kubeflow_label.yml

You can use that to rename labels.
