### ISSUE TITLE
kfctl Not actually setting GCP IAM roles

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2659]
I'm using the new kfctl go binary built from **v0.4.0-rc.1-199-g51b410ad**

The logs indicate that the IAM roles are being  set

```
INFO[0040] roles/dataproc.editor adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/compute.networkAdmin adding: Set{serviceAccount:jlewi-0307-basic-admin@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/bigquery.admin adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/cloudsql.admin adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/source.admin adding: Set{serviceAccount:jlewi-0307-basic-admin@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/viewer adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/dataflow.admin adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/cloudbuild.builds.editor adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/storage.objectViewer adding: Set{serviceAccount:jlewi-0307-basic-vm@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/iap.httpsResourceAccessor adding: Set{user:jlewi@google.com} 
INFO[0040] roles/logging.logWriter adding: Set{serviceAccount:jlewi-0307-basic-vm@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/storage.admin adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/ml.admin adding: Set{serviceAccount:jlewi-0307-basic-user@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/servicemanagement.admin adding: Set{serviceAccount:jlewi-0307-basic-admin@cloud-ml-dev.iam.gserviceaccount.com} 
INFO[0040] roles/monitoring.metricWriter adding: Set{serviceAccount:jlewi-0307-basic-vm@cloud-ml-dev.iam.gserviceaccount.com} 
```

However, when I get the IAM policy; I don't see any role bindings  actually being set. As a result I get errors such as CloudEndpoint not being created.

/cc @gabrielwen @kunmingg @lluunn

**Comment by gabrielwen** [comment]
IAM role bindings should be set [here](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/client/gcp/gcp.go#L418-L432)

If I remember correctly rewriting works, is it because [SetIamPolicy](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/client/gcp/gcp.go#L430) silently fails?

**Comment by jlewi** [comment]
@gabrielwen Not sure what the problem is.The logs indicate it is trying to set the binding role but its failing for some reason.

**Comment by gabrielwen** [comment]
Right, I think we need to look into [SetIamPolicy](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/utils/iamutils.go#L165https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/utils/iamutils.go#L165).

In specific, should look at the response which is in the type of [Policy](https://godoc.org/google.golang.org/api/cloudresourcemanager/v1beta1#Policy).  There is a field `ServerResponse`, which I suspect having some clues.  Sorry I didn't check this when I was implementing.

Another issue when looking at `SetIamPolicy` is that this API call is to override the whole project IAM policy - that is, risk of write conflicts.

**Comment by jlewi** [comment]
Thanks @gabrielwen. That makes sense.

**Comment by lluunn** [comment]
got this too, pods have permission error. 
looking into it now

**Comment by lluunn** [comment]
we are doing it similarly in bootstrapper: https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/gcpUtils.go#L281

**Comment by kunmingg** [comment]
@gabrielwen 
I have a PR to fix it:
https://github.com/kubeflow/kubeflow/pull/2681
Can you review when have time?
