### ISSUE TITLE
Better identity management in K8s

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/kubeflow#266]
TBD

**Comment by jlewi** [comment]
Can you provide more detail please? What are the current problems limitations? And why are these Kubeflow issues and not K8s issues?

**Comment by jlewi** [comment]
I'm closing this in favor of existing issues that are more specific.
If there's something not covered by existing issues lets open up more specific ones.

#372 Pattern for creating/using secrets across multiple prototypes
#101 Lock down Jupyter pods.

**Comment by kkasravi** [comment]
This may be a duplicate of #11 since auth is part of that issue (secure proxy)

**Comment by jlewi** [comment]
@kkasravi Can we make this issue or a new issue more specific?

The current state of the world is we have 

- IAP which will provide a google identity to JupyterHub
- An http basic auth module (see #11) for Ambassador.

So was the intent to provide an auth module for ambassador that would use other oauth providers like GitHub and then supply that id to JupyterHub?
