### ISSUE TITLE
kfctl doesn't create secret with username and password for basic auth

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2661]
I deployed Kubeflow using basic auth using the kfctl binary.

The secret ` kubeflow-login` containing the username and password isn't actually created.

It would be good to have a command in kfctl for setting the secret and username.
Something like

kfctl create-basic-auth-secret --username=<> --password=....

So users could easily update/change it if they forget.

**Comment by gabrielwen** [comment]
do we expect people using other platforms also use basic auth?  e.g. do we need to add a new method to the interface?
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/apis/apps/group.go#L89-L94

**Comment by jlewi** [comment]
Yes we expect people on other platforms to use basic auth.

@gabrielwen Is this fixed can we close it?

**Comment by gabrielwen** [comment]
Still need to add the cmd `create-basic-auth-secret`.  Currently it's passed during `kfctl init`

**Comment by jlewi** [comment]
@gabrielwen I also think we should avoid storing the encrypted password if possible.

We generally want to avoid storing sensitive information in the app directory because the expectation is people will check their app into source control.

The pattern we follow with other sensitive information like client_id and client_secret is to read it from an environment variable. This way we avoid storing it anywhere.

**Comment by gabrielwen** [comment]
Yep, makes sense.  will make the change tomorrow first thing.

**Comment by jlewi** [comment]
@gabrielwen Can we close this issue?
