### ISSUE TITLE
Instructions for upgrading from basic auth to IAP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2663]
It would be great to have instructions for how people can upgrade from basic auth to IAP.

Off the top of my head here are some steps involved

1. Create an OAuth client id / secret
1. Turn on IAP 
1. Turn on JWT validation at the gateway
1. Set IAP iam role on accounts

Some things to consider ?

* Can we avoid disabling basic auth until IAP is configured and working properly?

   * One way to do this would be to have a separate endpoint/ingress for IAP
      * One problem with this is that the base URL would then change so it would be user visible and pods like jupyter would need to be restarted to reconfigure the base_url prefix

  * If we turn on IAP I think the user would just login once with IAP and then again with basic auth
     * We could perhaps fix that by having the basic auth login proxy accept JWTs

  * We'd like the basic auth login username to match the identity used with IAP so users could continue to be associated with resources (e.g. jupyter pods) that they had created.

**Comment by kunmingg** [comment]
Sure, we can provide a more broad, like update API to edit existing deployment.
Which can also include version upgrade story.

**Comment by jlewi** [comment]
Lets punt to 0.7.
