### ISSUE TITLE
Default Install for Katib & Pipeline access from UI is broken

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#2665]
Action:
- Install Kubeflow 0.4.1 using standard deployment
- kubectl port-forward svc/ambassador -p 8080
- Access UI via browser
- Click on "Pipelines" or "Katib"

Expected:
- Access to Katib or Pipeline UI

Actual:
- Katib => blank page
- Pipelines => 404 not found

**Comment by andreyvelich** [comment]
Can you show the logs from Katib-UI controller and StudyJob controller, please?

**Comment by jlewi** [comment]
cc @vicaire /

**Comment by vicaire** [comment]
Is this issue for the pipeline UI or for the master UI that iframes the other UIs? 

Since both Katib and pipeline are affected, I am guessing this is an issue on the kubeflow-core side. Let me know if that's not the case and if you need someone from the pipeline team to have a look. Thanks.

**Comment by jlewi** [comment]
@vicaire  0.4.1 doesn't use iframing

@aronchick I'm checking on master which is using the new central dashboard and everything is working fine for me.

**Comment by aronchick** [comment]
if it's fixed on master, feel free to close (obv) - i was using 041
