### ISSUE TITLE
Assess usability on vanilla dockers

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/kubeflow#267]
Gather feedback and Evaluate vanilla docker

**Comment by jlewi** [comment]
Do you mean trying to run directly on Docker and not Kubernetes?

**Comment by jlewi** [comment]
Running on vanilla Docker is an explicit non-goal for Kubeflow. We take a hard dependency on Kubernetes so I don't think we should invest in supporting running on non K8s platforms.

**Comment by aronchick** [comment]
Changed the title - this is really supposed to be comparing the usability of minikube/docker-kube to a vanilla docker container. Here's an example of using Docker for data science - we should be just as easy (or easier) from start to finish - https://unsupervisedpandas.com/data-science/docker-for-data-science/

**Comment by jlewi** [comment]
@aronchick @abhi-g Can we close this issue?  "Assess usability" is rather vague.
