### ISSUE TITLE
[Dashboard v1] Hide Central Dashboard sidebar when viewing iframe pages

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#2678]
Based on some feedback, it seems like the iframe view creates some confusion if the child page has a sidebar component like the Pipeline Dashboard does. An ideal experience would hide the central dashboard's navbar and place some kind of overlay toggle to restore it on top of the iframe view.

**Comment by avdaredevil** [comment]
/priority p1
 I'll be working on this

**Comment by prodonjs** [comment]
Also, I spoke with @ajayalfred, it looks like Riley from the Pipelines UI team is OoO until next week. It looks like the change to the sidebar is isolated to https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/SideNav.tsx#L38. Do you think that's something you can address here as well?

**Comment by avdaredevil** [comment]
Sure I can def contribute to their codebase and get it done!

**Comment by avdaredevil** [comment]
_**Update:** @rileyjbauer is on this_
