### ISSUE TITLE
Cannot create notebooks with Custom Image notebooks with Non-IAP deployment

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#2680]
When launching notebook containers from Custom Images from the spawner UI, I am unable to create notebooks or terminals once the pod is ready and I am at the Jupyter tree view. This happens only when:
  1. the cluster has been setup with "Skip IAP" option checked at the deployment web app. 
and 2. The port-forwarding to the Central Dashboard is setup via running the command in Cloud Shell.

If either of the above two is not true, the notebooks work fine. ie. either IAP is enabled or, the port-forwarding is setup from local machine instead of cloud shell.

The specific error in the pod's container logs is:

2019-03-11 13:16:26.253 PDT
[W 2019-03-11 20:16:26.252 SingleUserNotebookApp handlers:325] **Blocking Cross Origin API request for /user/toto/api/contents. Origin: https://8080-dot-4278237-dot-devshell.appspot.com, Host: 127.0.0.1:8080**
 
Expand all | Collapse all {
 insertId:  "1io39e1fdw1bfi"  
 labels: {…}  
 logName:  "projects/abhishek-lab2/logs/notebook"  
 receiveTimestamp:  "2019-03-11T20:16:29.315339353Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "[W 2019-03-11 20:16:26.252 SingleUserNotebookApp handlers:325] Blocking Cross Origin API request for /user/toto/api/contents.  Origin: https://8080-dot-4278237-dot-devshell.appspot.com, Host: 127.0.0.1:8080
"  
 timestamp:  "2019-03-11T20:16:26.253116216Z"  
}
2019-03-11 13:16:26.260 PDT
[W 2019-03-11 20:16:26.260 SingleUserNotebookApp log:122] **404 POST /user/toto/api/contents (toto@10.8.1.7) 8.74ms**
 
Expand all | Collapse all {
 insertId:  "1io39e1fdw1bfj"  
 labels: {
  compute.googleapis.com/resource_name:  "fluentd-gcp-v3.2.0-8vhx9"   
  container.googleapis.com/namespace_name:  "kubeflow"   
  container.googleapis.com/pod_name:  "jupyter-toto"   
  container.googleapis.com/stream:  "stderr"   
 }
 logName:  "projects/abhishek-lab2/logs/notebook"  
 receiveTimestamp:  "2019-03-11T20:16:29.315339353Z"  
 resource: {
  labels: {…}   
  type:  "container"   
 }
 severity:  "ERROR"  
 textPayload:  "[W 2019-03-11 20:16:26.260 SingleUserNotebookApp log:122] 404 POST /user/toto/api/contents (toto@10.8.1.7) 8.74ms
"  
 timestamp:  "2019-03-11T20:16:26.260767605Z"  
}

**Comment by kunmingg** [comment]
Is the spawner UI refer to the old one or the new one?

**Comment by abhi-g** [comment]
This is on v0.4.1, so its the new UI, but older backend.

**Comment by jlewi** [comment]
@zabbasi I think this is the custom notebook that we want to use:
https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/Dockerfile

**Comment by zabbasi** [comment]
fixed in #536

**Comment by zabbasi** [comment]
@abhi-g fixed this. it is working now. dont have permission to close it.

**Comment by abhi-g** [comment]
when that PR merges it should automatically close the issue.

**Comment by zabbasi** [comment]
rebuild the custom image from https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/Dockerfile and it worked.
