### ISSUE TITLE
tf-operator Docker image based on Cent OS image with a security flaw

### ISSUE THREAD

**Issue by JavaDerek** [kubeflow/kubeflow#2688]
The base image for the tf-operator Docker image (as of March 12, 2019) is vulnerable to https://bugzilla.redhat.com/show_bug.cgi?id=1667032.  Minimally, the tf-operator Dockerfile should apply the appropriate security patches before laying down the actual Kubeflow bits.

**Comment by jlewi** [comment]
@richardsliu @zabbasi @pdmack Have we already updated the base image for the tf-job-operator docker image so that the next release will include the security patch?

**Comment by pdmack** [comment]
This will be fixed by an updated image from centos.
Hopefully early next week.

**Comment by JavaDerek** [comment]
BTW, I don't know if this should be a separate issue or not, but if the "7" tag basically means "the latest version of CentOS 7"... is that the right choice for basing KF images?  On one hand, I'll be happy to see these security fixes just automatically flow into KF this time.  But, doesn't that technically open the door for everything in KF to break if there was ever a CentOS push of something incompatible?  It almost seems like the KF images should derive from some more specifically tagged version and then consciously decide when to change versions after testing.

**Comment by richardsliu** [comment]
Can this be closed now?
