### ISSUE TITLE
kfctl config issue

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2691]
## Background
Currently, a KFApp has two layers:
1. parent app, the coordinator
2. child apps, a platform (gcp, minikube) and a packageManager (ksonnet, kustomize)

and different actions: init, generate, apply, delete, ..

When we run a command, e.g. `kfctl generate --A=B ...`, coordinator calls GcpApp.Generate and KsApp.Generate with the flags (the `option` variable in the code). 
I think it's not working properly now:
- some flag (e.g. UseBasicAuth) is needed is both platform and packageManager, and both generate and apply. 
- Gcp.Spec and KsApp.Spec stores different fields.
- I think it's confusing that whether a field, basicAuth, should be in `option`, or gcp.spec, or ks.spec.
- ksonnet.Generate right now has no information on whether to use basicAuth or not.

## Proposal
One possible solution is to save everything in `coordinator.spec`. And for any action (init or generate or else), coordinate passes `coordinator.spec` to platform and packageManager.
`gcpApp.Generate(coordinator.Spec)`

In addition, we can dump coordinator.spec to app.yaml. Then for any action, coordinator will
1. read app.yaml in as the spec
2. update the spec with new flags
3. pass spec to GcpApp and ksApp

This way users can just modify the app.yaml, and that will take effect.

cc @kkasravi @jlewi @kunmingg

**Comment by lluunn** [comment]
@gabrielwen

**Comment by kkasravi** [comment]
I think this makes sense. Each subcommand would call a function that takes the action and flags. This is merged with the app.yaml, unmarshalled into one Spec and given to coordinator. All platform and package managers share this one spec which may be mutated by the platform prior to passing to  the package manager.

**Comment by kkasravi** [comment]
We suggested a design doc for kfctl, this would be a good time to produce one, since it is a service with now a wider audience @lluunn @kunmingg @gabrielwen @swiftdiaries

**Comment by gabrielwen** [comment]
Discussed offline with @lluunn , we agree that information should be able to be shared between different components and be accessed easily.  Thanks for pointing this issue out - I'm gonna need it as well.

@kkasravi : Totally agree that we need a design doc for kfctl.  We have reached a stage where it's not only about kfctl CLI, we also need to consider compatibility with click-to-deploy app and extensibility to other platforms.  Let's make kfctl work for 0.5 for now and pivot back to the design doc :)

**Comment by swiftdiaries** [comment]
+1 on the design doc.

**Comment by kkasravi** [comment]
i'll refactor as suggested above - and get going on the design doc. Priority should be getting the code in a form we all like.

**Comment by kkasravi** [comment]
also no suggestion that others can't jump in on the code

**Comment by jlewi** [comment]
Are we going to be persisting information in two places? e.g. when we persist information to app.yaml is that going to duplicate information stored in other places e.g. GCP DM config files?

**Comment by kkasravi** [comment]
right now we're copying that information into app.yaml (see below for a sample app.yaml). Since app.yaml is created after `init`, the user can modify app.yaml prior to running `generate` to change the components or parameters. 

An alternative would be to provide a kustomization layer based on config files. I opened #2685 for this and would avoid duplication of the config info.

**Comment by kunmingg** [comment]
@jlewi Agree. 
One possible problem with duplicate config would be:
```
kfctl generate --configA=value1
(value1 saved to gcp/k8s configs)
kfctl apply --configA=value2
What will be used for apply? value1 or value2
```
It could be flaky to have a ```app.yaml``` to pass parameters between steps:
* user are allowed to overwrite between steps
* kfctl might duplicate values to different places in previous steps, which is not covered by user's overwrite

Can we remove ``` app.yaml ``` and apply just read gcp/k8s configs to figure out necessary actions to be made?

**Comment by kkasravi** [comment]
@kunmingg actually this is how it works now, you'll get a usage error 
```
$ ☞  kfctl generate --project=foo
Error: unknown flag: --project
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'
      --ipName string     ipName if '--platform gcp'
      --mount-local       mount-local if '--platform minikube'
  -V, --verbose           verbose output default is false
      --zone string       zone if '--platform gcp' (default "us-east1-d")

unknown flag: --project
```

each subcommand has a specific set of flags. A good example is the generate subcommand
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/kfctl/cmd/generate.go#L82

**Comment by kkasravi** [comment]
I should note that `--project` can only be set in `kfctl init ...` but is available to subsequent commands in their specific application_type. The proposal is to simplify this and put all values in ClientSpec
so it would look like 
```
type ClientSpec struct {
	config.ComponentConfig `json:",inline"`
	AppDir                 string `json:"appdir,omitempty"`
	Version                string `json:"version,omitempty"`
	Project           string `json:"project,omitempty"`
	Email             string `json:"email,omitempty"`
	IpName            string `json:"ipName,omitempty"`
	Hostname          string `json:"hostname,omitempty"`
	Zone              string `json:"zone,omitempty"`
	UseBasicAuth      bool   `json:"useBasicAuth"`
	SkipInitProject   bool   `json:"skipInitProject,omitempty"`
}
```
and this would be passed to each KfApp. This means the KfApp Interface would now look like

```
type ResourceEnum string

const (
	ALL      ResourceEnum = "all"
	K8S      ResourceEnum = "k8s"
	PLATFORM ResourceEnum = "platform"
)
type KfApp interface {
	Apply(resources ResourceEnum, spec *client.Spec) error
	Delete(resources ResourceEnum, spec *client.Spec) error
	Generate(resources ResourceEnum, spec *client.Spec) error
	Init(resources ResourceEnum, spec *client.Spec) error
}
```

"Spec" is now mutable and needs to be saved after each coordinator call to the platform and package managers. If we're not saving in "app.yaml" and using kustomize we need to decide what kustomize pattern we use in order to save this information.

**Comment by kunmingg** [comment]
How about
```
type KfApp interface {
	Apply(resources ResourceEnum, spec *client.ApplySpec) error
	Delete(resources ResourceEnum, spec *client.DeleteSpec) error
	Generate(resources ResourceEnum, spec *client.GenerateSpec) error
	Init(resources ResourceEnum, spec *client.InitSpec) error
}
```
```ApplySpec DeleteSpec GenerateSpec InitSpec``` are directly from user input and their fields are exclusive?

I feel it could be danger to allow edit "app.yaml" (ClientSpec) between steps as eg. user can change project after init, break consistency among actions.

**Comment by jlewi** [comment]
Do we have a short term fix?

Some high level thoughts

- apply should not take config parameters
   - the goal is to be entirely declarative
   - by the time we call apply all parameters should be specified in the underlying config calls

- the point of init/generate is to create default config files

- after init/generate are called users should modify the underlying config files to change config

- Parameters that affect config generation should arguably be specified during generate and not during init

   * e.g. `use_basic_auth` controls which components should be created and how they get configured
   * This could lead to problems if certain features like affect both platform and K8s resources
      
      * In this case when we call `kfctl generate platform` and `kfctl generate k8s`  both invocations would need to know the value of the config option 
  
      * Is this what's happening in the case of use-basic-auth?

- Should we just try to be clear that init parameters are intended to be one time only
  * i.e. they only matter when you call generate
  * If you want to rerun generate and apply any changes to the init parameters; we do this by delete all the config files and regenerating them.

**Comment by lluunn** [comment]
> ApplySpec DeleteSpec GenerateSpec InitSpec are directly from user input and their fields are exclusive?

@kunmingg the problem is some fields are needed in both generate and apply, like UseIstio, generated component will have different param, and apply will need to install istio first.

> - apply should not take config parameters

agree

> - after init/generate are called users should modify the underlying config files to change config
@jlewi but what if users want to change things like, UseBasicAuth? This will need different components and doesn't seem it's doable by directly modifying things.

> - Parameters that affect config generation should arguably be specified during generate and not during init

agree. Most of the param should be passed during generate. init should only take project, skip-init-project (anything else?)

**Comment by kkasravi** [comment]
There is a short term fix which I can open a PR for. @lluunn is there an issue open?

We could better align the flags with init and generate, I think that makes sense. We should also allow multiple generate calls perhaps with a —force flag so the user is aware that they are replacing the last generate.

**Comment by lluunn** [comment]
you mean PR? I haven't opened any PR for this issue.
What's the short term fix?

**Comment by kkasravi** [comment]
@kunming Also —platform, —version, —repo?

**Comment by kkasravi** [comment]
@kunming, I’ll make a pass on the different Specs and post here for feedback or point you to the code in the PR

**Comment by kkasravi** [comment]
@lluunn 
> you mean PR? I haven't opened any PR for this issue.
> What's the short term fix?

The extra components and componentParams set in GCP need to be made available to the package managers. For basic auth - the basic-auth-ingress component needs to be added to the components so ksonnet can see it. This was being done when GCP managed / called Ksonnet but 
was dropped on the merge when coordinator was introduced. I'll make this change (along with adding other gcp components to the component list like cert-manager) asap.
