### ISSUE TITLE
Add LICENSE file: Apache License, Version 2.0

### ISSUE THREAD

**Issue by dmueller2001** [kubeflow/kubeflow#27]
https://github.com/google/addlicense

**Comment by geojaz** [comment]
addressed in #29

**Comment by jlewi** [comment]
Reopening per@dmueller2001's [comment](https://github.com/google/kubeflow/pull/29#issuecomment-352473260).

> 

The license still has boilerplate details that need to be a completed.

Copyright [yyyy] [name of copyright owner]

**Comment by jlewi** [comment]
@vishh  Do you mind if I assign this to you since you submitted the first fix?

**Comment by mindprince** [comment]
https://github.com/google/kubeflow/pull/29#issuecomment-352502231
We can close this.
