### ISSUE TITLE
Ship v0.5.0 release

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2716]
Track todos here and ship release v0.5.0
Todos:
- [x] https://github.com/kubeflow/kubeflow/issues/1859
- [x] https://github.com/kubeflow/kubeflow/issues/2588
- [x] https://github.com/kubeflow/kubeflow/issues/2723
- [x] https://github.com/kubeflow/kubeflow/issues/2641
- [x] https://github.com/kubeflow/kubeflow/pull/2733

TFJob blockers:
- [x] https://github.com/kubeflow/tf-operator/issues/550
- [x] https://github.com/kubeflow/tf-operator/issues/916
- [x] https://github.com/kubeflow/tf-operator/issues/929

Pytorch blockers:
- [x] https://github.com/kubeflow/pytorch-operator/issues/134

Update release images:

- [x] tf-operator
- [x] pytorch-operator
- [x] katib
- [x] jupyter images
- [x] dashboard

Release branch:
- [x] Cut release branch
- [ ] e2e release demo test on release branch 

Update Docs

- [ ] Update the changelog by running [update_changelog](https://github.com/kubeflow/kubeflow/blob/76107ff3aa7f9fde6fd7f15f2ec0a69a35874efa/scripts/update-changelog.sh)

Cherrypick:
- [x] #2778 
- [x] #2853 
- [x] #2875

Other
- [ ] kfctl pin to 0.5 version when it's ready.
- [ ] fix `kfctl version`

**Comment by lluunn** [comment]
I will cut the first RC early next week

**Comment by richardsliu** [comment]
Need to update release images for:
- tf-operator
- pytorch-operator
- katib
- jupyter images
- dashboard

**Comment by kunmingg** [comment]
One more pending:
* Switch default to new notebook UI + controller before release cut
@zabbasi

**Comment by lluunn** [comment]
notebook CR status:
https://github.com/kubeflow/kubeflow/issues/2588
https://github.com/kubeflow/kubeflow/issues/2723

@vkoukis @kimwnasptd

**Comment by avdaredevil** [comment]
This PR:
#2733

**Comment by lluunn** [comment]
admission webhook: https://github.com/kubeflow/kubeflow/issues/2641

**Comment by mvartakAtVerta** [comment]
ModelDB V2 integration: #2748

**Comment by IronPan** [comment]
One todo for Pipeline: https://github.com/kubeflow/kubeflow/issues/2754

**Comment by gabrielwen** [comment]
#2750

**Comment by lluunn** [comment]
Created RC0.

TODO:
- update notebook for credential: #2770 
- notebook webapp show status #2588 
- http://bit.ly/05_mid_release_demo demo test

**Comment by gabrielwen** [comment]
Please cherrypick the following PRs (checked means it's merged)
- [ ] #2854 
- [ ] #2838 
- [x] #2873

**Comment by lluunn** [comment]
admission webhook fix: #2893

**Comment by lluunn** [comment]
notebook ui fix: #2848

**Comment by lluunn** [comment]
update notebook controller image: #2895

**Comment by lluunn** [comment]
cherrypick:
-[ ] notebook image update #2902

**Comment by gabrielwen** [comment]
cherrypick:
- [ ] List endpoints when delete is failed #2912

**Comment by gabrielwen** [comment]
cherrypick:
- [ ] Extract exact backend service name #2938

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/pull/2946
