### ISSUE TITLE
kfctl use case: deploy a component from within a container

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2724]
the OpenVINO use case in kubeflow pipelines needs to deploy a serving component after training is completed using parameters from the training phase. The approach is to launch a job that deploys a kfctl container with the required parameters as args. The kfctl cli will then deploy a single component, passing the args as that components arguments. 

Requirements
1) Create a docker container that runs kfctl with parameters passed via the command args or via the ENV
2) Use incluster-client-config similar to this [example](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration)

**Comment by kunmingg** [comment]
For single component, would it be easier to manage with CRD + controller?

**Comment by kkasravi** [comment]
@kunmingg probably. Though it looks like kubeflow/pipelines is doing something similar with [TF Serving](https://github.com/kubeflow/pipelines/blob/1045e023f32d2e99a0062c28980a9b847a40a679/components/kubeflow/deployer/src/deploy.sh) 

If we were to approach adding single components using a CRD + controller, would the controller be an [Application controller](https://docs.google.com/document/d/11vAkC25uNvm2z2smLUPmySZS16fjud6M2GFN6W-hYW8/edit#heading=h.ss1azctmy08s) which seems to handle new resources being [added](https://github.com/kubernetes-sigs/application/blob/master/pkg/genericreconciler/genericreconciler.go#L211)? I should probably add this use case to the Application CRD design doc if this is how we would add/remove/change single components. @kunmingg @lluunn Let me know your thoughts.

**Comment by lluunn** [comment]
Why do we need kfctl to deploy the component? Shouldn't we just generate the manifest(ks or kustomize) somehow?
Like using fairing?
@r2d4

**Comment by kkasravi** [comment]
@lluunn I'm not sure about fairing but this use case is a user deploying an additional component after kfctl apply - so the user probably won't have access to the kfctl environment and probably doesn't have privileges to the <kubeflow> namespace.

**Comment by kkasravi** [comment]
Jeremy has an umbrella issue on this i believe - https://github.com/kubeflow/pipelines/issues/677

**Comment by jlewi** [comment]
@kkasravi In the case of open vino and pipelines are you deploying a system component or are you deploying an instance?

I would kfctl to only be involved if you are deploying a system component; e.g. the controller for a custom resource but not the custom resource yourself.

For example, we use kfctl to deploy the Seldon controller but not to create individual SeldonDeployments.

Does OpenVino have shared components that are deployed as part of deploying kfctl?

If it does, to @lluunn's point, why wouldn't those components just be deployed via the system admin as part of deploying Kubeflow? Why would you deploy them from the pipeline?

In kubeflow/pipelines#677 we are using pipelines to create individual TFJob resources not to deploy the TFJob controller.

**Comment by kkasravi** [comment]
this is similar to TFServing, using [deploy.sh](https://github.com/kubeflow/pipelines/blob/1045e023f32d2e99a0062c28980a9b847a40a679/components/kubeflow/deployer/src/deploy.sh). A number of values are provided by the prior stage of the pipeline which is why it needs to launched within the pipeline. I don't think our RBAC model handles a use case where system components are added to the kubeflow namespace or even added to that user's profile namespace that can be viewed by others
