### ISSUE TITLE
kfctl presubmit test failure

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2725]
couldn't generate KfApp: coordinator Generate failed for ksonnet: couldn't initialize KfApi: there was a problem initializing the app: Could not create app; directory '/mnt/test
-data-volume/kubeflow-presubmit-kfctl-go-2655-ba9a167-6389-7998/kfctl-7998/ks_app' already exists

**Comment by lluunn** [comment]
Did you merge master?
I remember reviewed a PR from @gabrielwen to use MakeDirAll which should not have error if dir exist?

**Comment by kunmingg** [comment]
Just synced

**Comment by gabrielwen** [comment]
there is another failure:
```
Error: couldn't apply KfApp: coordinator Apply failed for gcp: gcp apply could not update deployment manager Error Error when running gcloud container clusters get-credentials: exit status 1
```
somehow it fails at `gcloud get-credentials`:
https://github.com/kubeflow/kubeflow/blob/28d9e09793bf52c9c396533ea226d97141effbf4/bootstrap/pkg/client/gcp/gcp.go#L510

**Comment by gabrielwen** [comment]
this seems wrong... `--project=kubeflow-ci-deployment`

**Comment by kunmingg** [comment]
@gabrielwen 
```kubeflow-ci-deployment``` is the sandbox project for kfctl tests.
https://github.com/kubeflow/kubeflow/issues/2610#issuecomment-473471641

**Comment by gabrielwen** [comment]
another error appears: `level=error msg="Deployment error: &{Code:RESOURCE_ERROR Location:/de
ployments/kfctl-cc4c/resources/kfctl-cc4c-ip Message:{\"ResourceType\":\"compute.v1.globalAddress\",\"ResourceErrorCode\":\"403\",\"Resou
rceErrorMessage\":{\"code\":403,\"errors\":[{\"domain\":\"usageLimits\",\"message\":\"Quota 'STATIC_ADDRESSES' exceeded. Limit: 21.0 glob
ally.\",\"reason\":\"quotaExceeded\"}],\"message\":\"Quota 'STATIC_ADDRESSES' exceeded. Limit: 21.0 globally.\",\"statusMessage\":\"Forbi
dden\",\"requestPath\":\"https://www.googleapis.com/compute/v1/projects/kubeflow-ci-deployment/global/addresses\",\"httpMethod\":\"POST\"
}} ForceSendFields:[] NullFields:[]}" filename="gcp/gcp.go:319`

**Comment by kunmingg** [comment]
@gabrielwen 
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py should help

**Comment by gabrielwen** [comment]
Now it's `The node was low on resource: nodefs`.

**Comment by gabrielwen** [comment]
thanks to @kunmingg , the test appears to be running as default service account and not having enough scope to run `gcloud get-credentials`, fixing it.

**Comment by gabrielwen** [comment]
now we have the following error: `could not create resources in rbac-setup.yaml exit status 1`

**Comment by kunmingg** [comment]
@gabrielwen 
One possible fix: https://github.com/kubeflow/kubeflow/pull/2742/files
testing

**Comment by gabrielwen** [comment]
@kunmingg 
I think it's because for rbac-setup you need to impersonate as admin: https://github.com/kubeflow/kubeflow/pull/2729/files

after impersonation I could pass that error and having another error, looking.

**Comment by kunmingg** [comment]
@gabrielwen 

Now https://github.com/kubeflow/kubeflow/pull/2742 has failure during apply:
```
level=error msg="(Will retry) Component metacontroller apply failed; Error: Attempting to deploy to environment 'default' at '127.0.0.1', but cannot l
ocate a server at that address" filename="ksonnet/ksonnet.go:228"
```

My guess is when run apply, somehow we use in-cluser kubeconfig (since kfctl is in a pod), so apply with point to cluster in kubeflow-ci which host kfctl, instead of kubeflow-ci-deployment

**Comment by gabrielwen** [comment]
@kunmingg 

Now #2729 passes kfctl_go_test and fails on kfctl_test.
