### ISSUE TITLE
ClusterRoleBindings creations are flowed in 0.4.1

### ISSUE THREAD

**Issue by llegolas** [kubeflow/kubeflow#2734]
clusterrolebindings across all components I've checked  are having default subjects which is breaking any previous deployments. Perhaps related to #374. It seem fix for ambassador has been accepted on March 12 2018 but i cannot see that in release 0.4.1

**Comment by jlewi** [comment]
Could you elaborate on what the problem is?
Are you saying the problem is fixed by #374 and is not in the 0.4 branch?

We are in the process of releasing 0.5 now; so you might want to just check if that release fixes your issues.

**Comment by llegolas** [comment]
#374 addresses (cluster)role binding only for ambassador. 
The same problem exists for some more components though. 
Most of the libsonnet files are having something similar to the below(example form argo):
```
    local argoClusterRoleBinding = {
      apiVersion: "rbac.authorization.k8s.io/v1beta1",
      kind: "ClusterRoleBinding",
      metadata: {
        labels: {
          app: "argo",
        },
        name: "argo",
      },
      roleRef: {
        apiGroup: "rbac.authorization.k8s.io",
        kind: "ClusterRole",
        name: "argo",
      },
      subjects: [
        {
          kind: "ServiceAccount",
          name: "argo",
          namespace: params.namespace,
        },
      ],
    },  // role binding
    argoClusterRoleBinding:: argoClusterRoleBinding,
```
Hard codding the subjects breaks any previous install of kubeflow at least with 0.4.1 release so effectively kubeflow is not multi-instance capable w/o manual fixing.
Among the components we are using and which are having the same behaviour in 0.4.1 are:
- ambassador
- argo
- metacontroller
- pipeline-apiserver
- pipeline-persistanceagent
- pipeline-scheduledworkflow
- studyjobcontroller
- vizier

If needed I can provide the exact line numbers

**Comment by llegolas** [comment]
I just checked the master branch if that is what is going to be 0.5.0.
Can't find real difference with 0.4.1 at least with the components I use:
- ambassador - still the same PR #408 is approved but seem not merged 
- argo - still the same + the argo cluster role needs workflows/finalizers resource, aready in upstream argo https://github.com/argoproj/argo/blob/master/manifests/install.yaml
- metacontroller - still the same
- pipeline (apiserver, persistenceagent, scheduledworkflow, spartakus,viewercrd) still the same
- katib (studyjobcontroller, vizier)

Scary lots of cluster-admin bindings too..
