### ISSUE TITLE
Is there a plan for Kubeflow to replace ksonnet with something else like helm?

### ISSUE THREAD

**Issue by rp4fx12** [kubeflow/kubeflow#2738]

**Comment by kkasravi** [comment]
We are replacing ksonnet with kustomize. kfctl has a plugin design, so additional package managers may also be considered and could be added between scheduled releases.

**Comment by govindKAG** [comment]
relevant issues page : https://github.com/kubeflow/kubeflow/issues/2412

**Comment by jlewi** [comment]
Duplicate of #2412
