### ISSUE TITLE
Kubeflow github onboarding experience

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#2741]
Kubeflow/Kubeflow repo is one of the starting point alongside with the website. 
Current user journey leads everyone straight to the website main page without consideration of the user's end goal. 
> As a person who would like to install and touch Kubeflow:

1. How do I install Kubeflow (locally, on cloud, on-prem)?
2. What capabilities does KF have?
3. What KF modules exist?
4. What modules are packaged in KF by default?
5. What KF modules will be installed by default?
6. Which modules do I install first?

> As a person who would like to learn more about Kubeflow usage

1. Is there any examples?
2. Is there any tutorials?
3. Is there any events?

> As a person who would like to contribute to Kubeflow:

1. Do I have enough expertise to contribute to Kubeflow?
2. How to find something to work on?
3. How to get KF membership?

> As a person who has something to say and would like to leave a feedback
1. What is the best place to leave a complaint/thankyou/proposal?

**This issue proposes to add following sections to Kubeflow Readme file to cover some of this questions and show most suitable direction to a person landed on this page.**

### Proposed sections
- [x] Product description section with link to the main website 
- [x] Start using Kubeflow section
  - [x] Links to getting started guideline documentation
  - [x] Links to examples
  - [x] Links to tutorials
  - [x] Links to events (?)
- [ ] Become Kubeflow contributor section
  - [x] Some buy-in description why it is cool to be KF contributor
  - [x] Link to the website page which contains all areas in which we need help and links with more details for each section
  - [ ] Community repository link to contributor rules, guideline, each module description
- [x] Leave your feedback section (Links to where people can leave their feedback, so we have one feedback storage)
- [ ] Info about the kubeflow repository itself
  - [ ] Link to the website with list of modules that Kubeflow contains and packages by default

**Comment by jlewi** [comment]
/assign @elviraux 

What is the priority of this issue?

**Comment by elviraux** [comment]
@jlewi medium priority as it affects only KF on-boarding experience whereas the project itself has more urgent things to be done.
why medium? because we started getting more kubeflow adopters and we should provide them a meaningful guidance, so they are able to serve themselves at least at the beginning.
This will lower an adoption barrier 
I've already started https://github.com/kubeflow/kubeflow/pull/2808

**Comment by elviraux** [comment]
@abhi-g @jlewi 
1. Do we need this links?
The argo one is broken
![image](https://user-images.githubusercontent.com/5718779/55427583-25145900-553c-11e9-8437-67fb65782e5a.png)

2. Can we add similar badges ?
![image](https://user-images.githubusercontent.com/5718779/55427726-7ae90100-553c-11e9-8da4-20408a2b4052.png)

**Comment by abhi-g** [comment]
On Tue, Apr 2, 2019 at 11:47 AM Elvira <notifications@github.com> wrote:

> @abhi-g <https://github.com/abhi-g> @jlewi <https://github.com/jlewi>
>
>    1.
>
>    Do we need this links?
>    The argo one is broken
>    [image: image]
>    <https://user-images.githubusercontent.com/5718779/55427583-25145900-553c-11e9-8437-67fb65782e5a.png>
>
> The links are actually quite useful for the Developers. If not I'd like
them to focus on these for checking tests status. Argo UI is not as useful
and doesn't load very well or times out.

**Comment by elviraux** [comment]
@abhi-g 
1. if argo UI is useless maybe I remove the link to it until it is stable/fixed?
2. Where can I get access to the explanation and PR guidance for repos that you were talking about today?
3. Could someone with write rights move the [form](https://bit.ly/2JF5Max) to KF team drive

**Comment by abhi-g** [comment]
@Elvira Fortune <elvirafortune@gmail.com> Sorry I am going to be slow to
respond to these. As I mentioned in the meeting today, my priority this
week is to get the release ready...

**Comment by elviraux** [comment]
@abhi-g that's fine, no point to rush on this. Just stating it here , so we don't forget later when we get more time
