### ISSUE TITLE
auto-deploy for v0.4 is failed.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2747]
auto-deploy for v0.4 is failed with the following error message: merging object with existing state: CustomResourceDefinition.apiextensions.k8s.io \"pytorchjobs.kubeflow.org\" is invalid: status.storedVersions[1]: Invalid value: \"v1beta2\": must appear in spec.versions"

Seems testing master code was not compatible with this release branch deploy

**Comment by kunmingg** [comment]
@gabrielwen

**Comment by jlewi** [comment]
Given our limited resources we might want to focus our efforts on v0.5 and master.
