### ISSUE TITLE
Integrate ModelDB V2

### ISSUE THREAD

**Issue by mvartakAtVerta** [kubeflow/kubeflow#2748]
ModelDB has been rewritten from the ground up to provide:
- flexible and extensible APIs
- durable storage
- Relational and non-relational DB backends
- re-vamped dashboards

This should be integrated into KubeFlow for release 0.5

**Comment by richardsliu** [comment]
@mvartakAtVerta Is this for katib? If so then we should not block 0.5 on this.

**Comment by mvartakAtVerta** [comment]
@richardsliu no, this is general purpose one (replacing V1). We are waiting for the new Katib API to stabilize before taking on ModeLDB integration

**Comment by richardsliu** [comment]
@mvartakAtVerta Is there already a PR for this?

**Comment by lluunn** [comment]
What are the things to be done?

**Comment by mvartakAtVerta** [comment]
PR here: only affects modeldb component: https://github.com/kubeflow/kubeflow/pull/2757

**Comment by richardsliu** [comment]
@mvartakAtVerta Thanks for the PR. However I don't believe this has to be in the 0.5 release (which is due in a week). This should be in 0.6 since it is feature work.

**Comment by mvartakAtVerta** [comment]
@richardsliu I'm not clear on this -- what's the issue in putting this in 0.5? (assuming the PR is ok?)

**Comment by richardsliu** [comment]
@mvartakAtVerta Is there any work left here or can this be closed? Looks like the PR is merged.

**Comment by mvartakAtVerta** [comment]
All set here.
ᐧ
