### ISSUE TITLE
Why my kubeflow worker replicas always assigned in the same node

### ISSUE THREAD

**Issue by DQinYuan** [kubeflow/kubeflow#2749]
this is my starting nodes use kubeflow, I start ten tasks including 9 worker replicas and 1 ps relica. but they are almost assigned in 3 nodes:

![stratInTheSameNode](https://user-images.githubusercontent.com/23725000/54711567-2f6e4480-4b85-11e9-931f-9b76d8f30efa.png)

In fact, i have 12 nodes in cluster:

![allNodes](https://user-images.githubusercontent.com/23725000/54711581-35fcbc00-4b85-11e9-9b6d-1f0584cd43b8.png)

how can i assign tasks more balance. What config to do?

**Comment by jlewi** [comment]
Kubeflow isn't involved in assigning jobs to nodes. The K8s master is responsible for scheduling nodes.
K8s has a bunch of features like affinity and node selector to control how pods get scheduled.

I would recommend looking at the K8s documention to try to figure out why the pods are always getting scheduled on the same node.
