### ISSUE TITLE
Update Argo to later version.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#2753]
There were many Argo fixes in the last half a year.
It would be great to catch up on them.
Unfortunately, Argo hasn't had any official releases since October. But maybe we can think of something and still update it. https://github.com/argoproj/argo/issues/1212

**Comment by xianlubird** [comment]
@jessesuen @Ark-kun @sarabala1979 
Because you are busy,  can we organise  a virtual team to help release v2.3.
Maybe we can work through slack or mail list.  
@jessesuen can you select a leader and we can work together to release.

**Comment by jlewi** [comment]
@vicaire Can someone on pipelines pick this up if it is critical to you?

/cc @jessesuen

**Comment by vicaire** [comment]
Ark-kun@, could you please have a look?

**Comment by Ark-kun** [comment]
Argo has been upgraded to v2.3.0
