### ISSUE TITLE
Verify the pipeline upgrade capability works with deployment binary and click-to-deploy UI

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2754]
The pipeline upgrade capability is documented here
https://www.kubeflow.org/docs/pipelines/upgrade/

Need to verify the function works smoothly with the new go binary, and update the document since it's still pointing to the kfctl.sh script.

**Comment by IronPan** [comment]
It looks like the -storage DM entry is not created using 
https://deploy-staging.kubeflow.cloud/#/deploy?version=e90237057f3a9d3544917a703f83ca162e90a074

**Comment by IronPan** [comment]
verified and it's working as expected. We need to make sure the click-to-deploy UI have permanent storage option selected by default.

**Comment by IronPan** [comment]
@kunmingg could you help with this? Then we can close this issue.

**Comment by jlewi** [comment]
@IronPan @kunmingg Can we close this?
