### ISSUE TITLE
Central Dashboard - Provide a not found view for links that aren't valid

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#2759]
Current behavior allows a user to directly navigate to a path like `/bad-page` and still see the home page content.

This should be amended to provide some view indicating that the path is not a valid path. This can be addressed by updating the `_routePageChanged` method in the `main-page` component.

**Comment by avdaredevil** [comment]
This is affecting our users already. Can we prioritize this @prodonjs?

This also leads to iframe-inception behavior like:
![image](https://user-images.githubusercontent.com/5303018/54788605-dafeaf80-4bec-11e9-95cd-445a9e26e941.png)

---
cc: @mpvartak 

/area front-end
/priority p0

**Comment by prodonjs** [comment]
I can have it tomorrow morning. Out of curiosity, the screenshot you
provided is from the local dev server right? That type of behavior
shouldn't be possible in-cluster today.

**Comment by mpvartak** [comment]
I had to port-forward to the centraldashboard pod (on GKE) because the ingress wouldn't get provisioned fast enough
