### ISSUE TITLE
kfctl-go e2e test failure

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2760]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2756/kubeflow-presubmit/6480/

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2743/kubeflow-presubmit/6483/

both from PR unrelated to kfctl, failed at `kfctl apply`

@gabrielwen @kunmingg

**Comment by lluunn** [comment]
from stackdriver logs

couldn't apply KfApp: coordinator Apply failed for gcp: gcp apply could not update deployment manager Error could not update cluster-kubeflow.yaml: Deployment error(400): BAD REQUEST

**Comment by lluunn** [comment]
For http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kfctl-go-2756-d0ec554-6496-e376?tab=workflow, the error is

```
could not download repo to cache Error couldn't create directory /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2756-d0ec554-6496-e376/kfctl-e376/.cache Error mkdir /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2756-d0ec554-6496-e376/kfctl-e376/.cache: file exists" filename="coordinator/coordinator.go:230"
```

**Comment by gabrielwen** [comment]
I have another error:
```
Error: couldn't apply KfApp: coordinator Apply failed for gcp: gcp apply could not update deployment manager Error could not update cluster
-kubeflow.yaml: Unable to read YAML: error converting YAML to JSON: yaml: line 91: did not find expected key
```

**Comment by lluunn** [comment]
I am still see error in my PR (#2781 )

```
Error: couldn't apply KfApp: coordinator Apply failed for gcp: gcp apply could not update deployment manager Error could not update cluster-kubeflow.yaml: Creating kfctl-3a67 error: Get https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-deployment/global/operations/...  read: connection reset by peer
```

**Comment by lluunn** [comment]
https://pantheon.corp.google.com/logs/viewer?organizationId=714441643818&project=kubeflow-ci&minLogLevel=0&expandAll=false&timestamp=2019-03-25T21:53:42.336000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-03-25T20:54:04.079Z&dateRangeEnd=2019-03-25T21:54:04.079Z&interval=PT1H&resource=k8s_container&folder=&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22kubeflow-presubmit-kfctl-go-2781-9382277-6671-3a67-309633560%22&scrollTimestamp=2019-03-25T21:34:32.000000000Z

**Comment by lluunn** [comment]
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kfctl-go-2781-14cbe6d-6723-86d3?tab=workflow

**Comment by gabrielwen** [comment]
`Invalid value: \"kubeflow-presubmit-kfctl-go-2815-0a9c930-1110636007134334976-0ae6\": must be no more than 63 characters`

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2815/kubeflow-presubmit/1110636007134334976/

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/pull/2781#issuecomment-477318612

error when applying metacontroller

**Comment by jlewi** [comment]
Connection reset by peer is #2804 
#2824 is tracking adding retries around DM calls.

The error about the name being too long looks like the problem with prow changing the build id.

I'm closing this issue since we have the above issues.

Lets open specific issues as needed for ongoing test failures.
