### ISSUE TITLE
make basic auth works with Istio

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2766]
Currently only iap part has changes for using istio

**Comment by gabrielwen** [comment]
@kunmingg should we close this?  currently basic auth could work with ISTIO.  Should we close it or should we wait until basic auth doesn't need ambassador?

**Comment by kunmingg** [comment]
@gabrielwen 
Does basic auth work with ISTIO on master head now?
Can you share the command?

**Comment by gabrielwen** [comment]
I think what I did is:
`kfctl init basic-auth-testing --platform gcp --project gabrielwen-learning -V --skip-init-gcp-project --use_istio --use_basic_auth`
`kfctl generate all -V`
`kfctl apply all -V`

**Comment by jlewi** [comment]
@gabrielwen @kunmingg  Can we update the E2E test that is using basic auth to use ISTIO? If that test passes then we know basic auth is working with ISTIO right?

**Comment by jlewi** [comment]
Here's a passing postsubmit for basic auth;
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1135679782407639040

Is this not using ISTIO?

**Comment by gabrielwen** [comment]
No, it's not currently:
https://github.com/kubeflow/kubeflow/blob/4fda196a8a6cb59ec6ada75952b4762e51fcd1af/prow_config.yaml#L65

**Comment by gabrielwen** [comment]
basic auth is broken for this:
https://github.com/kubeflow/kubeflow/blob/b989f84457ec88aaa543a21e864060ea74c71536/kubeflow/gcp/update_backend.sh#L18

port name for ISTIO is indeed `http2`, but for ambassador is `ambassador`.  fixing it.

**Comment by gabrielwen** [comment]
After #3404 we also need to migrate the changes to kustomize.

@lluunn

**Comment by jlewi** [comment]
Do we have an E2E test that we can use for basic-auth + ISTIO + kustomize?

**Comment by lluunn** [comment]
With https://github.com/kubeflow/kubeflow/pull/3404, we have basic auth + istio. But it's not using kustomize yet i think.

**Comment by jlewi** [comment]
Thanks @lluunn . Lets update the test to use auth+istio+kustomize and close this issue when it passes.

**Comment by lluunn** [comment]
I think we need to port the change of update_backend.sh, setup_backend.sh in https://github.com/kubeflow/kubeflow/pull/3404 to kustomize manifest
https://github.com/kubeflow/manifests/blob/master/gcp/iap-ingress/base/config-map.yaml
