### ISSUE TITLE
ERROR net/http: request canceled (Client.Timeout exceeded while reading body)

### ISSUE THREAD

**Issue by Niuxiaotong** [kubeflow/kubeflow#2799]
### Cenos7.6(x86_64)
# k8s：1.12.1
### https://www.kubeflow.org/docs/started/getting-started/_

[root@k8s01 ~]# ls
anaconda-ks.cfg  bin  kfapp01  kubeadm.yaml  kubeflowsrc
[root@k8s01 ~]# ../kubeflowsrc/scripts/kfctl.sh generate k8s
--
INFO Creating environment "default" with namespace "default", pointing to "version:v1.12.1" cluster at address "https://10.18.96.6:6443" 
 ERROR net/http: request canceled (Client.Timeout exceeded while reading body)
To undo this simply delete directory 'ks_app' and re-run `ks init`.
--
run commod again ,appear the same Erro.
please help me .thanks~~

**Comment by pdmack** [comment]
Sounds like you can't reach that API server. Are the kubelet/kube-apiserver processes up and healthy on that host? Is that the correct kube context you want to use?

**Comment by Niuxiaotong** [comment]
> Sounds like you can't reach that API server. Are the kubelet/kube-apiserver processes up and healthy on that host? Is that the correct kube context you want to use?
kubelet/kube-apiserver processes up and healthy on；
kube context？i am not sure.
the erro in my question may be caused by pod-network(eg,flannel )，but i can not slove it

**Comment by SunFromEast** [comment]
maybe the network probelm , the network is unstable,  I have inferenced [aliyun](https://yq.aliyun.com/articles/686672?spm=a2c4e.11153940.blogcont600601.58.4f4b1e99V8DePE) and you can also have a try

**Comment by Niuxiaotong** [comment]
kubeadm drain <node name>...
kubeamd delete node <node name>
kubeadm reset 
after those operation,start again to deploy kubeflow
the question about “../kubeflowsrc/scripts/kfctl.sh generate k8s”“is gone
but appear simliar erro:
../kubeflowsrc/scripts/kfctl.sh apply k8s
INFO Creating environment "default" with namespace "default", pointing to "version:v1.12.1" cluster at address "https://10.18.26.119:6443"
ERROR net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by GeorgeGeng** [comment]
你先确定下自己的kubelet有没有问题，我刚刚也遇到了这个问题，看了下是kubelet没起来，原因是k8s和docker的文件驱动不一样（failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"），修改其中一个，重启kubelet。

**Comment by BabycolaYang** [comment]
@Niuxiaotong i got the same issue ,did you solve it?

**Comment by Niuxiaotong** [comment]
> @Niuxiaotong i got the same issue ,did you solve it?

it^s so long time, i am no sure if I note it, but I will found it recently;
