### ISSUE TITLE
spark E2E test is failing; generate fails no prototype

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2811]
Here's a presubmit run.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/2787/kubeflow-presubmit/6705/

E2E test to generate spark fails with 

```
"no prototype names matched 'spark-operator'"
```

**Comment by jlewi** [comment]
Installing the pkg succeeds so I'm not sure why generate fails.

**Comment by jlewi** [comment]
It passed in the most recent periodic run:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-master/1016

Not sure why its failing in presubmits.

**Comment by lluunn** [comment]
also in https://github.com/kubeflow/kubeflow/pull/2781
