### ISSUE TITLE
[Discussion] Where should kfctl go code live? New repository?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2812]
The code for kfctl is currently in the bootstrap directory
https://github.com/kubeflow/kubeflow/tree/master/bootstrap

We also have the kfctl code directory
https://github.com/kubeflow/kubeflow/tree/master/kfctl

I believe the intent was to eventually move the code into the kfctl directory or simply rename the bootstrap directory. We've postponed doing that though because this will be a disruptive change.

If we're going to move the code should we also move it to a new repo?

If we move it a new repo what else should go in that repo?

  * Should we move the click to deploy app into that repo as well?

/cc @kunmingg @gabrielwen @kkasravi @ashahba

**Comment by kkasravi** [comment]
We could have clients in this repo, not sure about arena though

**Comment by jlewi** [comment]
What is clients in this case? Do you mean plugins for specific platforms?
