### ISSUE TITLE
kfctl presubmits don't need to run component tests 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2830]
Right now the kfctl E2E test does the following

1. Deploy Kubeflow
1. Verify different components work by exercising them
    * e.g. submitting TFJobs, deploying TFServing models, running Katib study jobs etc...

The second step is a major source of test flakes that is a major headache for kfctl development. This pain will only increase as the number of components increases. 
    * If the number of components increases linearly, we need to increase reliability exponentially in order to keep the rate of test failures constant.

The presubmits are really testing two things right now
  1. kfctl creates the expected resources
  1. The application specs (e.g. ksonnet package TFJob controller) create the necessary resources

I think we want to decouple these goals into separate more focused tests.

When testing changes to kfctl we only need to verify that the expected resources are created. For example, It should be sufficient to check that various controllers are started and reported as healthy. Running application specific E2E tests (e.g. submitting a study job) should be unnecessary.

We only need to run E2E tests for each application to verify that we ensure resource creation for each application is correct. For example, when changing the ksonnet package for the TFJob controller we want to verify the proper set of RBAC roles is created to enable successful operation. Running an actual TFJob is a good way to verify that.

I think we should split out the E2E tests for each application so that we can trigger them only when the corresponding package is modified.

Here's how we might proceed

* The new E2E tests for the kfctl go binary are not running any application specific tests so there's no work to be done there.
* We should update the kfctl.sh E2E test to stop running application specific tests.
* We should split up the existing component tests into individual tests that can be triggered selectively based on the corresponding package being modified.

**Comment by kkasravi** [comment]
it's too bad we can't use kfctl with prow related components (ie bootstrap/config/kfctl_testing.yaml to deploy a test environment.

**Comment by jlewi** [comment]
@kkasravi Isn't that what we are doing? What are we missing?
