### ISSUE TITLE
kfctl should support pulling config from a local directory and more general git syntax

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2831]
kfctl downloads the configuration here:
https://github.com/kubeflow/kubeflow/blob/cee0f6e3f84e01009abef3b81db65c6e3f36d91a/bootstrap/pkg/kfapp/coordinator/coordinator.go#L89

It currently assumes we are pulling the config from a git repo. 

We should support copying the repo from a directory. This way its easy to test local changes.

My suggestion would be to allow the version flag to be a uri. We could then do something like

```
--version=file://
```

The code can then determine how to download the files correctly based on the URI

/cc @kkasravi @gabrielwen

**Comment by jlewi** [comment]
Related the git syntax makes assumptions about the repository

```
  -v, --version string          desired version of Kubeflow or master if not specified. Version can be master (eg --version master) or a git tag (eg --version=v0.5.0), or a PR (eg --version pull/<id>). (default "master")
```

So when you do "pull/<id>" its assuming repository is "kubeflow".

Is there a convenient way to support URIs?

For reference here's the syntax github recommends for checking out PRs

```
git checkout -b kubeflow-bot-update_jupyter_625e24e master
git pull https://github.com/kubeflow-bot/kubeflow.git update_jupyter_625e24e
```

We also have [checkout_repos.sh](https://github.com/kubeflow/testing/blob/master/images/checkout_repos.sh)

Which uses

```
{REPO_ORG}/{REPO_NAME}@{SHA}:{PULL_NUMBER}
```

So it makes an assumption that it is github.

**Comment by jlewi** [comment]
@kkasravi Do we support local repos yet? Do our presubmit tests just rely on pulling from git via the PR?

Should we punt to 0.7?

**Comment by jlewi** [comment]
#3468 add --config file added some support for pulling from a local file. Repo paths are using hashi-corps go-getter which also supports local file.
https://github.com/hashicorp/go-getter

We should probably be consistent.

GoGetter's getAny method supports a ref keyword.
https://github.com/hashicorp/go-getter#git-git

We can use this with GitHub refs
https://help.github.com/en/articles/checking-out-pull-requests-locally

**Comment by jlewi** [comment]
You can test it out with go-getter's command line string.
https://github.com/hashicorp/go-getter/blob/master/README.md#installation-and-usage

**Comment by yanniszark** [comment]
@jlewi I like this a lot!
Anything that pulls things from URIs should use the same tool.
`go-getter` seems like a great choice also for `--config`.

Back to the issue, this seems related to the way we represent what repository to download.
https://github.com/kubeflow/kubeflow/issues/3471

How about we do something like:
1. Make a new `repos` field, which include `name: <>, repo: <>` entries (or maybe it should be strongly typed?)
2. Add logic inside the --config code path to handle the repo values and download to cache, using go-getter.
3. The supported URIs for repo are everything that go-getter supports.

**Comment by jlewi** [comment]
This should be fixed on master.

We can now supply a --config file which points to a yaml file containing KfDef. We use go-getter to fetch this so we can use any URL go-getter understands.

KfDef now allows you to specify one or more repos to fetch each of which can be defined by a URL that will be fetched by go-getter.
