### ISSUE TITLE
Make sure error messages appear where the user expects them in the Jupyter spawner UI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2834]
Steps to reproduce

1. Go to the notebook manager UI and click "+" to spawn a notebook
1. Fill out the form with an invalid name e.g. a notebook name with spaces
1. Click spawn

An error in this case pops up but it shows up at the top of the page. See screenshot below.

The problem is if the top of the page is above the fold (e.g. user is on a laptop) then the error isn't obvious to the user. it just looks like the user clicked spawn and nothing happened.

![error](https://user-images.githubusercontent.com/777219/55095593-a15af800-5075-11e9-941e-5116e6a721d4.png)

/cc @avdaredevil @kimwnasptd @vkoukis

**Comment by vkoukis** [comment]
ACK, shall we change the description to `Make sure error messages appear where the user expects them in the Jupyter spawner UI`?

My initial reaction to seeing the notification was "😱 , an API call fails and we don't show the error message", which thankfully is not the case here. We do show the error message, but it is indeed quite easy to miss, and we should make it more obvious.
