### ISSUE TITLE
kfctl - running generate twice will result in a malformed gcp_config/cluster-kubeflow.yaml if platform=gcp

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2842]
steps

1. kfctl init kubeflow-testing --namespace kubeflow-test-infra --project $PROJECT --platform gcp
2. kfctl generate all -V --email kam.d.kasravi@intel.com
3. kfctl generate all -V --email kam.d.kasravi@intel.com

The file gcp_config/cluster-kubeflow.yaml has an extra line in it

```
    # This is the name of the GCP static ip address reserved for your domain.
    # Each Kubeflow deployment in your project should use one unique ipName among all configs.
    ipName: kubeflow-testing-ip
pName: kubeflow-testing-ip
````

**Comment by jlewi** [comment]
@kkasravi Is this still an issue? Should we punt it to 0.7?

**Comment by jlewi** [comment]
kfctl has changed significantly since this bug was originally filed so I'm going to close it as obsolete.
