### ISSUE TITLE
Cannot pip install 'seaborn' or 'imbalanced-learn' packages in Jupyter notebook in Kubeflow UI

### ISSUE THREAD

**Issue by mjgrav2001** [kubeflow/kubeflow#2843]
@ankushagarwal Hi. I also am trying to pip install two packages (seaborn, imblearn) on a jupyter notebook in kubeflow (trying to create a pipeline for a workflow). I tried several different alternatives considering the Python environment in which the packages might be installed, but those two packages do not appear when I run a 'pip list' no matter what I do. I use the Python3 kernel for the notebook. Here are my steps:

Executing this in the notebook,

!import sys
!print(sys.executable)
!print(sys.path),

yields as output:

/opt/conda/bin/python
['/opt/conda/lib/python36.zip', '/opt/conda/lib/python3.6', '/opt/conda/lib/python3.6/lib-dynload', '', '/home/jovyan/.local/lib/python3.6/site-packages', '/opt/conda/lib/python3.6/site-packages', '/opt/conda/lib/python3.6/site-packages/IPython/extensions', '/home/jovyan/.ipython']

I then try to install different packages for example with these commands:

!{sys.executable} -m pip install --user tensorflow
!{sys.executable} -m pip install --user numpy
!{sys.executable} -m pip install --user scipy
!{sys.executable} -m pip install --user sklearn
!{sys.executable} -m pip install --user pandas
!{sys.executable} -m pip install --user pandas-gbq
!{sys.executable} -m pip install --user xlrd
!{sys.executable} -m pip install --user matplotlib
!{sys.executable} -m pip install --user seaborn
!{sys.executable} -m pip install --user imbalanced-learn

(I also tried

%%bash
python3 -m pip install --user tensorflow numpy scipy sklearn pandas pandas-gbq xlrd matplotlib seaborn imbalanced-learn

but to the same effect in the end, seaborn and imblearn do not appear in the pip list.)

When I execute '!pip list -o --format columns' in the notebook, neither 'seaborn' or 'imblearn' (i.e. package 'imbalanced-learn') appear in the listing:

Package Version Latest Type

absl-py 0.6.1 0.7.1 sdist
apache-beam 2.8.0 2.11.0 wheel
bleach 3.0.2 3.1.0 wheel
cachetools 3.0.0 3.1.0 wheel
certifi 2018.11.29 2019.3.9 wheel
configparser 3.5.0 3.7.3 wheel
decorator 4.3.0 4.4.0 wheel
dill 0.2.8.2 0.2.9 sdist
entrypoints 0.2.3 0.3 wheel
fastavro 0.21.15 0.21.19 wheel
gast 0.2.0 0.2.2 sdist
gevent 1.3.7 1.4.0 wheel
google-api-core 1.6.0 1.8.1 wheel
google-api-python-client 1.7.6 1.7.8 sdist
google-apitools 0.5.20 0.5.26 wheel
google-auth 1.6.1 1.6.3 wheel
google-cloud-bigquery 1.8.0 1.10.0 wheel
google-cloud-core 0.29.0 0.29.1 wheel
google-cloud-pubsub 0.26.0 0.40.0 wheel
google-gax 0.15.16 0.16.0 wheel
google-resumable-media 0.3.1 0.3.2 wheel
googleapis-common-protos 1.5.5 1.5.8 sdist
googledatastore 7.0.1 7.1.0 sdist
grpc-google-iam-v1 0.11.1 0.11.4 sdist
grpcio 1.17.0 1.19.0 wheel
gym 0.10.9 0.12.0 sdist
h5py 2.8.0 2.9.0 wheel
httplib2 0.11.3 0.12.1 sdist
jsonschema 2.6.0 3.0.1 wheel
Keras-Applications 1.0.6 1.0.7 wheel
Keras-Preprocessing 1.0.5 1.0.9 wheel
MarkupSafe 1.1.0 1.1.1 wheel
matplotlib 2.2.3 2.2.4 wheel
nbconvert 5.4.0 5.4.1 wheel
notebook 5.7.2 5.7.6 wheel
numpy 1.14.5 1.16.2 wheel
oauthlib 2.1.0 3.0.1 wheel
pandas 0.23.4 0.24.2 wheel
pandas-gbq 0.8.0 0.9.0 wheel
pbr 5.1.1 5.1.3 wheel
pip 18.1 19.0.3 wheel
ply 3.8 3.11 wheel
prometheus-client 0.5.0 0.6.0 sdist
prompt-toolkit 1.0.15 2.0.9 wheel
protobuf 3.6.1 3.7.0 wheel
pyasn1 0.4.4 0.4.5 wheel
pyasn1-modules 0.2.2 0.2.4 wheel
pydot 1.2.4 1.4.1 wheel
Pygments 2.3.0 2.3.1 wheel
pyparsing 2.3.0 2.3.1 wheel
python-dateutil 2.7.5 2.8.0 wheel
pytz 2018.4 2018.9 wheel
PyYAML 3.13 5.1 sdist
pyzmq 17.1.2 18.0.1 wheel
requests-oauthlib 1.0.0 1.2.0 wheel
scandir 1.9.0 1.10.0 sdist
scikit-learn 0.20.1 0.20.3 wheel
scipy 1.1.0 1.2.1 wheel
setuptools 39.1.0 40.8.0 wheel
tensor2tensor 1.11.0 1.13.1 wheel
tensorboard 1.10.0 1.13.1 wheel
tensorflow 1.10.1 1.13.1 wheel
tensorflow-data-validation 0.9.0 0.13.1 wheel
tensorflow-metadata 0.9.0 0.13.0 wheel
tensorflow-model-analysis 0.9.2 0.13.0 wheel
tensorflow-probability 0.5.0 0.6.0 wheel
tensorflow-serving-api 1.12.0 1.13.0 wheel
tensorflow-transform 0.11.0 0.13.0 sdist
tqdm 4.28.1 4.31.1 wheel
Werkzeug 0.14.1 0.15.1 wheel
wheel 0.32.3 0.33.1 wheel
wrapt 1.10.11 1.11.1 sdist

When I compile the kubeflow pipeline of this jupyter notebook and look at the execution in the experiment, it returns an error in each case (after commenting out appropriate sections in the code), 'seaborn not found' or 'imblearn not found', respectively. (Using 'conda install' of course did not resolve the issue either.)

Has there been a general resolution for this type of situation? Thank you for your feedback! Mark Jack

**Comment by jlewi** [comment]
This seems like an issue with conda. 
See this issue
https://github.com/kubeflow/kubeflow/issues/1803#issuecomment-430410311

One option is to build your own Jupyter image and not use conda.

Here's instructions for creating a 0.5 compatible Jupyter image
https://www.kubeflow.org/docs/components/jupyter/#creating-a-custom-jupyter-image

/cc @pdmack
