### ISSUE TITLE
Generalize the admission webhook to set environment variables and secrets based on config file

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2844]
The admission webhook 
https://github.com/kubeflow/kubeflow/blob/master/components/gcp-admission-webhook/main.go

Right now hardcodes the environment variables and secrets to mount.
https://github.com/kubeflow/kubeflow/blob/c5977793d5615e4ff867d5f0853e26a1201deb13/components/gcp-admission-webhook/main.go#L51

Can we make this configurable? e.g. make it easy for users to provide a spec describing the environment variables and secrets to mount?

Can we do something like PodPreset?
https://kubernetes.io/docs/tasks/inject-data-application/podpreset/

A simple thing would be to make the web-hook configurable via a YAML file provided via config map.

/cc @eLco @lluunn

**Comment by jlewi** [comment]
@zabbasi How's this coming?

**Comment by zabbasi** [comment]
> @zabbasi How's this coming?

Addressed in #3064. Currently integrated existing podpreset solution to kubeflow webhook component and made it working. Working this week to customize it to our requirements (e.g., set podpresets scope to namespace , add serviceaccount)
