### ISSUE TITLE
Does kubeflow actually work outside the google cloud already?

### ISSUE THREAD

**Issue by wzrdtales** [kubeflow/kubeflow#2846]
Really simple question, since I am currently evaluating kubeflow and was testing it on some private infrastructure (on premise, no cloud involved). So the question after the installation which directly evolved was: Is it working?

Indeed there is no clear way to actually check this, while digging through the docs I did not find anything useful to proof function of all the components. Indeed only the basic samples work, everything else just do not work at all. For example the `ML samples` XG Boost and the TFX sample don't work. They don't move above the first step of their job and do just plain nothing (also no error logs are being shown).  See screenshot below.

Next I tried this sample in the hope that the preinstalled samples are just malfunctioning
https://github.com/kubeflow/pipelines/tree/master/samples/kubeflow-tf

Same story, same ending. So I decided to stop evaluating kubeflow and come here to directly ask if it is actually usable anywhere else than the google cloud yet and if yes where and where I can get the informations around this topic.

Thank you in advance for your answer!

![image](https://user-images.githubusercontent.com/1786821/55170614-2843c980-5177-11e9-8c07-efeae0596ed6.png)

**Comment by jlewi** [comment]
Yes. Kubeflow works outside GCP. Lots of people are running Kubeflow successfully on other clouds or on prem.

Complex samples are often reading from specific data stores that are cloud specific. I think the TFX samples are using data on GCS or BigQuery.

If you provide more information on what you are trying to do we can probably point you in the right direction.

**Comment by wzrdtales** [comment]
Thanks for your reply!

Currently I am looking for a solution to lift some TF Models into production and this completely independent from cloud or not cloud. So it shouldn't rely on any specific cloud components, that is why I was going for testing an on prem solution to be independent in either way. So if you know if there is some example there in the wild for doing this outside of any cloud that would be fantastic and would help a great deal.

**Comment by aronchick** [comment]
+1 to Jeremy's comments! We just demo'd (for example) Kubeflow running on Azure - https://github.com/ritazh/k8s-ml/ - but, to his point, we should work hard to split up the TFX examples.

That said, I don't think we have a pure on-prem version - would you mind taking a swing at one of the examples and posting the first bug you run into?

**Comment by johnugeorge** [comment]
@wzrdtales Kubeflow doesn't have any any cloud specific dependency. eg:  You could have a look at tensor flow mnist example on Kubeflow 0.4 at https://github.com/CiscoAI/KFLab/tree/master/tf-mnist   We have tried this example on our servers.  This example should work with any k8s cluster.

**Comment by illeatmyhat** [comment]
It's very opaque to set up connecting to Kubeflow over SSL on a custom domain name in an on-prem cluster.
The existing documentation only covers GCP-specific tooling, and the `ks` approach is too different from the existing documentation of the components that Kubeflow uses (i.e. Ambassador)

**Comment by elyase** [comment]
I think this is a documentation issue. For example [here](https://www.kubeflow.org/docs/started/getting-started/) you can read:

"If you have an existing Kubernetes cluster or want to use Kubeflow on prem, follow the guide to deploying Kubeflow on Kubernetes."

On that page you are directed to use the new `kfctl` binary but then [on the downloads page](https://www.kubeflow.org/docs/reference/downloads/):
"The kfctl binary currently supports only Kubeflow deployments on Google Cloud Platform (GCP). The goal is to support other platforms too. Contributions welcome. See issue kubeflow/#2954."

This adds to the confusion. Additionally it would be great to have links to "on premise only" official examples that are guaranteed to work without cloud dependencies.

**Comment by yanniszark** [comment]
There is still work to be done in order to have complete feature-parity.
With the latest v0.6 release, you can deploy Kubeflow on an existing, on-prem Kubernetes cluster with the following guide: 
https://www.kubeflow.org/docs/started/getting-started-k8s/
