### ISSUE TITLE
How to add persistent volume in jupyter_spawner.py file ?

### ISSUE THREAD

**Issue by akshaydtada** [kubeflow/kubeflow#285]
Hi,

I have followed these steps https://github.com/kubeflow/kubeflow/blob/master/user_guide.md to deploy kubeflow.
I'm able to see Jupyter notebook interface after logging into the jupyter hub.
now to add persistent volume if I follow the steps mentioned here https://github.com/kubeflow/kubeflow/pull/22/files/48ffe99d30eb31abc4d54c4553483b6c5b2034bc and make these changes in jupyter_spawner.py file.
tf-hub goes into CrashLoopBackOff error saying
IndentationError: unexpected indent

Can you suggest some solution to this to add persistent volume ?

**Comment by carmark** [comment]
@akshaydtada 

`IndentationError: unexpected indent` is usually the syntax indent error in Python, you need to check it.

**Comment by jlewi** [comment]
@akshaydtada Can you explain what you did in more detail?  The link
https://github.com/kubeflow/kubeflow/pull/22/files/48ffe99d30eb31abc4d54c4553483b6c5b2034bc
points to a deleted file in our repo.

@inc0  submitted a change to mount the PVC at ${HOME}/work so you shouldn't need to do anything.

**Comment by akshaydtada** [comment]
I have followed these steps
https://github.com/kubeflow/kubeflow/blob/master/user_guide.md
and got jupyter notebook interface.
![jupyter4](https://user-images.githubusercontent.com/31499576/36711364-f1439c58-1ba8-11e8-93eb-0a9589ec1006.PNG)
but when i create files anywhere other that work folder it won't persist my files if i delete generated pod from k8s dashboard.
and if i try to create file in work folder it is saying permission denied.

So if it is supposed to persist  my data in work folder, why it is not allowing me to create files in that folder ?

**Comment by akshaydtada** [comment]
![word_permissnissue](https://user-images.githubusercontent.com/31499576/36712295-285b31ba-1bae-11e8-8d8e-47cd60a49348.PNG)
this is the error i'm getting.

**Comment by inc0** [comment]
@akshaydtada did you use fresh code (very fresh, we merged change just few days ago)? I didn't run to this issue (we also run our jupyters as root, so that's strange).

**Comment by inc0** [comment]
OK, I replicated this issue with rook. On it.

**Comment by akshaydtada** [comment]
@inc0 Yes, I'm using fresh code only and my default storage class is standard.
As I was getting this permission issue, I gave permission to work folder through pod terminal
`chmod 777 work`
then I'm able to create files in work folder.
But for every user I need to give permission manually.
This should not be the case right ?

**Comment by inc0** [comment]
@akshaydtada no, we already triaged this bug and fixing it.
