### ISSUE TITLE
[GCP] configure_envoy_for_iap.sh doesn't handle multiple backends?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2857]
The container running configure_envoy_for_iap.sh is crashing with the error.

```
Your active configuration is: [default]
Waiting for backend id PROJECT=kubeflow-ci-deployment NAMESPACE=kubeflow SERVICE=envoy filter=name~k8s-be-30767-...
sh: 804442768225131172: unknown operand
BACKEND_ID=121656759024655772 804442768225131172
sed: unmatched '|'
Restarting envoy
/var/envoy-config/configure_envoy_for_iap.sh: /var/shared/healthz.env: line 2: 804442768225131172: not found
/var/envoy-config/configure_envoy_for_iap.sh: /var/shared/healthz.env: line 5: 804442768225131172: not found
Fri Mar 29 02:09:53 UTC 2019 WARN: IAP check failed, restarting container.
```
So it looks to me like the script is detecting two backends and that's causing the error.

I think the reason there are two backends is because 
  1. Is for LetsEncrypt
  1. Is for envoy

I suspect normally what happens is the IAP container is crashing until the ACME dance finishes at which point LetsEncrypt backend is deleted.

In this particular case, it looks like the certificate isn't created because of the error.

```
  message: 'Failed to create new order: acme: urn:ietf:params:acme:error:rateLimited:
        Error creating new order :: too many certificates already issued for exact
        set of domains: jlewi-0327.endpoints.kubeflow-ci-deployment.cloud.goog: see
        https://letsencrypt.org/docs/rate-limits/'
```

To verify I'm going to try deleting the certificate to see if that deletes the second backend and fixes the issue.

If I'm correct then I think we need to figure out how to fix to deal with tmultiple backends.

https://github.com/kubeflow/kubeflow/blob/2686aeefc1a9c6c7c24c7e4e259af31942b8c291/kubeflow/gcp/configure_envoy_for_iap.sh#L41

**Comment by jlewi** [comment]
Deleting the service didn't delete one of the backend services.

One of the backend services wasn't connected to a loadbalancer. So i deleted that one.

configure_envoy_iap.sh is now running successfully

```
Activated service account credentials for: [jlewi-0327-admin@kubeflow-ci-deployment.iam.gserviceaccount.com]
[component_manager]
disable_update_check = true
[core]
account = jlewi-0327-admin@kubeflow-ci-deployment.iam.gserviceaccount.com
disable_usage_reporting = true
project = kubeflow-ci-deployment
[metrics]
environment = github_docker_image

Your active configuration is: [default]
Waiting for backend id PROJECT=kubeflow-ci-deployment NAMESPACE=kubeflow SERVICE=envoy filter=name~k8s-be-30767-...
BACKEND_ID=804442768225131172
Restarting envoy
```

**Comment by jlewi** [comment]
The ultimately resolved the issue. 

My suspicion is that the extra LB might have been because I was deleting and redeploying Kubeflow using the same name and we ended up leaking a backend.

**Comment by lluunn** [comment]
dup of #2550

IIUC the problem is not the acme backend, but some other backend service within the project that use the same port number.

**Comment by jlewi** [comment]
Duplicate of #2550
