### ISSUE TITLE
Add volume support for mpi-job

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#2858]
1. mpi-job by default doesn't have volume support, this is good for synthetic data. Recently, I need to train model using real storage. I'd like to add volume options.

2. mpi-job doesn't have unit test coverage. mpi-job-custom and mpi-job-simple are are jsonnet files which are not easy to test. I'd like to make some adjustment and make them easy to test.

I am working on a PR to address these issues. Prototype won't be changed and they just need to be refactored.

**Comment by jlewi** [comment]
@Jeffwan What is the priority of this issue?

Are you going to fix this as part of 0.6?

In 0.6 we will likely get rid of ksonnet; how does that affect this issue?

**Comment by Jeffwan** [comment]
PR is out.  https://github.com/kubeflow/kubeflow/pull/2869.  

I am working on some benchmark jobs that needs this small feature. It's fine this is changed in 0.6 along with ksonnet deprecation.
