### ISSUE TITLE
[gcp] speed up time to provision IAP endpoint on GCP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2860]
I wanted to jot down some ideas of how we could speedup the time it takes for the Kubeflow UI to be accessible via IAP.

We should measure the time it takes now before implementing anything

* Use a self signed certificate
   * A self signed certificate would allow the endpoint to beavailable while the ACME challenge is happening
   * We could replace the cert with the signed cert once its available
   * Users would get the warning in chrome/firefox until the new cert is propogated but at least it would be accessible

* envoy pod crashloops until IAP is configured
   * This is an idiosyncrancy of how we configure IAP
   * Our envoy config isn't valid until the IAP sidecar injects the values from IAP
   * This blocks the GCLB from detecting that the backend is healthy
   * Moving to ISTIO as the gateway and doing JWT validation there should fix this problem

**Comment by lluunn** [comment]
> Moving to ISTIO as the gateway and doing JWT validation there should fix this problem

This is already the case if install istio.
