### ISSUE TITLE
Too much monthly log bytes ingested with Stackdriver on GKE

### ISSUE THREAD

**Issue by onurgu** [kubeflow/kubeflow#2864]
My installation produces nearly 10s of GBs of logs per day in the default setup.

I was able to report this value using Stackdriver Metrics Explorer using the "billing/monthly_bytes_ingested" metric.

Is this a known issue?

As I saw that nearly 70 log entries like the following are reported in the SAME millisecond (X) by the stackdriver I gather there is a problem:

[29/Mar/2019 10:16:37] "GET /healthz HTTP/1.1" 200
[29/Mar/2019 10:16:47] "GET /healthz HTTP/1.1" 200
and many more

I can say that there is a corresponding log entry for every 10 seconds between 10:06:17 and 10:26:57. 

And these are reported again at the SAME milisecond (Y) just after 722 miliseconds before the previous milisecond (X).

What is the problem?

**Comment by jlewi** [comment]
Can you tell which pod this is coming from?
Its probably because some component has verbose logging turned on.

**Comment by onurgu** [comment]
When I look at the 'resource.labels.pod_name', I see two prefixes:

- envoy
- whoami-app

**Comment by onurgu** [comment]
A lot of logs like

`sync CloudEndpoint kubeflow/XYZ`

from pod_name = 'metacontroller-0'

and also some failure logs from

`ml-pipeline-persistenceagent`.

**Comment by onurgu** [comment]
I have spent more time investigating this.

First, I have seen that the real culprit was the `metadata-agent` containers that emit log entries with a size of nearly 35KB. Expected amount of data per day is 34.56GB when we assume that the number of such log entries is 12.

An example is:

```
I0402 07:59:03 7f3c527fc700 store.cc:57 Updating metadata map { type: 'k8s_cluster' labels: { cluster_name: 'XYZ' location: 'XXX' } }->{version: 0.1, is_deleted: 0, created_at: 1970-01-01T00:00:00.000000000Z, collected_at: 2019-04-02T07:59:03.101301727Z, metadata: {"blobs":{"services":[{"api":{"pods":[],"raw":{"apiVersion":"v1","kind":"Service","metadata":{"creationTimestamp":"2019-03-26T10:46:16Z","labels":{"component":"apiserver","provider":"kubernetes"},"name":"kubernetes","namespace":"default","resourceVersion":"29","selfLink":"/api/v1/namespaces/default/services/kubernetes","uid":"123456"},"spec":{"clusterIP":"10.X.Y.Z","ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":443}],
...
```

This message is originating from [https://github.com/Stackdriver/metadata-agent/blob/85d4f5a570911ddbc2cd0be2a87fa186694140d3/src/store.cc#L44](https://github.com/Stackdriver/metadata-agent/blob/85d4f5a570911ddbc2cd0be2a87fa186694140d3/src/store.cc#L44)

Thus, the problem is the `-v` switch in the `args` section of `stackdriver-metadata-agent` app in the [configuration file](https://storage.googleapis.com/stackdriver-kubernetes/stable/agents.yaml). This file is downloaded by `scripts/gke/util.sh` during the generation of the GCP platform configuration files.

I have removed this switch and redeployed the kubernetes cluster to GCP. It seems like it solved the problem for now.

**Comment by jlewi** [comment]
Thank you so much @onurgu.

It seems like you might be using an older version of KF. With 0.5 we no longer use those scripts. More importantly, Kubeflow is no longer explicitly installing the stackdriver agents; we just turn on the appropriate logging in GKE. So whatever defaults get used should be the defaults GKE sets.

So hopefully this is fixed in the later versions by GKE configuring the stackdriver agents with suitable defaults.
