### ISSUE TITLE
Attach stacktrace info to kfError

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2866]
We use kferror as an interface to define errors.
https://github.com/kubeflow/kubeflow/blob/3fa97bc61e7b4b1eeb0062a8cbc98920e9da43d5/bootstrap/pkg/apis/kferrors.go#L32

When we create errors we should attach a stack trace so its easy to know the source of the error. This will help in debugging.

We might want to provide helper methods for creating kferrors so that we automatically attach stack trace info e.g.

```
NewKferror(INTERNAL_ERROR, "Some error occurred.")
```

**Comment by jlewi** [comment]
Should we punt this to 0.7?

**Comment by jlewi** [comment]
errors has a WithStack method to attach stack trace.
https://godoc.org/github.com/pkg/errors

We should probably use that pretty widely in kfctl.

**Comment by yanniszark** [comment]
@jlewi I also use this in platform existing.
The `pkg/errors` library is extremely helpful in debugging errors.
We should also provide helper methods for returning errors, the current way of defining a new KfError struct results in a lot of clutter.
