### ISSUE TITLE
kfctl consider a model where bootstrap and kfctl can be combined [discussion]

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2870]
currently we have 2 binaries: kfctl, bootstrapper that end up doing similar things.
One is a client tool - targeted for devops users to be run on their laptop or within an ssh accessible linux server like a bastion node. The other is a server built in a docker container that takes requests from a web ui. Both do similar things. There are a few options that would combine these executables

1. Call it 'kfctl', run bootstrapper by calling 'kfctl --server'. Add the code under bootstrap/cmd/bootstrap to kfctl.
2. Split out kfctl so that it just has the cobra.commands under bootstrap/cmd/kfctl/cmd.
  - Each cobra.command (apply, delete, generate, init, show) calls the equivalent of `kubectl exec <pod> -c kfctl -it -- kfctl $*` using the k8s.io/go-client. 
  - these calls are handled within bootstrap/cmd/bootstrap/app/ksServer.go in the same way as the UI. 
  - [pro] kfctl has fewer threat vectors since its calls do not directly mutate the cluster, rather they go through the kfctl-server in the same way the UI does. 
  - [con] manually tweaking files under ks_app (and soon kustomize) now require remotely accessing the container (kubectl exec <pod> -it bash) and tweaking them there.

I can think of additional pros and cons of each approach. Please add thoughts / ideas.

**Comment by jlewi** [comment]
This is in progress; closing this issue as obsolete.
