### ISSUE TITLE
kfctl update the Dockerfile so kfctl_base and kfctl are pushed to the gcr registry

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2872]
Currently kfctl is pushed to gcr.io/PROJECT/kfctl.
We should also push the development environment (kfctl_base)

- [ ] Update the Dockerfile
- [ ] Update the Makefile targets
- [ ] Update developer_guide.md

**Comment by jlewi** [comment]
@kkasravi can you assign labels to this issue please?
What is the priority of this issue?
Are we going to try to get it done in 0.6?
