### ISSUE TITLE
We need to mount gcp sa ('user-gcp-sa')  and k8s sa with higher privileges in notebook pods

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#2876]
When running fairing in kubeflow notebooks, it fails because  notebook's k8s service account does not have enough privileges to list secrets. 
Here is the snapshot of the error we are getting:
with the following error : ---------------------------------------------------------------------------

/opt/conda/lib/python3.6/site-packages/kubernetes/client/rest.py in GET(self, url, headers, query_params, _preload_content, _request_timeout)
    229                             _preload_content=_preload_content,
    230                             _request_timeout=_request_timeout,
--> 231                             query_params=query_params)
    232 
    233     def HEAD(self, url, headers=None, query_params=None, _preload_content=True, _request_timeout=None):

/opt/conda/lib/python3.6/site-packages/kubernetes/client/rest.py in request(self, method, url, query_params, headers, body, post_params, _preload_content, _request_timeout)
    220 
    221         if not 200 <= r.status <= 299:
--> 222             raise ApiException(http_resp=r)
    223 
    224         return r

ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '984ec956-c8d9-499c-9327-c4e6869f2b3c', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 29 Mar 2019 23:13:33 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:kubeflow:default\" cannot list secrets in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}

We copied k8s config of my local computer to the notebook container to make it working. 

//cc @karthikv2k 
//cc @lluunn

**Comment by lluunn** [comment]
we are doing it with admission webhook: #2770
