### ISSUE TITLE
local port forwarding broken "This site can’t provide a secure connection"

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2884]
with new v0.5.1-rc1, I failed to connect to kubeflow UI by port forwarding ambassador endpoint (see below) which used to work in 0.4 or before.
![image](https://user-images.githubusercontent.com/2348602/55309533-f77fc080-5412-11e9-90dc-0739e0d019c3.png)

The cluster is deployed using staging click-to-deploy app + simple auth + v0.5.1-rc1

**Comment by jlewi** [comment]
Can you provide the details of the error?

What is the port-forwarding command you ran?

**Comment by jlewi** [comment]
When you have basic auth enabled we require you to use https. This is required because we don't want you sending your username and password in the clear.

By bypassing the ingress you are bypassing https and your connection is rejected. I think this is working as intended. 

If you have basic auth enabled why don't you connect through the external ingress rather than port-forwarding to ambassador?

/cc @paveldournov

**Comment by jlewi** [comment]
If you deployed basic auth why are you trying to connect via `kubectl port-forward`? Why don't you just access the endpoint

```
https://${APPNAME}.endpoints.${PROJECT}.cloud.goog
```

Cclick to deploy + basic auth + kubectl port-forward is not what I would consider a well supported use case and I'm not sure that's a use case we want to explicitly support.

The primary goal of  Click to Deploy is to allow people to use Kubeflow without installing anything locally and using just a web browser.

So in that regard it doesn't make much sense to deploy Kubeflow via the web app and then connect via an ssh tunnel that requires using `kubectl port-forward` locally or spinning up a VM to use as a proxy (Cloud Shell)

If you deploy via click to deploy then you can connect to the endpoint directly via  **https://${APPNAME}.endpoints.${PROJECT}.cloud.goog**

This will be secured via https and either Google credentials or basic auth (username/password) depending on how you deployed it.

In the past `kubectl port-forward` via Cloud Shell was offered as a kludgy alternative to IAP. That method had a bunch of drawbacks e.g. the shell would timeout and users would need to restart it. I think IAP and Basic Auth are better alternatives and users should pick one of them.

kubectl port-forward is a third option. In this case you are doing an ssh tunnel over the GKE master. 

If you want to use this method, you should probably disable external ingress and basic auth. I don't think this is something we would try to explicitly support unless we had a compelling reason why this was better then the alternatives of IAP or Basic Auth. As mentioned above, one of the goals of click to deploy is to not require any client side tools.

Supporting multiple modes of ingress e.g. **https://${APPNAME}.endpoints.${PROJECT}.cloud.goog** and `kubectl port-forward` is also not something I think we want to support. For two reasons

1. This effectively creates a backdoor that allows people to bypass security

    * e.g. if you have IAP enabled we don't want people to access the cluster unless they've gone through
      the OAuth flow and verified they have the valid IAM role
    * In this sense the error you are getting is WAI because you are trying to bypass to the intended basic auth web flow

1. A lot of web applications need to be explicitly configured with the base URL they are running on when operating behind a reverse proxy (e.g. Argo)

    * As a result port-forwarding to Ambasador will have mixed results because the base URL is no "localhost" which will not match the URL configured as the base URL for various apps

**Comment by paveldournov** [comment]
When I select "Skip IAP" in the deployer app - it asks for the user name and password and does not provision the DNS for the cluster. Given the user name and password is not sync'd with any centralized identity store, I'd prefer this to be a skippable step as well, but today it does not seem to be possible. So the only options are either IAP or basic-auth with non-working SSH. 

SSH to k8s has been a working method, more reliable than cloudshell and used by the users, removing this open should have come with a notification and discussion.

**Comment by amygdala** [comment]
Another thing to consider: Once you have a cluster set up with basic auth, you might want someone to have temporary access. That is, you might not want to give them the login/pwd. 
With port-forwarding supported, you could do that by temporarily allowing them to grab the gke cluster credentials and port-forwarding in.  Then revoke that permission when they're done.

**Comment by jlewi** [comment]
@kunmingg Added a work around to Click To Deploy. 
When this rolls out into production you will be able to select "IAP Defer Endpoint Setup.". This setup should be equivalent to local port-forwarding in 0.4 because Ambassador doesn't enforce any authorization; so you can port-forward to Ambassador.
