### ISSUE TITLE
Investigate img and kaniko for building containers

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#289]
https://github.com/jessfraz/img

Could be a nice solution for building containers in the cluster.

**Comment by jlewi** [comment]
This looks promising.

@cwbeitel Might be worth trying out in the context of your TF agents example. I wonder if people could build the image directly from their  Jupyter notebook.

**Comment by cwbeitel** [comment]
Oh, neat. Yeah building from the notebook is a nice offering. I'll try that out.

**Comment by cwbeitel** [comment]
So this https://gist.github.com/cwbeitel/f8c9d2a7c0dfc7ca8f2d598b126d6628 is as far as I've gotten, these instructions https://github.com/jessfraz/img reference using this PR to runc https://github.com/opencontainers/runc/pull/1688

The error I'm getting in the container is

```bash
jovyan@f65d4ed9d37a:~$ unshare
unshare: unshare failed: Operation not permitted
```

which is not happening from a shell on JupyterHub... I'm a bit out of my depth when it comes to low-level os stuff but I'll make another attempt this week if nobody else does, until then building with Argo.

**Comment by cwbeitel** [comment]
@jewi Anything wrong with notebook users (jovyan) being in root group by default? That would be an easy way to make `img` work but also permit installation of packages like ffmpeg or random other dependencies users might want during development. I myself would like to use JupyterLab as my development environment but can't really unless I can install system packages.

Being a root user gives people the ability to modify the container they're running in but not to modify anything externally except if there are credentials to be stored that only root should have access to which currently is not the pattern iiuc.

**Comment by cwbeitel** [comment]
So I got img working with root priv's but it just filled up the disk and crashed the node (even when provided 60Gb). But it sounds like running containers as root isn't a pattern we want.

One option mentioned in the img readme is orca-build, which depends on [skopeo](https://github.com/projectatomic/skopeo) which in turn has [these](https://github.com/projectatomic/skopeo/blob/master/Dockerfile.build) dependencies of which `libostree-dev ` does not appear to be available via apt for the current os version (16.04) but building from [source](https://github.com/ostreedev/ostree) seems to be working...

**Comment by cwbeitel** [comment]
@cyphar your orca-build tool solves an important problem. Have you been able to set this up on 16.04?

**Comment by aronchick** [comment]
Ok, bad news - Jessie has said this was just an experiment, and we
shouldn't depend on it. Has anyone looked ot Buildah?

**Comment by cwbeitel** [comment]
Yeah I saw that no worries. github.com/cyphar/orca-build is a separate project though from github.com/jessfraz/img

Buildah build and install seems to work, see [build script](https://gist.github.com/cwbeitel/e5099526d9c13046333255b3982219ad) but haven't been able to use it without sudo and getting [errors](https://gist.github.com/cwbeitel/96945cfa7e4105d16497b5c444da6d67).

Installed orca-build with similar build steps but builds fail with [these](https://gist.github.com/cwbeitel/d21cb18676033d1d06208b1e569bd59e) errors.

Maybe someone else will have some success.

**Comment by AkihiroSuda** [comment]
Buildkit is intended to reach production quality, and can be executed in rootless mode with patched runc: https://twitter.com/_AkihiroSuda_/status/955698849560997888

`buildctl` CLI is very complex but there is also simplified version of CLI: https://github.com/moby/buildkit/tree/master/examples/build-using-dockerfile

**Comment by aronchick** [comment]
Here's another video for investigation - https://twitter.com/sjenninglinux/status/968691553458966529?s=09

**Comment by cyphar** [comment]
@cwbeitel I have not yet tried it on 16.04, but I will give it a shot -- and yes I will get back into working on `orca-build` (for some reason I got unsubscribed from the issue list so I haven't seen the newer bug reports).

**Comment by elmiko** [comment]
+1 for investigating the buildah path more thoroughly

**Comment by cwbeitel** [comment]
@cyphar Awesome! Your approach seems very clean and concise.

@elmiko Yeah agree, looks like images need to be prefixed with docker://.../... for docker hub or the registry domain for elsewhere which explains the error I was getting regarding being unable to determine the registry when specifying the base image as simply "ubuntu".

**Comment by cwbeitel** [comment]
@aronchick Wow I didn't realize Bazel's [docker_build rule](https://github.com/bazelbuild/rules_docker) doesn't use docker or require root! Looks like the syntax is not nearly as permissive as a Dockerfile. But that could be a good fit if all you're doing is adding python dependencies and model code.

**Comment by dlorenc** [comment]
Just to throw a few other ideas into the mix, we (Google) have a tool here that can turn a Python app into a Docker image very quickly: https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/ftl/python

It supports requirements.txt and is designed to run inside a cluster.

It's basically a pure python implementation of Bazel's docker_build rule. We'd be happy to help get this integrated into Kubeflow.

**Comment by dlorenc** [comment]
cc @aaron-prindle @nkubala @kimsterv

**Comment by cwbeitel** [comment]
@dlorenc That's awesome. If someone was interested maybe they could write a gist showing the installation and usage of FTL on top of our current notebook images, gcr.io/kubeflow/tensorflow-notebook-cpu and gcr.io/kubeflow/tensorflow-notebook-gpu?

So far I've tried running it via 

```bash
bazel run //ftl:python_builder -- --name [image tag] --directory [build directory] --base [base image id]
```
see [logs](https://gist.github.com/cwbeitel/b7fbca2daf3d43b4bfb5f3a4c0138869), as well as the same with the version [available via GCS](https://console.cloud.google.com/storage/browser/gcp-container-tools/ftl/python/latest/). Maybe just a misunderstanding of CLI args?

**Comment by aaron-prindle** [comment]
@cwbeitel The example you posted should work if you add a tag:
gcr.io/kubeflow-rl/test:latest
 the --name argument you passed.  The base image assumes :latest but the --name target is required to be fully specified:
```
bazel run //ftl:python_builder -- --name gcr.io/kubeflow-rl/test:latest --directory /home/jovyan/ --base gcr.io/kubeflow-rl/agents-demo
```

**Comment by cwbeitel** [comment]
@aaron-prindle Thanks! That did progress further.

[Here's a notebook](https://github.com/cwbeitel/build-notes/blob/master/notes.ipynb) with my current notes on buildah and ftl in case anyone wants to hack around with it as well. Might need to focus on my existing PR for the moment.

**Comment by aaron-prindle** [comment]
@cwbeitel can you verify that auth is configured to pull down a private docker image (gcr and quay) with a docker daemon in this environment?  I believe that the [google/containerregistry](https://github.com/google/containerregistry/) library looks for a .docker/config.json file or a .dockercfg file to get the auth when pulling from a private repo.

**Comment by cwbeitel** [comment]
Was able to build a container using buildah (with sudo), push to a local registry, then pull from that registry using docker. Also to push the built image using buildah to quay. Pulls and builds cache but when pushing the tool doesn't appear to recognize when a layer already exists in the registry, see logs on [timing](https://gist.github.com/cwbeitel/c58744c9652c9574af7d26f4e2dae4c4). Recognizing it could be a configuration issue. Also so far haven't been able to get buildah to work without sudo.

@aaron-prindle Thanks yeah it works having run `docker login ...`. I have been able to run builds using FTL without sudo which is exciting. But as you can see in [these build logs](https://gist.github.com/cwbeitel/a4e0a4678e83eb4659dac3e2d9aaaa80) removing the --no-cache or --no-upload options causes the following error:

```bash
Traceback (most recent call last):
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/__main__/ftl/python/main.py", line 56, in <module>
    main(sys.argv[1:])
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/__main__/ftl/python/main.py", line 51, in main
    python_ftl.Build()
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/__main__/ftl/python/builder.py", line 62, in Build
    interpreter_builder.GetImage())
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/__main__/ftl/common/cache.py", line 168, in Set
    mount=self._mount) as session:
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/containerregistry/client/v2_2/docker_session_.py", line 71, in __init__
    name, creds, transport, docker_http.PUSH)
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/containerregistry/client/v2_2/docker_http_.py", line 194, in __init__
    self._Refresh()
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/containerregistry/client/v2_2/docker_http_.py", line 288, in _Refresh
    resp.status, content))
  File "/home/chris_w_beitel/.cache/bazel/_bazel_chris_w_beitel/3ae97e7121ba86d604c8259638dd2bc0/execroot/__main__/bazel-out/k8-fastbuild/bin/ftl/pytho
n_builder.runfiles/containerregistry/client/v2_2/docker_http_.py", line 140, in _CheckState
    raise BadStateException(message if message else 'Unknown')
containerregistry.client.v2_2.docker_http_.BadStateException: Bad status during token exchange: 400
{"errors":[{"code":"NAME_INVALID","detail":{},"message":"Nested repositories are not supported. Found: cwbeitel/something/python-requirements-cache"}]}
ERROR: Non-zero return code '1' from command: Process exited with status 1

```

Adding the --output-path option produces a tarball that I'll try uploading directly with `bazel run @containerregistry//:pusher.par -- --tarball ${OUTPUT} ...`

**Comment by cyphar** [comment]
> Also so far haven't been able to get buildah to work without sudo.

[This is not supported at the moment](https://github.com/projectatomic/buildah/issues/386), while `umoci` does support this (and has for a while).

**Comment by cwbeitel** [comment]
@cyphar Thanks for the info! I'll take a look at umoci.

With my current usage @containerregistry seems to be recognizing when layers exist but  see [logs](https://gist.github.com/cwbeitel/f8b36f596acdb0e5e1b5f5f240ac17c7), and as you'd expect can't pull the image and run it. Also for whatever reason currently stalls on "Loading v2.2 image from disk..." for about 5min each time it is run. I'm wondering if this is a quay vs. gcr issue.

**Comment by dlorenc** [comment]
Ah yeah, as far as I know quay never added support for the v2.2 image schema (or OCI). See here for some more info:
https://github.com/bazelbuild/rules_docker/issues/102

If v2 support is important we can add it pretty easily to the FTL code, but I think basically every other registry supports v2.2 at this point.

**Comment by cwbeitel** [comment]
Oh interesting. I don't think there is an advantage to use quay over GCR now that the latter is adding vulnerability scanning except in terms of UI for displaying vulnerabilities which you should probably be consuming programmatically anyway.

**Comment by cwbeitel** [comment]
Success. When pushing to gcr.io not only does containerregistry work but so does FTL, including the push step, caching, and enables skipping the time-consuming step of writing the output archive. So yeah this is now ["faaaaast"](https://github.com/google/containerregistry) 😁

@aronchick @jlewi This looks like a good option - no sudo, very fast build and push. By default whatever is in the directory specified to FTL via --directory lands in the container /srv so if using this to bundle a user's jupyter workspace you could just set the container working directory such that there's either a single python -m trainer.task entrypoint or one for each example.

Or we could use `bazel build ...` to package up a python_binary entrypoint for each of the examples and use FTL to ship bazel-bin and bazel-out via /srv... idk if people will want to have that imposition, which would be both example developers and users. But it seems like a nice way to manage a lot of complexity. And having a single codebase you integration test with bazel, ship as a single container, then vary your usage of by choosing different entrypoint commands seems like a good approach. i.e. not having separate training, serving, PS, and workspace containers... topic for another discussion.

**Comment by dlorenc** [comment]
@cwbeitel awesome! The `/srv` path should be configurable with `--destination` if you want the app to end up somewhere else in the container.

Looks like you have a community call next Tuesday, would it be a good next step for us to attend that and discuss getting FTL support merged in?

**Comment by cwbeitel** [comment]
@diorenc That would be great!

**Comment by dlorenc** [comment]
@cwbeitel great! Is there an agenda doc we can get on? I only see the agenda from today, here: https://docs.google.com/document/d/1mhGl19Qg4gpRa6AV6oSHZ2mUIliIeTqCIcLzRFy8UKE/edit

**Comment by cwbeitel** [comment]
Looks like prior to yesterday's meeting a [doc](https://groups.google.com/forum/#!topic/kubeflow-discuss/S7QlvU4-aO8) was posted by @ewilder asking for additions to the agenda as well as providing a link to the call. I'm guessing both are open to everyone. Just learning about these myself. There's a [slack workspace](https://kubeflow.slack.com) as well.

**Comment by ewilderj** [comment]
Meeting details are here: https://github.com/kubeflow/community

**Comment by cwbeitel** [comment]
Throwing another idea into the mix - we might consider circumventing the need to build containers at all by staging a user's workspace and conda env to NFS where they can be accessible by training jobs (to which the same NFS volume will have been mounted). With that approach on startup the train wrapper would activate the same conda environment the user was using for development on JupyterHub then do something like change to the NFS path containing the model code and run `python -m trainer.train`. Or equally well not leave these on NFS but stage in to the local machine on startup (from there or any other storage provider).

**Comment by jlewi** [comment]
@cwbeitel Can you summarize the learnings from this thread?

How are you building containers?
What are the limitations?

**Comment by cwbeitel** [comment]
Sure. I'm currently building containers from JupyterHub using Google Container Builder. Using the --cache-from option speeds up builds but still requires pulling a multi-GB cache image. But this is more or less fine if model development is performed locally and TFJobs are infrequent and long-running.

Another requirement in addition to fast builds is that tools can be used without sudo.

One unspecified variable that may affect the decision is how people intend to run this in production vs. what works for researchers.

There are two classes of options, those that involve building a container and those that do not. In the latter case we can have training jobs simply run the same base container as a user's workspace and stage the contents of a user's workspace to the training container (via an attached volume, including user's jupyterhub PV, or third-party storage intermediate)

- Build a container
  - with Docker
    - External Docker build service (e.g. Google Container Builder)
      - slow if not caching base image
    - Docker-in-docker Kube Job or Argo step
      - would have similar performance to GCB, needing to stage in and out image to --cache-from
    - Attaching Docker daemon sidecar to user's JupyterHub pod
      - I don't understand peoples' intended production models or docker-related security issues well enough to judge whether this is an appropriate non-research solution
  - with FTL
    - supports building without sudo
    - builds are greatly accelerated by local caching
    - when pushing to a remote repo does recognize when a layer is already present
    - as far as I understand would only support builds that can be expressed in terms of requirements.txt files
  - with Buildah
    - does not appear to recognize when a layer is already present in a remote registry, could be config issue or an issue with the choice of registry
    - does not support building containers without sudo
  - with umoci
    - apparently supports building containers without sudo
    - have not investigated fully
  - img was investigated, issues with setup, was not meant for production
- Do not build a container
  - stage dependencies via storage intermediate, activate on startup
    - as conda env
    - as bazel build output
      - requires users to use bazel which is cumbersome
      - is a general solution across languages
      - can be used to produce a container
      - does not require sudo
      - can express the building and pushing of a training container as a dependency for a test?
      - provides the means to do progressive builds of containers, only if dependencies have changed?
  - stage dependency description (e.g. requirements.txt or startup.sh) and install at beginning of job

For research purposes the best immediately-available options seem to be either using an external build service, attach a Docker daemon to the user's JupyterHub pod, or if we can assume we're only using Python then use FTL. Bazel seems like the most general and feature-rich non-sudo solution and what I would personally prefer in the not-immediate-short-term.

**Comment by cwbeitel** [comment]
Summarizing further findings:

- Bazel
  - Attempted to build container with Bazel that includes tensorflow and tensor2tensor dependency following [this](https://github.com/bitnami-labs/bazel_containers) example. Found that tensorflow and t2t libraries could not be imported inside resulting containers (whereas others e.g. tensorboard could);
  - Would appreciate help if there is anyone out there who has a good understanding of Bazel especially producing containers.
- FTL
  - Runs on tf-hub, e.g. [this](https://github.com/cwbeitel/examples/blob/enhance/enhance/py/ship_test.py), but currently fails when certain dependencies are included, see [this test](https://github.com/cwbeitel/examples/blob/enhance/enhance/py/ship_test.py) for some cases.
- Ship conda env
  - Prototyped this and found it is very expensive to compress, transfer, and uncompress a conda env. 
  - This could be remedied if the conda env was kept on shared storage (e.g. symlink ~/.conda/envs before conda create ...) but that approach doesn't provide a good way to version collections of dependencies and relate these to jobs.

- Base image, stage via NFS
  - Have a base image that changes infrequently, based on tf-hub notebook image
  - At runtime mount use code via NFS
  - Provide a flag on launcher script, see [this](https://github.com/cwbeitel/examples/blob/enhance/enhance/py/launcher.py#L269), that allows you to easily re-build the base image in the process of launching a job if dependencies need to change
  - This works well and is what I am using currently
  - This approach is not general across dev environments, assuming storage accessible by jobs has been mounted to user dev space; wouldn't work developing form my local. But if a third-party storage solution like GCS were used for staging and this was mounted to training, inference, render, etc. jobs that wouldn't be a problem. Not sure how opinionated the project intends to be about user's development workflow.

**Comment by aaron-prindle** [comment]
> 
> FTL
> 
> Runs on tf-hub, e.g. this, but currently fails when certain dependencies are included, see this test for some cases.

Can you clarify how you are running the ftl.par and the environment it's in?  I am not familiar with the gcr.io/tensorflow/tensorflow:latest image.  From the list of tests run, it seems that tensor2tensor and git dependencies were failing for you.  In my running of the ftl.par in our builder image with those test dependencies, I am seeing successful builds:

```
# git_test: requirements.txt
-e git://github.com/tensorflow/agents.git@459c4f88ece996eac3489e6e97a6ee0b30bdd6b3#egg=agents
```
```
$ ftl.par --base 'gcr.io/google-appengine/python:latest' --name 'gcr.io/ftl-node-test/git_test-image:latest' --directory, /workspace/ftl/python/testdata/git_test, --no-cache
$ docker run -it --entrypoint /bin/bash gcr.io/ftl-node-test/git_test-image:latest                                  
root@c8ac8a7e06a4:/home/vmagent/app# find /env -name tensor*                                         
/env/lib/python2.7/site-packages/tensorboard                                                         
/env/lib/python2.7/site-packages/tensorboard/plugins/debugger/tensor_store.py                        
/env/lib/python2.7/site-packages/tensorboard/plugins/debugger/tensor_store.pyc                       
/env/lib/python2.7/site-packages/tensorboard/plugins/debugger/tensor_helper.py                       
/env/lib/python2.7/site-packages/tensorboard/plugins/debugger/tensor_helper.pyc          
...
```

```
# tensor2tensor_test: requirements.txt
tensor2tensor==1.5.5
```
```
$ ftl.par --base 'gcr.io/google-appengine/python:latest' --name 'gcr.io/ftl-node-test/tensor2tensor_test-image:latest' --directory, /workspace/ftl/python/testdata/tensor2tensor_test, --no-cache
$ docker run -it --entrypoint=/bin/bash gcr.io/ftl-node-test/tensor2tensor_test-image:latest
root@dada3c9fd296:/home/vmagent/app# find /env -name tensor*
/env/lib/python2.7/site-packages/sympy/physics/quantum/tensorproduct.pyc
/env/lib/python2.7/site-packages/sympy/physics/quantum/tensorproduct.py
/env/lib/python2.7/site-packages/sympy/tensor
/env/lib/python2.7/site-packages/sympy/tensor/tensor.pyc
/env/lib/python2.7/site-packages/sympy/tensor/tensor.py
/env/lib/python2.7/site-packages/sympy/functions/special/tensor_functions.py
/env/lib/python2.7/site-packages/sympy/functions/special/tensor_functions.pyc
/env/lib/python2.7/site-packages/sympy/combinatorics/tensor_can.py
/env/lib/python2.7/site-packages/sympy/combinatorics/tensor_can.pyc
/env/lib/python2.7/site-packages/tensor2tensor
/env/lib/python2.7/site-packages/tensor2tensor-1.5.5.dist-info
...
```

**Comment by aaron-prindle** [comment]
@cwbeitel we will be discussing FTL and how it might be integrated into kubeflow at the kubeflow community meeting today.  If you're attending we can discuss the possible FTL integration there as well.

**Comment by cwbeitel** [comment]
Oh cool that's encouraging! Yeah looking forward to discussing there. Maybe just an environment issue.

**Comment by cwbeitel** [comment]
@aaron-prindle Awesome demo yesterday!

The issue I was having within jhub was a permissions issue not a problem with a dependency or with FTL.

My opinion of the way forward is to add some tooling that is shared across examples in [kubeflow/examples](https://github.com/kubeflow/examples) that (1) either builds normal iterations with FTL or ships code via shared storage and (2) optionally prefixes that step with a re-build of that container using a container build service, which is what I'm doing [here](https://github.com/cwbeitel/examples/blob/enhance/enhance/py/launcher.py).

I think we can bring this issue to a close by just offering one good solution and not trying to make it the best or be the consensus of everyone but we can also link this issue from the Slack to get more input.

@jlewi and @aronchick what do you think about next steps for this issue?

**Comment by jlewi** [comment]
I think a great next step would be a doc (maybe in kubeflow/examples) that captures the different tradeoffs of all the different solutions mentioned in this bug and others.

I think the solutions you mentioned have several limitations

1. FTL can't be used to build the base containers so I think its an incomplete solution. We need a good story for the base containers as well.

1. Shared storage has the following limitations
  - Code could change during execution causing unexpected failures
  - Its going to be harder to create on auditable trail for security and datascience reproducibility

My hypothesis is that Dockerfiles are still the mostly widely used way to build Docker images. So I'd really like a Dockerfile compatible solution.

From this thread buildah seems like a promising option.

A good way to explore buildah might be to use it in our own CI/CD process so we can get first hand experience.

We have an option issue to build the newly added container for the Central UI(#527). That would be a great place to experiment with using buildah by creating a K8s job to build that container using buildah.

/cc @cwbeitel

**Comment by jlewi** [comment]
This looks interesting

https://github.com/containerbuilding/cbi

I think it provides a common API with a bunch of different backends.

**Comment by cwbeitel** [comment]
As with all of the batch build options (if we're interested in that route instead of building in-notebook) the question I have is about build speed and how builds and pulled images are cached. E.g. when using GCB even using the --cache-from option builds are slow because the cache image needs to be pulled every time.

**Comment by jlewi** [comment]
This project looks promising
https://github.com/GoogleContainerTools/kaniko

**Comment by ankushagarwal** [comment]
kaniko does not support ARG and SHELL Dockerfile commands

https://github.com/GoogleContainerTools/kaniko#known-issues
