### ISSUE TITLE
gcp admission webhook cannot be re-applied

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2897]
Haven't figured out the detail, but it seems after reapply, the cert needs to be updated.
Seeing `bad cert` in webhook pod.

I think the problem is we are creating cert secret using a [job](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/create_ca.sh), and that needs re-run.

cc @jlewi

**Comment by lluunn** [comment]
Actually, it might be that webhook pod is mounting the old cert secret at re-apply.

When applying the first time, the webhook pod will wait for the job because it can't find the secret to mount. But the second time it won't wait.

**Comment by jlewi** [comment]
Does this mean kfctl apply will fail if we rerun it?

What is the particular error we are seeing on reapply?

**Comment by jlewi** [comment]
Why would the CA need to change on reapply isn't the SVC and everything else the same?

It be better to use a statefulset or deployment and then just have it run in a loop forever and make the code a null op if the webhook doesn't need to be udpated.

**Comment by lluunn** [comment]
I just verified:
After re-run kfctl apply, everything seems unchanged (pods no restart).
But when new pod is created, I can see error from webhook:

```
2019/04/03 16:52:55 http: TLS handshake error from 10.20.1.1:59196: remote error: tls: bad certificate
```

**Comment by lluunn** [comment]
Something might be related: when I do `kubectl apply` again, most resources (deployment, svc) will show "unchanged", but mutatingwebhookconfiguration shows "configured", although the spec is the same as before

```
mutatingwebhookconfiguration.admissionregistration.k8s.io/gcp-cred-webhook configured
```

**Comment by lluunn** [comment]
ah we patch cabundle for the webhookconfig, so can't just reapply.
Will send out a PR to fix
