### ISSUE TITLE
kfctl e2e test failure: cannot delete endpoint

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2900]
https://github.com/kubeflow/kubeflow/pull/2895#issuecomment-478806415

http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kfctl-go-iap-2895-4014fa2-1808-a964?tab=workflow&nodeId=kubeflow-presubmit-kfctl-go-iap-2895-4014fa2-1808-a964-785771799

cc @gabrielwen @kunmingg

**Comment by abhi-g** [comment]
@gabrielwen @lluunn Please let me know if this should be a p0

**Comment by gabrielwen** [comment]
from the error message it's because endpoint is already deleted.  so I think it doesn't necessary to be p0 as the test/kfctl is not broken.  will add a logic in deleteEndpoints to check if the endpoint is already gone.
