### ISSUE TITLE
Jupyter docker images need to be updated on the 0.5 branch

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2901]
Here: https://github.com/kubeflow/kubeflow/blob/f99e6e01beb5b81b27dc208a486c2dbce38dafe3/kubeflow/jupyter/ui/default/config.yaml#L27

And here
https://github.com/kubeflow/kubeflow/blob/f99e6e01beb5b81b27dc208a486c2dbce38dafe3/kubeflow/jupyter/ui/rok/config.yaml#L16

/cc @zabbasi

**Comment by zabbasi** [comment]
#2902
