### ISSUE TITLE
Notebook controller not attaching pod labels to inject secrets.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2904]
A spun up a notebook from kfctl built from master which sets version to 0.5.0.

The notebook controller was not attaching the pod labels to the notebook even though the environment variable POD_LABELS was set on the controller.

Notebook controller spec

[notebook-controller.pod.yaml.txt](https://github.com/kubeflow/kubeflow/files/3032129/notebook-controller.pod.yaml.txt)

Notebook spec

[cs-demo-0.pod.yaml.txt](https://github.com/kubeflow/kubeflow/files/3032132/cs-demo-0.pod.yaml.txt)

**Comment by jlewi** [comment]
The notebook controller image seems outdated.
gcr.io/kubeflow-images-public/notebook-controller:v20190325-v0.4.0-rc.1-258-g1728f05f-dirty-8c2dab

#2853 was only committed a couple days ago.

**Comment by jlewi** [comment]
It looks like #2853 didn't update the docker image.

**Comment by lluunn** [comment]
#2895 updated the image

**Comment by kunmingg** [comment]
Can we close this?
