### ISSUE TITLE
E2E Test for TFServing with GPUs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#291]
We need an E2E test for TF Serving with GPUs.

As part of this we should built it continuously with prow.

**Comment by jlewi** [comment]
I have some cycles to work on this.
I'm going to start by adding a ksonnet component to our E2E test to deploy with GPUs.

**Comment by jlewi** [comment]
Bump to P1 since we want to have GPU serving in our 0.1 release.

@lluunn How can we serve a model on GPUs and verify that GPUs were actually used?

**Comment by jlewi** [comment]
https://stackoverflow.com/questions/42630762/how-to-verify-tensorflow-serving-is-using-gpus-on-a-gpu-instance
    Suggests looking at nvidia-smi output
    Some of these metrics should now be available via stackdriver

**Comment by jlewi** [comment]
@lluunn This is blocked on #292 and the changes I requested in #383 to pass in a list of parameters to set on the ksonnet component. 

Once those are fixed do you want to pick this up? I think the next step would be adding appropriate steps to our E2E workflow to run the test using GPUs just like we do with CPUs.

**Comment by lluunn** [comment]
I am changing the cluster to kubeflow-ci, which has GPU pool.
https://github.com/kubeflow/testing/issues/18

**Comment by jlewi** [comment]
@lluunn Any update on the E2E test?

**Comment by lluunn** [comment]
WIP #442
