### ISSUE TITLE
[CUJ] alternative devices in notebooks

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2910]
Currently notebooks are opened within namespaces allocated by the profile-controller. The profile-controller sets up a new namespace with the following resources:
- role, rolebinding for the owner
- resource quota for the namespace

The notebook created for the owner uses a PodSpec created by the UI with an image selected within the UI that may be device specific to gpus.

- [ ] Data scientists may need to run DL algorithms that use devices other than gpus. 
- [ ] Data scientists may need to run distributed algorithms where gang-scheduling is needed in order to reserve nodes that have this hardware (devices)
- [ ] Data scientists may need to monitor the health of nodes running their DL algorithms
- [ ] Data scientists may want to visualise the data graphs within tensorboard 
- [ ] Data scientists want to do all of the above w/o devops involvement

#2882 is the umbrella issue

 @jlewi @ashahba

**Comment by ashahba** [comment]
@kkasravi Thanks for filing this issue.
Do you think we can work together and put more details on it or even come up with something like a design doc?
