### ISSUE TITLE
kfctl evaluate kustomize KEP 

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2911]
[Kustomize Generators and Transformers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190318-kustomize-generators-transformers.md#implementation-detailsnotesconstraints-optional) adds 2 new fields transformers and generators. These may provide solutions within current ksonnet components including testing.

**Comment by jlewi** [comment]
@kkasravi What is the remaining work to be done here?

**Comment by kkasravi** [comment]
Generators are available in kustomize and generators can be used in manifests testing to generate tests. No more work is required here
