### ISSUE TITLE
Jupyter UI should only launch Notebooks in the kubeflow Namespace

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#2925]
Some more context [here](https://github.com/kubeflow/kubeflow/pull/2919#issuecomment-479220566). 

The Notebooks should only be launched in the kubeflow Namespace. As such the Jupyter UI should not allow the user to create/connect/delete a Notebook in a different Namespace.

/assign kimwnasptd

**Comment by kimwnasptd** [comment]
@abhi-g with the PR for #2937 the default selected namespace now is kubeflow.

I was also thinking to remove the namespace selector from the Jupyter UI for 0.5 and always launch the Notebooks in the `kubeflow` Namespace. Then, once we include the multi-user isolation support, we could make another iteration on how the Jupyter UI should handle the namespaces.

@abhi-g @jlewi should I upload a PR for this or are we covered with the fix for #2937 ?

**Comment by abhi-g** [comment]
We had tried to make "Kubeflow" the default namespace, but running into
error. @jlewi suggested to not remove the chooser, but make Kubeflow
namespace default. That way we can continue to test the namespace based
isolation as we develop it.

**Comment by abhi-g** [comment]
@kimwnasptd #2937 covers this as well.
