### ISSUE TITLE
none deployment of kubeflow is available after following the official installation

### ISSUE THREAD

**Issue by felixhuangau** [kubeflow/kubeflow#2927]
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
kubernetes version:v1.14.0

After the official installation of kubeflow and the last code I run is `${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s`, I run `kubectl get deployment -n kubeflow` to check the deployment.
And I found none of them was available, and `kubectl get pod -n kubeflow` shows `No resources found.`

Here's the result of `kubectl get deployment -n kubeflow`
<img width="548" alt="image" src="https://user-images.githubusercontent.com/44130555/55498177-b4318600-568e-11e9-97e7-acaf06865141.png">

Why they are unavailable? So confused...

**Comment by pdmack** [comment]
Hmmm, pretty unusual.

Can you retry and `kubectl get events -n kubeflow`? Don't need to paste it here. Just a summary of what you see or a gist.

**Comment by felixhuangau** [comment]
> Hmmm, pretty unusual.
> 
> Can you retry and `kubectl get events -n kubeflow`? Don't need to paste it here. Just a summary of what you see or a gist.

This issues was solved, just free the disk space and those deployment run.
But some of those still not working, and the results of `kubectl get events -n kubeflow` shows `Warning BackOff pod/ml-pipeline-persistenceagent` `Warning   FailedScheduling 
25s         Warning   FailedScheduling       ` `Warning   Unhealthy pod/vizier-core-58bccb7b49-v8hwg `
`Warning   BackOff                pod/vizier-core` `Warning   FailedMount            pod/vizier-db` `Warning   FailedScheduling       pod/minio-555568f9b9-ndjmp`.

here's the result

<img width="556" alt="image" src="https://user-images.githubusercontent.com/44130555/55687003-3e3d5f80-59ab-11e9-9c92-b1b76699e7ad.png">

**Comment by jlewi** [comment]
I suspect the pods dependent on a PVC and are relying on a default storage class to create a suitable PV automatically.

Can you look at the pods that aren't starting and see whether there is a problem mounting a PV/PVC?

**Comment by yylin1** [comment]
This problem needs to clean PV and remove the old deployment file.
