### ISSUE TITLE
Example/Docs for using IAP with TFServing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#293]
We want examples/docs to show how to use IAP with TFServing. We want an example of client code that obtains an appropriate credential and adds it to the RPC.

**Comment by lluunn** [comment]
Following https://cloud.google.com/iap/docs/authentication-howto.

**Comment by lluunn** [comment]
#361 shows how to authenticate programmatically as service account.
There are currently no programmatic way to do it for user account. We have to follow instruction at https://cloud.google.com/iap/docs/authentication-howto. 
I will add this info to the doc.

**Comment by jlewi** [comment]
@lluunn Can we close this issue or is their more work?

**Comment by lluunn** [comment]
Just one more thing: https://github.com/kubeflow/kubeflow/pull/392
