### ISSUE TITLE
kfctl will fail for --platform gcp if $HOME/.kube/config doesn't exist

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2933]
Gcp will create /root/.kube/config but not until `kfctl apply ...` is called. Initializing Ksonnet.restConfig and Ksonnet.apiConfig in ksonnet GetKfApp is an error since they aren’t used until `kfctl apply...` . Since ksonnet is called after gcp in `kfctl apply...` initializing these values should be done inside of ksonnet Apply.

**Comment by kunmingg** [comment]
@kkasravi 
Can you reproduce?
Initializing Ksonnet.restConfig and Ksonnet.apiConfig in ksonnet GetKfApp will print warning message instead of throw error if ```.kube/config``` doesn't exist.
