### ISSUE TITLE
Jupyter Spawner UI needs to pick "kubeflow" namespace in the namespace chooser by default

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#2937]
Currently, the "default" namespace shows up. For novice users who may not understand namespaces, they'll end up creating notebooks in "default" namespace.

Our recommendation for v0.5 (until multi-user isolation support is complete) is to create notebooks in "kubeflow" namespace. All of Fairing instrumentation is designed to work seamlessly with notebooks created in  that namespace.

**Comment by davidawad** [comment]
I have nothing to do with this issue at all but I love kubeflow and wanted to give a shoutout to the awesome maintainers.

**Comment by amygdala** [comment]
I'd suggest not just making the 'kubeflow' namespace the default, but removing the ability to select any other namespace at all (until other namespaces work properly: see  https://github.com/kubeflow/kubeflow/issues/2947)

**Comment by abhi-g** [comment]
This sounds reasonable to me @amygdala. @jlewi any concerns?

**Comment by abhi-g** [comment]
#2951 modifies the UI to list only kubeflow namespace until multi-user isolation and profiles creation is functional.
