### ISSUE TITLE
How to access notebook on KUBO?

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [kubeflow/kubeflow#294]
I have installed kubeflow on CFCR. i am able to bring up my notebook but i am not able to access it from my local. Please provide possible solution for this. Thanks.

/my-kubeflow$ kubectl get svc -n=${NAMESPACE}
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
ambassador         ClusterIP   10.100.200.46    <none>        80/TCP     5d
ambassador-admin   ClusterIP   10.100.200.178   <none>        8877/TCP   5d
k8s-dashboard      ClusterIP   10.100.200.220   <none>        443/TCP    5d
tf-hub-0           ClusterIP   None             <none>        8000/TCP   5d
tf-hub-lb          ClusterIP   10.100.200.97    <none>        80/TCP     5d
tf-job-dashboard   ClusterIP   10.100.200.83    <none>        80/TCP     5d

**Comment by jlewi** [comment]
We discussed in slackchat. KUBO is being used to deploy Kubernetes on GCP.

My understanding of the setup is Kubernetes is accessed by first ssh'ing to a bastion node on GCP from which kubectl can be run. 

So the question is how to access pods in the Kubernetes cluster e.g. using port-forward from the local machine.

I think one way to do this would be to

1. Set up portforwarding to the bastion using ssh
1. On the bastion use kubectl port-forward to forward traffic from ssh to the pod.

For example

On the local machine, run the following to ssh into the bastion and forward local port 8080 to port 8080 on the bastion.

```
gcloud compute --project=${PROJECT} ssh --zone=${ZONE} jlewi-builder --ssh-flag="-L 8080:127.0.0.1:8080"
```

Then while ssh'd into the bastion you could run the following to forward traffic from the bastion to the pod.

```
kubectl port-forward ${POD} 8080:8080
```
You should now be able to access it at `http://localhost:8080`.

I wonder if Cloud Foundary provides a better solution for accessing its ports. 

I assume you could also setup and use IAP if its running on GCP.

**Comment by jlewi** [comment]
Adding a couple folks from the KUBO project in case they want to chime in.

/cc @johnsonj @alex-slynko

**Comment by jlewi** [comment]
Some docs 
https://docs-cfcr.cfapps.io/installing/gcp/routing-gcp/

**Comment by alex-slynko** [comment]
@BenChapman could you please check this?

**Comment by ajayakumar-jayaraj** [comment]
Any updates on it

**Comment by jlewi** [comment]
Closing this as stale.
