### ISSUE TITLE
Update fairing commit hash to latest working for release v0.5

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#2945]
Need to update fairing commit hash to the latest working commit for v0.5 release of Kubeflow pre-configured Jupyter notebook images.

/cc @karthikv2k @jlewi

**Comment by abhi-g** [comment]
@karthikv2k Please confirm top commit from kubeflow/fairing [564776c50d52942a42acec6280a8fd6be8812849](https://github.com/kubeflow/fairing/commits/master) is the correct one.

**Comment by abhi-g** [comment]
Few more fixes. Updated commit to [a9bb9d5cc1c9f1d75efa31198ddbdccfe176b7bf](https://github.com/kubeflow/fairing/commits/master)

**Comment by karthikv2k** [comment]
LGTM
