### ISSUE TITLE
0.5rc3: can only spawn notebook servers in kubeflow namespace

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#2947]
In 0.5rc3 (installed via the click-to-deploy web app), with the UI to spawn off a notebook server, it appears that picking any namespace but 'kubeflow' doesn't work.  With the other namespaces, there's no indication at the cluster end of any attempts to spin up new pods. (The UI just spins indefinitely).

However, if you choose 'kubeflow' as the namespace, all works as expected.  

Maybe related to: https://github.com/kubeflow/kubeflow/issues/2925 . Do the other namespaces need to be removed from the pulldown in the UI?

**Comment by abhi-g** [comment]
Apparently injection of secrets into notebooks created in Kubeflow namespace is causing the behavior that other namespace notebooks won't be creatable via the UI.
There is a workaround to create them which involves some instructions that we'll document
But the recommendation for general users is to create notebooks in Kubeflow namespace
We are making a UI change for the Jupyter web app to deafult the namespace field to "kubeflow" #2937

**Comment by abhi-g** [comment]
Closing as #2937 resolved with limiting notebook creation to only kubeflow namespace. UI doesn't present other namespaces as choices.
