### ISSUE TITLE
[kfctl] Support deployment on more platforms - currently just GCP

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#2954]
For the new kfctl binary in Kubeflow 0.5 we're targeting GCP only. For future releases, we want to support more platforms.

Note: I'm linking to this issue from the docs.

**Comment by Jeffwan** [comment]
AWS is working on support for kfctl(golang). We recently just finish kfctl.sh suppot. Please involve me in any related topics. Thanks!

**Comment by jlewi** [comment]
#2998 Thanks @Jeffwan filed #2998 assigned to you.
#2476 Azure support in kfctl

minikube and dockerfordesktop are already thread.
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/pkg/kfapp

Thanks @sarahmaddox closing this issue in favor of the more specific issues listed above.

**Comment by elyase** [comment]
Sorry what is the ticket for kfctl support on on premise?

**Comment by mattnworb** [comment]
@elyase I think that is mostly solved already by https://www.kubeflow.org/docs/started/getting-started-k8s/, is it not?

**Comment by elyase** [comment]
I tried following that and found some errors so not sure if the docs match the current capabilities of the kfctl binary.
