### ISSUE TITLE
ISTIO routing rule for pipelines

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2962]
We will need to define ISTIO routing rules for the pipelines UI to replace Ambassador.

**Comment by Jeffwan** [comment]
Just notice several issues are created to add istio rule for different components. 
For these static pods, it can have predefine rules. For resources like tf-serving or jupyter notebooks, how to add routing rule dynamically? Any component will be added to do this work?

**Comment by gabrielwen** [comment]
@kunmingg

**Comment by kunmingg** [comment]
@IronPan @hongye-sun 
What's current status of pipeline dependency on ambassador? We are working on replace ambassador with istio.
