### ISSUE TITLE
ksonnet prototypes for TensorBoard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#297]
We should provide some ksonnet components for tensorboard.

There are some examples in this PR
https://github.com/kubeflow/examples/pull/1/files#diff-b1c94ace60732530b2be5b0a67be2d40

The main thing is in addition to deploying TB, we'd like to add an ambassador route.

**Comment by abkosar** [comment]
Hey @jlewi, I'm new to contributing to open source. I came across this issue and I would like to work on this. Can you please assign this to me?

**Comment by jlewi** [comment]
Consider the issue assigned to you @abkosar 

I sent you an invite to the Kubeflow org; I think you need to accept in order for me to actually assign the issue to you.

**Comment by abkosar** [comment]
Just accepted the invite @jlewi 
Thanks!

**Comment by jlewi** [comment]
Welcome to the team!

**Comment by wbuchwalter** [comment]
Hey @abkosar, any progress to share on this?

**Comment by abkosar** [comment]
Hey @wbuchwalter, like we talked on Slack, still working on the issue, thanks for asking and help!

**Comment by jlewi** [comment]
@abkosar Any update on this?

We have a .libsonnet and .jsonnet file checked in here:
https://github.com/kubeflow/examples/tree/master/agents/app/components

So  we just need to move the .libsonnet file to
kubeflow/kubeflow/core 

And the jsonnet file to 
kubeflow/kubeflow/core/prototypes
and refactor it a bit to make it a prototype

Any chance we could get a PR done this week?

**Comment by abkosar** [comment]
@jlewi Just created the pull request following the directions. Tried to refactor the .jsonnet file  too but not sure if I refactored it correctly. 

But here is the link to the request: [#470](https://github.com/kubeflow/kubeflow/pull/470)

I'll appreciate any help and feedback. 

Thanks!

**Comment by jlewi** [comment]
Fantastic thank you.

**Comment by abkosar** [comment]
Hey @jlewi -- Updated the code with your directions and pushed it. Hopefully went a step forward, will appreciate any feedback.

Thanks!
