### ISSUE TITLE
[For:Dashboard v1] Require environment information via Kube-Controller

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2974]
We need to be able to rely on Kube-ctrl to get information about the network such as:
- Build Version
- Cloud Environment
- App Name (for platform-specific links) #2885 (#2935)

/assign @jlewi 
/cc @avdaredevil @prodonjs 

/kind feature-request
/priority p1

**Comment by jlewi** [comment]
#2976 is the issue to define an application resource that is the blocking issue.

**Comment by prodonjs** [comment]
I'm going to close this issue since I think there are other issues that encompass the same topic and we're not currently blocked by anything additional.

/close
