### ISSUE TITLE
Make kubeflow use Istio instead of ambassador by default

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2978]
Include sub issues in https://github.com/orgs/kubeflow/projects/7

**Comment by gabrielwen** [comment]
should we also add routing rules for all components with `getambassador.io/config`?  e.g.:
- tensorbaord
- kubebench-dashboard
- openvino
- echo-server
- centraldashboard
- basic-auth
- seldon
- tf-job-operator

**Comment by kunmingg** [comment]
Definitely.
openvino should be part of pipeline migration effort.

@avdaredevil any concerns for migrating centraldashboard to istio?

**Comment by avdaredevil** [comment]
Will there be any route level / behavioral changes in terms of navigation between embassador vs istio?

I didn't think there would be any issues on our side.

/cc @prodonjs any thoughts?

**Comment by gabrielwen** [comment]
I don't think it'll be any different (and it shouldn't be).  @avdaredevil @prodonjs please help review #3037 when you have chance, thanks.

**Comment by gabrielwen** [comment]
the to-do list is down to 2 items - basic auth and seldon.

**Comment by jlewi** [comment]
Things are working with ksonnet but not kustomize. So we need to get it working with kustomize.

**Comment by jlewi** [comment]
@gabrielwen @kunmingg What is the current status of this?

**Comment by kunmingg** [comment]
kfctl now use istio by default.
