### ISSUE TITLE
Make Profile controller support multi-user notebook 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2979]
For each profile CR (created through registry UI), controller need to manage following k8s resources:

Due end of Q2:
* Namespace
* K8s rbac Role & Rolebinding to grant k8s user and service account necessary access to above namespace.
  * enable user’s kubectl access
  * enable service-account’s in-cluster access
* Grant impersonate permission of k8s user account to notebook spawner backend
* Istio rbac rule

Nice to have:
* Grant impersonate permission of namespace service-accounts to notebook-controller

**Comment by kunmingg** [comment]
This effort should be followup of ```multi-user notebook with manual rules```

**Comment by jlewi** [comment]
So next step is to look at the demo script: #3022  and have the profile resource create the appropriate RBAC roles and bindings for Jupyter.

Follow on step is for profile resource to create namespace level access rules for ISTIO to restrict which users can access services in that namespace.

* Before we automate it with the profile resource we should add to the demo script (#3022) what the required commands would be.

**Comment by jlewi** [comment]
@kunmingg What is the current status of this? 

/assign @kunmingg

**Comment by kunmingg** [comment]
Can close once https://github.com/kubeflow/kubeflow/pull/3234 merge
