### ISSUE TITLE
Users should  be able to create notebooks without service account

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#2980]
Currently if a given namespace does not have  gcp secret and k8s service account namely user-gcp-sa and jupyter-notebook respectively, then user cannot create any notebook (ui's notebook status shows creating forever). We need to resolve this by giving the option to user to choose his desired service accounts to be installed in the notebook's pod.

**Comment by zabbasi** [comment]
/priority/p0

**Comment by kimwnasptd** [comment]
@jlewi will we need this feature for 0.6? 

IIUC in @avdaredevil 's [WIP PR](https://github.com/kubeflow/kubeflow/pull/3503) the Centraldashboard will only show the Namespaces in which a user has `edit` permissions. This means that the Namespaces available to a user will be the ones that were created by a profile and the user is either the owner or was added with a Binding.

In this case the ServiceAccount `default-editor` will be available in the listed Namespaces and the Notebook Pods will be created.

But if this PR will not be shiped with 0.6, then which SA should the webapp give to the Notebook Pods?

Will this PR be part of 0.6? If not, should the jupyter webapp let the user choose the SA for the Notebooks, or should we just create the `default-editor` for the `kubeflow` namespace? AFAIK we don't create it right now, so the Notebook Pods will fail to be created in that Namespace.

**Comment by jlewi** [comment]
I don't think this is an issue. notebooks are working in 0.6.2
