### ISSUE TITLE
Default IAM role and k8s rbac role for new user under multi-user case

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2982]
* IAM role should give access to k8s cluster and IAP app. (Create a custom role? kubeflow-user)
* k8s rbac role should block access to any k8s resource by default. (Assume user self-serve to start through UI)

**Comment by jlewi** [comment]
@kunmingg How's this coming? Can you explain the issue again? Will we just use RBAC as opposed to GKE IAM roles to grant users access to the KF cluster so that they only have access to specific namespaces?

**Comment by kunmingg** [comment]
DevOps / Admin need to grant each user with IAM role:
```
1. Kubernetes Engine Cluster Viewer
```
This role allow user to access clusters, but cannot get/create/delete k8s resources in any namespace by default.

2. user self-serve to create profile, profile will patch rbac role.
3. user can access their namespace via kubectl or Istio.

Will send PR for missing pieces.

**Comment by jlewi** [comment]
I spoke with @kunmingg and I think the issue here is we need to figure out what IAM role to grant users so that at a minimum they can run

```
gcloud container clusters get-credentials ${CLUSTER}
```

in order to configure .kubeconfig.

Once they've run that command we can rely on RBAC for fine grained permissions.

**Comment by jlewi** [comment]
Can close this out once #3123 is merged and we also need to update kubeflow website to tell folks how to set this.

**Comment by jlewi** [comment]
@kunmingg What is the current status of this?

**Comment by kunmingg** [comment]
Will add a README explain how admin manage access via profile, and close this one.

**Comment by jlewi** [comment]
@kunmingg Any progress on the README?

**Comment by jlewi** [comment]
@kunmingg ping?

**Comment by kunmingg** [comment]
Should be covered by:
https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/README.md
