### ISSUE TITLE
Registry URL for kfctl - similar to pip index-url

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#2989]
kfctl should be able to switch out registries from gcr and point at docker or local or custom registries with an index URL flag similar to what pip has.

Use cases: 
1. Airgapped installs onpremise
2. Setups where gcr is not accessible (China)

Pip index-url reference: https://pip.pypa.io/en/stable/reference/pip_wheel/#cmdoption-i

**Comment by vpavlin** [comment]
@swiftdiaries I see this is closed, but did you figure out any other way than manually changing all the images?
