### ISSUE TITLE
Jupyter spawner ui - let user select admission hooks to apply to the notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2992]
We are increasingly using webhooks to inject volumes and environment variables into Jupyter pods.

For example

  * On GCP we inject GCP credentials into Jupyter pods
  * We'd like to use to inject GIT secrets (see #2889 )

To support this we'd like the jupyter spawner UI to let users choose which admission hooks to apply to their notebooks.

Admission hooks are controlled based on labels. So step 1 would be to let users specify which labels to apply to their notebooks.

The next step would allow the web ui to introspect the cluster to see which admission hooks are installed in the cluster. Ideally each admission hook would have a human readable label describing what it does (e.g. as annotation). This would be something like

   * Attach S3 credentials for buckets ...

#2844 we'd like to generalize the admission web hook so users could easily define admission hooks for different things. Possibly by creating a CR similar to PodPresets.

Then the spawner UI could show a set of drop down boxes with these descriptions and a user could just check it. Under the hood the spawner UI could get the labels used by the corresponding admission hook and attach them. This will require some UI work as well as work on generalizing the web admission hook #2844.

/cc @zabbasi @vkoukis @kimwnasptd 

@zabbasi might pick up some of this work. I think a design doc would be a good place to start.

**Comment by zabbasi** [comment]
Similar work which implements podpreset using CRD and a mutating webhook.
https://github.com/jpeeler/podpreset-crd

**Comment by jlewi** [comment]
@zabbasi any update on this?

**Comment by zabbasi** [comment]
the demo script: https://bit.ly/2UOzzxB

**Comment by jlewi** [comment]
@kimwnasptd Do you have the information you need to get started on this? Do you have an ETA?

**Comment by kimwnasptd** [comment]
@jlewi yes, waiting for #3245 to be merged. I will have the PR ready mid-late this week

**Comment by zabbasi** [comment]
@kimwnasptd any update?

**Comment by jlewi** [comment]
@kimwnasptd any update on this?

**Comment by jlewi** [comment]
@kimwnasptd is this blocked on rewriting the jupyter web app to use Angular?

**Comment by kimwnasptd** [comment]
@jlewi yes, but I've almost finished rewriting the webapp. An accurate ETA I could give would be until the end of the week for this feature. 

Although, the time frame might swift depending on how much time it will take for the new UI to merge, but I'll start working on this feature while the new UI is being reviewed.

**Comment by jlewi** [comment]
Thanks @kimwnasptd 

Would it make sense to have a plan B in case there are problems with the rewrite #3439. Is there a simpler way to address #2992 with the existing UI.

What if we just added to the existing UI a field to let users add labels to apply to the notebook & pod? 
That would give users an easy way to attach admission hooks to their notebooks.

**Comment by subasathees** [comment]
@kimwnasptd , Hi Kimonas, I am new to the development, can you tell us how to develop the jupyter webapp UI, as we can see those are build with jsscript. is there any good article or document available like which tool to use for editing js script and jupyter web UI.
