### ISSUE TITLE
[Question] How to customize spawned Jupyter notebook service?

### ISSUE THREAD

**Issue by JohnPaton** [kubeflow/kubeflow#2995]
I would like to do a bit of customization on the Jupyter server deployments and services that our data scientists spawn - think of adding a label and some custom annotations. Customizing the UI config was easy, I just modified `vendor/kubeflow/jupyter/config.yaml` in the `ks` app created by `kfctl`. But if I try to make other modifications (e.g. to `sync-notebook.libsonnet`), these changes don't seem to get reflected in the cluster even if I regenerate and reapply the notebook-controller. Editing the config of the spawned resources directly is not an option as any changes are immediately reverted (I assume by the notebook-controller).

This could just be an experience issue on my part - I'm new to the whole `{j,k}sonnet` world. How can I add a custom label/annotation to my spawned notebook services?

**Comment by jlewi** [comment]
sync-notebook.libsonnet is no longer used. We now use a go lang controller.
https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller

I don't think we support arbitrary customizations. 

For labels and annotations it might make sense to just propogate the annotations from jupyter resource to the service.

For arbitrary customizations, one option would be to define an admission controller to modify the created resources.

#2844 is tracking generalizing our existing admission hook for pods. I don't think we'd thought about doing it for other resources like services but maybe we should.

**Comment by JohnPaton** [comment]
Hmmm... this is related to #2961, on my installation (I've destroyed and created a few clusters with various rc's of 0.5) I can't access spawned notebooks the `rewrite` in the Ambassador config annotation is sending requests to a non-existent endpoint on the notebook server. 

I was hoping to patch this myself until #2961 gets a bit more attention, as this renders Kubeflow unusable for data science for us. 

I'll look into admission controllers but I'l worried about getting into a loop trying to override notebook-controller.
