### ISSUE TITLE
Did notebook-controller use code-generator's deepcopy-gen?

### ISSUE THREAD

**Issue by quanguachong** [kubeflow/kubeflow#2996]
You use go module to manage packages. However,code-generator used by kubebuilder doesn't work in go module.
1. How did you generate the [zz_generated.deepcopy.go](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go) file? 

2. How to update `zz_generated.deepcopy.go` if you change [notebook_types.go](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go)?

**Comment by jlewi** [comment]
@zabbasi @lluunn Do you know the answer?

**Comment by jlewi** [comment]
I think we are using kubebuilder and I think that generates all the code.

**Comment by lluunn** [comment]
We use kubebuilder (which init with dep), and then migrate to go module. (`go mod init` and delete Gopkg.*)
I am actually not sure how zz_generated.deepcopy.go works.

**Comment by quanguachong** [comment]
Thanks anyway!

code-generator seems support go module now, https://github.com/kubernetes/code-generator/issues/57
