### ISSUE TITLE
[Discussion] Master branch tagging

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2997]
We commonly use [git describe](https://git-scm.com/docs/git-describe) to describe version information; e.g. for image tags.

```
git describe --tags --long
```

This will output the most recent tag, number of commits since the tag and then the actual commit.

On release branches this provides nice output e.g. on v0.5-branch

```
git describe --tags --long
v0.5.0-0-ge7d0b5a7
```

Since the branch hasn't diverged yet from the v0.5.0 tag.

If we check out a more commit before that e.g. 

```
git checkout 20205e4
v0.5.0-rc.3-12-g20205e4f
```

So its obvious we are 12 commits past the v0.5.0-rc.3 tag.

On master though we don't consistently tag it.

```
git describe --tags --long
v0-29-g9625cde8
```

Not sure where the v0 tag came from.

Should we add a v0.Y-dev tag at the fork point with the previous release branch? e.g. 

```
git merge-base upstream/master upstream/v0.5-branch
4485a65079a1b445195cb7cc34035655919aaaea
```

**Comment by avdaredevil** [comment]
A thing to add for a few folk which I ran into as well, is to make sure you have the latest copy of tags by running:

```sh
git fetch prod
```

_**Note:** In my case `prod` points to this Kubeflow repo, while origin points to my personal fork_

**Comment by jlewi** [comment]
I think I could delete the v0 tag by doing something like

```
git push upstream :refs/tags/v0
```

**Comment by jlewi** [comment]
Created a release 

```
v0.6.start
```

At the start of the release branch.
