### ISSUE TITLE
Add Platform AWS support to kfctl

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2998]
AWS is supported in kfctl.sh but we should think about porting that over to the kfctl binary.

I think @Jeffwan has said he will work on this.

/assign @Jeffwan 

Related Issues: #2954 
Related issues: #32

**Comment by Jeffwan** [comment]
Blocked by eksctl.. can not easily import as SDK

**Comment by jlewi** [comment]
@Jeffwan What's the plan for how users will deploy 0.6 on AWS?

**Comment by Jeffwan** [comment]
@jlewi Just come back from vacation and I will check in my changes in kfctl(golang) this week.  aws will be a platform.

**Comment by arun-gupta** [comment]
Looking forward to this support in `kfctl` as opposed to using `kfctl.sh`

**Comment by jlewi** [comment]
@Jeffwan Any update on this? Do you have a PR in progress.

**Comment by Jeffwan** [comment]
This is done. I think we can close this story. Right now, one thing left is to update documentation.  I can track issue in website project. https://github.com/kubeflow/website/issues/1024

**Comment by Jeffwan** [comment]
documentation merged.

/close
