### ISSUE TITLE
permission error during deployment when GOOGLE_APPLICATION_CREDENTIAL is set as the environment

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/kubeflow#3003]
If the GOOGLE_APPLICATION_CREDENTIAL is set as the environment variable, kfctl uses this credential directly instead of the credential from 'gcloud auth application-default login'.

The error looks like:
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set Cleared IamPolicy error: googleapi: Error 403: The caller does not have permission, forbidden
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set Cleared IamPolicy error: googleapi: Error 403: The caller does not have permission, forbidden

After GOOGLE_APPLICATION_CREDENTIAL is unset, it works.
It is probably a better idea for the kfctl to skip using GOOGLE_APPLICATION_CREDENTIAL.

**Comment by gabrielwen** [comment]
It's intended behavior of `google-api-go-client`:
https://github.com/golang/oauth2/blob/9f3314589c9a9136388751d9adae6b0ed400978a/google/default.go#L61

**Comment by jlewi** [comment]
@gabrielwen Should we output a log message indicating that GOOGLE_APPLICATION_CREDENTIALS is set and that's the credential being used?

**Comment by gabrielwen** [comment]
Yea, I think so.  We shouldn't change expected behavior (e.g. unset ENV `GOOGLE_APPLICATION_CREDENTIALS`) as poeple might count on it.

**Comment by ChethanUK** [comment]
I have set both 
```
export CLIENT_ID=
export CLIENT_SECRET=
```
and followed https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

But got error: 
```
couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment mana
ger Error Set Cleared IamPolicy error: googleapi: Error 403: The caller does not have permission, forbidden
```

**Comment by gabrielwen** [comment]
`CLIENT_ID` and `CLIENT_SECRET` is for Oauth.  Your error is most likely because of `GOOGLE_APPLICATION_CREDENTIALS` env.  Could you try to set `export GOOGLE_APPLICATION_CREDENTIALS=` and see if it works?

**Comment by travishen** [comment]
In my case, my user account only has **PROJECT EDITOR** role, I think that's why I met **IamPolicy** error.
Tried getting a service account that has role **PROJECT OWNER**, then set  `GOOGLE_APPLICATION_CREDENTIALS` to its credential file. Apply kubeflow again, it works.

**Comment by smathalikunnel** [comment]
I am getting the same error. I have only PROJECT EDITOR rights on the project due to company policy. Is there anyway we can install kubeflow without PROJECT OWNER rights?

**Comment by ChethanUK** [comment]
> PROJECT EDITOR

Yes, you need to be a project owner or get the IAM Service account.

**Comment by smathalikunnel** [comment]
It is not feasible to grant PROJECT OWNER role directly for a user or service account due to security policies.

It would help if we could get the granular roles/permissions required, so that they can be granted to the user/service account.

**Comment by jocieA** [comment]
Hi, 
I'm using a service account with Project Owner role and my account is set Owner as well but i'm still getting this error when deploying kubeflow using the CLI (cloud shell):

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update storage-kubeflow.yaml: Updating kubeflow-test2-storage error(400): BAD REQUEST.

Any ideas why i'm still getting this error?

Thanks

**Comment by staturecrane** [comment]
I am also having this exact same problem, and I am a Project Owner.

**Comment by ChethanUK** [comment]
> and I am a Project Owner.

Oops, How did you try installing using UI?

**Comment by beatgeek** [comment]
I'm not clear on what the solution is here? It seems to be failing because it doesn't have permission to do a deployment manager update when I do have perms. We can't have Project Owner be the expectation.

**Comment by jlewi** [comment]
> couldn't apply KfApp: (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp: (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set Cleared IamPolicy error: googleapi: Error 403: The caller does not have permission, forbidden

The error is indicating there is a problem setting the IAM Policy. This requires owner permissions or IAM policy admin permissions. This is needed if you want kfctl to do things like create and install service accounts.

If you don't have sufficient permission to do that then you will either need to

1. Get someone with owner permissions to do that for you
1. Follow the instructions for installing on an existing K8s cluster (https://v0-5.kubeflow.org/docs/started/getting-started-k8s/)

    * This will skip GCP specific setup that requires elevated permissions
    * But it means we won't do things like setup service accounts, DNS, or IAP
    * So that would have to be setup separately

**Comment by vahidtz** [comment]
Hi, 
I am using CLI to deploy kubeflow on gcp. using kftcl to generate files: 

sudo kfctl generate all --zone us-central1-c

I got this error:

WARN[0000] Backfilling auth; this is deprecated; Auth should be explicitly set in Gcp plugin  filename="gcp/gcp.go:1733"
ERRO[0000] Could not configure IAP auth; environment variable CLIENT_ID not set  filename="gcp/gcp.go:1762"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp: Could not configure IAP auth; environment variable CLIENT_ID not set
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'


I already set the CLINET_ID environment variable but still, get this error.
