### ISSUE TITLE
[multi user] Set default Network Policy for user namespace

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3004]
By default, pods are non-isolated.
We should setup user namespace Network Policy so that pods only accept traffic from istio or from within same namespace.

**Comment by jlewi** [comment]
Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
Ref: http://bit.ly/k8s_tenant_crd

@kunmingg Is this P0? Is there a critical 0.6 feature that would be blocked by this?

I'm uncertain about what the correct/good default would be. Its possible the long term solution might be to just align with http://bit.ly/k8s_tenant_crd and go with whatever defaults they end up picking.

Some thoughts
* If we don't define the policy admins can always define it themselves.
* If we do define the policy then its possible we break something.

Some questions what does this provide beyond ISTIO?

* Do we end up injecting the ISTIO sidecar on all pods including TFJob pods?

/cc @kkasravi

**Comment by kunmingg** [comment]
Currently we turn on Istio isolation by default for user namespace, so will block unrecognized request by default. 
Will adjust priority.

**Comment by jlewi** [comment]
@kunmingg Should we punt to 0.7?
