### ISSUE TITLE
Fix e2e test for click-to-deploy

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3005]
We already have e2e test running periodically for click-to-deploy, with and without Istio.
https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml#L4-L28

But they are failing.

**Comment by jlewi** [comment]
@lluunn any update?

Is this blocked on getting click to deploy to reuse the kfctl logic which @kunmingg has PR #3045 for?

**Comment by lluunn** [comment]
yes, waiting for that and then we can fix the test

**Comment by jlewi** [comment]
@lluunn Is this still blocked? I think @gabrielwen is working on getting the new click to deploy up and running. Once that happens does that unblock this issue?

**Comment by lluunn** [comment]
Yeah, I think so.
