### ISSUE TITLE
Install Istio by default

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3007]
- finish e2e first
- for both kfctl and C2D, we can set install istio flag to true by default
- cleanup iap components (e.g. remove envoy service)

**Comment by jlewi** [comment]
@lluunn @gabrielwen It looks like there is an E2E test now for ISTIO. What is the remaining work to enable ISTIO by default?

**Comment by gabrielwen** [comment]
I've added bunch of params to prototypes:
https://github.com/kubeflow/kubeflow/blob/15aad9bf896a4c789909cf4d7af41d4819955bbc/kubeflow/katib/prototypes/all.jsonnet#L16

therefore we need to add those params to configs before we can actually turn on istio, I think: 
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config

**Comment by lluunn** [comment]
@gabrielwen I think that's for removing ambassador?
Installing istio in #3072

**Comment by gabrielwen** [comment]
oh, that's true if you want to separate them into 2 steps.

**Comment by gabrielwen** [comment]
@lluunn can we close this issue?

**Comment by lluunn** [comment]
C2D is not flipped yet.

**Comment by jlewi** [comment]
@lluunn What is C2D?

What is the remaining work blocking us from using ISTIO by default with kustomize?

**Comment by lluunn** [comment]
sorry: click to deploy
For kfctl it's already fixed.
@kunmingg what's the status for click-to-deploy sharing backend?

**Comment by jlewi** [comment]
#3045 is the PR to have click to deploy use kfctl as go libraries.

**Comment by jlewi** [comment]
Lets update the defaults for kfctl on master to be ISTIO+kustomize.

**Comment by jlewi** [comment]
It looks like we are still not setting the install istio flag to true by default
https://github.com/kubeflow/kubeflow/blob/5f1762a5a973d3441f010096357ba882f2c9386e/bootstrap/cmd/bootstrap/app/options/options.go#L68

We should probably also fix the description to be "use-istio" as opposed to install istio.

**Comment by jlewi** [comment]
It looks like the default for use_istio is now true.
https://github.com/kubeflow/kubeflow/blob/5f1762a5a973d3441f010096357ba882f2c9386e/bootstrap/cmd/kfctl/cmd/init.go#L176

```
./bootstrap/bin/kfctl init --help
Create a kubeflow application under <[path/]name>. The <[path/]name> argument can either be a full path
or a <name>. If just <name>, a directory <name> will be created in the current directory.

Usage:
  kfctl init <[path/]name> [flags]

Flags:
      --disable_usage_report     disable_usage_report disable anonymous usage reporting.
  -h, --help                     help for init
  -n, --namespace string         namespace where kubeflow will be deployed (default "kubeflow")
      --package-manager string   either 'ksonnet|kustomize[@version]' (default "ksonnet")
  -p, --platform string          one of 'gcp|minikube'
      --project string           name of the gcp project if --platform gcp
  -r, --repo string              local github kubeflow repo
      --skip-init-gcp-project    Set if you want to skip project initialization. Only meaningful if --platform gcp. Default to false
      --use_basic_auth           use_basic_auth use basic auth service instead of IAP.
      --use_istio                use_istio use istio for auth and traffic routing. (default true)
  -V, --verbose                  verbose output default is false
  -v, --version string           desired version of Kubeflow or master if not specified. Version can be master (eg --version master) or a git tag (eg --version=v0.5.0), or a PR (eg --version pull/<id>). (default "master")

```
