### ISSUE TITLE
Test the TFServing configs with default image

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#301]
We need a test to verify that the current TFServing component works with the default image.

The current E2E test builds a new TFServing image and then deploys and tests it.
This is great for testing a new Docker image, but it doesn't test the current default image works.

We should add options to the E2E workflow used for testing so that we can test TFServing without rebuilding the image.

**Comment by jlewi** [comment]
I think its fine in the short term to change our E2E workflow to not build the image and instead run the test using the current ksonnet configs.

This will work well for our release process because the flow will be

- Run the Argo workflow to build all our containers
- Update the configs
- Create a PR and run E2E tests.

Longer term it would be good if we had an E2E test that also rebuilt the docker image and to selectively trigger the E2E test when certain files (like the Dockerfile) are changed so we don't always rerun the test.

**Comment by jlewi** [comment]
It would probably make sense to make it a parameter of the current workflow to controller whether we rebuild the Docker image for TF serving and use that image or use the default image.

**Comment by lluunn** [comment]
Fixed by #383
