### ISSUE TITLE
Best practices for large data (GCS)

### ISSUE THREAD

**Issue by marrrcin** [kubeflow/kubeflow#3011]
It seems to me like there is little to no information about how to use Kubeflow to run ML Pipelines that consume large amounts of data stored in Google Cloud Storage.

Consider the following two cases:
1. A few GB of CSV files stored in GCS (let's say that they are partitioned by 100MB each)
1. A few TB of image data.

What is the best practice to consume this data?
Should I write the code on my own to download data in batches and feed it into my classifier (in the training code) or should I download this data once and persist it in some kind of volume?

**Comment by jlewi** [comment]
It really depends on what you are doing. Are you using TensorFlow? TensorFlow can read directly from GCS and it is optimized to read efficiently using the io utils in TensorFlow.


/cc @vicaire  @paveldournov

**Comment by marrrcin** [comment]
I have use cases for TensorFlow but I also have pipelines with XGBoost, PyTorch and scikit-learn based models. My question is more general.

**Comment by vicaire** [comment]
/cc @hongye-sun (who has been working on pipeline components to interact with GCP: https://github.com/kubeflow/pipelines/tree/master/component_sdk)

In the case of Tensorflow, @jlewi's solution would work well as the training algorithm would download the files from GCS in batches as needed (See the Youtube8M example: https://github.com/google/youtube-8m). 

A similar batch pattern could be implemented for other frameworks. In all cases, you can decide, depending on the specifics of your application, to either:
1. Download the data from GCS as the training algorithm is making progress. 
2. Download all the data to a local volume before starting training. 

Here are a couple links that could be useful depending on the framework: 
- TensorFlow: https://github.com/google/youtube-8m
- PyTorch: https://stanford.edu/~shervine/blog/pytorch-how-to-generate-data-parallel
- XGBoost: https://www.kaggle.com/c/grupo-bimbo-inventory-demand/discussion/22321
- Scikit-learn: https://scikit-learn.org/0.15/modules/scaling_strategies.html

**Comment by vkoukis** [comment]
@marrrcin 
>  Should I write the code on my own to download data in batches and feed it into my classifier (in the training code) or should I download this data once and persist it in some kind of volume?

We have been working on making the second option -- working with volumes -- as easy as possible with KF Pipelines. We have a PR pending for this, see kubeflow/pipelines#801.

Working with volumes does have a few advantages:
* Bringing the data to a local volume in one of the first steps means you won't need to write code to access object storage directly in the next steps of the pipeline, so your code becomes way simpler, execution is orders of magnitude faster, and you can use any generic  library that can access local files.
* If the system managing this volume supports snapshots, you can snapshot your volume and start your pipeline super quickly, by cloning this volume, without waiting for a separate data ingestion step.

**Comment by marrrcin** [comment]
OK, thanks @vkoukis . Looking forward for this PR to resolve!
