### ISSUE TITLE
healthy check URI is / instead of /healthz

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3014]
Please look at `path`:
![image](https://user-images.githubusercontent.com/4784270/56071803-a393a680-5d45-11e9-9451-bd1a804029ff.png)

**Comment by gabrielwen** [comment]
@lluunn please help triage this, thanks :)

**Comment by jlewi** [comment]
@gabrielwen Can you provide more context? Is this one of our CI clusters? How was this error produced?

**Comment by lluunn** [comment]
We have a job to update the healthcheck path to /healthz: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/update_backend.sh#L38

And our Istio setup is assuming it's /healthz for routing and also jwt check excludes that.

However, it seems that although that job finished without error, the health check path is still /
