### ISSUE TITLE
Include emacs in jupyter images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3016]
Should we add emacs to the Jupyter images?

Immediate use case for me is resolving conflicts when using git.

It looks like we have vi installed right now.

/cc @zabbasi @pdmack

**Comment by rohithreddy** [comment]
Hi @jlewi , I am interested in contributing, any pointers would help me

**Comment by jlewi** [comment]
I think @pdmack might already be on this one?

**Comment by jlewi** [comment]
@rohithreddy How about trying out SWIFT on Kubeflow #767?

**Comment by pdmack** [comment]
I haven't looked at this yet so still up for grabs.

**Comment by jlewi** [comment]
@rohithreddy interested?

**Comment by rohithreddy** [comment]
@jlewi yes, I am
