### ISSUE TITLE
Demo script for running Jupyter in a non-default namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3017]
At the multi-user discussion on Friday I think we decided to aim to do a demo of launching a notebook in a non Kubeflow namespace on 04/30.

I think the intent is to come up with a doc that lays out all the  kubectl & cloud commands a user would have to run to setup a new namespace and begin launching notebooks in it.

I think @zabbasi has been working on some instructions at least for GCP.

Here's the demo script from 0.5: http://bit.ly/05_mid_release_demo

I think we should take that script and continue to iterate on it.

/cc @zabbasi @kimwnasptd @vkoukis

**Comment by jlewi** [comment]
@zabbasi Has a website doc. WIll open up a PR and mark it WIP; blocked on UI allowing people to select namespace.

**Comment by jlewi** [comment]
@zabbasi What are the blocking issues to getting #3022 merged?

**Comment by zabbasi** [comment]
> @zabbasi What are the blocking issues to getting #3022 merged?

 #3000 needs to be resolved so that users are able to create notebook in other namespaces.

**Comment by zabbasi** [comment]
> > @zabbasi What are the blocking issues to getting #3022 merged?
> 
> #3000 needs to be resolved so that users are able to create notebooks in other namespaces.

**Comment by jlewi** [comment]
Looks like #3000 is merged; does this unblock #3022 ?

**Comment by zabbasi** [comment]
the demo script: https://bit.ly/2UOzzxB
