### ISSUE TITLE
kfctl use kustomize by default by 04/30

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3020]
Creating this issue to track changing kfctl to use kustomize by default.

I'd like to target 04/30 for using kustomize by default on master as opposed to ksonnet. This gives us 8 weeks to iron out all the kinks before cutting 0.6.

@hougangliu @swiftdiaries @kkasravi Does that date seem reasonable?

**Comment by kkasravi** [comment]
@jlewi yes, though with some caveats. 
- We need a good story on e2e tests
- We need to standardize existing manifests in PR #13. 
- The README.md in PR #13 needs to show what we're suggesting as a standard form. This similar to what we did in ksonnet.

**Comment by hougangliu** [comment]
@jlewi I think it's OK for me since I can focus on manifest project in coming two weeks.

**Comment by swiftdiaries** [comment]
@kkasravi We might need to simplify the kfctl implementation. 
We can for now pipe out the kustomize output to `kubectl` for apply and delete. Get something minimal in then iron out details and add the ksonnet like UX.
WDYT?

**Comment by kkasravi** [comment]
@swiftdiaries [kfctl](https://github.com/kubeflow/kubeflow/pull/2971) apply, delete - is working right now for kustomize w/o calling kubectl - what types of simplifications were you thinking of?

**Comment by swiftdiaries** [comment]
Oh cool. My bad 😅
I thought with the ksonnet like UX we might be strapped for time.

**Comment by jlewi** [comment]
@swiftdiaries @kkasravi How's this coming? What are the key blocking issues & PRs?

**Comment by jlewi** [comment]
@swiftdiaries @kkasravi ?

**Comment by jlewi** [comment]
@swiftdiaries @kkasravi Ping? What is the current status?

It looks like there are still problems deploying with kustomize #3020 and we don't have an E2E test yet #2630

**Comment by kkasravi** [comment]
https://github.com/kubeflow/manifests/pull/58 was finally merged earlier today. I'm now waiting on https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3108/kubeflow-presubmit/1127824924451278848/ which was dependent on https://github.com/kubeflow/manifests/pull/58. 

I think #3060 #3108 were also failing because manifests/#58

**Comment by jlewi** [comment]
Are the defaults on master using kustomize and ISTIO? If so can we close this issue?

**Comment by kkasravi** [comment]
yes, we can close

**Comment by jlewi** [comment]
The default still appears to be ksonnet not kustomize.

https://github.com/kubeflow/kubeflow/blob/5f1762a5a973d3441f010096357ba882f2c9386e/bootstrap/cmd/kfctl/cmd/init.go#L105

@ashahba Would you mind submitting a quick PR just to update the default please?
