### ISSUE TITLE
kfctl use ISTIO by default by 04/30

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3021]
Filing this issue to track the time by when we switch to using ISTIO as opposed to Ambassador by default.

I'd like to target 04/30. This would give us 8 weeks to then work out any kinks on master before cutting 0.6.

@gabrielwen @lluunn Does it seem reasonable to flip over to using ISTIO by default by 04/30?

**Comment by lluunn** [comment]
sgtm

**Comment by gabrielwen** [comment]
sounds reasonable to me.

**Comment by hougangliu** [comment]
@jlewi  in 0.6, will Ambassador be dropped or co-exist with Istio to proxy kubeflow UIs?

**Comment by jlewi** [comment]
@hougangliu the goal is to be migrated completely over to ISTIO

**Comment by gabrielwen** [comment]
@jlewi should we close this one?  ISTIO is by default now and this issue doesn't look like blocked by kustomize.
