### ISSUE TITLE
Under release 0.5.0, kfctl init fails with kubeconfig error.

### ISSUE THREAD

**Issue by babu-selector** [kubeflow/kubeflow#3024]
/go/src/github.com/estwo/s2cloud # kfctl init ${KFAPP} --platform gcp --project ${PROJECT}

WARN[0018] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0019] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0019] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0021] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0022] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0026] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0031] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0035] batch API enabling is running: [deploymentmanager.googleapis.com servicemanagement.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com endpoints.googleapis.com file.googleapis.com ml.googleapis.com iam.googleapis.com sqladmin.googleapis.com] (op = operations/acf.2c66d564-3939-4d34-8c2d-be694bd0d4a1)  filename="gcp/gcp.go:1594"
WARN[0048] could not open /root/.kube/config Error stat /root/.kube/config: no such file or directory  filename="apps/group.go:188"
WARN[0048] could not load config Error: open /root/.kube/config: no such file or directory  filename="apps/group.go:208"

**Comment by tarrade** [comment]
I got the same issue using GCP. The tricks was to create a cluster to have the `/root/.kube/config`  file created by using the following command: `gcloud container clusters create CLUSTER_NAME`. [stackoverflow](https://stackoverflow.com/questions/56525510/deploy-kubeflow-on-gcp-cloudshell-using-cli-home-user-kube-config-no-such-fi). (by the way I am using release 0.5.1)

**Comment by jlewi** [comment]
@babu-selector How are you running this? It looks like the code thinks you are root and it can't find your .kubeconfig file

```
WARN[0048] could not load config Error: open /root/.kube/config: no such file or directory filename="apps/group.go:208"
```

**Comment by elviraux** [comment]
Closing the issue as author hasn't replied in two month

**Comment by cyrilthank** [comment]
> I got the same issue using GCP. The tricks was to create a cluster to have the `/root/.kube/config` file created by using the following command: `gcloud container clusters create CLUSTER_NAME`. [stackoverflow](https://stackoverflow.com/questions/56525510/deploy-kubeflow-on-gcp-cloudshell-using-cli-home-user-kube-config-no-such-fi). (by the way I am using release 0.5.1)

can you please share a similar workaround step for running on Linux server?

**Comment by tarrade** [comment]
@cyrilthank I am not an expert but I understood that installing kubectl will create the .kube.config file, see here https://kubernetes.io/docs/tasks/tools/install-kubectl/. Hope this help

**Comment by cyrilthank** [comment]
Thanks for your patient reply
I am trying to use the microk8s option in the Linux Server section of https://www.kubeflow.org/docs/started/workstation/getting-started-linux/

Appreciate it if you can share any leads since I am now stuck
Thanks Cyril
    On Monday, September 16, 2019, 11:48:14 PM GMT+5:30, Dr. Fabien Tarrade <notifications@github.com> wrote:  
 
 
@cyrilthank I am not an expert but I understood that installing kubectl will create the .kube.config file, see here https://kubernetes.io/docs/tasks/tools/install-kubectl/. Hope this help

**Comment by cyrilthank** [comment]
solution in https://ubuntu.com/kubeflow/install
microk8s.kubectl config view --raw > $HOME/.kube/config
