### ISSUE TITLE
Broken link on Kubeflow deployment UI

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/kubeflow#3027]
On the Kubeflow deployment UI:
https://deploy.kubeflow.cloud/

There's a link to the docs that doesn't go anywhere useful. The link is currently:
https://www.kubeflow.org/docs/started/getting-started-gke/#create-oauth-client-credentials

The link should be:
https://www.kubeflow.org/docs/gke/deploy/oauth-setup/

The link is on the word "instructions" in the following text:

```
An endpoint protected by GCP IAP will be created for accessing kubeflow. Follow these instructions to create an OAuth client and then enter as IAP Oauth Client ID and Secret
```

**Comment by kunmingg** [comment]
Will be fix in next image update.
