### ISSUE TITLE
option naming inconsistencies

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#303]
In kubeflow-core options are named camel case e.g. "jupyterHubServiceType"
but in tf-serving options are name with under scores e.g. "http_proxy_image"
We should have consistent naming standard, should we adopt under score naming schemes for all three?

**Comment by jlewi** [comment]
It looks like the convention in ksonnet is camel case
https://github.com/ksonnet/parts/blob/master/incubator/mysql/prototypes/simple-mysql.jsonnet
https://github.com/ksonnet/parts/blob/master/incubator/redis/prototypes/redis-all-features.jsonnet

I suggest we follow that. I'll fix this for tfServing as part of #387.

We should probably document this in a style guide somewhere.

**Comment by jlewi** [comment]
TFServing Fixed by #387
