### ISSUE TITLE
kubeflow builder

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/kubeflow#3030]
For now, it's hard for beginners to use kubeflow components, such as creating a pipeline including HP tune, train, serving and so on.

Maybe we can add a new command or subdemand of kfctl to build a "init" version of kubeflow components. For example:
`kfctl build pipeline --with-katib --with-tfjob --with-serving` generates a pipeline framework python file including katib-laucher, tfjob-laucher and tf-serving  component and a pipeline join them together. Related parameters can be default value with comment above to tell user what it means.
For tfjob, studyjob, etc,  we can do similar builder, too.

I think if user wants to implement its own kubeflow resource (tfjob etc), this way can help user much than from scratch.

@jlewi WDYT?

**Comment by jlewi** [comment]
How does this compare to just providing YAML or python files that people can copy and paste to get started?

**Comment by gyliu513** [comment]
@jlewi I think adding kueflow builder can make life easier, such as for pipeline, we can let end user input some parameters and the kubeflow builder can generate the python framework of the pipeline automatically, and the file will include some comments like where should be updated and where should not etc, just like [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder).  

If we just give the end user some sample files, the end user may still need to check more for how to add their logic in, like adding new functions etc. But for kubeflow builder, only adding some main logic is good enough.

**Comment by kkasravi** [comment]
There is an interesting way to do this using [datadriven commands](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/0032-datadrivencommands.md) which would allow a Resource Driven command to be driven by server input. 
See the [PR](https://github.com/kubernetes-sigs/cli-experimental/pull/2)

This would allow a pipeline to be dynamically assembled on the client based on one or more CRDs published to a server

**Comment by jlewi** [comment]
@hougangliu @gyliu513 If you want a tool/sugar to make generating a basic pipeline for users should that be a feature of pipelines and separate from kfctl? I believe pipelines has it own CLI.

Similarly if other applications want to generate scaffolding; should they provide their own libraries and tools to do so? Or reuse existing tools like kustomize/helm when appropriate?

I think of kctl as optimizing the deployment of Kubeflow itself; not individual Kubeflow resources.

In keeping with a micro-service architecture I think we want lots of well focused applications; kfctl being one of them.

I worry that if kfctl becomes involved in generating templates for individual resources (TFJob, TFServing, StudyJob, Pipelines) it will end up becoming monolithic and impede progress.

I tend to think of the primary problem kfctl is trying to solve as generating, optimized Kubeflow configuration files for deploying Kubeflow applications as opposed to consuming Kubeflow applications.

I see creating pipelines, TFJob etc... as consuming Kubeflow applications.

Its possible in the long run the distinction between deploying and consuming applications might become blurred but right now I think its a useful distinction.

**Comment by gyliu513** [comment]
https://github.com/StefanoFioravanzo/kale

FYI @hougangliu @jlewi
