### ISSUE TITLE
Does the tf.Serving prototype automatically grab new model versions?

### ISSUE THREAD

**Issue by ianhellstrom** [kubeflow/kubeflow#3031]
The prototype for TensorFlow Serving requires a [model base path](https://www.kubeflow.org/docs/components/tfserving_new/). Does this mean the service that runs the saved model automatically swaps when a new TensorFlow model version is stored in the same base path, or does the base path have to point to a specific saved model (incl. auto-generated model version)?

It does not say so in the documentation. Apart from that the documentation is incorrect in listing `model_path` as a parameter. It's `modelBasePath`: https://github.com/kubeflow/kubeflow/tree/55ca2146e6689f2dfeefb9b8a6e32db4aed8ee7b/kubeflow/tf-serving

See: https://github.com/kubeflow/kubeflow/blob/55ca2146e6689f2dfeefb9b8a6e32db4aed8ee7b/kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet#L8

The TensorFlow Serving REST API documentation seems to indicate so: https://www.tensorflow.org/tfx/serving/api_rest#predict_api

Is there a grace period for this hot-swapping of models, i.e. how long is the old version still served when a new model becomes available?

**Comment by lluunn** [comment]
By default it will grab the new model.
E.g. if your base path is gs://bucket/mymodel/
and you have a first model gs://bucket/mymodel/1/saved_model.pb

When you upload the new model at gs://bucket/mymodel/2/saved_model.pb, TF serving will grab it.

For the grace period, I think TF serving should use the new model right after the loading is done, but I am not sure about the detail
