### ISSUE TITLE
StatefulSet needs ServiceName for Argocd validation

### ISSUE THREAD

**Issue by mcminis1** [kubeflow/kubeflow#3032]
Stateful sets need a service name to sync in Argocd.

There are 2 missing StatefulSet.serviceNames:
iap.libsonnet : backend-updater
webhook.libsonnet: webhook-bootstrap

**Comment by jlewi** [comment]
@mcminis1 Any interest in submitting a PR?

**Comment by mcminis1** [comment]
@jlewi PR has been created. Thanks.
