### ISSUE TITLE
Migrate E2E tests off ksonnet

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#3035]
E2E tests use ksonnet extensively. As part of ksonnet-turndown we'd like to migrate them to something else.

The current thinking is to use the k8s python client and Pipelines (or Argo). 
Ideas and directions are welcome.

Action Item:
- [ ] Migrate one test, confirm design

/cc @richardsliu

**Comment by jlewi** [comment]
@swiftdiaries Any update? Do you think we will get this down for 0.6?

What are you thinking of in terms of a replacement for ksonnet?

**Comment by jlewi** [comment]
Another idea we should look at is using [TektonCD](https://github.com/tektoncd/pipeline/blob/master/docs/README.md#learn-more) as opposed to Argo.

I think one of the advantages of TektonCD Is that has [Task resource](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md) with well defined inputs & outputs.

We could use Task resources to break up our tests into reusable tasks. e.g.

* We could have separate tasks to deploy Kubeflow on minikf and GCP
* We could have separate tasks to run tests e.g. 1 task to verify notebooks is working another to verify katib
* We could then easily combine the tasks into different pipelines testing different combinations.


Here's how I think this might work

* We could rely on python functions to spit out the TektonCD pipelines we need to run

  * This way we can leverage python to do whatever substitution we need based on various parameters.

* We could modify our [prow_config.yaml](https://github.com/kubeflow/testing/blob/1009294940b2d873cc811f68eb6093eef474cf85/prow_config.yaml#L4) files to take a list of python functions to invoke; something like

   ```
   pipelines:
       - py_func: package.module.class.method_name
         kw_args:
             arg1: value
   ```

* Modify [run_e2e_workflow.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py) to submit and wait for the Tekton workflows in addition to the Argo workflows.

**Comment by texasmichelle** [comment]
Related task to update existing documentation. It would also be helpful to have a guide for adding a new test. The learning curve for the current setup is steep, so my vote is migrating to something that optimizes for ease of getting started, which will encourage ppl to actually write them. It's tough to enforce tests for new code when I don't have a comprehensible guide to point them to.

**Comment by jlewi** [comment]
I filed some more specific bugs.

kubeflow/testing#423 is the main one. Once that is fixed we can start moving tests off ksonnet.

Once we have moved a single repo off ksonnet we can file individual bugs for the other repositories.
