### ISSUE TITLE
Navigation within iframes should reflect to dashboard’s URL

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3042]
Currently, the URL does not change when a user navigates through different areas of iframed KF pages such as KF Pipelines. This behavior prevents usage of the back button and also makes it impossible to copy a link that navigates directly to the page the user is viewing.

As the iframed page URL changes, its state should be reflected as clearly as possible in the parent URL of the KF dashboard.

**Comment by prodonjs** [comment]
@avdaredevil What are your thoughts on how we can handle this in a generic way? Some pages (ie. Notebooks server hub) will do a full refresh which we could detect with a `load` event but others like Pipelines will use client-side routing. We could add something to the library we are developing to publish a message on route change, but that's not necessarily simple since there's no standard event for location change that we could listen for, so we'd be forcing others to use something.

The crude approach would be to set some kind of interval on the iframe's location object. I can't think of anything better that would be purely event driven at the moment.

**Comment by avdaredevil** [comment]
Let's make 2 assumptions
- This functionality will only be provided to SDK enabled sub-apps
- Default apps will act in a non-PWA fashion
  - We can, therefore, listen on unload events
  - If they're smart (ie. pipelines), they'll manually enable routing like:
    ```js
    sdk.disableRouting()
    window.attach('when-custom-event', _ => {
        sdk.setHref(href)
    }) // Oversimplification of event handling
    ```

**Comment by prodonjs** [comment]
I think those are fair assumptions. The other thought I had was to bind a handler to the `click` event anywhere inside the iframe's body and evaluate the URL for changes there. I believe that would work, but it does go against the idea of the iframe page being the initiator for communication. However, for this use case, I'm inclined to accept the idea of the dashboard owning the responsibility of monitoring the state of its children. It would certainly expedite the roll-out period. Let's discuss later today.
