### ISSUE TITLE
host of istio route rule uses hardcode cluster-domain

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/kubeflow#3046]
I notice that host of istio route rule for multiple services of kubeflow component is like $servicename + $namespace + ".svc.cluster.local" in multiple PR, such as #3013 #3028 #3033 #3036

However `.cluster.local` can be set as a different value for k8s cluster with `cluster-domain` option.
I think $servicename + $namespace + ".svc" is enough.

@gabrielwen WDYT?

**Comment by gabrielwen** [comment]
from [here](https://github.com/istio/api/blob/6b8d1849e7f44ef523b4442af69b57ddc960d38b/networking/v1alpha3/virtual_service.proto#L330) it seems it's either short name (e.g. service name) or fully qualified name.  Kunming and I tried to use `service name` + `namespace` but ISTIO couldn't resolve it correctly.  Therefore I doubt `service name` + `namespace` + `.svc` would work.  I could try to see if it works if you think we should, tho.

**Comment by hougangliu** [comment]
> from [here](https://github.com/istio/api/blob/6b8d1849e7f44ef523b4442af69b57ddc960d38b/networking/v1alpha3/virtual_service.proto#L330) it seems it's either short name (e.g. service name) or fully qualified name. Kunming and I tried to use `service name` + `namespace` but ISTIO couldn't resolve it correctly. Therefore I doubt `service name` + `namespace` + `.svc` would work. I could try to see if it works if you think we should, tho.

From the link, it seems we should use full path name. But as mentioned above,  hardcode `.cluster.local` is a potential issue. How about add a param named `clusterDomain`, if `clusterDomain` set, use it. Otherwise use "cluster.local" by default

**Comment by gabrielwen** [comment]
> > from [here](https://github.com/istio/api/blob/6b8d1849e7f44ef523b4442af69b57ddc960d38b/networking/v1alpha3/virtual_service.proto#L330) it seems it's either short name (e.g. service name) or fully qualified name. Kunming and I tried to use `service name` + `namespace` but ISTIO couldn't resolve it correctly. Therefore I doubt `service name` + `namespace` + `.svc` would work. I could try to see if it works if you think we should, tho.
> 
> From the link, it seems we should use full path name. But as mentioned above, hardcode `.cluster.local` is a potential issue. How about add a param named `clusterDomain`, if `clusterDomain` set, use it. Otherwise use "cluster.local" by default

Yea, agree.  I'm thinking about the same thing :)

**Comment by gabrielwen** [comment]
Pending PRs are updated.
