### ISSUE TITLE
Does kfctl need to build the Application resource dynamically?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3047]
This is a follow on to #2971.

One of the issues that came up in that review is whether we need to dynamically modify the Application resource defining Kubeflow. Here's the code
https://github.com/kubeflow/kubeflow/blob/665134ecfe799c5377fac8b5ce26a13c34221717/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L208

Currently the application resource is dynamically setting the list of componentkinds in Kubeflow.

The question in the review is whether we need to generate the componentkinds dynamically or if we could just have kustomize manifest for the application that lists the componentkinds as a superset of all component kinds in Kubeflow.

**Comment by kkasravi** [comment]
we no longer do this.
