### ISSUE TITLE
Does Kubeflow have functionality to terminate a run?

### ISSUE THREAD

**Issue by clj2567** [kubeflow/kubeflow#3048]

**Comment by jlewi** [comment]
@clj2567 Can you provide more information about what you mean? Do you mean a pipeline run?

**Comment by clj2567** [comment]
@jlewi Yes. Aborting a pipeline run. Say there is some issue during training and we want to abort the run. Is there any way to do it now?

**Comment by jlewi** [comment]
@paveldournov @vicaire @IronPan do you know the answer? I'm guessing a user could always try to find and delete the underlying Argo workflow.

**Comment by paveldournov** [comment]
There is an API and a UI element to stop the workflow in KF Pipelines. 
To stop the workflow execution from within the pipeline itself - you can use a conditional operator.

**Comment by clj2567** [comment]
@paveldournov Could you please direct me to a link to the API or UI element? I have looked for it but I didn’t find one .

**Comment by vicaire** [comment]
@clj2567, it is possible that you need to upgrade to the latest release of Kubeflow/pipeline. 

Here is the API to terminate a run: https://github.com/kubeflow/pipelines/blob/master/backend/api/run.proto#L116

The UI supports this feature as well. 

Adding @rileyjbauer who worked on this feature.

**Comment by clj2567** [comment]
@vicaire Thank you for pointing me in the right direction. But according to this releases, I maybe wrong, but I saw that it has only been merged into the master but no release.

**Comment by vicaire** [comment]
Got it. We usually have a weekly release so hopefully it should be
available by the end of the week. Thanks!

**Comment by paveldournov** [comment]
This has been implemented.
