### ISSUE TITLE
ImagePullBackOff for kube-metacontroller

### ISSUE THREAD

**Issue by matthen** [kubeflow/kubeflow#3055]
I am running kubeflow v0.3, and just found that kube-metacontroller is down with the following error event:

```
Failed to pull image "gcr.io/enisoc-kubernetes/metacontroller@sha256:18561c63e1c5380ac5bbaabefa933e484bdb499f10b61071506f9a0070bc65f6": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/enisoc-kubernetes/metacontroller@sha256:18561c63e1c5380ac5bbaabefa933e484bdb499f10b61071506f9a0070bc65f6 not found
--
```

is there a known solution to this? Thanks!

**Comment by jlewi** [comment]
I think v0.3 is using a very old version of kube-metacontroller and an outdated image. The updated ksonnet package is here
https://github.com/kubeflow/kubeflow/tree/v0.5-branch/kubeflow/metacontroller

The current image is here:
metacontroller/metacontroller:v0.3.0

You can try just substituting in the image; but I think other changes were needed to upgrade metacontroller. Your best bet is probably to upgrade to Kubeflow 0.5.

**Comment by matthen** [comment]
Thanks for the advice
