### ISSUE TITLE
BuildConfigFromClusterInfo returns config with wrong identity

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3061]
https://github.com/kubeflow/kubeflow/blob/de1fc808b40f58e4bbb7199fedb68df29d412c98/bootstrap/pkg/utils/gcputils.go#L60

See this issue for more info.
https://github.com/kubeflow/kubeflow/issues/3049

**Comment by jlewi** [comment]
Is this still relevant?
Was this code only used with ksonnet?
