### ISSUE TITLE
build kfctl binary for windows

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3073]
From @avdaredevil , we need to set env var:
```
GOOS=windows
GOARCH=amd64
```

However, with this I got 
```
go: github.com/Sirupsen/logrus@v1.4.1: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
make: *** [generate] Error 1
```

unset the env vars the build will succeed.
@r2d4 do you have experience building windows binary?

**Comment by r2d4** [comment]
These are the cross platform makefile rules I've written to cross compile go binaries

https://github.com/GoogleContainerTools/skaffold/blob/master/Makefile#L52-L74

**Comment by avdaredevil** [comment]
Any status on this folk?

**Comment by sxmon** [comment]
In my $GOPATH and in the kubeflow folder, I used
`grep -rlI Sirupsen . | xargs sed -i 's/Sirupsen/sirupsen/g'`

Then I did `go get .` in ~/kubeflow/bootstrap/cmd/kfctl. And kfctl works.

**Comment by avdaredevil** [comment]
Thanks, @sxmon this worked!!

@lluunn could we add this to our release process?

**Comment by lluunn** [comment]
@kunmingg @zhenghuiwang 
Can we add a windows binary to 0.6.0 and/or 0.6.1?
