### ISSUE TITLE
Notebooks-Controller in v0.5 error StatefulSet blockOwnerDeletion, PVC issue openShift 3.11

### ISSUE THREAD

**Issue by shalberd** [kubeflow/kubeflow#3086]
![grafik](https://user-images.githubusercontent.com/21118431/56578416-eec37a00-65cd-11e9-8ca0-1b250b09cf2d.png)
```
oc logs notebooks-controller-7c96f657b8-458h9
{"level":"info","ts":1556018940.2371798,"logger":"controller","msg":"Creating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"error","ts":1556018940.2386813,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"notebook-controller","requestkubeflow/tf-test-1","error":"statefulsets.apps \"tf-test-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Starunc1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUn.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Jittetil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\o/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1556018941.2389545,"logger":"controller","msg":"Creating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"error","ts":1556018941.2405286,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"notebook-controller","requestkubeflow/tf-test-1","error":"statefulsets.apps \"tf-test-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Starunc1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUn.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Jittetil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\o/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1556018942.240873,"logger":"controller","msg":"Creating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"error","ts":1556018942.2425103,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"notebook-controller","requestkubeflow/tf-test-1","error":"statefulsets.apps \"tf-test-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Starunc1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUn.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Jittetil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\o/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
```
OKD 3.11

**Comment by shalberd** [comment]
It seems that when I edit notebooks-controller role to include /finalizers
´´´
oc edit clusterrole notebooks-controller
 apiGroups:
  - kubeflow.org
  attributeRestrictions: null
  resources:
  - notebooks
  - notebooks/finalizers
  - notebooks/status
´´´
I get further.
´´´
{"level":"error","ts":1556025816.5004294,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"notebook-controller","request":"kubeflow/tf-test-1","error":"Operation cannot be fulfilled on statefulsets.apps \"tf-test-1\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1556025817.5007472,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556026560.9149659,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556027106.0057442,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556027902.0195415,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556028428.055287,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556029329.135413,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556029792.1582708,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556030733.2664132,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556031472.336848,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556031992.3668256,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556032569.4281855,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
{"level":"info","ts":1556033077.4742665,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"tf-test-1"}
´´´
Hoever, then, the persistent volume claim is not created, Status wheel on notebook servers web ui keeps spinning.
´´´
oc describe pod tf-test-1-0
Name:               tf-test-1-0
Namespace:          kubeflow
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             controller-revision-hash=tf-test-1-68dd6f6467
                    gcp-cred-secret=user-gcp-sa
                    gcp-cred-secret-filename=user-gcp-sa.json
                    notebook-name=tf-test-1
                    statefulset=tf-test-1
                    statefulset.kubernetes.io/pod-name=tf-test-1-0
Annotations:        openshift.io/scc=anyuid
Status:             Pending
IP:
Controlled By:      StatefulSet/tf-test-1
Containers:
  tf-test-1:
    Image:      gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0
    Port:       8888/TCP
    Host Port:  0/TCP
    Requests:
      cpu:     1
      memory:  35Gi
    Environment:
      NB_PREFIX:  /notebook/kubeflow/tf-test-1
    Mounts:
      /home/jovyan from tf-test-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jupyter-notebook-token-dpn9x (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  tf-test-1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  tf-test-1
    ReadOnly:   false
  jupyter-notebook-token-dpn9x:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jupyter-notebook-token-dpn9x
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  1m (x11307 over 2h)  default-scheduler  persistentvolumeclaim "tf-test-1" not found
´´´

**Comment by rbo** [comment]
Have the same problem with the finalizer.

@ kubeflow folks, it is ok to add `notebooks/finalizers` at this point: 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/notebook_controller.libsonnet#L149 if so I would like to create pull request.

For my openshift deployment I did a lot of stuff that kubeflow/jupyter is working:
```
oc adm policy add-scc-to-user anyuid -z jupyter -n $K8S_NAMESPACE
oc adm policy add-scc-to-user anyuid -z jupyter-notebook -n $K8S_NAMESPACE
oc adm policy add-scc-to-user anyuid -z jupyter-hub -n $K8S_NAMESPACE

# https://github.com/kubeflow/kubeflow/issues/3086
oc patch --type=json clusterrole notebooks-controller -p '[{"op":"add", "path":"/rules/-", "value":{"apiGroups":["kubeflow.org"],"resources":["notebooks/finalizers"],"verbs":["*"]}}]'
```
and some more for the other components.

**Comment by shalberd** [comment]
Minio, Katib and mysql can grab PVCs frpm PVs just fine
´´´
oc get pvc
NAME             STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
katib-mysql      Bound     vol7      45Gi       RWO,RWX                       17h
minio-pvc        Bound     vol5      45Gi       RWO,RWX                       17h
mysql-pv-claim   Bound     vol13     45Gi       RWO,RWX                       17h
´´´
How come the notebook controller cannot? This worked in 0.4, but not now in 0.5

**Comment by rbo** [comment]
@shalberd all my stuff is documented here: https://github.com/rbo/RedHatHackathon-KubeFlow-Demo - but I'm working on v0.5. Trying to run the github-issue-summery demo. Important parts : https://github.com/rbo/RedHatHackathon-KubeFlow-Demo/blob/master/deployer/kubeflow-deploy.sh

**Comment by shalberd** [comment]
@rbo Thank you very much for your deployment script of kubeflow 0.5 on openShift.
I am using OKD, local hostPath storage, e.g. 20 PVs of size 45GB (not the 200 of 500 GB as in Grant Shipleys demo):
https://github.com/gshipley/installcentos/blob/master/vol.yaml

**Comment by shalberd** [comment]
StorageClass Setup worked well, one by one, PVCs and associated PVs show up
A StorageClass solution would be something like hostPath on all the nodes.

# on each node, data directory, free to choose, e.g. /var/kubernetes
mkdir -p /var/kubernetes
# SELinux Label
chcon -Rt svirt_sandbox_file_t /var/kubernetes

Then use a hostPath provisioner StorageClass like (first three yamls) here:
https://github.com/MaZderMind/hostpath-provisioner

oc create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/rbac.yaml
oc create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/deployment.yaml (edit storage location if needed)
oc create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/storageclass.yaml (in kubeflow namspace)
