### ISSUE TITLE
TFJob Dashboard is not support pvc

### ISSUE THREAD

**Issue by alienxt** [kubeflow/kubeflow#3093]
Hi all,
   When submitting several TFjobs, I need add cephfs pvc, I can't choose pvc option.

I am using kubeflow v0.5.0.

**Comment by lcax200000** [comment]
i use nfs  storageClass & Volumes
I have the same problem
how could i  use it 
![image](https://user-images.githubusercontent.com/9493082/57360747-810e7500-71ad-11e9-9067-1f63eb0d8ab3.png)
