### ISSUE TITLE
How to use own jupyter image with GPU-Support

### ISSUE THREAD

**Issue by hno2** [kubeflow/kubeflow#3095]
Hey there, 

I tried building my own Image for Jupyter, but I can not get GPU support (with microk8s) working. 
With the "stock" tensorflow images everything works fine, but with my own image i get this error:
<details>

` Error: failed to create containerd task: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/snap/microk8s/522/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=GPU-9d3d06a1-5c8d-eaf7-e876-af7fcce34360,GPU-511b2f83-6562-01c3-ff75-241bb96a27c2 --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=29418 /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/ksg7fe-notebook/rootfs]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown`

</details>

I have a cards with CUDA 10 support and a recent driver installed.
<details>

```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 28%   27C    P8    11W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 28%   27C    P8     3W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 28%   28C    P8    21W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:83:00.0 Off |                  N/A |
| 28%   27C    P8     1W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```
</details>

**Comment by yylin1** [comment]
Try to use an older version of Jupyter Images.

**Comment by jlewi** [comment]
Looks like there is a bug here:
https://github.com/kubeflow/kubeflow/blob/89a41ecb287237c5a947c361d27a62f48e07f6c3/components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json#L2

The base image isn't a gpu image.

We should be using an nvidia cuda image as the base image.
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/versions/1.12.0gpu/version-config.json

Anybody want to submit a fix?

**Comment by jlewi** [comment]
Can you share your Dockerfile? 

What are you using as the base image?

/cc @carmine

**Comment by hno2** [comment]
It seems like cuda 10.1 was not supported by my graphics card. When using the cuda10.0 base image i have no problems. You can check out my Dockerfile enclosed.
[Dockerfile](https://github.com/kubeflow/kubeflow/files/3158945/Dockerfile.txt)
