### ISSUE TITLE
On Premise Auth Requirements

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#3096]
This is a master issue to track all requirements and proposed solutions to enable Authentication and Authorization in on-premise systems. Here are some broad level features we are looking forward to integrating with Kubeflow as a part of our on-premise CUJ:

1. Auth provider integration for on-premise setup: 
    1. Select an Open Source Project as an Auth provider and integrate it with our current Istio based Auth system.
2. AD/LDAP integration with auth provider.
    1. The above Auth Provider should be able to import identities from an AD/LDAP database.
3. Granular access control to all resources and operations in Kubeflow.
    1. Each resource or operation needs to be identified in Kubeflow’s components
4. Role Based Access Control for each user:
    1. Each user identified needs to have a set of policies implemented to restrict their usage of each resource or operation.
    2. Users can be clubbed into larger user groups.
5. A user-friendly UI for setting up RBAC accesses to users.
6. Integration of data centre (on-premise) resources or operations with Kubeflow user actions.
    1. In the future, we may need to provide the option of provisioning more nodes to a cluster admin or namespace admin.
    2. We may need to limit which user can run a particular workload in a namespace or cluster.

We would request you to add your own inputs to this requirement.

**Comment by krishnadurai** [comment]
Design proposal for addressing the above requirements:

http://bit.ly/2WPs1MS

**Comment by jlewi** [comment]
@krishnadurai I thought there were some ongoing questions, discussions about http://bit.ly/2WPs1MS ?

In particular I thought there was an open question whether or not to create a KF API gateway through which all requests were redirected or instead to directly rely on the underlying systems (ISTIO, K8s) and there are associated access control mechanisms.

Where did we land on this question?

/cc @kkasravi @vkoukis

**Comment by krishnadurai** [comment]
@jlewi 
We've chosen to have Istio act as the gateway for all these requests. We've added this discussion to the [document](https://docs.google.com/document/d/1WS9l45oIbWfxRWNQeisI3NIXfcIh0l9aHN_Fl3MQreU/edit#heading=h.dg6520664o64).

**Comment by jlewi** [comment]
@elviraux How come this is P0? If its P0 someone that means its release blocking and ideally someone should be assigned to it. The fact that the issue was marked stale suggests its not P0 since no one is actively working on it.  

@krishnadurai What is the work for 0.7 and was it the priority?

**Comment by elviraux** [comment]
@jlewi yeah, it's the same thing as we discussed in email. I will change p0 to p1 wherever I marked as p0 as I now know the criteria of p0 :)
