### ISSUE TITLE
upgrade_ks_app.py is not python3 compatible

### ISSUE THREAD

**Issue by JohnPaton** [kubeflow/kubeflow#3098]
Since python2 is nearly EOL it would be better to have this script work with python3.

**Comment by jlewi** [comment]
A PR would certainly be welcome.

On the other hand we will hopefully be migrated off ksonnet long before we hit python2 EOL.

**Comment by JohnPaton** [comment]
Oh really? Is there a roadmap document about that? I'd be very interested. 

I'll take a look at it but my experience with ksonnet is limited to this project so it's a bit of a catch-22 for me

**Comment by jlewi** [comment]
Most of the discussion happened in this thread:
https://groups.google.com/forum/#!searchin/kubeflow-discuss/ksonnet%7Csort:date/kubeflow-discuss/Zg14_Ok7XH4/GSPrle1tCwAJ

Here's the doc about kutomize
http://bit.ly/kf-kustomize

**Comment by JohnPaton** [comment]
Thanks for the links! The kustomize doc was very enlightening, I'm checking out kustomize now!

**Comment by naveen24691** [comment]
Is there anything pending to do here? I would like to extend it, if required.

**Comment by JohnPaton** [comment]
This issue has been fixed now, thanks for the reminder, it should be closed. 

From discussions with the team it sounds like putting effort into ksonnet-related scripts isn't really a priority since ksonnet itself is on its way out.

**Comment by naveen24691** [comment]
I agree. Thanks for the response
