### ISSUE TITLE
Document specs for a "reasonable" starter cluster

### ISSUE THREAD

**Issue by geojaz** [kubeflow/kubeflow#31]
Clearly, this is highly dependent on what we have available for folks to run. 

I repurposed a tiny GKE cluster (n1-standard-1 with autoscaling from 1-5 nodes). I was able to apply the manifests in components successfully, but wasn't able to schedule my model-server pods due to resource limitations. It looks like the bare minimum for the model server pods is a full CPU and a gig of ram- and they would be happy to get more. 

I think we should document a recommended minimum cluster config to get through these demos.

**Comment by jlewi** [comment]
Yeah. I'd probably suggest at least 8 CPU machine.
