### ISSUE TITLE
[Proposal] Distributed Julia Operator

### ISSUE THREAD

**Issue by cblackd7r** [kubeflow/kubeflow#3112]
Motivation
Julia is a high-level general-purpose dynamic programming language designed for high-performance numerical analysis and computational science.   Basic linear algebra, matrix computation, and differential equations in Julia is fast.   As machine learning systems become more complex, researchers increasingly need differentiable languages in which they can simply write their algorithms as code. Julia’s mathematical syntax makes it an ideal way to express algorithms just as they are written in academic papers.  

Goals
The Kubernetes Operator for Julia would enable scheduling of julia with GRPC and a distributed runtime that can be deployed with Kustomize, providing a scalable and programatic way to run Julia ML training and experimentation on K8S and Kubeflow via custom resource controller.

**Comment by jlewi** [comment]
@cblackd7r Do you have an existing repo with an initial version? Is that repo public or could it be made public?

Or would you be starting from scratch?

**Comment by cbbba18** [comment]
@jlewi We have started from scratch, and are currently in sprint 1.   Looking to have a zero dot release in a number of weeks and will look to convert repo to public with initial release.

**Comment by cblackd7r** [comment]
@jlewi We have started from scratch, and are currently in sprint 1. Looking to have a zero dot release in a number of weeks and will look to convert repo to public with initial release.

**Comment by jlewi** [comment]
@cblackd7r Any update on this? Are you still working and planning on delivering a Julia operator?

**Comment by jbottum** [comment]
@cblackd7r Hey Chris, what is your timeframe on this?

**Comment by brilhana** [comment]
Any pointers on how to implement this? I'd like to work on it.

**Comment by onetonfoot** [comment]
I'd also be interested in helping out on this
