### ISSUE TITLE
kfctl documentation does not cover platform argument

### ISSUE THREAD

**Issue by kweinmeister** [kubeflow/kubeflow#3118]
The [kfctl documentation](https://master.kubeflow.org/docs/started/getting-started-k8s/) does not cover the `platform` argument. It says that each command can accept either `k8s` or `all`. It would also be helpful to discuss the platform options, such as `aws`, `azure`, and `gcp`. 

It might make sense to create a separate `kfctl` reference page, which is linked from the Getting Started page.

**Comment by jlewi** [comment]
@kweinmeister Any interest in submitting a PR? 

Also do you mean `kfctl` and not `kfctl.sh` since with 0.5 we switched to the go binary rather than the shell script.

**Comment by kweinmeister** [comment]
@jlewi Sure, I will submit a PR for this. And, you're right, I meant `kfctl` -- I changed the issue accordingly.
