### ISSUE TITLE
Lock down cluster before we get backendID

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3122]
We apply the JWT check policy after getting the backendID:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/setup_backend.sh#L59

There might be a gap that unauthorized users can access the cluster.
We can deploy the policy with ingress, and then update it with correct backendID later.

cc @jlewi @gabrielwen

**Comment by kunmingg** [comment]
@lluunn Can we close?
