### ISSUE TITLE
Central Dashboard UI Cutoff in Firefox

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kubeflow#3129]
Kubeflow: v0.5.0
Firefox: 66.0.2 (64-bit) on Linux Mint
![kubeflow-firefix-centraldashboard-cutoff](https://user-images.githubusercontent.com/10563075/56852392-f313ce00-6912-11e9-94d0-9453a001bce9.png)

Anyone else?

**Comment by 0xE282B0** [comment]
The same problem exists with Firefox Quantum 66.0.3 (64-Bit) on macOS Mojave 10.14.4:

<img width="1351" alt="Bildschirmfoto 2019-04-28 um 00 33 03" src="https://user-images.githubusercontent.com/4034494/56855770-49056780-694d-11e9-9182-49b68f2e5ad8.png">
