### ISSUE TITLE
Consider including a scanned PyPI package mirror component

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#313]
In discussion of container security issues related to having root https://github.com/kubeflow/kubeflow/issues/300 the primary vector assuming trusted users seemed to be malicious third-party code. We could either

1. Put on the roadmap (probably as a low priority) a component for a scanned PyPI package mirror, or
2. Determine this as out of scope.

Related to https://github.com/kubeflow/kubeflow/issues/300

**Comment by jlewi** [comment]
Are you suggesting Kubeflow maintain a PyPI mirror of approved packages?

**Comment by cwbeitel** [comment]
I'm suggesting we illustrate a mechanism by which people can run and scan a PyPI mirror in their own cluster, not to run a public service for mirroring and scanning PyPI. But if there was such a public service being offered by the cloud provider on which a given Kubeflow deployment were running that would be one incentive to use that provider.

Initially it seems sufficient to use something like GCR's vulnerability scanning on the base workspace image.

To me this seems like an out-of-scope need just wanted to mention it for discussion.
