### ISSUE TITLE
"kfctl apply k8s" fails to deploy scheduledworkflows on mac 

### ISSUE THREAD

**Issue by 0xE282B0** [kubeflow/kubeflow#3130]
Hi, I'm trying to install Kubeflow on "Docker for mac with K8s" with these instructions from the [documentation](https://www.kubeflow.org/docs/started/getting-started-k8s/).

### Environment
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Kubeflow has been downloaded from https://github.com/kubeflow/kubeflow/releases/tag/v0.5.0
```
kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
```
The version number is confusing for a release.
### Issue
To install Kubeflow I used the following commands:
```
export KFAPP=kubeflow
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate k8s 
kfctl apply k8s
```

kfctl returned the following error message:
```
ERRO[0061] (Will retry) Component pipeline apply failed; Error: handle object: creating object: creating object: CustomResourceDefinition.apiextensions.k8s.io "scheduledworkflows.kubeflow.org" is invalid: spec.version: Required value  filename="ksonnet/ksonnet.go:174"
```

### Workaround
Edit the files `ks_app/vendor/kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet` and `ks_app/vendor/kubeflow/pipeline/pipeline-viewercrd.libsonnet` from the generated folder and  add the line ` version: "v1beta1",` to crd.spec.

```
...
   crd: {
      apiVersion: "apiextensions.k8s.io/v1beta1",
      kind: "CustomResourceDefinition",
      metadata: {
        name: "scheduledworkflows.kubeflow.org",
      },
      spec: {
        version: "v1beta1",
...
```

### Expected behaviour
`kfctl generate k8s´ creates a valid configuration

**Comment by jlewi** [comment]
/assign @IronPan 

Could you submit a fix and cherry pick to the v0.5-branch?

I wonder why this doesn't seem to affect everyone?

@0xE282B0 What version of K8s are you using?

**Comment by 0xE282B0** [comment]
@jlewi I'm using docker desktop for mac and it comes with a K8s v1.10.11
![Bildschirmfoto 2019-05-17 um 17 16 34](https://user-images.githubusercontent.com/4034494/57938054-93806100-78c7-11e9-898a-23e32855b865.png)

**Comment by IronPan** [comment]
The CRD API is using new K8s CRD multi-version API which is supported in v1.11 and after. 
Here is more context
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresources-versioning.md

The workaround looks good for earlier version.
