### ISSUE TITLE
Opening "+NEW SERVER" page gives 500 error

### ISSUE THREAD

**Issue by ryangrahamnc** [kubeflow/kubeflow#3131]
Been messing with kubeflow on a baremetal kubernetes server the past few days, during which time kubeflow notebook creation was working fine. Ended up deleting kubeflow and creating again (because I was switching from storageos to rook-ceph volumes), and now I'm getting a 500 error when I try to open the "create new server" page.

Procedure followed:
```
cd ~/fun/kflow # dir with kfctl bin

export PATH=$PATH:$(pwd)
export KFAPP=app3

kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V

# wait for kube to have all pods running
# wait a bit more (noticed mysql takes a minute or two to get databases bootstraped even after pods are in running state)

kubectl port-forward -n kubeflow svc/ambassador 8080:80


visit http://localhost:8080/_/notebooks

click "+ NEW SERVER"

Get 500 error.
```
![image](https://user-images.githubusercontent.com/1237156/56856781-f36e9200-692f-11e9-9912-caed0fb7d508.png)

How do I debug this? Looking at the ambassador logs, I only see a 500 happened, but no debug info about what caused the 500.
`ACCESS [2019-04-28T01:16:49.501Z] "GET /jupyter/new?namespace=kubeflow HTTP/1.1" 500 - 0 290 12 11 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "49b67615-d926-4413-bf51-8f76fa7d157b" "localhost:8080" "10.99.108.154:80"`

Tried a few different times to get it running. Waiting from minutes to hours each time to see if i just needs a little while to work. Also made sure I had everything deleted inbetween tries by running:
`kubectl get --all-namespaces notebooks,pytorchjobs,scheduledworkflows,studyjobs,tfjobs,viewers,workflows`
, which returned no results.

Maybe there are serviceaccounts/role/etc or something I need to nuke? i.e. a new serviceacct gets created with new important data, but it fails because the name's already taken?

Heres some other deets:
```
$ ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
And I'm using rook-ceph for volumes. The first time I got it running (when I had notebooks creating properly) I was using storageos for volumes, so the volume switch is a potential cause. But rook-ceph is working fine for me for other volumes, plus all the kubeflow pods successfully made it to `running` state, so I cant think of a reason it would be the problem.

**Comment by kimwnasptd** [comment]
hi @ryangrahamnc, could you also post the logs from the `jupyter-web-app` pod?
you could get them with this command:

**Comment by ryangrahamnc** [comment]
Yup, that got me something I can work with.
```
[2019-04-28 12:04:36,437] ERROR in app: Exception on /new [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 136, in new_notebook
    if api.get_default_storageclass() != "":
  File "/app/kubeflow_jupyter/common/api.py", line 105, in get_default_storageclass
    is_default = annotations.get(key, False)
AttributeError: 'NoneType' object has no attribute 'get'
192.168.0.227 - - [28/Apr/2019 12:04:36] "GET /new?namespace=kubeflow HTTP/1.1" 500 -
```

Looks like it is volume related. Just checked the storageclasses, and the storageos one was recreated even though I deleted its namespace/controllers. Therefore it would probably fail on any call that goes to it. Nuked it and now the page loads.
Thanks!

**Comment by jomach** [comment]
@ryangrahamnc How did you fixed it ? I have the same problem.

**Comment by ryangrahamnc** [comment]
I had a storageclass that was "corrupt". So I deleted it. It was pretty much my fault because I was creating/destroying storageclasses the day before and forgot to completely clean up.

**Comment by jomach** [comment]
@ryangrahamnc 
So I have this storage class: 
`microk8s-hostpath (default)   microk8s.io/hostpath   37d

$ kubectl describe storageclass microk8s-hostpath
Name:            microk8s-hostpath
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"microk8s-hostpath"},"provisioner":"microk8s.io/hostpath"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           microk8s.io/hostpath
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>`

I'm kind of new to this storageclasses. Do I need to configured the Jupyter to use the proper storage class oder is something wrong with my storage class ?

**Comment by jomach** [comment]
I think I will re-deploy the whole thing via master instead of v0.5.0 which I think this patch is not there.

**Comment by xxf09th** [comment]
@jomach @ryangrahamnc  Hi, I meet the same issue. This Error is caused by checking the annotations of your storageClass. If annotations is null, you will get this error. So just add some annotations to your storageClass, and it will pass.

**Comment by Eric-Zhang1990** [comment]
@xxf09th  I meet the same issue, but error is:
[2019-07-17 07:14:39,716] ERROR in app: Exception on /new [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 161, in new_notebook
    form_defaults = utils.spawner_ui_config("notebook")
  File "/app/kubeflow_jupyter/common/utils.py", line 33, in spawner_ui_config
    c = f.read().format(username=username)
KeyError: 'notebook-name'
10.244.1.17 - - [17/Jul/2019 07:14:39] "GET /new?namespace=kubeflow HTTP/1.1" 500 

can you tell me what your storageClass is? Thank you.

**Comment by kimwnasptd** [comment]
@Eric-Zhang1990 about month ago we updated the jupyter-web-app's code and the config file it uses. From the `KeyError: 'notebook-name'` in the log I can see that you use the the new config.yaml from that update. But, the line in the backend that produces the error is from an older jupyter-web-app image. 

Could you try to redeploy the jupyter-web-app from the manifests repo which has the newest changes?

**Comment by Rohithzr** [comment]
@kimwnasptd 
I am using `helm install stable/efs-provisioner` as my storageClass, I also tried EBS-GP2, but I am getting the below error
```
 [2019-07-23 05:11:37,312] ERROR in app: Exception on /new [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/kubeflow_jupyter/default/app.py", line 136, in new_notebook
    if api.get_default_storageclass() != "":
  File "/app/kubeflow_jupyter/common/api.py", line 105, in get_default_storageclass
    is_default = annotations.get(key, False) 
```

I am using 
> kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e

**Comment by pavelzhurov** [comment]
I've met the same issue with the storage class and found a flaw in the code which causes this issue. (I used kubeflow v0.5.3, but found this bug in the latest 0.5 version)
In the components/jupyter-web-app/kubeflow_jupyter/common/api.py there is a function:
```
def get_default_storageclass():
  strg_classes = storage_api.list_storage_class().items
  for strgclss in strg_classes:
    annotations = strgclss.metadata.annotations
    # List of possible annotations
    keys = [
        "storageclass.kubernetes.io/is-default-class",
        "storageclass.beta.kubernetes.io/is-default-class"  # GKE
    ]
    for key in keys:
      is_default = annotations.get(key, False)
      if is_default:
        return strgclss.metadata.name
  # No StorageClass is default
  return ""
```
`annotations` variable can be None, and if the default storage class is not the first in the list, this code will try to get "key" from it and won't handle the following exception.
In order to fix this, you just need to provide this annotation to all of your storage classes. You can do it with:
`kubectl patch storageclass <your-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`
