### ISSUE TITLE
error in "kfctl.sh generate all"  

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/kubeflow#3132]
+++++++++++++++++++++++++++++++++++++++++++
**environment:**
system: windows10
kubernetes: minikube v1.0.0
kuberflow version: v0.5.0

**Reference tutorials**：
https://v0-4.kubeflow.org/docs/started/getting-started-minikube/

++++++++++++++++++++++++++++++++++++++++++++

When I execute the command :
    ` ../kfctl.sh generate all`

**there is an error:**

+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ GKE_API_VERSION=v1beta1
+ GCP_DEFAULT_ZONE=us-east1-d
+++ dirname ../kfctl.sh
++ cd ..
++ pwd
+ DIR=/e/workspace/minikube_kubeflow/scripts
+ source /e/workspace/minikube_kubeflow/scripts/util.sh
+ source /e/workspace/minikube_kubeflow/scripts/gke/util.sh
++ set -xe
+ source /e/workspace/minikube_kubeflow/scripts/azure/util.sh
++ set -xe
+ source /e/workspace/minikube_kubeflow/scripts/aws/util.sh
++ set -xe
+ source /e/workspace/minikube_kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ INPUT=()
+ FORMAT=()
+ export 'KUBEFLOW_COMPONENTS="ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
+ KUBEFLOW_COMPONENTS='"ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
+ export KUBEFLOW_EXTENDEDINFO=false
+ KUBEFLOW_EXTENDEDINFO=false
+ which envsubst
+ [[ 2 -lt 2 ]]
+ COMMAND=generate
+ WHAT=all
+ shift
+ shift
+ main
+ [[ generate == \i\n\i\t ]]
+ source env.sh
++ PLATFORM=minikube
++ KUBEFLOW_REPO=/e/workspace/minikube_kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_COMPONENTS='"ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
++ KUBEFLOW_EXTENDEDINFO=false
++ KUBEFLOW_KS_DIR=/e/workspace/minikube_kubeflow/scripts/myApp/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ DOCKER_REGISTRY_KATIB_NAMESPACE=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_PLATFORM=minikube
++ MOUNT_LOCAL=false
++ DEPLOYMENT_NAME=myApp
+ [[ -z generate ]]
+ [[ -z all ]]
+ check_installed_deps
+ kf_deps=("ks" "kubectl")
+ declare -a kf_deps
+ kf_dep=ks
+ min_ks_ver=0.11.0
++ ks version
++ cut '-d ' -f3
++ head -1
+ ks_ver=0.13.1
+ '[' 0.13.1 '<' 0.11.0 ']'
+ [[ minikube == \g\c\p ]]
+ [[ minikube == \a\z\u\r\e ]]
+ [[ minikube == \a\w\s ]]
+ [[ generate == \g\e\n\e\r\a\t\e ]]
+ [[ all == \p\l\a\t\f\o\r\m ]]
+ [[ all == \a\l\l ]]
+ [[ minikube == \g\c\p ]]
+ [[ minikube == \a\z\u\r\e ]]
+ [[ minikube == \a\w\s ]]
+ [[ all == \k\8\s ]]
+ [[ all == \a\l\l ]]
+ createKsApp
+ pushd .
/e/workspace/minikube_kubeflow/scripts/myApp /e/workspace/minikube_kubeflow/scripts/myApp
++ dirname /e/workspace/minikube_kubeflow/scripts/myApp/ks_app
+ cd /e/workspace/minikube_kubeflow/scripts/myApp
++ basename /e/workspace/minikube_kubeflow/scripts/myApp/ks_app
+ eval ks init ks_app --skip-default-registries
++ ks init ks_app --skip-default-registries
INFO Using context "minikube" from kubeconfig file "C:\\Users\\wangwenxiao01/.kube/config"
INFO Creating environment "default" with namespace "default", pointing to "version:v1.14.0" cluster at address "https://xxx.xxx.xxx.xxx:8443"
INFO Generating ksonnet-lib data at path 'E:\workspace\minikube_kubeflow\scripts\myApp\ks_app\lib\ksonnet-lib\v1.14.0'
+ cd /e/workspace/minikube_kubeflow/scripts/myApp/ks_app
+ ks env rm default
INFO Deleting environment "default" with metadata at path "E:\\workspace\\minikube_kubeflow\\scripts\\myApp\\ks_app\\environments\\default"
INFO Successfully removed environment 'default'
+ ks registry add kubeflow /e/workspace/minikube_kubeflow/kubeflow
ERROR initializing helm HTTP client: normalizing Helm repository URL: "e" is an invalid scheme for Helm repository

It should be noted that "e" means E disk of my computer. 

How to solve this problem?

**Comment by jlewi** [comment]
Unfortunately windows isn't very well supported these days. We would love contributions in this area. Any interest in trying to fix this and submit a patch?

@vkoukis Is MiniKF better tested on Windows then Minikube?

Alternatively, could you try deploying Kubeflow on public cloud?

/cc @aronchick

**Comment by vkoukis** [comment]
@jlewi @jokerwenxiao @aronchick 
> @vkoukis Is MiniKF better tested on Windows then Minikube?

Hey Jeremy,

Windows is one of the platforms we test every single MiniKF release with, and it should work out of the box. We are definitely interested in anything breaking or not working exactly as it should with it.

**Comment by akilman** [comment]
Hitting the same on OSX 10.14.4 w/ ksonnet installed:

```
$ ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

**Comment by nagautier** [comment]
Having the same issue with ksonnet installed, tried latest release and compiling manually.
```
ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```
```
kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
```
 On Unbuntu 18.04 with minikube.

**Comment by soumentrivedi** [comment]
this is how i fixed it,

ks init kfapp # created a ksonnet project
kfctl init kfapp # initialises kf manifests
cd kfapp # changing into kfap directory
kfctl generate all -V

i hope this works for you.

**Comment by ishantanu** [comment]
Same issue on Kubernetes cluster created via kind/AWS.

Any resolution?

**Comment by elviraux** [comment]
Seems to be fixed, closing
