### ISSUE TITLE
GKE util with basic auth still requires client id

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#3136]
This is related to https://github.com/kubeflow/kubeflow/pull/2687 , but  the shell scripts need updating too.

**Comment by jlewi** [comment]
Do you mean kfctl.sh? The shell scripts are deprecated and no longer really supported for GCP. People should switch to using the go binary.

**Comment by holdenk** [comment]
Interesting, maybe we should print out the deprecation warning? I'll try this with the go binary :)
