### ISSUE TITLE
kubeflow-images-public/tensorflow-2.0.0a0-notebook-gpu failed to start on Kubeflow jupyterhub

### ISSUE THREAD

**Issue by chenglinzhang** [kubeflow/kubeflow#3141]
I downloaded the tensorflow-2.0.0 alpha0 docker image with:
```
docker pull gcr.io/kubeflow-images-public/tensorflow-2.0.0a0-notebook-gpu:v-base-2a92ca1-1121928672001921024
```
to run under Kubeflow 0.4 Jupyterhub. 

The image failed to start. ```kubectl log jupyter-username-x -n kubeflow-namespace-y``` prints the following error:
```
[FATAL tini (8)] exec start-singleuser.sh failed: No such file or directory
```

**Comment by yylin1** [comment]
This PR are fixed images: 

- fixed based images of tf gpu notebooks #3117 

But I found in `gcr.io/kubeflow-images-public` images has not been updated.

- [tensorflow-2.0.0a-notebook-gpu](https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-2.0.0a-notebook-gpu@sha256:eec16b5451e76f27ab460a322cdb254a5c7e33a486e6eec7061038314bc84d12/details?tab=info) 
- [ tensorflow-1.13.1-notebook-gpu](https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-1.13.1-notebook-gpu@sha256:eb4a69f65b00926fc3d0848b780b7fa74b2fa9d2f9587714650aaf3ff32f8297/details?tab=info)

@jlewi need your help to upload fixed Dockerfile in `gcr.io` Images.

**Comment by shalberd** [comment]
The GPU images first had an Ubuntu base image, but that was fixed. Now, we all are anxiously waiting for the images to be pushed to gcr.io. Those sorts of errors like wrong base images in the build process should be caught much earlier, in my opinion.

**Comment by jlewi** [comment]
The latest images are designed to work with Kubeflow 0.5 which doesn't use JupyterHub.

If you need to use an earlier version of Kubeflow which is using JupyterHub you need to use the images associated with that release.

**Comment by jlewi** [comment]
@zabbasi and @pdmack Are we not building our Jupyter images automatically and pushing to gcr.io/kubeflow-images-public?

**Comment by pdmack** [comment]
Thought that was done by our infra?

**Comment by yylin1** [comment]
@jlewi @pdmack 
I'm trying Notebook in kubeflow v0.5 when use old image (tensorflow-2.0.0a & 1.13.1), can successfully create. But have clicked `CONNECT` will jump to kubeflow Home UI. 

Maybe is fixed in PR #3117 .

**Comment by zabbasi** [comment]
Postsubmit test is supposed to build the images.  However the postsubmit for #3117 is failed. 
/assign zabbasi

**Comment by zabbasi** [comment]
Built the images, tested  and retag them to v0.5.0.
