### ISSUE TITLE
no matches for kind "VirtualService" error occur when deploy kubeflow

### ISSUE THREAD

**Issue by liu-sheng** [kubeflow/kubeflow#3145]
I have deployed a k8s cluster by `kubeadm` with version `1.14.1`, and then try to deploy kubeflow follow the [guide documentation](https://www.kubeflow.org/docs/started/getting-started-k8s/), when I run `kfctl apply all -V`, I got the error:
```
ERRO[0196] (Will retry) Component centraldashboard apply failed; Error: handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch733127502": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"  filename="ksonnet/ksonnet.go:174"
```

**Comment by jlewi** [comment]
Are you deploying from master?

Master requires ISTIO. Did you install ISTIO in your cluster?

**Comment by jlewi** [comment]
Per #3159 it looks like kfctl on v0.5.0 may be using manifests on master by default. You might need to

to pass --version=v0.5.0 to kctl init

**Comment by liu-sheng** [comment]
@jlewi yes, thanks :) I have added `-v v0.5.0` to kctl init to make this issue fixed.

**Comment by cyrilthank** [comment]
I am hitting this error with kfctl version kfctl v0.6.2-0-g47a0e4c7

can you please advise?

**Comment by jlewi** [comment]
@cyrilthank Please open a new issue since you are using a different version of Kubeflow its a different issue. Please include the commands you ran and the log output.
