### ISSUE TITLE
Location of dockerfile for each of the kubeflow jupyter docker images

### ISSUE THREAD

**Issue by gracechristina** [kubeflow/kubeflow#3147]
Hi,

Where can I find the dockerfile for each of the docker images provided in jupyterhub.
For example:
gcr.io/kubeflow-images-public/tensorflow-1.4.1-notebook-cpu:v0.5.0

I would like to know what are the packages installed in each of the images as it will make it easier to decide which docker image to use for the jupyter pod. Thank you.

**Comment by yylin1** [comment]
You can find it here. 
https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image/versions
