### ISSUE TITLE
Update MiniKF to work with ISTIO and Kustomize for 0.6

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3150]
0.6 will introduce ISTIO and Kustomize.

Filing this issue to track updating the MiniKF deployment.

/cc @kimwnasptd @vkoukis @ioandr

**Comment by jlewi** [comment]
@kimwnasptd @vkoukis Is there anymore work to be done here? Does MiniKF support 0.6?

**Comment by jlewi** [comment]
I think @katsiapis mentioned at the community meeting that MiniKf still needs to be released with 0.6 support but that it should happen soon.

**Comment by jlewi** [comment]
@kimwnasptd @yanniszark Any update on this?

**Comment by vkoukis** [comment]
We are now testing a Kubeflow 0.6-based MiniKF box, we expect to release it by the end of the week. I'll be back with updates, so we can close this issue.

**Comment by jbottum** [comment]
MiniKF 0.6 was delivered today
