### ISSUE TITLE
Update AWS deploy to use ISTIO and Kustomize for 0.6

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3151]
0.6 will introduce ISTIO and Kustomize.

Filing this issue to track updating the AWS deployment instructions

/cc @Jeffwan

**Comment by jlewi** [comment]
Bumping to P0. P0's are release blocking. I think we want to have a story for continuing to deploy on AWS before we finalize the first 0.6 release.

**Comment by jlewi** [comment]
ping?

**Comment by Jeffwan** [comment]
@jlewi Just come back from vacation.. manifest changes are almost done. I will send out PR this week.

**Comment by jlewi** [comment]
@Jeffwan Sounds great. We are coordinating the release on #release if you can try it out on AWS and report any issues that would be great.

**Comment by jlewi** [comment]
It looks like #3695 was cherry-picked onto the v0.6-branch.

@Jeffwan Should we close this issue now or wait for an RC and verify it is working?

**Comment by Jeffwan** [comment]
@jlewi I think we can close it for now. All basic support has been added and cherry-picked back to 0.6. For improvement and bug fix. I will submit separate PRs and we don't need issue to track it.
