### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3159]
* change v0.5 (and future release) kfctl default version from master to v0.5.1

**Comment by kunmingg** [comment]
master head could be broken at any time.
We should use release version as kfctl default version.
@jlewi 
@gabrielwen

**Comment by lluunn** [comment]
what fixes do we need for 0.5.1?

**Comment by gabrielwen** [comment]
current problem is disparity where CLI binary is built with v0-5-branch but using data in master.  We could make the change but in the meantime kustomize should also be considered as it's in different repository now (manifests).  Should we also make branches in manifests?

**Comment by kunmingg** [comment]
We can create release tag(v0.6) on manifests during next release.
For v0.5 we won't support kustomize.

**Comment by lluunn** [comment]
So we just need to change this to 0.5 at 0.5 branch right?

**Comment by gabrielwen** [comment]
Yes: https://github.com/kubeflow/kubeflow/pull/3170

**Comment by lluunn** [comment]
After that, need to update kfctl binary

**Comment by gabrielwen** [comment]
#3170 merged.  should we update the release?

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/releases/tag/v0.5.1

**Comment by tyrsius** [comment]
[This PR](https://github.com/kubeflow/kubeflow/pull/2983) added some functionality for AWS Cluster deployment, which wasn't in 0.5.0 but was in master. Now that master doesn't point to itself, the docs on using the `--awsClusterName` flag are incorrect.

**Comment by tyrsius** [comment]
Some of the AWS features introduced in [This PR](https://github.com/kubeflow/kubeflow/pull/2983) were broken on master by this change. All of the arguments to `kfctl.sh init` use default values, regardless of what is passed in. This wasn't happening on yesterday's master.

**Comment by lluunn** [comment]
Is it related to 0.5.1?
The change here doesn't touch master.
Do you want to file a separate issue to describe?

**Comment by tyrsius** [comment]
Hmm, perhaps its not. Ill open another issue

**Comment by Jeffwan** [comment]
Let me know if anything I can help for aws related changes.

**Comment by jlewi** [comment]
Closing this issue because 0.5.1 has been cut
