### ISSUE TITLE
Configure storage class using kfctl

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#3163]
Configure storage class and kfctl to use a storage class by default for some components (pipelines: minio, mysql, katib: mysql)

**Comment by posix4e** [comment]
I would love to be able to have a different storage class on azure, to get notebooks to work on read/write/many mounts

**Comment by swiftdiaries** [comment]
@posix4e I'm ccing in people from Azure 
/cc @ritazh @sozercan
