### ISSUE TITLE
Auth provider integration for on-premise setup

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#3166]
Select an Open Source Project as an Auth provider and integrate it with our current Istio based Auth system.

https://github.com/kubeflow/kubeflow/issues/3096

**Comment by yanniszark** [comment]
In the `existing_arrikto` platform, we have integrated [Dex](https://github.com/dexidp/dex) with the Istio Gateway, using an AuthService.
This way, we provide the full OIDC flow, not just the JWT validation that Istio currently supports.
Is there anything else to do for this issue?

Refs:
* https://github.com/kubeflow/kubeflow/pull/3538
* https://www.kubeflow.org/docs/started/getting-started-k8s/#Kubeflow-for-Existing-Clusters---by-Arrikto

**Comment by johnugeorge** [comment]
See https://github.com/kubeflow/kubeflow/issues/3162#issuecomment-514701515

**Comment by elviraux** [comment]
closing, dex is chosen
