### ISSUE TITLE
No response when click 'Spawn' button on creating notebook servers.

### ISSUE THREAD

**Issue by kaka11chen** [kubeflow/kubeflow#3168]
I installed the kubeflow release v0.5.0 successfully. But when I access the web ui to create a notebook server, there is no response when click 'Spawn' button on creating notebook servers.

From the jupyter-web-app logs, it returned http 400 status code.
Then I found jupyter-web-app in kubeflow release v0.5.0 used 'latest' version. I guess the image which is 'latest' version I pulled is change something, then I modified the version to jupyter-web-app:v0.5.0, it works.

**Comment by zabbasi** [comment]
From code, it looks like  branch v0.5-branch points to the right image. https://github.com/kubeflow/kubeflow/blob/v0.5-branch/kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet

**Comment by kaka11chen** [comment]
@zabbasi 
Setup document url: 
https://www.kubeflow.org/docs/started/getting-started-k8s/
Kubeflow releases: https://github.com/kubeflow/kubeflow/releases/download/v0.5.0/kfctl_v0.5.0_linux.tar.gz

**Comment by zabbasi** [comment]
@kaka11chen Thanks. Will take a look why latest image is picked up in your cluster. Meanwhile created a pr to set the image in master to a stable image https://github.com/kubeflow/kubeflow/pull/3177

**Comment by lluunn** [comment]
i think kfctl 0.5.0 still deploys master by default @kunmingg @gabrielwen .
We are fixing that.

In the meantime, if you pass --version=v0.5.0 when `kctl init`, it should be 0.5

**Comment by kaka11chen** [comment]
@lluunn That's correct. I tried to pass --version=v0.5.0 when `kctl init`, then the version is v0.5.0.

**Comment by jlewi** [comment]
#3159 is tracking a v0.5.1 release.

**Comment by jlewi** [comment]
@kaka11chen Did setting `--version` fix it for you?

**Comment by gabrielwen** [comment]
#3170 changes v0.5 default to v0.5.0.  could someone with write access update releases?

**Comment by kaka11chen** [comment]
@jlewi Yes.
