### ISSUE TITLE
TFJobs web app should respect namespace in Central Dashboard

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3178]
Sibling of #2845 
Depends on #2926 

TFJobs UI code is at https://github.com/kubeflow/tf-operator/tree/master/dashboard

/area front-end
/area centraldashboard
/assign @avdaredevil 
/assign @prodonjs 
/priority p2

**Comment by avdaredevil** [comment]
This is no longer valid, as we've deprecated as of #3424
