### ISSUE TITLE
TF Serving

### ISSUE THREAD

**Issue by sh0gg0th** [kubeflow/kubeflow#3180]
Where can I find an example of input.json mentioned [here](https://www.kubeflow.org/docs/components/tfserving_new/):

`curl -X POST -d @input.json http://EXTERNAL_IP:8500/v1/models/mnist:predict`

Thanks!

**Comment by scottilee** [comment]
@sh0gg0th I found an [example](https://15905978862850875460.googlegroups.com/attach/2a06b42ad69f3/input.json?part=0.1&view=1&vt=ANaJVrH-Bssm1DIzPu6P5OyF-RF3tBdz2guFP4D-DCUbGXc9JBeOBrygFwqUREUaapuHmbvKOefGEN_WqqgH3nOUmT6h3sH1ZH7sPi-HQ8AILT7C-pLcBeY) from https://www.lightbend.com/blog/how-to-deploy-kubeflow-on-lightbend-platform-openshift-kubeflow-model-serving.

**Comment by sh0gg0th** [comment]
@scottilee awesome, thank you!
