### ISSUE TITLE
secrets "user-gcp-sa" not found

### ISSUE THREAD

**Issue by yarongol** [kubeflow/kubeflow#3188]
I have deployed kubeflow on GCP using the UI (https://www.kubeflow.org/docs/gke/deploy/deploy-ui/). Used basic authentication rather than oauth
At which point I started following the instructions for an end to end flow (https://www.kubeflow.org/docs/gke/gcp-e2e/)
I got to the point where I call "kubectl describe secret user-gcp-sa"
and get an error "secrets "user-gcp-sa" not found"
(and indeed when I train the model I get a permission error  "kubeflow2-vm@xxxx.iam.gserviceaccount.com does not have storage.buckets.get access to xxxx-kubeflow2-bucket.")

evidently this secret was not created during the UI-based deployment. Is there a way to re-create it without starting from scratch? Should I be using the cli rather than the UI in order to deploy?

Thanks

**Comment by jlewi** [comment]
The secret should have been created.

Can you run 

```
kubectl -n ${NAMESPACE} get secrets
```

Are you running in the kubeflow namespace.

You can recreate the secret by downloading a service account key using gcloud or the UI and then creating a K8s secret. Something like

```
  gcloud --project=${PROJECT} iam service-accounts keys create ${FILE} --iam-account ${EMAIL}

  kubectl create secret generic --namespace=${K8S_NAMESPACE} ${SECRET} --from-file=${SECRET}.json=${FILE}
```

/cc @kunmingg

**Comment by yarongol** [comment]
Thank you. I re-run some of the instructions and it somehow fixed itself. I have the secret now.
