### ISSUE TITLE
large .pack file

### ISSUE THREAD

**Issue by inc0** [kubeflow/kubeflow#319]
One of our git .pack files is huge - almost 100MB. This is due to having whole model merged in repo at some point. It would be nice to surgically remove this file from git history to shrink our .pack files.

**Comment by rongou** [comment]
You can try this: https://rtyley.github.io/bfg-repo-cleaner/

I did it on my fork, it reduced the repo size from 112MB to 15MB. See https://github.com/rongou/kubeflow.
