### ISSUE TITLE
 why my ambassador always CrashLoopBackOff？

### ISSUE THREAD

**Issue by JK-97** [kubeflow/kubeflow#3198]
![企业微信截图_15569585032537](https://user-images.githubusercontent.com/16853338/57176353-a6d40b00-6e89-11e9-9893-b76cbc4acb32.png)

**Comment by jlewi** [comment]
What are are the logs for Ambassador pod?

**Comment by gokuatkai** [comment]
Hello, using v0.5.1 and EKS and docs default deployment command and I have the exact same situation
my ambassador container logs are:

```
AMBASSADOR: starting Envoy
AMBASSADOR: waiting
PIDS: 25:diagd 26:envoy 27:kubewatch
starting hot-restarter with target: /ambassador/start-envoy.sh
forking and execing new child process at epoch 0
forked new child process with PID=28
got SIGCHLD
PID=28 exited with code=1
Due to abnormal exit, force killing all child processes and exiting
exiting due to lack of child processes
AMBASSADOR: envoy exited with status 1
```
with the config lof output

and vizier logs are
```[mysql] 2019/06/07 13:26:43 packets.go:36: unexpected EOF```

Let me know if you need anything else

**Comment by Jeffwan** [comment]
@gokuatkai This is because https://github.com/kubeflow/kubeflow/issues/3259#issuecomment-492814792

current v0.5.1 still use incompatible istio version. I need to cherry-pick one change to v0.5.1.
