### ISSUE TITLE
Suggestion for task context class (for run/task metadata recording) 

### ISSUE THREAD

**Issue by yaronha** [kubeflow/kubeflow#3199]
following a discussion with @jlewi , incorporating the best from various model/experiment/workflow DBs i examined, and review we did with customers i would like to suggest a mechanism for recording tasks metadata ( tasks can be: runs, model inference, data processing, ..) , see below draft definitions we can further discuss them in the issue or Slack.

i believe it can provide a generic, robust, and complete mechanism for managing metadata and tracking various types of runs, this can also replace/enhance the way `pipline` track/passes metadata and artifacts between steps. it can coexist with current `pipline` args approach (e.g. automatically convert args to params or the other way around).

once we agree on such concept we can start implementation in a modular way.

# Task Context Object

the task context provide required configuration and properties to the task 
and records various logs, metrics, and outputs/artifacts.

task context is initialized by the task runtime (notebook, container, workflow, function, ..),
and can change per run. task context is tracked in a persistent database and can be viewed in a UI. 

## Properties 

    properties used by the task:
    name       - task name (not unique) 
    parent     - parent name/id (e.g. workflow/experiment name/id for runs) 
    par_type   - parent type (project, experiment, ..) 
    uid        - task unique ID 
    user       - user name who created/owns that task 
    log_level  - desired logging level (debug, info, warn, error)
    data_in    - fixed/tmp/mounted directory-path used as root for input data/artifacts
                 this allow providing files as inputs to a run, the files may be the 
                 result of a previous workflow step, can be sym linked, or loaded from objects.
                 defaults to current work/file dir.
    data_out   - directory-path/object-url used as root for writing artifacts
                 the output dir may be unique per run and eliminate the need for copies
                 and avoid overwriting data from previous runs 
                 defaults to current work/file dir.
    params     - a dictionary of input parameters for this task (string or number)
                 may be loaded/overwritten from argv cli input 
    secrets    - a dictionary of protected string values (e.g. passwords, tokens, ..) 
    labels     - a key/value list of labels 
    
    additional properties which are stored in the DB: 
    source     - source type, name, version/commit-hash
    secret_src - secret source/type, name (e.g. k8s secret and its name)
    start_time - when this task started 
    end_time   - when this task ended
    status     - current status of this task  
    artifacts  - a dictionary of artifact names and paths 
    results    - a dictionary of result parameters (value metrics)
    metrics    - a dictionary of result series (list/time-series metrics) 

note all the properties are read-only when accessed from a task.

## Methods (accessed from the task)

    logger                  
    - logger object (e.g. logger.debug('some debug'))
    
    get_param(key, default)
    - return the parameter, if doesnt exist return the default
    
    log_value(key, value)
    log_values(dict)
    - set a result parameter(s)
    
    log_metric(key, value, time/int, optional labels/flags)
    log_metrics(dict, time/int, optional labels/flags)
    log_metric_array(key, x_values, y_values)
    - set one or more metric values (extra labels can be used for time-series DBs) 
    
    log_artifact(key, local path, optional target path/url, optional type)
    - record an output as an artifact, if its not in the data_out path it will be 
      copied there, if relative/abs target path is specified it will override the defaults.
    
    log_all(values, metrics_map, artifacts)
    - batch mechanism to store all output in a single operation (less DB calls)

## Usage example 

```python
ctx = get_run_context(something)
with open(ctx.data_in + 'cfg.json') as fp:
    cfg =  json.load(fp.read())
conn = db_connect(url, ctx.secrets['user'], ctx.secrets['password'])    

ctx.logger.info('starting run {} ({})'.format(ctx.name, ctx.uid))
# run something 

ctx.log_value('accuracy', 7)
ctx.log_metrics('loss', history['loss'], epochs)
ctx.log_artifact('chart', 'chart.png')

```

**Comment by jlewi** [comment]
@zhenghuiwang @vicaire @karthikv2k  Can you take a look? I think this is most relevant to the various python libraries we are writing.

**Comment by zhenghuiwang** [comment]
@yaronha Thanks for the suggestion! It makes a lot of sense.

We plan to use `execution` to capture the same concept as `task`. [Here](https://github.com/kubeflow/metadata/blob/master/schema/alpha/docs/execution.md) is the initial definition of execution. We should add some of these properties here into it.

The method section is about Python library to log the metadata, which we have a plan but haven't started.

/cc @neuromage

**Comment by yaronha** [comment]
@zhenghuiwang @jlewi  i noticed the work, it seems quite extensive, include multiple classes and abstractions, will take time to agree on, develop and debug. 

IMO we should think about a staged approach, the model above is similar to [mlflow](https://mlflow.org/) with additional aspects of KFP etc. and addresses the essential requirements. it allow a simple mechanism to track the tasks/executions and pass along critical metadata & secrets in a in a runtime independent way (i.e. can run in the notebook, cli, container, function w/o env dependencies).

BTW i assume another key table is the parent e.g. `experiment` table, and those two can be a good start and easily plug under the current pipline UI structure.
