### ISSUE TITLE
AWS support!

### ISSUE THREAD

**Issue by geojaz** [kubeflow/kubeflow#32]
In the interest of portability and a true ability to run workloads "everywhere", we should support AWS. 

There is definitely work to make this happen and priority is likely Google, but AWS has ML offerings and researchers should be able to use them in a similarly slick manner to GOOG.

**Comment by aronchick** [comment]
ABsolutely! There should be (ideally) zero changes between Google and AWS.
The only thing we're missing are the details/instructions. Can you fill
them in (if you know them)? Or can you specify anything here that doesn't
indicate we support AWS?

**Comment by geojaz** [comment]
Yep! I'm working on writing the tutorial and in that process, I'm realizing there are changes and I'm working on it. Hopefully will have something PRed tonight or tomorrow.

**Comment by aronchick** [comment]
Outstanding, thank you!

**Comment by bhack** [comment]
Any update?

**Comment by fxue** [comment]
Tried running Kubeflow on AWS, here is a [documentation](https://docs.google.com/document/d/1gj64lMvVsTemu27DZZomOkEH-2iv844HhveYce5jycg/edit?usp=sharing) of the steps I ran through. Filed [issue](https://github.com/kubeflow/kubeflow/issues/203) for differences I bumped into.

**Comment by wskinner** [comment]
What else is left now that https://github.com/kubeflow/kubeflow/issues/203 has been closed? Are there any other outstanding blockers before kubeflow can be considered "supported" on AWS?

**Comment by suneeta-mall** [comment]
@wskinner I can confirm that kubeflow works on AWS out of box. I would argue though that the readme can be improved. I have created this PR https://github.com/kubeflow/kubeflow/pull/952 for that but I am still playing with kubeflow (so I may have missed some places)

**Comment by pdmack** [comment]
Does your testing include s3 enablement for tf-serving?

https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet#L56

**Comment by suneeta-mall** [comment]
@pdmack Not yet .. exploring serving is still in my todo. I will revert back when I have tried it and update this issue.

**Comment by ShahNewazKhan** [comment]
@pdmack @suneeta-mall I have a deployment of kubeflow on AWS EKS, I have uploaded the `inception` model found under `gs://kubeflow-models/inception` to a public s3 bucket `s3://t2t-train/inception`

Do I have to manually set the params for  https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving.libsonnet#L56 after creating the appropriate secrets?

**Comment by pdmack** [comment]
@ShahNewazKhan yes. Let me know if you have some issues activating those params. I thought we had some ksonnet issues with the bools previously and I don't see updates there.

**Comment by bhack** [comment]
What approach we want to have about GPU support in aws? Check https://github.com/kubeflow/kubeflow/issues/288

**Comment by jlewi** [comment]
I think the general approach we are converging on is

1. Have different getting started pages customized for different K8s distros/clouds 
 
    * See https://www.kubeflow.org/docs/started/getting-started/

1. One pattern that I think will be common see #1111 is to have specific deploy.sh scripts for different
    distros.

    * Those scripts can perform vendor/cloud specific initialization steps; e.g. deploying the GPU
       daemonset on GKE.

**Comment by mbelang** [comment]
Even AWS official documentation is not working with recent version of kubeflow... I had to install `0.2.5` to get it work. I think I'm going to reverse engineer the output of the current installation and create a `helm` chart to make it easier to work with...

**Comment by Roshrini** [comment]
@mbelang Found this repo which is very actively maintained and mentions the steps to deploy recent version of kubeflow to Amazon EKS. I tried instructions from here and was able to spin up the cluster and run TF training using Jupyter notebook https://github.com/aws-samples/machine-learning-using-k8s

**Comment by Jeffwan** [comment]
We recently have some progress for the AWS support in Kubeflow. Please check latest documentation. 
https://www.kubeflow.org/docs/aws/

This is just a start, we found there're some sub-projects we can improve better for aws users. Will publish more plans later on.

**Comment by scottilee** [comment]
@jlewi can this be closed since Kubeflow on AWS is supported and documented?

**Comment by Jeffwan** [comment]
Yeah. I think this one can be closed. In the future, I will create one issue for every release to track features users want. Like aws support for v0.6, etc
