### ISSUE TITLE
cannot connect to notebooks which are created in any namespace other than kubeflow

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#3206]
Created a kubeflow cluster from master which is deployed with IAP on GCP. 
When notebooks are created in kubeflow namespace, we can successfully connect to the notebooks form ui.
using [this instruction](https://docs.google.com/document/d/1zT1yhDgmS59_uMWJ76hr7FCyXTDQ1Ju1MVADnlCfNEQ/edit) we can also successfully create notebooks in any other namespace. However, while we can connect to the created notebooks using port-forwarding, we cannot connect to the  notebooks from ui (virtual service is created and its configuration looks fine ).

**Comment by kunmingg** [comment]
The gateway is missing in non-kubeflow namespaces.

**Comment by Kyrremann** [comment]
@zabbasi is the problem that it dosen't show up in the UI? Then you can use the search function, and search for your specific namespace.

As our problem is that if we use a different namespace then `kubeflow`, we need to search for our namespace each time we want to connect to a notebook.

**Comment by jlewi** [comment]
Obsolete.

I'm trying out 0.6 and I was able to spawn a notebook in the non Kubeflow namespace and connect to it.
