### ISSUE TITLE
Python/Go binary to bulk replace images in kustomization.yaml files  (was Port use_gcr_for_all_images.sh to work with kustomize)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3210]
Port https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/use_gcr_for_all_images.sh
to kustomize.

This script is used for switching the images to a private registry. We will need to update the script
to work with the new kustomize manifests.

**Comment by jlewi** [comment]
I might suggest rewriting this as a go program and baking it into kfctl.

It might be nice if the tool supported some flexible way to match and replace images; e.g. using regexes. This way we could easily replace all images hosted in quay.io with another registry.

This would go a long way to making it easy to mirror all the required images to a different registry and then pull the images from it.

**Comment by ashahba** [comment]
Is this for `v0.7`?

**Comment by swiftdiaries** [comment]
Yeah, we're slated for 0.7 but this hasn't been picked yet

**Comment by ashahba** [comment]
To backup your point @jlewi I think we should start with only supporting internal registries that have the same repo structure that we propose, otherwise users need to update image urls manually.
This is mainly to simplify the private registry support.

**Comment by xaniasd** [comment]
I'll take a stab at this if noone else is doing that already!

**Comment by jlewi** [comment]
Thanks @xaniasd !

After #4222 is merged can we update the docs on kubeflow/website before we close this issue?

A follow on issue would be to provide tooling to mirror of the Kubeflow images to a different repository. 

I think one way we might be able to do that in a generic way would be to spit out a Tekton workflow that would pull the images from one repo, retag them and push them. (I'm hoping that's doable with Tekton).

@xaniasd Any interest in tackling that next (after the docs?)?

**Comment by xaniasd** [comment]
@jlewi I can add the documentation (I'll look into the setup and make a PR). About the follow-up; sure thing. I'm not familiar with Tekton and how we want to use it in this case, if you could give some background information I can give it a try. That said, a simple way to do this would be to just implement it in kfctl and fork `docker pull/push` commands for each image. Then we don't assume a running tekton instance (?). Along the same lines, an even simpler option would be to use kfctl to just spit out a list of images and build a bash command to do the pulling and pushing.

**Comment by yanniszark** [comment]
@xaniasd I actually have a small PR ready for exactly this thing, spitting out a changelist in stdout.
The user can use it to mirror images with any tool they want.
Will make a PR tomorrow.

**Comment by jlewi** [comment]
There's a couple reasons why on GCP we'd like to leverage Google Cloud Build or possibly Tekton to replicate the images

1. The number of images for Kubeflow is large O(10)'s if not O(100')s so we want to do the retagging in parallel
1. Given the large number of images we'd like to do the image pulling/pushing in the cloud to avoid network transfer to lower machines
1. With private GKE and Secure VPC we want to be able to use service accounts to talk to GCR

We have a sample jsonnet workflow here.
https://github.com/kubeflow/kubeflow/blob/0a7155cedeff92797cb3b03ca1ac4e16a767f881/scripts/gke/gcb_copy_images.jsonnet#L28

I think for GCP what we'd want is a command or separate go binary to traverse the kustomize directory and generate a YAML spec for the workflow to replicate all images.

I think this should be separate from the `set-image-name` command so we can build a replication workflow without modifying the kustomization.yaml files.

The code should look at kustomization.yaml to get the old image name and tag and the new image name and tag.

Generating a Tekton workflow would be a cloud neutral solution to this.

**Comment by jlewi** [comment]
/lifecycle frozen

It looks like kustomize supports composition; see  kubernetes-sigs/kustomize#171

So if we define a kustomize manifest that composes all of the individual applications in Kubeflow (i.e. lists each kubeflow application as a base); then we should just be able to override all the images by writing a kustomization.yaml file in that package that specifies the image we want to replace and the new image.

Related: Get rid of kustomize magic in kfctl kubeflow/manifests#774
Relevant thread: https://groups.google.com/forum/m/#!topic/kubeflow-discuss/uWp39i2nNuQ

**Comment by kunmingg** [comment]
https://github.com/kubeflow/kfctl/pull/226

**Comment by jlewi** [comment]
@kunmingg what is the remaining work to close out this issue?

It looks like we need to update the documentation page; e.g https://www.kubeflow.org/docs/gke/private-clusters/#deploy-kubeflow-with-private-gke

to describe how to use the new functionality. Is there anything else that needs to be done?

**Comment by jlewi** [comment]
@kunmingg thoughts? Any more immediate work to be done?

**Comment by jlewi** [comment]
@kunmingg ping?
