### ISSUE TITLE
GCP basic auth port-forward ambassador

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#3213]
After deploying 0.5 on GCP with basic auth attempting use kubectl port forward to the ambassador service doesn't work because it keeps redirecting to https which isn't directly exposed by the ambassador (instead it's normally handled by the load balancer).

**Comment by ryandawsonuk** [comment]
I've also hit this. I notice I can access an ambassador endpoint by, say:
```
curl -v -u ${USER}:${PASSWORD} https://${DEPLOYMENT}.endpoints.${PROJECT}.cloud.goog/ambassador/v0/diag/
```
But not seeing a convenient way to port-forward and make requests without credentials as [several of the example notebooks do](https://github.com/kubeflow/examples/search?q=port-forward&unscoped_q=port-forward)

**Comment by jlewi** [comment]
Ambassador is used both as a reverse proxy and to ensure all requests have credentials when basic auth is used.

Options are

* Disable basic auth (and remove external ip) if you want to kubectl port-forward to ambassador with no credentials
* Attach credentials to the request
* Deploy a proxy like [nginx](https://serverfault.com/questions/230749/how-to-use-nginx-to-proxy-to-a-host-requiring-authentication) and use that to attach basic auth headers and then port-forward to that

Port forwarding to the individual services like the examples are doing should work. Credential checking happens in Ambassador; so if you bypass ambassador (e.g. port-forward to mnist service or katib) then that application will not check for credentials. 


See related issues for more context; explanation.
Related issues: #2884 #2890
