### ISSUE TITLE
Unable to access notebook in kubeflow ui

### ISSUE THREAD

**Issue by eCeleritas** [kubeflow/kubeflow#3214]
I have deployed kubeflow v0.5.0 on GCP using IAP. After following these steps (https://www.kubeflow.org/docs/notebooks/setup/) to setup a notebook server in kubeflow, I am unable to access the notebook server. I see a pod spin up related to the name of my notebook server (i.e. `my-notebook-server-name`) and I am able to port-forward to it using kubectl. However, when accessing via the kubeflow ui (i.e. `/notebook/kubeflow/my-notebook-server-name`), the kubelow ui presents me with the dashboard again. 

Looking more closely at the documentation, it says:
```
kubectl -n <NAMESPACE> describe pods jupyter-<USERNAME>
```

I see no pods with this pattern.  I do not see any errors in the ui console nor errors in the backend to help me track down the issue. Is there anything special that is needed for IAP or otherwise missing from the documentation?

**Comment by eCeleritas** [comment]
Restarting underlying pods caused the issue to go away. Closing this for now

**Comment by wcass77** [comment]
Which pods did you restart? I'm having the same issue. Thanks
