### ISSUE TITLE
Set port name to http-XX for all services

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3219]
Istio relies on port name to distinguish http vs tcp services (this affects some authz features).
We should make sure the port name is http-XX for all services.
See [doc](https://istio.io/help/faq/traffic-management/#naming-port-convention).

cc @kunmingg

**Comment by jlewi** [comment]
@lluunn what is the priority of this issue? 

@lluunn Are the Authz features this blocks needed for 0.6? Could we do Authz for notebooks without this?

**Comment by lluunn** [comment]
If we just need notebook services to be protected (in 0.6), we only need to change the port name for notebook services.

**Comment by jlewi** [comment]
Thanks @lluunn 

Is this the port name in the virtual service? It looks like we are doing that correctly in the notebook controller
https://github.com/kubeflow/kubeflow/blob/1989ba557e932b1d7d814ce739189591d03b3b7f/components/notebook-controller/pkg/controller/notebook/notebook_controller.go#L400

is there more work to be done to make this work correctly for notebooks?

Can we list out other services that we might eventually want to update? Maybe we can just do `kubectl get service` to get a list of services created in a KF cluster and go through them?

**Comment by lluunn** [comment]
Yeah for notebook it should be good.

**Comment by jlewi** [comment]
Attached is a dump of the K8s services currently in namespace kubeflow.

It looks like most service ports are not following the ISTIO convention:

> The port names must be of the form protocol-suffix with grpc, http, http2, https, mongo, redis, tcp, tls or udp as the protocol in order to take advantage of Istio’s routing features.

Example for katib ui

```
pec:
    clusterIP: 10.19.240.244
    ports:
    - name: ui
      port: 80
      protocol: TCP
      targetPort: 80
```

[service.yaml.txt](https://github.com/kubeflow/kubeflow/files/3439670/service.yaml.txt)

So I think the next step is

1. File a bunch of bugs in kubeflow/manifests to update different packages to follow the naming conventions
1. Start fixing these bugs
