### ISSUE TITLE
Python script to set parameters for ksonnet prototypes

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#322]
Background #215 

As part of our release process, we need to update the prototypes for various ksonnet prototypes to set the parameters to the value of newly built values (e.g. the newly built image for the TFJob operator).

So we'd like a tool like

```
python -m kubeflow.kubeflow.releasing.update_prototype --file=.../all.jsonnet --values=tfJobImage=gcr.io/kubeflow/tf-operator:v20180301
```

**Comment by Maerville** [comment]
Hi I would like to work on that issue, although I have few questions to ask.

So, basically, now I see 3 patterns of assigning value to the pareameters:

default value:
`// @optionalParam tfJobImage string gcr.io/tf-on-k8s-dogfood/tf_operator:v20180117-04425d9-dirty-e3b0c44 The image for the TfJob controller.` 

assign while creating parameter:
`local tfJobImage = import "param://tfJobImage";`

and also assign inner property
`tfJobImage:: "gcr.io/kubeflow-images-staging/tf_operator:v20180226-403",`

so, after running the script in a way you provided in example, which types of assignment have to be replaced?

**Comment by jlewi** [comment]
Fantastic.

The first and third options that you mentioned.

Basically our release process is defined [here](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-the-ksonnet-configs-for-master). As the instructions note, after we build a bunch of images we need to update the ksonnet configs as part of a release. We'd like a script to do this so we can automate it.
