### ISSUE TITLE
Error in AWS generate platform output

### ISSUE THREAD

**Issue by kyeotic** [kubeflow/kubeflow#3223]
When running the `apply platform` command from the [Install with AWS docs](https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/) this error is thrown

```
loading config file "/Users/tkye/dev/callysto/src/callysto/aws_config/cluster_config.yaml": no kind "ClusterConfig" is registered for version "eksctl.io/v1alpha4" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:60"
```

Changing the `cluster_config.yml` to point to `apiVersion: eksctl.io/v1alpha5` fixes it

**Comment by Jeffwan** [comment]
@tyrsius 
Thanks for reporting this issue! New version of eksctl is not compatible with older API versions. We are talking with eksctl team to either add support or we generate cluster spec based on user's eksctl version. In progress of it.

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/kubeflow/pull/3280 File to PR to address this issue for short term. eksctl will guarantee backward compatibility in next release

**Comment by Jeffwan** [comment]
This has been fixed and Let's close this issue. 

/close
