### ISSUE TITLE
admission webhook certificate problem

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3227]
The communication between mutatingWebhookConfiguration and the webhook pod needs a certificate, which we provision a self-signed one in this [script](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/create_ca.sh).

It's Statefulset, and runs:
1. create a cert
1. create a secret to store the cert (this secret will be mounted by webhook pod)
1. periodically check mutatingWebhookConfiguration has the same cert, if not, patch it

The problems here are, 
1. when this pod restarts, it creates a new cert, and patches it to mutatingWebhookConfiguration. However, the webhook server will not reload the the certificate and we will get tls error
2. When we redeploy everything, the webhook pod will read the old secret (since the secret exists), the script will patch new cert to mutatingWebhookConfiguration,  and thus also get tls error.
3. when we delete the component, the secret is not deleted.

cc @zabbasi @jlewi

**Comment by lluunn** [comment]
/assign  @zabbasi
Zahra is fixing this.

**Comment by jlewi** [comment]
@zabbasi is this fixed by #3229 or is there more to do?

**Comment by zabbasi** [comment]
This is fixed  by #3229 and is cherry picked to v0.5.0. 
/close
