### ISSUE TITLE
Add Pipelines card to provide one-click access to KF Pipeline runs

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3236]
As part of the UX enhancements [specifications](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZYbjDGnaKqEC/files/MCEJu8Y2hyDScWR0uwkSmYmqTA1fRs4iJFc), the KF dashboard should have a card that shows recently executed KF Pipeline runs allowing the user to access current or recently active runs from the KF landing page.with single click. This mirrors to the functionality described in #3120 for Jupyter Notebooks. 

/area front-end
/area centraldashboard
/assign @prodonjs
/priority p2

**Comment by prodonjs** [comment]
/cc @avdaredevil 
/cc @ajayalfred 

Wanted to run a quick set of questions by you. Kubeflow Pipelines has two major artifact types; Pipeline definitions that define a workflow graph to be executed in the Kubernetes engine, and Pipeline runs that are instantiations of those definitions run at a particular time. In my mind, it seems like it would be useful to have quick access to both.

This screenshot below shows a local change I'm working on where the Pipeline Definitions card shows the 5 most recently created Pipeline definitions, and the Pipeline Runs card shows the runs. 
![Dhx9kD179hQ](https://user-images.githubusercontent.com/6835846/58655264-bc511f00-82e7-11e9-99c6-db0998139ad8.png)

- Do you think this approach makes sense or should there only be one Pipelines card?
- If there's only one, should it show definitions, runs, or provide a toggle to switch between them?
- For runs, we can obtain the status, so how should we represent that?
  - My first thought would be to color the icon green for success, red for failure, and some form of yellow/orange if pending.

**Comment by ajayalfred** [comment]
Great suggestion! I think we should show them as 2 distinct cards.

For the pipeline definition card, the title can read "Pipelines" and show the 5 most recently used/modified/uploaded pipelines.

For pipeline runs card, the title can read "Pipeline Runs" and show the 5 most recent runs. Agree showing status will be useful. Instead of the pipeline icon to the left of each run, show the status in that space. We use a different icon to represent runs anyway, but status will definitely be more useful. Status icons for KFP available here –https://drive.google.com/corp/drive/folders/1dDrRWSFSM4UQNZLzWJy2Df8Uez4bGj30

Finally, can you stack the pipeline and pipeline runs card vertically in one column. They provide contextual information for each other that works best in conjunction with being placed together.

**Comment by prodonjs** [comment]
Excellent! Thanks for the feedback. In terms of putting the Pipeline cards on top of one another, which column do you think it makes the most sense to put them? The reason I staggered them across columns was to try to create some balance and avoid one column being significantly taller.

My proposal would be to move the documentation to the first column, use the second column for the cards that reflect items within the cluster, and the third column for the platform specific stuff including the resource charts. On a tall screen, you'd end up with something like this.
![Screenshot from 2019-05-30 16-42-13](https://user-images.githubusercontent.com/6835846/58663174-e7dd0500-82f9-11e9-8984-0a2b3b790326.png)

There's a bit of scrolling necessary on a laptop screen though, but I don't see how we avoid that.

**Comment by ajayalfred** [comment]
I'd say keep GCP and Docs card in 3rd column. Quick actions, utilization cards in column 1 and the rest in the middle column. Wdyt?

Also, the pipeline/runs/notebooks cards should probably all get the "Recent" prefix for the card title. Helps clarify why the user is seeing these 5 notebooks.

The x-axis label in the charts is displayed at an angle. Can this be changed to horizontal text? That would save so much vertical height of the card!

**Comment by ajayalfred** [comment]
One more thing I've noticed is that the second line of text in the card row is a little bigger than it should be. Use the text styling of the description line from the Docs card (noticeably smaller) in all other cards – that should save some vertical space across all list cards.
