### ISSUE TITLE
Expose TF serving service (gRPC) through ingress

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#324]
Currently GKE doesn't support HTTP/2, so we cannot send gRPC request to it.

Envoy has a grpc-http [bridge](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_http1_bridge_filter.html) which allows us to send gRPC request via HTTP/1.1, but Ambassador doesn't support it now.

We need to figure out a way to expose the gRPC TF serving service.

**Comment by jlewi** [comment]
@lluunn Can you clarify is it GKE or is the GCP load balancer?

**Comment by lluunn** [comment]
Yes it's the GCP load balancer: https://groups.google.com/forum/#!topic/grpc-io/bfURoNLojHo

**Comment by switchfootsid** [comment]
Been trying to work this on out, need an L7 load balancer to get it working. Nginx can also be configured to balance gRPC loads. Sadly, that's all I know at this point. Anyone at @kubeflow looking at this?

**Comment by llKetanll** [comment]
@jlewi Can we reopen this?
HTTP(S) Load balancer on GCP now supports gRPC and HTTP/2 (https://cloud.google.com/load-balancing/docs/https/#backend_services). This is something I was looking for and I am willing to contribute on this.
