### ISSUE TITLE
Create an Application resource to describe Jupyter

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3240]
We should create an Application resource in the Jupyter kustomize manifests directory to describe the Jupyter application

/cc @zabbasi

**Comment by jlewi** [comment]
There is an application spec for the web app.
https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/application.yaml

The controller
https://github.com/kubeflow/manifests/tree/master/jupyter/notebook-controller/base

@zabbasi @kkasravi Can we close this issue or is there more to be done?

**Comment by kkasravi** [comment]
we can close this. Enabling the application-controller and application overlay is #3429
