### ISSUE TITLE
Make Jupyter web app ship with its dependencies

### ISSUE THREAD

**Issue by nihir27** [kubeflow/kubeflow#3256]
Currently the Jupyter-web-app image pulls from js and css CDNs that reside on the public internet.

If a user is accessing the jupyter web app UI from a browser in an environment with no access to the internet, the UI is unusable.

**Comment by prodonjs** [comment]
@kimwnasptd You mentioned in https://github.com/kubeflow/kubeflow/pull/3102#issuecomment-487281355 that you were planning to rewrite the front-end in Angular, which would eliminate this issue. Do you have any tentative timeline in mind for when you might tackle that?

**Comment by kimwnasptd** [comment]
Hey @prodonjs, it is in my top priorities as it would make it easier to add new features and tests in the future. I've made a lot of progress, but I still have some work to do in the submit form. 

I believe I will have WIP PR sometime in the next week from which we could start iterating through.

**Comment by prodonjs** [comment]
Wow that is fantastic! I wasn't expecting it to be that close to being ready for review. That's exciting stuff! Feel free to copy @avdaredevil and myself into anything if you want a second set of eyes on it.
