### ISSUE TITLE
Jupyter notebook pod creation fails with 'serviceaccount "jupyter-notebook" not found'

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3261]
Steps to reproduce:

1. Clone kubeflow/kubeflow and checkout to commit 58022fbe26d9fc70a271519c8ae0fbe0f860eb57 (Mon May 13 14:16:13 2019 -0400).
2. Install Istio from `dependencies/istio`:
    1. `kubectl apply -f dependencies/istio/install/crds.yaml`
    2. `kubectl apply -f dependencies/istio/install/istio-noauth.yaml`
2. `cd bootstrap; make build-kfctl-container`
3. `cd bin` and follow [the generic guide](https://www.kubeflow.org/docs/started/getting-started-k8s/)
4. Get NodePort port of ambassador service, go to `http://<node-ip>/<port>`.
5. Create a new Notebook, try `kubectl describe statefulset` and see that it fails with 'serviceaccount "jupyter-notebook" not found'.

**What I think happened:**
It seems that the notebook controller used to be implemented in metacontroller and jsonnet.
I think that the controller [used to create it](https://github.com/kubeflow/kubeflow/blob/4b1ae00a997cd83b114c5b00d53a0928cdbcb81c/kubeflow/jupyter/jupyter.libsonnet#L344) but in Go it's probably not yet implemented.

cc @lluunn @kunmingg

**Comment by lluunn** [comment]
We should have that service account in kubeflow namespace.
Which namespace are you creating notebook at?
If it's not kubeflow, might not work now. @zabbasi

**Comment by yanniszark** [comment]
It should be the kubeflow namespace.
I will confirm tomorrow!

**Comment by zabbasi** [comment]
@yanniszark  
We no longer use jupyter-notebook serviceaccount for notebooks (see #3161)
Also notebook controller image is not up-to-date in master. if you are going to use istio, you hav to build the image first and then use it (/cc @gabrielwen). My pr resolves this (#3245)
