### ISSUE TITLE
Neither v0.5.0 nor v0.5.1 works when spawning "NewServer".

### ISSUE THREAD

**Issue by dongdan39** [kubeflow/kubeflow#3271]
Dear Developers,
  I found neither v0.5.0 nor v0.5.1 works when spawning "NEW SERVER" on "Notebook Servers", simply no response when clicking on the button. I installed my kubeflow following instructions from:
https://www.kubeflow.org/docs/started/getting-started-k8s/

[root@centos-7-vm-1 lin]# kubectl get deploy -n kubeflow
NAME                                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
ambassador                                 3         3         3            3           40h
argo-ui                                    1         1         1            1           40h
centraldashboard                           1         1         1            1           40h
jupyter-web-app                            1         1         1            1           40h
katib-ui                                   1         1         1            1           40h
minio                                      1         1         1            1           40h
ml-pipeline                                1         1         1            1           40h
ml-pipeline-persistenceagent               1         1         1            1           40h
ml-pipeline-scheduledworkflow              1         1         1            1           40h
ml-pipeline-ui                             1         1         1            1           40h
ml-pipeline-viewer-controller-deployment   1         1         1            1           40h
mysql                                      1         1         1            1           40h
notebooks-controller                       1         1         1            1           40h
pytorch-operator                           1         1         1            1           40h
studyjob-controller                        1         1         1            1           40h
tensorboard                                1         1         1            1           40h
tf-job-dashboard                           1         1         1            1           40h
tf-job-operator                            1         1         1            1           40h
vizier-core                                1         1         1            1           40h
vizier-core-rest                           1         1         1            1           40h
vizier-db                                  1         1         1            1           40h
vizier-suggestion-bayesianoptimization     1         1         1            1           40h
vizier-suggestion-grid                     1         1         1            1           40h
vizier-suggestion-hyperband                1         1         1            1           40h
vizier-suggestion-random                   1         1         1            1           40h
workflow-controller                        1         1         1            1           40h

Note that other dashboards works normally. Please check, thanks!

Cheers,
Dan

**Comment by dongdan39** [comment]
P.S: I did pass --version=v0.5.0 or v0.5.1 when kfctl init, but it does not work.

**Comment by jlewi** [comment]
Can you provide the YAML for your jupyter web app ?

```
kubectl get deploy -o yaml jupyter-web-app
```

When you click on new server what happens? Do you see the form to create a new notebook?

If nothing happens can you use the chrome developer tools (or equivalent in your browser) to see if there are javascript errors.


/assign @kimwnasptd

**Comment by jlewi** [comment]
Looks like #3168

**Comment by dongdan39** [comment]
> Can you provide the YAML for your jupyter web app ?
> 
> ```
> kubectl get deploy -o yaml jupyter-web-app
> ```
> 
> When you click on new server what happens? Do you see the form to create a new notebook?
> 
> If nothing happens can you use the chrome developer tools (or equivalent in your browser) to see if there are javascript errors.
> 
> /assign @kimwnasptd

[root@centos-7-vm-1 lin]# kubectl -n kubeflow get deploy -o yaml jupyter-web-app 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/5RRy27bMBC89zP2TEUKihzKW9D6ELR2hfRxKYJgTa8c1iSXIFcKDIP/XtAy3KCNUfQkijOzM7M8AEb7nVK2HEADxpjb6RoU7GzYgIYPFB3vPQUBBZ4ENygI+gAO1+RyPWGMoOHnGPdCqXmmdVNvFOwyh0ByZbk17COHOuRvYlEQ0NOrIyqQI5qK7sY1DY6fqyBHMtU6UXTWYAZ9rSCTIyOcKuBRzNOnf0QsRYGQjw6FjqL/qFdepDAcBG2glEH/OACF6fg9tbr//PHxy+L9/eLr4+p2uQAFE7qxIplMImkS75rDmClVQYGiztJvdy/YGxpwdALlQYH1uD3ecdhuMLx91/6RT0/d1c1VBydqPzrXs7NmDxruhhVLnyjPj3px+ZGTzI3OBXtOAvqm67qaYmI3elryGE48X489yhNoaElMazgMdvvbZP5vZiGUhzolU5qsoVtjqnp1Kc2sOecZ7HaJsW7/9fzNybpc9i6lvPkFAAD//wEAAP//2TYbVP8CAAA="}'
    kubecfg.ksonnet.io/garbage-collect-tag: gc-tag
  creationTimestamp: 2019-05-16T00:59:20Z
  generation: 1
  labels:
    app: jupyter-web-app
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: jupyter-web-app
  name: jupyter-web-app
  namespace: kubeflow
  resourceVersion: "29202031"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/deployments/jupyter-web-app
  uid: d63ee7f8-7775-11e9-ae91-fa163e24b7d2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jupyter-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jupyter-web-app
    spec:
      containers:
      - env:
        - name: ROK_SECRET_NAME
          value: secret-rok-{username}
        - name: UI
          value: default
        image: gcr.io/kubeflow-images-public/jupyter-web-app:v0.5.0
        imagePullPolicy: IfNotPresent
        name: jupyter-web-app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jupyter-web-app
      serviceAccountName: jupyter-web-app
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: jupyter-web-app-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-16T01:02:16Z
    lastUpdateTime: 2019-05-16T01:02:16Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-05-16T00:59:20Z
    lastUpdateTime: 2019-05-16T01:02:16Z
    message: ReplicaSet "jupyter-web-app-5fd56df98c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by dongdan39** [comment]
Turns out to be a network firewall problem when downloading a *.js script. Sorry for this confusion, please close this issue. Thanks!
