### ISSUE TITLE
test_is_kf_ready fails for iap-enabler with istio

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3273]
Post submit run
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1128463690513780736

The test failed waiting for iap-enabler.

Here's the exception

```
E           kubernetes.client.rest.ApiException: (404)
E           Reason: Not Found
E           HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Audit-Id': '58ef169e-f59f-4df7-a8d5-74562f29d334', 'Content-Length': '236', 'Date': 'Wed, 15 May 2019 01:27:28 GMT'})
E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"iap-enabler\" not found","reason":"NotFound","details":{"name":"iap-enabler","group":"extensions","kind":"deployments"},"code":404}
```

The calling code is

```
      ingress_namespace = "istio-system" if use_istio else namespace
      for deployment_name in ingress_related_deployments:
        logging.info("Verifying that deployment %s started...", deployment_name)
>       util.wait_for_deployment(api_client, ingress_namespace, deployment_name)

kf_is_ready_test.py:69: 
```

I suspect the problem is we are checking the wrong namespace.

It looks like it just started failing.

I suspect this is related to 
https://github.com/kubeflow/kubeflow/pull/3253

It looks like that PR changed the ksonnet parameter used for ISTIO.

So I suspect we are no longer actually enabling ISTIO.

1. kfctl_is_ready should print out the namespace we are checking as well as whether ISTIO is enabled
1. Why didn't this get caught by presubmit for #3253

**Comment by jlewi** [comment]
Here's the presubmit run.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3253/kubeflow-presubmit/1128396796620443649/

My conjecture is that presubmit is not actually testing the manifests at the PR being submitted.

**Comment by jlewi** [comment]
Here are the logs for the build deploy step

```
/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-3253-023af41-3649-673e/src/kubeflow/kubeflow/bootstrap/bin/kfctl init /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-3253-023af41-3649-673e/kfctl-673e -V --platform=gcp --version=pull/3253 --skip-init-gcp-project --disable_usage_report --project=kubeflow-ci-deployment --use_istio
```
[kubeflow-presubmit-kfctl-go-iap-istio-3253-023af41-3649-673e-2179499500.log.txt](https://github.com/kubeflow/kubeflow/files/3182718/kubeflow-presubmit-kfctl-go-iap-istio-3253-023af41-3649-673e-2179499500.log.txt)

Output doesn't indicate whether it actually pulled at that PR or not we could try to rerun the command to reproduce it.

**Comment by gabrielwen** [comment]
there maybe has some changes to kfctl recently that introduces this.  I'm also seeing changed behavior #3282

**Comment by jlewi** [comment]
Another failing presubmit
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3274/kubeflow-presubmit/1128767443351638016/

I fetched the event logs for "iap-enabler"


```
resource.labels.cluster_name="kfctl-e280"
logName="projects/kubeflow-ci-deployment/logs/events" 
jsonPayload.involvedObject.name="iap-enabler"
```
* A replica set was created
* Logs for the replica set show pod was created
* Here are the event logs for the pod

```
resource.labels.cluster_name="kfctl-e280"
logName="projects/kubeflow-ci-deployment/logs/events" 
jsonPayload.involvedObject.name="iap-enabler-99779c66d-54bhw"
```

Here are the logs
[iap-enabler-99779c66d-54bhw.log.txt](https://github.com/kubeflow/kubeflow/files/3184691/iap-enabler-99779c66d-54bhw.log.txt)

There are errors connecting to the server; but I'm not sure why that would affect whether the test thinks the deployment started.

**Comment by jlewi** [comment]
Code is calling util.wait_for_deployment
https://github.com/kubeflow/kubeflow/blob/a70c866ee7811ec907c63368a43703447348d99f/testing/kfctl/kf_is_ready_test.py#L69

Here's the exception

```
        if not 200 <= r.status <= 299:
>           raise ApiException(http_resp=r)
E           kubernetes.client.rest.ApiException: (404)
E           Reason: Not Found
E           HTTP response headers: HTTPHeaderDict({'Content-Length': '236', 'Audit-Id': 'aec059c2-d192-4cf3-a280-9bb1286037a4', 'Content-Type': 'application/json', 'Date': 'Wed, 15 May 2019 21:31:03 GMT'})
E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"iap-enabler\" not found","reason":"NotFound","details":{"name":"iap-enabler","group":"extensions","kind":"deployments"},"code":404}
```
It looks like this is happening immediately.

Hypothesis:
   * util.wait_for_deployment doesn't treat 404 (Not Found as retryable error)); maybe it should?
   * It seems weird that the build and deploy step would persist the deployment to the master but then a subsequent read would be inconsistent?

Lets look at timing of log statements

2019-05-15 14:31:04.189 PDT
kf_is_ready_test.py 68 INFO Verifying that deployment iap-enabler started...

Timestamp on the replica set is before that

2019-05-15 14:30:47.000 PDT
Scaled up replica set iap-enabler-99779c66d to 1

So master returning Not Found seems unlikely to be a transient error.

More likely is that we are not checking the namespace where the iap-enabler was actually created.

**Comment by jlewi** [comment]
Here's another presubmit failure
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3268/kubeflow-presubmit/1128776375902146560/

In this presubmit we should be logging which namespace we are checking.

Logs show its checking istio-namespace

```
kf_is_ready_test.py 70 INFO Verifying that deployment istio-system.iap-enabler started...
```

But the kfctl logs show that its created in namespace kubeflow

```

2019-05-15 15:04:13.538 PDT
util.py 71 INFO time="2019-05-15T22:04:13Z" level=info msg="Applying deployments kubeflow.iap-enabler" filename="cluster/upsert.go:73"
```

Event logs show that is actually in namespace `kubeflow`

```

2019-05-15 15:04:13.000 PDT
Scaled up replica set iap-enabler-99779c66d to 1
 
Expand all | Collapse all {
 insertId:  "1ei35qofmtn07b"  
 jsonPayload: {
  apiVersion:  "v1"   
  involvedObject: {
   apiVersion:  "apps/v1"    
   kind:  "Deployment"    
   name:  "iap-enabler"    
   namespace:  "kubeflow"    
   resourceVersion:  "3441"    
   uid:  "5fdfa6b3-775d-11e9-8edc-42010af0009d"    
  }
  kind:  "Event"   
  message:  "Scaled up replica set iap-enabler-99779c66d to 1"   
  metadata: {…}   
  reason:  "ScalingReplicaSet"   
  source: {…}   
  type:  "Normal"   
 }
 logName:  "projects/kubeflow-ci-deployment/logs/events"  
 receiveTimestamp:  "2019-05-15T22:04:13.745694196Z"  
 resource: {…}  
 severity:  "INFO"  
 timestamp:  "2019-05-15T22:04:13Z"  
}
```

So the problem is test expects iap-enabler in namespace istio-system but it was actually created in namespace kubeflow

**Comment by gabrielwen** [comment]
So the root cause was the result of the combination of two PRs: #3253 #3108 

in #3253 I change the param to be injectIstio and this value is set here:
https://github.com/kubeflow/kubeflow/blob/a70c866ee7811ec907c63368a43703447348d99f/bootstrap/pkg/kfapp/coordinator/coordinator.go#L292

As you can see only when `injectIstio` shows up in the list of componentParams that we will set this value.

In #3108 however, there are diffs between the app.yaml generated before the PR and after it.  One of the diffs is `injectIstio` in iap-ingress.  That is why although iap-enabler was deployed, namespace is `kubeflow` instead of `istio-system`.

**Comment by jlewi** [comment]
Thanks @gabrielwen 

I think the fact that the bug was caused  by the combination of #3253 #3108 also explains why this wasn't caught by presubmit.

Both of those PRs were probably testing against a base that didn't include the other. So presubmits weren't testing the combination of those PRs. So it was only in postsubmit and subsequent PRs rebased after those PRs that we started testing the combination.

This also means that after #3283 is submitted folks will need to rebase on master to pick up the fix.

**Comment by gabrielwen** [comment]
Yes, they need to sync to master.

I think the root cause of this is our testing logic as you described.  Say branch tree looks like:
```
---------base----------HEAD
              \
               ...
                 \
                branch
```
Our testing workflows take base + branch to test.  However, I think the correct logic should be:
1. use `HEAD + branch`
1. if it's able to patch, use it and run the tests.
1. if it is not able to patch, returns failure and asks author to rebase and re-run the test.

This is not 100% guarantee as there is consistency issue if a series of PRs run presubmit at the same time and combination of them will break the test.  But in general I think this should help us catch this issue 99% of the time.
