### ISSUE TITLE
Create a helm repository

### ISSUE THREAD

**Issue by naseemkullah** [kubeflow/kubeflow#3295]
A helm [chart is in the works](https://github.com/helm/charts/pull/13454) and we could host it in the kubeflow project and then add it to [helm hub](https://github.com/helm/hub/blob/master/Repositories.md).

Could we please look into creating a helm repository?

**Comment by gaocegege** [comment]
@jlewi There are so many users prefer Helm, can we have such a repo?

**Comment by jlewi** [comment]
Who is going to maintain the repo and commit to maintaining helm packages?

**Comment by naseemkullah** [comment]
My pleasure @jlewi ,

I am not sure how to ensure a good ux over time, all i know is there is a current desire for a helm chart and thus am working on creating one. I would presume that various users of the chart would step up to keep it maintained, and fix issues as they arise.

To maintain the repo itself it would be someone within the kubeflow org, I think it will consist of a GCS bucket with a public url such as `charts.kubeflow.org` and a simple CI system in place.

The helm chart itself would have to be maintained by the overall user community, with someone from kubeflow org to approve PRs.

**Comment by naseemkullah** [comment]
Kustomize then!
