### ISSUE TITLE
Install Istio for every test workflow

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3306]
Our latest notebook controller has dependency on Istio. Any test with notebooks will fail if Istio is not installed.
We should make sure all deployment e2e test workflows install Istio.

**Comment by jlewi** [comment]
@kunmingg Do we know which tests are failing?

**Comment by jlewi** [comment]
@kunmingg Any update?

**Comment by jlewi** [comment]
I'm closing this bug. Our tests are passing and we should be fully migrated to ISTIO.
