### ISSUE TITLE
Errors when creating a notebook (standard)

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#3312]
Action:
- Start Kubeflow on a custom namespace
- Port forward to svc/ambassador
- Go to central dashboard
- Create standard notebook server

Expected: "Connect" connects to notebook
Actual: "Sorry, <notebook name> is not a valid page"

**Comment by aronchick** [comment]
cc @zabbasi @jlewi

**Comment by zabbasi** [comment]
Have you deployed from v0.5. if yes then https://bit.ly/2UOzzxB should  help you to create a notebook in custom namespace. 
This feature in master is WIP and is not currently available.
