### ISSUE TITLE
`kfctl.sh apply platform` on EKS fails if automatically selected availability zone has no capacity

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#3316]
When running `kfctl.sh apply platform` on EKS, `kfctl` appears to automatically select which availabililty zones it will use. Sometimes one of the selected availability zone does not have capacity, leading to the error below:

```
Cannot create cluster 'kubeflow-aws' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zoneseast-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f
```

The expected behaviour should surely be that `kfctl` will only select availability zones that currently do have capacity?

**Comment by Jeffwan** [comment]
@karlschriek This is an problem on eksctl. I would suggest you to control availability zones manually in eksctl cluster config file. Please use AZs a b c for large region. 

See this
https://github.com/kubeflow/kubeflow/blob/ea43dfacf8216481ca2f1d9fcf90fc972392a6af/deployment/aws/infra_configs/cluster_config.yaml#L11-L12

**Comment by Jeffwan** [comment]
As we have documentation there, I will close this issue. Feel free to reopen if you still have questions on it.
