### ISSUE TITLE
kubeflow components fails when deploying in kubernetes environment, where PodSecurityPolicies are Enabled.(root containers not allowed) 

### ISSUE THREAD

**Issue by arjunm183** [kubeflow/kubeflow#3330]
Kubeflow component fails to deploy in k8s environment where PodSecurityPolicies are enabled with runAsUser rule: MustRunAsNonRoot

#Environment:
==================
**kubernetes:** v 1.12.6 and above

**kubeflow:** master, v0.5.0 

**kfctl:** 

kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e

**ks:** 

ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4

==================

#Issue Reproduce:
==================

PodSecurityPolicy enabled in kubernetes Cluster

Use the below PodSecurityPolicy Enabled.

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
 annotations:
   kubectl.kubernetes.io/last-applied-configuration: |
     {"apiVersion":"policy/v1beta1","kind":"PodSecurityPolicy","metadata":{"annotations":{},"name":"dhc-restricted"},"spec":{"allowPrivilegeEscalation":true,"allowedCapabilities":["IPC_LOCK","NET_BIND_SERVICE","SYS_RESOURCE"],"fsGroup":{"ranges":[{"max":65535,"min":1}],"rule":"MustRunAs"},"hostPorts":[{"max":42000,"min":30000}],"privileged":false,"runAsUser":{"rule":"MustRunAsNonRoot"},"seLinux":{"rule":"RunAsAny"},"supplementalGroups":{"ranges":[{"max":65535,"min":1}],"rule":"MustRunAs"},"volumes":["nfs","emptyDir","secret","downwardAPI","configMap","persistentVolumeClaim","projected"]}}
 creationTimestamp: "2019-03-06T05:51:42Z"
 name: restricted
 spec:
 allowPrivilegeEscalation: true
 allowedCapabilities:
 - IPC_LOCK
 - NET_BIND_SERVICE
 - SYS_RESOURCE
 fsGroup:
   ranges:
   - max: 65535
     min: 1
   rule: MustRunAs
 hostPorts:
 - max: 42000
   min: 30000
 runAsUser:
   rule: MustRunAsNonRoot
 seLinux:
   rule: RunAsAny
 supplementalGroups:
   ranges:
   - max: 65535
     min: 1
   rule: MustRunAs
 volumes:
 - nfs
 - emptyDir
 - secret
 - downwardAPI
 - configMap
 - persistentVolumeClaim
 - projected

#Deployment Procedure.
==================

export KFAPP=`pwd`/kfv1
echo $KFAPP
mkdir ${KFAPP}
kfctl init ${KFAPP} -n kfv1
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V

#ERROR: 
==================
Once Deployed it shows the below error 

NAME                                                        READY   STATUS                       RESTARTS   AGE
ambassador-99bcb595b-gvxwl                                  0/1     CreateContainerConfigError   0          28h
ambassador-99bcb595b-j7wdk                                  0/1     CreateContainerConfigError   0          28h
ambassador-99bcb595b-vq459                                  0/1     CreateContainerConfigError   0          28h
argo-ui-5b4fbfd4d7-4m55g                                    0/1     CreateContainerConfigError   0          28h
centraldashboard-766c66bb6d-8v828                           0/1     CreateContainerConfigError   0          28h
jupyter-web-app-7869fcc954-lpvck                            0/1     CreateContainerConfigError   0          28h
katib-ui-7f599d4cd7-78v4h                                   0/1     CreateContainerConfigError   0          28h
minio-594d76b6c-wbvzx                                       0/1     CreateContainerConfigError   0          28h
ml-pipeline-6895b87d8d-pkl5k                                0/1     CreateContainerConfigError   0          28h
ml-pipeline-persistenceagent-6997cccd5f-jpmvt               0/1     CreateContainerConfigError   0          28h
ml-pipeline-scheduledworkflow-54bf54d689-fdsfs              0/1     CreateContainerConfigError   0          28h
ml-pipeline-ui-b5d7cd9-b2h45                                0/1     CreateContainerConfigError   0          28h
ml-pipeline-viewer-controller-deployment-84ff476f75-xjhkz   0/1     CreateContainerConfigError   0          28h
mysql-677d997f97-fktnl                                      0/1     CreateContainerConfigError   0          28h
notebooks-controller-7dbd87c8b8-5nrc7                       0/1     CreateContainerConfigError   0          28h
pytorch-operator-7479bdb44b-s4nbz                           0/1     CreateContainerConfigError   0          28h
studyjob-controller-7846b9cc76-hw4lj                        0/1     CreateContainerConfigError   0          28h
tensorboard-cdfb59546-n2htz                                 0/1     Pending                      0          28h
tf-job-dashboard-cd85767fb-mxfv9                            0/1     CreateContainerConfigError   0          28h
tf-job-operator-5c48544cf7-vhkmn                            0/1     CreateContainerConfigError   0          28h
vizier-core-7bcd94756c-xvcws                                0/1     CreateContainerConfigError   0          28h
vizier-core-rest-59b4c49f79-l8g2r                           0/1     CreateContainerConfigError   0          28h
vizier-db-8699f796b7-r22bx                                  0/1     CreateContainerConfigError   0          28h
vizier-suggestion-bayesianoptimization-5c98c85fbf-q596h     0/1     CreateContainerConfigError   0          28h
vizier-suggestion-grid-696f96fdc7-hgtpn                     0/1     CreateContainerConfigError   0          28h
vizier-suggestion-hyperband-79b5b67f57-5qljh                0/1     CreateContainerConfigError   0          28h
vizier-suggestion-random-7b6768d6bf-7x8w6                   0/1     CreateContainerConfigError   0          28h
workflow-controller-5478d987d-q56pb                         0/1     CreateContainerConfigError   0          28h

#ContainerConfigError is as below
==================
" Error: container has runAsNonRoot and image will run as root "

Means my psp is restricting to run root container images, which is a valid reason to have security in our Kubernetes environment. 

#Workaround 
==================
To remove psp or say my psp to have 
runAsUser:
  rule: RunAsAny
Deploy kubeflow in a cluster where psp is not enabled. 
  * tested it works without psp.

Which is not a perfect solution.

#Solution
==================
Perfect Solution would be to have all the components of kubeflow to run as non root user.

**Comment by jlewi** [comment]
Thanks @arjunm183 We'll see about trying to tackle this in 0.7 (Q3).

**Comment by arjunm183** [comment]
@jlewi As a progress i started making the components as non root. I have made it and in progress of making other components. It is just the Dockerfile where i did some changes and tested. It works fine. 
Kindly let me know is there a way i can share those.
