### ISSUE TITLE
kfctl v0.5.1 binary not working for AWS

### ISSUE THREAD

**Issue by amarrella** [kubeflow/kubeflow#3344]
It looks like kfctl v0.5.1 binary doesn't support `--provider aws` while the source code tagged as v0.5.1 does. Also when I run:
```
./kfctl version
```
it seems to get an old dirty version:
```
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
```

**Comment by jlewi** [comment]
AWS currently still uses kfctl.sh

Migrating to kfctl is #2998 

The --version issue is #2986 
 
/cc @Jeffwan

**Comment by Jeffwan** [comment]
@amarrella Let's keep track of the issue here https://github.com/kubeflow/kubeflow/issues/3332
