### ISSUE TITLE
Update the Profile Controller to include name and image

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3346]
## About:
As part of our OKR to allow for supporting a user based flow on central-dashboard and having user auth baked in, we would need to have access to:
- Name
- Email
- Image

Now, we can try to detect some of these from cookies or headers, but that is non-deterministic, and is different for every platform (ie. Google vs AWS vs On Prem (Active Directory)).

Ideally this data is already normalized in the profile controller since we already track email there.. The way I imagine that would be that: Name and email are **mandatory** whereas image is **optional**.

---
/assign @kunmingg @lluunn 
/cc @avdaredevil @prodonjs 
/area profile-controller
/priority p1

**Comment by prodonjs** [comment]
@avdaredevil This doesn't seem applicable any longer given the current understanding of identity awareness and profiles, correct?

**Comment by avdaredevil** [comment]
That is correct, closing.

/close
