### ISSUE TITLE
Document Proxy settings for On-Prem install

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#3347]
When installing on-prem behind a proxy the following environment variables need to be set  `HTTPS_PROXY` and `NO_PROXY`  
where `NO_PROXY=<master-ip>`

The getting started page might be a good location for this.
https://www.kubeflow.org/docs/started/getting-started-k8s/

**Comment by chinmay22897** [comment]
I couldn't see any information which could help me in setting up on-prem kubeflow behind proxy, not at all properly documented.
