### ISSUE TITLE
Add namespace retrieval to environment info API route

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3348]
Namespace selector is a zero-state component so rather than load it with a separate AJAX request, it should be returned alongside the user and platform information that is returned on first-load.

/area front-end
/area centraldashboard
/assign @prodonjs 
/cc @avdaredevil

**Comment by avdaredevil** [comment]
Should we consider an interval refresh, in case namespaces, get added or removed, or are those pretty major events (that won't happen too frequently) thus we should expect a reload in that case?

**Comment by prodonjs** [comment]
I'm assuming that once the UI integration with the Profile Controller is in place, namespace creation should be an event that we are managing. Even then, I wouldn't imagine it's something that a particular user would do all that often where we'd want to grab new namespaces repeatedly.

The other piece that would be interesting to know is whether we only want to show namespaces with Kubeflow items deployed in them. Many of the other namespaces are either for Kubernetes internal components (kube-system) or are not used by the application (default, kube-public). It would be nice if we only showed namespaces that could be used for Kubeflow artifacts.
