### ISSUE TITLE
Deploying kubeflow produces 20000+ log lines making logs hard to read

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#3358]
Excessive trace-level logging makes it very hard to locate the reason for failure.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/1379/kubeflow-pipeline-e2e-test/1131997673897857024

**Comment by jlewi** [comment]
@Ark-kun Can you please clarify what logs you are looking for or what your use case is? 

I assume because you are referencing a prow job you mean the logs from the deploy script used in the E2E tests?

**Comment by Ark-kun** [comment]
> you mean the logs from the deploy script used in the E2E tests

Yes.
