### ISSUE TITLE
Support theia or microsoft visual studio code

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3362]
It is often useful to have a proper IDE when developing models. For example, even when using Jupyter, users may choose to organize python code into modules. They might also want to create additional files like YAML files.

Jupyter's editor capabilities are limited.

Microsoft visual studio code is really nice. In addition, there are an increasing number of plugins adding Kubernetes support to visual studio code.

It would be nice if users could easily run Microsoft visual studio code in a side car of their jupyter pods so they could combine VS code's editor capabilities with jupyter.

coder.com provides a remote server for running visual studio code.

I did some prototyping and it seems pretty straightforward to run vscode in a sidecar of jupyter
https://github.com/jlewi/kubeflow-dev/tree/master/vscode

One issue I've run into is that cdr/code-server#670 prevents it from working behind a reverse proxy.

/cc @kimwnasptd 
/cc @aronchick

**Comment by LeonardAukea** [comment]
@jlewi Nice idea. Would it not make more sense to use vs-code IDE locally and easily communicate with kubeflow apis? In the case of connecting to a server -> https://devblogs.microsoft.com/python/remote-python-development-in-visual-studio-code/
https://github.com/Microsoft/vscode-dev-containers . 
So what I'm getting at is the ability to attach vscode to a running server.

**Comment by jlewi** [comment]
I don't think the too are mutually exclusive.
There are two use cases for running vscode inside the cluster

1. For demos/tutorials it would be nice to have an IDE installed in the cluster and accessible via web browser so we don't have to deal with getting an editor installed locally
1 Being able to edit code stored inside a pod or PVC in the cluster without out having to copy the files back and forth to your local machine to edit.

**Comment by jlewi** [comment]
There's also Theia
https://theia-ide.org/

**Comment by jlewi** [comment]
Thei might be a better option for licensing and Kubernetes reasons. Thei is fully open source.

**Comment by LeonardAukea** [comment]
This is maybe a little much -> https://github.com/ml-tooling/ml-workspace but it has some good things.  I will probably spend a little time next week, to see if I can get something working. Our data sience teams and me included are not solely using notebooks. Also, now that VS Code has nice .ipynb support+ipykernel, jupyterlab is not getting used as much as before.

**Comment by fojtami1** [comment]
@LeonardAukea Same here. We have Docker image with both Jupyter and code-server running but only Jupyter is accessible in Kubeflow. It would be good to have some generic mechanism on how to expose any http service running in Kubeflow custom image.

**Comment by karlschriek** [comment]
@LeonardAukea ml-workspace actually looks like it will cover a lot of the requirements that data science teams are constantly giving me as feedback that they need from Jupyter. Especially these points keep coming up:

🔀 Seamless Git integration optimized for notebooks.
🚪 Access from anywhere via Web, SSH, or VNC under a single port.
🎛 Usable as remote kernel (Jupyter) or remote machine (VS Code) via SSH.

At the moment these three points are fairly trivial to approximate by running Jupyter on a single compute instance, dropping some Git credentials on there and opening an SSH tunnel. The rest is just connecting via web browser or configuring remote connection in VS Code or PyCharm. Because of that it is fairly difficult at this point to make the argument to a team of Data Scientists that they would be better off using Jupyter Server via Kubeflow rather than spinning up their own EC2 instances....

I find this to be really cool as well by the way:
💫 Jupyter, JupyterLab, and Visual Studio Code web-based IDEs.

**Comment by jlewi** [comment]
Exposing additional services each code-server should just be a matter of defining appropriate services and virtual services.

I experimented a bit with theia
https://github.com/jlewi/kubeflow-dev/blob/master/theia/jlewi-nb.yaml

I could access theia I ran into trouble getting extensions installed and turning it into a rich environment.

**Comment by velascoluis** [comment]
Hi, just wondering if this something we are planning for inclusion on KFP Post 1.0 Backlog? We are seeing this demand for the data engineering team, in particular for pipelines component development

**Comment by MotoRZR** [comment]
> Hi, just wondering if this something we are planning for inclusion on KFP Post 1.0 Backlog? We are seeing this demand for the data engineering team, in particular for pipelines component development
> 
> 

Also interested in this. Please advise

**Comment by SpontaneousDuck** [comment]
I was able to get something that worked well enough for us! I made my own Jupyter container as explained in the docs and installed `jupyter-server-proxy` and `jupyter-vscode-proxy` with anaconda into the environment. When I start up my container from Kubeflow, the link to VS code is added as shown below. When you click this it open up your workspace in a separate tab in `code-server`!
![image](https://user-images.githubusercontent.com/23267120/89184801-51dce400-d567-11ea-9769-cd0a7d2a7e08.png)

**Comment by jl-massey** [comment]
> I was able to get something that worked well enough for us! I made my own Jupyter container as explained in the docs and installed `jupyter-server-proxy` and `jupyter-vscode-proxy` with anaconda into the environment. When I start up my container from Kubeflow, the link to VS code is added as shown below. When you click this it open up your workspace in a separate tab in `code-server`!
> ![image](https://user-images.githubusercontent.com/23267120/89184801-51dce400-d567-11ea-9769-cd0a7d2a7e08.png)

I don't suppose you have a tutorial or step-by-step instructions for how you did this, exactly? (that you'd be willing to share)

**Comment by gilbeckers** [comment]
Hi, also interested in this!
 
Maybe another alternative, besides eclipse che, vs code or theia, is Gitpod?

**Comment by vule24** [comment]
### Step to build code-server on kubeflow:

1. Install `code-server`: `curl -fsSL https://code-server.dev/install.sh | sh`
1. Install `jupyter-server-proxy` : `pip3 install jupyter-server-proxy`
1. Install `jupyter-vscode-proxy`: `pip3 install jupyter-vscode-proxy`
1. Install `server-proxy` extension: `jupyter labextension install @jupyterlab/server-proxy` or use extensions manager on jupyterlab frontend.

### Step to build other apps on kubeflow

1. Install your app
1. Install `jupyter-server-proxy` : `pip3 install jupyter-server-proxy`
1. Create `jupyter_notebook_config.py` in one of jupyter path (run `jupyter --paths` to show config path. Eg: `${HOME}/miniconda3/etc/jupyter/jupyter_notebook_config.py`):
`c.ServerProxy.servers = {
  'my-app': {
    'command': ['app','arg1', arg2', ...],
    'absolute_url': True,
    'port': 8080, # app's port
    'timeout': 120,
    'launcher_entry': {
        'enabled': True,
        'icon_path': 'path/to/app/icon.svg',
        'title': 'MyApp',
    },
    'new_browser_tab': True
  }
}
`

**Comment by DavidSpek** [comment]
Support for Visual Studio Code will be present in Kubeflow 1.3. The PR for the notebook-controller has already been merged and the PR for the Jupyter Web App is about to be merged as well.

**Comment by omar16100** [comment]
Very excited for this!
