### ISSUE TITLE
kfctl: default installation is broken

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3367]
**What happened:**
`kfctl apply` failed with:
```
ERRO[0306] (Will retry) Component pipeline apply failed; Error: handle object: creating object: creating object: persistentvolumes "mysql-pv" is forbidden: error querying GCE PD volume <deployName>-storage-metadata-store: googleapi: Error 400: Invalid value '<deployName>-storage-metadata-store'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalidParameter  filename="ksonnet/ksonnet.go:175"
```

**Steps to reproduce:**
1. Checkout commit `f077966c2a2261517708d98833925b37ce150a86` (Friday 24 May 2019)
2. `cd bootstrap` and `make build-kfctl-container`
3. `cd bin` and follow [Kubeflow on Kubernetes guide](https://www.kubeflow.org/docs/started/getting-started-k8s/).

It seems that kfctl isn't changing the name of the PVs for the default installation.
In addition, this installation will not work on non-GCP environments as it specifically creates a GCE Persistent Volume.

**Comment by jlewi** [comment]
I believe @gabrielwen Has a PR to fix this.
Do we have an E2E test that verifies things are working as intended?

**Comment by yanniszark** [comment]
Hi @jlewi!
The PR for fixing Istio VirtualServices for on-prem installations (#3376) also fixes this.
The problem is that the [default ksonnet base overlay](https://github.com/kubeflow/kubeflow/blob/cad6f3f914dab749c4fd77441c05f17c7b134b6f/bootstrap/config/overlays/ksonnet/kfctl_default.yaml) has hardcoded options for using a GCP PD.

Not only that, but those are only handled by the gcp-specific code of `kfctl`, leaving the default installation broken.

In the aforementioned PR, I fixed the default ksonnet overlay so that it contains the correct options for a default installation.

**Comment by kkasravi** [comment]
@jlewi 

@gabrielwen's fix was merged, my suggestion to @yanniszark was to only define these componentParams in one place - though #3375 will remove these values anyway once it's merged.

**Comment by yanniszark** [comment]
I think this is no longer relevant
