### ISSUE TITLE
Create a simple TF model to test TF Serving

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#337]
For E2E testing of TF serving it would be great to have a very simple model; e.g. a model that would just do a matrix multiple.

We should create a simple python script that can produce a model in a format suitable for consumption by TF serving.

For reference we use a similarly simple TF program for testing training
https://github.com/kubeflow/tf-operator/tree/master/examples/tf_sample/tf_sample

**Comment by nishi-t** [comment]
Hi @jlewi,
I want to try this issue for my first contribution. I write simple codes for this issue and put it [my gist](https://gist.github.com/nishi-t/b9002119de7af7c0d23084878b797624) now. 
Where should I put it in the repository for making PR ?

Thnak you,

**Comment by lluunn** [comment]
Since it's for testing, I think it should go to kubeflow/testing.
@nishi-t do you want to send a PR?

**Comment by jlewi** [comment]
@lluunn Won't it be easier to keep the model in the same repository as the rest of the TFServing code? This way you make changes to the code and the test in the same PR?

**Comment by lluunn** [comment]
Ah good point! Sounds good.

**Comment by analyticalmonk** [comment]
Hi @jlewi,
Are you still looking for contribution towards this issues? If yes, I'll like to work on it.

**Comment by jlewi** [comment]
That would be great

**Comment by CSP197** [comment]
Hello @jlewi
I see there is a merged PR referencing this issue (#1271)
Has this issue been fixed? Or are you still accepting contributions for this issue?
-CSP
