### ISSUE TITLE
bootstrap: replace ksonnet with kustomize, move to v2

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3371]
Bootstrap should use the kustomize API and remove calls to ksonnet

**Comment by kkasravi** [comment]
@kunmingg 
bootstrap/cmd/kfctl is mostly done removing references to ksonnet

should I do the same to bootstrap and have you review or would you like to do it and I can review?

thanks
Kam

**Comment by kunmingg** [comment]
@kkasravi 
Great! Once https://github.com/kubeflow/kubeflow/pull/3045 merged everything should go through kfctl + kustomize.

**Comment by jlewi** [comment]
Duplicate of #3368
