### ISSUE TITLE
JupyterHub login unauthorized (401) - Kubeflow Version (0.4.0-rc.2)

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubeflow/kubeflow#3388]
Hi All,

Require your help as new to kubeflow. Basically in order to understand kubeflow i followed steps by steps to deploy  an example which is  - summarizing GitHub issues using a trained model. I deployed this on Kubeflow Version (0.4.0-rc.2). I open the centralized dashbaord it runs fine. When i click on JupyterHub it throws as error of JupyterHub login unauthorized with error code 401. 

[I 2019-06-02 02:29:09.846 JupyterHub proxy:299] Checking routes
[I 2019-06-02 02:29:42.493 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@10.40.1.9) 1.15ms
[W 2019-06-02 02:29:43.821 JupyterHub log:158] 401 GET /hub/login (@10.40.1.9) 1.92ms

In addition even though i am able to open the pipeline page but when i run the sample pipleline it does not show any progress even though everything is running on backend. Like when i run sample parallel example it did not showed anything on UI but completed successfully on backend.

Can anybody please help me on these 2 issues?

**Comment by jlewi** [comment]
Could you please try Kubeflow 0.5?
https://v0-5.kubeflow.org/docs/started/

We replaced jupyterhub in 0.5 with a simple web app which simplifies the authorization story.

Are you deploying on GCP? If not how are you accessing Kubeflow from outside the cluster and how are you handling authorization?

**Comment by hitesh1907nayyar** [comment]
Thanks @jlewi . This is resolved. I installed 0.5 last week.
