### ISSUE TITLE
Python 3.7 is now supported by Tensorflow

### ISSUE THREAD

**Issue by dellelce** [kubeflow/kubeflow#3391]
This is now out of date as Tensorflow now supports 3.7 (see https://github.com/tensorflow/tensorflow/issues/20517):
https://github.com/kubeflow/kubeflow/blob/1f8d0008c02b7582a45d4bce0d7d34ae97c081ce/components/tensorflow-notebook-image/Dockerfile#L97

**Comment by jlewi** [comment]
@dellelce Thanks any interest in submitting a PR to fix this?
