### ISSUE TITLE
[ksonnet] RUNTIME ERROR: Field does not exist: core

### ISSUE THREAD

**Issue by aichiludan** [kubeflow/kubeflow#340]
When i run
 
ks apply default -c kubeflow-core

it returns the follow error:

ERROR generate objects for namespace : unable to read /root/my-kubeflow/environments/default/main.jsonnet: RUNTIME ERROR: Field does not exist: core

And running some other ks commands also returns the same error. Who can help me fix this

**Comment by pineking** [comment]
@aichiludan is it the same issue as  https://github.com/kubeflow/kubeflow/issues/318 ?

**Comment by wbuchwalter** [comment]
This looks to be the same thing, and no answer, so closing for now.
@aichiludan if #318 doesn't fix your issue, let us know and we will reopen this one.
