### ISSUE TITLE
Not able to access any of the dashboards (Pipeline, TFJob, Katib, etc.) from Central Dashboard upon changing the Central Dashboard type to NodePort. 

### ISSUE THREAD

**Issue by sahilmalav** [kubeflow/kubeflow#3401]
I want to be able to access all the dashboards from an external IP. For this purpose, I changed the type of Central Dashboard, ML Pipeline, Jupyter and other related services to NodePort. Now I can access the Central Dashboard, but upon trying to access any of the dashboards from the Central Dashboard, I get an error of the form "Sorry, /pipeline/ is not a valid page". How do I access these dashboards from an external IP?
I'm using Kubeflow 0.5.1 on Kubeadm.

**Comment by jlewi** [comment]
Ambassador provides a reverse proxy that makes all the services available. You need to expose Ambassador (e.g. via an ingress or node port). 

If you expose it on an external IP you'll probably want to secure it using some form of authentication.

**Comment by sahilmalav** [comment]
I did expose Ambassador using NodePort, but it didn't seem to work. I can access the central dashboard, but not any of the dashboards within the central dashboard. Whenever I try accessing the pipeline dashboard for example, I get the error "Sorry, /pipeline/ is not a valid page".

**Comment by sahilmalav** [comment]
Solved. The problem was with persistent volume. I had to manually create three PV and PVC for mysql, vizier and minio. After that it ran fine.

**Comment by porimolchandro** [comment]
Hey @sahilmalav 
I'm facing same issue! Can you please explain a little bit more how did you solved?

**Comment by porimol** [comment]
Hey @sahilmalav 

I'm facing same issue! Can you please explain a little bit more how did you solved?

**Comment by sahilmalav** [comment]
@porimol : Check your pods in the Kubeflow namespace. If mysql and minio pods are failing, it's most likely due to unbound persistent volumes. They require one persistent volume each for storing data. Check if their PVCs are bound. If not, delete the existing ones and create PVC and PV for them manually.
