### ISSUE TITLE
Remove notebook.status.ContainerStatus

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#3406]
Once [this issue](https://github.com/kubeflow/kubeflow/issues/3405) is resolved we should remove notebook.status.ContainerStatus.

**Comment by kimwnasptd** [comment]
Also related with #3820. 

I think we shouldn't remove the `ContainerStatus`, but rather show the containerStatus of all the containers in the Pod. This way we can show errors that might occur in all the Containers and not just the one with the Notebook Image.

I would also be interested in picking this up.
/assign @kimwnasptd
