### ISSUE TITLE
kfctl: GetConfig() doesn't handle errors correctly

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3409]
When `GetConfig()` encounters an error, it doesn't surface it, but just logs the error with level=warning (should be error) and returns a nil *rest.Config pointer.
https://github.com/kubeflow/kubeflow/blob/23972866b2cdb771dead47e6839a5569206a9f85/bootstrap/pkg/apis/apps/group.go#L265-L275

 `GetConfig()` should be fixed to either return an error or panic.
I'm leaning with the first option, return an error and let the caller handle it.

**Comment by elviraux** [comment]
@yanniszark Hi, what's the status of it?

**Comment by yanniszark** [comment]
@elviraux not fixed.

**Comment by yanniszark** [comment]
cc @kkasravi @gabrielwen

**Comment by kkasravi** [comment]
@yanniszark 
As I recall - we return a warning intentionally for gcp. @kunmingg do you recall the exact reason? I think it was related to protect concurrent access. Calling panic will break gcp unless this behavior has changed.
