### ISSUE TITLE
how to read the data file in hdfs(clouder hadoop) if using kubeflow for deep learning

### ISSUE THREAD

**Issue by yisampi** [kubeflow/kubeflow#3416]
how to read the data file in hdfs(clouder hadoop) if using kubeflow for deep learning or machine learning?

**Comment by jlewi** [comment]
@jpatanooga @rawkintrevo @holdenk as our resident Hadoop experts do you have any pointers here?

**Comment by holdenk** [comment]
Sure, writing a Spark job would probably be the simplest way, you can then transform it into whichever format you want & put it wherever your downstream components needs to read from (say GCS, S3, etc.). The exact details of how to do this depend on the input format (HDFS is a filesystem with many different file formats written to it) and the target format (e.g. are you doing tensorflow downstream or something else)?
