### ISSUE TITLE
Authorization through RBAC for K8s and Istio resources

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#3417]
Master Issue: #3096 

Scope:
1) Authentication through Kubernetes OIDC
2) Istio requests authenticated through the end user authentication policy facility in Istio
3) All Kubeflow services should be Authorized through Istio service role and binding
4) Kubernetes resources should be authorized through Kubernetes RBAC

- [x] Define 3 policies for users with privileges:
  - [x] Read
  - [x] Write
  - [x] Admin
- [x] Script to apply these manifests to users
- [x] Tests for verifying previledges through authorization

Design Doc: http://bit.ly/2WPs1MS
Demo presentation link: http://bit.ly/31Td2V3

Linked to [On-Premise Project](https://github.com/orgs/kubeflow/projects/18)

[Issue title and description has been edited]

**Comment by jlewi** [comment]
@krishnadurai Does this mean that will be using ISTIO policies to control access to K8s resources? e.g. somehow we will be using ISTIO to determine whether user Alice can create/delete TFJobs in namespace alice-kf?

Or is this issue about using ISTIO control network policies; i.e control whether user alice can access Jupyter over http in namespace alice-kf?

**Comment by krishnadurai** [comment]
Yes, this issue means we will be using Istio policies to control access to K8s resources.

No, this does not mean access control for Jupyter over http in namespace alice-kf.

**Comment by jlewi** [comment]
Why not just use RBAC to control access to K8s resources as opposed to ISTIO?

I was thinking that we have 3 different types of resources

* K8s resources
* Network resources (e.g. http endpoints)
* Cloud resources

Each of these has their own IAM system

* K8s has RBAC
* ISTIO RBAC for network endpoints
* Cloud IAM for each cloud IAM resources

Why not just use each resources' appropriate IAM system and provide tooling as needed to make managing all of them easier?

Apologies if this has been discussed at the recent on prem working group meeting (I was not able to attend).

/cc @kkasravi @vkoukis @animeshsingh

**Comment by krishnadurai** [comment]
@jlewi I apologise for misunderstanding the question, I had thought the intent of your question was to have a network rule on Istio to control access. Here I intend to make use of a (Kubeflow based) service and apply a policy on Istio to control access to current Kubernetes resources - tfjob.

The intent is to use appropriate IAMs at each level as you've mentioned. This leaves the k8s resources' policies to be set on k8s RBAC.

**Comment by jlewi** [comment]
So is the idea here as described in your design doc to create an API gateway through which access to all k8s resources is mediated? 

Your design doc had multiple options in it. Could you provide a link to the option you are currently thinking of implementing?

**Comment by krishnadurai** [comment]
We are going ahead with [approach II](https://docs.google.com/document/d/1WS9l45oIbWfxRWNQeisI3NIXfcIh0l9aHN_Fl3MQreU/edit#heading=h.vihzmxyvrbzx) mentioned in the document.

The idea with this issue is to create an endpoint which may in-turn call these underlying k8s resources. This may be useful in cases where a user may want to directly deploy a model through an single API call.
Whereas this implementation would allow direct access to Kubernetes API or kubectl for all k8s resources.

**Comment by cblackd7r** [comment]
@krishnadurai Let me know if you have fork or PR that you have started.  Would like to help contribute cycles to this feature.

**Comment by krishnadurai** [comment]
@cblackd7r Sorry for not replying earlier.

I've created a PR which should do some context setting around this issue.
https://github.com/kubeflow/kubeflow/issues/3417

**Comment by nrchakradhar** [comment]
@krishnadurai 
Is there a PR which can be seen. I see the link above refers to this issue only.

**Comment by krishnadurai** [comment]
@nrchakradhar Here's the PR

https://github.com/kubeflow/manifests/pull/195

**Comment by krishnadurai** [comment]
@jlewi this issue is done.

/close
