### ISSUE TITLE
provide a fixed set of yaml files under bootstrap/config that reflect kfctl cli options  

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3419]
overlays under bootstrap/config (basic_auth,  gcp,  istio,  ksonnet, kustomize) are used to create a kfctl_default.yaml in Coordinator.Init by applying StrategicMergePatch to the set of overlays that match the kfctl cli options (--platform, --basic_auth, --use_istio).

Rather than do this within Coordinator, it should be done within separate tooling that generates different kfctl_default.yaml files across the permutation of cli options. Coordinator would then just derive the kfctl_default* filename and use that.

The location and name of the config file will incorporate the cli-options:

config/{platform}/kf{-basic_auth}{-istio}.yaml

permutations:
- platform=gcp
  - config/gcp/kf.yaml
  - config/gcp/kf-istio.yaml
  - config/gcp/kf-basic_auth.yaml
  - config/gcp/kf-basic_auth-istio.yaml
- platform=none
  - config/kf.yaml
  - config/kf-istio.yaml

invalid option combinations result in the absence of the file and a usage message from kfctl

**Comment by jlewi** [comment]
Should we aim to get rid of the different flags and just take the name of the YAML config file e.g.

```
kfctl init --config=kfctl_gcp_istio.yaml
```

This would allow us to eventually support URIs e.g.

```
kfctl init --config=https://github.com/kubeflow/kubeflow/myconfig.yaml
```
So people could easily create and share new configs.

**Comment by kkasravi** [comment]
I think this is a good idea, it would solve a few problems.

**Comment by kkasravi** [comment]
the existing bootstrap/config/{base,overlays} should be moved into manifests so that tooling in manifests can generate new config files if utilized.
