### ISSUE TITLE
Terminal of Jupyter Notebooks from jupyter not working.

### ISSUE THREAD

**Issue by otaviocv** [kubeflow/kubeflow#3421]
I've just made a new fresh installation of kubeflow in  brand new AWS EKS cluster with kubeflow 0.5.1. When I start a new jupyter server I can't open a new terminal.

**Comment by otaviocv** [comment]
I don't even know where to get logs.

**Comment by jlewi** [comment]
So your able to access the Jupyter UI but when you click new terminal in the Jupyter UI nothing happens

Can you please provide the spec of the notebook

List the notebooks 

```
kubect get notebeook
kubectl get -o yaml notebook <YOUR NOTEBOOK>
```
Upload the YAML to the issue.

You can get the logs for the associated notebook pod

```
kubectl logs <YOUR NOTEBOOK>-0
```

Can you upload those to the issue as well please?

Does the chrome JS console show any errors when you try to start a new terminal?

**Comment by Jeffwan** [comment]
@otaviocv 

We back port few changes to v0.5.1 and update official documentation. I've tested istio parts it looks good to me. Please have another test and let me know if your issue is resolved

**Comment by otaviocv** [comment]
I was using kubeflow v0.5.1 when this issue happened. But somewhat the terminal got back working. I will reopen this issue if the problem gets back.
