### ISSUE TITLE
Clean up ambassador mapping annotations

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3422]
After #2766 we no longer need ambassador mapping annotations for the most of manifests.  Only the following components needs the annotation as far as I can think of:
- basic-auth
- basic-auth login UI
- `istio-mapping-service` in #3404

**Comment by gabrielwen** [comment]
cc @lluunn

**Comment by jlewi** [comment]
It might be good to leave the annotations in place at least until 0.7. In theory this would allow people to continue to use Ambassador as their gateway rather than ISTIO.
