### ISSUE TITLE
notebook controller infinite looping on "Updating StatefulSet"

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3425]
Version latest master:
gcr.io/kubeflow-images-public/notebook-controller:v20190603-v0-175-geeca4530-e3b0c4

**Comment by kunmingg** [comment]
@gabrielwen @lluunn

**Comment by kunmingg** [comment]
Virtual service is not created.

**Comment by jlewi** [comment]
Closing as obsolete.
