### ISSUE TITLE
why my pod in kubeflow namesapce can not Connecting to the public network？？？？？？？？DNS？？？？？？？

### ISSUE THREAD

**Issue by JK-97** [kubeflow/kubeflow#3431]
issue：
pod in kube-system  can connect to the public network
pod in kueflow can can connect to the public network

----------(kubectl exec in a pod ,namespace kube-system )
$cat /etc/resolv.conf
nameserver 127.0.1.1
----------(kubectl exec in a pod ,namespace kubeflow )
$cat /etc/resolv.conf
nameserver 10.96.0.10

guess:
maybe it is due to dns

but how can i change it ?????????????

**Comment by jlewi** [comment]
How are you deploying and managing K8s?

Kubeflow doesn't setup any DNS or other cluster networking settings. So this is most likely an issue with your K8s setup and not Kubeflow.

You could confirm this by seeing if you have the same problem in any namespace you create.

**Comment by JK-97** [comment]
I am deploying a local cluster with kubeadm，
use this yaml files deploy dns:
`kubeadm` init `--pod-network-cidr=10.244.0.0/16`

`kubectl` apply -f `https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/rbac.yaml`
`kubectl` apply -f `https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml`

-----
but i don't know how to Modify configuration file。
is this?:
`kubectl -n <namespaces> edit svc <service>`

**Comment by JK-97** [comment]
> I am deploying a local cluster with kubeadm，
> use this yaml files deploy dns:
> `kubeadm` init `--pod-network-cidr=10.244.0.0/16`
> 
> `kubectl` apply -f `https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/rbac.yaml`
> `kubectl` apply -f `https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml`
> 
> but i don't know how to Modify configuration file。
> is this?:
> `kubectl -n <namespaces> edit svc <service>`



> How are you deploying and managing K8s?
> 
> Kubeflow doesn't setup any DNS or other cluster networking settings. So this is most likely an issue with your K8s setup and not Kubeflow.
> 
> You could confirm this by seeing if you have the same problem in any namespace you create.

**Comment by JK-97** [comment]
my coredns file ：
   apiVersion: v1
    data:
    Corefile: |
        .:53 {
            errors
            health
            kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
            }
            prometheus :9153
            proxy . /etc/resolv.conf
            cache 30
            reload
            loadbalance
        }
    kind: ConfigMap
    metadata:
    creationTimestamp: 2019-05-05T08:22:27Z
    name: coredns
    namespace: kube-system
    resourceVersion: "9385"
    selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
    uid: eb157cfb-6f0e-11e9-92a9-0492264b2d9d

**Comment by jlewi** [comment]
@JK-97 Kubernetes networking issues are a little outside the scope of our expertise.

You might have better luck with 

* kubeadm channels
* coredns channels

If you are using public cloud using that Clouds recommended Kubernetes install.
