### ISSUE TITLE
Rewrite the jupyter-web-app using a web framework

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#3439]
The webapp is currently written in plain HTML/JS. The reason behind that was to leverage existing code from the previous JupyterHub implementation. But using plain HTML/JS makes it more difficult to add more advanced features to the UI, such as a multi select for #2992. Also, it is making it more challenging to modularize the code in order to reduce code duplication.

Rewritting the webapp in a framework could tackle most of these problems and make to webapp easier to maintain and further develop.

/cc @jlewi @avdaredevil @prodonjs

**Comment by avdaredevil** [comment]
This is a great idea! Thanks @kimwnasptd. A few notes:
- What framework are you planning on using? (_we personally have no strong preference, though central-dashboard is written in [Google Polymer](https://polymer-library.polymer-project.org/)_)
- Could you make sure to integrate:
  - Style Guide: #2878 (_uniform styling across all kubeflow-apps_)
  - Central-Dashboard SDK: #3427 (_for namespace change event detection_)

**Comment by kimwnasptd** [comment]
I'm planning on using Angular 7 as I'm not that much familiar with Google Polymer. 

Sure! Using the style guide from #2878 will definitely improve the UX and will be a good step to uniform the styling of our kubeflow apps. I'll also make sure to use the centraldashboard's library for namespace change detection. I might need some of your's and @prodonjs's UI expertise for some implementation details.

**Comment by jlewi** [comment]
@kimwnasptd @avdaredevil Rewriting the web-app seems like a potentially time consuming and risky.

Should we target 0.7 for this issue and try to find a simpler solution for #2992 in 0.6?
