### ISSUE TITLE
JupyterLab version in default images is outdated

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#3442]
It would be nice if it included this fix https://github.com/jupyterlab/jupyterlab/pull/5814 for https://github.com/kubeflow/pipelines/issues/252

**Comment by jlewi** [comment]
@Ark-kun Has this been released? What version of jupyter lab do you want?

We should be installing the latest version of jupyter from pip
https://github.com/kubeflow/kubeflow/blob/5c4fc0b0afab30b7a43dae534db8d3a633ccf214/components/tensorflow-notebook-image/Dockerfile#L119

**Comment by Ark-kun** [comment]
Can you check your version using pip3 freeze?
The version in my notebook is 0.35.4 https://pypi.org/project/jupyterlab/0.35.4/ which has been released in November while the fixed version is 0.35.5 https://pypi.org/project/jupyterlab/0.35.5/

**Comment by Ark-kun** [comment]
> We should be installing the latest version of jupyter from pip

Technically, that's not guaranteed
That command first installs tensorflow (which might be installing some old version of jupyterlab) and then asks to have any version of jupyterlab without `--upgrade`.
https://github.com/kubeflow/kubeflow/blob/5c4fc0b0afab30b7a43dae534db8d3a633ccf214/components/tensorflow-notebook-image/Dockerfile#L121

AFAIK, this issue is solved though.

**Comment by Ark-kun** [comment]
I've verified that it's fixed in KF 0.7
