### ISSUE TITLE
General compatibility in AWS with Kiam/Kube2Iam

### ISSUE THREAD

**Issue by amarrella** [kubeflow/kubeflow#3446]
Hi there :) Thanks again for this project!

I'm getting more and more familiar with this project and I'm trying to run it in AWS (EKS) .
I can successfully run pipelines and create notebook servers now, but a feature that would be really helpful would be supporting Kiam/Kube2Iam so that we can manage permissions in a better way.

Would it be possible to:
- Add the possibility to add pod annotations via the Jupyter Web App UI
- Add the possibility to add pod annotations to the TFJobs 
- Add the possibility to add pod annotations to the pipelines components and make sure that all pipelines components can fall back to the metadata api if the aws environment variables are not set? (Kiam/Kube2Iam intercept these requests to provide credentials). This is also an issue with the Pipeline UI because currently we couldn't find a way to successfully use s3 to store for example the roc results and read it from the UI (we get access denied, because the minioclient expects these environment variables to be set https://github.com/kubeflow/pipelines/blob/master/frontend/server/server.ts#L74 )

Thanks in advance for your help :) 
Alessandro

**Comment by Jeffwan** [comment]
@amarrella 

Could I know if you're running on AWS or EKS? If it's EKS,  Our engineers are working on pod level IAM this would be release very soon. This would be a perfect fit for this case. 

If it's AWS, essential requirement for KIAM or kube2iam will be helpful.

**Comment by amarrella** [comment]
Hi @Jeffwan, yes I mean EKS apologies. this I great news :) thanks!

**Comment by Jeffwan** [comment]
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

EKS team release Fine-Grained IAM roles for service accounts. Please have a check of this feature. I am going to integrate this feature to kfctl AWS plugin and manifest
