### ISSUE TITLE
Importing Pipleline in Kubeflow automatically

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubeflow/kubeflow#3450]
Hi, 

I need to import a pipeline into Kubeflow automatically (Without UI). Is there any rest api enabled which can be called once kubeflow is installed on kubernetes or any other method ?

Best Regards
Hitesh Nayyar

**Comment by jlewi** [comment]
@vicaire @Ark-kun @IronPan Can you assign to someone who knows the answer?

**Comment by vicaire** [comment]
You could use the swagger client: https://github.com/kubeflow/pipelines/tree/master/backend/api/swagger

**Comment by hitesh1907nayyar** [comment]
Hi @vicaire 

Thanks for your help!

Can you please let me know how to use this ?  Steps to be performed or a sample example that i can do ?

Best Regards
Hitesh Nayyar

**Comment by vicaire** [comment]
I think @IronPan wrote some documentation about this recently. Assigning to him to provide pointers.
