### ISSUE TITLE
kfctl + kustomize on GKE not working

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3456]
```
kfctl init kf0612 -V --platform=gcp --package-manager=kustomize --skip-init-gcp-project --project=XX
kfctl generate all
kfctl apply all
```

Apply succeeded, but endpoint not accessible.
Also, I forgot to set client id and secret, but it didn't raise error

**Comment by lluunn** [comment]
Error on ingress:
error while evaluating the ingress spec: error getting BackendConfig for port "80" on service "istio-system/istio-ingressgateway", err: no BackendConfig for service port exists.

**Comment by lluunn** [comment]
the backend config name has prefix iap-ingress-, so there is a mismatch

**Comment by lluunn** [comment]
Also, certificate is referencing ingress, and the name is also mismatch

**Comment by kkasravi** [comment]
Hi @lluunn 

we have this in testing/kfctl/kf_is_ready_test.py
```
  if use_basic_auth:
    deployment_names.extend(["basic-auth-login"])
    stateful_sets.extend(["backend-updater"])
  else:
    ingress_related_deployments.extend(["iap-ingress-iap-enabler"])
    stateful_sets.extend(["iap-ingress-backend-updater"])
```

maybe we're not setting the right basic-auth components in app.yaml?

**Comment by lluunn** [comment]
I am testing iap as far.
In my PR https://github.com/kubeflow/manifests/pull/129 I removed name prefix for iap-ingress component.

**Comment by kkasravi** [comment]
that might result in duplicate components - i'll run as well, see if i can fix ingress so it doesn't care if basic-auth or iap-ingress is used

**Comment by lluunn** [comment]
ingress bootstrap pod error:
 message: Couldn't find key istioNamespace in ConfigMap istio-system/parameters
        reason: CreateContainerConfigError

**Comment by jlewi** [comment]
@lluunn What improvements to the E2E test are needed to verify that IAP is working?

* In the past, one of the problems with testing IAP was that we would have to manually update the OAuth credential with the redirect URI which would be unique for each deployment.

* With universal redirect that might no longer be an issue.

* The other issue we might run into is running into Lets-encrypt issues quota issues.

* We could use the trick we use in our auto-deploy clusters of replacing the cert with a self signed certificate
 https://github.com/kubeflow/testing/blob/1009294940b2d873cc811f68eb6093eef474cf85/py/kubeflow/testing/create_kf_instance.py#L285

**Comment by kkasravi** [comment]
looks like 'parameters' config-map needs to have a prefix in kustomization.yaml

**Comment by kkasravi** [comment]
it looks like there are a number of configmaps that have parameter or parameter+suffix names
```
$ ☞  kubectl get configmaps
NAME                                              DATA   AGE
application-controller-parameters                 1      37m
cert-manager-parameters                           2      35m
cloud-endpoints-parameters                        2      35m
jupyter-web-app-config                            1      36m
jupyter-web-app-parameters                        5      36m
katib-parameters                                  1      36m
metricscollector-template                         1      36m
minio-parameters                                  3      35m
ml-pipeline-viewer-viewer-parameters-d7c4mdtm9k   1      35m
notebook-controller-parameters                    2      36m
overlay-params                                    2      35m
parameters                                        1      36m
parameters-765kf622h4                             2      36m
parameters-d7h2725c8g                             1      35m
pytorch-operator-config                           1      36m
spartakus-parameters                              1      36m
tf-job-operator-config                            1      36m
ui-parameters-hb792fcf5d                          1      35m
worker-template                                   1      36m
workflow-controller-configmap                     1      37m
workflow-controller-parameters                    11     37m
```

**Comment by kkasravi** [comment]
for ./iap-ingress/base/kustomization.yaml and ./basic-auth-ingress/base/kustomization.yaml maybe we should name them both 
```
configMapGenerator:
- name: iap-ingress-parameters
  env: params.env
```
and update the vars section in both

**Comment by lluunn** [comment]
Another problem: my cloudendpoint is pending forever, and the pod shows:

```
2019/06/12 20:19:56 [INFO][kf0612-2] waiting for Ingress envoy-ingress
2019/06/12 20:19:58 [INFO][kf0612-2] Create pending
2019/06/12 20:19:58 [INFO][kf0612-2] waiting for Ingress envoy-ingress
2019/06/12 20:20:00 [INFO][kf0612-2] Create pending
2019/06/12 20:20:00 [INFO][kf0612-2] waiting for Ingress envoy-ingress
2019/06/12 20:20:02 [INFO][kf0612-2] Create pending
2019/06/12 20:20:02 [INFO][kf0612-2] waiting for Ingress envoy-ingress
```

**Comment by lluunn** [comment]
According to this: https://github.com/danisla/cloud-endpoints-controller/blob/master/cmd/cloud-endpoints-controller/main.go#L335
It can't find the ingress.

Seems the cloudEndpoint.spec.targetingress doesn't specify the namespace

**Comment by lluunn** [comment]
Another problem: the backend-updater cannot find ingress because the namespace env var is not set correctly:

When I exec into the pod
```
 echo $NAMESPACE
$(istioNamespace)
```

That's not replaced

**Comment by lluunn** [comment]
With the current fix in https://github.com/kubeflow/manifests/pull/129, the ingress seems healthy.
But when I visit the endpoint, I got Origin authentication failed.

**Comment by jlewi** [comment]
@lluunn Is that error related to ISTIO JWT validation? 

@lluunn  What checks could we add to [kf_is_ready_test.py](https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py) to catch these errors?

With universal redirect, the endpoint should now be accessible via IAP so we could verify that we can actually connect to the central dashboard using IAP.

**Comment by jlewi** [comment]
No longer relevant.
