### ISSUE TITLE
Fix healthcheck for istio-ingressgateway

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3459]
Previously istio-ingressgateway doesn't support health check, so we hack it by routing to another service: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/gcp/healthcheck_route.yaml

We should configure it properly now with istio 1.1.

**Comment by lluunn** [comment]
istio-ingressgateway now has a status-port.
We should change our healthcheck to point to that

**Comment by jlewi** [comment]
@lluunn What is the priority of this? Should we mark it P1 and try to get it done for 0.6?

**Comment by lluunn** [comment]
yeah, we should fix it in 0.6
/priority p1

**Comment by lluunn** [comment]
Health check is working with the change in https://github.com/kubeflow/manifests/pull/129

We should then:
1. remove the health check route rule since it's not needed
1. i think in jwt validation policy we don't need to exclude /healthz because the ingress health check is not on port 80

But first I think we should setup the test

**Comment by jlewi** [comment]
@lluunn Any update on this ?

**Comment by jlewi** [comment]
Is this blocking us from cutting a release? If it is lets mark it P0.

**Comment by lluunn** [comment]
this is fixed

**Comment by lluunn** [comment]
actually let me verify it today

**Comment by lluunn** [comment]
I tried master kfctl with IAP, able to access centraldashboard
