### ISSUE TITLE
Add/fix admission-webhook to  kfctl kustomize default components

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#3469]
admission-webhook is implemented using two components (bootstrap and webhook) in kustomize ([see here](https://github.com/kubeflow/manifests/tree/master/admission-webhook)) . However its components are not added to kustomize kfctl components.  
/cc @kkasravi

**Comment by yanniszark** [comment]
@zabbasi thanks for opening this.
I also bumped into this today and I was very confused by it.
This seems to be a bug inside the `mapDirs` function.
https://github.com/kubeflow/kubeflow/blob/24c39e3cd66862b9433f23f7f9cc2937c70a39dd/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L522

@kkasravi what exactly does the mapDirs function look for?
Can't we just look for the presence of the base/overlay dirs to decide if a directory is a component?
It looks like component discovery breaks for this case.

/cc @jlewi I believe that this should be very high priority for the ksonnet turndown.

**Comment by jlewi** [comment]
Can we add an appropriate test to ensure the admission hook is properly deployed?

e.g. can we add a check here
https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py
