### ISSUE TITLE
Failed to pull image "gcr.io/kubeflow/tf-benchmarks-gpu:....

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#348]
Was working yesterday. Just tried to re-deploy the tf-cnn job and cdk-tf-cnn-worker-... keeps throwing:
Failed to pull image "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

then ultimately results in:
Failed to pull image "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3": rpc error: code = Canceled desc = context canceled.

cf-tnn-ps... deploys fine.

**Comment by jlewi** [comment]
I tried pulling it and it worked:

```
gcloud docker -- pull gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3
v20171202-bdab599-dirty-284af3: Pulling from kubeflow/tf-benchmarks-gpu
Digest: sha256:f3f82df1752ad6190892b56c14773125cec7c0ff7f169107cb32e1e11cc57536
Status: Image is up to date for gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3
```

The image is defined; [gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3](http://gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3).

Are you sure its not an issue with your network connection? Can you retry?

**Comment by ernestmartinez** [comment]
Network was fine, I tried a bit later and it worked. I should have just tried a pull as you did.

**Comment by jlewi** [comment]
Glad its resolved.
