### ISSUE TITLE
Too much daily Stackdriver log volume

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/kubeflow#3485]
Stackdriver produces 43.75 gibibyte logs per day. 
Is this the expected amount of log ingests per day?

![Bildschirmfoto 2019-06-18 um 08 30 02](https://user-images.githubusercontent.com/1991664/59658235-57307100-91a3-11e9-9d60-c7b575b16ded.png)

**Version:**
Kubeflow: Build commit: c938247
Kubeflow created with the UI (GCP)

**Comment by SaschaHeyer** [comment]
Issue still exist

**Comment by vladislavkoz** [comment]
Yes, we have the same from the application-controller-stateful-set. It produces a lot of logs that are going to error logs on stackdriver.

**Comment by ValentinVerkhohliad** [comment]
Faced this today

**Comment by vladislavkoz** [comment]
![image](https://user-images.githubusercontent.com/40685761/92127699-3f75f480-ee0a-11ea-961f-efb6c4381d71.png)
