### ISSUE TITLE
application CR needs to create a suffix for the instance label

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3489]
see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Comment by jlewi** [comment]
@kkasravi Does this issue mean that we need our kustomize packages to generate a unique suffix for the instance label that gets attached to each resource owned by the application?

**Comment by kkasravi** [comment]
Yes, exactly

**Comment by jlewi** [comment]
Bump to P0 because this is required for upgrades and thus 0.7 blocking.

**Comment by kkasravi** [comment]
@jlewi If we merge #4052 I'll sync with kfctl.

I haven't tallied what PR's remain that are bootstrap/kfctl related.
