### ISSUE TITLE
kfctl: kustomize: patchesStrategicMerge fails if filename of patch doesn't equal original filename

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3490]
In order to make kustomize more flexible, @kkasravi added functionality to `kfctl` that merges 1+ overlays like mixins.
However, it seems that it doesn't handle `patchesStrategicMerge` correctly.
More specifically, it contains the implicit assumption that filenames in the `patchesStrategicMerge` field will match filenames in the base directory.

This has caused errors in the CI:
```
util.py                     71 INFO     couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error
:  (kubeflow.error): Code 500 with message: error generating kustomization for pipeline/minio Error open /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-basic-auth-3470-34f0
d8e-7792-a3e8/kfctl-a3e8/.cache/manifests/master/pipeline/minio/base/persistent-volume-claim-patch.yaml: no such file or directory
generated xml file: /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-basic-auth-3470-34f0d8e-7792-a3e8/output/artifacts/junit_kfctl-build-testbasic-auth-istio.xml
```

@kkasravi it seems this certain piece of code is for the case where we are looking at a KfDef file.
Can you please help in fixing this?

cc @jlewi for the ksonnet-turndown

https://github.com/kubeflow/kubeflow/blob/24c39e3cd66862b9433f23f7f9cc2937c70a39dd/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L1005-L1008

**Comment by jlewi** [comment]
@kkasravi @jbrette @yanniszark is this issue still relevant? Will the move to kustomize 3 impact this?

**Comment by kkasravi** [comment]
> @kkasravi @jbrette @yanniszark is this issue still relevant? Will the move to kustomize 3 impact this?

it should be fixed - the move to kustomize3 won't impact this

**Comment by yanniszark** [comment]
@kkasravi what version should I check in order to confirm that it is fixed?
Is the fix in master right now?

**Comment by kkasravi** [comment]
my bad - yannis - I meant I should fix this bug, not that I fixed the bug

**Comment by yanniszark** [comment]
/reopen
/remove-lifecycle stale
/lifecycle frozen

@kkasravi @gabrielwen any updates on this?

**Comment by jlewi** [comment]
Does kustomize now have the ability to support multiple overlays?

How is what we need different from kubernetes-sigs/kustomize#171 which says multiple overlays are supported?

There's also kubernetes-sigs/kustomize#1251 about diamond patterns

**Comment by yanniszark** [comment]
@jlewi kustomize doesn't support multiple overlays as seen in the composition pattern.
This is why we opened #1251 and we have seen some great developments. Would be great if folks from the Kubeflow community would also push for it.
/cc @apyrgio

This issue is about a bug in the current implementation of kfctl that composes a new kustomization to get around this issue.
We should test to see if this issue still exists.

**Comment by jlewi** [comment]
Should we just refactor our kustomize packages to not depend on combining overlays like mixins/diamond pattern?

I believe kustomize supports the case where an overlay references another overlay.

Right now most of our applications have two overlays istio and application both of which are
referencing base.

But we could restructure this as 

base -> istio -> application

Which I believe is supported by kustomize kubernetes-sigs/kustomize#171

Related thread: https://groups.google.com/forum/m/#!topic/kubeflow-discuss/qH56Yoz4SoE

**Comment by xaniasd** [comment]
If we "hardwire" overlays, don't we also enforce their usage?

Currently overlays are optional (I can skip istio by omitting the overlay) and this allows a lot of flexibility in deployment configurations. For instance, metadata db is installed as an overlay; if I want to use an existing database I can skip this overlay altogether. Same with istio; I haven't tried it but I suppose I can still use an alternative.

**Comment by jlewi** [comment]
i'm closing this issue because I think the path forward is to remove the kustomization magic as noted in kubeflow/manifests#774.

@xaniasd you can still optionally use overlays. This functionality is provided by kustomize. So you would just use kustomize rather than relying on kfctl to dynamically generate kustomization.yaml files.
