### ISSUE TITLE
upgrade to use kustomize v3+

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3497]
kustomize v2.0.3 had a number of limitations including not guaranteeing ordering of resources which caused us to create components for just crds. We should upgrade to v3+ and update manifests to remove workarounds for these limitations as well as take advantage of other new features.
Note: kustomize releases page is [here](https://github.com/kubernetes-sigs/kustomize/releases)

Kustomize 3.0 is being released the end of June 2019. Several features worth noting:
- bases are deprecated, everything is a resource. This makes overlays / mixins much simpler
- env becomes envs and can take a list - which could be the contents of param.env
- resource ordering is preserved
- apply will add an inventory object which can be used as a cache
- user plugins are given equal footing with built-in plugins
- plug-ins can be chained for example a generator plugin producing a list of applications could be the input to individual application generators
- edit can now remove resources 
- subcommands like apply can be implemented server-side using CRDs and an example is in cli-experimental

**Comment by jlewi** [comment]
@kkasravi Do we want to do this before 0.6 or can we wait for 0.7?

**Comment by kkasravi** [comment]
it would be valuable to get it in even if we don't fix the crds workaround.

**Comment by jlewi** [comment]
@kkasravi @jbrette Any update on this?

What sort of risk is involved with upgrading to v3? Is v3 backwards compatible with our existing manifests?

**Comment by jlewi** [comment]
Bump to P0 because we should figure out whether we are upgrading and if so when & how prior to Kubeflow 1.0.

**Comment by jbrette** [comment]
@jlewi This should have been closed a long time ago. At least the upgrade in the kubeflow and the manifest has been merged. I did not follow since but I had in mind something was supposed to be replicated in the kfctl repo.

**Comment by kkasravi** [comment]
@jlewi @jbrette yes we're using kustomize v3.1.0 in kubeflow/kfctl
https://github.com/kubeflow/kfctl/blob/master/go.mod#L89

**Comment by kkasravi** [comment]
@jlewi this can be closed
