### ISSUE TITLE
Proposal: Discuss Kubeflow organization and community 

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#35]
Current proposal (by @aronchick):
* Find an hour when we can discuss the overall community plans. This should include:
  * What org this should roll up to
  * If/when this moves to a foundation
  * Calendar for the next ~6 months
  * Community language for the website (e.g. guidelines, ownership, etc)

cc @willnorris @erikerlandson @foxish @elmiko

**Comment by erikerlandson** [comment]
cc @willb

**Comment by ddysher** [comment]
There's a lot of insightful discussions in the original [discussion](https://github.com/google/kubeflow/issues/35).  We've had a great conversation with @aronchick during Kubecon, just to reiterate on our thoughts on the issue.

- I believe the goal from @aronchick is to have an organization around kubeflow; right now it's not ready yet (due to google internal policies).
- The repository is apache licensed, so it's basically quite open
- There is prior experience from kubernetes, which lives under GoogleCloudPlatform for quite a long time.

**Comment by erikerlandson** [comment]
I think @willb wrote up a great [summary](https://github.com/google/kubeflow/issues/33#issuecomment-351220770) of what it means to be an open community. I don't want to repeat that here, but a point I want to amplify is that if Google's internal policies are currently gating decisions about what happens to the project, then the project is not (yet!) truly open. To borrow Will's phrasing, it is currently "a repository of permissively-licensed code" which is not the same thing as a fully-open community.

That doesn't mean that people can't participate, or collaborate, on the project in its current form! (clearly that is already happening!) I just want to clarify terms.

**Comment by aronchick** [comment]
I apologize - I think I was not clear about the reason it’s not open with @ddysher. The reason is not internal Google policies, the reason is that many people (including Googlers and non-Googlers) have been through this before and saw really limited benefit (and significant slowing) by moving Kubernetes. Their advice was do it but be thoughtful about the timing. 

I’m not, in anyway, saying we’re not moving! I just want to take the time to evaluate the actual cost/benefits we’ll get from our choices, and use that as the reason to move. There is no reason to make a hasty decision - this decision is entirely ours to make.

**Comment by ddysher** [comment]
Thanks @aronchick for clarifying!  Though we eventually want kubeflow to be a separate org, moving the repos is not a priority right now (at least from my point of view :).  We already started looking at possible ways to improve the project, and I hope we can lay a solid foundation for it!

**Comment by aronchick** [comment]
We do as well! Thank you so much for all your contributions so far, BTW - I couldn't be happier with the community we have already built.

Let me propose we get an actual meeting on the calendar to work this through as a group. Perhaps an hour? I'll follow up on Kubeflow-discuss?

**Comment by ddysher** [comment]
Sure, sounds good to me, let's follow up on kubeflow-discuss.

**Comment by jlewi** [comment]
Here are some potential issues:

* How do we keep track of teams and permissions? Examples
    -  Github permissions for managing repositories
    -  Permissions (e.g. GCP) controlling infrastructure used for testing & releasing
* How do we incubate new components specifically designed for Kubeflow?
    - In #33 there were a lot of components (e.g. CLI, ApiServer, UI, etc...)
    - Is a single repo going to be manageable?
* What policies/protections do we need to enforce to ensure code and artifacts are secure and safe to use?

**Comment by bhack** [comment]
How this could be related with a SIG ML setup? See https://github.com/google/kubeflow/pull/24

**Comment by aronchick** [comment]
I think the entire strategy should be brought together (what SIGs we participate in, how we guide the community, etc). Please join kubeflow-discuss@ where we're starting to talk about it now!

**Comment by dmueller2001** [comment]
@aronchick Could we use the first ML SIG meeting as a place to have this 1 hour discussion? The proposed date is Jan 19 at 9:00 am PST/5:00 pm UTC

**Comment by jlewi** [comment]
Closing this issue. 
See kubeflow/community for information about the community.
