### ISSUE TITLE
jupyter-web-app: hitting `spawn` returns 400 (Bad Request)

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3505]
Commit https://github.com/kubeflow/kubeflow/commit/cee39dbcfec7303ac61d3fbb08031acdaec0886f broke the `post_notebook` function by adding the following line:

https://github.com/kubeflow/kubeflow/blob/5397cc8c9e8a6ecb9aba1442953332444b679a96/components/jupyter-web-app/kubeflow_jupyter/default/app.py#L39

This line is unnecessary because `namespace` is already available inside the function.
Am I missing something @zabbasi ?

However, `ns` should be a value in body.
How come it's not?

The reason is because the ns field in the form has the HTML attribute `disabled: true`.
Because of this, `serializeArray()` doesn't include it.
https://github.com/kubeflow/kubeflow/blob/5397cc8c9e8a6ecb9aba1442953332444b679a96/components/jupyter-web-app/kubeflow_jupyter/default/static/js/add_notebook.js#L27

To fix, we should change the HTML attribute of `ns` from `disabled` to `readonly`.

Using image tag `f6aa1dc`.

/priority p1
/cc @kimwnasptd

**Comment by jlewi** [comment]
/assign @kimwnasptd 

Thanks @yanniszark @kimwnasptd Would you mind picking this up?

**Comment by kimwnasptd** [comment]
@jlewi yes, I'll fix it ASAP

**Comment by jlewi** [comment]
@kimwnasptd Has this been fixed?

**Comment by kimwnasptd** [comment]
@jlewi yes, fixed it in the HTML/JS UI before moving to Angular. Also, the new UI doesn't have this issue so we can close this.
