### ISSUE TITLE
Initial report for spartakus metrics

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#351]
Background #55 

We have turned on spartakus to collect usage metrics for Kubeflow. (Per #55 this is currently opt-in).

The data is available in BigQuery in project `kubeflow-usage`. 

The purpose of this bug is to create an initial report based on this data to share with the community.

Per #55 this report should be available to everyone in the community so it would probably be best to do put this in the team drive in kubeflow.org.

I think a couple of good reports to generate would be

- Number of unique (based on cluster id) pings per day
- Number of (non-unique) pings per day
- Duration of Kubeflow deployment

```
bq show  --project_id=kubeflow-usage --schema usage.collector | jq .
[
  {
    "type": "STRING",
    "name": "version",
    "mode": "REQUIRED"
  },
  {
    "type": "STRING",
    "name": "timestamp",
    "mode": "REQUIRED"
  },
  {
    "type": "STRING",
    "name": "clusterID",
    "mode": "REQUIRED"
  },
  {
    "type": "STRING",
    "name": "masterVersion",
    "mode": "NULLABLE"
  },
  {
    "fields": [
      {
        "type": "STRING",
        "name": "id",
        "mode": "REQUIRED"
      },
      {
        "type": "STRING",
        "name": "operatingSystem",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "osImage",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "kernelVersion",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "architecture",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "containerRuntimeVersion",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "kubeletVersion",
        "mode": "NULLABLE"
      },
      {
        "type": "STRING",
        "name": "cloudProvider",
        "mode": "NULLABLE"
      },
      {
        "fields": [
          {
            "type": "STRING",
            "name": "resource",
            "mode": "REQUIRED"
          },
          {
            "type": "STRING",
            "name": "value",
            "mode": "REQUIRED"
          }
        ],
        "type": "RECORD",
        "name": "capacity",
        "mode": "REPEATED"
      }
    ],
    "type": "RECORD",
    "name": "nodes",
    "mode": "REPEATED"
  },
  {
    "fields": [
      {
        "type": "STRING",
        "name": "name",
        "mode": "REQUIRED"
      },
      {
        "type": "STRING",
        "name": "value",
        "mode": "REQUIRED"
      }
    ],
    "type": "RECORD",
    "name": "extensions",
    "mode": "REPEATED"
  }
]
```

**Comment by jlewi** [comment]
@chrisheecho Do you want to take this on?

**Comment by chrisheecho** [comment]
Roger

**Comment by jlewi** [comment]
@chrisheecho if you are a member of kubeflow github org you can do "/assign @<user>"

I believe this issue has been fixed?

/assign @chrisheecho

**Comment by jlewi** [comment]
Lets wait for @mhausenblas to finish Spartakus refactoring.

**Comment by mhausenblas** [comment]
@jlewi from my side this is a little bit of a longer-term process. I've agreed with Tim to put together a planning doc with proposed work areas, see an [early draft here](https://docs.google.com/document/d/1A2LUgimqGjbggw8FVD_pWbTSNajv6DxkBbUNvx3Nx8A/), and to take it from there. This might well take until after KubeCon. Should you consider this a blocker then I'd suggest @chrisheecho just goes ahead with the plan and we sync on a later release. In any case I'd really appreciate if you could comment on the planning doc so that I get the priorities with Mr Hockin right ;)

CC: @aronchick  @willb

**Comment by jlewi** [comment]
#2 Broadening the resource types seems like the one most relevant to Kubeflow. In particular, it would be very valuable if we could collect metrics about batch jobs (e.g. Argo Workflows, TFJobs) e.g. #of jobs, size of jobs etc... 

I don't think this is blocking us though. There's a lot of useful data we could probably mine from the existing data.

**Comment by mhausenblas** [comment]
Thanks @jlewi and can I please ask you to comment on the GDocs :)

**Comment by jlewi** [comment]
Just responded on the docs.

**Comment by mhausenblas** [comment]
What does closing the issue imply? That we don't need the work in Spartakus anymore or ...? I planned to work on it in the next couple of weeks so would be good to know.
