### ISSUE TITLE
Persistent Print Preview for sharing notebooks

### ISSUE THREAD

**Issue by woop** [kubeflow/kubeflow#3512]
Currently it is possible to do a print preview of a Jupyter notebook. This allows users to share read only versions of their notebooks, which is quite useful.

However, one of the problems our users are facing is that when they delete their Jupyter container, the link to their shared notebook terminates. I'm assuming this is because their personal container is rendering that link, and Kubeflow is just forwarding requests to it.

Is there a way to persistently share notebooks as of now?

**Comment by jbottum** [comment]
@woop Do you still need this? Are you able to snapshot your notebook's workspace and persistent volume?

**Comment by woop** [comment]
@jbottum Yes this is hotly asked for by our data scientists. Is this available in the latest release?

**Comment by cvenets** [comment]
Hello @woop, have you tested Arrikto's Rok along with Kubeflow?

Rok allows you to snapshot your JupyterLab environment along with data residing on mounted persistent volumes in an differential, immutable, and versioned way. You can then have different users cloning these snapshots for reproducing, branching, recovering, or sharing their work.

Rok is free for single-node Kubeflow deployments and already available in MiniKF, so you can just download, test it, and hit us on Kubeflow's #minikf Slack channel with questions.

Please take a look at this playlist showcasing some of the above functionality:
https://www.youtube.com/playlist?list=PLD-Taer66dlLb_dz3KaEKoRF2iFj2Qz4p

Would the above address the challenge in your use case?

**Comment by woop** [comment]
> Hello @woop, have you tested Arrikto's Rok along with Kubeflow?
> 
> Rok allows you to snapshot your JupyterLab environment along with data residing on mounted persistent volumes in an differential, immutable, and versioned way. You can then have different users cloning these snapshots for reproducing, branching, recovering, or sharing their work.
> 
> Rok is free for single-node Kubeflow deployments and already available in MiniKF, so you can just download, test it, and hit us on Kubeflow's #minikf Slack channel with questions.
> 
> Please take a look at this playlist showcasing some of the above functionality:
> https://www.youtube.com/playlist?list=PLD-Taer66dlLb_dz3KaEKoRF2iFj2Qz4p
> 
> Would the above address the challenge in your use case?

We are looking at running this at very large scale, and ideally we would use purely open source software for that purpose. Am I right in understanding that Rok would not be free when running a large Kubeflow cluster?

**Comment by cvenets** [comment]
@woop, yes, you are right, and I understand that ideally you would run only open source software. However, we don't see a very easy way to have a Kubeflow-native solution that will provide you with the described functionality at this point, so I think that it is worth considering.

As mentioned above, it is very easy to test the tight integration or Rok and Kubeflow on the new MiniKF, which comes with Kubeflow 0.6, to see if it something that makes sense for your use case. And we can definitely answer all your questions.
