### ISSUE TITLE
Can't pull notebook images in private registry except for gcr.io

### ISSUE THREAD

**Issue by x28646510** [kubeflow/kubeflow#3516]
Hello, I would like to create notebooks by `jupyter-web-app` from images in private registry except for gcr.io, for example, azurecr.io.
In current implementation, it seems not to have feature to specify any `imagePullSecrets` .
Can I specify it? Or, are you planning to add feature to specify it?
Do we have to extend `jupyter-web-app`  by own?

**Comment by x28646510** [comment]
I found the answer myself. The command `kubectl -n kubeflow patch serviceaccount jupyter-notebook -p '{"imagePullSecrets": [{"name": "secret-name"}]}'` fixes my issue.

**Comment by PrathamSolanki** [comment]
> I found the answer myself. The command `kubectl -n kubeflow patch serviceaccount jupyter-notebook -p '{"imagePullSecrets": [{"name": "secret-name"}]}'` fixes my issue.

Hi @x28646510 can you please explain/elaborate your solution? I'm facing a similar issue where I want to use image that are in a private gitlab registry.

**Comment by vcarnogu** [comment]
It seems that in version 0.6 the service account for `jupyter-web-app-deployment` is `jupyter-web-app-service-account` so I ties to patch that account with imagePullSecrets but still getting authorization error. I am pretty sure my Secret resource created correctly.

**Comment by dynofu** [comment]
0.6.2 same problem...

**Comment by dynofu** [comment]
got it work. for 0.6.2, it needs to patch the `default-editor` account in the kubeflow-<username> namespace.

**Comment by ayoubelmimouni** [comment]
> got it work. for 0.6.2, it needs to patch the `default-editor` account in the kubeflow-`username` namespace.

but in that case you will have to do this step for every user namespace

**Comment by zzunny97** [comment]
Anyone solved this issue? I am facing same error

**Comment by kimwnasptd** [comment]
Note for everyone that is still looking at this issue, it is now possible to set `imagePullSecrets` via the PodDefaults https://github.com/kubeflow/kubeflow/pull/6600

So the flow would look like this:
1. An admin creates the K8s Secret, in the namespace they want to create a notebook https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
2. They create a PodDefault that injects that K8s Secret as `imagePullSecrets`
3. When the user creates a Notebook they'll need to select the appropriate `Configuration` (PodDefault) from the dropdown, in the web form

NOTE: This is different from adding `imagePullSecrets` to a ServiceAccount. In Kubeflow's case we are adding the `imagePullSecret` directly to the Notebook Pod.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

I'll also link https://github.com/kubeflow/kubeflow/issues/4037, for visibility. This is something very helpful to extend the KF docs with.
