### ISSUE TITLE
Better docs for http proxy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#352]
We have minimal docs here:
https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server/http-proxy

We should expand the docs. Here are some things to possible explain

- How do model_name and model_version in the request map to values specified in the model and/or TF Serving deployment options?
- The difference between predict and classify methods?

**Comment by yupbank** [comment]
and... i'm thinking to make http-proxy a pypi package as what mxnet-serving does...

**Comment by ankushagarwal** [comment]
It will also be good to document how the input tensors and output tensors of the model map to the json payload of the http proxy. I had to read the code to figure this out.

**Comment by ankushagarwal** [comment]
Also since we're storing the signatures of the models in our server, it will be good expose these signatures to the client as a http method - so that the client can understand what inputs and outputs are expected for a model. Something along the lines of:

```
GET /model/${model_name}:signature
GET /model/${model_name}/version/${model_version}:signature

signature_def: {
  key  : "my_prediction_signature"
  value: {
    inputs: {
      key  : "images"
      value: {
        name: "x:0"
        dtype: ...
        tensor_shape: ...
      }
    }
    outputs: {
      key  : "scores"
      value: {
        name: "y:0"
        dtype: ...
        tensor_shape: ...
      }
    }
    method_name: "tensorflow/serving/predict"
  }
}
```

**Comment by yupbank** [comment]
yes... that is in the roadmap.
```
---
GET /models/

model_name:
something
signature_def:
something..

---
model_name:
something
signature_def:
something..
```

**Comment by yupbank** [comment]
not just `signature_def` but also  `model_name` and `signature` is also something we can provide, instead of the api consumer need to worry about

**Comment by yupbank** [comment]
It’s more of a feature request though ...
