### ISSUE TITLE
Fix dynamic loading of platform plugins

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3520]
#3045 disabled dynamic loading in kfctl of KfApp plugins for platforms. Plugins are still supported for the package manager.

The relevant change is here
https://github.com/kubeflow/kubeflow/tree/1c07de4d4825f381062c7d7091398b837113b7f1/bootstrap/pkg/kfapp

Specifically getPlatform no longer calls LoadKfApp to dynamically load the plugin if there is no match.

This change was made because getPlatform's return type was changed to kftypes.Platform which is no longer compatible with LoadKfApp.

This was changed because #3045 also introduced the interface kfTypes.Platform in order to add a GetK8sConfig method to allow plugins to configure how K8s credentials are obtained.

Possible fixes

1. Define a LoadKfPlatform method that would dynamically load platform plugins

    * Code would be similar to LoadKfApp but return type kftypes.Platform

1. Get rid of kftypes.Platform by adding GetK8sConfig to the KfApp interface

    * It could be a null op in the case of package managers.

Also related to #3518 which suggests adopting semantics like reconcile.

**Comment by jlewi** [comment]
This will be fixed in an upcoming PR in which I add plugins to KFDef.Spec and allow each plugin to provide an arbitrary struct as a runtime.RawExtension

**Comment by jlewi** [comment]
#3651 refactored the coordinator code.

PackageManagers and Platforms should now have the same interface; platforms no longer take extra args during construction.

It should not be relatively straightforward to add back dynamic loading of plugins.

**Comment by gabrielwen** [comment]
@jlewi I think this was fixed?
