### ISSUE TITLE
Multi-user CUJ with notebooks and central dashboard test with basic auth

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3524]
Opening this issue to track verifying that the multi-user features @avdaredevil is adding to central dashboard works in the case of basic auth.

The central dashboard and other multi-user features depend on a header containing the user id.

The header in the JWT will be different depending on the setup and there's some question on how to handle this.

**Comment by jlewi** [comment]
@johnugeorge @yanniszark @avdaredevil is anyone planning on looking into this?

@avdaredevil What are the changes we are waiting on before testing that everything is working E2E with basic auth?

**Comment by avdaredevil** [comment]
Central-Dashboard has the Header Value it looks for along with the prefix for the user configured via environment variables (which currently default to Google IAP):
- `env:\USERID_HEADER`
- `env:\USERID_PREFIX`

If left unchanged during deployment in:
- Google IAP:
  - Will use Multi-User isolation
  - Scope everything based on perms
- Basic:
  - Will fallback to non-isolated mode
  - Everyone is considered cluster admins with `editor` access to all namespaces

#### If changed for `basic`, and headers exist
  - Will use Multi-User isolation
  - Namespaces are what kfam replies with
