### ISSUE TITLE
Add GCP authentication to documentation and getting started guide

### ISSUE THREAD

**Issue by KamalAman** [kubeflow/kubeflow#3526]
Providing an authentication secret for kubeflow on non GCP deployments does not seem to be documented anywhere. 

https://github.com/kubeflow/kubeflow/issues/3188 suggests a way to add a user-gcp-sa secret.

Setting the user-gcp-sa secret should be a part of the documentation as well as the getting started guide for non-gcp deployments.

**Comment by jlewi** [comment]
@KamalAman Can you explain what you are trying to do and what documentation you are looking for?

`user-gcp-sa` secret is specific to GCP. It is intended to contain a GCP service account private key which is used to grant access to GCP Cloud Services (e.g. GCS, BigQuery, etc...).

Are you running on a different cloud? If you're running a different cloud it would be up to that Cloud provider to come up with a solution specific to that cloud. If you let us know which cloud we can route to the appropriate folks in the community.

For a generic K8s cluster (e.g. on prem), I don't know that there is a generic solution.

**Comment by KamalAman** [comment]
@jlewi I'm using Minikube to run through the XGBoost and TFX examples provided as samples in the Kubeflow Pipeline which require GCP specific parameters to run.  

The documentation path i took was: 
1. [Getting start](https://www.kubeflow.org/docs/started/getting-started/)
2. [Minikube setup](https://www.kubeflow.org/docs/started/getting-started-minikube/)

Once Kubeflow is setup and you try to run the XGBoost/TFX example, you will get an authentication error when trying to access GCP resources if you configure them to read from GCP (of course). There is no documented way to provide these two sample pipelines an authentication secret for GCP. Setting a `user-gcp-sa` secret will provide these sample pipelines access to GCP. 

user-gcp-sa should be documented as a way users can authenticate the two sample pipelines to access GCP resources.

**Comment by jlewi** [comment]
Thanks @KamalAman 

I would expect samples to run on minikube without GCP. 

/cc @paveldournov
