### ISSUE TITLE
Pod cemetery, pods are not getting deleted

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/kubeflow#3530]
Hi Kubeflow Team,

currently all pods / workloads which are getting created are still existing even tough there are already done. 

Is this the expected behavior?

In the screenshot you can see each pods contains the {{workflow.uid}}. Each pipeline execution creates a pod. 

![pods](https://user-images.githubusercontent.com/1991664/59999015-28157600-9661-11e9-8a63-b8662ff2e34d.png)

Best regards
Sascha

**Comment by jbottum** [comment]
@SaschaHeyer are you still seeing this behavior in Kubefllow 0,6?
