### ISSUE TITLE
jupyter-web-app: Error 200 on load

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#3536]
In the new UI if no namespace is selected from the centraldashboard before opening the Jupyter UI, then the value `""` is passed as namespace. Because of this the GET will hit an invalid endpoint resulting in an error 200 popup.

The webapp should ignore the empty value from the centraldashboard.

**Comment by kimwnasptd** [comment]
cc @prodonjs @avdaredevil

**Comment by prodonjs** [comment]
Currently, we send whatever namespace is selected (which could be empty) from the dashboard to a connected iframe child once the child establishes connectivity. One option would be to send only non-empty namespaces but there may be scenarios in the future where that's a valid selection (ie. no selection infers "all namespaces").

Sorry for the confusion as we try to get this interface in place.

**Comment by kimwnasptd** [comment]
@prodonjs makes sense. Will make the webapp ignore the empty namespace for now and will update the code if necessary when we settle down on the implementation.

Keep me in the loop for this one

**Comment by avdaredevil** [comment]
@kimwnasptd would you mind having the page display:
```
Please select a namespace from the toolbar above...
```

**Comment by kimwnasptd** [comment]
@avdaredevil sorry for the late reply, would we want this message to be always shown or only when a Namespace will not be selected (value `""` for now)?
