### ISSUE TITLE
Install error with no internet connectivity

### ISSUE THREAD

**Issue by srinivascreddy** [kubeflow/kubeflow#3547]
Trying to install Kubeflow with kfctl, under constraints of enterprise policies which prevent direct internet connection. I have requested all required packages for 0.5.1 version and have them locally. While installing getting this error.

`ERROR Get https://raw.githubusercontent.com/kubernetes/kubernetes/v1.8.0/api/openapi-spec/swagger.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Have been searching documentation on what settings to update to point this to local path on my server from couple days, not finding anything in right direction. Wondering if I can get some help?

Thanks in advance!

**Comment by jlewi** [comment]
I believe this is coming from ksonnet. ksonnet tries to fetch the Kubernetes API spec to do some validation and to autogenerate a ksonnet library.

I believe the ksonnet CLI offers CLI options for overriding the path to fetch from a local directory.

`ks init` has flag `--api-spec` offhand not sure if that allows specifying a path to the swagger spec. The other issue though would be if kfctl supports passing that option along.
