### ISSUE TITLE
`kfctl init` throws warnings in envs without ~/.kube/config file

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/kubeflow#3549]
When running the `kfctl init` command from a fresh account, I'm seeing these errors:
```
WARN[0182] could not open /home/google3908041_student/.kube/config Error stat /home/google3908041_student/.kube/config: no such file or directory  filename="apps/group.go:188"
WARN[0182] could not load config Error: open /home/google3908041_student/.kube/config: no such file or directory  filename="apps/group.go:208"
```
Since this file is not generated until after `kfctl generate` and `kfctl apply`, perform these file mods after the context is generated.

**Comment by texasmichelle** [comment]
This is also a problem if you destroy, then create another cluster in the same project with the same name. In that case, kfctl tries to use the outdated ~/.kube/config connection info:

```
$ kfctl generate all --zone us-central1-c
FATA[0030] couldn't get server version info. Error: Get https://34.66.187.209/version: dial tcp 34.66.187.209:443: i/o timeout  filename="apps/group.go:196"
```

**Comment by cyrilthank** [comment]
I am encountering this exact message when i execute the steps in

step 2 of Deploy Kubeflow in https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

**Comment by cyrilthank** [comment]
below the entire error stack

cyril@tensorflowextended:/kubeflow-app$ kfctl apply all -V
INFO[0000] Downloading /kubeflow-app/app.yaml to /tmp/653910945/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /kubeflow-app/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /kubeflow-app/app.yaml to /tmp/042641548/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Initializing a default restConfig for Kubernetes  filename="kustomize/kustomize.go:249"
WARN[0000] could not open /home/cyril/.kube/config Error stat /home/cyril/.kube/config: no such file or directory  filename="apps/group.go:234"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b2a0b1]

goroutine 1 [running]:
k8s.io/client-go/v2/kubernetes.NewForConfig(0x0, 0x0, 0x0, 0x0)
	/tmp/v2/k8s.io/client-go/kubernetes/clientset.go:447 +0x51
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/apis/apps.GetClientset(0x0, 0x0)
	/home/jlewi/git_kubeflow/bootstrap/v2/pkg/apis/apps/group.go:262 +0x5d
github.com/kubeflow/kubeflow/bootstrap/v2/pkg/kfapp/kustomize.(*kustomize).Apply(0xc00004f680, 0x32af7e2, 0x3, 0x0, 0x0)
	/home/jlewi/git_kubeflow/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go:264 +0x219
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply.func2(0x0, 0x0)
	/home/jlewi/git_kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:745 +0x12e
github.com/kubeflow/kubeflow/bootstrap/pkg/kfapp/coordinator.(*coordinator).Apply(0xc0007effc0, 0x32af6fe, 0x3, 0x0, 0x0)
	/home/jlewi/git_kubeflow/bootstrap/pkg/kfapp/coordinator/coordinator.go:778 +0x229
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.glob..func1(0x4a88a20, 0xc00059d940, 0x1, 0x2, 0x0, 0x0)
	/home/jlewi/git_kubeflow/bootstrap/cmd/kfctl/cmd/apply.go:46 +0x4cb
github.com/spf13/cobra.(*Command).execute(0x4a88a20, 0xc00059d920, 0x2, 0x2, 0x0, 0x0)
	/home/jlewi/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0xb21
github.com/spf13/cobra.(*Command).ExecuteC(0x4a88c80, 0x4a88a20, 0x0, 0x0)
	/home/jlewi/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x64b
github.com/spf13/cobra.(*Command).Execute(0x4a88c80, 0x0, 0x0)
	/home/jlewi/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x3b
github.com/kubeflow/kubeflow/bootstrap/cmd/kfctl/cmd.Execute(0x3697070, 0x12)
	/home/jlewi/git_kubeflow/bootstrap/cmd/kfctl/cmd/root.go:61 +0x6d
main.main()
	/home/jlewi/git_kubeflow/bootstrap/cmd/kfctl/main.go:36 +0x39

**Comment by cyrilthank** [comment]
kubectl -n kubeflow get all

returns the below

No resources found.

**Comment by cyrilthank** [comment]
http://localhost:8080/
shows API endpoints like

![image](https://user-images.githubusercontent.com/4562436/64957024-9311ca00-d8a9-11e9-8145-a79dca745aaf.png)

**Comment by cyrilthank** [comment]
can you please advise?

**Comment by cyrilthank** [comment]
can you please advise the workaround for linux server analogous to the below https://github.com/kubeflow/kubeflow/issues/3024#issuecomment-500887738

**Comment by cyrilthank** [comment]
solution in https://ubuntu.com/kubeflow/install
microk8s.kubectl config view --raw > $HOME/.kube/config
