### ISSUE TITLE
Try to install istio in kubeflow env via document, the URL is invalid

### ISSUE THREAD

**Issue by BlodwenZ** [kubeflow/kubeflow#3552]
Hello,
I was trying to installl istio via official document in kubeflow ENV. Unfortunately, I found out those 3 URLs are not found(got 404 code). Please kindly help to provide correct URLs. The URLs are following:
https://raw.githubusercontent.com/kubeflow/kubeflow/master/dependencies/istio/kf-istio-resources.yaml
https://raw.githubusercontent.com/kubeflow/kubeflow/master/dependencies/istio/install/istio-noauth.yaml
https://raw.githubusercontent.com/kubeflow/kubeflow/master/dependencies/istio/kf-istio-resources.yaml

Looking forward your reply. :)
Thanks in advance.
Blodwen

**Comment by jbottum** [comment]
@BlodwenZ did you get this issue resolved? which release and platform are you deploying on?
