### ISSUE TITLE
Central Dashboard: add userid-header and userid-prefix cli flags

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3554]
Sub-issue for #3553.
Add cli flags to configure:
* Which header we read for the user info (now it's only `X-Goog-Authenticated-User-Email`)
* What prefix is expected (now it's expected to be in the form of `accounts.google.com:<user>`, so the prefix is `accounts.google.com:`)

/priority p0

cc @jlewi

**Comment by jlewi** [comment]
Is this really P0?

Does the central dashboard gracefully handle the case where no user id is provided?

**Comment by yanniszark** [comment]
We should ask the OWNERS for the full extent of the consequences.
@prodonjs @avdaredevil @swiftdiaries 

However, to truly say that the v0.6 release is configurable for other platforms and not just GCP, we should fix this as well.

**Comment by avdaredevil** [comment]
This support is added in #3503 with commit af2039a and improved with bb5fddd.

**Comment by yanniszark** [comment]
Thanks a lot @avdaredevil!
Amazing work in PR #3503. Let's close this when it gets merged.

**Comment by jlewi** [comment]
Still waiting for #3503; Discussing the ETA on that PR thread.

**Comment by jlewi** [comment]
@avdaredevil and @yanniszark lets not block this PR based on getting #3503 submitted since that is still WIP. 

Could someone please create a PR with just the commits mentioned by @avdaredevil ?

Once that is merged we will need to build and update the central dashboard image.

**Comment by jlewi** [comment]
Actually it looks to me like the code is already gracefully handling the case where the IAP headers aren't present
https://github.com/kubeflow/kubeflow/blob/bca68dd0da5b68eaa7a82e35d3471a6b98798b03/components/centraldashboard/app/api.ts#L36

It looks to me like right now the user would just fall back to anonymous@kubeflow.org.

So it looks like currently in the non-IAP case it won't be identity aware but the central dashboard will still work so I don't think this blocking 0.6.0.

**Comment by jlewi** [comment]
/assign @avdaredevil 

@avdaredevil Do you have an updated ETA for this?

**Comment by prodonjs** [comment]
FYI: Here's a [screencast](https://screencast.googleplex.com/cast/NjI2OTU1NTA5MTQzOTYxNnwwMDZhMWE5Mi0yOQ) showing the state of PR #3503 showing the three primary scenarios:

 1. No headers to establish user-identity (user sees all namespaces)
 2. User with a profile sees only their owned namespace
 3. User accessing the application for the first time must register a profile and then sees only their owned namespace.

I'll let AP provide more details on the expected timeline.

**Comment by yanniszark** [comment]
@prodonjs thanks for the status update.
A few comments:

>  Here's a screencast 

The screencast seems to be visible only by Google employees.
Could you share it in a publicly-accessible way?
> User with a profile sees only their owned namespace

My understanding is that a user may have multiple profiles.
So the UI should expect multiple namespace values (maybe a list selector?)
