### ISSUE TITLE
Access Management UI: add userid-header and userid-prefix cli flags 

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3555]
Sub-issue for #3553.
Add cli flags to configure:
* Which header we read for the user info (now it's only `X-Goog-Authenticated-User-Email`)
* What prefix is expected (now it's expected to be in the form of `accounts.google.com:<user>`, so the prefix is `accounts.google.com:`)

/priority p0

cc @jlewi @avdaredevil

**Comment by jlewi** [comment]
@avdaredevil what is the latest ETA for the access management UI?
