### ISSUE TITLE
Jupyter Web App: add userid-header and userid-prefix cli flags 

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3556]
Sub-issue for #3553.
Add cli flags to configure:
* Which header we read for the user info (now it's only `X-Goog-Authenticated-User-Email`)
* What prefix is expected (now it's expected to be in the form of `accounts.google.com:<user>`, so the prefix is `accounts.google.com:`)

/priority p0

cc @jlewi  @kimwnasptd

**Comment by jlewi** [comment]
@kimwnasptd Any update on this?

**Comment by kimwnasptd** [comment]
I'll upload a PR to close this issue with the behavior @jlewi described [here](https://github.com/kubeflow/kubeflow/issues/2981#issuecomment-509444739).

The webapp will:
* Keep its own privileged ServiceAccount
* When it receives a request, it will check if the user header is present.
   * If it is, it will query `kfam` to check whether that user has access to the specific Namespace. If the user has access, then the the webapp will make the requests using its own SA. Else it will return a warning.
   * If it is not, the webapp will simply make the requests using its own SA. This way it will comply with #3618
