### ISSUE TITLE
kustomize packages for installed apps should be in ${KFAPP}/kustomize

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3558]
My expectation is that the kustomize packages for installed applications should be stored in
${KFAPP}/kustomize

* This way if user checks it into source control their manifests are actually checked in
* Furthermore, for complex manipulations; user can just edit the kustomize manifests
* I think ${KFAPP}/kustomize should only contain manifests for the applications user installed
  * It shouldn't just be a dump of kubeflow/manifests
* So the behavior of kfctl should be to cache kubeflow/manifests somewhere and then copy applications as they are added to ${KFAPP}/kustomize

* We should write the code in a way that its easy to write a unittest that this is happening as expected

**Comment by lluunn** [comment]
Currently in my KFAPP/kustomzie dir I can see a lot of yaml files, argo.yaml, profiles.yaml etc.

So are you saying we aren't deploying everything there?
Or that we should keep the structure as kustomize package?

**Comment by lluunn** [comment]
WIP with #3601
