### ISSUE TITLE
Cut 0.6 RC

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3559]
Here is the [list](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubeflow+label%3Apriority%2Fp0+project%3Akubeflow%2F5+is%3Aopen+) of P0 blocks that are blocking us.

Demo script:
https://bit.ly/2UOzzxB

**Comment by jlewi** [comment]
We could start cutting release branches for the other repos and building images. The following repos don't seem to have any open bugs.

* PyTorch
* TFJob
* Katib

**Comment by jlewi** [comment]
Looks like @kunmingg cut some release branches

https://github.com/kubeflow/katib/releases/tag/v0.6.0-rc.0
https://github.com/kubeflow/tf-operator/releases/tag/v1.0.0-rc.0
https://github.com/kubeflow/pytorch-operator/releases/tag/v1.0.0-rc.0

**Comment by zhenghuiwang** [comment]
Needs to resolve two issues for metadata:
https://github.com/kubeflow/metadata/issues/67

and merge https://github.com/kubeflow/manifests/pull/188

I will merge them by Tuesday noon.

**Comment by jlewi** [comment]
Can we cut a 0.6 branch and starting updating E2E tests and auto-deployment scripts to deploy from that branch?

I think we should try to get that done and not wait on more changes to kubeflow/master. If there is a lot of changes on master, we can always merge all of those changes into the release branch. But it would be good to make progress on getting the RC branch all setup.

**Comment by jlewi** [comment]
https://github.com/kubeflow/manifests/tree/v0.6-branch
Has been cut and most image tags updated.

**Comment by jlewi** [comment]
Can update kfctl to point at release branch and begin testing it.

**Comment by jlewi** [comment]
https://github.com/kubeflow/kubeflow/tree/v0.6-branch 
is also cut.

**Comment by jlewi** [comment]
Created
https://github.com/kubeflow/kubeflow/releases/tag/v0.6.start

So that the ``git describe --tags --long``` would now start providing more sensible input.

**Comment by jlewi** [comment]
Here's my understanding of the current status of the release. The initial RC and 0.6.0 is only blocked by the following two issues

- [ ] #3643 - Release demo is not working with Fairing; this needs to be fixed
- [ ] #3618 - Is blocking our core CUJs from working on a cluster without Auth enabled
   * I think the issue here is installing Kubeflow on a cluster with ISTIO already installed
   * This case isn't currently covered by existing_arrikto.yaml because that installs ISTIO & Dex.

I believe of the 15 P0s these are the only ones blocking the first RC

* We aren't blocking 0.6.0 on the access management UI (#3555)
* #3554 - I don't think this is blocking 0.6.0; without it central dashboard should still work it just won't be identity aware in non IAP(GCP) case
   * See comment in #3554 it looks like the changes to make it support headers are available in an outstanding PR
   * So if someone wants to patch and merge those we should be able to include it in 0.6.0 or a minor release

**Comment by kunmingg** [comment]
https://github.com/kubeflow/kubeflow/pull/3661

**Comment by jlewi** [comment]
Here's my understanding of the current state of the release.

* #3661 merged all changes to kfctl onto the release branch
* To fix #3618 (work without auth) we need #3663 to be merged and then cherry-picked onto release branch
 
  * I don't think this is blocking cutting RC for kfctl because this is a config file so people would specify it
    via the `--config` file and can reference the appropriate commit.

* fairing has been fixed checked in

   * I think we should just plan on telling customers to run `pip install` from the repo in their notebooks
   * I don't think we should try to rebuild and update jupyter images with the newer version of fairing
   * Ideally we should cut a v0.6-branch for fairing but I don't think that's release blocking

* So I believe we can go head and cut a new RC for kfctl

**Comment by kunmingg** [comment]
One surprise during fairing test: https://github.com/kubeflow/kubeflow/issues/3677
Should we fix in v0.6? @jlewi

**Comment by jlewi** [comment]
I don't thin #3677 should be blocking

**Comment by jlewi** [comment]
Here's my friction log: http://bit.ly/2LqZOu2
This was built from master (should be a commit corresponding to one of RCs; the latest RC hadn't been cut yet).

I ran into the following issues
https://github.com/kubeflow/fairing/issues/319
https://github.com/kubeflow/examples/issues/601
https://github.com/kubeflow/examples/issues/600
https://github.com/kubeflow/website/issues/946

I don't think they are release blocking.

They are blocking creating a blog post that runs through 0.6 using that example.

**Comment by jlewi** [comment]
0.6.0 has been published.
https://github.com/kubeflow/kubeflow/releases/tag/v0.6.0

**Comment by jlewi** [comment]
Opened #3702 to track the minor release.
