### ISSUE TITLE
[GCP] Click to Deploy UI update to support 0.6

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3560]
We need to make some updates to the click to deploy UI and frontend to support 0.6.

https://github.com/kubeflow/kubeflow/tree/master/components/gcp-click-to-deploy

Here are the changes needed

1. The endpoint for createDeployment will be changed to `/kfctl/apps/v1alpha2/create`
1. The payload will be a [KfDef](https://github.com/kubeflow/kubeflow/blob/9bb2c0176506950415cee95c602d66dd88cc3f92/bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L24)
1. The KfDef should be constructed as follows
    * Fetch a YAML file from an http link and load the KfDef from it
    * override fields in the YAML spec based on the fields in the UI
1. As with the current UI; i'd like a drop down that is easy to populate with human readable descriptions e.g "0.6 with IAP" and behind the scenes are mapped to specific URI

    * I'd also like the ability to enter a specific URI link (possibly via query arg)

1. We will need to preserve existing code paths to continue to support v0.5.
    * It would be nice if the drop down box for version listed options for 0.6 and 0.5 and based
      on version we invoked correct code path.

/cc @avdaredevil @prodonjs

**Comment by jlewi** [comment]
Also #3548 is adding Secrets to KfDef. Secrets should be used to store the following information

   * OAuth client secret
   * Basic auth password
   * Access token

**Comment by prodonjs** [comment]
I'd estimate this at around a week's worth of effort, mostly because it'll take a little time to become familiar with the architecture. I've got to make sure things are ready to go on the Metadata UI side of things, which should hopefully wrap this week. Next week is a short week with the holiday so I think a conservative estimate might be for this to land sometime early in the week of 7/8. Is that reasonable?

**Comment by prodonjs** [comment]
@jlewi Are the instructions at https://github.com/kubeflow/kubeflow/blob/master/bootstrap/developer_guide.md#how-to-run-bootstrapper-with-click-to-deploy-app-locally still accurate? I could not get `make build` to work and I also noticed that the latest image for gcr.io/kubeflow-images-public/bootstrapper was from September of last year so I was curious if that's still the best way to set up a test backend to communicate with.

**Comment by jlewi** [comment]
@prodonjs Those instructions won't apply to the new backend/API. The most up todate instructions are
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/developer_guide.md#iterative-development-using-skaffold

Although it might make sense to create a dummy implementation of the CreateDeployment endpoint for FE deployment.

**Comment by prodonjs** [comment]
Majority of the work to separate v0.5.0 from v0.6.0 deployment submission is done. Need to understand the differences in the message format between the old and new endpoints and do some E2E testing before submitting. On target to be ready for merge by EOW.

**Comment by prodonjs** [comment]
@jlewi - Currently, the base configuration that is overriden by user input and sent to the `/kfctl/e2eDeploy` endpoint can be found at [components/gcp-click-to-deploy/app-config.yaml](https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/app-config.yaml). 

In making the app support v0.6.0 and v0.5.0, do we still need to support that format and endpoint, or can we migrate to the new `/kfctl/apps/v1alpha2/create` endpoint and provide `v0.5.0` in the version property of the request body? 

Also, it would appear that [kfctl_gcp_iap.0.6.yaml](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_gcp_iap.0.6.yaml) is a good starting point to use to build the request, correct?

**Comment by jlewi** [comment]
@prodonjs 

> In making the app support v0.6.0 and v0.5.0, do we still need to support that format and endpoint, or can we migrate to the new /kfctl/apps/v1alpha2/create endpoint and provide v0.5.0 in the version property of the request body?

I think we'd like to continue to be able to support v0.5 somehow. If we can have a single app with two different codepaths so users can just use the UI to select the version that would be great.

But if that's difficult then we can just deploy two different versions of the app on two different URLs.

> Also, it would appear that kfctl_gcp_iap.0.6.yaml is a good starting point to use to build the request, correct?

Correct. The webapp should just load that YAML spec via that URL and then overload the fields set in the UI e.g.

* Project
* Name
* Zone
* OAuth client id and secret.

**Comment by prodonjs** [comment]
> @prodonjs
> 
> > In making the app support v0.6.0 and v0.5.0, do we still need to support that format and endpoint, or can we migrate to the new /kfctl/apps/v1alpha2/create endpoint and provide v0.5.0 in the version property of the request body?
> 
> I think we'd like to continue to be able to support v0.5 somehow. If we can have a single app with two different codepaths so users can just use the UI to select the version that would be great.
> 
> But if that's difficult then we can just deploy two different versions of the app on two different URLs.

If the new endpoint can support deploying v0.5.0 simply by putting that value in for the `kfVersion`, things will be pretty simple. Otherwise, we may need to do what you suggest.

> 
> > Also, it would appear that kfctl_gcp_iap.0.6.yaml is a good starting point to use to build the request, correct?
> 
> Correct. The webapp should just load that YAML spec via that URL and then overload the fields set in the UI e.g.
> 
> * Project
> * Name
> * Zone
> * OAuth client id and secret.

GitHub allows CORS requests to get raw content so this should work allowing the app to pull the latest content. If we think that's too risky, we can always bundle it in with the build.

In any case, I'm out for a week starting tomorrow so this is going to have to park until then. I know @avdaredevil is going to be working on wrapping up multi-user stuff so hopefully waiting to get this through on the week of the 22nd is OK.
