### ISSUE TITLE
Metadata API and backend should be installed as part of default configs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3561]
There are kustomize packages for metadata but they are not currently part of the default configurations.

#3515 will submit changes to kfctl to support a `--config` flag which points at a YAML file that fully specifies all the applications to install.

That includes a YAML file for GCP. When that PR is submitted it should be easy to add to it the packages for metadata.

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this? 

It looks like #3590 added metadata as a component of Kubeflow.
Is there more work to be done or can we close this issue?

**Comment by zhenghuiwang** [comment]
This is fixed by #3590 
/assign @zhenghuiwang

**Comment by zhenghuiwang** [comment]
/close

This can be closed, but seems I can't close it.
