### ISSUE TITLE
kfctl: platform existing: deploy on existing kubernetes clusters

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3563]
This issue tracks the development of platform existing, a reference architecture for deploying Kubeflow on an existing cluster with minimal dependencies.

| Goal | PR | Status |
| -- | -- | -- |
| Add platform existing | https://github.com/kubeflow/kubeflow/pull/3538 | :heavy_check_mark: |
| Self-Signed certs | https://github.com/kubeflow/kubeflow/pull/3598 | :heavy_check_mark: |
| Docs PR | https://github.com/kubeflow/website/pull/861 | :heavy_check_mark: |
| Docs PR for LDAP | | :x: |

/priority p0

**Comment by jlewi** [comment]
@yanniszark What is the remaining work to close out this issue for 0.6?

**Comment by jlewi** [comment]
@yanniszark ping?

**Comment by yanniszark** [comment]
@jlewi the PR for LDAP docs remains: https://github.com/kubeflow/website/pull/898
I will take another pass at it today. Should be merged soon.

**Comment by jlewi** [comment]
Looks like kubeflow/website#898 is merged so I'm closing this issue.
