### ISSUE TITLE
Troubleshooting notebook credential injection

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3571]
Some users are reporting problems with notebooks not having GCP credentials injected automatically.

Their notebooks end up not having GOOGLE_APPLICATION_CREDENTIALS.

Opening the issue to begin to document how to go about collecting the information to troubleshoot this.

1. Get the pod spec for the notebook

    ```
    kubectl get pods -o yaml ${PODNOTEBOOK}
    ```

   * The pod should have the labels 

     ```
     gcp-cred-secret: user-gcp-sa
     gcp-cred-secret-filename: user-gcp-sa.json
     ```

   * These labels are what the admission webhook looks for to decide whether to inject the credentials into the pod.

   * If the labels are present we know the problem is downstream in the admission hook
   * If the labels aren't present then we know its a problem with the notebook controller attaching the labels

1. Check the notebook controller

    ```
    kubectl get deploy notebooks-controller -o yaml
    ```

    * What image is it using?
      
      * The latest [0.5.1 release should be using](https://github.com/kubeflow/kubeflow/blob/034c12f4292483b2b26b14f7fd69c7f72285114c/kubeflow/jupyter/prototypes/notebook_controller.jsonnet#L6) `gcr.io/kubeflow-images-public/notebook-controller:v20190401-v0.4.0-rc.1-308-g33618cc9-e3b0c4`

     * The POD_LABELs environment variable should also be set

       ```
      env:
        - name: POD_LABELS
          value: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json

       ```

1. Verify that the secret user-gcp-sa exists

    ```
    kubectl get secrets -o yaml user-gcp-sa
    ```

1. Check that the webhook controller is deployed

    ```
    kubectl get deploy -o yaml gcp-cred-webhook
    ```

## Workaround

A workaround is to modify your notebook resource to add the environment variable and volumes.

1. Get the notebook spec

    ```
   kubectl get notebook ${NOTEBOOK} -o yaml > /tmp/notebook.yaml
   ```

1. Add volume:
  
    ```
     - name: gcp-credentials
       secret:
        defaultMode: 420
        secretName: user-gcp-sa
    ```

1. Add volume mount 

    ```
       - mountPath: /secrets/gcp-service-account-credentials
         name: gcp-credentials
        readOnly: true
    ```

1. Add env

    ```
       - name: GOOGLE_APPLICATION_CREDENTIALS
         value: /secrets/gcp-service-account-credentials/user-gcp-sa.json
    ```

1. Apply the notebook resource
  
    ```
    kubectl apply -f  /tmp/notebook.yaml
    ```

1. Force a restart of the pod

    ```
    kubectl delete pods ${NOTEBOOK}-0
    ```

    * Verify pod is restarted with the new settings.

**Comment by jlewi** [comment]
Restarting the deployment gcp-cred-webhook is reported as fixing the problem.

@lluunn Any idea why that might be the case? Wasn't there some issue with the certificate for the admission web hook?

**Comment by lluunn** [comment]
I thought that certificate issue was fixed.
I need to try reproducing it to know what was the error

**Comment by lluunn** [comment]
One thing to check is looking at the webhook pod

**Comment by jlewi** [comment]
@lluunn Do we have an issue for the certificate problem? Do we know if the fix was in 0.5 or on master?

**Comment by lluunn** [comment]
It's not in 0.5, should be this one : https://github.com/kubeflow/kubeflow/pull/3351.

Is the problem here happening to 0.5 only?

**Comment by SinaChavoshi** [comment]
Hitting the same issue in 0.6.1.

**Comment by jlewi** [comment]
@SinaChavoshi did you try running through the debug steps listed in the first comment to identify where the problem is.

**Comment by SinaChavoshi** [comment]
debug info : 
1. The notebook Yaml does not contain the gcp-cred-secret labels. 

2.a. the controller image is using the image: gcr.io/kubeflow-images-public/notebook-controller:v20190603-v0-175-geeca4530-e3b0c4
2.b. the pod label value is set as follows: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json 

3. verified that the secret exists : 
```
kubectl -n kubeflow get secrets -o yaml user-gcp-sa
apiVersion: v1
data:
  user-gcp-sa.json: ewogI...
kind: Secret
metadata:
  creationTimestamp: 2019-08-05T23:37:54Z
  name: user-gcp-sa
  namespace: kubeflow
  resourceVersion: "774"
  selfLink: /api/v1/namespaces/kubeflow/secrets/user-gcp-sa
  uid: 0be77c24-b7da-11e9-b9e9-42010a800186
type: Opaque

```

4. gcp-cred-webhook does not seem to be deployed

**Comment by jlewi** [comment]
@SinaChavoshi to inject credentials into your notebook

1. The gcp-cred-webhook must be deployed
1. In the jupyter notebook creator UI you must select advanced configuration and select gcp-cred

How did you deploy Kubeflow? Can you provide the app.yaml file from your deployment?

**Comment by kellen** [comment]
Using `v0.5.1` on GCP and having the same issue. 

Debug:
```
$ kubectl -n kubeflow get pods -o yaml ${PODNOTEBOOK} | grep gcp-cred-secret
    gcp-cred-secret: user-gcp-sa
    gcp-cred-secret-filename: user-gcp-sa.json
$ kubectl -n kubeflow get deploy notebooks-controller -o yaml | grep "\(image:\|value: gcp-cred-secret\)"
          value: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
        image: gcr.io/kubeflow-images-public/notebook-controller:v20190401-v0.4.0-rc.1-308-g33618cc9-e3b0c4
$ kubectl -n kubeflow get secrets -o yaml user-gcp-sa | grep -o "user-gcp-sa.json: ...."
user-gcp-sa.json: ewog
$ kubectl -n kubeflow get deploy -o yaml gcp-cred-webhook
Error from server (NotFound): deployments.extensions "gcp-cred-webhook" not found
```

So `gcp-cred-webhook` is not working. Following instructions from your last comment:
```
$ kubectl get crd -o yaml poddefaults.kubeflow.org
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "poddefaults.kubeflow.org" not found
$ kubectl -n kubeflow get deployment admission-webhook-deployment
Error from server (NotFound): deployments.extensions "admission-webhook-deployment" not found
$ kubectl -n kubeflow get poddefaults
error: the server doesn't have a resource type "poddefaults"
$ kubectl -n kubeflow get notebooks -o yaml $NOTEBOOK | grep -A1 labels:
  labels:
    app: notebook
``` 

No other labels are present on the notebook.

**Comment by jlewi** [comment]
@kellen How did you deploy Kubeflow 0.5? It looks like you are missing all of the resources associated with injecting credentials. Did you follow the GCP specific instructions?

**Comment by axelmagn** [comment]
I am also having this issue with a GKE Kubeflow 0.6.2 cluster (without any special configurations).  During an attempt to list objects in a bucket using the python SDK, I see the following error:

```
Forbidden: 403 GET https://www.googleapis.com/storage/v1/b/calculatedgg-proto?projection=noAcl: kubeflow-test3-vm@saltierl-policy.iam.gserviceaccount.com does not have storage.buckets.get access to calculatedgg-proto.
```

I have tried a number of ways to authenticate as the `kubeflow-test3-user` account without success, including running `gcloud auth activate-service-account` within the notebook, setting my `GOOGLE_APPLICATION_CREDENTIALS` environment variable within the notebook, and running `gcloud auth login` from the jupyter terminal.

It should be noted that the bucket I am trying to access is a public bucket, and I have granted `kubeflow-test3-vm` the Storage Admin role as an attempted workaround (again without success).

**Comment by alan-krumholz** [comment]
Resolved
Had same issue. after going through this process (services names are outdated)  we noticed you need to check the "add gcp credential" configuration checkbox when creating the notebook server
This step wasn't needed before but the checkbox is unchecked by default in the newer version

**Comment by jlewi** [comment]
@axelmagn was the Kubernetes secret mounted into your pod? See original comment for some pointers about how to check volume and volumeMounts to ensure you are mounting a secret containing a GCP service account into your pod.

If you are still having trouble I'd suggest trying v0.7.0.

* In 0.7.0 we have switched to using [workload identity on GCP](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
* If you use the kfctl deployer and Kubernetes Service Accounts (KSA) should automatically be bound to Google Service Accounts(GSA) 
* When spawning jupyter notebooks you no longer need to select pod defaults

Docs are here
https://www.kubeflow.org/docs/gke/authentication/#starting-in-0-7-gke-workload-identity
