### ISSUE TITLE
Will dashboard links be customisable?

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kubeflow#3576]
This question has come up indirectly before (https://github.com/kubeflow/kubeflow/issues/3353) but I’d like to ask it directly. Is the intention/plan to make the links on the kubeflow dashboard customisable so that users can pick and choose components for their installation? And maybe add external components they consider relevant e.g. they might be running kubeflow alongside a relevant in-house system?

**Comment by prodonjs** [comment]
I think this would be a fantastic idea and something we would ideally like to be able to implement through configuration rather than code. This would allow users to customize the components linked to and embedded by the dashboard based on what they've deployed in their environment. We haven't given much thought to the mechanics yet, but would definitely be interested in hearing ideas if you have any and working towards getting something like this in place for a future release

**Comment by yanniszark** [comment]
/remove-lifecycle stale

This is important to the composability of Kubeflow.

**Comment by prodonjs** [comment]
I'm not particularly well-versed in the best practices for Kubernetes application structuring, but it seems like this would be something to store in a ConfigMap.

The name of the ConfigMap could be `centraldashboard-custom-links` and its contents would be comma-separated pairs of links with their display text. Assuming there are only a handful of links, these could be injected to the centraldashboard deployment via a new environment variable.

This would require a few server and client-side changes to the dashboard code, but does that seem reasonable?

**Comment by yanniszark** [comment]
/lifecycle frozen

@prodonjs what you describe seems like a reasonable start.
I agree with the idea to use a ConfigMap to store configuration exposed by the CentralDashboard.

**Comment by SachinVarghese** [comment]
Hi @prodonjs, the configMap idea suggested for this sounds great. Has there been any progress on this?

**Comment by prodonjs** [comment]
@SachinVarghese - I'm not longer actively involved in frontend work for Kubeflow, but we'd welcome a PR to support this kind of behavior if you are interested.

**Comment by cliveseldon** [comment]
@jlewi @jbottum I think the attached PR #5147 would be really useful for our commerical integrations with kubeflow at Seldon.

**Comment by ryandawsonuk** [comment]
I see the [linked PR](https://github.com/kubeflow/kubeflow/pull/5147) got merged and the configmap is in [the 1.2 manifests](https://github.com/kubeflow/manifests/blob/v1.2-branch/common/centraldashboard/base/links-configmap.yaml). But when I install the 1.2 RC0 with the [istio_dex setup](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) I don't get the configmap created. The links-configmap.yaml file is there in my .cache directory. I notice it's [not referenced in base_v3](https://github.com/kubeflow/manifests/blob/v1.2-branch/common/centraldashboard/base_v3/kustomization.yaml). Could that be the reason?

**Comment by ryandawsonuk** [comment]
@Jeffwan noticed you've been [making changes to the links](https://github.com/kubeflow/kubeflow/pull/5412). Perhaps this should be addressed under https://github.com/kubeflow/kubeflow/issues/5371 as the configurable links for dashboard is listed as an item in the 1.2 release notes

**Comment by Jeffwan** [comment]
@ryandawsonuk Could be a problem. Let me double check on my end. Thanks for reporting the problem

**Comment by berndverst** [comment]
@Jeffwan @ryandawsonuk shouldn't the ConfigMap be in `manifests/common/centraldashboard/base_v3` instead? Right now it's in `kubeflow/components/centraldashboard/config/centraldashboard-links-config.yaml`

I think that's the issue. Personally, I'd also want to overwrite this ConfigMap in the Azure Stack.

**Comment by Jeffwan** [comment]
@ryandawsonuk @berndverst Please check PR https://github.com/kubeflow/manifests/pull/1654

I notice the time we did v3 manifest migration, we didn't bring this change. I add it back now and vendor can easily customize their own links

**Comment by berndverst** [comment]
Example for how to customize (if I did this correctly):
https://github.com/kubeflow/manifests/pull/1655

**Comment by Jeffwan** [comment]
This feature will be shipped in v1.2.0 this week. I will close the issue and feel free to reopen if there's extra concerns
