### ISSUE TITLE
Web-app to manage tensorboard instances 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3578]
We should consider creating a standalone web app similar to our jupyter web app that makes it easy for folks to create/delete tensorboard instances.

I suspect copying and modifying the jupyter web app to create a web app for managing tensorboard would be pretty straightforward.

Some pointers to get started

* Here is a link to the current [jupyter web app code](https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app)
* The notebook in kubeflow/examples#/723 has an example of deploying TensorBoard by creating
   1. An ISTIO virtual service
   1. A K8s service
   1. A Deployment
* The code for the tensorboard controller is [here](https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller)

This project could be broken down into several pieces

1. Create a Web App for spinning up TensorBoard instances
1. Create a Docker image for building it
1. Create a kustomize manifest for deploying it
1. Update Kubeflow's [CD Pipelines](https://github.com/kubeflow/testing/tree/master/apps-cd)  to continually update the kustomize manifest with the latest image

Pipelines (@neuromage ) create a Viewer CRD which can be used for tensboard.
https://github.com/kubeflow/pipelines/tree/master/backend/src/crd/controller/viewer

Currently I believe that is integrated into pipelines and used to auto-visualize tensorboard data reported by pipelines.

@kimwnasptd Thoughts? Any interest in possibly tackling this as part of 0.7?

/cc @karthikv2k 
/cc @neuromage 
/cc @vkoukis

**Comment by kimwnasptd** [comment]
@jlewi yes I would like to contribute to this for 0.7. We could have a first implementation that would provide a very similar UX with the jupyter webapp and then iterate on that.

**Comment by jlewi** [comment]
@kimwnasptd any update on this?

I think there was a mention of the fact that you had a prototype for a UI? Do you have an ETA for when you will have something ready to demo and then a potential PR?

A TensorBoard controller was recently added
https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller

**Comment by gaocegege** [comment]
tensorboard CRD seems to be very simple now. I am wondering if we should use deployment directly. Is there any benefit of introducing a new CRD here?

**Comment by jlewi** [comment]
@kimwnasptd are you interested in potentially being a mentor for any GSOC students interested in working on this?

**Comment by KaviyaPeriyasamy** [comment]
@kimwnasptd. I am interested to do my gsoc contribution for this project.Can you guide me for the next steps and environmental setup?

**Comment by sarahmaddox** [comment]
> The label(s) `area/gsoc` cannot be applied, because the repository doesn't have them

@jlewi Please could you check the label sync job? I added the `area/gsoc` label in PR https://github.com/kubeflow/testing/pull/623.

**Comment by jlewi** [comment]
@sarahmaddox the label is there.

**Comment by sarahmaddox** [comment]
Thanks @jlewi!

**Comment by jlewi** [comment]
@kimwnasptd How is this going? What is the GitHub ID of the student working on this?

**Comment by kimwnasptd** [comment]
@jlewi his handle is @kandrio98.

He is wrapping up the first part of the [project](https://summerofcode.withgoogle.com/projects/#4660815581413376) which is to extend the Tensorboard Controller to also work with PVCs. We've also bumped into some other small problems with the controller but most of the necessary work is done.

I'll also provide an update here once we move on the next phase, which will be the backend of the web app.

**Comment by jlewi** [comment]
Great thanks; look forward to seeing the PVC changes.

**Comment by jlewi** [comment]
@kimwnasptd @elikatsis
Looking at the TBSpec

https://github.com/kubeflow/kubeflow/blob/101c77a37c64791ce2b3e5a65c96622906202645/components/tensorboard-controller/api/v1alpha1/tensorboard_types.go#L27

The only field is logspath. This seems insufficient. 

* How would the user specify resource requirements?
* How would the user attach secrets?
* How would the user specify the version of TB to run?

It looks like a lot of this stuff is being hard coded
https://github.com/kubeflow/kubeflow/pull/5069/files

Compare this to the notebook resource: https://github.com/kubeflow/kubeflow/blob/101c77a37c64791ce2b3e5a65c96622906202645/components/notebook-controller/api/v1/notebook_types.go#L27
which contains a PodTemplateSpec.

Did you consider just generalizing the notebook controller and web app to be a generic controller for stateful web applications and Web UI?

The primary difference between launching Jupyter images is

* The entrypoint
* The docker image

The jupyter controller and web UI already handles attaching PVCs. 

This would also allow us to handle other stateful applications e.g.

* IDEs like Theia or vscode
* RStudio

@kimwnasptd @elikatsis WDYT? Can we discuss at an upcoming community meeting?

cc @kandrio98 @thesuperzapper

**Comment by kimwnasptd** [comment]
@jlewi wrt the controller we were thinking of
1. extending the `logspath` field to support PVCs as described in #5039 
2. make it a little bit easier to work with RWO PVCs by adding some extra scheduling information

Note that working with Object Stores is already supported, although we should definitely discuss how to support secrets. We just wanted to extend the current functionality to also support PVCs, in the scope of this GSoC. 

You raise some pretty interesting points with generalizing our Notebooks Controller/web apps. I'll take a closer look and write down what changes/effort this would require. Lets discuss in the following community meeting, or if not I'll just post them here, to figure out next steps we could take.

Although I don't know how flexible we would be for the next month and a half since GSoC has a pretty strict timeline.

**Comment by jlewi** [comment]
Thanks @kimwnasptd 

Here's my conjecture; it looks like the path you are on will lead you to eventually putting a PodTemplateSpec in the TensorBoardController (or the equivalent)

Per #5039 you want to add nodeAffinity and presumably volumes as well.

To support object storage you need to support setting secrets and service accounts

* Since the secrets are hard coded today object store isn't really supported in practice; e.g. the controller is hardcoding GCP secrets which are no longer created when using workload identity

To accomodate different versions of tensorboard we will likely need to allow the docker image to specified as well.

At which point if we aren't using a podTemplateSpec the question arises what podTemplateSpec fields aren't being  exposed?

So it seems like what we really need is an easily extensible story for managing stateful web applications; e.g. jupyter and tensorboard.

**Comment by kimwnasptd** [comment]
@jlewi
> To support object storage you need to support setting secrets and service accounts.

> To accomodate different versions of tensorboard we will likely need to allow the docker image to specified as well.

> So it seems like what we really need is an easily extensible story for managing stateful web applications; e.g. jupyter and tensorboard.
> 

I really agree with your thought process and points and I also think that having an extensible story for deploying our stateful apps, like Jupyter, Tensorboard, Theia etc is a step towards the right direction.

My only concern as of right now is that I don't want the GSoC project to get off schedule or blocked from this transition to a more abstract/reusable way of deploying our apps.

The ideal scenario for me would be to:
1. Continue the GSoC project with the existing Tensorboard Controller, which provides very basic functionalities for Object Stores and PVCs. It would be the alpha version just to introduce users to using Tensroboard with Kubeflow
2. Start a discussion **in parallel** and figure out a cohesive story for deploying our stateful apps.
    * I think a good first step here would be to create a design doc based on our Notebooks Controller. It should address what features it already provides and how it deploys/exposes Notebooks. Then we could start iterating from there on which parts could be generalized or extended [ for example the `VirtualService`'s endpoint, or the ports that get exposed with the k8s Service ]
3. Once we've settled down and agreed on our story for stateful apps and have an implementation [ could be a new Custom Resource? ] then lets make the Tensorboard web app align with it.

@jlewi do you find the above plan reasonable?
Would you like us to proceed differently?

**Comment by jlewi** [comment]
LGTM

**Comment by kimwnasptd** [comment]
@jlewi @sarahmaddox, @kandrio98 @elikatsis and I are really excited to inform you that we have a first iteration of a web app for managing Tensorboard instances!

@kandrio98 did a lot of contributions both for in the Tensorboards Controller, #5069 #5218 #5262 #5266, as well as the actual web app, #5259 #5180 #5267. He has an e2e view of how to deploy a Tensorboard instance all the way from the user's perspective using the UI up to the k8s controller that is handling the CRs.

You can take a quick look of the app from the frontend's PR #5267.

With this we can start discussing together what the next steps can be. Some things that come to mind:
* Extend the Central Dashboard to allow users to navigate to the new web app
* Create scripts for continuously building images for the web app
* Create the manifests for deploying the web app and the Tensorboard Controller
* Deprecate the Tensorboard CR and move towards a more generalized Kubeflow CR as we've [discussed](https://github.com/kubeflow/kubeflow/issues/3578#issuecomment-655724933) in this issue. I'll be submitting the PRs for creating a Notebooks WG soon and this will be one of the top priorities we will be discussing.

All in all, I believe @kandrio98 learned _**a lot**_ through this project and it was a pleasure mentoring him for both @elikatsis and I.

**Comment by sarahmaddox** [comment]
Well done @kandrio98, @kimwnasptd, and @elikatsis!

**Comment by DavidSpek** [comment]
@kimwnasptd 
> I really agree with your thought process and points and I also think that having an extensible story for deploying our stateful apps, like Jupyter, Tensorboard, Theia etc is a step towards the right direction.

This would also address an old issue which has since been closed regarding "how to spin up a web application on a Kubeflow cluster": https://github.com/kubeflow/website/issues/2044

**Comment by wyljpn** [comment]
@kimwnasptd Thank you for your contribution to TWA.
I was wondering whether we can load logs from MinIO for Tensorboard because my logs were saved in MinIO.

I found an example to load logs saved in gs.

https://github.com/kubeflow/kubeflow/blob/v1.3-branch/components/tensorboard-controller/config/samples/tensorboard_v1alpha1_tensorboard.yaml

```
apiVersion: [tensorboard.kubeflow.org/v1alpha1](http://tensorboard.kubeflow.org/v1alpha1)
kind: Tensorboard
metadata:
  name: tensorboard-sample1
  namespace: kubeflow-quanlin
spec:
  # Add fields here
  logspath: "gs://quanlinkubeflow1_tf_mnist_logs1/mnist_tutorial/"
```

I tried to replace the logspath with my MinIO path, but it did not work.
![image](https://user-images.githubusercontent.com/37242439/152729654-4bd32819-412d-4da9-883f-a334340869af.png)
Could you kindly tell me how to configure it right?

**Comment by ConverJens** [comment]
@wyljpn That's because tensorboard uses tf io to connect to filesytems other than local and GCS and it requires some env vars to be set on the tensorboard container. You need to set the following:
```
S3_ENDPOINT: "your-s3-endpoint:minio-port" #Notice there should be no http/https prefix here!
AWS_ACCESS_KEY_ID: "your-s3-access-key"
AWS_SECRET_ACCESS_KEY: "your-s3-secret-key"
S3_USE_HTTPS: "1"
S3_VERIFY_SSL: "1"
```

**Comment by wyljpn** [comment]
I added EnvFrom in Containers to make it supports S3 Compatible Object successfully. 
https://github.com/kubeflow/kubeflow/blob/v1.3-branch/components/tensorboard-controller/controllers/tensorboard_controller.go

```
Containers: []corev1.Container{
{
	Name:            "tensorboard",
	Image:           "tensorflow/tensorflow:2.1.0",
        ...
	EnvFrom: []corev1.EnvFromSource{
		corev1.EnvFromSource{
			SecretRef: &corev1.SecretEnvSource{
				LocalObjectReference: corev1.LocalObjectReference{
					Name: "minio-tb-secret",
				},
			},
		},
	},
},
```
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-tb-secret
  namespace: rflow
  annotations:
      serving.kubeflow.org/s3-endpoint: minio-service-second.rflow-test.svc.cluster.local:9000
      serving.kubeflow.org/s3-usehttps: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  S3_ENDPOINT: minio-service.kubeflow.svc.cluster.local:9000
  S3_USE_HTTPS: "0"
  S3_VERIFY_SSL: "false"
```
![image](https://user-images.githubusercontent.com/37242439/152962376-d1df1c4c-614f-4b98-9c2f-cb79db908660.png)
![image](https://user-images.githubusercontent.com/37242439/152962406-ba4e77c2-7879-4103-b162-ca622a3ca93b.png)

**Comment by laserK3000** [comment]
Can this change be merged?

**Comment by kimwnasptd** [comment]
cross posting here, let's track this feature in https://github.com/kubeflow/kubeflow/issues/6493
