### ISSUE TITLE
kubeflow pipelines update uses (deprecated) ksonnet 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#3591]
Cluster update instructions @ https://www.kubeflow.org/docs/pipelines/upgrade/ uses ksonnet which is deprecated. 
 
from: https://ksonnet.io/get-started/ 
> The team behind ksonnet is stepping back from the project. As a result, work on ksonnet will end and the GitHub repositories will be archived. You can read more about our decision here.

**Comment by jlewi** [comment]
https://github.com/kubeflow/kubeflow/blob/master/scripts/upgrade_kfp.sh

This script is specific to pipelines.
Kubeflow as a whole doesn't have an upgrade story yet. Hopefully as part of 0.7

**Comment by jessiezcc** [comment]
what's the replacement of ksonnet?
/cc @IronPan

**Comment by jbottum** [comment]
@jessiezcc @IronPan is there an update on this ?  will this be in the v0.7 release?

**Comment by jessiezcc** [comment]
This should be already resolved. Feel free to close it.
