### ISSUE TITLE
Add Stackdriver Monitoring reader role to GKE Deployments

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3597]
This is necessary to support the CPU utilization charts added to the central dashboard for 0.6.0.

/area frontend
/area centraldashboard

**Comment by jlewi** [comment]
@prodonjs Which service account is this using?

**Comment by jlewi** [comment]
@prodonjs service account roles are defined here:
https://github.com/kubeflow/kubeflow/blob/master/deployment/gke/deployment_manager_configs/iam_bindings_template.yaml

Can you submit a fix for this please?

**Comment by prodonjs** [comment]
@jlewi I think the referenced PR #3533 is for that file. I believe it's approved but presubmits are hanging.
