### ISSUE TITLE
Outdated usage report message in kfctl with kustomize

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#3605]
Saw following error message when running 
```
kfctl generate all -V --zone ${ZONE}
```
Building kfctl from head(https://github.com/kubeflow/kubeflow/tree/31a9bb666a13e3aea60f9a246574db27f2ee9d05) which uses kustomize. 

****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  ks delete default -c spartakus
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

Then run the following command to remove it from your ksonnet app:
  ks component rm spartakus

For more info: https://www.kubeflow.org/docs/guides/usage-reporting/
****************************************************************

**Comment by jlewi** [comment]
@xauthulei  committed kubeflow/kfctl#9  

However, kubeflow/kubeflow is still source of truth for kfctl; so we need to get that PR cherry-picked onto kubeflow/kubeflow so the changes don't get overwritten on the next sync of kubeflow/kubeflow to kubeflow/kfctl

/assign @xauthulei

**Comment by xauthulei** [comment]
@jlewi , I commit my fixes in PR #3941

**Comment by jlewi** [comment]
@xauthulei Thank you so much. 
Just one more thing. After #3941 is merged can you follow these [instructions](https://github.com/kubeflow/kubeflow/blob/master/hack/cherry-picks.md) to cherry-pick it onto the v0.6-branch.

Its just a simple script you have to run to auto-create a PR with the same changes.

**Comment by xauthulei** [comment]
@jlewi , I will try to do it later.  Thanks.

**Comment by xauthulei** [comment]
> @xauthulei Thank you so much.
> Just one more thing. After #3941 is merged can you follow these [instructions](https://github.com/kubeflow/kubeflow/blob/master/hack/cherry-picks.md) to cherry-pick it onto the v0.6-branch.
> 
> Its just a simple script you have to run to auto-create a PR with the same changes.

It is done , see PR #3942, Could you review that. Many Thanks.

**Comment by jlewi** [comment]
#3941 has been merged so I'm closing this out.
