### ISSUE TITLE
Cannot use sudo even if you pass GRANT_SUDO=yes

### ISSUE THREAD

**Issue by awakia** [kubeflow/kubeflow#3606]
Previously if you pass "GRANT_SUDO=yes" as environment, you can use sudo in jupyter terminal. (ref: https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/start.sh#L42)

But from the change #2517,
I see `--allow_root` option but it might not work. ref: https://stackoverflow.com/questions/41622988/root-access-for-jupyter-ipython-notebook

Do you have any suggestion?
I want to install something as root user.

**Comment by jlewi** [comment]
I don't believe we use the start.sh script anymore.

Allowing SUDO privileges in a docker image is generally not advised from a security perspective, so in general I'd say that's not something we explicitly want to support. 

Is there a reason you want to install something as root rather into user Jovyan's userspace?

If you want to install something as root one option is to build your own customer docker image. During the build process you can run as root and install things globally (e.g. into /usr) into the image's filesystem

**Comment by jbottum** [comment]
@awakia did you find a work-around for this?

**Comment by odovad** [comment]
The issue is staled but why is it generally not advised since it's possible using AWS Sagemaker and in Google colab we are root by default ?
