### ISSUE TITLE
Pod mysql is CrashLoopBackOff

### ISSUE THREAD

**Issue by Eric-Zhang1990** [kubeflow/kubeflow#3611]
@kimwnasptd   Hi, I have some problems when I deploy kubeflow on 4 servers,
One problem is pod "mysql"、"ml-pipeline"、"ml-pipeline-persistenceagent" are in status "CrashLoopBackOff".
![深度截图_选择区域_20190706171415](https://user-images.githubusercontent.com/24602893/60754296-d16d4c00-a011-11e9-9f48-0d3518b058c7.png)
Second is I can get into Kubeflow UI on Chrome, but when I click "Notebooks"  in the left-hand panel of the Kubeflow UI, it shows "Sorry, /jupyter/ is not a valid page"， same as #3414.
![深度截图_选择区域_20190706170801](https://user-images.githubusercontent.com/24602893/60754351-6708db80-a012-11e9-85b9-d0f4dd7e2fee.png)
Can you help me? Thank you very much in advance.

**Comment by deathemperor** [comment]
@Eric-Zhang1990 what was your solution to overcome this?
