### ISSUE TITLE
Define sample user roles and role bindings for Kubeflow components for Authorization

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#3614]
Kubeflow can define default roles and role bindings for different types of intended users for the platform. For example, these users can belong to one of the types: kubeflow admin, data scientist, deployer or model validator. A reference RBAC rule template can be created to be applied on Istio and Kubernetes RBAC policies during deployment of Kubeflow.
This issue is the place-holder for finalizing default users, roles and role bindings to be created for Kubeflow RBAC usage.

Reference PR for the initial implementation where these default roles cab be populated: https://github.com/kubeflow/manifests/pull/195

/assign @animeshsingh @krishnadurai

**Comment by animeshsingh** [comment]
The initial doc capturing the user roles and groups required. 
https://docs.google.com/document/d/1C3J30zHDh_qxqbb-HAfmk6gs-s4QcF26nAQMo9AKb_4/edit?usp=sharing

Would be great to get feedback from user community and get more roles defined, and get the matrix filled out

@krishnadurai @hougangliu @jinchihe

**Comment by krishnadurai** [comment]
@animeshsingh could you please keep the document open for comments?

**Comment by animeshsingh** [comment]
Should be open - letme know. Also feel free to modify and update directly, and drive it. In OSCON this week - so won't be doing more there

**Comment by krishnadurai** [comment]
Sure, I'll try to add my inputs in there before our meeting this Thursday.

**Comment by jlewi** [comment]
@krishnadurai and @animeshsingh Any update on this?

How does this relate to #3938  to define cluster roles for Kubeflow and use cluster role aggregation?

**Comment by krishnadurai** [comment]
#3938 will provide a framework for defining user roles for each application. The idea here is to populate the role definitions here into #3938's implementation.
We should get started with this along with #3938.

**Comment by jlewi** [comment]
With 0.7.0 we are defining

* kubeflow-edit
* kubeflow-admin
* kubeflow-view

Cluster roles. 

@krishnadurai is there more to do here or can we close this?

**Comment by krishnadurai** [comment]
@jlewi we could close this issue.

The next step here would be to enable composable roles with Manage Contributors UI.

/close
