### ISSUE TITLE
Test core 0.6 CUJs on a cluster without identity auth

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3618]
Kubeflow 0.6 should work even if requests don't contain the user's identity. In this case, the experience should be equivalent to the 0.5 experience.

The purpose of this issue is to try out core 0.6 CUJs using a Kubeflow deployment that is not identity aware.

The CUJ should be something like the following

1. Deploy Kubeflow with ISTIO but no auth on a K8s cluster

    * ISTIO can be exposed via a nodeport but not a loadbalancer since that would be insecure

1. Connect to ISTIO via kubectl port-forward

1. Launch a notebook
1. Build/Train/Deploy from notebook

@lluunn has been running some tests with kops and this could be used to simulate a non GCP, non-identity aware cluster.

Related to:  #3553

/assign @lluunn

**Comment by lluunn** [comment]
Without platform part:
```
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate k8s -V
```

This will give error:
`ERRO[0000] Couldn't find component istio-crds            filename="kustomize/kustomize.go:454"`

**Comment by lluunn** [comment]
This might be that istio is currently in gcp package, but we don't include gcp here, but still want istio.

Related to https://github.com/kubeflow/manifests/issues/115 (move istio to its own pkg)
, and possibly https://github.com/kubeflow/kubeflow/issues/3491 (get rid of pkg/component)

**Comment by jlewi** [comment]
@lluunn if a user runs the following

```
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate k8s -V
```

I would not expect that to install ISTIO. My interpretation of the above is install only KF applications on my existing cluster. 

If we don't install ISTIO in this case would that fix the problem?

**Comment by lluunn** [comment]
I removed the istio components from app.yaml, the generate succeeds.
But apply failed with:
```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from /Users/lunkai/kfdev/kops-test/kf0708/kustomize/minio.yaml Error: persistentvolumes "minio-pv" is forbidden: error querying GCE PD volume dls-kf-storage-artifact-store: disk is not found
```

**Comment by lluunn** [comment]
Actually, I will filed another issue to track the deployment of k8s without platform.
Here I will try to bypass the error to get the cluster up and running

**Comment by lluunn** [comment]
After the cluster is up, I was able to connect to UI (central and notebook) with port-forward:
`kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80`

But the notebook statefulset has error:
```
create Pod test1-0 in StatefulSet test1 failed error: pods "test1-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
```

It should be because kubeflow namespace doesn't have profile related service account provisioned.
Same as #3502
But I also don't see profile controller. 

cc @jlewi @kunmingg

**Comment by lluunn** [comment]
Actually, the policy to do JWT validation is also in gcp package:
https://github.com/kubeflow/manifests/blob/master/gcp/iap-ingress/base/policy.yaml

**Comment by lluunn** [comment]
Profile is currently in gcp overlay: https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/overlays/gcp/kfctl_default.yaml#L16

**Comment by jlewi** [comment]
@lluunn I think #3627 will fix the ISTIO install issues correct?

For the service account errors

```
create Pod test1-0 in StatefulSet test1 failed error: pods "test1-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
```

I think this is WAI; i.e. user should have to create a profile and that will create a namespace with the appropriate service accounts for running Jupyter.

#3639 will make this a bit easier by create a profile by default for the user if KfDef.email is specified.

**Comment by lluunn** [comment]
After manually created a default-editor service account, I was able to create a notebook, and connect to it. So it works fine without auth header.

@jlewi "Build/Train/Deploy from notebook" isn't related to auth header right?

**Comment by jlewi** [comment]
@lluunn Build/Train/Deploy from notebook shouldn't be connected to auth header; i.e. I think if we can connect to the notebook we should be in good shape.

I think in the non-GCP case there's a question of what's used in a reference implementation for the docker registry. That's needed for fairing.

That shouldn't be blocking 0.6.

**Comment by jlewi** [comment]
Opened #3672 about the reference implementation for a registry; but that's for 0.7.

@lluunn Is there anything else we need to test before closing this issue?

**Comment by lluunn** [comment]
> @lluunn Build/Train/Deploy from notebook shouldn't be connected to auth header; i.e. I think if we can connect to the notebook we should be in good shape.

Yeah that's what I think. So we can close this now

/close

**Comment by lluunn** [comment]
Actually, I retested again, and was not able to connect to the notebook.
Which makes more sense because of Istio rbac.
I think I might miss something previously.

However, this can be easily fixed by either:
1. delete or disable the ClusterRbacConfig
2. deploy basic auth 

So not blocking 0.6 I think?
cc @jlewi @kunmingg

**Comment by kunmingg** [comment]
https://github.com/kubeflow/kubeflow/pull/3675
Under basic auth case, there will be no Istio access control.

**Comment by jlewi** [comment]
@kunmingg @lluunn The desired behavior is that if  we don't enforce access controls if we are using basic auth and or we have no auth configured.

**Comment by jlewi** [comment]
@kunmingg @lluunn #3675 has been merged. Is there more work to be done to close this out?
