### ISSUE TITLE
Sub-pages not available in central dashboard using port-forward

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#3620]
Env: v0.6 + IAP 
By port-forward central dashboard
```
kubectl port-forward -n kubeflow svc/centraldashboard 8888:80
```
And opening central dashboard, the sub pages are not available. 

![image](https://user-images.githubusercontent.com/2348602/60848042-e1b03300-a199-11e9-803d-481bfd7dbbbb.png)

**Comment by jlewi** [comment]
@IronPan This is working as intended. You need to port-forward to the ISTIO gateway service and then from that page all links would be accessible.

You'd also have to configure ISTIO to not do AuthZ (e.g. validate JWTs). 

I believe I saw a PR go by from @yanniszark that had instructions on doing port-forwarding to ISTIO.gateway.

@yanniszark do you recall what issue or PR?

**Comment by yanniszark** [comment]
@jlewi unfortunately I don't recall having any instructions for port-forwarding + ISTIO.

**Comment by jlewi** [comment]
There are some instructions [here](https://github.com/kubeflow/kubeflow/issues/3618#issuecomment-509766664) as part of testing our core 0.6 CUJ without auth.

**Comment by jbottum** [comment]
@IronPan is this issue resolved or should it be evolved ?
