### ISSUE TITLE
Restrict notebook controller (and other controllers) to a subset of namespaces

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3623]
We'd like to be able to restrict the notebook controller to a subset of namespaces.

Consider the following scenario; a user has a shared cluster in which some namespaces are used with Kubeflow and some are not.

The notebook controller should only have permission to create and deploy resources in the Kubeflow namespaces.

Ideally the list of namespaces should be dynamic; i.e. a label or annotation should be used to indicate whether a namespace is a KF namespace and the notebook controller should be able to access it.

RBAC should be used to enforce access to a subset of namespaces. This might require dynamically creating new RBAC roles; i.e. when a new namespace is created we might need to create a role binding granting the service account of the notebook controller access to the new namespace.

An open question is how restricting a controller to a subset of namespaces interacts with [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/controller)

   * Does the implementation of controller require at least viewer permissions on all namespaces so that the controller can detect events for resources?
      
See kubeflow/tf-operator#759

The goal should be to define a pattern that all of our operators can follow.

/assign @richardsliu 
/assign @johnugeorge 

@richardsliu @johnugeorge Since you are leading our operator efforts do you want to take a look at this?

**Comment by johnugeorge** [comment]
@jlewi 
Currently, operators can be cluster scoped (which then listens to all namespaces) or namespace scoped(restricted to a single namespace).   We can extend to a list of namespaces instead of one.  Namespace to be watched is currently set as a flag which is loaded during startup. 

Do you propose to have labels similar to istio's `istio-injection: enabled`  labels on a namespace?    Shouldn't this be done outside the operator logic?

**Comment by jlewi** [comment]
@johnugeorge We are hearing the following request from customers. They have a shared K8s cluster. Kubeflow should be restricted to a subset of namespaces enforced via RBAC. So we'd like a good story for how to restrict Kubeflow to a subset of namespaces. I think requirements are

* Kubeflow should only have write permissions on a subset of namespaces in which Kubeflow is being used
* It should be easy to add new namespaces in which Kubeflow is being used.

@IronPan What is pipelines currently doing?

**Comment by richardsliu** [comment]
Pipelines implementation:
1. Scope informers to specific namespaces ([PR](https://github.com/kubeflow/pipelines/pull/851/files))
2. Introduce viewer CRD ([PR](https://github.com/kubeflow/pipelines/pull/1562/files))
3. Remove cluster role and binding ([PR](https://github.com/kubeflow/pipelines/pull/1623/files))

The problem with this solution is that each informer only watches one namespace. So to workaround this, we can consider:
- Creating multiple informers for a list of namespaces; or
- Requiring the user to create multiple controllers.

The latter seems like a straightforward solution but may be cumbersome for users. Maybe we can use kustomize overlays to make this process easier? That way the same pattern can be more easily adopted by different operators.

**Comment by johnugeorge** [comment]
> Pipelines implementation:
> 
> 1. Scope informers to specific namespaces ([PR](https://github.com/kubeflow/pipelines/pull/851/files))
> 2. Introduce viewer CRD ([PR](https://github.com/kubeflow/pipelines/pull/1562/files))
> 3. Remove cluster role and binding ([PR](https://github.com/kubeflow/pipelines/pull/1623/files))
> 

Current operators handle the same way. 

> The problem with this solution is that each informer only watches one namespace. So to workaround this, we can consider:
> 
> * Creating multiple informers for a list of namespaces; or
> * Requiring the user to create multiple controllers.
> 
> The latter seems like a straightforward solution but may be cumbersome for users. Maybe we can use kustomize overlays to make this process easier? That way the same pattern can be more easily adopted by different operators.

@jlewi Is this ok with customers? One other concern is the waste of resources when multiple controllers are created

**Comment by johnugeorge** [comment]
See MultiNamespaceListerWatcher  implementation in Prometheus operator :  
https://github.com/coreos/prometheus-operator/blob/master/pkg/listwatch/listwatch.go#L90

**Comment by kunmingg** [comment]
Shall we limit operators to access only kubeflow user namespaces?
Since v0.6 to check if a namespace belongs to kf user: we can check if namespace is owned by a profile.

**Comment by jlewi** [comment]
I'd prefer not to go down the road of running 1 controller per namespace. I think this makes administering Kubeflow clusters much harder (e.g. doing upgrades) because now you have N instances to manage which  becomes impractical without addititional tooling if N is large.

**Comment by jlewi** [comment]
@richardsliu Could you provide an update based on your work with gatekeeper?

**Comment by richardsliu** [comment]
Wrote a doc here: https://bit.ly/2yJeU5u
