### ISSUE TITLE
tensorflow-notebook-image Image build failure due conda updating to python-3.7

### ISSUE THREAD

**Issue by sub-mod** [kubeflow/kubeflow#3625]
Hi All,

I am building tensorflow-notebook-image using below commands
I tested this on v0.5-branch and v0.4-branch
```
git checkout remotes/origin/v0.5-branch
cd components/tensorflow-notebook-image
 ./build_image.sh ./Dockerfile submod/tensorflow-1.13.1-notebook-cpu v0.5.0 ./versions/1.13.1/version-config.json
```

These command worked fine until few weeks ago.
But from past few days I am not able to build them as I get the below error:
```
...
Successfully installed pip-19.0.1
tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
You are using pip version 19.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/bash -c pip install --upgrade pip==19.0.1 &&     pip --no-cache-dir install     ${TF_PACKAGE}     jupyter     jupyter-console==6.0.0     jupyterhub     jupyterlab     xgboost     git+https://github.com/kubeflow/fairing@bd8313d9a4e4dd3b69a840e7cf0ea0d2326d720e     ${PIPELINE_SDK_PACKAGE}     && conda clean -tipsy' returned a non-zero code: 1
```

I notice that `conda update conda` would remove python 3.6 and install python 3.7
```
python:                 3.6.4-hc3d631a_1       defaults    --> 3.7.1-h5001a0f_0          conda-forge
```
This behavior is seen both on v4.4.10 and v4.5.4 Miniconda version.
Is this is known bug ? if so, is there a workaround other than manually changing the Dockerfile by removing `conda update conda` ?

v4.5.4 has some notes about this issue
```
# Install conda as jovyan user and check the md5 sum provided on the download site
# After Miniconda v4.5.4 the default Python version is no longer 3.6, but TensorFlow
# still doesn't support Python 3.7. If we still like to upgrade Miniconda we need
# to add the line "conda install python==3.6" to RUN command below
```
But adding `conda install python==3.6` did not help as `conda update conda` would remove python 3.6 anyways.And since the python version is updated to 3.7 the wheel files mentioned in the version-config.json cannot be installed and the image build fails.

**Comment by jlewi** [comment]
@sub-mod What are you trying to do? Specifically why are you trying to build the docker images from source rather than using the pre-built docker images?

If you are trying to create a custom Jupyter image; then I would suggest trying to follow the directions here
https://www.kubeflow.org/docs/notebooks/custom-notebook/

And simplifying the Dockerfile to install what you need.

It looks like the error you are getting is that you are running into a version mismatch with TF 1.13.

My suggestion would be to start with a TF 1.13 docker image and then follow the instructions above for customizing that docker image to work with Kubeflow and also to install any specific dependencies you have.

**Comment by sub-mod** [comment]
@jlewi 
 
I am building kubeflow tensorflow-notebook-image container image for my internal kubeflow deployment which will have a custom tensorflow wheel file created by me. I have only created  tensorflow-1.13 wheel and I do not have the wheels for the subprojects like tensorflow-serving-api etc.

creating a dockerfile from scratch is not what I want to do.

**Comment by jlewi** [comment]
@sub-mod 

> creating a dockerfile from scratch is not what I want to do.

So it looks like you want to build a custom version in TensorFlow and then build a jupyter image with that version of TF.

The error 

```
tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```

Indicates the version of TF you have compiled is not compatible with the Docker image you are trying to install it.

I can think of two options

1. Fix your build of TF to create a compatible version
1. Find an alternative way to build the docker image that is compatible with your version of

    * If your using TF's build process then you might investigate whether there's  a way to build a Docker image with your version of TF installed in it.

**Comment by sub-mod** [comment]
@jlewi 
I mentioned in my first comment that this is because ` conda update conda` would remove python 3.6 and install python 3.7. As a result I am not able to install the py36 tensorflow wheel since the python version is 3.7. 
This would fail for kubeflow as well. Because the `1.13.1/version-config.json` file  doesnot have 3.7 tensorflow wheel file URLs. So, option 1. suggestion is not needed.

As soon as I remove ` conda update conda`  I am able to build the image.

**Comment by jlewi** [comment]
Thanks @sub-mod.  Glad you figured it out.

#3725 aims to simplify our images and potentially move away from conda.
