### ISSUE TITLE
TF 1.14 and TF 2.0b containers not available

### ISSUE THREAD

**Issue by gogasca** [kubeflow/kubeflow#3633]
TF 1.14 and TF 2.0 beta containers are not available when creating a KF notebook.

in gcr.io/kubeflow-images-public

![image](https://user-images.githubusercontent.com/30065079/61004663-4fd03380-a31b-11e9-9760-4e16b287e89d.png)

**Comment by jlewi** [comment]
See #2358 

It should be possible to use stock TF images with Kubeflow. You should just need to set the command line argument as documented in that issue.

Currently its not possible to do that via the UI but you should be able to do that via kubectl.

@gogasca Do you want to try doing that with kubectl and reporting any issues you hit?

**Comment by jlewi** [comment]
Closing in favor of #3725
