### ISSUE TITLE
"Kubeflow on Kubernetes" Documentation not in sync with current kfctl-v0.5.1 release

### ISSUE THREAD

**Issue by naveen24691** [kubeflow/kubeflow#3636]
Documentation currently available on the https://www.kubeflow.org/docs/started/getting-started-k8s/ does not seem to be working with kfctl-v0.5.1.

kfctl init ${KFAPP} --config=${CONFIG} -V

```
Error: unknown flag: --config
Usage:
  kfctl init <[path/]name> [flags]

Flags:
      --disable_usage_report    disable_usage_report disable anonymous usage reporting.
  -h, --help                    help for init
  -n, --namespace string        namespace where kubeflow will be deployed (default "kubeflow")
  -p, --platform string         one of 'gcp|minikube'
      --project string          name of the gcp project if --platform gcp
  -r, --repo string             local github kubeflow repo
      --skip-init-gcp-project   Set if you want to skip project initialization. Only meaningful if --platform gcp. Default to false
      --use_basic_auth          use_basic_auth use basic auth service instead of IAP.
      --use_istio               use_istio use istio for auth and traffic routing.
  -V, --verbose                 verbose output default is false
  -v, --version string          desired version of Kubeflow or master if not specified. Version can be master (eg --version master) or a git tag (eg --version=v0.5.0), or a PR (eg --version pull/<id>). (default "v0.5.1")

unknown flag: --config

```

However, when I built the kfctl binary from branch v0.6-branch. It seems to be working fine and I am able to install kubeflow on local kubernetes. Looks like documentation is not in sync with the release version v0.5.1

**Comment by Smokrow** [comment]
Same here!

**Comment by yanniszark** [comment]
Hi @Smokrow @naveen24691 

These are instructions for the master branch.
To try it out, you have to build kfctl, by following the instructions there.

If you want to try the v0.5 release, then you have to select it in the upper right side of the page.
This is the page you're following for v0.5: https://v0-5.kubeflow.org/docs/started/getting-started-k8s/

**Comment by naveen24691** [comment]
I see. Thanks.
Anyway, I see the **release v0.6 is out**. This issue is no longer seems to be valid. We can go ahead and close this one.

**Comment by yanniszark** [comment]
Thanks
/close
