### ISSUE TITLE
JupyterWebApp should surface errors (Kubernetes events) related to starting a notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3637]
If the pod for a notebook can't be started then the UI will just keep saying waiting for the notebook and not provide any information about why it can't start.

The UI should surface Kubernetes events so that the user can see what the problem is.

For example, when I tried to start the notebook in the "kubeflow" namespace it doesn't start because of a missing service account

```
Events:
  Type     Reason        Age                     From                    Message
  ----     ------        ----                    ----                    -------
  Warning  FailedCreate  4m28s (x355 over 169m)  statefulset-controller  create Pod jlewitest-0 in StatefulSet jlewitest failed error: pods "jlewitest-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found

```

This is working as intended; the problem is that the failure isn't surfaced in the UI to the user.

More generally we will get similar failures if a user tries to launch a notebook and specifies a volume that doesn't exist.

We want the UI to surface the error so users can figure out how to fix it.

/cc @kimwnasptd

**Comment by kimwnasptd** [comment]
The Jupyter webapp gets the status from the Notebook CR and not from the underlying StatefulSet/Pod. The Notebook Controller sets/updates the status in the CR only while the Pod is created. So if there is a problem with the Pod's scheduling, then the status will not be updated in the Notebook CR.

I think we should handle this case directly from the Notebook Controller.

Currently the webapp checks the `status.containerState` in the Notebook CR and if 
1. it is `waiting` 
2. the `reason` is not `ImagePullBackOff` (error sign :x: ), `ContainerCreating` or `PodInitializing` (spinner) then UI will show a warning sign :warning: 

So to get the UI to show a warning sign in this case, the Controller should also update the state while the Pod isn't created and set the CR's `containerState` to `waiting` and just add the corresponding text to `reason`.

cc @lluunn

**Comment by Jeffwan** [comment]
@jlewi Is the problem solved. By default, `default-editor` is still missing.

**Comment by jlewi** [comment]
@kimwnasptd That makes sense; do you want to open up an issue for the relevant changes to controller?

@Jeffwan The default-editor account is created by creating a Profile resource and using that to create your namespace with associated service accounts.

**Comment by kimwnasptd** [comment]
@jlewi [opened it](https://github.com/kubeflow/kubeflow/issues/3772). Lets track it there

**Comment by jlewi** [comment]
Related: kubeflow/kubeflow#3405 jupyter-web-app should read notebook conditions

Related: kubeflow/kubeflow#3772 Lots of discussion about how to surface statefulset events in the jupyter CR and web app
