### ISSUE TITLE
[GCP] Integrate with workload identity

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3638]
We should integrate with GKE Workload Identity so users should no longer have to download and
manage service accounts directly.
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by lluunn** [comment]
I will look into this.
/assign

**Comment by lluunn** [comment]
It's pretty straightforward to use the feature, basically:
1. create gcp service account
1. create k8s service account
1. add IAM binding

I think there are two tasks:
First, integrate with KF deployment and core components in kubeflow namespaces.
We can get rid of `admin-gcp-sa` in [manifest](https://github.com/kubeflow/manifests/search?q=admin-gcp-sa&unscoped_q=admin-gcp-sa) and kfctl [gcp.go](https://github.com/kubeflow/kubeflow/blob/e6944f35149f7c362d32fb9d57fc9f3842a46347/bootstrap/pkg/kfapp/gcp/gcp.go#L68)

Second, integrate with profile. I am not sure what's the ideal user experience.
Previously, we ask user to create gcp service account + download key + create secret.
Now, we don't need "download key + create secret", but we need a IAM binding, which I think users (in the multi-user scenario) might not have permission to do? 
Or should profile controller take care of creating IAM binding as well? I think there might be a problem that how do we know if the user is allowed to use this service account.

WDYT @jlewi @kunmingg

**Comment by lluunn** [comment]
Actually, the IAM binding is different here:
`gcloud iam service-accounts add-iam-policy-binding`

Which is not the project level iam binding:
`gcloud projects add-iam-policy-binding`

So users might be able to do it, still investigating.

**Comment by lluunn** [comment]
Tested with a pod with workload identity setup:

```
gcloud auth list
ACTIVE  ACCOUNT
*       demo1-admin@kai-test2.iam.gserviceaccount.com
```

gsutil works.

python library also works:
```
client = storage.Client()
bucket = client.get_bucket("kai-test2-models")
bucket.list_blobs()
...
```

**Comment by jlewi** [comment]
Thanks @lluunn so the remaining work here is to figure out how to out to integrate with profiles so that by default any new profile created will automatically bind the edit service account to the appropriate GCP service account?

Any thoughts on how we might do that?

**Comment by jlewi** [comment]
Looks like we have #3917 tracking creating default credentials when creating a new profile.

**Comment by jlewi** [comment]
@lluunn Are we enabling workload identity by default on master?
https://github.com/kubeflow/kubeflow/blob/5b652b18892c7b49af48ecc365b0af1080e0cb06/deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml#L39

* It looks like the default value is set to false ?

**Comment by jlewi** [comment]
@lluunn ping? Do we we have to do any work to enable workload identity by default on master?

Note the deployment manager configs are now in kubeflow/manifests
https://github.com/kubeflow/manifests/tree/master/gcp/deployment_manager_configs

**Comment by lluunn** [comment]
workload identity works in kubeflow and istio-system namespace, the remaining thing is to make it work with default profile / other profile.
Seems overlap with #3917

**Comment by jlewi** [comment]
It looks like we create the secrets in the kubeflow namespace even if workload identity is enabled.
https://github.com/kubeflow/kubeflow/blob/e38c6f3234b301f33226706c285aafb9bd32d357/bootstrap/pkg/kfapp/gcp/gcp.go#L815

I think we should continue to do that in 0.7 for backwards compatibility.

It looks like we still need to enable it in our KFDef spec.
https://github.com/kubeflow/manifests/blob/806766e0013ebfe7e60ab7f8d66b24cd5e532550/kfdef/kfctl_gcp_iap.yaml#L344

We should probably extend our E2E test to verify that the KSA is correctly bound to the GSA and the GSA correctly authorizes the correct service account.

**Comment by jlewi** [comment]
kubeflow/kfctl#40  for the test.
kubeflow/website#1175 for the docs

**Comment by jlewi** [comment]
* I think @kunming committed #4155 which should automatically setup new namespaces using the profile controller
  * I think we still need to wait for the manifests to be updated (tracked in #3917)

* Once that is fixed we should try going through the same CUJ we did for the 0.6 release and verify things are working as expected.

**Comment by jlewi** [comment]
This is fixed.
