### ISSUE TITLE
ks delete default fails

### ISSUE THREAD

**Issue by testphys** [kubeflow/kubeflow#364]
Following the user guide on a minikube cluster, `ks delete default` resulted in `Error strconv.Atoi: parsing "": invalid syntax` for `ksonnet v0.8.0` and in `Error Parse major version failed for` for `ksonnet v0.9.0`.

**Comment by jlewi** [comment]
This appears to be an issue with ksonnet. 
ksonnet/ksonnet#272

It was supposed to be fixed in v0.9.0. Can you open up an issue in ksonnet and provide information about the major and minor version of your cluster.

**Comment by jlewi** [comment]
We should test if this has been fixed by the 0.9 release and if it is close this issue.

**Comment by jlewi** [comment]
This should be fixed with 0.9.2 we should just confirm that.

/cc @ankushagarwal

**Comment by ankushagarwal** [comment]
Verified that this is fixed by 0.9.2
