### ISSUE TITLE
[GCP] Create a PodDefault and GCP secret in namespace ${KUBEFLOW}-user by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3640]
With 0.6 notebooks can no longer be spawned in namespace  kubeflow.

instead users should (see https://bit.ly/2UOzzxB)

1. create their own namespace by defining a profile
1. Download and install a GCP secret in that namespce
1. Create a PodDefault in that namespace

Currently users have to do this manually https://bit.ly/2UOzzxB.

kfctl should do this by default for the user running kfctl. This creates an experience equivalent to what we have in 0.5.

I think we can reuse the existing kubeflow-user GCP service account.

#3639 will define the profile by default for the user.

One potential complication is that we will need to get the order of operations correct e.g.
we need the profile to be created before we can install the service account in the namespace.

**Comment by jlewi** [comment]
I think the quick fix to do this is to add some code at the end of kustomize.Apply 
https://github.com/kubeflow/kubeflow/blob/bca68dd0da5b68eaa7a82e35d3471a6b98798b03/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L230

The code can do something like

1. check if Platform is GCP
1. Download and upload a GCP secret to the profile namespace 

    * #3693 should take care of creating the profile and thus namespace.

1. Create PodDefaults using the newly created secret in that namespace.

**Comment by jlewi** [comment]
reopening

@gabrielwen We need to cherry pick #3639 into the v0.6-branch

**Comment by gabrielwen** [comment]
#3741 does it.
