### ISSUE TITLE
kfctl delete all --delete-storage does not 

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3646]
steps to reproduce

1. kfctl init dls-kf --platform gcp --project $PROJECT --disable_usage_report --namespace=dls-kf --version=v0.6.start --skip-init-gcp-project --package-manager=kustomize@pull/207/head
2. CLIENT_ID=xxx CLIENT_SECRET=yyy kfctl generate all --zone=us-west1-a
3. CLIENT_ID=xxx CLIENT_SECRET=yyy kfctl apply all --verbose
4. kfctl delete all --delete_storage

checking the deployment manager in the gcp console shows that the storage remains

**Comment by jlewi** [comment]
As part of the fix we should update the E2E test to verify that its cleaned up
https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kfctl_delete_test.py

**Comment by holdenk** [comment]
Ran into this again today.

**Comment by gabrielwen** [comment]
verified it's not working in v0.7.0

**Comment by gabrielwen** [comment]
#120 removes the flag - now you need to set this value to gcp plugin in KfDef.
