### ISSUE TITLE
Can't specify a manifests PR for any kubeflow PR

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3649]
there should be a way to specify a manifests PR when a kubeflow PR requires changes in manifests.
Similarly, there should be a way to specify a kubeflow PR from a manifests PR.

@jlewi Is there a way to use PULL_PULL_SHA? Right now I'm setting it explicitly in kfctl_go_test.py (see #3639 )

**Comment by jlewi** [comment]
@kkasravi If you need to do cross repo changes e.g. upgrade a manifest from v1 to v2 and update kfctl to use v2 normal workflow would be to do this in 3 PRs.

1. Create V2 in kubeflow/manifests
1. Update kubeflow/kubeflow to use V2
1. Delete v1 in kubeflow/manifests

To the extent kfctl supports pulling kubeflow/manifests at a particular commit or PR you can use that to control which version a PR in kubeflow/kubeflow runs against.
