### ISSUE TITLE
[GCP] Install ISTIO on private GKE clusters

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3650]
Now that we are using ISTIO we will need to figure out and document how to install ISTIO on private GKE clusters.

**Comment by jlewi** [comment]
Status update.

* I think there are various folks in the community working on this

  * @jtfogarty  is one

  * There's this [thread](https://groups.google.com/forum/#!searchin/kubeflow-discuss/gojek%7Csort:date/kubeflow-discuss/1V4w7OHoML0/94jGnamoAgAJ) in the mailing list

* kubeflow/kubeflow#3210 is tracking updating our tools to replicate images to GCR to be compatibile with private GKE.

  * For ISTIO and private GKE, I think we might want to switch to using [ISTIO on GKE](https://cloud.google.com/istio/docs/istio-on-gke/installing) rather than installing it ourselves

**Comment by oxxygenio** [comment]
Here is the 2 most important steps of how to get istio working on the private cluster in GKE. Spent 4 full days hunting this down.
1. Allow incoming traffic, use Cloud NAT, this will allow access to istio images. (i.e. **istioctl manifest apply** will work)
2. Set the firewall rule for the master to allow port 9443 on ingress, if you don't the sidecar webhook inject will not work (no pods will be created on your deployments).

Enjoy.

**Comment by jlewi** [comment]
@oxxygenio thanks for tracking this down. 

Cloud Nat seems like a great solution (at least as a stop gap) to allow pulling all the images until #3210 is fixed.

@oxxygenio any interest in submitting a PR to update the docs
https://github.com/kubeflow/website/blob/6f0cc17a639a96444f64cfb097a22d827d679bf7/content/docs/gke/private-clusters.md

With this information?

**Comment by jlewi** [comment]
Issue for migrating to Anthos service Mesh (AKA managed ISTIO)
kubeflow/manifests#1024

**Comment by jlewi** [comment]
https://github.com/kubeflow/gcp-blueprints
is now using ASM. So we just need to verify it works with private GKE and then we can close this issue.

**Comment by jlewi** [comment]
Closing in favor of: kubeflow/gcp-blueprints#33
