### ISSUE TITLE
notebook controller 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3656]
Place holder for graduating the notebook controller to 1.0

#3655 is for beta.

Below is a table based on our proposed application requirements (see kubeflow/community#285)

### Configuration and deployment

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Kustomize package  | Required  | Done |  
| Application CR  | Required  | [Done](https://github.com/kubeflow/manifests/tree/master/jupyter/notebook-controller/overlays/application) | 
| Images listed in kustomization.yaml | Required  | Done |
| Upgradeability | Required  | No-op | 
| Separate cluster scoped and namespace scoped resources | Recommended  | Done | kubeflow/kubeflow#4063
| Kustomize package should be deployable on its own | Recommended  | Not Done | kubeflow/kubeflow#4064

### Custom Resources

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Version stability | Required  | Done | kubeflow/kubeflow#3940
| multi-version support | Required  | Done | kubeflow/kubeflow#3940
| Supports status subresource | Required  | Done | kubeflow/kubeflow#4016
| CRD schema validation | Required  | [Done](https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base/crd.yaml#L15) |

### Misc. (feature/fix/enhancement)
| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Fix CR status | Required | Done | kubeflow/kubeflow#3772
| Integration with Profile | Required | Done | kubeflow/kubeflow#2981
| Culling | Recommended | WIP | kubeflow/kubeflow#1394

### Logging and monitoring

| Description | Category |  Status | Issue
|-------------|----------|-------------|-------------|
| Liveness/Readiness signals | Required  | Done | kubeflow/kubeflow#4060
| Prometheus metrics | Required  |  Done | kubeflow/kubeflow#3722 |
| Json logging | Recommended  | Not Done | kubeflow/kubeflow#4066

### CI/CD

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| E2E tests | Required  | Done | kubeflow/kubeflow#3721
| Scalability / load testing | Required | Done | kubeflow/kubeflow#4019 |
| Continuous building of docker images | Recommended | Done | kubeflow/kubeflow#4020 |
| Continuous updating of Kustomize manifests | Recommended  | Done | kubeflow/kubeflow#4020

### Docs

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| API Reference docs | Required | Done | kubeflow/kubeflow#3723 |
| Application docs | Required | [Needs Review](https://www.kubeflow.org/docs/notebooks/) |  |

### Ownership/Maintenance

| Description | Category | Explanation | Status | Issue
|-------------|----------|-------------| ----------|-------------
| Healthy number of committers and commits | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| List of users running the application | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by jlewi** [comment]
* kubeflow/kubeflow#4621 - is tracking the V1 API; looks like we need to update the kustomize manifest

* It looks like multi-version support was done as part of upgrading to v1beta1
  * https://github.com/kubeflow/manifests/blob/b7be78ad68cc0526570bfa3f775c99a020337d34/jupyter/notebook-controller/base/crd.yaml#L14

* Looks like E2E tests #3721 is done

* For prometheus metrics it looks like we just need to verify that its been fixed.

**Comment by jlewi** [comment]
Looks like the only remaining issue before closing this out is the docs.

**Comment by jlewi** [comment]
Here's the CR  from a 1.0 cluster deployed at
https://github.com/kubeflow/manifests/tree/861868c

This confirms the V1 API is listed.

[notebook.yaml.txt](https://github.com/kubeflow/kubeflow/files/4153785/notebook.yaml.txt)

**Comment by jlewi** [comment]
Looks like there are a couple issues left

* Liveness probes #4060 - waiting on cherry-pick and verification
* Reference Docs #3723 
* Scalability load testing #4019

**Comment by DavidSpek** [comment]
The three issued mentioned above by @jlewi have since been closed. Can this issue also be closed?
