### ISSUE TITLE
Profile CRD should have scope Namespaced

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3658]
@kunmingg 

In order to do multi-tenancy we need to scope all profiles  and the profiles-controller to the namespace provided in `kfctl init ...`, otherwise the default_profile is cluster wide and a second deployment of kubeflow won't work.

**Comment by kunmingg** [comment]
@kkasravi  
Do you mean re-deploy kubeflow to same cluster?
Is this a problem for all cluster-scope CRDs?
Can we skip if CR already exist?

**Comment by kkasravi** [comment]
It is, we have this problem in general. For creating a default profile, wouldn’t it create problems if the same person deployed Kubeflow more than once to the same cluster?

**Comment by kunmingg** [comment]
I think the issue is we might need to support smooth re-deploy & upgrade (in v0.7?).

**Comment by mattnworb** [comment]
+1 to this issue, having separate distinct installations of Kubeflow on the same Kubernetes cluster sounds very useful (as that isolation is exactly what k8s namespaces are meant to provide).

**Comment by yanniszark** [comment]
> a second deployment of kubeflow won't work.

The general feeling I got from v0.6, is that we are moving towards a model where Kubeflow is deployed once (system components in namespace kubeflow) and then users are isolated using namespaces.

Are we working towards a different model now?
I have the feeling that multiple kubeflow installations would be difficult to achieve now, considering that the current multi-tenancy model is still in the works.

@jlewi @abhi-g thoughts?

**Comment by abhi-g** [comment]
I am trying to understand the User Scenario where this is required. It will be helpful if we can document the value of multiple Kubeflow deployments within a single K8s cluster.

**Comment by kkasravi** [comment]
If system components were namespace scoped then multiple deployments could be created, where submitting a Profile would need a Profile.metadata.namespace which would be that particular Kubeflow deployment

**Comment by kunmingg** [comment]
@mattnworb 
Kubeflow v0.6 support namespace based user / service isolation.
Is that what you mean?

**Comment by kunmingg** [comment]
What's the benefit to duplicate system components?
I feel k8s resources are either global or namespace-scoped?

**Comment by mattnworb** [comment]
> @mattnworb
> Kubeflow v0.6 support namespace based user / service isolation.
> Is that what you mean?

No. I am agreeing with the comments above that the `Profile` resource should be namespaced (in the kubeflow home namespace) so that an administrator could choose to install multiple instances of Kubeflow in the same kubernetes cluster (e.g. `kubeflow-1`, `kubeflow-2`) without them sharing the list of profiles if they wish to. If the CRD is global instead of namespaced, then kubeflow is making that decision for the administrators, but if you namespace the custom resource, you put the decision in the admin's hands.

**Comment by kkasravi** [comment]
> What's the benefit to duplicate system components?
> I feel k8s resources are either global or namespace-scoped?

if you need to upgrade different tenants at different times.
If you need to delete one tenant.

**Comment by kunmingg** [comment]
@kkasravi 
By `tenant` do you mean user (profile) or a kubeflow system namespace?
If it's kubeflow system namespace, can we instead have multiple clusters and each cluster only have 1 system namespace?

**Comment by kunmingg** [comment]
If we have both kubeflow system v0.6 and v0.7 deployed to same cluster (each has their own namespace: ns06 and ns07), they might be conflict when operating on a user's namespace?

**Comment by kkasravi** [comment]
> By `tenant` do you mean user (profile) or a kubeflow system namespace?

@kunmingg the kubeflow system namespace


> If it's kubeflow system namespace, can we instead have multiple clusters and each cluster only have 1 system namespace?

yes that would be a good alternative

**Comment by kkasravi** [comment]
> If we have both kubeflow system v0.6 and v0.7 deployed to same cluster (each has their own namespace: ns06 and ns07), they might be conflict when operating on a user's namespace?

When the Profile is submitted and profile.metadata.namespace=ns06, we would need to add this as an annotation when the user's namespace is created. I don't think we've done much prototyping on this

**Comment by jlewi** [comment]
I agree with @abhi-g 's comment above that we are missing a clear use case for why we want to support two kubeflow deployments in the same cluster.

I think supporting multiple kubeflow deployments in the same cluster is a significant amount of work.

As @kunmingg and @yanniszark mentioned above our multi-tenancy model today is that the components in the kubeflow namespace run as shared multi-tenant services and each user consumes them in their own namespace.

IIUC the proposal is to support a model where we have to multiple sets of the shared Kubeflow services.
