### ISSUE TITLE
Notebooks are not accessible when using docker image from Jupyter Docker Stack

### ISSUE THREAD

**Issue by jerrylam** [kubeflow/kubeflow#3660]
I'm running kubeflow 0.5
I'm trying to use an image from jupyter docker stack: https://hub.docker.com/r/jupyter/all-spark-notebook from the http://<host>:8080/_/notebooks.
After the container starts, I clicked "connect". It returns:
```
404 : Not Found
You are requesting a page that does not exist!
```
The same image works fine if I start the container from the jupyterhub component. 

I suspect this is the URL issue because I inspect the container running the notebook and I can see it returns 404. 
I suspect that this is a problem with the jupyter-web-app component.
I wonder if it is intended that the jupyter-web-app component work with the jupyter docker stack?
Thank you.

**Comment by jlewi** [comment]
@jerrylam see the docs here
https://www.kubeflow.org/docs/notebooks/custom-notebook/

You need to specify the jupyter command to properly configure jupyter to start with appropriate arguments.

Please reopen this issue if that doesn't answer your question.
