### ISSUE TITLE
Can't use notebook

### ISSUE THREAD

**Issue by zhang87492** [kubeflow/kubeflow#3667]
Visit kubeflow's notebook, click on newserver, always get an error like this
`Uncaught ReferenceError: $ is not defined
    at notebooks.js:9`
![D(2Q(Q53~16YX0@$RB 2@22](https://user-images.githubusercontent.com/13113547/61263495-a629f000-a7bb-11e9-9e11-8f66d766983f.png)

**Comment by zhang87492** [comment]
version v.0.5.0

**Comment by richardsliu** [comment]
@zhang87492 
0.6 was just released. Can you see if your issue still happens?

**Comment by zhang87492** [comment]
@richardsliu 
I want to updata kubeflow when a stable version is available.
