### ISSUE TITLE
[Reference] Architecture in cluster docker registry for fairing?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3672]
One of our core CUJs is build/train/deploy from a notebook running inside a cluster.

This requires a docker registry that we can push docker images to.

Should we provide a reference implementation that can run in cluster?

/cc @krishnadurai 
/cc @yanniszark

**Comment by krishnadurai** [comment]
@jlewi we can have a docker registry as an optional component.
I'm looking for certain clarifications here as I'm not familiar with fairing's code:

Are the repositories you pull from and push to different? My current understanding is that they are the same.
https://github.com/kubeflow/fairing/blob/4fc76bebf10c375b266821a91e67c0d5a5530069/fairing/builders/append/append.py#L37

In this case, we might need to mirror contents of the remote repository to this internal repository.
