### ISSUE TITLE
Notebook spawn: button turn green even backend not ready.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3677]
For now as long as service of notebook instance up, button will turn green.
Even if backend pod not ready (timeout due to first time launch huge image...) 

User will end up saw `unhealthy upstream` after click button.
We should wait till pod is ready.

**Comment by kunmingg** [comment]
@karthikv2k @abhi-g

**Comment by abhi-g** [comment]
@kimwnasptd Is this a UI issue?

**Comment by kimwnasptd** [comment]
The webapp checks the `status.containerState` in the Notebook CR. This gets set from the Notebook Controller and it mirrors the state of the undrelying Pod. The UI will show the green check only if the state is `running`.

@kunmingg IIUC your backend Pod is not created, yet the UI shows a green check? What is the `status` in that Notebook's CR? How can I reproduce what you saw?

**Comment by kimwnasptd** [comment]
I think the issue might be that the `status.containerState` that we expose in the Notebook CR refers to the `containerStatus[0]` in the Notebook Pod.

But, if we also have ISTIO then this Container is the one with Envoy. So the UI actually shows the status of the Envoy Container and not the Notebook Image's Container (which might even have an `ImagePullBackOff` for example).

More info on #3820
