### ISSUE TITLE
How to create TFJob/PytorchJob/MXnetJob Resource using io.fabric8 kubernetes client?

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/kubeflow#3681]

**Comment by Jeffwan** [comment]
@jokerwenxiao They are all custom resources and I think you can follow this example

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java

**Comment by jlewi** [comment]
@jokerwenxiao Please take a look at @Jeffwan 's answer. If that doesn't answer you question please reopen this issue. It would be helpful if you could provide more description about 

* what you are trying to do
* what you tried
* what result you got

**Comment by raven-jia** [comment]
> @jokerwenxiao Please take a look at @Jeffwan 's answer. If that doesn't answer you question please reopen this issue. It would be helpful if you could provide more description about
> 
> * what you are trying to do
> * what you tried
> * what result you got

Hi, I'm also trying to create kubeflow pytorchjob using fabric8. According to @Jeffwan 's answer, I should use 
`new CustomResourceDefinitionBuilder()`
to define kubeflow.org/v1 pytorchjob as a CRD. Then I should have some files as the definition, in @Jeffwan 's case, it's Dummy.class. So do you know which files I can use like that?

However, my situation is that, I have kubeflow installed on k8s clusters, I just need fabric8 to connect my java program to the clusters. But fabric8 client does not have the kubeflow resource. I feel that for my situation, do a CRD may not be necessary? Do you know how I could do?

Thank you! I'm not sure I'm on the right track, so correct me if there's anything I misunderstood!

**Comment by zyedManai** [comment]
Hello @ravenj73 do you have updates on this issue? Have you solved the problem ?
