### ISSUE TITLE
Kubeflow SDK

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kubeflow#3683]
/feature

In kubeflow projects, each component has its own SDK, such as Fairing have fairing sdk, and pipeline has kfp sdk, that will confuse kubeflow end user.  As @animeshsingh raised in https://github.com/kubeflow/kfserving/issues/246, ideally we need to start aligning to "one" sdk for whole of kubeflow.

/cc @animeshsingh @jlewi

**Comment by gyliu513** [comment]
@jlewi @jinchihe +1 for this, OpenStack also has similar SDK as https://github.com/openstack/openstacksdk , it would be great to have kind of kubeflowsdk for facilitate second development work.

FYI @hougangliu

**Comment by animeshsingh** [comment]
+1 
As discussed. Initial thoughts here
https://docs.google.com/document/d/1AqoBKaCszbKNPV9VEruDx0HCbrk-EJaei05m3kEG5-0/edit
