### ISSUE TITLE
fresh baremetal install fails to start tf-job-operator - can't find CRD

### ISSUE THREAD

**Issue by rosgluk** [kubeflow/kubeflow#3684]
Hi, I'm trying to install Kubeflow 0.6rc0 and tf-job-operator is not taking off

k8s client  v1.15.0
k8s server v1.14.3  baremetal - kubespray+metallb
kfctl is compiled from fresh master branch
used unmodified kfctl_existing_arrikto.0.6.yaml

and pod with tf-job-operator is in CrashLoopBackOff, trying to find CRD and fails, but it looks like CRD is there...

can someone please point where to look to fix it?

------

kubectl get pods -n kubeflow
->
...
tf-job-operator-79cbfd6dbc-2r4s9                           0/1     CrashLoopBackOff   13         46m

--------------------------------

kubectl describe pod tf-job-operator-79cbfd6dbc-2r4s9  -n kubeflow
->
Name:           tf-job-operator-79cbfd6dbc-2r4s9
Namespace:      kubeflow
...
   Environment:
      MY_POD_NAMESPACE:  kubeflow (v1:metadata.namespace)
      MY_POD_NAME:       tf-job-operator-79cbfd6dbc-2r4s9 (v1:metadata.name)
    Mounts:
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from tf-job-operator-token-n5npl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
...
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  47m                   default-scheduler  Successfully assigned kubeflow/tf-job-operator-79cbfd6dbc-2r4s9 to node2
  Normal   Pulled     45m (x5 over 47m)     kubelet, node2     Container image "gcr.io/kubeflow-images-public/tf_operator:v0.6.0.rc0" already present on machine
  Normal   Created    45m (x5 over 47m)     kubelet, node2     Created container tf-job-operator
  Normal   Started    45m (x5 over 47m)     kubelet, node2     Started container tf-job-operator
  Warning  BackOff    117s (x211 over 47m)  kubelet, node2     Back-off restarting failed container

-----------------------

kubectl logs tf-job-operator-79cbfd6dbc-2r4s9  -n kubeflow
->
{"filename":"app/server.go:75","level":"info","msg":"EnvKubeflowNamespace not set, use default namespace","time":"2019-07-17T12:17:05Z"}
{"filename":"app/server.go:79","level":"info","msg":"Using cluster scoped operator","time":"2019-07-17T12:17:05Z"}
{"filename":"app/server.go:85","level":"info","msg":"[API Version: v1 Version: v0.1.0-alpha Git SHA: Not provided. Go Version: go1.12 Go OS/Arch: linux/amd64]","time":"2019-07-17T12:17:05Z"}
W0717 12:17:05.840732       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"filename":"tf-operator.v1/main.go:40","level":"info","msg":"Setting up client for monitoring on port: 8443","time":"2019-07-17T12:17:05Z"}
{"filename":"app/server.go:209","level":"error","msg":"the server could not find the requested resource (get tfjobs.kubeflow.org)","time":"2019-07-17T12:17:05Z"}
{"filename":"app/server.go:109","level":"info","msg":"CRD doesn't exist. Exiting","time":"2019-07-17T12:17:05Z"}

-----

kubectl describe crd tfjobs.kubeflow.org
->

Name:         tfjobs.kubeflow.org
Namespace:    
Labels:       app.kubernetes.io/deploy-manager=ksonnet
              ksonnet.io/component=tf-job-operator
Annotations:  ksonnet.io/managed:
                {"pristine":"H4sI...
              kubecfg.ksonnet.io/garbage-collect-tag: gc-tag
API Version:  apiextensions.k8s.io/v1beta1
...
  Version:                      v1beta1
  Versions:
    Name:     v1beta1
    Served:   true
    Storage:  true
    Name:     v1beta2
    Served:   true
    Storage:  false
Status:
  Accepted Names:
    Kind:       TFJob
    List Kind:  TFJobList
    Plural:     tfjobs
    Singular:   tfjob
  Conditions:
    Last Transition Time:  2019-07-06T11:40:46Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1

---------------------

**Comment by jlewi** [comment]
Something looks wrong with your TFJob install.

The version should be v1 
https://github.com/kubeflow/manifests/blob/eeaff416be9d273356bb55e2d823bb797b950ba4/tf-training/tf-job-operator/base/crd.yaml#L44

But it looks like you have v1beta1 installed.

It also looks like the CRD was installed via ksonnet which indicates an install from a version previous to 0.6.

* I would suggest deleted the CRD and reinstalling it.

Are you trying to install 0.6 on a cluster you had previously installed Kubeflow on?

**Comment by rosgluk** [comment]
Hi jlewi,
thanks for your reply

>> Are you trying to install 0.6 on a cluster you had previously installed Kubeflow on?
yes, was trying to install 0.5.1 there before and removed with

kfctl delete all -V

kfctl was of previous precompiled version then
probably left some residual

----

the following helped:

cd ${KFAPP}     # where kfcluster configs are
kubectl delete crd tfjobs.kubeflow.org
kubectl create -f kustomize/tf-job-operator/base/crd.yaml

---

please close this issue
