### ISSUE TITLE
[kfctl] apply on partially deployed kubeflow cluster fails; 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3686]
I  did the following

1. Deploy kubeflow
1. Delete namespace kubeflow
1. Rerun kfctl apply to fix kubectl

This gives the error

```
couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocate
```

We should fix this; i.e catch the error and keep going.

Running kfctl apply on an already deployed Kubeflow should be idempotent for resources that already exist

**Comment by QxiaoQ** [comment]
Also meet this issue, when I install kubeflow on Minikube.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/31646170/61618199-e814d380-ac9e-11e9-9607-5cdaa7ea22b8.png">

**Comment by pdmack** [comment]
31380 conflicts with kube-proxy port, at least for on-prem.

istio/istio#10795 identified this but left the nodePorts in there.

**Comment by jlewi** [comment]
@pdmack Do you want to open a separate issue about the port conflict?

**Comment by jlewi** [comment]
Duplicate of #3810

**Comment by lalithvaka** [comment]
@jlewi I am trying the Kubeflow for the first time and ran into this issue. Wondering how do I get past this before the 0.7 is released? 
Also ran into the following as well.. 
INFO[0021] creating StatefulSet/application-controller-stateful-set  filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"

**Comment by jlewi** [comment]
@lalithvaka This looks like #3989

**Comment by lalithvaka** [comment]
> @lalithvaka This looks like #3989

Thank you Jeremy @jlewi , I have reviewed the 3989. kubectl get crd -->  gives me a bunch from adapters to zipkins. Towards the end of the issue, I see its pointed to #3810 (comment) (https://github.com/kubeflow/kubeflow/issues/3810#issuecomment-527687504). Do you suggest I use this fix for a workaround?

**Comment by jlewi** [comment]
>  kubectl get crd --> gives me a bunch from adapters to zipkins.

I'm not sure what this means.

If your trying to rerun kfctl apply and hitting the issue in #3810 then I would suggest following the work around in that issue.

If your issue looks like a different problem please open a new issue.

**Comment by lalithvaka** [comment]
> > kubectl get crd --> gives me a bunch from adapters to zipkins.
> 
> I'm not sure what this means.
> 
> If your trying to rerun kfctl apply and hitting the issue in #3810 then I would suggest following the work around in that issue.
> 
> If your issue looks like a different problem please open a new issue.

I believe the workaround seems to have worked with lot of warning msgs. I got all the KubeFlow seervices up and running. Thank you @jlewi  for all the help. Appreciate it.
