### ISSUE TITLE
unittests for consistency across deployment examples

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3688]
We are moving in the direction of having multiple config files like
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_gcp_iap.0.6.yaml
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_existing_arrikto.0.6.yaml

that specify different configurations of Kubeflow

We should add unittests that ensure consistency.

i.e. we should add a test that verifies certain applications are included across a set of configs.

**Comment by Tabrizian** [comment]
I want to help but not sure how to get started.

**Comment by Swikar** [comment]
> I want to help but not sure how to get started.

@Tabrizian have you yet figure out how to get started, this issue?

**Comment by Tabrizian** [comment]
@Swikar No, I didn't.
