### ISSUE TITLE
Namespace selection UI is half hidden by navigation bar

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#3698]
KF 0.6, deployment on 7/19 from Master

KF main dashboard, namespace selector
When clicking on the namespace selector at the top of the page, the drop down is half way hidden by the left nav pane, making it impossible to see the names of the namespaces.

![namespaceselect](https://user-images.githubusercontent.com/4884947/61571919-34b4a080-aa4c-11e9-9608-838b8a7c6479.png)

**Comment by avdaredevil** [comment]
On it!

**Comment by jlewi** [comment]
@avdaredevil Do we need to build a new docker image and update the manifest
https://github.com/kubeflow/manifests/blob/v0.6-branch/common/centraldashboard/base/kustomization.yaml

It looks like the current image is pointing at v0.6.0-rc2 which is 6 days old and thus likely from before the PR was submitted.

It looks like there is a newer image:
v20190726-v0.6.0-rc.0-30-g2141a36b

It looks like this is coming from pull request
https://github.com/kubeflow/kubeflow/commit/2141a36b

@avdaredevil Ideally we would do the following

1. Cherry-pick required changes on to the v0.6-branch of kubeflow/kubeflow
2. Build and push an image from the v0.6-branch 
3. update the manifests on the v0.6-branch of kubeflow/manifests

Should we do that?

**Comment by avdaredevil** [comment]
I see, let's stash this till v0.6.2, since the image you mentioned includes partial upgrades for the Multi-User isolation CUJ.

**Comment by jlewi** [comment]
@avdaredevil What's the ETA for getting a docker image built with the changes and getting kubeflow/manifests updated to include the changes?

**Comment by avdaredevil** [comment]
The images are already made, the PRs still have some work that needs to be done:
- Addressing UX Review
- Addressing minor testing comments on #3758 

I already have the images built with functional up-to-date changes (gcr.io/kubeflow-images-public/centraldashboard:v20190801-v0.6.0-rc.0-44-g5b463203). If you'd like I can make that image as the target and satisfy #3795 

Or I can wait till those changes are done, and then build a new set. (functionally there will be no difference as mostly there are 1-2 UX tweaks and new tests that are added)

**Comment by avdaredevil** [comment]
/close

In favor of Cherrypick Issue aforementioned

**Comment by jlewi** [comment]
@avdaredevil What docker image includes the fix? And have we updated kubeflow/manifests to use the new image?
