### ISSUE TITLE
KF dashboard is not showing the link to Artifacts

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#3699]
KF deployed from master, 7/19

The deployment includes the metadata-ui and other metadata services,
The metadata UI is accessible over a port forward to the metadata-ui pod

However - the KF Dashboard is not showing the link to the Artifacts (metadata) page, and the link <cluster DNS>/_/metadata is not working.

**Comment by prodonjs** [comment]
I believe this has been addressed by ensuring that the image tagged for v0.6.0 (https://github.com/kubeflow/manifests/blob/f0744dcab59c8c9325b10ed8d2b97339da22bc5c/common/centraldashboard/base/kustomization.yaml#L17) reflects the correct code state which includes #3569 .
