### ISSUE TITLE
Size of gcr.io/kubeflow/tensorflow-notebook-*

### ISSUE THREAD

**Issue by flx42** [kubeflow/kubeflow#37]
From the README:
> We also ship standard docker images that you can use for training Tensorflow models with Jupyter.
> 
>     gcr.io/kubeflow/tensorflow-notebook-cpu
>     gcr.io/kubeflow/tensorflow-notebook-gpu
> 
> [...] Note that GPU-based image is several gigabytes in size and may take a few minutes to localize.

("localize"?)

They are both large:
```sh
$ docker images gcr.io/kubeflow/tensorflow-notebook-gpu:latest
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
gcr.io/kubeflow/tensorflow-notebook-gpu   latest              e68d36c67064        2 weeks ago         7.11GB

$ docker images gcr.io/kubeflow/tensorflow-notebook-cpu:latest
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
gcr.io/kubeflow/tensorflow-notebook-cpu   latest              9cb2a6008740        2 weeks ago         5.17GB
```
Are the Dockerfiles public for these images? I can probably do a quick PR to improve the size.

You might be interested to look at the improvements I did in the `devel-gpu` Dockerfile for TensorFlow:
https://github.com/tensorflow/tensorflow/pull/15355

Also, it would be helpful if you could chime in on this RFE:
https://github.com/tensorflow/tensorflow/issues/15284
Maybe we can have a single image with Jupyter+TensorFlow+TensorBoard? That would shrink the other TensorFlow images that are shipped today (e.g. `gpu` and `devel-gpu`).

**Comment by pineking** [comment]
I also think the size can be reduced. BTW: is it possible to push the images to dockerhub instead of gcr.io?

**Comment by jlewi** [comment]
@vishh  Are we just using the tensorflow Docker images? I don't see any Dcokerfiles for these notebook images inside google/kubeflow.

**Comment by flx42** [comment]
No it's not the same, if you do `docker history --no-trunc gcr.io/kubeflow/tensorflow-notebook-gpu`, you can see it's different from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu or https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu

**Comment by jlewi** [comment]
We'd like to support a bunch of different frameworks e.g.

- TensorFlow
- xgboost
- scikits

Some questions:

- Should we provide one fat image with all these libraries or have multiple images?
- Are there existing, curated images that we can reuse as opposed to building our own?

**Comment by aronchick** [comment]
Was there something in particular that was an issue with GCR.io?

**Comment by yuvipanda** [comment]
@aronchick afaict gcr.io doesn't provide a human friendly URL to pass to people, which I've always found annoying for public images.

@jlewi there's some at http://github.com/jupyter/docker-stacks/ (and PRs welcome!) that do get a fair amount of usage.

**Comment by jlewi** [comment]
This is the source for our existing Docker images
https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/example/tensorflow-notebook-image

So everything is public and we should probably move them into Kubeflow.

Using an NVIDIA as the base image for our GPU images makes sense to me.

/cc @flx42

**Comment by flx42** [comment]
Ok, let's discuss about the size again when it's on this repo.
But I believe it still makes sense to check with the TensorFlow team if a single common Jupyter image can be created.
