### ISSUE TITLE
kubeflow v0.6.0 installation using kfctl failing

### ISSUE THREAD

**Issue by ocdkube** [kubeflow/kubeflow#3701]
Trying to install kubeflow v0.6.0 using kfctl, but its failing while generating component.
Below is the output for same:

**# ../kfctl generate all -V**
INFO[0000] reading from /tmp/kubeflow/kubeflow/app.yaml  filename="coordinator/coordinator.go:341"
INFO[0000] reading from /tmp/kubeflow/kubeflow/app.yaml  filename="coordinator/coordinator.go:341"
INFO[0000] Ksonnet.Generate Name kubeflow AppDir /tmp/kubeflow/kubeflow Platform   filename="ksonnet/ksonnet.go:369"
INFO[0000] Creating environment "default" with namespace "kubeflow", pointing to "version:v1.11.0" cluster at address "https://okd-master:8443"  filename="env/create.go:77"
INFO[0004] Generating ksonnet-lib data at path '/tmp/kubeflow/kubeflow/ks_app/lib/ksonnet-lib/v1.11.0'  filename="lib/lib.go:148"
INFO[0004] Successfully initialized the app kubeflow.    filename="ksonnet/ksonnet.go:505"
INFO[0004] App kubeflow add registry kubeflow URI /tmp/kubeflow/kubeflow/.cache/v0.6.0/kubeflow  filename="ksonnet/ksonnet.go:621"
INFO[0004] Retrieved 6 files                             filename="registry/cache.go:114"
INFO[0004] Retrieved 22 files                            filename="registry/cache.go:114"
INFO[0004] Retrieved 9 files                             filename="registry/cache.go:114"
INFO[0004] Retrieved 32 files                            filename="registry/cache.go:114"
INFO[0004] Retrieved 6 files                             filename="registry/cache.go:114"
INFO[0004] Retrieved 49 files                            filename="registry/cache.go:114"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for ksonnet:  (kubeflow.error): Code 400 with message: couldn't add package katib-v1alpha2. Error: there was a problem installing package katib-v1alpha2: resolving package metadata: kubeflow/katib-v1alpha2: open /tmp/kubeflow/kubeflow/.cache/v0.6.0/kubeflow/katib-v1alpha2/parts.yaml: no such file or directory
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'
      --ipName string     ipName if '--platform gcp'
      --mount-local       mount-local if '--platform minikube'
  -V, --verbose           verbose output default is false
      --zone string       zone if '--platform gcp'

couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for ksonnet:  (kubeflow.error): Code 400 with message: couldn't add package katib-v1alpha2. Error: there was a problem installing package katib-v1alpha2: resolving package metadata: kubeflow/katib-v1alpha2: open /tmp/kubeflow/kubeflow/.cache/v0.6.0/kubeflow/katib-v1alpha2/parts.yaml: no such file or directory

**Comment by jlewi** [comment]
It looks like the code is invoking ksonnet

```
INFO[0004] Successfully initialized the app kubeflow. filename="ksonnet/ksonnet.go:505"
```

But 0.6 shouldn't be invoking that code.

Can you please run

```
kfctl version
```

So we can check which version of kfctl you are running?

**Comment by ocdkube** [comment]
# ./kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e

**Comment by Kyrremann** [comment]
@ocdkube your using an old version of `kfctl`. The output for `v0.6.0` should be:
```
$ kfctl version
kfctl v0.6.0-0-g71aea0a9
```

**Comment by jlewi** [comment]
@ocdkube Please try the new version of kfctl and reopen the issue if that doesn't fix the problem.
