### ISSUE TITLE
Cut 0.6.1  - tracking bug for cutting the first minor release for 0.6

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3702]
#3559 - Tracking bug for 0.6.0 - Has previous context

Here is the [list](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubeflow+label%3Apriority%2Fp0+project%3Akubeflow%2F5+is%3Aopen+) of P0 blocks that are blocking us.

Demo script:
https://bit.ly/2UOzzxB

Key features that we'd like to get into 0.6.1

* Fix bugs with metadata UI not showing up.
* #3640 Create GCP secret by default in the namespace

**Comment by avdaredevil** [comment]
This needs to be added: #3742

**Comment by jlewi** [comment]
@avdaredevil IT looks like #3742 didn't make the cut. PTAL at my comment on the issue.
