### ISSUE TITLE
KfDef specs should use KfDef v1beta1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3703]
The KfDef specs stored here:
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config

Should be updated to use KfDef.Spec.Applications.
Support for KfDef.Spec.Applications should already be available in v0.6.0

Follow on to #3491

0.7 configs should be updated to use KfDef v1beta1.

**Comment by jlewi** [comment]
GCP configs are updated.

I think Arrikto config will be updated by #3904.

@Jeffwan Do you want to update the AWS configs?

**Comment by Jeffwan** [comment]
Just see this issue. I will make corresponding change.

**Comment by richardsliu** [comment]
Is this done?

**Comment by jlewi** [comment]
@richardsliu no; kfctl doesn't support v1beta1 yet and the KFDef YAML files still need to be updated.
https://github.com/kubeflow/manifests/blob/18a8882d1ae3b4fdae2d1d34f80005948a7566b7/kfdef/kfctl_gcp_iap.yaml#L2

@gabrielwen How far will you get with this this week?

@gabrielwen will be OOO next week so maybe someone else can help pick up remaining work next week?

**Comment by gabrielwen** [comment]
so here we could use v1beta1 in kfctl:
https://github.com/kubeflow/kubeflow/blob/6a0fd60a8bfec01ebff6ff4d1a2760320b399374/bootstrap/pkg/apis/apps/kfdef/kfloader.go#L197

I just mentioned this to @swiftdiaries so he will use this function during `build/apply`.

therefore other remaining work would be migrate v1alpha1 to v1beta1.  I'll write a simple script to do this (basically use the function I mentioned above for transformation).  I might need help for verification after this point.

**Comment by gabrielwen** [comment]
TODOS:
- [ ] Migrate all codes using v1alpha1 to v1beta1.
- [ ] A simple CLI to transform KfDef v1alpha1 to v1beta1.
- [ ] Update all KfDef config files on master to v1beta1.

**Comment by jlewi** [comment]
@lluunn any update on this?

**Comment by gabrielwen** [comment]
@lluunn is updating gcp to use `KfConfig`

@Jeffwan could you also do the same thing for AWS?  starting at this point we should change to KfConfig:
https://github.com/kubeflow/kubeflow/blob/2395c5fc0d384cf6dd4d7167bbe9010cd1315b54/bootstrap/pkg/kfapp/coordinator/coordinator.go#L119

**Comment by gabrielwen** [comment]
@yanniszark could you help on updating existing_arrikto for using `KfConfig`?  it should start at this point and convert `KfDef` to `KfConfig`:
https://github.com/kubeflow/kubeflow/blob/2395c5fc0d384cf6dd4d7167bbe9010cd1315b54/bootstrap/pkg/kfapp/coordinator/coordinator.go#L117

**Comment by lluunn** [comment]
I ran into an issue:
kfdef has a method, WriteToConfigFile, that writes the updated kfdef back to disk (app.yaml).
To support this method in kfconfig, we need to convert kfconfig to kfdef. But then there is a cycle import: converter --> kfconfig --> converter.

Any suggestion?

@kunmingg proposed we should try to avoid writing back kfdef.

**Comment by lluunn** [comment]
discussed offline.
We should move converter logic into kfconfig.
kfconfig can read from kfdef, and write to kfdef.

**Comment by yanniszark** [comment]
@gabrielwen sure!
Does GCP use KfConfig? I'm asking because I'd love to have a reference implementation to follow.
Btw, why leave do we leave it up to the platform to convert the KfDef and don't just pass a KfConfig?

In addition, I should point out something that occurred to me recently.
Kubernetes' conversion makes a hypothesis that it's possible to convert from one version to any other in a lossless manner.
This is not true for KfDef.
eg a v1beta1 config with multiple plugins doesn't have a corresponding v1alpha1 KfDef.

**Comment by gabrielwen** [comment]
@yanniszark @Jeffwan we are adding some missing fields/functions to KfConfig.  It should be done today/tomorrow and after that we should only need an one line change.

@yanniszark could you explain more about information loss?  doesn't v1alpha1 KfDef also have a list of plugins?
https://github.com/kubeflow/kubeflow/blob/2395c5fc0d384cf6dd4d7167bbe9010cd1315b54/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L73

**Comment by yanniszark** [comment]
> @yanniszark could you explain more about information loss? doesn't v1alpha1 KfDef also have a list of plugins?

I thought Plugins was only part of the v1beta1 spec.
Seems like I was mistaken.
Was the field added to maintain backwards compatibility?

**Comment by abhi-g** [comment]
Can we close this issue @jlewi @gabrielwen or still work remaining>

**Comment by gabrielwen** [comment]
it's still WIP.

**Comment by gabrielwen** [comment]
Fixing minor bugs.  Currently known bugs:
- [ ] nil pointer reference in gcp.go when populating errors.
- [ ] ingress doesn't have backends set up.

**Comment by jlewi** [comment]
After kubeflow/manifests#565 I think we need to update the docs to point to 0.7.0 files

**Comment by gabrielwen** [comment]
> After [kubeflow/manifests#565](https://github.com/kubeflow/manifests/pull/565) I think we need to update the docs to point to 0.7.0 files

I've already updated the doc yesterday (GCP part).

**Comment by jlewi** [comment]
Looks like the docs might already be uptodate
https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

Is using

```
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws_cognito.0.7.0.yaml
"
```

GCP docs look good.

Looks like the Arrikto docs  aren't using the "0.7.0.yaml" file
https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

**Comment by jlewi** [comment]
@gabrielwen  looks like @sarahmaddox filed kubeflow/website#1224 to track doc updates.

Is there any additional work beyond docs or can we close this?

**Comment by gabrielwen** [comment]
@jlewi I think we can close this - @Jeffwan also verified that 0.7.0 works on AWS side.
