### ISSUE TITLE
kubeflow operators

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/kubeflow#3706]
Enable Kubeflow to be installed by operators to facilitate the management of those components.

@jlewi comments for this?

FYI @hougangliu @jinchihe

**Comment by jlewi** [comment]
@gyliu513 Can you elaborate on your thinking? We have kfctl which installs all of the applications. Do you think each individual application needs its own operator/controller?

**Comment by gyliu513** [comment]
@jlewi Yes, I actually hope that we can manage all components in Kubeflow via Operator, like Katib, kfserving etc.

**Comment by hougangliu** [comment]
for now we install Kubeflow by kfctl, and kubeflow operator here aims to introduce `Kubeflow` CRD and create a kubeflow cluster once user create a `Kubeflow` CR (it specifies which components with specified attributes will be installed).

But now AFAIK, for some kubeflow components (saying katib), it doesn't support to monitor specified namespace CR (if all monitors same CR, they all try to Reconcile it), we need make these components monitor namespaced scope CR first. Then we need think more about CRD conflict issue(saying multiple `Kubeflow` CR will make some CRD shared (maybe have different version) by multiple Kubeflow cluster)

**Comment by kkasravi** [comment]
the granularity of operators could be by application CR - where we have one per kubeflow 'component' see #3703 - we currently deploy an application-controller which looks for application CRs, however this could be expanded considerably as suggested here

**Comment by gyliu513** [comment]
@hougangliu can we add labels to CR so that the operator only monitor CRs with specified labels but not namespaces? Also for your case of CRD conflict, yes, it is a question, but for now, I think we can take this as low priority, we can have the assumption that the end user will not install multiple Kubeflow in one Kubernetes cluster.

@kkasravi good idea, we can leverage the `application CR` and treat katib, kfserving etc as application, let's check how #3703 will go. ;-)

**Comment by gyliu513** [comment]
/reopen

I was thinking we can leverage the meta-operator for this https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/operator-framework/3AYitLcQ9Bg/teV_0dL0CAAJ

1) Convert all components in Kubeflow to operators
2) Create an overall kubeflow operator to manage all of the sub operators in Kubeflow, like kfserving, pipeline etc.

FYI @jlewi @animeshsingh @hougangliu @jinchihe

**Comment by gyliu513** [comment]
This project https://github.com/IBM/operand-deployment-lifecycle-manager can help to install kubeflow operators.

**Comment by jlewi** [comment]
Thanks @gyliu513 Could we clarify the scope of this issue so we can determine when its complete? I know work has begun on a kubeflow operator. 

Perhaps we should think about opening up a Kanban board to track that work and figure out what we will deliver in Kubeflow 1.1?

/cc @animeshsingh
