### ISSUE TITLE
[kfctl] Need a way to inject plugins to kfctl workflows

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3708]
Currently we define workflows for all steps (init/generate/apply) to be `<platform>() -> k8s()`.  Say if we need to run something after `k8s()` or in the middle of platform and k8s, we need to manually hack it.  We should make the app structure flexible such that it's easy to add new step to workflows.

**Comment by yanniszark** [comment]
@jlewi maybe this is something we can address with the new plugin design of kfctl.

**Comment by jlewi** [comment]
An idea discussed before see: #3566 was to update the controller to have K8s controller like semantics.
In particular we would have a reconcile function that would be called multiple times until the deployment reached some terminal state.

KfDef.Status.Conditions would then be used to track state information that affected what operations were performed on each invocation of reconcile.

**Comment by jlewi** [comment]
#3709 for kfctl design doc.
