### ISSUE TITLE
Kfctl Design Doc for v1beta1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3709]
We need an updated design doc for kfctl.

Here are some key features we should capture

1. Adopting K8s controller reconcile semantics (see #3566)
1. Extensibility model i.e. plugin support
1. Proposal for KfDef v1beta1
1. What the desired CLI semantics are (see #3518)
1. Some discussion about code location and organization
    * There had been some discussion about moving it to its own repo

One of the key motivations is to focus on what we need to get kfctl and KfDef 1.0 in the Q4 release.

That means we'd like to have a v1beta1 KfDef in 0.7

**Comment by jlewi** [comment]
@kkasravi @yanniszark either of you interested?

**Comment by kkasravi** [comment]
I would be more than happy to contribute to the design doc, including moving to kustomize 3.X+, removing v2.zip, and any other issues I've been involved in.

**Comment by yanniszark** [comment]
I'd love to contribute to this.
I'm very excited by the work done so far in kfctl. :smile:

**Comment by jlewi** [comment]
@yanniszark Do you want to start a doc?

**Comment by yanniszark** [comment]
@jlewi sure, I will start one in the Kubeflow Drive.

**Comment by jlewi** [comment]
@yanniszark Any update on this?

**Comment by yanniszark** [comment]
I am coming back from PTO this week.
A draft should be out very soon, most likely by the end of this week.

**Comment by kkasravi** [comment]
>copied over from https://github.com/kubeflow/kubeflow/pull/3783#discussion_r312686204
>from @jlewi
>Thanks for raising this @kkasravi ; I didn't realize we were exposing this as a new top level >command.

>@yanniszark @gabrielwen I'd really prefer not to introduce any more user visible changes (e.g. new command); so if we do need to go with a PostApply hook lets implement it so as not be user visible.

@jlewi - Clarification from me: PostApply is not a new command (there is no kfctl/cmd/postapply.go - but it's called from the apply command (kfctl/cmd/apply.go). An alternative would be to call it lower down the stack like - like from coordinator's apply.

**Comment by yanniszark** [comment]
The initial draft of the design doc is here:
https://docs.google.com/document/d/1kviNOdjoBPeoJ56KBvMKWq7SzrSN5rFUQoULK8muD-M/edit?usp=sharing

cc @jlewi @kkasravi

**Comment by kkasravi** [comment]
Thanks @yanniszark !

Did you want comments within the document?

**Comment by yanniszark** [comment]
@kkasravi I believe the standard procedure is to leave comments on the doc, right?
@jlewi can help move this to the kubeflow drive, as I don't have access to that.

Let me also give you and @jlewi edit access.

**Comment by jlewi** [comment]
I think we can get rid of  repos.root I think we already have code to try to deal with the weird sub directories github adds
https://github.com/kubeflow/kubeflow/blob/337fdd0dbcde92d20eb270d4c123bec98ffd2ebc/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L460

**Comment by jlewi** [comment]
@yanniszark Any update on this? What are the remaining steps to finalize the design doc and begin implementation?

**Comment by yanniszark** [comment]
@jlewi design is tracked here: https://docs.google.com/document/d/1kviNOdjoBPeoJ56KBvMKWq7SzrSN5rFUQoULK8muD-M/edit?usp=sharing

Design is almost finalized.
The next implementation steps are:
1. New semantics to simplify kfctl usage.
2. Transition all current platforms to implement a plugin interface.
3. Implement the reconcile loop.

**Comment by jlewi** [comment]
@yanniszark Any update on the design doc? Are there any remaining issues we need to close out?

**Comment by jlewi** [comment]
I skimmed the doc again; here's my suggestion

1. I think there are 2 main improvements that we want to get LGTM'd and implemented in 0.7 and graduate to 1.0 in Q4
    1. The new simplified CLI semantics
    1. The reconcile implementation to enable plugins to perform order dependent steps (e.g. creation of default profiles, ingress/auth setup etc...)
1. We should call out the above two things and get explicit LGTM from an appropriate set of reviewers;
     1. Is @kkasravi and @jlewi sufficient? 
1. Anything not directly in scope for 0.7; i.e. related to the above 2; lets move to a section future directions; i.e.
    1. Any new kfctl sub commands (e.g. doctor, ls, etc...)
    1. GitOps
1. Lets try to resolve open comment threads 
    1. If the discussion/issue is resolved lets make sure the text captures any relevant decisions/outcomes and mark the thread resolved
    1. If there are open questions/issues lets create an Appendix and summarize the ongoing issue discussion for future resolution.

**Comment by yanniszark** [comment]
@jlewi sounds good to me.
Can you also please move the kfctl design doc to the Kubeflow google drive, so that it's accessible from the same place as the other docs?

**Comment by jlewi** [comment]
@yanniszark I don't seem to have permission to move it the team drive. Can you make jlewi@kubeflow.org an owner?

**Comment by jlewi** [comment]
@yanniszark Any update on this?

**Comment by yanniszark** [comment]
I think the design doc is now complete, as well as the implementation.
The only thing that is maybe remaining is to put it in the public Kubeflow drive.
@jlewi can you make a copy and include it?

**Comment by jlewi** [comment]
kubeflow/community#308 to setup a process for moving design docs into the shared g-drive.

**Comment by jlewi** [comment]
I've created a copy of this doc owned in the kubeflow.org drive
http://bit.ly/kfctl_design_public
