### ISSUE TITLE
Trigger rebuild of TF serving image in E2E test only when files change

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#371]
Building the TFServing image is expensive; particularly for GPU images.

It doesn't make sense to rebuild the TF Serving image for each presubmit. We should only rebuild it if certain files (like the Dockerfile are changed).

#301 is going to change our current tests so that we don't rebuild the docker image on each presubmit.

**Comment by lluunn** [comment]
we don't need this now that #1299
