### ISSUE TITLE
kfctl: support relative local repos in config

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3712]
We use `go-getter` to fetch repos defined in KfDef.
The `GetAny` method doesn't support relative local paths by default (for security reasons).
https://github.com/hashicorp/go-getter/blob/3279f7834bfada0785f23677629791ea1abb7475/client.go#L31

For `kfctl`, we may want to support these types of paths (eg `manifests` instead of `/home/yannis/go/src/github.com/kubeflow/manifests`).

This would also make the KfDef more portable.

cc @jlewi @kkasravi

**Comment by jlewi** [comment]
How would using relative local paths make it more portable? Aren't relative paths more likely to break if KfDef is moved to a different machine?

**Comment by yanniszark** [comment]
@jlewi 
Scenario: user commits every dependency for kfctl (manifests, kubeflow) in a repo.
The config file should be able to point to the local relative paths of the manifests, kubeflow folders.
Right now, the config file requires a full path.
This means that anyone who downloads the repo has to edit the config file with the full path to make it work.

**Comment by yanniszark** [comment]
@jlewi @gabrielwen any updates on this?
I have noticed some improvements in kfctl for relative URLs, do they also apply for the repos set in the KfDef?
From the reactions in my comment, it seems like a couple of users need this (we need this internally as well).

**Comment by jlewi** [comment]
If the files are in a repo then why wouldn't you point the repos in you KFDef at the Git repository; e.g.

```
  repos:
  - name: manifests
    uri: https://github.com/${ORG}/${REPO}/archive/${VERSION}.tar.gz
```

This assumes the directory structure is a mirror of kubeflow/manifests. If its not a mirror of the manifests and you have a different directory structure then you can modify the repoRef.path for every application to point to the appropriate location

e.g.

```
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: ${SOME}/${PATH}/${PREFIX}/pipeline/api-service
```

**Comment by yanniszark** [comment]
Closing as no longer relevant.
