### ISSUE TITLE
[kfctl] Clean up unstructured PodDefault content

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3713]
Clean it up in `ConfigPodDefault` after v2 dependency goes away.

**Comment by jlewi** [comment]
@gabrielwen Could you provide a link to the code or a little bit more explanation so that people less familiar with the code can understand this issue?

**Comment by gabrielwen** [comment]
mm, I kinda forgot what to clean up...

**Comment by gabrielwen** [comment]
/close
close for now.
