### ISSUE TITLE
Upgrade to mpi-operator 0.2.x

### ISSUE THREAD

**Issue by AndriiNeverov** [kubeflow/kubeflow#3715]
https://github.com/kubeflow/mpi-operator/tree/v0.2.1 has been released recently changing the CRD schema and even command-line options (e.g. --gpus-per-node has been removed)

**Comment by jlewi** [comment]
@AndriiNeverov Could you elaborate on the work needed? Does this entail upgrading the kustomize manifest to use the new operator?

Have we published docker images with the updated code?

/cc @johnugeorge @richardsliu

**Comment by AndriiNeverov** [comment]
@jlewi 

- MPI Job's CRD schema has changed significantly in v1alpha2 (see https://github.com/kubeflow/mpi-operator/blob/master/deploy/crd/crd-v1alpha2.yaml)
- CLI options have changed as well (e.g. kubeflow/mpi-job/mpi-operator.libsonnet still uses --gpus-per-node which is gone in https://github.com/kubeflow/mpi-operator/blob/master/cmd/mpi-operator.v1alpha2/app/options/options.go)
- The kustomize manifest doesn't exist yet (https://github.com/kubeflow/manifests/issues/227)
