### ISSUE TITLE
Establish a pattern for creating/using secrets used by multiple kubeflow prototypes

### ISSUE THREAD

**Issue by elsonrodriguez** [kubeflow/kubeflow#372]
https://github.com/kubeflow/kubeflow/pull/323 has secret handling semantics that may need to be forked out if more Kubeflow prototypes end up using those s3 credentials.

Consolidating such logic in a single place to avoid duplication is a good idea. Otherwise every other prototype will end up with very similar parameters for s3 or any other credentials/config that need to be added.

**Comment by jlewi** [comment]
I think the path forwarded is using pod presets or admission controllers. #782 created a prototype for doing that.

Closing this issue for that reason.
