### ISSUE TITLE
Are we still using k8s-model-server

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3720]
Is the code in
https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server

still being used? I think we were originally building TFServing images because TFServing wasn't publishing images.

I think there is also a proxy in there to do things like request response logging.

What functionality in this directory is being replaced by KFServing?

/cc @ellis-bigelow @lluunn @animeshsingh

**Comment by animeshsingh** [comment]
TFServing should be available via KFServing moving forward. We should phase this out IMHO
/cc @ellis-bigelow @jlewi

**Comment by jlewi** [comment]
Code deleted in #4338
