### ISSUE TITLE
notebook controller E2E tests

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3721]
See go/tf-operator-1-0 and #3654 

We need E2E tests for the notebook controller to cover core scenarios

**Comment by jlewi** [comment]
Anyone interested in picking this up?

I think a good place to start would be

1. Write a python script that would create a notebook resource and then verify that the notebook pod starts correctly

   * We can use the pytest module (like [kfctl_go_test.py](https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kfctl_go_test.py)). 
   
1. Integrate the above into an E2E Argo workflow

**Comment by jlewi** [comment]
@scottilee Any interest in picking this up?

**Comment by scottilee** [comment]
@jlewi It seems like I can reuse a lot of what's been done in https://github.com/kubeflow/examples/pull/633, specifically in `execute_notebook.py` and `job.yaml`, but instead launch it as a pod or deployment instead, is that correct?

And rather than kfctl_go_test.py it looks like (kf_is_ready_test.py)[https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py] would be a good example to use to test that the resource is created? Let me know what you think.

**Comment by jlewi** [comment]
@scottilee I think this test would be a bit different from kubeflow/examples#633. That test was verifying that we can run a particular notebook ipynb file successfully.

This test is intended to verify that a notebook controller properly starts a notebook.

So what you want to do is write a python script that does something like

1. Create a notebook resource like the following

```
kind: Notebook
metadata:
  creationTimestamp: 2019-09-12T04:35:52Z
  generation: 1
  labels:
    addgcpsecret: "true"
    app: xgboost-demo
  name: xgboost-demo
  namespace: jlewi-kf
  resourceVersion: "1041356"
  selfLink: /apis/kubeflow.org/v1alpha1/namespaces/jlewi-kf/notebooks/xgboost-demo
  uid: cd9f2891-d516-11e9-a836-42010a8e00aa
spec:
  template:
    spec:
      containers:
      - env: []
        image: gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0
        name: xgboost-demo
        resources:
          limits: {}
          requests:
            cpu: "4"
            memory: 1.0Gi
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace-xgboost-demo
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default-editor
      ttlSecondsAfterFinished: 300
      volumes:
      - name: workspace-xgboost-demo
        persistentVolumeClaim:
          claimName: workspace-xgboost-demo
      - emptyDir:
          medium: Memory
        name: dshm
```

1. Now verify that a statefulset is correctly created running the notebook

1. Verify that jupyter is actually running by sending a request to 

    ```
    https://${ENDPOINT}/notebook/${NAMESPACE}/${NOTEBOOK}/tree?
    ```

    * You can look at [endpoint_ready_test.py](https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/endpoint_ready_test.py) to get code  to send a request using IAP

My suggestion would be to create a python script that does just the first 2 steps first and get that checked in before trying to test the endpoint.

**Comment by jlewi** [comment]
@scottilee actually it looks like we already have a test.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/jupyter_test.py

@scottilee Apologies I'd totally forgotten about that. It looks like that test is still using ksonnet though to define the notebook resource. 

We should update that to get rid of ksonnet. I think we should just store the notebook resource in a YAML file and then modify it in python as needed.

That test will also likely need to be updated now that we are updating the notebook controller version.

**Comment by nrchakradhar** [comment]
@jlewi @scottilee Please let me know if I can help here. I need some guidance on what changes are needed and I can submit a PR.

**Comment by jlewi** [comment]
@nrchakradhar I think @scottilee already has a PR for this #4171 

@scottilee is there any additional work beyond #4171

**Comment by jlewi** [comment]
Looks like we need someone to pick up #4171 and drive it to completion.

**Comment by jlewi** [comment]
It looks like @gabrielwen updated the jupyter_test
https://github.com/kubeflow/kfctl/blob/10988786321357f45b620943f9ed9cc4714665d1/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py#L385

This is showing up in the test grid
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-kfctl

I'm marking this as fixed.
