### ISSUE TITLE
notebook controller should report metrics to prometheus

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3722]
The notebook controller should provide basic prometheus metrics such as

number notebooks created
number notebooks running

See #3654 and go/tf-operator-1-0 for guidance.

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/kubeflow/issues/3654#issuecomment-514038484

**Comment by yeya24** [comment]
I think this issue is already fixed by https://github.com/kubeflow/kubeflow/pull/4123 @jlewi

**Comment by jlewi** [comment]
Thanks @yeya24 is there a simple way to verify this? i.e. can we curl the prometheus endpoint for the controller to get a list of the metrics?

**Comment by yeya24** [comment]
@jlewi  You can curl the metrics endpoint exposed by the notebook controller.  For example, curl xxxx:8443/metrics | grep notebook

**Comment by jlewi** [comment]
@yeya24 thank you; any chance you could curl the endpoint for a 0.7 notebook controller and then just paste the output into this issue. This way we can verify that its been fixed in 0.7 and see what metrics are exposed.

**Comment by yeya24** [comment]
@jlewi  I am not sure whether 0.7.0 release includes this feature or not. But I build the master branch and it worked well

**Comment by jlewi** [comment]
@yeya24 Thanks; could you please past the curl output into this issue as verification that its been fixed?

**Comment by jlewi** [comment]
Bump to P0 because its a requirement for 1.0.

Before we close this issue out we should verify the output of the prometheus metric handler includes the metrics required for 1.0.

**Comment by jlewi** [comment]
Docker image

```
gcr.io/kubeflow-images-public/notebook-controller:vmaster-gb1400446
```

```
kubectl -n kubeflow port-forward notebook-controller-deployment-6f4bd994c8-w8669 8080:8080
curl http://localhost:8080/metrics
```

Returns the following output
[output.txt](https://github.com/kubeflow/kubeflow/files/4126507/output.txt)
