### ISSUE TITLE
notebook controller API reference docs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3723]
We need to publish API reference docs for the notebook controller as part of going beta and eventually 1.0.

See go/tf-operator-1-0

**Comment by jlewi** [comment]
Bump to P0 because its required for 1.0.

**Comment by zhenghuiwang** [comment]
Tried the same tool for generating TF1.0 ref doc, but failed. https://github.com/ahmetb/gen-crd-api-reference-docs/issues/12#issuecomment-573938275

**Comment by zhenghuiwang** [comment]
We can't auto gen docs following [this guide](https://github.com/kubeflow/website/tree/master/gen-api-reference) now. Summarizing the problems and a workaround:

**Problems**
1. The [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs) tool doesn't work well with go module. Specifically it doesn't recognize the `replace` statement in go module, such as

```
replace github.com/kubeflow/kubeflow/components/common => ../common
```

which is common in kubeflow/kubeflow.

2. Current version of kubernetes/gengo stops generating `doc.go`, which gen-crd-api-docs tool still relies on. (see more discussion at https://github.com/ahmetb/gen-crd-api-reference-docs/issues/15#issuecomment-575844836)

**Workaround**
1. Create a new Go package for your target CRD api package, e.g. (I created https://github.com/zhenghuiwang/nbctrler to clone kubeflow/components/notebook-controller)
2. Remove all `replace` statement in go.mod.

If your target `go.mod` doesn't have replace statement, you can skip step 1,2.

3. Manually create `doc.go` with these comments:
```
// Package v1 contains API Schema definitions for the kubeflow.org v1 API group
// +kubebuilder:object:generate=true
// +groupName=kubeflow.org
package v1
``` 
4. Download the gen-doc tool and run command like this to gen doc locally.
```
./gen-crd-api-reference-docs -config /Users/zhenghui/kubeflow/website/gen-api-reference/kubeflow-config.json -api-dir "github.com/zhenghuiwang/nbctrler/api/v1" -out-file tmp_notebook.md
```

/cc @richardsliu @kunmingg  @abhi-g

**Comment by abhi-g** [comment]
Thanks Zhenghui for finding a workaround!
