### ISSUE TITLE
Publish v0.6.0 binaries to the GitHub releases page

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3724]
Looks like we forgot to publish binaries to
https://github.com/kubeflow/kubeflow/releases

**Comment by jlewi** [comment]
I uploaded a linux version.

```
git checkout v0.6.0
cd bootstrap
make push-to-github-release
```

I had to manually run the command

```
github-release upload     --user kubeflow     --repo kubeflow     --tag v0.6.0     --name "kfctl_v0.6.0-0-g71aea0a9_linux.tar.gz"     --file bin/kfctl_v0.6.0-0-g71aea0a9_linux.tar.gz
```

* The Makefile ends up using the wrong tag because we use

```
$(shell git describe --tags --long))$(TAG)
```

So we include the commit in the version. I think including the commit in the version is a good thing; we should probably just fix the Makefile.

We also need to document that we should do it as part of the release process.

**Comment by jlewi** [comment]
We need to build a darwin version.

**Comment by Rohithzr** [comment]
how can I build this locally?

**Comment by kkasravi** [comment]
@Rohithzr `make build-kfctl` or `make install` (to copy to /usr/local/bin)

**Comment by kkasravi** [comment]
too big to upload - here is a link 
https://www.dropbox.com/s/g1p563kq1thzuoj/kfctl_v0.6.0-0-g71aea0a9_darwin.tar.gz?dl=0

**Comment by kunmingg** [comment]
darwin version updated
