### ISSUE TITLE
Cleanup TensorFlow Jupyter image Dockerfiles

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3725]
Can we cleanup and simplify how we build our TensorFlow docker images?
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile

In particular, 

* Can we use the published TF images as base images?
* Do we need to do any customization anymore?
   * Now that we support custom Jupyter images [docs](https://www.kubeflow.org/docs/notebooks/custom-notebook/) is it sufficient to specify the appropriate entrypoint in the Docker image?
* Can/should we avoid using conda?
* Do we need to support both python2 and python3 runtimes?
   * The reason we were supporting python2 was to support TFX libraries; I think we should create a separate jupyter image just for TFX.
* Can we drop support for older versions of TF? 

See #2358. I think @zabbasi  got stock TF images to work.

I think the goal of this issue should be to try to simplify our Jupyter images to the point where they are just 2 lines

```
FROM ...
ENTRYPOINT ...
```

**Comment by Tabrizian** [comment]
I can work on this issue.

**Comment by jlewi** [comment]
@Tabrizian How's this going?

**Comment by Tabrizian** [comment]
I created the initial PR and CCed you. 

Here is the PR: https://github.com/kubeflow/kubeflow/pull/4046

**Comment by jlewi** [comment]
After #4096 is merged, the jupyter images should be automatically built on postsubmit (hopefully).

We should be able to see the list of images built by going to the URL of one of the images e.g.

http://gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-gpu

Once the images are built we need to update the configmap in the jupyter manifest to list the new images.
https://github.com/kubeflow/manifests/blob/ffede944f18343271f526bd217cde2edbe6e0e38/jupyter/jupyter-web-app/base/config-map.yaml#L26

**Comment by jlewi** [comment]
Bump to P0 because I think we want to include the updated Jupyter images in 0.7.

**Comment by nrchakradhar** [comment]
> Once the images are built we need to update the configmap in the jupyter manifest to list the new images.
> https://github.com/kubeflow/manifests/blob/ffede944f18343271f526bd217cde2edbe6e0e38/jupyter/jupyter-web-app/base/config-map.yaml#L26

Can the build can automatically update this file?

**Comment by Tabrizian** [comment]
Is it required to tag the builds in gcr? I can update the manifest files if tag is not required.

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/kubeflow/issues/4144  I have some requirements related to this story. Please have a check

**Comment by nrchakradhar** [comment]
@jeffwan
https://github.com/kubeflow/kubeflow/pull/4046#discussion_r323847161
Please check the comment. As per this, custom image is the way forward I believe. We also have need to include multiple packages internal and external and have to rely on custom image only.

**Comment by Jeffwan** [comment]
@nrchakradhar Makes sense. We will move forward with custom images.

**Comment by jlewi** [comment]
I think https://github.com/kubeflow/kubeflow/pull/4046#discussion_r323847161
was specifically about conda.

I think its reasonable to include Cloud CLIs (e.g. gcloud / AWS CLI) in the stock jupyter images.

We've been installing the gcloud CLI in our jupyter images and I think we should continue to do so. By extension I think its fine to install AWS or other cloud CLIs.

I think if we reach a point where all the different Cloud tools lead to bloated images then I think we can split the images into separate images for the different clouds.

**Comment by jlewi** [comment]
> Is it required to tag the builds in GCR? I can update the manifest files if tag is not required.

Lets go ahead and update the manifests to the SHAs. We can do that as part of cutting the release.

Are we still installing gcloud in the images? If not can we add that back and then add the AWS CLI as well per @Jeffwan's request?

**Comment by jlewi** [comment]
It looks like we are installing gcloud here
https://github.com/kubeflow/kubeflow/blob/e38c6f3234b301f33226706c285aafb9bd32d357/components/tensorflow-notebook-image/Dockerfile#L85

So installing AWS CLI as well seems reasonable.

**Comment by Tabrizian** [comment]
I can do it.

**Comment by Tabrizian** [comment]
Pull request is #4207

**Comment by jlewi** [comment]
* kubeflow/manifests#401 got rolled back for unrelated reasons
* it is being rolled forward in kubeflow/manifests#438

@Tabrizian is there anything else to be done here or can we mark this fixed once kubeflow/manifests#438 is merged?

**Comment by Tabrizian** [comment]
@jlewi Glad that it was not from my PR. There are some minor things remaining (e.g. refactoring the user, and removing some libraries) I can improve them in a subsequent PR.
