### ISSUE TITLE
kfctl should support upgrading kubeflow deployments

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3727]
We'd like kfctl to begin providing some path for people to upgrade their Kubeflow deployments.

/cc @richardsliu

**Comment by kkasravi** [comment]
capturing some comments from Matt Brown that we should keep in mind 

```
how do I update the `.cache/manifests` folder that kfctl generates in the working directory over time, as the upstream repo changes?
```
```
is there any guide on how to modify kustomize resources in a way that won’t interfere with kfctl?
```
```
I was wondering if there was anything more advanced, for instance to not lose the modifications if i ever run `kfctl generate` again
```

**Comment by johnugeorge** [comment]
Some extra thoughts:

Can I upgrade few of components than the whole  KF deployment? 
What is the process of picking up of quick fixes that are made to component? Can I pick a different version of a particular component ?
Is kfctl deployment idempotent? Does it track versions of components?

**Comment by mattnworb** [comment]
To elaborate on @johnugeorge’s comment, a key use case I had in mind above would be to upgrade the kubeflow-pipelines (api, ui, etc) components.

**Comment by jlewi** [comment]
@richardsliu Do you want to add a link to your doc?

**Comment by jlewi** [comment]
@richardsliu any update on this? Do you have an ETA for when the initial PR will land in kfctl.

**Comment by jlewi** [comment]
@richardsliu any update on this?

* How's it going with kubeflow/kubeflow#4115?
* Are we blocked on fixes to kubeflow manifests to define missing Application CRs and give applications unique instance names?

**Comment by sarahmaddox** [comment]
@richardsliu @jlewi Is this landing in v0.7? If yes, we need to add a doc issue for it.

**Comment by jlewi** [comment]
@sarahmaddox we will likely "soft" launch it in 0.7; i.e. we will explicitly not document/advertise it until we know its working reliably and have worked out all the kinks.

**Comment by jlewi** [comment]
@richardsliu Could you provide an update please?

**Comment by richardsliu** [comment]
This should be done now. It's not going to be part of v0.7.1 but it should be working in the 1.0-rc.0 build (https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.0).

Documentation is here: https://www.kubeflow.org/docs/upgrading/upgrade/

**Comment by richardsliu** [comment]
Pending work: add an e2etest

**Comment by jlewi** [comment]
@richardsliu can we close this out?

**Comment by mattnworb** [comment]
thanks for all the work on this! excited to try out the alpha features mentioned in https://www.kubeflow.org/docs/upgrading/upgrade/

**Comment by jlewi** [comment]
@richardsliu ping can we close this out?

**Comment by richardsliu** [comment]
Yes. You will need to use the [v1.0 RC](https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.2) to experiment with this feature.

/close

**Comment by jbottum** [comment]
@richardsliu I was looking the docs for upgrading an existing cluster.   an initial step is to delete the existing cluster.   should we have a step to somehow save that cluster's config before deleting it?

**Comment by yantriks-edi-bice** [comment]
@richardsliu please see related #4724
