### ISSUE TITLE
minio-pv,mysql-pv bound but looking for gce-pd storage

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#3728]
`AttachVolume.NewAttacher failed for volume "minio-pv" : Failed to get GCE GCECloudProvider with error <nil>`

On-prem, all-in-one install using a fresh built kfctl (0.6-ish) using platform="minikube" and components="k8s". Obviously, no public cloud storage attached.

Shouldn't these just make use of a default StorageClass?

**Comment by yanniszark** [comment]
@pdmack I believe the config file for minikube are out-of-date.
It should be possible to deploy Kubeflow on Minikube using platform [`existing_arrikto`](https://master.kubeflow.org/docs/started/getting-started-k8s/#Kubeflow-for-Existing-Clusters---by-Arrikto).
Just make sure to have a LoadBalancer available, using the `minikube tunnel` command.

**Comment by pdmack** [comment]
Thanks @yanniszark but what do we mean by a LoadBalancer in this context and why would it be required?

**Comment by yanniszark** [comment]
@pdmack it is required to expose the Istio Gateway with standard ports.
I am working on lifting this requirement, but it exists for now.

**Comment by jlewi** [comment]
@pdmack @johnugeorge has a PR pending kubeflow/website#977 that will update the instructions for installing on an existing cluster.

https://deploy-preview-977--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-k8s/

I think those instructions should work with minikube and not require an LB.

@pdmack Can you provide links to the instructions/code etc... that you were following so we can file bugs to clean them up?

**Comment by pdmack** [comment]
Still there in the 0.6.2 kfctl
```
INFO[0007] creating PersistentVolume/minio-pv            filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from minio Error: persistentvolumes "minio-pv" is forbidden: error querying GCE PD volume dls-kf-storage-artifact-store: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: i/o timeout
```
```
export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml"
```
`kfctl apply k8s -V`

**Comment by pdmack** [comment]
Hmmm, got it working but had to be explicit about minikube in the init.

`./kfctl init 062-kubeflow --config=${CONFIG} -V -p minikube`
