### ISSUE TITLE
Page rendering broken for notebook page 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#3733]
If i leave the cluster for a while ( usually 4-5 days) and try to connect to the notebook page the rendering of the notebook page comes up broken. see screen shot: 

https://screenshot.googleplex.com/Byyqe4XTEve

![image](https://user-images.githubusercontent.com/20114005/61737240-a175b680-ad3c-11e9-9b55-a41e8f264813.png)

**Comment by prodonjs** [comment]
This seems like the same issue as https://github.com/kubeflow/pipelines/issues/908 and #2852. I don't think there's anything specific in the UI layer we can do to address it at this time but it does seem to be an error that occurs across all web surfaces in Kubeflow after the cluster remains idle for some period of time.

**Comment by jlewi** [comment]
@SinaChavoshi Are you using Kubeflow 0.5 or 0.6?

#2852 is the uber issue for upstream/disconnect errors.

The current recommendation is to upgrade to 0.6 and see if the error still occurs.

**Comment by avdaredevil** [comment]
Any updates on this?

/unassign @avdaredevil

**Comment by SinaChavoshi** [comment]
this was on 0.5 I'm verifying if it reproduces on 0.6. In the mean time I'll close this issue as the root cause is same as #2852, if it reproduces on 0.6 I will add to that thread.
