### ISSUE TITLE
[v0.6.0] source code building errors

### ISSUE THREAD

**Issue by xauthulei** [kubeflow/kubeflow#3736]
My steps : 
1>Download  kubeflow-0.6.0.zip , and unzip it.
2>Compiler 
`cd /Users/llhu/kubeflow_mac/kubeflow-0.6.0/bootstrap;make build-builder-container`
 **fatal: not a git repository (or any of the parent directories): .git**
docker build \
		--build-arg GOLANG_VERSION=1.12 \
		--target=builder \
		--tag gcr.io/kubeflow-images-public/kfctl: .
invalid argument "gcr.io/kubeflow-images-public/kfctl:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build-builder-container] Error 125

And I fond this in the `Makefile`
`/Users/llhu/kubeflow_mac/kubeflow-0.6.0/bootstrap;grep "git " Makefile`
`TAG ?= $(eval TAG := $(shell git describe --tags --long))$(TAG)`

I thought, we need to include/add the `.git` dir to release source.

**Comment by jlewi** [comment]
The command to build kfctl is

```
make build-kfctl
```

**Comment by xauthulei** [comment]
Thanks @jlewi ,However, there still other errors likes :
go: verifying github.com/hashicorp/go-getter@v1.0.2: checksum mismatch
	downloaded: h1:gw2LPsqe+ri9lYBKUtpzdNgE8RzPuJ67ORTp35owxdQ=
	go.sum:     h1:ba+UwCRuxJ7+rS+cO6JnQZUrweQjmEAkwKu9r7+HCpM=
make: *** [generate] Error 1

**Comment by yanniszark** [comment]
Hi @jlewi @xauthulei.
Could you try building with `build-kfctl-container` to build `kfctl` in a container?
It is much more reproducible and will eliminate any host-specific bugs.

**Comment by xauthulei** [comment]
@yanniszark , Thanks for your quickly response. Yea, I also got this error:
/Users/llhu/kubeflow_mac/kubeflow-0.6.0/bootstrap
huleis-mbp:bootstrap llhu$ make build-kfctl-container
**fatal: No names found, cannot describe anything.**
DOCKER_BUILDKIT=1 docker build \
		--build-arg GOLANG_VERSION=1.12 \
		--build-arg VERSION= \
		--target=kfctl \
		--tag gcr.io/kubeflow-images-public/kfctl/builder: .
invalid argument "gcr.io/kubeflow-images-public/kfctl/builder:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build-kfctl-container] Error 125

That is why we need to included the `.git` to the source liking my initial errors .

**Comment by yanniszark** [comment]
@xauthulei I believe this error occurs because we use the git hash to generate the image tag.
Maybe we should give it a good default.

**Comment by discordianfish** [comment]
Would be great to document how to build this as close as the release deploys as possible.

@xauthulei I would suggest you checkout the repo via git and try again.

**Comment by xauthulei** [comment]
Thanks for your good suggestions @discordianfish @yanniszark . I am prefer to give it a good default.
