### ISSUE TITLE
Create a GitHub issue template for bugs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3738]
We should create an issue template for users asking for help.

We should ask people for information such as

* What kfctl commands did they run
* What is the output of `kfctl version`
* What their kubernetes platform is

**Comment by jlewi** [comment]
We can start with what fairing does
https://github.com/kubeflow/fairing/tree/master/.github

**Comment by yeya24** [comment]
I' d like to work on this.
