### ISSUE TITLE
Enhancements to existing_arrikto.yaml

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3739]
Opening this issue to figure out what improvements we'd like to make to
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_existing_arrikto.0.6.yaml

* Can we create kustomize packages for ISTIO and DEX  so we can treat them like every other application?
  * Right now they are installed from YAML files
    https://github.com/kubeflow/kubeflow/tree/master/deployment/existing

Do we need a plugin (i.e. go code in kfctl) or could we do the entire setup just by creating K8s resources?

IIUC one of the issues is that we need to know the external IP in order to generate certificates?
https://github.com/kubeflow/kubeflow/blob/ed40c4fab3e96f79fbf674d836dedf8878104021/bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go#L291

But what if we just ran that code say as a K8s job? Could that job just wait for the IP to become available and when it does generate the self-signed certificate. At which point the ISTIO gateway  would finish setting up because the certificate exists?

/cc @yanniszark 
/cc @johnugeorge

**Comment by johnugeorge** [comment]
Thanks @jlewi for tracking this. 

> Opening this issue to figure out what improvements we'd like to make to
> https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_existing_arrikto.0.6.yaml
> 
> * Can we create kustomize packages for ISTIO and DEX  so we can treat them like every other application?

I completely agree with composable architecture.  This should be right direction where users should be able to select the components based on their needs.  DEX/OIDC Kustomize packages are being added in manifests https://github.com/kubeflow/manifests/pull/195 

/cc @krishnadurai

**Comment by illeatmyhat** [comment]
It'd be nice if we were able to configure the storage settings for each component, i.e. ephemeral vs PV, the storage request size

**Comment by jlewi** [comment]
I think one question that came up in the context of kubeflow/website#977 is what is the future of 
`existing_arrikto.yaml`

Will existing_arrikto.yaml evolve as one of the vendor neutral solutions that we as a community want to support? e.g. some supported configuration like installing ISTIO and Dex

or 

Will existing_arrikto.yaml evolve to track Arrikto's opinions

/cc @yanniszark @vkoukis

**Comment by yanniszark** [comment]
Update:
There seems to be a community agreement that Kubeflow needs a config in the lines of
existing_arrikto, for installing on on-prem clusters.
Since our intention was for it to be a community config from the start, we refactor it into a community-supported config.
More info: https://github.com/kubeflow/manifests/issues/599

This makes this issue obsolete.
/close
