### ISSUE TITLE
Update GKE API to v1. 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3746]
Our [config](https://github.com/kubeflow/kubeflow/tree/master/deployment/gke/deployment_manager_configs) are currently on [GKE API v1beta1](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters).
We should update version to [v1](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#top_of_page)

**Comment by kunmingg** [comment]
Thanks @IronPan

**Comment by jlewi** [comment]
I think we have used the GKE API v1beta1 API because certain features that we wanted to enable (e.g. StackDriver logging) were still in beta and not available in the v1 API yet.

So we'll need to check to see whether all of the settings we currently use are available via the V1 API.
