### ISSUE TITLE
uninstalling kubeflow failing

### ISSUE THREAD

**Issue by asispatra** [kubeflow/kubeflow#3749]
```
$ kfctl delete all
INFO[0000] deleting kubeflow application                 filename="cmd/delete.go:35"
ERRO[0000] could not delete compositecontrollers.metacontroller.k8s.io Error customresourcedefinitions.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" not found  filename="ksonnet/ksonnet.go:269"
ERRO[0000] could not delete controllerrevisions.metacontroller.k8s.io Error customresourcedefinitions.apiextensions.k8s.io "controllerrevisions.metacontroller.k8s.io" not found  filename="ksonnet/ksonnet.go:269"
ERRO[0000] could not delete decoratorcontrollers.metacontroller.k8s.io Error customresourcedefinitions.apiextensions.k8s.io "decoratorcontrollers.metacontroller.k8s.io" not found  filename="ksonnet/ksonnet.go:269"
ERRO[0000] could not delete applications.app.k8s.io Error customresourcedefinitions.apiextensions.k8s.io "applications.app.k8s.io" not found  filename="ksonnet/ksonnet.go:269"
ERRO[0000] could not delete meta-controller-cluster-role-binding Error clusterrolebindings.rbac.authorization.k8s.io "meta-controller-cluster-role-binding" not found  filename="ksonnet/ksonnet.go:283"
Error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for ksonnet:  (kubeflow.error): Code 400 with message: couldn't delete namespace kubeflow Error: Operation cannot be fulfilled on namespaces "kubeflow": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
Usage:
  kfctl delete [all(=default)|k8s|platform] [flags]

Flags:
      --delete_storage   Set if you want to delete app's storage cluster used for mlpipeline.
  -h, --help             help for delete
  -V, --verbose          verbose output default is false

couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for ksonnet:  (kubeflow.error): Code 400 with message: couldn't delete namespace kubeflow Error: Operation cannot be fulfilled on namespaces "kubeflow": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
$
```

**Comment by InCogNiTo124** [comment]
Duplicate of #3646?

**Comment by asispatra** [comment]
@InCogNiTo124 This is not the same issue.

**Comment by jlewi** [comment]
I think the problem is kfctl is not properly handling the fact that deleting the namespace will return an error if K8s is currently trying to delete the objects in the namespace

```
couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for ksonnet:  (kubeflow.error): Code 400 with message: couldn't delete namespace kubeflow Error: Operation cannot be fulfilled on namespaces "kubeflow": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
```

We probably need to fix the kfctl logic to properly handle this better.

The original issue was reporting a problem with kfctl 0.5. since it was using ksonnet. I suspect the problem exists in 0.6 as well and we should try to fix as part of the 0.7 release or sooner if possible.

/cc @yanniszark @kkasravi

**Comment by jlewi** [comment]
We should probably update the test as well to verify it works as intended
https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kfctl_delete_test.py

**Comment by yanniszark** [comment]
@jlewi @kkasravi
How should we handle this?
Some thoughts are:
1. Wait for Kubeflow namespace to be deleted before proceeding with Resource deletion.
2. Check the error and catch the specific scenario. Not sure how we would do this other than checking for the error message inside the error, which seems brittle.

**Comment by kkasravi** [comment]
hi @yanniszark - welcome back!

2 approaches that I can think of:

1. use labels - similar to what we did in 0.5.
The reason why we're breaking now is we have many applications and we no longer have a global label. We need to create [instance](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) labels per application and could delete all resources which carry the same app.kubernetes.io/part-of label. This would include istio namespace and profile namespaces.

2. the application-controller will insert [owner-refs](https://github.com/kubernetes-sigs/application/blob/master/pkg/genericreconciler/genericreconciler.go#L124) of resources it thinks it owns. This isn't comprehensive right now but would allow easier cascaded deletes if the ApplicationCR is deleted. 

I think we need to (as Jeremy suggests) - have an e2e test for this. I've been working on e2e so I hope to have something this week for this.

**Comment by jlewi** [comment]
Closing as obsolete/stale

**Comment by Lordfourteen** [comment]
I try to uninstall kubeflow via `kfctl delete -f ${CONFIG_URI}` after getting a lot of ImagePullBackOff pod in kubeflow namespace, then I get an error below:

NAME              STATUS        AGE
cert-manager      Active        20h
default           Active        115d
ingress-nginx     Active        80d
istio-system      Active        20h
knative-serving   Active        19h
kube-node-lease   Active        115d
kube-public       Active        115d
kube-system       Active        115d
kubeflow          Terminating   20h

How can i fix it or remove the kubeflow namespace?

**Comment by eedorenko** [comment]
The problem is still there kfctl v1.0.1-0-gf3edb9b
