### ISSUE TITLE
Jupyter notebook image should pin TF version

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#375]
The latest image for jupyter notebook uses tensorflow 1.5-dev version and the TFServing image uses tensorflow 1.4 release.

I ran into an issue where I trained a model using the jupyter notebook, but had compatibility issues while serving that model with TFServing.

We should try to maintain the same tensorflow versions in the various kubeflow images.

**Comment by jlewi** [comment]
Our notebooks are currently using the nightly build of TF.
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile.cpu#L162

We should probably pin TF to a specific version. 

/cc @ojarjur

**Comment by jlewi** [comment]
We should pin the version of TF in our notebook images.
We should also consider including the TF version in the image name so that we could potentially build images for different versions of TF.

**Comment by aronchick** [comment]
Pinning is great, but i wonder how we make this an easily option - we've
seen lots of issues with various versions of frameworks not supporting
particular models, and i want people to be able to swap readily.

**Comment by jlewi** [comment]
Agree. For notebook images we can build different notebook images for different TF versions.

Thanks to @ojarjur's changes to the Dockerfile, its already parameterized by the TF version. And thanks to work by @pdmack we can have a drop down box in the Jupyter UI from which users can select the appropriate image to use. So we could have images for different TF versions.
