### ISSUE TITLE
Deploying notebooks on 0.6 fails

### ISSUE THREAD

**Issue by rajesh-chawla** [kubeflow/kubeflow#3752]
I’m working to deploy notebooks using 0.6, but not able to. When I attempt to create a new notebook, I see the error below in the notebook-controller-deployment pod.

{“level”:“info”,“ts”:1564071153.570385,“logger”:“controller”,“msg”:“Updating StatefulSet”,“namespace”:“kubeflow”,“name”:“rc1”}
{“level”:“info”,“ts”:1564071153.6148093,“logger”:“controller”,“msg”:“Pod not found...“} (edited)

From Slack, @Nihir suggested a workaround by re-building and changing the serviceaccount.

My question is: Is this a reasonable workaround ?

**Comment by jlewi** [comment]
Could you please take a look at kubeflow/website#935 and include the relevant information?

**Comment by rajesh-chawla** [comment]
I attempted to create a notebook called 'test1'. Following the suggestions above, I executed the command: 

`kubectl describe statefulsets test1`

shows the following error:

    Type     Reason        Age                     From                    Message
    ----     ------        ----                    ----                    -------
    Warning  FailedCreate  2m19s (x26 over 7m39s)  statefulset-controller  create Pod test1-0 in StatefulSet test1 failed error: pods "test1-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found

Note -- on slack, the user Nihir had suggested changing default-editor in the code to juptyer-web-app-service-account in components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py and recompiling kfctl. Unfortunately, this did not work for me.

**Comment by rajesh-chawla** [comment]
I can create a notebook successfully after I create a service account named 'default-editor' clusteradmin rights.
