### ISSUE TITLE
darwin verison on `v0.6.1-rc.1` doesnt work.

### ISSUE THREAD

**Issue by Rohithzr** [kubeflow/kubeflow#3755]
I tried`v0.6.1-rc.1` darwin release binary but gives me `exec format error: kfctl` error

**Comment by zhenghuiwang** [comment]
Uploaded a new binary to the release page. It should work now.

Please reopen this or file new issue if it doesn't work for you.

/close

**Comment by zhenghuiwang** [comment]
@DivineOps  I verified I can download and run kfctl darwin binary on Mac via https://github.com/kubeflow/kubeflow/releases/tag/v0.6.2

Can you add more information on how to reproduce your problem?
