### ISSUE TITLE
[v0.6.0] how to get yaml file of entire kubeflow app

### ISSUE THREAD

**Issue by TaylorHere** [kubeflow/kubeflow#3757]
We still using yaml files to deploy our app, in v0.5.0 we use 'ks show' to get yaml files
but in v0.6.0, 'ks show' didn't work, it says:
```
ERROR initializing app: reading app configuration: error unmarshaling JSON: parsing semver: kfdef.apps.kubeflow.org/v1alpha1: Invalid character(s) found in major number "kfdef"
```
and 'fctl show' didn't work as well, it says:
```
Error: couldn't show KfApp:  (kubeflow.error): Code 500 with message:  not in Platforms
```

**Comment by jlewi** [comment]
After running `kfctl generate`

All of the kustomize packages should be in ${KFAPP}/kustomize

For each of those applications you can run `kustomize build` to generate the YAML


Relevant code
https://github.com/kubeflow/kubeflow/blob/e12958a577ce376aa69d7a5f71292f5f1f8a40f6/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L625

**Comment by TaylorHere** [comment]
hi, that's great to hear this is a way to get YAML
another question is where I can find kustomize bin file, or need I build it by myself?
