### ISSUE TITLE
kfctl apply failes with No Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by Kyrremann** [kubeflow/kubeflow#3759]
I'm trying to apply Kubeflow `v.0.6.0` in our cluster, and it failes with the following error:

```
$ kfctl apply all -V
INFO[0000] Downloading /home/user/workspace/kubeflow/app.yaml to /tmp/455975017/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /home/user/workspace/kubeflow/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /home/user/workspace/kubeflow/app.yaml to /tmp/812831412/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Initializing a default restConfig for Kubernetes  filename="kustomize/kustomize.go:248"
FATA[0000] Can not get kubernetes kfdef: No Auth Provider found for name "azure"  filename="apps/group.go:262"
```

We use Azure/AD to connect/login to the cluster, and if I create a user that authenticates with a token instead (of my regular user) it all works. 

I assume the problem is that `kfctl` is missing support for azure as an `oidc` flow. 

There has been a short disuccion on [slack](https://kubeflow.slack.com/archives/C7REE0EHK/p1564132253111500).

**Comment by yanniszark** [comment]
@jlewi @kkasravi 
I suspect the issue is that the client we use for kfctl doesn't support the OIDC flow.
How do we want to handle situations like this?

**Comment by jlewi** [comment]
/assign @kkasravi 
/assign @gabrielwen 

Could one of you take a look please?

**Comment by kkasravi** [comment]
Documentation says to use k8s not all
‘kfctl apply k8s’

**Comment by jlewi** [comment]
It looks like this is coming from here:
https://github.com/kubeflow/kubeflow/blob/32b74431a72ce4064b727111a92de3ec42a172b3/bootstrap/v2/pkg/apis/apps/group.go#L262

If I understand @Kyrremann's comment the various auth modules in the K8s go client are plugins
and need to be explicitly importing.
I think its this module
https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth

@Kyrremann Any interest in trying to add a PR to do that?

@aronchick Anyone on the Azure side who could pick this up and test it out?

**Comment by Kyrremann** [comment]
@kkasravi isn't that for what type of resources your supposed to generate? Also, maybe the example in the documentation should be updated if your not supposed to use `all` when applying to vanilla kubernetes cluster?

**Comment by Kyrremann** [comment]
@jlewi I can try to take a look!

**Comment by Kyrremann** [comment]
Okay, after a bit of googling, and looking at some other code we have, the solution should be pretty straightforward.
https://github.com/liggitt/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/README.md#auth-plugins

But, I can't get it to work with `kfctl`, and I'm wondering if I'm building the tool wrong.

This is what I've done:
1. Added the import-line to `kubeflow/bootstrap/pkg/apis/apps/group.go`
2. `make build-kfctl`
3. `./kfctl init/generate/apply`
4. No success

**Comment by jlewi** [comment]
That is the right way to build it. Not sure why it didn't work.

**Comment by yeya24** [comment]
I think I can help with this.

**Comment by Kyrremann** [comment]
Should we get #3881 merged?

**Comment by yanniszark** [comment]
@kkasravi does the new apply logic (which uses kubectl) also fix this problem?
Or do we need to add blank imports at certain locations in the code?

**Comment by Kyrremann** [comment]
If a new version of `kfctl` rely on the users `kubectl` I think the problem will be solved by it self.

**Comment by Lijo050** [comment]
Hi, @yeya24 After modifying the code which you suggested, I'm getting the issue
```
# k8s.io/client-go/plugin/pkg/client/auth/azure
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)
```

**Comment by yeya24** [comment]
> Hi, @yeya24 After modifying the code which you suggested, I'm getting the issue during
> **make build-kfctl**
> 
> ```
> # k8s.io/client-go/plugin/pkg/client/auth/azure
> ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
> ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
> ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
> ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)
> ```

Sorry, I have encountered this issue once. This is because your client-go version is too old. Ref:  https://github.com/pingcap/tidb-operator/pull/756#issuecomment-520759888

**Comment by Lijo050** [comment]
> > Hi, @yeya24 After modifying the code which you suggested, I'm getting the issue during
> > **make build-kfctl**
> > ```
> > # k8s.io/client-go/plugin/pkg/client/auth/azure
> > ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
> > ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
> > ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
> > ../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)
> > ```
> 
> Sorry, I have encountered this issue once. This is because your client-go version is too old. Ref: [pingcap/tidb-operator#756 (comment)](https://github.com/pingcap/tidb-operator/pull/756#issuecomment-520759888)

Oh thanks, @yeya24 but how should I update the client-go as the client-go@v0.0.0-20190228174230-b40b2a5939e4 is automatically being generated. Sorry, I'm pretty new here.

**Comment by Lijo050** [comment]
Also @yeya24 I don't think its the same issue because the last line of the error is not same
`../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)`

`../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment`
