### ISSUE TITLE
[Discussion] Patterns for creating ksonnet prototypes?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#376]
For many prototypes like TFServing we might want to allow complex modifications

Example
   * Users might want to customize resource foot print of HttpProxy and/or TFServing
   * Users might want to attach secrets or volumes
   * Users might need to set multiple environment variables 
   * See #323 for example

Creating parameters for each flag won't scale. We need to structure our ksonnet prototypes to make it easier to override the parts people care about. Furthermore, this will probably require users modifying the component jsonnet files directly as opposed to just overriding paramters.

As an example if a user wants to override the resources for TFServing it would be nice if they could just supply a dictionary.

It would be useful to look at the ksonnet/parts registry for examples/motivation.

**Comment by jlewi** [comment]
One issue is what to do about default parameter values for optional parameters.

As an example consider the default docker image to use for TFServing. The correct default image to use depends on whether the user is using CPU or GPU.

Option 1: Have two parameters "mode_server_cpu_image", "model_server_gpu_image"
Option 2: Have a single parameter "model_server_image" and set the value in GCL depending on GPUs.
Option 3: Don't define parameters in the prototype. Instead we can define a maps of defaultParams in the .libsonnet file and then override it with whatever parameters are set for the component/environment.

e.g. in tfserving.libsonnet
```
{
  parts:: {
      defaultParams:: {
          model_image:: ...
          ....
      }

     modelServer(overrides={}) :: {
         local params = defaultParams + overrides;
     }
```

I like option 2 much better but there are some drawbacks.

Until ksonnet/ksonnet#273 is fixed we need to set the default to some magic string like "null" and use that to detect when the value is default.

The other draw back is that the default parameter values won't show up when user does `ks param list`

I think the drawback of option 3 is that we don't have the benefit of the help strings encoded in the prototype.

**Comment by jlewi** [comment]
Thinking about this more and based on
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md

I think there are a class of components specifically

TfJob
Argo Workflows
TFServing images
Seldon models
TensorBoard jobs

Where I think it might make more sense to for an existing template/example and then let users modify it. I think this ultimately leads to more readable config than doing complicated things like overriding environment variables and requests limit.

We can support this by using ksonnet prototypes. When we generate a component from a prototype ksonnet copies that prototype into components directory.

So if our prototype defines a complete manifest (as opposed to relying on imports) then ks generate gives users an example which they can then easily customize for their use case.

So for models and jobs I think we should add more prototypes to cover more use cases and rely less on imported templates.

We should also investigate the use of AdmissionControllers and PodPresets (#732)

/cc @lluunn @elsonrodriguez

**Comment by ankushagarwal** [comment]
I mostly agree with the discussion above. 

The way I see it is we have two classes of components:

* **Kubeflow Contoller Components** - These are the _pluggable_ components which provide Kubeflow services - JupyterHub, Ambassador (CRD), IAP (With cert manager and issuer CRDs), Envoy, Argo CRD, TFJob CRD, Seldon CRD, Pachyderm Backend, Spartakus, GPU Driver Daemonset. Instead of having an _core_ component, we should let users decide which components they want to use. Users are not expected to customize these components a lot - we will provide reasonable parameters for each component which allow for some customization.

* **Kubeflow Jobs Components** - These are services / jobs which users can create. Examples - a TFServing Deployment, a TFJob Training Job, a Pachyderm pipeline, a Seldon Serving Job. Users are expected to create these manually and heavily customize these based on their requirements. For these Components, we should provide an exhaustive set of examples of out of the box components which contain full job specs. As mentioned in the discussion above - it's going to be hard to parametrize these components.


Right now we have too many packages in the kubeflow registry - `argo, core, openmpi, pachyderm, pytorch-job, seldon, tf-job, tf-serving`. I propose that we have only two packages in the kubeflow registry - `kubeflow` and `examples` and move/refactor components from all these packages into these two packages.

Here is how I envision our component organization should look like. A `kubeflow` package with pluggable components which provide the backend infrastructure for running kubeflow jobs. These might vary from cloud to cloud and can be parametrized using a `cloud` parameter.

And an `examples` package with an exhaustive set of examples for running different kinds of jobs / services. These are not expected to vary much across clouds.

```
kubeflow/ - package
  prototypes/
    jupyterhub.jsonnet
    iap.jsonnet
    seldon.jsonnet
    pachyderm.jsonnet
    argo.jsonnet
    nfs.jsonnet
...
    
examples/ - package
  prototypes/
    tfjob-simple.jsonnet
    tfjob-distributed-cpu.jsonnet
    tfjob-distributed-gpu.jsonnet
    tf-serving-cpu.jsonnet
    tf-serving-gpu.jsonnet
    pachyderm-pipline.jsonnet
    pachyderm-pipline-multi-stage.jsonnet
...

```

**Comment by pdmack** [comment]
Sure, I'm trying to divine what the DevOps UX is for a newcomer with regards to our organization of components.  I myself was tripped up by the distinction between TFJob as CRD (currently in core) and TFJob as a user component (currently in tf-job). The instinct for me is to logically group these all under the domain of the tf-job package but as distinct prototypes. So it seems to me we are looking at two possibilities:
1. logically group components as either infra (kubeflow) or user-defined (examples)
1. logically group components as standalone vs. co-dependent ("core", which maybe would be a somewhat misleading term in this sense)

**Comment by lluunn** [comment]
@jlewi Agree with using complete manifest over using import.

@ankushagarwal  The two classes make sense; I would call them service part and client part.
So I guess there might be a better name for "examples".

**Comment by jlewi** [comment]
Will having all the packages Argo, Jupyter, Pachyderm, Seldon etc... in core scale?

From a maintenance perspective (e.g. OWNERs) files grouping components into directories based on ownership is convenient.

**Comment by ankushagarwal** [comment]
> Will having all the packages Argo, Jupyter, Pachyderm, Seldon etc... in core scale?

I don't think that the idea of having a `core` prototype will scale. As mentioned in the comment above, we cannot assume that people want all the components of `core` prototype. #669 is an early manifestation of this long term issue. What if I wanted to install only jupyterhub, nfs and pytorch operator for my kubeflow deployment? 

I strongly feel that having a single package with a list of pluggable 'controller' components is going to be more scalable than the multi-package approach we have today. pkg -> prototype -> component hierarchy is unnecessary complicated (https://github.com/ksonnet/ksonnet/issues/263)

For maintenance, we could always just delegate the heavylifting of each prototype to a directory with separate OWNERS file like below. The `jupyterhub.jsonnet` would just contain the params and an import.  

```
kubeflow/
  prototypes/
    jupyterhub.jsonnet
    tf-job-crd.jsonnet
    iap.jsonnet
    seldon.jsonnet
    pachyderm.jsonnet
    argo.jsonnet
    nfs.jsonnet
  lib/
    jupyterhub/
      OWNERS
      jupyterhub.libsonnet
    tf-job-crd/
      OWNERS
      tf-job-crd.libsonnet  
...
    
examples/
  prototypes/
    tfjob-simple.jsonnet
    tfjob-distributed-cpu.jsonnet
    tfjob-distributed-gpu.jsonnet
    tf-serving-cpu.jsonnet
    tf-serving-gpu.jsonnet
    pachyderm-pipline.jsonnet
    pachyderm-pipline-multi-stage.jsonnet
...

```

**Comment by pdmack** [comment]
So in that model, does every jsonnet file of kubeflow/prototypes become distilled to 3 lines of difference?
e.g.,
```
local env = std.extVar("__ksonnet/environments");
local k = import "k.libsonnet";
local params = std.extVar("__ksonnet/params").components["tf-job-crd"];
local tfjob = import "kubeflow/lib/tf-job-crd/tf-job-crd.libsonnet";

local updatedParams = params {
  namespace: if params.namespace == "null" then env.namespace else params.namespace,
};

std.prune(k.core.v1.list.new(tfjob.all(updatedParams)))
```

Seems like boilerplate.

**Comment by inc0** [comment]
My 0.02$

I think we need to answer what do we want to hold in our repo?

1. Everything
That means literally everything someone will want to run in relation to their ML work should have ksonnet prototype - we kinda do this now (case in point - NFS, Istio, Envoy)
I don't think this is scallable as soon we'll have to handle Prometheus ksonnet prototypes etc etc.
My opinion is that we shouldn't really handle this part and rather make sure that we are pluggable enough so users could pick and choose solution they want without big hassle.

2. Just projects strictly related to ML
Things like Pachyderm, Seldon. Neither are Kubeflow projects but both are great satellite project/alternatives to certain parts of Kubeflow (Seldon vs tf-serving).
I think this approach is best (assuming we qualify exactly what it means to be project related to ML). One benefit would be that these communities could have tight relationship with us (as they do today) so we can cooperate easily. I think it would be reasonable to have rule that if project X would want to have ksonnet prototype in Kubeflow, there should be someone from this projects community involved in Kubeflow prototype maintenance and creation (listed in OWNERS). This will allow us to be up-to-date with deployment and lifecycle mgmt of code.

3. Just kubeflow projects
That would mean dropping things like Pachyderm, Seldon or Jupyter. If we build our project in pluggable enough way, integration would still be easy, but we wouldn't be responsible of deployment of these components. That would drastically narrow our scope and allow us to be more focused on growing portfolio of Kubeflow-hosted projects.
This apporach would be easiest to handle for us but not necessarily easiest for users - for example we use KSonnet where other projects could use Helm.

Now, another question - ksonnet prototypes for Katib should live in kubeflow/kubeflow repo or kubeflow/katib? If we do the latter, that will allow better management of OWNERS, and within kubeflow repo we could host integration code like bootstrapper (and install all pkgs in image). We could also hold external projects prototypes in kubeflow itself.

Alternative is what we do right now - have all things ksonnet in kubeflow repo. To me it becomes unwieldy quickly especially if we won't have clean separation of kubeflow projects vs non-kubeflow projects and who is responsible for health of relevant code.

So, my suggestion:

We will do option 2 + all kubeflow projects would host their own ksonnet prototypes + integration in boostrapper.
Repo would look like this (roughly)

"""
katib.git/
  katib.jsonnet
kubeflow.git/
  bootstrapper/
     <<image with ks pkg install katib>>
  kubeflow/
      pachyderm/
          OWNERS - someone from Pachyderm community
          pachyderm.jsonnet
tf-operator
   tf-operator.jsonnet
"""
etc

We would need to make sure that things like Envoy are still easy to plug in and use kubernetes prototypes (like services or storageclass) as much possible without necessarily hosting definitions of these (we just say we need StorageClass, no matter if it's NFS or local PVC).

**Comment by jlewi** [comment]
Lets try to rationalize our ksonnet repo organization in 0.4.0.

Next step would probably be a proposal to document how we want to organize things.

We should use the label area:/ksonnet to try track all the issues related to ksonnet and try to address the issues related to structure wholistically in 0.4

**Comment by kkasravi** [comment]
@jlewi @ankushagarwal @pdmack @lluunn @inc0 see #1485 as an example of simplifying tensorboard where 2 prototypes are split out: tensorboard-aws.jsonnet, tensorboard-gcp.jsonnet. Both extend a common prototype (tensorboard.libsonnet). Worth noting is the use of k.libsonnet in the base prototype - see
- https://github.com/kubeflow/kubeflow/pull/1485/files#diff-9bf1896c3cec2fcc18ac8835d197e7abR29
- https://github.com/kubeflow/kubeflow/pull/1485/files#diff-1c93ad27eba3193e7fff771b3b19b330R19

Whether we want to use k.libsonnet to build all k8 components is worth discussing - although the patterns for using k.libsonnet are fairly simple. See this [tutorial](https://github.com/ksonnet/ksonnet-lib/blob/master/docs/TUTORIAL.md) on the use of mixin libraries.

**Comment by jlewi** [comment]
Discussion of use of k.libsonnet
   
    * https://github.com/kubeflow/kubeflow/pull/1437#issuecomment-418523083 
          * Suggested trying to avoid use of k.libsonnet in user facing prototypes (e.g. TFJob, TFServing) because the feedback is most users prefer simple json
          * Use of k.libsonnet is probably more acceptable in system components (e.g. JupyterHub) that users are less likely to modify
    * https://github.com/kubeflow/kubeflow/pull/1535#issuecomment-422177056
          * Suggested that when constructing an initial base object (e.g. setting a bunch of fields) do this by defining the object in json as opposed to constructing it as a series of mixins that each modify one field
          * Use mixins when modifying an existing object

Probably a good idea to begin capturing this in a doc.

**Comment by jlewi** [comment]
Obsolete now that ksonnet is deprecated.
