### ISSUE TITLE
kfctl: existing_arrikto: LoadBalancer address discovery doesn't work for AWS

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3764]
In platform existing_arrikto, we get the LoadBalancer address by looking at `status.loadBalancer.ingresses[0].ip`.
However, ELB gives a hostname, not an IP.

The logic should be fixed to also work for hostname.

/priority p0
/assign @yanniszark

**Comment by jlewi** [comment]
@yanniszark Can you provide an update please? 

We will likely cut v0.6.2 this week. If you'd like #3760 to be included can you get that PR merged and then cherry-pick it onto the v0.6-branch?

**Comment by yanniszark** [comment]
@jlewi it seems @Jeffwan has LGTM'd it but the CI bot hasn't picked it up.
However, the v2.zip file no longer exists in master, but will exist in v0.6.2.

In order to deal with this I understand that I need 2 PRs:
1. Merge this functionality in master, without the changes to v2.zip.
2. Cherry pick it in v0.6.2, adding the changes to v2.zip.

I will use #3760 to merge in master and open another PR to cherry pick the change in v0.6-branch.
Does this sound good ?

**Comment by Jeffwan** [comment]
@yanniszark Sounds good. How does release work? 0.6.2 will be cut based on 0.6-branch or a separate branch. If it's 0.6-branch, I think there's no need to cherry-pick to v0.6.2

**Comment by yanniszark** [comment]
@Jeffwan v0.6.2 will be cut based on the v0.6-branch.
PR #3760 adds the functionality to master. From there, it will be cherry picked to the v0.6-branch.

@Jeffwan if you are ok with #3760, can you please LGTM it?

**Comment by jlewi** [comment]
@Jeffwan @yanniszark it looks #3760 was merged.

Has it been cherry-picked to v0.6-branch?

If not can one of you open a cherry pick please?

These instructions explain how to use our helper script to create cherry-picks.
https://github.com/kubeflow/kubeflow/blob/master/hack/cherry-picks.md

**Comment by yanniszark** [comment]
@jlewi the commit that cherry picks this in v0.6-branch is this:

**Comment by jlewi** [comment]
@yanniszark Thanks so can we close this issue? If not what work remains to close this out?

**Comment by jlewi** [comment]
@yanniszark @Jeffwan So is this issue resolved? Can we close it?

**Comment by Jeffwan** [comment]
@jlewi This change was merged to master and v0.6.1. I just close the issue
