### ISSUE TITLE
Delete ksonnet directory on master

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3771]
We should delete the ksonnet registry on master
https://github.com/kubeflow/kubeflow/tree/master/kubeflow

ksonnet is no longer supported on master and should no longer be used on master.

**Comment by Jeffwan** [comment]
/hold

Let's hold this story for a while. 

1. Leave it for package migration 
2. Looks like a lots of examples are still using the packages there. 

Probably after we confirm all docs/examples are up to date

**Comment by jlewi** [comment]
Fixed by #4484
