### ISSUE TITLE
Pipelines + tensorboard + S3, blank page

### ISSUE THREAD

**Issue by tanguycdls** [kubeflow/kubeflow#3773]
Hi, I'm running Kubeflow (V0.5) on AWS, using Pipelines I want to use the Tensorboard button in the pipelines metadata result. 

I saved my pipeline result into a private S3 bucket with the following code:  
```
metadata = {
    'outputs' : [{
      'type': 'tensorboard',
      'source': 's3://'+ bucket_name + '/' + destination,
    }]}
```
```
with open('/mlpipeline-ui-metadata.json', 'w') as f:
        json.dump(metadata, f)`
```
But when I try opening the Artifacts results of that operation I only get the circle loading bar and nothing happens. If I look at the Network Request i find a POST REQUEST with the following response : 
>>> {"outputs": [{"type": "tensorboard", "source": "s3://BUCKET_NAME/FOLDER1/FOLDER2/1564392073"}]}

I tried using GCS instead to save the file and in that case, the Tensorboard button appears and I can start the TB instance. (It fails because I don't have any GC creds (MountVolume.SetUp failed for volume "gcp-credentials" : secrets "user-gcp-sa" not found). 

How should I save my summary writers to be able to start the TB instance from the pipeline artifacts on AWS/ S3? 

Thank your for your help, 
## EDIT : 
I found that issue https://github.com/kubeflow/pipelines/issues/337 in the pipeline project of Kubeflow. Can someone confirm that Tensorboard through Pipelines on AWS stored in S3 is currently not supported ?

**Comment by Jeffwan** [comment]
@tanguycdls 

Yes, it's hardcoded there and may takes some efforts to make it generic. Right now, TB in pipeline artifacts is not supported. 

I would suggest you right now not using it. It create a pod and you need to manage its lifecycle. Instead, using one TB in kubeflow and load more model under s3 path.

**Comment by tanguycdls** [comment]
Thank you for your answer  ! In that case we will start them independantly and handle their lifecycle manually on Notebooks ...

I did not have the time yet to try ROC Curve and confusion matrix are they supported with S3 or is it the same for all artifacts ? 

Thks !

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/pipelines/pull/1278

ROC curve and Confusion Matrix is a little bit different. It will work.

**Comment by descampsk** [comment]
With this PR https://github.com/kubeflow/pipelines/pull/1906, we are able to use S3 and Tensorboard. 

It need to use AWS_REGION and  AWS_LOG_LEVEL=3 env variables (see https://github.com/tensorflow/tensorflow/issues/21898)

However 

> I would suggest you right now not using it. It create a pod and you need to manage its lifecycle. Instead, using one TB in kubeflow and load more model under s3 path.

The viewer controller is now supposed to clean older viewers pods but there is a bug I reported here: 
https://github.com/kubeflow/pipelines/issues/2757

**Comment by tanguycdls** [comment]
it now works
