### ISSUE TITLE
Grafana access through istio

### ISSUE THREAD

**Issue by rajesh-chawla** [kubeflow/kubeflow#3776]
/kind question

**Question:**
I’ve deployed kubeflow (0.6) using the config at: https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_existing_arrikto.0.6.yaml

I see at least two options from the Istio side. First as a [virtualservice](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/) or via [gateway](https://istio.io/docs/tasks/telemetry/gateways/). My question is: Is there a recommendation from kubeflow and how should authentication (via dex) be handled?

**Comment by Ventals** [comment]
@rajesh-chawla btw, which method you selected? And how configured access?

**Comment by Ventals** [comment]
I found that Grafana already exposed via Istio Gateway.
**On kubeflow version - 1.0.2**

By path **/istio/grafana/**
But have some trouble with availability, more info in this issue
