### ISSUE TITLE
kfctl init flag --namespace doesn't change the kubeflow installation namespace

### ISSUE THREAD

**Issue by sahilmalav** [kubeflow/kubeflow#3778]
/kind bug

I'm trying to install Kubeflow 0.6.1. For this, I downloaded and unzipped kfctl, and executed 
**kfctl init ${KFAPP} --namespace=kubeflow-six --config=${CONFIG} -V** 
Post this, when I did **kfctl generate all -V**, the app.yaml file still had namespace mentioned as "kubeflow" instead of "kubeflow-six", as I had mentioned in the flag. 

Expected Behaviour : The namespace should have been "kubeflow-six" instead of the default "kubeflow". 

**Environment:**

- Kubeflow version: v0.6.1
- kfctl version:  kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform:  Kubeadm
- Kubernetes version: : v1.14.1
- OS : Ubuntu 18.04LTS

**Comment by yeya24** [comment]
What's your configuration file? Can you paste it here?
I am wondering what's the priority of kf configuration and kfctl flags. Which one should have higher priority?

**Comment by sahilmalav** [comment]
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kf-six
  namespace: kubeflow
spec:
  appdir: /home/xprops/kubeflow-0.6/kf-six
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: argo
    name: argo
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/webhook
    name: webhook
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: jupyter/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-db
    name: katib-db
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-manager
    name: katib-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-controller
    name: katib-controller
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-ui
    name: katib-ui
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: metadata
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/metrics-collector
    name: metrics-collector
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/suggestion
    name: suggestion
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: jupyter/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  - kustomizeConfig:
      parameters:
      - initRequired: true
        name: usageId
        value: <randomly-generated-id>
      - initRequired: true
        name: reportUsage
        value: "true"
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: tensorboard
    name: tensorboard
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/api-service
    name: api-service
  - kustomizeConfig:
      parameters:
      - name: minioPvName
        value: minio-pv
      - name: minioPvcName
        value: minio-pv-claim
      repoRef:
        name: manifests
        path: pipeline/minio
    name: minio
  - kustomizeConfig:
      parameters:
      - name: mysqlPvName
        value: mysql-pv
      - name: mysqlPvcName
        value: mysql-pv-claim
      repoRef:
        name: manifests
        path: pipeline/mysql
    name: mysql
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/persistent-agent
    name: persistent-agent
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-runner
    name: pipelines-runner
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui
    name: pipelines-ui
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-viewer
    name: pipelines-viewer
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/scheduledworkflow
    name: scheduledworkflow
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  componentParams:
    argo:
    - name: overlay
      value: istio
    centraldashboard:
    - name: overlay
      value: istio
    jupyter-web-app:
    - name: overlay
      value: istio
    katib-ui:
    - name: overlay
      value: istio
    metadata:
    - name: overlay
      value: istio
    minio:
    - name: minioPvName
      value: minio-pv
    - name: minioPvcName
      value: minio-pv-claim
    mysql:
    - name: mysqlPvName
      value: mysql-pv
    - name: mysqlPvcName
      value: mysql-pv-claim
    notebook-controller:
    - name: overlay
      value: istio
    pipelines-ui:
    - name: overlay
      value: istio
    spartakus:
    - initRequired: true
      name: usageId
      value: <randomly-generated-id>
    - initRequired: true
      name: reportUsage
      value: "true"
    tensorboard:
    - name: overlay
      value: istio
    tf-job-operator:
    - name: overlay
      value: istio
  components:
  - metacontroller
  - argo
  - centraldashboard
  - bootstrap
  - webhook
  - jupyter-web-app
  - katib-db
  - katib-manager
  - katib-controller
  - katib-ui
  - metadata
  - metrics-collector
  - suggestion
  - notebook-controller
  - pytorch-job-crds
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  - api-service
  - minio
  - mysql
  - persistent-agent
  - pipelines-runner
  - pipelines-ui
  - pipelines-viewer
  - scheduledworkflow
  - profiles
  enableApplications: false
  manifestsRepo: /home/xprops/kubeflow-0.6/kf-six/.cache/manifests/manifests-master
  packageManager: kustomize
  packages:
  - argo
  - common
  - examples
  - admission-webhook
  - jupyter
  - katib-v1alpha2
  - metacontroller
  - metadata
  - modeldb
  - mpi-job
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  - pipeline
  - profiles
  platform: existing_arrikto
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  useBasicAuth: false
  useIstio: true
status:
  reposCache:
    kubeflow:
      localPath: '"/home/xprops/kubeflow-0.6/kf-six/.cache/kubeflow/kubeflow-master"'
    manifests:
      localPath: '"/home/xprops/kubeflow-0.6/kf-six/.cache/manifests/manifests-master"'

**Comment by sahilmalav** [comment]
I was expecting that providing a namespace flag will change the value of namespace in the app.yaml file. But that didn't happen. Moreover, when I manually changed it and tried deploying, _istio_ threw some error because it was searching for namespace "kubeflow".
