### ISSUE TITLE
Automate Building Post-Submit Images for Central-Dashboard

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3781]
## About
We would like to get an image built for CentralDashboard from master everytime a PR is merged

/kind feature

### misc:
/kind feature
/cc @prodonjs @jlewi 
/assign @avdaredevil 
/priority p1

**Comment by jlewi** [comment]
Here are some pointers

We had a process for auto-updating the jupyter web app image
https://github.com/kubeflow/kubeflow/tree/master/releasing/auto-update

We want to do something similar for the central dashboard.

The first step would be to create a script like
https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/update_jupyter_web_app.py

That does the following

1. Build the image using GCB
1. Edit the [kustomization file](https://github.com/kubeflow/manifests/blob/64b24db9ba932346d26f9e742215da1939a9f3db/common/centraldashboard/base/kustomization.yaml#L14) to use the new image
1. Use Hub-Cli to create a PR with the changes.

**Comment by jlewi** [comment]
This is still needed for centraldashboard 1.0

**Comment by jlewi** [comment]
This is fixed.
