### ISSUE TITLE
Can't generate CHANGELOG.md for releases

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#3787]
/kind bug

**What steps did you take and what happened:**
I tried to generate new change logs for v0.6 releases by running `scripts/update-changelog.sh` with my personal Github token, but the script failed with errors
```
RETRY - Octokit::AbuseDetected: 'GET https://api.github.com/repos/kubeflow/kubeflow/issues/2022/events?per_page=100: 403 - You have triggered an abuse detection mechanism. Please wait a few minutes before you try again. // See: https://developer.github.com/v3/#abuse-rate-limits'
```

Tried to use `--since-tag` flag to reduce the traffic, but still hit the rate limit of Github.

Seems related to
https://github.com/github-changelog-generator/github-changelog-generator/issues/656

**Comment by sarahmaddox** [comment]
I'm going to close this issue, as it's not relevant for the website docs. Please do re-create the issue in kubeflow/kubeflow to track work if need be.

/close

**Comment by sarahmaddox** [comment]
Oops sorry, my bad. I thought this issue was in the kubeflow/website repo. Re-opening this one.

/reopen
