### ISSUE TITLE
Notebook servers don't have proper labels for mounting gcp specific secret

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/kubeflow#3788]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When you create a notebook server in GCP/GKE environment, it supposed to have "add-gcp-secret":"true" label that mounts a service account creds via a volume mount but it is missing the label.

**What did you expect to happen:**
All notebook servers in GCP environment should have "add-gcp-secret":"true" label.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the is sue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): https://github.com/kubeflow/kubeflow/releases/tag/v0.6.1
- kfctl version: (use `kfctl version`): kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`): 1.12.9-gke.7
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9 (stretch)

**Comment by jlewi** [comment]
@karthikv2k In the Jupyter UI to spawn the notebook in the configuration box did you select
the drop down that says inject GCP credentials.

It looks like we are lacking docs about this.

**Comment by jlewi** [comment]
Obsolete with 0.7 since we now use workload identity.
