### ISSUE TITLE
Kubeflow 0.6 Installation failing for on-prem k8s cluster

### ISSUE THREAD

**Issue by shivam-rai** [kubeflow/kubeflow#3790]
Hi.

While trying to install kubeflow (via kfctl) for an on-prem k8s cluster, kfctl generate stage is failing with the following output

kfctl generate all -V

INFO[0000] Downloading /kf/ugc-kf/app.yaml to /tmp/431686218/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /kf/ugc-kf/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /kf/ugc-kf/app.yaml to /tmp/192332577/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Initializing kustomize package map            filename="kustomize/kustomize.go:149"
INFO[0000] Component path map: {}                        filename="kustomize/kustomize.go:170"
INFO[0000] Converting component metacontroller to an application in KfDef.Spec  filename="kustomize/kustomize.go:202"
ERRO[0000] Could not backfill the component metacontroller; no component path specified  filename="kustomize/kustomize.go:207"
ERRO[0000] Could not backfill KfDef.Spec.Applications from components; error Could not backfill the component metacontroller; no component path specified  filename="kustomize/kustomize.go:584"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error: Could not backfill the component metacontroller; no component path specified

**Config used for init**
https://gist.github.com/shivam-rai/5233717fc8d07a6f06d881989560b40a

**app.yaml generated after init**
https://gist.github.com/shivam-rai/e0a74cc29da835d68e1ea13e059cd6b1

**Init command**
kfctl init ${KFAPP} --config /kf/kf_config.yaml --disable_usage_report -V

**generate command**
kfctl generate all -V

**Version Info:**

kfctl version is kfctl v0.6.0-0-g71aea0a9
kustomize version is Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
k8s version is: v1.15.0

**Comment by mattshma** [comment]
I meet the same question with you @shivam-rai , the error message like this:

# kfctl generate all -V
INFO[0000] Downloading /opt/app/kubeflow/app.yaml to /tmp/996299833/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /opt/app/kubeflow/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /opt/app/kubeflow/app.yaml to /tmp/019566148/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  ks delete default -c spartakus
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

Then run the following command to remove it from your ksonnet app:
  ks component rm spartakus

For more info: https://www.kubeflow.org/docs/guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:188"
INFO[0000] Initializing kustomize package map            filename="kustomize/kustomize.go:149"
INFO[0000] Component path map: {}                        filename="kustomize/kustomize.go:170"
INFO[0000] Converting component metacontroller to an application in KfDef.Spec  filename="kustomize/kustomize.go:202"
ERRO[0000] Could not backfill the component metacontroller; no component path specified  filename="kustomize/kustomize.go:207"
ERRO[0000] Could not backfill KfDef.Spec.Applications from components; error Could not backfill the component metacontroller; no component path specified  filename="kustomize/kustomize.go:594"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error: Could not backfill the component metacontroller; no component path specified
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'
      --ipName string     ipName if '--platform gcp'
      --mount-local       mount-local if '--platform minikube'
  -V, --verbose           verbose output default is false
      --zone string       zone if '--platform gcp'

couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error: Could not backfill the component metacontroller; no component path specified

# kfctl version
kfctl v0.6.1-rc.2-1-g3a37cbc6

Had your solved it ?

**Comment by shivam-rai** [comment]
Hi mattshma.

There's apparently a bug in the init step, where if you use on-disk files for repos in your init-config, the generated app.yaml has incorrect paths in the  status> reposCache.

As a result, your generate command doesn't fetch packages from your .cache properly.

I could solve it by manually fixing localPath "kf/ugc-kf/.cache/manifests" -> "kf/ugc-kf/.cache/manifests/manifests-master" and hence closed the issue.

Hope it helps you.

**Comment by mattshma** [comment]
You're right, after modify app.yaml these fields: `manifestsRepo`, `status.reposCache.kubeflow.localPath` and `status.reposCache.manifests.localPath`, I run `kfctl generate all -V` successful. Thanks!
