### ISSUE TITLE
kfctl shows wrong version in v0.6.1

### ISSUE THREAD

**Issue by InCogNiTo124** [kubeflow/kubeflow#3791]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Downloaded the latest release from the release page but the printed version does not match the downloaded

```
cd /tmp
wget https://github.com/kubeflow/kubeflow/releases/download/v0.6.1/kfctl_v0.6.1_linux.tar.gz
tar xvf kfctl_v0.6.1*
./kfctl version
> kfctl v0.6.1-rc.2-1-g3a37cbc6
```
**What did you expect to happen:**
it should print out `kfctl v0.6.1`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Although a minor issue, it could create confusion in the next releases.
**Environment:**
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
v0.6.1
- kfctl version: (use `kfctl version`): v0.6.1-rc2-1-g3a37cbc6
- Kubernetes platform: (e.g. `minikube`) aws eks 
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Amazon Linux AMI 2018.03.

**Comment by jbottum** [comment]
@kkasravi have you seen this ?
