### ISSUE TITLE
using relative paths in KfDef app.yaml?

### ISSUE THREAD

**Issue by mattnworb** [kubeflow/kubeflow#3794]
/kind question

**Question:**
Is it possible to use relative paths in the KfDef definition in app.yaml for things like `repo`, `manifestsRepo`, `reposCache` etc? The generated app.yaml uses absolute paths.

We'd ultimately like to be able to store the generated directories in a Git repo and share among multiple engineers who would have a need to manage/upgrade the same set of clusters, so portability between different machines etc would be extremely valuable.

**Comment by yanniszark** [comment]
Seems like a dup of https://github.com/kubeflow/kubeflow/issues/3712.
@mattnworb does https://github.com/kubeflow/kubeflow/issues/3712 cover your issue?

**Comment by mattnworb** [comment]
it does, thanks!
