### ISSUE TITLE
Update Manifest with new Central-Dashboard Image with Multi-User Isolation Changes

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3795]
## About:
Will create a manifest entry to get both changes rolled out from master into the v0.6 release.
- [ ] Hard prerequisite: Get all unit tests in for the new components introduced by the aforementioned components

### meta:
/assign @avdaredevil 
/cc @jlewi @prodonjs

**Comment by jlewi** [comment]
@avdaredevil Is there more work to be done here? Has kubeflow/manifests been updated on both kubeflow/manifests@v0.6-branch and kubeflow/manifests@master

**Comment by avdaredevil** [comment]
Nope, this is done. Closing...
