### ISSUE TITLE
E2E Testing For Kubeflow.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#38]
We need to setup continuous E2E testing for google/kubeflow

- [ ] Create a basic an E2E test
     - [ ] Deploy and verify JupyterHub is working
     - [X] Deploy and verify TfJob is working
     - [ ] Verify TfServing is working
- [X] Setup prow for google/kubeflow
     - [X] Setup presubmit tests
     - [ ] Setup postsubmit tests

I think it makes sense to write the E2E test first and then once we have it we can setup prow integration.

**Comment by foxish** [comment]
Related: https://github.com/kubernetes/test-infra/issues/6011

**Comment by jlewi** [comment]
Track progress following these [instructions](https://github.com/tensorflow/k8s/tree/master/test-infra#notes-adding-tensorflowk8s-to-k8s-prow-instance) to setup prow.

- [ ] Step 1; PR to add google/kubeflow to prow configs; kubernetes/test-infra#6110 is out for review
- [x] Step 2; Setup GitHub prow webhook
- [ ]  Step 3; Add k8s robot to google/kubeflow
- [ ]  Step 4: Setup PR dashboard
- [ ] Step 5: Grant read access to Gubernator GCS bucket to kubeflow-testing service account

**Comment by jlewi** [comment]
presubmits are passing
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-presubmit

postsubmits don't seem to be running
I think this is the same issue as tensorflow/k8s#370 i.e we aren't truncating the commit sha when constructing the Argo workflow name.

To fix this we should probably modify kubeflow/kubeflow to pull run_workflow_e2e.py from kubeflow/testing once kubeflow/testing#9 is submitted. That pr should fix this issue.
