### ISSUE TITLE
Smoke test for JupyterHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#380]
Our E2E tests should verify that JupyterHub actually starts up when Kubeflow is deployed.

It would also be good to verify that we can spawn a notebook but that might be harder.

**Comment by jlewi** [comment]
We already ensure JupyterHub is deployed here.
https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L174

**Comment by pdmack** [comment]
Could check the notebook with something like:
`$ curl -s -X GET -H "Authorization: token 45d9275e90aa403cb9d6c74fac254ca4" "http://127.0.0.1:8000/user/developer/api/sessions" | jq '.[0].notebook.path'
"work/Untitled.ipynb"`

**Comment by jlewi** [comment]
@pdmack I think we have to spawn the notebook first; I suspect we could use a similar command.

**Comment by jlewi** [comment]
@pdmack Should we move this to 0.3? It looks like non-trivial work and I don't think anyone is working on it.

**Comment by jlewi** [comment]
@pdmack Any thought about what if anything we should try to do as part of 0.4?

**Comment by pdmack** [comment]
Just basic imports of important packages in the py2 and py3 kernels to start would be better than nothing.

https://github.com/Kaggle/docker-python/blob/master/test_build.py
