### ISSUE TITLE
AMD/ROCM support

### ISSUE THREAD

**Issue by boniek83** [kubeflow/kubeflow#3804]
/kind feature

**Why you need this feature:**
More hardware choice. You can use consumer cards (e.g. Radeon VII with 16GB HBM2) legally in datacenter as opposed to NVidia.

**Describe the solution you'd like:**
Make AMD hardware first class citizen next to NVidia. 

**Anything else you would like to add:**
AMD forked a lot of code (with intention to merge it upstream) all available under: https://github.com/RadeonOpenCompute
https://github.com/RadeonOpenCompute/ROCm_Documentation
Intergration of rocm with kubernetes is pretty straightforward (they have kubernetes device plugin). They have some docker images available: https://hub.docker.com/u/rocm
I coudn't get horovod fork (wtih mxnet) to compile, there is no docker with horovod (at least I couldn't find one). Tensorflow seems to be working.

**Comment by jlewi** [comment]
@boniek83 Do you have more info on what the integration points in Kubeflow are. Is it a matter of compiling our docker containers with ROCM?

Do we need to wait for support to be upstreamed into Kubernetes?

/cc @kkasravi

**Comment by y2kenny** [comment]
> Do we need to wait for support to be upstreamed into Kubernetes?

@jlewi We have [AMD GPU device-plugin](https://github.com/RadeonOpenCompute/k8s-device-plugin) support for Kubernetes for awhile, are there other things needed?  I did a quick keyword search on the repository and looks like some of the components are hard coded to a vendor but I am not sure if they are significant (I am very new to KubeFlow and I am not sure what all the pieces are.)

**Comment by jlewi** [comment]
@y2kenny this issue is closed; I would suggest opening a new issue or reopening if you think there is more to discuss. I'm not sure what the issue would be; i.e. if AMD GPUs are supported in Kubernetes then it should be able to attach them to pods and code should be able to use them. So what would be the feature ask/work for Kubeflow?
