### ISSUE TITLE
Dex login is not enforced (Onprem existing_arrikto config)

### ISSUE THREAD

**Issue by tlkh** [kubeflow/kubeflow#3805]
/kind bug

**What steps did you take and what happened:**

On a freshly installed Kubernetes on-prem (single node for testing), Kubeflow deploys successfully (used MetalLB for LoadBalancer). Following instruction on [this page](https://www.kubeflow.org/docs/started/getting-started-k8s/) under "Log in as a static user", I can reach the dashboard right away by adding the port number, thus bypassing the Dex authentication mechanism.

**Working:**

* `https://ip-addr/` directs me correctly to the Dex login screen
* `https://ip-addr:5556/dex/auth/local?req=xxx` directs me correctly to the Dex login screen
* Wrong passwords on the login screen are rejected, so that part seems to be working. 

**Not Working:**

* **`https://172.17.31.15:5556/` lets me access the central dashboard right away (tested again with Incognito and other devices)**
* In central dashboard, even after login, the user (top right) shows as `anonymous@kubeflow.org`

**What did you expect to happen:**

Expected behaviour is for an unauthenticated user to be forced to login, and not able to bypass and reach the central dashboard. In addition, the correct user (eg email) should be shown in central dashboard. 

**Environment:**

- Kubeflow version: 0.6
- kfctl version: (use `kfctl version`): 0.6
- Kubernetes platform: (e.g. `minikube`) On-prem (existing_arrikto)
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Anything else you would like to add:**

Some of the pods don't seem to be deploy correctly, but I don't think that should affect the authentication mechanism. When checking logs, it seems to be some kind of permission errors.

```
> kubectl logs mysql-75654987c5-vj75v -n kubeflow
chown: changing ownership of '/var/lib/mysql/': Operation not permitted

> kubectl logs metadata-db-8d9b95598-p5928 -n kubeflow
chown: changing ownership of '/var/lib/mysql/datadir/': Operation not permitted
```

Output from `kubectl get pods -n kubeflow`:

```
admission-webhook-bootstrap-stateful-set-0                  1/1     Running            0          26m
admission-webhook-deployment-b77bd65c5-gzp6s                1/1     Running            0          26m
argo-ui-6db54c878-95pp7                                     1/1     Running            0          26m
centraldashboard-7b69b696cb-74668                           1/1     Running            0          26m
dex-6847f88df6-x27kh                                        1/1     Running            0          26m
jupyter-web-app-deployment-fbb87f9d-wqdqs                   1/1     Running            0          26m
katib-controller-55ccdcc6c8-dml4t                           1/1     Running            1          26m
katib-db-b48df7777-s9h9t                                    0/1     CrashLoopBackOff   10         26m
katib-manager-6944b56f96-r64bb                              0/1     CrashLoopBackOff   11         26m
katib-manager-rest-6f6b8f4b54-mpkkz                         1/1     Running            0          26m
katib-suggestion-bayesianoptimization-66c6764d5b-jm2sm      1/1     Running            0          26m
katib-suggestion-grid-5c758dbf4b-bcwvw                      1/1     Running            0          26m
katib-suggestion-hyperband-76cdd95f46-6cll6                 1/1     Running            0          26m
katib-suggestion-nasrl-6bc7855ddd-b5dsg                     1/1     Running            0          26m
katib-suggestion-random-65c489b584-rflf4                    1/1     Running            0          26m
katib-ui-57bcbb9f56-khhbr                                   1/1     Running            0          26m
metacontroller-0                                            1/1     Running            0          26m
metadata-db-8d9b95598-p5928                                 0/1     CrashLoopBackOff   10         26m
metadata-deployment-545d79c747-6w6zb                        0/1     CrashLoopBackOff   9          26m
metadata-deployment-545d79c747-bx4hh                        0/1     CrashLoopBackOff   9          26m
metadata-deployment-545d79c747-zpckv                        0/1     Error              10         26m
metadata-ui-76b5498765-dn2nq                                1/1     Running            0          26m
minio-56dc668bd-2768b                                       1/1     Running            0          26m
ml-pipeline-567b7d6b44-zhhb9                                1/1     Running            3          26m
ml-pipeline-persistenceagent-69f558486c-9gj4p               0/1     CrashLoopBackOff   6          26m
ml-pipeline-scheduledworkflow-869954f57c-pzcgs              1/1     Running            0          26m
ml-pipeline-ui-c8d7b55cc-6w6b8                              1/1     Running            0          26m
ml-pipeline-viewer-controller-deployment-566d875695-jhzqp   1/1     Running            0          26m
mysql-75654987c5-vj75v                                      0/1     Error              10         26m
notebook-controller-deployment-58c6c5d8cc-qf6kr             1/1     Running            0          26m
profiles-deployment-7f8d45c9f9-9nw6s                        2/2     Running            0          26m
pytorch-operator-69d875b748-k4w7h                           1/1     Running            0          26m
spartakus-volunteer-6cfc55fd88-gwpgh                        1/1     Running            0          26m
tensorboard-5f685f9d79-gq67h                                1/1     Running            0          26m
tf-job-dashboard-5fc794cc7c-2xdbs                           1/1     Running            0          26m
tf-job-operator-6c9674bcd8-nfg4t                            1/1     Running            0          26m
workflow-controller-5b4764bc47-97grs                        1/1     Running            0          26m
```

**Comment by yanniszark** [comment]
I took a look at this and I believe the following is happening:

1. Kubeflow VirtualService bind to all ports of the Istio Gateway, meaning they are accessible from 5556 as well.
2. The Dex VirtualService only handles requests to paths that starts with `/dex`. Requests that don't start with `/dex` will be directed to Kubeflow.

When https://github.com/kubeflow/kubeflow/issues/3839 is resolved, this problem will no longer exist.
Until then, a quick solution would be to edit the Dex VirtualService to handle all the traffic coming to port 5556.
I will make a PR soon.

**Comment by yanniszark** [comment]
Until the long term solution #3839 is implemented, I made a PR to fix this:
#3885
