### ISSUE TITLE
request: ability to pass kube context name to kfctl as flag

### ISSUE THREAD

**Issue by mattnworb** [kubeflow/kubeflow#3815]
/kind feature

**Why you need this feature:**
I have many Kubernetes clusters in my KUBECONFIG file that I work across, many of which do not run Kubeflow. It would be fantastic if I could be explicit when using `kfctl` about which context I want it to work against.

Currently, kfctl uses the `current-context` from KUBECONFIG, with no option (that I can find) to select which one to use.

**Describe the solution you'd like:**
The ability to pass a context name via a `--kube-context` flag to `kfctl` in the same way that other CLI tools that interact with a Kubernetes cluster support, a la `kubectl` or `helm`.

**Comment by yeya24** [comment]
I' d like to work on this.

**Comment by mattnworb** [comment]
I think this is still valid

**Comment by EKami** [comment]
Same issue here =/
