### ISSUE TITLE
Why pytorch 0.4.0 can not connect server in jupyter notebook?

### ISSUE THREAD

**Issue by Eric-Zhang1990** [kubeflow/kubeflow#3817]
/kind bug
I can run pytorch 1.0 in jupyter notebook, but can not run pytorch 0.4 and 0.4.1 in jupyter notebook. Can someone tell me why?
![深度截图_选择区域_20190804155742](https://user-images.githubusercontent.com/24602893/62421206-c79e3d80-b6d0-11e9-881d-59d80469e870.png)
(1). pytorch 1.0:
![深度截图_选择区域_20190804160419](https://user-images.githubusercontent.com/24602893/62421257-89554e00-b6d1-11e9-970f-f5fb69333324.png)
(2). pytorch 0.4.0 and 0.4.1:
![深度截图_选择区域_20190804155541](https://user-images.githubusercontent.com/24602893/62421193-8c9c0a00-b6d0-11e9-8ff9-dee1cb847f60.png)

**What did you expect to happen:**
I want to run pytorch with different version in jupyter notebook.

**Environment:**
- Kubeflow version: 0.6:
- kfctl version: (use `kfctl version`): 
- Kubernetes platform: k8s
- Kubernetes version: (use `kubectl version`): 13.3
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by jlewi** [comment]
Can you provide more detail; logs or other information that would help people reproduce the error?

**Comment by Eric-Zhang1990** [comment]
@jlewi   This is the logs. Thank you.
[logs.txt](https://github.com/kubeflow/kubeflow/files/3465570/logs.txt)

**Comment by Eric-Zhang1990** [comment]
@jlewi  This is the log of pytorch 1.0, it can run correctly.
[root@k8s-node-3 home]# kubectl logs -n kubeflow zhangshifeng-pytorch-test1-0
[I 01:17:26.988 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 01:17:27.213 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 01:17:27.217 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 01:17:27.217 NotebookApp] The Jupyter Notebook is running at:
[I 01:17:27.217 NotebookApp] http://zhangshifeng-pytorch-test1-0:8888/notebook/kubeflow/zhangshifeng-pytorch-test1/
[I 01:17:27.217 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 01:26:03.349 NotebookApp] 302 GET /notebook/kubeflow/zhangshifeng-pytorch-test1/ (10.244.7.10) 1.10ms
[E 01:26:03.453 NotebookApp] Could not open static file ''
[W 01:26:03.542 NotebookApp] 404 GET /notebook/kubeflow/zhangshifeng-pytorch-test1/static/components/react/react-dom.production.min.js (10.244.7.10) 8.76ms referer=http://192.168.112.9:8088/notebook/kubeflow/zhangshifeng-pytorch-test1/tree?
[W 01:26:03.665 NotebookApp] 404 GET /notebook/kubeflow/zhangshifeng-pytorch-test1/static/components/react/react-dom.production.min.js (10.244.1.14) 2.23ms referer=http://192.168.112.9:8088/notebook/kubeflow/zhangshifeng-pytorch-test1/tree?

**Comment by Eric-Zhang1990** [comment]
Can someone give some advise to me ? Thanks.

**Comment by jlewi** [comment]
How are you installing pytorch 0.4.0 in a notebook?

**Comment by Eric-Zhang1990** [comment]
@jlewi  I use pytorch docker image as base image, Dockerfile looks like this:

FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
RUN pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple tensorboardX==1.6.0
RUN pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple opencv-python==3.4.2.17
RUN pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple jupyter

ENV NB_PREFIX /

CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]

**Comment by jlewi** [comment]
I might suggest using `kubectl run`or a Pod to launch that container and then starting a shell in it using `kubectl exec`. Then start python and see if the import works.

It looks like you are using a GPU image. Are you running that on a machine with GPUs? I know TensorFlow will faill if you use a GPU build and try to import it on a machine without a GPU.
