### ISSUE TITLE
0.6-branch doesn't work as per install instruction

### ISSUE THREAD

**Issue by cc4i** [kubeflow/kubeflow#3818]
/kind bug

**What steps did you take and what happened:**
Customize your Amazon EKS cluster configuration before following the next step
${KUBEFLOW_SRC}/scripts/kfctl.sh apply platform

Error:
/Users/chuancc/mywork/mylabs/kubeflow/kubeflow-aws/scripts/aws/util.sh: line 26: /Users/chuancc/mywork/mylabs/kubeflow/kubeflow-aws/kfapp/aws_config/cluster_features.sh: No such file or directory

**What did you expect to happen:**
Initial kubeflow successfully.

------

Under deployment/aws/infra_configs/ cluster_features.sh wasn't there, and now it's cluster_features.yaml. Not finish yet?

**Comment by cc4i** [comment]
Or 
remove "source ${KUBEFLOW_INFRA_DIR}/cluster_features.sh" from scripts/aws/util.sh ?

**Comment by samuelthan** [comment]
Similarly, i am encountering the same issue when deploying to AWS EKS using 0.6.1 while using instruction at https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ 

Changing branch to 0.6.1

**Comment by cc4i** [comment]
cluster_features.sh was meaningless, eksctl used cluster_features.yaml  as configuration.

**Comment by Jeffwan** [comment]
cluster features options are not supported in 0.6 branches above. The major concern for us is this is EKS specific. We also want to decouple the cluster creation and kubeflow deployment. 

Let us know if you have any requirements, we can prioritize it.
