### ISSUE TITLE
Profile controller to beta

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3822]
/kind feature

**Why you need this feature:**

We need to get the profile controller to beta quality in 0.7.

We should do an API review.

See also: #3092 

We should figure out the required features and file separate issues for them (see #3654)

I think a big question is aligning terminology and implementation with the multi-tenancy story being developed in Kubernetes.

Here's the original proposal about the [multi-tenant CRD](https://docs.google.com/document/d/1hpJX5O_siMmNGMvIHvz8Pm7XOjJLz5g57XWrgwWarFw/edit#heading=h.c0uts5ftkk58) 

@johnugeorge @kkasravi I think there was a more recent doc about soft multi-tenancy. Can you provide a link.

**Comment by kkasravi** [comment]
this link: https://docs.google.com/document/d/1hpJX5O_siMmNGMvIHvz8Pm7XOjJLz5g57XWrgwWarFw/edit#heading=h.c0uts5ftkk58

**Comment by nrchakradhar** [comment]
Hi,
Can you please change the permissions so that the documents are available for general viewing.

Another question:
The Profile CRD mentions about only GCP platform support. How does it work for other platforms like AWS or the new one Arrikto?

**Comment by kkasravi** [comment]
@nrchakradhar I don't own this document - it is linked from this document https://docs.google.com/document/d/1U8RQQmTUjxgMZY05HG2f7b3KsB94BhK4Ko6aWbLNXcc/edit# see [3] in the appendix

All of the documents are found under docs in https://github.com/kubernetes-sigs/multi-tenancy

**Comment by nrchakradhar** [comment]
@kkasravi Thanks for the reference. I am able to view few documents but the exact ones referenced here still need permissions from "somebody".

**Comment by jlewi** [comment]
Bump to P0 because we need a v1beta1 controller in 0.7.

I think the immediate step is to add multi-versioning support to the controller and create a v1beta1 version of the API.

We can probably follow what @lluunn is doing for the Jupyter controller see: #3940

**Comment by kunmingg** [comment]
Currently the major diff between 
(1). our profile and 
(2). [multi-tenant CRD](https://docs.google.com/document/d/1hpJX5O_siMmNGMvIHvz8Pm7XOjJLz5g57XWrgwWarFw/edit#heading=h.c0uts5ftkk58)

is (2) intend to support multiple admins and namespaces (as lists) in tenant CR (profile).

The main concern about having lists in tenant CR is it's `anti-Declarative API` design:
`Update` becomes extra tricky as need to compare diff with previous status and delete & create resources as needed.

Our current design provide limited alignment with conditions: 
- 1:1 mapping between tenant CR and namespace
- separate tenant CR and binding CR if more users need to access same namespace.

**Comment by jlewi** [comment]
@kunmingg looks like kubeflow/kubeflow#4155 was merged; what is the remaining work?

* Are there any more PRs that need to be merged?
* Do we need to build a new docker image?
* Do we need to update kubeflow/manifests?

**Comment by kunmingg** [comment]
@jlewi I think we need 2 more major changes:
- enable finalizer: https://github.com/kubeflow/kubeflow/pull/4235
- update manifests.

**Comment by jlewi** [comment]
@kunmingg Are all the manifest changes in #493? Are we just waiting on RCs for kfctl and kubeflow/manifests?

**Comment by jlewi** [comment]
Verification:

I deployed Kubeflow with
kubeflow/kubeflow@0ba828a18ee97094a5aa24da2fe09ca75d05d15d
kubeflow/manifests@fccc0ac71efa0ca7816e4f9aa59d03d9dc6934d4
 v0.7-branch

Attached is the CRD definition

Notably the version is v1beta1

```
 version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
```

[profile-crd.yaml.txt](https://github.com/kubeflow/kubeflow/files/3767833/profile-crd.yaml.txt)

Here is the profiles deployment
[profiles-deployment.yaml.txt](https://github.com/kubeflow/kubeflow/files/3767844/profiles-deployment.yaml.txt)


The images are

```
gcr.io/kubeflow-images-public/profile-controller@sha256:f0011f9c8b73e8a26e2ea203394031104d09753f684177caf1017c15aac658f9
gcr.io/kubeflow-images-public/kfam@sha256:3b0d4be7e59a3fa5ed1d80dccc832312caa94f3b2d36682524d3afc4e45164f0
```

Which matches kubeflow/manifests#493

So marking this as verified
