### ISSUE TITLE
Make Kubeflow AWS deployment EKS unlocked

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#3827]
/kind feature

**Why you need this feature:**
Recently, I am seeing some users asking kubeflow support on self-managed kubernetes cluster on AWS. Besides that, there're so many ways to create an EKS cluster using CloudFormation, eksctl, terraform, aws cli, etc.. 

Currently, kfctl has dependencies like `eksctl` which locks users to use EKS which make users in different environment hard to use.

**Describe the solution you'd like:**
In the future release, I would suggest user to always bring cluster and just install kubeflow, rather than creating a cluster in the kfctl. This can still be supported optionally but should not be a blocker for self-managed cluster users. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by discordianfish** [comment]
I think kubeflow should be completely cloud agnostic. It's fine to require cloud-provider-controller integration like volumes and loadbalancer but I don't really understand why we have all these cloud specific installation 'flavors'. This also makes the docs redundant and hard to grasp. Ideally it would talk about (or just point to upstream docs) re/ setting up a cluster and then have generic docs that apply to all cloud environments.

**Comment by arun-gupta** [comment]
A related issue happened when trying to use eksctl 0.4.1 to create the EKS cluster. There is no need for `aws-iam-authenticator` in that case and yet `kfctl init` throws the following error:

```
INFO[0006] Writing stripped KfDef to /home/ec2-user/environment/eksworkshop-eksctl/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0006] Downloading /home/ec2-user/environment/eksworkshop-eksctl/app.yaml to /tmp/302999109/app.yaml  filename="v1alpha1/application_types.go:334"
Error: KfApp initialization failed:  (kubeflow.error): Code 500 with message: coordinator Init failed for aws:  (kubeflow.error): Code 400 with message: Could not find command aws-iam-authenticator in PATH
```
