### ISSUE TITLE
kf 0.6 - User 'xyz@abc.com' is not authorized for namespace 'kubeflow'

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#3835]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In notebook page when i select kubeflow as name space (ie already at .../_/jupyter/?ns=kubeflow) I get an error that my user 'xyz@abc.com' is not authorized for namespace 'kubeflow'. User has admin access to the GCP account

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.6.1
kfctl version: (use kfctl version): kfctl v0.6.1-rc.2-1-g3a37cbc6
Kubernetes platform: (e.g. minikube): GCP
Kubernetes version: (use kubectl version):
OS (e.g. from /etc/os-release): google cloud shell

**Comment by SinaChavoshi** [comment]
resolved by changing the name space to kubeflow-user env

**Comment by SinaChavoshi** [comment]
The name space is not selected by default  It may makes sense to set the default name space to user account. Also the documentation in kubeflow.org does not reflect the 0.6 UI this may be confusing for users to figure out.

**Comment by DanSanche** [comment]
@SinaChavoshi I'm seeing this error appear on all namespaces. Did you have to create the kubeflow-user namespace? what deployment name did you use?

**Comment by jlewi** [comment]
Closing this issue. Since it looks like it has been resolved.
