### ISSUE TITLE
jupyter-web-app: Set custom Image cmd and args

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#3838]
/kind feature

**Why you need this feature:**
Currently if someone would like to use a custom image they would need to create a Dockerfile, update the ENTRYPOINT and then push it to a public/private registry. We could skip the push step by allowing the user to set the cmd/args of their image.

This has also been requested from user's both in slack and from issues [ #2961 #3821 ]

**Describe the solution you'd like:**
The user should be able to set a custom `CMD` and/or `ARGS` for the Notebook Image.

**Comment by jlewi** [comment]
@kimwnasptd any update on this? What's the likelihood we can have this for 1.0?

**Comment by supertetelman** [comment]
I was just about to open the same issue using ubeflow version v7.0.0

**Why:**
I have worked with a lot of team members who want to use off the shelf Docker images from AWS, GCP, NGC, etc. Many of these containers contain DL frameworks they would really like to use, but don't run Jupyter by default.

It is possible to get this working with custom Dockerfile, but many of them don't want to push up to public DockerHub, want to keep their work private, and don't know (and don't want to know) command line or how to build/push a Dockerfile.

**What:**
Simply having an additional field at the bottom of the Notebook creation page that allows a custom CMD or ENTRYPOINT would satisfy this requirement. There could be a toggle to display/hide this option.


**Something like this:**
![custom_command_kubeflow](https://user-images.githubusercontent.com/1010167/70826219-3ab07280-1d9b-11ea-9e0c-be0cfb2eab6d.PNG)

**Comment by jlewi** [comment]
@kimwnasptd any update?

**Comment by kimwnasptd** [comment]
I'll start working on a PR for it right after #4288 in order to group together the work of extending JWA' form fields.

**Comment by supertetelman** [comment]
Is there a way we can just hardcode the entrypoint and startup args for all containers launched? I'm looking through the source and having trouble figuring out where I would set that until this feature is in.

**Comment by jlewi** [comment]
@supertetelman The notebook custom resource should contain a pod template spec which should allow you to set the command to be executed on startup. So the web app would just need to set that in order to override the entrypoint set in the docker image.

**Comment by Kloempi** [comment]
@kimwnasptd did you already have a chance to work on this?

**Comment by supertetelman** [comment]
> @supertetelman The notebook custom resource should contain a pod template spec which should allow you to set the command to be executed on startup. So the web app would just need to set that in order to override the entrypoint set in the docker image.

Thanks. I was able to modify that in the kustomize files, and that resolves some of the issues I've been seeing. But that still doesn't solve 100% of my use cases and passing through these values through the UI would still be ideal. I did have something doing this passthrough back in version v0.5, but it seems like a lot has changed.

**Comment by supertetelman** [comment]
Is there any way I could help out with this feature? Getting this working is currently a big deal for a lot of the customers I am dealing with who are looking to use containers from http://ngc.nvidia.com/ that are not all built to start Jupyter by default.

**Comment by supertetelman** [comment]
I'm going to bump this because I think it is an important feature to have.

Other closed-source AI Workflow platforms (CNVRG, Iguazio, Domino, ...) make it very easy to launch any container on their platforms and I think implementing this feature would be a simple way to get the same functionality.

**Comment by DavidSpek** [comment]
This seems related to my comment https://github.com/kubeflow/kubeflow/issues/2208#issuecomment-697928715, where I suggested setting the arguments directly rather than backing them into the container images.
