### ISSUE TITLE
kfctl: existing_arrikto: operate Dex and Kubeflow behind the same port (443) using relative URLs

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3839]
/kind feature

**Why you need this feature:**

Currently, Dex is exposed at port 5556.
This is a problem for some corp networks that cannot expose port 5556. (e.g. #3826 )

**Describe the solution you'd like:**

Dex could live in path /dex at port 443.
This would remove the need for exposing port 5556 and would make it even easier for people to use this feature in onprem clusters.

Instead of using absolute URLs, the authservice communication with Dex and user redirects will happen with relative URLs.
This will also make Dex work with port-forwarding and also NodePort.

**Comment by jbottum** [comment]
@yanniszark I put this in 0.7, please let me know if we need to 1.0 or other

**Comment by Kyrremann** [comment]
Is it possible to start testing this on local clusters?
I'm having a hard time setting up Kubeflow 0.6, since we don't have support for loadbalance in our cluster, but we still need to separate our users.
