### ISSUE TITLE
Cluster Autoscaling Not Working

### ISSUE THREAD

**Issue by SheharyarTkxel** [kubeflow/kubeflow#3844]
**Problem Statement**: 
I want to deploy 2 Node Groups (1st with 3 CPUs in Master, 2nd with 0 GPUs in Worker) and then scale up/down the GPU based Worker nodes as the load goes up/down.

**What I've done so far**: 
Followed the [official tutorial](https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/) to setup Kubeflow on AWS with this yaml file configuration (don't mind the formatting):

`apiVersion: eksctl.io/v1alpha5
availabilityZones: 
  - us-east-2a
  - us-east-2b
  - us-east-2c
kind: ClusterConfig
metadata: 
  name: kubeflow-gpu-aws
  region: us-east-2
  version: "1.12"
nodeGroups: 
  - 
    desiredCapacity: 3
    instanceType: t3.large
    maxSize: 3
    minSize: 1
    name: cpu-nodegroup
    volumeSize: 150
  - 
    availabilityZones: 
      - us-east-2a
    desiredCapacity: 0
    iam: 
      withAddonPolicies: 
        autoScaler: true
    instanceType: p2.xlarge
    labels: 
      k8s.amazonaws.com/accelerator: nvidia-tesla-k80
    maxSize: 3
    minSize: 0
    name: Scale-GPU
    volumeSize: 100`

After this I followed this [tutorial](https://eksworkshop.com/scaling/deploy_ca/#create-iam-policy-for-asg-1) to setup the Cluster Autoscaler. But it doesn't scale up the GPU nodes and instead gives out this message in the _kubectl describe pods_ command "**pod didn't trigger scale-up (it wouldn't fit if a new node is added)**". 

**Output of _kubectl logs -f deployment/cluster-autoscaler -n kube-system_**
![image](https://user-images.githubusercontent.com/51945960/62692044-5a005300-b9e9-11e9-9961-a2dde29d5e96.png)

**Environment:**

- Kubeflow version: v0.5-branch
- Kubernetes version: (Client=GitVersion: v1.15.0  ||  Server= v1.12.10-eks-2e569f)
- OS: CentOS VM

**Comment by Jeffwan** [comment]
More like a cluster autoscaler issue. Better to submit issue there. I am also maintainer of CA. What's the CA version?

**Comment by Jeffwan** [comment]
Let's track this issue here https://github.com/kubernetes/autoscaler/issues/2161

**Comment by SheharyarTkxel** [comment]
I'm following this tutorial, and the cluster autoscaler yaml file in it specifies this which I assume is the version:
![image](https://user-images.githubusercontent.com/51945960/62853165-ecb03300-bd04-11e9-94c4-6dac308f44ab.png)

Let me know if I am wrong and how it check the version of CA from a command.

**Comment by SheharyarTkxel** [comment]
@Jeffwan I'd appreciate if you comment on the feasibility of my scenario, if it is even possible:

**Scenario**
I want to deploy 2 Node Groups (1st with 3 CPUs in Master, 2nd with 0 GPUs in Worker) and then scale up/down the GPU based Worker nodes as the load goes up/down.

**Comment by Jeffwan** [comment]
@SheharyarTkxel Sure, that's possible and lots of user use this way. You need to create two node groups and follow CA instruction to scale from 0 for GPU nodes. you workloads should also have node affinity to choose GPU nodes. 

I will close this issue and please submit an issue to corresponding repo. If the guidance you think has a problem, submit to eksworkshop.com github. If you think there's an issue in cluster autoscaler, we can discuss the issue there https://github.com/kubernetes/autoscaler/issues

We only talk about Kubeflow related issue here.
