### ISSUE TITLE
Bootstrap server logs user credential when returning error

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3847]
/kind bug

**What steps did you take and what happened:**
When bootstrap server sends invalid KfDef to statefulset, it returns error with payload having user access token.  Bootstrap server prints it out which exposes user access token to people who have access to logs.

**What did you expect to happen:**
We should strip access token whenever we print out request payload.

**Comment by jlewi** [comment]
This method strips out secrets before writing KfDef to a file.
https://github.com/kubeflow/kubeflow/blob/5b652b18892c7b49af48ecc365b0af1080e0cb06/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L612

We should think about generalizing that method so we can reuse the same stripping logic before logging KFDef.
