### ISSUE TITLE
TFServing prototype for using GCS with service account key

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#385]
#323 add a prototype for plumbing through credentials and config needed to serve models from S3.

I'm in the process of refactoring that to turn it into a separate prototype to make it more manageable.

We should create a similar prototype for GCS. For GCS we want to be able to use a secret containing a google service account and set GOOGLE_APPLICATION_CREDENTIALS.

**Comment by jlewi** [comment]
@lluunn  This is blocked on #292 but you could pick it up once that's committed.

**Comment by lluunn** [comment]
I don't understand the goal here.
We are able to serve model from GCS now right?
@jlewi

**Comment by jlewi** [comment]
The question is how do you authenticate to GCP. 

We'd like to use a service account. But we don't want to rely on the VM's service account because multiple different pods could be running on a VM all with access to the VM service account. So in general we want the VM service account to have minimal permissions.

So the model is that users will 

- create a GCP service account
- they will then download the private key for that service account
- they will create a K8s secret from that key
- Their TF serving pods will mount the secret into the pod
-- the serving pod will set GOOGLE_APPLICATION_CREDENTIALS environment variable to tell Google client auth libraries to use the key.

So we want to update the TFServing component so that users 

- can set parameter cloud = "gcp"
- Setting cloud = "gcp" causes the TFServing pod to be modified as needed to use a service account
   - I.e. secret is mounted into the pod
   - GOOGLE_APPLICATION_CREDENTIALS environment variable is set on the pod.

**Comment by lluunn** [comment]
#416 fix it.
