### ISSUE TITLE
Azure instructions for 0.6 need to be updated (was "Katib is not a valid page" from Kubeflow Central Dashboard)

### ISSUE THREAD

**Issue by cyzhangchenya** [kubeflow/kubeflow#3850]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We try to install Kubeflow on the Azure Kubernetes Service (https://azure.microsoft.com/en-us/services/kubernetes-service/) clusters, following https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/.

We use Ambassador to do load balancing and we can open up Kubeflow Central Dashboard UI. However, both Katib (/katib/) and Artifact Store (/metadata/) are "not valid pages" when clicking them from the menu bar; others (pipeline, notebook servers) are fine.

All Katib services and pods are running fine. We did not find much useful information in their logs as well.

(btw. From https://github.com/kubeflow/kubeflow/issues/3401, do we need to set up some persistent volumes in this case?)

**What did you expect to happen:**

Katib UI can be a valid page.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```
kubectl get pods -n kubeflow
NAME                                                       READY   STATUS              RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                 1/1     Running             0          24h
admission-webhook-deployment-6b89c84c98-zx478              1/1     Running             0          24h
ambassador-858f5f49db-8h8tp                                1/1     Running             0          19m
ambassador-858f5f49db-qlvj7                                1/1     Running             0          19m
ambassador-858f5f49db-sk5fl                                1/1     Running             0          19m
application-controller-stateful-set-0                      1/1     Running             0          24h
argo-ui-5dcf5d8b4f-4bmhn                                   1/1     Running             0          24h
centraldashboard-5cf588b8d4-2q8t9                          1/1     Running             0          24h
jupyter-web-app-deployment-6b57c59bcd-gvhc2                1/1     Running             0          24h
katib-controller-88c97d85c-dvpzq                           1/1     Running             1          24h
katib-db-8598468fd8-hf2nd                                  1/1     Running             0          24h
katib-manager-574c8c67f9-pkpsz                             1/1     Running             7          24h
katib-manager-rest-778857c989-jvvxb                        1/1     Running             0          24h
katib-suggestion-bayesianoptimization-65df4d7455-j4ph2     1/1     Running             0          24h
katib-suggestion-grid-56bf69f597-m7ds8                     1/1     Running             0          24h
katib-suggestion-hyperband-7777b76cb9-gvvz9                1/1     Running             0          24h
katib-suggestion-nasrl-77f6f9458c-hqjsk                    1/1     Running             0          24h
katib-suggestion-random-77b88b5c79-tzgv9                   1/1     Running             0          24h
katib-ui-7587c5b967-jhh9f                                  1/1     Running             0          24h
metacontroller-0                                           1/1     Running             0          24h
metadata-db-5dd459cc-np4j2                                 1/1     Running             0          24h
metadata-deployment-6cf77db994-6q5vw                       1/1     Running             5          24h
metadata-deployment-6cf77db994-b9k7k                       1/1     Running             5          24h
metadata-deployment-6cf77db994-d5txh                       1/1     Running             6          24h
metadata-ui-78f5b59b56-crpjd                               1/1     Running             0          24h
minio-758b769d67-5gckl                                     0/1     ContainerCreating   0          24h
ml-pipeline-5875b9db95-jdqbs                               1/1     Running             179        24h
ml-pipeline-persistenceagent-9b69ddd46-qmbjn               0/1     CrashLoopBackOff    90         10h
ml-pipeline-scheduledworkflow-7b8d756c76-xg4ml             1/1     Running             0          24h
ml-pipeline-ui-79ffd9c76-rf7ww                             1/1     Running             0          24h
ml-pipeline-viewer-controller-deployment-5fdc87f58-g4rzd   1/1     Running             0          24h
mysql-657f87857d-lhv5d                                     0/1     ContainerCreating   0          24h
notebook-controller-deployment-56b4f59bbf-l47xd            1/1     Running             0          24h
pytorch-operator-5ff88548cc-tfsnx                          1/1     Running             0          24h
spartakus-volunteer-5fdfddb779-xzdmh                       1/1     Running             0          24h
tensorboard-6544748d94-hdzfr                               1/1     Running             0          24h
tf-job-dashboard-56f79c59dd-jfw2w                          1/1     Running             0          24h
tf-job-operator-79cbfd6dbc-cx5xm                           1/1     Running             0          24h
workflow-controller-db644d554-6rssr                        1/1     Running             0          24h
```

**Environment:**

- Kubeflow version: v0.6.1
- Minikube version: N/A
- Kubernetes version: (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`)

**Comment by xaniasd** [comment]
@cyzhangchenya @jlewi  I think this has to do with the katib-ui service manifest ([code](https://github.com/kubeflow/manifests/blob/master/katib-v1alpha2/katib-ui/base/katib-ui-service.yaml) ), it doesn't include ambassador annotations. 

Easy to fix, shall I create a PR?

**Comment by cyzhangchenya** [comment]
That would be very helpful. @xaniasd @jlewi 

Otherwise, we do not have a working solution following the official documentation https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/. Both Katib (/katib/) and Artifact Store (/metadata/) are "not valid pages" when clicking them from the menu bar; others (pipeline, notebook servers) are fine.

**Comment by jlewi** [comment]
It looks like the Azure instructions are outdated.
https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/

Kubeflow 0.6 is using ISTIO as its service mesh and gateway. So instead of exposing Ambassador

```
kubectl get svc –n kubeflow
kubectl expose svc ambassador -n kubeflow --type LoadBalancer --name <SVC_NAME>
kfctl apply k8s -V
```

You need to expose the ISTIO gateway
https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/


/cc @aronchick

**Comment by xaniasd** [comment]
@jlewi does this mean that setups without istio are not supported any more? 

FYI: I created a [PR](https://github.com/kubeflow/manifests/pull/300) solving this issue.

**Comment by jlewi** [comment]
See #3396

**Comment by vjrantal** [comment]
The Azure installation docs at https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/ are now updated. However, there is always the possibility for the "works on my machine"-syndrome so would be nice to hear if those instructions work for others as well.

> We use Ambassador 

@cyzhangchenya If above means that you must use Ambassador, above docs might not cover your needs, because they are based on using Istio.

**Comment by jlewi** [comment]
@vjrantal Than you!
