### ISSUE TITLE
[CentralDashboard v2] Cherrypick v0.6.2

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3852]
## About:
Cherrypick for v0.6.2 release w/ dashboard updates:
- [x] #3742
- [x] #3758 
- [x] #3503
- [x] #3842 
- [x] #3843

### Meta
_**closes: #3698**_
/assign @kunmingg @abhi-g 
/cc @avdaredevil 
/priority p0 
/area centraldashboard
/area front-end

**Comment by abhi-g** [comment]
By the way should this be v0.6.3 or 0.6.2? I don't think we have released v0.6.2 yet.
