### ISSUE TITLE
[spawning jupyter failed] 'kubeflow-core' is not a component or a module

### ISSUE THREAD

**Issue by AnnieWei58** [kubeflow/kubeflow#3854]
I am trying to spawn the jupyterhub, but it fails. When I try this line of code: 
> ks param set kubeflow-core jupyterNotebookPVCMount /home/jovyan/work

it gives me the following error:
> could not find component: extracting module and component names from kubeflow-core: 'kubeflow-core' is not a component or a module

**Environment:**

- Kubeflow version: v0.4.1
- kfctl version: v0.5.1
- Kubernetes platform: Kubeflow on Kubernetes
- Kubernetes version: v1.14.2
- OS: Centos7

**Comment by jbottum** [comment]
@AnnieWei58 have you tried with v0.6? What platform are you using?
