### ISSUE TITLE
pvc not detected

### ISSUE THREAD

**Issue by yptheangel** [kubeflow/kubeflow#3855]
Running the MNist example from https://www.kubeflow.org/docs/components/training/tftraining/

mnist-worker-0 is a pod created by my TFJob
when i check my pod, `kubectl -n kubeflow get po mnist-worker-0`
I get this.
![no-pvc-but-actually-do](https://user-images.githubusercontent.com/30103695/62775505-6ca68500-bada-11e9-9ddb-544da8e7a461.PNG)

 Are PVC shown in `kubectl get pvc` accessible by kubeflow tfjob pods?

**Comment by jlewi** [comment]
Can you provide the output of 

```
kubectl get tfjobs -o yaml <TFJOB>
kubectl get pods -o yaml pod
```

This doesn't look like an issue with a controller but more likely a problem with either your PVC configuration or the specification of the PVC in your pod.

Is your PVC defined in the kubeflow namespace? 

What is the output of 

```
kubectl get -n kubeflow pvc
```

I suspect the problem is you created the PVC in a different namespace from where your TFJob is running

/cc @jinchihe

**Comment by yptheangel** [comment]
@jlewi thanks for your fast reply! You are right that I should specify the namespace: kubeflow when creating the pv and pvc.

Why am I still seeing this "Mount failure" failure after `kubectl -n kubeflow describe pod mnist-worker-0` . Why is the TFJob trying to mount on a volume with the name "mypv default-token..."?
![describe-pod-mnist-worker](https://user-images.githubusercontent.com/30103695/62832753-22eaa580-bc66-11e9-9518-a9c0a573dc31.PNG)

From the screenshot of `kubectl -n kubeflow describe tfjob mnist` I saw that the TFJob ran successfully.  

![tfjob-output](https://user-images.githubusercontent.com/30103695/62832755-2aaa4a00-bc66-11e9-8bd8-cad0d6e424ca.JPG)

**Comment by jinchihe** [comment]
@yptheangel So is that OK now? If the TFJob status is succeeded, I think the related pod shoud be finished.

**Comment by yptheangel** [comment]
@jinchihe since TFJobSucceeded means successful completion, I assume that the error message can be ignored and close this issue. Thanks for the assistance @jlewi
