### ISSUE TITLE
default-editor service account is not created while starting notebook server

### ISSUE THREAD

**Issue by blublinsky** [kubeflow/kubeflow#3858]
/kind bug

**What steps did you take and what happened:**
After installing kubeflow 0.6 following https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/, creation of Notebook fails, because serviceaccount default-editor does not exist. 
Same issue is described https://github.com/kubeflow/kubeflow/issues/3232

**Environment:**
OpenShift 4.1
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.6 build version v1beta1
- kfctl version: kfctl v0.6.0-0-g71aea0a9
- Kubernetes platform: Openshift
- Kubernetes version: kubernetes v1.13.4+c62ce01

**Comment by jlewi** [comment]
@blublinsky How did you create the namespace where you are trying to launch the notebook?

The service accounts are created by the profile controller. You should create a profile resource to create your namespace and provision it with the appropriate service accounts.

There is some documentation here.
https://www.kubeflow.org/docs/other-guides/multi-user-overview/#step-2-creating-a-user-profile

/cc @kunmingg

**Comment by blublinsky** [comment]
Thanks
Missed this

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/
