### ISSUE TITLE
Kubeflow main page namespace selection

### ISSUE THREAD

**Issue by blublinsky** [kubeflow/kubeflow#3859]
/kind bug

When trying to change namespace on Kubeflow main page, the drop down of namespaces is showing behind the left blue pane, which completely obstructs the list

- Kubeflow version: 0.6
- kfctl version: kfctl v0.6.0-0-g71aea0a9
- Kubernetes platform: OpenShift
- Kubernetes version: kubernetes v1.13.4+c62ce01

**Comment by bbhuston** [comment]
Experiencing same issue when installing Kubeflow into an existing GKE cluster

Kubeflow version: 0.6.1-rc.2
kfctl version: kfctl v0.6.1-rc.2-1-g3a37cbc6
Kubernetes platform: GCP/GKE (install into existing cluster)
Kubernetes version: kubernetes v1.13.4

**Comment by bbhuston** [comment]
> Experiencing same issue when installing Kubeflow into an existing GKE cluster
> 
> Kubeflow version: 0.6.1-rc.2
> kfctl version: kfctl v0.6.1-rc.2-1-g3a37cbc6
> Kubernetes platform: GCP/GKE (install into existing cluster)
> Kubernetes version: kubernetes v1.13.4

Just tried installing with the same setup as above but using version 0.6.2-rc.2.   Same issue with namespace selection

**Comment by shawnho1018** [comment]
I encountered similar issue. However, I could not judge if the drop down of namespaces is showing behind the left blue pane. For me, the namespace selection is just not working. When I click "Select namespace", there is a only a button animation (blue color appeared on white button) but no drop-down selection at all. 

my kfctl version:  v0.6.1-rc.2-1-g3a37cbc6
kubernetes platform: Vanilla kubernetes installed from kubeadm
Kubernetes version: kubernetes v.1.15.1

**Comment by avdaredevil** [comment]
Yes, it's the same and has been resolved with the latest release. 

@shawnho1018 seems to have a different issue, and that seems to be based on no namespace list being returned to the dashboard (might be a networking / permissioning issue)

**Comment by shawnho1018** [comment]
> Yes, it's the same and has been resolved with the latest release.
> 
> @shawnho1018 seems to have a different issue, and that seems to be based on no namespace list being returned to the dashboard (might be a networking / permissioning issue)

I also suspected it was the serviceaccount issue but I don't see any error log in 
kubectl logs -n kubeflow -f centraldashboard-79df4778f7-glhfj

> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve


> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
"other" is not a supported platform for Metrics
Using Profiles service at http://10.101.82.170:8081/kfam
Server listening on port http://localhost:8082
--
As for networking, all master/worker nodes are routable to each other. Any suggestion how I could dig further?

**Comment by bbhuston** [comment]
@jlewi  @avdaredevil  Thanks for looking into this issue.  In contrast to what I previously posted, I am actually hitting the exact same issue as @shawnho1018.  (I originally has just assumed the namespace drop-down was hidden somewhere, but in fact it's not even selectable.)

Having said this, I do not believe the issue is caused by a "roll-your-own-kubernetes" networking setup that @shawnho1018 has with his kubeadm installation (because I'm hitting this on a plain-vanilla GKE cluster), nor do I believe that it was fixed in the latest release -- I am hitting this same issue even after doing a bleeding edge install of the kfctl manfests (i.e., by setting `--version="v0.6.2-rc.0"` at the `kfctl init` step). 

The steps to reproduce my exact issue on GKE are listed below

```
# Generate legacy default auth credential file for use with terraform 
gcloud auth application-default login

# Download latest terraform client, if not already present
brew install terraform

# Create terraform file that uses  [official GCP GKE module](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/4.1.0/submodules/beta-private-cluster)
cat << EOF > main.tf
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster"
  version                    = "4.1.0"
  project_id                 = "my-gcp-project"
  name                       = "my-test-cluster"
  regional                   = true
  region                     = "us-east1"
  zones                      = ["us-east1-b", "us-east1-c", "us-east1-d"]
  network                    = "default"
  subnetwork                 = "default"
  ip_range_pods              = ""
  ip_range_services          = ""
  service_account            = "my-service-acount"
  http_load_balancing        = true
  horizontal_pod_autoscaling = true
  kubernetes_dashboard       = false
  network_policy             = false
  istio                      = false
  cloudrun                   = false

  node_pools = [
    {
      name               = "default-node-pool"
      machine_type       = "n1-standard-2"
      min_count          = 1
      max_count          = 100
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = false
      service_account    = "my-service-account"
      preemptible        = false
      initial_node_count = 1
    },
  ]

  node_pools_oauth_scopes = {
    all = []
    default-node-pool = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  node_pools_labels = {
    all = {}
    default-node-pool = {
      default-node-pool = true
    }
  }

  node_pools_metadata = {
    all = {}
    default-node-pool = {
      node-pool-metadata-custom-value = "my-node-pool"
    }
  }

  node_pools_taints = {
    all = []
    default-node-pool = [
      {
        key    = "default-node-pool"
        value  = true
        effect = "PREFER_NO_SCHEDULE"
      },
    ]
  }

  node_pools_tags = {
    all = []
    default-node-pool = [
      "default-node-pool",
    ]
  }
}
EOF

# Create GKE cluster via standard terraform client commands
terraform init
terraform plan
terraform apply

### Install kubeflow into existing cluster as per official guidance ###

# download kfctl
wget -O kfctl_v0.6.1_darwin.tar.gz https://github.com/kubeflow/kubeflow/releases/download/v0.6.1/kfctl_v0.6.1_darwin.tar.gz
tar -xvf kfctl_v0.6.1_darwin.tar.gz

# create generic k8s kubeflow app
CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml"
KFAPP=my-test-app
./kfctl init ${KFAPP} --config=${CONFIG} --version="v0.6.2-rc.0" -V

# generate and deploy generic k8s kubeflow manifests
cd ${KFAPP} 
./../kfctl generate all -V
./../kfctl apply all -V

# swap out NodePort istio-ingressgateway service for LoadBalancer one (I'm unable to port-forward correctly with the NodePort service for some reason)
kubectl -n istio-system delete svc istio-ingressgateway 

cat << EOF >  istio-ingressgateway-lb.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http2":"iap-backendconfig"}}'
  labels:
    app: istio-ingressgateway
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    # nodePort: 30513
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    # nodePort: 31380
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    # nodePort: 31390
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcp
    # nodePort: 31400
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: https-kiali
    # nodePort: 30453
    port: 15029
    protocol: TCP
    targetPort: 15029
  - name: https-prometheus
    # nodePort: 30584
    port: 15030
    protocol: TCP
    targetPort: 15030
  - name: https-grafana
    # nodePort: 31827
    port: 15031
    protocol: TCP
    targetPort: 15031
  - name: https-tracing
    # nodePort: 32653
    port: 15032
    protocol: TCP
    targetPort: 15032
  - name: tls
    # nodePort: 31118
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  sessionAffinity: None
  type: LoadBalancer
EOF

kubectl apply -f istio-ingressgateway-lb.yaml

# port-forward istio-ingressgateway and navigate to central dashboard
kubectl -n istio-system port-forward svc/istio-ingressgateway 8080:80 &
echo 'navigating to "http://localhost:8080/" takes one to the central dashboard and namespaces are unselectable'

# nuke cluster
terraform destroy
rm -rf .terraform/ && rm terraform.*
echo "Peace!  I'm out"
```

**Comment by deepdad** [comment]
I don't see the dropdown. Using minikube. Is there a workaround to create a notebook server + namespace?

**Comment by shawnho1018** [comment]
> I don't see the dropdown. It is just stuck.
> <img alt="Screenshot 2019-08-12 at 15 13 31" width="447" src="https://user-images.githubusercontent.com/22483621/62867596-f0978180-bd13-11e9-9a8a-81f99be6ef60.png">
> Using minikube on a Mac. Is there a workaround to create a notebook server + namespace?
@deepdad  where do you see the error log? Could you point to me? 
My symptom looks the same like yours. I am waiting for @avdaredevil  and @jlewi but it would be nice to diagnose if my error is the same as yours.

**Comment by deepdad** [comment]
That's in the browser @shawnho1018 developer tools
It may also be that I don't share the /Users folder with Virtualbox. That has too much access rights.
For the rest here's a history, it has some tiny differences with the docs (no ambassador, forwarding is different and this combines tow pages of the docs but I didn't change any of the files while it is sometimes the case that the `minikube ip` is hard coded in K8 files):

 ```
cd kubeflow/
 export KUBEFLOW_TAG=v0.6.0
 curl -O https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/setup-minikube.sh
nano setup-minikube.sh 
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.3.0/minikube-darwin-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
kv=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
curl -Lo kubectl   https://storage.googleapis.com/kubernetes-release/release/$kv/bin/linux/amd64/kubectl   && sudo install kubectl /usr/local/bin/
-LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
sudo install kubectl /usr/local/bin/
mkdir kubeflowapp
export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml"
export KFAPP="kubeflowapp"
./kfctl init ${KFAPP} --config=${CONFIG} -V
./kfctl generate all -V
./kfctl apply all -V
minikube start --cpus 4 --memory 8096 --disk-size=50g
./kfctl apply all -V
kubectl -n kubeflow get  all
opsys=darwin
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |  grep browser_download |  grep $opsys |  cut -d '"' -f 4 |  xargs curl -O -L
mv kustomize/kustomize_3.1.0_darwin_amd64 kustomize/kustomize
chmod u+x kustomize/kustomize 
kubectl -n kubeflow get  all
kubectl get all -n istio-system
export NAMESPACE=istio-system
kubectl port-forward svc/istio-ingressgateway -n ${NAMESPACE} 8080:80
```

**Comment by deepdad** [comment]
This bug is linked to this code:

```
return C=function(){return e},e}
window.customElements.define("namespace-selector", 
  class extends a.a{
    static get template(){
      return Object(a.b)(C())
    }
    static get properties(){
      return { 
        queryParams:Object,namespaces:Array,selected {        
          type:String,observer:"_onSelected", value:"", notify:!0
        }, allNamespaces:{
          type:Boolean,value: !1
        }, selectedNamespaceIsOwned:{          
          type:Boolean, readOnly: !0, notify:!0, value:!1
        }
      }
    } static get observers(){
      return["_queryParamChanged(queryParams.ns)","_ownedContextChanged(namespaces, selected)"]
  }  isOwner(e){
    return"owner"==e
  } getNamespaceText(e,n){
    return n?"All Namespaces":e||"Select namespace"
 }
 _queryParamChanged(e){
   e&&this.selected!==e&&(this.selected=e)
  }
 _ownedContextChanged(e,n){
   const t=(e||[]).find(e=>e.namespace==n)||this.selectedNamespaceIsOwned;this
```
It doesn't say much I guess.

**Comment by avdaredevil** [comment]
Hey all, could you try checking the following:
- In the `Networks tab` in chrome debugger, can you send the responses / statuses recieved for `/api/has-workgroup` and `/api/env-info`
- In your console run:
  ```js
  JSON.stringify(document.querySelector("main-page").shadowRoot.querySelector("namespace-selector").namespaces)
  ```

**Comment by shawnho1018** [comment]
I tested using your script on console but get empty response. 

![image](https://user-images.githubusercontent.com/28553789/62897292-d48de300-bd07-11e9-9eee-db29f04314f4.png)

**Comment by avdaredevil** [comment]
Okay this helps, so the dashboard server is unable to see any namespaces for your user. If you hover your mouse over your version (as shown below):

<p align="center"><img src='https://user-images.githubusercontent.com/5303018/62902760-736d0c00-bd15-11e9-98b8-b13d210a9277.png' width=400></p>

Can you send a snapshot of what that looks like?

Also, try running `/api/workgroup/exists` instead of the `/api/has-workgroup`

**Comment by shawnho1018** [comment]
@avdaredevil 
1. Mine is v0.0.2-655831
![image](https://user-images.githubusercontent.com/28553789/62902990-29d0f100-bd16-11e9-8d08-c44af8afe63e.png)
2. Not sure the meaning of the returned value but it does return. 
![image](https://user-images.githubusercontent.com/28553789/62903141-977d1d00-bd16-11e9-8207-7ffe211bfc86.png)

**Comment by avdaredevil** [comment]
Awesome! Thanks for the quick replies @shawnho1018.

For context, the `/api/workgroup/exists` route allows the dashboard to quickly realize if you have IAP / OAuth headers, and if so do you have a workgroup (synonymous with a namespace for now) deployed.

Essentially from this, the dashboard concludes that the IsolationMode (for namespaces) is based on:
- Single-User: Every user is a cluster-admin, and everyone sees the same list of namespaces
- Multi-User: Each user is scoped to the namespaces they have access to (as owner or contributor), and if you don't own a namespace, initiate the registration-view.

**Comment by shawnho1018** [comment]
In that case, since I am the single user, shouldn't I simply see the all namespaces in the cluster? Still scratch my head without knowning how I could resolve this issue. Need a bit more guidance from you @avdaredevil

**Comment by avdaredevil** [comment]
Okay, so it seems you have no WorkgroupBindings in your network. Essentially the kfam-controller is giving the dashboard a list of 0 bindings. This is unusual to me as some system namespaces should have been created thus some bindings would exist for those. This part gets a little past my understanding of the backend. 

I'd suggest pinging @lluunn and @kunmingg on Slack regarding a deeper understanding as to why kfam has no bindings.

Hope that helps?

**Comment by yanniszark** [comment]
I also confirm this bug.

My understanding is that this is a blocker for v0.6.2.
The Dashboard lists user bindings for the namespace and gets nothing back, which makes the Central Dashboard not work without the GCP IAP Headers.

/priority p0
cc @jlewi

**Comment by kunmingg** [comment]
Is this use non-GCP + new-central-dashboard?
We can create a default public profile for this case to save user effort.

**Comment by blublinsky** [comment]
In my case, the list of namespaces is coming back. It is just unusable, being obstructed by left hand panel
Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by yanniszark** [comment]
> Is this use non-GCP + new-central-dashboard?

Yes, it says platform Openshift.

>  We can create a default public profile for this case to save user effort.

From what I know, the default profile creation currently only happens for GCP. 

I believe it's important to understand what @avdaredevil was expecting to find but didn't.

**Comment by jlewi** [comment]
@blublinsky I think the issue with the namespace selector being obstructed is a different issue; #3698.

@avdaredevil @kunmingg Why isn't the WorkGroupBindings populated? is it because of

1. The request has no ID headers; identifying the user?
1. No profiles were created?
1. Something else?

Can you provide some troubleshooting instructions to diagnose where the problem is ?

**Comment by avdaredevil** [comment]
@yanniszark Essentially workgroups are 1:1 constructs to a namespace. A workgroup holds permissioning data for a namespace. Now there are two cases:

### IAP / Other Header based auth (non-GCP)
- Scan the UserID headers
- Ascertain User-identity
- Dashboard changes view to multi-user isolation mode
  - Scope namespaces based on bindings (workgroup bindings) that that user has access to.

### Basic Auth / Unsecured Network
- Query all bindings (every single one) from kfam (this was requested by @kunmingg and @abhi-g over using Kubernetes controller to get the list of all namespaces)
- Loop over all bindings, de-duplicate the list by name.
- ORM the data for visual purposes only:
  - Change `role` in each binding to `contributor` (edit access)
  - Change `user` in each binding to `anonymous@kubeflow.org`

**Comment by yanniszark** [comment]
I found a way to fix this.
It seems that by default, the CentralDashboard assumes the Profile KFAM Service is at localhost:8084

https://github.com/kubeflow/kubeflow/blob/7c0932a117f2f2dc232271992d0348c4747021eb/components/centraldashboard/app/server.ts#L21-L22

Changing this to profiles-kfam and 8081 seems to fix the problem, as the selector is populated.
@avdaredevil why is the default address localhost:8084?
Can we make it profiles-kfam:8081 instead?

**Comment by fediazgon** [comment]
@yanniszark Is there a way to patch a running deployment?

**Comment by avdaredevil** [comment]
You can change the environment variables passed to CentralDashboard so that it uses the new values

This can be done by editing the YAML in cloud console

**Comment by shawnho1018** [comment]
> > Is this use non-GCP + new-central-dashboard?
> 
> Yes, it says platform Openshift.
Not for me. My environment is raw installation from kubeadm (with Calico as CNI). My k8s version is 1.15.1. 
> 
> > We can create a default public profile for this case to save user effort.
> 
> From what I know, the default profile creation currently only happens for GCP.
> 
> I believe it's important to understand what @avdaredevil was expecting to find but didn't.
> In addition, making a Profile doesn't fix it for me.

**Comment by prodonjs** [comment]
The issue results from the fact that during the initial deployment, the `centraldashboard` Deployment is created before the `profiles-service`. Thus, the PROFILES_KFAM_SERVICE_HOST and PROFILES_KFAM_SERVICE_PORT are not set by Kubernetes so the dashboard falls back to the default value of localhost.

The easiest way to address the issue in a running deployment is to manually delete the centraldashboard pod and allow the Deployment to recreate it. The new Pod will be created with the appropriate environment variables set and will use it to establish the connection to the Profiles backend.

**Comment by shawnho1018** [comment]
> The issue results from the fact that during the initial deployment, the `centraldashboard` Deployment is created before the `profiles-service`. Thus, the PROFILES_KFAM_SERVICE_HOST and PROFILES_KFAM_SERVICE_PORT are not set by Kubernetes so the dashboard falls back to the default value of localhost.
> 
> The easiest way to address the issue in a running deployment is to manually delete the centraldashboard pod and allow the Deployment to recreate it. The new Pod will be created with the appropriate environment variables set and will use it to establish the connection to the Profiles backend.

I followed your step to delete the centraldashboard pod but the problem remains.

**Comment by prodonjs** [comment]
Can you share the image URI from your centraldashboard deployment as well as output from `kubectl logs deployment/centraldashboard`?

**Comment by shawnho1018** [comment]
> Can you share the image URI from your centraldashboard deployment as well as output from `kubectl logs deployment/centraldashboard`?
![image](https://user-images.githubusercontent.com/28553789/62972229-6bba6f80-bdc8-11e9-815c-7849fa5e6922.png)

this is my log after a newly initiated pod:
root@ansible:~/kubeadm-ansible# kubectl logs -f centraldashboard-79df4778f7-rnlpm  -n kubeflow
kubeflow-centraldashboard@0.0.2 start /app
npm run serve


kubeflow-centraldashboard@0.0.2 serve /app
node dist/server.js

Initializing Kubernetes configuration
"other" is not a supported platform for Metrics
Using Profiles service at http://10.101.82.170:8081/kfam
Server listening on port http://localhost:8082

**Comment by prodonjs** [comment]
Interesting. The Pod definitely picked up the environment variables and should be able to establish communication with the profiles API server. That doesn't seem to be the problem here, but it is a general issue we need to address.

I'm out of my depth at this point. Passing it back to @avdaredevil to dig in a little further.

**Comment by avdaredevil** [comment]
@shawnho1018 Your problem arises on a different step I believe. Your network may not have any bindings at all. The recommended way to create this workgroup/profile is to do this via kfctl for now (in non-identity networks, such as yours).

**_Easier, but may not work approach_**: We could fool the dashboard into thinking you are in multi-user and trigger a registration flow by running (in your Dev Console on Central-Dashboard):

```js
document.querySelector("main-page")._setRegistrationFlow(true)
```

**Comment by jlewi** [comment]
@prodonjs Can you open an issue about the environment variables. If we're dependent on the order of deployment that seems like a bug. The central dashboard should be community with the KFAM backend via the DNS name established by the virutal service and service defined for the backend. Those should be deterministic based on the kustomize packages.

**Comment by jlewi** [comment]
@avdaredevil @kunmingg 

Can we reproduce this issue; IIUC we should be able to reproduce it by installing on an existing GKE cluster.

Are these changes related to the addition of the kfam API? 

It looks like people are hitting this issue now with 0.6.1 which should not be picking up the KFAM API changes.

My guess is that the configs somewhere are not sufficiently pinned so people using releases prior to 0.6.2 are picking up some cherry picks.

if so; do we need to roll back some changes until we've tested further?

**Comment by jlewi** [comment]
Here's my summary of the issue so far

1. The original issue on the thread is the namespace UI selection being half hidden which is #3698
    * This should potentially be fixed by the latest central dashboard image

1. A secondary issue that people are reporting is that they are not seeing any namespaces

    * This appears to be due to the fact that they are picking up the latest central dashboard image
       which is now talking to the KFam API to identify which namespaces to display

    * It seems like there are two issues here

       i) central dashboard may not be configured with the proper IP address of the KFam API
      ii) They may not be creating any profiles so not have any namespaces which they can access

1. Users of v0.6.1 are picking up the central dashboard changes because our configs are not pinned to specific commits by

     * kfctl_gcp_iap.yaml on v0.6 branch  is pulling in master of kubeflow/manifests
https://github.com/kubeflow/kubeflow/blob/55d9d6dc1f8d5274e0d35e25655fc634637958e2/bootstrap/config/kfctl_gcp_iap.yaml#L298

     * kfctl_k8s_istio.yaml is pulling the latest of kubeflow/manifests/v0.6-branch
https://github.com/kubeflow/kubeflow/blob/55d9d6dc1f8d5274e0d35e25655fc634637958e2/bootstrap/config/kfctl_k8s_istio.yaml#L148

    * It looks like the v0.6 branch and also master were recently updated to pull in the new central dashboard image (see kubeflow/manifests#265)

Suggested Mitigation 

* The new central dasbhoard UI functionality needs more testing and probably documentation before  we give it to users

* Users not using an RC should not be picking up the new dashboard

* We should pin kubeflowmanifests on v0.6-branch to kubeflow/manifests commit before the update to central dashboard image

What do folks think?

@yanniszark I think you were working on a PR to pin the kubeflow/manifests used on the v0.6-branch?

**Comment by yanniszark** [comment]
@jlewi the PR got merged and fixed it.
It seems that it was broken by this PR: https://github.com/kubeflow/kubeflow/pull/3892
cc @kunmingg

**Comment by jlewi** [comment]
@yanniszark Which PR was the fix? And how did #3892 fix it?

**Comment by yanniszark** [comment]
Sorry, I forgot to mention.
#3867 fixed the issue and pinned all configs to v0.6-branch, but #3892 pinned some configs to master again.
However, getting https://github.com/kubeflow/kubeflow/pull/3894 merged should again pin everything to a specific tag.

**Comment by jlewi** [comment]
@shawnho1018 configs should now pin to an earlier version of kubeflow/manifests which should avoid picking up the changes to the central dashboard

I think that means you won't get the fix for the namespace selector being obscured fix.

#3893 is tracking verifying all the auth scenarios work with 0.6.2
.

**Comment by deepdad** [comment]
I don't really follow the pinning. Repeating the commands that previously worked no longer do. The output looks different. Ending with `couldn't create KfApp:  (kubeflow.error): Code 400 with message: invalid name due to a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'm
`.

**Comment by jlewi** [comment]
@deepdad I think you deleted/or hid you comment

> I don't really follow the pinning. Repeating the commands that previously worked no longer do. The output looks different. Ending with couldn't create KfApp: (kubeflow.error): Code 400 with message: invalid name due to a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'm .

What did you give as the name for your KFAapp? I think the problem is your name isn't valid so you probably just need to fix the name.

**Comment by beatgeek** [comment]
Seeing this same issue on build version v0.6.2-rc.0 with a deployment to existing cluster. (BTW the docs reference a port-forward using the ambassador service but there is no such service it's istio-ingress).

**Comment by bbhuston** [comment]
> Seeing this same issue on build version v0.6.2-rc.0 with a deployment to existing cluster. (BTW the docs reference a port-forward using the ambassador service but there is no such service it's istio-ingress).
> 
> GPC GKE - install on existing cluster

I'm still experiencing the same issue as @beatgeek.   I tried installing `v0.6.2-rc.0` into an existing GKE cluster with no luck.  The exact code I used to hit this error is listed here -- https://github.com/kubeflow/kubeflow/issues/3859#issuecomment-520231946

**Comment by avdaredevil** [comment]
Central Dashboard was updated to surface any errors: https://github.com/kubeflow/kubeflow/pull/3933 [[image-pr](https://github.com/kubeflow/manifests/pull/282)].

**Comment by sylus** [comment]
This is also still happening to me launching latest central dashboard and 0.6.2-rc.1. Is anyone actually able to use a release recently?

**Comment by sylus** [comment]
Tried again against 0.6.2-rc.2 and latest centralsdashboard but namespace is still empty.

Is there anyway to make this work or have to wait for full 0.6.2 release?

![Capture](https://user-images.githubusercontent.com/984304/63595170-47a81c80-c586-11e9-840f-de63d9d8649e.PNG)

**Comment by jlewi** [comment]
@avdaredevil The original problem reported in this issue was that the namespace selector was obscured by the left blue pane.

Has that issue been fixed? If so lets go ahead and close this issue.

**Comment by avdaredevil** [comment]
Yeah that issue was fixed quite a few weeks back

/close
