### ISSUE TITLE
Roles used for operators do not allow operations on finalizers

### ISSUE THREAD

**Issue by blublinsky** [kubeflow/kubeflow#3861]
/kind bug
Roles used for operators, for example, notebook-controller-role, does not list .../finalizers, for example, notebooks/finalizers

https://github.com/kubeflow/kubeflow/issues/3086

**Environment:**

- Kubeflow version: 0.6
- kfctl version: kfctl v0.6.0-0-g71aea0a9
- Kubernetes platform: OpenShift
- Kubernetes version: kubernetes v1.13.4+c62ce01

These roles has to be extended as follows:

  - verbs:
      - '*'
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
      - notebooks/status
      - notebooks/finalizers

**Comment by jlewi** [comment]
@blublinsky Any interest in submitting PRs to fix this?

You can find the manifests defined in
https://github.com/kubeflow/manifests

**Comment by blublinsky** [comment]
You are talking about this: https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base/cluster-role.yaml#L31 <https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base/cluster-role.yaml#L31>
Right?

If I am correct - sure


Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by jlewi** [comment]
@blublinsky Any interest in fixing this for 0.7?

**Comment by blublinsky** [comment]
Its right here
https://github.com/kubeflow/manifests/pull/276 <https://github.com/kubeflow/manifests/pull/276>

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by blublinsky** [comment]
Nothing changes for 0.7

**Comment by jlewi** [comment]
@blublinsky is this fixed by kubeflow/manifests#612 ?

**Comment by blublinsky** [comment]
Yes
Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/
