### ISSUE TITLE
[CentralDashboard v2] Default namespace to OwnedNamespace or Kubeflow

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3863]
## About:
`Select namespace` as a state makes little sense as it:
- Causes unnecessary User Interactions on the dashboard
- Leads to an uneven UX for sub-apps that don't handle a non-selected namespace

### Meta:
/kind feature
/priority p1
/area centraldashboard
/area front-end
/assign @avdaredevil 
/cc @kimwnasptd @prodonjs

**Comment by jlewi** [comment]
@avdaredevil might have a fix by end of week.
