### ISSUE TITLE
Enable istio-injection in kubeflow namespace

### ISSUE THREAD

**Issue by tmc** [kubeflow/kubeflow#3866]
I expected the istio flag would enable istio for kubeflow components and not just the profile namespaces that are created.

The motivation here is that for observability, security and compliance reasons I'd like all GKE workloads to flow through Istio.

Initial experimentation here seems to indicate traffic to the dbs is interrupted when injection+sidecars are in place for the kubeflow namespace.

**Comment by jlewi** [comment]
@tmc Can you please elaborate? Which DB traffic is interrupted? And why do you think adding the istio side cars to pods in the Kubeflow namespace will fix this?

**Comment by tmc** [comment]
> @tmc Can you please elaborate? Which DB traffic is interrupted? And why do you think adding the istio side cars to pods in the Kubeflow namespace will fix this?

When enabling istio-injection on the kubeflow namespace, after restarting all the pods I have mysql client connectivity issues from the metadata-deployment pod (to the metadata-db pod).

**Comment by jlewi** [comment]
Thanks @tmc. Could you explain your motivation for turning on ISTIO in the Kubeflow namespace? Are you trying to restrict access to Kubeflow services? Enforce quotas? etc...

/cc @krishnadurai @zhenghuiwang @lluunn

**Comment by tmc** [comment]
@jlewi as part of our compliance controls we require all in-cluster traffic (when possible) to be protected by mTLS and to flow through Istio.

**Comment by yanniszark** [comment]
Looking around a little bit, it seems that there are some challenges using Istio with Stateful Services:
https://github.com/istio/istio/issues/10659

@tmc maybe you're bumping in this issue?

**Comment by tmc** [comment]
> Looking around a little bit, it seems that there are some challenges using Istio with Stateful Services:
> [istio/istio#10659](https://github.com/istio/istio/issues/10659)
> 
> @tmc maybe you're bumping into this issue?

Kubeflow, AFAIK doesn't utilize StatefulSets so I don't think that issue is relevant.

**Comment by krishnadurai** [comment]
@tmc the current configs for Kubeflow are not set up for an Istio enabled kubeflow namespace. Depending on the deployment you must have used, the cluster RBAC policy could have been set 'ON' for the entire cluster and hence when you apply Istio sidecars to pods kubeflow namespace, requests might have been filtered by istio-proxy.
Can you please check if cluster RbacConfig Mode is 'ON' for the entire cluster?
If that's the reason, we might have to define a new cluster RBAC policy with ['ON_WITH_EXCLUSION'](https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#RbacConfig-Mode) and 'kubeflow' being excluded. This suggestion is a work-around.

**Comment by tmc** [comment]
@krishnadurai This was a pretty vanilla install into a GKE cluster with the Istio addon enabled.

version: 0.6.1,
config: kfctl_k8s_istio.yaml (without istio installation)
ClusterRbacConfig: ON

Changing it to OFF does indeed bring all pods up successfully!

**Comment by krishnadurai** [comment]
Thanks for verifying!

**Comment by ryandawsonuk** [comment]
Could anyone explain how you set ClusterRbacConfig to OFF? I am also hitting issues communication issues (on non-kubeflow services) in a cluster with kubeflow installed. I can see [some parameters in the code](https://github.com/kubeflow/kfctl/search?q=ClusterRbacConfig&unscoped_q=ClusterRbacConfig) but not sure how you set them.

**Comment by krishnadurai** [comment]
@ryandawsonuk you could edit using:
```
kubectl edit clusterrbacconfig default
```

**Comment by ryandawsonuk** [comment]
Good point, thanks

**Comment by jlewi** [comment]
The current behavior for the Kubeflow namespace is no istio side car injection. We achieve this by not adding the label

```
 istio-injection: enabled
```

To the namespace. Unfortunately this means the ISTIO mutating web hook isn't enabled for any pods in the kubeflow namespace so we can't selectively enable it for specific services.

So I think we should change the default behavior

* Add "istio-injection: enabled" to the kubeflow namespace.
* Add the label to disable istio injection in all of our existing services in the Kubeflow namespace 
   * This way we preserve the current behavior of having ISTIO side car injection disabled by default.

**Comment by jlewi** [comment]
@Bobgy Lets not mark this as fixed until after #131 and we have done some manual verification on master that everything is working.

The xgboost_synthetic example is a good manual smoke test.

I think we should target this for 1.1 I don't think we should try to enable it in 1.0.

**Comment by Bobgy** [comment]
@jlewi Thanks, sounds good to me.
KFP must enable multi user mode at the same time as this change. Otherwise, workflows in kubeflow ns may fail due to injected sidecar.

**Comment by xaniasd** [comment]
I would like to better understand why istio-injection is disabled by default for kubeflow components. Is it historical reasons? Aren't kubeflow components as part of the mesh? To put it differently, are there specific reasons not to use it?

Enhancing observability is a good enough reason to enable istio, but we can make good use of its other features as well (since it's there). 

about the original question, I had to disable mTLS for the mysql service to resolve connectivity issues (see [here](https://istio.io/faq/security/#mysql-with-mtls) for details). Hope this helps

**Comment by Bobgy** [comment]
@xaniasd I guess I misunderstood what observability means in this context. Can you elaborate on "Enhancing observability"? I thought putting a service into the mesh only decreases its observability (because only workloads with RBAC authorization can access it).

**Comment by xaniasd** [comment]
Hi @Bobgy I mean the ability to better understand what's going on in the system. For instance are there any network bottlenecks, is a component slow or unresponsive. This sort of fhings. So if my system does not perform as expected, I'd like to have the means to get useful insights about the internal state.

Components in the Control Plane (such as controllers) aren't necessarily in scope, but some Kubeflow components do participate in the actual computational work so in my view they should be      included. 

Does this make sense?

I think your work is in the right direction by the way, if I can help somehow please let me know.

**Comment by Bobgy** [comment]
@xaniasd I see, that makes sense to me now. Thanks for the explanation!

I'm currently busy with other things, it would be helpful if you can investigate why tests are failing in https://github.com/kubeflow/kfctl/pull/131.

**Comment by Bobgy** [comment]
I'm resuming to work on this. Blocker I met: https://github.com/kubeflow/kfctl/pull/131#issuecomment-593752785

tfjob workloads in kubeflow namespace also need to explicitly disable sidecar injection.

**Comment by kunmingg** [comment]
@Bobgy 
Can you add which test is failing?

**Comment by Bobgy** [comment]
`smoke-tfjob-kfctl-gcp-iap` timed out, but I cannot find exactly logs in those pods

**Comment by jlewi** [comment]
> Therefore, I propose to change cluster level default value to not inject sidecars and add the enable sidecar annotation for all workloads that has migrated to use istio sidecar.

I would prefer not to change the cluster level default.

Every since Kubeflow added multi-user support the only thing that should be running in the kubeflow namespace should be the shared services that get deployed when Kubeflow is deployed.

So there shouldn't be dynamic services (e.g. TFJobs) running in the kubeflow namespace. The exception was pipelines but the goal of this work is to move pipelines into namespaces other than kubeflow.

So can we stick with the original plan of adding annotations to individual services in the Kubeflow namespace that need the side car disabled to preserve existing behavior?

It sounds like the current issue is not the services themselves but a TFJob that's created by an existing test. So it looks like an existing test just needs to be updated to work with this change.

**Comment by Bobgy** [comment]
Sounds good with the high level plan as long as dynamic workloads are not in kubeflow namespace.
Then I will
* try to patch the TFJob test
* update KFP to always add istio sidecar disabled before multi user mode is completely turned on

**Comment by Bobgy** [comment]
@jlewi Tests are finally passing now.
Can I confirm with you our next step plans?

* I have merged disable istio sidecar change https://github.com/kubeflow/pipelines/pull/3305 into kubeflow/pipelines.
* After next KFP release, I will submit a PR to upgrade KFP version in Kubeflow
* After that, we can merge this kfctl change without breaking existing KFP usage

**Comment by Bobgy** [comment]
/reopen
because https://github.com/kubeflow/kfctl/issues/296 was reverted

**Comment by Bobgy** [comment]
The new proposed solution is in https://github.com/kubeflow/kfctl/issues/296#issuecomment-621696080
