### ISSUE TITLE
kfctl: existing_arrikto: cherry-pick 3760, 3857, 3885 for v0.6.2

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3868]
#3760 #3857 #3885 

PRs for cherry pick:
- [x] #3955 cherry picks #3885
- [ ] #3884 cherry picks #3857 
- [X] #3760 was cherry picked in v0.6.2, but it wasn't in master yet. Since the PR went in without further changes, is it ok to keep it like this @jlewi ?

/priority p0

**Comment by gabrielwen** [comment]
@yanniszark should we close this?

**Comment by yanniszark** [comment]
@gabrielwen #3884 is not merged yet.
In addition #3885 must be merged in order to create a cherry pick.
