### ISSUE TITLE
Newest-to-oldest TF image option list in UI config?

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#3869]
I wonder if we should reverse the order of the tensorflow image options here?

https://github.com/kubeflow/kubeflow/blob/c06470dbe14e94b17faa4ae7473fe9150e7fc129/kubeflow/jupyter/ui/rok/config.yaml#L15

**Comment by kimwnasptd** [comment]
AFAIK the code under kubeflow/kubeflow was the ksonnet packages. These are not used anymore now that we've migrated to kustomize.

**Comment by pdmack** [comment]
Where is the list being generated from then?

**Comment by kimwnasptd** [comment]
from this [yaml](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/config-map.yaml) in the manifests repo
