### ISSUE TITLE
KF 0.6: 'configurations' missing from spawner_ui_config.yaml

### ISSUE THREAD

**Issue by abbyearnin** [kubeflow/kubeflow#3873]
/kind bug

**What steps did you take and what happened:**
Posting this to help others who may face this issue + hopefully get a quick fix on this
@kimwnasptd 

I deployed Kubeflow 0.6 by following the ISTIO method (https://master.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)

Most things deployed correctly, but trying to create a server in the Jupyter web app was throwing a Key Error for `defaults['configurations']` . I found the fix as well, just simply added an empty value for that key in the spawner_ui_config.yaml for example:

`  configurations:\n    # fake input to bypass error\n    value: \"[]\"\n`

Thanks

**Comment by kimwnasptd** [comment]
hi @abbyearnin 

By taking a look at the [kfctl_k8s_istio.yaml](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml) I see that it uses this uri for the manifests:
```
https://github.com/kubeflow/manifests/archive/master.tar.gz
```

When I untar it, the config that gets deployed for the jupyter-web-app (`manifests-master/jupyter/jupyter-web-app/base/config-map.yaml`) has this key.

Was the cluster that you used kfctl on a clean one or did it have a previous installation of kubeflow?
