### ISSUE TITLE
fix 'pipeline-runner' role to allow creation of VirtualServices

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#3874]
/kind bug
KF 0.6.1

When I try to create a VirtualService from a pipeline step, I get this error: 
`Error from server (Forbidden): error when creating "/ml/t2tapp.yaml": virtualservices.networking.istio.io is forbidden: User "system:serviceaccount:kubeflow:pipeline-runner" cannot create resource "virtualservices" in API group "networking.istio.io" in the namespace "kubeflow".`

I'm guessing that this file (or similar) needs to be updated: https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pipeline/pipeline-apiserver.libsonnet

(A workaround is to do something like this from the command line:
`kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=kubeflow:pipeline-runner`)

**Comment by amygdala** [comment]
Just bumping this in case there's another point release it could be folded into, as currently our workshop attendees will need to run the above command-line fix after c2d GUI setup.

**Comment by jlewi** [comment]
kubeflow/manifests#396 is about creating the roles "kubeflow-edit",  "kubeflow-view", "kubeflow-admin".

These roles are defined here:
https://github.com/kubeflow/manifests/tree/master/kubeflow-roles

In the profile created namespaces there will be edit and view service accounts for kubeflow that will be bound to these roles.

There is a couple mitigating factors with pipelines with respect to leveraging this to address the issue @amygdala is raising.

Right now pipelines are running in the kubeflow namespace and not the profile created namespace. So we will not have the profile created service accounts in the kubeflow namespace and we can't just run the pipeline steps using that service account.

One option would be to create a role binding between the pipeline runner service account and the kubeflow-edit cluster role. This way pipeline steps would have all the permissions kubeflow users should have in terms of resource creation.

**Comment by amygdala** [comment]
Let's keep this open... last I checked, it was still necessary to run the command-line workaround as part of codelab(s), which is not optimal.

**Comment by jlewi** [comment]
Related: kubeflow/manifests#891

**Comment by Bobgy** [comment]
This was already resolved in https://github.com/kubeflow/manifests/issues/891
/close
