### ISSUE TITLE
presubmit failures; required node image not available

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3886]
/kind bug

I'm seeing presubmit failures on  PR: #3824 . This PR is just updating the ROADMAP so unlikely related to that PR.

The failure I'm seeing is

```
util.py                     71 INFO     time="2019-08-13T13:14:28Z" level=error msg="Creating kfctl-46c6 error: &{Code:RESOURCE_ERROR Location:/deployment
s/kfctl-46c6/resources/kfctl-46c6 Message:{\"ResourceType\":\"gcp-types/container-v1beta1:projects.locations.clusters\",\"ResourceErrorCode\":\"400\",\"Re
sourceErrorMessage\":{\"code\":400,\"message\":\"The required node image is not available.\",\"status\":\"INVALID_ARGUMENT\",\"statusMessage\":\"Bad Reque
st\",\"requestPath\":\"https://container.googleapis.com/v1beta1/projects/kubeflow-ci-deployment/locations/us-east1-d/clusters\",\"httpMethod\":\"POST\"}}
ForceSendFields:[] NullFields:[]}" filename="gcp/gcp.go:348"
util.py                     71 INFO     Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflo
w.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Creating kfctl-46c6 erro
r(400): BAD REQUEST
```

spyglass [link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3824/kubeflow-presubmit/1161261200583954437/)

**Comment by jlewi** [comment]
Someone is hitting a similar error trying to customize their GKE deployment
kubeflow/website#1065

**Comment by jlewi** [comment]
The error `The required node image is not available` should indicate cluster creation failed because we are trying to use a VM image which doesn't exist. 

I'm not sure why we would get that error though because I don't think we try to explicitly set the image.

**Comment by jlewi** [comment]
API reference for NodeConfig
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig

```
gcloud --project=kubeflow-ci-deployment container get-server-config --zone=us-east1-d
Fetching server config for us-east1-d
defaultClusterVersion: 1.12.8-gke.10
defaultImageType: COS
validImageTypes:
- COS
- UBUNTU
- COS_CONTAINERD
- UBUNTU_CONTAINERD
- WINDOWS_SAC
validMasterVersions:
- 1.13.7-gke.19
- 1.13.7-gke.8
- 1.13.6-gke.13
- 1.12.9-gke.13
- 1.12.9-gke.7
- 1.12.8-gke.12
- 1.12.8-gke.10
- 1.12.7-gke.26
- 1.12.7-gke.25
- 1.11.10-gke.6

```

**Comment by johnugeorge** [comment]
@jlewi 

One observation:
It is happening only for us-east1-d zone when tried with CLI.  Works fine for us-central1-a

GKE bug?

**Comment by algermissen** [comment]
I am experiencing a similar issue in europe-west3.

**Comment by asmod3us** [comment]
Experiencing the same issue with image type UBUNTU in europe-west2-a. Any known workarounds?

**Comment by asmod3us** [comment]
Encountering the same issue even when attempting to create a cluster via GCP UI, so I'd say it's unrelated to kubeflow or the terraform provider.

**Comment by dkozlov** [comment]
1.13.7-gke.8 works for me

**Comment by jlewi** [comment]
Thanks I'll try moving our tests to us-central1-a

**Comment by johnugeorge** [comment]
looks like it works now with us-east1-d

**Comment by yaseenisolated** [comment]
This is resolved everywhere.
