### ISSUE TITLE
Multi-Tenancy Compatibility Reset on v0.6

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3893]
/kind feature
We need to guarantee kubeflow Multi-Tenancy Compatibility with different environments:
- [ ] Always create default profile 
- [ ] Istio rbac is only `ON` when coming requests contains identity which is accepted by both Istio and k8s.
- [ ] Notebook spawner should not block user creating notebooks when Istio rbac is `OFF`
- [ ] Test for on prem environment; document how to setup Multi-Tenancy on prem.

**Comment by jlewi** [comment]
See also this comment for list of scenarios we want to test
https://github.com/kubeflow/kubeflow/issues/3437#issuecomment-520674809

**Comment by kimwnasptd** [comment]
> Notebook spawner should not block user creating notebooks when Istio rbac is OFF
@kunmingg could you elaborate a little bit more on this one? What's the use case that the jupyter webapp blocks the user from creating a Notebook?

**Comment by yanniszark** [comment]
@jlewi the existing_arrikto config using Dex is capable of identity awareness.
In order to do that, this issue needs to be resolved first: https://github.com/kubeflow/kubeflow/issues/3553

The packages of some applications in manifests have to be extended to make the userid header customizable. 
Right now, it is set to `x-goog-authenticated-user-email` by default.

I will try to tackle this issue today, as it should be in this release.

**Comment by jlewi** [comment]
@krishnadurai @yanniszark @avdaredevil I created a doc based on the 0.6.0 release demo script.
http://bit.ly/2ZgOE1v

Lets get it updated for 0.6.2 and use to make sure we are testing all the scenarios we care about.

**Comment by krishnadurai** [comment]
@jlewi looks like you would need to grant access to this document.

**Comment by jlewi** [comment]
@krishnadurai Apologies; I thought I'd put it in the kubeflow shared drive but I guess not. Please try again.

**Comment by kunmingg** [comment]
@yanniszark 
Seems https://github.com/kubeflow/kubeflow/blob/v0.6-branch/bootstrap/config/kfctl_existing_arrikto.yaml still have Istio rbac on.
Will we have user identify setup in proxy under this condition?

**Comment by jlewi** [comment]
0.6.2 has been released so I'm going to go ahead and close this.
