### ISSUE TITLE
Not able to access kubeflow dashboard even after configuring metallb and ambassador service 

### ISSUE THREAD

**Issue by JishinJames** [kubeflow/kubeflow#3897]
Not able to access kubeflow dashboard even after configuring metallb and ambassador service .

can access each individual page through port forwarding ...
Thanks for your time.

**Comment by krishnadurai** [comment]
@JishinJames can you please add more information on the config which you were using for deployment?

**Comment by JishinJames** [comment]
I use the following metallb config YAML file .

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250

**Comment by JishinJames** [comment]
I use the following metallb YAML File and it is a single node kubernetes ( On prem ) cluster .

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240/28

**Comment by JishinJames** [comment]
I use the following ambassador config file for deployment .

apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  namespace: istio-system
spec:
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
  type: LoadBalancer

**Comment by elviraux** [comment]
@JishinJames Hi were you able to resolve this? 
If not what env you're using? Is it on cloud? onprem?

@krishnadurai

**Comment by krishnadurai** [comment]
@JishinJames I was looking for a deployment config which you must have used for deploying Kubeflow. Could you please provide this information?

**Comment by yanniszark** [comment]
Hi @JishinJames, in case it helps, we have information on setting up and troubleshooting MetalLB in the [existing_arrikto guide](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto).
Many users have reported success with it and I'd love to help out if you bump into any problems.
