### ISSUE TITLE
Creating a Notebook Server doesn't end loading.

### ISSUE THREAD

**Issue by deepdad** [kubeflow/kubeflow#3902]
Using the setup here: https://github.com/kubeflow/kubeflow/issues/3901#issuecomment-521200663

It seems that 
`Quick shortcuts > Create a new Notebook server > [enter a name, leave the rest as is]`
results in a spinner before the listed notebook servers but not much more.

<img width="948" alt="Screenshot 2019-08-14 at 13 58 39" src="https://user-images.githubusercontent.com/22483621/63019503-ccff4300-be9b-11e9-9c30-a884002487c6.png">

**Comment by deepdad** [comment]
2:04:23 PM
create Pod test2-0 in StatefulSet test2 failed error: pods "test2-0" is forbidden: error looking up service account default/default-editor: serviceaccount "default-editor" not found
test2
1:52:17 PM
create Pod test-0 in StatefulSet test failed error: pods "test-0" is forbidden: error looking up service account default/default-editor: serviceaccount "default-editor" not found
test

**Comment by jlewi** [comment]
How did you create the namespace?

Did you create a profile to create the namespace?

The profile is what populates the namespace with appropriate service accounts

```
kubectl get profiles
```

**Comment by UrmsOne** [comment]
@deepdad 
I meet the same problem,too.

If you use default namesapce, you  could try to `kubectl create sa -n kubelfow default-editor`.

Maybe it will solve the problem.

**Comment by jlewi** [comment]
A number of issues with namespaces and RBAC are fixed with 0.7.0.
Please try 0.7.0 and if you are still having problems open a new issue.

**Comment by CameliaBenLaamari** [comment]
I'm facing the same problem, and no error is displayed.
I'm using a KF dashboard that was already set up for me by my supervisor and is up and running on a server. So I can't execute terminal commands to change configurations. Any idea how to solve this?
![image](https://user-images.githubusercontent.com/76062686/126878527-0a60e231-cdcb-41a4-8c42-d6405ce026ae.png)
