### ISSUE TITLE
kfctl_k8s_istio On-Premise with MetalLB

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/kubeflow#3903]
/kind bug

**What steps did you take and what happened:**
I have MetalLB that is configured to offer external IPs. I have Prometheus running on my cluster and MetalLB is correctly serving IPs for that. Kubeflow deployed correctly and had no errors (other than taking about 15 mins for everything to come ready). The problem is istio-ingress looks like it did not even try for an external IP and defaulted to a NodePort type.

```
kubectl get svc -n istio-system
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S) 
istio-ingressgateway     NodePort    10.233.38.43    <none>        15020:30186/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30757/TCP,15030:31669/TCP,15031:32675/TCP,15032:31747/TCP,15443:30528/TCP   50m
```

**What did you expect to happen:**
istio-ingress to get an external IP from my MetalLB LoadBalancer

**Anything else you would like to add:**
I am doing this using Nvidia's Deepops tools to deploy my k8s cluster. 

**Environment:**

- Kubeflow version: v0.6.1
- kfctl version: kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: k8s
- Kubernetes version:  v1.14.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 server

**Comment by krishnadurai** [comment]
Currently the implementation for Istio ingress gateway service is set to NodePort by default. If we edit the istio-ingress-gateway service to Load Balancer type, you should be able to use MetalLB running with the ingress gateway and get the external IP.

**Comment by SpontaneousDuck** [comment]
Perfect! Was able to accomplish this with ```kubectl edit svc istio-ingressgateway -n istio-system``` and changing the type from ```NodePort``` to ```LoadBalancer```.

**Comment by leela-uppuluri** [comment]
@SpontaneousDuck I started installing kubeflow-1.0 on kubernetes-v1.15 cluster and was following the same kubeflow office documentation but I am stuck at accessing the kubeflow dashboard which does need the setup of loadBalancer or NodePort or Port forwarding is required. I was confused with setting up the istio gateway and virtual service. Can you please walk me through the steps on how you did install and configure MetalLB to access kubeflow dashboard and other things?

**Comment by dzungductran** [comment]
@jelwi Same here about configure MetalLB to access Kubeflow. It would be nice to have some of this documentation on Kubeflow site.
