### ISSUE TITLE
Kubeflow error

### ISSUE THREAD

**Issue by LinuxDevSecOps** [kubeflow/kubeflow#3911]
Hello I have successfully installed kuberflow.
But I am not able to install Kuberflow GUI..

Getting error.. attached with SS
![Screenshot from 2019-08-15 21-38-38](https://user-images.githubusercontent.com/48767068/63106642-17201b80-bfa5-11e9-9577-29dce56d8021.png)

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
1.15.2
- kfctl version: 
  0.6.1

- Kubernetes platform: minikube
  1.3.1
- Kubernetes version: `kubectl version`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2
- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04 - 64 bit

**Comment by jlewi** [comment]
Can you please provide the commands you ran? 
Could you also try following the latest instructions for 0.6.

**Comment by butuzov** [comment]
I believe the reason for this error is running kubeflow on the minikube with kubernetes versioned above 0.14. What @LinuxDevSecOps  can do is to follow @jlewi's advise from this issue

https://github.com/kubeflow/kubeflow/issues/3610#issuecomment-511461426

**Comment by LinuxDevSecOps** [comment]
@jlewi Yes here the commands:


  804  sudo apt install virtualbox
  805  sudo dpkg -i virtualbox-6.0_6.0.10-132072_Ubuntu_bionic_amd64.deb 
  806  cd Downloads/
  807  ls
  808  sudo dpkg -i virtualbox-6.0_6.0.10-132072_Ubuntu_bionic_amd64.deb 
  809  cd ~
  810  sudo minikube start
  811  sudo minikube dashboard --url
  812  sudo curl -O https://raw.githubusercontent.com/kubeflow/kubeflow/v0.2-branch/bootstrap/bootstrapper.yaml
  813  sudo  kubectl create -f bootstrapper.yaml
  814  sudo kubectl get ns
  815  sudo kubectl -n kubeflow get svc
  816  sudo netstat -ltnp
  817  POD=`kubectl -n kubeflow get pods --selector=service=ambassador | awk '{print $1}' | tail -1`
  818  sudo POD=`kubectl -n kubeflow get pods --selector=service=ambassador | awk '{print $1}' | tail -1`
  819  export KUBEFLOW_TAG=v0.4.1
  820  sudo curl -O https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/setup-minikube.sh
  821  sudo chmod +x setup-minikube.sh
  822  sudo ./setup-minikube.sh
  823  sudo minikube start
  824  sudo ./setup-minikube.sh
  825  SUDO kubectl -n kubeflow-admin get all
  826  sudo  kubectl -n kubeflow-admin get all
  827  sudo kubectl -n kubeflow get pods
  828  sudo kubectl get ns
  829  sudo ubectl apply --validate=false -f default.yaml
  830  sudo kubectl apply --validate=false -f default.yaml
  831  cd Do
  832  cd Downloads/
  833  ls
  834  sudo tar -xvf kfctl_<release tag>_<platform>.tar.gz
  835  sudo tar -xvf kfctl_v0.6.1_darwin.tar.gz
  836  export PATH=$PATH:"<path to kfctl>"
  837  export PATH=$PATH:"</opt>"
  838  cd ~
  839  cd /opt/
  840  ls
  841  cd ~
  842  sudo kfctl --platform=gcp --use_istio=true
  843  sudo export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml"
  844  sudo kubectl -n kubeflow get pods
  845  sudo minikube start
  846  sudo minikube dashboard --url
  847  sudo kubectl -n kubeflow get svc
  848  sudo ./setup-minikube.sh
  849  history
  850  sudo minicube start
  851  sudo minikube start
  852  clear
  853  sudo minikube start
  854  sudo minikube dashboard --url

**Comment by jlewi** [comment]
@LinuxDevSecOps What instructions are you following?

It looks like you are using really old versions

* i.e. `https://raw.githubusercontent.com/kubeflow/kubeflow/v0.2-branch/bootstrap/bootstrapper.yaml`  is over a year old and no longer used
* And then later you are referencing version 0.4

**Comment by jlewi** [comment]
I'm going to close this issue. There are updated instructions for installing Kubeflow on minikube here.
https://www.kubeflow.org/docs/started/workstation/getting-started-linux/#minikube

Please try those and if you are still having problems open a new issue.
