### ISSUE TITLE
Add init containers for services with dependencies to improve robustness

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#3913]
/kind improvement

**Why you need this feature:**
I notice some components have dependencies on other service or deployment. Looks like kustomize can not solve this problem pretty well. Even kustomize has order support, some  container with large container image or PV can takes longer to start up. 

Here's an example. Restarts are not 0.  
```
NAME                                                        READY   STATUS    RESTARTS   AGE
metadata-db-7f78b5fbf8-mrk82                                1/1     Running   0          36h
metadata-deployment-6f4c4f9d5c-42phd                        1/1     Running   3          36h
metadata-deployment-6f4c4f9d5c-j2mhb                        1/1     Running   3          36h
metadata-deployment-6f4c4f9d5c-snt7b                        1/1     Running   3          36h
metadata-ui-547b468655-rn7nc                                1/1     Running   0          36h
minio-85cb66c844-tsxn8                                      1/1     Running   0          36h
ml-pipeline-cb898579d-6c4m2                                 1/1     Running   2          36h
ml-pipeline-persistenceagent-7669b6f4d5-h752j               1/1     Running   0          36h
ml-pipeline-scheduledworkflow-59d6cfd48c-hc9jl              1/1     Running   0          36h
ml-pipeline-ui-68c558cc45-9gvhl                             1/1     Running   0          36h
ml-pipeline-viewer-controller-deployment-66bc57bcd5-b6k5x   1/1     Running   0          36h
mpi-operator-955d87586-54crt                                1/1     Running   0          36h

```

Here's an other example.
https://github.com/kubeflow/kubeflow/issues/3900#issuecomment-521414791

**Describe the solution you'd like:**
Add iniContainers to Deployment like this 

```
initContainers:
  - name: init-profiles-kfam
    image: busybox
    command: ['sh', '-c', 'until nslookup profiles-kfam; do echo waiting for profiles-kfam; sleep 2; done;']
```

Let me know if it makes sense and there's better way. I can help on it

**Comment by jlewi** [comment]
What's the downside of just letting containers restart? Is it just to avoid confusing errors?

**Comment by Jeffwan** [comment]
To me, restart works fine and it just bring noise and maybe not the best practice. 
Not sure if anyone may raise questions about restart or get confused by errors during the installation. 
This is a minor enhancement and priority is low.
