### ISSUE TITLE
Central dashboard should should surface an error if it can't talk to kfam

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3916]
/kind feature

We've encountered several issues due to the central dashboard backend failing to connect to the kfam API e.g.

#3859
#3900
#3915

I think we should improve the code to better surface errors

* in #3915 502s to the workinggroup API prevented the page from showing up for 1 minute
  * Instead can we show an error or other message?
* There is a failure mode where users aren't directed to create a namespace and yet they can't select a namespace in the selector
   * Can we show users an error explaining what they need to do to fix this.

/assign @avdaredevil

**Comment by beatgeek** [comment]
👍 to this feature. Unable to select a namespace on build version v0.6.2-rc.0 and also prevents launching a notebook server.

**Comment by sylus** [comment]
Also having this problem can we trigger a new release with the fix. Really having a lot of trouble getting kubeflow to work the past few releases.

Super appreciate all of the hard work that has been put into it though :D

**Comment by jlewi** [comment]
@sylus @beatgeek did you try the workaround of deleting the centraldashboard pod? This issue is just about surfacing the error. The root cause and work around is #3900

**Comment by jlewi** [comment]
I'm marking this bug as fixed because when I tried the latest image
gcr.io/kubeflow-images-public/centraldashboard:v20190816-v0.6.0-rc.0-57-g1d4b59c1

I got an error on the central dashboard indicating it couldn't talk to the Profile controller. This is the desired behavior.
