### ISSUE TITLE
Provision default GCP credentials when creating a new profile

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3917]
/kind feature

Right now a user can easily create new namespaces either 

* Via the UI
* By creating the profile

But the new namespace would not have GCP credentials.

Can we allow system admins to set a default GCP account to be  used by new namespace?

When we deploy Kubeflow we create a ${KFAPP}-user GCP account for this purpose.

So it would make sense to automatically bind that account to new namespaces (while still make it easy to disable).

I think we should focus on doing this using workload identity
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

So its a matter of 

1. Granting appropriate IAM roles on the new service account
1. Annotating the KSA correctly

How should we do this? We could add the code directly to profile creator but that would mean adding platform specific code to the profile creator.

What we'd like is an easy way for the platforms to define hooks that would run after the profile is created.

* One option would allow the profile controller to be configured with an optional webhook that would be invoked as part of the reconcile function;
* Then platforms could just define their own webhooks

/cc @kunmingg @lluunn

**Comment by jlewi** [comment]
Bump to P0 because it could affect profile controller API

/assign @kunmingg

**Comment by jlewi** [comment]
I was thinking about how this might work

* Profile controller could have plugins like KFDef
  * We can look at KFDef v1beta1 to see how to properly serialize arbitrary KRM style objects to a plugin
* A GCPPlugin could specify the GCP service account to use
* The profile controller could configure the new namespace to use the GCP service account specified in the profile
   * The profile controller would have to be running using a GCP service account with sufficient privileges to change the IAM roles on the service account
   * The profile controller should perform an IAM check to ensure the user is authorized to use that service account
      * i.e. check that the user creating the profile can act as that service account

**Comment by kunmingg** [comment]
Shall we block the profile resources creation or just leave warning messages when user is not authorized to use that service account?

**Comment by jlewi** [comment]
@kunmingg That's a good question. WDYT?

**Comment by jlewi** [comment]
@kunmingg Any update on this? Could you provide an initial ETA so we can help plan for cutting 0.7.

**Comment by kunmingg** [comment]
This one is included in https://github.com/kubeflow/kubeflow/pull/4155
as part of GCP plugin.

About checking user permission:
I feel if the profile owner has GKE cluster access (required for creating profile.) should we just provision default GCP credentials for all new profiles?

**Comment by jlewi** [comment]
> I feel if the profile owner has GKE cluster access (required for creating profile.) should we just provision default GCP credentials for all new profiles?

Would users want to use the default GCP credentials provisioned on deployment? That newly created service account probably doesn't have access to the resources (BigQuery/GCS, etc....) that the user wants to use.

Furthermore, the namespaces corresponding to different teams aren't really isolated if they all have access to the same GCP account.

So i think each namespace would want to use a different GCP account so the user probably needs to specify that when creating a profile.

We might want to file a bug about UI improvements for creating profiles to allow users to specify the service account.

**Comment by jlewi** [comment]
@kunmingg is this fixed as part of kubeflow/kubeflow#4155

* Should we continue to leave this issue open until we have a test per kubeflow/kfctl#40 to verify this is working as expected?

**Comment by kunmingg** [comment]
We can close it as new profile now in manifests
https://github.com/kubeflow/manifests/pull/493
