### ISSUE TITLE
OSX related issues while using  `setup-minikube.sh`

### ISSUE THREAD

**Issue by butuzov** [kubeflow/kubeflow#3920]
/kind question

Related to #3901 

I have a couple of questions regarding `setup-minikube.sh`

**Question:**
* [x] ~~Why does `ksonnet` fixed to version `0.11.0`?~~ ok, kuztomize to replace it.
* [x] ~~Can version above be used?~~
* [x] ~~Why does install use binary version from github.com/ksonnet/ksonnet instead of using `brew` as it does for `kubectl`? See [L42-l63](kubeflow/kubeflow/blob/master/scripts/setup-minikube.sh#L42-L63)~~
* [  ] Why does `brew` existance isn't checked, and fallback install provided?
* [x] ~~Should installer check for `ksonnet` or for `kustomize`? (i am new to kubeflow, but this issue referenced in #3901).~~
* [  ] Can I add case of OSX ssytem with `coreutils` and `gnutls` installed? 
  *  `nproc` available if coreutils installed.
  *   osx's `df -g .` not available if gnutls installed. [PR#3922](#3922)

I can prepare fix and add resolving for all these parts if you don't mind. But I need answers at least for some of the questions. 

update:
`ksonnet` is deprecated. I got this.

**Comment by jlewi** [comment]
setup-minikube.sh is very outdated and probably needs to be updated on master to work with 0.6

@abhi-g Are you working on this?

@butuzov If you want to add special if statements for OSX I think that's fine.

/cc @abhi-g

**Comment by abhi-g** [comment]
I am trying to get it updated. The script already has some osx related
sections. Feel free to update if necessary.

**Comment by butuzov** [comment]
I see.

Let me dive a bit more into kubeflow project. I really see that it's in transform phase (like setup-minikube.sh isn't helpful at all at this moment), due to a change package manager from ksonnet to kustomize. I will try to keep my on it in the next two weeks.

**Comment by jlewi** [comment]
@butuzov any update?

See also #4045 about deprecating and removing kfctl.sh.

**Comment by butuzov** [comment]
@jlewi Hi.

Sorry, was and a bit still busy with ongoing things. Can you clarify, regrading #3952 - you want to rebase changes to 0.6 branch? 

thank you.

**Comment by jlewi** [comment]
@butuzov replied on the issue.

**Comment by jlewi** [comment]
We have removed setup-minikube.sh
