### ISSUE TITLE
GKE cluster autoprovisioning settings are problematic

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#3930]
/kind bug

With KF 0.6.1 on GKE

The kfctl autoprovisioning settings seem problematic for the GKE cluster setup.  If you create a new autoscaling node pool with n1-standard-8 nodes and min of 0, it can't actually scale, as that would bump the CPUs to 24, over the configured max.  This happens, e.g., if you follow the node pool creation example in the docs about using preemptible VMs.

The low number of GPUs could be problematic as well.  I think a user won't know/realize about the auto-provisioning config and will not understand why autoscaling is not working.

![unnamed](https://user-images.githubusercontent.com/115093/63199740-9eb46b80-c033-11e9-876d-f95b078d0f47.png)

**Comment by jlewi** [comment]
@amygdala Do you have recommended default settings?


The settings are configured here
https://github.com/kubeflow/kubeflow/blob/169f03d1321f420ff00d2a972ae7475c058f5ef4/deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml#L70
https://github.com/kubeflow/kubeflow/blob/169f03d1321f420ff00d2a972ae7475c058f5ef4/deployment/gke/deployment_manager_configs/cluster.jinja#L98

**Comment by amygdala** [comment]
This is kind of a tough question.  We'd presumably want the values to be reasonably small. But the problem is that if someone also creates an explicit node pool, configured to use autoscaling, it probably won't scale as intended, and (if the user is not aware of the autoprovisioning constraints) it will be hard for them to figure out why.  

I think that we should probably:
-  bump the CPU to at least 48 and the k80s to at least 16. And memory to ~500?
- add some info about this on the 'troubleshooting' page, and include the command to adjust autoprovisioning settings
- consider having it be a high-level CLI flag as to whether or not to use autoprovisioning for the cluster ?  If the user had to make an explicit decision about whether to use it, they will understand better if it breaks subsequent autoscaling.

**Comment by kkasravi** [comment]
@amygdala @jlewi @kunmingg 
we need this for kubecon SD where cluster-kubeflow.yaml needs to include 
```
    cpu-pool-min-cpu-platform “Intel Skylake"
```

**Comment by yanniszark** [comment]
@jlewi @kkasravi  can these settings be surfaced via the gcp plugin spec?
We can surface them in the spec or give the user a method to specify their own cluster_config.
WDYT?

**Comment by jlewi** [comment]
I see the problem now. 

The limits sets for auto provisioning are limits for the **cluster** not **per node**. So setting a max of 20 CPUs means the cluster as a whole should have a maximum of 20 CPUs not that a node should have a maximum of 20.

It also looks like we can list multiple accelerators
https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.ResourceLimit

Related issue: kubeflow/kfctl#82 - auto-optimize cluster size
Related issue: kubeflow/kfctl#59 - auto set GPU type for node auto provisioner

One thing we could do is automatically set the limits based on the quota a user has?

**Comment by amygdala** [comment]
yeah, it is per cluster. 

I wonder if it's a good idea to use the user's quota as the limit— at first that sounded good, but now I am thinking that if they have some v. high quota, then potentially they could scale out more than they meant to with some ill-configured job, then get an unexpectedly high bill etc.

Maybe we could just set it reasonably high (I'm assuming that if it's higher than the user's actual quota, things still work), and point to the docs on how to modify it if they want to adjust it.
