### ISSUE TITLE
Frequent websocket disconnections; GCP, IAP, v0.6.2 RC

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3932]
/kind bug

My setup is as follows

* GCP
* IAP
* v0.6.2-rc0

I'm running Jupyter and I'm noticing semi frequent web socket disconnection errors; more so than in previous releases.

This is most pronounced when using a terminal because it just hangs and you have to refresh.

One thing to check would be the connection time outs for the GSLB as well as ISTIO?

**Comment by jlewi** [comment]
We should check what the GCP backend service timeout is set to.

**Comment by prcastro** [comment]
@jlewi was this issue fixed for you?
