### ISSUE TITLE
Feature request: consider kfctl config compatible with GCP free trial project

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#3936]
/kind feature

We should consider having a kfctl predefined config that 'just works' for GCP free trial customers and the quota they're given, even though it would be somewhat underpowered.
E.g. see https://github.com/kubeflow/website/issues/1065.
(The same might hold for the other cloud providers).

**Comment by jlewi** [comment]
This is a great idea.

**Comment by amygdala** [comment]
noooo, stale[bot]

**Comment by amygdala** [comment]
I don't think the bot is going to re-open this, and I don't have permissions to— Jeremy, would you mind re-opening & removing the 'stale' label? I'd like to keep it on our radar. @jlewi

**Comment by MadsAdrian** [comment]
Any progress on this one?

**Comment by fzhurd** [comment]
any update?

**Comment by tall-josh** [comment]
any news?

**Comment by btphan95** [comment]
any update?

**Comment by tall-josh** [comment]
I'm working on a blog post where I setup Kubeflow on the GCP free trial. I ended up following the [Deploy Using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli) instructions but instead of using `kfctl apply ...` I used `kfctl build ...` then modified the `kfctl_gcp_iap.yaml`.

[Here](https://github.com/tall-josh/tall-josh.github.io/blob/master/drafts/blog-posts/Kubeflow.md#how-to-setup-kubeflow-on-gpus-free-trial-tier) is a link to the first draft if anyone is interested.

**Comment by btphan95** [comment]
> I'm working on a blog post where I setup Kubeflow on the GCP free trial. I ended up following the [Deploy Using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli) instructions but instead of using `kfctl apply ...` I used `kfctl build ...` then modified the `kfctl_gcp_iap.yaml`.
> 
> [Here](https://github.com/tall-josh/tall-josh.github.io/blob/master/drafts/blog-posts/Kubeflow.md#how-to-setup-kubeflow-on-gpus-free-trial-tier) is a link to the first draft if anyone is interested.

This was super informative and helpful! Funny too haha

**Comment by btphan95** [comment]
I tried increasing my quota for the number of CPUS for my account, and promptly got approved. This helped me circumvent the error.

**Comment by vasco989k** [comment]
hello @btphan95  
I have a question about modifying kfctl_gcp_iap.yaml.
after modify file , i don`t know next action. 
explain next step more detail ,plz

**Comment by tall-josh** [comment]
Hmmm, I left out that step. My B. 

After modifying the `kfctl_gcp_iap.yaml` file simply run `kfctl apply -v -f kfctl_gcp_iap.yaml` :-) 

Hope that helps.

**Comment by juliusvonkohout** [comment]
/close
Kfctl is gone
