### ISSUE TITLE
Kuberflow using ansible PLAYBOOK

### ISSUE THREAD

**Issue by LinuxDevSecOps** [kubeflow/kubeflow#3937]
/kind question

Hello Can someone help to install kuberflow by ansible PLAYBOOK? I have number of things already deployed.

The following components are configured and enabled

o Katib (for Hyperparameter Tuning)

o Jupyter Notebooks

o Model DB

o Pipelines

o Seldon Serving 

o TF Serving

o TFJob

o TFX (with cluster deployment and local dev on VM via supporting scripts)

o Autoscaling with K8s resources

I dont still install Kubernets and kubectl.. Can you guide about it ? how to start ?

**Comment by jlewi** [comment]
Can you provide more detail about what you are trying to deploy with Ansible?

Can you use Ansible to orchestrate kfctl?

**Comment by LinuxDevSecOps** [comment]
Hello @jlewi ,
https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.1/bootstrap/config/kfctl_k8s_istio.yaml

check this. I want to deploy kubeflow using Ansible Playbook. Like we can ran kubernetes using Ansible Playbook. Can you give me a full idea about how to deploy kubeflow using Ansible Playbook??

**Comment by krishnadurai** [comment]
One of the ways could be to install `kfctl` in a machine. This could be done by downloading kfctl from the [releases page](https://github.com/kubeflow/kubeflow/releases).
`kfctl` has three steps during setup, namely: `init`, `generate` and `apply`. Refer installation docs [here](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/).
Each of these `kfctl` steps can be made a step in an ansible task to deploy Kubeflow using [command](https://docs.ansible.com/ansible/2.5/modules/command_module.html) module.

**Comment by LinuxDevSecOps** [comment]
solved
