### ISSUE TITLE
Define Kubeflow cluster role and combine roles  (was default roles should include virtualservices)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3938]
/kind feature

It looks like permission to create virtual services aren't attached by default to the roles created in namespaces. See below

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

editors should probably have the ability to edit virtual services so they can deploy services in their namespaces and configure traffic.

viewers should probably have viewer permissions.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Here is the edit role

```
kubectl get clusterrole edit -o yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2019-08-16T04:04:19Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: edit
  resourceVersion: "319"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/edit
  uid: ebc81501-bfda-11e9-970b-42010a8e010d
rules:
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - secrets
  - services/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
```

**Comment by jlewi** [comment]
It looks like we are just using the builtin edit and view roles defined by Kubernetes
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings

So by default users won't have ability to create Kubeflow custom resources; e.g. notebooks; TFJob etc...

Should we create our own viewer and editor roles and use those by default?

/cc @krishnadurai @kunmingg @animeshsingh

**Comment by yanniszark** [comment]
@jlewi we could either do that or aggregate our own custom ClusterRole with the default edit one.
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles

**Comment by krishnadurai** [comment]
@jlewi It would always be easier for users to have defaults for each role defined by a Kubeflow manifest including the (default minimum) resources Kubeflow introduces. I've used the term default minimum with the view that there will be certain resources which are optionallly deployed in a user's Kubeflow deployment.
For these optional components - as @kkasravi had initially suggested - we could make these clusterrules a part of the application CRD effort, which would be a modular way of managing these rules for each application and the Kubernetes resources they introduce. The idea here is that these rules get included only when each of these applications or components are a part of the deployment.

@yanniszark's idea of using aggregated-clusterroles seems like a good way to manage default ClusterRole as an extension to the existing Kubernetes defaults - not requiring us to keep updating these Kubernetes defaults at our manifests. Though, this will require us to patch or add labels to default Kubernetes roles.

One way of looking at it is that we have independent Kubeflow viewer and editor roles which carry the default minimum resources which Kubeflow introduces - like tfjobs, notebooks etc. The Kubenetes default clusterroles are aggregated into this role with its own resources. Other optional applications deployed with Kubeflow can define their default clusterrole for viewer and editor roles and are aggregated back into Kubeflow clusterroles, if the application is included in the user's deployment.

IMO this would be easy to manage and is in line with our goal of composability.

/cc @animeshsingh

**Comment by krishnadurai** [comment]
The question here would be now is that whether Istio is treated as a separate application and have its own clusterroles for viewer and editor? And this can be aggregated back to Kubeflow viewer and editor clusterroles.

**Comment by krishnadurai** [comment]
I can give an attempt at this for 0.7.

**Comment by jlewi** [comment]
@krishnadurai Any update on this?

I'm bumping to P0 because I think if we are going to introduce our own cluster role and start using role aggregation we do that in 0.7 so we can get it stable before 1.0.

**Comment by krishnadurai** [comment]
@jlewi I should be able to pick this up by the end of this week.

**Comment by jlewi** [comment]
@krishnadurai Do you have an ETA on this? Will we be able to be code complete by the end of the week?

**Comment by krishnadurai** [comment]
@jlewi I will be raising an initial PR within a few days.

**Comment by jlewi** [comment]
@krishnadurai Any update on this? Do you have an ETA for when this will be done? This will help us plan for cutting 0.7.

**Comment by krishnadurai** [comment]
@jlewi I'll be pushing in the changes within tomorrow.

**Comment by krishnadurai** [comment]
@jlewi @kunmingg PTAL to the above PRs addressing changes for K8s default roles with Istio as an application. Builds are failing as reported earlier.

**Comment by jlewi** [comment]
@krishnadurai could you provide an update please? Looks like a bunch of PRs have been merged. Do we just need to get kubeflow/manifests#393 merged or is there more we need to do?

**Comment by krishnadurai** [comment]
@jlewi after kubeflow/manifests#393 gets merged we should close this issue.
