### ISSUE TITLE
deploy not work https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

### ISSUE THREAD

**Issue by LinuxDevSecOps** [kubeflow/kubeflow#3939]
I am using centOs 7.8

when i try to deploy using https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Script to download and unpack for Linux/MacOS:

is shows this message
![Screenshot from 2019-08-18 19-52-53](https://user-images.githubusercontent.com/48767068/63225433-c9e4b980-c1f1-11e9-83ed-06c44e7ff0a5.png)

Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

@willb @jonas @ewilderj

**Comment by jlewi** [comment]
Is this the command you ran

```
curl -s https://api.github.com/repos/kubeflow/kubeflow/releases/latest |\
    grep browser_download |\
    grep $opsys |\
    cut -d '"' -f 4 |\
    xargs curl -O -L && \
    tar -zvxf kfctl_*_${opsys}.tar.gz 
```

I suspect there is a bug in that serious of scripts and it ends up not getting the URL correctly.

I'd suggest just going to the releases page and downloading the release you need
https://github.com/kubeflow/kubeflow/releases

**Comment by johnugeorge** [comment]
you could download it  from https://github.com/kubeflow/kubeflow/releases/tag/v0.6.1

**Comment by swiftdiaries** [comment]
Sorry about this. I verified it on Ubuntu and Mac. I assumed it would work with CentOS as well.
Shall I remove the script from the page?

**Comment by johnugeorge** [comment]
@swiftdiaries I think so. Script is error prone as binaries might not available in all platforms.

**Comment by jlewi** [comment]
@krishnadurai @swiftdiaries what should we do to close this issue out?

Should we try to fix the script or should we just update the docs to tell people to manually download it rather than executing some script?

**Comment by krishnadurai** [comment]
It would be better to have the website point to the releases page and the users manually download it. I'll shortly open a PR to address the same.
