### ISSUE TITLE
Build Envoy Container with JWT validation

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#394]
See #60 

We will need to build an envoy container that contains an updated binary with JWT validation support for IAP.

The team maintaining the JWT fork of envoy isn't building containers anymore but they are building a binary  which is available in GCS

```
curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-alpha-${ISTIO_ENVOY_VERSION}.
tar.gz}
```

The fixes we need should be in this version.

```
export ISTIO_ENVOY_VERSION=0fb4886b463698702b6a08955045731903a18738
```

This was a Dockerfile I used in the past
https://github.com/jlewi/proxy/blob/iap/docker/Dockerfile.kubeflow

**Comment by ankushagarwal** [comment]
Looks like we don't have the correct permissions

```
export ISTIO_ENVOY_VERSION=0fb4886b463698702b6a08955045731903a18738
curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-alpha-${ISTIO_ENVOY_VERSION}.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by ankushagarwal** [comment]
This can be closed because https://github.com/kubeflow/kubeflow/pull/409 is merged
