### ISSUE TITLE
Update Jupyter notebook CRD to support v1beta1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3940]
/kind feature

**Why you need this feature:**

In 0.7 we want to release notebook v1beta1 (#3655). In 0.7  we'd like to provide backwards compatibility with notebooks/v1alpha1 if possible.

Right now it doesn't look like v1beta1 schema will be that different (as of right now there are no changes to the v1beta1 spec relative to v1alpha1).

Following 
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

We should be able to simultaneously serve v1alpha1 and v1beta1 just by updating the CRD.

This issue tracks making that change.

@lluunn Any interest?

**Comment by lluunn** [comment]
sure

/assign

**Comment by jlewi** [comment]
@lluunn Any update on this?

**Comment by jlewi** [comment]
@lluunn What are the next steps here? 

Do we need to build an updated docker image and update the kustomize manifest?

Do we need to update docs?

Could we run a simple manual verification that we can create notebooks either using the v1alpha1 API or the v1beta1 API.

**Comment by jlewi** [comment]
@lluunn Looks like the manifests have been updated. What are the remaining work items?

**Comment by lluunn** [comment]
- update webapp: #4163
- figure out how to setup webhook #4164 . This is needed if we change the spec (currently no spec change from alpha to beta)

**Comment by lluunn** [comment]
The remaining work is tracked in #4164
