### ISSUE TITLE
Reformat only modified files

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#395]
We have a script
https://github.com/kubeflow/kubeflow/blob/master/scripts/autoformat_jsonnet.sh

to autoformat jsonnet files. It would be nice if we added some sugar to only autoformat modified files relative to master. 

What I have below sort of works but jsonnet chokes on non jsonnet/libsonnet files so we need to filter
those out.

```
git diff --name-only upstream/master  | xargs jsonnet fmt  -i --string-style d   --comment-style s  --indent 2 
```

**Comment by ankushagarwal** [comment]
I thought autoformat_jsonnet.sh is an idempotent operation. Do we want to reformat modified files for performance reasons?

**Comment by mikezuniga** [comment]
This was already implemented for what I can see in the issue referenced above

**Comment by ankushagarwal** [comment]
Closing because https://github.com/kubeflow/kubeflow/pull/553 is merged

**Comment by jlewi** [comment]
@ankushagarwal To answer your question; the problem is that its not uncommon for a bunch of jsonnet/libsonnet files to be improperly modified. So if we reformat all files, we often end up modifying files that wouldn't otherwise be modified in the PR. IMO this is undesirable from a a reviewer perspective because it can end up creating a bunch of formatting changes irrelevant to the core of the PR.

The standard practice when auto-formatting code is to only autoformat files that are already being modified as part of the PR.
