### ISSUE TITLE
how to make use of kubeflow for a data scientist?

### ISSUE THREAD

**Issue by AnnieWei58** [kubeflow/kubeflow#3962]
What are the differences and connections between different components (i.e. jupyter hub, tfjob dashboard, katib dashboard and pipeline dashboard) shown on the kubeflow UI? 

Or what's the usual process for making use of these components for a data scientist? Is there anyone interested to discuss?

**Comment by elviraux** [comment]
@AnnieWei58 is it still relevant to you?
