### ISSUE TITLE
Web UI on bare metal setup?

### ISSUE THREAD

**Issue by whillas** [kubeflow/kubeflow#3972]
/kind question

**Question:**
So, I'm installing on a local Kubernetes cluster, bare metal set (if there is such a thing when installing to Kubernetes) following these instructions: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

All seems good (once i sorted out volumnes). But I have no idea how to get access to the web UI?

I'm supposed to open a Gateway with Istio? On what port? For which pod? How!

A bare metal guide (i.e. after kubernetes is setup) would be <<AMAZING>>

thanks guys

**Comment by swiftdiaries** [comment]
You could port-forward to the istio-ingressgateway service,
`kubectl port-forward svc/istio-ingressgateway 8080:80 -n istio-system`

**Comment by yanniszark** [comment]
Hi @whillas!
We have tried [kfctl_existing_arrikto](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/) on many bare-metal clusters, using MetalLB to expose the Web UI.
You will find instructions in the guide on how to install MetalLB.
