### ISSUE TITLE
Notebook cannot connect after modifying the default cluster. domain - notebook controller doesn't support custom domains

### ISSUE THREAD

**Issue by UrmsOne** [kubeflow/kubeflow#3974]
/kind bug

Hello,
I'm playing around with a Kubeflow installation on local VM following the instructions in
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

When I changed the default cluster. domain to 'k8s.xxx.opd.local', I encountered the following problems(It's not found in the default cluster.domain "cluster.local").

![image](https://user-images.githubusercontent.com/31981402/63498490-97d89d80-c4f8-11e9-9cf8-36d5e15fbe9d.png)

After I created notebook, it couldn't connect.I'm sure it's working, and notebook controller is working without errors.
![image](https://user-images.githubusercontent.com/31981402/63496692-ef750a00-c4f4-11e9-8808-ee5c178be2b7.png)

* INGRESS_HOST：192.168.221.131
* INGRESS_PORT： 31380
![image](https://user-images.githubusercontent.com/31981402/63496791-18959a80-c4f5-11e9-8b14-3f79402015fd.png)

* ingressgateway logs：
```
[2019-08-22T07:38:39.240Z] "GET /notebook/kubeflow/t2/ HTTP/1.1" 503 NR "-" 0 0 0 - "10.244.1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" "4a0d1d4a-e1d7-9fd7-acb0-8ce6d3b55ba0" "192.168.221.131:31380" "-" - - 10.244.2.226:80 10.244.1.0:6060 -
```

* istio-ingressgateway  CLUSTER-IP: 10.100.31.25
* `curl -I http://10.100.31.25/notebook/kubeflow/`

```
HTTP/1.1 200 OK
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Fri, 21 Jun 2019 14:40:54 GMT
etag: W/"599-16b7a7bacf0"
content-type: text/html; charset=UTF-8
content-length: 1433
date: Thu, 22 Aug 2019 08:04:10 GMT
x-envoy-upstream-service-time: 33
server: istio-envoy
```

*  `curl -I http://10.100.31.25/notebook/kubeflow/t2`

```
HTTP/1.1 503 Service Unavailable
date: Thu, 22 Aug 2019 08:04:35 GMT
server: istio-envoy
transfer-encoding: chunked
```

**Environment:**

- Kubeflow version v0.6.1
- kfctl version: kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: VM(kubeadm)
- Kubernetes version: v1.10.11
- OS: debian9
- kubeflow: v0.6.1

Is this a bug?Can anyone help me debug the issue?
Thanks a lot for this project and thank you in advance for your help!
Urmsone

**Comment by UrmsOne** [comment]
Hello,

The problem is that when I create notebook server, VirtualServices resources generated by notebook_controller.go is incorrect.

![image](https://user-images.githubusercontent.com/31981402/63582999-b60fcd80-c5cc-11e9-9189-846eb2d9bd58.png)

**Because I modified the clusterDomain to `k8s.xxx.local`,not defualt `cluster.local`**
![image](https://user-images.githubusercontent.com/31981402/63583148-06872b00-c5cd-11e9-85dc-6cacada29416.png)


**But the code only supports the default clusterDomain “cluster.local”**

![image](https://user-images.githubusercontent.com/31981402/63583676-0f2c3100-c5ce-11e9-88ad-085c0924d25d.png)

[https://github.com/kubeflow/kubeflow/blob/f9ed088da4281b49dbce0043fe13a9681d2c99d6/components/notebook-controller/pkg/controller/notebook/notebook_controller.go]()


Could you support custom clusterDomain in future versions?
Thanks.

**Comment by jlewi** [comment]
@UrmsOne thanks for reporting this and getting to the root of it.

Any interest in opening a PR to fix this? I think we would need to make two changes

1. Add a command line argument (or environment variable) to the controller to set what the behavior should be
   * Whether we use a command line flag or environment variable should be based on what is more consistent with the existing behavior of the controller
1. Modify the manifest for the notebook controller so that we can set an application parameter to control that suffix

/cc @gabrielwen

**Comment by jlewi** [comment]
@UrmsOne @kimwnasptd @lluunn Do we know if this has been fixed in 0.7?

**Comment by jlewi** [comment]
It looks like the cluster domain is still hard coded.
https://github.com/kubeflow/kubeflow/blob/183919dccbe1e5c77aece17fd5064992383dddb6/components/notebook-controller/controllers/notebook_controller.go#L373

So it looks like we need to expose it via a command line flag or environment variable.

**Comment by UrmsOne** [comment]
@jlewi Sorry, I have been busy with my graduation project recently, which delayed to fix this bug.

I will try my best to fix this bug by providing a command line flag or environment variable，

and submit the PR within this week.

**Comment by mfojtak** [comment]
This is not fixed. Should be reopened.

**Comment by parthasarathi-pm** [comment]
Add env in apps/jupyter/notebook-controller/upstream/manager/manager.yaml
        env:
          - name: CLUSTER_DOMAIN
            value: example.com

this will solve notebook controller from creating virtual server with default domain suffix cluster.local
@mfojtak
