### ISSUE TITLE
"RBAC: access denied" when accessing the dashboard

### ISSUE THREAD

**Issue by nicklhy** [kubeflow/kubeflow#3975]
Hi everyone,
After reading the tutorial in this [page](https://www.kubeflow.org/docs/other-guides/accessing-uis/). I tried to access the dashboard with kubectl+port-forwarding but got an error like below
```shell
$ export NAMESPACE=istio-system
kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80

# in another shell
$ curl http://localhost:8080/
RBAC: access denied
```
Do I need to do some extra settings about RBAC ?

**Comment by yanniszark** [comment]
Hi @nicklhy!
What guide did you follow to deploy Kubeflow?

**Comment by nicklhy** [comment]
@yanniszark I deployed the kubeflow with [kfctl_k8s_istio](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/).

**Comment by krishnadurai** [comment]
@nicklhy could you please change Istio's ClusterRbacPolicy as 'OFF' instead of 'ON'?

BTW, you could access the UI with the NodePort 31380.

**Comment by krishnadurai** [comment]
This will be resolved with 0.6.2.
Refer PR: https://github.com/kubeflow/kubeflow/pull/3877

**Comment by nicklhy** [comment]
@krishnadurai Thank you so much! I can access the UI immediately after changing the istio Cluster RBAC Config.
But when I opened the UI in Chrome, I got an error message at the left bottom corner:
```
Error: The request failed with status code:500
```
This error message shows every time I reload the page. Although the UI looks good to me by far.

**Comment by krishnadurai** [comment]
@nicklhy you'll need to pick your deployment config from this newer 0.6.2 release. The configs were not pinned to a certain commit which has the fix.

Refer issues:
#3900
#3969
#3982

**Comment by nicklhy** [comment]
The problem disappeared after upgrading the config to v0.6.2.

**Comment by dagondagon666** [comment]
> @nicklhy could you please change Istio's ClusterRbacPolicy as 'OFF' instead of 'ON'?
> 
> BTW, you could access the UI with the NodePort 31380.

Still need to change ClusterRbacPolicy to OFF when installing with 1.0.1. Is this normal?

**Comment by krishnadurai** [comment]
@dagondagon666 the config kfctl_k8s_istio.yaml already has ClusterRbacPolicy set to OFF.

**Comment by dagondagon666** [comment]
> @dagondagon666 the config kfctl_k8s_istio.yaml already has ClusterRbacPolicy set to OFF.

No I think it set to "ON"?

https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml#L46

**Comment by krishnadurai** [comment]
@dagondagon666 here's the file for kfctl_k8s_istio.yaml:

https://github.com/kubeflow/manifests/blob/8e6548d7a0beed5309b44472818cbee2afebd95a/kfdef/kfctl_k8s_istio.v1.0.1.yaml#L42

Whereas kfctl_istio_dex.yaml is an auth enabled setup and will have the setting as 'ON'.

**Comment by dagondagon666** [comment]
> @dagondagon666 here's the file for kfctl_k8s_istio.yaml:
> 
> https://github.com/kubeflow/manifests/blob/8e6548d7a0beed5309b44472818cbee2afebd95a/kfdef/kfctl_k8s_istio.v1.0.1.yaml#L42
> 
> Whereas kfctl_istio_dex.yaml is an auth enabled setup and will have the setting as 'ON'.

Ahh you are right, I recalled the wrong issue (or story) actually. For this thread we are using the kfctl_k8s_istio.yaml and for #4846 it's using the dex one
