### ISSUE TITLE
Version v0.6.2-rc.1 centraldashboard can not open subpage like as pipeline、katlib、notebookserver page etc.

### ISSUE THREAD

**Issue by lanya16** [kubeflow/kubeflow#3976]
/kind bug
**What steps did you take and what happened:**
![image](https://user-images.githubusercontent.com/22021811/63501765-d5402980-c4fe-11e9-9864-5d30ba8e009e.png)
problem like above image showing, when I access pipeline or jupyter notebook  or katlib, it navigiate to error page.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Kubeflow version: v0.6.2-rc.1
- kfctl version: kfctl v0.6.2-rc.1
- Kubernetes platform: meta device
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS: Ubuntu 18.04.2 LTS
-LoadBalancer: metallb V0.8.1

- config file: export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.2-rc.1/bootstrap/config/kfctl_k8s_istio.yaml"

**Comment by beatgeek** [comment]
This looks similar to what you see when you use a service IP rather than an LB endpoint for the UI

**Comment by lanya16** [comment]
![image](https://user-images.githubusercontent.com/22021811/63559309-78d31d80-c583-11e9-9958-197940a0007d.png)
@beatgeek

**Comment by lanya16** [comment]
It is my fault, I should edit istio-ingressgateway to LB type , not edit centeraldashboard.
