### ISSUE TITLE
Envoy Ingress creation fails with Invalid value for field resource.iap.oauth2ClientSecret

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#3977]
/kind bug

Not sure if I'm missing some step or if this is a Kubeflow bug or a GCP one.

**What steps did you take and what happened:**
Using **0.6.2rc1**, deployed a GCP cluster with IAP following these steps:
[Deploy OAuth](https://www.kubeflow.org/docs/gke/deploy/oauth-setup/)
[Deploy using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/)

**What did you expect to happen:**
Istio-system envoy-ingress to be deployed.

**Anything else you would like to add:**
Current log for envoy-ingress

```
>> kubectl -n istio-system describe ingress
Name:             envoy-ingress
Namespace:        istio-system
Address:
Default backend:  default-http-backend:80 (10.44.1.4:8080)
Rules:
  Host                                           Path  Backends
  ----                                           ----  --------
  gcp-kf1.endpoints.cpsg-ai-kubeflow.cloud.goog
                                                 /*                                                                        istio-ingressgateway:80 (<none>)
                                                 /.well-known/acme-challenge/tYrscv_ZnQzjv-XNsWccGeo_TDHJr4d3Mjww92KfETg   cm-acme-http-solver-gn7wm:8089 (<none>)
Annotations:
  certmanager.k8s.io/issuer:                         letsencrypt-prod
  ingress.kubernetes.io/ssl-redirect:                true
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"certmanager.k8s.io/issuer":"letsencrypt-prod","ingress.kubernetes.io/ssl-redirect":"true","kubernetes.io/ingress.global-static-ip-name":"gcp-kf1-ip","kubernetes.io/tls-acme":"true"},"creationTimestamp":"2019-08-22T09:29:31Z","generation":2,"labels":{"kustomize.component":"iap-ingress"},"name":"envoy-ingress","namespace":"istio-system","resourceVersion":"4324","selfLink":"/apis/extensions/v1beta1/namespaces/istio-system/ingresses/envoy-ingress","uid":"58608ca8-c4bf-11e9-9173-42010a8e00e3"},"spec":{"rules":[{"host":"gcp-kf1.endpoints.cpsg-ai-kubeflow.cloud.goog","http":{"paths":[{"backend":{"serviceName":"istio-ingressgateway","servicePort":80},"path":"/*"},{"backend":{"serviceName":"cm-acme-http-solver-gn7wm","servicePort":8089},"path":"/.well-known/acme-challenge/tYrscv_ZnQzjv-XNsWccGeo_TDHJr4d3Mjww92KfETg"}]}}]},"status":{"loadBalancer":{}}}

  kubernetes.io/ingress.global-static-ip-name:  gcp-kf1-ip
  kubernetes.io/tls-acme:                       true
Events:
  Type     Reason  Age                            From                     Message
  ----     ------  ----                           ----                     -------
  Normal   ADD     <invalid>                      loadbalancer-controller  istio-system/envoy-ingress
  Warning  Sync    <invalid> (x3 over <invalid>)  loadbalancer-controller  Error during sync: error running backend syncing routine: googleapi: Error 400: Invalid value for field 'resource.iap.oauth2ClientSecret': ''. IAP OAuth2 client secret must be set if IAP is enabled., invalid
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v0.6.2-rc.1
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by jlewi** [comment]
@krishnadurai Where did you see the error "iap.oauth2ClientSecret"
What value did you provide for the OAuth2 client secret?

**Comment by krishnadurai** [comment]
@jlewi This was in the GCP cloud console.
Navigating to Kubernetes Engine - Services and Ingress and clicking on envoy-ingress. This is where I had gotten the error.

I'll just re-test and report here.

**Comment by krishnadurai** [comment]
I've tested this again and it is working with a fresh run.
Seems the CLIENT_SECRET could have been picked by from earlier bash value.

Should we add a check at the beginning for CLIENT_ID - CLIENT_SECRET compatibility?

**Comment by krishnadurai** [comment]
Agreed.

/kind enhancement

**Comment by jlewi** [comment]
I don't believe there is any API we can use to validate the client and secret. 
The troubleshooting doc has instructions for changing the OAuth credential after it is deployed
https://www.kubeflow.org/docs/gke/troubleshooting-gke/#changing-the-oauth-client-used-by-iap

**Comment by krishnadurai** [comment]
Then we should close this issue. Since the docs cover enough on how to tackle this problem.

/close
