### ISSUE TITLE
service inception is up , but not able to use the inception_client 

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [kubeflow/kubeflow#398]
i have deployed inception model component but i am not able to use the inception client, I have made the implementation on GKE 3 Node cluster with details below:

Name	
default-pool
Size
3
Node version	
1.8.7-gke.1 Change
Node image	
Container-Optimized OS (cos) Change
Machine type	
n1-standard-4 (4 vCPUs, 15 GB memory)
Total cores	
12 vCPUs
Total memory	
45.00 GB
Automatic node upgrades	
Disabled
Automatic node repair	
Disabled
Autoscaling	
Off
Preemptible nodes	
Disabled
Boot disk size in GB (per node)	
100
Local SSD disks (per node)	
0
Instance groups	
gke-my-cluster-default-pool-cdafae44-grp

**kubeflow outputs:**

my-kubeflow $kubectl get svc inception -n=${NAMESPACE}
NAME        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
inception   ClusterIP   10.39.245.51   <none>        9000/TCP,8000/TCP   32s

my-kubeflow $kubectl get pods -n $NAMESPACE --show-all
NAME                               READY     STATUS    RESTARTS   AGE
ambassador-657699f59d-pwbm2        2/2       Running   0          1h
ambassador-657699f59d-qm2hq        2/2       Running   0          1h
ambassador-657699f59d-tkm76        2/2       Running   0          1h
inception-6878f8fc46-rjdx5         1/1       Running   0          1m
tf-hub-0                           1/1       Running   0          1h
tf-job-operator-55c9bc9765-b6ftz   1/1       Running   0          1h

my-kubeflow $kubectl port-forward inception-6878f8fc46-rjdx5 -n ${NAMESPACE} 9000:9000
Forwarding from 127.0.0.1:9000 -> 9000
Handling connection for 9000
Handling connection for 9000
Handling connection for 9000
Handling connection for 9000
Handling connection for 9000

my-kubeflow $curl -v http://127.0.0.1:9000
* Rebuilt URL to: http://127.0.0.1:9000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection #0 to host 127.0.0.1 left intact

**Comment by pdmack** [comment]
Sorry, but are you actually using the [inception_client](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py)? 

Someone else can correct me here but I think you need gRPC to communicate with the server. You won't be able to just curl it with HTTP 1.1

**Comment by jlewi** [comment]
@pdmack Is correct.

However, we do provide an http to gRPC proxy which should be running on port 8000. There are some instructions on using it [here](https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server/http-proxy)

**Comment by jlewi** [comment]
@ajayakumar-jayaraj Does that address your question can we close this issue?
