### ISSUE TITLE
Kubeflow deployment fails on kfctl apply

### ISSUE THREAD

**Issue by praveen049** [kubeflow/kubeflow#3989]
kind bug

**What steps did you take and what happened:**
i am using the kubeflow deployment guide here https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ for deploying kubeflow on Mac.

The step :
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/Users/xxxx/Desktop/know/ml/minikube/
echo $KFAPP
demo
echo $CONFIG
https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.1/bootstrap/config/kfctl_k8s_istio.yaml
kfctl init ${KFAPP} --config=${CONFIG} -V
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V

Generates the below error

INFO[0031] creating StatefulSet/application-controller-stateful-set  filename="kustomize/kustomize.go:440"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"

**What did you expect to happen:**
Expecte kubeflow deployment successful on my cluster

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 
- kfctl version: (use `kfctl version`): kfctl v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: (e.g. `minikube`): minikube 
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:57:42Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):uname -a
Darwin XXX-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by jlewi** [comment]
Can you run 

```
kubectl get crd
```

And see if the application CRD is installed? It should have been installed during the previous step.
https://github.com/kubeflow/kubeflow/blob/945a58b70b1f628d833c331533c4e96502101ee0/bootstrap/config/kfctl_k8s_istio.yaml#L44

**Comment by praveen049** [comment]
@jlewi  
crd is not installed

kubectl get crd
No resources found.

Any suggestion on how to resolve this ?

**Comment by jlewi** [comment]
@kkasravi why would the apply refactor fix this? Do we know why the Application resource wasn't installed?  

Could this be a race condition because the Application CR is still being created when we try to create an Application resource?

@praveen049 If you provide the full log output that would help us tell whether the Application CR was created before trying to create the Application resource. If it is then that suggests my hypothesis is that its a race condition.

I believe the apply refactor #3957 would allow to recover in that case by enabling you to just rerun kfctl apply to continue where you left off.

**Comment by jlewi** [comment]
@kkasravi Could you elaborate on what the problem is and why #3957 fixes this so we can close it out if it in fact it is fixed?

**Comment by kkasravi** [comment]
@jlewi @praveen049 

Jeremy - you're correct in that there is a lag time between when the application crd is registered and when an application can be submitted. 

Moving to kustomize3 #4055 where resources are sorted by crd first and having /manifests/application/application-crd separate from /manifests/application/application seems to fix this.

**Comment by yanniszark** [comment]
From the [Kubernetes Docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/):
```
It might take a few seconds for the endpoint to be created. You can watch the Established condition of your CustomResourceDefinition to be true or watch the discovery information of the API server for your resource to show up.
```

I suspect this is the exact problem we are hitting.

> Moving to kustomize3 #4055 where resources are sorted by crd first and having /manifests/application/application-crd separate from /manifests/application/application seems to fix this.

The following solutions:
* Applying CRDs first.
* Having CRDs in a separate kustomize package and installing it first.

work by mere coincidence. The race condition is still there, it's just less probable to hit it.
We should find a way to deal with this.

The most fool-proof way that comes to mind is waiting for the `Established` condition after creating a CRD.

/cc @jlewi @kkasravi

**Comment by jlewi** [comment]
## Work around in 0.6

I think if you hit this issue with 0.6 you can work around is to use this fix
https://github.com/kubeflow/kubeflow/issues/3810#issuecomment-527687504

to rerun apply.sh

**Comment by jlewi** [comment]
@yanniszark @kkasravi so is the work to close out this bug

1. Migrate to kustomize v3 #4055
1. Make sure `kfctl apply` can be rerun

    * This would at least make it easy for kustomize to mitigate by manually rerunning apply

> The most fool-proof way that comes to mind is waiting for the Established condition after creating a CRD.

1. Given we are already oversubscribed for 0.7 should we punt on further improvements to later?
1. Alternatively should we add backoff/retry logic in apply that would handle this use case?

**Comment by kkasravi** [comment]
i would opt to do further improvement later - since we have server-side, structured-schema and some other things that may make this easier to deal with in a generic way.

**Comment by richardsliu** [comment]
We should punt this to later.

**Comment by praveen049** [comment]
Hi
   Is it possible to deploy kubeflow now ?  Any instructions which i could use for deploying ?

Thanks

**Comment by praveen049** [comment]
Hi, i have tried the kubeflow deployment again with version 0.6.2. 

I am running into the same error:

INFO[0042] creating ClusterRoleBinding/application-controller-cluster-role-binding  filename="kustomize/kustomize.go:447"
INFO[0042] creating ConfigMap/application-controller-parameters  filename="kustomize/kustomize.go:447"
INFO[0042] creating Service/application-controller-service  filename="kustomize/kustomize.go:447"
INFO[0043] creating StatefulSet/application-controller-stateful-set  filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"

But this time, 
kubectl get crd

generates some output

NAME                                   CREATED AT
adapters.config.istio.io               2019-10-04T10:07:04Z
apikeys.config.istio.io                2019-10-04T10:07:04Z
applications.app.k8s.io                2019-10-04T10:07:45Z
attributemanifests.config.istio.io     2019-10-04T10:07:04Z
authorizations.config.istio.io         2019-10-04T10:07:04Z
bypasses.config.istio.io               2019-10-04T10:07:04Z
...
..

Please let me know if any more information is needed

**Comment by jlewi** [comment]
@praveen049 you are hitting a race condition as mentioned above. If you want to deploy with kfctl v0.6.2 you will need to do the following

1. Follow the KF instructions to run kfctl apply which will fail with the above errors
1. Create an apply.sh with the following contents

```
#!/usr/bin/env bash

for i in $(cat app.yaml | grep '^        path: ' | awk -F: '{print $2}');do
  childdir=${i#*/}
  if [[ -d kustomize/$childdir && -f kustomize/$childdir/kustomization.yaml ]]; then
    kustomize build kustomize/$childdir | kubectl apply -f -
    sleep 3
  fi
done
```
1. ```chmod +x apply.sh``` 
1. move the script to where  you called kfctl generate.
1. Run the script from that location

Ref https://github.com/kubeflow/kubeflow/issues/3810#issuecomment-527687504

Long term fix will be to use kfctl 0.7 which will fix the issues with rerunning kfctl apply.

**Comment by praveen049** [comment]
Hi @jlewi

With the workaround, the deployment is able to progress. Thank you. But i have now run into another issue - the pods image downloads are going to 'ImagePullBackOff' state.

$ kubectl -n kubeflow get pods
NAME                                                        READY   STATUS              RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                  0/1     ImagePullBackOff    0          12m
admission-webhook-deployment-b77bd65c5-pxwhp                0/1     ContainerCreating   0          12m
application-controller-stateful-set-0                       0/1     ImagePullBackOff    0          12m
argo-ui-6db54c878-wpb7k                                     0/1     ImagePullBackOff    0          12m

I am accessing from China and am using proxy with http_proxy, https_proxy and no_proxy for the kubectl cluster setting.

Anything i need to do additionally ?

Thanks

**Comment by hemantha-kumara** [comment]
@praveen049 Can you pls update proxy details in `/etc/sysconfig/docker` and try ?
something like below ?
```
HTTP_PROXY=http://<ProxyHost>:<Port>
HTTPS_PROXY=https://<ProxyHost>:<Port>
NO_PROXY=localhost,127.0.0.0/8
```

**Comment by praveen049** [comment]
@hemantha-kumara

I am running on mac and the proxy configuration are set in the docker UI and also in ~/.docker/config.json.  I have also created and set config in the /etc/sysconfig/docker.

Now the 
kubectl -n kubeflow get pods

shows that the status is ContainerCreating but the status does not change to Ready

NAME                                                        READY   STATUS              RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                  0/1     ContainerCreating   0          12m
admission-webhook-deployment-b77bd65c5-ql2tq                0/1     ContainerCreating   0          12m
application-controller-stateful-set-0                       0/1     ContainerCreating   0          14m
argo-ui-6db54c878-2zk4b                                     0/1     ContainerCreating   0          12m
centraldashboard-559bc9fb6d-br9nf                           0/1     ContainerCreating   0          12m

Am i still missing something ?

Thanks

**Comment by hemantha-kumara** [comment]
Can you please paste output  of pod describe here ?

**Comment by praveen049** [comment]
[output_kubeflow.txt](https://github.com/kubeflow/kubeflow/files/3700968/output_kubeflow.txt)

Attached is the output of the command

kubectl -n kubeflow get pods

The status remains 'ContainerCreating'

**Comment by praveen049** [comment]
Attaching the output of pod describe
[argo-ui.txt](https://github.com/kubeflow/kubeflow/files/3701150/argo-ui.txt)
[ml-pipeline-scheduledworkflow.txt](https://github.com/kubeflow/kubeflow/files/3701151/ml-pipeline-scheduledworkflow.txt)
[output_kubeflow.txt](https://github.com/kubeflow/kubeflow/files/3701152/output_kubeflow.txt)
[tf-job-dashboard.txt](https://github.com/kubeflow/kubeflow/files/3701153/tf-job-dashboard.txt)

**Comment by praveen049** [comment]
Out of all the describe for all pds
[describe_all_pods.txt](https://github.com/kubeflow/kubeflow/files/3701204/describe_all_pods.txt)

**Comment by hemantha-kumara** [comment]
@praveen049 
From the log, all seems fine(docker is getting pulled as there is no image pull off error), may be proxy is slow, hence it is taking time.
You can try pulling docker manually and see how fast image is getting pulled.
`docker pull gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta`

**Comment by praveen049** [comment]
@hemantha-kumara

yes, the problem was with the proxy. Now the image download are ok. Thanks

**Comment by jlewi** [comment]
@praveen049 so is this resolved?

**Comment by praveen049** [comment]
Hi @jlwei yes, the issue is fully resolved.   

Thank you.

**Comment by yanniszark** [comment]
@jlewi how is this resolved?
Is the race-condition around CRDs fixed somehow?
