### ISSUE TITLE
kfctl_existing_arrikto.yaml isn't installing application controller and CRD

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3999]
/kind bug

kfctl_existing_arrikto.yaml is not installing application controller and CRDs. As a result users can't do 

```
kubectl get applications
```

To see the list of installed applications. 
It also means the version on the centraldashboard isn't displayed correctly because there is no application to get the version from.

We need to fix this on the v0.6-branch and master.

**Comment by yanniszark** [comment]
Fixed in master by kfctl apply -f https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml.
For v0.6-branch: https://github.com/kubeflow/kubeflow/pull/4004
