### ISSUE TITLE
kfctl supports v1beta1 of KfDef (and v1alpha1)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4002]
/kind feature

In 0.7 we will introduce a v1beta1 spec for KFDef.
See #3478

This issue tracks adding support for that new spec to kfctl.

With 0.7 we should aim to provide backwards compatibility with v1alpha1 specs. To support that; we should define a conversion function which converts v1alpha1 specs to v1beta1 specs.

**Comment by jlewi** [comment]
@gabrielwen Could you provide an update and ETA please?

**Comment by richardsliu** [comment]
@gabrielwen Can this be closed?
