### ISSUE TITLE
Provided notebook name needs parsing to follow accepted kubernetes naming convention for resources like mounted volumes

### ISSUE THREAD

**Issue by LeonardAukea** [kubeflow/kubeflow#4003]
/kind bug

I installed kubeflow on my local kubernetes cluster following the instructions for `kfctl_k8s_istio`. 
This worked fine and dandy. I happened to notice that there where some restrictions for what may be provided as a name for the notebook, if a server was to launch sucessfully. I guess this is due to the mounted volume name being inherited from the name given to the notebook. It would make sense to make sure all names provided to rescources follow the following rules: 

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions. https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

I tried to find the location in the codebase to add functionality for parsing the notebook name  in order to force the above conventions when allocated to some kubernetes resource (volume, container, ..) but I'm not yet very familiar with the codebase. I guess that it has something to do with the templated 
var `notebook-name`. One could pipe lower and remove special chars and replace whitespaces and underscores with `-`. (Assuming jinja2)    

**Environment:**
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: kfctl v0.6.2-rc.2
- Kubernetes platform: docker-for-desktop
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): macOS 10.15 (19A536g)

**Comment by jlewi** [comment]
Thanks @LeonardAukea for the report. Were you using the UI to create notebooks or were you creating notebooks using the kubectl CLI?

@kimwnasptd Is this something we should fix in the spawner UI?

**Comment by jlewi** [comment]
Per #3970 looks like we also need to reject invalid names.

**Comment by LeonardAukea** [comment]
@jlewi I was using the UI. The name of the server needs to be parsed according to convention.

**Comment by vkoukis** [comment]
@jlewi
> @kimwnasptd Is this something we should fix in the spawner UI?
It doesn't impact correctness, but it will improve the UI if the notebook manager UI rejects invalid names early on. We will pick this up for 0.7.

/assign kimwnasptd
/assign elikatsis

**Comment by jlewi** [comment]
@vkoukis @kimwnasptd any update on this?
