### ISSUE TITLE
Kubeflow Jupyter Notebook "Jovyan" Password - Docs for installing fairing in CAIP notebook

### ISSUE THREAD

**Issue by SheharyarTkxel** [kubeflow/kubeflow#4005]
Trying to setup [Kubeflow Fairing](https://www.kubeflow.org/docs/fairing/install-fairing/#set-up-kubeflow-fairing-in-a-hosted-jupyter-notebook) with its installation guide. As instructed in this guide we are supposed to run "docker ps" in the Jupyter Notebook Terminal. However, it turns out that, although, Docker is installed already (verified it by reinstalling with pip) it doesn't let us use the "docker ps" command. This is what it says when we enter "docker ps":
`/bin/sh: 4: docker: not found`

I tried reinstalling by other methods but since sudo command doesn't work in this terminal because of the lack of password for Jovyan, it doesn't let Docker install again due to permission issues.

**What I want:**
Either let me know how to configure Docker so that I may be able to utilize the already installed Docker with commands like "docker ps" or otherwise let me know how to pass through the step when it asks for Jovyan's password on "sudo su -".

**Comment by jlewi** [comment]
@SheharyarTkxel are you running in GCP hosted notebook?
https://cloud.google.com/ai-platform/notebooks/docs/

Those instructions are specific to running a Cloud AI Platform notebook. 


@karthikv2k Should we clarify the docs to make it clear those instructions are for a CAIP notebook and not a kubeflow notebook?

Is there a reason CAIP notebooks require special instructions? Why aren't the instructions the same as for local environment/ non Kubeflow notebook?

**Comment by saurabh24292** [comment]
The issue is same even for local environment. Can the docs be please updated in case they are not yet. And if the docs are already updated, this is probably a bug. Any workarounds? The only one I see is to be able to be root here.

**Comment by saurabh24292** [comment]
Anything here?

**Comment by neupaneaj** [comment]
How was this issue resolved? Can somebody please update the solution. 

I have come across the same issue.

**Comment by piyushcse29** [comment]
I am also on the same trouble.

**Comment by pvgbabu** [comment]
Hi All, Any iupdate on this, I am facing same issue. how to install docker in kubeflow notebooks for fairing

**Comment by hemangjoshi37a** [comment]
Has anyone found any password yet for jovyan??

please help.

**Comment by charlesparasa** [comment]
same here please help
