### ISSUE TITLE
Adding --skip flag to `kfctl`  in order to choose not to install services already existing on running cluster. 

### ISSUE THREAD

**Issue by LeonardAukea** [kubeflow/kubeflow#4010]
/kind feature

We have decided to go  with kubeflow in order to provide a great platform for Data Science teams. We are currently trying to get an installation going of kubeflow on our existing cluster. In order to do this we would like to decoulpe `isto`,`dex`, `argo` that we already have set up. Let's just say, that these steps are currently not very intuitive and thus it would be great to have the option to use and configure already installed services. Having the `--skip` option would be of great aid. Furthermore, some nice readme of how to configure some of these manually. I think this is a common use case.

**Comment by yanniszark** [comment]
@LeonardAukea 
This can already be achieved by editing the KfDef config file and removing the applications that you don't need.
However, I do believe that we need better documentation on how to edit the KfDef file.
Relevant issue from website: https://github.com/kubeflow/website/pull/1093

**Comment by LeonardAukea** [comment]
@yanniszark That is what we are currently doing. Another issue we stumbled upon was that `kfctl delete all    ` actually messed up previously installed dex and istio
