### ISSUE TITLE
kubeflow installer does not create katib/metadatadb database

### ISSUE THREAD

**Issue by boniek83** [kubeflow/kubeflow#4011]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Install fresh kubeflow 0.6.2 with fresh pv for katib-db and metadata-db. Readiness probe fails in bofh cases.

**What did you expect to happen:**
Database should be created automatically if it doesn't exist.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.6.2
- kfctl version: (use `kfctl version`): v0.6.2-0-g47a0e4c7
- Kubernetes platform: (e.g. `minikube`) kubernetes
- Kubernetes version: (use `kubectl version`): 1.14.5
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by hougangliu** [comment]
@boniek83 yes, for katib-db, the below ENV will create katib database automatically if it doesn't exist (https://hub.docker.com/_/mysql). Can you show me the pod logs of katib-db? how many times had the Pod restarted?
```
          - name: MYSQL_DATABASE
            value: "katib"
```

**Comment by hougangliu** [comment]
AFAIK, for some PV, `mysql:8` docker image cannot work well anyhow.
@boniek83  so you can also try to change image of katib-db deployment to `mysql:5`  and change `datadir` value of katib-db deployment as below to try what happens.
```
        args:
        - --datadir
        - /var/lib/mysql/anotheranyname
```

**Comment by johnugeorge** [comment]
Is your PVC bound to PV? Please provide more information

**Comment by boniek83** [comment]
I am using https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner as storage provisioner on on-premises kubernetes cluster. PVC is bound to PV. 

On mysql:8 I can manually create database when inside of db container. Only after creating database manually, service shows active endpoint and I can telnet to katib-db at port 3306. I didn't test if connetion works with mysql client command due to errors earlier and recommendation to try mysql 5.

When using mysql:5 image database brings itself up (database is created automatically) but katib-manager is not working:
> [mysql] 2019/08/30 10:24:17 packets.go:36: unexpected EOF
is printed to logs and katib-manager restarts. Telnet to katib-db at port 3306 from another container works, but mysql -h katib-db -P 3306 -u root -p doesn't, command exits with error:
> ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0


Will there be an option to specify our own mysql instance and username? Running mysql on kubernetes with root is not a good practice - no replication, no monitoring, no backups, no security.
