### ISSUE TITLE
Jupyter CR should support substatus

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4016]
/kind feature

Jupyter custom resource needs to support sub resource per our application requirements (kubeflow/community#285).

Its possible it already supports subresource in which case we just need to verify it and then we can close this issue.

[Docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource)

**Comment by kimwnasptd** [comment]
The status subresource is already implemented in the Jupyter CR. Both in the [current](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go#L67) Controller as well as in the [next iteration](https://github.com/kubeflow/kubeflow/blob/72677737f64cdf1a21479dac979ebafabe27cb59/components/notebook-controller/api/v1alpha1/notebook_types.go#L62) that @lluunn is writing. 

We are also updating the status of a Jupyter CR instance to mirror the [containerStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#containerstatus-v1-core) of the first container in the underlying Pod.

**Comment by lluunn** [comment]
This is already done, both in the old and new version
