### ISSUE TITLE
CD for jupyter notebook controller

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4020]
/kind feature

**Why you need this feature:**
We'd like to continually build the jupyter notebook controller from the latest commits and update the  kustomize manifest to use the new image so that master is updated in a timely fashion.

We have some scripts/tooling for jupyter-web app here
https://github.com/kubeflow/kubeflow/tree/master/releasing/auto-update

This probably needs improvement

**Comment by jlewi** [comment]
Current status:

* @kkasravi Defined some initial tekton workflows in #4238
* kubeflow/testing#424 is tracking installing Tekton on our test clusters so we can run these workflows

I think the next critical step is to get Tekton installed on our releasing cluster to begin running these workflow

**Comment by kkasravi** [comment]
@jlewi I updated tektoncd-install to 0.8.0 ([here](https://github.com/kkasravi/kfctl-config-files/tree/master/tektoncd-install)) which allows a Pipeline to be embedded in PipelineRun. This allows all parameters to be defined in PipelineRun however it's dependent on removing builtin.NewLegacyOrderTransformerPlugin from kfctl (so resources are honored in the ordered listed)

**Comment by kkasravi** [comment]
Possible game plan
1. Get the kfctl fix in (noted above)
2. Update tekton-install in manifests to 0.8.0
3. Update the CI for components to use 0.8.0 (embedded Pipeline in PipelineRun)
4. kubeflow/testing#424

**Comment by lluunn** [comment]
cc

**Comment by jlewi** [comment]
@kkasravi  where does kfctl come into play?

* There's a Tekton PipelineRun defined [here](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/ci/pipeline-run.yaml) to do 

  * Instructions for running it are [here](https://github.com/kubeflow/kubeflow/tree/master/components/base)

So I would think we would need to do the following

1. Setup our releasing cluster to run these pipelines

    * Install tekton in our release cluster kubeflow/testing#424
    * Create [required secrets](https://github.com/kubeflow/kubeflow/tree/master/components/base) in the cluster

1. Install the [tekton pipeline templates](https://github.com/kubeflow/kubeflow/tree/master/components/base) in the cluster

1. Do a manual run(s) of the tekton pipeline to verify it works. 

1. Setup a solution to auto-trigger tekton CD workflows on post-submit and periodically

1. Setup a solution to auto sync the [tekton pipeline templates](https://github.com/kubeflow/kubeflow/tree/master/components/base) to the cluster


I have created a [column in the EngProd dashboard to track[(https://github.com/orgs/kubeflow/projects/13#column-7268759) this

**Comment by kkasravi** [comment]
> @kkasravi where does kfctl come into play?
> 

@jlewi 
Apologies - we can ignore kfctl. I had used kfctl to generate a pipeline for each component. 
Since it's a 'generator' I believe we agreed that it should be keep out of the actual CI/CD for now.

**Comment by jlewi** [comment]
@kkasravi I'm taking a look at the existing pipelines. I'm noticing that

1. It looks like the step to actual rebuild the manifests and presumably create the PR is commented out
  * https://github.com/kubeflow/kubeflow/blob/2da148904248d8616b50a0d8287742f2e2bdc968/components/base/task.yaml#L81

* Is this because that script isn't working yet?

1. It looks look like outputImageDir is no longer supported in Tekton

    * It looks like it is used [here](https://github.com/kubeflow/kubeflow/blob/2da148904248d8616b50a0d8287742f2e2bdc968/components/base/task.yaml#L41) to write the digest file of the newly built image to a PVC

   * It looks like the script in the next step is attempting to use that location to get the digest
     
* https://github.com/kubeflow/kubeflow/blob/2da148904248d8616b50a0d8287742f2e2bdc968/py/kubeflow/kubeflow/ci/rebuild-manifests.sh#L45

How come you used the PVC to pass the digest as opposed to using Tekton's support for passing files?

**Comment by kkasravi** [comment]
> * Is this because that script isn't working yet?
> 
no - it was working in the constant-cubist project. I usually add the 'sleep infinity' to debug in the container

> How come you used the PVC to pass the digest as opposed to using Tekton's support for passing files?

I had used the PVC as a place to share data across tasks. I wasn't aware of tekton's passing files support or perhaps it wasn't there in the version i developed against (i started when it was on 0.5.2 and ended with 0.7)

**Comment by jlewi** [comment]
@kkasravi oh maybe I'm mistaken about passing files but I thought it had some mechanism for handling artifacts and moving them between steps.

**Comment by jlewi** [comment]
Bump to P0 because it is required for 1.0.

Here's an update:

* kubeflow/testing#450 is the uber issue for CD 
* We have a sample Tekton PipelineRune for profile controller in
  * https://github.com/kubeflow/testing/tree/master/apps-cd/runs
* The next steps for kubeflow/testing#450 will include defining automation for the notebook controller as well as UI and other applications.
