### ISSUE TITLE
Notebooks connection error

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/kubeflow#4021]
/kind bug

**What steps did you take and what happened:**
Creating notebooks looks like it works but any connection returns a 404 error on the jupyter server. tried a bunch of different provided servers  and was only able to get the tensorflow 1.5 w/gpu image working. All other images return a webpage with a 404 error and a jupyter header. Custom images also do the same thing (tensorflow/tensorflow). I just upgraded from kubeflow v0.5 and all images I tried worked on that version. 

**What did you expect to happen:**
Notebook launches correctly from the dashboard

**Environment:**
- Kubeflow version: v0.6.2 
- kfctl version: v0.6.2-0-g47a0e4c7
- Kubernetes platform: Bare-metal
- Kubernetes version: 1.14.3
- OS: Ubuntu 18.04

**Comment by jlewi** [comment]
Thanks @SpontaneousDuck this was a bug in the notebook controller that was fixed in kubeflow/kubeflow#4402

The fix should be in 0.7.0 which we released this morning.
