### ISSUE TITLE
Central dashboard liveness and readiness probes

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4022]
/kind feature

Central dashboard needs liveness and readiness probes.

**Comment by jlewi** [comment]
@avdaredevil thinks we already have liveness and readiness handlers; are they configured though in the kustomize manifest?

**Comment by jlewi** [comment]
@avdaredevil Could you please update this bug with the URLs to be used for readiness and liveness checks so that we can get the manifests updated please?

**Comment by avdaredevil** [comment]
The 2 urls that can be used are:
- `<host>/debug` - User info, server info
- `<host>/api/workgroup/env-info` - User related environment info (namespaces, user access, platform data)

**Comment by jlewi** [comment]
I'm reopening this.

See kubeflow/kubeflow#4718 it looks like #777 used env-info as the liveness probe. That URL however ends up failing if the profile controller is deployed.

I don't think the liveness check for the centraldashboard should depend on external services. That means the liveness check ends up being a check on the liveness of external services.

@avdaredevil Does <host>/debug have dependencies on external services? 

How difficult would it be to create a separate <host>/healthz URL?

My concern with using <host>/debug is that overtime it might evolve and overtime no longer be suitable for a liveness probe.

**Comment by avdaredevil** [comment]
Sure given the points aforementioned, I could write up a healthz route for CD. Would you mind outlining the API spec for this route? What should it serve, what things should I check for, etc?

**Comment by jlewi** [comment]
@avdaredevil The liveness probe should indicate the central dashboard is alive. So how about starting with "/healthz" that just returns a 200?

**Comment by jlewi** [comment]
The change to the centraldashboard is in
https://github.com/kubeflow/manifests/commits/0831dd56a6fa9d205a0dfce3242f18c88ce01295

I verified this as

```
kubectl -n kubeflow port-forward service/centraldashboard 8080:80
curl http://localhost:8080/healthz
{"codeEnvironment":"production","message":"I tick, therfore I am!"}
```

So next step is just updating the manifest

**Comment by jlewi** [comment]
This has rolled out to master and v1
https://github.com/kubeflow/kubeflow/issues/4718#issuecomment-582180377
