### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by chaosxeras** [kubeflow/kubeflow#4025]
the images here are broken

https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/

**Comment by jlewi** [comment]
@chaosxeras Can you explain what broken means?

**Comment by chaosxeras** [comment]
Hi jlewi, here you go

![image](https://user-images.githubusercontent.com/14956538/64306302-eab85780-cfc4-11e9-9a89-0a07a347fa29.png)

<img src="../ConfigInputs.png" alt="ConfigInputs">
<img src="../LocalDeployment.png" alt="LocalDeployment">

**Comment by jlewi** [comment]
Thanks @chaosxeras 

Looks like an easy fix; looks like the doc is located here
https://github.com/kubeflow/website/blob/master/content/docs/other-guides/virtual-dev/getting-started-minikube.md

Images are here
https://github.com/kubeflow/website/tree/master/content/docs/started

We should probably move the PNGs into the same directory

@chaosxeras any interest in submitting a PR to fix this?

**Comment by chaosxeras** [comment]
Hi @jlewi, 

I have not done that before haha. Sorry, I'll leave it to you

**Comment by jlewi** [comment]
@mosn why isn't this a good-first-issue? It should be a pretty straightforward fix of the markdown docs and possible relocating some files in the source tree.

Where does docsy come into play here? Once you open a PR the presubmits will create a preview that can be used to verify its working.

**Comment by mosn** [comment]
@jlewi I will give it another shot. I guess I am a bit confused with the Hugo project and it backfired here.

**Comment by yeya24** [comment]
I' d like to open a PR for this.
