### ISSUE TITLE
Central dashboard 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4026]
/kind feature

Tracking issue for central dashboard to satisfy all of our 1.0 requirements based on kubeflow/community#285

We currently don't have a kanban board but here's a [search query](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Akubeflow+project%3Akubeflow%2F25+label%3Aarea%2Fcentraldashboard)

### Configuration and deployment

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Kustomize package  | Required  | Done |  
| Application CR  | Required  | Done | 
| Images listed in kustomization.yaml | Required  | Done |
| Upgradeability | Required  | No work needed |
| Separate cluster scoped and namespace scoped resources | Recommended  | Not Done |
| Kustomize package should be deployable on its own | Recommended  | Not Done |

### Logging and monitoring

| Description | Category |  Status | Issue
|-------------|----------|-------------|-------------|
| Liveness/Readiness signals | Required  |Not Done | kubeflow/kubeflow#4022 |
| Prometheus metrics | Required  | Not Done | kubeflow/kubeflow#4023 |
| Json logging | Recommended  | Not Done | |

### CI/CD

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| E2E tests | Required  | Not Done | kubeflow/kubeflow#4015 |
| Scalability / load testing | Required | Not Done | kubeflow/kubeflow#4024 |
| Continuous building of docker images | Recommended | Done | kubeflow/kubeflow#3781 |
| Continuous updating of Kustomize manifests | Recommended  | Done |  kubeflow/kubeflow#3781 |

### Docs

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| API Reference docs | Required | Not applicable |  |
| Application docs | Required | Done | kubeflow/website#1107 |

### Ownership/Maintenance

| Description | Category | Explanation | Status | Issue
|-------------|----------|-------------| ----------|-------------
| Healthy number of committers and commits | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| List of users running the application | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by jlewi** [comment]
It looks like the readiness and liveness probes were merged in #4022 but not on the 1.0 branch.

**Comment by jlewi** [comment]
kubeflow/manifests#777 is the cherry pick for the probes

**Comment by jlewi** [comment]
Here's the app CR from a 1.0 cluster deployed at
https://github.com/kubeflow/manifests/tree/861868c

The app CR is set.
[centraldashboard.app.yaml.txt](https://github.com/kubeflow/kubeflow/files/4153873/centraldashboard.app.yaml.txt)

**Comment by jlewi** [comment]
It looks like the remaining work is

* Fixing the liveness probe #4022 
* Adding prometheus metrics #4023
* Testing #4015 and #4023

**Comment by jlewi** [comment]
I think we are still waiting for the E2E test.

**Comment by jlewi** [comment]
@avdaredevil any update on the test?

**Comment by andreyvelich** [comment]
We can close it.
