### ISSUE TITLE
Does not work when k8s uses CRI other than docker (containerd in my case)

### ISSUE THREAD

**Issue by ciceroverneck** [kubeflow/kubeflow#4028]
/kind bug

```
MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
```

**What steps did you take and what happened:**
Install and start pipeline

**What did you expect to happen:**
Run the pipiline 

**Anything else you would like to add:**
```
kubectl get events conditional-execution-pipeline-5t6hm-2339328559.15bf1c0200eeb0cb
LAST SEEN   TYPE      REASON        OBJECT                                                MESSAGE
55s         Warning   FailedMount   pod/conditional-execution-pipeline-5t6hm-2339328559   MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
```

**Environment:**

- Kubeflow version: v0.6.2
- kfctl version: v0.6.2
- Kubernetes platform: bare metal, kubeadm installation 
- Kubernetes version: v1.15.0 
- OS: Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by jlewi** [comment]
Thanks for the report.

I believe @Tomcli and @swiftdiaries are working on adding containerd support

See kubeflow/manifests#266

@swiftdiaries @Tomcli do you think this will be ready for 0.7?
