### ISSUE TITLE
Manage Contributors cannot distinguish user name with numerical characters

### ISSUE THREAD

**Issue by atsuik** [kubeflow/kubeflow#4036]
/kind bug

**What steps did you take and what happened:**
I tried to manage contributors to a namespace with Manage Contributors in central bashboard.
Our user names are distinguish individuals from numerical characters.

Such as
- a001@example.com
- a002@example.com
- ...

Manage Contributors creates `rolebindings.rbac.authorization.k8s.io` and `servicerolebindings.rbac.istio.io` for `a001@example.com` which name `user-a-example-com-clusterrole-edit`.

Since numerical characters are omitted from the resource names,
I could not add `a002@example.com` to contributors.

**What did you expect to happen:**
I expected that the resource name for `a001@example.com` is `user-a001-example-com-clusterrole-edit`.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v0.6.2
- kfctl version: (use `kfctl version`): v0.6.2
- Kubernetes platform: (e.g. `minikube`): kubeadm
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu18.04

**Comment by jlewi** [comment]
Thanks @atsuik for the bug report. 

@kunmingg is this an issue in the profile controller?
