### ISSUE TITLE
Use images from private registry

### ISSUE THREAD

**Issue by PrathamSolanki** [kubeflow/kubeflow#4037]
I want to use images that are present in a private GitLab registry. I found similar issues/questions but no definitive answer:

- [Can't pull notebook images in private registry except for gcr.io](https://github.com/kubeflow/kubeflow/issues/3516)
- [Not using secret when pulling from private Registry](https://github.com/kubeflow/pipelines/issues/695)

Can you please tell me how can I do this?

**Comment by hemantha-kumara** [comment]
@PrathamSolanki  does pulling images from private GitLab registry requires credentials ?

If credentials are not required, then it would be straight forward by changing manifests deployment/statefulset or base kustomization files to point to private registry image.
for eg in jupyter-web-app, image name  can be changed in  [kustomization.yaml](https://github.com/kubeflow/manifests/blob/d19cfbdaa7d92e5bf6f8fd9fbe148f8d1b6734ec/jupyter/jupyter-web-app/base/kustomization.yaml#L19)  
or you can directly edit in [deployment.yaml](https://github.com/kubeflow/manifests/blob/d19cfbdaa7d92e5bf6f8fd9fbe148f8d1b6734ec/jupyter/jupyter-web-app/base/deployment.yaml#L25) 

In other case if credentials are required for pulling images, then existing manifests may not be supporting credentials.
You may have to update manifests container section to  support this. you can refer below k8s doc link to update deployment/statefulsets.(imagePullSecrets)
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by danieldn** [comment]
There is an open issue addressing this feature
https://github.com/kubeflow/kubeflow/issues/3210

**Comment by PrathamSolanki** [comment]
So I managed to make it work:

1) Create a secret in the appropriate namespace:

```
kubectl create secret docker-registry gitlab-auth \
  --docker-server=$DOCKER_REGISTRY_SERVER \
  --docker-username=$DOCKER_USER \
  --docker-password=$DOCKER_PASSWORD \
  --docker-email=$DOCKER_EMAIL \
  -n kubeflow
```

2) Bind it to the service account:

`kubectl -n kubeflow patch serviceaccount pipeline-runner -p '{"imagePullSecrets": [{"name": "gitlab-auth"}]}'`

3) Inside the yaml that specifies Seldon config add:

```
predictors:
  - componentSpecs:
    - spec:
        imagePullSecrets:
          - name: gitlab-auth
```

**Comment by macrokernel** [comment]
Hi @prathamsolanki, 
It seems like Charmed Kubeflow 1.10 does not have the `pipeline-runner` serviceaccount:

```shell
$ kubectl -n kubeflow get serviceaccount pipeline-runner
Error from server (NotFound): serviceaccounts "pipeline-runner" not found
```

Can you advise on which SA should be used instead of `pipeline-runner`?
