### ISSUE TITLE
MPI Application

### ISSUE THREAD

**Issue by ozturkosu** [kubeflow/kubeflow#4042]
/kind question

**Question:**
[You can ask any question about this project.]

Hi,

I need to run MPI scientific application with Kubernetes. I have realized that kubeflow provide an option to use MPI with Kubernetes. However, from my understanding kuberflow is designed for Machine Learning application. Is it possible to use it with normal MPI application?

Thank you so much for your help,

Best

Emin

**Comment by jbottum** [comment]
@ozturkosu Hi, did you get this resolved or is it still an open question ?
