### ISSUE TITLE
Receiving ingress spec error when trying to follow tutorial

### ISSUE THREAD

**Issue by zmunro** [kubeflow/kubeflow#4044]
/kind bug

**What steps did you take and what happened:**
I was following the setup guide [here](https://www.kubeflow.org/docs/gke/deploy/deploy-ui/) and I decided to use the username and password option to connect to Kubeflow. When I hit create deployment, it got stuck on `Waiting for the kubeflow ingress to get ready...` and just kept printing that out for an hour. The `envoy-ingress` was stuck on "Creating" so I clicked on it and there was an error at the top of the page that said ```error while evaluating the ingress spec: service "kubeflow/ambassador" is type "ClusterIP", expected "NodePort" or "LoadBalancer"```. Sure enough the spec for that service says `type: ClusterIP`. Not sure what is going on but something is busted.

**What did you expect to happen:**
Kubeflow to be initialized without any hassles and the ingress to be initialized.

**Anything else you would like to add:**
I used the UI [here](https://deploy.kubeflow.cloud/#/deploy) to create the deployment.

**Environment:**
Brave browser

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): not used
- Kubernetes platform: GKE
- Kubernetes version: (use `kubectl version`): ```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-gke.6", GitCommit:"feb35bccc781d4b5d16125f53e396fe2643d6618", GitTreeState:"clean", BuildDate:"2019-07-26T17:47:00Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}```
- OS (e.g. from `/etc/os-release`): MacOS

**Comment by jlewi** [comment]
@zmunro Which version of Kubeflow did you try to deploy?

/cc @kunmingg

**Comment by marcoleewow** [comment]
Hi, I am also facing the same problem with the UI deployment on v0.6.2

**Comment by kunmingg** [comment]
@marcoleewow 
Can you share output of 
`kubectl describe ingress -n istio-system`?

**Comment by jlewi** [comment]
We just released 0.7.0 which fixes a number of bugs.
Please try the latest release and if you are still having problems please open a new issue.
