### ISSUE TITLE
Deprecate kfctl.sh in the program & related scripts

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4045]
**Why you need this feature:**
People try and use kfctl.sh since it's there and matches the name they expect, and external documentation points to this.

**Describe the solution you'd like:**
We should print in RED that the shell script has been replaced with the `kfctl` go program and they should not use this.

**Anything else you would like to add:**

If we really wanted people to notice we could exit with a non zero exit code unless they set a KF_DEPRECATED_FEATURES flag.

**Comment by jlewi** [comment]
Should we just delete it? I think I had suggested deleting it but @Jeffwan (or someone else?) had pointed out that there were still references to it in some places. 

At this point though its so old and still using ksonnet that I don't think it even works anymore. So I'm not sure what value there is in keeping it.

**Comment by holdenk** [comment]
I think just deleting it would be the best path forward.

**Comment by holdenk** [comment]
Gave a first stab at it in - https://github.com/kubeflow/kubeflow/pull/4084

**Comment by Jeffwan** [comment]
It makes sense to remove scripts folder now. Last time I mean `ksonnet` package have still have reference and I am not sure if all components have been migrated. I would suggest to move that folder later.
