### ISSUE TITLE
Create a ksonnet component to deploy seldon-core models

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#405]
Just like the [tf-serving](https://github.com/kubeflow/kubeflow/tree/master/kubeflow/tf-serving) component, we should have a `seldon-core-serving` component which allows us to deploy/serve seldon core models

**Comment by lluunn** [comment]
Isn't this one? https://github.com/kubeflow/kubeflow/tree/master/kubeflow/seldon

**Comment by ankushagarwal** [comment]
Wasn't aware of that. Closing this.
