### ISSUE TITLE
Profile & Kfam 1.0

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4058]
Place holder for graduating the Profile & Kfam to 1.0

Below is a table based on our proposed application requirements (see kubeflow/community#285)

### Configuration and deployment

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Kustomize package  | Required  | Done |  
| Application CR  | Required  | Done | kubeflow/manifests#343
| Images listed in kustomization.yaml | Required  | Done |
| Upgradeability | Required  | Done | kubeflow/kubeflow#4070
| Separate cluster scoped and namespace scoped resources | Recommended  | NA |
| Kustomize package should be deployable on its own | Recommended  | Not Done |

### Custom Resources

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Version stability | Required  | Done | kubeflow/kubeflow#4071
| Backward compatibility | Required  | Done | kubeflow/kubeflow#4072
| Supports status subresource | Required  | Done | kubeflow/kubeflow#4073
| CRD schema validation | Required  | Done | kubeflow/kubeflow#4074

### Logging and monitoring

| Description | Category |  Status | Issue
|-------------|----------|-------------|-------------|
| Liveness/Readiness signals | Required  | Done | kubeflow/kubeflow#4075
| Prometheus metrics | Required  | Done | kubeflow/kubeflow#4076
| Json logging | Recommended  | Not Done | | 

### CI/CD

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| E2E tests | Required  | Done | kubeflow/kubeflow#4077
| Scalability / load testing | Required | Not Done | kubeflow/kubeflow#4078
| Continuous building of docker images | Recommended | Not Done | |
| Continuous updating of Kustomize manifests | Recommended  | Not Done | 

### Docs

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| API Reference docs | Required | Not Done | kubeflow/website#1123 |
| Application docs | Required | Not Done | kubeflow/website#1124 |

### Ownership/Maintenance

| Description | Category | Explanation | Status | Issue
|-------------|----------|-------------| ----------|-------------
| Healthy number of committers and commits | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| List of users running the application | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by jlewi** [comment]
@kunmingg could you provide an update? How are we doing for 1.0?

**Comment by jlewi** [comment]
@kunmingg could you provide an update? It would be great to update the table in the initial comment to reflect current status.

It looks like issues #4071-#4073 are all done. So can we mark all the custom resource issues as done?

Logging & monitoring issues are also fixed; can we mark those items as done?

It looks like the primary work remaining might be the docs?

**Comment by kunmingg** [comment]
Updated, docs should not be release blocking?

**Comment by jlewi** [comment]
@kunmingg docs are critical to 1.0. Can we finalize the docs as part of the doc sprint?

**Comment by jlewi** [comment]
@kunmingg ping?
