### ISSUE TITLE
Metadata for kubeflow 1.0

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#4059]
What task should be finished when Kubeflow releases its 1.0
/assign @zhenghuiwang

**Comment by jbottum** [comment]
@jlewi are we tracking this in another issue? should this be a p0 for Kubeflow 1.0?

**Comment by jlewi** [comment]
Metadata is currently planned for 1.0 as part of Kubeflow 1.0. So I think this is the only bug we have.

/cc @zhenghuiwang
