### ISSUE TITLE
Notebook controller should expose liveness/readiness signal

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4060]
/kind feature

**Why you need this feature:**
part of jupyter 1.0 https://github.com/kubeflow/kubeflow/issues/3656

**Comment by jlewi** [comment]
Bump to P0 because its required for 1.0

**Comment by jlewi** [comment]
@kunming @johnugeorge @richardsliu does controller runtime provide any out of box signals we can use for liveness and readiness?

**Comment by johnugeorge** [comment]
It was added recently in https://github.com/kubernetes-sigs/controller-runtime/pull/419

**Comment by jlewi** [comment]
@johnugeorge Would we have to update the controller-runtime that we are using in order to take advantage of that? How difficult is that likely to be?

**Comment by johnugeorge** [comment]
I see that controller runtime used in notebook controller is 0.2.0 https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/go.mod#L12 

However, https://github.com/kubernetes-sigs/controller-runtime/pull/419 changes are only in 0.4.0. This requires update of controller runtime pkg. However, there are breaking changes described in https://github.com/kubernetes-sigs/controller-runtime/releases.

**Comment by jlewi** [comment]
@kunmingg looks like we need to cherry-pick #837 into the 1.0 branch

**Comment by kunmingg** [comment]
@jlewi https://github.com/kubeflow/manifests/pull/845

**Comment by jlewi** [comment]
Confirmed this is working in a v1 cluster deployed at
https://github.com/kubeflow/manifests/tree/32aba35

[notebook-controller-deployment.yaml.txt](https://github.com/kubeflow/kubeflow/files/4156846/notebook-controller-deployment.yaml.txt)

**Comment by MartinForReal** [comment]
related #5197
