### ISSUE TITLE
KFServing for Kubeflow 1.0

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#4061]
Tasks on KF serving deployment needs to be complete for Kubeflow 1.0

Below is a table based on our proposed application requirements (see kubeflow/community#285)

### Configuration and deployment

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Kustomize package  | Required  | |  
| Application CR  | Required  |  | 
| Images listed in kustomization.yaml | Required  |  |
| Upgradeability | Required  |  |
| Separate cluster scoped and namespace scoped resources | Recommended  |  |
| Kustomize package should be deployable on its own | Recommended  |  |

### Custom Resources

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Version stability | Required  |Not Done  |
| Backward compatibility | Required  | Not Done |
| Supports status subresource | Required  | Not Done |
| CRD schema validation | Required  | Not Done|

### Logging and monitoring

| Description | Category |  Status | Issue
|-------------|----------|-------------|-------------|
| Liveness/Readiness signals | Required  | Not Done |
| Prometheus metrics | Required  | Not Done | |
| Json logging | Recommended  | Not Done | |

### CI/CD

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| E2E tests | Required  | Not Done | 
| Scalability / load testing | Required | Not Done | |
| Continuous building of docker images | Recommended | Not Done | |
| Continuous updating of Kustomize manifests | Recommended  | Not Done | 

### Docs

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| API Reference docs | Required | Not Done | |
| Application docs | Required | Not Done |  |

### Ownership/Maintenance

| Description | Category | Explanation | Status | Issue
|-------------|----------|-------------| ----------|-------------
| Healthy number of committers and commits | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| List of users running the application | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

### Image License
https://github.com/kubeflow/kubeflow/issues/4061

**Comment by animeshsingh** [comment]
@zhenghuiwang can you point me to the markdown behind the issue - would like to replace the tables in kfservign repo and start getting them filled to chase it down

**Comment by zhenghuiwang** [comment]
@animeshsingh the issue is generated from [this markdown].(https://github.com/kubeflow/community/pull/285/files#diff-16c3cd6e7ec2e780a917f291ac999bb1)

**Comment by jlewi** [comment]
@ellis-bigelow @animeshsingh  do we expect KFServing to be 1.0 in time for Kubeflow 1.0?

I think there was some discussion that for Kubeflow 1.0 we might scope down graduating the model servers used by KFServing to 1.0.
