### ISSUE TITLE
Notebook manager UI 1.0

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4062]
/kind feature

Tracking issue for Notebook Manager UI to satisfy all of our 1.0 requirements based on kubeflow/community#285

[Kanban board tracking issues](https://github.com/orgs/kubeflow/projects/11)

### Configuration and deployment

| Description | Category | Status | Issue
|-------------|----------|-------------| -------------
| Kustomize package  | Required  | Done |  
| Application CR  | Required  | Needs verification | #4068
| Images listed in kustomization.yaml | Required  | Done |
| Upgradeability | Required  | Not Done | #4067 
| Separate cluster scoped and namespace scoped resources | Recommended  | Not Done |
| Kustomize package should be deployable on its own | Recommended  | Not Done |

### Logging and monitoring

| Description | Category |  Status | Issue
|-------------|----------|-------------|-------------|
| Liveness/Readiness signals | Required  | Not Done | #4069
| Prometheus metrics | Required  | Not Done |  #4086
| Json logging | Recommended  | Not Done | |

### CI/CD

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| E2E tests | Required  | Not Done | #4087 |
| Scalability / load testing | Required | Not Done | #4088 |
| Continuous building of docker images | Recommended | Not Done |  |
| Continuous updating of Kustomize manifests | Recommended  | Not Done |  |

### Docs

| Description | Category | Status | Issue |
|-------------|----------|-------------|-------------|
| API Reference docs | Required | Not applicable |  |
| Application docs | Required | Not Done |  |

### Ownership/Maintenance

| Description | Category | Explanation | Status | Issue
|-------------|----------|-------------| ----------|-------------
| Healthy number of committers and commits | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| List of users running the application | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by jlewi** [comment]
@kimwnasptd Could you provide an update on how the Jupyter Web App is looking for 1.0? 

I see [1 P0](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Akubeflow+label%3Aarea%2Fjupyter+label%3Apriority%2Fp0) and  [18 P1s](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Akubeflow+label%3Aarea%2Fjupyter+label%3Apriority%2Fp1) related to jupyter (but not necessarily the jupyter web app).

What are the absolute must have P0s for the Jupyter Web App for 1.0?

**Comment by jlewi** [comment]
@kimwnasptd could you update this issue?

I looks like we currently have [4 P0s](https://github.com/orgs/kubeflow/projects/11#column-7596321)

**Comment by jlewi** [comment]
@kimwnasptd @cvenets could you provide an update here? How are the remaining P0s looking?

**Comment by kimwnasptd** [comment]
@jlewi the only blocking one is the e2e tests. I've created a [PR](https://github.com/kubeflow/kubeflow/pull/4773) with some initial tests.

The remaining work is to handle the IAP login in the tests and bundle it as a postsubmit test

**Comment by andreyvelich** [comment]
We can close it.
