### ISSUE TITLE
[Notebook controller] support json logging

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4066]
/kind feature

**Why you need this feature:**
part of jupyter 1.0

Applications should optionally emit structured logs with suitable metadata to facilitate debugging.

e.g. CR controllers should annotate log messages with the name of the resource involved so it's easy to filter logs to all messages about a resource

**Comment by mapdegree** [comment]
Request to re-open. It would be very beneficial to have the option to set logs in JSON format as many of users redirect logs into Elastic.

Thanks
