### ISSUE TITLE
Notebooks Manager UI needs liveness/readiness probes

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4069]
/kind feature

**Why you need this feature:**
Required for Kubeflow 1.0 inclusion of Notebooks Manager UI

**Describe the solution you'd like:**
Notebooks manager UI needs liveness and readiness probes

**Comment by jlewi** [comment]
@kimwnasptd Does the jupyter web app already have a suitable endpoint for liveness and readiness checks or do we have to add one?

**Comment by kimwnasptd** [comment]
No, will need to add them for these checks

**Comment by jlewi** [comment]
Bump to P0 because its required for 1.0.
