### ISSUE TITLE
Profile & Kfam: Upgradeability

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4070]
Profile & Kfam: Upgradeability

**Comment by jlewi** [comment]
Bump to P0 because this is required for 1.0.

@kunmingg is there any work to be done? Should this just work out of the box?

**Comment by kunmingg** [comment]
Will test out once https://github.com/kubeflow/kubeflow/issues/4071 is closed

**Comment by kunmingg** [comment]
Verified
