### ISSUE TITLE
Profile & Kfam: Version stability

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4071]
To guarantee backward compatibility:
- Profile CRD should be locked in v0.7.0
- Kfam API should be locked in v0.7.0

----

Will create v1 API which will be same as v1beta1 and achieve compatibility for free.

**Comment by jlewi** [comment]
@kunmingg Is there more work to be done here? 

It looks like we have a v1beta1.
https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller/api

I'm guessing we need a v1 for 1.0. Do we have an issue for that?

**Comment by kunmingg** [comment]
Issue description updated.
Will create v1 API

**Comment by jlewi** [comment]
@kunmingg Looks like #4663 was merged. What is the remaining work to close this out?

**Comment by kunmingg** [comment]
This one can be closed
