### ISSUE TITLE
Profile & Kfam: Prometheus metrics

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4076]
See parent issue: https://github.com/kubeflow/kubeflow/issues/4058
And common formatting: https://github.com/kubeflow/kubeflow/issues/4099

**Comment by yeya24** [comment]
I' d like to work on this feature. But what metrics do we need?

**Comment by kunmingg** [comment]
@yeya24 
Thanks!
How about start with metrics in https://github.com/kubeflow/kubeflow/issues/4099?
Any suggestion on how to show error messages through prometheus metrics?

**Comment by yeya24** [comment]
> @yeya24
> Thanks!
> How about start with metrics in #4099?
> Any suggestion on how to show error messages through prometheus metrics?

Actually, error messages is not very suitable for prometheus metrics. They should be deal with some logging systems. 

At most times, we can just use a simple counter type to represent the total times of error.  If the type of error is limited, we can add the error type as a label of the metrics.

**Comment by kunmingg** [comment]
Sounds good, how about categorize errors by calling path and / or error severity?

**Comment by yeya24** [comment]
> Sounds good, how about categorize errors by calling path and / or error severity?

Actually, I don't think this make any sense. This should be done in logging.

**Comment by kunmingg** [comment]
Can we make `reuqest path` and `error severity` as 2 tags in errors?
So we alert is triggered, we can include them in alert messages, and oncall people will know which call path has errors, and roughy what kind of error it is?
For example for [kfam](https://github.com/kubeflow/kubeflow/blob/master/components/access-management/api/swagger.yaml) we can include the paths as error metrics tags

**Comment by jlewi** [comment]
@yeya24 Any update on this?

Bump to P0 because this is required for 1.0.

**Comment by yeya24** [comment]
@jlewi  Actually currently I am not working on this because I saw this PR https://github.com/kubeflow/kubeflow/pull/4251.
I am wondering do we need to wait until that PR merges?
