### ISSUE TITLE
Profile & Kfam: E2E tests

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4077]
Profile & Kfam: E2E tests

**Comment by jlewi** [comment]
We have the start of a test for the profile controller here:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/profiles/tests/profiles_test.py

It doesn't look like that test is running as part of CI though.

**Comment by nrchakradhar** [comment]
@kunmingg @jlewi 
I can give this a try. The workflows.libsonnet had this commented as WIP.
https://github.com/kubeflow/kubeflow/blob/2ea609c4bf963b988afaec387ce28abe5d2fa487/testing/workflows/components/workflows.libsonnet#L327
Profiles is now part of all kfdef.yaml s. 
I can make this test in lines similar to test_jupyter.py.
Once this is working, I assume we can include creation/deletion of "pre-post-test-profile" in the main e2e workflow and also validate other tests like notebook, tf-job, pipeline etc in the test profile.

Let me know if this is as per expectation. I will raise a PR.

**Comment by jlewi** [comment]
Yes I think we want something like test_jupyter.py 
We now use this file to define the E2E workflow
https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py

>  also validate other tests like notebook, tf-job, pipeline etc in the test profile.

I didn't quite understand this.

**Comment by nrchakradhar** [comment]
> > also validate other tests like notebook, tf-job, pipeline etc in the test profile.
> 
> I didn't quite understand this.

If my understanding is correct, we run e2e tests still in kubeflow namespace. For better multi-user experience tests, it may be good to create a specific test profile and run these tests. Please correct any incorrect understanding of mine.

**Comment by jlewi** [comment]
@nrchakradhar You are correct. If e2e tests are running in the kubeflow namespace (e.g. spinning up a notebook) that will likely cause problems. 

Creating a specific profile is a good idea.

**Comment by nrchakradhar** [comment]
@kunmingg @jlewi 
Sorry for coming back on this late. I am planning to have the following for the e2e test of profile in pythonic way.  The jsonnet test will be removed.
**Creation:** 
1.   createProfile(profileYamlFile)

     - Reads a profile.yaml file and creates profile using `create_cluster_custom_object`

2.   verifyNamespaceCreation(name)
3.   verifyServiceAccounts(name)

       - "default-editor" and "default-viewer" are created

4.   verifyRolebindings(name)

       - 'kubeflow-admin', 'kubeflow-edit', 'kubeflow-view' rolebindings are present in the namespace

**Deletion**
1.   deleteProfile(group, version, name)

      - Using `delete_cluster_custom_object`, delete profile

2.   verifyProfileDeletion(name)

      - `get_cluster_custom_object ` raises exception

      - `read_namespace` raises exception

I will raise a PR sometime in the next week.

**Comment by nrchakradhar** [comment]
Kfam tests has not been included yet. Not sure if this needs to be reopened or a new issue tagged for kfam needs to be created?

**Comment by jlewi** [comment]
@nrchakradhar I reopened this. Lets not close this until its complete.

A couple notes

* I missed it in #4455 but it looks like you added the python code for the test in `kubeflow/profiles/tests/` 
* The code should probably move to either
   * py/kubeflow/kubeflow/ci/
   * or components/profile

* kubeflow/profiles is the old ksonnet directory which we want to delete (#4484)
* Python code should generally live under py/kubeflow/kubeflow
  * This makes it easy to add a single directory to the python path and then import it
  * if necessary we can create a new sub package to organize code related to the profile controller

* The E2E workflow has now moved to kubeflow/kfctl

   * https://github.com/kubeflow/kfctl/blob/master/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py

**Comment by jlewi** [comment]
Bump to P0 because this is required for 1.0.

@nrchakradhar any chance you could pick up some of the remaining work here?

**Comment by nrchakradhar** [comment]
@jlewi Sorry I will not be able to work on this. Unfortunately, in my current role/organisation I am not allowed to make contributions.

**Comment by kunmingg** [comment]
closed via
https://github.com/kubeflow/kfctl/pull/166
https://github.com/kubeflow/kubeflow/pull/4633
