### ISSUE TITLE
Jupyter notebook gives "Error during WebSocket handshake: Unexpected response code: 504"

### ISSUE THREAD

**Issue by anupash147** [kubeflow/kubeflow#4081]
/kind bug

I have implemented kubeflow in aws using https://deploy-preview-977--competent-brattain-de2d6d.netlify.com/docs/started/k8s/kfctl-k8s-istio/. Also configured my dex auth with my company policy.  I am able to setup the multiuser environment. But when i succeed creating the jupyter server and start using the server the notebook never connects.

On inspect i get error : Error during WebSocket handshake: Unexpected response code: 504

Nothing in the logs of container. 
[W 04:19:07.074 NotebookApp] Replacing stale connection: b94f2038-4331-4499-93b9-25932db96ff0:3fd26c97100c435d90e8ecd0737436b7
[W 04:21:11.891 NotebookApp] Replacing stale connection: b94f2038-4331-4499-93b9-25932db96ff0:3fd26c97100c435d90e8ecd0737436b7

How do i debug or fix it.

My Kubeflow version 0.6.0-rc2 running on kubenetes 0.14 deployed over ec2 machines using kops.

Screenshot : https://15905978862850875460.googlegroups.com/attach/f7afed2c6d72/Screen%20Shot%202019-08-31%20at%202.47.18%20PM.png?part=0.1&view=1&vt=ANaJVrFetsB8H7xKMriHhK3Jjud_o2K0KRovfUle6FuOHsurGeZ9iFyfHUkNehue5krB6ZE95MdFEfmDKorjh6ADXOLUByow6z4pLB34xvXR56sYXEI_16A

**Comment by anupash147** [comment]
Thanks fo the response @jlewi , I am using the istio gateway, and i tried adding upgradewebsocket : true ref : https://github.com/istio/istio/issues/9152 but it does not still seems to work. I still get the 504..

In work i editted the virtualservice that defines the routing to the gateway. Let me know if you need more information?

**Comment by anupash147** [comment]
Another related issue looks pretty much the same : https://github.com/kubeflow/kubeflow/issues/1344

**Comment by kunmingg** [comment]
@jlewi 
Shouldn't be related unless ambassador is being used.

@anupash147 
How did you configure dex?

**Comment by anupash147** [comment]
@kunmingg : we configured kubeflow to the OIDC protocol.

**Comment by fabianbaier** [comment]
Hi,

Iam running into an similar issue (though not using dex) on AWS. Protocol used for the ingress is `TCP` so I was hoping websockets would work out of the box. It works fine when using port-forwarding:

```kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80```

Best,
FB

**Comment by anupash147** [comment]
True, i also saw this issue when i enabled https over the gateway. This is when i was testing without istio enabled.

**Comment by jlewi** [comment]
@anupash147 If you are using EC2 did you try following the AWS directions?

/cc @Jeffwan

**Comment by jlewi** [comment]
@anupash147 @fabianbaier please describe the complete path for a request? I believe at every hop there's a potential for something to go wrong.

If it works when you port-forward to the ISTIO gateway e.g. 

```
kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80
```
Then this suggests the problem is upstream of Kubeflow. So it is most likely a configuration problem in the load-balancer (or whatever network stack you are using) to direct traffic to the ISTIO gateway.

**Comment by anupash147** [comment]
@fabianbaier 
```
kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:443
```
works .

**Comment by fabianbaier** [comment]
@jlewi 

I think you're right. This was most likely a problem with the load-balancer per se. I noticed when re-deploying it worked fine. Now that said I can't replicate the problem so I really hope it was a one time thing. I am sure to update you here if I run into this again.

@anupash147

So the idea behind this is to see if websockets via https work in general and then trying to identify the culprit from there? E.g. in this case if this portforwarding would work, looking as a next step at the LoadBalancer and if something goes there wrong with https?

**Comment by anupash147** [comment]
@fabianbaier : I redeployed into fresh cluster i did not even get to the point of 504 now but rather my notebook itself stopped working, it landed to a page which says "Sorry, /notebook/anup/t2/ is not a valid page"

On looking at my namespace i found out the virtual services had '*' in the hostname.

NAME                  GATEWAYS                      HOSTS   AGE
notebook-aash-test2   [kubeflow/kubeflow-gateway]   [*]     5d8h

now for rest of the services of which i control via manifest, i was able to change it to my host domain but the above one whenever i edit it to the desirable hostname it just swing back to '*'.. maybe this is the one that messes up the routing.

**Comment by anupash147** [comment]
@fabianbaier @jlewi : here is my loadbalancer annotation

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http2":"iap-backendconfig"}}'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '*'
```
applied to the istio-ingressgateway.

**Comment by anupash147** [comment]
Finally i have the solution : https://github.com/istio/istio/issues/11579

**Comment by yangpeng1994** [comment]
> 你好
> 
> 我在AWS上遇到了类似的问题（尽管没有使用dex）。用于入口的协议是，所以我希望websockets能够开箱即用。使用端口转发时，它可以正常工作：`TCP`
> 
> `kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80`
> 
> 最佳， FB

I did. It doesn't seem to work
