### ISSUE TITLE
Prometheus/Telemetry metrics for Notebooks Manager UI

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4086]
/kind feature

**Why you need this feature:**
Identify and create prometheus metrics for the Notebooks Manager UI. This issue is part of getting Notebooks Manager UI ready for Kubeflow 1.0

**Describe the solution you'd like:**
Idenitfy which metrics make sense to track the usage and usability of the Notebooks manager UI. Examples include:

   - #successful notebook creation
   - #notebook pods running across all namespaces, per namespace
   - #failures in pod deployment
   - #reused volume mounts
  and others.

**Comment by yeya24** [comment]
I' d like to work on this feature.

**Comment by abhi-g** [comment]
@yeya24 You're probably correct. The metrics I listed make more sense for the controller. Hopefully we can identify metrics more appropriate to the UI itself if any.

**Comment by yeya24** [comment]
> @yeya24 You're probably correct. The metrics I listed make more sense for the controller. Hopefully we can identify metrics more appropriate to the UI itself if any.

Yes, actually I some pod or infra related metrics are only useful in controller. For ui, some http api related metrics like total http requests, http latency are OK.

I will open a PR soon for controller metrics. But maybe I think we don't need metrics for ui, just does not make much sense.

**Comment by yeya24** [comment]
@abhi-g  Looks like the notebook-controller code in master branch has a bug. I apply my notebook.yml and it failed during reconciling:
``` bash
2019-09-13T15:43:38.301-0400    ERROR   controller-runtime.controller   Reconciler error        {"controller": "notebook", "request": "default/notebook-sample", "error": "Operation cannot be fulfilled on statefulsets.apps \"notebook-sample\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
```

**Comment by lluunn** [comment]
Let's leave this open and verify we have the metrics working.

**Comment by yeya24** [comment]
@lluunn  I think the metrics work. So do we need to close this issue?
