### ISSUE TITLE
Create end-to-end tests for Notebook Manager UI for releases

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4087]
/kind feature

**Why you need this feature:**
We need end-to-end tests for Notebook Manager UI to ensure releases are stable. This is an application criteria for Kubeflow 1.0.

**Describe the solution you'd like:**
We should inventory existing tests for the Notebooks manager UI and create any missing test flows.

**Comment by krishnadurai** [comment]
Thanks @abhi-g for creating this issue. A couple of questions here for the tests:
1) Which auth provider are we planning to include for the test?
2) Will this test go on to cover multi-user scenarios?

**Comment by jlewi** [comment]
Bump to P0 because this is a requirement for 1.0

**Comment by jlewi** [comment]
Duplicate of #3657
