### ISSUE TITLE
installs from releases such as 0.6 of kfctl are broken

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kubeflow#4093]
Thrift have moved from git.apache.org to github - https://github.com/hashicorp/terraform/issues/22664#issuecomment-527142529

This is fixed in master - https://github.com/kubeflow/kubeflow/issues/4051

But tagged versions also reference the old thrift git

**Comment by yanniszark** [comment]
@ryandawsonuk broken in what way?
I thought that git.apache.org was a source needed during the build of kfctl.
Is it used elsewhere inside a Kubeflow installation?

**Comment by ryandawsonuk** [comment]
Oh true what I was trying to do was build kfctl. But there's no need to do that for old releases as it can be obtained at https://github.com/kubeflow/kubeflow/releases/ Thanks
