### ISSUE TITLE
Namespace select only shows kubeflow-anonymous

### ISSUE THREAD

**Issue by gar1t** [kubeflow/kubeflow#4094]
/kind bug

**What steps did you take and what happened:**

1. Open dashboard
2. Try to select a namespace

The dropdown contents flash for a moment and then only show a single entry: `kubeflow-anonymous`.

See this video for a demo:

https://www.loom.com/share/70a896c7fe9948fe82cabb58221107c4

**What did you expect to happen:**

In my previous use of Kubeflow, there were a number of namespaces.

**Anything else you would like to add:**

During `kfctl apply` the behavior described in #4087 occurred. The operation exited with code 1 and the env eventually started (verify using `kubectl -n kubeflow get po` that all pods a running).

After a hard (cache clearning) page reload, I did not see any messages in the browser Console, nor did I see any non 2xx responses in Networks.

The payload of /api/env-info is:

```
{
  "user": "anonymous@kubeflow.org",
  "platform": {
    "kubeflowVersion": "v0.6.2",
    "provider": "other://",
    "providerName": "other"
  },
  "namespaces": [
  {
    "namespace": "kubeflow-anonymous",
    "role": "contributor",
    "user": "anonymous@kubeflow.org"
  }
  ],
  "isClusterAdmin": true
}
```

I see events for the `kubeflow` by opening the page with the path `/activity?ns=kubeflow` (i.e. manually editing the namespace in the browser URL).

**Environment:**

- Kubeflow version: `v0.6.2`
- kfctl version: (use `kfctl version`): `v0.6.2-0-g47a0e4c7`
- Kubernetes platform: microk8s
- Kubernetes version: `v1.15.3`
- OS: `Linux kubeflow 4.15.0-58-generic #64-Ubuntu SMP`

**Comment by danieldn** [comment]
I believe v0.6.2 only shows kubeflow-anonymous under namespace on initial deployment. It will then only show namespaces associated with user profiles created. https://www.kubeflow.org/docs/other-guides/multi-user-overview/

I do agree with the UX comment in the video when creating a new notebook server for the first time and trying to edit the namespace from the namespace box when you're suppose to have selected it from the top drop down.

**Comment by gar1t** [comment]
There's a lot of (log) activity under the 'kubeflow' namespace in 0.6.2.
The only way to view that, that I can tell, is to hack the URL
(`?ns=kubeflow`).

**Comment by avdaredevil** [comment]
As it stands, this seems to be the behavior that is expected for namespaces (in terms of the list you can see)

/cc @kunmingg @abhi-g 

In terms of the UX for notebooks, I agree, we could make this more intuitive (cc: @ajayalfred @kimwnasptd PTAL).

Thanks!

**Comment by gar1t** [comment]
If the `kubeflow` namespace isn't in the list, how is a user supposed to view the activity associated with that namespace?

**Comment by kunmingg** [comment]
Starting at v0.6.2, `kubeflow` namespace will be for infra services like controllers.
User can create notebooks or deploying workloads in their own namespace.
If identity-aware-proxy is not setup, the default user namespace is `kubeflow-anonymous`

**Comment by gar1t** [comment]
That makes sense. But what if someone wants to to view infra activity - for whatever reason?

**Comment by abhi-g** [comment]
The infra activity for Kubeflow namespace deployments should be accessible
via the K8s dashboard in general, or on GKE Hub on GKE.

**Comment by jlewi** [comment]
If you wanted to look at the kubeflow namespace you can also use kubectl

**Comment by shanidchamal** [comment]
Hi, i am using v0.6.2 and using a notebook server in my namespace to write a pipeline function using the Kubeflow Pipelines DSL with reference [link](https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/). i am also specifying the notebook server's pvc name with kfp.onprem.mount_pvc method to store the output to notebook server's directory. when i compile the code i get the link to experiment and run, but the run is in pending state with volume claim not found message.
i know the reason is that the pipelines are being created in kubeflow namespace and not in the notebook's namespace.
am i doing it the wrong way or is it the expected functionality as of now?
