### ISSUE TITLE
Monitoring for kubeflow 1.0

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4099]
/kind feature

**Why you need this feature:**
We need to have unified monitoring signals among kubeflow components:

- Central Dashboard
- Notebooks Manager UI
- Jupyter Notebooks Controller
- [Profiles Controller](https://github.com/kubeflow/kubeflow/issues/4076)
- TFJob Operator
- Model Deployment instance using Seldon

**Describe the solution you'd like:**
Common monitoring metrics should have `same name across all components`, with `each component name as tag` on the metrics.

Idea on common metrics:
```
liveness (heartbeat)
readiness
num_request
num_error
version
```

**Comment by kunmingg** [comment]
Should we break errors into sub types based on request path and / or error severity?
So errors now have 3 tags:
```
component
path
severity
```

**Comment by yeya24** [comment]
> Should we break errors into sub types based on request path and / or error severity?
> So errors now have 3 tags:
> 
> ```
> component
> path
> severity
> ```

I think severity make sense. But what is component for? Do you want all these kf component share the same metrics name, and only with different component tag?

**Comment by kunmingg** [comment]
Yes, ideally if components share metrics names then we can use same alert rules to apply on all of them.
For example we can use 1 alert rule to watch all components' `heartbeat`

metrics library would be great, the only challenge is not components written in go.

**Comment by jlewi** [comment]
@kunmingg beyond adding prometheus metrics to the individual applications; what is the P0 work for 1.0?
