### ISSUE TITLE
Kiali Path exposed on istio-ingressgateway as nodeport, but the service shows clusterIP 

### ISSUE THREAD

**Issue by yaser-hameed** [kubeflow/kubeflow#4103]
/kind question

Does kiali work out of the box with kubeflow version 0.6.2 with the istio gateway ? I can see the following in istio-ingressgateway. 

- name: https-kiali
    nodePort: 31988
    port: 15029
    protocol: TCP
    targetPort: 15029

However the kiali service is exposed as a cluster ip:

kubectl get svc kiali -n istio-system
NAME    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
kiali   ClusterIP   100.64.121.103   <none>        20001/TCP   4d

There are no virtual services for kiali as well. So will we need to create one to expose kiali via the gateway ?

**Comment by krishnadurai** [comment]
@yaser-hameed Looks like in the official helm chart for Istio installation they have exposed it through [kubernetes ingress](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml).
Could you see if this works for you?

**Comment by yaser-hameed** [comment]
I had deployed kubeflow using this https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/. It had deployed istio along with it, so i did not go with a separate helm isto installation. In the end i created a istio gateway and virutal services to access kiali, grafana and jaeger and got it working

**Comment by leela-uppuluri** [comment]
@yaser-hameed I started installing kubeflow-1.0 on kubernetes-v1.15 cluster and was following the same kubeflow office documentation but I am stuck at accessing the kubeflow dashboard which does need the setup of loadBalancer or NodePort or Port forwarding is required. I was confused with setting up the istio gateway and virtual service. Can you please walk me through the steps on how you did configure those to access kubeflow dashboard and other things?

**Comment by dzungductran** [comment]
@leela-uppuluri have you figure this out? I am having the same issue and can't find any instructions on how to get the dashboard to work correct.

**Comment by leela-uppuluri** [comment]
@dzungductran I actually tried NodePort port forwarding to 30080 and that worked for me to bring up the kubeflow dashboard. This is how the URL for kubeflow webui looks like on my end, http://<Worker_Node_IP>:30080/
