### ISSUE TITLE
Kfctl  init  --config="local file" failed

### ISSUE THREAD

**Issue by QxiaoQ** [kubeflow/kubeflow#4109]
/kind bug

**What steps did you take and what happened:**

 ./kfctl init kfapp-kfctl --config=kfctl_platform_gcp.yaml -V 
 return error 

INFO[0000] Downloading kfctl_platform_gcp.yaml to /tmp/677895880/app.yaml  filename="v1alpha1/application_types.go:334"
ERRO[0000] Could not load kfctl_platform_gcp.yaml; error  (kubeflow.error): Code 400 with message: could not fetch specified config kfctl_platform_gcp.yaml: relative paths require a module with a pwd  filename="coordinator/coordinator.go:266"
Error: couldn't create KfApp:  (kubeflow.error): Code 500 with message:  (kubeflow.error): Code 400 with message: could not fetch specified config kfctl_platform_gcp.yaml: relative paths require a module with a pwd
![Screen Shot 2019-09-11 at 2 55 07 PM](https://user-images.githubusercontent.com/31646170/64675199-2cee0700-d4a5-11e9-84f4-f140891daf6b.png)

**Environment:**

- kfctl version: (use `kfctl version`):0.6.2
- Kubernetes platform: kind
- Kubernetes version: 
Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:51:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):Linux red20 3.10.0-1062.el7.x86_64

**Comment by QxiaoQ** [comment]
![Screen Shot 2019-09-11 at 2 55 07 PM](https://user-images.githubusercontent.com/31646170/64675168-16e04680-d4a5-11e9-8293-2fef8dd57184.png)

**Comment by QxiaoQ** [comment]
> I think you get that error when not specifying a full path. I do something like this for mine
> 
> `kfctl init ${KFAPP} --config=/tmp/kfctl_config -V`


Thanks @danieldn .
Yes, a full path works for me.
But as the cli help doc ,I can see a relative path in "for example":
_Flags:
      --config string            Static config file to use. Can be either a local path or a URL.
                                 For example:
                                 --config=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                                 --config=kfctl_platform_gcp.yaml_

So, I think this is an issue, we should support relative path too.

**Comment by QxiaoQ** [comment]
This issue has been fixed. So I close it.

**Comment by Julianxo** [comment]
> This issue has been fixed. So I close it.

Fixed in which version? I have this issue in 0.7.1
