### ISSUE TITLE
Test kfctl on master for bugs due to Istio upgrade

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#4117]

**Comment by jlewi** [comment]
@elviraux Can you provide more context please? Where/when was ISTIO upgraded? Did something break?

**Comment by krishnadurai** [comment]
I think what @elviraux is referring to here is kubeflow/manifests#323. Even though its tested against the Web UI, Notebooks, Profiles and Pipelines manually there's still a case something could break.
@elviraux should we have a tracking issue for this or let individuals file separate ones when they encounter it?

**Comment by jlewi** [comment]
Can we have an automated test?

We have kubeflow/kubeflow#3496 tracking setting up an E2E test on an existing cluster. So ideally that would be the basis for an E2E test of kfctl_k8s_istio.yaml.

Ideally that E2E test should have sufficient coverage to give us high confidence about ISTIO.

**Comment by krishnadurai** [comment]
I think an automated test for Notebooks and Multi-user workflows will be the way to go here since these are the primary features being affected by Istio. I'll pair with @swiftdiaries to see what we can do here.

**Comment by jlewi** [comment]
Thanks @krishnadurai 

Some pointer that might be helpful

* I believe @yanniszark is working on #3496
* We have a test for provisioning a notebook here
  * https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/jupyter_test.py
* @jinchihe wrote an E2E test that runs our xgboost_synthetic notebook using papermill
  * https://github.com/kubeflow/examples/blob/master/test/workflows/components/xgboost_synthetic.jsonnet

**Comment by richardsliu** [comment]
@swiftdiaries Any updates on this?

**Comment by jlewi** [comment]
@krishnadurai can we close this as a duplicate of kubeflow/kubeflow#3496?
If not what is the unique work this issue is tracking?

**Comment by krishnadurai** [comment]
We could close this.
I'll make a separate issue for creating another E2E test for Istio 1.3.1.

/close
