### ISSUE TITLE
Profile should support resource allocation

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4119]
/kind feature

**Why you need this feature:**
User should be able to specify amount of resources available on each profile.
For example CPU, GPU specifying platform.

One option to apply them is offering resource templates during user creating profiles.

@kkasravi

**Comment by kunmingg** [comment]
Feature request is part of https://github.com/kubeflow/kubeflow/issues/3092

**Comment by jlewi** [comment]
@kunmingg is this implemented?

**Comment by kunmingg** [comment]
Yes, it's now an option in v1beta1
