### ISSUE TITLE
Executing child process 'start-notebook.sh' failed: 'Permission denied'

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#412]
I am trying to get Jupyterhub working. I get a 500 server error from the spawner. 

If I execute:
docker run  gcr.io/kubeflow/tensorflow-notebook-gpu 
[FATAL tini (7)] Executing child process 'start-notebook.sh' failed: 'Permission denied'

**Comment by pdmack** [comment]
The release process is evolving so that image appears to be bad atm.
However,
`docker run gcr.io/kubeflow-images-staging/tensorflow-notebook-gpu` launches a notebook fine for me.
`[I 12:50:30.240 NotebookApp] The Jupyter Notebook is running at: ...` 

Please give that one a try.

**Comment by ernestmartinez** [comment]
Thanks I'll give it a try.

**Comment by jlewi** [comment]
For CPU you can use:
gcr.io/kubeflow-images-staging/tensorflow-notebook-cpu

**Comment by jlewi** [comment]
Closing this issue because it looks like the problem was outdated images.

**Comment by ernestmartinez** [comment]
The images are still failing with:
Failed to load the native TensorFlow runtime
