### ISSUE TITLE
ambassador always CrashLoopBackOff

### ISSUE THREAD

**Issue by hansaimlim** [kubeflow/kubeflow#4124]
Hello,

I am referring to the issue #3198 (https://github.com/kubeflow/kubeflow/issues/3198)  since I got the same error after installing kubernetes and kuberflow on my server machine.
Three ambassador pods are stuck in CrashLoopBackOff status, vizier-core is also same.
Ambassador log says envoy exited with code 1.
My OS is Ubuntu 18.04 LTS. For installation, I followed the steps in https://github.com/NVIDIA/deepops, particularly the instructions on https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md.
The instruction is to use ansible to remotely install kubernetes and kubeflow to the server machine.

Following the comment by @Jeffwan, I feel like the problem is already known and solvable. But I'm very new to kubernetes & kubeflow; I don't know how to "manually disable" istio-sidecar-injector.

Please let me know what commands I need to run to manually disable istio-sidecar-injector and how to restart the malfunctioning pods.
If exact commands vary according to systems, please let me know what to look for (usual location of the files; how they look like, etc.). 

Thank you very much for helping me.

**Comment by Jeffwan** [comment]
@hansaimlim which version are you running? You suppose not to have this issue anymore in 0.6.2

**Comment by hansaimlim** [comment]
@Jeffwan Thank you for your reply. 
It seems the script that I used were set to kubeflow version 0.5.1. I would like to update the version and see if it solves the issue. What is the proper way to update kubeflow version? 

I'm slowly getting to understand the process of using ansible and yaml files for remote installation -- I'm a very very newbie for this. It will be very helpful if you specify whether it should be done on controller machine (where I run ansible) or worker node machine (where the jobs are actually being executed). 
I have access to both machines as root.

**Comment by Jeffwan** [comment]
@hansaimlim Can you check official documentation to install kubeflow on a kubernetes cluster? I think kubeflow doesn't have a official way to be installed using ansible. You can write your own ansible scripts to do that. At this moment, we would suggest to use `kfctl`. You can find the details in https://www.kubeflow.org/

**Comment by jbottum** [comment]
@hansaimlim hi, we would like to move this along.  A suggestion is to try with most current i.e. v0.6, and/or  consider for v1.0 which start in mid-Oct.   
@pdmack pete, would this be something that Ansible could help with?

**Comment by hansaimlim** [comment]
@jbottum Thanks for your suggestions. I definitely would like to follow your suggestions to fix the issue.
As suggested by @Jeffwan , I tried to use kubeflow v0.6.2.
On worker node:

`hansaimlim@dls1:/home/hansaimlim/$ kfctl version
kfctl v0.6.2-0-g47a0e4c7`

On master node:

`(kubeflowadmin_py27) hansaimlim@dgx-station:~/deepops$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                        READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-7557f5c484-mmxrh                    1/1     Running             0          24m
kube-system   calico-node-6lns7                                           1/1     Running             0          24m
kube-system   coredns-d7f78d7-2g4bp                                       1/1     Running             0          23m
kube-system   dns-autoscaler-5fc5fdbf6-nk5nn                              1/1     Running             0          23m
kube-system   kube-apiserver-dls1                                         1/1     Running             0          24m
kube-system   kube-controller-manager-dls1                                1/1     Running             0          24m
kube-system   kube-proxy-j4bdm                                            1/1     Running             0          24m
kube-system   kube-scheduler-dls1                                         1/1     Running             0          24m
kube-system   kubernetes-dashboard-6c7466966c-qchkv                       1/1     Running             0          23m
kube-system   nodelocaldns-tt4lh                                          1/1     Running             0          23m
kube-system   nvidia-device-plugin-daemonset-1.12-vldqh                   1/1     Running             0          22m
kube-system   tiller-deploy-677fbf76bb-hwgc9                              1/1     Running             0          23m
kubeflow      ambassador-865dddf7d7-4kk8w                                 0/1     CrashLoopBackOff    5          6m1s
kubeflow      ambassador-865dddf7d7-8ktms                                 0/1     CrashLoopBackOff    5          6m1s
kubeflow      ambassador-865dddf7d7-rnskn                                 0/1     CrashLoopBackOff    5          6m1s
kubeflow      argo-ui-cff444b96-gtqxf                                     1/1     Running             0          6m
kubeflow      centraldashboard-7b5ddd4b84-ngrwr                           0/1     ImagePullBackOff    0          5m59s
kubeflow      jupyter-0                                                   1/1     Running             0          3d6h
kubeflow      jupyter-web-app-74869dfff8-khlbq                            1/1     Running             0          6m1s
kubeflow      katib-ui-56bdcb847b-sgztm                                   1/1     Running             0          5m59s
kubeflow      kfam-d8b448646-rxtfg                                        1/1     Running             0          6m1s
kubeflow      kubeflow-controller-bdf684777-kjqsp                         1/1     Running             0          6m1s
kubeflow      metacontroller-0                                            1/1     Running             0          3d6h
kubeflow      minio-5c5b9cf6cc-lnq5w                                      0/1     ContainerCreating   0          6m1s
kubeflow      ml-pipeline-75788c79c4-rmdh9                                1/1     Running             0          6m1s
kubeflow      ml-pipeline-persistenceagent-5bb5bf65f9-jwlbm               1/1     Running             2          6m
kubeflow      ml-pipeline-scheduledworkflow-68459b7fb5-djklh              1/1     Running             0          6m
kubeflow      ml-pipeline-ui-5cbfd5f987-grpf5                             1/1     Running             0          6m
kubeflow      ml-pipeline-viewer-controller-deployment-7d8595fb47-jvpb9   0/1     CrashLoopBackOff    5          6m
kubeflow      mysql-c96db6c4d-l7hjt                                       0/1     ContainerCreating   0          6m
kubeflow      notebooks-controller-8679dc99bc-6fljh                       0/1     CrashLoopBackOff    5          6m1s
kubeflow      profiles-649d4d5ccf-qdttf                                   0/1     CrashLoopBackOff    5          6m1s
kubeflow      pytorch-operator-676bc8468-gvqrj                            1/1     Running             0          5m59s
kubeflow      spartakus-volunteer-568c5bddf8-5wfpt                        1/1     Running             0          5m59s
kubeflow      studyjob-controller-6b6fc85c6c-xqtg2                        0/1     CrashLoopBackOff    5          5m59s
kubeflow      tf-job-dashboard-89bc567d6-n9tr9                            1/1     Running             0          5m58s
kubeflow      tf-job-operator-654b5db9c-r5dnm                             1/1     Running             0          5m58s
kubeflow      vizier-core-85465f4f68-5ggcm                                0/1     CrashLoopBackOff    6          5m58s
kubeflow      vizier-core-rest-59d46c6d44-pzmnc                           1/1     Running             0          5m58s
kubeflow      vizier-db-869c4c9f9b-q5424                                  0/1     ContainerCreating   0          5m58s
kubeflow      vizier-suggestion-bayesianoptimization-6cc8f7856b-b76nx     1/1     Running             0          5m57s
kubeflow      vizier-suggestion-grid-775b6cf96d-r59wf                     1/1     Running             0          5m57s
kubeflow      vizier-suggestion-hyperband-5545df855b-2nhdh                1/1     Running             0          5m57s
kubeflow      vizier-suggestion-random-74649c67c4-p7bfk                   1/1     Running             0          5m57s
kubeflow      workflow-controller-5c66498b79-t4s2j                        0/1     CrashLoopBackOff    5          5m57s
monitoring    alertmanager-kube-prometheus-0                              0/2     ContainerCreating   0          3d6h
monitoring    prometheus-kube-prometheus-0                                3/3     Running             1          3d6h
rook-ceph     rook-ceph-tools-b8c679f95-7twrq                             1/1     Running             0          12m
`

`(kubeflowadmin_py27) hansaimlim@dgx-station:~/deepops$ kubectl describe pods ambassador-865dddf7d7-4kk8w -n kubeflow
Name:           ambassador-865dddf7d7-4kk8w
Namespace:      kubeflow
Priority:       0
Node:           dls1/REDACTED
Start Time:     Wed, 18 Sep 2019 23:07:20 -0400
Labels:         app.kubernetes.io/name=kubeflow
                pod-template-hash=865dddf7d7
                service=ambassador
Annotations:    <none>
Status:         Running
IP:             10.233.106.18
Controlled By:  ReplicaSet/ambassador-865dddf7d7
Containers:
  ambassador:
    Container ID:   docker://d03e9dc0042a97fc2e1614263a9c417013f8d149db4dd18be41a46b91d0069f7
    Image:          quay.io/datawire/ambassador:0.37.0
    Image ID:       docker-pullable://quay.io/datawire/ambassador@sha256:54b8cf9d1294b91e255f275efe9ddd33544edd29325e02e606c00cf4e5304154
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 18 Sep 2019 23:13:33 -0400
      Finished:     Wed, 18 Sep 2019 23:13:35 -0400
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  400Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   http-get http://:8877/ambassador/v0/check_alive delay=30s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8877/ambassador/v0/check_ready delay=30s timeout=1s period=30s #success=1 #failure=3
    Environment:
      AMBASSADOR_NAMESPACE:  kubeflow (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-zcf5v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ambassador-token-zcf5v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ambassador-token-zcf5v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m33s                  default-scheduler  Successfully assigned kubeflow/ambassador-865dddf7d7-4kk8w to dls1
  Normal   Pulled     5m34s (x5 over 7m30s)  kubelet, dls1      Container image "quay.io/datawire/ambassador:0.37.0" already present on machine
  Normal   Created    5m34s (x5 over 7m29s)  kubelet, dls1      Created container ambassador
  Normal   Started    5m34s (x5 over 7m28s)  kubelet, dls1      Started container ambassador
  Warning  BackOff    2m23s (x26 over 7m6s)  kubelet, dls1      Back-off restarting failed container`

`(kubeflowadmin_py27) hansaimlim@dgx-station:~/deepops$ kubectl describe pods ambassador-865dddf7d7-8ktms -n kubeflow
Name:           ambassador-865dddf7d7-8ktms
Namespace:      kubeflow
Priority:       0
Node:           dls1/REDACTED
Start Time:     Wed, 18 Sep 2019 23:07:20 -0400
Labels:         app.kubernetes.io/name=kubeflow
                pod-template-hash=865dddf7d7
                service=ambassador
Annotations:    <none>
Status:         Running
IP:             10.233.106.35
Controlled By:  ReplicaSet/ambassador-865dddf7d7
Containers:
  ambassador:
    Container ID:   docker://28b7212a209b064da3324c6e1043f368f7066de84d01935c80b64e9e37dd5bda
    Image:          quay.io/datawire/ambassador:0.37.0
    Image ID:       docker-pullable://quay.io/datawire/ambassador@sha256:54b8cf9d1294b91e255f275efe9ddd33544edd29325e02e606c00cf4e5304154
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 18 Sep 2019 23:13:37 -0400
      Finished:     Wed, 18 Sep 2019 23:13:38 -0400
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  400Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   http-get http://:8877/ambassador/v0/check_alive delay=30s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8877/ambassador/v0/check_ready delay=30s timeout=1s period=30s #success=1 #failure=3
    Environment:
      AMBASSADOR_NAMESPACE:  kubeflow (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-zcf5v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ambassador-token-zcf5v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ambassador-token-zcf5v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  9m14s                  default-scheduler  Successfully assigned kubeflow/ambassador-865dddf7d7-8ktms to dls1
  Normal   Pulled     7m18s (x5 over 9m10s)  kubelet, dls1      Container image "quay.io/datawire/ambassador:0.37.0" already present on machine
  Normal   Created    7m18s (x5 over 9m8s)   kubelet, dls1      Created container ambassador
  Normal   Started    7m18s (x5 over 9m7s)   kubelet, dls1      Started container ambassador
  Warning  BackOff    4m2s (x24 over 8m47s)  kubelet, dls1      Back-off restarting failed container`

`(kubeflowadmin_py27) hansaimlim@dgx-station:~/deepops$ kubectl describe pods ambassador-865dddf7d7-rnskn -n kubeflow
Name:           ambassador-865dddf7d7-rnskn
Namespace:      kubeflow
Priority:       0
Node:           dls1/READCTED
Start Time:     Wed, 18 Sep 2019 23:07:20 -0400
Labels:         app.kubernetes.io/name=kubeflow
                pod-template-hash=865dddf7d7
                service=ambassador
Annotations:    <none>
Status:         Running
IP:             10.233.106.45
Controlled By:  ReplicaSet/ambassador-865dddf7d7
Containers:
  ambassador:
    Container ID:   docker://da60711d14ce8e013831e003309f8bae089c7136929eeffdbe5a9ed2dfb81d40
    Image:          quay.io/datawire/ambassador:0.37.0
    Image ID:       docker-pullable://quay.io/datawire/ambassador@sha256:54b8cf9d1294b91e255f275efe9ddd33544edd29325e02e606c00cf4e5304154
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 18 Sep 2019 23:13:35 -0400
      Finished:     Wed, 18 Sep 2019 23:13:36 -0400
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  400Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   http-get http://:8877/ambassador/v0/check_alive delay=30s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8877/ambassador/v0/check_ready delay=30s timeout=1s period=30s #success=1 #failure=3
    Environment:
      AMBASSADOR_NAMESPACE:  kubeflow (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-zcf5v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ambassador-token-zcf5v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ambassador-token-zcf5v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  10m                     default-scheduler  Successfully assigned kubeflow/ambassador-865dddf7d7-rnskn to dls1
  Normal   Pulled     8m3s (x5 over 9m57s)    kubelet, dls1      Container image "quay.io/datawire/ambassador:0.37.0" already present on machine
  Normal   Created    8m3s (x5 over 9m55s)    kubelet, dls1      Created container ambassador
  Normal   Started    8m3s (x5 over 9m54s)    kubelet, dls1      Started container ambassador
  Warning  BackOff    4m48s (x25 over 9m36s)  kubelet, dls1      Back-off restarting failed container`

I'm not sure what these descriptions mean. I am not even sure if it is usual to see three ambassador pods when I'm using only one master node and one worker node (total two separate machines).

Please let me know for any suggestions to fix this issue. I am new to this field, so I may be missing something easy for experts. Please let me know if you see any, even basic, mistakes I might have made.

Thank you again for helping me!

**Comment by jlewi** [comment]
@hansaimlim if you have Ambassador running that means you are using Kubeflow 0.5 or earlier not 0.6. Please follow the instructions on https://www.kubeflow.org/docs/started/
For installing 0.6.

Downloading the 0.6 version of kfctl is not sufficient; you need to actually use the 0.6 kfctl CLI to actually deploy Kubeflow.

My suggestion would be to tear down your existing cluster and start from scratch following the 0.6 instructions.

**Comment by hansaimlim** [comment]
@jlewi Thanks for your comment. I had no progress since written above. I will try it from scratch.
