### ISSUE TITLE
Kubeflow Central Navigation UI browser does not open at 8080 or 31380

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/kubeflow#4135]
/kind bug
After running the steps in 
https://ubuntu.com/kubeflow/install

kubectl cluster-info
Kubernetes master is running at https://10.0.2.15:6443
KubeDNS is running at https://10.0.2.15:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am not able to access the UI at port 31380

**What did you expect to happen:**

access the UI at port 31380
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- kfctl version: (use `kfctl version`):  v0.6.2-0-g47a0e4c7

**Comment by cyrilthank** [comment]
![image](https://user-images.githubusercontent.com/4562436/65017265-f2241d00-d943-11e9-91ae-85f34df1e9dc.png)

**Comment by cyrilthank** [comment]
kubectl -n kubeflow describe pod centraldashboard-7b69b696cb-44x6k

returns

cyril@master-node:~$ kubectl -n kubeflow describe pod centraldashboard-7b69b696cb-44x6k
Name:           centraldashboard-7b69b696cb-44x6k
Namespace:      kubeflow
Priority:       0
Node:           <none>
Labels:         app=centraldashboard
                kustomize.component=centraldashboard
                pod-template-hash=7b69b696cb
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/centraldashboard-7b69b696cb
Containers:
  centraldashboard:
    Image:        gcr.io/kubeflow-images-public/centraldashboard:v0.6.0-rc2
    Port:         8082/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from centraldashboard-token-ms9z9 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  centraldashboard-token-ms9z9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  centraldashboard-token-ms9z9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  48s (x129 over 3h10m)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.

**Comment by cyrilthank** [comment]
kubectl -n kubeflow logs -p centraldashboard-7b69b696cb-44x6k
does not return any output

**Comment by cyrilthank** [comment]
Please advise if there is any logs gathering for kubernetes which i can use to get the logs uploaded

**Comment by anupash147** [comment]
Firstly is your dashboard pod running, description above shows as pending. Secondly are you on ubuntu machine and installed kubeflow in the same machine itself, so that you can localhost into kubeflow UI ?

**Comment by lovishch20** [comment]
> stalled kubeflow in the same machine itsel

Yes , I also got this issue. My all pods and services are running under kubeflow namespace but we are still stuck at dashboard UI part.
My machine is Ubuntu 18.04 and Kubeflow and minikube is up and running but not KF UI.
Thanks

**Comment by jlewi** [comment]
@cyrilthank if your still having trouble per @anupash147 suggestion could you please look into why the pods are stuck in the pending state. i.e. do a `kubectl describe pods ${POD}`

I would al suggest trying the latest 0.7.0 release.
