### ISSUE TITLE
Problem with  Kubeflow End to End - GitHub Issue Summarization Codelab

### ISSUE THREAD

**Issue by serhio7** [kubeflow/kubeflow#4138]
**What steps did you take and what happened:**
Trying to follow this [tutorial](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html?index=..%2F..index#2)
When I'm running this command `kfctl apply platform -V`, I've got following error:

![image](https://user-images.githubusercontent.com/4029753/65059234-4c41d400-d97e-11e9-98bf-413fb71d2227.png)
**Environment:**

- kfctl version:0.5.1.:
- Kubernetes platform: gcp
- OS linux

**Comment by serhio7** [comment]
Solved.The problem was with cluster-kubeflow.yaml setting     cluster-version:  to "latest" and download key in json format from deploy kubeflow-codelab service account for  GOOGLE_APPLICATION_CREDENTIALS helped

**Comment by jlewi** [comment]
Thanks @serhio7 glad you figured it out.

It looks like the codelab is still using v0.5 and the DM configs for 0.5 are outdated.
Related kubeflow/examples/issues/617 update GIS example to get rid of ksonnet.
