### ISSUE TITLE
kfctl with kfctl_gcp_iap.yaml failed

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4140]
/kind bug

**What steps did you take and what happened:**
kfctl init --config=kfctl_gcp_iap.yaml 
kfctl generate all
kfctl apply all

I see error:
```
WARN[0000] reconcile process has error:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 500 with message: gcp apply could not update deployment manager Error could not update storage-kubeflow.yaml; Insert deployment error: googleapi: Error 400: Invalid resource field value in the request., badRequest; retrying...  filename="coordinator/coordinator.go:237"
```

But the apply continue, and it's creating k8s resources in the cluster my kubeconfig was pointing to before.

I think there are two problems:
1. in app.yaml, there is no project field, and hostname is `kf0917.endpoints..cloud.goog`. So it can't infer my gcp project
2. The reconcile failure should be fatal and stop the process.

**Environment:**

built kfctl from master

cc @gabrielwen @jlewi

**Comment by lluunn** [comment]
related:
After I fixed the project field, I got resource error when kfctl apply:

```
ERRO[0030] Creating kf0917 error: &{Code:RESOURCE_ERROR
...
```

But kfctl also continues to apply k8s part..

**Comment by jlewi** [comment]
@gabrielwen is this related to how you implemented reconcile semantics in #4106

I think you are using "errors" to indicate that the apply isn't finished and so it just keeps retrying.

I think swallowing the error and just continuing could lead to confusing behavior. We probably want to migrate to using conditions to indicate whether the Apply is done or needs to be reinvoked.

**Comment by gabrielwen** [comment]
yea I think this will be fixed after condition based retrying.

**Comment by jlewi** [comment]
Closing this because IAP is working with 0.7.0
