### ISSUE TITLE
Add other libraries to tensorflow-notebook-image?

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4144]
/kind question

**Question:**

AWS users like to use awscli, or docker client in notebook. I am wondering if I can add some libraries to this Dockerfile? If not, seems we have to build our own and use custom images.

https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile

**Comment by jlewi** [comment]
@Jeffwan I think adding the AWS CLI and the docker client to the stock jupyter images is reasonable to me.

**Comment by Jeffwan** [comment]
AWSCli was added here. https://github.com/kubeflow/kubeflow/commit/ef4137233d82ad70d403391884124f03dc39d69a#diff-767e7f31b790ce0c9594a45ad4b5a398

I think I need to file another PR for docker client. I think we still need to use `docker login` for authentication.
