### ISSUE TITLE
Problem with Kubeflow End to End - GitHub Issue Summarization

### ISSUE THREAD

**Issue by serhio7** [kubeflow/kubeflow#4147]
/kind bug
Following [tutorial ](https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html?index=..%2F..index#4)
What directory kubectl looking for train.py, because I have file:///home/../examples/github_issue_summarization/notebooks/train.py
**What steps did you take and what happened:**

```
~/kubeflow-codelab/ks_app $ kubectl logs -f tfjob-issue-summarization-master-0
python: can't open file 'train.py': [Errno 2] No such file or directory
```

**What did you expect to happen:**

**Environment:**

```
$ kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
$ ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

**Comment by maxisawesome** [comment]
Did you download kfctl earlier? I had an old version of kfctl installed and got the same output form `kfctl version` (`v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e`).  My fix was running `which kfctl`, rm'ing it (for me, the output was `/usr/local/bin/kfctl`), then reinstalling kfctl and moving the file to  `/usr/local/bin/`
