### ISSUE TITLE
kubeflow upgrade: support or deprecate legacy CRs based on k8s version & components.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4150]
/kind feature
For example kubeflow v0.7 and v0.6 will have different CR versions for notebook and profile.
Our controllers reply on CR conversion webhook to support multiple CR versions.
The CR conversion webhook is alpha (off) for k8s 1.13 and 1.14, and is beta since k8s 1.15 (on).

We can suspend and warn users during upgrade if existing CRs will not be supported after upgrade.

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by kunmingg** [comment]
@jlewi 
@richardsliu

**Comment by yanniszark** [comment]
@kunmingg any status updates on this?

**Comment by jlewi** [comment]
I'm closing this as infeasible.

See: kubeflow/kfctl#304

I think we want to get out of the business of rolling our own complex upgrade logic. So I think every application should either be backwards compatible or provide a suitable warning (in the release notes) telling users not to upgrade if existing CRs will break.
