### ISSUE TITLE
Virtualservice created by notebook controller defaults to kubeflow/kubeflow-gateway

### ISSUE THREAD

**Issue by anupash147** [kubeflow/kubeflow#4152]
/kind bug

I have installed kubeflow over an existing k8 cluster with OIDC protocol enabled security. As a part of security the istio-ingress gateway is setup in istio-system and not in kubeflow. So i had to change manifest/<app>/overlays/istio.yaml to point to my hostname and istio-system/kubeflow (the gateway). But i observed when i create jupyter notebook server in kfam controlled namespace, the virtual service routes are created properly but the hosts and the gateway are incorrectly created. This causes the notebook to show that my notebook url is not found

```
NAME                   GATEWAYS                          HOSTS                                AGE
notebook-anup-t2       [kubeflow/kubeflow-gateway]       [*]                                  17h
```
Note i cannot edit this gateway because it get back to original, seems like its controlled. 

As a work around i created another dummy gateway and inject it with correct gateway and host and then the notebook starts working. Time being its a hack but i need a long term solution

```
NAME                   GATEWAYS                          HOSTS                                AGE
notebook-anup-t2       [kubeflow/kubeflow-gateway]       [*]                                  17h
=hack=>   notebook-anup-t2-tst   [istio-system/kubeflow-gateway]   [kf.my.domain]   18h
```

Environment 
- kfctl version: (use `kfctl version`): 0.6.2
- Kubernetes platform: (e.g. `minikube`): Kops / aws ec2's
- Kubernetes version: (use `kubectl version`): 
`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
`
- OS (e.g. from `/etc/os-release`): linux

**Comment by crauterb** [comment]
@anupash147 think is this a duplicate of #3945 or am I mistaken?

**Comment by jbottum** [comment]
@crauterb @jeremievallee if this the same as 3945, should we close one of these issues?
