### ISSUE TITLE
No Namespaces in Central Dashboard

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/kubeflow#4153]
/kind bug

**What steps did you take and what happened:**
after completing the installation and setup steps in
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

i dont see the namespaces in the centralboard UI

**What did you expect to happen:**
to be not only see the namespaces but select namespace
to proceed with the steps in https://www.kubeflow.org/docs/notebooks/setup/

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Please help as this is a show stopper for us
as the workaround in https://github.com/kubeflow/kubeflow/issues/3870
is not working and erroring with

couldn't generate KfApp: (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error: (kubeflow.error): Code 500 with message: couldn't copy application knative-crds

And already we are unable to get kubeflow working with kubernetes
due to
https://github.com/kubeflow/kubeflow/issues/4145

Hence request your help

**Environment:**

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):

kfctl version: (use kfctl version):
kfctl v0.6.2-0-g47a0e4c7

Kubernetes platform: (e.g. minikube)
microk8s

Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jlewi** [comment]
We just released Kubeflow 0.7.0 which fixes a number of issues with central dashboard.
Please try the latest release and if you are still having problems please open a new issue.
