### ISSUE TITLE
Include Ambassador Auth OIDC repository in Kubeflow organisation

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4160]
/kind feature
/area auth

**Why you need this feature:**
This will let Kubeflow contributors maintain Ambassador Auth OIDC's fork for implementing Istio Auth filters.

https://github.com/arrikto/ambassador-auth-oidc

/assign @jlewi 
/cc @yanniszark

**Comment by jlewi** [comment]
If we want to move the repo over; we could just transfer it over. This way the issues and everything else are preserved.

/cc @yanniszark

**Comment by yanniszark** [comment]
@jlewi I'll try to resolve it this week.

**Comment by krishnadurai** [comment]
@yanniszark
We are looking forward for Ambassador OIDC to be in within the 0.7 release.
I hope this will be accommodated.

**Comment by yanniszark** [comment]
@krishnadurai of course, this will be addressed promptly :smile:

**Comment by krishnadurai** [comment]
@yanniszark thanks
