### ISSUE TITLE
Adds test cases to v1beta1 KfDef and KfConfig

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#4162]
Currently we didn't port all test cases from v1alpha1 to v1beta1.  Part of the reasons is because we haven't implement functions that v1alpha1 has:
- [ ] [SyncCache](https://github.com/kubeflow/kubeflow/blob/2f15d8dbe85f0081652c1e5363f6a8c547a3e5fc/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L422)
- [x] [GetSecret](https://github.com/kubeflow/kubeflow/blob/2f15d8dbe85f0081652c1e5363f6a8c547a3e5fc/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L509)
- [x] [SetSecret](https://github.com/kubeflow/kubeflow/blob/2f15d8dbe85f0081652c1e5363f6a8c547a3e5fc/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L530)
... (To be added)

We need to see which functions we need to add them to v1beta1.  We also need to copy relevant test cases over to v1beta1.

**Comment by amalts** [comment]
is this issue still relevant? I would like to take this up.

**Comment by gabrielwen** [comment]
@amalts this is still open, and thanks for taking this up!

currently we only have a subset of tests:
https://github.com/kubeflow/kfctl/blob/master/pkg/apis/apps/kfdef/v1beta1/application_types_test.go

and the reason is that we moved part of the functions in v1alpha1 to an internal data structure:
https://github.com/kubeflow/kfctl/blob/master/pkg/kfconfig/types.go

could you add some test cases to `KfConfig`?  thanks!

**Comment by amalts** [comment]
Sure.

**Comment by gabrielwen** [comment]
I think we can close this until we need more tests :)
