### ISSUE TITLE
Jupyter web app should use v1beta1 notebook

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4163]
Now notebook CR has v1beta1 #3940 . The spec is the same so far.
The webapp should launch the notebook in v1beta1 instead of v1alpha1.

**Comment by jlewi** [comment]
@lluunn I think the jupyter has multi-version support so will the jupyter web app work even if it is using v1alpha1? Do we need a version of Kubernetes later than 1.12 for that to work?

**Comment by Jeffwan** [comment]
jupyter web app will look for v1beta1 and it won't work if CRD is still v1alpha1. I had this issue recently when I upgrade a older cluster. I forget to remove CRDs and notice this issue.
