### ISSUE TITLE
Implement notebook CR conversion webhook

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4164]
In the PR https://github.com/kubeflow/kubeflow/pull/4105, we use trivial conversion since there is no spec change in alpha and beta so far.
But we should figure out how to setup the webhook eventually if we want to change the spec.

**Comment by lluunn** [comment]
cc @kunmingg 
I think you need similar thing for profile

**Comment by kunmingg** [comment]
Yeah, and this webhook works with k8s 1.15+,
we might need to wait for GKE 1.15 then can start multi version CRD support.

**Comment by jlewi** [comment]
@lluunn should we attempt to do this for 1.0? Can we afford to downgrade to P2 and wait until we have to API changes before we implement this?

If this requires 1.15+ then it wouldn't even work yet with the KF versions we are testing on.

**Comment by lluunn** [comment]
We can wait until we need to change API
