### ISSUE TITLE
Azure auth: cannot call non-function spt.Token (type adal.Token)

### ISSUE THREAD

**Issue by Lijo050** [kubeflow/kubeflow#4172]
/kind bug

I was trying to install kubeflow on Azure by following: [https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/](https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/)
And then at `kfctl apply all -V` faced the issue:
`FATA[0000] Can not get kubernetes kfdef: No Auth Provider found for name "azure"  filename="apps/group.go:264"`

Then by following [https://github.com/kubeflow/kubeflow/issues/3759](https://github.com/kubeflow/kubeflow/issues/3759) I Imported the azure auth plugins and while `make build-kfctl` faced this issue:

`../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../.go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)`

Here the last line `cannot call non-function spt.Token (type adal.Token)` is something new.

**Environment:**
- Kubeflow version: latest from the kubeflow master branch
- Kubernetes platform: Azure
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10",  GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jbottum** [comment]
@aronchick hey david, is there someone that might look at this?

**Comment by yeya24** [comment]
@Lijo050  Can this be solved using my patch https://github.com/kubeflow/kubeflow/pull/3881? Or they are different things?

**Comment by Lijo050** [comment]
@yeya24 Yes I could solve it with your patch, Many thanks
