### ISSUE TITLE
Any way to access all configs yaml file generated using Deploy using UI method

### ISSUE THREAD

**Issue by Akashdesarda** [kubeflow/kubeflow#4175]
/kind feature

**Why you need this feature:**
We get all configs YAML file when we use the CLI method. So is there any method to have access to them using Deploy using UI method.

**Comment by jbottum** [comment]
@Akashdesarda can you please provide some examples of users segments (and their size) that will use this feature request i.e. are there a lot of folks needing this?

**Comment by Akashdesarda** [comment]
> @Akashdesarda can you please provide some examples of users segments (and their size) that will use this feature request i.e. are there a lot of folks needing this?

Think of a scenario,
 I want to limit my GKE cluster to create a specific type of machine. I can achieve this very easily by making changes like initialNodePool in gcp_config.yaml (which is generated using the CLI method)
But using the UI method I don't have any direct control over GKE and what machine it is going to spin up. I think a lot of people would be using this to have a better control over GKE.
