### ISSUE TITLE
ImagePullBackOff for deployment made using UI

### ISSUE THREAD

**Issue by Akashdesarda** [kubeflow/kubeflow#4183]
/kind bug

**What steps did you take and what happened:**
I deployed using UI and have all necessary permission (wrt to GKE & GCR) still, the pipeline cannot pull image from GCR. 
[A clear and concise description of what the bug is.]
As per the documentaton on kubernetes deployment made on GKE have permission to access GCR. But still, kubefloe pipeline cannot pull the image. 
This bug is so weired that till afternoon I was able to pull every image but suddenly evening I started facing this issue. I even created a new cluster but even that new cluster have same problem. 

**What did you expect to happen:**
There should be no ImagePullBackOff error and Kubeflow pipeline should have access to GCR. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: NA
- Kubernetes platform: GKE
- Kubernetes version:1.12.10-gke.5
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
@Akashdesarda could you provide the docker image of the image having problems?

Could you also provide the information

```
kubectl get pods -o yaml ${POD}
kubectl describe pods ${POD}
```

**Comment by Akashdesarda** [comment]
This problem was solved by providing proper docker-secret.

**Comment by sid027** [comment]
@Akashdesarda can you give a bit more detail about where and how you put the docker-secret?
I am having similar issues but only when using GPU nodes on Kubeflow. see #4572

**Comment by Akashdesarda** [comment]
> @Akashdesarda can you give a bit more detail about where and how you put the docker-secret?
> I am having similar issues but only when using GPU nodes on Kubeflow. see #4572

kubectl --namespace=kubeflow create secret docker-registry $SECRETNAME \  
--docker-server=https://gcr.io \                        
--docker-username=_json_key \
--docker-email=user@example.com \
--docker-password="$(cat ./service_account.json.json)"
**username should be _json_key**

**Comment by sid027** [comment]
#2561

**Comment by sid027** [comment]
kubeflow/pipelines#2561
