### ISSUE TITLE
e2e: refactor existing_arrikto test to use pyfunc

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4189]
/kind feature

**Why you need this feature:**
All E2E tests are refactored to use pyfunc and move away from the deprecated ksonnet tools.

**Describe the solution you'd like:**
The existing_arrikto E2E tests should:
* Use a pyfunc in prow.yaml to define their workflows.
* Split create, delete cluster into separate workflow steps. 

Followup from: #4154

**Comment by jlewi** [comment]
I believe the current plan is to combine kfctl_existing_arrikto with kfctl_istio_dex.yaml

This means we should have a single E2E test which is being tracked in kubeflow/kubeflow#3496
