### ISSUE TITLE
GCP credentials for notebook - new UI breaks user experience

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#4190]
New UI experience for notebook creation requires the users to manually select 

Configurations-> add gcp credential when running on GCP. This configuration is very hidden and it is a change in user experience from the past were credentials were injected by default. 

It is extremely difficult for users to realize / identify the root cause. Recommendation is to either select this by default when deploying on GCP or show a warning on UI creation page to highlight this to the user. 
 
https://screenshot.googleplex.com/ErZmLj7pbrY.png

**Comment by jlewi** [comment]
The issue here is that the jupyter web app doesn't currently have a way to preset certain pod defaults on all notebooks. Users have to manually select the POD defaults.

In 0.7 we will enable GCP workload identity so GCP cerdentials will be based on Kubernetes Service Accounts.

/cc @kimwnasptd

**Comment by axelmagn** [comment]
I have a related issue: when I click on the Configuration submenu to expand it, nothing happens.  No configuration options are displayed.

**Comment by jlewi** [comment]
This is fixed in 0.7. With 0.7 we use workload identity and notebooks are automatically using Kubernetes Service Accounts that are mapped to Google Service Accounts so users no longer need to attach credentials
