### ISSUE TITLE
kubeflow/kfctl breakage

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#4196]
/kind bug

**What steps did you take and what happened:**
can't build kubeflow/kfctl after syncing with kubeflow/kubeflow/bootstrap

problems:
- bootstrap/pkg/apis/apps/kfdef/v1beta1/*.go imports github/kubeflow/kfctl (circular dependency)
- go.mod imports profile-controller by downloading an older version of kfctl
- pkg/apis/apps/kfdef/testdata is missing a doc.go

kfctl needs to be in lock-step with profile-controller, profile-controller needs to move to v2 so no incidental dependency on kfctl is introduced. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
Why does kfctl need to be in lock step with profile controller?

**Comment by jlewi** [comment]
@kkasravi any update on this? How does this impact our plan to move kfctl to kubeflow/kfctl?

**Comment by kkasravi** [comment]
@jlewi this is fixed.

**Comment by kkasravi** [comment]
no impact - see https://github.com/kubeflow/kfctl/pull/51
