### ISSUE TITLE
Split up core ksonnet package into separate packages

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#42]
The core package consists of 

- JupyterHub
- TfJob CRD
- NFS Provisioner

These should probably each be their own package. The core component could then depend on these packages.

The reason we didn't do this in the initial PR #36 was because ksonnet doesn't yet support having packages depend on other packages see ksonnet/ksonnet#231

**Comment by jlewi** [comment]
Adding this to 0.4.0 .

In 0.4.0 we should try to rationalize our package structure and otherwise overhaul the organization of our ksonnet registry (e.g. #1454)

**Comment by jlewi** [comment]
I filed the more specific issues #1885 and #1886
I think we can start with that and go from there.

**Comment by jlewi** [comment]
Here's a list of the components still in the core package

ambassador
centraldashboard
cert-manager
cloud-endpoints
google-cloud-server
iap
prometheus
spartakus

So we basically have 2 types of components left

1. Common components
1. GCP specific components.

The GCP specific components should probably be moved into their own package.

For common components we have a couple options

1. Rename "core" to "common" or maybe "misc"
    
    * The main reason for doing this is because "core" is a bit overloaded. It conveys a false sense that the components are more important than the others but that's not really true
  
1. We could try to come up with more specific packages to organize things in e.g networking or monitoring.


@pdmack @kkasravi @ashahba WDYT?

**Comment by jlewi** [comment]
I think the only remaining item is to rename core. I vote renaming it to common.

**Comment by pdmack** [comment]
"common" to me implies general utility for other components, like logging. "core" is not bad IMHO if it's basically the content of an MVP.

My $0.02.

**Comment by kkasravi** [comment]
I'll do the core -> common PR. @jlewi @pdmack if you agree on a better name let me know

**Comment by kkasravi** [comment]
one argument for common is kubeflow/core/util.libsonnet which is used by other components.
