### ISSUE TITLE
ERROR net/http: request canceled (Client.Timeout exceeded while reading body)

### ISSUE THREAD

**Issue by jmsking** [kubeflow/kubeflow#4200]
**Question**
*I hava deploy a k8s cluster and install a ksonnet, there occurs a error when i init an kubeflow-app using ksonnet, the detail as follows:*

>> **ks init my-kube**
>> INFO Using context "kubernetes-admin@kubernetes" from kubeconfig file "/root/.kube/config"
>> INFO Creating environment "dev" with namespace "default", pointing to "version:v1.14.2" cluster at address "https://172.31.155.10:6443"
>> ERROR net/http: request canceled (Client.Timeout exceeded while reading body)
>> To undo this simply delete directory 'my-kubeflow' and re-run `ks init`.
>> If the error persists, try using flag '--context' to set a different context or run `ks init --help` for more options

**Environment:**
- *-----K8s-----*
>>**kubectl version**
>>Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- *-----OS-----*
>> **cat /etc/os-release**
>>NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

- *------api-server-----*
>> **kubectl get po -n kube-system**
>> kube-apiserver is running

- *-------kubelet-------*
>> **systemctl status kubelet**
>> kubelet is active(running)

**Any help i will appreciate!**

**Comment by krishnadurai** [comment]
@jmsking Which version of Kubeflow are you trying to deploy?

Currently with the latest release of Kubeflow 0.6.2 we do not support ksonnet deployments and have moved to using kustomize.

Here are some docs to help you get started:

https://www.kubeflow.org/docs/started/k8s/

**Comment by jmsking** [comment]
thanks for you rapidly reply, i will try to install kubeflow according to the kubeflow document you supplied.
