### ISSUE TITLE
kfctl generate fails with `--platform` for GCP, remove `--platform`

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4208]
/kind bug

**What steps did you take and what happened:**

I generated a new gcp platform project and tried to run generate all. It failed with a missing cluster.jinja file.

> holden@hkdesktop:~$ kfctl init --platform gcp --project boos-demo-projects-are-rad --skip-init-gcp-project preview07gcp 
> holden@hkdesktop:~$ cd preview07gcp/
> holden@hkdesktop:~/preview07gcp$ kfctl generate all -V
> INFO[0000] Downloading /home/holden/preview07gcp/app.yaml to /tmp/908216557/app.yaml  filename="v1alpha1/application_types.go:349"
> WARN[0000] Defaulting Spec.IpName to preview07gcp-ip. This is deprecated; IpName should be explicitly set in app.yaml  filename="coordinator/coordinator.go:606"
> WARN[0000] Defaulting Spec.Hostame to preview07gcp.endpoints.boos-demo-projects-are-rad.cloud.goog. This is deprecated; Hostname should be explicitly set in app.yaml  filename="coordinator/coordinator.go:617"
> WARN[0000] Defaulting Spec.Zone to us-east1-d. This is deprecated; Zone should be explicitly set in app.yaml  filename="coordinator/coordinator.go:627"
> INFO[0000] Writing stripped KfDef to /home/holden/preview07gcp/app.yaml  filename="v1alpha1/application_types.go:660"
> INFO[0000] Downloading /home/holden/preview07gcp/app.yaml to /tmp/208198504/app.yaml  filename="v1alpha1/application_types.go:349"
> INFO[0000] 
> ****************************************************************
> Notice anonymous usage reporting enabled using spartakus
> To disable it
> If you have already deployed it run the following commands:
>   cd $(pwd)
>   kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
> 
> For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
> ****************************************************************
>   filename="coordinator/coordinator.go:183"
> INFO[0000] /home/holden/preview07gcp/.cache/kubeflow exists; not resyncing   filename="v1alpha1/application_types.go:455"
> INFO[0000] /home/holden/preview07gcp/.cache/manifests exists; not resyncing   filename="v1alpha1/application_types.go:455"
> INFO[0000] CreatePipelinePersistentStorage not set defaulting to true  filename="gcp/gcp.go:1854"
> INFO[0000] EnableWorkloadIdentity not set defaulting to false  filename="gcp/gcp.go:1859"
> WARN[0000] Backfilling auth; this is deprecated; Auth should be explicitly set in Gcp plugin  filename="gcp/gcp.go:1867"
> INFO[0000] Adding plugin gcp                             filename="v1alpha1/application_types.go:605"
> Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.error): Code 400 with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33/deployment/gke/deployment_manager_configs/cluster.jinja to /home/holden/preview07gcp/gcp_config/cluster.jinja using repo local path /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33 Error cannot open input for copying: open /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33/deployment/gke/deployment_manager_configs/cluster.jinja: no such file or directory
> Usage:
>   kfctl generate [all(=default)|k8s|platform] [flags]
> 
> Flags:
>       --email string      email if '--platform gcp'
>   -h, --help              help for generate
>       --hostname string   hostname if '--platform gcp'
>       --ipName string     ipName if '--platform gcp'
>       --mount-local       mount-local if '--platform minikube'
>   -V, --verbose           verbose output default is false
>       --zone string       zone if '--platform gcp'
> 
> couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.error): Code 400 with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33/deployment/gke/deployment_manager_configs/cluster.jinja to /home/holden/preview07gcp/gcp_config/cluster.jinja using repo local path /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33 Error cannot open input for copying: open /home/holden/preview07gcp/.cache/kubeflow/kubeflow-kubeflow-63a5a33/deployment/gke/deployment_manager_configs/cluster.jinja: no such file or directory
> holden@hkdesktop:~/preview07gcp$ 
> 

**What did you expect to happen:**

Generate a project I can then apply

**Anything else you would like to add:**

There are some jinja files, just not where expected.

> holden@hkdesktop:~/preview07gcp$ find ./.cache/ |grep jinja
> ./.cache/manifests/manifests-master/gcp/deployment_manager_configs/storage.jinja.schema
> ./.cache/manifests/manifests-master/gcp/deployment_manager_configs/cluster.jinja.schema
> ./.cache/manifests/manifests-master/gcp/deployment_manager_configs/network.jinja
> ./.cache/manifests/manifests-master/gcp/deployment_manager_configs/storage.jinja
> ./.cache/manifests/manifests-master/gcp/deployment_manager_configs/cluster.jinja
> 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): N/A ( 5ecfa5b2e48a89c6e0d6835cc93a47c04262af28 )
- kfctl version: kfctl 5ecfa5b2
- Kubernetes platform: (e.g. `minikube`) GCP
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

> NAME="Ubuntu"
> VERSION="18.04.3 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.3 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> 
>

**Comment by holdenk** [comment]
From a conversation on slack with @jlewi it seems like we should delete `--platform` since it's no longer supported.

**Comment by jlewi** [comment]
The --platform flag should be removed in v0.7.0 and the docs and help should be updated.
