### ISSUE TITLE
Can not launch TensorFlow Serving because AVX not available on VM

### ISSUE THREAD

**Issue by ogre0403** [kubeflow/kubeflow#421]
Hi all, 

I followed user guide try to [serve-a-model-using-tensorflow-serving](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#serve-a-model-using-tensorflow-serving),  but tf-serving pod can't be created. 
I setup kubeflow in my own kubernetes cluster, not using GKE or minikube. 
How can I fix this error ? Because there is no logs in Pod, I cannot show provide other useful information. 
Thanks. 

```
root@vagrant:~# kubectl get pod
NAME                              READY     STATUS             RESTARTS   AGE
ambassador-6ccb864c46-268xt       2/2       Running            0          10m
ambassador-6ccb864c46-9hrsh       2/2       Running            0          10m
ambassador-6ccb864c46-m7gc7       2/2       Running            0          10m
inception-858476d4c4-cr49s        0/1       CrashLoopBackOff   6          10m
tf-hub-0                          1/1       Running            0          10m
tf-job-operator-78757955b-nk457   1/1       Running            0          10m
```

```
Name:           inception-858476d4c4-cr49s
Namespace:      default
Node:           192.168.2.21/192.168.2.21
Start Time:     Wed, 14 Mar 2018 18:33:26 +0000
Labels:         app=inception
                pod-template-hash=4140328070
Annotations:    <none>
Status:         Running
IP:             172.20.0.152
Controlled By:  ReplicaSet/inception-858476d4c4
Containers:
  inception:
    Container ID:  docker://f59a9db5a3cf6f2e33671ba30ff71d3e34e32e1835ab908c4250f3c7f93f8c75
    Image:         gcr.io/kubeflow-images-staging/tf-model-server:v20180227-master
    Image ID:      docker-pullable://gcr.io/kubeflow-images-staging/tf-model-server@sha256:07ded66bc3a8e5ca582c3dc1871c2636a4ebc06b082e3afd76a68c45f1953385
    Port:          9000/TCP
    Args:
      /usr/bin/tensorflow_model_server
      --port=9000
      --model_name=inception
      --model_base_path=gs://kubeflow-models/inception
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    132
      Started:      Wed, 14 Mar 2018 18:39:24 +0000
      Finished:     Wed, 14 Mar 2018 18:39:24 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     4
      memory:  4Gi
    Requests:
      cpu:        1
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pb8qz (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-pb8qz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pb8qz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age               From                   Message
  ----     ------                 ----              ----                   -------
  Normal   Scheduled              9m                default-scheduler      Successfully assigned inception-858476d4c4-cr49s to 192.168.2.21
  Normal   SuccessfulMountVolume  9m                kubelet, 192.168.2.21  MountVolume.SetUp succeeded for volume "default-token-pb8qz"
  Normal   Pulled                 7m (x5 over 9m)   kubelet, 192.168.2.21  Container image "gcr.io/kubeflow-images-staging/tf-model-server:v20180227-master" already present on machine
  Normal   Created                7m (x5 over 9m)   kubelet, 192.168.2.21  Created container
  Normal   Started                7m (x5 over 9m)   kubelet, 192.168.2.21  Started container
  Warning  BackOff                4m (x24 over 9m)  kubelet, 192.168.2.21  Back-off restarting failed container

```

**Comment by pdmack** [comment]
Really not sure without more details, at least master and node versions and config. The only thing that I can think of that _might_ be an issue is if your kube/docker env wasn't (for some reason) allowing privileged execution for that particular pod to add the `model-server` user to uid/gid 1000.

https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/images/Dockerfile.cpu#L52

**Comment by aronchick** [comment]
Recommendation from the K8s team: Can you set 'terminationMessagePolicy' to  'FallbackToLogsOnError'

Then the tail of the log will show up in the API.
https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/

/cc @jlewi @texasmichelle  should we have this be our default for now? Or is there a way to highlight this in the debugging process?

**Comment by pdmack** [comment]
@ogre0403 hmmm vagrant...
This a VM with a KVM provider? If so, perhaps it is effectively the same as kubernetes/minikube/issues/2377.

**Comment by jlewi** [comment]
My debugging suggestion is to modify the K8s deployment for the model and set the command to
["tail", "-f", "/dev/null"]

You can then "kubectl exec -it" into the pod. This ensures your pod is running with the same exact settings (i.e. userid/groupid) as when you try to deploy.

You can now run the command normally run to deploy the model and you can see what error you are getting.

**Comment by ogre0403** [comment]
Thanks for your useful  suggestion.
 
After I read tf-serving [Dockerfile](https://github.com/kubeflow/kubeflow/blob/79a4c3736efb4d3713bbc957eed05c4db3ee8ecd/components/k8s-model-server/images/Dockerfile.cpu#L48) I noted tf-serving install ` tensorflow-model-server`. 
I also read the [tf-serving install guide](https://www.tensorflow.org/serving/setup), there is one note: 
```
Note: In the above commands, replace tensorflow-model-server with tensorflow-model-server-universal if your processor does not support AVX instructions.
```
I found my vm does'nt  have avx instruction, so I replace tensorflow-model-server with tensorflow-model-server-universal in Dockerfile and re-build new images.  Then tf-serving Pod can be created. 
```
...
RUN apt-get update && apt-get install -y \
        tensorflow-model-server-universal  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
...
```

```sh
root@vagrant:~/my-kubeflow# kubectl get pod
NAME                         READY     STATUS    RESTARTS   AGE
inception-7f78798dd8-7rlnc   1/1       Running   0          3s
```

**Comment by ogre0403** [comment]
@jlewi I also try to build  `tensorflow-model-server` from source without any optimization flag, then the output binary is also work for me . I think  `tensorflow-model-server` binary in TFServing image require cpu support AVX. 

We can build another TFServing image use  non-AVX supported binary. 
Because there is one variable for serving image (`modelServerImage`) already, user can use this variable to change image.

**Comment by bhack** [comment]
Check the [Available binaries section](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md#available-binaries)

**Comment by jlewi** [comment]
Is non-AVX something we should support?

How common is it to not have AVX these days? It seems like AVX started shipping in 2013.
https://en.wikipedia.org/wiki/Advanced_Vector_Extensions

**Comment by aronchick** [comment]
I think the problem is that the hypervisor may not support AVX - I'd be
totally ok with just a nice error message (for now).

**Comment by jlewi** [comment]
I think we should follow up with K8s to see if there is a way to specify that AVX is required and that nodes provide it or don't provide it. 

That seems like the best way to handle this.

/cc @lluunn

**Comment by bhack** [comment]
@jlewi https://github.com/kubernetes-incubator/node-feature-discovery

**Comment by jlewi** [comment]
Thanks.

@balajismaniam provided me more info

- node-feature-discovery is a daemon set that runs on nodes and labels them
- We can use node-affinity/anti-affinity to do proper scheduling

**Comment by jlewi** [comment]
We should file issues related to previous comment and then close out this issue.
