### ISSUE TITLE
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Timeout: request did not complete within requested timeout 30s

### ISSUE THREAD

**Issue by jmsking** [kubeflow/kubeflow#4212]
/kind bug

**What steps did you take and what happened:**
>>when i start kubeflow according to the document as https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/
>>$kfctl apply all -V
**Then there occurs a errors as follows**
>>INFO[0001] creating attributemanifest/istioproxy         filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Timeout: request did not complete within requested timeout 30s

**Any suggestion is much appreciate**

**Comment by mikejmills** [comment]
I have a similar issue

`Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: no matches for kind "Deployment" in version "extensions/v1beta1"
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: no matches for kind "Deployment" in version "extensions/v1beta1"`

**Comment by MostafaGazar** [comment]
I believe this is related to k8s changes in v1.16 https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

If you are using [multipass](http://multipass.run) with [microk8s](http://microk8s.io) you can install v1.14. It should work fine, I just tried it. Follow the steps in https://tutorials.ubuntu.com/tutorial/get-started-kubeflow and install microk8s via `sudo snap install microk8s --classic --channel=1.14/stable`

**Comment by justrohan** [comment]
Can you share the output of --all-namespaces?

**Comment by jlewi** [comment]
Kubeflow doesn't work on 1.16 yet. 
See: kubeflow/manifests#375
