### ISSUE TITLE
Move config_spec and kfDef Name in kfctl_go_test.py into get_config_spec()

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#4226]
/kind improvement

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
To ensure that all config related changes are in one place.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Reference discussion in PR: #4040

**Comment by swiftdiaries** [comment]
Sorry about that @nrchakradhar !
Other PRs were blocked on that merge and I wanted to get it done fast.
Commented on your PR.

**Comment by nrchakradhar** [comment]
@swiftdiaries Based on #4187 I guess this can be closed. WDYT?
