### ISSUE TITLE
multiple Matplotlib libraries

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#423]
While trying basic plots in jupyter I get
AttributeError: module 'matplotlib.cbook' has no attribute 'popall

google search suggested multiple installed matplotlib libraries to be culprit.

jovyan@jupyter-admin:~$ conda list matplotlib
# packages in environment at /opt/conda:
#
matplotlib                2.1.2                     <pip>
matplotlib                2.0.2                    py36_2    conda-forge

jovyan@jupyter-admin:~$ pip list |grep matplotlib
matplotlib (2.1.2)

Trying to uninstall conda libs caused:

jovyan@jupyter-admin:~$ conda uninstall matplotlib
Fetching package metadata
Solving package specifications: .

The following packages will be REMOVED:

    matplotlib: 2.0.2-py36_2 conda-forge

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(339): An error occurred while uninstalling package 'conda-forge::matplotlib-2.0.2-py36_2'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

PermissionError(13, 'Permission denied')
Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /opt/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-116-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:100

**Comment by willingc** [comment]
Looks like you have a Python version mismatch with conda package. Delete the entire conda/Anaconda directory and reinstall.

**Comment by ernestmartinez** [comment]
The issue is having conda and pip installed libs for matplotlib, the fix being to pip uninstall matplotlib. Unfortunately I cannot sudo nor become root in order to delete anything as a Jupyterhub user.

**Comment by jlewi** [comment]
@willingc I believe we are using a combination of conda and non-conda packages; I'm guessing because not everything we want is in conda (e.g. TFX and beam). Is this the right thing to do? Is there a better way to handle this.

**Comment by jlewi** [comment]
If I'm understanding comment 1 it looks like conda is installing matplotlib 2.0.2 but there is a newer version 2.1.2 installed as well. 

It looks like matplotlib 2.2 is the latest release.

Can we fix this just by uninstalling the conda installed version in our docker images using the command @willingc provided above.

**Comment by willingc** [comment]
The best way would be to create an environment.yml file to use with conda where you can conda install and pip install from one file. [Example from repo2docker](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.frozen.yml) [Example from JupyterHub docs - this is the more straightforward example](https://github.com/jupyterhub/jupyterhub/blob/master/docs/environment.yml)

In general, I would use conda-forge for the channel.

The yaml file will list conda packages and then pip packages. Here's an example from the conda docs: https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually

**Comment by willingc** [comment]
@jlewi The conda cheatsheet is helpful too. https://conda.io/docs/user-guide/cheatsheet.html

**Comment by pdmack** [comment]
Is this still an issue? All I see in the current 1.8 notebook is:
```
matplotlib                2.2.2                     <pip>
```

**Comment by jlewi** [comment]
Marking this fixed based on @pdmack's comment.
