### ISSUE TITLE
Add label to all namespaces to support Katib in 0.7

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/kubeflow#4231]
/kind feature

In 0.7 release,  all namespaces where katib experiments have to be deployed should have the following label. 
`     katib-metricscollector-injection: enabled
`
This includes Kubeflow + all user namespaces that are created by profile. 

Related:  https://github.com/kubeflow/katib/issues/841

Sample:  https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/0-namespace.yaml#L6

**Comment by jlewi** [comment]
Is there a reason katib depends on the label on the namespace and not the label on the individual pods?

**Comment by johnugeorge** [comment]
@jlewi I think, it matters in large clusters where there are non kubeflow namespaces.  Since object selectors are introduced only in k8s 1.15(https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/apis/admissionregistration/types.go#L264) , there will be  performance impact and pod level web hooks can become a bottleneck for pre 1.15 clusters.  We can remove this label when k8s 1.15 becomes the default. 

/cc @gaocegege

**Comment by gaocegege** [comment]
Namespace selector of webhooks can avoid performance issues. Or the webhook will accept many requests from all namespaces.

Label on the individual pods has the right behavior, too. But the performance issue cannot be avoided. We still get many requests from all namespaces.
