### ISSUE TITLE
KF 0.5 deployment from UI is broken 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/kubeflow#4233]
When deploying KF 5.0 from UI I get the following error: 

Deployment status: {"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No valid versions with the prefix \"1.11\" found.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/chavoshi-dev-4/zones/us-central1-a/clusters","httpMethod":"POST"}}

**Comment by jlewi** [comment]
If you want to deploy 0.5 you can use the CLI and update the deployment manager configs to set a newer version of GKE.

**Comment by jbottum** [comment]
@SinaChavoshi With 0.7 on the way (next week), I think our efforts will be to fix items in 0.7 or 0.6.  Can you please justify the need for 0.5.   thanks.
