### ISSUE TITLE
Unable to mount volumes for pod "jupyter-...

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#424]
I'm running a MAAS bare metal deployment . I am running canonicals kubernetes distribution deployed using JUJU. I have a ceph cluster deployed for PV.
When trying to start a jupyter notebook, a PV volume must be explicitly defined and existing otherwise, I get this error:
Unable to mount volumes for pod "jupyter-ernie_kf-tutorial(d67e51db-27a9-11e8-b9ac-001c23c7771d)": timeout expired waiting for volumes to attach/mount for pod "kf-tutorial"/"jupyter-ernie". list of unattached/unmounted volumes=[volume-ernie]

Syslog on kubernetes-worker shows:
Mar 14 17:07:55 gpu kubelet.daemon[10247]: E0314 17:07:55.417229   10247 desired_state_of_world_populator.go:273] Error processing volume "volume-ernie" for pod "jupyter-ernie_kf-tutorial(d67e51db-27a9-11e8-b9ac-001c23c7771d)": error processing PVC "kf-tutorial"/"claim-ernie": PVC kf-tutorial/claim-ernie has non-bound phase ("Pending") or empty pvc.Spec.VolumeName ("")

**Comment by jlewi** [comment]
Is this the same issue as #336 i.e. no default storage class?

Proposed fix #365 
/cc @inc0

**Comment by inc0** [comment]
@ernestmartinez so check your storage class and see if it's healthy (it has to be default storage class. Check if you can manually create pv and connect it. When you create pvc (jupyter hub does that), it will also create PV. You shouldn't have to do anything.

**Comment by ernestmartinez** [comment]
I did not have a storage class so I create one as follows:
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: slow
provisioner: kubernetes.io/rbd
parameters:
    monitors: 192.168.2.14:6789,192.168.2.19:6789,192.168.2.230:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: kf-tutorial
    pool: rbd
    userId: admin
    userSecretName: ceph-secret

My ceph-secret is defined as follows:
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kf-tutorial
data:
  key: AQAP7qdanut/JBAAtKwrRzcr/5UkoClKuBndfe==
type:
  kubernetes.io/rbd


When I try to spawn a Jupyter session I get this error in syslog on the kubernetes-worker:
Mar 15 12:44:04 gpu kubelet.daemon[2434]: E0315 12:44:04.415460    2434 desired_state_of_world_populator.go:273] Error processing volume "volume-admin" for pod "jupyter-admin_kf-tutorial(6b380deb-284e-11e8-8c3f-001c23c7771d)": error processing PVC "kf-tutorial"/"claim-admin": PVC kf-tutorial/claim-admin has non-bound phase ("Pending") or empty pvc.Spec.VolumeName ("")

So I tried creating a PVC as defined below:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-vol01
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi

When I try to create it, I get the following error:
kubectl create -f pvc.yaml -n kf-tutorial
Error from server (BadRequest): error when creating "pvc.yaml": PersistentVolumeClaim in version "v1" cannot be handled as a PersistentVolumeClaim: v1.PersistentVolumeClaim: Spec: v1.PersistentVolumeClaimSpec: VolumeMode: Resources: v1.ResourceRequirements: Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', parsing 207 ...      Bot"... at {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"name":"ceph-vol01","namespace":"kf-tutorial"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi 45,1          Bot"}},"volumeMode":"Block"}}

**Comment by ernestmartinez** [comment]
I was able to fix my problem creating a PVC, the error was due to whitespace after the storage line. But it still did not create a PV.

**Comment by ernestmartinez** [comment]
kubectl describe pvc -n kf-tutorial
Name:          claim-admin
Namespace:     kf-tutorial
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=jupyterhub
               heritage=jupyterhub
               hub.jupyter.org/username=admin
Annotations:   <none>
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type    Reason         Age               From                         Message
  ----    ------         ----              ----                         -------
  Normal  FailedBinding  8s (x5 over 58s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

**Comment by inc0** [comment]
Well pvc declaration you've shown should definetly spawn PV in addition to PVC. There is something wrong with your storage class. I don't have ceph installation handy besides rook, so I can't really test it locally, but it should work in a way that PVC would create PV automatically.

**Comment by jlewi** [comment]
#365 is open to add an option to disable the use of PVC which would be a work around.

**Comment by ernestmartinez** [comment]
PVC creation of PV works now. But issue persists when trying to run multiple users simultaneously.

**Comment by inc0** [comment]
glad you got that to work. Maybe your storageclass was broken but if fixed itself after a while?

**Comment by stobias123** [comment]
ran into this same issue. no problems when I created the volume manually.
