### ISSUE TITLE
kfctl on minikube goes into a loop prompting for namespace creation

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4241]
/kind bug

**What steps did you take and what happened:**

Deployed kubeflow using `kfctl apply -f ../kfctl_k8s_istio.yaml`. Wait for services to settle by watching the pods. Ran `minikube service istio-ingressgateway  --namespace istio-system` to connect to the UI. Created namespace in the UI. Pressing finish button did not remove the overlay.

**What did you expect to happen:**

I expected to see the regular kubeflow UI once I pressed finish.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The kubeflow UI is loaded underneath (you can see it flash up when you hit refresh).

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl 2395c5fc
- Kubernetes platform: (e.g. `minikube`): minikube
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
@holdenk by overlay do you mean the UI?

**Comment by jlewi** [comment]
@avdaredevil this looks like an issue with the centraldashboard. Any suggestion about what debug information to collect to help diagnose this?

**Comment by avdaredevil** [comment]
Hi @holdenk,
When you run through the registration flow in the UI could you include the output you get from: (using chrome-dev tools)
- `/api/has-workgroup`
- `/api/env-info`
- `/api/workgroup/create`
_**Note:** Fetch this output after you press create / submit_

Also, are there any errors in the console?

**Comment by holdenk** [comment]
I can take a look @avdaredevil . When you say "include the output from using chrome dev tools" though can you clarify what you mean? Like what the response was in the request or something else?

**Comment by avdaredevil** [comment]
I mean, what was the response payload, should be JSON. Looks something like:
![image](https://user-images.githubusercontent.com/5303018/66523594-22735d00-eaa5-11e9-9fcf-2a41e47f805c.png)

**Comment by Christina-Young** [comment]
I am getting this same issue, using microK8s and kfctl v0.7.0 just downloaded and installed today.  I also created the namespaces manually using the instructions on this page:  [](https://www.kubeflow.org/docs/other-guides/multi-user-overview/) and verified with `kubectl get profiles -o yaml`, but Kubeflow ignores the manually created ones and still prompts for namespace creation.

**Comment by avdaredevil** [comment]
@Christina-Young could you please include your API information as I've outlined above. This will allow us to debug your issue better. Specifically your responses for `has-workgroup` and `env-info`

**Comment by jlewi** [comment]
@avdaredevil what was the PR with the fix that added polling to fix issues with namespace creation?

**Comment by avdaredevil** [comment]
#4364, #4384

**Comment by jlewi** [comment]
It looks like the PRs have been merged so I'm going to close this issue.
