### ISSUE TITLE
Second time apply of kfctl fails with 'current directory not empty, please switch directories'

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4242]
/kind bug

**What steps did you take and what happened:**
Change directory into an empty directory. Apply kfctl through:

```
kfctl apply -f /path/<config>.yaml
``` 

Re-apply with either command: 
```
kfctl apply -f /path/<config>.yaml
``` 
or 
```
kfctl apply
``` 

Shows an error on execution:
```
Error: error loading kfapp:  (kubeflow.error): Code 500 with message: could not load /path/to/install/dir/app.yaml. Error:  (kubeflow.error): Code 400 with message: current directory not empty, please switch directories
```
**What did you expect to happen:**
Second time `apply` should function when the directory is not empty.

**Anything else you would like to add:**
We would need to fix on the intended behaviour here since this should be applicable to other scenarios as well. I think one way of doing it is having apply command with the flag '-f' dictate whether to build or not, otherwise if '-f' is not supplied, we could assume the manifests are pre-built.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): Master branch
- kfctl version: (use `kfctl version`): kfctl v0.6.0-rc.0-143-g2395c5fc (from master branch)
- Kubernetes platform: On Premise Kubernetes
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

/cc @swiftdiaries @jlewi @kkasravi @yanniszark @gabrielwen

**Comment by holdenk** [comment]
I also ran into this. I think the problem is the hidden cache directory `.cache`. Can you run `ls -al`? Maybe we should update the error message to make it clear that this can include hidden files because the first few times I got this I wasn't sure what was happening.

**Comment by swiftdiaries** [comment]
/assign @swiftdiaries 
Fix: https://github.com/kubeflow/kubeflow/pull/4232
