### ISSUE TITLE
jovyan user cannot sudo in terminal

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#425]
If I open a terminal session from jupyter and I try to sudo I'm prompted for a password.

**Comment by pdmack** [comment]
The `jovyan` user does not have a password set with sudo access by default in order to avoid the case where a user starts a container from the image on a public host. However, there is an environment variable named GRANT_SUDO that can be passed to the container to do just that.

If you want to run the image from docker and give `joyvan` sudo then:
`docker run -it --rm -p 8888:8888 -e GRANT_SUDO=yes --user root gcr.io/kubeflow-images-staging/tensorflow-notebook-cpu`

![screen shot 2018-03-14 at 5 07 52 pm](https://user-images.githubusercontent.com/2380545/37430995-5001a53e-27aa-11e8-8d3f-f85d9cd2912e.png)

**Comment by ernestmartinez** [comment]
Thanks but I'm not running jupyter from the CLI, it is started by Jupyterhub from a kubeflow deployment.

**Comment by pdmack** [comment]
I'm sure it is, which is exactly my point. The Kubeflow image does not have that setting enabled.

**Comment by ernestmartinez** [comment]
the only reason I was trying to sudo was to address some permission errors I was getting. So my real problem is really sudo. I'll just wait for responses on my other issues.

Thanks

**Comment by hemangjoshi37a** [comment]
Has anyone found any password yet for jovyan??

please help.

**Comment by RichardBronosky** [comment]
If you want to understand the `docker run -it --rm -e GRANT_SUDO=yes` thing, see https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L89-L93

I will add that if the way the maintainers have chosen to handle users and password, you can change it in a Dockerfile. I explain how to add/change user/password in https://askubuntu.com/a/1307156/146273
```
username=jovyan
password=jovyan

adduser --gecos "" --disabled-password $username
chpasswd <<<"$username:$password"
# this would also work if username=root
```

**Comment by apulache** [comment]
Hi everyone!. 

I've just Kubeflow working on my K8S Cluster and I've notice that you could use the flag --user for installing pip packages. Apparently no sudo password is needed. 

For example: pip install torch --user (works in Jupyter Notebook using ! and on the Terminal as well.

I haven't try other commands, just pip and worked like a charmed.

Hope it helps!!!

**Comment by riteshpallod** [comment]
> > GRANT_SUDO
> 
> Please, what is the equivalent of --user for Kubernetes. I try the GRANT_SUDO variable and it is not working.

`--user root` add this.

**Comment by vulong3896** [comment]
If you want to use sudo in Jupyter's terminal, build your own image with Jupyter lab in the CMD layder, don't used the default image of kubeflow

**Comment by adgaultier** [comment]
you can also use a PodDefault  to mount a file with  `jovyan ALL = (ALL) NOPASSWD:ALL`  @ /etc/sudoers.d
you just need to have sudo in the base image
then you can keep this  as a base image for your users and still target the namespaced notebooks where you grant sudo to trusted users

**Comment by kk120120** [comment]
would like to share my last week experience in stackoverflow. hope it is helpful for beginners, as it has more detail steps. 
https://stackoverflow.com/a/79724625/27745919

principal is same to adgaultier's answer :  https://github.com/kubeflow/kubeflow/issues/425#issuecomment-1973797101
