### ISSUE TITLE
kfctl apply cannot re-run after failure

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4254]
/kind bug

**What steps did you take and what happened:**
1. kfctl apply -f XXX
It failed because I forgot to set client id and secret
2. retrying kfctl apply
This time failed with:
```
Error: error building KfApp:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: current directory not empty, please switch directories
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]
```

kfctl is built from master

**Comment by lluunn** [comment]
workaround: delete app.yaml and .cache manually

**Comment by yanniszark** [comment]
@jlewi is this the intended behavior?
Don't we want to allow the user to call kfctl apply twice?

**Comment by jlewi** [comment]
Duplicate of kubeflow/kfctl#45

@yanniszark this is a bug see kubeflow/kfctl#45.
