### ISSUE TITLE
[GCP] istio-ingressgateway failing health check on /healthz/ready

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4266]
/kind bug

I just deployed kubeflow using kfctl_gcp_iap.yaml from master.
When I checked the ingress the backend (istio-ingressready) was reported as unhealthy with 0 successful health checks.

The health check was set to /healthz/ready
which looks like the intended result
https://github.com/kubeflow/manifests/blob/21160c1463a46645a5b70e465988723ec1df6ccc/gcp/iap-ingress/base/config-map.yaml#L186

However when I ported forwarded to the ingress gateway I got a 401 on /healthz/ready

```
curl -I http://localhost:8080/healthz/ready
HTTP/1.1 401 Unauthorized
content-length: 29
content-type: text/plain
date: Thu, 10 Oct 2019 05:01:07 GMT
server: istio-envoy
```

/healthz gave me  a 200.

```
curl -I http://localhost:8080/healthz
HTTP/1.1 200 OK
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Wed, 09 Oct 2019 22:56:09 GMT
etag: W/"599-16db2bc9f28"
content-type: text/html; charset=UTF-8
content-length: 1433
date: Thu, 10 Oct 2019 05:01:35 GMT
x-envoy-upstream-service-time: 2
server: istio-envoy
```

So I deleted the backend-updater and in the UI set the health check to /healthz.

The health check passed and my backend came up.

So it looks like the health check is incorrect.

Did something change?

Could this explain why the endpoint test is ready is failing kubeflow/kfctl#42

/cc @zhenghuiwang @lluunn

**Comment by jlewi** [comment]
In my 0.7.0 cluster the docker image for the ingress gateway is

```
  - containerID: docker://a0e204b36e544aa55344e95384ce1f8c56c34649c1052320814896add054545c
    image: istio/proxyv2:1.1.6
    imageID: docker-pullable://istio/proxyv2@sha256:e7ee1ad38bd5b556ad0527ac691a9f647b66835960417b154c5d28b2ed9219cb

```

**Comment by jlewi** [comment]
On my 0.6 cluster image is

```
- containerID: docker://777f549715a1f72c10a96df814c7376209004c9f485bda7bd0ad8f8c51bbd012
    image: istio/proxyv2:1.1.6
    imageID: docker-pullable://istio/proxyv2@sha256:e7ee1ad38bd5b556ad0527ac691a9f647b66835960417b154c5d28b
```

**Comment by jlewi** [comment]
I just deployed Kubeflow from kubeflow/manifests 99246ddd4b2503b57b44a908ff0a7e41c4de4b0a which doesn't include kubeflow/manifests#491.

My endpoint was accessible just fine.

Here's my JWT policy

```
kubectl -n istio-system get policy -o yaml ingress-jwt
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authentication.istio.io/v1alpha1","kind":"Policy","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"iap-ingress","app.kubernetes.io/instance":"iap-ingress-v0.7.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"iap-ingress","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.7.0","kustomize.component":"iap-ingress"},"name":"ingress-jwt","namespace":"istio-system"},"spec":{"origins":[{"jwt":{"audiences":["TO_BE_PATCHED"],"issuer":"https://cloud.google.com/iap","jwksUri":"https://www.gstatic.com/iap/verify/public_key-jwk","jwtHeaders":["x-goog-iap-jwt-assertion"],"trigger_rules":[{"excluded_paths":[{"exact":"/healthz"},{"prefix":"/.well-known/acme-challenge"}]}]}}],"principalBinding":"USE_ORIGIN","targets":[{"name":"istio-ingressgateway","ports":[{"number":80}]}]}}
  creationTimestamp: "2019-10-13T00:15:37Z"
  generation: 2
  labels:
    app.kubernetes.io/component: iap-ingress
    app.kubernetes.io/instance: iap-ingress-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: iap-ingress
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: iap-ingress
  name: ingress-jwt
  namespace: istio-system
  resourceVersion: "5234"
  selfLink: /apis/authentication.istio.io/v1alpha1/namespaces/istio-system/policies/ingress-jwt
  uid: 952ee659-ed4e-11e9-aee2-42010a8e003e
spec:
  origins:
  - jwt:
      audiences:
      - /projects/147474701642/global/backendServices/2103215684271985193
      issuer: https://cloud.google.com/iap
      jwksUri: https://www.gstatic.com/iap/verify/public_key-jwk
      jwtHeaders:
      - x-goog-iap-jwt-assertion
      trigger_rules:
      - excluded_paths:
        - exact: /healthz
        - prefix: /.well-known/acme-challenge
  principalBinding: USE_ORIGIN
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 80
jlewi@jlewi-glap
```

The GCP health check is set to /healthz/ready.

**Comment by quanjielin** [comment]
that's weird, since ```exact``` should be a full string match(not prefix match) - 

```
bool AuthnUtils::MatchString(absl::string_view str,
                             const iaapi::StringMatch& match) {
  switch (match.match_type_case()) {
    case iaapi::StringMatch::kExact: {
      return match.exact() == str;
    }
    case iaapi::StringMatch::kPrefix: {
      return absl::StartsWith(str, match.prefix());
    }
```

**Comment by jlewi** [comment]
Lets verify with the next RC; 0.7.0RC.1 that 

1. The endpoint is accessible
1. GCP health check is set to /healthz/ready
1. That JWT policy is set to allow /healthz/ready

If all of that is working then we can close this bug.

**Comment by holdenk** [comment]
FYI I'm seeing something vaguely similar on 0.7RC1, I don't have the time to debug today though since it's Spark summit this week.

**Comment by jlewi** [comment]
@richardsliu's issue looks like he might have be running prior to #513

  * We should no loner be using the script to set the timeout.
  * The line "echo Increasing backend timeout for JupyterHub" has been deleted.

Next steps

* We should get a green for test_endpoint is ready test #4227 
* We need to verify with an RC that the health check is properly set

**Comment by zhenghuiwang** [comment]
The SSL certificate usage is under the limit. #4227 should not be an issue now.

**Comment by jlewi** [comment]
Lets leave this bug open until we have a passing green on master and the release branch
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master

It looks like we aren't getting any signal for the test_endpoint in the periodic tests.

That should hopefully be fixed by #4321 which was just merged.

**Comment by jlewi** [comment]
Here's a passing postsubmit.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1186357628540817412

For kfctl master

**Comment by jlewi** [comment]
Verification

Deployed with
kubeflow/kubeflow@0ba828a18ee97094a5aa24da2fe09ca75d05d15d
kubeflow/manifests@fccc0ac71efa0ca7816e4f9aa59d03d9dc6934d4
 v0.7-branch

Screenshot showing health check is /healthz/ready

![healthcheck](https://user-images.githubusercontent.com/777219/67497166-75671b80-f632-11e9-99fc-09dd9bf1f1a5.png)

Test unfortunately is hitting lets encrypt rate limiting

kubeflow/kfctl#63

**Comment by rky0930** [comment]
I got this issue after install kfserving v0.3.0 using kfserving/hack/quick_install.sh
After run the script, I can't access to kf-pipeline-ui. 

<img width="903" alt="스크린샷 2020-03-23 오후 12 30 09" src="https://user-images.githubusercontent.com/5013450/77278235-2832c700-6d02-11ea-86a6-bcc30687fe13.png">
