### ISSUE TITLE
Missing 2.0 TF images and add semantic 0.7.0 tags to the jupyter images and update the config map

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4267]
/kind feature

**Why you need this feature:**
We should add 0.7.0 tags to the jupyter images for 0.7.0 and update the configmap in manifests to use those tags.

These images unlike other images are user facing so it makes sense to use pretty/semantics tags.

**Comment by jlewi** [comment]
Added the v0.7.0 tags to the following images

* gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu@sha256:fe174faf7c477bc3dae796b067d98ac3f0d31e8075007a1146f86d13f2c98e13
* gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-gpu@sha256:895aa500ff09c9080e0755044e4fd9a3bd3dc3ae403415e220ebcc1dab09b6ef

It looks like the 2.0 images listed in the config map
https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/config-map.yaml#L29

*  gcr.io/kubeflow-images-public/tensorflow-2.0.0a-notebook-cpu:v-base-ef41372-1177829795472347138
* gcr.io/kubeflow-images-public/tensorflow-2.0.0a-notebook-gpu:v-base-ef41372-1177829795472347138

Don't actually exist.

/cc @Tabrizian

**Comment by Tabrizian** [comment]
@jlewi Sorry for the typo. 

Could you please tag the image below too, so that I can create another PR that updates the image names with tags?

https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-2.0.0a0-notebook-gpu@sha256:5c68ba7d700814c3deb8f91787ee2dd95c1ad5d3e2a11e8b328d55ca507c7b20/details?tab=info

**Comment by jlewi** [comment]
Thanks @Tabrizian 

I also tagged
gcr.io/kubeflow-images-public/tensorflow-2.0.0a0-notebook-cpu@sha256:e45be757280cd44c468892305fd10dd76098f01ad4706f0a8be1387051d9baca

**Comment by Tabrizian** [comment]
@jlewi I guess we can now close this issue.

**Comment by jlewi** [comment]
@Tabrizian lets verify its fixed and then we can close.

**Comment by jlewi** [comment]
Screen shot of jupyter images

![jupyterimages](https://user-images.githubusercontent.com/777219/66709527-155fa380-ed1b-11e9-935e-137f93d68fb0.png)

I started a jupyter image with the 2.0 GPU image
[tf-2-gpu-0.pods.txt](https://github.com/kubeflow/kubeflow/files/3721336/tf-2-gpu-0.pods.txt)

I ran

```
import tensorflow as tf
tf.__version__
```

Output was 

```
tf.__version__
```

Also checked it could see the GPU

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

Output was

```
Num GPUs Available:  1
```

So going to close this as fixed.

**Comment by ChethanUK** [comment]
I am getting "no healthy upstream" in 0.7 release.

**Comment by dgrahn** [comment]
@ChethanUK What is the workaround for this issue?
