### ISSUE TITLE
[kfctl] 0.7 not creating a default profile

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4270]
/kind bug

**What steps did you take and what happened:**
I used kfctl built from ec929c11b11951f6fd350f6552778f0df26566e6 to deploy using kfctl_gcp_iap.yaml

I expected a profile to be created automatically by the CLI but it was not.

**Comment by jlewi** [comment]
@kunmingg, @gabrielwen said you might have some insight here?

Was this an intentional change or is this a bug due to all the refactoring?

I think we should keep this behavior to match 0.6 behavior.

**Comment by kunmingg** [comment]
We can create default profile through an entry in manifests:
https://github.com/kubeflow/manifests/pull/493/files#diff-54be2f30a4a3a41da1eb4c1d33cdc0f1
Once the PR merged, user will have default profile.

**Comment by jlewi** [comment]
@kunmingg How would this work exactly? In particular, who sets the email to use as the profile user? Does that get set automatically by kfctl so the experience matches 0.6? Or would a user have to explicitly modify their KFDef file.

**Comment by jlewi** [comment]
@kunmingg Does your kfctl changes from yesterday have a fix for this?

**Comment by kunmingg** [comment]
Yes, close it now

**Comment by kunmingg** [comment]
https://github.com/kubeflow/manifests/pull/493
