### ISSUE TITLE
can not visit the kubeflow web ui according to the official website

### ISSUE THREAD

**Issue by jmsking** [kubeflow/kubeflow#4276]
/kind bug

**What steps did you take and what happened:**
>> I have install kubeflow according to https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ 
**Then i run these command as follows:**
>> $ kubectl get svc -n istio-system
- NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                                    AGE
- grafana                  ClusterIP   10.105.105.96    <none>        3000/TCP                                                                                                                                     9d
- istio-citadel            ClusterIP   10.104.62.222    <none>        8060/TCP,15014/TCP                                                                                                                           9d
- istio-egressgateway      ClusterIP   10.99.162.102    <none>        80/TCP,443/TCP,15443/TCP                                                                                                                     9d
- istio-galley             ClusterIP   10.105.238.131   <none>        443/TCP,15014/TCP,9901/TCP                                                                                                                   9d
- istio-ingressgateway     NodePort    10.103.202.229   <none>        15020:32695/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30469/TCP,15030:30275/TCP,15031:30225/TCP,15032:32213/TCP,15443:32747/TCP   9d
- istio-pilot              ClusterIP   10.108.6.253     <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       9d
- istio-policy             ClusterIP   10.97.249.167    <none>        9091/TCP,15004/TCP,15014/TCP                                                                                                                 9d
- istio-sidecar-injector   ClusterIP   10.97.133.121    <none>        443/TCP                                                                                                                                      9d
- istio-telemetry          ClusterIP   10.97.17.235     <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       9d
- jaeger-agent             ClusterIP   None             <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                                   9d
- jaeger-collector         ClusterIP   10.97.171.53     <none>        14267/TCP,14268/TCP                                                                                                                          9d
- jaeger-query             ClusterIP   10.103.40.12     <none>        16686/TCP                                                                                                                                    9d
- kiali                    ClusterIP   10.97.253.249    <none>        20001/TCP                                                                                                                                    9d
- prometheus               ClusterIP   10.103.226.230   <none>        9090/TCP                                                                                                                                     9d
- tracing                  ClusterIP   10.97.107.7      <none>        80/TCP                                                                                                                                       9d
- zipkin                   ClusterIP   10.109.176.56    <none>        9411/TCP                                                                                                                                     9d
**Then i want to visit the kubeflow central UI dashboard as presented at https://www.kubeflow.org/docs/other-guides/accessing-uis/, but when i visit http://localhost:8080, there is not a page presented**
_**Any help i will appreciate, Thx**_

**Comment by mosn** [comment]
could you please check the backend pod and see if it crashes? in such case you need to duplicate the admin secret in istion namespace as well.

**Comment by jmsking** [comment]
Yeahh, i find the pod is ErrImagePull.

because i am in china, so i can't visit the gcr.io, but i upload the needed image to nodes, for example: i have upload the image gcr.io/kubeflow-images-public/ingress-setup:latest in all nodes.

**$ docker images | grep gcr.io/kubeflow-images-public/ingress-setup**
gcr.io/kubeflow-images-public/ingress-setup                   latest                                               0cd6060b6372        13 months ago       256MB

And i modify the imagePullPolicy from Always to IfNotPresent using a shell scripts as follows:
`for file in $(grep -r imagePullPolicy | awk '{print $1}' | sed 's/://g'); do
    echo $file
    sed -i 's/Always/IfNotPresent/g' $file
done`

then i check whether modify successful or not as follows:
**$ grep -r imagePullPolicy**
then i find all "Always" is replaced by "IfNotPresent"

And i delete these pod as follows:
**$ kubectl delete pod admission-webhook-bootstrap-stateful-set-0 -n kubeflow**
And i find the pod is still pulling image from "gcr.io/kubeflow-images-public/ingress-setup:latest"
so there still throws a ErrImagePull exception
### And i have no ideas to solve these question, so any help i will very appreciated, thanks a lot

**Comment by mosn** [comment]
Have you tried the [documentation](https://www.kubeflow.org/docs/other-guides/kustomize/)
Also `${REPO}/components/` contains file which describes this in detail. 

If this helped, please consider closing the issue.

**Comment by jmsking** [comment]
Thanks for your rapidly reply.

i have installed the kubeflow according to this documentation you provided, and i have execute:
 kfctl init, generate and apply operation in order
but sone backend pod is ErrImagePull in kubeflow namespaces
