### ISSUE TITLE
Few long pending Jupyter, notebook controller PRs to be merged

### ISSUE THREAD

**Issue by nrchakradhar** [kubeflow/kubeflow#4277]
/kind question

**Question:**
There are few PRs related to Jupyter and notebook controller which are pending for quite some time now. For 0.7, merging them will help with code maintenance. Can this be looked into?

https://github.com/kubeflow/kubeflow/pull/3865 - Fix typo in notebook creation form
https://github.com/kubeflow/kubeflow/pull/3748 - remove jupyterhub code
https://github.com/kubeflow/kubeflow/pull/4098 - cleanup some codes in notebook controller
https://github.com/kubeflow/kubeflow/pull/4123 - support metrics in notebook-controller
https://github.com/kubeflow/kubeflow/pull/4216 - [3945] Configurable Istio Gateway for Notebook Controller

**Comment by jlewi** [comment]
Thanks @nrchakradhar if the reviewers aren't responsive to PRs you can ping the reviewers and if they still aren't responsive reassign them to someone.

**Comment by jlewi** [comment]
@kimwnasptd Can you help get this PRs merged?

@nrchakradhar Have you reviewed and LGTM'd the PRs? Can you please do an initial review

It looks like @krishnadurai is handling #4216

**Comment by kimwnasptd** [comment]
Yes, will start by reviewing #3865 #3748 and #4098

**Comment by lluunn** [comment]
reviewing them, thanks
