### ISSUE TITLE
Remove tensorboard link from Jupyter notebooks (hub?)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#428]
See #422 

There is an icon in Jupyter notebooks to launch tensorboard. We should remove that as using Jupyter to launch TensorBoard is no longer the recommended approach.

I think the initial idea was to use Jupyter/JupyterHub as a way to proxy connections to tensorboard. But we have a better reverse proxy solution with TensorBoard.

The plan moving forward is to add ksonnet components to make it easy to launch TensorBoard as a K8s deployment #297.

**Comment by jlewi** [comment]
I think this is where we install tensorboard
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile#L186

**Comment by ernestmartinez** [comment]
Is there any procedure I can use in the interim to run Tensorboard?

**Comment by jlewi** [comment]
@ernestmartinez My recommendation is to spawn TensorBoard manually as a K8s deployment per #297 
You can use this as an example
https://github.com/kubeflow/examples/pull/1/files#diff-b1c94ace60732530b2be5b0a67be2d40

**Comment by kkasravi** [comment]
see #446

**Comment by ernestmartinez** [comment]
Excuse my ignorance, but I'm not quite sure how to use the above link. I'm assuming it's a ks manifest, but I'm not quite sure if I should be installing a pkg, or applying it directly. 

Directions would be much appreciated.

**Comment by jlewi** [comment]
@ernestmartinez The above link is not a package its a component. You could copy it into the components directory of your ksonnet app and then use it.
