### ISSUE TITLE
central dashboard profile creation: use dns1123 name when auto fill and check names and 2 profiles created

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4281]
/kind bug

On profile setup page, I got auto filled name `kunming-google.com`, which is not compatible with sub resources name.

We should apply [format check](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L110) to profile names that either user input or we auto-fill.

**Environment:**
- central dashboard version: v0.6.2

**Comment by kunmingg** [comment]
And seems auto fill will change input field after user click `finish`.
It might be confusing as if user click `finish again`, they'll end up have 2 profiles created.

**Comment by avdaredevil** [comment]
The 2 profiles never succeed since only 1 profile can be made by a give name. Though yes, it's a less than ideal situation sometimes

**Comment by jlewi** [comment]
@avdaredevil I observed two profiles being created. Can we fix this?

**Comment by kunmingg** [comment]
@avdaredevil 
I think 2 profiles being created is because after user click "submit", auto-fill will change the profile name, and user thought it was auto-suggestion and click again.
So they end up have 2 created.

**Comment by avdaredevil** [comment]
Ok all of these are tackled in #4283

**Comment by kunmingg** [comment]
new image: gcr.io/kubeflow-dev/centraldashboard:v20191016-v0.7.0-rc.2-2-g4fdb2d1b

**Comment by kunmingg** [comment]
@avdaredevil 
Seems register page is not auto-redirecting to dashboard main page after profile created?

**Comment by avdaredevil** [comment]
Are you sure the profile got created?

**Comment by jlewi** [comment]
@avdaredevil @prodonjs Is it possible to begin writing some quick and dirty tests with selenium or similar (related to kubeflow/testing#288)? Maybe we can just script a curl command?

**Comment by avdaredevil** [comment]
@jlewi to add some context on this. This issue only seems to happen on the first profile setup in the cluster, and the behavior being seen here is that:
- We hit `profiles-kfam` with the `create` call
- It replies with a success
- We query profiles, and get an **empty list** (*perhaps it hasn't propagated yet, and profiles-kfam early replies with a success*)
- Dashboard thinks profile creation failed, keeps you on registration flow. (this is expected behavior).
  - Addendum: dashboard already has tests for this scenario via API mocks, but we expect that the API, when sending a success response, means that the network will list the profile created

**Comment by jlewi** [comment]
@avdaredevil Can we make the centraldashboard code more robust? Lets assume KFam isn't immediately consistent; how can the registration flow handle that better?

If the central dashboard just create a create call why does it immediately redirect back to the central dashboard and cause the looping behavior? Could the registration flow instead poll with some timeout to see if profiles returns non empty list before redirecting?



@avdaredevil Can we automate the E2E testing though so we can begin to get an automated signal that this is working? Can we create an E2E test for KFam that calls create?



@kunmingg Can you think of any reason why KFam API wouldn't be consistent? It looks like its just calling the K8s APi
https://github.com/kubeflow/kubeflow/blob/master/components/access-management/kfam/profiles.go

**Comment by yanniszark** [comment]
AFAIK, name is required to conform to DNS-1035.

**Comment by jlewi** [comment]
Chatted with @avdaredevil 

@avdaredevil and @prodonjs will look into adding some kind of polling mechanism to make the centraldashboard more robust in the event the backend API is not consistent.

ETA EOD Monday.

**Comment by jlewi** [comment]
It doesn't look like the image has been updated on the v0.7-branch
https://github.com/kubeflow/manifests/blob/v0.7-branch/common/centraldashboard/base/kustomization.yaml

Nor has it been updated on master
https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base/kustomization.yaml

**Comment by jlewi** [comment]
New image
gcr.io/kubeflow-images-public/centraldashboard:v0.7.0-rc.5-5-g0ba828a1
sha256:fa4ab9421b691eadaaa3a30d5ba69542f0c33e1c01da05298d0b5bd01856465b

**Comment by jlewi** [comment]
New image based on latest fix
gcr.io/kubeflow-images-public/centraldashboard:v0.7.0-rc.5-15-g62d91774
sha256:bcf462b61b7f39e1479c4ac6dd0eb5a1b2504f2d2e18e325c6e8404a28f09a60

We should update master; verify it works and then cherry pick it if it looks good.

**Comment by jlewi** [comment]
Tested on master. Everything looks good with image
gcr.io/kubeflow-images-public/centraldashboard@sha256:bcf462b61b7f39e1479c4ac6dd0eb5a1b2504f2d2e18e325c6e8404a28f09a60

A short screen cast to verify it works.
https://drive.google.com/file/d/1swFa0OSk_QkQMLWAys5nyTRJBqB_z79p/view?usp=sharing

**Comment by lluunn** [comment]
Seems this is fixed?

**Comment by jlewi** [comment]
Lets close this.
