### ISSUE TITLE
Jupyter Web App Better UI for Selecting GPUs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4288]
/kind feature

**Why you need this feature:**
Right now to add GPUs users have to add a free form string like "{ "nvidia.com/gpu": 1}" in the extra resources field.

This isn't very intuitive. It would be better if we could have a form that would just allow a user to enter the number of GPUs.

/cc @kimwnasptd

**Comment by kimwnasptd** [comment]
Yes, makes sense
/assign kimwnasptd

**Comment by jlewi** [comment]
@kimwnasptd do you think this will land in time for 1.0?

**Comment by kimwnasptd** [comment]
Yes, I'll try to start working on it by the end of the week.
It will need at most two days.
