### ISSUE TITLE
testing: add missing deployments/statefulsets to kf_is_ready_test.py

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4294]
/kind feature

**Why you need this feature:**
The `kf_is_ready_test` checks if certain Kubeflow deployments/statefulsets are ready.
The current list is missing a lot of the installed deployments/statefulsets (eg katib, metadata, some pipelines, admission webhook, ...).

**Describe the solution you'd like:**
Add the missing deployments/statefulsets to kf_is_ready_test in order to improve coverage.

**Anything else you would like to add:**
/cc @jlewi who has some suggestions on how to implement this in pytest.

**Comment by jlewi** [comment]
Repasting my comment from #4154 

I don't think we want one monolithic test. This prevents us from

* Having fine grained visibility into which services are causing problems
* Increases the likelihood of flakes
* Decreases our ability to skip or mark as expected flaky services

With pytest we can easily break this up into multiple test functions e.g.

```
def test_kfserving
   _wait_for_deployments(....)
   _wait_for_statefulsets(...)

def test_gcp
    _wait_for_deployments(....)
   _wait_for_statefulsets(...)
```

We can then use the pytest annotations to mark flaky tests to prevent them from blocking PRs.
We can also use pytest annotations to conditionally enable some tests
http://doc.pytest.org/en/latest/skipping.html
