### ISSUE TITLE
Document how directory structure is being used by kfctl for deployments and upgrades

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4300]
Need to document/clarify how the directory is inferred by kfctl under different contexts.

For deploying, kfctl can be used while inside an empty directory to create a new KfApp locally:
```
mkdir $KFAPP
cd $KFAPP
curl -L -o <some kfdef yaml file>
kfctl apply -V -f <kfdef yaml file>
```

But for upgrades, this won't work since we have to first find a reference to the old KfDef. The code is performing a directory walk starting at the current working directory, which means we have to call upgrade while we're inside the directory of the old kfapp (or a parent directory of it).

**Comment by ryandawsonuk** [comment]
Would be good to mention the purpose of the $KFAPP directory too. I've done a `kfctl build` and found that the directory is empty. It does create a `kustomize` directory and a `.cache` directory. Presumably these sibling directories are important as I can then do a `kfctl apply` without an error. But it's not intuitive that the directory is empty.

**Comment by ryandawsonuk** [comment]
Possibly what I'm seeing is not intended behaviour actually - https://github.com/kubeflow/kubeflow/issues/4358

**Comment by jtfogarty** [comment]
/area/document
