### ISSUE TITLE
How to expose the inference pipeline REST API end point ?

### ISSUE THREAD

**Issue by praveen049** [kubeflow/kubeflow#4314]
/kind question

**Question:**
[You can ask any question about this project.]
[my-pipeline.zip](https://github.com/kubeflow/kubeflow/files/3732961/my-pipeline.zip)

I have implemented a simple one stage ML inference pipeline. I have loaded the pipeline from the kubeflow UI and created a run. Everything seems to be ok - there are no error. 

This pipeline contains one component which contains a container running Flask and exposing REST API. 

How to make this REST API accessible from outside the cluster ?

Attached is the pipeline yaml file.

**Comment by krishnadurai** [comment]
@praveen049 could you try adding your Flask application's service file as a virtual service to Istio and then expose it via an istio ingress gateway? You could try adding this to the kubeflow's existing gateway as well.

**Comment by parthmishra** [comment]
@krishnadurai When exposing a REST API via istio ingress gateway, does that mean it's accessible from the cloud endpoint (assuming GKE deployment)? Or is it only accessible at the nodeIp:nodePort of the istio ingress gateway?

**Comment by praveen049** [comment]
@krishnadurai 
I have created the service using NodePort to expose the REST API and it seems ok

![image](https://user-images.githubusercontent.com/24820914/66977974-9a133e80-f0da-11e9-84e1-a3d9dc7842d1.png)

But curl to the port 31128 returns connection closed. I am attaching the pods describe.

[my-pipeline-pods-describe.txt](https://github.com/kubeflow/kubeflow/files/3737402/my-pipeline-pods-describe.txt)

Can you please help to confirm if i am missing something ?

Thanks

**Comment by praveen049** [comment]
Hi
  Any suggestions on how to troubleshoot this issue ?

Thanks

**Comment by krishnadurai** [comment]
I guess you need to set your bind IP to 0.0.0.0 in your Flask application to accept incoming requests.

**Comment by praveen049** [comment]
Hi 
 The Flask is bound to 0.0.0.0; this is the command used 

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000, debug=True)

I am able to run this Flask container as a pod in K8S cluster and create service to expose REST API as NodePort and it's working - I am able to curl from outside the cluster.

I suspect i am missing something when creating the Kubeflow component. Below is the code for creating the component

@kfp.dsl.component
def my_component():
  return kfp.dsl.ContainerOp(
    name='infer',
    image='praveen049/inf'
  )

Do i need to specify the expose port info here ?

**Comment by krishnadurai** [comment]
@praveen049 just to clarify, now are you able to curl and get the right response?

**Comment by krishnadurai** [comment]
Thanks @praveen049 for the explanation.

Probably @gaoning777 might be able to help you with your use-case.

**Comment by praveen049** [comment]
@gaoning777 @jlwei

Hi 
   Is it possible to get help with this issue ?

Thanks

**Comment by praveen049** [comment]
@gaoning777 @jlewi 

Any pointers on how to troubleshoot this issue ?

Instead of NodePort are there any other ways to expose the model to listen for request ?

**Comment by jlewi** [comment]
@praveen049 How exactly are you trying to connect inference and the ML pipeline. My general recommendation would be that you use pipelines to create a K8s resource like a Deployment or a KFServing resource to deploy the model. So the step is just creating that resource. The debug process would then be

1. Figure out what the spec should be so that you can connect to it
1. Verify the pipeline creates the  resource with the expected spec

It looks like you are trying to deploy the model directly in a pod executed as part of the pipeline

```
@kfp.dsl.component
def my_component():
return kfp.dsl.ContainerOp(
name='infer',
image='praveen049/inf'
)
```

I probably wouldn't recommend that approach. Nontheless the debug process would be the same.

1. Verify the pod exists and has the correct spec
1. Verify you can connect to it.

If it doesn't work it likely means one of two things

1. It doesn't work because of how pipelines is configuring the pod
    * You can verify this by creating the same pod spec directly and trying to reproduce the problem and changing the settings to verify it works

1. Its a problem unrelated to pipelines
    * You can verify by trying to reproduce by creating the pod directly with the same specs.

**Comment by praveen049** [comment]
@jlewi 

Thanks for the inputs. Yes, i am deploying the model directly as part of the pipeline.  I will try using the KFServing.

Btw, I am now able to expose the REST API using ClusterIP on a multi node k8s cluster - previously i was trying on microk8s cluster and it was not working.

Thanks

**Comment by desaintmartin** [comment]
@praveen049 out of curiosity, how did you have the related `Service` created/deleted? Have you been able to automate it?

**Comment by shantanuVerma7** [comment]
@praveen049 Hi, I have found a solution which may help you. In my case, I m running Tornado HTTP server in one of Kubeflow component. To make the port accessible on which tornado server is listening to, I have used the `add_port` method of `kfp.dsl.ContainerOp` class. The `add_port` method accepts object of class `V1ContainerPort` of module `kubernetes.client.models`. Below is the example.

I have created Kubeflow components using `kfp.component.func_to_container_op`
`comp_op = kfp.component.func_to_container_op(function_name,base_image)`

Define the pipeline
```
from kubernetes.client.models import V1ContainerPort
@dsl.pipeline(
    name = 'any name',
    description = 'some description')
def pipeline_func():
    task1 = comp_op.add_port(V1ContainerPort(container_port=8800,host_port=8800))

```
When you'll describe the pod, you will see
```
main:
    Port: 8800/TCP
    Host Port:  8800/TCP
```

**Comment by desaintmartin** [comment]
One question @shantanuVerma7: how do you manage lifecycle of your tornado server? Usually, the Pods composing the DAG pipeline will complete and the next stage of the DAG will run, but with a server that possibly never stops, how does it work?

**Comment by talal-sen** [comment]
> I suspect i am missing something when creating the Kubeflow component. Below is the code for creating the component

@shantanuVerma7 When i use your code, i get this error

`AttributeError: 'function' object has no attribute 'add_port'
`

**Comment by shantanuVerma7** [comment]
@talal-sen Can you please share the code?
