### ISSUE TITLE
How to install in Kubernetes under docker for Mac

### ISSUE THREAD

**Issue by shaunc** [kubeflow/kubeflow#4324]
/kind question

**Question:**
[You can ask any question about this project.]

There are no instructions anywhere to install in an existing kubernetes installation. Can I just run `kubectl -f ...` or `kubectl -k ...`? (And if not, why? .. ok that's another issue :)). If so -- what should I install?

NB Tried instructions in https://github.com/kubeflow/website/issues/318 -- but they don't work. I assume that they are for an obsolete version.

**Comment by devenjarvis** [comment]
Hey @shaunc there is another open issue with writing up this documentation. It also wasn't working for me, but I commented on that issue with what did work for me to get Kubeflow running on docker for mac. Warning, it's not the most straightforward process, but now that it's been figured out it's not impossible to get working. Hopefully, that issue will move forward soon and there will be official documentation on how to get this setup. In the meantime, I hope this helps!

https://github.com/kubeflow/website/pull/945#issuecomment-541310944

**Comment by shaunc** [comment]
Great -- thanks! ... though  a tool that claims to use GitOps should be installable via kubectl in whatever cluster.

**Comment by jtfogarty** [comment]
/area/docs
