### ISSUE TITLE
Notebook spec allows for periods '.' in the notebook name

### ISSUE THREAD

**Issue by zhilingc** [kubeflow/kubeflow#4325]
/kind bug

**What steps did you take and what happened:**
The notebook spec follows the standard resource naming convention (characters allowed in names are: digits (0-9), lower case letters (a-z), `-`, and `.`), but since the notebook controller tries to spawn a service with the same name, and service names cannot contain periods, the notebook will fail to start. 

From the UI, this is all opaque to the user.

Error log from notebook controller:
```
"kubeflow/david.lucker1","error":"Service \"david.lucker1\" is invalid: metadata.name: Invalid value: \"david.lucker1\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**What did you expect to happen:**
Some validation catching periods in notebook names. 

**Environment:**

- Kubeflow version: 0.5.0
- Kubernetes platform: gke
- Kubernetes version: 1.15.4 (also tested on 1.16.0)

**Comment by yeya24** [comment]
Two solutions for this issue.
1. Add a notebook name validation in notebook UI
2. Implement the check logic inside the controller, do some replacing for the invalid notebook name

I prefer the previous one.

**Comment by zhilingc** [comment]
I agree, the former is sufficient and should be easy to implement, since the main problem now is that kf UI users don't get any feedback when they submit an erroneous notebook name.
