### ISSUE TITLE
0.7rc3 darwin tarball is actually linux

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/kubeflow#4343]
looks like the linux tarball for 0.7rc3 accidentally was uploaded as the darwin tarball.

**Comment by swiftdiaries** [comment]
Added a fix here: https://github.com/kubeflow/kubeflow/pull/4308

**Comment by arun-gupta** [comment]
Thanks for the prompt fix! Is this related to https://github.com/kubeflow/kubeflow/issues/3755? Wondering if this is happening again?

I was trying to showcase Kubeflow at an event over the weekend and could not get the setup to work.

**Comment by LeonardAukea** [comment]
0.6.2 is the latest working build

**Comment by LeonardAukea** [comment]
Actually, the latest build 0.7.0. rc.4 works but it has been renamed `kfctl-darwin` https://github.com/kubeflow/kubeflow/blob/2fa8ba73efc4b30a5804cdb144bf531a16889423/bootstrap/Makefile#L116
