### ISSUE TITLE
v0.7.0-rc.3 "kfctl init is deprecated; please use new semantics" but what are the new semantics?

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/kubeflow#4345]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by shanidchamal** [comment]
@JakeTheWise see #3518
