### ISSUE TITLE
Kubeflow AWS 0.7 issues

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4354]
/kind bug

We have few issues open and need to be resolved for 0.7. Create this issue to track AWS specific bugs and issues.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): 0.7
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Jeffwan** [comment]
[] https://github.com/kubeflow/kubeflow/issues/4355
[] https://github.com/kubeflow/manifests/pull/518

**Comment by jlewi** [comment]
@Jeffwan I just approved kubeflow/manifests#518 but I think you will need to cherry pick it onto the v0.7-branch of kubeflow/manifests

**Comment by jlewi** [comment]
@Jeffwan Any update on this? It looks like kubeflow/manifests#518 just merged to master so I'm guessing we need to cherry pick it onto the 0.7 branch.

**Comment by jlewi** [comment]
@Jeffwan See my response on #4368

**Comment by Jeffwan** [comment]
Yeah, I will have doc change later on. Next step is to have some logic in build to make sure user can use Env and Template to build kustomize in one command. I will do this for next release.

The last two cherry-pick PRs for aws. Then we are good to go. 

https://github.com/kubeflow/manifests/pull/572
https://github.com/kubeflow/kubeflow/pull/4392

**Comment by Jeffwan** [comment]
No pending PRs. Thanks for the help. 

/close


List recent changes relate to this story for tracking. 
https://github.com/kubeflow/kubeflow/pull/4356 Fix aws plugin not found issue
https://github.com/kubeflow/kubeflow/pull/4383 Clean up alb and istio dependencies in kfctl delete
https://github.com/kubeflow/kubeflow/pull/4390 Fix apply overrides custom changes after Build for aws config

https://github.com/kubeflow/manifests/pull/518 Add application name for seldon and mpi-operator
https://github.com/kubeflow/manifests/pull/567 Clean up istio gateway and virtual services.

https://github.com/kubeflow/website/pull/1244 Updated the AWS guides for kfctl v0.7
https://github.com/kubeflow/website/pull/1271 Pin aws manifests to 0.7.0 and Update aws docs
