### ISSUE TITLE
kfctl build different structure for local or remote kfdef

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kubeflow#4358]
I am following the flow from https://github.com/kubeflow/kubeflow/pull/4040

If I do a `kfctl build -f` with `https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_existing_arrikto.yaml` then I get an app.yaml file generated. If I copy the same file to a local path and reference that then I do not get an app.yaml file, meaning that I can't then perform the apply step.

Also the directory structures generated are different. I get a kustomize directory under kfapp. If I use a local path to a kfdef file then I get a kustomize directory parallel to the kfapp dir.

**Comment by jlewi** [comment]
I think this is a duplicate of kubeflow/kfctl#54. The name of the YAMl file should be whatever the user defines.

**Comment by ryandawsonuk** [comment]
Good point, the file generated is indeed `kfctl_existing_arrikto.yaml` and not `app.yaml`. 

I've re-titled the issue as the other aspect of this I think isn't a duplicate. Namely that when I build from a remote file I get a kustomize folder under kfapp. When I build from a local file then the kustomize directory is placed parallel to the kfapp.

**Comment by ryandawsonuk** [comment]
Related to https://github.com/kubeflow/kubeflow/issues/4301
