### ISSUE TITLE
kfctl generate all - fails with error "Code 500 with message: couldn't copy application katib-db"

### ISSUE THREAD

**Issue by John-Tate** [kubeflow/kubeflow#4366]
/kind bug

**What steps did you take and what happened:**
Using the kfctl_k8s_istio.yaml config

```
export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml"
kfctl init ${KFAPP} --config=${CONFIG} -V
cd ${KFAPP}
kfctl generate all -V

INFO[0000] Processing application: istio-crds            filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: istio-install         filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: istio                 filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: application-crds      filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: application           filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: metacontroller        filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: argo                  filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: centraldashboard      filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: bootstrap             filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: webhook               filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: jupyter-web-app       filename="kustomize/kustomize.go:606"
INFO[0000] Processing application: katib-db              filename="kustomize/kustomize.go:606"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application katib-db
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'
      --ipName string     ipName if '--platform gcp'
      --mount-local       mount-local if '--platform minikube'
  -V, --verbose           verbose output default is false
      --zone string       zone if '--platform gcp'

couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application katib-db

```

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: 0.6.2
- Kubernetes platform: minikube
- Kubernetes version: 1.16.0
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by shanidchamal** [comment]
It is because the directory named katib-db is not present in manifest dir of kfapp directory.
check by changing directory to kfapp/.cache/manifest/...
i guess #4048 PR fixes it.

**Comment by kcturner123** [comment]
The next question is: "Why is it not there?"

**Comment by shanidchamal** [comment]
Sorry for not making it clear. @John-Tate  is using the master configuration file for v0.6.2 installation. so it fetches the manifest in master branch as well. [https://github.com/kubeflow/manifests](https://github.com/kubeflow/manifests). as you can see there is no katib-db in this manifest. This can be solved by using v0.6.2 config file. change the line to `export CONFIG="https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml"`. also Kubeflow is being tested with Kubernetes 1.14 only.

**Comment by kcturner123** [comment]
Thank you, that does make it much clearer. I am using microk8s 1.16, so I understand that I may have to roll back to 1.14.

**Comment by xigang** [comment]
same problem.

````
kubernetes version: v1.14.10
kfctl version: kfctl v1.0-rc.3-1-g24b60e8
kubeflow version: v0.7.1
```
When executing the following command, the following error is reported：

```
kfctl build -V -f kfctl_k8s_istio.0.7.1.yaml
```

logs:
```
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] .cache/manifests exists; not resyncing        filename="kfconfig/types.go:468"
INFO[0000] Processing application: istio-crds            filename="kustomize/kustomize.go:408"
Error: failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
                      	kfctl build -V --file=${CONFIG}
  -h, --help          help for build
  -V, --verbose       verbose output default is false

failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds
```

**Comment by xigang** [comment]
https://github.com/kubeflow/kubeflow/issues/4199

**Comment by xigang** [comment]
https://github.com/kubeflow/kubeflow/issues/4057

**Comment by xigang** [comment]
https://github.com/kubeflow/kubeflow/issues/4198

**Comment by ZhiqiangWangICT** [comment]
> I have a issue. How can i solve it ?
> 
> ```
> kubernetes version: v1.14.10
> kfctl version: kfctl v1.0-rc.3-1-g24b60e8
> kubeflow version: v0.7.1
> ```
> When executing the following command, the following error is reported：
> 
> ```
> kfctl build -V -f kfctl_k8s_istio.0.7.1.yaml
> ```
> 
> logs:
> ```
> INFO[0000]
> ****************************************************************
> Notice anonymous usage reporting enabled using spartakus
> To disable it
> If you have already deployed it run the following commands:
>   cd $(pwd)
>   kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
> 
> For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
> ****************************************************************
>   filename="coordinator/coordinator.go:120"
> INFO[0000] .cache/manifests exists; not resyncing        filename="kfconfig/types.go:468"
> INFO[0000] Processing application: istio-crds            filename="kustomize/kustomize.go:408"
> Error: failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds
> Usage:
>   kfctl build [flags]
> 
> Flags:
>   -f, --file string   Static config file to use. Can be either a local path:
>                       		export CONFIG=./kfctl_gcp_iap.yaml
>                       	or a URL:
>                       		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
>                       		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
>                       		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
>                       		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
>                       	kfctl build -V --file=${CONFIG}
>   -h, --help          help for build
>   -V, --verbose       verbose output default is false
> 
> failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds
> ```
> ```

I met same question, how did you fix it?
