### ISSUE TITLE
kfctl 0.7 not working with v0.6 config

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4371]
/kind bug

**What steps did you take and what happened:**
Deploy v0.6.2 using kfctl on master:
`kfctl build -V -f https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml`

Error is:
`Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp: Application default-install is missing`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
Downgrading to P1 because its not release blocking.
