### ISSUE TITLE
Setting up custom authentication using OIDC

### ISSUE THREAD

**Issue by webD97** [kubeflow/kubeflow#4374]
/kind question

**Question:**
Hello, first of all: Thank you for your amazing work on this project!

I am currently evaluating Kubeflow as a machine learning platform in our company. We have set up an on-premise k8s Cluster dedicated to Kubeflow 0.6.2 (which we set up with the arrikto config and MetalLB).  We need to customize some parts of the deployment to our needs and I got somewhat stuck, so I am hoping for some ideas/input from you.

We want to use an internal OIDC Provider for authentication. Although Dex seems to be able to federate our OIDC Provider, we prefer to get rid of Dex completely and let the authservice use our provider directly. I have experimented a bit and discovered that the authservice deployment has env variables that we can update so that it uses our OIDC provider (OIDC_PROVIDER_CA_FILE, OIDC_PROVIDER, OIDC_ID, OIDC_SECRET). This seems to work fine: The browser gets redirected properly between Kubeflow and our OIDC provider.

One thing that does not seem to work correctly to me is the following: Although I have been authenticated by the OIDC provider and have created a profile via the wizard screen in Kubeflow (which greets me with the message _Welcome, anonymous!_),, Kubeflow shows my username as _anonymous@kubeflow.org_. Also different users are not able to see the profile creation wizard, they get access to the Kubeflow dashboard immediately (also as _anonymous@kubeflow.org_). I wonder whether this is a problem with my OIDC setup (maybe some missing data in the id_token?). Did I miss something? Are there any OIDC-related docs other than _Multi-user, auth-enabled Kubeflow with kfctl\_existing\_arrikto_? 

Once I can fix this, I would like to make my changes reproducible with kustomize. Currently I am editing the authservice deployment using kubectl. Unfortunately I could not find the definition of the authservice and dex in the manifests of Kubeflow 0.6.2. Where are they coming from during installation?

Thank you in advance for your help and ideas!

**Comment by yanniszark** [comment]
Hi @webD97!
Thanks for trying out the existing_arrikto installation.
We are working on improving our auth installation and lowering the barrier of entry.

Let me try to address some of your concerns:

> Kubeflow shows my username as anonymous@kubeflow.org.

This is probably a misconfiguration in the authservice. The user value comes from the kubeflow-userid header. This is set by the authservice, by parsing the IDToken JWT. There was probably an error in that step.

> Unfortunately I could not find the definition of the authservice and dex in the manifests of Kubeflow 0.6.2. Where are they coming from during installation?

In v0.6.2, there were coming from the kubeflow repo, because of kfctl limitations.
In v0.7, we have lifted this restriction and are using them straight from the manifests repo. 
You can find them there:
* dex: dex-auth/dex-crds
* authservice: istio/oidc-authservice

The v0.7 release should be available shortly with all of these.

**Comment by webD97** [comment]
Thank you for your quick reply, @yanniszark!

I took a glance at the authservice logs and these seem to confirm your assumption of something going wrong there while extracting the username.

```
2019/10/14 09:37:33 Starting web server at :8080
2019/10/14 09:37:40 172.17.0.6 / Cookie not set, redirecting to login.
2019/10/14 09:37:40 172.17.0.6 Login validated with ID token, redirecting with JWT cookie.
2019/10/14 09:37:40 Unmarshalled to: {Email:}
2019/10/14 09:37:40 172.17.0.6 / Authorized & accepted.
2019/10/14 09:37:40 Adding header: kubeflow-userid =
```

 I will wait for Kubeflow 0.7 and check whether it works better with our own OIDC provider.

There is one other thing I noticed: I inspected the JWT that I found in the _auth_ cookie in Kubeflow and found out that it consists of two nested JWTs. This is something I have never seen before:

```json
{
  "exp": 1571831402,
  "iat": 1571831282,
  "iss": "10.63.25.201",
  "jti": "5f438340-874a-4653-87e6-f26842fc15ae",
  "uif": "eyJpc3..."
}
```

The issuer of this token is the machine that Kubeflow is running on. The _uif_ field contains another JWT whose issuer is our OIDC provider. This "outer" JWT does not contain a _sub_ field, but the "inner" JWT does. Maybe this is the reason why the authservice cannot find a username? I do not understand the purpose of these nested tokens (but I am also not exactly an expert at OIDC). Can you explain this to me?

**Comment by yanniszark** [comment]
@webD97 the nested JWT is the old way of keeping track of the logged in status.
We are now transitioning to sessions.
The new code lives here and soon in kubeflow: https://github.com/arrikto/oidc-authservice

**Comment by webD97** [comment]
Thank you for clarifying this 👍

**Comment by webD97** [comment]
I've got another question regarding customization:

If I understand [this file](https://github.com/kubeflow/manifests/blob/master/istio/oidc-authservice/base/params.env) correctly, Starting with 0.7, I should be able to override the OIDC params from the app.yaml config file; is this correct?

I also need to inject a custom CA cert into the authservice. What is the recommended approach for doing this with kustomize? In my manual experiments, I created a config map with the cert, mounted it into the container, changed `OIDC_PROVIDER_CA_FILE` to point to it and the authservice picked it up automatically. Will this variable still be supported in 0.7?

How would I do this with kustomize (so that `kfctl generate` applies my changes)? Do I need to fork the manifests repo, make my changes there and use it instead of kubeflow/manifests?

**Comment by yanniszark** [comment]
@webD97 it seems like your OIDC provider is not setting the email claim in the JWT.
Is that correct?
The new AuthService uses the UserInfo endpoint, so maybe it fixes that.

I recommend to wait for a bit until the dust settles and v0.7 is out.
A lot of things have changed slightly.

**Comment by webD97** [comment]
I just tried out v0.7.0-rc.6. Its authservice does not seem to support the `OIDC_PROVIDER_CA_FILE` env variable anymore. I found that one quite handy to inject company's CA cert.

**Comment by lalithvaka** [comment]
> /kind question
> 
> **Question:**
> Hello, first of all: Thank you for your amazing work on this project!
> 
> I am currently evaluating Kubeflow as a machine learning platform in our company. We have set up an on-premise k8s Cluster dedicated to Kubeflow 0.6.2 (which we set up with the arrikto config and MetalLB). We need to customize some parts of the deployment to our needs and I got somewhat stuck, so I am hoping for some ideas/input from you.
> 
> We want to use an internal OIDC Provider for authentication. Although Dex seems to be able to federate our OIDC Provider, we prefer to get rid of Dex completely and let the authservice use our provider directly. I have experimented a bit and discovered that the authservice deployment has env variables that we can update so that it uses our OIDC provider (OIDC_PROVIDER_CA_FILE, OIDC_PROVIDER, OIDC_ID, OIDC_SECRET). This seems to work fine: The browser gets redirected properly between Kubeflow and our OIDC provider.
> 
> One thing that does not seem to work correctly to me is the following: Although I have been authenticated by the OIDC provider and have created a profile via the wizard screen in Kubeflow (which greets me with the message _Welcome, anonymous!_),, Kubeflow shows my username as _[anonymous@kubeflow.org](mailto:anonymous@kubeflow.org)_. Also different users are not able to see the profile creation wizard, they get access to the Kubeflow dashboard immediately (also as _[anonymous@kubeflow.org](mailto:anonymous@kubeflow.org)_). I wonder whether this is a problem with my OIDC setup (maybe some missing data in the id_token?). Did I miss something? Are there any OIDC-related docs other than _Multi-user, auth-enabled Kubeflow with kfctl_existing_arrikto_?
> 
> Once I can fix this, I would like to make my changes reproducible with kustomize. Currently I am editing the authservice deployment using kubectl. Unfortunately I could not find the definition of the authservice and dex in the manifests of Kubeflow 0.6.2. Where are they coming from during installation?
> 
> Thank you in advance for your help and ideas!


> I just tried out v0.7.0-rc.6. Its authservice does not seem to support the `OIDC_PROVIDER_CA_FILE` env variable anymore. I found that one quite handy to inject our company's CA cert.

Hi @webD97 , were you able to integrate the Auto service with your enterprise OIDC successfully with 0.7 release and now with 1.0?

**Comment by webD97** [comment]
Yes, we got it to work in 0.7 (although the solution was still a bit hacky in my opionion).

**Comment by lalithvaka** [comment]
> Yes, we got it to work in 0.7 (although the solution was still a bit hacky in my opinion).
Would be great if you can post any steps you have followed to complete the integration. Am in the same boat of going through the integration with Ping Federate.

**Comment by webD97** [comment]
Yeah, I can try to help you with that. Unfortuantely I do not have the time right now to do a full step-by-step guide. What exactly are you having trouble with?

**Comment by lalithvaka** [comment]
Thank you for the offer. Here I have documented what I have configured and what am running into. 
https://github.com/kubeflow/kubeflow/issues/4847   
Just to summarize, I have used the build option and updated kustomize/oidc-authservice/base/params.env file to include the Ping Federate OIDC credentials / URLS and my Authservice-0 pod keeps throwing me with the following error every 10 seconds
time="2020-03-09T22:08:40Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: 404 Not Found: \n\n<title>404 Not Found</title>\n\nNot Found\n
The requested URL /.well-known/openid-configuration was not found on this server.
\n\n"

Please let me know if you

**Comment by webD97** [comment]
Looks like something is wrong with your params. Can you reach `https://<oidc-server>/.well-known/openid-configuration` with a browser or curl?

**Comment by lalithvaka** [comment]
My OIDC server i can reach from outside using my browser with out corporate firewall. Same with OIDC auth URL as well. Would it be ok to use Slack channel to have a better collaboration? you can find me @Lalith Vaka
