### ISSUE TITLE
KFP should support Tekton as an endpoint

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kubeflow#4378]
/kind feature

**Why you need this feature:**
MLOps features implemented by Kubeflow Pipelines can be a great adddition to Tekton as well, and there are requests from community members to enable these functionalities on top of Tekton

**Describe the solution you'd like:**
Start an  github repo which can help getting some experiments going on this side, while KFP itself is undergoing DSL changes vis a vis TFX alignment. We want to keep this experimental work separate for now

**Anything else you would like to add:**
Community participation
https://lists.cd.foundation/g/sig-mlops

**Comment by jlewi** [comment]
@animeshsingh pinged me on slack and requested the name kfp-tekton

**Comment by jlewi** [comment]
Setup according to
https://github.com/kubeflow/community/blob/master/repository-setup.md

Prow jobs still need to be setup.
