### ISSUE TITLE
Enhance support for OIDC auth to accept OpenShift 3.11

### ISSUE THREAD

**Issue by lomori** [kubeflow/kubeflow#4379]
/kind feature

**Why you need this feature:**
We would like to have kubeflow 0.6.x, in particular authentication, working on OpenShift 3.11.

**Describe the solution you'd like:**
Currently, the authservice Deployment resource has at least two issues that are causing problems:

1. OIDC_PROVIDER environment variable. See below example from our deployment
            - name: OIDC_PROVIDER
              value: 'https://172.29.132.204:5556/dex'
That IP is being retrieved by looking up the External IP assigned to the istio-ingressgateway service. This is correct for standard cloud providers that are able to provide a real IP for services type LoadBalancer, but that's not the case in OpenShift, unfortunately. That IP is invalid outside the cluster. This might be resolved using a k8s Ingress resource.

2. SELF_URL environment variable. See the example below.
            - name: SELF_URL
              value: 'https://172.29.132.204'
Same issue as above. This IP is not reachable from outside the cluster.

**Anything else you would like to add:**
It would be nice to be able to point to my own OIDC server.

**Comment by yanniszark** [comment]
Hi @lomori.
Have you tried the latest v0.7 release?
The way we setup OIDC is so that an external IP is not required.
You should be able to make it work in Openshift.
