### ISSUE TITLE
Cannot deploy v0.7rc5 to GCP from CLI

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/kubeflow#4381]
I ran `kfctl apply -f https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml -V`.

I got this error: `couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request`.

Checking GKE, a new cluster successfully spins up with all the kubeflow resources passing health checks. What am I doing wrong?

**Comment by Jetafull** [comment]
@JakeTheWise Did you solve this issue? I got the same error message.

**Comment by JakeTheWise** [comment]
Yes, sorry, it worked when I changed it to pull from master: `kfctl apply -f https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_gcp_iap.0.7.0.yaml -V`

**Comment by Jetafull** [comment]
The link to the master seems to be incorrect. I tried `kfctl apply -f https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_gcp_iap.yaml -V` but still got the same error.
