### ISSUE TITLE
scripts/setup-minikube.sh does not exist

### ISSUE THREAD

**Issue by retnuh** [kubeflow/kubeflow#4388]
/kind bug

**What steps did you take and what happened:**

While following the directions on the [Minikube for Kubeflow](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/) page, while executing the following:

```
export KUBEFLOW_TAG=v0.7.0-rc.5
curl -O https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/setup-minikube.sh
chmod +x setup-minikube.sh
./setup-minikube.sh
```

It turns out that there is no `scripts/setup-minikube.sh` script on that tag, or on master.

**What did you expect to happen:**

The script should exist!

**Anything else you would like to add:**

It's also surprising that there's no instructions under [Virtual Developer Environments](https://www.kubeflow.org/docs/other-guides/virtual-dev/) for just installing a kubeflow on a locally running Kubernetes cluster (which Docker Desktop for macOS basically has out of the box).  Maybe it's just a case of following the [standard instructions](https://www.kubeflow.org/docs/started/k8s/overview/) but even a blurb saying that that should be okay would be helpful.  (Maybe this should be raised as a separate issue).

**Environment:**

- Kubeflow version: v0.7.0-rc.5dashboard):
- kfctl version: (use `kfctl version`): N/A
- Kubernetes platform: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by KamalAman** [comment]
The script was removed in [PR 4084](https://github.com/kubeflow/kubeflow/pull/4084) Referenced in [Issue 4045](https://github.com/kubeflow/kubeflow/issues/4045)

**Comment by jlewi** [comment]
Here's an old link to the script
https://github.com/kubeflow/kubeflow/blob/e03858038f32c1cc419d0bffe94eb3e48289d90e/scripts/setup-minikube.sh

The generic minikube setup was closely coupled to the install of ksonnet and install of Kubeflow using the old kfctl.sh.

I'm not sure it would be worth it to try to to disentangle the minikube setup from the rest of it.

I think we should just delete the quick startup section in the docs that references this script.
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/#quick-setup

Below it we have instructions to set things up without using that script.
