### ISSUE TITLE
KubeFlow or Kubeflow?

### ISSUE THREAD

**Issue by DjangoPeng** [kubeflow/kubeflow#44]
I'm confused of the project name. Is it KubeFlow or Kubeflow? 

Personally speaking, KubeFlow is better because `Kube` and `Flow` are individually selected from two communities, which are `Kubernetes` and `TensorFlow` (can be extended to ML community in the future).

**Comment by sub-mod** [comment]
Base on reading https://news.ycombinator.com/item?id=15873659
It seems to me that it is KubeFlow for now but Kubeflow in future.
> NOTE: The name "flow" does not refer directly to TensorFlow; if anything it's a nod at all the river themes that pop up in the ML community (eg FBLearner Flow)

**Comment by aronchick** [comment]
"Kubeflow" please! (My opinion, I hate midword capitalization)
