### ISSUE TITLE
kfctl generate istio VirtualService with --use_istio false

### ISSUE THREAD

**Issue by sarjeet2013** [kubeflow/kubeflow#4411]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The bug is that the kustomize generated configs contains service yaml for istio `VirtualService` when `--use_istio false` is used

**What did you expect to happen:**

No istio related configs generated

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

With `--use_istio false`, there won't be istio CRDs and it will fail the deployment as some of the VirtualService is not recognised. See the errors below.

```
no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
v0.6.2
- Kubernetes platform: (e.g. `minikube`)
(On-prem) GCP cluster
- Kubernetes version: (use `kubectl version`):
1.15
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
ISTIO is required for Kubeflow beginning with 0.6.

The --use_istio flag is legacy and misleading and is removed in 0.7
