### ISSUE TITLE
CentralDashboard's welcome screen profile setup is broken - in non-identity aware cluster

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4415]
/kind bug

**What steps did you take and what happened:**

- Deployed kubeflow on a fresh Kubernetes cluster with kfctl_k8s_istio.0.7.0.yaml - with no default profile
- Accessed Web UI, this prompts to setup an initial profile
- After entering the profile name and clicking finish, the web UI doesn't transition to the dashboard
- Instead the UI remains unchanged and doesn't transition to the dashboard
- A second attempt at pressing the finish button leads to the state in the  image shown below

<img width="504" alt="Screenshot 2019-10-26 at 2 58 52 AM" src="https://user-images.githubusercontent.com/6263389/67605821-1d98f380-f79d-11e9-97a7-8acf84e16257.png">

**Anything else you would like to add:**
Central Dashboard is giving flaky behaviour with new deployments.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v0.7.0-rc.5-7-gc66ebff3 (v0.7.0-rc.6)
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-gke.0", GitCommit:"569511c9540f78a94cc6a41d895c382d0946c11a", GitTreeState:"clean", BuildDate:"2019-08-21T23:28:44Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): MacOS

**Comment by jlewi** [comment]
@krishnadurai which image are you using for central dashboard

If the profile `krishna-1` exists are you able to access the central dashboard?

/assign @avdaredevil

**Comment by Kyrremann** [comment]
We have the same problem. We use image `gcr.io/kubeflow-images-public/centraldashboard:v20190823-v0.6.0-rc.0-69-gcb7dab59`.

The profile is created, and if you just refresh the page you get directed to the dashboard. So everything "works", it's just the last missing redirect.

**Comment by jlewi** [comment]
That is an old image.

There is an updated image for 0.7 that attempts to fix these issues.
gcr.io/kubeflow-images-public/centraldashboard:sha256:bcf462b61b7f39e1479c4ac6dd0eb5a1b2504f2d2e18e325c6e8404a28f09a60

That was published recently.

**Comment by Kyrremann** [comment]
Okay, we are still on Kubeflow 0.6.2, waiting for a release of 0.7 (not a RC).

Don't know what @krishnadurai is on.

**Comment by krishnadurai** [comment]
@jlewi this is the image:

gcr.io/kubeflow-images-public/centraldashboard@sha256:bcf462b61b7f39e1479c4ac6dd0eb5a1b2504f2d2e18e325c6e8404a28f09a60

Confirmed the behaviour again.

**Comment by prodonjs** [comment]
@krishnadurai - I deployed the v0.7.0-rc.6 candidate to GCP which has the same centraldashboard image that you mention.

![Screenshot 2019-10-29 at 4 38 33 PM](https://user-images.githubusercontent.com/6835846/67807230-c92a9800-fa6a-11e9-986d-f406fed22468.png)

Your network requests should look similar to those above, which show a `create` POST, followed by 1 or more `exists` GETs until one of them includes `"hasWorkgroup": true`.

I retried the creation flow from the UI repeatedly but could not reproduce the behavior. Can you try to do so by deleting your profile resource (`kubectl delete profiles <profile name>`), and then reloading the UI which should trigger the flow again?

**Comment by krishnadurai** [comment]
Hello @prodonjs,

What I can see from the network tab is the '/api/workgroup/exists' API returning with 304 and the JS code goes on retrying the request repeatedly.

**Comment by krishnadurai** [comment]
Here's the HAR file from my Firefox browser.

**Comment by krishnadurai** [comment]
Link to the HAR document:
https://drive.google.com/file/d/0B1DnPeJ2dI2uT3dUMTM1QVB5UUlrSHJPSllRXy1QZFNKNHZr/view?usp=sharing

**Comment by krishnadurai** [comment]
A workaround to those who are facing this issue: Just refesh the page. It should take you to the dashboard.

**Comment by prodonjs** [comment]
Thanks for the information @krishnadurai. I looked into things more closely and what's peculiar is that your requests to `/api/workgroup/exists` seem to indicate that your cluster does not have identity awareness based on request headers sent to the centraldashboard server (the responses all show `"hasAuth": false`).

Thus, as the logic [here](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/api_workgroup.ts#L258) indicate,s if the incoming request cannot be associated with a user's identity, the response will always indicate that their is no workgroup for the user, thereby putting you in the awkward state you see.

@avdaredevil - This looks like a scenario where the cluster is non-identity aware, but there is no default namespace created for the user. I'm not sure if this is a change between versions, but it looks like our current logic may need to be modified.

**Comment by avdaredevil** [comment]
Yup you're right @prodonjs. I can make a follow up PR to resolve this.

**Comment by krishnadurai** [comment]
@prodonjs @avdaredevil 
Here's some additional information:
Originally, in v0.6.0 release, kfctl used to created a default profile: `kubeflow-anonymous` and with v0.7.0, it's optional. The default for this release is to have no profile created by default.

**Comment by jlewi** [comment]
@krishnadurai @Kyrremann Is this a cluster that is not identity aware?

* Is there an Auth server that is attaching JWT's to the request at the gateway?

  * I'm guessing no if you are using kfctl_k8s_istio.0.7.0.yaml 

  * In which case this should be a non-identity aware cluster. Which matches `hasAuth: False`

In the case where we don't know a user's identity my expectation is that AuthN should be disabled

* All users should see all Kubeflow namespaces whenever they access the central dashboard

  * It doesn't look like this is happening

  * It looks like the [FE](https://github.com/kubeflow/kubeflow/blob/618c77bef8e8672e2df174bf25659a3dbfcb9982/components/centraldashboard/app/api_workgroup.ts#L258) is hardCoding hasWorkgroup to False

  * Should it instead be sending the request to KFam and should KFam be returning the suitable workGroup?

   * I'm a little confused why refreshing would help? On refresh wouldn't we just end up get stuck again in the auto-registration flow because we don't have auth?

**Comment by jlewi** [comment]
kubeflow/kubeflow#4015 is tracking E2E tests for central dashboard and self-registration flow.

**Comment by jlewi** [comment]
@krishnadurai Do we have an issue tracking an E2E test for kfctl_k8s_istio?

**Comment by krishnadurai** [comment]
> @krishnadurai @Kyrremann Is this a cluster that is not identity aware?

The cluster is not identity-aware.

>     * Is there an Auth server that is attaching JWT's to the request at the gateway?
>       * I'm guessing no if you are using kfctl_k8s_istio.0.7.0.yaml
>       * In which case this should be a non-identity aware cluster. Which matches `hasAuth: False`

No, there's no auth server attaching the JWT to the request. You are right about the rest of the points. 

>       * I'm a little confused why refreshing would help? On refresh wouldn't we just end up get stuck again in the auto-registration flow because we don't have auth?

The check for the welcome screen for profiles right now seems to be configured based on whether there is a profile available or not. So when we refresh, the check fails in this scenario as the user has already created a profile.

**Comment by Kyrremann** [comment]
Not sure what you mean by identity aware, it's multiuser. We are also using an old image as it turns out (see comment further up).

What I do noticed is that if I remove all my cookies before going trough the process it works. This may also because I'm creating the same profile (and namespace), so maybe there is something stored in Kubeflow somewhere.

**Comment by krishnadurai** [comment]
@Kyrremann Can you share your HAR file as described above? That will help us see if the JWT is embedded in the request header or not in your case.

The root cause of this issue is documented here: https://github.com/kubeflow/kubeflow/issues/4415#issuecomment-547638105

And could you please check if this problem persists with 0.6.2 Kubeflow release?

**Comment by krishnadurai** [comment]
> @krishnadurai Do we have an issue tracking an E2E test for kfctl_k8s_istio?

This issue #3496 was made to track kfctl_k8s_istio.

**Comment by Kyrremann** [comment]
I'll create a HAR file.
I'm using `Build: v0.6.2 | Dashboard: v0.0.2-cb7dab | Isolation-Mode: multi-user`, and container image is `gcr.io/kubeflow-images-public/centraldashboard:v20190823-v0.6.0-rc.0-69-gcb7dab59`.

I can also manually upgrade the container image if desired.

**Comment by Kyrremann** [comment]
My HAR-file https://drive.google.com/file/d/1DDMCYisX5vnpWVAVVNHcY7ozd1IWEMox/view?usp=sharing

Also, tried two times, and it now worked both times. Which is strange. Several of my users has reported this problem.

**Comment by jlewi** [comment]
I built a new image

gcr.io/kubeflow-images-public/centraldashboard:list-8-gf5250b01 
sha256:4299297b8390599854aa8f77e9eb717db684b32ca9a94a0ab0e73f3f73e5d8b5

**Comment by jlewi** [comment]
Cherry pick #590 has been merged.
So the fix should be in the v0.7-branch and we just need to wait for verification.

**Comment by nrchakradhar** [comment]
> Cherry pick #590 has been merged.
> So the fix should be in the v0.7-branch and we just need to wait for verification.

#590 seems to point to kubeflow repo itself instead of kubeflow/manifests [#589](https://github.com/kubeflow/manifests/pull/589)

**Comment by jlewi** [comment]
@krishnadurai Are you able to verify this is fixed no so that we can close out this issue?

**Comment by krishnadurai** [comment]
@jlewi this is fixed
/close
