### ISSUE TITLE
Sorry, /pipeline/ is not a valid page

### ISSUE THREAD

**Issue by songkane** [kubeflow/kubeflow#4419]
/kind question

**Question:**
Hi，
I installed kubeflow using community kfctl ”https://www.kubeflow.org/docs/started/k8s/overview/#community-maintained“ , all dp,sts,svc pvc are running with no erro. But the when click sidebar 【pipeline，jupyter，katib，metadata】,errors come

![image](https://user-images.githubusercontent.com/15307785/67681723-d8f1a000-f9c8-11e9-979a-bc3454379c8a.png)
![image](https://user-images.githubusercontent.com/15307785/67681755-e73fbc00-f9c8-11e9-894c-22450b4a533b.png)

eg. I also create a new central svc (loadbalancer) for web browser

env
kfctl : v0.7.0-rc.6
CONFIG_URI:"https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml"

k8s resources
![image](https://user-images.githubusercontent.com/15307785/67680984-5f0ce700-f9c7-11e9-9926-688b19360bcd.png)
![image](https://user-images.githubusercontent.com/15307785/67681922-3c7bcd80-f9c9-11e9-82a4-13252fb91032.png)

![image](https://user-images.githubusercontent.com/15307785/67681023-76e46b00-f9c7-11e9-902c-6234bbd50673.png)

**Comment by shanidchamal** [comment]
@songkane reason is that you are accessing centraldashboard via deployment exposed as LoadBalancer service and not via istio-ingressgateway as mentioned in [istio website](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/)

**Comment by songkane** [comment]
Thank you, Using istio-ingressgateway is ok, it's better to update document about this .
