### ISSUE TITLE
kfctl / C2D: throw warning when length(deploy-name.endpoints.project-id.cloud.goog) > 63

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4421]
/kind bug
This is a limitation from let's encrypt.
We should throw warning messages and exit when 
length(deploy-name.endpoints.project-id.cloud.goog) > 63

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by amygdala** [comment]
maybe we should hash the project+deployment string and use the hash for the cert.

**Comment by kunmingg** [comment]
cert hostname need to match cloud endpoint hostname
