### ISSUE TITLE
e2e test for c2d

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4430]
/kind feature

We have a e2e test for click to deploy, running as postsubmit/periodic.

But it's failing for long time.
I am going to disable it for now, and we should update and re-enable it.

/cc @kunmingg

**Comment by jlewi** [comment]
It looks like the test code is here:
https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy_app.py
It looks like this just issues deploy requests.

The Argo workflow has a step to deploy the kfctl server. So it looks like the E2E test deploys kfctl server and then issues a deploy request to it.
