### ISSUE TITLE
Qualify 0.7.0 with kfctl_k8s_istio.yaml

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4441]
We are now on 0.7.0RC7 for kfctl
https://github.com/kubeflow/kubeflow/releases

There are currently no known P0 issues.
https://github.com/orgs/kubeflow/projects/22?card_filter_query=label%3Apriority%2Fp0

Opening this bug to track qualifying the `kfctl_k8s_istio.yaml` config. 

Ideally we'd like to aim to finalize 0.7.0 today. So it would be great to do run through the deployment and identify and fix any issues that come up.

There was a bug #4415 with the registration flow in the case with no identity.

We'd like to verify that issue has been fixed.

Related to: #4249 

/assign @krishnadurai

**Comment by krishnadurai** [comment]
> There was a bug #4415 with the registration flow in the case with no identity.
> 
> We'd like to verify that issue has been fixed.

This is fixed. Just verfied with a fresh deployment with the newest RC.

**Comment by krishnadurai** [comment]
What I've verified with this configuration:

1. Central Dashboard seems fine and #4415 is fixed now.
2. Notebooks and profiles are accessible and functional as intended
3. Pipelines seem to be working fine
4. Katib's random experiment example ran into this issue:

```
kubectl logs -n kubeflow random-experiment-random-868cd68f9b-8whsf
INFO:hyperopt.utils:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
INFO:hyperopt.fmin:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.

**Comment by hougangliu** [comment]
@krishnadurai 
for katib, it works fine, you can ignore the INFO.

**Comment by krishnadurai** [comment]
@hougangliu thanks.

**Comment by krishnadurai** [comment]
> ```
> kubectl logs -n kubeflow random-experiment-random-868cd68f9b-8whsf
> INFO:hyperopt.utils:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
> INFO:hyperopt.fmin:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
> ```

The katib tests passed.

**Comment by krishnadurai** [comment]
@jlewi the RCs look good.

#4452 is a cherry-pick which needs to be merged in.
