### ISSUE TITLE
Errors installing Kubeflow on an existing K8S/Istio cluster

### ISSUE THREAD

**Issue by CapKenR** [kubeflow/kubeflow#4469]
/kind bug

**What steps did you take and what happened:**
I have an existing Kubernetes cluster (1.14) with Istio (1.3.3), Knative and a few other applications running in it. I followed the instructions for installing Kubeflow for my situation.
```
$ wget https://github.com/kubeflow/kubeflow/releases/download/v0.7.0/kfctl_v0.7.0_linux.tar.gz
$ tar xzf kfctl_v0.7.0_linux.tar.gz
$ mv kfctl ~/.local/bin/
$ export KF_NAME=kubeflow
$ export BASE_DIR=/home/ken.rider/.cache
$ export KF_DIR=${BASE_DIR}/${KF_NAME}
$ wget https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
$ cp kfctl_k8s_istio.0.7.0.yaml kfctl_k8s.0.7.0.yaml
$ vi kfctl_k8s.0.7.0.yaml
$ mkdir -p ${KF_DIR}
$ cd ${KF_DIR}
$ kfctl apply -V -f ~/kfctl_k8s.0.7.0.yaml
$ kubectl get all -n kubeflow
```

I see several errors/warnings in the output where kubeflow is attempting to make changes to resources in another namespace (knative-serving in all the ones I see) that it shouldn't be impacting.

```
Name: "webhook", Namespace: "knative-serving"
Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" "metadata":map["annotations":map[...]]}
for: "/tmp/kout953651665": Deployment.apps "webhook" is invalid: spec.selector: Invalid value: v1.LabelSelector{...}: field is immutable]  filename="kustomize/kustomize.go:183"
WARN[0287] Will retry in 39 seconds.                     filename="kustomize/kustomize.go:184"
```
```
WARN[0330] Encountered error during apply:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{...}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "activator", Namespace: "knative-serving"
```
```
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{...}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "activator", Namespace: "knative-serving"
```
```
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{...}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "activator", Namespace: "knative-serving"
```
```
Name: "webhook", Namespace: "knative-serving"
Object: &{...}
for: "/tmp/kout880397355": Deployment.apps "webhook" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"webhook", "app.kubernetes.io/component":"knative-serving-install", "app.kubernetes.io/instance":"knative-serving-install-v0.8.0", "app.kubernetes.io/managed-by":"kfctl", "app.kubernetes.io/name":"knative-serving-install", "app.kubernetes.io/part-of":"kubeflow", "app.kubernetes.io/version":"v0.8.0", "kustomize.component":"knative", "role":"webhook"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]
```

**What did you expect to happen:**
kubeflow installed without errors.
AND, not make changes to resources already deployed for other applications.

**Anything else you would like to add:**
I didn't capture all of the output but what I did is attached as kfctl_apply.log.
[kfctl_apply.log](https://github.com/kubeflow/kubeflow/files/3810684/kfctl_apply.log)
I've also attached the kfctl_k8s.0.7.0.yaml (with a .txt extension) I used with the apply.
[kfctl_k8s.0.7.0.txt](https://github.com/kubeflow/kubeflow/files/3810688/kfctl_k8s.0.7.0.txt)

**Environment:**

- Kubeflow version: 0.7.0
- kfctl version: v0.7.0
- Kubernetes platform: Docker Enterprise
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-docker-1", GitCommit:"51f07ed581173b287557a03fea5e3a0d14093729", GitTreeState:"clean", BuildDate:"2019-09-19T18:37:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by krishnadurai** [comment]
@CapKenR thanks for reporting this.

I have a few questions:

1. Could you also please mention your installed Knative version?
1. Could you try installing by removing `knative-crds` and `knative-install` applications in the KfDef spec you've shared? I think your K8s cluster already has them installed and we shouldn't need to re-install them through KfDef again.

**Comment by krishnadurai** [comment]
Marking @ellis-bigelow @yuzisun @animeshsingh in case this is relevant to how we install or need to upgrade knative.

**Comment by CapKenR** [comment]
1. Could you also please mention your installed Knative version?
v0.10.0
2. Could you try installing by removing knative-crds and knative-install applications in the KfDef spec you've shared? I think your K8s cluster already has them installed and we shouldn't need to re-install them through KfDef again.
I've commented them out of the spec. I'll try it again as soon as the previous kubeflow namespace has been deleted. It's had a terminating status for about 30 minutes now which seems like an extremely long time to delete a namespace. I'll update the issue when I have a chance to try the apply again.

**Comment by CapKenR** [comment]
Attempting to delete the namespace, via `kfctl delete -V -f ~/kfctl_k8s.0.7.0.yaml` and `kubectl delete ns kubeflow`, has left the cluster in a bad state.
```
$ kubectl get ns
NAME                 STATUS        AGE
default              Active        2d15h
istio-system         Active        2d15h
knative-eventing     Active        2d14h
knative-monitoring   Active        2d14h
knative-serving      Active        2d14h
kube-node-lease      Active        2d15h
kube-public          Active        2d15h
kube-system          Active        2d15h
kubeflow             Terminating   45h
```
I'm using [Namespace “stuck” as Terminating, How do I remove it?](https://stackoverflow.com/questions/52369247/namespace-stuck-as-terminating-how-do-i-remove-it).
```
$ kubectl api-resources
error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
```
$ kubectl get apiservice | grep False
v1beta1.custom.metrics.k8s.io               knative-serving/autoscaler   False (MissingEndpoints)   2d15h
```
I may end up having to delete the cluster and start over if I can't figure out what's been screwed up.

**Comment by CapKenR** [comment]
I took the approach above to delete the namespace that was stuck terminating.
```
(
NAMESPACE=kubeflow
kubectl proxy &
kubectl get namespace $NAMESPACE -o json |jq '.spec = {"finalizers":[]}' >temp.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
)
```
I applied the updated KfDef spec (without the knative-crds and knative-install applications I just commented out and the Istio ones I'd previously commented out). It appears to have been successful.
```
$ kfctl apply -V -f ~/kfctl_k8s.0.7.0.yaml
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to ken.rider based on location of config file: /home/ken.rider/kfctl_k8s.0.7.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000]
.
.
.
application.app.k8s.io/seldon-core-operator created
INFO[0068] Applied the configuration Successfully!       filename="cmd/apply.go:72"
```
I'll play around with it to see if it's really working then I'll delete the cluster and create a new one to see if it works on a "clean" system.

**Comment by nrchakradhar** [comment]
#4486 is also mentioning the same for kfctl delete

**Comment by krishnadurai** [comment]
@CapKenR did this work with a clean system?

**Comment by CapKenR** [comment]
@krishnadurai, sorry. I forgot to update this issue. I did successfully install Kubeflow on a new, clean system, i.e. new K8S install, new Istio install and new Knative install. I followed that with a Kubeflow 0.7.0 install without the Knative and Istio applications.

**Comment by krishnadurai** [comment]
@CapKenR should we close this issue then?

**Comment by CapKenR** [comment]
I would suggest updating the documentation to reflect the need to comment out the Knative applications if you already have Knative installed.
