### ISSUE TITLE
Unable to install on minikube k8s on ubuntu

### ISSUE THREAD

**Issue by praveen049** [kubeflow/kubeflow#4472]
/kind bug

**What steps did you take and what happened:**
I am trying to install kubeflow 0.7 using the instructions https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

The apply step generates lot of WARNs and fails with below error:

`failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout823380323": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[configMapKeyRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[fieldRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[resourceFieldRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[secretKeyRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[resources].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root]`

I am attaching the output.
[kf07-install-minikube.txt](https://github.com/kubeflow/kubeflow/files/3812672/kf07-install-minikube.txt)

**What did you expect to happen:**
I am expecting the apply to be complete and pods to startup.

**Anything else you would like to add:**
I found some error in minikube logs below:

```
[Nov 06 05:32:02 minikube kubelet[3563]: E1106 05:32:02.888857    3563 pod_workers.go:191] Error syncing pod 583cdc9c-4ce1-493f-a771-7395b707fe7d ("istio-telemetry-6f6d8db656-9nd89_istio-system(583cdc9c-4ce1-493f-a771-7395b707fe7d)"), skipping: failed to "StartContainer" for "mixer" with CrashLoopBackOff: "back-off 5m0s restarting failed container=mixer pod=istio-telemetry-6f6d8db656-9nd89_istio-system(583cdc9c-4ce1-493f-a771-7395b707fe7d)"
Nov 06 05:32:03 minikube kubelet[3563]: E1106 05:32:03.287815    3563 pod_workers.go:191] Error syncing pod 25c59b81-1f8b-4fe5-8e28-8d9a9978e693 ("istio-policy-749ff546dd-2lv9z_istio-system(25c59b81-1f8b-4fe5-8e28-8d9a9978e693)"), skipping: failed to "StartContainer" for "mixer" with CrashLoopBackOff: "back-off 5m0s restarting failed container=mixer pod=istio-policy-749ff546dd-2lv9z_istio-system(25c59b81-1f8b-4fe5-8e28-8d9a9978e693)"

==> storage-provisioner ["cf0068b93e47"] <==
E1106 05:02:56.276618       1 controller.go:682] Error watching for provisioning success, can't provision for claim "kubeflow/metadata-mysql": events is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot list resource "events" in API group "" in the namespace "kubeflow"
E1106 05:04:12.185556       1 controller.go:682] Error watching for provisioning success, can't provision for claim "kubeflow/katib-mysql": events is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot list resource "events" in API group "" in the namespace "kubeflow"
E1106 05:04:22.698542       1 controller.go:682] Error watching for provisioning success, can't provision for claim "kubeflow/minio-pv-claim": events is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot list resource "events" in API group "" in the namespace "kubeflow"
E1106 05:04:28.247855       1 controller.go:682] Error watching for provisioning success, can't provision for claim "kubeflow/mysql-pv-claim": events is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot list resource "events" in API group "" in the namespace "kubeflow](url)"
```

The kubectl describe pods shows the attached info. Some of the pods are in Running status but the rest of the pods do not start.

[kubectl_get_pods.txt](https://github.com/kubeflow/kubeflow/files/3812694/kubectl_get_pods.txt)

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): `0.7.0`
- Kubernetes platform: (e.g. `minikube`) `minikube`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by shanidchamal** [comment]
unsupported Kubernetes version 1.16. use supported version 1.14
