### ISSUE TITLE
How can I use jupyterhub in the v0.7?

### ISSUE THREAD

**Issue by qinshuaihua** [kubeflow/kubeflow#4477]
/kind question

**Question:**
[I installed kubeflow in an existing cluster by the kfctl and config file.Now I can get pods below,but I do not know how to use jupyterhub in this version:]
![image](https://user-images.githubusercontent.com/34976119/68353906-e7b52100-0145-11ea-8ab5-a4967d1e0698.png)

**Comment by shanidchamal** [comment]
in Kubeflow, JupyterHub is replaced with web app that users can use to manage notebooks. It can be accessed through Kubeflow dashboard. head into [Set Up Your Notebooks](https://www.kubeflow.org/docs/notebooks/setup/) section for connecting to Kubeflow UI and Jupyter spawner UI.

**Comment by qinshuaihua** [comment]
> in Kubeflow, JupyterHub is replaced with web app that users can use to manage notebooks. It can be accessed through Kubeflow dashboard. head into [Set Up Your Notebooks](https://www.kubeflow.org/docs/notebooks/setup/) section for connecting to Kubeflow UI and Jupyter spawner UI.

Thank you. I will try to learn about that.
