### ISSUE TITLE
Add E2E tests for Istio 1.3.1

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4480]
/kind feature

**Why you need this feature:**
Istio 1.3.1 was recently added as an optional upgrade over Istio 1.1.6. In order to promote Istio 1.3.1 as the default installation for Istio, we should first introduce an automated E2E test.

**Describe the solution you'd like:**

Using kfctl tests we should define a KfDef containing Istio 1.3.1 as the default install. The test should:

1. Ascertain deployment with kfctl executes successfully
1. Some primary components of KfDef (centraldashboard, jupyter notebook-conroller) including Istio 1.3.1 are up and running
1. Test if the endpoint is ready for the deployment

/assign @krishnadurai

**Comment by krishnadurai** [comment]
As discussed in the community meeting on 12th November, we should look to introduce 1.3.1 Istio with kfctl_k8s_istio_dex.yaml and this test when its ready.

**Comment by jlewi** [comment]
@krishnadurai can you link to the relevant issues for k8s_istio_dex.yaml please?

**Comment by krishnadurai** [comment]
@jlewi I've used kubeflow/manifests#599 for tracking k8s_istio_dex.yaml.

**Comment by yanniszark** [comment]
/reopen
/lifecycle frozen
cc @krishnadurai any updates on this?

**Comment by krishnadurai** [comment]
@yanniszark Here's what we can do:

1. Have E2E tests for kfctl_istio_dex configuration deployment validate for all components being deployed.
2. Create a sample notebook with a user and see if the URL is accessible.

/cc @swiftdiaries

**Comment by yanniszark** [comment]
@krishnadurai sounds good. We could also leverage the `istioctl verify-install` command.

**Comment by DavidSpek** [comment]
@yanniszark Given the plans to upgrade istio, I think this issue can be closed and should be recreated for the newer version of istio once it has been implemented. Implementing E2E tests for istio 1.3.1 at this point seems a bit pointless

**Comment by yanniszark** [comment]
Istio manifests will actually be tested as part of wg-manifests. Also agree with what you say @DavidSpek. We can close this.
/close
