### ISSUE TITLE
Problems deploying Kubeflow on GCP  -- Please set the type prefix to be "serviceAccount:"., badRequest"

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/kubeflow#4483]
/kind bug

**What steps did you take and what happened:**
Previously I had no problems deploying kubeflow following the tutorial for CLI on GCP,https://www.kubeflow.org/docs/gke/deploy/deploy-cli/.  But currently when redeploying within a new project I am experiencing some strange problems with:

"(kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set New IamPolicy error: googleapi: Error 400: Account iotpubsub-1536350750202@appspot.gserviceaccount.com is of type "serviceAccount". Please set the type prefix to be "serviceAccount:"., badRequest"

**What did you expect to happen:**

Expected the deployment to succeed. 

**Anything else you would like to add:**
Been successful deploying kubeflow previously without any problems :) 
**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): 0.7.0
- Kubernetes platform: (e.g. `minikube`): GKE
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): Mac

**Comment by jlewi** [comment]
@NikeNano could you please run 

```
gcloud projects get-iam-policy ${PROJECT}
```

and look for `iotpubsub-1536350750202@appspot.gserviceaccount.com` 

If you feel comfortable please upload the output here?

This isn't a service account that Kubeflow is creating. Kubeflow does a Read-Modify-Write for the IAM policy.

My conjecture is that somehow the iam policy on the project already has that account listed without the prefix `serviceAccount`. So Kubeflow ends up trying to write it back to the project and that ends up generating the error.

/cc @kunmingg @gabrielwen

**Comment by NikeNano** [comment]
Apparently I had issus with the authentication to GCP. When running the command 

```
gcloud projects get-iam-policy ${PROJECT}
```

,it turned out that I had to rerun:

``` 
gcloud auth login
```
Then everything worked fine! 

Thank you for you help @jlewi I really appreciate it!
