### ISSUE TITLE
Istio ingress fails to reach ready state on EKS, statuscode 503

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#4500]
/kind bug

Upon deploying Kubeflow 0.7.0 on an EKS Cluster with Kubernetes 1.14 (following this guide: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/) all services start up correctly and `kubectl get ingress -n istio-system` returns an address after a few minutes. However, the address is not accessible. `kubectl -n istio-system describe pod/istio-ingressgateway-xxxxxxxxxx-yyyy` then yields:

```
Events:
  Type     Reason       Age               From                                    Message
  ----     ------       ----              ----                                    -------
  Normal   Scheduled    2m                default-scheduler                       Successfully assigned istio-system/istio-ingressgateway-565b894b5f-b56pz to ip-192-168-24-84.ec2.internal
  Warning  FailedMount  2m                kubelet, ip-192-168-24-84.ec2.internal  MountVolume.SetUp failed for volume "istio-ingressgateway-service-account-token-tzgwg" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  2m                kubelet, ip-192-168-24-84.ec2.internal  MountVolume.SetUp failed for volume "ingressgateway-ca-certs" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  2m                kubelet, ip-192-168-24-84.ec2.internal  MountVolume.SetUp failed for volume "ingressgateway-certs" : couldn't propagate object cache: timed out waiting for the condition
  Normal   Pulled       2m                kubelet, ip-192-168-24-84.ec2.internal  Container image "docker.io/istio/proxyv2:1.1.6" already present on machine
  Normal   Created      2m                kubelet, ip-192-168-24-84.ec2.internal  Created container istio-proxy
  Normal   Started      2m                kubelet, ip-192-168-24-84.ec2.internal  Started container istio-proxy
  Warning  Unhealthy    1m (x19 over 2m)  kubelet, ip-192-168-24-84.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
```

I am using `kfctl_aws.0.7.0.yaml`, not the cognito version.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0
- kfctl version: (use `kfctl version`): 0.7.0
- Kubernetes platform: EKS
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-27T14:42:18Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by karlschriek** [comment]
Also tried with istio 1.3.1 (as describe here: https://github.com/kubeflow/manifests/pull/413), with the same result

**Comment by karlschriek** [comment]
Some more testing reveals:
- EKS Kubernetes 1.14 / Istio 1.1.6 -> doesn't work
- EKS Kubernetes 1.13 / Istio 1.1.6 -> doesn't work
- EKS Kubernetes 1.12 / Istio 1.1.6 -> works

**Comment by krishnadurai** [comment]
@karlschriek does this look more to do with Istio? I think it would be better to reach out to https://github.com/istio/istio/ regarding this issue.

**Comment by chanwit** [comment]
@karlschriek I stuck by this bug as well. have you know the root cause of this problem?

**Comment by Jeffwan** [comment]
@chanwit  @karlschriek 
In this case, could you guys please share the istio-system pods status? It's possible that Ingressgateway is blocked by Pilot, which is blocked by galley which is blocked by citadel, etc. 
Let's make sure your istio control plane is ready and healthy.

**Comment by chanwit** [comment]
don't mind me. I upgraded Istio to 1.3.5 via Helm and it's working fine now.

**Comment by karlschriek** [comment]
> @karlschriek does this look more to do with Istio? I think it would be better to reach out to https://github.com/istio/istio/ regarding this issue.

I undestand the reasoning that this should probably be addressed by the Istio team, but on the other hand Kubeflow is an ecosystem consisting of a great many different such projects. 

From my perspective Kubeflow is interesting to the community of Machine Learning developers exactly because it promises to abstract away a lot of the underlying complexity. That promise gets watered down quite a lot when the responsibility for ensuring that the ecosystem works simply gets delegated to the projects Kubeflow is built on! 

Also, quite possibly the problem is already solved with a newer version of Istio (which @chanwit's comment above seems to suggest), but the default Kubeflow distribution is currently locked to 1.1.6 Based on my tests, it isn't addressed by 1.3.1 though (which was the latest version being discussed as becoming the new standard version). It is probably quite important for the Kubeflow team to know this.

**Comment by chanwit** [comment]
My way of installing Istio 1.3.5 is not the standard way used by `kfctl`
Basically, I removed all Istio deployment, svc and manually did it via Helm.

**Comment by karlschriek** [comment]
> @chanwit @karlschriek
> In this case, could you guys please share the istio-system pods status? It's possible that Ingressgateway is blocked by Pilot, which is blocked by galley which is blocked by citadel, etc.
> Let's make sure your istio control plane is ready and healthy.

So I just started up the autoscaling groups on the cluster where I was testing this out (EKS with Kubernetes 1.14 and Istio 1.3.1) and... today it works. I find this behaviour very difficult to comprehend. Either there is some element of randomness in there that causes the pods to block each other depending on the startup order, which means the 20 odd times I tried without success last week was just bad luck. Or something has changed on EKS to correct the problem. @Jeffwan, do you have any ideas?

**Comment by Jeffwan** [comment]
@karlschriek 
I don't think we have anything changed this week on our end. It's a kubecon week this week.. 
Are you using your corp environment? Not sure if you see this by using your personal account? 
I would also suggest you to reach out to EKS team via account manager and we can help check your cluster as well.

**Comment by karlschriek** [comment]
@Jeffwan, ok thanks for the reponse! Yep I can see this using my personal account, have just been unavailable the last few days. 

For now at least the cluster we are using is running, but if we run into problems again I'll be in touch with our account manager.

**Comment by DdMad** [comment]
I was facing the same issue and after upgrade istio to 1.4.3 (original version with Kubeflow is 1.1.6) it is working now.

**Comment by JohnRobinv** [comment]
@DdMad May I ask how to upgrade istio version?

**Comment by DdMad** [comment]
@JohnRobinv here is the guide: https://istio.io/docs/setup/upgrade/cni-helm-upgrade/

**Comment by JohnRobinv** [comment]
> @JohnRobinv here is the guide: https://istio.io/docs/setup/upgrade/cni-helm-upgrade/

Thanks for your reply. But I did use neither helm nor istioctl to install it.
I deployed kubeflow to an existing GKE cluster. And encountered same issue above..
So I m wondering if I can upgrade the istio component directly. Otherwise I need to remove the cluster first then deploy a new version of kubeflow.

**Comment by DdMad** [comment]
@JohnRobinv I think it should be fine because helm and istioctl are just tools. You just need to install helm, and then follow the guide to use helm to upgrade istio. (probably no need to have istioctl though it's just a binary)
I'm using K8s on-prem, and it works for me to upgrade istio this way

**Comment by mosyang** [comment]
I follow the **Istio configuration for trustworthy JWTs** part in [kubeflow document](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#before-you-start) without upgrading istio.  It works!
- kubernetes 1.14.10 with kubeadm
- kubeflow with kfctl_istio_dex.v1.0.1.yaml
- Add below parameters into kube-apiserver launch command in `/etc/kubernetes/manifests/kube-apiserver.yaml`

> --service-account-issuer=kubernetes.default.svc
> --service-account-signing-key-file=/etc/kubernetes/pki/sa.key

- systemctl restart kubelet
