### ISSUE TITLE
Cannot connect to google cloud storage

### ISSUE THREAD

**Issue by corvin-quodai** [kubeflow/kubeflow#4506]
/kind bug

**What steps did you take and what happened:**
Running on GKE.
Cannot connect to google cloud storage via python. SSH'd into worker node of 0.7.0 IAP deployment and tried to connect to google cloud storage via python sdk (commands and stack trace see below). Did the same in a 0.6.2 non-IAP deployment (same service account config) and it works perfectly fine.

`curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google"` properly returns access token on both nodes.

```
>>> from google.cloud import storage
>>> t = storage.Client()
>>> t.get_service_account_email()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/credentials.py", line 96, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/credentials.py", line 77, in _retrieve_info
    request, service_account=self._service_account_email
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/_metadata.py", line 200, in get_service_account_info
    recursive=True,
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/_metadata.py", line 153, in get
    response,
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 500 Response:\nb'GKE Metadata Server encountered an error: Could not recursively fetch uri\\n'", <google.auth.transport.requests._Response object at 0x7f2b82286e80>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/client.py", line 228, in get_service_account_email
    api_response = self._base_connection.api_request(method="GET", path=path)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/_http.py", line 389, in api_request
    target_object=_target_object,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/_http.py", line 266, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/_http.py", line 295, in _do_request
    return self.http.request(url=url, method=method, headers=headers, data=data)
  File "/usr/local/lib/python3.6/site-packages/google/auth/transport/requests.py", line 212, in request
    self._auth_request, method, url, request_headers
  File "/usr/local/lib/python3.6/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/credentials.py", line 102, in refresh
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 500 Response:\nb'GKE Metadata Server encountered an error: Could not recursively fetch uri\\n'", <google.auth.transport.requests._Response object at 0x7f2b82286e80>)
>>> import socket
>>> socket.gethostbyname('metadata.google.internal')
'169.254.169.254'
```

**What did you expect to happen:**
Should connect regularly.

**Environment:**

- Kubeflow version: 0.7.0 and 0.6.2
- kfctl version: 0.7.0
- Kubernetes platform: GKE
- Kubernetes version: 1.16
- OS (from `/etc/os-release`):
```
BUILD_ID=10895.348.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=f2a646b776532b7dda331faf8c66b0dbfa7c28b5
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=69
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=69
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

**Comment by corvin-quodai** [comment]
Some more info: when manually passing the credentials key for the service account that the instance uses, I get access to the buckets. Verifies that the service account is setup correctly. Seems like the creation of the VMs in the GKE node pool for kubeflow does not properly pass the credentials to the VMs.

**Comment by NikeNano** [comment]
I am still new but thougt I could share how I understand at least, hope it helps!

I think the VM:s per default have very limited access to GCP resources. Instead I believe the use of service accounts are suggested. You could change the scope of the VM:s in the gcp_config/cluster.jinja file if you like to change it :) What are you using kubeflow for? For pipelines there are some specific functions to add the created service account credentials in order to get the GCP access ".apply(gcp.use_gcp_secret('user-gcp-sa')", for example see: https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/

**Comment by jlewi** [comment]
Have you taken a look at the doc
https://www.kubeflow.org/docs/gke/authentication/#starting-in-kubeflow-v0-7-google-kubernetes-engine-gke-workload-identity  ?

If you are using workload identity is your pod running as a service account bound to a GCP service account (GSA) with appropriate credentials?

If you are using the old method of attaching a service account for a GSA are you mounting the secret and setting GOOGLE_APPLICATION_CREDENTIALS?

**Comment by pradeepbhadani** [comment]
I faced similar issue with another application. 
It turned out that Google Service Account (attached to the pod) lost its IAM binding for `roles/iam.workloadIdentityUser`.
Re-issuing `gcloud iam service-account add-iam-policy-binding` command fixed the issue.
