### ISSUE TITLE
[Feature] At the end of a training run, create a service endpoint for the model

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#451]
P0: a K8s service endpoint
P1: the creation of that service endpoint has the option to create an external LB, with a resolvable DNS endpoint

**Comment by jlewi** [comment]
Can you clarify what you are requesting here? If you want to train a model and deploy it, why wouldn't you just create an Argo workflow to do that? 

Should the problem of continuous training and deployment be handled by systems like TFX?

**Comment by bhack** [comment]
Is there a plan about TFX public release? Cause we already mentioned it in another ticket

**Comment by bhack** [comment]
Now the we know a little bit more about the TFX release plan and that kubeflow will have other kind frameworks operator (pytorch, mxnet etc.) what is your outlook about TFX/Kubeflow interaction/integration?

**Comment by jlewi** [comment]
TFX currently consists of the following components
- TF Serving
- TF.transform
- TFMA

We already use TFServing and are working on building out the story; e.g. ISTIO integration and model deployment.

TF.Transform and TFMA are baked into our Jupyter notebook images so folks can use them. I can't think of any immediate work on the Kubeflow side other than integrating them into our examples to highlight them.

**Comment by jlewi** [comment]
An alternative to using an explict graph like Argo to handle train -> deploy would be to do an implicit event driven graph.

- When a training job finishes we could emit an event (could be K8s event) indicating the model is ready and pointing at its location
- A handler (kubeless? or some other lambda framework) could listen for such events and deploy models

TFJob should already emit an event when the job is done. So a lambda could listen for that event and then parse the TFJob to get the model location.

@inc0 This might be an interesting application of Kubeless.

**Comment by thomasSve** [comment]
How is this issue moving forward? Currently I have my models deployed with tensorflow serving in kubeflow and am trying to add a endpoint service to the deployment so I can improve my monitoring

**Comment by jlewi** [comment]
@thomasSve I would suggest looking at using kubeflow/pipelines to define workflows that train and deploy models.
