### ISSUE TITLE
TFServing supports for general collections of metrics.

### ISSUE THREAD

**Issue by irvifa** [kubeflow/kubeflow#4514]
I saw this issue https://github.com/kubeflow/kubeflow/issues/1036 and was wondering will it be good to provide an API that will allow us to define our own metrics collector. A building block/API that can be extended should be good enough (this will accommodate more user specific use cases).

**Comment by yeya24** [comment]
I don't think this is a kubeflow-side issue. It is more likely a Prometheus configuration. You can easily drop the metrics you don't want in Prometheus.

**Comment by irvifa** [comment]
@yeya24 Hi, thanks. However I'd like to highlight more on the part of standardizations of creating a plugin for the metrics, besides the prometheus itself.

**Comment by irvifa** [comment]
@jtfogarty any update on this? Because it's been marked to stale due to inactivity

**Comment by jtfogarty** [comment]
@irvifa this issue might be better in the [kfserving repo](https://github.com/kubeflow/kfserving)

**Comment by irvifa** [comment]
I see.. I'm moving the issues then. And close this one. Thanks!
