### ISSUE TITLE
Jupyter Notebooks - can we change 'schedulerName'?  

### ISSUE THREAD

**Issue by itayvallach** [kubeflow/kubeflow#4524]
/kind question

**Question:**
We want to use our own custom scheduler for running Jupyter notebooks and not the default-scheduler. Is that possible?

**Comment by fediazgon** [comment]
No, it is not possible. You can see [here](https://github.com/kubeflow/kubeflow/blob/6f790f8f3b43d8048d9fbeff7e64857da264f83b/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml) all the values fetched from the UI. Also, in [this file](https://github.com/kubeflow/kubeflow/blob/6f790f8f3b43d8048d9fbeff7e64857da264f83b/components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py) you can see how the notebook's `spec` is populated and there is no track of `schedulerName`.

**Comment by itayvallach** [comment]
@fediazgon  Thank you for the response. This is quite disappointing, I would expect to have control over the scheduler of my notebooks. I created a very simple PR that will allow users to set a custom schedulerName using the "notebook-controller-parameters" ConfigMap, I think this is the proper place for this configuration.
Link to the PR: https://github.com/kubeflow/kubeflow/pull/4525
