### ISSUE TITLE
Kubeflow 0.7.0 Deployment IAP Failed Create Endpoints with private GKE

### ISSUE THREAD

**Issue by tiopramayudi** [kubeflow/kubeflow#4527]
/kind bug

**What steps did you take and what happened:**
I faced problem when deploying kubeflow 0.7.0 in private cluster using gke 1.14 and this `https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml` and used modified network for cluster dm. There is no error logs while doing deployment, but I can't access `https://${{FQDN}}`, got error DNS_PROBE_FINISHED_NXDOMAIN. I did troubleshoot by running this 
```json
  kubectl describe -n istio-system managedcertificate gke-certificate

  Status:
  Certificate Name:    mcrt-853cec7a-8a3b-4c34-989e-8818e9c104b4
  Certificate Status:  Provisioning
  Domain Status:
    Domain:  {{KF_NAME}}.endpoints.{{PROJECT}}.cloud.goog
    Status:  FailedNotVisible
```

I also noticed that endpoint is not created. This is log on cloud-endpoints-controller 
`[ERROR][{{KF_NAME}}] Failed to get existing endpoint service: Get https://servicemanagement.googleapis.com/v1/services/{{KF_NAME}}.endpoints.{{PROJECT}}.cloud.goog?alt=json: status code 500 trying to fetch http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token` 

**What did you expect to happen:**
I can access `https://${{FQDN}}`

**Anything else you would like to add:**
Some troubleshooting steps from jeremy,
```json
gcloud --project=${PROJECT} iam service-accounts  get-iam-policy ${KFNAME}-admin@${PROJECT}.iam.gserviceaccount.com 

bindings:
- members:
  - serviceAccount:${PROJECT}.svc.id.goog[istio-system/kf-admin]
  - serviceAccount:${PROJECT}.svc.id.goog[kubeflow/kf-admin]
  - serviceAccount:${PROJECT}.id.goog[kubeflow/profiles-controller-service-account]
  role: roles/iam.workloadIdentityUser
etag: BwWYLZVxpU4=
version: 1
```

```json
kubectl -n istio-system describe cloudendpoints ${KF_NAME}
Name:         {{KF_NAME}}
Namespace:    istio-system
Labels:       app.kubernetes.io/component=iap-ingress
              app.kubernetes.io/instance=iap-ingress-v0.7.0
              app.kubernetes.io/managed-by=kfctl
              app.kubernetes.io/name=iap-ingress
              app.kubernetes.io/part-of=kubeflow
              app.kubernetes.io/version=v0.7.0
              kustomize.component=iap-ingress
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"ctl.isla.solutions/v1","kind":"CloudEndpoint","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"iap-ing...
API Version:  ctl.isla.solutions/v1
Kind:         CloudEndpoint
Metadata:
  Creation Timestamp:  2019-11-21T15:37:22Z
  Generation:          1
  Resource Version:    3382
  Self Link:           /apis/ctl.isla.solutions/v1/namespaces/istio-system/cloudendpoints/{{KF_NAME}}
  UID:                 cfa7fcdd-0c74-11ea-85b1-4201ac100013
Spec:
  Project:  {{PROJECT}}
  Target Ingress:
    Name:       envoy-ingress
    Namespace:  istio-system
Events:         <none>
```

Checking if there are problems with the node-metadata server in the case where I modified the network

```json
kubectl run --rm -it \
  --generator=run-pod/v1 \
  --image google/cloud-sdk:slim \
  --serviceaccount kf-admin \
  --namespace kubeflow \
  workload-identity-test

gcloud auth list
ACTIVE  ACCOUNT
*       {{KF_NAME}}-admin@{{PROJECT}}.iam.gserviceaccount.com

gcloud config list
[component_manager]
disable_update_check = true
[core]
account = {{KF_NAME}}-admin@{{PROJECT}}.iam.gserviceaccount.com
disable_usage_reporting = true
project = {{PROJECT}}
[metrics]
environment = github_docker_image
```

Also deployment status for `activator`, `autoscaler`, `autoscaler-hpa`, `controller` is ` Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"`. Also there is discussion here `https://groups.google.com/forum/#!topic/kubeflow-discuss/1V4w7OHoML0` related issue that I faced

**Environment:**

- kfctl version: (use `kfctl version`): 0.7.0
- Kubernetes platform: GKE
- Kubernetes version: (use `kubectl version`): 1.14.8-gke.17

**Comment by lluunn** [comment]
I tried the [instructions](https://www.kubeflow.org/docs/gke/private-clusters/#deploy-kubeflow-with-private-gke) before step 11 (updated image to gcr). So some images cannot be pulled, but cloudendpoint should be fine.
But got different error:
- when visiting FQDN, I got ERR_NAME_NOT_RESOLVED, server IP address could not be found. I think this means cloud endpoint is not functioning.
- I can see a cloudendpoint resource, but the cloudendpoint pod logs seems not doing anything:
  ```
  2019/12/03 19:53:47 [INFO] Fetching Project ID from Compute metadata API...
  2019/12/03 19:53:47 [INFO] Fetching Numeric Project ID from Compute metadata API...
  2019/12/03 19:53:47 [INFO] Instantiating GCE client...
  2019/12/03 19:53:47 [INFO] Instantiating Google Cloud Service Management Client...
  2019/12/03 19:53:47 [INFO] Initialized controller on port 80
  ```

Also, many istio images cannot be pulled, I think we need a different manifests:
```
NAME                                      READY   STATUS              RESTARTS   AGE
backend-updater-0                         1/1     Running             0          72m
grafana-67c69bb567-kpd28                  0/1     ImagePullBackOff    0          73m
iap-enabler-7f87598576-vwzdm              1/1     Running             0          72m
istio-citadel-67697b6697-4ckxn            0/1     ImagePullBackOff    0          73m
istio-cleanup-secrets-1.1.6-b68kf         0/1     ImagePullBackOff    0          73m
istio-egressgateway-7dbbb87698-k8xt5      0/1     ImagePullBackOff    0          73m
istio-galley-7bffd57ff4-lndht             0/1     ContainerCreating   0          73m
istio-grafana-post-install-1.1.6-cfzr7    0/1     ImagePullBackOff    0          73m
istio-ingressgateway-565b894b5f-dsqn7     0/1     ImagePullBackOff    0          73m
istio-pilot-6dd5b8f74c-5bspb              0/2     ImagePullBackOff    0          73m
istio-policy-7f8bb87857-xj7xw             0/2     ImagePullBackOff    0          73m
istio-security-post-install-1.1.6-2b42f   0/1     ImagePullBackOff    0          73m
istio-sidecar-injector-fd5875568-xlth7    0/1     ContainerCreating   0          73m
istio-telemetry-8759dc6b7-5tvzh           0/2     ImagePullBackOff    0          73m
istio-tracing-5d8f57c8ff-hd4z6            0/1     ImagePullBackOff    0          73m
kiali-d4d886dd7-t7wzw                     0/1     ImagePullBackOff    0          73m
prometheus-d8d46c5b5-842n7                0/1     ContainerCreating   0          73m
whoami-app-cbdf7bf6f-chdqx                1/1     Running             0          72m
```

**Comment by lluunn** [comment]
The cloudendpoint pod logs in a normal kubeflow cluster:
```
2019/12/03 22:21:37 [INFO] Fetching Project ID from Compute metadata API...
2019/12/03 22:21:37 [INFO] Fetching Numeric Project ID from Compute metadata API...
2019/12/03 22:21:37 [INFO] Instantiating GCE client...
2019/12/03 22:21:37 [INFO] Instantiating Google Cloud Service Management Client...
2019/12/03 22:21:37 [INFO] Initialized controller on port 80
2019/12/03 22:21:44 [DEBUG][kf1203] Changed because parent sig different
2019/12/03 22:21:44 [DEBUG][kf1203] Changed because ingress target IP changed
2019/12/03 22:21:44 [INFO][kf1203] Service does not yet exist, creating: kf1203.endpoints.kai-test2.cloud.goog
2019/12/03 22:21:46 [INFO][kf1203] Current state: ENDPOINT_CREATE_PENDING
2019/12/03 22:21:46 [INFO][kf1203] Create pending
2019/12/03 22:21:46 [INFO][kf1203] Waiting for Endpoint creation: kf1203.endpoints.kai-test2.cloud.goog
2019/12/03 22:21:47 [INFO][kf1203] Create pending
2019/12/03 22:21:47 [INFO][kf1203] Waiting for Endpoint creation: kf1203.endpoints.kai-test2.cloud.goog
...
```

**Comment by lluunn** [comment]
Since the istio-ingressgateway cannot be pulled, I tried using GKE's istio add-on.
This can be added after cluster created: https://cloud.google.com/istio/docs/istio-on-gke/installing#adding_istio_on_gke_to_an_existing_cluster

After this, I think the certificate works. Now my error when visiting FQDN is: Origin authentication failed.

I think the problem is iap-enabler, logs:
```
node port is 31462
BACKEND_ID=871584170915856936
+ NODE_PORT=31462
+ echo 'node port is 31462'
+ [[ -z k8s-be-31380--45316dca55a0f388 ]]
+ [[ -z 871584170915856936 ]]
+ echo BACKEND_ID=871584170915856936
+ JWT_AUDIENCE=/projects/711890160434/global/backendServices/871584170915856936
patch JWT audience: /projects/711890160434/global/backendServices/87158417091585693
```
It gets that the node port should be 31462 (not the default one 31380 that we always pick), but it seems to get the id of a wrong backendservice. 
I think we need to cp https://github.com/kubeflow/manifests/pull/573 to 0.7

**Comment by lluunn** [comment]
For some reason my IAP was turned off. I enabled it again via console https://console.cloud.google.com/security/iap?_ga=2.216801814.-1643724808.1565303314, and now I can see the kubeflow dashboard

**Comment by jlewi** [comment]
Thanks @lluunn should we update the instructions
https://www.kubeflow.org/docs/gke/private-clusters/

Can we add a banner to the page similar to the one on the upgrade page indicating that upgrades are
alpha support?
https://github.com/kubeflow/website/blob/master/content/docs/upgrading/upgrade.md

Related: kubeflow/kubeflow#3082 - Document use of shared VPC

**Comment by jlewi** [comment]
Closing this as a duplicate of  kubeflow/kubeflow#3650 which is tracking installing Kubeflow on private GKE.

Duplicate of kubeflow/kubeflow#3650

Filed kubeflow/website#1542 to update the docs with a banner indicating Alpha support.

**Comment by joepeskett** [comment]
I'm having the same issue as described by the original post with both v0.7.1 and v1.0.0 - was there a solution found or a reason for this issue? Can see the @lluunn did not reproduce the issue with cloud-endpoints.
