### ISSUE TITLE
Will the multi-tenant setup with Istio interfere with other deployments running the cluster

### ISSUE THREAD

**Issue by nsriram13** [kubeflow/kubeflow#4530]
/kind question

I want to try out the multi-tenant auth-enabled Kubeflow installation setup as described [here](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/). I have a dev cluster where I have other deployments and we use nginx Ingress controller with an AWS load balancer for routing for those deployments. I see that Kubeflow uses Istio for all the routing and requires that we install Istio on the cluster.

**Question:**
Will installing Kubeflow with Istio cause the existing routing mechanisms to fail? Some example scenarios that I am thinking of:
* will Envoy sidecar proxy to be injected into every pod in the cluster or can it somehow be restricted to just the namespaces and pods associated with Kubeflow. 
* Can the same load balancer be used to talk to 2 ingress controllers?

My worry is that installing Istio will break our other apps that use nginx ingress controller. Anybody has success using both - is this a common pattern?

**Comment by jlewi** [comment]
You can configure ISTIO to not do sidecar injection by default in a namespace and only do sidecar injection if a namespace has an appropriate label.

More info in the docs e.g.
https://istio.io/docs/ops/setup/injection-concepts/

**Comment by nsriram13** [comment]
Thanks @jlewi . The ‘namespaceSelector’ seems like a good solution here. Will experiment some and report back what we find.

**Comment by nrchakradhar** [comment]
Any thoughts on ingress controller which is Ngnix?
