### ISSUE TITLE
Support any OpenID provider for multi-user feature

### ISSUE THREAD

**Issue by samos123** [kubeflow/kubeflow#4558]
/kind feature

**Why you need this feature:**
Enterprise already has Ping Identity as the identity provider and we wish to re-use that without having to introduce yet another component, Dex.

**Describe the solution you'd like:**
Ability to configure an OpenID provider such as Ping without using Dex with the multi-user feature

**Comment by yanniszark** [comment]
Hi @samos123!
Kubeflow is an OIDC-compliant client (oidc-authservice) so you should be able to set it up however you want.
You can also comment out Dex from the KfDef file in order to skip installing it.

**Comment by samos123** [comment]
Thanks @yanniszark will close the issue for now.

**Comment by lalithvaka** [comment]
I have tried integrating with Ping and am running into issues as following.
My authservice log showing as follows

➜ kubectl logs authservice-0 -n istio-system                                  
time="2020-03-09T22:08:39Z" level=info msg="Starting readiness probe at 8081"
time="2020-03-09T22:08:39Z" level=info msg="No  USERID_TOKEN_HEADER  specified, using 'kubeflow-userid-token' as default."
time="2020-03-09T22:08:39Z" level=info msg="No  SERVER_HOSTNAME  specified, using '' as default."
time="2020-03-09T22:08:39Z" level=info msg="No  SERVER_PORT  specified, using '8080' as default."
time="2020-03-09T22:08:39Z" level=info msg="No  SESSION_MAX_AGE  specified, using '86400' as default."
time="2020-03-09T22:08:39Z" level=info msg="Starting web server at :8080"
time="2020-03-09T22:08:40Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: 404 Not Found: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /.well-known/openid-configuration was not found on this server.</p>\n</body></html>\n"

I have updated the params.env under oidc-authservice/base folder.
Not sure if am missing anything else to configure.

**Comment by yanniszark** [comment]
Hi @lalithvaka! Can you open a new issue since this one is closed.
It sounds like a bad setup of the oidc-authservice client.
