### ISSUE TITLE
kfctl is not correctly evaluating repos.uri when using file://

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4560]
/kind bug

I'm attempting to install a private 0.7 cluster in a GCP project that requires access to the internet through our corporate proxy.  This is very similar to an On-Prem installation.  I downloaded the following;

```
https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
https://github.com/kubeflow/manifests/archive/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz
```

I modified `kfctl_gcp_basic_auth.0.7.0.yaml` and changed the repos: to reflect the below;

```
  repos:
  - name: manifests
    uri: file://home/jeff_fogarty_usbank_com/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz
  version: v0.7.0
```

This returned the error:

```
Code 500 with message: could not sync cache. Error:  (kubeflow.error): Code 400 with message: couldn't download URI file://home/jeff_fogarty_usbank_com/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz Error source path error: stat /jeff_fogarty_usbank_com/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz: no such file or directory
```

I expected kfctl to file the tar.gz file.

I solved this by modifying `kfctl_gcp_basic_auth.0.7.0.yaml`  as below;

```
repos:
  - name: manifests
    uri: file://home/home/jeff_fogarty_usbank_com/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz
```

- Kubeflow version: 0.7.0
- kfctl version: 0.7.0
- Kubernetes platform: kubectl on gcp
- Kubernetes version: 1.17:
- OS: NAME="Ubuntu" VERSION="18.04.3 LTS (Bionic Beaver)"

**Comment by gabrielwen** [comment]
/cc @zhenghuiwang 
for oncall

**Comment by zhenghuiwang** [comment]
@jtfogarty the general schema of URL is 
```
[scheme:][//[userinfo@]host][/]path
```
based on Golang URL representation https://golang.org/pkg/net/url/#URL

If you have `//`, then the first part after `//` is treated as host name and get removed.(That's why redundant`/home/home` works)

Right path would be `file:/home/jeff_fogarty_usbank_com/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz`

**Comment by zhenghuiwang** [comment]
Feel free to reopen it if you still see problems.
