### ISSUE TITLE
kfctl is not expecting all subdirectories in manifest tar file

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4561]
/kind bug

After the steps in #4560 with the fix, I was able to run but with the below error;

```
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.error): Code 400 with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /home/jeff_fogarty_usbank_com/.cache/manifests/gcp/deployment_manager_configs/cluster.jinja to /home/jeff_fogarty_usbank_com/gcp_config/cluster.jinja using repo local path /home/jeff_fogarty_usbank_com/.cache/manifests Error cannot open input for copying: open /home/jeff_fogarty_usbank_com/.cache/manifests/gcp/deployment_manager_configs/cluster.jinja: no such file or directory
```
the issue is that the gcp directory is not under `/home/jeff_fogarty_usbank_com/.cache/manifests` 
but under 
`home/jeff_fogarty_usbank_com/.cache/manifests/manifests-c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38`

I expected the proper path to be found

**Environment:**
- Kubeflow version: 0.7.0
- kfctl version: 0.7.0
- Kubernetes platform: kubectl on gcp
- Kubernetes version: 1.17:
- OS: NAME="Ubuntu" VERSION="18.04.3 LTS (Bionic Beaver)"

**Comment by gabrielwen** [comment]
/cc @zhenghuiwang 
for oncall

**Comment by zhenghuiwang** [comment]
I was able to reproduce it. Seems the `.cache` doesn't use the same manifest file name as set in the `manifest.name` consistently.

@gabrielwen @kkasravi can you take a look?

**Comment by gabrielwen** [comment]
the root cause is because when URI is `file:/`, we assume it points to a directory and have symlink to it.  it's not true when URI is a file, in which we will extract it to a new directory.
