### ISSUE TITLE
Jupyter notebook launch in kubeflow-created profile/namespace fails on Openshift 4.x

### ISSUE THREAD

**Issue by crobby** [kubeflow/kubeflow#4566]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried launching a Jupyter notebook in a profile created by kubeflow

**What did you expect to happen:**
The notebook pod shout start

**Anything else you would like to add:**
It looks like kubeflow profiles add a label to the profile/namespace of "istio-injection: enabled", which eventually leads to an istio-init container trying to come up at launch-time.  That istio-init container fails because it's trying to do something with iptables, which is not in play for Openshift 4.x (I'm using 4.2).

If I remove that label from the namespace, the Jupyter pod does come up and is functional.

**Environment:**
Openshift 4.2

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

Kubeflow version:  v0.7.0

Client Version: 4.3.0-0.okd-2019-11-15-182656
Server Version: 4.2.8
Kubernetes Version: v1.14.6+dea7fb9

**Comment by jlewi** [comment]
@animeshsingh @pdmack do you have someone who could look into this?

**Comment by pdmack** [comment]
#3935

**Comment by animeshsingh** [comment]
@jlewi will look into it

**Comment by jlewi** [comment]
@animeshsingh is this issue still relevant or should we close it?

**Comment by crobby** [comment]
I have not tried this with 1.0 yet, but I suspect it is likely to still be an issue.
