### ISSUE TITLE
Display available system resources and namespace quotas to end users

### ISSUE THREAD

**Issue by supertetelman** [kubeflow/kubeflow#4567]
/kind feature

I works with data scientists who like to run relatively large workloads. Depending on which Kubeflow instance they are running on the nodes will have different maximum hardware availability (i.e. the largest GPU node might have 2 GPUs and a 4 GPU job will never execute, but it would execute in a different cluster). Similarly, if quotas/limits have been set for a namespace the data scientists will run into similar issues.

There is currently no way for an end-user to see the hardware limits or software limits that will impact them.

It would be useful to add a new "Resource" section that displays some of the following:

- GPU/CPU/Memory/Other resources of the nodes they have access to
- Quota/limits placed on their current namespace
-*Optionally, it might be useful to show the current usage for the nodes and namespaces

While this removes the abstraction of the hardware/DevOps components from the data scientists, I believe that giving visibilty into the resource availability would enable end-users to get better system utilization.

There may be an issue in environments where auto-provisioning / cloud scaling is enabled. I don't think this needs to be implemented in real-time. Giving to the hour information would be sufficient for most of my users.

**Comment by HassanOuda** [comment]
Can we reopen this? At least, maybe let us know where in the code/yaml files we can change to assign default resource quotas for user namespaces as a quick workaround. Thanks.

**Comment by dwojcik92** [comment]
Is there any solution to this problem? I would like to know how many GPUs are available in cluster before starting Notebook. Are there any workarounds?
