### ISSUE TITLE
Kubeflow should allow deployment and management through Operator(s)

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kubeflow#4570]
/kind feature

**Why you need this feature:**
Operators help deploy, monitor and manage the lifecycle of applications deployed on Kubernetes.  And OpenShift. Especially from OpenShift Container Platform 4.1 and onward, with the Operator Lifecycle Manager being installed by default, it just takes several clicks to install an operator and managed applications. Operators can be published to operatorhub.io either certified or not.

**Describe the solution you'd like:**
To leverage the benefits of frameworks and tooling around Operators, we have created a Kubeflow Operator to deploy the Kubeflow framework on OpenShift Container Platform and manage the lifecycle of deployed Kubeflow components. We would like to collaborate with the community to enhance and harden it towards its eventual destination. 

We would like a repo in Kubeflow org, named kubeflow-operator, and enhance it on similar lines as the knative operators in community.

https://github.com/knative/serving-operator
https://github.com/knative/eventing-operator

**Anything else you would like to add:**
Initial design doc here
https://docs.google.com/document/d/1vNBZOM-gDMpwTbhx0EDU6lDpyUjc7vhT3bdOWWCRjdk/edit?usp=sharing

**Comment by jlewi** [comment]
Thanks; I left some comments in the doc.

**Comment by jlewi** [comment]
@animeshsingh is there code publicly available already if so can you share a link?

**Comment by jlewi** [comment]
@animeshsingh could you provide an update?  Should we have a follow up discussion at the next community meeting?

**Comment by animeshsingh** [comment]
@jlewi Team is back from break today. Will follow through this week, and let's bring it up in next week's meeting

**Comment by animeshsingh** [comment]
First PR on this issues is in kfctl repo now
https://github.com/kubeflow/kfctl/pull/189

cc @jlewi

**Comment by animeshsingh** [comment]
2nd PR to register the Operator to OLM is being worked on here
https://github.com/kubeflow/kfctl/pull/208

**Comment by jlewi** [comment]
@animeshsingh Can we close this issue?
