### ISSUE TITLE
Can't deploy tf job to kubernetes cluster: "No match for kind TFJob"

### ISSUE THREAD

**Issue by plaffitte** [kubeflow/kubeflow#4571]
/kind bug

**What steps did you take and what happened:**
I ran the command `kubectl apply -f test.yaml`
Where test.yaml is taking from the examples in the doc and looks like this:

`apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tfjob
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: gcr.io/your-project/your-image
            command:
              - python
              - -m
              - trainer.task
              - --batch_size=32
              - --training_steps=1000
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: gcr.io/your-project/your-image
            command:
              - python
              - -m
              - trainer.task
              - --batch_size=32
              - --training_steps=1000`

**What did you expect to happen:**
I expected the job to be deployed on the kubernetes cluster.
Instead, I get the following error:

`error: unable to recognize "test.yaml": no matches for kind "TFJob" in version "kubeflow.org/v1"`

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 
- kfctl version: 0.7.0
- Kubernetes platform: `AWS`
- Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): MacOs High Sierra

**Comment by yeya24** [comment]
Seems the TFJob CRD is not installed.

**Comment by plaffitte** [comment]
@yeya24 Yes that was the issue... Thanks
