### ISSUE TITLE
Using GPU for 1 component of the pipeline

### ISSUE THREAD

**Issue by sid027** [kubeflow/kubeflow#4572]
I would like to use GPU for the `training` step of my kubeflow pipeline.

![image](https://user-images.githubusercontent.com/7779466/70794636-5d905600-1d9e-11ea-99ca-99b30baa9d5f.png)

I create a containerOP for this component `train = dsl.ContainerOp(
        name="training",
        image=train_image
    )`
then `train.set_gpu_limit("1")`

*Note: I use GCP*

**Question:**
I can see that the kubeflow cluster starts a new GPU pool with a GPU node. However, there is a problem in pulling the `train_image`. Is there a permission issue here? How can I resolve it?

*NOTE: There is no issue when I leave out `train.set_gpu_limit("1")` from the pipeline*

**Comment by jnmclarty** [comment]
Can you post or link to your pipeline's python + any yaml?

**Comment by yanniszark** [comment]
Hi @sid027, this question seems better suited for the pipelines repo (https://github.com/kubeflow/pipelines)
