### ISSUE TITLE
Clone Interactive Jupyter Notbook

### ISSUE THREAD

**Issue by supertetelman** [kubeflow/kubeflow#4573]
/kind feature

**Issue**
Many times when I deploy a notebook I would like to deploy another one that is similar. Sometimes this is because the one I launched had an error, sometimes I want more/less resources, and sometimes I would like to bump the version of the Docker image.

**Recommendation**
I would like to see a clone notebook button on the Notebooks page that pre-populates the create notebook page with all the same parameters.

**Comment by jlewi** [comment]
Downgrading to P2 because I don't think this is critical for 1.0.

**Comment by jbottum** [comment]
@supertetelman Hey Adam, is this still a requirement that your user/customer wants?

**Comment by supertetelman** [comment]
I've still had people asking for this, yes.
