### ISSUE TITLE
a problem for jupyterhub account management

### ISSUE THREAD

**Issue by seanlin1326** [kubeflow/kubeflow#4575]
I am a beginer for manage account  by jupyterhub
I have to manage 62 acount for  62 student for a ai lesson
to do that I have to spawn 62 account server
this is a hard job
![P_20191216_142513_vHDR_Auto](https://user-images.githubusercontent.com/58818014/70899972-c4c63880-2032-11ea-89cc-f62d374b644f.jpg)

<img width="849" alt="問題github " src="https://user-images.githubusercontent.com/58818014/70899894-9ba5a800-2032-11ea-8649-46d86ad91db6.PNG">

and this is a big problem
I spawn this account server (account pod) will destroy and expired after I spawning them one hour later
it mean if this lesson start from 6 pm
I can not spawn them at 1 pm ，because they will destroy themself at 3 pm
I must to spawn them at 5:30 pm，it is very unconvenient
I want to control this server(pod) can survive more long
and I can spawn the 62 pod automatic
last week , my university's power cut
and  the acount's passward I've set up were lost
and I have to set up passward again
have a way to automatically set up passward(jupyterhub account passward)

**Comment by jbottum** [comment]
Hi, What version of Kubeflow are you running ?   Could you potentially upgrade to 0.7 ?

**Comment by jlewi** [comment]
JupyterHub is no longer part of kubeflow. It was removed in 0.5 or 0.6.
