### ISSUE TITLE
Add licenses for dependencies in TF operator images

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#4579]
Related to https://github.com/kubeflow/testing/issues/539

Need to add all license content for thrid-party dependencies in TF operator images.

**Comment by jlewi** [comment]
@krishnadurai is working on converting to a distroless image in kubeflow/tf-operator#1124
That might cut down on number of dependencies.

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/tf-operator/pull/1127 is merged
