### ISSUE TITLE
Add licenses for dependencies in Central Dashboard images

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#4580]
Related to kubeflow/testing#539

Need to add all license content for thrid-party dependencies in central dashboard images.

**Comment by kunmingg** [comment]
@avdaredevil 
Hi AP, do you have time to pick it up? Otherwise I can take care.

**Comment by jlewi** [comment]
@kunmingg @avdaredevil any update?

**Comment by jlewi** [comment]
@zhenghuiwang @kunmingg @avdaredevil any update on this? Have we made progress with NodeJS?

**Comment by zhenghuiwang** [comment]
Fixed by https://github.com/kubeflow/kubeflow/pull/4703
