### ISSUE TITLE
Pulling images from private google container registry with kubeflow on minikube.

### ISSUE THREAD

**Issue by fedeesku** [kubeflow/kubeflow#4584]
We are having trouble giving a container within a pipeline uploaded to Kubeflow access to a private custom docker image stored in a google container registry. We are running the default kubeflow on top of a kubernetes cluster run on minikube. Can someone help us understand how to add the access token/service account to the Kubeflow deployment? We have read a couple of docs that achieve this on a custom Kubernetes deployment but not on a Kubeflow deployment.

The error we get when running the pipeline on Kubeflow is:

**This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image**

This is a section of the pipeline code that calls the image.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/23128279/70963256-f0a6e580-2055-11ea-9109-d68cabd5a766.png)

Thank you!!

**Comment by DontWorry33** [comment]
You could try setting the image pull secret. The way I've been doing it is by adding this to my pipeline:

`dsl.get_pipeline_conf().set_image_pull_secrets([client.V1LocalObjectReference(name="regcred")])`

where client is the kubernetes client and regcred is the kubernetes secret created like this:

`kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
`

Also make sure the secret is in the correct namespace. There might be a better way to do this that i'm unaware of but this works for me to pull images from any private container registry (not just gcr)

**Comment by jlewi** [comment]
@fedeesku did that resolve the issue for you? You might also want to check out this doc from HeptIO
http://docs.heptio.com/content/private-registries/pr-gcr.html

**Comment by fedeesku1** [comment]
I apologize for the delay.  This solved my issue. With the default set up with kubeflow, the namespace where everything is created is called 'kubeflow'. Therefore to solve this issue as you mentioned, I added "--namespace kubeflow" to the command that creates the secret key.
