### ISSUE TITLE
Profile Plugins: A property of the Profile CRD or the controller?

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4588]
/kind bug

While working a bit on the profile-controller and the new plugin model, we realized that Plugins should be a property of the profile-controller and not of the individual Profile.

Consider what happens now:
1. Plain Profile is created by KFAM.
2. Profile-controller patches the spec of the Profile with the plugins that are enabled in the controller.

We observe the following antipatterns in the current behavior of the Profile Controller:
* A controller edits the spec of an Object. Controllers should edit status and only users should edit spec.
* The information is duplicated over all Profiles, when it could just be present in the profile-controller configuration. Profiles now aren't portable, but tied to the configuration of the current cluster.

We would like to propose the following changes:
* Plugins are a property of the profile-controller and express policy for what a Profile will contain. As such, they should be declared once as configuration of the profile-controller (the whole Plugins array should be fed to the profile controller as configuration, eg via a ConfigMap).
* For exposing what Plugins were used for the reconciliation of a Profile, we can use conditions in status.

/cc @kunmingg @jlewi @vkoukis

**Comment by jlewi** [comment]
@yanniszark Can you explain this issue with some examples?

Here's an example from GCP

```
apiVersion: kubeflow.org/v1beta1
kind: Profile
spec:
  plugins:
  - kind: WorkloadIdentity
    spec:
      gcpServiceAccount: ${SANAME}@${PROJECT}.iam.gserviceaccount.com
```

So in this case the user who creates the profile is specifying what GCP service account to be used with the newly created profile.

Only the creator of the profile not the cluster admin knows what service account they want to use.

So how would the profile controller inject the plugin?

What are the use cases for plugins that you are trying to cover?

**Comment by jlewi** [comment]
@yanniszark could you please give this issue a more descriptive title?

**Comment by yanniszark** [comment]
@jlewi I had not realized that in the case of the GCP Plugin, you want to get the user's input.
In that case, having that setting appear in the Profile spec is desirable.
However, I believe this options is not exposed yet in the central dashboard.

The other mentioned issues are:
* The Profile controller edits the Profile spec. This should happen in a mutating admission webhook, as controllers should not edit the Object spec.
* The Profile controller should note what plugins it has applied in the Profile status.

How about we open issues for those and close this one, as the main concern was the design of the Plugin model?

**Comment by yanniszark** [comment]
> Regarding the controller editing the profile spec; is the profile controller just filling in default values? Isn't it quite common for controllers to fill in defaults for the spec?

@jlewi the accepted technique for defaulting is to use Mutating Admission Webhooks.
eg kubebuilder docs instruct using a mutating admission controller for defaulting (https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html)

**Comment by jlewi** [comment]
@yanniszark I'm fine with using webhooks. Its not clear from the docs whether its "a way" of doing things or "the recommended ways".

Replacing the defaulting with a webhook seems like low priority but if someone wants to do it; sounds good to me.

What work is needed to close this issue out?

**Comment by yanniszark** [comment]
I opened this thread to track showing applied plugins in status:
https://github.com/kubeflow/kubeflow/issues/5001

I don't think it's necessary to open a thread for a mutating admission controller now.

/close
