### ISSUE TITLE
Convert all Kubeflow Container images to use distroless image as its base image

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4590]
/kind feature

**Why you need this feature:**
The current images being used by Kubeflow include:

- Alpine: Known inconsistency in security practices
- RHEL: UBI based images have license concerns
- Debian: Jessie is EOL in 2020
- Ubuntu: Not many concerns

**Describe the solution you'd like:**

A good way to approach this problem is to have a common base image with no known CVEs pre-installed to reduce the number of CVEs in the final image generated for applications.

**Anything else you would like to add:**
Explore the possibility of using distro-less images.

/cc @elviraux @swiftdiaries 

Relates to #4589

**Comment by nrchakradhar** [comment]
@krishnadurai 
How about using centos base image for all?
https://hub.docker.com/_/centos

**Comment by krishnadurai** [comment]
@nrchakradhar Thanks for suggesting. I'm exploring distro-less images right now since they might not contain the additional weight of the OS.

**Comment by jlewi** [comment]
Based on the docs 
https://github.com/GoogleContainerTools/distroless/tree/master/base
https://github.com/GoogleContainerTools/distroless#base-operating-system

I think we want to use the "static:debian10" images as base images 
unless we need glibc, libssl, or openssl. If we need the latter then we should use "base:debian10"

**Comment by krishnadurai** [comment]
@jlewi it seems we require libc for tf-operator image since it is using Runtime C dependencies.

**Comment by jlewi** [comment]
@krishnadurai what is the remaining work before we close this out?

**Comment by krishnadurai** [comment]
@jlewi 
@jtfogarty has made a list of images being used within Kubeflow. We are planning to convert all these images to use distroless.

@jtfogarty could you please share the sheet tracking this effort with the community in this issue?

**Comment by jtfogarty** [comment]
https://docs.google.com/spreadsheets/d/1ijWIyjGQpDy68-vjBmLyFY0U1oGCT--A0nVGgzLGDhU/edit?usp=sharing

**Comment by jlewi** [comment]
Are we using this issue to track migrating our images to distroless images? If so should we change the title of this issue?

**Comment by krishnadurai** [comment]
@jlewi I've changed the title as suggested.

**Comment by animeshsingh** [comment]
@krishnadurai is there automation in place for these conversions? cc @adrian555

**Comment by krishnadurai** [comment]
@animeshsingh we are doing this manually.
I'm not sure how we could try this in an automated manner. Do you have anything in mind?

**Comment by jlewi** [comment]
@krishnadurai Any update on this?

**Comment by jbottum** [comment]
@krishnadurai @jtfogarty @elviraux We would like to include this in Kubeflow 1.1.   Will we have a delivery for this in Kubeflow 1.1?

**Comment by nrchakradhar** [comment]
@krishnadurai @@jtfogarty Can you please share your views about whether this will make it into 1.1 of kubeflow?

**Comment by krishnadurai** [comment]
Here's the latest vulnerability report:

https://bit.ly/2XVjRpt

cc @jtfogarty @jbottum

**Comment by 8bitmp3** [comment]
@krishnadurai is this CVE/VULNDB list for Kubeflow maintained or it's just a snapshot? Thanks

**Comment by krishnadurai** [comment]
@8bitmp3 this is a snapshot of the day I've posted the comment on.

**Comment by vivekanandpoojari** [comment]
@krishnadurai I wanted to get in touch with you regarding the experience of moving a c++ based containerised application to distroless. My application is currently based on centos and quite heavy. ubi is one option but wanted to consider distroless for a rhel based c++ application.

**Comment by jlewi** [comment]
@krishnadurai What is the remaining work that this issue is tracking? Can we file more narrowly scoped issues and then close this in favor of them?
