### ISSUE TITLE
Environment variable TF_CONFIG is not set in the job's pod for non distributed tfjob.

### ISSUE THREAD

**Issue by md-shabbir** [kubeflow/kubeflow#4591]
/kind bug

In kubeflow 0.7, Env **TF_CONFIG** is **not** set in the job's pod for non distributed tfjobs. However in kubeflow 0.6, it was set for both distributed and non distributed tfjobs.

I am not sure it is a kind of bug or it was done intentionally.

**Environment:**

- Kubeflow version: 0.7.0
- kfctl version: v0.7.0
- Kubernetes version: v1.15.3
- OS: Ubuntu 18.04.3 LTS (Bionic Beaver)

**Comment by jlewi** [comment]
@johnugeorge @richardsliu do you know if this was intentional?

**Comment by johnugeorge** [comment]
Yes. It was merged recently 
See https://github.com/kubeflow/tf-operator/pull/1080

**Comment by jlewi** [comment]
Closing this as working as intended.
