### ISSUE TITLE
Eliminating unnecessary artefacts in container images used by Kubeflow

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4594]
/kind feature

**Why you need this feature:**
Some of the Kubeflow images, for e.g. Metadata:v0.1.10, contain bazel build software, git repos etc. We need to reduce the size of images by stripping off unnecessary layers in images and artefacts generated.

Release: v0.7.0

Relates to Issue: #4589

/assign
/cc @elviraux @swiftdiaries

**Comment by jlewi** [comment]
@krishnadurai should we break this up into issues about specific images so its easier to track the work?

**Comment by krishnadurai** [comment]
@jlewi Sure, I'll break this issue into specific images.
