### ISSUE TITLE
Jupyter Terminal Multiple Issues

### ISSUE THREAD

**Issue by o-vexler** [kubeflow/kubeflow#4596]
/kind bug

Hi guys! :)

**What steps did you take and what happened:**
The terminal feature in the Jupyter that is deployed with Kubeflow seems to not function properly- no auto-completion (tab), no up arrow (gibberish letters appear), no clear screen.

**What did you expect to happen:**
I actually checked that with a Jupyter version that I have deployed in GCP (unrelated to Kubeflow), and everything seems to be working there from the terminal- there is auto-completion, tabs etc...

**Anything else you would like to add:**
1. The commands `jupyter --version` and `jupyter notebook --version` produce the same output on both jupyters I have (Kubeflow's Jupyter, and my unrelated to Kubeflow Jupyter):
`jupyter notebook --version`: 5.7.8
`jupyter --version`: 4.4.0

2. When installing zsh with a custom image (based on the kubeflow base image) and running it- everything works great.

**Environment:**

- Kubeflow version: 0.6.2
- kfctl version: (use `kfctl version`): deployed from the UI.
- Kubernetes platform: (e.g. `minikube`): GCP
- Kubernetes version: (use `kubectl version`): Output of this command from within the notebook terminal: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

Thank you very much guys! I really hope that Kubeflow will continue to grow and get more advanced, This a great project.

Omer

**Comment by FaustineLi** [comment]
Just stating that I ran into this exact same bug in Kubeflow 0.7

**Comment by jlewi** [comment]
Did you try running `bash` to start a bash shell in the terminal? 

I'm not sure what the default is but I found bash to be much more usable.

Kubeflow's jupyter images are just the TensorFlow images.

You can always build your own jupyter image or take an existing jupyter image and make it worth Kubeflow in order to pick up the features you like
https://www.kubeflow.org/docs/notebooks/custom-notebook/
