### ISSUE TITLE
class ContainerOp(BaseOp):def container(self): no parent() function

### ISSUE THREAD

**Issue by wangzy0327** [kubeflow/kubeflow#4602]
@property
--
  | def container(self):
  | """`Container` object that represents the `container` property in
  | `io.argoproj.workflow.v1alpha1.Template`. Can be used to update the
  | container configurations.
  |  
  | Example:
  | import kfp.dsl as dsl
  | from kubernetes.client.models import V1EnvVar
  |  
  | @dsl.pipeline(name='example_pipeline')
  | def immediate_value_pipeline():
  | op1 = (dsl.ContainerOp(name='example', image='nginx:alpine')
  | .container
  | .add_env_variable(V1EnvVar(name='HOST', value='foo.bar'))
  | .add_env_variable(V1EnvVar(name='PORT', value='80'))
  | .parent # return the parent `ContainerOp`
  | )
  | """
  | return self._container

**Comment by jlewi** [comment]
I'm closing this issue because the initial issue report isn't very descriptive. @wangzy0327 if you are still having trouble could you please reopen this and provide more explanation of the problem or feature you are requesting.
