### ISSUE TITLE
Error: mysql_query failed: errno: 2006, error: MySQL server has gone away. Code: 13

### ISSUE THREAD

**Issue by VasiliShi** [kubeflow/kubeflow#4604]
kubernetes:1.14.1
os:centos
kubeflow:0.7

the error located in home->pipeline->artifacts:
error message:Error: mysql_query failed: errno: 2006, error: MySQL server has gone away. Code: 13

**Comment by louisvernon** [comment]
Related issue: https://github.com/kubeflow/metadata/issues/198

**Comment by VasiliShi** [comment]
done，just restarting metadata-grpc-deployment
