### ISSUE TITLE
GKE Kubeflow google cloud SDK "ERROR: timed out" 

### ISSUE THREAD

**Issue by rky0930** [kubeflow/kubeflow#4607]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Deploy Kubeflow 0.7 on GKE
2. Run a Pods(docker image google/cloud-sdk:273.0.0)
3. start to use google cloud SDK(gsutil) 
4. gsutil and glcoud start to timeout **few hours later**

The timeout error does not occur initially, but begins to occur after a few hours.
Once it occurs, the timeout error continues to occur.
I did some research and couldn't find a reason. If anyone knows the reason for this, please help.

**gsutil timeout message**
```
yoon@daangn-gpu2:~$ k exec -it -n kubeflow yoon-preprocess-test-pod /bin/bash
root@yoon-preprocess-test-pod:/app# gsutil ls gs://<GS_URL>
ERROR: (gsutil) timed out
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```
**gcloud timeout message**
```
yoon@daangn-gpu2:~$ k exec -it -n kubeflow yoon-preprocess-test-pod /bin/bash
root@yoon-preprocess-test-pod:/app# gcloud auth list
ERROR: (gcloud.auth.list) timed out
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

**What did you expect to happen:**
No problem using google cloud sdk

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: build version 0.7.0
- kfctl version: kfctl v0.7.0
- Kubernetes platform: GKE
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-gke.2", GitCommit:"0f206d1d3e361e1bfe7911e1e1c686bc9a1e0aa5", GitTreeState:"clean", BuildDate:"2019-11-25T19:35:58Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
- Inside Pod -
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial

**gsutil timeout image**
<img width="977" alt="gke-kubeflow-gstuil-timeout" src="https://user-images.githubusercontent.com/5013450/71547727-21d4cd80-29e7-11ea-82c2-1aecb8c0e452.png">
**glcoud timeout image**
<img width="980" alt="gke-kubeflow-glcoud-timeout" src="https://user-images.githubusercontent.com/5013450/71547700-c1de2700-29e6-11ea-967a-2c1a501bd30d.png">

**Comment by jlewi** [comment]
@rky0930 this doesn't look like a Kubeflow issue but a GCP or GKE issue.

Do you observe the same behavior on non-Kubeflow GKE clusters? Can you reproduce the behavior on a GKE cluster at the same version (1.14) with workload identity enabled?

We've observed some problems in the past with workload identity see kubeflow/kfctl#48.
Can you run the command 

```
kubectl -n kube-system get pods
```

To verify that the GKE metadata server pods are running and healthy.

**Comment by bruce3557** [comment]
I got the same issue: https://github.com/kubeflow/pipelines/issues/2773

I think that is GKE's issue. The workload identity is unstable now

**Comment by rky0930** [comment]
@jlewi Thanks for the answer. 
All pods in kube-system is running status now. 
```
yoon@daangn-gpu2:~$ kubectl -n kube-system get pods
NAME                                                           READY   STATUS    RESTARTS   AGE
event-exporter-v0.2.5-7df89f4b8f-66w5r                         2/2     Running   0          3d18h
fluentd-gcp-scaler-54ccb89d5-pnl7g                             1/1     Running   0          3d18h
fluentd-gcp-v3.1.1-7rmg9                                       2/2     Running   0          3d18h
fluentd-gcp-v3.1.1-mjc9f                                       2/2     Running   0          3d18h
gke-metadata-server-fv5jt                                      1/1     Running   0          3d18h
gke-metadata-server-mxhs2                                      1/1     Running   0          3d18h
heapster-7d456cb754-nmjv4                                      3/3     Running   0          3d18h
kube-dns-5877696fb4-qmmvp                                      4/4     Running   0          3d18h
kube-dns-5877696fb4-sdlbh                                      4/4     Running   0          3d18h
kube-dns-autoscaler-85f8bdb54-gflsw                            1/1     Running   0          3d18h
kube-proxy-gke-kubeflow2-kubeflow2-cpu-pool-v1-755478a8-937x   1/1     Running   0          3d18h
kube-proxy-gke-kubeflow2-kubeflow2-cpu-pool-v1-755478a8-wszw   1/1     Running   0          3d18h
l7-default-backend-8f479dd9-prz7q                              1/1     Running   0          3d18h
metrics-server-v0.3.1-5c6fbf777-ctlqd                          2/2     Running   0          3d18h
netd-52zl5                                                     1/1     Running   0          3d18h
netd-lfvp4                                                     1/1     Running   0          3d18h
prometheus-to-sd-9f55j                                         2/2     Running   0          3d18h
prometheus-to-sd-hgk27                                         2/2     Running   0          3d18h
stackdriver-metadata-agent-cluster-level-6bf96696bf-st8g4      1/1     Running   0          3d18h
```
And I checked liveness of gke-metadata-server, I seem unstatble
```
    Liveness:     http-get http://127.0.0.1:54898/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
```

@bruce3557 Thanks for the answer. 
Looks like the same issue. Did you find a solution? 
Is binding the workload to a pipeline runner the solution?
I think I need to check more of the workload identity side.

**Comment by rky0930** [comment]
@bruce3557 Thanks for the answer. 
Looks like the same issue. Did you find a solution? 
Is binding the workload to a pipeline runner the solution?
I think I need to check more of the workload identity side.

**Comment by bruce3557** [comment]
@rky0930 
Binding workload identity just solved the pipeline issue.
But about timeout issue, we need to wait for GCP fixing that.

**Comment by jlewi** [comment]
@rky0930 can you provide the logs of the gke-metadata-server pods? You can use this script to fetch the logs.
https://github.com/jlewi/kubeflow-dev/blob/master/fetch_stackdriver_pod_logs.sh

**Comment by louisvernon** [comment]
We just filed a ticket with Google Support about this today. We see this problem on `1.15.4-gke.22` but not on `1.14.9-gke.2`. We are using workload identity.  The gke-metadata-server daemonset pods report:

```
getServiceAccountMetadata("workload-identity-test", "kubeflow-prod-user@myproject.iam.gserviceaccount.com"): surfaceable error (status 500, message "Unable to generate access token"): getFederatedToken("myproject.svc.id.goog", pod): Post https://securetoken.googleapis.com/v1/identitybindingtoken: context canceled
```
We are able to at least temporarily resolve the issue by cycling the gke-metadata-server daemonset pods.

**Comment by rky0930** [comment]
@jlewi I tried running the script, but there was no output. Maybe something is wrong. After that, I was unable to retry as I reinstalled the cluster.

**Comment by rky0930** [comment]
@louisvernon I fixed it by downgrading the cluster to version 1.14.8-gke.18. I will keep checking the tickets you have left and will upgrade the cluster later. Thanks.

**Comment by rky0930** [comment]
This problem is occurring again. Probably using version 1.14.8-gke.18 is not a workaround. I am currently resolving the problem by restarting the node's metadata-server temporarily.

**Comment by yantriks-edi-bice** [comment]
@rky0930 how do you downgrade? Can't seem to find where that is defined.

**Comment by rky0930** [comment]
@yantriks-edi-bice Oh sorry. I deleted and reinstalled the GKE cluster to downgrade.  I have not tried downgrading an existing cluster.

**Comment by rky0930** [comment]
Despite the downgrade GKE cluster, gcloud SDK "time out error" occurred again.. Finally, we disabled GKE metadata server option in the node pool. And it's working without error.

**Comment by Felihong** [comment]
Hey @rky0930 , not sure if this is a good idea if one wants to use `workload identity` as there is no request token can be used.

**Comment by rky0930** [comment]
I know GCP recommends using workload identities. But, there was no other way because of the error. Temporarily storing and using the service key in the kubernetes secret. Actually GKE Metadata server is in beta now, so I will use workload identities when it is released as GA.

**Comment by jlewi** [comment]
see https://cloud.google.com/kubernetes-engine/docs/release-notes#january_24_2020 for release notes about GKE versions to avoid with bugs in workload identity
see kubeflow/kubeflow#4693

The Kubeflow 0.7.1 and 1.0.0 configs are pinned to known good versions.

**Comment by Bobgy** [comment]
FYI, for anyone still hitting intermittent permission issues with GKE workload identity.

First, your GKE version should be one of the good versions mentioned in above comment.
Second, your clients should use latest google/cloud-sdk, version >=277.0.0

I verified intermittent timeouts go away with 1.14.8-gke.33 and google/cloud-sdk:279.0.0. Recommend upgrading language specific clients to latest version too.
