### ISSUE TITLE
External Minio Configuration

### ISSUE THREAD

**Issue by bearrito** [kubeflow/kubeflow#4611]
/kind question

**Question:**
Is it possible to configure an external Minio Server?

I have searched the project using - https://www.kubeflow.org/search/?q=minio

I only saw reference to the Minio server that is presumably configured by the Kubeflow install process. We already have a Multi-DC HA Minio system setup, I would like to use that instead. Is this possible?

**Comment by jbottum** [comment]
@cspavlou Hey Chris, any comments here ?
