### ISSUE TITLE
External Database Configuration

### ISSUE THREAD

**Issue by bearrito** [kubeflow/kubeflow#4612]
/kind question

**Question:**
Hello, I am trying to understand the exact requirement for MySQL use. 

I have found the following in the Katib project - https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/mysql/mysql.go

I also located https://github.com/kubeflow/metadata/blob/master/service/service.go but was unable to deduce what the DB requirements were.

This is related to my previous issue of https://github.com/kubeflow/kubeflow/issues/4611 of being able to use an external HA DB instead of a local one hosted in the cluster. My penultimate goal would be to use Kubeflow backed by an external Cockroach DB.

Is this a request that has been considered before and rejected?

Thanks and Happy New Year.

**Comment by andrewspiers** [comment]
This is a good question, is there any way to configure kubeflow to use an external mysql db?
