### ISSUE TITLE
Add licenses for dependencies in JupyterWeb App Image

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4620]
/kind feature

Related to https://github.com/kubeflow/testing/issues/539

Need to add all license content for thrid-party dependencies in JupyterWebApp image.

**Comment by zhenghuiwang** [comment]
Backend Go dependency licenses added here https://github.com/kubeflow/kubeflow/pull/4632

**Comment by jlewi** [comment]
@zhenghuiwang What work remains for this?

**Comment by zhenghuiwang** [comment]
The remaining work are adding licenses for Jupyter webapp NodeJS frontend to the docker image, since the image has both frontend and backend.
