### ISSUE TITLE
kfctl 0.7.1 -- both linux and darwin versions are linux?

### ISSUE THREAD

**Issue by wronk** [kubeflow/kubeflow#4629]
/kind bug
I believe both versions (linux and darwin) of 0.7.1 release are actually linux

Setting up a cluster using kfctl for v0.7.1 on mac (darwin version) results in an error:
`$ kfctl build -V -f ${CONFIG_URI}`
`-bash <home_dir>/.kfctl/kfctl: cannot execute binary file`

**What did you expect to happen:**
I expected `kfctl` to build the deployment files

**Anything else you would like to add:**
MD5 sums are the same for both the `linux` and `darwin` versions downloaded from [here](https://github.com/kubeflow/kubeflow/releases/tag/v0.7.1).
```
~/Downloads$ md5 kfctl_v0.7.1-0-ga627f74_darwin.tar.gz
MD5 (kfctl_v0.7.1-0-ga627f74_darwin.tar.gz) = eaa841bd0e38bb37f31cf3cc7e4c50a8
~/Downloads$ md5 kfctl_v0.7.1-0-ga627f74_linux.tar.gz
MD5 (kfctl_v0.7.1-0-ga627f74_linux.tar.gz) = eaa841bd0e38bb37f31cf3cc7e4c50a8
```

**Environment:**

- Kubeflow version: 0.7.1
- kfctl version: (use `kfctl version`): 0.7.1
- Kubernetes platform: GCP
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher"`
- OS (e.g. from `/etc/os-release`): macOS 10.15 (Catalina)

**Comment by jlewi** [comment]
kubeflow/kfctl#161 is the issue to fix the makefile.

/assign @richardsliu

**Comment by richardsliu** [comment]
Fixed by https://github.com/kubeflow/kfctl/pull/163.

**Comment by richardsliu** [comment]
New binaries published: https://github.com/kubeflow/kubeflow/releases/tag/v0.7.1
