### ISSUE TITLE
Pods "mysql"、"ml-pipeline"、"ml-pipeline-persistenceagent" are in status "CrashLoopBackOff".

### ISSUE THREAD

**Issue by jobvarkey** [kubeflow/kubeflow#4630]
Hello,
I installed Kubeflow v0.70 using kfctl_existing_arrikto config in on-prem multinode kuberntes v1.15.7 cluster running on Ubuntu 18.04.
These three Pods are in constant CrashLoopBackoff:
mysql
ml-pipeline
ml-pipeline-persistenceagent

Can someone please help to resolve this issue?

Thanks,
Job Varkey

**Comment by jobvarkey** [comment]
These are Pod logs:
kubectl logs -f -n kubeflow ml-pipeline-588b64fff-j7hjk
I0107 22:11:17.235107       1 client_manager.go:126] Initializing client manager
F0107 22:17:42.958380       1 error.go:296] dial tcp 10.97.35.125:3306: connect: connection refused

kubectl logs -f -n kubeflow ml-pipeline-persistenceagent-79ff896578-8n5vm
W0107 22:18:12.845412       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfi not work.
time="2020-01-07T22:20:43Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline cliening for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1beta1/healthz: dial tcp 10.101.2nnect: connection refused: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1bdial tcp 10.101.208.47:8888: connect: connection refused"

kubectl logs -f -n kubeflow mysql-6c9cb88c4d-8hq2l
2020-01-07 22:18:00+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.46-1debian9 started.
chown: changing ownership of '/var/lib/mysql/.snapshot': Read-only file system

**Comment by jobvarkey** [comment]
This issue was resolve by changing NFS version used for PV mount from 3 to 4.

**Comment by vaskokj** [comment]
@jobvarkey 

How/where did you change it from 3 to 4?

**Comment by jobvarkey** [comment]
In the /etc/fstab mount command for the NFS FS.

**Comment by vaskokj** [comment]
Thanks, but I guess your setup is different from mine (unless I'm misunderstanding something). 

I have my kubernetes cluster using the nfs-client kubernetes dynamic provisioner. 

Kubeflow creates the pvc and pv for me "automatically" and _should_ be mounting things automatically, but apparently they aren't. I'm getting very similar errors that you are 

```
$ kubectl logs -n kubeflow katib-mysql-dcf7dcbd5-djx45
2020-03-04 13:46:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian9 started.
2020-03-04 13:46:11+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-03-04 13:46:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian9 started.
mkdir: cannot create directory '/var/lib/mysql': Permission denied
```

```
$ kubectl logs -n kubeflow katib-db-manager-54b66f9f9d-d5dch
E0304 13:42:21.619878       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.23.201:3306: connect: connection refused
E0304 13:42:26.611773       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.23.201:3306: connect: connection refused
E0304 13:42:31.635879       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.233.23.201:3306: connect: connection refused
```

```
$ kubectl logs -n kubeflow metadata-db-65fb5b695d-656hw
mkdir: cannot create directory '/var/lib/mysql': Permission denied
```

I don't think I can control how things are mounted.

**Comment by jobvarkey** [comment]
I created a NFS client provisioner using the NFS v4 FS before installing kubeflow.
https://www.kubeflow.org/docs/other-guides/kubeflow-on-multinode-cluster/

**Comment by vaskokj** [comment]
@jobvarkey 

Hmmm, that does appear to be the same thing I've done (just went about it in a different way). I don't see in any of those configurations settings where you could change anything about the mount commands (nfs4 vs nfs3). I'm 100% positive that my actual NFS server is running only nfs4.
```
$ rpcinfo -t nfs1.example.com nfs 4
program 100003 version 4 ready and waiting
```

```
rpcinfo -t nfs1.example.com nfs 3
rpcinfo: RPC: Program/version mismatch; low version = 3, high version = 4
program 100003 version 3 is not available
```

**Comment by jobvarkey** [comment]
Sorry, not a nfs expert but your issue seems like related to some kind of nfs mismatch.
