### ISSUE TITLE
Disable authentication for certain URLs

### ISSUE THREAD

**Issue by webD97** [kubeflow/kubeflow#4634]
/kind question

**Question:**
We set up Kubeflow 0.7 using the arrikto config and it is running very well so far. Now we'd like to add some custom VirtualServices to the cluster which do not require authentication. Unfortunately, the istio-ingressgateway enforces authentication for our custom VirtualService as well. Is it possible to tell Istio to ignore authentication for certain URLs -- maybe even a wildcard?

**Comment by yanniszark** [comment]
Hi @webD97!

The Kubeflow v0.7 config uses the [oidc-authservice](https://github.com/arrikto/oidc-authservice) to authenticate requests at the Istio Gateway.
In the oidc-authservice config, we provide the `SKIP_AUTH_URI` option which you can use to whitelist paths by prefix.
Does this solve your issue?

**Comment by webD97** [comment]
Oh yes, you're right. I forgot about this env variable. It does work but now I also need to get rid of any RBAC checks. With authentication disabled, I always get `RBAC: access denied` when trying to access my own VirtualServices.

**Comment by webD97** [comment]
I disabled RBAC for these services in my RbacConfig for now. One last question regarding `SKIP_AUTH_URI`: Is there a way to disable auth per hostname instead of path?

**Comment by yanniszark** [comment]
@webD97 there is no such option yet.
I opened https://github.com/arrikto/oidc-authservice/issues/13 for the feature request.
