### ISSUE TITLE
kubeflow-0.7.0 profiles-deployment

### ISSUE THREAD

**Issue by zw39125432** [kubeflow/kubeflow#4635]
/kind question
image:gcr.io/kubeflow-images-public/profile-controller:v20190619-v0-219-gbd3daa8c-dirty-1ced0e
k8s  version:1.14

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
containers:
      - command:
        - /manager
        args:
        - "-userid-header"
        - $(userid-header)
        - "-userid-prefix"
        - $(userid-prefix)
        - "-workload-identity"
        - $(gcp-sa)
        image: gcr.io/kubeflow-images-public/profile-controller:v20190619-v0-219-gbd3daa8c-dirty-1ced0e
        imagePullPolicy: Always
        name: manager
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
installing Kubeflow on an existing Kubernetes cluster 

Deployment config:kfctl_k8s_istio.yaml

error:
flag provided but not defined : --workload-identity
Usage of /manager:
****

What do the following three parameters represent
$(userid-header) : 
$(userid-prefix):
$(gcp-sa):
In k8s dashboard, several parameters are empty

What is the role of profile controller in kubeflow and what is the image of startup failure？
How can I fix this problem？
**Question:**
[You can ask any question about this project.]

**Comment by jlewi** [comment]
@kunmingg do you want to answer these questions?

**Comment by hhji** [comment]
i also have the problem in kubeflow 1.0.2 + K8S 1.16.0, the issue have solution ?

**Comment by Jeffwan** [comment]
`-workload-identity` is used to authenticate pods for GCP services.  If you don't use it, please remove the fields. It might be manifest argument errors in earlier versions. Please try 1.1 and if there's still problems, let us know
