### ISSUE TITLE
Latest Kubeflow on Openshift 3.11

### ISSUE THREAD

**Issue by razumv** [kubeflow/kubeflow#4636]
/kind question

**Question:**
Hello! I have an openshift 3.11 with kube version 1.11. How can I deploy the latest version (0.7) of kubeflow with authorization? Is there anyone who managed to do this?

**Comment by yanniszark** [comment]
Hi @razumv!
I would suggest following this guide: https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/
In addition, check out the extra instructions needed here: https://github.com/marcredhat/crcdemos/blob/master/kubeflow/README.adoc

I have done some work on installing Kubeflow on Openshift with @marcredhat and we have successfully installed it.

**Comment by razumv** [comment]
Hello @yanniszark 
According to the information at https://www.kubeflow.org/docs/started/k8s/overview/, I concluded that kubeflow version 0.7 will only be on kube 1.14, 1.15.
Or all the same, for this https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/ guide I can put on Openshift 3.11 (kube 1.11).
So far, I have succeeded in installing only kubeflow 0.5, but ldap authorization is very important for me and I want 0.7 :)

**Comment by yanniszark** [comment]
Kubernetes 1.11 is a bit low.
You can always try to deploy and come back if you encounter any problems.
We have succeeded in deploying KF v0.7 in Openshift 4 with CRC, so you can also take a look at that for advice (https://github.com/marcredhat/crcdemos/blob/master/kubeflow/README.adoc).

/cc @pdmack

**Comment by vpavlin** [comment]
@razumv There is now a separate section for KF on OpenShift (https://www.kubeflow.org/docs/openshift/), but only target OpenShift 4.x.

OpenShift 3.11 is rather old at this point and I don't see anyone working on getting KF running there.
