### ISSUE TITLE
Vertical bar command

### ISSUE THREAD

**Issue by vovawed** [kubeflow/kubeflow#4638]
/kind question

**Question:**
I need to run (put this to `command` inside of `yaml` file):
```gsutil cat gs://bucket/obj.csv.gz | zcat |  gsutil cp - gs://bucket/obj.csv```

I was trying to separate them with comma but it didn't work.

**Comment by webD97** [comment]
That's a pipe symbol and I'm pretty sure it's a reserved symbol in YAML. Have you tried putting the command in quotes?

**Comment by vovawed** [comment]
> That's a pipe symbol and I'm pretty sure it's a reserved symbol in YAML. Have you tried putting the command in quotes?

Sure:
```
"gsutil", "cat", {inputValue: output}, "|", "zcat", "|", "gsutil", "cp", "-", {inputValue: input}
```

**Comment by webD97** [comment]
I think you need to call a shell to make pipes work, please try this one:

```yaml
command: "/bin/sh -c 'gsutil cat gs://bucket/obj.csv.gz | zcat | gsutil cp - gs://bucket/obj.csv'"
```
