### ISSUE TITLE
Create scheduled Pipeline job from the python SDK

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/kubeflow#4647]
/kind feature

**Why you need this feature:**
From the KFP Python SDK can start [pipeline runs](https://github.com/kubeflow/pipelines/blob/9a3a5c15cb9dd4b7cf8892efa3d138029b949b03/sdk/python/kfp/_client.py#L299) but it is not possible to create runs that should be recurring. However this could be don through the UI. In order to allow users to do this through code instead I suggest that this is added to the 
https://github.com/kubeflow/pipelines/blob/9a3a5c15cb9dd4b7cf8892efa3d138029b949b03/sdk/python/kfp/_client.py#L299

or a new function is created as 
```Python 
def schedule_pipelin(...): 
```

in https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py#L299

**Describe the solution you'd like:**
I would like there to be a option where the users could schedule a pipeline to run through the python SDK in order to avoid manual work using the UI. 

**Anything else you would like to add:**
I would be happy to make a contribution, and build this : )

**Comment by jbottum** [comment]
@jessiezcc Jesse - would the new looping functionality in 0.7 help on this request?

**Comment by NikeNano** [comment]
After checking the code base a bit and the swagger API I believe it could be implemented using the kfp_server_api utalising kfp_server_api.models.ApiTrigger() and kfp_server_api.models.api_job.ApiJob(). Happy for feedback or to know how to do it with the current API. :)

**Comment by NikeNano** [comment]
Friendly ping @jessiezcc, is this something that is implemented? If not is this something that is of interest for KFP to have? I think it would be nice and important in order to do CI/CD for Kubeflow for scheduled pipeline jobs.

**Comment by NikeNano** [comment]
I will start to work on this and make a PR. Need it for a project so will build it and see if it is suitable for Kubeflow when is is done :)

**Comment by NikeNano** [comment]
Should be in kubeflow/pipelines,my bad , will close this and make PR in kubeflow pipelines :)

**Comment by NikeNano** [comment]
Should be in kubeflow/pipelines,my bad , will close this and make PR in kubeflow pipelines :)
