### ISSUE TITLE
Dev tools

### ISSUE THREAD

**Issue by bhack** [kubeflow/kubeflow#465]
What impact could have [Skaffold](https://github.com/GoogleCloudPlatform/skaffold) in the organization of the dev/production loop here or for users examples?

/cc @jlewi @r2d4
Ref. https://github.com/kubeflow/tf-operator/issues/136

Edit: I've edited the title to talk more in general about dev tools: https://github.com/kubeflow/tf-operator/issues/136#issuecomment-388038934 /cc @squillace

**Comment by r2d4** [comment]
Just from a first glance, in CI it could get rid of this script with skaffold's GCB integration

https://github.com/kubeflow/tf-operator/blob/master/build/images/tf_operator/build_and_push.py

It could also provide the dev cycle for developing the app and the chart using skaffold's helm integration.

https://github.com/kubeflow/tf-operator/tree/master/tf-job-operator-chart

If I get some time this week, I'll play around with a basic skaffold.yaml for the repo.

**Comment by bhack** [comment]
An interesting thread started at https://groups.google.com/forum/#!topic/kubernetes-dev/YcjXRDrCdbI

**Comment by bhack** [comment]
Could be also interesting to see some of its benefits for users in https://github.com/kubeflow/examples

**Comment by bhack** [comment]
@nqn The distribute KVC U-net example in the repo is quite interesting.

**Comment by bhack** [comment]
As we are introducing wave flux in https://github.com/kubeflow/kubeflow/issues/971 take a look at https://www.weave.works/blog/weaveworks-gitops-developer-toolkit-part-one-skaffold
