### ISSUE TITLE
Sorry, /pipeline/ is not a valid page

### ISSUE THREAD

**Issue by ijackcy** [kubeflow/kubeflow#4650]
When I open centraldashboard web page, I am prompted that the page Sorry, /pipeline/ is not a valid page
Sorry, /jupyter/ is not a valid page
Sorry, /katib/ is not a valid page

i checked the log of the pod.

root@ubuntu-master:/home/xiaowei# kubectl -n kubeflow logs centraldashboard-5578cc9569-t87hj

> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve

> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
Unable to fetch Application information: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'applications.app.k8s.io is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "applications" in API group "app.k8s.io" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { group: 'app.k8s.io', kind: 'applications' },
  code: 403 }
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
"other" is not a supported platform for Metrics
Using Profiles service at http://profiles-kfam.kubeflow:8081/kfam
Server listening on port http://localhost:8082 (in production mode)
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
Unable to fetch Application information: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'applications.app.k8s.io is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "applications" in API group "app.k8s.io" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { group: 'app.k8s.io', kind: 'applications' },
  code: 403 }
Unable to fetch Events for anonymous: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "anonymous"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }
Unable to fetch Events for anonymous: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "anonymous"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }
Unable to fetch Events for anonymous: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "anonymous"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }
Unable to fetch Events for kubeflow: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }
Unable to fetch Events for kubeflow: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }
Unable to fetch Events for kubeflow: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'events is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "events" in API group "" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { kind: 'events' },
  code: 403 }

i found that all pods work very well.
root@ubuntu-master:/home/xiaowei# kubectl -n kubeflow get all
NAME                                                               READY   STATUS    RESTARTS   AGE
pod/admission-webhook-bootstrap-stateful-set-0                     1/1     Running   0          4d18h
pod/admission-webhook-deployment-b7d89f4c7-c7n8h                   1/1     Running   2          4d18h
pod/application-controller-stateful-set-0                          1/1     Running   0          61m
pod/argo-ui-6754c76f9b-6cw2l                                       1/1     Running   0          4d18h
pod/centraldashboard-5578cc9569-t87hj                              1/1     Running   0          4d18h
pod/jupyter-web-app-deployment-6b7d9c5fd6-4d2jr                    1/1     Running   0          4h14m
pod/katib-controller-789d76d446-4jqth                              1/1     Running   1          4d18h
pod/katib-db-549499b7df-4jnjl                                      1/1     Running   2          4d16h
pod/katib-manager-7b9fdcd46d-h6rhf                                 1/1     Running   2          4d17h
pod/katib-ui-dd75bd446-47gbz                                       1/1     Running   0          4d18h
pod/kfserving-controller-manager-0                                 2/2     Running   1          4d18h
pod/metacontroller-0                                               1/1     Running   0          4h15m
pod/metadata-db-7584d44b65-z99w7                                   1/1     Running   0          4d18h
pod/metadata-deployment-cd8f7d58f-pjpmm                            1/1     Running   0          4d18h
pod/metadata-envoy-deployment-bff4f8b9-bc9kk                       1/1     Running   2          4d18h
pod/metadata-grpc-deployment-7cc5d84854-btbwg                      1/1     Running   6          4d18h
pod/metadata-ui-7c978889b5-xmtdb                                   1/1     Running   2          4d18h
pod/minio-764648495-vg5nk                                          1/1     Running   2          4d18h
pod/ml-pipeline-588b64fff-v2rvb                                    1/1     Running   0          4d18h
pod/ml-pipeline-ml-pipeline-visualizationserver-6c7c97869d-6p649   1/1     Running   0          4d18h
pod/ml-pipeline-persistenceagent-79ff896578-tv5xc                  1/1     Running   3          4d18h
pod/ml-pipeline-scheduledworkflow-7d89bb6db5-dgsgg                 1/1     Running   0          4d18h
pod/ml-pipeline-ui-6656886579-pf8gj                                1/1     Running   0          4d18h
pod/ml-pipeline-viewer-controller-deployment-546bd5f545-5v2jw      1/1     Running   0          4d18h
pod/mysql-6c9cb88c4d-f8r5q                                         1/1     Running   0          4d18h
pod/notebook-controller-deployment-6d594ddd6b-xfm5c                1/1     Running   1          4d18h
pod/profiles-deployment-67799585bd-mgd9n                           2/2     Running   2          4d18h
pod/pytorch-operator-fdfd7985-k2llg                                1/1     Running   2          4d18h
pod/seldon-operator-controller-manager-0                           1/1     Running   1          4d18h
pod/spartakus-volunteer-5888bc655-scbl2                            1/1     Running   2          4d18h
pod/tensorboard-9c6674f98-djtxt                                    1/1     Running   0          19h
pod/tf-job-operator-5dff84b966-w2k4v                               1/1     Running   2          4d18h
pod/workflow-controller-85c665bcb9-4lx7p                           1/1     Running   0          4d18h

Environment:

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
kfctl version: 0.70
Kubernetes version: 1.15.1
OS : ubuntu server 16.04

**Comment by kishoreallwynraj** [comment]
I am also facing the same issue. My kubeflow setup is on openshift.

I also tried running below command and deleted and recreated the pod but still the same issue.
oc adm policy add-scc-to-user anyuid -z centraldashboard -n kubeflow

**Comment by jlewi** [comment]
This looks like an issue with your ingress.

How is the ingress to your Kubeflow cluster configured? Are you accessing your cluster through the ingress (as opposed to port-forwarding to centraldashboard)

"/jupyter", "/katib" etc... are reverse proxy routes set up through ISTIO on your ingress.

You can run

```
kubectl -n kubeflow get virtualservice
```

To see a list of routes. 

How did you deploy Kubeflow and configure ingress to Kubeflow?

**Comment by liuchintao** [comment]
Hi, I met the same problem, I used this command `kfctl apply -f -V kfctl_k8s_istio.v1.0.0.yaml` to deploy Kubeflow. All pods work well when I use `kubectl get -n kubeflow po`, but **centraldashboard** pod‘s log shows that `nodes` and `applications` are not in API group.

I could not find istio related namespace or pods were deployed. Is there an example to how to create an ingress for kubeflow?

**Comment by liuchintao** [comment]
> 
> 
> Hi, I met the same problem, I used this command `kfctl apply -f -V kfctl_k8s_istio.v1.0.0.yaml` to deploy Kubeflow. All pods work well when I use `kubectl get -n kubeflow po`, but **centraldashboard** pod‘s log shows that `nodes` and `applications` are not in API group.
> 
> I could not find istio related namespace or pods were deployed. Is there an example to how to create an ingress for kubeflow?

OK, I resolved it, I should not create an ingress manually, istio has created an ingressgateway for me, I find out istio ingressgateway svc's nodeport and visit kubeflow ui successfully.

**Comment by dzungductran** [comment]
@liuchintao, I am having the same issues, can you tell me the steps to resolve this issue?

**Comment by jbottum** [comment]
@liuchintao @dzungductran Hi Guys - Did you get this documented?  Should we post this?  Can we close this issue?

**Comment by dzungductran** [comment]
You can close it. I found that istio is not setup correctly on my on-premise K8S using the istio setup from KF. I haven't debug the actual setup of istio yet. I got it to work by reinstall istio after KF installation.
