### ISSUE TITLE
update the version of knative bundled with KF

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#4651]
/kind bug

Not sure if this should be a 'bug' or 'feature'.  However, seems that some KFServing integration problems (https://github.com/kubeflow/kfserving/issues/629) could probably be addressed if KF was using knative 0.11.

**Comment by alexwennerberg** [comment]
Related KFServing issue: https://github.com/kubeflow/kfserving/pull/630

**Comment by jlewi** [comment]
@jtfogarty this issue would probably be better assigned to kfserving
/area inference
/remove-area engprod

**Comment by jlewi** [comment]
@animeshsingh @ellis-bigelow is there already an issue tracking this?

**Comment by animeshsingh** [comment]
KNative upgrade is an original open issue here 
https://github.com/kubeflow/kfserving/issues/596

**Comment by jlewi** [comment]
Duplicate of kubeflow/kfserving#596
