### ISSUE TITLE
Configurable Istio Gateway for Notebook Controller is not working

### ISSUE THREAD

**Issue by Subreptivus** [kubeflow/kubeflow#4656]
/kind bug

**What steps did you take and what happened:**
Changing `ISTIO_GATEWAY` environment variable on notebook controller deployment isn't reflected on Istio VirtualService for notebook. It is still using default value of `kubeflow/kubeflow-gateway`.

```
root@notebook-controller-deployment-7967d8b565-x5gvj:/# env|grep -i istio
USE_ISTIO=true
ISTIO_GATEWAY=istio-system/istio-gateway
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: "2020-01-15T22:02:10Z"
  generation: 1
  name: notebook-ikom-test8
  namespace: ikom
  ownerReferences:
  - apiVersion: kubeflow.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: test8
    uid: 19d3dde8-b5a9-46ac-b57a-d73c3b49f6a0
  resourceVersion: "6399125"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/ikom/virtualservices/notebook-ikom-test8
  uid: 9c111e99-b954-470a-a872-2f1919f7de61
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /notebook/ikom/test8
    rewrite:
      uri: /notebook/ikom/test8
    route:
    - destination:
        host: test8.ikom.svc.cluster.local
        port:
          number: 80
    timeout: 300s
```

**What did you expect to happen:**
Istio Gateway for notebook virtual service is equal to `ISTIO_GATEWAY` environment variable on notebook controller

**Environment:**

- Kubeflow version: 0.7.1
- kfctl version: kfctl v1.0-rc.1-0-g963c787
- Kubernetes platform: Azure Kubernetes Services
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"2640ac46d96791a135961425127d9c2f7e184924", GitTreeState:"clean", BuildDate:"2019-11-14T04:58:54Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- OS: MacOS 10.14.6

**Comment by jlewi** [comment]
@jtfogarty This issue is actually about jupyter 
/area jupyter
/area front-end cancel

**Comment by Subreptivus** [comment]
Guys, sorry for not checking it earlier.
There is something wrong with your Docker image building or tagging system!
Just have a chance to build Notebook Controller myself and try it, and it's working as expected.
So for release v0.7.1 there is something wrong with this image. Code from here: https://github.com/kubeflow/kubeflow/tree/v0.7-branch/components/notebook-controller works fine!
