### ISSUE TITLE
when kfctl apply -f, where is dex?

### ISSUE THREAD

**Issue by aheeruru** [kubeflow/kubeflow#4679]
Hi. 

I try to install kubeflow with auth on my own kubernetes cluster.
And I look this guide https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

but failed..

maybe it couldn't find directory 'dex'

I checked manifests-0.7-branch.tar.gz.
I found 'dex-auth' directory but couldn't find dex.

What did I miss? please help me.

$ kfctl apply -V -f kfctl_existing_arrikto.yaml

.....
configmap/istio-parameters-797cg68672 created
gateway.networking.istio.io/kubeflow-gateway unchanged
serviceentry.networking.istio.io/google-api-entry unchanged
serviceentry.networking.istio.io/google-storage-api-entry unchanged
virtualservice.networking.istio.io/google-api-vs unchanged
virtualservice.networking.istio.io/google-storage-api-vs unchanged
virtualservice.networking.istio.io/grafana-vs unchanged
clusterrbacconfig.rbac.istio.io/default configured
configmap/oidc-authservice-parameters created
service/authservice created
deployment.apps/authservice created
envoyfilter.networking.istio.io/authn-filter created
persistentvolumeclaim/authservice-pvc created
ERRO[0002] error evaluating kustomization manifest for dex Error absolute path error in 'kustomize/dex' : evalsymlink failure on 'kustomize/dex' : lstat /opt/kubeflow/kustomize/dex: no such file or directory  filename="kustomize/kustomize.go:163"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for dex Error absolute path error in 'kustomize/dex' : evalsymlink failure on 'kustomize/dex' : lstat /opt/kubeflow/kustomize/dex: no such file or directory

**Comment by yanniszark** [comment]
Hi @aheeruru, can you provide the kfctl version you are using?
`kfctl version`

Personally, I have installed existing_arrikto v0.7 many times successfully using version v0.7.0:
https://github.com/kubeflow/kubeflow/releases/tag/v0.7.0

**Comment by aheeruru** [comment]
oh sorry.

I used previous kfctl version kfctl v0.7.0. But tar and existing_arrikto version is 0.7.1.
After changing kfctl version to kfctl v0.7.1-2-g55f9b2a, it works well.

Thanks :)
