### ISSUE TITLE
Expecetd timeline for support of Kubernetes 1.16

### ISSUE THREAD

**Issue by indranilr** [kubeflow/kubeflow#4680]
/kind question

**Question:**
What is the expected timeline (I am assuming it will be a upcoming minor release) for Kubernetes 1.16  version support in Kubeflow ? 0.7 documentation suggests support till version 1.15.

**Comment by yanniszark** [comment]
I would expect the only roadblock for 1.16 to be the deprecated extensions apiVersion for Deployments, StatefulSets etc.
Doing a quick grep in the v0.7-branch of manifests reveals such apiVersion only in the Ingress resources of GCP and AWS.

/cc @Jeffwan @jlewi you may want to open issues for transitioning the Ingresses to `networking.k8s.io/v1`.

I would expect the on-prem configs, such as the [existing_arrikto config](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto) to work as they are.

**Comment by jlewi** [comment]
Duplicate of kubeflow/manifests#375
