### ISSUE TITLE
Install / Deploy Kubeflow failed via YAML 

### ISSUE THREAD

**Issue by authenticfake** [kubeflow/kubeflow#4681]
/kind bug

Install / Deploy Kubeflow failed via YAML 

**What steps did you take and what happened:**
following the installation guide 
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/
duirng the Set up and deploy Kubeflow launching the below command
/kfctl apply -V -f kfctl_k8s_istio.0.7.1.yaml

we receive the following error
**What did you expect to happen:**

INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to kubeflow based on location of config file: kfctl_k8s_istio.0.7.1.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
 
For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Deleting cachedir .cache/manifests because Status.ReposCache is out of date  filename="kfconfig/types.go:464"
INFO[0000] Fetching /tmp/v0.7-branch.tar.gz to .cache/manifests  filename="kfconfig/types.go:485"
INFO[0000] Fetch succeeded; LocalPath .cache/manifests   filename="kfconfig/types.go:526"
INFO[0000] Processing application: istio-crds            filename="kustomize/kustomize.go:340"
Error: failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds
Usage:
  kfctl apply -f ${CONFIG} [flags]
 
Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false
 
failed to build kfApp from URI kfctl_k8s_istio.0.7.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7.1
- kfctl version: 0.7.1
- Kubernetes platform: Kupernatis / microkubernetes 
- Kubernetes version: 1.14
- OS CentOS

**Comment by jlewi** [comment]
It looks like there was a problem copying the istio-crds application from the cache to the application directory
https://github.com/kubeflow/kfctl/blob/4df015716ef484b386d9000594e3d24e334ebe5e/pkg/kfapp/kustomize/kustomize.go#L365

Here's the spec
https://github.com/kubeflow/manifests/blob/eae2dae52d83b4fbfd22da86e27185f6347664dd/kfdef/kfctl_k8s_istio.0.7.1.yaml#L299

It looks like the path is valid
https://github.com/kubeflow/manifests/tree/v0.7-branch/istio/istio-crds

@krishnadurai @swiftdiaries is everything working with the 1.0 config?
