### ISSUE TITLE
Notebook status should be set based on the joint "ready" state of the containers

### ISSUE THREAD

**Issue by AndriiNeverov** [kubeflow/kubeflow#4689]
/kind bug

**What steps did you take and what happened:**

Assuming all the nodes have the notebook image so that no time is spend in pulling, create a new notebook server. The status goes almost immediately to green/Ready. 

In the reality the Pod has 1/2 Ready state, because Istio sidecar is still starting (has "ready" set to "false"). Clicking on the CONNECT results in an error until the sidecar gets ready.

This is important to fix, since in the env where notebook images are distributed across all nodes every user will see this error on every notebook creation.

Could be related to https://github.com/kubeflow/kubeflow/issues/3637.

**What did you expect to happen:**

The status should be Waiting/Not Ready until all containers are indeed ready.

**Anything else you would like to add:**

// notebook_controller.go

cs := pod.Status.ContainerStatuses[0].State
instance.Status.ContainerState = cs
...
err = r.Status().Update(ctx, instance)

Status().Update should somehow be calculated based on pod.Status.ContainerStatuses[*].Ready instead of just pod.Status.ContainerStatuses[0].State.Running.

**Environment:**

- Kubeflow version: 0.7.1

**Comment by jlewi** [comment]
@jtfogarty Issues about notebooks should be assigned area/jupyter
