### ISSUE TITLE
deploy.kubeflow.cloud does nothing

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/kubeflow#4690]
After trying to deploy kubeflow using deploy.kubeflow.cloud with IAP, no GKE cluster was started.
version: kubeflow 0.7
I've deployed kubeflow successfully before with this mechanism. I properly followed the steps to set up IAP, genertaing OAuth creds, etc.

**Comment by jlewi** [comment]
@kunmingg What debug information would be useful for debugging this?

**Comment by kunmingg** [comment]
Can you share the logs from the bottom of the UI?

**Comment by jlewi** [comment]
Closing as obsolete.
