### ISSUE TITLE
Can Kubeflow Metadata be used independently? 

### ISSUE THREAD

**Issue by jusingh** [kubeflow/kubeflow#4692]
/kind question

**Question:**
We have a homegrown ML Pipeline and we are working at standardizing pipeline components. To start with we are evaluating metadata store to explore, compare, and examine pipelines’ runs in detail.

So was curious to know if we can just use Kubeflow Metadata[1] without using other components of Kubeflow 

[1] https://www.kubeflow.org/docs/components/misc/metadata/

**Comment by jtfogarty** [comment]
/area usage
/ priority p2

**Comment by jusingh** [comment]
Hi, any update on this? thxs!

**Comment by jlewi** [comment]
@jessiezcc @neuromage @avdaredevil @zhenghuiwang @rmgogogo  What is the current status of using metadata independent of KFP?

IIUC there are a bunch of changes related to lineage which are in KFP which aren't available in standalone metadata?
