### ISSUE TITLE
[Security Risk] No sha File Fingerprints on the Releasepage

### ISSUE THREAD

**Issue by avolution** [kubeflow/kubeflow#4695]
For example: https://github.com/kubeflow/kubeflow/releases/tag/v0.7.1

Would be nice to have fingerprints for every release to ensure to get the original file.

(PGP Signing of the release files would be even better)

**Comment by avolution** [comment]
The CLI Install documentation should then also be updated with an "Verify Download" section

-> https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

**Comment by avolution** [comment]
[keep open]

**Comment by yanniszark** [comment]
@avolution would you be interested in contributing this feature?
It's definitely good to have, but I'm not sure if there are available cycles to implement it at the moment.
