### ISSUE TITLE
kfctl set-image-name command appends inventory:omitempty: null into all the kustomization.yaml files

### ISSUE THREAD

**Issue by chethanmahadevaiah** [kubeflow/kubeflow#4696]
kfctl set-image-name command appends "inventory:omitempty: null" into all the kustomization.yaml files in the manifests dir

Command to reproduce the issue:
    kfctl set-image-name test-repo.io

with this "inventory:omitempty: null" key-value pair in the yaml file, kfctl apply fails.

**Comment by nrchakradhar** [comment]
Should this be moved to kfctl repo?

**Comment by chethanmahadevaiah** [comment]
> Should this be moved to kfctl repo?

Moved to kfctl repo
Closing this

**Comment by chethanmahadevaiah** [comment]
https://github.com/kubeflow/kfctl/issues/194
