### ISSUE TITLE
GCPs internal load balancer port limitation 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4697]
/kind question

When installing Kubeflow on a private GKE cluster, the istio-ingressgateway service needs to be modified with the below selections;

``` 
metadata:
   annotations:
      cloud.google.com/load-balancer-type: internal
```
```
Change type to 
  type: LoadBalancer
```
There is a limited number of ports for this internal load balancer
[Load Balancing Quotas](https://cloud.google.com/load-balancing/docs/quotas#forwarding_rules )

**Question:**
How does GCPs internal load balancer port limitation impact istio-ingressgateway's current config

**Comment by jlewi** [comment]
@jtfogarty How are you installing ISTIO? Are you using [GCP Managed ISTIO](https://cloud.google.com/istio/docs/istio-on-gke/overview)

It looks like GCP managed ISTIO installs the ingress gateway. So I think once that's installed you should be able to expose traffic internally. 

I would expect that managed ISTIO takes care of properly configuring the ISTIO gateway.

So what I would probably do is.

1. Fork kubeflow/manifests
1. Modify the GCP deployment manager configurations to install managed ISTIO
1. Create a forked KFDef which doesn't install ISTIO
    * You should just need to remove the ISTIO packages
    * You could start with [kfctl_anthos.yaml](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_anthos.yaml) 
        * You would probably need to add the GCP plugin back if you wanted kfctl to create the DM configs
