### ISSUE TITLE
Notebook Web Server Gives Error "unable to list events for namespace None"

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4699]
/kind bug

When I try to spin up a notebook in the notebook server I get an error.

```
User jlewi@google.com is not authorized to list .v1.events for namespace: None
```
Screen shot is below

@kimwnasptd Is this related to a combination of using a subject access review check and trying to display events in the jupyter web app?

It looks like there may be a bug somewhere and its not getting the appropriate namespace.

The docker image is:
gcr.io/kubeflow-images-public/jupyter-web-app:vmaster-g56c9025a

![jupyter_web_app](https://user-images.githubusercontent.com/777219/73327525-2e795b00-420b-11ea-97a8-6bd07a7263e7.png)

**Comment by jlewi** [comment]
or is this an issue with the central dashboard not making the namespace available correctly to the webapp?

@avdaredevil

**Comment by jlewi** [comment]
kubeflow/kubeflow#4214 looks like the PR that modified the backend.

/cc @fediazgon

**Comment by kimwnasptd** [comment]
@jlewi I think this doesn't have to do with centraldashboard since the namespace is already selected.

My first guess would be that the clusterrole for the jupyter-web-app doesn't have permissions to list events. Can you verify it has the necessary permissions? 

The authorization error is shown because of the subjectaccessreview mechanism. The `namespace: None` is because the Events are not namespaced resources. I should change the error message to not show None in such cases.

**Comment by jlewi** [comment]
Here's the output of the clusterrole

```
kubectl get clusterrole -o yaml jupyter-web-app-cluster-role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"jupyter-web-app","app.kubernetes.io/component":"jupyter-web-app","app.kubernetes.io/instance":"jupyter-web-app-v0.7.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"jupyter-web-app","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.7.0","kustomize.component":"jupyter-web-app"},"name":"jupyter-web-app-cluster-role"},"rules":[{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list","create","delete"]},{"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"],"verbs":["create"]},{"apiGroups":["kubeflow.org"],"resources":["notebooks","notebooks/finalizers","poddefaults"],"verbs":["get","list","create","delete"]},{"apiGroups":[""],"resources":["persistentvolumeclaims"],"verbs":["create","delete","get","list"]},{"apiGroups":[""],"resources":["events"],"verbs":["list"]},{"apiGroups":["storage.k8s.io"],"resources":["storageclasses"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2020-01-29T00:22:58Z"
  labels:
    app: jupyter-web-app
    app.kubernetes.io/component: jupyter-web-app
    app.kubernetes.io/instance: jupyter-web-app-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: jupyter-web-app
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: jupyter-web-app
  name: jupyter-web-app-cluster-role
  resourceVersion: "2476"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/jupyter-web-app-cluster-role
  uid: 80662646-422d-11ea-9c48-42010a80023f
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/finalizers
  - poddefaults
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
```

I'm not seeing a label like 

```
rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view
```

That would be used to aggregate clusterroles.

So I suspect the issue is we need to define or update kubeflow-edit and view cluster roles for jupyter that could then be aggregated to give the user the required permission.

**Comment by jlewi** [comment]
I was able to work around this by making myself an admin.

```
kubectl create clusterrolebinding --user=jlewi@google.com --clusterrole=admin jlewi-admin
```

This also might explain why other users haven't reported this yet.
If a user creates the cluster with kfctl we grant them cluster admin privileges as part of the deploy process so they would already have permission.

**Comment by jlewi** [comment]
@kimwnasptd We should probably add admin,edit,and viewer roles like we do for other applications and rely on cluster role aggregation. Like we do for TFJob

https://github.com/kubeflow/manifests/blob/3fe91f521c28bb43283d8363384271b60eb7c301/tf-training/tf-job-operator/base/cluster-role.yaml#L42

**Comment by jlewi** [comment]
I will create a PR.

**Comment by jlewi** [comment]
Still not working.

Here are the role bindings in the newly created namespace.
[rolebinding.yaml.txt](https://github.com/kubeflow/kubeflow/files/4137881/rolebinding.yaml.txt)

There is a binding for jlewi@google.com to kubeflow-cluster-admin.

**Comment by jlewi** [comment]
Creating a role binding 

```
kubectl create rolebinding --user=jlewi@google.com --clusterrole=kubeflow-view jlewi-view
```

Doesn't fix the problem.

Creating a clusterrolebinding does fix it.

```
kubectl create rolebinding --user=jlewi@google.com --clusterrole=kubeflow-view jlewi-view
```

@kimwnasptd So it looks like there might be another bug in the subject access review check not properly checking namespace?

**Comment by jlewi** [comment]
As @kimwnasptd pointed out earlier events aren't namespace scoped. Which explains why creating a rolebinding doesn't work.

I can think of the following solutions

1. Grant every user a clusterrolebinding to access events.
1. Drop the subject access review check in the notebook API server on list events
    * We could rely on the notebook server to filter out events a user shouldn't see

#2 seems more restrictive and easier to implement.

**Comment by jlewi** [comment]
Confirmed this is fixed at
https://github.com/kubeflow/manifests/commit/e9dfeb30abcd12a920ad8f8510f26a167390e5fc
