### ISSUE TITLE
Included docker image doesn't contain tensorflow

### ISSUE THREAD

**Issue by vaskokj** [kubeflow/kubeflow#4704]
/kind bug

**What steps did you take and what happened:**
Went to Notebook Server link, created new notebook with the included gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-gpu:v0.7.0 image. Started a Python3 notebook and ran 

"import tensorflow as tf" and pythons typical no module found error.

**What did you expect to happen:**
tensorflow to be included in a tensorflow image.

**Anything else you would like to add:**

Launching a Python2 notebook in the same container, and tensorflow was available. 

Which then leads to this issue when you try to `pip install tensorflow`
https://github.com/kubeflow/kubeflow/issues/4667

I have not tried the other images but will do that and follow up.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0
- kfctl version: (use `kfctl version`): 1.0.rc1
- Kubernetes platform: (e.g. `minikube`): Kubespray
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by jlewi** [comment]
@Tabrizian  any idea?
Looks like the base image is configured to be the py3 version
https://github.com/kubeflow/kubeflow/blob/dfd447a5d61068b94c0edcf2d91b1ab9014e489a/components/tensorflow-notebook-image/versions/1.14.0gpu/version-config.json#L2

**Comment by jlewi** [comment]
Lets verify that the new 1.0 image has TF and if it does close this issue.

**Comment by Tabrizian** [comment]
@jlewi I tried running a brand new notebook and it has tensorflow. Also, I tried the individual docker image and it works. I tried it on `kubeflow v0.7`.

**Comment by jlewi** [comment]
@Tabrizian thanks

I tagged the new images

gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0
gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0
gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu:1.0.0

**Comment by jlewi** [comment]
I did a sanity check on the new image

```
kubectl run -it --image=gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0 tf-gpu-1-15 --restart=Never /bin/bash

>>> import tensorflow as tf
>>> tf.__file__
'/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py'
```

I also see CUDA in the image

```
/usr/local/cuda-10.0/
```

**Comment by jlewi** [comment]
I tried gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0 in a python3 notebook on KF 1.0 and it also worked.

**Comment by jlewi** [comment]
I verified that the new 2.1.1 GPU image has TF as well.
https://github.com/kubeflow/manifests/tree/129b889
