### ISSUE TITLE
After Create Server fails, UI reports API error

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4707]
/kind bug

**What steps did you take and what happened:**
During the corse of testing, creation of a Notebook Server fails.  After the failure the UI consistently reports an api failure

![Screen Shot 2020-01-30 at 3 51 39 PM](https://user-images.githubusercontent.com/6708730/73493550-97321600-4378-11ea-86fc-a55712d41d34.png)

**What did you expect to happen:**
The UI should not be impacted by a pod failure

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version:  v1.0-rc.1-0-g963c787
- Kubernetes platform: v1.15.7
- Kubernetes version: v1.15.7
- OS (e.g. from `/etc/os-release`): NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by jlewi** [comment]
@jtfogarty could you please provide the logs for the backend server for jupyter UI?

@kimwnasptd could you help @jtfogarty with the commands to debug the issue?

**Comment by jtfogarty** [comment]
@jlewi I do not see this happening on the latest;

Kubeflow version: dev_local
kfctl version: v1.0-rc.2-13-g521fcfe
Kubernetes platform: v1.15.7
Kubernetes version: v1.15.7
OS (e.g. from /etc/os-release): NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by kimwnasptd** [comment]
I remember seeing these errors back on 0.6.

IIRC this had happened to me if I had left the tab idle for a long period of time and then I re-opened it. I also wasn't able to see these errors in the backend's logs. 

@jtfogarty could you also post the output from
```
kubectl logs -n kubeflow <jupyter-web-app-pod>
```

**Comment by jtfogarty** [comment]
@kimwnasptd I'm not seeing this issue any longer.  

I'll continue to test but it appears to no longer be an issue.

**Comment by jtfogarty** [comment]
this error appeared today.  Attached are the logs
[jupyter-web-app-deployment.log](https://github.com/kubeflow/kubeflow/files/4167916/jupyter-web-app-deployment.log)

**Comment by jtfogarty** [comment]
This is an on-prem install where I have the ingress servers configured as a nodeport
The istio pod has a status of OOMKilled

**Comment by jtfogarty** [comment]
@jlewi can we change this to a p0 ?

/priority p0

**Comment by jtfogarty** [comment]
[istio-1.log](https://github.com/kubeflow/kubeflow/files/4226890/istio-1.log)

**Comment by jlewi** [comment]
@jtfogarty Can you please describe the failure mode? 

The weblogs you attached 13 days ago don't show any crashes in the Jupyter web app. The logs also look fine. 

It looks like to me like the original bug report is about client side javascript not being able to talk to the backend.

If ISTIO pods are being killed e.g. because of OOM or some other reason then that would prevent traffic from the browser from being able to reach the jupyter web backend.

So based on the information this doesn't look like a bug in Kubeflow but an issue with how ISTIO is deployed on your particular cluster.

**Comment by jtfogarty** [comment]
@jlewi I'm just trying to troubleshoot this environment.  Would this be better to start a thread on kubeflow-discuss or the cuj-onprem channel

I will reinstall with 1.0.0 manifests

**Comment by jlewi** [comment]
@jtfogarty I think its fine to open issues and use that to track. My suggestion would be to label them such that we don't think they are release blocking bugs if we don't think they are release blocking bugs.

My suggestion would be to use labels
kind/question (or kind/process) to indicate its some of ongoing investigation that's not clearly known to be an issue with KF
P1 or P2 for priority
customer issues - for Kanban board

**Comment by jtfogarty** [comment]
Attached is a log file from the centraldashboard.  

[cb.log](https://github.com/kubeflow/kubeflow/files/4268115/cb.log)

I'm seeing errors consistently after the ingress controller stabilized

**Comment by jtfogarty** [comment]
This issue can be closed.  It appears to be related to #4860
