### ISSUE TITLE
Running the TensorFlow training job does not work - pods can't start because of missing service account

### ISSUE THREAD

**Issue by PaulQbFeng** [kubeflow/kubeflow#4711]
/kind bug

**What steps did you take and what happened:**
I am following the [MNIST E2E tutorial](https://www.kubeflow.org/docs/gke/gcp-e2e/). Everything works well until the Training on GKE. The `kustomize build . | kubectl apply -f -` yields : <br> <pre><code>configmap/mnist-map-training-g4bbb7ckgm created
tfjob.kubeflow.org/mnist-train-dist created</pre></code>

But no `mnist-train-dist-chief-0` workload is created.

**Anything else you would like to add:**

`kubectl -n kubeflow get tfjobs` yields <pre><code>NAME               STATE   AGE
mnist-train-dist           9d</code></pre>

`kubectl -n ${NAMESPACE} get tfjobs mnist-train-dist -o yaml` yields 
<pre><code>apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeflow.org/v1","kind":"TFJob","metadata":{"annotations":{},"name":"mnist-train-dist","namespace":"kubeflow"},"spec":{"tfReplicaSpecs":{"Chief":{"replicas":1,"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}},"spec":{"containers":[{"command":["/usr/bin/python","/opt/model.py","--tf-model-dir=$(modelDir)","--tf-export-dir=$(exportDir)","--tf-train-steps=$(trainSteps)","--tf-batch-size=$(batchSize)","--tf-learning-rate=$(learningRate)"],"env":[{"name":"modelDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/"},{"name":"exportDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export"},{"name":"trainSteps","value":"200"},{"name":"batchSize","value":"100"},{"name":"learningRate","value":"0.01"}],"image":"gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341","name":"tensorflow","workingDir":"/opt"}],"restartPolicy":"OnFailure","serviceAccount":"default-editor"}}},"Ps":{"replicas":1,"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}},"spec":{"containers":[{"command":["/usr/bin/python","/opt/model.py","--tf-model-dir=$(modelDir)","--tf-export-dir=$(exportDir)","--tf-train-steps=$(trainSteps)","--tf-batch-size=$(batchSize)","--tf-learning-rate=$(learningRate)"],"env":[{"name":"modelDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/"},{"name":"exportDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export"},{"name":"trainSteps","value":"200"},{"name":"batchSize","value":"100"},{"name":"learningRate","value":"0.01"}],"image":"gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341","name":"tensorflow","workingDir":"/opt"}],"restartPolicy":"OnFailure","serviceAccount":"default-editor"}}},"Worker":{"replicas":2,"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}},"spec":{"containers":[{"command":["/usr/bin/python","/opt/model.py","--tf-model-dir=$(modelDir)","--tf-export-dir=$(exportDir)","--tf-train-steps=$(trainSteps)","--tf-batch-size=$(batchSize)","--tf-learning-rate=$(learningRate)"],"env":[{"name":"modelDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/"},{"name":"exportDir","value":"gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export"},{"name":"trainSteps","value":"200"},{"name":"batchSize","value":"100"},{"name":"learningRate","value":"0.01"}],"image":"gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341","name":"tensorflow","workingDir":"/opt"}],"restartPolicy":"OnFailure","serviceAccount":"default-editor"}}}}}}
  creationTimestamp: "2020-01-21T14:52:54Z"
  generation: 1
  name: mnist-train-dist
  namespace: kubeflow
  resourceVersion: "3124131"
  selfLink: /apis/kubeflow.org/v1/namespaces/kubeflow/tfjobs/mnist-train-dist
  uid: b4a59706-3c5d-11ea-bc41-42010a840297
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/
            - name: exportDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.01"
            image: gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341
            name: tensorflow
            workingDir: /opt
          restartPolicy: OnFailure
          serviceAccount: default-editor
    Ps:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/
            - name: exportDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.01"
            image: gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341
            name: tensorflow
            workingDir: /opt
          restartPolicy: OnFailure
          serviceAccount: default-editor
    Worker:
      replicas: 2
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            env:
            - name: modelDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/
            - name: exportDir
              value: gs://axarevgeoplatformevalsandbox-mnist-kubeflow-bucket/1579531341/export
            - name: trainSteps
              value: "200"
            - name: batchSize
              value: "100"
            - name: learningRate
              value: "0.01"
            image: gcr.io/axarevgeoplatformevalsandbox/mnist-train:1579531341
            name: tensorflow
            workingDir: /opt
          restartPolicy: OnFailure
          serviceAccount: default-editor
</code></pre>

`kubectl -n kubeflow logs -l name=tf-job-operator` yields 

<pre><code>{"filename":"record/event.go:221","level":"info","msg":"Event(v1.ObjectReference{Kind:\"TFJob\", Namespace:\"kubeflow\", Name:\"mnist-train-dist\", UID:\"b4a59706-3c5d-11ea-bc41-42010a840297\", APIVersion:\"kubeflow.org/v1\", ResourceVersion:\"3124131\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedCreatePod' Error creating: pods \"mnist-train-dist-chief-0\" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount \"default-editor\" not found","time":"2020-01-23T15:35:44Z"}
{"filename":"tensorflow/job.go:130","level":"info","msg":"Updating tfjob: mnist-train-dist","time":"2020-01-23T15:36:14Z"}
{"filename":"tensorflow/controller.go:339","job":"kubeflow.mnist-train-dist","level":"info","msg":"Reconcile TFJobs mnist-train-dist","time":"2020-01-23T15:36:14Z","uid":"b4a59706-3c5d-11ea-bc41-42010a840297"}
{"filename":"tensorflow/pod.go:80","job":"kubeflow.mnist-train-dist","level":"info","msg":"Need to create new pod: ps-0","replica-type":"ps","time":"2020-01-23T15:36:14Z","uid":"b4a59706-3c5d-11ea-bc41-42010a840297"}
{"filename":"tensorflow/pod.go:179","job":"kubeflow.mnist-train-dist","level":"warning","msg":"Restart policy in pod template will be overwritten by restart policy in replica spec","replica-type":"ps","time":"2020-01-23T15:36:14Z","uid":"b4a59706-3c5d-11ea-bc41-42010a840297"}
{"filename":"record/event.go:221","level":"info","msg":"Event(v1.ObjectReference{Kind:\"TFJob\", Namespace:\"kubeflow\", Name:\"mnist-train-dist\", UID:\"b4a59706-3c5d-11ea-bc41-42010a840297\", APIVersion:\"kubeflow.org/v1\", ResourceVersion:\"3124131\", FieldPath:\"\"}): type: 'Warning' reason: 'SettedPodTemplateRestartPolicy' Restart policy in pod template will be overwritten by restart policy in replica spec","time":"2020-01-23T15:36:14Z"}
{"filename":"tensorflow/controller.go:455","job":"kubeflow.mnist-train-dist","level":"warning","msg":"reconcilePods error pods \"mnist-train-dist-ps-0\" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount \"default-editor\" not found","time":"2020-01-23T15:36:14Z","uid":"b4a59706-3c5d-11ea-bc41-42010a840297"}
{"filename":"tensorflow/controller.go:290","job":"kubeflow.mnist-train-dist","level":"info","msg":"Finished syncing tfjob \"kubeflow/mnist-train-dist\" (10.867556ms)","time":"2020-01-23T15:36:14Z"}
E0123 15:36:14.518194       1 controller.go:266] error syncing tfjob: pods "mnist-train-dist-ps-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
{"filename":"record/event.go:221","level":"info","msg":"Event(v1.ObjectReference{Kind:\"TFJob\", Namespace:\"kubeflow\", Name:\"mnist-train-dist\", UID:\"b4a59706-3c5d-11ea-bc41-42010a840297\", APIVersion:\"kubeflow.org/v1\", ResourceVersion:\"3124131\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedCreatePod' Error creating: pods \"mnist-train-dist-ps-0\" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount \"default-editor\" not found","time":"2020-01-23T15:36:14Z"}
</code></pre>
**Environment:**

- Kubeflow version: **0.7.0**
- kfctl version:  **v1.0-rc.1-0-g963c787**
- Kubernetes platform: 
- Kubernetes version: **v1.14.10**
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
The TFJob is failing because the service account "default-editor" doesn't exist in the target namespace.
There's a couple ways to fix this.

1. You can run in a profile created namespace so that you have the default-editor service account

    * This is probably what you want to do because that service account will be mapped using workload identity to a GCP service account to allow access to GCP resources

1. You could change the serviceAccount specified in the TFJob spec to be a service account that exists in your project

It looks like TFJob needs a better way to service pod errors; users shouldn't have to operator logs to figure out why pods didn't start.

/cc @johnugeorge @richardsliu

**Comment by johnugeorge** [comment]
Agree. We can add in the next release
