### ISSUE TITLE
Minikf 1.0 RC 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4714]
/kind process

Creating this bug to track creating a minikf 1.0 RC. The minikf page looks like the last update is from 201909
https://www.arrikto.com/minikf/

@vkoukis @yanniszark @elikatsis @jbottum do we have an ETA for a minikf 1.0 RC?

**Comment by jlewi** [comment]
@vkoukis @yanniszark @elikatsis @jbottum  any update on this?

**Comment by jlewi** [comment]
@vkoukis @yanniszark @elikatsis @jbottum any update on this?

**Comment by jlewi** [comment]
@vkoukis @yanniszark @elikatsis @jbottum any update on this?

**Comment by yanniszark** [comment]
Hi @jlewi, we are actively preparing MiniKF 1.0.
We've tested everything and we are currently ironing out a couple of small details.
Our plan is to have MiniKF with KF 1.0 available for use in both Vagrant and GCP on the day right after the 1.0 release.

**Comment by cspavlou** [comment]
MiniKF with Kubeflow 1.0 is available on GCP and Vagrant. We have also updated the Kubeflow docs to always show the MiniKF and Kubeflow version:
- [GCP](https://www.kubeflow.org/docs/started/workstation/minikf-gcp/)
- [Vagrant](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikf/)

**Comment by cspavlou** [comment]
@jlewi , I think we should close this issue
