### ISSUE TITLE
[AWS] 1.0 issues and features

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4719]
/kind feature

**Why you need this feature:**
This is a parent issue of all 1.0 AWS specific features. Let's use this to track all the issues and features for 1.0 release. 

- Simply and provides better experiences to bootstrap kubeflow
  - https://github.com/kubeflow/kfctl/issues/235
- Fine Grane IAM control on pods
  - https://github.com/kubeflow/kubeflow/issues/4403
- Managed external mysql database
  - https://github.com/kubeflow/kubeflow/issues/4546
  - https://github.com/kubeflow/kubeflow/issues/4545
- Managed object storage support for pipeline metadata and artifact data 
  - https://github.com/kubeflow/pipelines/pull/2080
  - https://github.com/kubeflow/pipelines/pull/3056
- Enable Authorization for AWS and unblock managed contributor feature 
  - https://github.com/kubeflow/kubeflow/issues/4761
  - https://github.com/kubeflow/kubeflow/issues/4746
- AWS components manifest upgrade 
  - https://github.com/kubeflow/manifests/issues/889
- OIDC Support (not via Cognito) on ALB ingress Controller. 
  - https://github.com/kubeflow/manifests/issues/945
- HTTPS 443 listener support in manifest
  - https://github.com/kubeflow/manifests/pull/653 
  - https://github.com/kubeflow/manifests/issues/946
- https://github.com/kubeflow/kubeflow/issues/3827

- E2E examples updates
  - https://github.com/kubeflow/examples/issues/724

- 1.0 docs on Kubeflow site
  - https://github.com/kubeflow/website/issues/1435
  - https://github.com/kubeflow/website/issues/1672
  - https://github.com/kubeflow/website/issues/1671
  - https://github.com/kubeflow/website/issues/1670
  - https://github.com/kubeflow/website/issues/1669
  - https://github.com/kubeflow/website/issues/1667

Note in the scope.
- Enable BasicAuth for basic AWS configs.
- Graduate MxNet Operator v1beta1.
- Upstream testing for Kubeflow on AWS

**Comment by jlewi** [comment]
@Jeffwan A lot of the linked issues look like they are still open. Is any of this release blocking?

Does the demo script http://bit.ly/demo-v1-0 work on AWS?

**Comment by descampsk** [comment]
We can maybe add this PR https://github.com/kubeflow/pipelines/pull/2080.

**Comment by Jeffwan** [comment]
@descampsk Yeah. This one is pretty helpful. Let me sync with @eterna2 on this

**Comment by eterna2** [comment]
Missed out a config field name change:
https://github.com/kubeflow/pipelines/pull/3056 will fix this oversight.

**Comment by descampsk** [comment]
@Jeffwan do you think it will be possible to add this to the kubeflow 1.0 ?
https://github.com/kubeflow/kfctl/issues/232

**Comment by jlewi** [comment]
@Jeffwan what can we get done by EOD today and EOW? 

Per previous comment it looks like most of this is feature requests so its not release blocking.

I would like to get an mnist notebook (kubeflow/examples#724) for the blog post. Since the examples aren't actually in the release it can land after the release; we just need it in time for the blog.

**Comment by Jeffwan** [comment]
@jlewi Yeah, if it's possible, I want to have these merged in master and bring back to 1.0-branch. Most of our users really like to have these supported and codes are ready. 

1. Authorization support in AWS.  https://github.com/kubeflow/manifests/pull/908
2. IAM role for service account. https://github.com/kubeflow/kfctl/pull/225 https://github.com/kubeflow/kubeflow/pull/4751
3. Add Anonymous user id to request for manifests without auth https://github.com/kubeflow/manifests/pull/909
4. Add external mysql option for pipeline and metadata. https://github.com/kubeflow/manifests/pull/906
5. A follow up PR to enable S3 for pipeline api-service  https://github.com/kubeflow/pipelines/pull/3056

For mnist notebook, I think I will follow your suggestion to have separate notebooks and I can make it by EOW

**Comment by jlewi** [comment]
@Jeffwan does kubeflow/manifests#909 need to be cherry-picked onto the 1.0 branch?

Looks like kubeflow/manifests@908 is still pending.

**Comment by Jeffwan** [comment]
> @Jeffwan does [kubeflow/manifests#909](https://github.com/kubeflow/manifests/pull/909) need to be cherry-picked onto the 1.0 branch?
> 
> Looks like kubeflow/manifests@908 is still pending.

All release blocking issues are already merged back to v1.0-branch

**Comment by Jeffwan** [comment]
v1.0.1 has been released. We can close this issue.
