### ISSUE TITLE
Build more efficient tensorflow-notebook images

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#472]
The current cpu images are ~10GB and the current gpu images are ~14GB. 

We should try to build smaller images.

Here is the Dockerfile used to build these images : https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile

**Comment by jlewi** [comment]
Its possible we have a bunch of intermediary layers as a result of the build process that are storing files that were subsequently deleted in later layers.

I think a quick check is you can use docker to export the image to a tarball and then reimport it. I believe that flattens all the layers.

You can then look at the size of the reimported image and see if its smaller.
