### ISSUE TITLE
How can I delete a namespace created for the new user? What is the mechanism behind to re-create namespace?

### ISSUE THREAD

**Issue by DdMad** [kubeflow/kubeflow#4720]
/kind question

**Question:**
Hi, recently I want to delete some of the namespaces, e.g `test-ns`, that are created by new users (i.e. in the setup step, each new user is asked to create a new namespace), but then after I run `kubectl delete ns test-ns`, the namespace `test-ns` is re-created right away. May I know how can I delete that namespace? What is the mechanism behind to re-create such namespace? (I remember after I delete Kubeflow from my cluster, I'm able to delete those namespaces, but I can't find which component is responsible for this)

Also, I wonder if there is a way to skip the setup step for new user or to not create new namespace for new user? Because I don't want to create a new namespace for every new user.

Thanks in advance!

**Comment by DdMad** [comment]
I figure out that once I delete the related profile, the namespace will be deleted as well. However, then when I refresh Kubeflow page, it will ask me to setup a new namespace again, which is I don't want. Is there a way that I can have a user that does not have any namespace? Or each user must have 1 namespace (+ 1 profile)? Because now I'm only using Kubeflow Pipelines and currently it does not have/need isolation based on namespace.

**Comment by kunmingg** [comment]
kubeflow multi-tenancy is enabled by default on GCP, and kubeflow central UI requires every user owning their own profile to host their notebooks / running pods.

Current version of pipeline has not integrate with multi-tenancy mode yet, if you only want to use pipeline you can access pipeline UI directly at 
`kf_endpoint_url/pipeline`, to skip checks from central UI.

**Comment by jlewi** [comment]
@kunmingg Does every user need their own namespace? Or can users be added as members of an existing namespace if they want to share that namespace. I think that is a use case we should support

**Comment by kunmingg** [comment]
Multiple users sharing a namespace is supported.

**Comment by DdMad** [comment]
@kunmingg Thanks for the reply. Look forward to the multi-tenancy feature.

**Comment by marziman** [comment]
@jlewi as I wrote in slack,
currently a user is forced to have a profile and namespace. Somehow adding contributors/users to an existing namespace doesnt work. It prompts for a new namespace.
For us, having a namespace for every user is too much.

Your help would be appreciated.
Thanks
