### ISSUE TITLE
[vanilla k8s] Kubeflow 1.0 demo-script

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#4725]
/kind feature

Persona: Infrastructure Engineer
Control Plane Walkthrough:

- [x] Install Kubeflow with (istio) KfDefs
- [ ]  Install Kubeflow with dex - pending
- [x] Configure / Get Istio IngressGateway endpoint
- [ ] Create profiles (w/ kubectl) #4725
- [x] Create notebooks from user-namespace (w/ kubectl) 
- [ ] Login (port-forward) into notebook as user
- [ ] Create TFJob (w/ kubectl, fairing from notebook)
- [ ] Create PyTorchJob (w/ kubectl, fairing from notebook)
- [ ] Create MPIJob for Horovod (w/ kubectl)

Persona: Data Scientist
User Plane Walkthrough:

- [ ] Get Central Dashboard login URI from Infra Engineer
- [ ] "Login" to central-dashboard
- [ ] Create new user profile using self-service workflow
- [ ] Create notebook server 
- [ ] Create TFJob (w/ fairing)
- [ ] Create PyTorchJob (w/ fairing)
- [ ] Create XGBoostJob (w/ fairing)

Persona: ML Engineer
User Plane Walkthrough:

- [ ] Get model URI from data scientist
- [ ] Create KFService for model
- [ ] Load test model w/ test, validation dataset

/cc @johnugeorge

**Comment by swiftdiaries** [comment]
Installation:
Install with the `kfctl_k8s_istio` config succeeds.
Install with the `kfctl_istio_dex` config fails with readiness probe failed for the `authservice-0` in the `istio-system` namespace - not sure if I'm following the right deployment steps with the config.

Notebook Creation:
Fails with User not having permissions to create resources in newly created namespace

**Comment by imnotaqtpie** [comment]
hi, can i work on this issue if it is still available?

**Comment by swiftdiaries** [comment]
Hi
Thank you for the interest!
Yes, we still haven't covered/documented the entire breadth of this issue. 
As of now we only have the [mnist notebook](https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb).
Feel free to pickup individual work items in the Data Scientist or ML Engineer walkthroughs

**Comment by harshalmittal4** [comment]
Hi, I would like to work on this issue, is this issue still available?

**Comment by swiftdiaries** [comment]
Hi @harshalmittal4 
There are a bunch of issues with the [existing mnist notebook](https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb).
This issue has some context: https://github.com/kubeflow/examples/issues/748
It'd be cool if we can get those addressed.
Vanilla k8s does need some additional examples (something other than mnist).

**Comment by swapdebarshi** [comment]
@swiftdiaries I am interested in working on this. Can I pick any item from Infrastructure/ML engineer personas if they are still available?
