### ISSUE TITLE
kubeflow 1.0 - errors while installing knative-serving components

### ISSUE THREAD

**Issue by mfojtak** [kubeflow/kubeflow#4728]
/kind bug

**What steps did you take and what happened:**
Trying to install kubeflow using this manifest on AWS kubernetes cluster:
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml

kfctl fails with this error:
```
ERRO[0672] Permanently failed applying application knative-install; error:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout071915945": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/config-validation?timeout=30s: dial tcp 100.68.22.48:443: connect: connection refused  filename="kustomize/kustomize.go:206"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout071915945": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/config-validation?timeout=30s: dial tcp 100.68.22.48:443: connect: connection refused
```

**What did you expect to happen:**
Install kubeflow successfully

**Anything else you would like to add:**
I looked into knative weebhook pod logs and there's following error:
```
Error loading/parsing logging configuration:configmaps "config-logging" not found
```
There are no config maps in knative-serving namespace.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
- kfctl version: (use `kfctl version`): 1.0-rc3
- Kubernetes platform: (e.g. `minikube`): AWS with kops
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by mfojtak** [comment]
The problem is that I had kubeflow installed previously.
It is known problem that kfctl delete command does not work properly and leaves most of the objects undeleted.
What was blocking the install were objects in validatingwebhookconfigurations and mutatingwebhookconfigurations. I also deleted crds.
closed

**Comment by mfojtak** [comment]
Related to #3767

**Comment by ReyRen** [comment]
@mfojtak 
hello, really need you'd help :)
I occurred the same issue like you. And I tried using `kfctl delete `, and then delete namespaces include "cert-manager", "istio-system", "knative-serving" and "kubeflow"(Solved the Terminating status). However, the "knative-install error" still exist when using `kfctl apply ..` to reinstall. 
#3767 seems not have a clear solution.
Can you please tell me how to recover back to the clean env(previous install kubeflow)?
Thanks

**Comment by ReyRen** [comment]
It seems kfctl-v1.1.0 solved this problem
