### ISSUE TITLE
User None is not authorized to list ... for namespace: anonymous

### ISSUE THREAD

**Issue by mfojtak** [kubeflow/kubeflow#4731]
/kind bug

**What steps did you take and what happened:**
Installed kubeflow 1.0.
While trying to create notebook server I am getting errors like:
```
User None is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: anonymous
```
and
```
User None is not authorized to list .v1.persistentvolumeclaims for namespace: anonymous
```

**What did you expect to happen:**
Successfully create notebook servers

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
- kfctl version: (use `kfctl version`): 1.0-rc3
- Kubernetes platform: (e.g. `minikube`) AWS kops
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by swiftdiaries** [comment]
+1 facing the same issue with the `kfctl_k8s_istio` config

**Comment by swiftdiaries** [comment]
The logs from the jupyter-web-app:
```
"GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
2020-02-05 00:42:38,949 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
```
The decorator function for every action in the Jupyter Web App hits [this function](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py#L41). It seems to derive the `User` from the USERID_HEADER but since the `kfctl_k8s_istio` config runs w/o the EnvoyProxy Filter for setting the USERID_HEADER this fails.

Is this intentional?
Do we want to force users to deploy some sort of Auth in front of the ingressgateway?

**Comment by jlewi** [comment]
@krishnadurai @yanniszark is someone looking into this?

**Comment by krishnadurai** [comment]
@kimwnasptd could we have a flag in subjectAccessReview method is_authorised to disable authorization for no-authentication configurations like kfctl_k8s_istio?

Similar to the DEV_MODE flag? https://github.com/kubeflow/kubeflow/blob/dfd447a5d61068b94c0edcf2d91b1ab9014e489a/components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py#L46-L51

**Comment by jlewi** [comment]
That might work as a short term fix. That approach though has a pretty big downside that it forces us to special case the logic everywhere.

I think the alternative approach that was proposed was that we handle the non-auth case by mapping all users to some account e.g. anonymous.

I think the bug we encountered with that in other places we assume users can be the subject of RBAC rules. So if we just make up the user e.g "anonymous" we will get errors when trying to put that user into an RBAC role.

Could the kfctl_k8s_istio.yaml config just allow the user to hard code what userid to use and ask users to put in an id that is user?

For example, on GKE you would just hardcode something like "jlewi@google.com"

**Comment by yanniszark** [comment]
@jlewi @swiftdiaries I believe that supporting the non auth use case by writing alternate paths in our apps is not a very scalable option long term.

I would propose hardcoding a user, like @jlewi proposes.
This could be done with an Istio rule to add a userid header to every request coming from the istio gateway.

**Comment by jlewi** [comment]
@krishnadurai and @kimwnasptd is someone working on this?

**Comment by swiftdiaries** [comment]
These are the things that I've done:
1. Created an Envoy Filter to add the header to all requests
2. Set the same env var on the jupyter web app

Envoy Filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: no-auth-filter
spec:
  workloadLabels:
    istio: ingressgateway
  filters:
  - filterConfig:
      inlineCode: |
        function envoy_on_response(response_handle)
          response_handle:headers():add("userid_header", "kubeflow-userid")
          response_handle:headers():add("kubeflow-userid", "anonymous")
        end
    filterName: envoy.lua
    filterType: HTTP
    insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: GATEWAY
```

And I can see the headers when I curl the service.
Headers:
```
> GET /_/jupyter HTTP/1.1
.
.
< HTTP/1.1 200 OK
.
.
< userid_header: kubeflow-userid
< kubeflow-userid: anonymous
.
.
```

But the jupyter web app can't see the headers(?)
Env Vars:
```
k exec -it -n kubeflow jupyter-web-app-deployment-544b7d5684-llnv4 env | grep USERID
USERID_HEADER=kubeflow-userid
USERID_PREFIX=
```

Logs:
```
2020-02-06 08:00:49,028 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
10.244.0.8 - - [06/Feb/2020 08:00:49] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
```

**Comment by yanniszark** [comment]
@swiftdiaries I believe that tracing the headers through each hop (with something like tcpdump) will reveal the underlying issue.

**Comment by jlewi** [comment]
@swiftdiaries Is adding response headers what you want to do? Don't you want to add them to the request as the request is what the jupyter web app sees.

I think one thing that could could be helpful to debug this is to write a simple web app (e.g. in flask/go etc...) that just echos back the request and headers. This way you can easily see what headers were on the request.

I suspect ISTIO might have some built in debug functionality or tools to do this.

**Comment by libgy8zli** [comment]
same issue with EKS and kfctl.1.0.0rc

**Comment by jlewi** [comment]
@swiftdiaries any update on this?
/cc @Jeffwan

**Comment by mfojtak** [comment]
I managed to solve this by following steps:
 - installed Istio 1.4.3
 - installed kfctl_istio_dex.yaml with istio-crds and istio-install removed and set clusterRbacConfig to OFF

Now all works and it solves #4733
Should upgrade to Istio 1.4.3 be taken into consideration for 1.0 release?

**Comment by swiftdiaries** [comment]
That's awesome ! Since only the `kfctl_istio_dex.yaml` config uses the `istio-1.3.1` it might be worthwhile to consider upgrading.
WDYT? @yanniszark @krishnadurai 

On another note, this would still be an issue with the `kfctl_k8s_istio.yaml` and I'm trying to set the right headers but I still can't get visibility into how the Jupyter Web App is getting the request.

You're right @jlewi, I was throwing everything at the envoyfilter (request, response) and the one that I pasted here was the last config I used. The requests doesn't seem to play well with the Jupyter Web App as well so I was trying the response.

I did create a simple app that spits out the request as it comes in. It works on local, on Kubernetes as a service but not the virtual service behind the gateway. It's just so weird. I'm still looking into it for possible solutions.

**Comment by krishnadurai** [comment]
@mfojtak which config: 'kfctl_k8s_istio.yaml' or 'kfctl_istio_dex.yaml' is this particular issue referring to?
'kfctl_k8s_istio.yaml' might set up a user named 'anonymous' and is a no-auth based config.

**Comment by mfojtak** [comment]
Sorry, my mistake. This comment was meant for #4721 and #4733

**Comment by krishnadurai** [comment]
The PR kubeflow/manifests#885 looks to address this issue by adding the user anonymous@kubeflow.org.

Here's the status of the UI before the filter is applied:
<img width="1563" alt="Before UI" src="https://user-images.githubusercontent.com/6263389/74100727-e7b72980-4b57-11ea-8bfe-520dd7b40401.png">

After the EnvoyFilter is applied:
<img width="1676" alt="After UI" src="https://user-images.githubusercontent.com/6263389/74100732-f30a5500-4b57-11ea-8ab1-97059ba9cd2c.png">

**Comment by jlewi** [comment]
@krishnadurai it looks like the cherry-pick to 1.0 was merged in kubeflow/manifests#895.

Can you verify that the fix is WAI on the 1.0 branch and then we can close this?

**Comment by Jeffwan** [comment]
Em.. AWS need to make corresponding change as well. We didn't  plan to use `USERID_HEADER`, instead, we considered to use istio claim https://github.com/kubeflow/kubeflow/issues/4746 but seems other projects like jupyter-web-app uses `USERID_HEADER` as well and I am considering if we should add envoyfilter to move to this pattern.

**Comment by Jeffwan** [comment]
User authenticated ALB in AWS will get a header like `x-amzn-oidc-accesstoken` and `x-amzn-oidc-data` need to be decoded and there isn't an user identity header can be used directly. 

1. One solution is add istio policy and decode jwt token and get claim like `name` or `email`
2. Probably decode it earlier in envoy layer and create a `USERID_HEADER ` and istio RBAC doesn't need any changes.

**Comment by jlewi** [comment]
@Jeffwan Do we have a separate issue for the AWS use case?

I think this use case is slightly differently  because its a generic no identity use case. I think in your case you are trying to create a good solution for AWS and that probably merits its own solution (even if it ends up being the same).

**Comment by Jeffwan** [comment]
@jlewi AWS have two manifests, the basic one doesn't have authN and authZ support. I think I will make the same change like `kfctl_k8s_istio.yaml` for this one. The other one with full authN and authZ support, I will create separate issue for it.

**Comment by jlewi** [comment]
Makes sense @Jeffwan

**Comment by piyushcse29** [comment]
Getting this error also on-prem existing cluster installation. Any workaround is highly appreciated!

**Comment by krishnadurai** [comment]
@jlewi I've verified it with:
https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.yaml

The v1.0.0 config needs to be updated:
https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml

<img width="1568" alt="Screenshot 2020-02-13 at 4 44 27 PM" src="https://user-images.githubusercontent.com/6263389/74429255-9e7d1780-4e80-11ea-8461-6c280bafe224.png">

**Comment by jlewi** [comment]
@krishnadurai can you update the 1.0.0 spec?

1. On master run https://github.com/kubeflow/manifests/blob/master/hack/build_kfdef_specs.py 
1. Create a PR to master with updated 1.0 specs
1. Cherry pick that onto the 1.0 branch

Thanks

**Comment by krishnadurai** [comment]
Sure I'll update it

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/manifests/pull/909 

Here's the fix for one aws manifest without auth.

**Comment by hexiaoting** [comment]
I still does not know how to solve this problem.
I use minikube to setup kubernetes, 
use kfctl_k8s_istio.v1.0.0 to deploy kubeflow.

![image](https://user-images.githubusercontent.com/7898329/74512321-fda36080-4f42-11ea-8f75-2c50890da15f.png)

I am new to k8s and kubeflow and istio.
how can i solve this problem, Can you tell me the detail commands, thank you

**Comment by hexiaoting** [comment]
@jlewi @krishnadurai @yanniszark 
The detail commands to solve this problem , Please

**Comment by krishnadurai** [comment]
@hexiaoting could you please look to install with:
https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.yaml

The v1.0.0 config:
https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml

Is not updated yet and I'm working to refresh all v1.0.0 configurations.

**Comment by hexiaoting** [comment]
@krishnadurai 
I tried execute:
```
sudo kfctl delete -f kfctl_k8s_istio.v1.0.0.yaml
sudo kfctl apply -f /home/zhibin/hwt/workspace/kf/kfctl_k8s_istio.yaml
```
But it failed. Here is the logs:
`
esource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-telemetry", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"telemetry\",\"istio\":\"mixer\",\"istio-mixer-type\":\"telemetry\",\"operator.istio.io/component\":\"Telemetry\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.4\",\"release\":\"istio\"},\"name\":\"istio-telemetry\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"telemetry\",\"istio\":\"mixer\",\"istio-mixer-type\":\"telemetry\"}}}}\n"] "creationTimestamp":"2020-02-14T02:59:21Z" "generation":'\x01' "labels":map["app":"telemetry" "istio":"mixer" "istio-mixer-type":"telemetry" "operator.istio.io/component":"Telemetry" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.4" "release":"istio"] "name":"istio-telemetry" "namespace":"istio-system" "resourceVersion":"460197" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-telemetry" "uid":"ff8c44ee-4ed5-11ea-a875-ac1f6b20f7f4"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"telemetry" "istio":"mixer" "istio-mixer-type":"telemetry"]]] "status":map["currentHealthy":'\x01' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x01' "observedGeneration":'\x01']]}
for: "/tmp/kout592155698": PodDisruptionBudget.policy "istio-telemetry" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.]  filename="kustomize/kustomize.go:202"
WARN[0087] Will retry in 5 seconds.                      filename="kustomize/kustomize.go:203"
`

**Comment by krishnadurai** [comment]
@hexiaoting I'm suggesting that you use this config file instead: https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.yaml

Could you please delete your kubeflow deployment and retry again, since you will be changing configurations?

**Comment by hexiaoting** [comment]
Yes, I have delete kubeflow by using `sudo kfctl delete -f kfctl_k8s_istio.v1.0.0.yaml`;
and uninstall istio by exec ` istioctl manifest generate | kubectl delete -f -`

and I tried again by exec:`sudo kfctl apply -f /home/zhibin/hwt/workspace/kf/kfctl_k8s_istio.yaml`.
It still failed.
```
for: "/tmp/kout452548132": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request]  filename="kustomize/kustomize.go:202"
```

**Comment by hexiaoting** [comment]
@krishnadurai How to delete my kubeflow deployment clearly? Is below command enough?
```
sudo kfctl delete -f kfctl_k8s_istio.v1.0.0.yaml
```
After I executed this , I found the result of 
```
sudo kubectl get all --all-namespaces
```
still include kubeflow namespace.

**Comment by krishnadurai** [comment]
Could you please delete the namespace as well?

**Comment by hexiaoting** [comment]
Yes, I exec:
```
sudo kubectl delete namespaces kubeflow
sudo kubectl delete namespaces istio-system
```
but it is terminating all the time. it's not finished in 20 minutes
```
[zhibin@gpu80 istio-1.4.4]$ sudo kubectl get namespaces
NAME              STATUS        AGE
anonymous         Active        106m
cert-manager      Active        21h
default           Active        22h
istio-system      Terminating   38m
knative-serving   Active        21h
kube-node-lease   Active        22h
kube-public       Active        22h
kube-system       Active        22h
kubeflow          Terminating   62m
```

**Comment by krishnadurai** [comment]
@hexiaoting how have you installed istio? Is it through the Kubeflow manifests?

**Comment by shuaibiyy** [comment]
@hexiaoting the solution works for me with this Profile:
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-anonymous
spec:
  owner:
    kind: User
    name: anonymous@kubeflow.org
```
Note: the name for some reason has to be "anonymous@kubeflow.org" (still new to kubeflow).

**Comment by hexiaoting** [comment]
> @hexiaoting how have you installed istio? Is it through the Kubeflow manifests?

Does this command will install istio? 
```
sudo kfctl apply -V -f /home/zhibin/hwt/workspace/kf/kfctl_k8s_istio.yaml
```
maybe I use "sudo istioctl manifest apply --set profile=demo" to install it(I'm not sure)


ps: which command in kubeflow will install istio?

**Comment by hexiaoting** [comment]
> @hexiaoting the solution works for me with this Profile:
> 
> ```
> apiVersion: kubeflow.org/v1beta1
> kind: Profile
> metadata:
>   name: kubeflow-anonymous
> spec:
>   owner:
>     kind: User
>     name: anonymous@kubeflow.org
> ```
> 
> Note: the name for some reason has to be "[anonymous@kubeflow.org](mailto:anonymous@kubeflow.org)" (still new to kubeflow).

how to make this profile work? which command? thank you

**Comment by krishnadurai** [comment]
@hexiaoting the manifest in the config you mention installs istio-ingressgateway as NodePort and port number 31380 as the port exposing http2 for the ingress gateway connection.

Was Istio previously installed in your setup? Or did you make changes after the kfctl installation?

**Comment by shuaibiyy** [comment]
@hexiaoting if you have the profile in a file called `profile.yaml`, you can run it using `kubectl apply -f kf-profile.yaml`. It'd then create a namespace called `kubeflow-anonymous`.

**Comment by hexiaoting** [comment]
> @hexiaoting the manifest in the config you mention installs istio-ingressgateway as a NodePort service and port number 31380 as the port exposing http2 for the ingress gateway connection.
> 
> Was Istio previously installed in your setup? Or did you make changes after the kfctl installation?

I have installed Istio when I install kubeflow the first time using kfctl_k8s_istio_v1.0.0.yaml, And you know I have the auth problem, then you tell me to use kfctl_k8s_istio.yaml to reinstall , so I uninstall it by using 
```
kfctl delete -f /home/zhibin/hwt/workspace/kf/kfctl_k8s_istio_v1.0.0.yaml
and reinstall it using kfctl_k8s_istio.yaml
```

I did not make any change after the kfctl installation.

**Comment by hexiaoting** [comment]
@shuaibiyy Thanks a lot. But now I reinstall kubeflow failed     (crying)

**Comment by hexiaoting** [comment]
> @hexiaoting the manifest in the config you mention installs istio-ingressgateway as a NodePort service and port number 31380 as the port exposing http2 for the ingress gateway connection.
> 
> Was Istio previously installed in your setup? Or did you make changes after the kfctl installation?

I reinstalled everything.
It's Ok now, Thank you

**Comment by hexiaoting** [comment]
> @hexiaoting if you have the profile in a file called `profile.yaml`, you can run it using `kubectl apply -f profile.yaml`. It'd then create a namespace called `kubeflow-anonymous`.

Thanks a lot

**Comment by swiftdiaries** [comment]
For future reference:
This is the [demo script for 1.0](https://bit.ly/38jdNcX) on vanilla kubernetes clusters.

**Comment by ReggieCarey** [comment]
I'm a grateful new user of this open source technology.  Thank you to all contributors.  Releasing instructions (install options without authentication) that result in a failed deployment, does not benefit the community or people's trust in this product suite.  Either we need something like DEX or there is functional anonymous path.  I wish the documentation would be clear about what configuration files will result in a functional platform.
