### ISSUE TITLE
Ready 1.0 Blog and Webinar decks

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4732]
/kind feature

**Why you need this feature:**
Following Kubeflow release process, we need a 1.0 announcement blog post and a 1.0 Webinar deck for the upcoming release.

**Describe the solution you'd like:**
Here are the relevant drafts that authors should review:

- [Blog](https://docs.google.com/document/d/11h3OohwrQtRKtDoH1_0e2tMM_rFh5PBBKJRJTgTfjqg/edit?ts=5e3211c0)
- [Webinar Deck](https://docs.google.com/presentation/d/1B0fwMypAyLBrHlyHIc6zdBk9TDGKZKcbc5XKpr8cVfM/edit#slide=id.g6e6cfc68dd_2_27)

If you are one of the authors and unable to access, please request access.

**Comment by theadactyl** [comment]
Will be live at https://medium.com/p/a3950202751/

**Comment by jlewi** [comment]
@jbottum @theadactyl can we close this issue or should we wait until the webinar is done?
