### ISSUE TITLE
kfctl_istio_dex manifest fails

### ISSUE THREAD

**Issue by mfojtak** [kubeflow/kubeflow#4733]
/kind bug

**What steps did you take and what happened:**
Install kubeflow using kfctl_istio_dex manifest from here:
https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.yaml

kfctl runs successfully but pods in istio-system namespace won't start with:
```
MountVolume.SetUp failed for volume "istio-certs" : couldn't propagate object cache: timed out waiting for the condition
```

**What did you expect to happen:**
Kubeflow installed successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
- kfctl version: (use `kfctl version`): 1.0.0-rc3
- Kubernetes platform: (e.g. `minikube`) AWS kops
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by swiftdiaries** [comment]
Hey @mfojtak 
I got the same error. [This](https://github.com/kubeflow/kfctl/issues/170#issuecomment-582151955) is a fix/workaround for the volume token mount error
Also, if you aren't setting the OIDC flags for the API server then the dex config might fail (Neverminf, if you've set them).

**Comment by mfojtak** [comment]
@swiftdiaries My cluster was bootstrapped by kops which does not allow to change those api server flags. Besides, it is pretty dangerous to tweak them. Also, the feature istio is forcing users to use is beta in k8s.
Is it possible to use older verion of istio? How can I do it in kubeflow?

**Comment by swiftdiaries** [comment]
Unfortunately, Istio forces us to use these for kubeadm created clusters. The next version of Istio removes this dependency.
The OIDC flags are also API server flags. You can set the API server flags on kops with the cluster spec on [these types](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L441).
I understand that these are beta features and likely to change and break. But until the next version of Istio is out, these are the options.

**Comment by yanniszark** [comment]
Hi @mfojtak.
Another option would be to install Istio without SDS.

The steps for that would be something like:
1. Download the Istio version that Kubeflow uses and generate their manifests with SDS disabled.
2. Make your own kustomize package of those manifests.
3. Include it in your KfDef, replacing the current one.

I understand this is a very manual process, so if someone has the time to try it and solve this for everyone it would be awesome.

**Comment by mfojtak** [comment]
@yanniszark well, that sounds like a lot of work. I hoped I would just install kubeflow without having to do any plumbing.
I understand it is a complex system and I respect that.
The only thing I wanted was to show sandbox vanilla kubeflow to my colleagues. And I am struggling bad with just that. 
On the other hand, I am adaptable person and I can improvise. I tried everything:
1. Installing kubeflow on Docker for Desktop - does not work due to memory limitations. ok.
2. Installing kubeflow using kfctl_istio - useless because of #4731
3 installing kubeflow using kfctl_istio_dex - istio screwed up and they will fix it in upcoming version. What I don't uderstand is why kubeflow had to choose the very screwed up version and become hostage of it. 

Are there any other options for me?

**Comment by yanniszark** [comment]
@mfojtak I should mention here that since all config files are using the same Istio version, you will encounter this issue on all of them.

I can see many possible solutions:
* Use [MiniKF](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikf/). This is one of the easiest ways to get started and explore Kubeflow without caring too much about the installation procedure.
* Use v0.7 kfctl_existing_arrikto which uses an older Istio version and doesn't require setting up trusted JWTs. (https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/)
* Use a Kubernetes cluster that allows you to have access to the trusted JWTs feature.

At this point, I would also like to point out that there isn't a v1.0 release yet, so if you try RC branches you can expect that something might be broken.
For a stable release, try v0.7 for now.

**Comment by vivekpd15** [comment]
Have been struggling since 3 days to do the same on a KOPS 1.15 cluster. @mfojtak If you manage to get the trusted JWT feature working, please let me know. I will do the same.

**Comment by mfojtak** [comment]
@vivekpd15 
I took a risk and set flags serviceAccountIssuer and serviceAccountSigningKeyFile.
The kube api server would not come again!
I was lucky to roll back the changes and my cluster is healthy again.
So I would not recommend to tweak the dangerous settings.

**Comment by mfojtak** [comment]
I managed to solve this by following steps:
 - installed Istio 1.4.3
 - installed kfctl_istio_dex.yaml with istio-crds and istio-install removed and set clusterRbacConfig to OFF

Now all works and it solves #4731
Should upgrade to Istio 1.4.3 be taken into consideration for 1.0 release?

**Comment by krishnadurai** [comment]
@mfojtak I've added comments in the issue:
- kubeflow/manifests#959
This might help solve your issue.

**Comment by mfojtak** [comment]
@krishnadurai I think it is better to use latest version of istio witch solves the issue. Setting experimental cluster low level flags is not a solution in my opinion. First of all not everybody is allowed to do that plus it is dangerous.

**Comment by krishnadurai** [comment]
@mfojtak your concerns are valid. We might look to upgrade Istio in the near future; i.e. subsequent releases which will not require us to set these flags.

**Comment by swiftdiaries** [comment]
Added this to the docs website in PR:
https://github.com/kubeflow/website/pull/1779
