### ISSUE TITLE
K8s authrequests filling up

### ISSUE THREAD

**Issue by Kyrremann** [kubeflow/kubeflow#4737]
/kind bug

**What steps did you take and what happened:**
I'm having a problem where Dex is generating a buck load of authrequests, which slowly over time will kill my apiserver. There is already this issue https://github.com/dexidp/dex/issues/1292, but I was curious if other has had similar problems.

For me it seems like it's API calls to Jupyter that needs to log in all the time, as 

> /jupyter/api/namespaces/<namespace>/notebooks Cookie not set, redirecting to login

 is logged several times each seconds (from `authservice`). And this again is coming from the jupyter dashboard (aka centraldashboard).

I would also note that I'm using an external load balancer, where I manually added the node ports. Meaning that we have kubeflow.company.no for the dashboard and kubeflow.company.no:5556 for dex.

**Environment:**

- Kubeflow version: v0.6.2
- kfctl version: v0.6.2-0-g47a0e4c7
- Kubernetes platform: on-prem
- Kubernetes version: v1.15.4
- OS (e.g. from `/etc/os-release`): coreos

**Comment by yanniszark** [comment]
Hi @Kyrremann, thanks for the detailed bug report.
I believe there are two orthogonal issues here:

1. Backend is accumulating too much state. Dex should take measures to prevent that (eg expire time, rate limiting, etc).
2. Something in your cluster is constantly accessing Dex while unauthenticated.

IMO, we should take two measures here:
1. Move the Dex state off of etcd. We don't want Dex crashing the Kubernetes etcd.
2. Pinpoint the reason why so many unauthenticated requests are generated.

You say that you believe those requests are coming from the Central Dashboard.
What lead you to believe that?
I could think of a scenario where the CentralDashboard is open and constantly pings for the Notebooks, gets logged out in the meantime and ends up accumulating a lot of storage in Dex.

**Comment by yanniszark** [comment]
@jtfogarty I believe this is more of an auth issue:

/assign @yanniszark 
/remove-area front-end
/area auth

**Comment by Kyrremann** [comment]
Agree that there is two problem, and moving Dex out would be a safe measurement for future problems.

About #2 which is the main problem for me. The reason for that I'm "blaming"  central is that the jupyter dashboard is talking with the API nonstop to get the list of notebooks:
`https://kubeflow.adeo.no/jupyter/api/namespaces/<namespace>/notebooks`

![image](https://user-images.githubusercontent.com/1830501/73845634-55471b00-4823-11ea-92ed-a1bca773c505.png)

It may also ask for namespaces as your suggestion.

**Comment by jlewi** [comment]
I would expect the Jupyter UI is constantly polling the APIServer in order to get info about notebooks to display.  Its possible that maybe using a watch would be more efficient.

If this is triggering APIServer auth requests, I suspect this might be related to the subject access review checks performed by the notebook UI server.

/cc @kimwnasptd

**Comment by Kyrremann** [comment]
Maybe one of the issues in my setup is that I have different address for issuer and redirect?
What is the normal config?

From my Dex configmap:
```
issuer: https://kubeflow.company.no:5556/dex
staticClients:
- redirectURIs:
   - https://kubeflow.company.no/login/oidc
```

**Comment by Kyrremann** [comment]
just wanted to say that this has been solved in kubeflow v1.

**Comment by yanniszark** [comment]
@Kyrremann how has this been fixed? Do you mean the JWA is not polling as much?
Or that Dex has changed its database?

**Comment by Kyrremann** [comment]
Not sure what fixed it, but Dex manage to clean up its resources, so they don't build up.

**Comment by aaron-arellano** [comment]
this is definitely an issue we are seeing with kubeflow v1.5.0, not fixed at all

**Comment by pashtet04** [comment]
Still an issue with Kubeflow v1.7.0

```
time="2023-10-02T10:40:13Z" level=error msg="garbage collection failed: failed to list auth requests: Get \"https://[10.96.0.1]:443/apis/dex.coreos.com/v1/namespaces/auth/authrequests\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```
