### ISSUE TITLE
KF1.0: No GPU Vendors Listed In UI (GCP)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4738]
/kind bug

Here's a screen shot of the Jupyter UI in a 1.0 cluster
https://github.com/kubeflow/manifests/tree/dd24e6e
![gpu_vendor](https://user-images.githubusercontent.com/777219/73849282-86e9c300-47de-11ea-96d3-f138269e7a3a.png)

No vendors are listed in the GPU window.

@kimwnasptd do the GPU vendors need to be listed in a configmap?

**Comment by kimwnasptd** [comment]
@jlewi yes, I made a [PR](https://github.com/kubeflow/manifests/pull/798) to manifests to resolve this one but I'm having some problems with the tests.

**Comment by jlewi** [comment]
thanks @kimwnasptd replied on the PR

**Comment by jlewi** [comment]
Fixed on master at https://github.com/kubeflow/manifests/tree/30b666f
![master_vendor](https://user-images.githubusercontent.com/777219/73895309-05248480-4834-11ea-9ae7-f70f1e96cdcc.png)

**Comment by jlewi** [comment]
Before we close this is issue I would like to ensure that on GCP a GPU node gets properly provisioned and the pod assigned.

**Comment by jlewi** [comment]
Confirmed this is working.

* Using the new UI I was able to attach a GPU
* NAP automatically created a GPU node pool
* I verified I could import tensorflow and see the GPU

https://github.com/kubeflow/manifests/tree/129b889
[pod.txt](https://github.com/kubeflow/kubeflow/files/4163109/pod.txt)

![tensorflow](https://user-images.githubusercontent.com/777219/73903982-7160b180-484f-11ea-8eed-a0f0ac7ccdf3.png)
