### ISSUE TITLE
Katib training containers should wait until istio proxy will be ready

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/kubeflow#4742]
/kind bug

**What steps did you take and what happened:**
To solve this problem https://github.com/kubeflow/kubeflow/issues/4730#issuecomment-582653698 I had to add 1-2 minutes delay before running `request` to download mnist dataset in the training container.
The problem was that istio proxy container was not ready when training container ran request.

Training containers should somehow wait until istio proxy will be ready.

@krishnadurai proposed specified `istio-injection: disabled` annotation for the Profile namespace where user submits Katib Experiments.
/cc @johnugeorge @jlewi @gaocegege @hougangliu

**Comment by krishnadurai** [comment]
@andreyvelich A minor correction to the issue header comment.
The pods for the experiment should have the annotation 'istio-injection': 'disabled' rather than the namespace. So the controller creating the pods might want to add these annotations.

**Comment by jlewi** [comment]
Istio reference https://istio.io/docs/setup/additional-setup/sidecar-injection/#understanding-what-happened
