### ISSUE TITLE
Cannot get into the notebook-controller-deployment POD.

### ISSUE THREAD

**Issue by UllasShanthakumar** [kubeflow/kubeflow#4743]
/kind bug

**What steps did you take and what happened:**
I have setup a Ubuntu VM on OpenStack and deployed Kubeflow on it.
I am not able to get into notebook controller deployment pod.

**I get the following error :** 
kubectl -n kubeflow exec -it notebook-controller-deployment-7645699bdb-gbbnk bash
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "f05eed1125abbc9a106d737e66af43ec3c6c461a546dbe3a561ff73886b5421f": OCI runtime exec failed: exec failed: container_linux.go:345: **starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown**

Its the same case with any other shell as well.

**What did you expect to happen:**
Should have been able to get into POD

**Anything else you would like to add:**

**Able to get describe pod** 
kubectl -n kubeflow describe pod notebook-controller-deployment-7645699bdb-gbbnk
Name:         notebook-controller-deployment-7645699bdb-gbbnk
Namespace:    kubeflow
Priority:     0
Node:         myinstall/10.0.0.3
Start Time:   Tue, 04 Feb 2020 09:23:01 +0000
Labels:       app=notebook-controller
              app.kubernetes.io/component=notebook-controller
              app.kubernetes.io/instance=notebook-controller-v0.7.1
              app.kubernetes.io/managed-by=kfctl
              app.kubernetes.io/name=notebook-controller
              app.kubernetes.io/part-of=kubeflow
              app.kubernetes.io/version=v0.7.1
              kustomize.component=notebook-controller
              pod-template-hash=7645699bdb
Annotations:  <none>
Status:       Running
IP:           10.1.82.31
IPs:
  IP:           10.1.82.31
Controlled By:  ReplicaSet/notebook-controller-deployment-7645699bdb
Containers:
  manager:
    Container ID:  containerd://a65c602ad64cdf62a94db0781c50500d2965eb0ba51e37829530acbeabf7418d
    Image:         gcr.io/kubeflow-images-public/notebook-controller@sha256:6490f737000bd1d2520ac4b8cbde2b09749cdb291b1967ddda95d05131db49db
    Image ID:      gcr.io/kubeflow-images-public/notebook-controller@sha256:6490f737000bd1d2520ac4b8cbde2b09749cdb291b1967ddda95d05131db49db
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    State:          Running
      Started:      Tue, 04 Feb 2020 09:23:10 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      USE_ISTIO:      true
      ISTIO_GATEWAY:  kubeflow/kubeflow-gateway
      POD_LABELS:     gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from notebook-controller-service-account-token-x2lw7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  notebook-controller-service-account-token-x2lw7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  notebook-controller-service-account-token-x2lw7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Note :** I am able to get the logs for this pod.

**My System configuration :** 
VCPU - 8
RAM 16GB

**Environment:**

- Kubeflow version: build version v1beta1

- kfctl version: v0.7.1-2-g55f9b2a

- Kubernetes platform: Microk8s. Installed through snap --classic version.

- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

Let me know if i need to furnish any further details.

**Comment by jlewi** [comment]
This is working as intended. We are using distroless images.
https://github.com/GoogleContainerTools/distroless

I don't think these images contain bash or other shell environment.
