### ISSUE TITLE
How to enable to run sudo from kubeflow jupyter notebook terminal

### ISSUE THREAD

**Issue by jobvarkey** [kubeflow/kubeflow#4744]
Hi,

I am running Kubeflow v0.70.
In the Kubeflow jupyter nootbook terminal I need to switch to root for installing some pip packages but the sudo command is asking for jovyan password which i don't have.

$ sudo su -
[sudo] password for jovyan:

Does anyone know how to enable sudo in kubeflow jupyter notebook?

Thanks,
Job Varkey

**Comment by yanniszark** [comment]
Hi @jobvarkey!
Installing packages with pip should be done with the --user option.
This way, they end up in your workspace volume which isn't affected even if the Pod restarts.

**Comment by jobvarkey** [comment]
Hi Yannis,

Thanks for the update. The --user and virtual environment options worked..
