### ISSUE TITLE
Notebook Servers cant pull docker image from private registry.

### ISSUE THREAD

**Issue by UllasShanthakumar** [kubeflow/kubeflow#4745]
/kind question

**Question:**
Hi Team,

I would like to know the configurations required to use our custom image which is hosted in our private docker registry. Do we have a step by step procedure which needs to be followed to obtain the same.
When i use a Custom image while launching a Notebook Servers we are getting **ImagePullBackOff** error. The complete path of the image is provided.
I am not sure about what settings has to updated in-order to point the Notebook server to out private docker registry.

Also request to provide a sample Custom image's Docker file to cross verify the same.

**My System configuration :**
VCPU - 8
RAM 16GB

**Environment:**

Kubeflow version: build version v1beta1

kfctl version: v0.7.1-2-g55f9b2a

Kubernetes platform: Microk8s. Installed through snap --classic version.

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

Let me know if any further details needs to be furnished.

**Comment by speaknowpotato** [comment]
hi, is there any update on this issue?
