### ISSUE TITLE
Dashboard deployed on eks does not show manage contributors in navigation

### ISSUE THREAD

**Issue by Julianxo** [kubeflow/kubeflow#4748]
/kind bug

**What steps did you take and what happened:**
I followed the tutorial for AWS setup on this page https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/.
I also followed this tutorial to setup TLS and AWS Cognito.

I can register users and i can login (logout is not possible because of a missing logout button).
But i do not see the "Manage Contributers" link in the menu like mentioned here.
https://www.kubeflow.org/docs/aws/authentication/

**What did you expect to happen:**
I except the "Manage Contributers" to show up. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I found a similar bug report here https://github.com/kubeflow/kubeflow/issues/4113
But I did not get how this was solved. 

**Environment:**

- Kubeflow version: I tested 0.7.0 and 0.7.1
- kfctl version: (use `kfctl version`): v0.7.1-2-g55f9b2a
- Kubernetes platform: (e.g. `minikube`): AWS EKS
- Kubernetes version: (use `kubectl version`): Client 1.16, Server 1.14
- OS (e.g. from `/etc/os-release`): macOS Mojave 10.14.6

**Comment by Jeffwan** [comment]
@Julianxo Hi AWS doesn't have this supported in 0.7, we will resolve this in 1.0 which will be officially released soon. If people still want to use it in 0.7, I will consider to cherry-pick back the changes

**Comment by Julianxo** [comment]
I can confirm that it is fixed in version 1.0
