### ISSUE TITLE
Profile controller uses project id from user sa for identity namespace

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/kubeflow#4749]
/kind bug

**What steps did you take and what happened:**
We have teams in different gcp projects are using a shared Kubeflow cluster.  When I try to use a gcp service account from a different project for `gcpServiceAccount` field in a user's profile, profile-controller throws an error: 
```Identity namespace does not exist (${PROJECT_ID}.svc.id.goog)```

It seems the project id used in identity namespace is inferred from user's gcp service account. https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/plugin_workload_identity.go#L54

**What did you expect to happen:**
I think it might make more sense to use the id of the project where Kubeflow cluster was created in.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): 0.7.1
- Kubernetes platform: (e.g. `minikube`): GKE
- Kubernetes version: (use `kubectl version`): v1.14.8-gke.33
- OS (e.g. from `/etc/os-release`): mac OS Mojave v10.14.6

**Comment by jlewi** [comment]
I don't know that we will fix this issue.

Per kubeflow/manifests#1136 I think we are moving away from profiles and bootstrapping namespaces using GitOps and declarative packages.

We are also moving to using Cloud Config Connector.
https://github.com/kubeflow/gcp-blueprints

So in this new world if you wanted to configure which GCP service account is bound to a KSA you would just modify the K8s resource and if necessary create an IAMPolicyMember to grant the appropriate workload identity on the GCP SA.

**Comment by daikeshi** [comment]
Tha's OK. We currently use a fork of profile controller (with the fix) as the workaround. 
We will need some migration after Kubeflow deprecates profile in the future, but it should be fine.

**Comment by jlewi** [comment]
Removing from 1.1 because I don't think anyone is working on it.

**Comment by daikeshi** [comment]
Hey @jlewi, the fix I made has already been merged in master with this PR https://github.com/kubeflow/kubeflow/pull/4754. I think we just need to publish a new image and update the deployment manifest. Will that be automatically taken care of in Kubeflow 1.1 release so we can remove our fork? Let me know if there's anything I can help with.

**Comment by jlewi** [comment]
kubeflow/kubeflow#5067 is tracking the release of the profile controller for KF 1.1
