### ISSUE TITLE
Notebook ReadWriteMany PVC option doesn't work

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#4757]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm trying gh-summarization-issue example for KF v1.0-rc4 with gcp_iap_v1.0.0.yaml.

[Distributed training needs ReadWriteMany PVC](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/02_distributed_training.md) The notebook UI supports creating ReadWriteMany volume directly but it failed with this message:

```
Name:          gh-issue-sumarization-vol
Namespace:     kubeflow-zhenghui
StorageClass:  standard
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason              Age                  From                         Message
  ----       ------              ----                 ----                         -------
  Warning    ProvisioningFailed  34s (x9 over 4m17s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
Mounted By:  gh-issue-sumarization-0
```

**What did you expect to happen:**
The volume should be created. (Or there is no such option and users can create one using `kubectl`)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): v1.0-rc4
- Kubernetes platform: (e.g. `minikube`): GCP
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): MacOS

**Comment by zhenghuiwang** [comment]
<img width="616" alt="Screen Shot for notebook creation" src="https://user-images.githubusercontent.com/8263977/74289082-fa119e80-4ce2-11ea-8bc1-e11fc2d2ae5e.png">

**Comment by jlewi** [comment]
I think there are two separate issues here

1. The Jupyter web app should not let people mount volumes with ReadWriteMany if that is not supported
1. Telling people how to run GitHub issue summarization with distributed training

Lets use this option to track the first and use a separate issue for GH issue summarization.

Can the UI query the APIServer to determine what modes a PVC supports? When creating a New volume we are relying on the default storage class. Its not clear that this information is available progrmatically. Here's the storage class for GCP pd.

```
allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2020-02-10T19:08:22Z"
    labels:
      addonmanager.kubernetes.io/mode: EnsureExists
      kubernetes.io/cluster-service: "true"
    name: standard
    resourceVersion: "308"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
    uid: b4cf6885-4c38-11ea-86b4-42010a8e01a3
  parameters:
    type: pd-standard
  provisioner: kubernetes.io/gce-pd
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
```

Does pd-standard imply that it should only be read write once?
One option would be to map known provisioner types to the mode?

**Comment by jlewi** [comment]
kubeflow/examples/issues/734 for GitHub Issue Summarization example

**Comment by jlewi** [comment]
@kimwnasptd WDYT?

**Comment by jlewi** [comment]
ping @kimwnasptd  ?

Removing from KF 1.1 because it looks like no one is working on this so I don't think its going to get fixed.

**Comment by kimwnasptd** [comment]
@jlewi forgot to reply to this one,

From what I know, the approach to permit users to create PVCs with a mode that is not supported from a storage class (the default with current JWA) is not feasible. Since with the current k8s API we don't have a way to deduce what access modes a storage class supports.

What I would propose would be the following:
1. Allow users to select the storage class for their PVCs in JWA
2. Make sure to always surface Notebook errors with JWA

So if a PVC would not be created then users will see that from the UI and use a proper StorageClass.
@jlewi WDYT?

**Comment by jlewi** [comment]
LGTM
