### ISSUE TITLE
Enable multi-user authorization for AWS

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4761]
/kind feature

**Why you need this feature:**
From kubeflow 0.5, AWS add ALB authentication via Cognito or OIDC. At that time we have not finish authorization part. 

After ALB load balancer authenticates a user successfully, it sends the user claims received from the IdP to the target. The load balancer signs the user claim so that applications can verify the signature and verify that the claims were sent by the load balancer. Applications that require the full user claims can use any standard JWT library to verify the JWT tokens.

```
- x-amzn-oidc-accesstoken
The access token from the token endpoint, in plain text.

- x-amzn-oidc-identity
The subject field (sub) from the user info endpoint, in plain text.

- x-amzn-oidc-data
The user claims, in JSON web tokens (JWT) format.
```

Existing profiles controllers, central-dashbaord and jupyter-notebook and istio rbac use `userid-header` to validate the user. 

There're a few options to resolve this problem.
1. Use community's solution - dex solution. In this case, no need to do authentication on ALB ingress controller side but we will lose some benefits from ALB like CIDR filter, DDOS protection, etc. https://github.com/kubeflow/manifests/issues/652#issuecomment-582639739

2. Add istio policy and then istio rbac can get claim from `request.auth.claims[email]`, the problem of this solution is we have to authenticate request another time and ingressgateway level auth doesn't work. We probably need to add policy for different services (notebook, etc) which is too complicated. 

3. Istio doesn't have very straightforward way to modify headers, we have to use an adaptor and decode JWT code in the handler, then retrieve the claim we need and append to the headers. 

**Describe the solution you'd like:**
I determine to use 3rd to resolve the problem.

**Comment by jlewi** [comment]
@Jeffwan Is this targeted for 1.0? If so what's the likelihood all the changes will land by end of today?

**Comment by Jeffwan** [comment]
@jlewi 

It's ready and I tested it's working fine on my side. https://github.com/kubeflow/manifests/pull/908 adds extra component only used by aws. Should be very safe.

**Comment by devgrok** [comment]
That's a much more complete solution than what I cobbled together.

I had originally thought I could trick istio into decoding the `x-amzn-oidc-data` header by serving a hard-coded jkws,json for the LoadBalancer only to discover I was reading the 1.3/1.4 istio documentation and kubeflow currently uses 1.1.6. 
I had thought that wasn't possible to configure that version istio/envoy to use the ALB's encoded token (or probably i didn't think it is was practical). I'd be interested to see the implementation of the aws-istio-authz-adaptor to see how you achieved it - where is the code for that image checked in?

As an aside, does istio 1.3 make it easier to implement this? (or was I mis-reading the docs for it?)

**Comment by devgrok** [comment]
It might be a good idea to delete https://github.com/kubeflow/manifests/blob/master/aws/istio-ingress/base/istio-policy.yaml -- as it's not included in the kustomize build (it confused me a few times till I face palmed when I realised it wasn't being used).
I'm guessing that your filter does the equivalent (albeit more) of what that policy defines.

**Comment by Jeffwan** [comment]
@devgrok Hi, Yeah, I didn't apply `istio-policy.yaml`. It was using before but we didn't have authorization at that time. Istio RBAC requires you to use istio policy to extract claims. There's no support to use `request.auth.claims[email]` with a custom header.  We can not get ride `istio-policy.yaml` in this solution. The side affect is we have two layer authentication,  ALB (1st time) -> istio-gateway -> istio-policy to services (2nd). It's also hard to control policies for different services (we need namespaces level policy or istio-gateway level, based on my test, it's not working)

`aws-istio-authz-adaptor` code is not there, actually it's pretty simple, just decode token and return user claim email. I am thinking maybe this is generic enough and try to host in somewhere else like `github.com/aws` or  `github.com/awslabs`. Please find me on Slack `Jiaxin Shan` and I can share code with you first. 
 
Community has 1.3.1 istio and most of the manifest doesn't use it. I will go track if there's easier solution in newer istio version

**Comment by Jeffwan** [comment]
PR has been merged and I address few issues for authz adaptor. 
OIDC and Cognito have been tested and it's pretty stable. We can close this story now.

**Comment by SarathChandran** [comment]
After installing v1.0 manifest with congnito I am facing the following error

Related issues on earlier versions didn't help : https://github.com/kubeflow/kubeflow/issues/4718 
https://github.com/kubeflow/kubeflow/issues/4540


```
> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve


> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
Unable to fetch Application information: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'applications.app.k8s.io is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "applications" in API group "app.k8s.io" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { group: 'app.k8s.io', kind: 'applications' },
  code: 403 }
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
"other" is not a supported platform for Metrics
Using Profiles service at http://profiles-kfam.kubeflow:8081/kfam
Server listening on port http://localhost:8082 (in production mode)
```

**Comment by Jeffwan** [comment]
@SarathChandran  Can you ok the central dashboard successfully? I remember this issues exist and not related to multi user

**Comment by SarathChandran** [comment]
Yes i am able to open central dashboard with port forwarding..but not with cognito signin

**Comment by Jeffwan** [comment]
could you delete this profile and try to see if you are able to login with anonymous?

**Comment by SarathChandran** [comment]
Tried already.. same result

**Comment by Jeffwan** [comment]
> Tried already.. same result

Can you share your cognito settings? normally it's setting issue leads to `An error was encountered with requested page`. It would be helpful for us to debug if you can share `istio-ingress` annotations and your cognito callback url.

**Comment by SarathChandran** [comment]
```
alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:eu-west-1:<account_id>:userpool/eu-west-1_xxxxxx","UserPoolClientId":"<client_token>",
      "UserPoolDomain":"xxxx.auth.eu-west-1.amazoncognito.com"}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:<account_id>:certificate/xxxxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-xxxxxx, subnet-xxxxxx,
      subnet-xxxxx
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/auth-idp-cognito":"{\"UserPoolArn\":\"arn:aws:cognito-idp:eu-west-1:<account_id>:userpool/eu-west-1_xxxx\",\"UserPoolClientId\":\"<client_token>\", \"UserPoolDomain\":\"xxxx.auth.eu-west-1.amazoncognito.com\"}","alb.ingress.kubernetes.io/auth-type":"cognito","alb.ingress.kubernetes.io/certificate-arn":"arn:aws:acm:eu-west-1:<account_id>:certificate/xxxxxxxx","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTPS\":443}]","alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/subnets":"subnet-xxxx, subnet-xxxx, subnet-xxxx","kubernetes.io/ingress.class":"alb"},"labels":{"kustomize.component":"istio-ingress"},"name":"istio-ingress","namespace":"istio-system"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"istio-ingressgateway","servicePort":80},"path":"/*"}]}}]}}
    kubernetes.io/ingress.class: alb
```

And callback url: https://xxxx-istiosystem-istio-xxxx.eu-west-1.elb.amazonaws.com/oauth2/idresponse

**Comment by SarathChandran** [comment]
Hi @Jeffwan, is there any update on this issue?

**Comment by Jeffwan** [comment]
@SarathChandran  In my setting, I use short domain name as `UserPoolDomain` name, 

`{"UserPoolDomain":"kubeflow-testing"}'

![image](https://user-images.githubusercontent.com/4739316/76390478-b2eeeb80-632a-11ea-8a32-6f9e01523aa0.png)

Can you try this?

**Comment by SarathChandran** [comment]
I tried just the domain name. Also tried custom domain auth.<subdomain>.<domain>.com. But same result. I could see a related log though while re-applying kfclt 

`2020/03/12 16:38:59 well-defined vars that were never replaced: origin-header`
 
How could i fix this from happening?

**Comment by Jeffwan** [comment]
> I tried just the domain name. Also tried custom domain `auth.<subdomain>.<domain>.com`. But same result. I could see a related log though while re-applying kfclt
> 
> `2020/03/12 16:38:59 well-defined vars that were never replaced: origin-header`

This is ok. Not a problem. The problem is we defined `origin-header` variable but didn't use it here https://github.com/kubeflow/manifests/blob/v1.0.0/aws/aws-istio-authz-adaptor/base/instance.yaml. 


Do you mind to share the screenshot of your coginito setting? Please hide the confidential part

**Comment by SarathChandran** [comment]
![ap-client](https://user-images.githubusercontent.com/4623218/76621646-587fa600-6549-11ea-982c-b83ad39ddda8.png)
![cust-domain](https://user-images.githubusercontent.com/4623218/76621650-5a496980-6549-11ea-9f93-dacdb99d1ca5.png)
![kf-config](https://user-images.githubusercontent.com/4623218/76621712-78af6500-6549-11ea-8c02-3785bff62ed6.png)

**Comment by Jeffwan** [comment]
@SarathChandran Thanks. I compare with my setting, I think the only thing different is you use your own domain. I think the setting is correct. 


1. Have you ever tried to use Cognito domain? 

This is my setting. 
![image](https://user-images.githubusercontent.com/4739316/76654752-f747da80-6528-11ea-8554-ec606a99df7f.png)

```
cognitoUserPoolDomain: kubeflow-testing
```

2. Do you have certificate in N.Virginia for your own domain?  Because Cognito requires a certificate in N.Virginia in order to have a custom domain for a user pool.

Check here for more details https://www.kubeflow.org/docs/aws/aws-e2e/#certificate-manager

**Comment by SarathChandran** [comment]
Hi @Jeffwan , I have tried both step 1 and 2

**Comment by SarathChandran** [comment]
Hi @Jeffwan , i finally figured the issue.. it was to do with callback url: https://www.kubeflow.org/docs/aws/custom-domain/#using-custom-domain 

Please accept the PR: https://github.com/kubeflow/website/pull/1815/files

It was proper in the screenshots though.

**Comment by Jeffwan** [comment]
@SarathChandran Feel so sorry for the confusion. I appreciate your help fix the doc. It looks good to me and waiting for sarah to approve that. Please sign CLA.

**Comment by SarathChandran** [comment]
I have signed the CLA. Can i get an invite to kubeflow slack channel?

**Comment by Jeffwan** [comment]
> I have signed the CLA. Can i get an invite to kubeflow slack channel?

please use this link for this moment.
https://join.slack.com/t/kubeflow/shared_invite/zt-cpr020z4-PfcAue_2nw67~iIDy7maAQ

**Comment by ykeuter** [comment]
Not sure if this is the right place to ask, but I am trying to get authorization to work on AWS (with OIDC). I followed the configuration as in https://www.kubeflow.org/docs/aws/authentication-oidc/ using kfctl_aws_cognito.v1.0.2.yaml (and v1.0-branch). My spec looks like this:
```
spec:
      auth:
        oidc:
          certArn: <certificat arn>
          oAuthClientId: <client id>
          oAuthClientSecret: <client secret>
          oidcAuthorizationEndpoint: https://<oidc>/connect/authorize
          oidcIssuer: https://<oidc>
          oidcTokenEndpoint: https://<oidc>/connect/token
          oidcUserInfoEndpoint: https://<oidc>/connect/userinfo
      region: eu-north-1
      addons:
      - fluentd-cloud-watch
      roles:
      - data-science-kubeflow-worker-role
```
The authentication part seems to be working correctly, but I get this message when calling the ALB hostname:
`PERMISSION_DENIED:authzadaptor-handler.handler.istio-system:`
What am I missing?

**Comment by jlewi** [comment]
@ykeuter commenting on closed issues is generally not a good idea. If your having problems please open a new issue and if you think its related to closed issues you can reference the issue in the closed issue
