### ISSUE TITLE
Failed v1.0 install - problems with cert-manager

### ISSUE THREAD

**Issue by aheeruru** [kubeflow/kubeflow#4762]
/kind question

**Question:**
Hello.

I try to install kubeflow 1.0 on my own kubernetes cluster, but failed.
maybe trouble is in webhook.cert-manager.

kfctl try repeatedly calling webhook and then finished with error.

help..

k8s version : v1.15.7

$ kfctl version
kfctl v1.0-rc.3-1-g24b60e8

$ kfctl apply -V -f ./kfctl_k8s_istio.v1.0.0.yaml

configmap/cert-manager-parameters unchanged
service/cert-manager unchanged
service/cert-manager-webhook unchanged
deployment.apps/cert-manager unchanged
deployment.apps/cert-manager-cainjector configured
deployment.apps/cert-manager-webhook configured
apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
application.app.k8s.io/cert-manager configured
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0273] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout114147475": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client  filename="kustomize/kustomize.go:202"
WARN[0273] Will retry in 25 seconds.                     filename="kustomize/kustomize.go:203"
......
apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
application.app.k8s.io/cert-manager configured
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0375] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout124508159": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client  filename="kustomize/kustomize.go:202"
WARN[0375] Will retry in 35 seconds.             

.....
ERRO[0609] Permanently failed applying application cert-manager; error:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client  filename="kustomize/kustomize.go:206"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client

**Comment by jlewi** [comment]
@krishnadurai @yanniszark @cliveseldon Do you have any idea what's going on here?

```
Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client filename="kustomize/kustomize.go:202"
```


@aheeruru is cert-manager already deployed in your cluster by some chance?

**Comment by cliveseldon** [comment]
This seems to be the issue: https://github.com/jetstack/cert-manager/issues/1964

**Comment by yantriks-edi-bice** [comment]
I tried to upgrade from 0.7.x to 1.0.0 (using 1.0 branch kfdef for GCP and IAP) and got the following:

configmap/cert-manager-parameters unchanged
service/cert-manager unchanged
service/cert-manager-webhook unchanged
deployment.apps/cert-manager unchanged
deployment.apps/cert-manager-cainjector configured
deployment.apps/cert-manager-webhook configured
apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
application.app.k8s.io/cert-manager configured
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0243] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout895674883": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"

**Comment by aheeruru** [comment]
@yantriks-edi-bice 
Same. I used 0.7. now i try to upgrade 1.0

@jlewi 

At first I just read pod status 'Running'.
After describe pod, I found that failed volume mount.

but there is no difference 0.7's cert-manager yaml and 1.0's cert-manager yaml.
why does error occur ? Is there something to do additionally such as creating volume ?


$ kubectl get po -n cert-manager

kubectl get po -n cert-manager -w
NAME                                     READY   STATUS    RESTARTS   AGE
cert-manager-5d849b9888-mknpq            1/1     Running   0          3m1s
cert-manager-cainjector-dccb4d7f-fqvlx   1/1     Running   0          3m1s
cert-manager-webhook-695df7dbb-kbv4m     1/1     Running   0          3m1s



=============================================================

kubectl describe po -n cert-manager cert-manager-webhook-695df7dbb-kbv4m

Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    3m31s                  default-scheduler  Successfully assigned cert-manager/cert-manager-webhook-695df7dbb-kbv4m
  Warning  FailedMount  2m13s (x8 over 3m17s)  kubelet, MountVolume.SetUp failed for volume "certs" : secret "cert-manager-webhook-tls" not found
  Warning  FailedMount  74s                    kubelet, Unable to mount volumes for pod "cert-manager-webhook-695df7dbb-kbv4m_cert-manager(1f8c72aa-0a74-4814-a998-8b5a92de8f2e)": timeout expired waiting for volumes to a                                               ttach or mount for pod "cert-manager"/"cert-manager-webhook-695df7dbb-kbv4m". list of unmounted volumes=[certs]. list of unattached volumes=[certs cert-manager-webhook-token-9vm5x]
  Normal   Pulled       60s                    kubelet, Container image "quay.io/jetstack/cert-manager-webhook:v0.11.0" already present on machine
  Normal   Created      60s                    kubelet, Created container cert-manager
  Normal   Started      59s                    kubelet, Started container cert-manager

**Comment by jlewi** [comment]
@yantriks-edi-bice and @aheeruru Are we talking about a single issue or multiple issues? Talking about multiple issues on the same thread is very confusing and difficult to debug.

* The [original comment](https://github.com/kubeflow/kubeflow/issues/4762#issue-564552156) indicated that kfctl_k8s_istio.v1.0.0.yaml was being used
  * Were you deploying on a cluster with KF already installed?
  * Was this a self managed cluster?
  * As @cliveseldon points out that error looks like which suggests a misconfigured cluster jetstack/cert-manager#1964

* The [second comment] from @yantriks-edi-bice looks like a different error
   * Are you running on GCP on a GKE cluster? If so then that is a very different configuration and a different issue from the previous one

* The [third comment](https://github.com/kubeflow/kubeflow/issues/4762#issuecomment-586052221) is an entirely different error message from the previous two
   * I'm unclear what the setup in this case is.
   * Was this an existing cluster running 0.7?
   * How was this Kubernetes cluster deployed?

**Comment by aheeruru** [comment]
@jlewi 
oh, I mean I just face error while try to upgrade 0.7 to 1.0 like yantriks-edi-bice.
My cluster is own cluster.

answer to your question.

The original comment indicated that kfctl_k8s_istio.v1.0.0.yaml was being used

Were you deploying on a cluster with KF already installed?
-> yes. 0.7 was installed. But deleted it before install v1.0. 
-> I delete 0.7's all resources containing v.0.7.0 crd. 
 
Was this a self managed cluster?
-> yes. my own k8s cluster deployed at physical machine. not cloud (such as aws, azure...)
 

The third comment is an entirely different error message from the previous two

Was this an existing cluster running 0.7?
-> no, I deleted it.
How was this Kubernetes cluster deployed?
-> I deployed it my self ref k8s deploy guide.


In my opinion, first comment and third commend is about same problem.
because first error output said 
"https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client"

third said
cert-manager cert-manager-webhook pod's couldn't bind Volume.


I checked yaml about cert-manager, found this.

/opt/kubeflow/kustomize/cert-manager# grep -r cert-manager-webhook-tls
base/deployment.yaml:          - --webhook-serving-secret=cert-manager-webhook-tls
base/deployment.yaml:          secretName: cert-manager-webhook-tls
base/api-service.yaml:    cert-manager.io/inject-ca-from-secret: "cert-manager/cert-manager-webhook-tls"

So, I thought first error occurred by third error.
I don't know well about cert-manager. 
But log seems to volume mount failed, couldn't generate secret. so api-service which use secret was going wrong. 
Finnaly, error occurred when call this uri. https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client.


Anyway problem is in cert-manger as you said.
I check my cluster again and jetstack/cert-manager#1964 link which you gave me.

If solve it, I comment here.

Thanks :)

**Comment by jlewi** [comment]
Thanks. I wonder if cert-manager is trying to generate its own certificate and having problems.

Is it possible you have multiple deployments of cert-manager on your cluster? Or that you didn't fully delete the previous install of cert-manager?

**Comment by cliveseldon** [comment]
This cert-manager PR might help solve these things on release of v0.14 of cert-manager: https://github.com/jetstack/cert-manager/pull/2574 which fixes https://github.com/jetstack/cert-manager/issues/2537

**Comment by aheeruru** [comment]
Solve.

there are several reasons.

first,
apiservice and validatingwebhookconfigurations.admissionregistration.k8s.io not deleted even if namespace deleted.
maybe during delete ns, something is wrong.

second,
kube-apiserver uses proxy.
After deleting proxy config, it works well.

But our environment must use proxy. 
I try to find solution. If you have know-how about it, please notice me.

Anyway I close the issue.

Thank you for your help :)

**Comment by yantriks-edi-bice** [comment]
> @yantriks-edi-bice and @aheeruru Are we talking about a single issue or multiple issues? Talking about multiple issues on the same thread is very confusing and difficult to debug.
> 
> * The [second comment] from @yantriks-edi-bice looks like a different error
>   
>   * Are you running on GCP on a GKE cluster? If so then that is a very different configuration and a different issue from the previous one

Yes, I'm running on GCP on a GKE cluster. Wasn't sure if it was the same or an entirely different issue. Will open a new one.

**Comment by thavlik** [comment]
Ran into this problem on AKS. Unable to install.

**Comment by samithaj** [comment]
Error  in local k8 (installed with kind) 
`validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0110] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout245589381": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
WARN[0110] Will retry in 9 seconds.                      filename="kustomize/kustomize.go:203"
`

**Comment by nzhang0430** [comment]
> /kind question
> 
> **Question:**
> Hello.
> 
> I try to install kubeflow 1.0 on my own kubernetes cluster, but failed.
> maybe trouble is in webhook.cert-manager.
> 
> kfctl try repeatedly calling webhook and then finished with error.
> 
> help..
> 
> k8s version : v1.15.7
> 
> $ kfctl version
> kfctl v1.0-rc.3-1-g24b60e8
> 
> $ kfctl apply -V -f ./kfctl_k8s_istio.v1.0.0.yaml
> 
> configmap/cert-manager-parameters unchanged
> service/cert-manager unchanged
> service/cert-manager-webhook unchanged
> deployment.apps/cert-manager unchanged
> deployment.apps/cert-manager-cainjector configured
> deployment.apps/cert-manager-webhook configured
> apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
> application.app.k8s.io/cert-manager configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
> WARN[0273] Encountered error applying application cert-manager: (kubeflow.error): Code 500 with message: Apply.Run Error error when creating "/tmp/kout114147475": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client filename="kustomize/kustomize.go:202"
> WARN[0273] Will retry in 25 seconds. filename="kustomize/kustomize.go:203"
> ......
> apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
> application.app.k8s.io/cert-manager configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
> WARN[0375] Encountered error applying application cert-manager: (kubeflow.error): Code 500 with message: Apply.Run Error error when creating "/tmp/kout124508159": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client filename="kustomize/kustomize.go:202"
> WARN[0375] Will retry in 35 seconds.
> 
> .....
> ERRO[0609] Permanently failed applying application cert-manager; error: (kubeflow.error): Code 500 with message: Apply.Run Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client filename="kustomize/kustomize.go:206"
> Error: failed to apply: (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize: (kubeflow.error): Code 500 with message: Apply.Run Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client
> Usage:
> kfctl apply -f ${CONFIG} [flags]
> 
> Flags:
> -f, --file string Static config file to use. Can be either a local path:
> export CONFIG=./kfctl_gcp_iap.yaml
> or a URL:
> export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml
> export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.0.yaml
> export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml
> export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_k8s_istio.0.7.0.yaml
> kfctl apply -V --file=${CONFIG}
> -h, --help help for apply
> -V, --verbose verbose output default is false
> 
> failed to apply: (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize: (kubeflow.error): Code 500 with message: Apply.Run Error error when creating "/tmp/kout202869655": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s: x509: certificate is valid for kubernetes.default.svc, not apiserver-loopback-client


$ kfctl version
kfctl v1.0-rc.3-1-g24b60e8

I was runs twice same command, will be install successfully!
  Run 1st time: do following steps
(1)$ export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml"
$kfctl apply -V -f ${CONFIG_URI}

Do 2nd time:
$wget   https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
$kfctl apply -V  -f  ./ kfctl_k8s_istio.v1.0.0.yaml

**Comment by mattiasarro** [comment]
For me running it twice did not work, though I guess it would have worked had I waited long enough. The error occurred somewhat randomly, a few times when installing a fresh cluster on AWS EKS. For me the issue was that one `cert-manager-cainjector` pod was in ImagePullBackoff. Deleting this pod spawned a new one which was able to pull the image, and after that `kfctl apply` worked. 

```
$ kubectl -n cert-manager get pods
NAME                                     READY   STATUS             RESTARTS   AGE
cert-manager-5d849b9888-v48j4            1/1     Running            0          26m
cert-manager-cainjector-dccb4d7f-sdt6p   0/1     ImagePullBackOff   0          26m
cert-manager-webhook-695df7dbb-rcflb     1/1     Running            0          26m

$ k describe pod cert-manager-cainjector-dccb4d7f-sdt6p -n cert-manager
.....
Events:
  Type     Reason     Age                   From                                     Message
  ----     ------     ----                  ----                                     -------
  Normal   Scheduled  26m                   default-scheduler                        Successfully assigned cert-manager/cert-manager-cainjector-dccb4d7f-sdt6p to ip-192-168-61-186.ec2.internal
  Normal   Pulling    25m (x4 over 26m)     kubelet, ip-192-168-61-186.ec2.internal  Pulling image "quay.io/jetstack/cert-manager-cainjector:v0.11.0"
  Warning  Failed     25m (x4 over 26m)     kubelet, ip-192-168-61-186.ec2.internal  Failed to pull image "quay.io/jetstack/cert-manager-cainjector:v0.11.0": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/jetstack/cert-manager-cainjector/manifests/v0.11.0: received unexpected HTTP status: 500 Internal Server Error
  Warning  Failed     25m (x4 over 26m)     kubelet, ip-192-168-61-186.ec2.internal  Error: ErrImagePull
  Normal   BackOff    6m36s (x85 over 26m)  kubelet, ip-192-168-61-186.ec2.internal  Back-off pulling image "quay.io/jetstack/cert-manager-cainjector:v0.11.0"
  Warning  Failed     103s (x107 over 26m)  kubelet, ip-192-168-61-186.ec2.internal  Error: ImagePullBackOff
```

**Comment by sakaia** [comment]
I also met same error.

```bash
WARN[0047] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout831491755": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
```

**Comment by alexbarta** [comment]
same issue on fresh k8s installation v1.15.12

**Comment by tranlyvu** [comment]
same issue here

**Comment by alexbarta** [comment]
Yesterday finally I was able to install it. In my case there was a routing issue between kube-apiserver pods and internal service endpoints including cert-manager service (calico networking w/ ipip encapsulation). I guess some problems with iptables but I didn't have much time for troubleshooting.

Basically I have reinstalled the cluster with flannel networking and installed kubeflow 1.0.2. After several retries cert-manager webhook was up and running, and installation did complete successfully.

**Comment by tranlyvu** [comment]
@alexbarta Thanks, in my case
1) I reinstall ed my Kubenetes and used Flannel, 
2) but my pod keep sticking in "creatingContainer" state, then I run https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel
3) then I reinstalled Kubeflow and it works

**Comment by alexbarta** [comment]
@tranlyvu glad it helped

**Comment by charlesa101** [comment]
still having the same issue without flannel!

**Comment by tranlyvu** [comment]
> still having the same issue without flannel!

Try to use canal , it solved my problem

**Comment by jlewi** [comment]
This issue was closed on February 14. If you are still having problems I would suggest opening a new issue and referencing the closed issues. Closed issues are generally ignored.

**Comment by Anujay-Saraf** [comment]
@jlewi 

Need one help here with your expertise and understanding

I am unable to receive a working certificate thru letsencrypt prod/staging API:

Snapshot
![image](https://user-images.githubusercontent.com/27989098/88207853-00328080-cc6e-11ea-8989-012da75951c0.png)


The current setup includes below approach

K8s cluster setup with 1.0.2 Istio Dex Yaml, mentioned in kubeflow.org documentation, which comes with istio 1.3.1 and cert-manager which is coming there as default.
As my major task is to complete this with kubeflow enabled with istio-ingressgateway along with HTTPS Lets-Encrypt ACME SSL Certificate generation.
Kindly let me know a possible solution.

K8s API version 1.14
Istio -1.3.1
Cert-Manager: the same which comes with default manifest.

**Comment by kim-sardine** [comment]
check out https://github.com/jetstack/cert-manager/issues/2640#issuecomment-601872165

I just added `.svc,.svc.cluster.local` to `no_proxy` and setup k8s again. and it works.
