### ISSUE TITLE
Notebook server fails to launch - KFserving webhook not found

### ISSUE THREAD

**Issue by shuaibiyy** [kubeflow/kubeflow#4763]
/kind bug

**What steps did you take and what happened:**
I deployed kubeflow on AWS using the instructions outlined in the [AWS guide](https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/). After deployment, I attempted to create a notebook server using one of the provided public images, i.e.,
gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0. After clicking Launch, the notebook server appears to be stuck in creating state.

Hovering over the status icon displays the following error in the tooltip:
`Reissued from statefulset/default: create Pod default-0 in StatefulSet default failed error: Internal error occurred: failed calling webhook "inferenceservice.kfserving-webhook-server.pod.mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-pods?timeout=30s: service "kfserving-webhook-service" not found`

<img width="1251" alt="Screen Shot 2020-02-14 at 00 42 25" src="https://user-images.githubusercontent.com/1766965/74489431-8d0a2e80-4ec5-11ea-89e1-60d77f350def.png">

**What did you expect to happen:**
I expected the notebook server to launch successfully.

**Environment:**
- Kubeflow version:  1.0
- kfctl version: (use `kfctl version`): v1.0-rc.3-1-g24b60e8
- Kubernetes platform: (e.g. `minikube`): AWS
- Kubernetes version: (use `kubectl version`): v1.17.2
- OS (e.g. from `/etc/os-release`): macOS Mojave

**Comment by jlewi** [comment]
It looks like the KFServing webhook is unavailable and preventing pods from being deployed.

@shuaibiyy as a workaround if you add the label

```
serving.kubeflow.org/inferenceservice: disabled
```

@shuaibiyy can you check the status of kfserving

```
 kubectl -n kubeflow get statefulset kfserving-controller-manager -o yam
 kubectl -n kubeflow describe statefulset kfserving-controller-manager
kubectl -n kubeflow logs kfserving-controller-manager-0 manger
```


To the namespace where you are trying to run the pod that should prevent the kfserving webhook from running in that namespace.



/cc @Jeffwan @cliveseldon @animeshsingh

**Comment by shuaibiyy** [comment]
@jlewi thanks for the workaround! it works.
The output of `kubectl -n kubeflow get statefulset kfserving-controller-manager -o yaml` is:

`Error from server (NotFound): statefulsets.apps "kfserving-controller-manager" not found`

**Comment by rafaelbarreto87** [comment]
Running into the same issue. The workaround works, but I was wondering if there's a more permanent fix. We're not planning on using the serving capabilities of Kubeflow, so we commented out the `kfserving` components. Is there a more general way to not install the serving functionality?

**Comment by animeshsingh** [comment]
@shuaibiyy can you try this command to delete any stale web-hooks and try again? 

`kubectl delete mutatingwebhookconfigurations inferenceservice.serving.kubeflow.org &&  kubectl delete validatingwebhookconfigurations inferenceservice.serving.kubeflow.org && kubectl delete po kfserving-controller-manager-0  -n kfserving-system`

**Comment by animeshsingh** [comment]
@rafaelbarreto87 you can edit the kfdef to remove kfserving if you don't need that as part of the install.

**Comment by animeshsingh** [comment]
cc @ellis-bigelow @yuzisun

**Comment by rafaelbarreto87** [comment]
@animeshsingh That's what I did. Here's are the KDefs:

```

But the webhook continues to be called:

```
$ grep serving -R kustomize
kustomize/pipelines-runner/base/cluster-role.yaml:  - serving.kubeflow.org
kustomize/cert-manager/base/deployment.yaml:          - --webhook-serving-secret=cert-manager-webhook-tls
```

**Comment by rafaelbarreto87** [comment]
Hum... I think this has to do with the stale web-hooks from a previous install... I'll delete them and try again. Thanks.

**Comment by shuaibiyy** [comment]
@animeshsingh It appears deleting the stale webhooks solves the issue even without the earlier workaround, i.e., setting "serving.kubeflow.org/inferenceservice" to "disabled". Thanks.

**Comment by animeshsingh** [comment]
Thanks folks. Highlighted this in troubleshooting section of KFServing as well.
https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#troubleshooting

@jlewi this can be closed
