### ISSUE TITLE
invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy'

### ISSUE THREAD

**Issue by yantriks-edi-bice** [kubeflow/kubeflow#4768]
/kind bug

**What steps did you take and what happened:**

Tried to upgrade from 0.7 to 1.0.0 using [https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml](url)

WARN[0102] Encountered error applying application application:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"StatefulSet\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v1.0.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v1.0.0\"},\"name\":\"application-controller-stateful-set\",\"namespace\":\"kubeflow\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"application-controller\",\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v1.0.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v1.0.0\"}},\"serviceName\":\"application-controller-service\",\"template\":{\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"app\":\"application-controller\",\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v1.0.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v1.0.0\"}},\"spec\":{\"containers\":[{\"command\":[\"/root/manager\"],\"env\":[{\"name\":\"project\",\"value\":\"saas-ml-dev\"}],\"image\":\"gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta\",\"imagePullPolicy\":\"Always\",\"name\":\"manager\"}],\"serviceAccountName\":\"application-controller-service-account\"}},\"volumeClaimTemplates\":[]}}\n"},"labels":{"app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/version":"v1.0.0"}},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/version":"v1.0.0"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/version":"v1.0.0"}}},"volumeClaimTemplates":[]}}
to:
Resource: "apps/v1, Resource=statefulsets", GroupVersionKind: "apps/v1, Kind=StatefulSet"
Name: "application-controller-stateful-set", Namespace: "kubeflow"
Object: &{map["apiVersion":"apps/v1" "kind":"StatefulSet" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"StatefulSet\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v0.7.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v0.7.0\"},\"name\":\"application-controller-stateful-set\",\"namespace\":\"kubeflow\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"application-controller\",\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v0.7.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v0.7.0\"}},\"serviceName\":\"application-controller-service\",\"template\":{\"metadata\":{\"labels\":{\"app\":\"application-controller\",\"app.kubernetes.io/component\":\"kubeflow\",\"app.kubernetes.io/instance\":\"kubeflow-v0.7.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"kubeflow\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v0.7.0\"}},\"spec\":{\"containers\":[{\"command\":[\"/root/manager\"],\"env\":[{\"name\":\"project\",\"value\":\"saas-ml-dev\"}],\"image\":\"gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta\",\"imagePullPolicy\":\"Always\",\"name\":\"manager\"}],\"serviceAccountName\":\"application-controller-service-account\"}},\"volumeClaimTemplates\":[]}}\n"] "creationTimestamp":"2020-02-05T22:54:49Z" "generation":'\x01' "labels":map["app.kubernetes.io/component":"kubeflow" "app.kubernetes.io/instance":"kubeflow-v0.7.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"kubeflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"v0.7.0"] "name":"application-controller-stateful-set" "namespace":"kubeflow" "resourceVersion":"22304378" "selfLink":"/apis/apps/v1/namespaces/kubeflow/statefulsets/application-controller-stateful-set" "uid":"835f2814-486a-11ea-bc60-42010a80022a"] "spec":map["podManagementPolicy":"OrderedReady" "replicas":'\x01' "revisionHistoryLimit":'\n' "selector":map["matchLabels":map["app":"application-controller" "app.kubernetes.io/component":"kubeflow" "app.kubernetes.io/instance":"kubeflow-v0.7.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"kubeflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"v0.7.0"]] "serviceName":"application-controller-service" "template":map["metadata":map["creationTimestamp":<nil> "labels":map["app":"application-controller" "app.kubernetes.io/component":"kubeflow" "app.kubernetes.io/instance":"kubeflow-v0.7.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"kubeflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"v0.7.0"]] "spec":map["containers":[map["command":["/root/manager"] "env":[map["name":"project" "value":"saas-ml-dev"]] "image":"gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" "imagePullPolicy":"Always" "name":"manager" "resources":map[] "terminationMessagePath":"/dev/termination-log" "terminationMessagePolicy":"File"]] "dnsPolicy":"ClusterFirst" "restartPolicy":"Always" "schedulerName":"default-scheduler" "securityContext":map[] "serviceAccount":"application-controller-service-account" "serviceAccountName":"application-controller-service-account" "terminationGracePeriodSeconds":'\x1e']] "updateStrategy":map["rollingUpdate":map["partition":'\x00'] "type":"RollingUpdate"]] "status":map["collisionCount":'\x00' "currentReplicas":'\x01' "currentRevision":"application-controller-stateful-set-69fc9ddb48" "observedGeneration":'\x01' "readyReplicas":'\x01' "replicas":'\x01' "updateRevision":"application-controller-stateful-set-69fc9ddb48" "updatedReplicas":'\x01']]}
for: "/tmp/kout090746272": StatefulSet.apps "application-controller-stateful-set" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden  filename="kustomize/kustomize.go:202"

WARN[0102] Will retry in 26 seconds.                     filename="kustomize/kustomize.go:203"

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0 (though an upgrade to 0.7.1 was attempted some time back)
- kfctl version: (use `kfctl version`): v1.0-rc.3-1-g24b60e8
- Kubernetes platform: (e.g. `minikube`) GKE on GCP
- Kubernetes version: (use `kubectl version`): client v1.13.11-dispatche server v1.14.8-gke.33
- OS (e.g. from `/etc/os-release`): MacOs Mojave

**Comment by jlewi** [comment]
@yantriks-edi-bice Could you please describe what you did? What commands did you run? If you are upgrading a 0.7 deployment did you follow the upgrade instructions?

https://www.kubeflow.org/docs/upgrading/upgrade/

**Comment by yantriks-edi-bice** [comment]
Yes, I followed the upgrade instructions. Used following spec

https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml

and standard command (after verifying all prereqs)

kfctl apply -f /Users/edibice/kubeflows/kfctl_upgrade_gcp_iap_1.0.0.yaml -V

**Comment by yantriks-edi-bice** [comment]
Also deleted the following as suggested here #4763 

kubectl delete mutatingwebhookconfigurations inferenceservice.serving.kubeflow.org && kubectl delete validatingwebhookconfigurations inferenceservice.serving.kubeflow.org && kubectl delete po kfserving-controller-manager-0 -n kfserving-system

**Comment by jlewi** [comment]
@richardsliu thoughts?

**Comment by richardsliu** [comment]
@yantriks-edi-bice Could you provide the full traces from running `kfctl apply`? 

To restart the upgrade process, look in your local directory for a folder with some hash values as the name. Delete this folder and then run `kfctl apply ...` again.

**Comment by yantriks-edi-bice** [comment]
We can close this one. I’ve been able to upgrade to 1.0.2 recently though it required a lot of manual deletes as it seems the upgrade wasn’t finding the expected versions etc. I thought I was upgrading from a 1.0 but I guess it wasn’t clean
