### ISSUE TITLE
Jupyter notebook tensorboard error localhost refused to connect.

### ISSUE THREAD

**Issue by TristansCloud** [kubeflow/kubeflow#4774]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am attempting to run tensorboard in a jupyter notebook server. I am using this model https://github.com/kubeflow/tf-operator/blob/master/examples/v1/mnist_with_summaries/mnist_with_summaries.py. I tried to launch 
tensorboard using 
```python
tensorboard --logdir '/tmp/tensorflow/mnist/logs/mnist_with_summaries'
```
and got localhost refused to connect error

**What did you expect to happen:**

tensorboard to start

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.1
- kfctl version: (use `kfctl version`): 0.7.1
- Kubernetes platform: (e.g. `minikube`): private cloud
- Kubernetes version: (use `kubectl version`): v1.15.9
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by jlewi** [comment]
If you want to run tensorboard, the recommended way to do this is to launch a separate deployment for tensorboard and use a virtual service to setup a reverse proxy route. There's an example in this notebook
https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb
