### ISSUE TITLE
jupyter notbookserver error 

### ISSUE THREAD

**Issue by mockdone** [kubeflow/kubeflow#4781]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

V 1.0

2020-02-19 03:44:27,160 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
10.16.1.65 - - [19/Feb/2020 03:44:27] "GET /api/namespaces/mytest/notebooks HTTP/1.1" 200 -

http://10.18.5.30/jupyter/api/namespaces/mytest/notebooks
get:
{log: "User None is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: mytest",…}

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: v1beta1:
- kfctl version: v1.0-rc.3-1-g24b60e8:
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: 1.14:
- OS (e.g. from `/etc/os-release`):centos

**Comment by mockdone** [comment]
I solved this。
 by the way ,how to use tensorboard?is there any document?

**Comment by zemarx** [comment]
@mockdone How did you solve it?

**Comment by mockdone** [comment]
> @mockdone How did you solve it?

use another yaml
 https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_k8s_istio.yaml
