### ISSUE TITLE
Fairing Access to Kubernetes cluster

### ISSUE THREAD

**Issue by awcchungster** [kubeflow/kubeflow#4786]
/kind question

**Question:**
1. I have a Kubeflow notebook created that is using a custom container that I found on a tutorial. Does kubectl get autoinstalled on each container through kubeflow notebooks?

2. How does kubectl get the kubeconfig for the cluster it is running on? When I run a fairing job, it successfully deploys on the cluster, but I didn't specify any of the settings.

**Comment by jlewi** [comment]
kubectl needs to be installed in the Docker image you are using for notebooks (or you need to install it after the notebook starts).

The notebook images Kubeflow ships come with kubectl and other tools (gcloud, AWS CLI) installed in our images. if you are using your own images you will need to install them if you want them.

Fairing uses the python client library for K8s which has built in support for getting access to the K8s API from within a pod using the pods service account.

For more information
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
