### ISSUE TITLE
Kubeflow Central Dashboard No Namespaces showed

### ISSUE THREAD

**Issue by 251744647** [kubeflow/kubeflow#4788]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Installed kubeflow  on a fresh GKE non-identity aware cluster with kfctl_k8s_istio.0.7.1.yaml, with no default profile, and exposed central dashboard by nginx proxy_pass to istio-ingressgateway. 

- Access the central dashboard ui, this doesn't prompt to setup an initial profile. It shows the home page, with No Namspaces showed.

![centraldashboard](https://user-images.githubusercontent.com/13617297/75019505-f7296180-54cb-11ea-934e-b4e62ef909e8.jpg)

- 

**What did you expect to happen:**
In the central dashboard UI, see all the namespaces the cluster have.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

In the chrome developer tools, we can see http code of /api/workgroup/exists is 304, response is "{"hasAuth":false, "user":"anonymous", "hasWorkgroup": false}". And http code of /api/workgroup/env-info is 403, forbidden error. 

![env-info02](https://user-images.githubusercontent.com/13617297/75020318-7bc8af80-54cd-11ea-9074-bd63c043baae.jpg)

We can see below information from /debug :
![debug-user](https://user-images.githubusercontent.com/13617297/75020379-9b5fd800-54cd-11ea-958d-23e915baf646.jpg)

I know there are similar issues like this, for example, https://github.com/kubeflow/kubeflow/issues/4415,  but they were like 'can't select namespace', this one is 'no namespaces' showed. 
Central dashboard pod log shows "Unable to get envrionment info: [object object]"
profile-kfam pod no obvious errors.  After I created profiles manually, the kfam pod log can see the profile information.

I even  created profiles manually which the user is anonymous@kubeflow.org , and granted cluster admin role to user anonymous@kubeflow.org in GKE cluster, but still get this 403 error.

So i am wondering if the "No Namespaces" in central dashboard relates to env-info 403 error, and if it is, what kind of privileges I need to grant, and to whom?

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0
- kfctl version: (use `kfctl version`):  
- Kubernetes platform: (e.g. `minikube`) GKE cluster master version 1.15.7-gke.23
- Kubernetes version: (use `kubectl version`):  1.15
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux Server release 7.7 (Maipo)

**Comment by jlewi** [comment]
Labeling this as platform/onprem since its using the non-GCP specific configs even though its running on GKE.

If your using GKE I would highly recommend using the GCP configs as that's tested and maintained by Google.

There were various issues in 0.7 with configurations that don't have any identity.  If you are having problems with configurations that aren't using identity I would suggest trying the 1.0 RC.

**Comment by 251744647** [comment]
@jlewi Thanks a lot for your suggestion! 
Right now we are still considering using 0.7 as the kf 1.0 we are not so confident with it even which it means we are struggling with the 0.7 issues 'with configurations that don't have identity'.

@krishnadurai @kunmingg  May I know how to debug this, any comment are much appreciated!

**Comment by krishnadurai** [comment]
@251744647 could you please give us more information regarding whether if:
- The profile created wasn't able to create a namespace.
- Is it just the central dashboard which is not able to list the namespaces?

Copy pasting central-dashboard's and profile-controller's logs might help.

**Comment by 251744647** [comment]
@krishnadurai  Thank you so much for the response!

- The profile was able to create a ns. I created the profile manually, and then the related namespace was created automatically. 

- Yes it is just the central dashboard not able to list the ns, the others like access /jupyter can see and select the namespace.

- I need to rebuilt the env and collect the logs here. So need some time.

**Comment by 251744647** [comment]
@krishnadurai Please kindly find below log details:
Central dashboard pod log:

![1](https://user-images.githubusercontent.com/13617297/76418431-95c52600-63d9-11ea-933f-f12708d720ee.jpg)


Profile pod manager container log:
![11](https://user-images.githubusercontent.com/13617297/76418460-a1b0e800-63d9-11ea-9626-7fa17669ef57.jpg)



Profile pod kfam container log:

![111](https://user-images.githubusercontent.com/13617297/76418443-99f14380-63d9-11ea-97df-78ec49f81981.jpg)

**Comment by joey100** [comment]
@krishnadurai Upper profile manager log showed there was connection issue to the kubernetes apiserver, that may be a problem. Fortunately, the connection issue has been fixed now,it's firewall rule issue. I created a new profile, created cluster-admin rolebinding to the anonymous user, still no namespaces showed in the central dashboard. 
Please kindly review the new profile manager log:

![111](https://user-images.githubusercontent.com/18437960/77074508-ea951c00-6a2b-11ea-89d7-3d5a1af94886.jpg)

**Comment by maxisacoder** [comment]
same case

**Comment by mrjiangguoqing** [comment]
same problem in 1.9.0 in a self-host cluster.but don't appear in cloud provider cluster.very strange.the kube version is the same.
