### ISSUE TITLE
Notebook image continuous builds need to be updated to use Tekton 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4789]
/kind feature

On postsubmits we were running ksonnet workflows to auto build the notebook images and 
push them to gcr.io/kubeflow-images-public

We need to make two updates

1. We want to get rid of ksonnet and Argo and switch to using Tekton for CI/CD pipelines
1. We want to run these Tekton pipelines in our release infrastructure
    * see https://github.com/kubeflow/testing/tree/master/apps-cd

Today we have release infrastructure for continuously building Kubeflow Docker Images and updating our Kustomize manifests to reference the new images. This is described at
https://github.com/kubeflow/testing/tree/master/apps-cd

We'd like to do the same for the notebook images. However, what exists needs to be modified because for the notebook images we need to update the configmap listing the notebook images and not the kustomization.yaml file.

/cc @Tabrizian

**Comment by Tabrizian** [comment]
@jlewi I can work on this if this is not already done...

**Comment by marcindulak** [comment]
Will this setup create a chance so more notebook image types will be maintained?

The tensorflow notebook images are well maitained

![Screenshot from 2020-02-23 11-23-33](https://user-images.githubusercontent.com/3178318/75110504-49cf5e80-562f-11ea-9d6a-4d51082cd8b3.png)

but pytorch and other frameworks seem not

![Screenshot from 2020-02-23 11-23-08](https://user-images.githubusercontent.com/3178318/75110509-5358c680-562f-11ea-93cf-ac4636605a09.png)

**Comment by Tabrizian** [comment]
@marcindulak, I am not sure whether it is in our plan but it is definitely a requirement. Meanwhile, you can easily create your own custom images and use them for the notebooks.

**Comment by jlewi** [comment]
@Tabrizian if you could take a look at this that would be fantastic.

**Comment by Tabrizian** [comment]
@jlewi Sorry for the delay, I was looking into this and I am not sure about exactly what I am supposed to do. As far as I understood, I should add an entry to the file below for building the tensorflow images and remove the ks and jsonnet files, right?

https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml

**Comment by jlewi** [comment]
@Tabrizian sorry for the delay. I think its a bit more involved then that. 

Here's how our CD currently works.

* We have a [Tekton pipeline](https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml) that consists of two tasks

   * A tekton task to build the docker imake using Kaniko
   * Tekton task to run a python script [create_manifests.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cd/create_manifests_pr.py)
 that 
      1. Runs `kustomize edit` to update the image in the manifest
      1. Creates a GitHub PR

I think if you add an entry to applications.yaml that will build the docker image and update the kustomize manifest.

However, we really need to update the [config_map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) used by the jupyter web app as that's where the notebook images are specified. 

That will require a new python script and some changes to the Tekton task and pipeline.

**Comment by jlewi** [comment]
@Tabrizian any update on this?

**Comment by Tabrizian** [comment]
@jlewi Sorry for the delay, I will create the initial PR in one or two days.

**Comment by Tabrizian** [comment]
@jlewi I was wondering how can I condition on a specific application pipeline. In order to modify the [config_map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) is it ok if I change the [create_manifests_pr.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cd/create_manifests_pr.py) file and condition on the manifests dir and if it is related to the `tensorflow-notebook-image` I will modify the config-map and add it to the PR?

**Comment by jlewi** [comment]
@Tabrizian yes you will probably need to update create_manifests_pr.py.

Right now we have a single [Tekton Pipeline](https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml) that is used for all applications.

My initial thought is that we probably want to support different pipelines for different applications. So we might want to specify the name of the pipeline in https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml for each application.

create_manifests_pr.py could then spawn a PipelineRun using the appropriate pipeline.

How does that line up with your thinking?

**Comment by Tabrizian** [comment]
@jlewi Yes, this makes complete sense.

**Comment by Tabrizian** [comment]
@jlewi I wanted to play a bit with the tekton pipelines for this PR, but it seems like I don't have access to the release cluster which was mentioned in [Run a Pipeline](https://github.com/kubeflow/testing/tree/master/apps-cd#run-a-pipeline) section. Can I create a PR to update my permissions in the internal-acls repo or there is another workaround for it?

**Comment by jlewi** [comment]
@Tabrizian you can just install Tekton in your own cluster. Access to the release cluster is tightly restricted because anyone with access to the release cluster can modify release artifacts.

**Comment by jlewi** [comment]
@Tabrizian any progress on this?

**Comment by Tabrizian** [comment]
@jlewi Unfortunately, I didn't have time to work on this. It takes longer than I expected. I try to work on it during the weekend but don't count on me. Sorry.

**Comment by jlewi** [comment]
No worries thanks for the update.

**Comment by jlewi** [comment]
We can probably break this into 2 steps

1. Just building the docker images automatically
1. automatically opening up PRs to update the config maps.

**Comment by willb** [comment]
@jlewi We're using Tekton pipelines for a closely-related use case; I'm happy to take a look later this week.

**Comment by jlewi** [comment]
@jtfogarty also expressed some interest

**Comment by Jeffwan** [comment]
@jlewi Besides notebook images, profile controller needs to be update as well. Same as other training operators. This story is just for notebook, right? Do we have stories for others? If we don't have owners, let me know.

**Comment by jlewi** [comment]
@Jeffwan  This issue is specific to the notebook images because it is the config maps that need to be updated.

We already have 
https://github.com/kubeflow/testing/tree/master/apps-cd
which works for most of our other images. 

We do need to make some config updates to work with the latest manifests. That is being tracked by 
kubeflow/testing#631

**Comment by 4n4nd** [comment]
Hey @jlewi, we have an internal [Tekton pipeline](https://github.com/thoth-station/jupyternb-build-pipeline) to build notebook images which has been working well for us. These images use a minimal base image [s2i-minimal-notebook](https://github.com/aicoe/s2i-custom-notebook).

**Comment by jlewi** [comment]
@jtfogarty @4n4nd @willb is someone willing to look into this?

**Comment by harshad16** [comment]
@4n4nd I went over the issue. 
It feels like the requirement here is to build a notebook image via the tekton pipeline [build task](https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/task.yaml#L4) and update the tag in the [config-map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) via [update task](https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/task.yaml#L55). 

one solution could be:
- Include [tensorflow-notebook-image](https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image) into the [application.yaml](https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml)
- Use a param to notify the pipeline that the component version is to be updated in [config-map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) rather than the [kustomize.yaml](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/kustomization.yaml) in manifest dir. 
- After passing this param, it could be used to implement the logic that creates a pull-request to update the [config-map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) using the python file [create_manifests_pr.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cd/create_manifests_pr.py).

@jlewi  what do you think about the above solution. 
btw what did you mean by 
> My initial thought is that we probably want to support different pipelines for different applications. So we might want to specify the name of the pipeline in https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml for each application.
>create_manifests_pr.py could then spawn a PipelineRun using the appropriate pipeline.

**Comment by jlewi** [comment]
> It feels like the requirement here is to build a notebook image via the tekton pipeline build task and update the tag in the config-map.yaml via update task.

Yes; this is exactly right.

> btw what did you mean by

So my suggestion would be to create a new pipeline; e.g. right now we have a single pipeline
https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml

Which works because all applications get built and updated the same way.

Notebook images differ from that pipeline because we need to update config-map.yaml and not the kustomization file.

So my suggestion would be create a new pipeline by copying [pipeline.yaml](
https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml)

Refactor/modify create_manifests_pr.py  to make it work for notebook image releases

That script is really doing two things
1. Update kustomization.yaml
1. Creating the PR 

The first bit is the logic that we need to change for notebook images. The second (creating the PR) could be reused across both types of pipelines. 

One suggestion might be to split those into two separate steps in the Tekton task. Then the only step that would have to change would be modifying the files. The step to create the PR would be unchanged.

**Comment by harshad16** [comment]
> > It feels like the requirement here is to build a notebook image via the tekton pipeline build task and update the tag in the config-map.yaml via update task.
> 
> Yes; this is exactly right.
> 
> > btw what did you mean by
> 
> So my suggestion would be to create a new pipeline; e.g. right now we have a single pipeline
> https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml
> 
> Which works because all applications get built and updated the same way.
> 
> Notebook images differ from that pipeline because we need to update config-map.yaml and not the kustomization file.
> 
> So my suggestion would be create a new pipeline by copying [pipeline.yaml](https://github.com/kubeflow/testing/blob/master/apps-cd/pipelines/base/pipeline.yaml)
> 
> Refactor/modify create_manifests_pr.py to make it work for notebook image releases
> 
> That script is really doing two things
> 
> 1. Update kustomization.yaml
> 2. Creating the PR
> 
> The first bit is the logic that we need to change for notebook images. The second (creating the PR) could be reused across both types of pipelines.
> 
> One suggestion might be to split those into two separate steps in the Tekton task. Then the only step that would have to change would be modifying the files. The step to create the PR would be unchanged.

Thanks for the explanation @jlewi, that make sense.
I will try to contribute to this.  :+1:

**Comment by jlewi** [comment]
@harshad16 any update?

**Comment by harshad16** [comment]
> @harshad16 any update?

@jlewi have some trouble in testing. 
however here is what I trying to do, 
making a change in the [update_kf_apps.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cd/update_kf_apps.py) to check if the image is present or not in the [config-map.yaml](https://github.com/kubeflow/manifests/blob/9ec6bb39e9bb76d7a9bdef290628a6c6f36952ce/jupyter/jupyter-web-app/base/config-map.yaml#L27) , based on that the new pipeline would run, which build and call update manifest for tensorflow-notebook-images, and still working on getting configmap update with [create_manifests_pr.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cd/create_manifests_pr.py)

will open the pull request to get feedback.

**Comment by jlewi** [comment]
@harshad16 Thanks. Is there a Tekton pipeline we could trigger manually to do just the builds so that we could get new docker images built for the release?

**Comment by harshad16** [comment]
> @harshad16 Thanks. Is there a Tekton pipeline we could trigger manually to do just the builds so that we could get new docker images built for the release?

this [pipeline](https://github.com/harshad16/testing/blob/master/apps-cd/pipelines/base/notebook-pipeline.yaml) can be used to trigger manually to build and push , still a wip.
as i run my workload on openshift instance i had to changed few of the things in tasks.

**Comment by jlewi** [comment]
@harshad16 It would be really helpful if we could do two things

1. Check in any pipelines and tasks into kubeflow/testing
1. Create a PipelineRun to build  the notebook images we need

If someone could just manually do `kubectl apply -f run.yaml` to kick of a run to build updated KF images that would be super helpful.

If it will speed things up you can run directly on our CI GKE clusters. Just send me a PR to add yourself to
https://github.com/kubeflow/internal-acls/blob/master/ci-team.members.txt

**Comment by jlewi** [comment]
@harshad16 I was thinking about how to make this more reusable (e.g kubeflow/code-intelligence#155)

create_manifests_pr.py is really doing two things

1. It is applying use case specific logic to modify some files
    * e.g. in one case we are updating kustomize images
    * in this issue we are updating the spawner config
    * in kubeflow/code-intelligence#155 we want to modify model configs

1. Push a commit to a fork and create a GitHub PR
    * This logic isn't really use case specific

Tekton tasks already make it easy for us too sequentially run two binaries. So it might make sense to split create_manifests_pr.py into two binaries/steps.

Going one step further, we might want to split the 2nd step into two steps as well

1. Push a commit to git
1. Create PR
    * This will vary depending on source control system (e.g. GitLab vs. GitHub).

These could actually run as separate Tekton tasks because the only data passed between them is in git repo. This would allow for greater reusability across source control systems.

**Comment by harshad16** [comment]
sorry wasn't available for the last few days, we get onto this.

> 1. Check in any pipelines and tasks into kubeflow/testing
> 2. Create a PipelineRun to build  the notebook images we need
> If someone could just manually do `kubectl apply -f run.yaml` to kick of a run to build updated KF images that would be super helpful.

saw that the tensorflow-notebook-image builds are done via this [script](https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/build_image.sh)  was trying to create a task which would build the image with buildah and the build args.  

> If it will speed things up you can run directly on our CI GKE clusters. Just send me a PR to add yourself to
> https://github.com/kubeflow/internal-acls/blob/master/ci-team.members.txt

this would be super helpful. will send in a pr.

**Comment by harshad16** [comment]
> Tekton tasks already make it easy for us too sequentially run two binaries. So it might make sense to split create_manifests_pr.py into two binaries/steps.

This could be doable as one task step of task can do the modify of file and another can do the commit or push-based on params.

> Going one step further, we might want to split the 2nd step into two steps as well
> 
> 1. Push a commit to git
> 2. Create PR
>    
>    * This will vary depending on source control system (e.g. GitLab vs. GitHub).
> 
> These could actually run as separate Tekton tasks because the only data passed between them is in git repo. This would allow for greater reusability across source control systems.

Make sense, This would be really useful. In one of our team project, we have done something similar we pass in the git repo as param and the tasks does a commit push to the kustomize changes to the git repo with a bots creds.

**Comment by jlewi** [comment]
@harshad16 No problem. I was working on CD in the context of  kubeflow/code-intelligence#155 .

This got me thinking that it might be easier to build actual custom resources that 

1. Expressed the appropriate condition to trigger the tekton pipeline
1. Contain the tekton pipelinerun to run

The existing apps-cd is basically already implementing a reconciler but without actually implementing it as a K8s controller.

The question is then what should the reconcile condition be?

If we followed the existing pattern then we would have a single reconciler that would compare the latest commit to the docker image in a manifest and if they aren't the same fire off a Tekton pipeline.

I wonder though if it would be more generic too split this into 2 reconcilers

1. First CR would check if a docker image exists built from the latest code and if not fire of a Tekton pipeline to build it (kubeflow/testing#721)
1. Second CR would check if the latest image matched the value of a `kpt setter` or a `kustomize image` and if not fire off a Tekton pipeline to run it.

**Comment by harshad16** [comment]
> @harshad16 No problem. I was working on CD in the context of [kubeflow/code-intelligence#155]

@jlewi , can I take couple of more days to work on this? I should have spend more time on this, been a bit lazy :see_no_evil: 
I will open a pr and comment on this pr as well https://github.com/kubeflow/internal-acls/pull/276
apologize for the delay.

**Comment by jlewi** [comment]
@harshad16 sure thanks

**Comment by jlewi** [comment]
@harshad16 I'm working on a [controller](https://github.com/kubeflow/code-intelligence/tree/master/Label_Microservice/go) that will do the following

* Send an http request that will return a payload whether a sync is needed and the parameters if so for a tekton run
* If a sync is needed fire off a tekton pipeline 

This would make it easy to generalize our continuous builds. That should fit nicely with what you are doing because we still need

1. A tekton pipeline to actually build and update the resources
1. Code to compute whether a sync is needed (we just need to wrap it in an http server).

**Comment by jlewi** [comment]
@thesuperzapper @kimwnasptd What's the path forward for CI/CD for notebook images?
