### ISSUE TITLE
Integrating Pipeline with Azure KeyVault

### ISSUE THREAD

**Issue by Shaked** [kubeflow/kubeflow#4794]
/kind question

**Question:**

Hey, 

Is it possible to integrate a `pipeline`'s container with Azure KeyVault? 

We are currently mounting our Azure KeyVault using https://github.com/Azure/kubernetes-keyvault-flexvol in order to mount configuration and secrets to our containers on our k8s cluster. 

It would be useful to mount Azure KeyVault as we won't need to expose our TenantId/SubscriptionId in our git repository.

Thank you
Shaked

**Comment by berndverst** [comment]
When creating the pipeline using the Kubeflow Pipelines DSL (and then compiling it) you can specify the FlexVolumeSource as source for your Volume to mount. On each `ContainerOp` add the Volume via the `add_volume` and `add_volume_mount` methods which take as input V1Volume and V1VolumeMount classes from the Python Kubernetes client.

```
import kfp.dsl as dsl
from kubernetes import client as k8s_client
```

```
op = dsl.ContainerOp(......)

op.add_volume(k8s_client.V1Volume(name='test', flex_volume=client.V1FlexVolumeSource(
        driver="azure/kv", 
        options={
            "usepodidentity": "false",                   # [OPTIONAL] if not provided, will default to "false"
            "usevmmanagedidentity": "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            "vmmanagedidentityclientid": "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            "keyvaultname": "testkeyvault"              # [REQUIRED] the name of the KeyVault
            "keyvaultobjectnames": "testsecret"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            "keyvaultobjectaliases": "secret.json"      # [OPTIONAL] list of KeyVault object aliases
            "keyvaultobjecttypes": secret               # [REQUIRED] list of KeyVault object types: secret, key, cert (semi-colon separated)
            "keyvaultobjectversions": "testversion"     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
            "resourcegroup": "testresourcegroup"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            "subscriptionid": "testsub"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            "tenantid": "testtenant" 
            })
        )

op.add_volume_mount(k8s_client.V1VolumeMount(
    mount_path="/kvmnt",
    name="test")
    )
```

**Comment by berndverst** [comment]
@Shaked do you use Fairing? Steps would be different for that and I'm unsure how to do it at this time.

**Comment by Shaked** [comment]
@berndverst your answer is clear and very helpful, thank you! 

I haven't checked/used Fairing up until now, should I check it?

**Comment by berndverst** [comment]
@Shaked I've never used Fairing with Pipelines but some people seem to be talking about it. If you use the Python SDK and compile using the DSL the instructions I shared here should work.

This was a great question by the way. I had to look through the Azure docs, Kubernetes Client docs and Pipelines SDK docs to figure out how to do it. (I work for Microsoft by the way)

**Comment by Shaked** [comment]
Hey @berndverst 

I know it's a bit off-topic but maybe you have an idea regarding https://github.com/Azure/kubernetes-keyvault-flexvol/issues/183? 

The problem is that flexvolume is not installed on nodes that were scaled up especially for kubeflow's pipeline job.

**Comment by Shaked** [comment]
This issue has been resolved in https://github.com/Azure/kubernetes-keyvault-flexvol/issues/183 keep in mind that it for GPU nodes, you'd have to use `tolerations` and for GKE you'd have to follow the PR https://github.com/Azure/kubernetes-keyvault-flexvol/pull/186 as GKE nodes do not support the jq command line tool by default
