### ISSUE TITLE
TensorBoard KFP viz doesn't appear to work properly with KF 1 installation

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#4795]
/kind bug
With kf 1 rc4.
Not sure if this should be filed under the kf or kfp repo.

The TB KFP viz (as documented [here](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#tensorboard)) appears to no longer work properly on a KF install, but _does_ work on a hosted kfp installation, running the same pipeline step.  
This used to work on KF 0.7.1, IIRC.

On the KF installation, I see the following.  
<img width="685" alt="Screenshot 2020-02-23 12 30 56" src="https://user-images.githubusercontent.com/115093/75122491-c7589600-5652-11ea-986c-c2146f2ada11.png">
The given log directory is definitely populated with the correct stuff.

If I run the _same pipeline_ on hosted kfp, the result is as expected, e.g. as below.  
<img width="780" alt="Screenshot 2020-02-23 15 40 56" src="https://user-images.githubusercontent.com/115093/75122509-f40cad80-5652-11ea-84d4-fb7fd4b4558a.png">

Haven't dug in further yet.

**Comment by Bobgy** [comment]
Thanks for the report!
/assign @Bobgy

**Comment by Bobgy** [comment]
@amygdala Can you share your exact pipeline?

**Comment by amygdala** [comment]
It's [this one](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/pipelines/example_pipelines/gh_summ.py.tar.gz) (uncompiled pipeline definition [here](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/pipelines/example_pipelines/gh_summ.py)).
I confirmed again that I could repro with the KF 1 release (though I think that's essentially the same as the RC 4 release where I was seeing the issue).

The component yaml for the training step is [here](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/pipelines/components/t2t/train_component.yaml)  — though again, this **does work with hosted KFP**, so I assume this is not the culprit.
The underlying code for the training step is [here](https://github.com/kubeflow/examples/tree/master/github_issue_summarization/pipelines/components/t2t/t2t-train).

**Comment by Bobgy** [comment]
```
E0228 11:53:23.809175 140224491833088 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 395, in __call__
    return self.exact_routes[clean_path](environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 320, in _serve_plugins_listing
    is_active = plugin.is_active()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 74, in is_active
    return tf.io.gfile.exists(summary_filename) and\
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 280, in file_exists_v2
    pywrap_tensorflow.FileExists(compat.as_bytes(path))
PermissionDeniedError: Error executing an HTTP request: HTTP response code 403 with body '{
  "error": {
    "code": 403,
    "message": "Primary: /namespaces/gongyuan-pipeline-test.svc.id.goog with additional claims does not have storage.objects.get access to gongyuan-test/f4d42f46-9ad9-4d2c-8fe5-d7d3a2666192/tfx-taxi-cab-classification-pipeline-example-fpljz-2548132154/data/plugins/beholder/frame.summary.",
    "errors": [
      {
        "message": "Primary: /namespaces/gongyuan-pipeline-test.svc.id.goog with additional claims does not have storage.objects.get access to gongyuan-t'
	 when reading metadata of gs://gongyuan-test/f4d42f46-9ad9-4d2c-8fe5-d7d3a2666192/tfx-taxi-cab-classification-pipeline-example-fpljz-2548132154/data/plugins/beholder/frame.summary
```
I reproduced the issue with a different pipeline with tensorboard, and used `kubectl logs viewer-xxxxx` to see tensorboard's log, seems like it doesn't have required permission.

**Comment by Bobgy** [comment]
The tensorboard pod uses default service account, we need to change it to `kf-user`, similar to https://github.com/kubeflow/kubeflow/issues/4803#issuecomment-592306016

**Comment by Bobgy** [comment]
/assign @Bobgy 
I fixed the permission issue in https://github.com/kubeflow/manifests/pull/970
