### ISSUE TITLE
KFP builtin samples fail in KF1.0

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/kubeflow#4803]
/kind bug
/area pipelines

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Just run built in samples
2. All of them, except conditional sample fails (because conditional sample is the only one that never reads from gcs)

**What did you expect to happen:**
1. They should pass

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think the problem is that `pipeline-runner` service account should be bound to workload identity.
This is part of https://github.com/kubeflow/pipelines/issues/1691#issuecomment-569020262

**Environment:**

- Kubeflow version: 1.0
- kfctl version: kfctl v1.0-0-g94c35cf
- Kubernetes platform: gke
- Kubernetes version: (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.24", GitCommit:"f2734800eba37df4400813ab9340886059d56105", GitTreeState:"clean", BuildDate:"2020-02-05T18:38:43Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): mac

**Comment by Bobgy** [comment]
@jlewi Can you help me point to where I should add the workload identity binding?

**Comment by jlewi** [comment]
@Bobgy which namespace are pipelines running in? And which service account are they using? Is it possible to reuse one of the existing service accounts that is already bound to workload identity rather than creating a new one?

In the kubeflow namespace there is the `kf-user` service account that is already bound to the GCP sa.

```
kubectl -n kubeflow get serviceaccount -o yaml kf-user
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: kf-v1-0226-6ce-user@kubeflow-ci-deployment.iam.gserviceaccount.com
  creationTimestamp: "2020-02-26T07:36:40Z"
  name: kf-user
  namespace: kubeflow
  resourceVersion: "1170"
  selfLink: /api/v1/namespaces/kubeflow/serviceaccounts/kf-user
  uid: ba1fd0fb-586a-11ea-8a86-42010a8e004e
secrets:
- name: kf-user-token-64wr4
```
In profile namespaces we have the "default-editor" service account.

**Comment by Bobgy** [comment]
@jlewi Thanks for the help.
Current status (before multi user support lands in KF), pipelines still run in kubeflow namespace, and they are using `pipeline-runner` service account.

It requires kfp api server change to switch to a different default service account, I guess it makes sense to do so now.
/cc @IronPan 
/cc @chensun  

And I need to make sure permissions it needs can be satisfied by `kf-user` service account.
https://github.com/kubeflow/manifests/blob/master/pipeline/pipelines-runner/base/cluster-role.yaml

I'll take a look

**Comment by jlewi** [comment]
@Bobgy IIUC the built in samples were working correctly in 0.7. What changed? Were the samples updated to use workload identity as opposed to using the GOOGLE_APPLICATION_CREDENTIALS?

**Comment by Bobgy** [comment]
@jlewi Yes, the samples were updated to default to supporting workload identity / node default GSA.

**Comment by Bobgy** [comment]
@jlewi Can you explain what makes creating additional WI bindings hard? Is it because the logic can only be added in `kfctl` so it will have to branch for different deployments?

**Comment by Bobgy** [comment]
@jlewi I just tried configuring default service account for KFP in https://github.com/kubeflow/manifests/blob/4d8b1cb7e6340a69303ce59878fc29f6b3a71a72/pipeline/api-service/base/config-map.yaml#L19, it lacks some permissions.

After I bind `pipeline-runner` cluster role with `kf-user` it works fine now. Do you think that's a suitable fix? I will submit a PR for you to review.

**Comment by amygdala** [comment]
Do you think this fix would also address this bug? https://github.com/kubeflow/kubeflow/issues/3874
@Bobgy

**Comment by Bobgy** [comment]
@amygdala No, kf-user service account doesn't have any bindings by default. It won't have the permission you ask for. If you think #3874 is important, you can add that permission to kf-user too.

**Comment by Bobgy** [comment]
To workaround this issue in our own cluster, please refer to https://github.com/kubeflow/pipelines/issues/3069#issuecomment-595043632

**Comment by Bobgy** [comment]
/reopen

Waiting for a new Kubeflow release to pick up the fix

**Comment by Bobgy** [comment]
/close
Kubeflow 1.0.2 has picked up cherrypicks of this fix.
