### ISSUE TITLE
kubeflow supports deploying mxnet-operator using kustomize

### ISSUE THREAD

**Issue by xigang** [kubeflow/kubeflow#4805]
/kind feature

**Why you need this feature:**
The current kubeflow deployment supports tensorflow-operator and pytorch-operator by default, hoping to increase mxnet-operator.

**Describe the solution you'd like:**
NONE

**Anything else you would like to add:**
NONE
/cc @jlewi @jtfogarty

**Comment by terrytangyuan** [comment]
+1 to this. cc a few others who might be interested in working on this @suleisl2000 @wackxu @gaocegege @jzp1025 @KingOnTheStar @Jeffwan. I'll circulate this to MXNet dev team as well.

**Comment by szha** [comment]
cc @zhreshold. Looks like a good initiative that AutoGluon can integrate with for its HPO functionality.

**Comment by zhreshold** [comment]
+1 for mxnet op

**Comment by Jeffwan** [comment]
@jlewi @terrytangyuan 
We first need to graduate mxnet-operator  to v1. v1 API is already there and need some more tests or tuning. Then we can add to manifest. I can help on all this work.

**Comment by terrytangyuan** [comment]
@Jeffwan Great! Feel free to divide this into multiple smaller issues/tasks and assign yourself if you are working on it. This way others who are interested can contribute as well.

**Comment by terrytangyuan** [comment]
Related issues: 
* https://github.com/kubeflow/mxnet-operator/issues/54 
* https://github.com/kubeflow/mxnet-operator/issues/36 
* https://github.com/kubeflow/mxnet-operator/issues/59

**Comment by Jeffwan** [comment]
@terrytangyuan Sounds good. I will create some more blocking issues for graduation and people can pick them.

**Comment by terrytangyuan** [comment]
Thanks for the interest. We’ll add links to the relevant work/issues here. Please stay tuned and take a look at them when they are ready.

**Comment by terrytangyuan** [comment]
See https://github.com/kubeflow/mxnet-operator/issues/66
