### ISSUE TITLE
kfctl with in-cluster config leads to missing ClusterName in KfDef, preventing deletion

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/kubeflow#4815]
/kind bug
**What steps did you take and what happened:**
When installing kubeflow from a pod within the cluster, following the install docs (e.g https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) like this:

```
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml"
export KF_NAME=foobar23
export BASE_DIR=$(mktemp -d)
export KF_DIR=${BASE_DIR}/${KF_NAME}
mkdir -p $KF_DIR
cd $KF_DIR
curl -Lo kfctl_istio_dex.yaml $CONFIG_URI
export CONFIG_FILE=${KF_DIR}/kfctl_istio_dex.yaml
kfctl apply -V -f ${CONFIG_FILE}
```

kfctl seems to assume there is a local `kubeconfig` as indicated by this warning:

```
WARN[0000] could not load config Error: open /root/.kube/config: no such file or directory  filename="apps/group.go:324"
WARN[0000] unable to load .kubeconfig.                   filename="kustomize/kustomize.go:159"
```

This prevents cluster deletion:
```
$ kfctl delete -V -f ${CONFIG_FILE}
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to foobar23 based on location of config file: /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/kfctl_istio_dex.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Deleting cachedir /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/.cache/manifests because Status.ReposCache is out of date  filename="kfconfig/types.go:472"
INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.0.0.tar.gz to /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0011] updating localPath to /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/.cache/manifests/manifests-1.0.0  filename="kfconfig/types.go:540"
INFO[0011] Fetch succeeded; LocalPath /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/.cache/manifests/manifests-1.0.0  filename="kfconfig/types.go:561"
INFO[0011] folder /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/kustomize exists, skip kustomize.Generate  filename="kustomize/kustomize.go:372"
INFO[0011] /var/folders/ch/zs6dvdm9577csh6r1b4mw9zh0000gp/T/tmp.yGrM7as5/foobar23/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
INFO[0011] Initializing a default restConfig for Kubernetes  filename="kustomize/kustomize.go:138"
WARN[0011] could not open /foo/bar/baz Error stat /foo/bar/baz: no such file or directory  filename="apps/group.go:298"
INFO[0011] trying to load rest.config with inClusterConfig...  filename="apps/group.go:299"
WARN[0011] could not load rest.config with inClusterConfig and /foo/bar/baz  filename="apps/group.go:302"
Error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 400 with message: cannot find ClusterName within KfDef, this may cause error deletion to clusters.
Usage:
  kfctl delete [flags]

Flags:
      --delete_storage   Set if you want to delete app's storage cluster used for mlpipeline.
  -f, --file string      The local config file of KfDef.
      --force-deletion   force-deletion output default is false
  -h, --help             help for delete
  -V, --verbose          verbose output default is false

couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 400 with message: cannot find ClusterName within KfDef, this may cause error deletion to clusters.
```

**What did you expect to happen:**
kubeflow should work with in-cluster config.

**Anything else you would like to add:**
I think it would make sense to get rid of ClusterName altogether.

What was the reason to have this instead of just using client-go's defaults and leave it to the user to set the right cluster/context when running kfctl?

I'd suggest to:

- drop ClusterName
- add --context flag to kfctl to override the current context (same as kubectl or other clis like argo)
- use client-go's defaults behavior (aka detect if in-cluster or not, use the current-context when using local kubeconfig)

The current behavior is also dangerous. I would never expect kfctl to operate on a cluster I haven't switched to or explicitly referred to when invoking it.

**Environment:**

- Kubeflow version: 1.0.0
- kfctl version: (use `kfctl version`): 1.0.0

**Comment by discordianfish** [comment]
Okay, looks like this issue is caused by running `kfctl build`, then `kfctl delete` without ever running `kfctl apply` which would take the cluster name from kubeconfig and write it as metadata.ClusterName to the kfdef file. That kinda makes sense, without apply there is nothing to delete.

So I'd be fine with just closing this issue. Then again, I think it would make sense to get rid of ClusterName altogether.

What was the reason to have this instead of just using client-go's defaults and leave it to the user to set the right cluster/context when running kfctl?

I'd suggest to:
- drop ClusterName
- use default context
- add --context flag to kfctl to override the current context (same as kubectl or other clis like `argo`)

**Comment by jlewi** [comment]
ClusterName is there because for the public configs kfctl will actually create the K8s cluster and all the other resources needed.

**Comment by tomalbrecht** [comment]
> ClusterName is there because for the public configs kfctl will actually create the K8s cluster and all the other resources needed.

How does this solve the problem with `kfctl delete -V -f ${CONFIG_FILE}`
How do I delete the deployment?

**Comment by LamoraHolmes** [comment]
Have the same problem here. Installing Kubeflow like it's described in the manual but can't delete it in the same way. 
It is pretty enoying to manually delete all namespaces or resources coming with the deployment of KF

**Comment by matthiasfalk** [comment]
This problem still persists. Is there any solution to it?

**Comment by yydzhou** [comment]
Is there anyone looking at this issue? or at least provide a workaround?

**Comment by supertetelman** [comment]
I manually added the `ClusterName` field to the downloaded manifest file before running the `kubectl delete` command and that seems to have helped:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
  ClusterName: cluster.local
```

**Comment by StarCoral** [comment]
Thank you @supertetelman , I solve this error by this way.
and the ClusterName is according the admin.conf

**Comment by agup006** [comment]
> I manually added the `ClusterName` field to the downloaded manifest file before running the `kubectl delete` command and that seems to have helped:
> 
> ```
> apiVersion: kfdef.apps.kubeflow.org/v1
> kind: KfDef
> metadata:
>   namespace: kubeflow
>   ClusterName: cluster.local
> ```

This worked for me, I had to use the full name `cluster-name`.`region`.eksctl.io

**Comment by azelezni** [comment]
Some more info would be helpful, where exactly do I delete `ClusterName`? I don't see it anywhere in the manifests.

**Comment by LRSutton** [comment]
> Some more info would be helpful, where exactly do I delete `ClusterName`? I don't see it anywhere in the manifests.

Edit the kfctl_*.yaml file that you are using.

Create an entry in the `metadata` section:
> clusterName: <your cluster's name>

for example, the top of my kfdef.yaml file reads:

```apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  clusterName: kubernetes
  creationTimestamp: null
  namespace: kubeflow
spec:
  applications:
  ...
```

Once you have this edited, you should be able to execute a `kfctl delete -f <your kfdef file>`

**Comment by shuhaohe** [comment]
> I manually added the `ClusterName` field to the downloaded manifest file before running the `kubectl delete` command and that seems to have helped:
> 
> ```
> apiVersion: kfdef.apps.kubeflow.org/v1
> kind: KfDef
> metadata:
>   namespace: kubeflow
>   ClusterName: cluster.local
> ```

work for me. Steps here

kubectl config view

`>apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.10.22.7:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: kubeflow
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
`
So the cluster name is kubernetes.

And then add `ClusterName: kubernetes` to the original yaml file.

Notes: fetch the ORIGINAL YAML from github before reruning deletion.

**Comment by shuhaohe** [comment]
> > I manually added the `ClusterName` field to the downloaded manifest file before running the `kubectl delete` command and that seems to have helped:
> > ```
> > apiVersion: kfdef.apps.kubeflow.org/v1
> > kind: KfDef
> > metadata:
> >   namespace: kubeflow
> >   ClusterName: cluster.local
> > ```
> 
> This worked for me, I had to use the full name `cluster-name`.`region`.eksctl.io

Thanks.

**Comment by shuhaohe** [comment]
> > I manually added the `ClusterName` field to the downloaded manifest file before running the `kubectl delete` command and that seems to have helped:
> > ```
> > apiVersion: kfdef.apps.kubeflow.org/v1
> > kind: KfDef
> > metadata:
> >   namespace: kubeflow
> >   ClusterName: cluster.local
> > ```
> 
> This worked for me, I had to use the full name `cluster-name`.`region`.eksctl.io

works for me.

replace the ClusterName with your onw cluster name. Get it by `kubectl config view`
