### ISSUE TITLE
Enable sensible set of linters/staticcode analysis

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/kubeflow#4817]
/kind feature

**Why you need this feature:**
Since I started contributing to kubeflow I ran into a lot of violations of go best practices that could have been surfaced by a set of linters/static code analysis tools.

**Describe the solution you'd like:**
I'd suggest adding https://github.com/golangci/golangci-lint to run for new pull requests.
Since this is relatively lightweight (compared to full e2e tests), I'd also suggest adding a separate github check for that, so it can run on all new PRs without a ok-to-test label.

**Anything else you would like to add:**
While I can help adding the linter, I can't commit fixing all the issues it would complain about. Maybe there is a way to, for now, only lint new code.

**Comment by jlewi** [comment]
Lint tests would be a huge improvement. We've been looking for a way to do this that makes it super easy to add the same tests to all repos.

Current thinking is to use Tekton to create reusable tasks and pipelines. Its possible Tekton already has tasks for lint and other static analysis that we could reuse.

So one place to start might be defining Tekton pipelines to run lint. We could then incorporate that into our CI system once Tekton support is integrated (#622).

Our current tekton templates are here:
https://github.com/kubeflow/testing/tree/master/tekton/templates

Some related issues
kubeflow/testing#425 for Tekton support
kubeflow/examples#729

**Comment by jlewi** [comment]
You can now use Tekton to write reusable test pipelines: refer to

https://github.com/kubeflow/testing/blob/master/docs/tekton.md
https://github.com/kubeflow/testing/tree/master/tekton

We have a reusable pipeline for running go unittests but not lint yet.

**Comment by jlewi** [comment]
I think we would want reusable tests for

* golint
* pylint
* py unittests

**Comment by scottilee** [comment]
Since it has been a while I have a couple questions... is Tekton run in Prow and if so why? If not then when are things like tests run in Tekton versus in Prow?

**Comment by discordianfish** [comment]
Still relevant

**Comment by yanniszark** [comment]
For notebook-controller, will be addressed by:
https://github.com/kubeflow/kubeflow/pull/5403
