### ISSUE TITLE
Some jupyter customrize

### ISSUE THREAD

**Issue by DanaHan** [kubeflow/kubeflow#4818]
/kind question

**Question:**
I am testing Kubeflow V1.0. Everything is ok. I want to change some settings of jupyter web app for my real application.
1. I have 6 Nvidia GPUs. But in the gpu nums select list of  jupyter web app, I can only choose None,1,2,4,8. How can I change this gpu num list settings. I found this feature is hardcode in ts file. Is there a simple way to modify these values?
2.By default, when I click connect button, I can visit classic jupyterHub UI. And I know I can change the URI for /tree to /lab to access jupyterlab. How can I change a setting to access jupyterlab directly?

**Comment by Jeffwan** [comment]
> I have 6 Nvidia GPUs. But in the gpu nums select list of jupyter web app, I can only choose None,1,2,4,8. How can I change this gpu num list settings. I found this feature is hardcode in ts file. Is there a simple way to modify these values?

https://github.com/arrikto/kubeflow/blob/d5b42667e633a819324d727567b81606f6e2fc01/components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.ts#L18
it's fixed value here but I think you can override setting here. https://github.com/arrikto/kubeflow/blob/d5b42667e633a819324d727567b81606f6e2fc01/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml#L126


> By default, when I click connect button, I can visit classic jupyterHub UI. And I know I can change the URI for /tree to /lab to access jupyterlab. How can I change a setting to access jupyterlab directly?

https://github.com/kubeflow/kubeflow/blob/dcaeee742984533a2aff34bb28e14ea5aa9ae74a/components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.ts#L89

You probably can specify `/lab` here.

**Comment by DanaHan** [comment]
@Jeffwan ,Thank you.
1. I have tried to uncomment  this line    # values: "none", "1", "2", "4", "8". But the jupyter web app create page become blank for all list.
2. Yes, I can modify this line window.open(`/notebook/${rsrc.namespace}/${rsrc.name}/`). But I am not sure where can I change this settings for an installed kubeflow. Do I need to compile kubeflow again?

**Comment by Jeffwan** [comment]
> @Jeffwan ,Thank you.


> 1. I have tried to uncomment  this line    # values: "none", "1", "2", "4", "8". But the jupyter web app create page become blank for all list.

Check UI console for the errors. 

> 2. Yes, I can modify this line window.open(`/notebook/${rsrc.namespace}/${rsrc.name}/`). But I am not sure where can I change this settings for an installed kubeflow. Do I need to compile kubeflow again?

Technically, we can customize it and build your own  image, and replace the image in kubeflow/manifests.

**Comment by DanaHan** [comment]
jupyter web app console show "kubeflow_jupyter.common.utils | ERROR | Notebook config is not a valid yaml"

**Comment by Jeffwan** [comment]
> jupyter web app console show "kubeflow_jupyter.common.utils | ERROR | Notebook config is not a valid yaml"

Another solution is to do `jupyter lab ` to enable lab page by default.

**Comment by DanaHan** [comment]
@Jeffwan .
My server consistent runs in kubeflow V0.4 before. In this version. spawner.py is exposed in config-map. So I can custom deployment method by my self. "c.KubeSpawner.default_url = '/lab'" is used to access jupyterlab directly.

I also add "if self._default_config_contains('cpu')" to confirm whether I am using a cpu version image and disable gpu settings in jupyter create page in case of user request gpu cards with a cpu version image.

By the way, I have customized jupyter tensorflow images to access jupyterlab now. But this method is not convenient if people just want to change the access URL. And for the new official version images,  this step need to repeat.

**Comment by Jeffwan** [comment]
@DanaHan I will create an issue to enable lab by default. Let's see if users has concerns or not. Please vote if you want this feature. https://github.com/kubeflow/kubeflow/issues/4838

**Comment by hemantha-kumara** [comment]
> My server consistent runs in kubeflow V0.4 before. In this version. spawner.py is exposed in config-map. So I can custom deployment method by my self. "c.KubeSpawner.default_url = '/lab'" is used to access jupyterlab directly.

@DanaHan @Jeffwan We have created custom image with `--NotebookApp.default_url='/lab'` option in Dockerfile CMD and by default /lab is opening whenever we connect notebook

Added above option along with options mentioned in this doc 
https://www.kubeflow.org/docs/notebooks/custom-notebook/ 
`CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}" --NotebookApp.default_url='/lab']`

**Comment by DanaHan** [comment]
@Jeffwan @hemantha-kumara ，Thanks.
In my opinion, it's not a good idea to set defalut in docker file.
It should be a choice to give platform admin to set this value. If some custom settings can be exposed to a config-map should be a good idea.

**Comment by nrchakradhar** [comment]
@DanaHan Agree with you that if it can be made more configurable, it will help.

**Comment by hemantha-kumara** [comment]
> It should be a choice to give platform administrator to set this value. If some more customized settings can be exposed to a config-map should be a good idea.

Yes, I agree with you. It would be good if custom settings can be exposed via configmap. 
But in our case, custom image is created by us and hence we did it via Dockerfile.

**Comment by DanaHan** [comment]
@hemantha-kumara .
Yes, Now I also customize my personal images by:
CMD ["sh","-c", "jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]

**Comment by DanaHan** [comment]
Finally, I find how to set GPU num list:
I find in   https://github.com/kubeflow/kubeflow/blob/51fb79ad06b761af135fae6d3b04dad01ecbd440/components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.html#L16
The GPU num list is get from parameters "v".

So in config-map jupyter-web-app-config.
In GPU section: you can add v: {"none", "1", "2", "4", "8", "16"} to change default gpu list values to suitable your platform.

**Comment by kimwnasptd** [comment]
@DanaHan could we re-open this issue?

I think the best way to handle it is to add a more intuitive name in the gpu configuration section of the web app's config to allow the users to edit this list.

I can add a fix for it

**Comment by DanaHan** [comment]
@kimwnasptd 
Of course. I also want a more intuitive way to tell user how to customize kubeflow.

**Comment by DanaHan** [comment]
@kimwnasptd
Of course. I also want a more intuitive way to tell user how to customize kubeflow.

**Comment by KonstantinosAnd** [comment]
Hello guys! I would be interested in implementing this. @kimwnasptd Would you mind if worked on this one?

**Comment by kimwnasptd** [comment]
@KonstantinosAnd sure! We'll need to

1. add another field in the `gpus` section of web app's config.
2. extend the frontend to utilize this field, or show the default `1, 2, 4, 8` options if it doesn't find this setting in the config
3. update the config in the manifests repo

You could tackle the first two in a PR as a first step and then we'll make another one for the manifests.

/assign @KonstantinosAnd

**Comment by jbottum** [comment]
@kimwnasptd @KonstantinosAnd Hi Guys, What is the status of this?   Can we have it by Kubeflow 1.1 or should we downgrade or push it to the next release?

**Comment by bravo325806** [comment]
@DanaHan I have try to add v: {"none", "1", "2", "4", "8", "16"}  in config-map jupyter-web-app-config.
I add in gpus layer or value layer can't change default gpu list values 
can you show how you modified it? Thanks
