### ISSUE TITLE
GPU select

### ISSUE THREAD

**Issue by DanaHan** [kubeflow/kubeflow#4821]
/kind feature

**Why you need this feature:**
I have a GPU server runs kubeflow V1.0. In this server, I have 2 TitanV cards and 4 2080Ti. These have different SM cores and video memory. I want to use different cards for different test. But now, in kubeflow I can only select gpu nums for a jupyter web app. I can not select GPU model when I create a jupyter web app. This feature is important in this hyper-gpu server.

**Describe the solution you'd like:**
In jupyter web app create page. It is better to add a list to show which cards are available now after confirm the request GPU NUMS. Or a checkbox list to show the GPU card model select.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Jeffwan** [comment]
They are both NVDIA GPUs, right? Do you mean you have 2 TitanV cards and 4 2080Ti on one server? If so, how do you select different GPU without Kubeflow?

**Comment by DanaHan** [comment]
Of course. They are both Nvidia GPUs. It is easy to distinguish different cards. For example, the list can show card IDs. Or at least, I want to request the different GPU models(2080Ti or Titan).

**Comment by Jeffwan** [comment]
> Of course. They are both Nvidia GPUs. It is easy to distinguish different cards. For example, the list can show card IDs. Or at least, I want to request the different GPU models(2080Ti or Titan).

I ask this is because this is not a Kubeflow problem. Can you tell us how do you use different GPUs in Kubernetes without Kubeflow?

**Comment by DanaHan** [comment]
@Jeffwan . 
1.A single server with different GPU cards is very common for small labs or companies.Because they will continue to add or replace new GPU cards according to the budgets. 
2.My server consistent runs in kubeflow. When users requset GPUs，if I can not select GPU model, for example, I will get both 2080Ti and TitanV in a single container. But these cards have different SM cores number and memory. When I run a train task with multi-gpus, the titanV will be delayed by 2080Ti for the different core frequency and titanV gpu memory will be wasted. For some big resolution pictures train task, 2080Ti's memory is not enough.
3. A workaround in the bare server may set nv_visable to special gpu model.
4.What should we do in kubeflow is we can show gpu ids or gpu models list in jupyter web app create page. In this way, users can request only 2080Ti or TitanV in a container.

**Comment by yanniszark** [comment]
Hi @DanaHan!
This is an interesting problem so I thought I would take a look and try to find out what people are doing to solve it.

First of all, the K8s docs on GPU scheduling advice the user to have different types of GPU live on different Nodes and then make use of NodeSelector:

>If different nodes in your cluster have different types of GPUs, then you can use Node Labels and Node Selectors to schedule pods to appropriate nodes.

Source: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#clusters-containing-different-types-of-gpus

In K8s, GPU scheduling is implemented using [kubelet device plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/).

The procedure is more or less the following:
* A gRPC server (nvidia daemonset) is running on each Node and advertises the available gpu resources. Notice that gpu resources are exposed as "nvidia.com/gpu", so the kubelet doesn't know there are differences between them.
* When a Pod is created that requests a "nvidia.com/gpu", the kubelet selects some of the available GPU IDs and allocates them to the container.

As you can see, the current model doesn't really work for Nodes which have multiple types of GPU cards.
I see two possible solutions here:
* Have each GPU model live in its own Node. (e.g., 1 Node for GTX Titan V, 1 Node for 2080Ti)
* Run a device plugin for each GPU model (e.g., nvidia.com/gpu-gtx-titan-v, nvidia.com/gpu-gtx-2080-ti, etc.) The latter requires some hacking around with NVidia's Device Plugin (https://github.com/NVIDIA/k8s-device-plugin) 

Relevant Issue: https://github.com/NVIDIA/k8s-device-plugin/issues/133

All in all, this is a K8s issue.

**Comment by DanaHan** [comment]
@yanniszark Thanks for your detailed explain.
You are right. It's K8s issue. We can not control k8s and nvidia plugins roadmaps.
So I think we should discuss a workaround in kubeflow now.

As I have said. In a bare server, I can set CUDA_VISIBLE_DEVICES before run a deeplearning task. In the post below, it discusses how to set Environment variables(OCI spec) to select a special card model when create a container.
[https://github.com/NVIDIA/nvidia-container-runtime#environment-variables-oci-spec](url)

First of all, I think we should perform a minimal modification to achieve our goal.
I use cadvisor embedded in kubelet to get gpu metrics now. Cadvisor can back GPU model name.
So is it possible 1) get gpu info from cadvisor or as most monitor software from nvidia-smi; 2) set  Environment variables to control which gpu can be request this time. 3) create my container.

**Comment by jlewi** [comment]
Can you achieve what you want by creating Notebook resources via `kubectl` and specifiying the appropriate settings in the PodTemplateSpec?

**Comment by richardsliu** [comment]
It might be helpful to have a way to add node selector labels in the UI. Then the user will be able to add custom selectors like accelerator type, node pool, etc.
