### ISSUE TITLE
Fix the documentation on "Application code grant" screenshot

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/kubeflow#4826]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Congito docs page

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
Can somebody add what are the "Application code grant" that one needs to add for cognito in this page https://www.kubeflow.org/docs/aws/authentication/ at "In order to authenticate and manage users for Kubeflow, let’s create a user pool." . Its just another line in the screenshot but its missing. Please add it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by imskr** [comment]
I would like to fix this!
