### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH on Cloud Endpoint

### ISSUE THREAD

**Issue by aaaaahaaaaa** [kubeflow/kubeflow#4828]
/kind bug

**What steps did you take and what happened:**
Deployed Kubeflow on GCP using the CLI following the documentation for a customised deployment (https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#customizing-your-kubeflow-deployment). Only updated `cluster.jinja` to specify the network and subnetwork configuration before creating the deployment.

Once deployed, endpoint (cloud.goog domain) shows the following error:
>ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**What did you expect to happen:**
Kubeflow UI to be served through cloud.goog domain.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: `1.0`:
- kfctl version: `v1.0-0-g94c35cf`:
- Kubernetes platform: GCP
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.24", GitCommit:"f2734800eba37df4400813ab9340886059d56105", GitTreeState:"clean", BuildDate:"2020-02-05T18:38:43Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): MacOS 10.15.3

**Comment by aaaaahaaaaa** [comment]
Well, somehow the deployment just healed itself. It's now working.

**Comment by NikeNano** [comment]
If any one else end up here, wait a couple of minutes up to ~20 ish and you should be good!
