### ISSUE TITLE
Notebook server cannot start notebook in anonymous namespace

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4831]
/kind bug

This happens on a Kubeflow cluster without IAP. Try to start a notebook session in anonymous namespace, and this error comes up:

`User None is not authorized to list .v1.persistentvolumeclaims for namespace: anonymous`

**Comment by tall-josh** [comment]
I think this is related. After following the aws install instructions. I create a profile and attempt to create a notebook only to be met with:
![image](https://user-images.githubusercontent.com/18511395/75943480-32268e80-5ee9-11ea-944c-523516518b1c.png)

I am VERY new to Kube and Kubeflow. So it is entirely possible I'm just doing something silly.

**Comment by krishnadurai** [comment]
@richardsliu could you also provide the name of the config you are using?

Related issue: https://github.com/kubeflow/kubeflow/issues/4731

**Comment by richardsliu** [comment]
@krishnadurai I was using https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_anthos.v1.0.0.yaml

**Comment by krishnadurai** [comment]
@richardsliu you could add an envoy filter to the anthos config as implemented here:

https://github.com/kubeflow/manifests/pull/885

Refer to the discussion in #4731

**Comment by jbottum** [comment]
@jtfogarty Jeff, I moved it to Kubeflow 1.1

**Comment by hexiaoliangRick** [comment]
@krishnadurai  i have same problem.can you help.
i use k8s 1.7.5 , istio 1.6.5  and kubeflow kfctl_k8s_istio.v1.0.2.yaml, and i changed the type of service istio-ingressgateway  from 'load balancer' to 'node port'。 
1. i user `istioctl manifest apply \
    --set profile=demo \
    --set values.kiali.enabled=true \
    --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
    --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"`
to install istio.
2. i delete **istio-cards** and **istio-install ** in kfctl_k8s_istio.v1.0.2.yaml. and then ,i user `kfcetl apply -v -f kfctl_k8s_istio.v1.0.2.yaml` to install my kubeflow.

3. i change the type of service istio-ingressgateway in istio-system namespace .


what should i do to fix this problem?
![image](https://user-images.githubusercontent.com/54734710/87687541-70498e00-c7b8-11ea-822e-35f20d55c6fd.png)

**Comment by hexiaoliangRick** [comment]
> @krishnadurai i have same problem.can you help.
> i use k8s 1.7.5 , istio 1.6.5 and kubeflow kfctl_k8s_istio.v1.0.2.yaml, and i changed the type of service istio-ingressgateway from 'load balancer' to 'node port'。
> 
> 1. i user `istioctl manifest apply \ --set profile=demo \ --set values.kiali.enabled=true \ --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" \ --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"`
>    to install istio.
> 2. i delete **istio-cards** and **istio-install ** in kfctl_k8s_istio.v1.0.2.yaml. and then ,i user `kfcetl apply -v -f kfctl_k8s_istio.v1.0.2.yaml` to install my kubeflow.
> 3. i change the type of service istio-ingressgateway in istio-system namespace .
> 
> what should i do to fix this problem?
> ![image](https://user-images.githubusercontent.com/54734710/87687541-70498e00-c7b8-11ea-822e-35f20d55c6fd.png)
ok after i remove istio1.6.5 and install istio 1.4.3. i solved this problem.

**Comment by connorlwilkes** [comment]
> > @krishnadurai i have same problem.can you help.
> > i use k8s 1.7.5 , istio 1.6.5 and kubeflow kfctl_k8s_istio.v1.0.2.yaml, and i changed the type of service istio-ingressgateway from 'load balancer' to 'node port'。
> > 
> > 1. i user `istioctl manifest apply \ --set profile=demo \ --set values.kiali.enabled=true \ --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" \ --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"`
> >    to install istio.
> > 2. i delete **istio-cards** and **istio-install ** in kfctl_k8s_istio.v1.0.2.yaml. and then ,i user `kfcetl apply -v -f kfctl_k8s_istio.v1.0.2.yaml` to install my kubeflow.
> > 3. i change the type of service istio-ingressgateway in istio-system namespace .
> > 
> > what should i do to fix this problem?
> > ![image](https://user-images.githubusercontent.com/54734710/87687541-70498e00-c7b8-11ea-822e-35f20d55c6fd.png)
> > ok after i remove istio1.6.5 and install istio 1.4.3. i solved this problem.

Any idea why this worked with Istio 1.4.3 and not with 1.6.5. I am facing a similar issue using Istio 1.5.10 and I don't quite know why downgrading would make a difference here?

**Comment by connorlwilkes** [comment]
> @richardsliu you could add an envoy filter to the anthos config as implemented here:
> 
> [kubeflow/manifests#885](https://github.com/kubeflow/manifests/pull/885)
> 
> Refer to the discussion in #4731

@krishnadurai even when adding that I still get this same issue.

Output of commands below:

```
$ k describe envoyfilter add-user-filter -n kubeflow
Name:         add-user-filter
Namespace:    kubeflow
Labels:       <none>
Annotations:  API Version:  networking.istio.io/v1alpha3
Kind:         EnvoyFilter
Metadata:
  Creation Timestamp:  2020-09-11T16:18:15Z
  Generation:          1
  Resource Version:    7827660
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/kubeflow/envoyfilters/add-user-filter
  UID:                 f72125c1-011a-4c75-9455-4de129323c21
Spec:
  Filters:
    Filter Config:
      Inline Code:  function envoy_on_request(request_handle)
    request_handle:headers():add("kubeflow-userid","anonymous@kubeflow.org")
end

    Filter Name:  envoy.lua
    Filter Type:  HTTP
    Insert Position:
      Index:  FIRST
    Listener Match:
      Listener Type:  GATEWAY
  Workload Labels:
    App:  istio-ingressgateway
Events:   <none>

$ k describe profiles kubeflow-anonymous
Name:         kubeflow-anonymous
Namespace:
Labels:       <none>
Annotations:  API Version:  kubeflow.org/v1
Kind:         Profile
Metadata:
  Creation Timestamp:  2020-09-11T16:22:21Z
  Finalizers:
    profile-finalizer
  Generation:        2
  Resource Version:  7829296
  Self Link:         /apis/kubeflow.org/v1/profiles/kubeflow-anonymous
  UID:               44fae551-c7dc-4e62-b389-650b92121eac
Spec:
  Owner:
    Kind:  User
    Name:  anonymous@kubeflow.org
  Resource Quota Spec:
Events:  <none>

k exec -it -n kubeflow jupyter-web-app-deployment-55cdff4ff9-82gvt env | grep USERID
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Defaulting container name to jupyter-web-app.
Use 'kubectl describe pod/jupyter-web-app-deployment-55cdff4ff9-82gvt -n kubeflow' to see all of the containers in this pod.
USERID_HEADER=kubeflow-userid
USERID_PREFIX=

$ k logs jupyter-web-app-deployment-55cdff4ff9-82gvt -c jupyter-web-app
2020-09-11 16:49:49,045 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:49] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
2020-09-11 16:49:50,050 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:50] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
2020-09-11 16:49:52,050 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:52] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
2020-09-11 16:49:53,059 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:53] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
2020-09-11 16:49:55,948 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:55] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
2020-09-11 16:49:59,232 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.
127.0.0.1 - - [11/Sep/2020 16:49:59] "GET /api/namespaces/kubeflow-anonymous/notebooks HTTP/1.1" 200 -
```

This is using 1.5.10 version of Istio. I have tried kicking the pod to no avail
