### ISSUE TITLE
CentralDashboard failed to start on custom k8s

### ISSUE THREAD

**Issue by gtarcoder** [kubeflow/kubeflow#4832]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I installed kubeflow on own k8s cluster following these guides (https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/, https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) .
But failed to access kubeflow's central dashboard.  After investigating, I found something is wrong wtih centraldashboard...
Executing kubectl get pods -n kubeflow , gets following results:
NAME                                                  READY             STATUS    RESTARTS AGE
centraldashboard-869f55ddbd-mwkg4 0/1 CrashLoopBackOff      2              31s

Executing kubectl logs -n kubeflow centraldashboard-869f55ddbd-mwkg4 gets following results:
`
kubeflow-centraldashboard@0.0.2 start /app
npm run serve

kubeflow-centraldashboard@0.0.2 serve /app
node dist/server.js
`

**What did you expect to happen:**
Can get access to central dashboard

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`) rancher
- Kubernetes version: (use `kubectl version`): v1.14.3, git commit 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
- OS (e.g. from `/etc/os-release`): ubunt16.04

**Comment by tomalbrecht** [comment]
When I got such CrashLoopBackOffs errors, they recovered over time. It takes some time for kfctl to pull all images and deploy them - there are dependencies to other pods. The cluster will retry after a while. In my case it took around 30-45 minutes until everything was running. 

Please check the istio-system namespace as well. This namespace should come up in early stages of the deployment. If it doesn't it's very likely the whole deployment will never come up. In this case you should check the logs in this namespace.

**Comment by urekalion** [comment]
in my case, denisl78's solution is worked in #4819

**Comment by gtarcoder** [comment]
> in my case, denisl78's solution is worked in #4819

thanks, that works.

**Comment by gtarcoder** [comment]
#4819 seems caused by this bug.. It can be resolved following #4819.
