### ISSUE TITLE
Kubeflow 1.0.1 release

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4834]
/kind question

**Question:**
Request a patch release. AWS has a few improvements and we'd love to roll out in the new version. 

1.  kfctl v1.0.1
  - https://github.com/kubeflow/kfctl/compare/v1.0...v1.0-branch
2. manifest v1.0.1
  - https://github.com/kubeflow/manifests/compare/v1.0.0...v1.0-branch
  - https://github.com/kubeflow/manifests/issues/984

Seems kfctl version for 1.0 doesn't use semantic versioning?  Should we cut 1.0.1 or 1.1.0? 
We had some discussion here. 
https://github.com/kubeflow/kubeflow/issues?q=is%3Aissue+is%3Aopen+1.0+cut

Feel free to add more commits which address 1.0 issues and we can have them release together.

**Comment by richardsliu** [comment]
For fixes we should release a patch, e.g. 1.0.1. 

I need to figure out the patch upgrade story since we've release the feature in 1.0.

**Comment by richardsliu** [comment]
This is done now.

**Comment by Jeffwan** [comment]
Thanks! @richardsliu.  Richard help release Kubeflow v1.0.1. All AWS feature in https://github.com/kubeflow/kubeflow/issues/4719 should be unlocked
