### ISSUE TITLE
Failed to install Minikf on Windows 10

### ISSUE THREAD

**Issue by redcican** [kubeflow/kubeflow#4836]
Hello, I tried to install the latest version of minikf followed the official instruction. But it failed. Does anyone have an idea to solve it?
![Download](https://user-images.githubusercontent.com/10456402/76154356-46ca7880-60db-11ea-9956-c1d0acfe98d3.png)

**Comment by cschieberle** [comment]
I ran into the same issue? Any chance this was solved?

**Comment by srmeier** [comment]
Also having this issue.

**Comment by yanniszark** [comment]
Hi @redcican @srmeier!
Thanks for using MiniKF.
The error you're seeing means that Minikube timed out waiting for the API-Server to come up.

This could be an issue with the machine you're using not being powerful enough.
What are your system and VM specs? Do you meet the following requirements?
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikf/#system-requirements

If you meet the requirements, can you please send us some logs to debug further? Here's how to do it:

1. `vagrant ssh` into your MiniKF VM
1. Run `minikf-gather-logs`. This will produce a tarball .tgz file in your MiniKF directory.
1. Please share the tarball here

**Comment by srmeier** [comment]
@yanniszark, Thanks. I believe you're right about the resources. My computer has 32GB ram but my VirtualBox was only showing a 10GB allocated amount. After playing around a little, I adding the following to my `Vagrantfile`:

```
config.vm.provider "virtualbox" do |vb|
    vb.memory = "20480"
end
```

And I was able to get past this error.

**Comment by Vikram486** [comment]
I am getting below error.
![MiniKF error](https://user-images.githubusercontent.com/53994396/86521579-72ceee00-be70-11ea-9f68-2474897777e5.PNG)
