### ISSUE TITLE
KfAwsPlug preventing install

### ISSUE THREAD

**Issue by awcchungster** [kubeflow/kubeflow#4837]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The KF installer breaks on stable 1.0

I run: 

> kfctl apply -V -f ${CONFIG_FILE}

And this error occurs

> INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:54"
> INFO[0000] output: [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.13.0"}  filename="utils/awsutil.go:62"
> INFO[0000] 
> ****************************************************************
> Notice anonymous usage reporting enabled using spartakus
> To disable it
> If you have already deployed it run the following commands:
>   cd $(pwd)
>   kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
> 
> For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
> ****************************************************************
>   filename="coordinator/coordinator.go:120"
> INFO[0000] Deleting cachedir /home/ubuntu/kf1stable/kubeflow-1-rc-1/.cache/manifests because Status.ReposCache is out of date  filename="kfconfig/types.go:472"
> INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.0.0.tar.gz to /home/ubuntu/kf1stable/kubeflow-1-rc-1/.cache/manifests  filename="kfconfig/types.go:493"
> INFO[0000] updating localPath to /home/ubuntu/kf1stable/kubeflow-1-rc-1/.cache/manifests/manifests-1.0.0  filename="kfconfig/types.go:540"
> INFO[0000] Fetch succeeded; LocalPath /home/ubuntu/kf1stable/kubeflow-1-rc-1/.cache/manifests/manifests-1.0.0  filename="kfconfig/types.go:561"
> INFO[0000] Caller ARN Info: {
>   Account: "840279583790",
>   Arn: "arn:aws:iam::840279583790:user/alchung-test",
>   UserId: "AIDA4HJEQ5QXBQES3TWBS"
> }  filename="utils/awsutil.go:38"
> ERRO[0000] Could not unmarshal plugin KfAwsPlugin to the provided type; error error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field AwsPluginSpec.roles of type []string  filename="kfconfig/types.go:245"
> Error: failed to build kfApp from URI /home/ubuntu/kf1stable/kubeflow-1-rc-1/kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for aws:  (kubeflow.error): Code 500 with message: aws set aws plugin defaults Error Could not unmarshal plugin KfAwsPlugin to the provided type; error error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field AwsPluginSpec.roles of type []string
> Usage:
>   kfctl apply -f ${CONFIG} [flags]
> 
> Flags:
>   -f, --file string   Static config file to use. Can be either a local path:
>                                 export CONFIG=./kfctl_gcp_iap.yaml
>                         or a URL:
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
>                         kfctl apply -V --file=${CONFIG}
>   -h, --help          help for apply
>   -V, --verbose       verbose output default is false
> 
> failed to build kfApp from URI /home/ubuntu/kf1stable/kubeflow-1-rc-1/kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for aws:  (kubeflow.error): Code 500 with message: aws set aws plugin defaults Error Could not unmarshal plugin KfAwsPlugin to the provided type; error error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field AwsPluginSpec.roles of type []string

**What did you expect to happen:**

Kubeflow would be set up

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):  kfctl v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`): EKS
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by awcchungster** [comment]
@Jeffwan Do you know what is happening here?

**Comment by awcchungster** [comment]
#4642

**Comment by Jeffwan** [comment]
could you share more info in your ticket next time? 

```
Could not unmarshal plugin KfAwsPlugin to the provided type; error error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field AwsPluginSpec.roles of type []string
```

Please share the kfAwsPlugin setting in your manifest, I doubt if your setting is correct

**Comment by PatrickXYS** [comment]
I think this is manifest KfAwsPlug format error, and should be solved.

/close
