### ISSUE TITLE
Enable JupyterLab view by default

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4838]
/kind feature

**Why you need this feature:**
https://github.com/kubeflow/kubeflow/issues/4818

Currently, user has to change url to `/lab` to switch to lab view. I am thinking if we want to enable lab view as default option and user can still switch to default view. 

Any concerns or insights? If not, I will update container images.

**Comment by hemantha-kumara** [comment]
@Jeffwan Have you tried setting in `--NotebookApp.default_url='/lab'` option in Dockerfile CMD?
`jupyter notebook --notebook-dir=/home/cjup --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.default_url='/lab'`

We have created custom image with above mentioned command and by default /lab is opening whenever we connect notebook.

**Comment by hemantha-kumara** [comment]
@Jeffwan 
As discussed in #4818 it would be good if we could handle settings from configmap instead of changing in all Dockerfile.

May be we can put /lab by default in configmap.

**Comment by Jeffwan** [comment]
@hemantha-kumara Make sense. Trying to see any concerns to make that. If not, I will go change configmap

**Comment by jrykr** [comment]
@Jeffwan is the plan still to implement this via configmap? I just came across this issue after I too changed to `/lab` manually. Looks like the issue has gone stale, and I couldn't locate a solution elsewhere.

**Comment by Jeffwan** [comment]
@jrykr I feel like it's much easier to change image. This should be default view. I think I will add it in next release.

**Comment by DavidSpek** [comment]
I agree that Jupyter Lab should be the default view and that it should be set in the images. This should be discussed with the notebook WG.
