### ISSUE TITLE
TF serving GPU e2e test is flaky

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#484]
Example: #482 the test failed in a doc PR

**In the step deploy-tf-serving-gpu, it verified deployment is up.**
INFO|2018-03-22T19:11:44|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/testing/py/kubeflow/testing/util.py|263| Deployment inception-gpu in namespace kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67 is ready

**However, in test-tf-serving-gpu step, it failed:**
INFO|2018-03-22T19:11:48|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/kubeflow/testing/test_tf_serving.py|99| prediction failed: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed"). Retrying...
INFO|2018-03-22T19:11:53|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/kubeflow/testing/test_tf_serving.py|99| prediction failed: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed"). Retrying...
INFO|2018-03-22T19:12:04|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/kubeflow/testing/test_tf_serving.py|116| Writing test results to /mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/output/artifacts/junit_kubeflow-tf-serving-image-inception-gpu.xml
INFO|2018-03-22T19:12:04|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/testing/py/kubeflow/testing/test_util.py|151| Creating /mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/output/artifacts/junit_kubeflow-tf-serving-image-inception-gpu.xml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/kubeflow/testing/test_tf_serving.py", line 127, in <module>
    main()
  File "/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-482-70f83cc-790-8b67/src/kubeflow/kubeflow/testing/test_tf_serving.py", line 94, in main
    result = str(stub.Predict(request, 10.0))  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")

**Comment by jlewi** [comment]
Can we disable the test for now?

**Comment by jlewi** [comment]
Could it be related to this?
https://github.com/grpc/grpc/issues/14653

**Comment by lluunn** [comment]
Able to repro in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/485/kubeflow-presubmit/798/

grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")

**Comment by lluunn** [comment]
The deployment was up and running..

kubectl get -n=kubeflow-presubmit-tf-serving-image-485-4aba7d5-798-0411 deploy
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
inception-cpu   1         1         1            1           1h
inception-gpu   1         1         1            1           1h

**Comment by lluunn** [comment]
It looks like although the deployment is ready, the model server is still loading the model when we tried prediction. This should be the issue.

**Comment by lluunn** [comment]
#486 
kubeflow-presubmit-tf-serving-image-486-ba58eb1-801-14d8

Test failed; Timeout waiting for deployment inception-gpu in namespace kubeflow-presubmit-tf-serving-image-486-ba58eb1-801-14d8

**Comment by lluunn** [comment]
Sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/543/kubeflow-presubmit/937/

ERROR|2018-03-30T18:47:56|/mnt/test-data-volume/kubeflow-presubmit-tf-serving-image-543-4476009-937-d294/src/kubeflow/testing/py/kubeflow/testing/util.py|266| Timeout waiting for deployment inception-gpu in namespace kubeflow-presubmit-tf-serving-image-543-4476009-937-d294 to be ready

From Stackdriver, I can only see logs from inception-cpu, no inception-gpu

![screenshot from 2018-04-02 12-22-17](https://user-images.githubusercontent.com/32310205/38211830-8e091c3e-3670-11e8-8e63-873bc3b2835b.png)

**Comment by lluunn** [comment]
There is no gpu in the cluster...

**Comment by lluunn** [comment]
Some update in #558.
I can't reproduce the error. I add a sleep and verified we can see logs for gpu deployment. I think we can submit #558 and see if error occurs again.

**Comment by jlewi** [comment]
According to our dashboard the GPU tests seem to be running reliably
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-postsubmit

Closing this issue.
