### ISSUE TITLE
Error installing kfctl_istio_dex on k8s: failed to fetch "istio-token"

### ISSUE THREAD

**Issue by Oblynx** [kubeflow/kubeflow#4840]
/kind bug

**What steps did you take and what happened:**

I try to install Kubeflow 1.0 on an on-premises k8s cluster following the [kfctl-istio-dex](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) instructions. After the kfctl run finishes I inspect the state of the cluster and discover pods stuck in `ContainerCreating` in namespace `istio-system` with the following error: `MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource`

#### details from a stuck pod

```bash
$ kubectl -n istio-system describe pod istio-pilot-55f7f6f6df-skbwg
...
Volumes:
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
...
Events:
  Type     Reason       Age                    From                                       Message
  ----     ------       ----                   ----                                       -------
  Warning  FailedMount  18m (x60 over 124m)    kubelet, kosamara-kf6-t6bhcj7vzwdp-node-0  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource

$ kubectl -n istio-system get -o yaml pod istio-pilot-55f7f6f6df-skbwg
...
  volumes:
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
```

**What did you expect to happen:**

To have no stuck pods.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: v1.0.0 (KfDef manifests from https://github.com/kubeflow/manifests/archive/v1.0.0.tar.gz)
- kfctl version: v1.0-0-g94c35cf
- Kubernetes platform: on-prem OpenStack Magnum (vanilla + coredns + flannel networking + traefik ingress)
- Kubernetes version: (use `kubectl version`): v1.15.3
- OS (e.g. from `/etc/os-release`): Fedora 29.20181126.0 (Atomic Host)

**Comment by krishnadurai** [comment]
This is a duplicate of kubeflow/manifests#959.

**Comment by Oblynx** [comment]
Indeed. That solved my issue, thanks!
