### ISSUE TITLE
How to write training framework

### ISSUE THREAD

**Issue by shaunc** [kubeflow/kubeflow#4841]
/kind question

**Question:**

We would like to evaluate kubeflow as a management platform around our ML library. Where can I find documentation/pointers on writing a training framework?

**Comment by jlewi** [comment]
I don't really understand what you mean by writing a training framework. 

One pattern Kubeflow uses to make certain types of computation easier (e.g. distributed training) is creating Kubernetes custom resources:
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

**Comment by shaunc** [comment]
Kubeflow supports (e.g.) tensorflow and pytorch out of the box. Where should we look for specifications/recipes/pointers for writing a wrapper for a different ML platform?
