### ISSUE TITLE
Unable to deploy Kubeflow on Openshift 3.11

### ISSUE THREAD

**Issue by soumochak83** [kubeflow/kubeflow#4844]
Platform details: Openshift OKD 3.11
Kubeflow version: 0.5
I'm trying to deploy Kubeflow using the documentation - https://v0-5.kubeflow.org/docs/started/getting-started-k8s/. However seeing this error while trying to run the command - kfctl init ${KFAPP}

kfctl init ${KFAPP}
FATA[0000] could not download repo to cache Error  (kubeflow.error): Code 400 with message: couldn't download kubeflow repo https://github.com/kubeflow/kubeflow/tarball/v0.5.1?archive=tar.gz Error Error opening a gzip reader for /tmp/getter164338714/archive: EOF  filename="coordinator/coordinator.go:304"

Please help to fix this issue.

**Comment by jbottum** [comment]
@pdmack hey pete, any comments on this ?
