### ISSUE TITLE
Unable to connect to kubeflow dashboard-"upstream connect error or disconnect/reset before headers. reset reason: connection termination"

### ISSUE THREAD

**Issue by MeghanaSrinath** [kubeflow/kubeflow#4846]
I followed [this](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) guide to setup kubeflow along with Dex and Istio.

I was able to successfully install kubeflow and obtained the LoadBalancer IP from the command:
```
kubectl get svc -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0]}'
```

But when I hit the kubeflow IP in the browser, I get the error as
```
RBAC: access denied.
```

As per the suggestion in [this](https://github.com/kubeflow/kubeflow/issues/3975) post, I tried turning OFF the Istio's ClusterRbacPolicy.
On re-trying, I get the error as:
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination.
```

Are there any additional changes required for the setup?
```
kfctl version
kfctl v1.0-0-g94c35cf

istioctl version
client version: 1.4.5
cluster-local-gateway version:
citadel version: 1.4.5
galley version: 1.4.5
ingressgateway version: 1.4.5
pilot version: 1.4.5
policy version: 1.4.5
sidecar-injector version: 1.4.5
telemetry version: 1.4.5
data plane version: 1.4.5 (3 proxies), 1.3.1 (1 proxies)

kubernetes version
v1.14.10-gke.17

OS:
Ubuntu
```

**Comment by MeghanaSrinath** [comment]
Turns out, it was a firewall issue in our k8s cluster. I tried by allowing all traffic on the ports and it worked. however, if there is a requirement for specific ports to be open to traffic, can this be included in the document?

**Comment by jshelman** [comment]
I have same issue after fresh install of 1.0.1.   @MeghanaSrinath   how did you allow all traffic on all ports?

**Comment by MeghanaSrinath** [comment]
I created a firewall rule to allow traffic on all ports. But I had restricted the source range to our VPN (not to internet) and this rule was attached to all the required instances. This was only done to see if the issue was with the firewall or something else. Ideally, we should be allowing only the required ports to the required ranges. Hence would like to know the details as well!

**Comment by jlewi** [comment]
Closing this issue because it looks like the problem was resolved.

Kubeflow uses ISTIO and in the next release we will be switching to Anthos Service Mesh 
https://cloud.google.com/service-mesh/docs

to install and manage ISTIO on GKE. So you can look at the ASM docs to better understand how to restrict access to your clusters while still allowing Kubeflow to be accessible.
