### ISSUE TITLE
OIDC-Authservice integration with Ping Federate setup

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/kubeflow#4847]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Did the kfctl build and updated the oidc-authservice/base/params.env to include the following as an SSO integration setup with Ping Federate

client_id=kubeflow-oidc-authservice_OIDC_DEV1
oidc_provider=https://xxxx.org
oidc_redirect_uri=http://K8SAPIServerIP:31380/login/oidc
oidc_auth_url=https://xxxx.org/as/authorization.oauth2
application_secret=xxxxx
skip_auth_uri=/dex
userid-header=kubeflow-userid
userid-prefix=
namespace=istio-system

hi @yanniszark I have tried integrating with Ping and am running into issues as following. Not sure if am missing anything.

My authservice-0 log showing as follows
➜ kubectl logs authservice-0 -n istio-system
time="2020-03-09T22:08:39Z" level=info msg="Starting readiness probe at 8081"
time="2020-03-09T22:08:39Z" level=info msg="No USERID_TOKEN_HEADER specified, using 'kubeflow-userid-token' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SERVER_HOSTNAME specified, using '' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SERVER_PORT specified, using '8080' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SESSION_MAX_AGE specified, using '86400' as default."
time="2020-03-09T22:08:39Z" level=info msg="Starting web server at :8080"
time="2020-03-09T22:08:40Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: 404 Not Found: \n\n<title>404 Not Found</title>\n\nNot Found\n
The requested URL /.well-known/openid-configuration was not found on this server.
\n\n"

Also, not able to access the kubeflow dashboard using portforward and noticed above log

**What did you expect to happen:**
A redirect to the Ping SSO screen

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ➜ kubectl get pods -n istio-system          
NAME                                                         READY   STATUS      RESTARTS   AGE
authservice-0                                                0/1     Running     0          22h
cluster-local-gateway-9d544d7db-n55ln                        1/1     Running     0          22h
istio-citadel-75f76d94f-j5thr                                1/1     Running     0          22h
istio-galley-c9f4fb7bf-fp76b                                 1/1     Running     0          22h
istio-ingressgateway-68875ff4cd-pzf7h                        1/1     Running     0          22h
istio-nodeagent-bbxrd                                        1/1     Running     0          22h
istio-nodeagent-zbdsq                                        1/1     Running     0          22h
istio-pilot-99597b4f6-kcrrq                                  2/2     Running     0          22h
istio-policy-757f4d7856-48khj                                2/2     Running     0          22h
istio-security-post-install-release-1.3-latest-daily-5hdgg   0/1     Completed   0          22h
istio-sidecar-injector-5f5484c5f5-lvwjh                      1/1     Running     1          22h
istio-telemetry-598cdc58bf-2p722                             2/2     Running     0          22h
prometheus-7dbbf976d8-52lkb                                  1/1     Running     0          22h
(base) 

➜ kubectl get pods -n kubeflow
NAME                                                           READY   STATUS             RESTARTS   AGE
admission-webhook-deployment-5767bcf4b7-9pc4d                  1/1     Running            0          25h
application-controller-stateful-set-0                          1/1     Running            0          25h
argo-ui-778676df64-b5wbf                                       1/1     Running            0          25h
centraldashboard-869f55ddbd-spzdf                              1/1     Running            0          25h
jupyter-web-app-deployment-89789fd5-9qdtb                      1/1     Running            0          25h
katib-controller-6b789b6cb5-pn7tf                              1/1     Running            1          25h
katib-db-manager-64f548b47c-jwxtj                              0/1     CrashLoopBackOff   303        25h
katib-mysql-57884cb488-ct2k5                                   0/1     Pending            0          25h
katib-ui-5c5cc6bd77-s8d7c                                      1/1     Running            0          25h
kfserving-controller-manager-0                                 2/2     Running            1          25h
metadata-db-76c9f78f77-4lz4b                                   1/1     Running            1          25h
metadata-deployment-674fdd976b-kgfpv                           1/1     Running            0          25h
metadata-envoy-deployment-5688989bd6-s79bs                     1/1     Running            0          25h
metadata-grpc-deployment-5579bdc87b-7kwhz                      1/1     Running            19         25h
metadata-ui-9b8cd699d-6hw2j                                    1/1     Running            0          25h
minio-755ff748b-4llnd                                          0/1     Pending            0          25h
ml-pipeline-79b4f85cbc-pkbcg                                   0/1     CrashLoopBackOff   289        25h
ml-pipeline-ml-pipeline-visualizationserver-5fdffdc5bf-n2v2n   1/1     Running            0          25h
ml-pipeline-persistenceagent-645cb66874-v29z9                  0/1     CrashLoopBackOff   201        25h
ml-pipeline-scheduledworkflow-6c978b6b85-8z4wr                 1/1     Running            0          25h
ml-pipeline-ui-6995b7bccf-9z4m2                                1/1     Running            0          25h
ml-pipeline-viewer-controller-deployment-8554dc7b9f-qjgt9      1/1     Running            0          25h
mysql-598bc897dc-fsc6t                                         1/1     Running            0          25h
notebook-controller-deployment-7db57b9ccf-f85hk                1/1     Running            0          25h
profiles-deployment-7b89df86c8-87cmb                           2/2     Running            0          25h
pytorch-operator-5fd5f94bdd-qcwtx                              1/1     Running            1          25h
seldon-controller-manager-679fc777cd-j4fh5                     1/1     Running            2          25h
spark-operatorcrd-cleanup-2rh6n                                0/2     Completed          0          25h
spark-operatorsparkoperator-c7b64b87f-tnbhq                    1/1     Running            0          25h
spartakus-volunteer-6b767c8d6-m2x24                            1/1     Running            0          25h
tensorboard-6544748d94-q9c6d                                   1/1     Running            0          25h
tf-job-operator-7d7c8fb8bb-d5dhb                               1/1     Running            1          25h
workflow-controller-945c84565-8drwm                            1/1     Running            0          25h

Set up a K8S cluster on Azure using 3 VMs and created local volumes

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):kfctl v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`): 1 console node and 2 worker nodes on Azure
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by yanniszark** [comment]
@lalithvaka the first step of the OIDC flow is the Provider discovery.
The oidc-authservice hits <provider-url>/.well-known/openid-configuration and gets the OIDC Provider's settings.
This step seems to result in a 404.
Can you check if the <provider-url>/.well-known/openid-configuration is correct?
It should look something like this https://accounts.google.com/.well-known/openid-configuration

**Comment by lalithvaka** [comment]
hi @yanniszark Just that I understand, are you saying that our Enterprise OIDC IDP (Ping) should have exposed  https://enterprise OIDC provider URL>.well-known/openid-configuration and it should look like https://accounts.google.com/.well-known/openid-configuration ??

**Comment by lalithvaka** [comment]
Hi @yanniszark , @krishnadurai  can you please comment on the above configuration if am updating the OIDC parameters in the right file? kustomize/oidc-authservice/base/params.env ? Appreciate your help.

**Comment by krishnadurai** [comment]
@lalithvaka It would be better to set parameters in the kfdef:
https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.yaml#L82-L95

Any parameter you set here overrides the parameter set in `kustomize/oidc-authservice/base/params.env`

**Comment by krishnadurai** [comment]
> hi @yanniszark looks like this would be an issue to start with as am not able to access this outside our enterprise network and my cluster is on Azure VMs. Is there any workaround to this? 

It must be possible for you to start a shell in the authservice pod (or create one pod in authservice's namespace - istio-system) to check if there's an appropriate response from a curl command.

**Comment by yanniszark** [comment]
@lalithvaka the parameters end up as environment variables on the oidc-authservice statefulset, in the istio-system namespace.
You can try editing those for quicker iterations.

**Comment by lalithvaka** [comment]
> > hi @yanniszark looks like this would be an issue to start with as am not able to access this outside our enterprise network and my cluster is on Azure VMs. Is there any workaround to this?
> 
> It must be possible for you to start a shell in the authservice pod (or create one pod in authservice's namespace - istio-system) to check if there's an appropriate response from a curl command.

Hi @krishnadurai My pod is not starting with constant msgs in the logs as following. Am not sure if there is an alternate to this unless I tear the entire cluster and redeploy. As you know kfctl delete won't work as I have deployed istio as well for me to redeploy kubeflow alone.

My authservice-0 log showing as follows
➜ kubectl logs authservice-0 -n istio-system
time="2020-03-09T22:08:39Z" level=info msg="Starting readiness probe at 8081"
time="2020-03-09T22:08:39Z" level=info msg="No USERID_TOKEN_HEADER specified, using 'kubeflow-userid-token' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SERVER_HOSTNAME specified, using '' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SERVER_PORT specified, using '8080' as default."
time="2020-03-09T22:08:39Z" level=info msg="No SESSION_MAX_AGE specified, using '86400' as default."
time="2020-03-09T22:08:39Z" level=info msg="Starting web server at :8080"
time="2020-03-09T22:08:40Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: 404 Not Found: \n\n<title>404 Not Found</title>\n\nNot Found\n
The requested URL /.well-known/openid-configuration was not found on this server.
\n\n"

**Comment by krishnadurai** [comment]
Could you possibly deploy another sleep pod to the istio-system namespace?

You could curl from this pod to get the well-known configuration url's
output.

**Comment by lalithvaka** [comment]
> @lalithvaka the parameters end up as environment variables on the oidc-authservice statefulset, in the istio-system namespace.
> You can try editing those for quicker iterations.

Hi @yanniszark I was able to change the configuration and redeploy oidc-authservice kustomizeconfig with out deleting the whole cluster / kubeflow install. But now I am running into "Error opening bolt store: open /var/lib/authservice/data.db: permission denied" error. And the authservice statefulset goes into crashloopback error. Am not sure if need to create a local Persistent Volume?

➜ kubectl logs authservice-0 -n istio-system                                     
time="2020-03-17T22:55:03Z" level=info msg="Starting readiness probe at 8081"
time="2020-03-17T22:55:03Z" level=info msg="No  USERID_TOKEN_HEADER  specified, using 'kubeflow-userid-token' as default."
time="2020-03-17T22:55:03Z" level=info msg="No  SERVER_HOSTNAME  specified, using '' as default."
time="2020-03-17T22:55:03Z" level=info msg="No  SERVER_PORT  specified, using '8080' as default."
time="2020-03-17T22:55:03Z" level=info msg="No  SESSION_MAX_AGE  specified, using '86400' as default."
time="2020-03-17T22:55:03Z" level=info msg="Starting web server at :8080"
time="2020-03-17T22:55:04Z" level=fatal msg="Error opening bolt store: open /var/lib/authservice/data.db: permission denied"

➜ kubectl get pods -n istio-system
NAME                                                         READY   STATUS             RESTARTS   AGE
authservice-0                                                0/1     CrashLoopBackOff   5          4m20s
cluster-local-gateway-9d544d7db-n55ln                        1/1     Running            0          8d
istio-citadel-75f76d94f-j5thr                                1/1     Running            0          8d
istio-galley-c9f4fb7bf-fp76b                                 1/1     Running            0          8d
istio-ingressgateway-68875ff4cd-pzf7h                        1/1     Running            0          8d
istio-nodeagent-bbxrd                                        1/1     Running            0          8d
istio-nodeagent-zbdsq                                        1/1     Running            0          8d
istio-pilot-99597b4f6-kcrrq                                  2/2     Running            0          8d
istio-policy-757f4d7856-48khj                                2/2     Running            0          8d
istio-security-post-install-release-1.3-latest-daily-5hdgg   0/1     Completed          0          8d
istio-sidecar-injector-5f5484c5f5-lvwjh                      1/1     Running            1          8d
istio-telemetry-598cdc58bf-2p722                             2/2     Running            0          8d
prometheus-7dbbf976d8-52lkb                                  1/1     Running            0          8d
(base)

**Comment by lalithvaka** [comment]
Thank you @yanniszark for helping resolve this issue. "work around this by chowning the pv's underlying folder to the correct group (see fsgroup value on authservice pod) or to something like 755". Also be able to update the scope in the stateful set yaml to exclude groups. Though we might need groups to do the AuthZ eventually.

**Comment by igmik** [comment]
faced the same problem. Workaround with changing owner of the pv folder helped.
