### ISSUE TITLE
Jupyter Notebook dataVolumes will only provision a PVC with gp2 storageClass on AWS

### ISSUE THREAD

**Issue by mmochan** [kubeflow/kubeflow#4848]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running on AWS EKS cluster, successfully installed kubeflow kfctl_aws.0.7.1.yaml.

Attempting to create a kubeflow Jupyter Notebook using a new dataVolume provisioned with AWS FSX Lustre filesystem

<img width="928" alt="Screen Shot 2020-03-11 at 10 47 46 AM" src="https://user-images.githubusercontent.com/80488/76371389-d8f5a980-6385-11ea-9666-59cdaf4d5b55.png">

I am using the AWS FSX Lustre filesystem ( appropriate drivers installed ) for provisioning Notebook FSX dataVolumes. FSX dynamic creation has been tested and working outside of Kubeflow.

Updated the default configMap for the dataVolumes in jupyter-web-app/base/config-map.yaml  to use my FSX Lustre storage class

**config-map.yaml**
`      dataVolumes:
        value:
          - value:
              type:
                value: fsx
              name:
                value: 'fsx-lustre'
              size:
                value: '1200Gi'
              mountPath:
                value: /home/jovyan/fsx-vol-1
              accessModes:
                value: ReadWriteMany
              class:
                value: fsx-sc
        readOnly: false`

**Storage Class**
`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: subnet-xxxxxxxx
  securityGroupIds: sg-xxxxxxxx
  s3ImportPath: s3://kubeflow-bucket
  s3ExportPath: s3://kubeflow-bucket/export
  deploymentType: PERSISTENT_1
  perUnitStorageThroughput: "200"
mountOptions:
  - flock`

**What did you expect to happen:**
I expected a PVC to be created using the fsx-sc storage class and not gp2
`NAME       STATUS    VOLUME  CAPACITY   ACCESS MODES   STORAGECLASS   AGE
fsx-lustre   Pending                                                                        gp2                          11m

Failed to provision volume with StorageClass "gp2": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: build version 0.7.0 ( kfctl_aws.0.7.1.yaml ):
- kfctl version: v0.7.2-rc.0-0-g4df0157 & 1.0.0
- Kubernetes platform: AWS EKS
- Kubernetes version: v1.14.9-eks-502bfb:
- OS: Amazon Linux 2:

**Comment by mmochan** [comment]
👍

**Comment by Jeffwan** [comment]
@PatrickXYS Static provisioning can be used there for sure. Check PR
https://github.com/kubeflow/manifests/pull/1081
https://github.com/kubeflow/website/pull/1864

Can you help check dynamic provision case? I think the problem is config doesn't apply to controller and it uses wrong storage class to create the PVC.

**Comment by strawberrypie** [comment]
It would be great to select which storage class to use for provisioning a volume.
