### ISSUE TITLE
Access external data from Notebook Server

### ISSUE THREAD

**Issue by vaskokj** [kubeflow/kubeflow#4851]
/kind question

**Question:**
How would I go about accessing external data from within my notebook server? For example, how would I connect to an NFS server? Is this possible without needing to create a new custom docker image?

**Comment by jlewi** [comment]
If your data store is accessible through Kubernetes PVs/PVCs then you would create a PVC (e.g. for an NFS share) and then attach the PVC when you start the notebook.

If its accessible through an API (e.g HDFS/S3/GCS) then you would attach appropriate credentials to your notebook and then use the appropriate client library to talk to that data store.
