### ISSUE TITLE
Code 500 with message: couldn't copy application kfserving-gateway

### ISSUE THREAD

**Issue by NicholaiStaalung** [kubeflow/kubeflow#4856]
/kind bug

**What steps did you take and what happened:**
Tried to deploy kubeflow on GCP following the official guide. Also using Cloud IAP (Oauth).

After entering `kfctl apply -V -f ${CONFIG_URI}` the following error occured

> failed to build kfApp from URI https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway

**What did you expect to happen:**
Deploy kubeflow on GCP

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The full log from the command:

> INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.0-

> branch/kfdef/kfctl_gcp_iap.v1.0.1.yaml to /tmp/262064859/tmp.yaml  filename="utils/k8utils.go:172"
> INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.1.yaml to /tmp/133881470/tmp_app.yaml  filename="loaders/loaders.go:71"
> INFO[0000] App directory /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience already exists  filename="coordinator/coordinator.go:270"
> INFO[0000] Writing KfDef to kfctl_gcp_iap.v1.0.1.yaml    filename="coordinator/coordinator.go:273"
> INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to datascience based on location of config file: /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/kfctl_gcp_iap.v1.0.1.yaml.  filename="coordinator/coordinator.go:202"
> INFO[0000] Creating default token source                 filename="gcp/gcp.go:184"
> INFO[0000] Creating GCP client.                          filename="gcp/gcp.go:196"
> INFO[0000] 
> ****************************************************************
> Notice anonymous usage reporting enabled using spartakus
> To disable it
> If you have already deployed it run the following commands:
>   cd $(pwd)
>   kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
> 
> For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
> ****************************************************************
>   filename="coordinator/coordinator.go:120"
> INFO[0000] Creating directory /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/.cache  filename="kfconfig/types.go:445"
> INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz to /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests  filename="kfconfig/types.go:493"
> INFO[0003] updating localPath to /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests/manifests-1.0.1  filename="kfconfig/types.go:540"
> INFO[0003] Fetch succeeded; LocalPath /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests/manifests-1.0.1  filename="kfconfig/types.go:561"
> INFO[0003] /home/nrs/../build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
> WARN[0003] Backfilling auth; this is deprecated; Auth should be explicitly set in Gcp plugin  filename="gcp/gcp.go:1949"
> INFO[0004] Setting Email to default: nrs@...com  filename="gcp/gcp.go:2023"
> INFO[0004] Setting Project to default: datascienceplatform-266011  filename="gcp/gcp.go:2036"
> INFO[0004] Setting Zone to default: europe-west3-b       filename="gcp/gcp.go:2049"
> INFO[0004] Configuring pipelines persistent storage      filename="gcp/gcp.go:1378"
> INFO[0004] Configuring pipeline, minio, and mysql applications  filename="gcp/gcp.go:2173"
> INFO[0004] Processing application: istio-crds            filename="kustomize/kustomize.go:408"
> INFO[0004] Processing application: istio-install         filename="kustomize/kustomize.go:408"
> INFO[0004] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
> INFO[0004] Processing application: kfserving-gateway     filename="kustomize/kustomize.go:408"
> Error: failed to build kfApp from URI https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway
> Usage:
>   kfctl apply -f ${CONFIG} [flags]
> 
> Flags:
>   -f, --file string   Static config file to use. Can be either a local path:
>                                 export CONFIG=./kfctl_gcp_iap.yaml
>                         or a URL:
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
>                                 export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
>                         kfctl apply -V --file=${CONFIG}
>   -h, --help          help for apply
>   -V, --verbose       verbose output default is false

EDIT. I tried deploying the istio version to an existing cluster. Same error. The cluster has kubernetes version 1.14

EDIT: Tried deploying from the shell on GCP. Same error

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.0
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: (e.g. `minikube`) GCP (GKE)
- Kubernetes version: (use `kubectl version`): 17
- OS (e.g. from `/etc/os-release`): Ubuntu 19.10

**Comment by hwk42** [comment]
the same problem appear to macOS 10.15, when deploying with config kfctl_k8s_istio.v1.0.1.yaml. But in 10.14, all is ok.

**Comment by unix-way** [comment]
A corresponding issue should probably be created in the kubeflow/manifests repository.
The reason is that the kfserving-gateway manifest is in the master branch of that repository, but not in v1.0-branch, and (hence) not in the manifests archive, to which the definition file refers. A quick solution is to replace `https://github.com/kubeflow/manifests/archive/v1.0-branch.tar.gz` with `https://github.com/kubeflow/manifests/archive/master.tar.gz` in https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.v1.0.1.yaml#L425 when the file is downloaded, and then run `kfctl build -f` against the modified file.

**Comment by unix-way** [comment]
The issue is already there: https://github.com/kubeflow/manifests/issues/991
And you can use https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml

**Comment by sshakeri** [comment]
I too got this error for V1.0.1, switching to V1.0.0 got me passed the kfserving-gateway issue.

It ultimately failed during update with this error

`Deployment.apps "webhook" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"webhook", "app.kubernetes.io/component":"knative-serving-install", "app.kubernetes.io/instance":"knative-serving-install-v0.11.1", "app.kubernetes.io/managed-by":"kfctl", "app.kubernetes.io/name":"knative-serving-install", "app.kubernetes.io/part-of":"kubeflow", "app.kubernetes.io/version":"v0.11.1", "kustomize.component":"knative", "role":"webhook"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]`

**Comment by krishnadurai** [comment]
We are yet to release the fix for this issue on v1.0 release. Please install with: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml as mentioned in the earlier comment.

> The issue is already there: [kubeflow/manifests#991](https://github.com/kubeflow/manifests/issues/991)
> And you can use https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml

**Comment by sshakeri** [comment]
I am not on gcp, is it supposed to work for no gcp deployments?

```(kubeflow.error): Code 500 with message: coordinator Init failed for gcp: Gcp.gcpInitProject Could not initatie a GCP client: initGcpClient failed to create default token source: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.```

**Comment by NicholaiStaalung** [comment]
> We are yet to release the fix for this issue on v1.0 release. Please install with: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml as mentioned in the earlier comment.
> 
> > The issue is already there: [kubeflow/manifests#991](https://github.com/kubeflow/manifests/issues/991)
> > And you can use https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml

Tried it and it got past the error. But i got a new one which ill post in the other issue.

**Comment by NicholaiStaalung** [comment]
And thanks btw!
