### ISSUE TITLE
AMD not in GPU vendor list?

### ISSUE THREAD

**Issue by jammingyu9** [kubeflow/kubeflow#4858]
/kind question
/kind feature
/area jupyter

Hello,

It seems that previous "External Resources" entry has changed to "GPU Vendor" in Jupyter Notebook 
 server since v1.0. (when creating a notebook)
However, I see AMD is missing in the vendor list.
May I know when will it be added?

Thank you.

**Comment by jlewi** [comment]
If your cluster supports AMD GPUs then you could customize the jupyter web app config to include AMD.

https://github.com/kubeflow/manifests/blob/5b2ecb760b36cd95fea1071a761b2659225eb0e2/jupyter/jupyter-web-app/base/config-map.yaml#L116

Until AMD GPUs are widely available in Cloud and well supported by ML software like TensorFlow its unlikely we would make AMD part of the default.

**Comment by jammingyu9** [comment]
Okay, thank you for the config.
