### ISSUE TITLE
How to set custom nodeSelector for complete setup

### ISSUE THREAD

**Issue by tech348712013870132** [kubeflow/kubeflow#4861]
/kind question

**Question:**

Is it possible to say kfctl that all deployments should be created with a specific and custom nodeSelector on setup?
We are using the latest kfctl_istio_dex.yaml and kfctl version for our kubernetes setup but not yet figured out how to accomplish this (or have we maybe overlooked the possibility?)

We would really love to see an implementation for this feature :)

**Comment by jlewi** [comment]
This is currently not possible. 

Could you explain more why you want to use a custom node selector?

If you wanted to do this you'd probably need to run `kfctl build` and then customize/hack the resulting kustomize manifests in ${KFAPP}/kustomize to attach custom node selectors.

You might want to investigate creating a custom kustomize plugin (e.g. a transformer) to make it easy to automatically add a nodeselector to all pods.

**Comment by tech348712013870132** [comment]
The reason we are searching for this setting is that we have one big cluster with different node pools and want to prevent that the kubeflow microservices are spawning randomly in all pools which can cause node resource overload.

So our abstract goal can be described as limiting all kubeflow deployments to one specific node pool that suits the specific hardware requirements of the kubeflow deployments.

**Comment by saisona** [comment]
@tech348712013870132 I'm currently searching for the same purpose of you ! Fell free to share any informations with me, as I will do the same

**Comment by Archa91** [comment]
Hi guy, I'm not an expert of kustomize, but i have the same concern about adding a nodeSelector to the entire setup.

At this moment, I add a kustomize patch files to all applications (regardless deployment or statefulset).
I created a bash script to automatically add all these files to all applications in a loop, do what you want ^^

Example for app "api-service":
```bash
$ pwd
.../my-eks-cluster/kustomize/api-service
```

Add this to the end of the kustomization.yaml
```
patches:
- path: nodeSelectors-deployment-patch.yaml
  target:
    kind: Deployment
- path: nodeSelectors-statefulset-patch.yaml
  target:
    kind: StatefulSet 
```
```bash
$ cat nodeSelectors-deployment-patch.yaml
apiVersion: v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      nodeSelector:
        Role: kubeflow
        Nodegroup: eks-workers-kubeflow_1
```

```bash
$ cat nodeSelectors-statefulset-patch.yaml
apiVersion: v1
kind: StatefulSet
metadata:
  name: not-important
spec:
  template:
    spec:
      nodeSelector:
        Role: kubeflow
        Nodegroup: eks-workers-kubeflow_1
```

And apply all by doing a `kfctl apply -V -f kfctl.x.x.x.x.yaml`

Like I said, I'm not an expert of kustomize, if you know a better way I'll greatly appreciate.

Regards,
