### ISSUE TITLE
Notebook Images : Change owner to jovyan of /home/jovyan 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4863]
/kind bug

We create the home directory /home/jovyan here
https://github.com/kubeflow/kubeflow/blob/296bf145c33afd65b60f2e0e3e62b781c1330386/components/tensorflow-notebook-image/Dockerfile#L90 

but we don't change the owner and group to be jovyan and users respectively.

When using the docker image with Kubeflow notebooks that doesn't matter because we end up overwriting /home/jovyan with a volume that will have user and group set correctly.

However it can lead to unexpected behavior when people use the image directly; e.g. as the base image with func_to_container_op.

/cc @Tabrizian

**Comment by imskr** [comment]
Can I fix this?

**Comment by jlewi** [comment]
@imskr I believe this is already fixed by #4867 

I believe we still need to build updated docker images and then update the configmap on master to use them.

**Comment by jlewi** [comment]
#4789 is tracking continuous builds.

**Comment by jlewi** [comment]
This might not make it into 1.1 as the continuous builds #4789 is still in the works.
