### ISSUE TITLE
[KFAM] LivenessProbe doesn’t work with istio mutual TLS

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/kubeflow#4865]
/kind feature

**Why you need this feature:**
I'd like to enable istio mutual TLS and add some authorization rules to KFAM to secure profile control.
However, when KFAM is injected with an istio sidecar, it keeps crashing loop because the liveness probe cannot reach KFAM after mTLS is enabled.

Exactly documented by istio in https://istio.io/docs/ops/configuration/mesh/app-health-check/#liveness-and-readiness-probes-with-http-request-option.

**Describe the solution you'd like:**
There are two options
* enable the probe rewrite admission hook (requires istio 1.2.0 or later, we are at 1.1.6 in kubeflow)
* separate probe endpoint port with usual workload port, so we can just let istio intercept the workload port and not the probe port.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Bobgy** [comment]
@kunmingg Is there any ETA for istio 1.4.5 upgrade?
Will it be possible within 2 weeks? I want to know if I can wait for it, if not I can try to contribute the separate port fix.

/assign @Bobgy

**Comment by kunmingg** [comment]
Do you have an open issue for enabling istio mutual TLS and add some authorization rules to KFAM?
Can you add details in the issue?

**Comment by Bobgy** [comment]
Thanks! I will create such an issue

**Comment by Bobgy** [comment]
This can depend on https://github.com/kubeflow/manifests/issues/1024 for istio upgrade.

**Comment by Bobgy** [comment]
@kunmingg Created KFAM related issue in https://github.com/kubeflow/kubeflow/issues/4871.

**Comment by yanniszark** [comment]
@Bobgy you may find this section useful: https://istio.io/faq/security/#k8s-health-checks

**Comment by Bobgy** [comment]
@yanniszark Thanks!
> Using a liveness command for health checks, e.g., one can install curl in the service pod and curl itself within the pod.
This seems also a good alternative.

**Comment by Bobgy** [comment]
/remove-lifecycle/stale

**Comment by Bobgy** [comment]
A new comment removes stale

**Comment by Bobgy** [comment]
Hmmm, noticed profile controller is using a distroless image, so it has neither curl nor wget in the image.

https://github.com/kubeflow/kubeflow/blob/master/components/access-management/Dockerfile

**Comment by Bobgy** [comment]
@jlewi Do you have any suggestions? This is still a blocker.
Shall we disable profile controller's liveness and readiness hooks for now and wait for all platforms to upgrade to istio 1.4+, so that we can use the probe rewrite solution which seems least intrusive.

> enable the probe rewrite admission hook (requires istio 1.2.0 or later, we are at 1.1.6 in kubeflow)

**Comment by jlewi** [comment]
@Bobgy Why do we need to enable mutual TLS and authorization rules for KFam? I believe as discussed elsewhere (e.g. https://github.com/kubeflow/community/blob/master/guidelines/auth.md); using subject access review and not calling KFam is the preferred approach for doing auth.

Can KFP just use KFam as is today without mutual TLS until it can be switched to subject access review?

**Comment by Bobgy** [comment]
> @Bobgy Why do we need to enable mutual TLS and authorization rules for KFam? I believe as discussed elsewhere (e.g. https://github.com/kubeflow/community/blob/master/guidelines/auth.md); using subject access review and not calling KFam is the preferred approach for doing auth.
> 
> Can KFP just use KFam as is today without mutual TLS until it can be switched to subject access review?

Yes, just using KFAM is also a workaround. Not protecting kfam by istio is a security risk because it exposes several apis that allow adding users as contributors to a namespace. Although, it's not related to KFP.

I'm okay with this solution because it also exists today, but I'll call that out when writing documentation for KFP multi user mode.
