### ISSUE TITLE
Upgrading 1.0.0 to 1.0.1 fails with "couldn't copy application kfserving-gateway"

### ISSUE THREAD

**Issue by yantriks-edi-bice** [kubeflow/kubeflow#4868]
/kind bug

**What steps did you take and what happened:**

YNTKLLC-EDI:kubeflows edibice$ kfctl apply -f /Users/edibice/kubeflows/kfctl_upgrade_gcp_iap_1.0.1.yaml -V
INFO[0000] Downloading /Users/edibice/kubeflows/kfctl_upgrade_gcp_iap_1.0.1.yaml to /var/folders/3z/w4wzm1796659_8v7xc7z75gm0000gn/T/119420020/update.yaml  filename="v1alpha1/application_types.go:129"
INFO[0011] Found KfCfg with matching name: kf-tst version: v1.0.0 at kf-tst/kfctl_gcp_iap.v1.0.0.yaml  filename="kfupgrade/kfupgrade.go:195"
INFO[0014] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.1.yaml to /var/folders/3z/w4wzm1796659_8v7xc7z75gm0000gn/T/615302467/tmp_app.yaml  filename="loaders/loaders.go:71"
INFO[0015] Merging plugin spec: KfGcpPlugin              filename="kfupgrade/kfupgrade.go:235"
INFO[0015] Merging application spartakus param usageId from 7439583937720421527 to 3229636564305222583  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application minio param minioPd from test1-storage-artifact-store to kf-tst-storage-artifact-store  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application mysql param mysqlPd from test1-storage-metadata-store to kf-tst-storage-metadata-store  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application profiles param admin from  to edi.bice@yantriks.com  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application iap-ingress param ipName from test1-ip to kf-tst-ip  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application iap-ingress param hostname from  to kf-tst.endpoints.saas-ml-dev.cloud.goog  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application default-install param user from  to edi.bice@yantriks.com  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Merging application default-install param profile-name from anonymous to kubeflow-edi-bice  filename="kfupgrade/kfupgrade.go:246"
INFO[0015] Creating directory /Users/edibice/kubeflows/fitkvsk  filename="kfupgrade/kfupgrade.go:91"
INFO[0015] Creating default token source                 filename="gcp/gcp.go:184"
INFO[0015] Creating GCP client.                          filename="gcp/gcp.go:196"
INFO[0015] 
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0015] Creating directory /Users/edibice/kubeflows/fitkvsk/.cache  filename="kfconfig/types.go:445"
INFO[0015] Fetching https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz to /Users/edibice/kubeflows/fitkvsk/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0016] updating localPath to /Users/edibice/kubeflows/fitkvsk/.cache/manifests/manifests-1.0.1  filename="kfconfig/types.go:540"
INFO[0016] Fetch succeeded; LocalPath /Users/edibice/kubeflows/fitkvsk/.cache/manifests/manifests-1.0.1  filename="kfconfig/types.go:561"
INFO[0016] /Users/edibice/kubeflows/fitkvsk/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
INFO[0016] Configuring pipelines persistent storage      filename="gcp/gcp.go:1378"
INFO[0016] Configuring pipeline, minio, and mysql applications  filename="gcp/gcp.go:2173"
INFO[0016] Processing application: istio-crds            filename="kustomize/kustomize.go:408"
INFO[0016] Processing application: istio-install         filename="kustomize/kustomize.go:408"
INFO[0017] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
INFO[0017] Processing application: kfserving-gateway     filename="kustomize/kustomize.go:408"
ERRO[0017] Failed to build KfApp from URI: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway  filename="kfupgrade/kfupgrade.go:272"
Error: couldn't apply KfUpgrade: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

couldn't apply KfUpgrade: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`): 1.14.10-gke.22
- OS (e.g. from `/etc/os-release`):

**Comment by jtfogarty** [comment]
This is related to [manifests/issues/1029](https://github.com/kubeflow/manifests/issues/1029)

**Comment by yantriks-edi-bice** [comment]
Yes, I was able to proceed after using the fixed manifest from master
