### ISSUE TITLE
Secure KFAM with mutual TLS and istio authorization rules

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/kubeflow#4871]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Unblocks KFP multi user support https://github.com/kubeflow/pipelines/issues/3241
Kubeflow pipelines is working on a secure multi user deployment in Kubeflow.

One of the security concern is that some endpoints in KFAM allows user to create namespace or add contributor to a namespace. (Please correct me if this is not accurate.)

Therefore, I'd like KFAM service secured by istio mutual TLS and authorization rules to only allow trusted services access it.

Services that can access KFAM:
* central dashboard
* kubeflow pipelines api server (To be added when enabling KFP multi user mode)

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
1. Fix https://github.com/kubeflow/manifests/issues/976 first. (I've sent a PR https://github.com/kubeflow/manifests/pull/1042)
1. Turn on mTLS for KFAM using a destination rule: https://archive.istio.io/v1.1/docs/tasks/security/mtls-migration/#configure-clients-to-send-mutual-tls-traffic. (This is required, because using service account as `source.principal` in `ServiceRoleBinding` is only supported in mutual TLS.)
1. Add authorization rules to allow requests from centraldashboard using https://archive.istio.io/v1.1/docs/reference/config/authorization/constraints-and-properties/#supported-properties `source.principal`, the principal should be corresponding service account.
1. Let centraldashboard and kfp api server inject sidecar too, because clients need sidecar to use mTLS enabled services.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The solution is currently blocked by https://github.com/kubeflow/kubeflow/issues/4865

**Comment by yanniszark** [comment]
@Bobgy keep in mind that in order to use `source.principal`, the requesting service has to have an Istio sidecar injected as well, in order to use mutual TLS.
So I believe your solution needs an additional step, which is to inject istio sidecar for Central Dashboard and KFP API Server.

**Comment by Bobgy** [comment]
> @Bobgy keep in mind that in order to use `source.principal`, the requesting service has to have an Istio sidecar injected as well, in order to use mutual TLS.
> So I believe your solution needs an additional step, which is to inject istio sidecar for Central Dashboard and KFP API Server.

Exactly! I forgot to mention that.
FYI, I've got full set of manifests working with KF 1.0 in https://github.com/Bobgy/manifests/pull/3/files. I'm gradually trying to merge my changes there to KF manifest repo.

**Comment by Bobgy** [comment]
@yanniszark @kunmingg Would you mind taking a look at kubeflow/manifests#1021 first? It's also a dependency of this issue.

**Comment by Bobgy** [comment]
Update, changed PR to https://github.com/kubeflow/manifests/pull/1042

**Comment by Bobgy** [comment]
/lifecycle frozen
This needs to be addressed as part of KF 1.1 for enabling kfp multi user mode

**Comment by DavidSpek** [comment]
@thesuperzapper This now falls in the scop of wg-notebooks so it should be added to the kanban.

**Comment by Bobgy** [comment]
I think we can close it, because we have decided to deprecate kfam
