### ISSUE TITLE
Configuration webapi endpoint in Kubeflow - GCP 

### ISSUE THREAD

**Issue by matheusjericoo** [kubeflow/kubeflow#4872]
**/kind question**

Hello, I'm having trouble setting up API access for the webapi container (api Flask to make predictions) in the kubeflow pipeline.
I created a pipeline with three containers (pre-processing, training and API). I deployed containers in Container Registry. The pipeline was created and is working, but i dont know how to access the API.
- The pre-processing container reads data on Google Storage, transforms it and saves the new dataset on PVC;
- The training container reads the PVC dataset, trains a machine learning model and saves the model on PVC;
- The API container is an API that provides an "/predict" endpoint for making predictions based on the model loaded on the PVC.

How to configure the API container to have an endpoint (url) available to send a POST via postman to do the pipeline test? Because in pipeline.py i didn't configure this and i didn't know where configure this.On kubernetes, I would configure service.yaml / deployment.yaml / ingress.yaml for the API image in the container registry, but in kubeflow i'm confused. Can I configure this in pipeline.py? I'm deploying the pipeline in Kubeflow UI, I'm push the pipeline in "Pipeline" and creating "Experiments"

Pipeline.py Code 
```python
import kfp.dsl as dsl
from kubernetes import client as k8s_client


@dsl.pipeline(
    name='Workflow ML',
    description=''
)
def ms_af(
    persistent_volume_name='gcp',
    persistent_volume_path='/mnt/gcp',
    imagetag='latest',
    model_name='af',
    profile_name='af'
):

    operations = {}
    bucket_gs = 'BUCKET-951'
    base_path = 'DatasetAf'
    data_file = 'dataset.csv'
    dataset_af = 'dataset_af.csv'
    params_mlp = {'solver':'adam', 'learning_rate':'adaptive', 'hidden_layer_sizes':5}
    params_rf = {'criterion': 'entropy', 'max_depth': 7, 'max_features': 0.5, 'n_estimators': 50, 'random_state': 0}
    model_folder = 'model'
    path_model = "/mnt/gcp/model" # persistent_volume_path+"/"+model_folder
    # preprocess data
    operations['preprocess'] = dsl.ContainerOp(
        name='preprocess',
        image='gcr.io/PROJECT_ID/preprocess:0.1',
        command=['python'],
        arguments=[
            '/scripts/data.py',
            '--bucket_gs', bucket_gs,
            '--base_path', base_path,
            '--data_file', data_file,
            '--target', persistent_volume_path,
            '--target_file', dataset_af
        ]
    )

    #train
    operations['training'] = dsl.ContainerOp(
        name='training',
        image='gcr.io/PROJECT_ID/training:0.1',
        command=['python'],
        arguments=[
            '/scripts/train.py',
            '--base_path', persistent_volume_path,
            '--params_mlp', params_mlp,
            '--params_rf', params_rf,
            '--dataset', dataset_af,  
            '--outputs', model_folder, 
        ]
    )
    operations['training'].after(operations['preprocess'])

    # register model
    operations['api'] = dsl.ContainerOp(
        name='api',
        image='gcr.io/PROJECT_ID/api:0.3',
        command=['python'],
        arguments=[
            '/srv/www/application/app.py',
            '--path_model', path_model,
        ]
    )
    operations['api'].after(operations['training'])


    for _, op in operations.items():
        op.container.set_image_pull_policy("Always")
        op.add_volume(
            k8s_client.V1Volume(
                name='gcp',
                persistent_volume_claim=k8s_client.V1PersistentVolumeClaimVolumeSource(
                    claim_name='gcp-managed-disk')
                )
            ).add_volume_mount(k8s_client.V1VolumeMount(
                mount_path='/mnt/gcp', 
                name='gcp')
            )


if __name__ == '__main__':
   import kfp.compiler as compiler
   compiler.Compiler().compile(ms_antifraude, __file__ + '.tar.gz')

```

**Comment by jlewi** [comment]
@matheusjericoo I think if you are trying to deploy an API endpoint what you want to do is have the final step create the K8s resources need to deploy the server. 

So for example, if you would normally deploy the server by creating a Deployment and Ingress then just create those resources in the final step of the pipeline. You can do this by using the K8s python client library and writing some python code to create those objections.

/cc @jessiezcc

**Comment by matheusjerico** [comment]
Thanks for answer @jlewei. I did exactly this. But i didn't create in python code. I created yaml file with ingress, service, deployment to endpoint.

**Comment by jbottum** [comment]
@matheusjerico Hi matheusperico, is this issue still open ?  can it be closed ?
