### ISSUE TITLE
Create a sample for notebook to Kubeflow deployment using Tensorflow 2.0 Keras

### ISSUE THREAD

**Issue by siddharthjain1611** [kubeflow/kubeflow#4874]
A sample notebook to Kubeflow deployment using Tensorflow 2.0 Keras

It is needed to Launch training/hyperparameter tuning jobs on the cluster and Deploy the model using KFServing
 This issue is raised with respect to the GSoC 2020 project ideas, I Siddharth Jain would love to work on this project in my summer in GSoC 2020. Therefore, I request the community to please guide and help me through the process.

**Comment by maxkaustav** [comment]
TFX is a good option to use kubeflow and deploy as it provides easy training and easy deploying

**Comment by siddharthjain1611** [comment]
> TFX is a good option to use kubeflow and deploy as it provides easy training and easy deploying

KFServing enables serverless inferencing on Kubernetes and provides performant, high abstraction interfaces for common machine learning (ML) frameworks like TensorFlow, XGBoost, scikit-learn, PyTorch, and ONNX to solve production model serving use cases.

**Comment by jbottum** [comment]
@siddharthjain1611 Hi Siddharth, how is this development coming?  Should we expect it in KF 1.1 (late June)?  Please let us know.

**Comment by siddharthjain1611** [comment]
@jbottum A gsoc project is already going on this topic therefore I think we can close this issue.
