### ISSUE TITLE
application-controller produces logs in stderr

### ISSUE THREAD

**Issue by Kulikovpavel** [kubeflow/kubeflow#4875]
/kind bug

**What steps did you take and what happened:**
Deploy kubeflow 1.0 on GCP
After deploy, application-controller starts to print logs in stderr, that leads to ERRORs in stackdriver

**What did you expect to happen:**
All logs will be in stackdriver as stdout

**Environment:**

- Kubeflow version: 1.0
- kfctl version: 
- Kubernetes platform: GCP
- Kubernetes version: 
- OS (e.g. from `/etc/os-release`):

**Comment by vladislavkoz** [comment]
We've faced the same issue. Around 2M logs per hour created by the application-controller-stateful-set.

**Comment by ValentinVerkhohliad** [comment]
I faced the same issue. Around 1.5M logs per hour created by the application-controller-stateful-set.

**Comment by vladislavkoz** [comment]
![image](https://user-images.githubusercontent.com/40685761/92127688-3d139a80-ee0a-11ea-9ac1-2925bf738773.png)

**Comment by jonasdebeukelaer** [comment]
Same here, any ideas why it's spamming so much? Something about error listing certain resources...
And are other just dealing with this filtering these out through GCP logging or other?

```
2021/01/08 10:24:06 Matching labels:  map[app.kubernetes.io/name:kubeflow-pipelines]
2021/01/08 10:24:06 Requested ServiceAccount.v1, Registered: /v1, Kind=ServiceAccountList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested Service.v1, Registered: /v1, Kind=ServiceList
2021/01/08 10:24:06 Requested PersistentVolumeClaim.v1, Registered: /v1, Kind=PersistentVolumeClaimList
2021/01/08 10:24:06 Requested ConfigMap.v1, Registered: /v1, Kind=ConfigMapList
2021/01/08 10:24:06 Requested Secret.v1, Registered: /v1, Kind=SecretList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1, Kind=DeploymentList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta2, Kind=DeploymentList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta1, Kind=DeploymentList
2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io Role}, no matches for kind "Role" in version "rbac.authorization.k8s.io/v1alpha1"
2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io RoleBinding}, no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1alpha1"
2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta2"
2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta1"
2021/01/08 10:24:06 Matching labels:  map[app.kubernetes.io/name:kubeflow-pipelines]
2021/01/08 10:24:06 Requested ServiceAccount.v1, Registered: /v1, Kind=ServiceAccountList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleList
2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleBindingList
2021/01/08 10:24:06 Requested Service.v1, Registered: /v1, Kind=ServiceList
2021/01/08 10:24:06 Requested PersistentVolumeClaim.v1, Registered: /v1, Kind=PersistentVolumeClaimList
2021/01/08 10:24:06 Requested ConfigMap.v1, Registered: /v1, Kind=ConfigMapList
2021/01/08 10:24:06 Requested Secret.v1, Registered: /v1, Kind=SecretList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta2, Kind=DeploymentList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta1, Kind=DeploymentList
2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1, Kind=DeploymentList
2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io Role}, no matches for kind "Role" in version "rbac.authorization.k8s.io/v1alpha1"
2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io RoleBinding}, no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1alpha1"
2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta2"
2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta1"
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)  Expected Resources:
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-visualizationserver
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-scheduledworkflow
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/pipeline-runner
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-container-builder
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-cache-deployer-sa
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-ui
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-persistenceagent
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-metadata-writer
2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-viewer-crd-service-account
```

**Comment by muthurajr** [comment]
Same here!! Is there any solution or workaround available to overcome the issue?

**Comment by vladislavkoz** [comment]
> Same here, any ideas why it's spamming so much? Something about error listing certain resources...
> And are other just dealing with this filtering these out through GCP logging or other?
> 
> This is after an upgrade to kubeflow 1.2 by the way.
> The spamming started then. I think I'd already applied a filter in the past though, just that it seemed no longer effective after upgrade.
> 
> ```
> 2021/01/08 10:24:06 Matching labels:  map[app.kubernetes.io/name:kubeflow-pipelines]
> 2021/01/08 10:24:06 Requested ServiceAccount.v1, Registered: /v1, Kind=ServiceAccountList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested Service.v1, Registered: /v1, Kind=ServiceList
> 2021/01/08 10:24:06 Requested PersistentVolumeClaim.v1, Registered: /v1, Kind=PersistentVolumeClaimList
> 2021/01/08 10:24:06 Requested ConfigMap.v1, Registered: /v1, Kind=ConfigMapList
> 2021/01/08 10:24:06 Requested Secret.v1, Registered: /v1, Kind=SecretList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1, Kind=DeploymentList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta2, Kind=DeploymentList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta1, Kind=DeploymentList
> 2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io Role}, no matches for kind "Role" in version "rbac.authorization.k8s.io/v1alpha1"
> 2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io RoleBinding}, no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1alpha1"
> 2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta2"
> 2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta1"
> 2021/01/08 10:24:06 Matching labels:  map[app.kubernetes.io/name:kubeflow-pipelines]
> 2021/01/08 10:24:06 Requested ServiceAccount.v1, Registered: /v1, Kind=ServiceAccountList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleList
> 2021/01/08 10:24:06 Requested Role.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1alpha1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested RoleBinding.rbac.authorization.k8s.io/v1, Registered: rbac.authorization.k8s.io/v1beta1, Kind=RoleBindingList
> 2021/01/08 10:24:06 Requested Service.v1, Registered: /v1, Kind=ServiceList
> 2021/01/08 10:24:06 Requested PersistentVolumeClaim.v1, Registered: /v1, Kind=PersistentVolumeClaimList
> 2021/01/08 10:24:06 Requested ConfigMap.v1, Registered: /v1, Kind=ConfigMapList
> 2021/01/08 10:24:06 Requested Secret.v1, Registered: /v1, Kind=SecretList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta2, Kind=DeploymentList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1beta1, Kind=DeploymentList
> 2021/01/08 10:24:06 Requested Deployment.apps/v1, Registered: apps/v1, Kind=DeploymentList
> 2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io Role}, no matches for kind "Role" in version "rbac.authorization.k8s.io/v1alpha1"
> 2021/01/08 10:24:06    >>>ERR listing: {rbac.authorization.k8s.io RoleBinding}, no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1alpha1"
> 2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta2"
> 2021/01/08 10:24:06    >>>ERR listing: {apps Deployment}, no matches for kind "Deployment" in version "apps/v1beta1"
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)  Expected Resources:
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-visualizationserver
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-scheduledworkflow
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/pipeline-runner
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-container-builder
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-cache-deployer-sa
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-ui
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-persistenceagent
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/kubeflow-pipelines-metadata-writer
> 2021/01/08 10:24:06 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   exp: kubeflow/*v1.ServiceAccount/ml-pipeline-viewer-crd-service-account
> ```

Yes, I've excluded these(spam) out from GCP logging?

**Comment by jonasdebeukelaer** [comment]
is it possible to reopen this? @Kulikovpavel @Bobgy ?

**Comment by Bobgy** [comment]
There's a similar issue on kubeflow/gcp-blueprints,
I gave a workaround to change the statefulset to omit all logs (redirecting them to /dev/null)
https://github.com/kubeflow/gcp-blueprints/issues/184#issuecomment-760574562

I think you can refer to that issue instead.

Duplicate of https://github.com/kubeflow/gcp-blueprints/issues/184

**Comment by Bobgy** [comment]
@jonasdebeukelaer

**Comment by jonasdebeukelaer** [comment]
ah ok thanks!
