### ISSUE TITLE
Do not allow a Notebook Server to be created if Existing Workspace or Data Volumes is selected and the Volume does not exist.

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4883]
/kind feature

**Why you need this feature:**
This will prevent the user from attempting to create a Notebook server that will not start

**Describe the solution you'd like:**
When the user select Existing for Workspace or Data Volumes, do not allow the user to type the volume name, Only allow them to select a name

**Anything else you would like to add:**
none

**Comment by lalithvaka** [comment]
I totally agree with this issue. I see our teams doing this mistake and expecting the notebook servers to come up. Existing option should be followed by a drop down only. Or we should. think about redesigning the volume selection process.
cc @avdaredevil
