### ISSUE TITLE
Open ports on kubeflow standard installation on GCP

### ISSUE THREAD

**Issue by JeffersonH44** [kubeflow/kubeflow#4886]
/kind question

**Question:**
Hello all, I just have a question, I've deployed kubeflow on GCP (just following the instructions on the docs) but I'm seeing that has the following firewall rule (on the image), why is necessary all those ports being exposed to the public? is there any way to constrain it?

![image](https://user-images.githubusercontent.com/7885709/77430631-7b138980-6da9-11ea-8e7a-01c1a7ac0292.png)

**Comment by jlewi** [comment]
I think those ports might be created by the ISTIO ingress. I don't think those are actually exposed to the public world. They should be blocked by the GCP firewall rules.
