### ISSUE TITLE
Support more than one owner of a profile CR

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#4888]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
User express interests in owning a namespace/profile by a group people, instead of a single person. 
This makes the system more robust in case that individuals leave the team.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
There are few options to achieve this
- Support group as the owner
- Support multiple individuals as the owners of a namespace

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
Isn't this doable today using RBAC today?

Using profiles to manage ACLs is an explicit non-goal for the profile resource. The expectation is that once the namespace exists people use RBAC to manage access and permissions to namespaces.

The OWNER field in Profile is really just bootstrapping the namespace with an initial role binding.

**Comment by nrchakradhar** [comment]
@IronPan  @jlewi We have a slightly different requirement. Can a user be included in a Profile as contributor without he/she being associated with their own namespace.

**Comment by nrchakradhar** [comment]
Sorry. Just saw #4889

**Comment by jlewi** [comment]
See discussion in: https://groups.google.com/g/kubeflow-discuss/c/whS_j4RlEJo

Closing this as per the discussion I don't think we want to do this.
