### ISSUE TITLE
Support login to Kubeflow cluster without creating his/her namespace for a non-admin contributor

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#4889]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

With the current implementation, users have to go through the self-registration process the first time they login to the UI regardless whether they are already added as a contributor to another namespace. Thus a user must own a namespace even if they don’t end up using it. This assumption is made by other parts of the UI to simplify the flow.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
A contributor can skip creating a namespace. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
@avdaredevil could you provide a pointer to the code where this is disabled?

**Comment by avdaredevil** [comment]
Is this logic required to be amended for just multi-user isolation mode, or single-cluster isolation mode (all users are anon) as well?

**Comment by lalithvaka** [comment]
If I understand right, this is for multi user isolation use case. 
Here is how I would see this working as.
1. An admin creates a profile using YAML
2. Add all users participating in the profile as contributors
3. If any of theses users coming to the platform(Kubeflow) for the first time and is already a contributor to at least one they should not be asked to create a profile.
4. Creating an individual self service profile as an owner should be optional based on an environment flag per each enterprise's requirements . Even if the flag is on, allow the user to skip and get launched to the dashboard. 

This logic is probably in the following files. 
centraldashboard/public/components/main-page.js 
centraldashboard/app/api_workgroup.ts

**Comment by jlewi** [comment]
@lalithvaka Do you want to submit a PR making it configurable via a flag or an environment variable (which ever is more consistent with how it works today)?

**Comment by lalithvaka** [comment]
@jlewi Yes, I can, but my understanding of TypeScript coding and how the central dashboard works is very limited.  @avdaredevil would you be able to help here on how to get the Environment variables from to turn on / off based on a flag?

**Comment by avdaredevil** [comment]
Sure thing @lalithvaka! Central-Dashboard uses environment variables.
- The logic for defaulting and ENV extraction is [***here***](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/server.ts#L25-L31)
- Feel free to add a new config there (and update relevant tests)
- You'll most likely want to add another `app.use()` clause [***here***](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/server.ts#L49) that adds the new `ENV_VAR` to the `req: Request` object
  - Additionally adding this variable in the `/debug` route which is right under that reads it from the req object, and verifies that your backend change is working!
- You can now send this variable to the UI via `/api/workgroup/env-info` route. Code is [***here***](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/api_workgroup.ts#L301)

**Comment by jlewi** [comment]
@lalithvaka Any update on this?

Is this likely to land in 1.1 or should we just remove it from 1.1?

/cc @yanniszark @bmorphism

**Comment by lalithvaka** [comment]
@jlewi I was having a hard time getting this taken care of with no Typescript knowledge even though I was able to hardcode and make it work in our non prod environment and its working as expected with out env variable or config value. Wondering if any one on this thread with Typescript experience wants to collaborate with me to get this moving? a 30mins zoom call could help. Appreciate the help in advance. 
/cc @yanniszark  @bmorphism @avdaredevil

**Comment by TomasPihrt** [comment]
@jlewi could you please share how to completely disable this welcome screen namespace creation? thanks

**Comment by jlewi** [comment]
@TomasPihrt Please take a look at 
https://github.com/kubeflow/kubeflow/issues/4889#issuecomment-634202996
I'm not familiar with the code so don't have any pointers beyond that; sorry.

**Comment by marcjimz** [comment]
@jlewi @lalithvaka we have a solution on this and will provide a PR today. Can we ensure that this makes it in the cut for 1.1? This is a pretty key feature in maintaining a multi-tenant environment, in addition to the KFP multi-tenant work.

**Comment by jlewi** [comment]
@marcjimz The release train waits for no one :). My suggestion would be to get the PR in and we can go from there.

**Comment by lalithvaka** [comment]
@jlewi , I have a PR as well for displaying GPU details on notebook servers table. Am assuming that bot is randomly assigning for review. So it all depends on how quickly the reviewers push it through? Is it ok, if we reach out to the reviewers directly? 
Thank you @marcjimz for submitting the PR. Will look forward to it.

**Comment by jlewi** [comment]
@lalithvaka it is ultimately the PR creator's responsibility to see that the PR gets assigned to appropriate reviewers and ping reviewers as needed. Reviewer assignment is based on heuristics (OWNERs files) with mixed accuracy.

**Comment by avdaredevil** [comment]
@maganaluis @lalithvaka I've reviewed the PR and left my feedback, PTAL. Additionally could you write the way you envision this flow in the PR description? Thanks!

**Comment by maganaluis** [comment]
@avdaredevil Thank you for reviewing, I took care of the changes and I also added more info on how we expect it to use it.

/cc @marcjimz

**Comment by yanniszark** [comment]
This issue has been addressed by PR: https://github.com/kubeflow/kubeflow/pull/5080
The solution introduced there is to add a `REGISTRATION_FLOW= true (default) | false` setting to be able to toggle the registration flow on/off via an environment variable.

**Comment by jlewi** [comment]
@yanniszark @lalithvaka Is the PR included in the 1.1 release? If not should it be?

**Comment by lalithvaka** [comment]
@jlewi yes, would be great to have it in 1.1 release. But this PR #5080 was merged on Jun23rd and I heard from @jbottum that 1.1 release was cut on Jun 19th. Please confirm if we still have time for 1.1. 

There are two additional changes that will complete this enhancement 
1. @maganaluis is submitting a PR request for the Env variable update in the Manifests 
2. I will need to submit the corresponding documentation PR.

**Comment by jlewi** [comment]
@lalithvaka Please check the 1.1 branch and see if your PR is on it. If its not then you can follow
https://github.com/kubeflow/kubeflow/blob/master/hack/cherry-picks.md

To cherry-pick it into the release branch. 

Once its on the release branch you will want to verify that a PR is opened up against the kubeflow/manifests release branch to update the docker image.

**Comment by jlewi** [comment]
@lalithvaka @maganaluis I don't think this made it to Kubeflow 1.1; per kubeflow/manifests#1553 it doesn't look like the image got updated.

**Comment by lalithvaka** [comment]
@jlewi  I see the right images made it to common/centraldashboard/base/kustomization.yaml files but not under /common/centraldashboard/base_v3/kustomization.yaml. If I remember right, we did cherry pick this. Not sure why it did not pick the right image into base_v3? Also, is there a reason why we still have old base/kustomization.yaml files? 
cc/ @maganaluis

**Comment by jlewi** [comment]
It looks like the PR kubeflow/manifests#1465 was never reviewed and approved.

It looks like this is an area where ownership and accountability aren't clear. The application OWNERs should be responsible for ensuring the application is released and the binaries make it to the release.

Per: kubeflow/community#380 it looks like we are missing WG sponsorship for the centraldashboard.

The OWNERs file looks outdated
https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/OWNERS

I believe @avdaredevil and @prodonjs are only working on this best effort. 

So it looks like we either need to find

1. New OWNERs for centraldashboard
1. Begin deprecating and removing centraldashboard

**Comment by jlewi** [comment]
@avdaredevil thanks for confirming; I would suggest not LGTM'ing. To me the root issue is figuring out who the new owner will be and I lean towards letting the new owners take responsibility. The outdated manifests help create urgency around this issue which should help us resolve it. Lets continue the ownership discussion in kubeflow/community#380
