### ISSUE TITLE
Support updating the owner of a profile

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#4890]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Currently when editing the profile CR to update the owner, profiles-kfam doesn’t update the owner annotation of the associated namespace. The old owner still exists.

It's currently by design the owner field cannot be updated: because controller will not know the previous owner, so cannot revoke access of the previous owner. 

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
Support updating the owner and the old owner is revoked. This might be done by adding annotations in the profile CR for the old owner so the controller knows which old owner can be revoked.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yanniszark** [comment]
@IronPan this is a limitation of how the KFAM is currently working (magic annotations).
We should rely on checking K8s RBAC as the source of truth.
That would solve this issue and a multitude of other issues (#4924, #4938, #4936).
I am preparing currently preparing a doc that will also address this specific issue.
, tracked by https://github.com/kubeflow/kubeflow/issues/4960

**Comment by jlewi** [comment]
I'm closing this because I don't think we want to continue to build out profiles. Instead, we want to move towards using RBAC and ISTIORbac so updating "OWNERs" would be the equivalent of making changes to the RBAC roles and bindings.
