### ISSUE TITLE
customize NB_PREFIX base_url

### ISSUE THREAD

**Issue by guanhuichen** [kubeflow/kubeflow#4891]
I cannot customize NB_PREFIX like /prefix/notebook/namespace/nb1 instead of /notebook/namespace/nb1.

The related commit
https://github.com/kubeflow/kubeflow/pull/2620/commits/1285fc09ab334d745b5e796d3bb913a789e717c9

**Comment by jlewi** [comment]
Can you please explain what you are trying to do? Why are you trying to customize the prefix?
