### ISSUE TITLE
Making echo-server Distroless

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4892]
/kind question

**Question:**
@avdaredevil 
 I'm looking to make all images distroless and am wanting to know what is the purpose of the echo-server ?

Reference issue is Convert Container image to distroless #4590

**Comment by avdaredevil** [comment]
I think this is a better question for @jlewi 

Component referenced: https://github.com/kubeflow/kubeflow/tree/master/components/echo-server

**Comment by jlewi** [comment]
It is used for debugging IAP and other connectivity issues.
