### ISSUE TITLE
Dataflow operator Python 3 support

### ISSUE THREAD

**Issue by EDjur** [kubeflow/kubeflow#4894]
/kind question

**Question:**
I'm trying to use the dataflow operator as defined here https://github.com/kubeflow/pipelines/tree/master/components/gcp/dataflow/launch_python

However, I notice that the underlying docker container uses Python 2.7 and hardcode installs apache-beam[gcp]==2.10.0 https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/Dockerfile

Is there any way to run whatever version of python I like (e.g. Python3 and a more up to date version of Beam)?

To me it seems extremely backwards that Kubeflow would only support running Dataflow using a fixed version of Beam, and Python 2.7 only. So I'm hoping that I'm wrong here and that it is indeed possible to use Python3.

**Comment by EDjur** [comment]
On further research, it seems possible to indeed install newer versions of Beam. But the Python2 requirement seems hard to bypass.

**Comment by aaltay** [comment]
Copying my relevant comment from: https://github.com/kubeflow/pipelines/issues/2601

This issue is still open. Beam and Dataflow will soon stop supporting python2 pipelines. After that, kubeflow may not be able launch Dataflow pipelines.
