### ISSUE TITLE
Kubeflow deployment to an existing air-gapped Kubernetes cluster

### ISSUE THREAD

**Issue by sachua** [kubeflow/kubeflow#4897]
/kind question

**Question:**
I followed the guide from https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ to deploy kubeflow on my existing air-gapped Kubernetes 1.15 cluster, but the images still need to be pulled from the Internet. 

I would like to ask if there are any suggestions on how I can go about deploying kubeflow 1.0 without an internet connection with kustomize, since ksonnet is deprecated.

I was thinking of manually pulling the images and uploading them to my private registry which can be pulled by my Kubernetes, will this solution work?

Are there any other possible solutions that I can try to deploy kubeflow on an existing air-gapped Kubernetes cluster?

**Comment by Minkyu-Choi** [comment]
That solution will work.  I was able to deploy kubeflow 1.0 using private registry(But features not fully tested).
However, you'll need to modify many kubeflow manifests manually.

Most sub applications defined images field to change it's image name and tag used in deployment or statefulset at kustomization.yaml under application's base folder. But some are not(seldon-core-operator, cluster-local-gateway).

Additionally, if your private registry is secured then you'll need to add imagePullSecrets for all service accounts which is used by kubeflow pod.

Most service account defined in service-account.yaml under application's base folder. But you should change other files for following applications.(dex, katib-controller, katib-ui, metadata-ui, seldon-core-operator)

I'm not sure this is the best method at this moment but it's hard to find any convenient method.

Any better idea would be welcome and thanks for you guys great work.

**Comment by yannhowe** [comment]
@Minkyu-Choi did you use kfctl or did you replace all the values and parameters manually and apply the manifests using kubectl?

**Comment by Minkyu-Choi** [comment]
@yannhowe I used kfctl. I ran build command first(kfctl build -f) and manually replaced values under kustomize folder. Then I applied this configuration using kfctl(kfctl apply -f).

**Comment by sachua** [comment]
@Minkyu-Choi I managed to deploy kubeflow 1.0 and everything seems to be running except profiles-development.

```
sachua@LAPTOP-V92QORV2:/opt/kftest$ kubectl -n kubeflow logs pod/profiles-deployment-575858b965-5qgmt -c manager   
flag provided but not defined: -workload-identity                                                                                                                                                                                          
Usage of /manager:                                                                                                                                                                                                                           
  -kubeconfig string                                                                                                                                                                                                                               
        Paths to a kubeconfig. Only required if out-of-cluster.                                                                                                                                                                              
  -master string                                                                                                                                                                                                                                   
        The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if 
        out-of-cluster.                                                                                                                         
  -metrics-addr string                                                                                                                                                                                                                           
        The address the metric endpoint binds to. (default ":8080")                                                                                                                                                                            
  -userid-header string                                                                                                                                                                                                                              
        Key of request header containing user id (default "x-goog-authenticated-user-email")                                                                                                                                                   
  -userid-prefix string                                                                                                                                                                                                                              
        Request header user id common prefix (default "accounts.google.com:")
```

did you face any similar issues and how did you solve it?

**Comment by yannhowe** [comment]
> @yannhowe I used kfctl. I ran build command first(kfctl build -f) and manually replaced values under kustomize folder. Then I applied this configuration using kfctl(kfctl apply -f).

Thanks this is pretty much what we are doing also. Glad to see you had results. The project is moving v quickly but if we can get it offline repeatably we will share.

**Comment by Minkyu-Choi** [comment]
@sachua
> did you face any similar issues and how did you solve it?

No, I haven't faced similar issues with profiles-deployment. But, you need to check application's image tag set correctly compare to original deployment.

I had another issue which application behaved abnormally, but it turned out that application's image tag was not correctly set.

In case of profiles-deployment I'm using [v1.0.0-ge50a8531] tag for profile-controller and [v1.0.0-gf3e09203] tag for kfam. Hope this helps you.

**Comment by sachua** [comment]
@Minkyu-Choi Thanks for your advice on image tags, I was able to solve the profiles-deployment issue!

An advice for any others following in our footsteps, I had to update my jupyter-web-app image tag to [v1.0.0-g2bd63238] as well to get the notebooks to work!
