### ISSUE TITLE
Stale Bot closes triaged and lifecycle/frozen issues

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4900]
/kind bug

**What steps did you take and what happened:**
Stale Bot closes triaged and lifecycle/frozen issues
https://github.com/kubeflow/kubeflow/issues/4068

**What did you expect to happen:**
I wouldn't expect lifecycle/frozen issues to be closed.

Not sure who to ping for this one :/
/cc @jlewi

**Comment by jlewi** [comment]
I think this is a misconfiguration issue in our stale bot config.
https://github.com/marketplace/stale

We need to add lifecycle/frozen to the exempt labels in our .github/stale.yml config files
https://github.com/kubeflow/kubeflow/blob/6188f27e403ea1b75bb7229dfa05c9e030d74823/.github/stale.yml#L9

**Comment by jlewi** [comment]
I created: https://github.com/kubeflow/.github/blob/master/.github/stale.yml
Which should create org wide settings. If we verify that works then we can delete the repo level stale installs and this should make it easier to consistently apply and manage.

**Comment by jlewi** [comment]
I don't believe stalebot respects kubeflow/.github.  So we just need to fix the stale.yml configs for each repo. I fixed a bunch of them.
