### ISSUE TITLE
Update the published Kubeflow Roadmap 

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#4903]
/kind feature

**Why you need this feature:**
We need to update our publish roadmap.
https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md

**Describe the solution you'd like:**
I would like to update the roadmap so that the 1.0 info is correct and provide some guidance on 1.10

**Anything else you would like to add:**
this doc provides an initial draft.

https://docs.google.com/document/d/1O-yYcD4z0pP53nz9i8Z8h7brveUc_7F9BM-6VIgJfew/edit#heading=h.10jjg9jlc7nh

**Comment by jlewi** [comment]
Thanks @jbottum for getting this started. 

Do you want to solicit input from the various [label owners](https://github.com/kubeflow/community/blob/master/labels-owners.yaml) about what they are working on? Ideally each repository with its own ROADMAP would update it as well (e.g. kubeflow/fairing#476)

What you have in the doc looks pretty good to me. If possible it might be nice to break it out into 2-3 themes. I would put "Enterprise Readiness" as one bucket.

It would be nice to have another bucket for "Application Development" and put some of the upcoming features for individual applications. Some that come to mind.
   * Pipelines multi user support
   * Metadata lineage tracking
   * Ping other area/application owners for other features?

**Comment by Jeffwan** [comment]
I want to add some roadmaps for operators and MLOPS experiences.

**Comment by jlewi** [comment]
@jbottum can we close this?
