### ISSUE TITLE
Update video examples on Kubeflow.org

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#4904]
/kind feature

**Why you need this feature:**
to update Kubeflow examples for users

**Describe the solution you'd like:**
update this webpage with videos from the talks from KubeCon San Diego

Updates to Kubeflow Docs (examples/videos) 
https://www.kubeflow.org/docs/examples/videos/

this google doc has the urls for these talks

https://docs.google.com/document/d/1llU1KItZ1KLBRQM2poyMFoKWqyiwGuH7uyP0ho5YOUM/edit#

Building a Medical AI with Kubernetes and Kubeflow - Jeremie Vallee, Babylon Health

NOW PLAYING
Building and Managing a Centralized Kubeflow Platform at Spotify - Keshi Dai & Ryan Clough, Spotify
NOW PLAYING
Tutorial: From Notebook to Kubeflow Pipel... Michelle Casbon, Stefano Fioravanzo & Ilias Katsakioris
NOW PLAYING
Measuring and Optimizing Kubeflow Clusters at Lyft - Konstantin Gizdarski & Richard Liu
NOW PLAYING
Advanced Model Inferencing Leveraging KNative, Istio & Kubeflow Serving - Animesh Singh & Clive Cox

NOW PLAYING
Managing Machine Learning in Production with Kubeflow and DevOps - David Aronchick, Microsoft
NOW PLAYING
Towards Continuous Computer Vision Model Improvement with Kubeflow - Derek Hao Hu & Yanjia Li

NOW PLAYING
Keynote: Machine Learning using Kubeflow and Kubernetes - Arun Gupta

NOW PLAYING
Hyperparameter Tuning Using Kubeflow - Richard Liu, Google & Johnu George, Cisco Systems

NOW PLAYING
Panel: Enterprise-grade, On-prem Kubeflow in the Financial Sector
NOW PLAYING
Supercharge Kubeflow Performance on GPU Clusters - Meenakshi Kaushik & Neelima Mukiri, Cisco

NOW PLAYING
Enabling Kubeflow with Enterprise-Grade Auth for On-Prem... Yannis Zarkadas & Krishna Durai

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sarahmaddox** [comment]
/unassign

/good-first-issue

Thanks @jbottum I'll leave this **good first issue** for a community member to tackle.

**Comment by sarahmaddox** [comment]
The docs are in the kubeflow/website repo. Here's a guide to updating the docs:
https://github.com/kubeflow/website/blob/master/README.md

**Comment by sarahmaddox** [comment]
This is fixed by https://github.com/kubeflow/website/pull/1879
Thanks @browningjp!
/close
