### ISSUE TITLE
model training fails because EKS cluster can't connect to s3 endpoint sometimes

### ISSUE THREAD

**Issue by plaffitte** [kubeflow/kubeflow#4905]
/kind bug

**What steps did you take and what happened:**
I am trying to run several ML model training in a python script using tensorflow 2. To do this I dockerize my script and setup a tfjob on Kubeflow. For some models the training goes to completion but for others the training fails and I get the following error when tensorflow tries to save the checkpoint:

`cannot connect to endpoint`

**What did you expect to happen:**

I expect the s3 connection errors to be handled by tensorflow so that it doesn't error out when it can't connect to the endpoint during checkpoint saving.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.0.0
- kfctl version: 0.7.0
- Kubernetes platform: EKS
- Kubernetes version: 1.14.0
- OS (e.g. from `/etc/os-release`):

**Comment by Jeffwan** [comment]
@plaffitte 

All your checkpoint persistence call failed? Have you ever successfully talk to S3 in your environment? Could you share trainer pod env setting for S3?

**Comment by plaffitte** [comment]
Thanks for your answer @Jeffwan , I don't know if they all fail, but when I set the env variable `AWS_LOG_LEVEL` to `1` I get a lot of `404` from `aws_logging.py` during the training process. 
However this does not seem to hinder training since it continues. So it seems like it is able to communicate to S3 (In fact at the very beginning of the script I download a dataset from S3 and that works like a charm).  
But I guess at some point it becomes critical, such as when the evaluation is looking for a new checkpoint and it hasn't been saved because it could not find the endpoint.
I'm sorry I'm not sure how to interpret all those log messages...

Here are my pod settings:

`apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccount: default-editor
          containers:
          - name: tensorflow
            image: training-image
            command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-data-dir=$(dataDir)
            - --tf-model-dir=$(modelDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)
            - --tf-training-mode=$(mode)
            env:
            - name: modelDir
              value: $(modelDir)
            - name: dataDir
              value: $(dataDir)
            - name: trainSteps
              value: $(trainSteps)
            - name: batchSize
              value: $(batchSize)
            - name: learningRate
              value: $(learningRate)
            - name: mode
              value: $(mode)
            volumeMounts:
              - name: training-data
                mountPath: "/data"
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: training-data
            emptyDir: {}

**Comment by Jeffwan** [comment]
I don't see you have AWS environment variables in the container for TF to talk to s3

**Comment by plaffitte** [comment]
@Jeffwan Yeah I'm sorry all the AWS env variables are in a different config file with a config map definition. Here's a snippet:

`configMapGenerator:
- literals:
  - trainSteps=50
  - batchSize=16
  - learningRate=0.01
  - name=test-with-mnist-config
  - awsAccessKeyIDName=awsAccessKeyID
  - awsSecretAccessKeyName=awsSecretAccessKey
  - S3_ENDPOINT=s3.us-east-1.amazonaws.com
  - AWS_ENDPOINT_URL=http://s3.us-east-1.amazonaws.com
  - AWS_REGION=us-east-1
  - BUCKET_NAME=some-bucket
  - S3_USE_HTTPS=1
  - S3_VERIFY_SSL=1
  - dataDir=s3://some-bucket/some-folder
  - modelDir=/opt/model/
  - mode=train
  name: mnist-map-training`

**Comment by Jeffwan** [comment]
Can you try to change `http://s3.us-east-1.amazonaws.com` to `s3.us-east-1.amazonaws.com`?

**Comment by plaffitte** [comment]
Thanks for the suggestion, I'm trying that right now. In the meantime I just wanted to share with you the error I was able to pinpoint during my last experiment run. It seems to change a little according to the level of verbose that I set in my script (`AWS_LOG_LEVEL` and `TF_CPP_MIN_LOG_LEVEL`). This is what I got:

`I0403 07:13:10.347058 140302641305408 basic_session_run_hooks.py:613] Saving checkpoints for 3052 into s3://moodagent-research/Users/pierre/cluster/World/model/model.ckpt.
2020-04-03 07:13:10.685166: E tensorflow/core/platform/s3/aws_logging.cc:60] HTTP response code: 400
Exception name: XAmzContentSHA256Mismatch
Error message: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
7 response headers:
connection : close
content-type : application/xml
date : Fri, 03 Apr 2020 07:13:10 GMT
server : AmazonS3
transfer-encoding : chunked
x-amz-id-2 : Q8G0wOH3xdZObVoX2p1AOr0Au4RyAEh6VTjCbWCh2gz4ApL7A5gznkTS61KoEgwHZQtN3ICpv1c=
x-amz-request-id : CBE8C06328C621C5

 Error during training on feature World

XAmzContentSHA256Mismatch: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
	 [[node save/SaveV2_1 (defined at usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py:334) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/SaveV2_1:
 Const (defined at usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py:333) ()`

**Comment by plaffitte** [comment]
I made the change you suggested but I still have issues. Now it seems like I get a different error every time... Those are 4 errors I've got from running my script so far:

`Read less bytes than requested
	 [[node save/RestoreV2 (defined at usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py:334) ]] ()`

`XAmzContentSHA256Mismatch: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
	 [[node SaveV2_1 (defined at usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py:403) ]] ()`

`There was no new checkpoint after the training. Eval status: no new checkpoint ('There was no new checkpoint after the training. Eval status: no new checkpoint',)`

`XAmzContentSHA256Mismatch: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
	 [[node SaveV2_1 (defined at usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py:403) ]] ()`

**Comment by Jeffwan** [comment]
@plaffitte Have you tested in a container, we are trying to solve kubeflow problems here. If there's something wrong on the SDK side. I would suggest you to submit issue to aws/sdk. For example, https://github.com/aws/aws-sdk-go/issues/148 it has similar issue but in goland

**Comment by plaffitte** [comment]
@Jeffwan Thanks for the tip, I'll put my issue there. And thanks for your help
