### ISSUE TITLE
Notebook provisioner UI ignores specified StorageClass

### ISSUE THREAD

**Issue by groszewn** [kubeflow/kubeflow#4906]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We have deployed Kubeflow at `v1.0.1` into our cluster.  Our cluster does not have a default StorageClass, and when attempting to provision a notebook from the `New Server` button, the `New` dropdown option for `workspaceVolume` does not appear (regardless of whether we set the `workspaceVolume` class to an existing StorageClass in the cluster).
![image](https://user-images.githubusercontent.com/13921855/78153437-0d023e80-7409-11ea-92ce-dd5c1931b2ff.png)

**What did you expect to happen:**

If the config has value `{none}` and no default storage class is set then the UI should have the `New` option disabled. It should also show a tooltip as to why it is disabled.

If the config has an existing StorageClass specified, the `New` option should work as expected with that StorageClass.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): `1.0.1`
- kfctl version: (use `kfctl version`): `v1.0.1-0-gf3edb9b`
- Kubernetes platform: (e.g. `minikube`) Custom AWS Cluster
- Kubernetes version: (use `kubectl version`): `v1.14.8`
- OS (e.g. from `/etc/os-release`): `Ubuntu 18.04`

**Comment by kimwnasptd** [comment]
/area jupyter
/priority p1

Thanks for catching that @groszewn! The frontend seems to completely ignore the `class` value of the workspace volume in the config and always expects to use the default storage class.

The UX should be the following:
* The frontend must use the value in the config for the storage class of the workspace volume
* The default value of the class in the config should be `{none}` (use the default storage class)
* If the config has value `{none}` and no default storage class is set then the UI should have the `New` option disabled. It should also show a tooltip as to why it is disabled.

I can create a PR for this in the next couple days
/assign kimwnasptd

**Comment by jbottum** [comment]
@groszewn Hey Nick - Do you still need this enhancement ?  We are getting close to the Kubeflow 1.1 cut date.   Please let us know.

**Comment by groszewn** [comment]
Hey @jbottum, it would be great to have this fix available.
