### ISSUE TITLE
Manage Contributor is not there in kubeflow UI 1.0.1

### ISSUE THREAD

**Issue by unagaraju88** [kubeflow/kubeflow#4910]
/kind bug
Manage Contributor option is not there in the kubeflow UI 
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After installing kubeflow kfctl_k8s_istio.v1.0.1.yaml  , I logged into kubeflow UI with default namespace (anonymous)as per the steps https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/ 
But I do not see manage contributor option.
I created the kubernetes cluster and deployed kubeflow.

**What did you expect to happen:**
I expected that by default namespace, I get admin privilege to view "Manage Contributor"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0 kfctl_k8s_istio.v1.0.1.yaml  this is the file I used to deploy kubeflow.
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: (e.g. `minikube`) Azure
- Kubernetes version: (use `kubectl version`):  v1.15.7 
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.43.1.el7.x86_64

**Comment by jtfogarty** [comment]
@unagaraju88 Using kfctl_k8s_istio.v1.0.1.yaml  is really a single user install so Manage Contributor will not be applicable
