### ISSUE TITLE
Failed kubeflow deployment on Openshift Cluster

### ISSUE THREAD

**Issue by leela-uppuluri** [kubeflow/kubeflow#4914]
Hello,

I was trying to install kubeflow-0.7.0 on openshift-4.2.0. I tried to follow all the steps that you mentioned in the official documentation and I could able to build successfully but I am seeing the below snapshot error after running this `kfctl apply -V -f ./kfctl_k8s_istio.0.7.1.yaml` command. I tried to delete and install everything from scratch but still sees the same error. Does anyone of you have any recommendations on this?

![capture1](https://user-images.githubusercontent.com/43678538/78326401-ea267600-753f-11ea-9363-b02a42e1d16d.png)

**Comment by jbottum** [comment]
@pdmack hey pete, can you please relay this to the appropriate folks, thanks.

**Comment by vpavlin** [comment]
Hi @leela-uppuluri can you try to follow: https://www.kubeflow.org/docs/openshift/ ?

**Comment by leela-uppuluri** [comment]
@vpavlin I was following the same documentation and lately I realized that I have different version of kubernetes installed on openshift cluster which is incompatible with kubeflow.
