### ISSUE TITLE
Add support for kill switches for left side tabs of Dashboard like GitHub, Contributors..etc

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/kubeflow#4917]
/kind feature
Since multitenancy takes a long time to get implemented across the board. It is useful to have kill switches to hide the left side tabs which is not needed to be deployed. Examples are pipelines, github, contributors..etc
**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

Use kill switches as simple ENV variables by which we can enable and disable the tabs so that there is a control to hide this from the UI>
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
Are you talking about the centraldashboard? Including a screenshot might help. 

What is github contributors referring to?
