### ISSUE TITLE
Kubeflow without Google Cloud Storage

### ISSUE THREAD

**Issue by tech348712013870132** [kubeflow/kubeflow#4922]
/kind question

**Question:**
Is it possible to replace the usage of Google Cloud Storage buckets with an alternative on-premise solution so that it is possible to run e.g. Kubeflow Pipelines completely in-depended from the Google Cloud Platform?

**Comment by jbottum** [comment]
@tech348712013870132 hey Tech, Josh here from Arrikto.   Arrikto provides a standards based storage solution that integrates with Kubeflow.   Rok provides a storage class to CSI and enables K8s operations (Dynamic Volume Provisioning, Statefulsets, etc) for persistent volumes.    www.arrikto.com

**Comment by jlewi** [comment]
@tech348712013870132  most kubeflow applications don't require GCS or object storage. Kubeflow pipelines requires object storage but it uses MinIO to provide an abstraction that also provides a reference implementation for on prem solutions.

Did you try following one of the on prem installation guides and run into problems?
