### ISSUE TITLE
Profile doesn't work with Group ownership

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#4923]
/kind bug

**What steps did you take and what happened:**
I have kubeflow auth setup with dex and okta saml connector. Things works perfectly for user owned profiles.

However, when I create profile with the owner as a Group. e.g.
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
name: group1-profile
spec:
owner:
kind: Group
name: group1

I'm not able to get this to work although I see groups attribute coming back correctly in the saml. So even if the user has group "group1", I don't see that profile available for them in the profile drop-down list in the UI.

**What did you expect to happen:**
User have access to group1-profile because it is owned by Group "group1" and user belongs to that group.

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): dev_local
- kfctl version: v1.0-0-g94c35cf
- Kubernetes platform: eks
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.4

**Comment by kunmingg** [comment]
FYI:
On roadmap: https://github.com/kubeflow/kubeflow/issues/4188

**Comment by yanniszark** [comment]
Let's close in favor of #4188 
/close
