### ISSUE TITLE
Manage contributors not visible Kubeflow v0.6.2

### ISSUE THREAD

**Issue by catalinad90** [kubeflow/kubeflow#4926]
Good day,

I have installed Kubeflow v0.6.2 with istio https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml and kfctl v0.6.2 on a Kubernetes cluster v1.14.

I'm not able to see the manage contributors tab from the dashboard, but I can create new profiles  from cli with kubectl. 

Can someone provide support on what might be missing?

Thanks,
Catalina

**Comment by Jeffwan** [comment]
@catalinad90 You need to use manifest with multi-user support. https://www.kubeflow.org/docs/components/multi-tenancy/ check here.

**Comment by catalinad90** [comment]
@Jeffwan 

What you have sent me is for v1.0, but I have v0.6.2. This manifest can be applied to v0.6.2? And where exactly can I find it. 

The manifests used for the kubeflow deployment are the ones referenced in the istio file for version v0.6.2:

https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml 

Thanks,
Catalina

**Comment by Jeffwan** [comment]
@catalinad90 I mean kfctl_k8s_istio.0.6.2.yaml this manifest doesn't have multi-user support. This feature is not available for all manifest

**Comment by catalinad90** [comment]
Thanks for the clarification @Jeffwan ! :)
