### ISSUE TITLE
Release Kubeflow v1.0.2

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4929]
TODO:

- [x] https://github.com/kubeflow/manifests/issues/984
- [x] Enable patch upgrade
- [x] Create v1.0.2 kfdefs
- [x] Cut release for manifests
- [x] Cut release for kfctl
- [x] Enable testing on v1.0.2
- [x] Create patch release upgrade spec
- [ ] Update deploy app

/cc @Jeffwan 
/cc @Bobgy 

Please add cherrypick PRs.

**Comment by Jeffwan** [comment]
We have these two PRs need to backport to v1.0branch 

https://github.com/kubeflow/manifests/issues/1035
https://github.com/kubeflow/manifests/pull/1081

**Comment by Jeffwan** [comment]
We have a change only want to apply on v1.0.2 manifest. I think it can be done after `Create v1.0.2 kfdefs`?

**Comment by richardsliu** [comment]
What is the change? I am thinking of just creating the base v1.0.2 manifests today, which we can modify later.

**Comment by Jeffwan** [comment]
@richardsliu All changes are listed above.

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/kfctl/pull/302

**Comment by Bobgy** [comment]
Just taking a note, these KFP PRs are cherry picked to 1.0.2: https://github.com/kubeflow/manifests/pull/1065, https://github.com/kubeflow/manifests/pull/1064 and https://github.com/kubeflow/manifests/pull/1093

**Comment by richardsliu** [comment]
cherry-picks:
https://github.com/kubeflow/manifests/pull/1111
https://github.com/kubeflow/kfctl/pull/316

**Comment by richardsliu** [comment]
Release is done: https://github.com/kubeflow/kfctl/releases/tag/v1.0.2

/close

**Comment by Jeffwan** [comment]
I create a doc issue update https://github.com/kubeflow/website/issues/1906. I think doc team will take it over. Thanks for the excellent work @richardsliu
