### ISSUE TITLE
Upgrade Kubeflow 1.0.0. to 1.0.1 failing with Encountered error applying application istio-install: (kubeflow.error): Code 500 with message: Apply.Run Error 

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/kubeflow#4934]
/kind bug
Upgrade Kubeflow 1.0.0 to 1.0.1 failed with infinite loop

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

servicerole.rbac.istio.io/istio-ingressgateway unchanged
servicerolebinding.rbac.istio.io/istio-ingressgateway unchanged
ERRO[0635] Permanently failed applying application istio-install; error:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-galley", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\",\"operator.istio.io/component\":\"Galley\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"galley" "istio":"galley" "operator.istio.io/component":"Galley" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-galley" "namespace":"istio-system" "resourceVersion":"19692743" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-galley" "uid":"5fab29f2-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"galley" "istio":"galley" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-galley" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-pilot", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"operator.istio.io/component\":\"Pilot\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"pilot" "istio":"pilot" "operator.istio.io/component":"Pilot" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-pilot" "namespace":"istio-system" "resourceVersion":"19692957" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-pilot" "uid":"5feff602-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"pilot" "istio":"pilot" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-pilot" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"}}}}\n"},"labels":{"app":"sidecarInjectorWebhook","operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"app":"sidecarInjectorWebhook","release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-sidecar-injector", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"operator.istio.io/component\":\"Injector\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"sidecar-injector" "istio":"sidecar-injector" "operator.istio.io/component":"Injector" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-sidecar-injector" "namespace":"istio-system" "resourceVersion":"11623413" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-sidecar-injector" "uid":"5fba6e07-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"sidecar-injector" "istio":"sidecar-injector" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-sidecar-injector" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.]  filename="kustomize/kustomize.go:206"
Error: couldn't apply KfUpgrade:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-galley", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\",\"operator.istio.io/component\":\"Galley\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"galley" "istio":"galley" "operator.istio.io/component":"Galley" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-galley" "namespace":"istio-system" "resourceVersion":"19692743" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-galley" "uid":"5fab29f2-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"galley" "istio":"galley" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-galley" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-pilot", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"operator.istio.io/component\":\"Pilot\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"pilot" "istio":"pilot" "operator.istio.io/component":"Pilot" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-pilot" "namespace":"istio-system" "resourceVersion":"19692957" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-pilot" "uid":"5feff602-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"pilot" "istio":"pilot" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-pilot" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"}}}}\n"},"labels":{"app":"sidecarInjectorWebhook","operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"app":"sidecarInjectorWebhook","release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-sidecar-injector", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"operator.istio.io/component\":\"Injector\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"sidecar-injector" "istio":"sidecar-injector" "operator.istio.io/component":"Injector" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-sidecar-injector" "namespace":"istio-system" "resourceVersion":"11623413" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-sidecar-injector" "uid":"5fba6e07-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"sidecar-injector" "istio":"sidecar-injector" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-sidecar-injector" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.]
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

couldn't apply KfUpgrade:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-galley", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"galley\",\"istio\":\"galley\",\"operator.istio.io/component\":\"Galley\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-galley\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"galley\",\"istio\":\"galley\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"galley" "istio":"galley" "operator.istio.io/component":"Galley" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-galley" "namespace":"istio-system" "resourceVersion":"19692743" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-galley" "uid":"5fab29f2-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"galley" "istio":"galley" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-galley" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\"}}}}\n"},"labels":{"operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-pilot", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"operator.istio.io/component\":\"Pilot\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-pilot\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"pilot\",\"istio\":\"pilot\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"pilot" "istio":"pilot" "operator.istio.io/component":"Pilot" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-pilot" "namespace":"istio-system" "resourceVersion":"19692957" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-pilot" "uid":"5feff602-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"pilot" "istio":"pilot" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-pilot" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden., error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecarInjectorWebhook\",\"istio\":\"sidecar-injector\"}}}}\n"},"labels":{"app":"sidecarInjectorWebhook","operator.istio.io/component":null,"operator.istio.io/managed":null,"operator.istio.io/version":null,"release":null}},"spec":{"selector":{"matchLabels":{"app":"sidecarInjectorWebhook","release":null}}}}
to:
Resource: "policy/v1beta1, Resource=poddisruptionbudgets", GroupVersionKind: "policy/v1beta1, Kind=PodDisruptionBudget"
Name: "istio-sidecar-injector", Namespace: "istio-system"
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodDisruptionBudget" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1beta1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"operator.istio.io/component\":\"Injector\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.4.6\",\"release\":\"istio\"},\"name\":\"istio-sidecar-injector\",\"namespace\":\"istio-system\"},\"spec\":{\"minAvailable\":1,\"selector\":{\"matchLabels\":{\"app\":\"sidecar-injector\",\"istio\":\"sidecar-injector\",\"release\":\"istio\"}}}}\n"] "creationTimestamp":"2020-03-26T22:01:41Z" "generation":'\x01' "labels":map["app":"sidecar-injector" "istio":"sidecar-injector" "operator.istio.io/component":"Injector" "operator.istio.io/managed":"Reconcile" "operator.istio.io/version":"1.4.6" "release":"istio"] "name":"istio-sidecar-injector" "namespace":"istio-system" "resourceVersion":"11623413" "selfLink":"/apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-sidecar-injector" "uid":"5fba6e07-6fad-11ea-bab1-000d3a06c1df"] "spec":map["minAvailable":'\x01' "selector":map["matchLabels":map["app":"sidecar-injector" "istio":"sidecar-injector" "release":"istio"]]] "status":map["currentHealthy":'\x00' "desiredHealthy":'\x01' "disruptionsAllowed":'\x00' "expectedPods":'\x00' "observedGeneration":'\x01']]}
for: "/tmp/kout056651486": PodDisruptionBudget.policy "istio-sidecar-injector" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.]
(base) 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: (e.g. `minikube`): OnPrem
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by discordianfish** [comment]
Can confirm this. Happens to me when trying to upgade from 1.0.0 to 1.0.2. Seems to happen with almost? all Application resources:

- application.app.k8s.io/api-service
- application.app.k8s.io/persistent-agent
- application.app.k8s.io/pipelines-ui
- application.app.k8s.io/pipelines-viewer
- application.app.k8s.io/pipeline-visualization-service

All due to `MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`
