### ISSUE TITLE
Implications of disabling sidecar injection for user namespaces

### ISSUE THREAD

**Issue by akirillov** [kubeflow/kubeflow#4935]
/kind question

**Question:**
Hi everyone!

Currently, Profile controller adds sidecar injection annotation [by default](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L120-L130) which enables Istio sidecar injection for all pods and jobs in the profile namespace. 

Here are some of the things that do not work well with Istio:
* Spark from a notebook in client mode: https://github.com/kubeflow/kubeflow/issues/4306
* Horovod https://github.com/horovod/horovod/issues/1855
* Job-based workloads do not complete because of https://github.com/istio/istio/issues/11045 e.g. https://github.com/kubeflow/katib/issues/1042. Pipelines are also affected if Istio is enabled.

Some of the issues can be resolved by adding `"sidecar.istio.io/inject": "false"` annotation to the resources but it will be required for every resource created by a user and seems like an unnecessary boilerplate which also doesn't solve all the problems.

So my question here is what are the (security) implications of disabling Istio at the namespace level for user namespaces? When Istio is disabled, RBAC policies are still in place and users are only allowed to operate within their namespaces.

**Comment by yanniszark** [comment]
Hi @akirillov!
I will try to answer your question with an example.

> When Istio is disabled, RBAC policies are still in place and users are only allowed to operate within their namespaces.

Correct, K8s RBAC is still in place, however Istio RBAC targets a different area.
K8s RBAC authorizes access to the K8s API-Server endpoints (who can create Notebooks, Pods, etc.)

Istio RBAC authorizes access to network resources (Services).
The big application of that right now is Jupyter Notebooks. Istio RBAC allows you to access your Jupyter Notebook web interface, but denies access to non-authorized identities.
Without Istio RBAC, everyone would be able to access your Notebooks.
Does that answer your question?

**Comment by akirillov** [comment]
Thanks a lot for the answer, @yanniszark! Just to clarify, does it mean that anybody authenticated with the cluster (i.e. having a Profile) will have access to all the notebooks or completely everybody who have network access?

**Comment by yanniszark** [comment]
Anyone that is authenticated.
You still need to pass through the Istio Gateway that enforces authentication.
Since this is answered, I'm closing this and linking the answer to https://github.com/kubeflow/website/issues/1903, we can improve the doc as part of that issue.
/close
