### ISSUE TITLE
cluster-admin ClusterRoleBinding not respected

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#4936]
/kind bug

**What happened:**
Users who have a 'cluster-admin' ClusterRoleBinding are not admins in Kubeflow, (in that they cant see all namespaces under "Manage Contributors").

This behaviour is implied here: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-through-the-kubeflow-ui

Am I missing something about how you make someone a kubeflow admin?

**Environment:**
- Kubeflow version: v1.0.0
- Kubernetes platform: GKE
- Kubernetes version: v1.15.9-gke.24

**Comment by yanniszark** [comment]
@jtfogarty I don't think this is P2 as Kubeflow wants to depend on K8s RBAC and the CentralDashboard should work if the user has cluster-admin permissions.
/priority p1

**Comment by jlewi** [comment]
#4960 Uber issue tracking a rethink of the multi user model

**Comment by thesuperzapper** [comment]
There is a chance this is related to: https://github.com/kubeflow/manifests/pull/1119

But I am not sure where the call to check for a cluster-admin ClusterRoleBinding might happen. (E.g. is it currently in the centraldashboard?)

**Comment by thesuperzapper** [comment]
@jlewi but either way, where did this feature go, has it ever existed?

**Comment by thesuperzapper** [comment]
@jlewi, @yanniszark, I have found where you currently specify the cluster admin, but it seems that you can __only specify a single user__.

[Here is the code](https://github.com/kubeflow/kubeflow/blob/v1.0/components/access-management/main.go#L40), which is used by the `kfam` image, by specifying the `/access-management -cluster-admin me@email.com`. 

We would need to inject the RBAC based changes into [this kfam api call](https://github.com/kubeflow/kubeflow/blob/v1.0/components/access-management/kfam/api_default.go#L282).

**Comment by jlewi** [comment]
As @yanniszark has mentioned elsewhere should we just update the caller code to do a subject access review check?
