### ISSUE TITLE
How to access GPU from default image (tensorflow-2.1.0-notebook-gpu:1.0.0)?

### ISSUE THREAD

**Issue by saschagrunert** [kubeflow/kubeflow#4939]
/kind question

**Question:**

Hey, I've got my GPU node to work and would like to access the graphics card now from the default GPU enabled notebook image. The issue is, that I do not have sufficient permissions with the user `jovyan` to run (for example) `nvidia-smi`. If I try to sudo inside the image, then I only get:

```
> kubectl exec -it gpu-test-0 sudo nvidia-smi
Defaulting container name to gpu-test.
Use 'kubectl describe pod/gpu-test-0 -n workspace' to see all of the containers in this pod.
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
command terminated with exit code 1
```

I tried multiple volume provisioner (not NFS based), but still got the same error message. Any ideas?

**Comment by saschagrunert** [comment]
I created a similar GPU based container image here: https://github.com/saschagrunert/kubeflow-notebook-gpu

Yeah I know it's running as root. But now I am able to utilize my GPU :shrug:

**Comment by Jeffwan** [comment]
Trying to understand the case why people need low level control. I assume user will just use gpu based framework like tensorflow, pytorch in notebook? Any other use cases? If that's a reasonable request, we can make some changes here

**Comment by saschagrunert** [comment]
The thing is that the notebook user is not able to access the GPU. I’m wondering how other users handle that kind of issue. 🤔

**Comment by PatrickXYS** [comment]
So we wonder the reason that notebook users want to access the GPU, from my side, users may want to monitor GPU status.

**Comment by jlewi** [comment]
I believe TensorFlow and PyTorch are able to access the GPU even without being root. So the issue might just be nvidia-smi or other low level tools.

**Comment by saschagrunert** [comment]
Did a bit more research on the topic and I think that the nvidia container runtime (via docker) automatically adds the user and group permissions to the device when mounted into the container. I don’t have a docker setup at hand, but I guess we can verify that via running `nvidia-smi` or checking access to `/dev/nvidia*`.

I think if I’m right the I have to fix it in the OCI hook and adding the right permissions.
