### ISSUE TITLE
Protect InferenceService with Google IAP

### ISSUE THREAD

**Issue by livneros** [kubeflow/kubeflow#4946]
Hey. 
We are trying to enable access for our InferenceService only with an IAP authentication.
Currently, the access is open through the load balancer's public IP. 
Is there any solution for that? maybe similar to the [tfserving solution](https://www.kubeflow.org/docs/components/serving/tfserving_new/#sending-prediction-request-through-ingress-and-iap)
Thanks.

**Comment by Jeffwan** [comment]
Check this close https://github.com/kubeflow/kfserving/issues/760

**Comment by jlewi** [comment]
Duplicate of kubeflow/kfserving#760
