### ISSUE TITLE
TF Serving component logging

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#495]
TF Serving component should be able to export logs to some backend.

We will start with pod logs (stdout/stderr). Later we will look into logging payload.

**Comment by jlewi** [comment]
@lluunn What is the current status of this item? What got done in last week's sprint?

**Comment by lluunn** [comment]
I tried out the new Stackdriver GKE agents, https://cloud.google.com/monitoring/kubernetes-engine/.
It's working.
Nothing to be done for now, closing this.
