### ISSUE TITLE
PVC discovery

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#4950]
/kind feature

**Describe the solution you'd like:**
Currently, we force users to remember the name of PVC's created through the notebook spawner UI if they want to mount them again. 

It would be relatively easy to show a search box for all PVC's in the currently selected namespace.

This would reduce wasted resources when users don't mean to constantly create new PVC as they create/shutdown notebook servers.

**Comment by yanniszark** [comment]
Hi @thesuperzapper!
We have added a feature similar to what you describe in the latest MiniKF.
We also have [a blog post](https://journal.arrikto.com/democratizing-the-use-of-pvcs-with-the-introduction-of-a-volume-manager-ui) about the feature as well as some [youtube videos](https://www.youtube.com/watch?v=Uj_byHLpMh0&list=PLD-Taer66dlIDrGCRjQmfwzfpBSSCm7Fd) demonstrating it.
You can try it out yourself, by deploying MiniKF [locally](https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/) or on [GCP](https://www.kubeflow.org/docs/started/workstation/minikf-gcp/).
Does that satisfy your requirements?

**Comment by thesuperzapper** [comment]
While that is cool, it doesn't solve the issues with the notebook spawner UI, namely that users must type the name of the PVC.

Also, I am confused, is this a commercial product?

**Comment by thesuperzapper** [comment]
bump - I still believe this is a good idea

I haven't got around to starting a PR for this yet (so if anyone else is game, go ahead).
The architecture is relatively straightforward, as the notebook server can just list the PVC's in the users namespace, and expose this as a drop-down.

**Comment by thesuperzapper** [comment]
This is implemented in https://github.com/kubeflow/kubeflow/pull/5280

**Comment by ca-scribner** [comment]
Not exactly the same, but we've tried to make PVC management easier for users by adding a separate PVC table (StatCan/jupyter-apis#18).  Arguably this could be a separate page on the left hand bar, too.  Either way it makes it much easier to notice and manage your PVC sprawl.

<img width="555" alt="Screenshot 2020-11-09 115640" src="https://user-images.githubusercontent.com/48125859/98571814-e9e31b80-2282-11eb-87bd-a4309d7bf519.png">

**Comment by DavidSpek** [comment]
I think this also ties in with the Volume Manager UI and my plan to add volume and notebook snapshot and restore support to it.

**Comment by thesuperzapper** [comment]
@DavidSpek did we ever implement this?

**Comment by DavidSpek** [comment]
@thesuperzapper Nope, if you select `Existing` you won't get a list of existing PVCs. This will need to be part of the spawner rewrite, along with an option for `Clone Snapshot`, etc.
