### ISSUE TITLE
Allow creation of profiles within dashboard

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#4952]
/kind feature

**Describe the solution you'd like:**
Currently to create a new profile (other than with the first registration flow) users must manually create Profile resources (in the default namespace).

This means many use-cases for kubeflow are cumbersome, for example, creating a profile for a specific business project, and adding collaborators.

Therefore, we should allow users to create new Profiles within the dashboard

**Comment by thesuperzapper** [comment]
I still think this is important. (bumping to remove stale)

**Comment by mohittalele** [comment]
bumping to remove stale
