### ISSUE TITLE
Enforce Profile/Namespace naming in registration flow

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#4953]
/kind feature

**Describe the solution you'd like:**
Currently, users can create any namespace they like within the Profile registration flow, as long as it doesn't already exist. 

This is a security risk, as they could name the profile (and corresponding namespace), as if it were another user, or production environment.

We should allow cluster operators to specify restrictions on the profile name.

This could be implemented as a simple regex on the profile name field, or as an option to preform some standard Profile name creation based off the user's login.

Example of possible Profile name structure:
* `[kubeflow-profile-prefix]_[user-login-hash]`
* `[kubeflow-profile-prefix]_[user-entered-value]`

**Comment by Jeffwan** [comment]
Similar to this one https://github.com/kubeflow/kubeflow/issues/4943

**Comment by jlewi** [comment]
Duplicate of #4942

**Comment by thesuperzapper** [comment]
@jlewi this is not a dupe of #4942, this issue is requesting the ability to enforce what namespace are created, not if they are automatically created

**Comment by jlewi** [comment]
I think as discussed in 
https://groups.google.com/forum/#!topic/kubeflow-discuss/whS_j4RlEJo I think we are moving away from self-serve at least in the context of platform teams serving multiple customers.

I think the direction we are trending is that the operators would create the namespaces and thus enforce whatever restrictions they want at creation time.

I think the pattern that is highest priority is doing this through GitOps; i.e. a team would open up a PR to request a namespace and then admin would approve it.

**Comment by jbottum** [comment]
@thesuperzapper @jlewi @Jeffwan this feature is scheduled for delivery in Kubeflow 1.1.   What is our next step?  Do we have a path to deliver this functionality ?

**Comment by thesuperzapper** [comment]
@jbottum, all it needs is a pretty basic forum validation to the Profile registration namespace field, and maybe some backend protection to prevent just forcing the API to accept a different namespace name with REST calls.

**Comment by jlewi** [comment]
@thesuperzapper are you interested in working on this?

**Comment by thesuperzapper** [comment]
I am currently working on improving the Notebook Spawner UI, so depending on how long that takes me, I might not get time for this, feel free to take it up (or assign it) if you like.

**Comment by thesuperzapper** [comment]
Bump

**Comment by thesuperzapper** [comment]
Bump

**Comment by thesuperzapper** [comment]
/reopen
I think we should still consider doing this

cc @DavidSpek

**Comment by konsloiz** [comment]
Hello everyone. Is this feature added in the current Kubeflow version? We are deploying Kubeflow in a big enterprise and this seems really useful.

**Comment by thesuperzapper** [comment]
@konsloiz no, not yet, but it shouldn't be very hard to implement into the central dashboard by using an environment variable to specify the profile-name regex.

 Do you have the capacity to help @konsloiz?
