### ISSUE TITLE
Kubernetes GPU pods /Kubeflow

### ISSUE THREAD

**Issue by romanbilenko174** [kubeflow/kubeflow#4954]
/kind question

**Question:**
I have 2 servers with 4 tesla K40 GPUs.

I have successfully created a kubernetes cluster installed kubeflow 1.0 and evertything needed for it to work fine.

I can successfully create a Jupyter notebook server with 4 GPUs and use keras multigpu model on it and everything works fine.

Can I use 8 gpu (4 from one server and 4 from another) to create jupyter notebook server or run any gpupod or only 4 for one gpupod is avaliable for me?

When I try use 8 GPUs I get 0/2 nodes are available: 2 Insufficient nvidia.com/gpu

**Comment by Jeffwan** [comment]
You can not attach GPU from different nodes to one single pod. In this case, you need distributed training.

**Comment by yanniszark** [comment]
Closing since the question is answered.
/close
