### ISSUE TITLE
TF serving component monitoring

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#496]
TF serving component should expose metrics, through some endpoint or push to other backend.

Metrics include
- system metrics: cpu / mem usage, gpu usage, rpc metrics
- application metrics: number of predictions, error count, latency

**Comment by jlewi** [comment]
For rpc metrics, does gRPC or TF Serving expose these metrics? If not should we use envoy & istio to provide a proxy and collect the metrics from the proxy.

**Comment by jlewi** [comment]
Now that we are using ISTIO what work remains?

**Comment by lluunn** [comment]
- The label in the graph needs to be figured out. The source might not be in the istio service mesh, so the label shows as known. related to https://github.com/kubeflow/examples/issues/79
- expose dashboard, https://github.com/kubeflow/kubeflow/issues/644
- For system metrics, we already have cpu/mem, and gpu will come soon. I don't think there is immediate AI on our side.
- documentation on how to get system metrics and rpc metrics.
