### ISSUE TITLE
Design Doc: Evaluate and Improve our Multi-User model

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4960]
/kind feature

Prepare a design doc evaluating and suggesting improvements for our current multi-user model.
Capture the discussion in this thread: https://groups.google.com/forum/#!searchin/kubeflow-discuss/subject$20access$20review%7Csort:date/kubeflow-discuss/whS_j4RlEJo/98xnBHH4BgAJ

Update:
Doc: https://docs.google.com/document/d/11Xi-I2OqJvUuy_Zg0NskMF9GmworRDJhlu68poDgK5c/edit?usp=sharing

KFAM Current Use-Cases: https://docs.google.com/document/d/19cHFmuv-qfutY27aQv1n-u3xEH8rXcSU60xybMbU1Co/edit?usp=sharing

cc @jlewi

**Comment by yanniszark** [comment]
Doc: https://docs.google.com/document/d/11Xi-I2OqJvUuy_Zg0NskMF9GmworRDJhlu68poDgK5c/edit?usp=sharing

**Comment by jbottum** [comment]
@yanniszark TDo we have a path to complete this delivery for Kubeflow 1.1?  What is our next step ?

**Comment by jbottum** [comment]
@yanniszark Hi Yannis, Can this issue please be downgraded to P2 or closed before the 1.1 cut date please ?

**Comment by jlewi** [comment]
@yanniszark can we close this
