### ISSUE TITLE
Missing Deployments in 1.0.1 using kfctl_istio_dex_v1.0.1

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4961]
/kind question

**Question:**
why are there missing istio deployments in below;

The below was installed using kfctl_istio_v1.0.1

||||||
|---|---|---|---|---|
|NAME|READY|UP-TO-DATE|AVAILABLE|AGE|
|cluster-local-gateway|1/1|1|1|23d|
|grafana|1/1|1|1|23d|
|istio-citadel|1/1|1|1|23d|
|istio-egressgateway|1/1|1|1|23d|
|istio-galley|1/1|1|1|23d|
|istio-ingressgateway|1/1|1|1|23d|
|istio-pilot|1/1|1|1|23d|
|istio-policy|1/1|1|1|23d|
|istio-sidecar-injector|1/1|1|1|23d|
|istio-telemetry|1/1|1|1|23d|
|istio-tracing|1/1|1|1|23d|
|kfserving-ingressgateway|1/1|1|1|23d|
|kiali|1/1|1|1|23d|
|prometheus|1/1|1|1|23d|
 

This was installed using kfctl_istio_dex_v1.0.1
||||||
|---|---|---|---|---|
|NAME|READY|UP-TO-DATE|AVAILABLE|AGE|
|cluster-local-gateway|1/1|1|1|5d1h|
|istio-citadel|1/1|1|1|5d1h|
|istio-galley|1/1|1|1|5d1h|
|istio-ingressgateway|1/1|1|1|5d1h|
|istio-pilot|1/1|1|1|5d1h|
|istio-policy|1/1|1|1|5d1h|
|istio-sidecar-injector|1/1|1|1|5d1h|
|istio-telemetry|1/1|1|1|5d1h|
|prometheus|1/1|1|1|5d1h|

Is there a reason why there are missing deployments?

**Comment by jtfogarty** [comment]
@jlewi from yesterday's meeting, it sounds like it was intentional on taking out kfserving-ingressgateway.  Maybe the others as well.

**Comment by jlewi** [comment]
@yanniszark @johnugeorge do you know the answer?

**Comment by yanniszark** [comment]
The kfctl_istio config uses Istio 1.6.1 manifests.
The kfctl_istio_dex config uses Istio 1.3.1 manifests.
Our 1.3.1 manifests no longer include the tracing components (istio-tracing, kiali, grafana, jaeger, etc.)

cc @krishnadurai who ported the Istio 1.3.1 manifests.
I don't have a strong preference either way (minimal install vs bells n whistles).

**Comment by vincentarthur** [comment]
Hi @yanniszark @jlewi , as you guys discussed on other thread related to KFP multi-user [https://github.com/kubeflow/pipelines/issues/3645](url), you did mentioned 1.1.0-alpha1.

As we are also trying to use Dex for kubflow, may i know if kfctl_istio_dex would upgrade to istio 1.6 ? or keep using 1.3.1. As we think tracing components is very useful.

Thanks.

**Comment by jlewi** [comment]
That's a question for @yanniszark and the other owners of `kfctl_istio_dex`.
