### ISSUE TITLE
Notebook with EBS volume - creation failure

### ISSUE THREAD

**Issue by alanhughes** [kubeflow/kubeflow#4962]
/kind bug

**What steps did you take and what happened:**
We run an EKS cluster with workers in multiple availability zones. If you try and create a notebook server with extra data volumes, in mode "ReadWriteOnce", there is no guarantee that both EBS volumes will be created in the same AWS availability zone. If they are created in different zones, the notebook fails to start, since no worker node can attach to two volumes in different AZs.

**What did you expect to happen:**
When multiple volumes are specified, they should get created in the same AWS region 

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: Using 1.0.1 manifests, bottom left of UI says `dev_local`
- kfctl version: (use `kfctl version`): kfctl v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): Client Version: v1.17.4
Server Version: v1.15.10-eks-bac369
- OS (e.g. from `/etc/os-release`): MacOS Catalina 10.15.4

**Comment by alanhughes** [comment]
workaround at the moment is to pre-create a storage class per zone with:
```
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - <availability-zone>
``` 
as per https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies

and then pre-create all PVCs that we will require, distributing them as required between `StorageClass`es, but requiring that any volumes that will be attached to the same notebook are in the same `StorageClass`

**Comment by Jeffwan** [comment]
This is a common issue. There's no guarantee PV are always created in the right AZ. 
There's some community solution on this. 
https://kubernetes.io/blog/2018/10/11/topology-aware-volume-provisioning-in-kubernetes/

I think more elegant solution is create a topolocy-aware storage class and set it as default storage class for Jupyter controller.  

This would be a lightweight wrapper of default storage class

**Comment by Jeffwan** [comment]
/assign @Jeffwan 

Can you help verify if this work for you case?

**Comment by jbottum** [comment]
@Jeffwan Hi Jeff, we are getting close to the Kubeflow 1.1 cut date.   This seems like an important fix but I think there is work on AWS that is needed.  I have moved this to a P2.
