### ISSUE TITLE
MiniKF dashboard external IP address not connecting

### ISSUE THREAD

**Issue by marwanfahmi** [kubeflow/kubeflow#4963]
Hi,

I have a MiniKF deployment on GCP and the VM instance is up and running with both HTTP and HTTPS traffic allowed in the VM settings, however, when I navigate to the external IP address to access the Kubeflow dashboard I get Unable to connect message. What could possibly cause this?

Many Thanks,

**Comment by yanniszark** [comment]
Hi @marwanfahmi!
When the MiniKF VM gets provisioned, it needs some time for everything to come up.
Until then, you get the error you described.

Please check out the instructions about MiniKF on GCP in the kubeflow docs: https://www.kubeflow.org/docs/started/workstation/minikf-gcp/
You will see how to SSH into the VM and follow the on-screen instructions.

Can you confirm if this solves you issue?

**Comment by marwanfahmi** [comment]
Hi @yanniszark - This to confirm that this resolved my issue. I got confused because I was able to ssh the machine but not access the UI. Thanks a lot!
