### ISSUE TITLE
exposing host docker in jupyterlab custom container

### ISSUE THREAD

**Issue by miramar-labs** [kubeflow/kubeflow#4966]
I created a custom container with JupyterLab and a bunch of other things in it .. including docker CE ... and added it as a notebook server .. works great but I'd like to do my docker build's from the jupyterLab terminal window .. and so i'm wondering if there is a way to customize the way kubeflow launches the container .. i'd like to add '-v /var/run/docker.sock:/var/run/docker.sock' to the docker run command .. any ideas how I can do that?

**Comment by jlewi** [comment]
You can edit the notebook resource using `kubectl get/kubectl apply` and modify the pod template spec to include additional volume mounts.
