### ISSUE TITLE
Manage contributor add failure - rolebinding unique name issue

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/kubeflow#4970]
/kind bug

**What steps did you take and what happened:**
Manage contributor screen. Adding a contributor creates a role binding / service role binding with name including userID's first character by ignoring the digits and not able to add other users with similar numbers.
our Org uses UserIDs as a1234@xx.org, a2345@xx.org. 

![image](https://user-images.githubusercontent.com/8292387/79807750-b2317800-8320-11ea-8939-a32d2bf33618.png)
![image](https://user-images.githubusercontent.com/8292387/79807788-c2495780-8320-11ea-9654-67fdbca24cca.png)

**What did you expect to happen:**
rolebinding and service role bindings names to use digits too

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):1.0.2
- kfctl version: (use `kfctl version`): 
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yanniszark** [comment]
This is the code that decides the name of RoleBindings:
https://github.com/kubeflow/kubeflow/blob/8f8e348bc8df0b65f09c3082b1f559fff20d62e6/components/access-management/kfam/bindings.go#L56-L72
We should probably amend that logic.
I'm not sure what priority to put on this.
We should decide our plans for the contributor UI first, because if we are moving towards a GitOps approach, the contributor UI becomes less valuable.
On the other hand, this should be an easy fix if we can decide on what naming rule to use.

/area multiuser
cc @jlewi @kunmingg

**Comment by lalithvaka** [comment]
Thank you @yanniszark , I was able to fix this code(with my limited go knowledge) to support numbers in the email address. This changes  email address to i397401@zq.msds.kp.org to i397401-zq-msds-kp-org which is being used in the role binding names.
```
//getBindingName returns bindingName, which is combination of user kind, username, RoleRef kind, RoleRef name.
func getBindingName(binding *Binding) (string, error) {
	// Only keep lower case letters, replace other with -
	reg, err := regexp.Compile("[^a-z0-9]+")
	if err != nil {
		return "", err
	}
	nameRaw := strings.ToLower(
		strings.Join([]string{
			binding.User.Kind,
			url.QueryEscape(reg.ReplaceAllString(binding.User.Name, "-")),
			binding.RoleRef.Kind,
			binding.RoleRef.Name,
		}, "-"),
	)

	return reg.ReplaceAllString(nameRaw, "-"), nil
}
```

**Comment by lalithvaka** [comment]
@yanniszark submitted a pull request - https://github.com/kubeflow/kubeflow/pull/4979

/area multiuser
cc @jlewi @kunmingg
