### ISSUE TITLE
Dashboard deployed on eks does not show manage contributors in navigation

### ISSUE THREAD

**Issue by asahnovskiy** [kubeflow/kubeflow#4975]
/kind bug

**What steps did you take and what happened:**
I deployed kubeflow v1.0.2 on existed EKS cluster using https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml

**What did you expect to happen:**
I except the "Manage Contributers" to show up.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: I assume v1.0.2 but I see **build version dev_local** at the bottom left corner of the Kubeflow dashboard 
- kfctl version: kfctl_v1.0.2-0-ga476281
- Kubernetes platform: EKS 1.15.10
- Kubernetes version:1.15.13
- OS (e.g. from `/etc/os-release`):

**Comment by helkhalfi** [comment]
👍

**Comment by Jeffwan** [comment]
@asahnovskiy 
kfctl_k8s_istio.v1.0.2.yaml manifest doesn't support multi-user, that's the reason you don't see it.

Feel free to use following manifest based on your needs. 
- kfctl_aws_cognito.v1.0.2.yaml
- kfctl_istio_dex.v1.0.2.yaml

**Comment by asahnovskiy** [comment]
I got it. Thanks.
