### ISSUE TITLE
Cannot access notebook servers: Sorry, /jupyter/ is not a valid page

### ISSUE THREAD

**Issue by fhingerl** [kubeflow/kubeflow#4976]
/kind bug

**What steps did you take and what happened:**
I installed Kubeflow (v1.0 on Kubernetes 1.14) on AWS EKS and all components worked fine. Since the installation did not come with KFServing / KNative,  I installed KNative following these instructions: https://triggermesh.com/2019/04/installing-knative-on-amazon-web-services-eks/

After performing above steps, I cannot access my notebook servers and pipelines through the Kubeflow UI anymore. The notebooks servers are still running though (tested with kubectl -n anonymous get notebooks). "Home", "Artifact Store" are all still accessible through the web UI.

**What did you expect to happen:**
Notebook servers and pipelines should be accessible through Kubeflow UI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.0 (dev_local)
- kfctl version: (use `kfctl version`): v1.0.1-0-gf3edb9b
- Kubernetes platform: AWS EKS
- Kubernetes version: (use `kubectl version`): v1.17.4
- OS (e.g. from `/etc/os-release`): (local machine) macOS High Sierra, v10.13.6

**Comment by sheep94lion** [comment]
How do you access the Kubeflow UI, are you using port-forwarding?
