### ISSUE TITLE
Not able to select the namespace in Jupyter notebook.

### ISSUE THREAD

**Issue by jithinvalsalan** [kubeflow/kubeflow#4980]
/kind bug
![Kubeflow_Jupyternotebook](https://user-images.githubusercontent.com/32053559/80343829-39806d80-8884-11ea-84f0-d3ff3ae42116.JPG)

**What steps did you take and what happened:**
Deployed kubeflow on existing kubernetes version 1.14 using Multi-user, auth-enabled Kubeflow with kfctl_istio_dex. After successful deployment of kubeflow and profile registration, I was trying to access jupyter notebook server, but it is not allowing to select the namespace. 

**What did you expect to happen:**
I should be able to create Jupyter notebook server and run some sample pipelines.

**Anything else you would like to add:**
I am using kfctl_istio_dex.v1.0.2.yaml file and not changed anything in this file.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`) : Existing Kubernetes cluster(On prem, 3 node cluster)
- Kubernetes version: (use `kubectl version`): v1.14.10
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by jithinvalsalan** [comment]
oss@master:~$ kubectl logs  centraldashboard-869f55ddbd-rsrw9 -n kubeflow

> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve


> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
Unable to fetch Application information: { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'applications.app.k8s.io is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "applications" in API group "app.k8s.io" in the namespace "kubeflow"',
  reason: 'Forbidden',
  details: { group: 'app.k8s.io', kind: 'applications' },
  code: 403 }
Unable to fetch Nodes { kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message:
   'nodes is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" cannot list resource "nodes" in API group "" at the cluster scope',
  reason: 'Forbidden',
  details: { kind: 'nodes' },
  code: 403 }
"other" is not a supported platform for Metrics
Using Profiles service at http://profiles-kfam.kubeflow:8081/kfam
Server listening on port http://localhost:8082 (in production mode)
oss@master:~$

**Comment by jbottum** [comment]
@vkoukis Hi Vangelis, could you please have someone look a this for our friends at Redhat ?

**Comment by shawnzhu** [comment]
I can not reproduce this defect by deploying `kfctl_istio_dex.v1.0.2.yaml`. It works for me that it populates the current namespace value into the **read-only** (i.e., disallow user to input) input box labled `namespace`. Underneath it comes from the API response of `/api/workgroup/env-info`.

> ```
> Unable to fetch Application information: { kind: 'Status',
> apiVersion: 'v1',
> metadata: {},
> status: 'Failure',
> message:
> 'applications.app.k8s.io is forbidden: User "system:serviceaccount:kubeflow:centraldashboard" > cannot list resource "applications" in API group "app.k8s.io" in the namespace "kubeflow"',
> reason: 'Forbidden',
> ```

This is unexpected since the role `centraldashboard` is able to list resource `application`:

```
$ kubectl describe role -n kubeflow centraldashboard
Name:                      centraldashboard
Labels:                    app=centraldashboard
                           kustomize.component=centraldashboard
Annotations:               PolicyRule:
  Resources                Non-Resource URLs  Resource Names  Verbs
  ---------                -----------------  --------------  -----
  applications             []                 []              [get list watch]
  pods/exec                []                 []              [get list watch]
  pods/log                 []                 []              [get list watch]
  pods                     []                 []              [get list watch]
  applications.app.k8s.io  []                 []              [get list watch]
  pods.app.k8s.io/exec     []                 []              [get list watch]
  pods.app.k8s.io/log      []                 []              [get list watch]
  pods.app.k8s.io          []                 []              [get list watch]
  secrets                  []                 []              [get]
$ kubectl describe rolebinding -n kubeflow centraldashboard
Name:         centraldashboard
Labels:       app=centraldashboard
              kustomize.component=centraldashboard
Annotations:  Role:
  Kind:       Role
  Name:       centraldashboard
Subjects:
  Kind            Name              Namespace
  ----            ----              ---------
  ServiceAccount  centraldashboard  kubeflow
```

See https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base/role.yaml#L7-L15

@jithinvalsalan it would be helpful if you can confirm the role `centraldashboard` and rolebinding `centraldashboard` have been applied successfully.

**Comment by unagaraju88** [comment]
Any update on this bug? I am also facing same issue.

**Comment by zengqingfu1442** [comment]
I also encoutered this same issue. 
k8s: 1.21.1
kubeflow manifests: 1.3.1
