### ISSUE TITLE
Support marking PodDefaults as mutually exclusive

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/kubeflow#4981]
/kind feature

**Why you need this feature:**
We have PodDefaults for the notebook spawner that set an IAM role annotation. If a user selects both by accident, it causes the notebook to become unschedulable due to both PodDefaults trying to set the same annotation.

**Describe the solution you'd like:**
There should be an annotation that groups PodDefaults. The form validation in the UI should prevent selecting to PodDefaults with the same group. Optionally the options could be displayed as option or checkbox elements.

**Anything else you would like to add:**
Alternatively we could try to merge the PodDefaults and check for conflicts to avoid having to add an annotation. But there might be non-conflicting options that users still want to make as mutually exclusive.

**Comment by Jeffwan** [comment]
@discordianfish Do you use IRSA or Kube2IAM?  What not attach role to `default-editor` directly?
