### ISSUE TITLE
Support dynamical updates to the jupyter-web-app's image list

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/kubeflow#4982]
/kind feature

**Why you need this feature:**
I want to automatically add new images we build to jupyter-web-app's image dropdown menu.

Currently this is configured in the jupyter-web-app-config config map. The only way to update this in a way that doesn't break on updates is by using a custom overlay but that's not suitable for dynamic/automated updates.

**Describe the solution you'd like:**
I'm not sure that stuffing all possible configurations in a CRD is the best way, but it's what is done so far in the webapp and what istio and friends are doing, so maybe the way to go would be to create a kubeflow.org/image and use that to populate the image list in the web UI.

**Anything else you would like to add:**
I want to judge interest first and make sure there isn't anyone else working on this. If people feel that creating a CRD is the right way, I can create a proposal for it.

**Comment by Jeffwan** [comment]
@discordianfish Is it ok to actively fetch configmap to check updates? I feel building CRD is kind of heavy

**Comment by discordianfish** [comment]
I think a CRD might be a good long term solution but with so many things in flux, I agree that this probably isn't the best way for now. Especially since I probably won't have resources to work on this after all..

Instead, now with https://github.com/kubeflow/kfctl/issues/304, I'd probably use an overlay to either remove the configmap or add the images when applying the kustomize manifests. So I think it makes sense to close this issue for now.
