### ISSUE TITLE
Multiple Teams & Multi-User Kubeflow Support

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/kubeflow#4983]
/kind feature

**Why you need this feature:**
In our scenario we have limited IP space, and have multiple teams (Say over 50+) who would like to use Kubeflow, each team is composed of 5-10 users. We already have a Kubernetes cluster and would like to set up Kubeflow on a namespace per team basis. 

**Describe the solution you'd like:**
A way to isolate the Kubeflow components behind an ingress controller in such a way that we can access a Kubeflow instance on a namespace per team say /team-xyz/kubeflow-ui

More details:

- Each team has its own Dashboard, or isolated view of the Dashboard
- Pipelines and KFServing are also isolated to the namespace for that particular team

**Anything else you would like to add:**
I'm looking to contribute to the solution if no one can provide it, or if the feature is anti-pattern it would be beneficial to know how could we still incorporate it without preventing future upgrades. 

Any information on how to get started would also be appreciated it.

**Comment by jlewi** [comment]
@maganaluis Kubeflow already tries to support this scenario but letting each team consume Kubeflow in their own namespace.

The components that are in the kubeflow namespace (e.g. the controllers and UI) run as multi-tenant services and implement appropriate auth checks.

Not all Kubeflow applications support multi-user yet (pipelines being one of the big ones).

Can you describe what features are missing for your use case?

**Comment by maganaluis** [comment]
@jlewi Thank you for the reply, pipelines would the one we are looking at as well as KFServing. I still have to do more research on this, although I know there is people working on pipelines https://github.com/kubeflow/pipelines/issues/1223 and as of now there is support to add contributors to a specific profile/namespace, which we are looking to leverage.

I would be interested in installing from master, let me know if there is already instructions for it.

**Comment by jlewi** [comment]
You might want to track either kubeflow/pipelines#1223 and kubeflow/pipelines#3645 to see when the multiuser changes are available on master.

@animeshsingh @yuzisun @ellis-bigelow what is the status of multiuser support for KFServing?

**Comment by ellis-bigelow** [comment]
I'm not entirely familiar with this. Does this effectively mean deploying the operator to a single namespace?

**Comment by yanniszark** [comment]
I believe KFServing is based on K8s CRDs, so namespace isolation is already provided by the K8s API Server.

**Comment by jlewi** [comment]
@yanniszark @ellis-bigelow what about controlling who can send requests to specific models? I would expect that's using ISTIO RBAC. Does KFServing let users control who can access models with ISTIO RBAC?

**Comment by ellis-bigelow** [comment]
We creates deterministically named virtual services under the hood for routing. Users can apply Istio RBAC rules to those virtual services to control access.
