### ISSUE TITLE
MiniKF install error

### ISSUE THREAD

**Issue by jkim711** [kubeflow/kubeflow#4986]
/kind bug
MiniKF install error
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Downloaded MiniKF using Vagrant 
Vagrant up was successful
http://10.10.10.10 didn't show terminal so I connect through 'vagrant ssh'
entered the command 'minikf' to initiate the installation.
It got stuck in the following state
                                                                                                            ┌────────Minikube + Kubeflow + Rok = MiniKF──────────┐                                                               │ Waiting for PostgreSQL...                          │                                                               │ 0/1 pods ready

**What did you expect to happen:**
I expected the command minikf to finish the instllation

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Window 10
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jbottum** [comment]
@jkim711 @cspavlou Hi Jkim711, did you try to restart your implementation ?   Is this still open?

**Comment by jkim711** [comment]
Yes. I tried several times. I should try again to connect to 10.10.10.10 using chrome instead of IE.
I am behind a corporate firewall using a proxy. I did set the Vagrant proxy environment variables.
Are there potentially other public network connections made during the installation?

**Comment by jbottum** [comment]
@jkim711 Hi Jkim711, this sounds like a firewall issue.    Can you potentially try in a configuration without the firewall (or potentially MiniKF in the GCP marketplace) ?

**Comment by jkim711** [comment]
Hi entered in proxy settings through the shell to get it to work. 

echo 'export http_proxy="http://xx.xx.xx.xx:8080"' >> ~/.bash_profile 
echo 'export https_proxy="http://xx.xx.xx.xx:8080"' >> ~/.bash_profile 
export http_proxy=http://xx.xx.xx.xx:8080 
export https_proxy=http://xx.xx.xx.xx:8080 

sudo su 
echo 'Acquire::http::proxy "http://xx.xx.xx.xx:8080";' >> /etc/apt/apt.conf 
echo 'Acquire::https::proxy "http://xx.xx.xx.xx:8080";' >> /etc/apt/apt.conf 
exit 
echo 'proxy=http://xx.xx.xx.xx:8080' >> ~/.curlrc 
sudo mkdir /usr/share/ca-certificates/extra 
sudo cp ~/company.crt /usr/share/ca-certificates/extra 
sudo dpkg-reconfigure ca-certificates 
sudo su 
cat company.crt >> /etc/ssl/certs/ca-certificates.crt 
exit

**Comment by cspavlou** [comment]
Hi @jkim711 ,

MiniKF should work in an air-gapped environment. It turns out that there was a minor bug that made `kubelet` try to pull an already pre-pulled image. Will fix that in an upcoming release. Regarding proxy one could use the `vagrant-proxyconf` plugin and set `Vagrantfile` accordingly after vagrant init.

**Comment by afilcheff** [comment]
Hi,
I have a similar issue,  I get stuck at 67% at provisioning minikube and then it errors with the following message:
![Capture1](https://user-images.githubusercontent.com/54940372/82879848-37263780-9f46-11ea-9f96-a3cdec14709a.PNG)

I tried finding the provision.log so I can upload it here, but I cannot figure out how to locate it.
Here is also a picture of my vm config
![Capture2](https://user-images.githubusercontent.com/54940372/82879986-705ea780-9f46-11ea-869f-da328a6b8199.PNG)

@cspavlou could this be relevant to the issue you mentioned?

**Comment by monil536** [comment]
I am facing similar issue. Does any one have any solution that can work behind the proxy ?

![image](https://user-images.githubusercontent.com/23745458/86034914-7514f080-ba09-11ea-97b9-f903ac9916a1.png)

**Comment by gudipudipradeep** [comment]
@afilcheff  I am also getting same issue.  Please help on it.
build/bdist.linux-x86_64/egg/rok_common/cmdutils.py:942

**Comment by jhkcia** [comment]
I face the same problem like @monil536 when I try to access minikube on 10.10.10.10.
Is there exists any solution for this problem?
