### ISSUE TITLE
OAuth Authorized redirect URIs

### ISSUE THREAD

**Issue by shravspy** [kubeflow/kubeflow#4987]
When I try to edit newly created OAuth credential and click the pencil icon. I go to Authorized redirect URIs box and update it with link in document with my client id and press return key, I do not see  the URI  as confirmed item under Authorized redirect URIs. (The URI should no longer be editable.) URI is still in editable phase. Hence I sm not able to redirect to  Kubeflow dashboard once my project link is created

**Comment by yanniszark** [comment]
/remove-area centraldashboard
/area auth

@shravspy I'm confused about where all of this happens.

> When I try to edit newly created OAuth credential and click the pencil icon. I go to Authorized redirect URIs box and update it with link in document with my client id and press return key, I do not see the URI as confirmed item under Authorized redirect URIs. 

This doesn't sound like a Kubeflow UI, so it seems that some context is missing.
Could you provide more information/context about what you are trying to do and what is failing?

**Comment by DimaKav** [comment]
In the setting up Oauth for Cloud IAP

The uri will not go into the "confirmed" as stated in #7 https://www.kubeflow.org/docs/gke/deploy/oauth-setup/

![image](https://user-images.githubusercontent.com/8162980/91493392-1aaed980-e86c-11ea-9cc3-e4c87c0e416e.png)
