### ISSUE TITLE
Can we support k8s 1.16？

### ISSUE THREAD

**Issue by denkensk** [kubeflow/kubeflow#4992]
/kind question

**Question:**
I find it says that `Kubeflow does not work on Kubernetes 1.16.` in the doc https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements.

will you be supporting k8s 1.16 anytime soon?

**Comment by denkensk** [comment]
\cc @openrory @saschagrunert!

**Comment by saschagrunert** [comment]
I'm working now on 1.16 for weeks and the only issues I noticed so far are related to container runtimes and custom configuration. I think we should state that it supports 1.16. We could also verify that it works with 1.18 because that's what I would expect.

**Comment by denkensk** [comment]
Thanks for your response. Can we update the doc in `https://github.com/kubeflow/website/blob/master/content/en/docs/started/k8s/overview.md` to state it compatible? @saschagrunert

**Comment by saschagrunert** [comment]
Here we go: https://github.com/kubeflow/website/pull/1933

**Comment by jlewi** [comment]
Duplicate of kubeflow/manifests#375
