### ISSUE TITLE
Install Kubeflow on Existing GKE Cluster

### ISSUE THREAD

**Issue by TravRan** [kubeflow/kubeflow#4995]
Is there a way to install Kubeflow on a GKE cluster I deployed via KCC? In researching I see you can use KfGcpPlugin to specify some of the DM configs. It would be nice to have an option to say skip the GKE deployment and reference an existing GKE deployment.

**Comment by jlewi** [comment]
This is not well supported today. If you have an existing GKE cluster you can follow the instructions for installing on an existing Kubernetes cluster to deploy Kubefow on to it.

The downside of that approach is that you won't create any of the GCP resources you need.

The blueprints which are currently WIP should be more composable.
https://github.com/kubeflow/gcp-blueprints

With the blueprint you could just remove the KCC resource to create the GKE cluster but still create all the other GCP resources needed.

The blueprint isn't deploying all the Kubeflow applications yet though. In particular its still missing KFP and KFServing.

**Comment by TravRan** [comment]
I'm trying to remove the PlugIns from kfdef, which includes KfGcpPlugin. After doing that and creating the IP address, IAM Bindings, cluster, and storage; below is the error I'm seeing when running kfctl. I'm wondering if this error has anything do with what I did or not. I see a lot of people have seen this problem recently.

WARN[0291] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout209198072": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"

**Comment by jlewi** [comment]
This looks like kubeflow/manifests#1121
Just try rerunning apply after waiting a biit to give certmanager time to startup.

**Comment by TravRan** [comment]
I figured out the issue with cert-manager. Since I'm using a private GKE cluster I had to open up a firewall. My deployment completed and I was able to get almost everything working. Just one of the backend services for Envoy-Ingress is unhealthy. I'm wondering if the issues with the pods in the screenshot below is why.

![image](https://user-images.githubusercontent.com/60673895/80988369-07798900-8df9-11ea-8c5d-4e9226de0e9e.png)

**Comment by jlewi** [comment]
No the pipelines viewer issue would likely not cause the envoy-ingress backend to be unhealthy.

You meant want to check out the troubleshooting guide.
https://www.kubeflow.org/docs/gke/troubleshooting-gke/

**Comment by TravRan** [comment]
I was able to get the backend healthy by updating the health check to actually use the status-port instead of the http2 port. Onto my next issue. Now when I log into kubeflow it give me this error. Origin authentication failed. I'm thinking it has to do with IAP. I'm seeing the errors below in backend-updater-0 iap-enabler-XX. I'm also thinking this may just be due to a version mismatch. What is the supported gke version for v1.0.2? I'm using 1.15.11-gke.11 currently.

![image](https://user-images.githubusercontent.com/60673895/81009085-94343f00-8e19-11ea-9230-dbbab24e1ff7.png)

**Comment by jlewi** [comment]
IAP backend origin authentication usually means the JWT policy validating the IAP token isn't valid or unset.

You can try kicking the backend updater pod
https://github.com/kubeflow/manifests/blob/825d3eae229560398d76b71b50c2e6ab82828d22/gcp/iap-ingress/base/stateful-set.yaml

The JWT policy is based on the backend id which could change if your ingress gets recreated if you force that pod to restart it should update it.

**Comment by TravRan** [comment]
I was able to get everything working! After digging into the code a little I found out removing the GCP plugin altogether was a bad idea. Workload Identity = true actually triggers a lot more than just SA creation. Creating the KSA's and binding are a couple of things as well as much more. Instead what I did was keep the plugin stuff in the kfdef. DM just acquired the objects I deployed. This allows me to create everything in KCC, including the IP address, which allows me to pre-configure the Cloud Endpoint deployment. After kfctl completes I just delete the Deployment manager deployments and preserve the resources. KCC continues to do it's thing the entire time. If you want, I can share my kcc kubeflow deployment base I'm using with KCC.

**Comment by jlewi** [comment]
@TravRan glad its working. It would be great to get your input on Kubeflow's KCC configs. They are currently stored [here](https://github.com/kubeflow/manifests/tree/master/gcp/v2/cnrm).

The complete blueprint for deploying with KCC is here
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow

Any feedback would be greatly appreciated.
