### ISSUE TITLE
kubeflow cannot connect to a notebook server (takes forever)

### ISSUE THREAD

**Issue by lvbaouu** [kubeflow/kubeflow#4996]
I have been following this blog (https://codelabs.developers.google.com/codelabs/cloud-kubeflow-minikf-kale/#3) to try to set up a pipeline from kubeflow. What should I do other than waiting?

But it has been over an hour to set to connect to a notebook server (please see attached screenshow):

<img width="970" alt="Screen Shot 2020-05-02 at 6 59 32 PM" src="https://user-images.githubusercontent.com/43765777/80894256-7c3cae00-8ca7-11ea-8669-992c3f1fbaf8.png">

**Comment by jlewi** [comment]
@lvbaouu Can you check the status of the notebook resource, statefulset, and pods?  

Chances are the pod for your notebook is stuck in a pending state for some reason. If you use `kubectl` to look at the pod it will probably provide information on why the pod is pending.

**Comment by lvbaouu** [comment]
when i tried the same process on another computer. it got connected very fast...
