### ISSUE TITLE
Remotely connect to the Kubeflow Dashboard UI via ssh

### ISSUE THREAD

**Issue by kaikun213** [kubeflow/kubeflow#4997]
/kind question

**Question:**
I setup microk8s with dns, dashboard, storage and kubeflow enabled on a local workstation.
I am trying to connect to that server and access the Kubeflow Dashboard UI remotely via ssh.

I was able to access a jupyter notebook via ssh tunneling:
```
ssh -N -L localhost:8888:localhost:8080 user@remote-address
```
but it is not able to access the ambassador xip.io domain.

I tried to use port forwarding to publish the sites on localhost. 
In the documentation (https://www.kubeflow.org/docs/components/central-dash/overview/) it describes the command `kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80`.
However, the istio-system is not enabled by default. When I enabled it I ran into similar problems as described here: https://github.com/ubuntu/microk8s/issues/1128 by accessing the gateway.
I am able to do port forwarding on the remote machine to host the individual dashboard sites (e.g. pipelines/home) on localhost:8080 via:

```
kubectl port-forward -n kubeflow svc/ambassador 8080:80
```

But I am not able to access it then via remote ssh tunneling.

Is there an easy way to access the dashboard remotely via ssh?

**Comment by marcoleewow** [comment]
@kaikun213 were you able to figure a way to access the dashboard UI via ssh? I encounter the same problem too

**Comment by realsushi-official** [comment]
Here is a basic solution for port forwarding a microk8s addon like Dashboard
**Remote side**
- `microk8s kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443`
**Client side**
- `ssh -L 10443:localhost:10443 $USER@$IP`
- `curl https:localhost:10443`
Tested with **Firefox 89** by bypassing the missing ssl certificate. (Didn't work with chrome even when removing security)
