### ISSUE TITLE
Multiple Users/Google-Group as Cluster Admin

### ISSUE THREAD

**Issue by knave07** [kubeflow/kubeflow#4998]
/kind question

**Question:**
We have multiple users who would like to try Kubeflow and have spun up a new Kubernetes cluster for Kubeflow. We want this cluster to be managed by a team that will be the cluster-admin as well. 
So Is it possible to add multiple-users as cluster-admin?  or a google group as a cluster-admin? or you guys have any plan for adding this feature.
I guess in the current scenario the user who has deployed Kubeflow is shown as the cluster-admin.

I want something like this:
Account info(Cluster Admin)
user_1@xyz.com
user_2@xyz.com
google_group@xyz.com

**Comment by yanniszark** [comment]
/area multiuser
@knave07 Kubeflow currently doesn't support groups in its web apps.
See issue: https://github.com/kubeflow/kubeflow/issues/4188
However you can add permissions for each member separately to achieve the same effect.

For adding a member as cluster-admin, you can do that by creating a ClusterRoleBinding with `kubectl`.
Does this answer your question?

**Comment by knave07** [comment]
Thanks. 
After adding user to ClusterRoleBinding(default admin) with kubectl, the web app still shows the same old cluster admin.

**Comment by yanniszark** [comment]
@knave07 I understand that your issue was solved then?

**Comment by knave07** [comment]
> @knave07 I understand that your issue was solved then?

Yes. I could add cluster admins manually using kubectl.

**Comment by yanniszark** [comment]
Great, closing then...
/close
