### ISSUE TITLE
KubeFlow 

### ISSUE THREAD

**Issue by hassanzadeh** [kubeflow/kubeflow#5002]
Hello Guys,
I tried launched a KubeFlow cluster on GCP using CLI. I used the config from https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml .
The first time I deployed everything was working, and I could access the dashboard from https://<KF_NAME>.endpoints.<project-id>.cloud.goog . However, after I deleted the cluster, and created again I could not access the dashboard again. I think it has to do with the cert-manager namespace. During the deployment, I get the following warnings multiple times:

WARN[0079] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout674901976": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
WARN[0085] Will retry in 12 seconds.                     filename="kustomize/kustomize.go:203"

Eventually, when the cluster is built the cert-manager namespaces shows "Terminating". I tried to delete the cluster (kfctl delete -f ...) and recreate again, but samething happens. What is wrong here?

Update: I tried to delete all I could and relaunch the cluster, now the cert-manager shows "Active" however, the dashboard is still not accessible. Here is the list of services (none has external-ip, not sure if that should be the case):

admission-webhook-service                      ClusterIP   10.11.241.77    <none>        443/TCP             10m
application-controller-service                 ClusterIP   10.11.245.48    <none>        443/TCP             11m
argo-ui                                        NodePort    10.11.255.93    <none>        80:31295/TCP        10m
centraldashboard                               ClusterIP   10.11.251.139   <none>        80/TCP              10m
cloud-endpoints-controller                     ClusterIP   10.11.254.169   <none>        80/TCP              9m47s
jupyter-web-app-service                        ClusterIP   10.11.241.117   <none>        80/TCP              10m
katib-controller                               ClusterIP   10.11.247.174   <none>        443/TCP,8080/TCP    9m55s
katib-db-manager                               ClusterIP   10.11.241.184   <none>        6789/TCP            9m55s
katib-mysql                                    ClusterIP   10.11.253.31    <none>        3306/TCP            9m55s
katib-ui                                       ClusterIP   10.11.248.248   <none>        80/TCP              9m54s
kfserving-controller-manager-metrics-service   ClusterIP   10.11.243.38    <none>        8443/TCP            9m57s
kfserving-controller-manager-service           ClusterIP   10.11.241.55    <none>        443/TCP             9m57s
kfserving-webhook-server-service               ClusterIP   10.11.240.27    <none>        443/TCP             8m44s
metadata-db                                    ClusterIP   10.11.243.75    <none>        3306/TCP            10m
metadata-envoy-service                         ClusterIP   10.11.242.44    <none>        9090/TCP            10m
metadata-grpc-service                          ClusterIP   10.11.248.206   <none>        8080/TCP            10m
metadata-service                               ClusterIP   10.11.240.212   <none>        8080/TCP            10m
metadata-ui                                    ClusterIP   10.11.248.158   <none>        80/TCP              10m
minio-service                                  ClusterIP   10.11.245.51    <none>        9000/TCP            9m53s
ml-pipeline                                    ClusterIP   10.11.253.70    <none>        8888/TCP,8887/TCP   9m53s
ml-pipeline-ml-pipeline-visualizationserver    ClusterIP   10.11.254.19    <none>        8888/TCP            9m48s
ml-pipeline-tensorboard-ui                     ClusterIP   10.11.246.133   <none>        80/TCP              9m50s
ml-pipeline-ui                                 ClusterIP   10.11.244.157   <none>        80/TCP              9m50s
mysql                                          ClusterIP   10.11.255.36    <none>        3306/TCP            9m52s
notebook-controller-service                    ClusterIP   10.11.248.100   <none>        443/TCP             10m
profiles-kfam                                  ClusterIP   10.11.248.29    <none>        8081/TCP            9m47s
pytorch-operator                               ClusterIP   10.11.249.126   <none>        8443/TCP            10m
seldon-webhook-service                         ClusterIP   10.11.249.185   <none>        443/TCP             9m40s
tensorboard                                    ClusterIP   10.11.244.112   <none>        9000/TCP            9m56s
tf-job-operator                                ClusterIP   10.11.240.209   <none>        8443/TCP            9m56s

Env:
Kfctl version: kfctl v1.0.2-0-ga476281
kubernetese version: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.37", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-10T21:17:01Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
OS: Ubuntu 18.04

**Comment by dale88** [comment]
mark , I have the same issues.
