### ISSUE TITLE
updating dex-config.yaml with new users based on the instructions kills the server

### ISSUE THREAD

**Issue by yosit** [kubeflow/kubeflow#5005]
/kind bug

**What steps did you take and what happened:**
following the instructions from here: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#add-static-users-for-basic-auth

Once you update the dex-config.yaml and restart deployment the cluster is unrecoverable. even when deploying the original dex-config.yaml

The logs say:
error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: no password hash provided

**What did you expect to happen:**
dex to restart and recognize the new users.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
- kfctl version: 0.18.0
- Kubernetes platform: eks
- Kubernetes version: 1.15.11
- OS (e.g. from `/etc/os-release`):

**Comment by yanniszark** [comment]
Hi @yosit!
I expect that you have an incorrect Dex config and the error message is indicative of that:
```
error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: no password hash provided
```
Can you provide your configuration here?

/remove-priority p1
/priority p2

**Comment by yosit** [comment]
@yanniszark Looking at my last version of it I see two hash fields where it should have only one - will try to reproduce and report back.

**Comment by yosit** [comment]
This is not an issue - I managed to follow the instructions, sorry for the hassle.
