### ISSUE TITLE
Release versions discrepancy in the UI after upgrading from 0.6 to 1.0.2

### ISSUE THREAD

**Issue by yassine-labidi** [kubeflow/kubeflow#5007]
/kind bug

**What steps did you take and what happened:**
Upgrade kubeflow from `0.6` to `1.0.2` using the following manifest: 
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml

**What did you expect to happen:**
The UI should display the appropriate version of the kubeflow install. Instead it displayed `dev_local`

**Anything else you would like to add:**
It seems the issue might originate from this [line](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/webpack.config.js#L22).

**Environment:**

- Kubeflow version: (This is where the bug seems to be. The version displayed is `dev_local`):
- kfctl version: (use `1.0.2`):
- Kubernetes platform: (e.g. `GKE`)
- Kubernetes version: (`v1.18.2`):
- OS (`MacOS`):

**Comment by jlewi** [comment]
It looks like the code is using an environment variable to set the version.
It doesn't look like this environment variable is actually getting set in the manifest.
https://github.com/kubeflow/manifests/tree/master/common/centraldashboard

Which I think is why BUILD_VERSION is defaulting to dev_local

@avdaredevil is BUILD_VERSION used to set the commit in the UI.

**Comment by avdaredevil** [comment]
Right, when the website-image is `built` not when it's `run` this enironment variable needs to be set. And the [Makefile](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard/Makefile), and [make-win.ps1](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard/make-win.ps1)

Here is the [line in the webpack build file](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/webpack.config.js#L22) where this env_var is used

**Comment by emenendez** [comment]
Hi there! This issue still seems to be present in Kubeflow 1.6.1. I know it's a very small thing -- but is it possible to re-open this issue?
