### ISSUE TITLE
[ERROR]gateways.networking.istio.io "kubeflow-gateway" is forbidden

### ISSUE THREAD

**Issue by edenbuaa** [kubeflow/kubeflow#5009]
/kind bug

**What steps did you take and what happened:**
`kfctl apply -V -f  kfctl_k8s_istio.v1.0.2.yaml`

then report error:

`WARN[0005] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when creating "/tmp/kout283909133": configmaps "istio-parameters-t6hhgfg9k2" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": gateways.networking.istio.io "kubeflow-gateway" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": serviceentries.networking.istio.io "google-api-entry" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": serviceentries.networking.istio.io "google-storage-api-entry" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": virtualservices.networking.istio.io "google-api-vs" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": virtualservices.networking.istio.io "google-storage-api-vs" is forbidden: unable to create new content in namespace kubeflow because it is being terminated, error when creating "/tmp/kout283909133": virtualservices.networking.istio.io "grafana-vs" is forbidden: unable to create new content in namespace kubeflow because it is being terminated]  filename="kustomize/kustomize.go:202"`

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) 
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): ubuntu

How to fix this issue? thanks.

**Comment by edenbuaa** [comment]
any suggestions?

**Comment by yanniszark** [comment]
@edenbuaa the error logs give a hint about what is going on:
```
unable to create new content in namespace kubeflow because it is being terminated
```

The namespace `kubeflow` is being terminated so create fails.
You have to wait until the namespace is deleted and then apply with `kfctl`.
Does this solve your issue?

**Comment by edenbuaa** [comment]
@yanniszark thank. I try to deploy again after deleting the ` namespace` and `istio-system`, then the following error was reported:
`WARN[0015] Encountered error applying application isltio-install:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Tiller\",\"istio\":\"ingressgateway\",\"release\":\"istio\"},\"name\":\"istio-ingressgateway\",\"namespace\":\"istio-system\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Tiller\",\"istio\":\"ingressgateway\",\"release\":\"istio\"}},\"template\":{\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Tiller\",\"istio\":\"ingressgateway\",\"release\":\"istio\"}},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"ppc64le\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"s390x\"]}]},\"weight\":2}],\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\",\"ppc64le\",\"s390x\"]}]}]}}},\"containers\":[{\"args\":[\"proxy\",\"router\",\"--domain\",\"$(POD_NAMESPACE).svc.cluster.local\",\"--log_output_level=default:info\",\"--drainDuration\",\"45s\",\"--parentShutdownDuration\",\"1m0s\",\"--connectTimeout\",\"10s\",\"--serviceCluster\",\"istio-ingressgateway\",\"--zipkinAddress\",\"zipkin:9411\",\"--proxyAdminPort\",\"15000\",\"--statusPort\",\"15020\",\"--controlPlaneAuthPolicy\",\"NONE\",\"--discoveryAddress\",\"istio-pilot:15010\"],\"env\":[{\"name\":\"POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"INSTANCE_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.podIP\"}}},{\"name\":\"HOST_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.hostIP\"}}},{\"name\":\"ISTIO_META_POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"ISTIO_META_CONFIG_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"ISTIO_META_ROUTER_MODE\",\"value\":\"sni-dnat\"}],\"image\":\"docker.io/istio/proxyv2:1.1.6\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"istio-proxy\",\"ports\":[{\"containerPort\":15020},{\"containerPort\":80},{\"containerPort\":443},{\"containerPort\":31400},{\"containerPort\":15029},{\"containerPort\":15030},{\"containerPort\":15031},{\"containerPort\":15032},{\"containerPort\":15443},{\"containerPort\":15090,\"name\":\"http-envoy-prom\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":30,\"httpGet\":{\"path\":\"/healthz/ready\",\"port\":15020,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":1,\"periodSeconds\":2,\"successThreshold\":1,\"timeoutSeconds\":1},\"resources\":{\"limits\":{\"cpu\":\"100m\",\"memory\":\"128Mi\"},\"requests\":{\"cpu\":\"10m\",\"memory\":\"40Mi\"}},\"volumeMounts\":[{\"mountPath\":\"/etc/certs\",\"name\":\"istio-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-certs\",\"name\":\"ingressgateway-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-ca-certs\",\"name\":\"ingressgateway-ca-certs\",\"readOnly\":true}]}],\"serviceAccountName\":\"istio-ingressgateway-service-account\",\"volumes\":[{\"name\":\"istio-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio.istio-ingressgateway-service-account\"}},{\"name\":\"ingressgateway-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-certs\"}},{\"name\":\"ingressgateway-ca-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-ca-certs\"}}]}}}}\n"},"labels":{"heritage":"Tiller","release":"istio"}},"spec":{"selector":{"matchLabels":{"chart":"gateways","heritage":"Tiller","release":"istio"}},"strategy":null,"template":{"metadata":{"labels":{"heritage":"Tiller","release":"istio"}},"spec":{"$setElementOrder/containers":[{"name":"istio-proxy"}],"containers":[{"$setElementOrder/env":[{"name":"POD_NAME"},{"name":"POD_NAMESPACE"},{"name":"INSTANCE_IP"},{"name":"HOST_IP"},{"name":"ISTIO_META_POD_NAME"},{"name":"ISTIO_META_CONFIG_NAMESPACE"},{"name":"ISTIO_META_ROUTER_MODE"}],"env":[{"name":"ISTIO_META_ROUTER_MODE","value":"sni-dnat"},{"$patch":"delete","name":"ISTIO_METAJSON_LABELS"},{"$patch":"delete","name":"ISTIO_META_CLUSTER_ID"},{"$patch":"delete","name":"ISTIO_META_OWNER"},{"$patch":"delete","name":"ISTIO_META_WORKLOAD_NAME"},{"$patch":"delete","name":"NODE_NAME"},{"$patch":"delete","name":"SDS_ENABLED"},{"$patch":"delete","name":"SERVICE_ACCOUNT"}],"image":"docker.io/istio/proxyv2:1.1.6","name":"istio-proxy","resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"10m","memory":"40Mi"}}}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "istio-ingressgateway", Namespace: "istio-system"
Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" "metadata":map["annotations":map["deployment.kubernetes.io/revision":"1" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Helm\",\"istio\":\"ingressgateway\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-ingressgateway\",\"namespace\":\"istio-system\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"istio-ingressgateway\",\"istio\":\"ingressgateway\"}},\"strategy\":{\"rollingUpdate\":{\"maxSurge\":\"100%\",\"maxUnavailable\":\"25%\"}},\"template\":{\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Helm\",\"istio\":\"ingressgateway\",\"release\":\"RELEASE-NAME\"}},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"ppc64le\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"s390x\"]}]},\"weight\":2}],\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\",\"ppc64le\",\"s390x\"]}]}]}}},\"containers\":[{\"args\":[\"proxy\",\"router\",\"--domain\",\"$(POD_NAMESPACE).svc.cluster.local\",\"--log_output_level=default:info\",\"--drainDuration\",\"45s\",\"--parentShutdownDuration\",\"1m0s\",\"--connectTimeout\",\"10s\",\"--serviceCluster\",\"istio-ingressgateway\",\"--zipkinAddress\",\"zipkin:9411\",\"--proxyAdminPort\",\"15000\",\"--statusPort\",\"15020\",\"--controlPlaneAuthPolicy\",\"NONE\",\"--discoveryAddress\",\"istio-pilot:15010\"],\"env\":[{\"name\":\"NODE_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"spec.nodeName\"}}},{\"name\":\"POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"INSTANCE_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.podIP\"}}},{\"name\":\"HOST_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.hostIP\"}}},{\"name\":\"SERVICE_ACCOUNT\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"spec.serviceAccountName\"}}},{\"name\":\"ISTIO_META_POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"ISTIO_META_CONFIG_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"ISTIO_METAJSON_LABELS\",\"value\":\"{\\\"app\\\":\\\"istio-ingressgateway\\\",\\\"chart\\\":\\\"gateways\\\",\\\"heritage\\\":\\\"Helm\\\",\\\"istio\\\":\\\"ingressgateway\\\",\\\"release\\\":\\\"RELEASE-NAME\\\"}\\n\"},{\"name\":\"ISTIO_META_CLUSTER_ID\",\"value\":\"Kubernetes\"},{\"name\":\"SDS_ENABLED\",\"value\":\"false\"},{\"name\":\"ISTIO_META_WORKLOAD_NAME\",\"value\":\"istio-ingressgateway\"},{\"name\":\"ISTIO_META_OWNER\",\"value\":\"kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway\"},{\"name\":\"ISTIO_META_ROUTER_MODE\",\"value\":\"standard\"}],\"image\":\"docker.io/istio/proxyv2:1.5.2\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"istio-proxy\",\"ports\":[{\"containerPort\":15020},{\"containerPort\":80},{\"containerPort\":443},{\"containerPort\":31400},{\"containerPort\":15029},{\"containerPort\":15030},{\"containerPort\":15031},{\"containerPort\":15032},{\"containerPort\":15443},{\"containerPort\":15090,\"name\":\"http-envoy-prom\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":30,\"httpGet\":{\"path\":\"/healthz/ready\",\"port\":15020,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":1,\"periodSeconds\":2,\"successThreshold\":1,\"timeoutSeconds\":1},\"resources\":{\"limits\":{\"cpu\":\"2000m\",\"memory\":\"1024Mi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"128Mi\"}},\"volumeMounts\":[{\"mountPath\":\"/etc/certs\",\"name\":\"istio-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-certs\",\"name\":\"ingressgateway-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-ca-certs\",\"name\":\"ingressgateway-ca-certs\",\"readOnly\":true}]}],\"serviceAccountName\":\"istio-ingressgateway-service-account\",\"volumes\":[{\"name\":\"istio-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio.istio-ingressgateway-service-account\"}},{\"name\":\"ingressgateway-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-certs\"}},{\"name\":\"ingressgateway-ca-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-ca-certs\"}}]}}}}\n"] "creationTimestamp":"2020-05-12T11:33:16Z" "generation":'\x01' "labels":map["app":"istio-ingressgateway" "chart":"gateways" "heritage":"Helm" "istio":"ingressgateway" "release":"RELEASE-NAME"] "name":"istio-ingressgateway" "namespace":"istio-system" "resourceVersion":"1142080" "selfLink":"/apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway" "uid":"2b602537-15ee-4d94-835f-1e94687c4ecc"] "spec":map["progressDeadlineSeconds":'\u0258' "replicas":'\x01' "revisionHistoryLimit":'\n' "selector":map["matchLabels":map["app":"istio-ingressgateway" "istio":"ingressgateway"]] "strategy":map["rollingUpdate":map["maxSurge":"100%" "maxUnavailable":"25%"] "type":"RollingUpdate"] "template":map["metadata":map["annotations":map["sidecar.istio.io/inject":"false"] "creationTimestamp":<nil> "labels":map["app":"istio-ingressgateway" "chart":"gateways" "heritage":"Helm" "istio":"ingressgateway" "release":"RELEASE-NAME"]] "spec":map["affinity":map["nodeAffinity":map["preferredDuringSchedulingIgnoredDuringExecution":[map["preference":map["matchExpressions":[map["key":"beta.kubernetes.io/arch" "operator":"In" "values":["amd64"]]]] "weight":'\x02'] map["preference":map["matchExpressions":[map["key":"beta.kubernetes.io/arch" "operator":"In" "values":["ppc64le"]]]] "weight":'\x02'] map["preference":map["matchExpressions":[map["key":"beta.kubernetes.io/arch" "operator":"In" "values":["s390x"]]]] "weight":'\x02']] "requiredDuringSchedulingIgnoredDuringExecution":map["nodeSelectorTerms":[map["matchExpressions":[map["key":"beta.kubernetes.io/arch" "operator":"In" "values":["amd64" "ppc64le" "s390x"]]]]]]]] "containers":[map["args":["proxy" "router" "--domain" "$(POD_NAMESPACE).svc.cluster.local" "--log_output_level=default:info" "--drainDuration" "45s" "--parentShutdownDuration" "1m0s" "--connectTimeout" "10s" "--serviceCluster" "istio-ingressgateway" "--zipkinAddress" "zipkin:9411" "--proxyAdminPort" "15000" "--statusPort" "15020" "--controlPlaneAuthPolicy" "NONE" "--discoveryAddress" "istio-pilot:15010"] "env":[map["name":"NODE_NAME" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"spec.nodeName"]]] map["name":"POD_NAME" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.name"]]] map["name":"POD_NAMESPACE" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.namespace"]]] map["name":"INSTANCE_IP" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"status.podIP"]]] map["name":"HOST_IP" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"status.hostIP"]]] map["name":"SERVICE_ACCOUNT" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"spec.serviceAccountName"]]] map["name":"ISTIO_META_POD_NAME" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.name"]]] map["name":"ISTIO_META_CONFIG_NAMESPACE" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.namespace"]]] map["name":"ISTIO_METAJSON_LABELS" "value":"{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Helm\",\"istio\":\"ingressgateway\",\"release\":\"RELEASE-NAME\"}\n"] map["name":"ISTIO_META_CLUSTER_ID" "value":"Kubernetes"] map["name":"SDS_ENABLED" "value":"false"] map["name":"ISTIO_META_WORKLOAD_NAME" "value":"istio-ingressgateway"] map["name":"ISTIO_META_OWNER" "value":"kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway"] map["name":"ISTIO_META_ROUTER_MODE" "value":"standard"]] "image":"docker.io/istio/proxyv2:1.5.2" "imagePullPolicy":"IfNotPresent" "name":"istio-proxy" "ports":[map["containerPort":'\u3aac' "protocol":"TCP"] map["containerPort":'P' "protocol":"TCP"] map["containerPort":'\u01bb' "protocol":"TCP"] map["containerPort":'\u7aa8' "protocol":"TCP"] map["containerPort":'\u3ab5' "protocol":"TCP"] map["containerPort":'\u3ab6' "protocol":"TCP"] map["containerPort":'\u3ab7' "protocol":"TCP"] map["containerPort":'\u3ab8' "protocol":"TCP"] map["containerPort":'\u3c53' "protocol":"TCP"] map["containerPort":'\u3af2' "name":"http-envoy-prom" "protocol":"TCP"]] "readinessProbe":map["failureThreshold":'\x1e' "httpGet":map["path":"/healthz/ready" "port":'\u3aac' "scheme":"HTTP"] "initialDelaySeconds":'\x01' "periodSeconds":'\x02' "successThreshold":'\x01' "timeoutSeconds":'\x01'] "resources":map["limits":map["cpu":"2" "memory":"1Gi"] "requests":map["cpu":"100m" "memory":"128Mi"]] "terminationMessagePath":"/dev/termination-log" "terminationMessagePolicy":"File" "volumeMounts":[map["mountPath":"/etc/certs" "name":"istio-certs" "readOnly":%!q(bool=true)] map["mountPath":"/etc/istio/ingressgateway-certs" "name":"ingressgateway-certs" "readOnly":%!q(bool=true)] map["mountPath":"/etc/istio/ingressgateway-ca-certs" "name":"ingressgateway-ca-certs" "readOnly":%!q(bool=true)]]]] "dnsPolicy":"ClusterFirst" "restartPolicy":"Always" "schedulerName":"default-scheduler" "securityContext":map[] "serviceAccount":"istio-ingressgateway-service-account" "serviceAccountName":"istio-ingressgateway-service-account" "terminationGracePeriodSeconds":'\x1e' "volumes":[map["name":"istio-certs" "secret":map["defaultMode":'\u01a4' "optional":%!q(bool=true) "secretName":"istio.istio-ingressgateway-service-account"]] map["name":"ingressgateway-certs" "secret":map["defaultMode":'\u01a4' "optional":%!q(bool=true) "secretName":"istio-ingressgateway-certs"]] map["name":"ingressgateway-ca-certs" "secret":map["defaultMode":'\u01a4' "optional":%!q(bool=true) "secretName":"istio-ingressgateway-ca-certs"]]]]]] "status":map["availableReplicas":'\x01' "conditions":[map["lastTransitionTime":"2020-05-12T11:34:25Z" "lastUpdateTime":"2020-05-12T11:34:25Z" "message":"Deployment has minimum availability." "reason":"MinimumReplicasAvailable" "status":"True" "type":"Available"] map["lastTransitionTime":"2020-05-12T11:33:16Z" "lastUpdateTime":"2020-05-12T11:34:25Z" "message":"ReplicaSet \"istio-ingressgateway-6758bbc86d\" has successfully progressed." "reason":"NewReplicaSetAvailable" "status":"True" "type":"Progressing"]] "observedGeneration":'\x01' "readyReplicas":'\x01' "replicas":'\x01' "updatedReplicas":'\x01']]}
for: "/tmp/kout702427350": Deployment.apps "istio-ingressgateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"istio-ingressgateway", "chart":"gateways", "heritage":"Tiller", "istio":"ingressgateway", "release":"istio"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable  filename="kustomize/kustomize.go:202"
`

**Comment by jlewi** [comment]
Kubernetes is complaining because you are trying to reapply and change some immutable fields. Is it possible to just delete everything and start over?
