### ISSUE TITLE
Sorry, /notebook is not a valid page

### ISSUE THREAD

**Issue by ConverJens** [kubeflow/kubeflow#5010]
/kind bug

**What steps did you take and what happened:**
Deployed kfctl_istio_dex.v1.0.2.yaml in an on-prem k8s cluster. Created a notebook server through the centraldashboard notebook page successfully. Clicking on 'Connect' leads to 
http://CLUSTER_IP:31380/notebook/admin/my-notebook 
were error is shown.
Also, centraldashboard 'Recent Notebooks' also shows no notebooks in namespace even though they exist.

**What did you expect to happen:**
Jupyter server UI to open and 'Recent Notebooks' to be populated.

**Anything else you would like to add:**
The notebook server is accessible via port-forwarding and notebooks can be spawned and works as expected. All other pages (metadata, experiments etc) works as expected.

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: v1.0.1-0-gf3edb9b
- Kubernetes platform: vanilla on-prem k8s
- Kubernetes version: v1.17.4
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
@ConverJens have you searched GitHub for similar issues? This is likely an issue with your networking / ISTIO and similar issues in the past might have helpful information on debugging.

/cc @johnugeorge  @yanniszark

**Comment by ConverJens** [comment]
@jlewi Thanks for the response. I've looked at all the similar issues that I can find, closest seems to be: https://github.com/kubeflow/pipelines/issues/1442. However, just like the last three comments on that issue, I'm on KubeFlow 1.0.X but the routing issue remains.

All other components (pipelines, artefacts, setting up notebook servers, etc) are working correctly and can be found through the dashboard. Only the jupyter server page is unavailable through the central dashboard. This leads me to believe that the kubeflow Istio installation is working as it should. Also, since port-forwarding to the notebook server works, the deployed service seems to work. 

It might be the case that the notebook server service needs to register somewhere to enable service discovery and that that does't happen. Is it the case that this happens in some other way if KubeFlow is deployed on GCP or AWS?

I can't find any issues in any logs related to these components.

Any help or pointers ahead would be greatly appreciated!

**Comment by ConverJens** [comment]
@jlewi @johnugeorge @yanniszark Any update on this?

**Comment by jlewi** [comment]
@ConverJens  I think you are going to have to dive into ISTIO and the Dex setup to try to troubleshoot what's going on here. 

The first thing to investigate is how the [ISTIO ingressgateway](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/) is deployed.

Per those instructions you should run 

```
kubectl get svc istio-ingressgateway -n istio-system
```

Is your ISTIO ingressgateway exposed via node port? via service type load balancer? Is it connected to a K8s ingress to wire it up to an external load balancer.

Then I would look at the virtual service for the notebook. 

* What is the path it is serving on?
* Is the ISTIO gateway specified correctly?
  * If the gateway is in a different namespace then the gateway specification should include the namespace it is specified in

You might want to go through some of the ISTIO tutorials to understand how to expose services externally behind the gateway.

I think the [tutorial](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/) uses httpbin. That might help you verify that your ISTIO is setup correctly and configured.

**Comment by ConverJens** [comment]
@jlewi Again, thank you for your respons!

The istio-ingressgateway is exposed via node port:
`istio-ingressgateway   NodePort   10.43.125.55   <none>        15020:31741/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:32223/TCP,15030:32129/TCP,15031:32469/TCP,15032:30159/TCP,15443:31846/TCP   20d   app=istio-ingressgateway,istio=ingressgateway`

As for the notebook, there is no virtual service deployed, only a service. If that is needed, I would assume that the notebook controller would delpoy this and not that I would need to do this myself. Is the virtual service required.

I will go through the tutorial and see if I can find anything else.

**Comment by jlewi** [comment]
@ConverJens yes a virtual service is required. A virtual service is required to tell ISTIO how to route traffic to your backend. The ISTIO virtual service should be created by the notebook controller.

I would suggest looking at the notebook controller logs to see why the virtual service isn't being created.

**Comment by ConverJens** [comment]
@jlewi Will do! Thanks for the pointer. I'll let you know what I find.

**Comment by ConverJens** [comment]
@jlewi You were right about the virtualservice. Adding it manually fixed made the notebook server reachable through the dashboard. Still haven't found why it wasn't automatically created.

**Comment by ConverJens** [comment]
@jlewi Found the issue, for some reason the USE_ISTIO var is hard-coded to false in notebook-controller/base/deployment.yaml. So even though USE_ISTIO is set to true in notebook-controller/overlays/istio/param.env the Kustomize merge will fail since base/deployment.yaml doesn't use the variable USE_ISTIO. That resolves it for me. Thanks for the help!

**Comment by ConverJens** [comment]
@jlewi There is an overlay with a var that sets USE_ISTIO=true. However, for some reason Kustomize still produces a configmap with USE_ISTIO=FALSE.

I'll chech if this is still an issue when 1.1.0 is released and let you know.

**Comment by ConverJens** [comment]
@jlewi Just upgraded to KF 1.1.0 using kfctl_istio_dex.v1.1.0.yaml and did no longer have this issue so I think you can consider it solved.

**Comment by akranga** [comment]
I believe this code causes the problem: [deployment_patch.yaml](https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base/deployment_patch.yaml) AFAIK it is still in master and in `v1.1` branch. Similar to authors of the patch, I was not able to find any elegant solution, so ended up with [this](https://github.com/agilestacks/components/blob/master/kubeflow-v1.0/ext/jupyter/notebook-controller/base/deployment_patch.yaml). Hope it will help to someone

**Comment by makeitai** [comment]
Deleting istio-ingressgateway pod might.

kubectl -n istio-system delete pod istio-ingressgateway-xxxxx-xxxx

My kubeflow version is 1.3.  It worked for me

**Comment by padrian** [comment]
I still have this issue on 1.3.0
I am using kfctl_aws.v1.3.0.yaml

**Comment by mdf-ido** [comment]
I saw this again in version 1.10.0 and created the istio service for the notebook controller separately since I saw the notebook getting created in the namespace but not shown in centraldashboard to resolve the issue of the 500 error.
