### ISSUE TITLE
Operator for FATE - Federated Learning

### ISSUE THREAD

**Issue by LaynePeng** [kubeflow/kubeflow#5011]
/kind question

**Question:**
We are from VMware, and working on Federated Learning areas. Currently we are collaborating with Webank on FATE (https://github.com/FederatedAI/FATE ). For easier to run Federated Learning on Kubernetes, we are building a operator to submit learning job as well as deploy FATE cluster. The first version have done, and ready to show. We would like to contribute the work to Kubeflow. And wonder how to get start it. 

We saw some proposals are submited in kubeflow->issue, and also found https://github.com/kubeflow/community/tree/master/proposals . Where we should go, PR to community-> proposal or raise a issue here?

**Comment by Jeffwan** [comment]
Submit a PR to community proposal here https://github.com/kubeflow/community/tree/master/proposals

**Comment by jlewi** [comment]
I would also suggest emailing kubeflow-discuss@googlegroups.com and perhaps presenting at one of the upcoming community meetings to promote your work and discuss how to integrate it with Kubeflow.

**Comment by jlewi** [comment]
@LaynePeng what sort of help, collaboration, integration are you looking for? It sounds like you already have a FATE operator built. Is this already public somewhere?

**Comment by LaynePeng** [comment]
Thank @Jeffwan and @jlewi . I have PR the proposal to community (https://github.com/kubeflow/community/pull/335). Yes, we have built a runnable version and going to book a timeslot in community meeting to demo. I found we can edit and add the demo plan in [Kubeflow Community Meeting Working Doc](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit) . Or as your suggestion, just send email about the demo of topic, name , propse date, duratiom to  kubeflow-discuss@googlegroups.com ?

**Comment by jlewi** [comment]
@LaynePeng its fine to comment in the doc.

**Comment by Jeffwan** [comment]
@LaynePeng https://github.com/kubeflow/fate-operator seems you already setup the project and has the process. Do you need other help?
