### ISSUE TITLE
support retry with parameter values of the previous run

### ISSUE THREAD

**Issue by wenmin-wu** [kubeflow/kubeflow#5014]
/kind feature

**Why you need this feature:**

My most use case of kubeflow is processing data for a target date and I get the target date by calling `datetime.now() - timedelta(days=n)`. Sometimes, the job failed and when I re-run it's already one day passed, and the `target_date` is not my expected. 

**Describe the solution you'd like:**

Support `bash` or `python` injection for the input parameters, like:

```Bash
 --target-date=$(date --date='1 day ago' +%F)
```
or
 
```Python
--target-date={{(datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")}}
```
The input parameters will be evaluated for the first  try, and the values will be stored in datastore such as MINIO, when retry the run, it will query the values from the datastore.

**Anything else you would like to add:**

It's also good to have an option to choose which nodes to run when retry, I'm not sure whether I need to create another issue:)

I have experience of TypeScript, Python and Go, however, I'm not quite familiar with the implementation of kubeflow. It will be great if someone can implement this feature or someone tell me how to implement this feature. Thanks!

**Comment by amitripshtos** [comment]
Argo is the one which sends the parameters to the pods and starts the processes. I don't think it's can be done to send Argo a parameter that should be "compiled" or ran at runtime.

This feature also makes everything more ambiguous and not explicit - and that's bad practice especially for DAGs and ML-Related parameters (what will be saved in the metadata store?)

A good practice is just to enter the right parameter you wanted, so even re-running will cause the same behavior.

You can create this ability by running pipelines using the Python SDK, and set the right date parameter using python (when creating a new pipeline run) instead of using the UI.

I hope I helped a bit with your issue.

**Comment by Bobgy** [comment]
I agree with @amitripshtos. Recommend passing in the date instead of calling `datetime.now()`.
/cc @Ark-kun 
Do you know a better way to handle this?

**Comment by Bobgy** [comment]
Also, how can we move this issue to kubeflow/pipelines repo?

**Comment by wenmin-wu** [comment]
Hi @amitripshtos and @Bobgy thanks for your reply, I see your point. However, I'm talking about the scheduled pipeline with `cron`, if the job failed and it's already one day past, after clicking retry my pipeline won't process data of one day ago. 

For a daily scheduled pipeline, what does the retry for? If the job failed I need to think about whether my pipeline will process the same data as previous before I click retry? And if not, I need to go back to the pipeline page and create a run with the correct parameter entered manually? 

This feature is supported by some popular workflow orchestration tool like [Airflow](https://airflow.apache.org/docs/stable/) and [Azkaban](https://azkaban.github.io/azkaban/docs/latest/), I don't think it's ambiguous and not explicit, but it's a useful feature should be supported by any workflow orchestration tool.

**Comment by Bobgy** [comment]
To be honest, I think kubeflow pipelines have limited features on `cron` jobs.

Would using an Airflow to trigger cron jobs in kubeflow pipelines suit your use-case? It can run a KFP client to trigger a pipeline using date as an argument, so that this task will be retriable.

I vaguely recall there's probably an argument that you can use to auto-fill scheduled date when the task was run from `cron`. Let me take a look.

**Comment by wenmin-wu** [comment]
Hi @Bobgy, thanks a lot, after uploading pipeline with `kfp.Client`, I call `kfp_server_api.api.run_service_api.RunServiceApi(...).create_job` to create a `cron` job. Good to know there's probably an argument to auto-fill.

**Comment by Bobgy** [comment]
Hi @wenmin-wu, I found how to get scheduled time from a `cron` job.

https://github.com/kubeflow/pipelines/blob/578e8231d01074b9dbe40ace1db8cc444a6a1bd8/backend/src/crd/samples/scheduledworkflow/parameterized.yaml#L29-L34

I don't think these have been well-documented, but should be good for your use-case. If you put placeholders like `[[ScheduledTime]]` in arguments passed to your workflow. When they are scheduled, these arguments will be replaced with actual time.
When you want to retry a run, just clone it and it will get the arguments it was previously used.

**Comment by wenmin-wu** [comment]
Hi @Bobgy, thanks a lot. Just to double-check to make sure I get your point. Let's say today I create a `cron` job and tomorrow it run but failed. Then I retry it, is the time tomorrow or today?

**Comment by Bobgy** [comment]
@wenmin-wu when you retry it, you are cloning the same workflow with the same arguments. That argument was already instantiated with the date it was ran on. In your example, the run was ran on tomorrow, so the argument should be `tomorrow`. When you retry it the day after tomorrow, you will use the same arguments, so the argument will still be `tomorrow`.

**Comment by wenmin-wu** [comment]
Thanks @Bobgy, let me create a cron job to try this, you saved me days of time.

**Comment by Bobgy** [comment]
No problem. Please let me know if it works out. (tbh, I haven't tried this feature by myself, but looking at code that's how it's supposed to work and I remember hearing about it)

**Comment by wenmin-wu** [comment]
Hi @Bobgy , just to let know it doesn't work for me. I think it's because I didn't use the scheduled workflow template. My template is like this:
```Python
SCHEDULE_JOB_TEMPLATE = """
    {
        "description": "{{pipeline_description}}",
        "name": "{{pipeline_name}}",
        "pipeline_spec": {
            "parameters": {{pipeline_parameters}},
            "pipeline_id": "{{pipeline_id}}"
        },
        "resource_references": [
            {
                "key": {
                    "id": "{{experiment_id}}",
                    "type": "EXPERIMENT"
                },
                "relationship": "OWNER"
            }
        ],
        "enabled": {{pipeline_enabled}},
        "max_concurrency": "{{pipeline_max_concurrency}}",
        "trigger": {
            "cron_schedule": {
                "cron": "{{pipeline_cron}}"
            }
        }
    }
    """
```
and I pass the ``[[ScheduledTime]]`` to my function, after creating a run on kubeflow my function just print the raw string.
```Python
@dsl.pipeline(name=get_pipeline_name(), description=get_pipeline_desc())
def pipeline(target_date: str = "[[ScheduledTime]] - [[CurrentTime]]"):
    pass
```

**Comment by Bobgy** [comment]
@wenmin-wu Did you create a one time run or recurring one? Only recurring runs will get those values

**Comment by Bobgy** [comment]
@wenmin-wu one more clarification is that, the doc I referred to was talking about scheduled workflow template, but that's actually an internal implementation representation. You don't need to worry about that. Just using normal workflows with those arguments in a recurring run, those values should be replaced when run.

**Comment by wenmin-wu** [comment]
Hi @Bobgy, thanks for your help, I successfully got the scheduled time and current time by using these macros. The value I got today is `"20200527035000 - 20200527035002"` of `"[[ScheduledTime]] - [[CurrentTime]]"` . Let me close this issue.
