### ISSUE TITLE
How are the RBAC roles set? 

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/kubeflow#5017]
/kind question

**Question:**
Where in the code base are the different RBAC roles set? I would like to be able to run a mpijob from the notebooks server but get problems with the permissions. I am new to RBAC roles and such but as far as I understand a custom ServieAccount(sa) is create and given the role of the `default-editor`. This role dont have the access to mpijob resources and I get the following error: 

```
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '50308cfc-40cc-440d-b26d-662f6570b129', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 13 May 2020 06:00:26 GMT', 'Content-Length': '390'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"mpijobs.kubeflow.org is forbidden: User \"system:serviceaccount:kubeflow-niklas-sven-hansson:default-editor\" cannot create resource \"mpijobs\" in API group \"kubeflow.org\" in the namespace \"kubeflow-niklas-sven-hansson\"","reason":"Forbidden","details":{"group":"kubeflow.org","kind":"mpijobs"},"code":403}
```

I would like to set similar permissions(as default in the kubeflow deployment if people think it is good idea) as exist for tfjobs to allow users to create jobs from the notebooks. This is also related to my work in https://github.com/kubeflow/mpi-operator/pull/244.

Thanks!

**Comment by NikeNano** [comment]
FYI I will also create an example notebook to demonstrate it :)

**Comment by NikeNano** [comment]
The information for this is available in [kubeflow/manifests/kubeflow-roles](https://github.com/kubeflow/manifests/tree/master/kubeflow-roles)

**Comment by yanniszark** [comment]
@NikeNano we use aggregated ClusterRoles to define our default Roles in a composable way.
@krishnadurai has worked on this and I remember some great diagrams, @krishnadurai do you know if we have a website entry for this?
If not, it may be worth starting one and adding the existing material.

**Comment by NikeNano** [comment]
Thanks @yanniszark I managed to figure it out after looking at the manifest repo. Would be awesome to see that diagram!

**Comment by krishnadurai** [comment]
@NikeNano this presentation has a few diagrams which would be helpful:

https://docs.google.com/presentation/d/1j5tBrCkLNG-QxTl44iv-x5KpCapnczpxCbUzSciA2l8/edit#slide=id.g70b2208acc_1_230

**Comment by NikeNano** [comment]
Great! Thanks @krishnadurai
