### ISSUE TITLE
Recommended minikube setup

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#502]
Users have reported running into trouble with minikube because their nodes end up being too small and other issues.

We should document some recommended settings for minikube based on what's needed to run some of our E2E examples and our E2E tests (see kubeflow/testing#6)

**Comment by willingc** [comment]
FYI Minikube installs with no difficulty. 

Specifying the basic settings for memory and storage in VirtualBox would be helpful. Alternatively, a minimal notebook environment (similar to jupyter/docker-stacks minimal notebook stack) w/o Tensorflow would allow loading even if someone installs with inadequate memory for the larger images.

**Comment by jlewi** [comment]
Thanks @willingc 

I think we should keep the recommended settings in sync with what we use in our E2E tests
https://github.com/kubeflow/kubeflow/blob/master/testing/install_minikube.sh#L36

Although our E2E tests don't actually verify that we can start Jupyter images.

**Comment by abhi-g** [comment]
On my linux desktop, I am able to get the TensorFlow hello world equivalent working with Minikube setup using:
minikube start --cpus 4 --memory 8096 --disk-size=40g
Note that I also used --vm-driver=kvm2 along with the others.

For someone who just installed Minikube following the instructions on https://kubernetes.io/docs/getting-started-guides/minikube/#installation would have ended up creating a Minikube VM with defaults of 1 CPU and 2GB of memory when testing their hello word app. That VM is unusable for Kubeflow. We can add instructions on our docs to "minikube delete" followed by the minikube start with the recommended settings.

On Mac, I'll be trying with VirtualBox as the hypervisor. Unfortunately my Mac has only 4 cores total :( 
Will report how that goes.

**Comment by abhi-g** [comment]
With less than 4 cpus on minikube vm, Jupyterhub notebook doesn't come up at all.

**Comment by abhi-g** [comment]
Will do.
