### ISSUE TITLE
Admission webhook sidecar-injector.istio.io denied the request

### ISSUE THREAD

**Issue by leela-uppuluri** [kubeflow/kubeflow#5020]
/kind bug

**What steps did you take and what happened:**
I was trying to create a notebook server from kubeflow dashboard and I was running into this error `Reissued from statefulset/<notebookserver_name>: Create Pod <pod_name> in StatefulSet failed error: admission webhook "sidecar-injector.istio.io" denied the request: error converting YAML to JSON: could not find expected ':'`

**What did you expect to happen:**
It should create a notebook server with the necessary configuration.

**Environment:**

- Kubeflow version: dev_local
- kfctl version: v1.0.1
- Kubernetes platform: Open source k8s cluster
- Kubernetes version: v1.15
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

![ns-7](https://user-images.githubusercontent.com/43678538/82228401-ae2c5200-98ee-11ea-8304-865ff0b66a9b.png)

**Comment by jbottum** [comment]
@leela-uppuluri Hi, is this cluster running on-prem or in the cloud ?

**Comment by leela-uppuluri** [comment]
@jbottum It is running on-prem.

**Comment by leela-uppuluri** [comment]
@jbottum Do you have any suggestions or feedback on this?

**Comment by MartinForReal** [comment]
I think there might be something wrong with your Notebook manifests file.

**Comment by arshashi** [comment]
Any fix would be greatly appreciated.

Below is the error while creating the pod. Any suggestions.

Warning	FailedCreate	create Pod notebook-0 in StatefulSet notebook failed error: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:7:27: executing "inject" at <.Values.global.proxy_init.image>: invalid value; expected string	8 minutes ago

**Comment by MartinForReal** [comment]
@arshashi I think there is something wrong with your istio sidecar injector. Maybe you need to update image name in istio-sidecar-injector configmap

**Comment by arshashi** [comment]
@MartinForReal Thanks for the response.   

are you saying under Istio-system namespace, we have a pod with the name istio-sidecar-injector-8476 which is associated to gcr.io/istio-release/sidecar_injector:release-1.3-latest-daily to be updated? any suggestion on updating configmap as mentioned?

**Comment by leela-uppuluri** [comment]
> @leela-uppuluri Did you find the fix for this issue?

@shrutich91 I still didn't have a good workaround on that. Please let me know if anything works for you.

**Comment by MartinForReal** [comment]
maybe you need to make sure init image has a correct name @arshashi 
![image](https://user-images.githubusercontent.com/5207478/92731294-78344180-f3a7-11ea-96fd-6320d3b5badf.png)

**Comment by MartinForReal** [comment]
>Should I try adding the “image” and “resources” key along with repository and tag?.

yes 

> I think the error clearly points the above difference where image is not a string because it is NULL.
I think this is the root cause

**Comment by MartinForReal** [comment]
I think this is not a bug of notebook controller and it's an istio related issue

**Comment by MartinForReal** [comment]
'''
"proxy_init": {
"image": "proxyv2", #####image name here
"resources": {
"limits": {
"cpu": "100m",
"memory": "50Mi"
},
"requests": {
"cpu": "10m",
"memory": "10Mi"
}
}
},

'''

I think the image name should be changed accordingly. 

Can we close this issue?

**Comment by arshashi** [comment]
@MartinForReal Thanks for the help and I feel this can be closed.
