### ISSUE TITLE
Release demo script for 1.1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5021]
We aim to release Kubeflow 1.1 at the end of June. With that in mind it would be good to begin defining an appropriate release demo script to help ensure everyone is on the same page and begin qualifying releases.

Some useful links

* http://bit.ly/demo-v1-0 - The demo script for 1.0 this is probably a good place to start for creating a KF 1.1 demo script
* The [KF Roadmap for 1.1](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md#kubeflow-11-features-target-release-late-june-2020) - A good reference point to start figuring out what features to highlight in the demo script
   
Based on those links it looks like there's a couple features that might be worth highlighting in the demo script

* multi-user pipelines (kubeflow/pipelines#1223) 
  * This is probably the biggest new feature landing in 1.1 so it would be good to highlight this in the demo script

* upgrades (kubeflow/kfctl#304) this is a major ask from customers
   * A lot of the refactoring work in the manifests in 1.1 is happening to simplify upgrades
   * It would be good to have script that illustrates how upgrades work

* Lineage tracking (kubeflow/website#1959) 
   * I think this feature already landed in 1.0 but I don't think our release decks our promoting it so it might be worthwhile to highlight in 1.1

**Comment by Jeffwan** [comment]
As I understand, upgrade feature only works for solution with persistent volume static provisioned? We have a few components use PVC and default storage class to dynamically provision cloud disks. I am curious if this has been covered?

**Comment by jlewi** [comment]
@Jeffwan why not?
