### ISSUE TITLE
unable to contact profile controller kubeflow

### ISSUE THREAD

**Issue by xalekx** [kubeflow/kubeflow#5029]
/kind bug

**What steps did you take and what happened:**
I have installed kubeflow using https://developer.ibm.com/technologies/artificial-intelligence/tutorials/kubeflow-in-ibm-cloud-public/. 
I am connected via ssh to a remote bare metal machine.  Using ``` kubectl get -n istio-system svc/istio-ingressgateway``` i get that the type is nodetype and there is no external address. Using the cluster ip from the kubernetes dashboard and using port 31380 ( the above command returns this ports ```15020:32150/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:32725/TCP,15030:30329/TCP,15031:30715/TCP,15032:31971/TCP,15443:31679/TCP ```) i get ot the kubeflow dashboard but unable to contact profile controller kubeflow is shown on the bottom right and there are no namespaces available.
Picture : https://imgur.com/a/9iMtzV4

How do i solve this issue?

Also there is no load balancer for IBM cluster. I tried intalling metallb but it messed everything up and coulnt even get to the dashboard following the above method.

Thanks

**Environment:**

- Kubeflow version: dev_local
- kfctl version: v1.0.1-0-gf3edb9b
- Kubernetes platform: IBM cluster
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9+IKS", GitCommit:"044064595e3a0af0d71be49184f82bdfc69924ac", GitTreeState:"clean", BuildDate:"2020-04-17T15:25:39Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
:
- OS (e.g. from `/etc/os-release`): Bare metal linux IBM machine
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jbottum** [comment]
@animeshsingh do you have someone that supports these questions

**Comment by ConverJens** [comment]
@xalekx Have you check the logs of centraldashboard? I had similar issues that were caused by the namespace variable in central dashboard failed to resolve at kustomize time causing lacking privileges for centraldashboard which gave me profile/namespace issues. One note however was that I used the 1.0.2 istio yaml for on-prem deployment and not the ibm one.

**Comment by mikechengwei** [comment]
mark

**Comment by animeshsingh** [comment]
@xalekx if this is still an issue - pleaae sync up with @shawnzhu @adrian555

**Comment by shawnzhu** [comment]
I will try to help by providing more information.

> I am connected via ssh to a remote bare metal machine. Using kubectl get -n istio-system svc/istio-ingressgateway i get that the type is nodetype and there is no external address

I assume you mean the type is `NodePort`. you need to follow the section of the above guide to update its type to `LoadBalancer`, then you will see its external IP via running `kubectl get svc/istio-ingressgateway -n istio-system`.

> i get ot the kubeflow dashboard but unable to contact profile controller kubeflow is shown on the bottom right and there are no namespaces available.

Prior to kubeflow v1.0.2, it will require a cluster admin manually creates a profile. You can use this guide to create a profile: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation.

If you use `export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_ibm.yaml"` around May 20, you were deploying kubeflow v1.0.2, so you probably get to access the kubeflow dashboard **prior to** the automatic profile creation, which will be the first thing you saw when visiting the Kubeflow dashboard. it looks like this:

![](https://www.kubeflow.org/docs/images/auto-profile1.png)

You can follow ☝️ guide to create a profile via web UI. See details from https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles

> Also there is no load balancer for IBM cluster. I tried intalling metallb but it messed everything up and coulnt even get to the dashboard following the above method.

Actually there are several (NLB 1.0, VPC load balancer, ALB, etc) depends on the Kubernetes worker node provider you choose. You can use this guide to see details: [Quick start for load balancers](https://cloud.ibm.com/docs/containers?topic=containers-loadbalancer-qs).

BTW: I'm to work on https://github.com/kubeflow/website/pull/2028 to document the multi-tenant feature that @adrian555 added. it will be more helpful.
