### ISSUE TITLE
StackDriver Logs

### ISSUE THREAD

**Issue by allenc97** [kubeflow/kubeflow#5030]
/kind question

**Question:**
[You can ask any question about this project.]

There are far too many logs logged into Stackdriver by kubeflow. Is there a way we can disable logging for many of the default components that we don't use, I.e katib?

**Comment by knave07** [comment]
@allenc97 You could make an exclusion rule in your GCP project to exclude the logs containing certain keywords. 

Go to logging and you can see all the exclusions from here:
<img width="1672" alt="Screen Shot 2020-06-30 at 20 35 20" src="https://user-images.githubusercontent.com/37116431/86123408-69622080-bb14-11ea-8c22-279d7f60620f.png">

Create Exclusion from here: 
<img width="1430" alt="Screen Shot 2020-06-30 at 20 51 23" src="https://user-images.githubusercontent.com/37116431/86123569-b6de8d80-bb14-11ea-839d-f4d0fc5fae95.png">

Just type in the keyword (in your case "katib") in the search filter and then write the name, description, and % to Exclude and you are done.
