### ISSUE TITLE
Any plans for supporting kubernetes v1.18?

### ISSUE THREAD

**Issue by aurorazl** [kubeflow/kubeflow#5031]
/kind question

**Question:**
[You can ask any question about this project.]
Any plans for supporting kubernetes v1.18?Are kubeflow 1.10  Compatible with kubernetes 1.18.2?

**Comment by fdasilva59** [comment]
Yes, this would be nice to support latest K8S versions

**Comment by shawnzhu** [comment]
@aurorazl kubeflow 1.0.2 runs on k8s v1.8.2 well when using kfdef https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.2.yaml So please provide details on what doesn't work.

Notice one thing you might need to do is enable istio _SDS_ support. see details from https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#notes-on-the-configuration-file

(If you're using Minikube, please refer to this step in https://github.com/kubeflow/manifests/issues/959#issuecomment-629677950)

**Comment by tduffy000** [comment]
@shawnzhu I assume you meant kubeflow 1.0.2 runs ok on _k8s v1.18.2_? Does that mean [this](https://www.kubeflow.org/docs/started/k8s/overview/) needs updating?

**Comment by shawnzhu** [comment]
@tduffy000 Sorry, I mean k8s v1.18.2. and it works for me. Let me bring this topic in slack to get more inputs.

**Comment by aurorazl** [comment]
@shawnzhu I installed kubeflow 1.0.2 on k8s v1.18.2 using kfctl_k8s_istio.The Kfserving example meets a problem "Cannot POST /v1/models/flowers-sample:predict".Now i try to solve it.

**Comment by tduffy000** [comment]
@aurorazl how are you pinging the endpoint? did you setup the por tforwarding as well?

**Comment by celinew1221** [comment]
Install microk8s 1.18.2 + kubefflow 1.0.0 using kfctl_k8s_istio. KFServing is not working. Got `404 Not Found`

```
inferenceservice.serving.kubeflow.org/flowers-sample created
*   Trying 10.152.183.94...
* TCP_NODELAY set
* Connected to 10.152.183.94 (10.152.183.94) port 80 (#0)
> POST /v1/models/flowers-sample:predict HTTP/1.1
> Host: 
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 16201
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 172
< date: Wed, 03 Jun 2020 18:16:16 GMT
< x-envoy-upstream-service-time: 0
< server: istio-envoy
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/flowers-sample:predict</pre>
</body>
</html>
* Connection #0 to host 10.152.183.94 left intact
```
There is no status for inference service.
```
NAME             URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample                                                    115s
```
Details
```
apiVersion: v1
items:
- apiVersion: serving.kubeflow.org/v1alpha2
  kind: InferenceService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"flowers-sample","namespace":"test"},"spec":{"default":{"predictor":{"tensorflow":{"storageUri":"gs://kfserving-samples/models/tensorflow/flowers"}}}}}
    creationTimestamp: "2020-06-03T18:16:13Z"
    generation: 1
    name: flowers-sample
    namespace: test
    resourceVersion: "10935"
    selfLink: /apis/serving.kubeflow.org/v1alpha2/namespaces/test/inferenceservices/flowers-sample
    uid: bb19b816-d525-40a4-81e1-b9c2924f1042
  spec:
    default:
      predictor:
        tensorflow:
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          runtimeVersion: 1.14.0
          storageUri: gs://kfserving-samples/models/tensorflow/flowers
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
No port-forwarding. Using KFServing tensorflow examples.

The same example is teseted under microk8s 1.15 with the same manifest. Confirmed working.

**Comment by yanniszark** [comment]
Kubeflow should be working for K8s 1.18 (as well as 1.15, 1.16 and 1.17).
The website text is misleading at this point.
We unfortunately don't have CI validation, but we have multiple user reports.
Let's continue discussion on https://github.com/kubeflow/website/pull/1933 to see how we can better communicate this situation to users.

**Comment by tduffy000** [comment]
Thanks for the update @yanniszark 👍

**Comment by shawnzhu** [comment]
The only problem I have so far on k8s v1.18 is the pod `seldon-controller-manager` from `seldon-core-operator:1.1.0` keeps crashing because of https://github.com/SeldonIO/seldon-core/issues/1675 which would be fixed in future release of seldon-core-operator. it also provided a workaround via :

> I was able to work around by installing a crd definition (`seldondeployments.machinelearning.seldon.io`) exported from a successful v1.17 install
