### ISSUE TITLE
Broken Link under Access Kubeflow central dashboard 

### ISSUE THREAD

**Issue by yahavb** [kubeflow/kubeflow#5036]
Under - Access Kubeflow central dashboard

If you are using https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws_cognito.v1.0.2.yaml, run following command to get Kubeflow service endpoint host name and copy link in browser.

The link is broken to kfctl_aws_cognito.v1.0.2.yaml

**Comment by dzungductran** [comment]
I have similar issue as in: https://github.com/kubeflow/kubeflow/issues/5026. I haven't able to get anyone to help on KF community slack channel. I have been searching for solutions of the last week. KF seems to work fine since ML-pipeline seems to work, but centraldashboard does not work.

**Comment by PatrickXYS** [comment]
Right now the link is fine, not sure what happened before.

/close
