### ISSUE TITLE
How can I configure multi-user namespace sharing in kubeflow?

### ISSUE THREAD

**Issue by Minkyu-Choi** [kubeflow/kubeflow#5038]
/kind question

**Question:**
[You can ask any question about this project.]
First of all, thanks for you guys great work.

Our team have deployed kubeflow 1.0 version on air-gapped onprem environment.
And I wonder if kubeflow support following multi-user namespace sharing use-case or not.

1. Admin user(namespace owner) log-in to kubeflow and create profile with namespace.
2. Admin user add other users as contributor to admin's namespace.
3. Normal user log-in to kubeflow as a member of admin's namespace.

Since we don't want to add namespace per user I've tried to add new user as contributor through UI(Manage Contributor menu) before new user log-in to kubeflow but kubeflow requested profile creation.

According to this comment https://github.com/kubeflow/kubeflow/issues/4720#issuecomment-582662941 It seems like kubeflow support multi-user namespace sharing but I couldn't find a way to configure this.

Thanks in advance!

**Comment by marziman** [comment]
Hello,
we have the same issue. We cant add multiple users to a namespace and every user
get his own namespace, which is ressource wise and for other reasons not what we want.

Can anyone help with this topic? Thanks.

**Comment by jlewi** [comment]
KF just uses K8s RBAC and ISTIO  RBAC under the hood. So you should be able to add users to a namespace just by creating appropriate role bindings.

/cc @bmorphism @yanniszark

**Comment by linkvt** [comment]
For us this is also a major issue as everybody with access to the ingress is able to create and use resources in the cluster even if he might not have access to the Kubernetes cluster in general (e.g. via kubectl).
We don't want to give users permissions to create their namespaces effectively bypassing e.g. ResourceQuotas which are set for all other namespaces. This is IMO a massive risk for stable operations of a multi user cluster which often exist on-prem.   

I found a `profiles-cluster-role-binding` cluster role binding which binds to the `cluster-admin` role. Removing this role makes the welcome dialog disappear preventing the creation of a profile, so it seems to be the correct role(binding), there are also logs in the `profiles-deployment` pod that confirm this.

I will check what would be the least restrictive Role(Binding) needed for a readonly profiles management but think, that the `cluster-admin` role shouldn't be given to any of the kubeflow services in general without a real reason...
