### ISSUE TITLE
Finalize proposal for durable storage of K8s spec and status

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#504]
I think I'd like to have a minimal version of a logger for arbitrary subset of K8s resources in our 0.2.0 release.

Filing this issue to track it.

There is a proposal in kubeflow/community#46

**Comment by jlewi** [comment]
HeptIO has a tool Ark that will snapshot all your K8s resources to a tarball. Its primarily intended for backing up  & restoring your cluster but it might be useful for for our use case.

**Comment by ankushagarwal** [comment]
Ack. Will take a look at it.

**Comment by ankushagarwal** [comment]
Do we want to include deploying ark as a ksonnet package on kubeflow repo?

Ark has a lot of k8s manifest files specific to cloud providers checked in [here](https://github.com/heptio/ark/tree/master/examples). Which brings us back to the discussion in https://github.com/kubeflow/kubeflow/issues/376

**Comment by ankushagarwal** [comment]
Probably bootstrap manager can deploy ark based on cloud provider.

**Comment by jlewi** [comment]
@ankushagarwal @kunmingg What is the current status of this issue?

**Comment by kunmingg** [comment]
@jlewi Haven't looked into it.

**Comment by IronPan** [comment]
##  Proposal for kubeflow resource persistence

This proposal is based on the original [proposal](https://github.com/jlewi/community/blob/cdda54d44f94b4c063bbd7c1212b070c39f6ec55/proposals/provenance-logging.md) from @jlewi, with more implementation details.

![screen shot 2018-05-16 at 5 29 18 pm](https://user-images.githubusercontent.com/2348602/40150490-b8986140-592e-11e8-9315-070771261505.png)

The cluster runs an agent that subscribes to K8s API and constantly [watches](https://kubernetes.io/docs/reference/api-concepts/#efficient-detection-of-changes) the K8s resource changes.

The agent runs as a K8s service in the cluster. The Agent pod spec includes the resources to be tracked as pod parameters. User can [update](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)  the spec and do a re deployment to change what's being tracked and what's not. 
```
spec:
      containers:
      - name: persistence-agent
        image: ...
        args: ["workflow", "tfjob", ...]
```

Once the Agent received the K8s events, it [INSERT ... ON DUPLICATE KEY UPDATE](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html) the entry to the database. The database would therefore keep the last state of the resource.

The MySQL DB schema would look like following. The full resource spec would be stored as text in the DB. This way it would never hit the MySQL [row limitation](https://dev.mysql.com/doc/mysql-reslimits-excerpt/5.7/en/column-count-limit.html).

| UUID | kind | apiVersion | object |
| -----|------|------------|--------|
| string | string | string  | [text](https://dev.mysql.com/doc/refman/8.0/en/blob.html) | 

The MySQL can be swapped by Google Cloud SQL, AWS RDS, etc if user doesn't want to manage the mysql instance and the underlying persistent disk.

## Alternatives
Store records in K8s logs
- Storing logs appears to be simpler as we don't need an dedicated Agent. However this requires extra post processing to parse the record and deduplicate the entries before it gets consumed by the subsequent ETL pipelines.

Store records in HBase
- MySQL is lightweight comparing to HBase. MySQL should be capable of handling the data volume of K8s resource events. Using HBase requires either an instance running outside of cluster or non-trivial amount of configurations ([masters & slaves](https://github.com/harryge00/hbase-kubernetes)) to make it run within the cluster.

Backup in Ark
- Per Ark [document](https://heptio.github.io/ark/v0.8.1/about), it creates a tarball snapshot of K8s resources to the object store during backup. As a result, the data is not directly consumable and need non-trivial post process to merge snapshots and deduplicate entries.

**Comment by jlewi** [comment]
Punting to 0.5.0; I don't think we will have cycles to try to do anything in 0.4

**Comment by jlewi** [comment]
Downgrading to P2.

I think this is blocked pending some resolution about our metadata plans.
