### ISSUE TITLE
How to configure the kfserving LoadBalancer

### ISSUE THREAD

**Issue by edenbuaa** [kubeflow/kubeflow#5040]
/kind bug

**What steps did you take and what happened:**
install kubeflow v1.0 in my local kubernates following the instructions here: `https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/` 

And then `kubectl get svc -n istio-system` :
```
NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                                                                                   AGE
istio-ingressgateway       NodePort       10.197.201.239   <none>        15020:32117/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:32222/TCP,15030:30665/TCP,15031:31076/TCP,15032:30469/TCP,15443:31070/TCP                                                3d19h
kfserving-ingressgateway   LoadBalancer   10.197.216.216   <pending>     15020:31822/TCP,80:32380/TCP,443:32390/TCP,31400:32400/TCP,15011:31709/TCP,8060:30059/TCP,853:30405/TCP,15029:31833/TCP,15030:32325/TCP,15031:30220/TCP,15032:30446/TCP,15443:31222/TCP   3d19h
```

the `kfserving-ingressgateway` external ip always `pending`

**What did you expect to happen:**
I want to know how to config the load balancer for my local kubernates cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) 
- Kubernetes version: (use `kubectl version`): v1.15
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by jbottum** [comment]
@yuzisun Hey Dan, Is there someone in the kfserving area that might look at this issue?

**Comment by jbottum** [comment]
@edenbuaa Hi edenbuaa - is this running on GCP ?

**Comment by yuzisun** [comment]
@edenbuaa is this the same issue we have been discussing in https://github.com/kubeflow/kfserving/issues/833 ?

**Comment by edenbuaa** [comment]
@jbottum  it's not running on GCP, it's my local cluster.
@yuzisun this not that question. I want to know how to config a loadbalancer for kfserving or istio in my local cluster.

**Comment by seboktamas** [comment]
Hi, can we use kfserving as part of kubeflow deployment on local cluster, or we must use some cloud provider's infrastructure?
