### ISSUE TITLE
User example@domain.com is not authorized to list .v1.namespaces for namespace: None

### ISSUE THREAD

**Issue by pinglin** [kubeflow/kubeflow#5046]
/kind bug

**What steps did you take and what happened:**

1. Deploy Kubeflow with KFDef [kfctl_istio_dex.v1.0.2 ](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.2.yaml)

2. Login to the Kubeflow dashboard through Dex OIDC and navigate to `Notebooks Servers` page

3. A snack bar pops out showing `User example@domain.com is not authorized to list .v1.namespaces for namespace: None`

But all functions afterwards work normally.

**What did you expect to happen:**

Showing no error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Pod `jupyter-web-app-deployment` logs show
```
10.233.104.162 - - [30/May/2020 02:18:11] "GET /api/namespaces HTTP/1.1" 200 -
10.233.104.162 - - [30/May/2020 02:18:11] "GET /api/namespaces/<namespace>/notebooks HTTP/1.1" 200 -
```
I've tried to trace a bit the source codes. It seems to me that the called [function](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py#L81-L90) decorated by an authorization check [function](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py#L139-L144) will anyway return an error [json](https://github.com/kubeflow/kubeflow/blob/a49f658f047f83b634365a238c6a2ba2baa97c9d/components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py#L99-L102), since there is no namespace argument passed in so the namespace is `None` [here](https://github.com/kubeflow/kubeflow/blob/a49f658f047f83b634365a238c6a2ba2baa97c9d/components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py#L89). 

I was also wondering why `/api/namespaces` needs to be called here?

**Environment:**

- Kubeflow version: build version dev_local
- kfctl version: v1.0.2 (run as Kubeflow operator)
- Kubernetes platform: on-prem
- Kubernetes version: v1.15.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

**Comment by joey100** [comment]
@pinglin I face the same issue. And also may I know whether you face the "RBAC: access denied" issue(the web page shows RBAC: access denied information) several minutes after logining through Dex OIDC? Thanks.

**Comment by ReggieCarey** [comment]
If no one decides to look at a problem, does not make it a non-problem.  Letting your bot close issues simply because no one has the cycles to research them is problematic.  I'm facing this problem and it seems to reveal a larger issue under the hood.  But I don't read go code to figure out what's going on.
