### ISSUE TITLE
kfctl - could not get platform aws Error Failed to create config file from /root/.kube/config

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kubeflow#5047]
Hello All,
I am using https://github.com/kubeflow/kfctl/tree/v1.0.2 kfctl docker image to deploy kubeflow https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ in AWS cloud and used https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml ( i have customized this yaml file )

Details FYI -- Using kubernetes_job resource to run "kfctl apply -V -f ${CONFIG_FILE}" in container at one time.  kfctl is creating kubernetes pods/services.., as per config from kfctl_aws.v1.0.2.yaml , this is triggering while container entrypoint.

Blocker is -- kfctl is not using service account credentials ( attached IAM role has AWS resource creation permission ), that's why kubernetes API server saying system:ananymous forbidden error. kfctl is in inside container ( pods ) and kfctl is looking ~/.kube/config file in PODs itself, but it is not there.

How do we config that kfctl to use service account to create resource in AWS..?? OR
How to say to kfctl to use kubeconfig file credentials..?? OR
Is there any way to fix that error..??

Also i have added namespaces to rules that bind with sa, but still kube/config error from pod/kubeflow,

error 1:-
`
[root@a-3b7daj8kxugj2 devops.aipclouddev.com]# kubectl logs pod/kubeflow-8j6bp -n kubeflow

time="2020-05-28T11:34:20Z" level=info msg="No name specified in KfDef.Metadata.Name; defaulting to aip-cloud-devops-us1 based on location of config file: /opt/kubeflow/aip-cloud-devops-us1/kfctl_aws.yaml." filename="coordinator/coordinator.go:202"
time="2020-05-28T11:34:20Z" level=fatal msg="could not get platform aws Error Failed to create config file from /root/.kube/config **" filename="coordinator/coordinator.go:216"
`

error 2:-
`
module.aip_cloud.module.eks.random_pet.workers[1]: Refreshing state... [id=just-burro]
module.aip_cloud.module.eks.aws_autoscaling_group.workers[0]: Refreshing state... [id=cloud-devops-us1-worker-group-120200511075508666100000009]
module.aip_cloud.module.eks.aws_autoscaling_group.workers[1]: Refreshing state... [id=cloud-devops-us1-kiam-servers2020051107550866620000000a]
module.aip_cloud.module.kubeflow.kubernetes_namespace.kubeflow: Refreshing state... [id=kubeflow]

Error: namespaces "kubeflow" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "kubeflow"

`

**Comment by jbottum** [comment]
@Jeffwan Hi Jiaxin, is there someone that could look at this issue?

**Comment by PatrickXYS** [comment]
You mentioned you have customized the yaml file. 

Would you mind telling us what changes you've made?

**Comment by alexanderDoria** [comment]
I'm having the same issue, went through the default Kubeflow AWS installation guide: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

Complete error: 

> FATA[0000] could not get platform aws Error Failed to create config file from /Users/alexdoria/.kube/config **  filename="coordinator/coordinator.go:216"

**Comment by lkr2des** [comment]
I was encountering probably same or similar error, I had do change back KUBECONFIG back to

export KUBECONFIG=~/.kube/config 

and that overcame the below error for me.

 filename="coordinator/coordinator.go:202"
FATA[0000] could not get platform aws Error Failed to create config file from :/home/lkumar/.kube/config-cdml **  filename="coordinator/coordinator.go:216"

**Comment by Jeffwan** [comment]
> "Error: namespaces "kubeflow" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "kubeflow""

It doesn't seem you use the right IAM. Could you double check `~/.kube/config` and see if you use user with `system:master` access? 

For KUBECONFIG issue, please check this issue. https://github.com/kubeflow/kfctl/pull/300 It should be part of v1.0.2/

**Comment by micemuni** [comment]
Actually i am trying to automate the kubeflow deployment in my existing Kubernetes platform and got the above error during automation. Now used manual steps to setup kubeflow

**Comment by Priapos1004** [comment]
The solution for me was to run the command "aws eks update-kubeconfig --name <clustername>" before deploying the cluster.
