### ISSUE TITLE
[GCP] Cloud Endpoints Controller Doesn't Correctly Handle The Case Where Service Is Being Deleted

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5048]
/kind bug

If you deploy Kubeflow, delete it, and then redeploy with the same then the cloud endpoints controller will fail to create the service. The problem is that the cloud endpoints service will still be in the delete state and needs to be undeleted.

This is described in more detail here:
https://github.com/kubeflow/kubeflow/issues/3230#issuecomment-531532226

The problem is that the CloudEndpoints controller currently doesn't handle this. We should update the controller to handle this.  We should probably also change the controller to no longer use metacontroller and just build it using controller runtime.

Latest code is here:
https://github.com/jlewi/cloud-endpoints-controller

We might also want to move the code into a kubeflow repository.

**Comment by jlewi** [comment]
To check whether you are hitting this problem run the following command

```
gcloud --project=${PROJECT}  endpoints services list
gcloud --project=${PROJECT}  endpoints services describe ${SERVICE NAME}
```

This will tell you if the endpoint exists and if it is in the process of being deleted. If its being deleted you can undelete it

```
gcloud  --project=$PROJECT endpoints services undelete ${SERVICE_NAME}
```

**Comment by Shaked** [comment]
I am currently trying to install kubeflow 1.2 on GCP following https://www.kubeflow.org/docs/gke/deploy/ and I stumbled at the same problem where DNS is not being created. However, I haven't created the service before and it doesn't exist in `gcloud --project=${PROJECT}  endpoints services list`

I also wrote about it in Kubeflow's Slack: 

When I run:
```
$ kubectl -n istio-system get cloudendpoints kubeflow-demo -o yaml
```
I do see that there's a `kubeflow-demo`  object.  Having said that, it doesn't have any status.

Also when I verify the ingress:
```
kubectl -n istio-system get ingress
NAME            CLASS    HOSTS                                                      ADDRESS          PORTS   AGE
envoy-ingress   <none>   kubeflow-demo.endpoints.PROJECT.cloud.goog   XX.YYY.ZZZ.LLL   80      4h56m
```

However, when I check `gcloud` it seems like it doesn't exist:
```
gcloud --project=${KF_PROJECT} endpoints services list | grep kubeflow-demo
```

**Comment by ulrikpl** [comment]
I am having the same problem as Shaked installing Kubeflow on GCP. Did anyone find a solution?

**Comment by JohanWork** [comment]
I am also having this issue, happened to me after deleting the deployment and trying to set it up again.

**Comment by Shaked** [comment]
@ulrikpl @JohanWork  please check https://github.com/kubeflow/gcp-blueprints/issues/198

**Comment by andreyvelich** [comment]
We can close it.
