### ISSUE TITLE
Have the JupyterHub spawner report issues with spawning the user's server

### ISSUE THREAD

**Issue by ojarjur** [kubeflow/kubeflow#505]
Right now, if you use the JupyterHub spawner to spawn a server, and the corresponding notebook server fails to start, then you can wind up just seeing a 500-error page with no details (after which, you have to resort to running `kubectl get ...` to debug the issue).

I think a lot of potential user confusion/frustration could be avoided if we could report the underlying issue on the error page instead of only showing a 500-error.

For example, the first time I tried using Kubeflow, I got an issue where I had accidentally undersized my cluster, so my server failed to start because the pod couldn't be scheduled. If the issue was made clear by the JupyterHub UI, then I would have resolved the issue much faster than I did.

I would like to report at least the following potential sources of errors if they occur:

1. Specifying an image name that does not exist (e.g. due to a copy-and-paste error)
2. Permissions issues downloading the specified image.
3. Timeouts while downloading the image.
4. Pods that fail to schedule.

There may be some parts of this that warrant upstream contributions to JupyterHub, but we should still have at tracking issue in Kubeflow for it, since the KubeFormSpawner would need to incorporate whatever eventually gets built for this.

**Comment by jlewi** [comment]
@pdmack Are you making progress? Do you need help?

**Comment by pdmack** [comment]
@jlewi no progress here sadly. Been fighting #561 etc. Feel free to re-assign, or I could switch off maybe if we are re-stacking priorities for 0.2.

**Comment by pdmack** [comment]
jupyterhub/kubespawner/#153

I've asked on gitter when we might expect another kubespawner release.

**Comment by pdmack** [comment]
Sounds like we will get this simultaneously with the official JH 0.9 release. @willingc ?

**Comment by jlewi** [comment]
#905 upgrade JupyterHub and KubeSpawner.

The new UI is much better. There is a status bar and it looks like it shows K8s events related to the pod as well.

I'm going to mark this as fixed with the expectation that we will file new issues related to the latest version of JupyterHub and KubeSpawner as needed.

**Comment by clkao** [comment]
Very glad to see this getting into kubeflow! Special thanks to @minrk for the progress api implementation in jupyterhub as well as reviewing my initial PR.
