### ISSUE TITLE
dashboard does not support https

### ISSUE THREAD

**Issue by yahavb** [kubeflow/kubeflow#5050]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The kubeflow dashboard istio-ingressgateway does not support https so the cognito call-back URL is not working. 

**What did you expect to happen:**
Per https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ after executing `kubectl patch service -n istio-system istio-ingressgateway -p '{"spec": {"type": "LoadBalancer"}}'` and setting the `certArn` from ACM (certificate manager), the dashboard endpoint does not respond to https requests

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): `build version dev_local`
- kfctl version: (use `kfctl version`): `kfctl v1.0.2-0-ga476281`
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): Client Mac, Server Linux

**Comment by PatrickXYS** [comment]
If you follow this page https://www.kubeflow.org/docs/aws/authentication/, you don't have to modify `istio-ingressgateway` but directly use ingress for cognito.
