### ISSUE TITLE
[AWS] Kubeflow 1.1 pending issues

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5057]
/kind feature

- [X] Update IRSA to include Region info in the name. Otherwise, different region kubeflow cluster will result in conflict IAM role names. 
- [ ]  Easily setup AWS RDS in kubeflow_aws.yaml and we need corresponding changes in kfctl
- [X] Either enable basic auth or use dex for kubeflow_aws.yaml to provide a non Cognito (AWS managed Service) solution
- [X] Upgrade istio to 1.3.1 or higher version
- [X]  Add an option for AWS jupyter notebook image.
- [x] Graduate MXNet to v1 and add into manifest.
- [x] Enable IRSA by default in AWS KFDefs
- [ ] V3 manifests.

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Comment by cloudbow** [comment]
* Make istio ingress generate an alb with lor(least outstanding request) algorithm as the default as part of target group loadbalancing.

**Comment by Jeffwan** [comment]
@cloudbow I see Slack #aws channel has some asks on this. I think the ALB version we are using covers this feature and user can enable it using an annotation. I am not sure if we should make it default algorithm. Probably needs more data points or more explanation why this is needed as default.

**Comment by cloudbow** [comment]
ok, can we have doc item which says how to do this with kustomize ?

**Comment by cloudbow** [comment]
* Show available memory and cpu for creating new pods as part of the drop down so that the pod won't end up in pod intializing state

**Comment by cloudbow** [comment]
I have tried installed grafana dashboars to find out the total cpu requested but what I found is that since the requests are not fully reserving the memory , the used memory will not show the requested memory . For eg; if someone requested for 10GB for notebook server its shown as used by any unix system since the memory is not allocated yet. But the request will get rejected even when no where its shown that its yet used.

**Comment by jlewi** [comment]
@Jeffwan update?

**Comment by Jeffwan** [comment]
@jlewi The left two things will be postponed to next release. for 1.1, aws side is good.
