### ISSUE TITLE
Cut a 0.1 release

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#506]
Tracking bug for cutting a 0.1 release

TODO

- [X] Update the TFJob image to pull in fixes to kubeflow/tf-operator#500
- [X] Create a tag/branch for our ksonnet configs
- [X] Update the Jupyter Images that our configs point to.
- [X] Update Docs to point to branch

Things to verify manually

- [ ] IAP works 
- [ ] TFJobs UI works
- [ ] Can spawn notebooks
- [ ] TFCNN runs

**Comment by jlewi** [comment]
Branch has been cut
https://github.com/kubeflow/kubeflow/tree/v0.1-branch

**Comment by jlewi** [comment]
Create a release candidate
https://github.com/kubeflow/kubeflow/releases/tag/v0.1.0-rc.0

**Comment by jlewi** [comment]
We should cherry pick #548 which fixes the TFJob UI ksonnet configs into the component.

**Comment by pdmack** [comment]
kubeflow/kubeflow#541

**Comment by jlewi** [comment]
Its official v0.1.0
https://github.com/kubeflow/kubeflow/releases/tag/v0.1.0

Will send a PR updating the docs.
