### ISSUE TITLE
[Release 1.1] Release Jupyter

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5060]
/kind process

Opening this issue to track releasing jupyter for Kubeflow 1.1

Per #5022 we need the following

* Updated docker images (for controller, JWA, and notebook images kubeflow/kubeflow#4789)
* Updated manifests
* Updated docs

**Comment by jlewi** [comment]
We are still looking for an area owner for notebooks.

@jtfogarty I think you mentioned you might be interested?

@aronchick You also expressed interest in leading notebooks?

**Comment by vpavlin** [comment]
@jlewi A few people from our team started to look into notebook controller recently and would be happy to help with the release - cc @4n4nd @durandom

**Comment by jlewi** [comment]
Here are some relevant issues:

* Our [CD infra](https://github.com/kubeflow/testing/tree/master/apps-cd#kubeflow-cd-with-tektoncd-pipelines) is described here
   * Ideally the controller and web app images are continuously being built and PRs are being opened against kubeflow/manifests
   * It looks like PRs are being [opened](https://github.com/kubeflow/manifests/pulls/kubeflow-bot) but the tests aren't passing
   * We likely need to make some updates as well given the refactoring of the manifests
* #4789 - Is tracking CD for the notebook images themselves

  * We will either need to fix that or figure out how to give people permissions to do manual builds

/cc @kimwnasptd

**Comment by kimwnasptd** [comment]
@jlewi I could take a stab at the 
* Update manifests
* Update the docs with the current state of Notebooks

I don't think I have the bandwidth for #4789 right now. But we could just update JWA's config yaml with the correct images for the release, until a proper fix for #4789 will be available

**Comment by jlewi** [comment]
/assign @kimwnasptd 

Are we on track on to have an RC by 06/19?

**Comment by kimwnasptd** [comment]
@jlewi I think I won't be able to make it until the end of this week.
But if it's ok I am very confident that I can have them ready in the next week

**Comment by jlewi** [comment]
@kimwnasptd 

* the apps cd pipelines have been fixed
* application owners please review PRs to update your apps and ensure they get merged
    * https://github.com/kubeflow/manifests/pulls/kubeflow-bot

**Comment by jlewi** [comment]
@kimwnasptd What's the status of Jupyter for 1.1?  It looks like the docs still need to be updated.
https://www.kubeflow.org/docs/notebooks/why-use-jupyter-notebook/

/cc @kimwnasptd @StefanoFioravanzo
