### ISSUE TITLE
Jupyter notebook creation UI parsing error resulting in blocking notebook creation in all profiles

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#5064]
/kind bug

**What steps did you take and what happened:**
- Create a notebook server from UI
- In 'Memory' field, modify '1.0Gi' to '1.0GB'
- Click 'Launch'
- The new notebook server keep spinning and doesn't finish creating
- Further more, all other new notebooks creation in any profile will fail
- When looking at notebook controller, I see this error:

```
"E0604 23:25:47.018560       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.Notebook: v1beta1.NotebookList.Items: []v1beta1.Notebook: v1beta1.Notebook.Spec: v1beta1.NotebookSpec.Template: v1beta1.NotebookTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|y":"2.0GB"}},"volume|..., bigger context ...|resources":{"requests":{"cpu":"2","memory":"2.0GB"}},"volumeMounts":[{"mountPath":"/home/jovyan","na|..."` 
```

- It wasn't obvious to determine which notebook was the problem, but we figured it out in an ad-hoc fashion and had to use kubectl to delete that notebook manually to unblock.

**What did you expect to happen:**
- Creation fails at UI due to parsing error because of 'GB' instead of 'Gi' and tell the user to fix that (Rather than resulting in blocking all notebook server creation in any profile until that notebook is deleted manually using kubectl by admin!)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- kfctl version: (use `kfctl version`): kfctl v1.0-0-g94c35cf
- Kubernetes platform: EKS
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.5

**Comment by hopper-signifyd** [comment]
@DavidSpek Was this issue actually fixed or just marked as frozen?

**Comment by yangSignifyd** [comment]
Hey @DavidSpek, could we bring this up again since it seems a bug from Kubeflow?
