### ISSUE TITLE
[Release 1.1] Multi-user release

### ISSUE THREAD

**Issue by bmorphism** [kubeflow/kubeflow#5067]
/kind process

Opening this issue to track releasing multi-user for Kubeflow 1.1 and would like to add area OWNERS for @bmorphism and @yanniszark 

Per #5022 and Slack discussion in #release we need the following.

- manifests for GitOps-type deployment of Kubeflow for https://github.com/kubeflow/manifests/issues/1136

- more broadly, incl. for existing model, multi-user enhancements tracked in #4960 and worked on by @yanniszark

**Comment by jlewi** [comment]
The following artifacts should be included as part of multi-user release.

* profile controller - https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller
* kfam - https://github.com/kubeflow/kubeflow/tree/master/components/access-management

The images need to be built and the kustomize manifests need to be updated.

The images and PRs should get built automatically via the CD pipeline
https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml

The PRs will need to be approved to be merged.

There are some issues with the apps-cd pipeline: kubeflow/testing#631

@bmorphism @yanniszark please keep on kubeflow/testing#631 to see if it gets fixed to unblock updates of the multi-user applications.

**Comment by jlewi** [comment]
* the apps cd pipelines have been fixed
* application owners please review PRs to update your apps and ensure they get merged
    * https://github.com/kubeflow/manifests/pulls/kubeflow-bot

/cc @bmorphism @yanniszark

**Comment by jlewi** [comment]
@bmorphism @yanniszark any update?

**Comment by jlewi** [comment]
@bmorphism @yanniszark any update?
