### ISSUE TITLE
Continuous testing for release branches

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#507]
Background
   #215 Create a release process

The current thinking is to create a release branch for our ksonnet configs.
We'll need a way to run presubmits and post submits on the branch.

When using a branch do the prow environment variables provide information that lets us know we are on a branch?

**Comment by jlewi** [comment]
@krzyzacy @BenTheElder Is it possible to configure a prow job to run on all branches? Or do I need to manually list branches I want it to run on.

**Comment by krzyzacy** [comment]
prowjob runs on all branches by default :-) just don't specify a branch field

**Comment by jlewi** [comment]
Great thanks.

@gaocegege as an FYI since you were asking how to enable the tests for our TFJob branches
