### ISSUE TITLE
"kfctl apply" fails on Istio 1.6.x

### ISSUE THREAD

**Issue by AndriiNeverov** [kubeflow/kubeflow#5070]
/kind bug

**What steps did you take and what happened:**

Installed Istio (tried 1.6.0, 1.6.2) using the "default" profile

kfctl apply -V -f kfctl_istio_dex.yaml # with istio-crds and istio-install removed and set clusterRbacConfig to OFF due to "RBAC: access denied"

```
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-admin configured
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-edit unchanged
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-view unchanged
configmap/istio-parameters-t6hhgfg9k2 unchanged
gateway.networking.istio.io/kubeflow-gateway unchanged
serviceentry.networking.istio.io/google-api-entry unchanged
serviceentry.networking.istio.io/google-storage-api-entry unchanged
virtualservice.networking.istio.io/grafana-vs unchanged
clusterrbacconfig.rbac.istio.io/default unchanged
WARN[0563] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout799007708": admission webhook "validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host  filename="kustomize/kustomize.go:202"
WARN[0563] Will retry in 41 seconds.                     filename="kustomize/kustomize.go:203"
```

**What did you expect to happen:**

"apply" step to complete.

**Anything else you would like to add:**

Works on Istio 1.4.9, 1.5.5.

**Environment:**

- Kubeflow version: 1.0.0
- kfctl version: kfctl v1.0-0-g94c35cf
- Kubernetes platform: VMware TKG
- Kubernetes version: v1.16.3+vmware.1
- OS (e.g. from `/etc/os-release`): MacOS 10.13.6

**Comment by jlewi** [comment]
I don't think ISTIO 1.6 is supported yet. IIUC alot of things changed in ISTIO 1.6

/cc @krishnadurai @yanniszark

**Comment by apryiomka** [comment]
@AndriiNeverov , we had the same error, fixed by editing the [generated kustomize manifest](https://github.com/kubeflow/manifests/blob/master/istio/istio/base/kf-istio-resources.yaml#L60-L64):
```
 tls:
  - match:
    - port: 443
      sniHosts:
      - www.googleapis.com
```

`sni_hosts` was renamed to `sniHosts` and in 1.6 they stopped supporting `sni_hosts`.

**Comment by dbuades** [comment]
> @AndriiNeverov , we had the same error, fixed by editing the [generated kustomize manifest](https://github.com/kubeflow/manifests/blob/master/istio/istio/base/kf-istio-resources.yaml#L60-L64):
> 
> ```
>  tls:
>   - match:
>     - port: 443
>       sniHosts:
>       - www.googleapis.com
> ```
> 
> `sni_hosts` was renamed to `sniHosts` and in 1.6 they stopped supporting `sni_hosts`.

That was it, thank you very much!

**Comment by fryzhykau** [comment]
> @AndriiNeverov , we had the same error, fixed by editing the [generated kustomize manifest](https://github.com/kubeflow/manifests/blob/master/istio/istio/base/kf-istio-resources.yaml#L60-L64):
> 
> ```
>  tls:
>   - match:
>     - port: 443
>       sniHosts:
>       - www.googleapis.com
> ```
> 
> `sni_hosts` was renamed to `sniHosts` and in 1.6 they stopped supporting `sni_hosts`.

Could you please point to the file where you have applied this change (in regards to the recent kubeflow 1.2.0 release for example)? Previous link doesn't work.
Trying to make it work with istio 1.6.14 as recommended on the docs pages.
