### ISSUE TITLE
kfctl_aws_cognito.v1.0.2.yaml couldn't copy  istio-ingress and aws-istio-authz-adaptor

### ISSUE THREAD

**Issue by malawskim** [kubeflow/kubeflow#5072]
/kind bug

**What steps did you take and what happened:**
I am not able to install kubeflow using kfct_aws_cognito.v.1.0.2.yaml.
kfctl apply -V -f kfct_aws_cognito.v.1.0.2.yaml
...
...
"failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for istio-ingress Error absolute path error in 'roles/infra/apps/kustomize/istio-ingress' : evalsymlink failure on 'roles/infra/apps/kustomize/istio-ingress' : lstat /infra/apps/kustomize/istio-ingress: no such file or directory"]}
the same happens with aws-istio-authz-adaptor

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):kfctl v1.0.2-0-ga476281
- Kubernetes platform: EKS 1.15
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15+",GitVersion:"v1.15.10-eks-bac369"
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf"
- OS (e.g. from `/etc/os-release`): macOs Catalina

**Comment by Jeffwan** [comment]
` Error absolute path error in 'roles/infra/apps/kustomize/istio-ingress' : evalsymlink failure on 'roles/infra/apps/kustomize/istio-ingress' : lstat /infra/apps/kustomize/istio-ingress: no such file or directory"]}
the same happens with aws-istio-authz-adaptor`

em.. Can you check the folder? and also check `.cache/` folder if you can find `istio-ingress`?

**Comment by malawskim** [comment]
@Jeffwan Looks like it might be related to the Mac OS version - Catalina 10.15.4 (19E287). I was able to run it without any errors on different Linux machine.

**Comment by malawskim** [comment]
> ` Error absolute path error in 'roles/infra/apps/kustomize/istio-ingress' : evalsymlink failure on 'roles/infra/apps/kustomize/istio-ingress' : lstat /infra/apps/kustomize/istio-ingress: no such file or directory"]} the same happens with aws-istio-authz-adaptor`
> 
> em.. Can you check the folder? and also check `.cache/` folder if you can find `istio-ingress`?

No, it is not present there.
