### ISSUE TITLE
GPU use display by Notebook Servers

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/kubeflow#5073]
/kind feature

**Why you need this feature:**
Once a team profile is created and multiple data scientists spin up notebook servers with out knowing how much of GPU capacity is already used. Current Notebook server dashboard displays CPU, Memory and Image name but not the GPUs used.  Displaying GPUs used by notebook servers help avoid confusion with in the team on whether the resources are still available to use.

**Describe the solution you'd like:**
Display GPUs on the Notebook servers page
![image](https://user-images.githubusercontent.com/8292387/84796357-63fdc580-afad-11ea-976f-7646177da84b.png)
Will submit a PR for this to address the same.

**Anything else you would like to add:**
Above Notebook server spinning due to lack of gpu resources

**Comment by jlewi** [comment]
@lalithvaka These changes are landing pretty late for 1.1. Before cherry-picking it into 1.1 please manually verify that it is working on master.  You could also talk to @kimwnasptd to see where we are in terms of an E2E test that could verify the UI is working.
