### ISSUE TITLE
How to expose the central dashboard with an external nginx.

### ISSUE THREAD

**Issue by ducminhnguyen** [kubeflow/kubeflow#5078]
/kind question

Hi, I am trying to expose the central dashboard to external users. I am deploying kubeflow on-prem and have it ingress at port 31380. However, when I try to connect nginx to that port with 
```
server {
        listen          80;
        server_name     mylink.com;
        location / {
                proxy_pass http://10.10.10.10:31380;
        }
}
```
The browser always return 426 code and does not load the webpage.
![image](https://user-images.githubusercontent.com/5888561/85013979-0da0aa80-b198-11ea-93db-a530505d103f.png)

I also try to make the centraldashboard service to be nodePort and expose at 30080 and have the same nginx config as above, this approach can load the front page but cannot load other pages.
Front page:
![image](https://user-images.githubusercontent.com/5888561/85013681-92d78f80-b197-11ea-81e3-b155091f6aac.png)
Subpages:
![image](https://user-images.githubusercontent.com/5888561/85013780-bef31080-b197-11ea-80ca-a2644cad636f.png)

**Comment by Enzo90910** [comment]
Here's how I managed to do it: I left the Istio installed by kubeflow alone, and I added a Nginx Ingress to my cluster, opening 80/443 ports on all nodes. I have an Ingress rule which makes the Nginx-Ingress proxy the Istio services follows:
`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubeflow
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: myhttpscert
  rules:
    - host: kubeflow.mycompany.com
      http:
       paths:
        - path: /.*
          backend:
            serviceName: istio-ingressgateway
            servicePort: 80
`

**Comment by Enzo90910** [comment]
I think I also changed the istio-ingressgateway service from NodePort to ClusterIP.

**Comment by sorowakers** [comment]
You need to use the following configuration in your external nginx host configuration

`server {                                         
    listen 80;                              
    server_name mylink.com;                                                     
    location / {                                 
       proxy_pass http://10.10.10.10:31380;   
       proxy_http_version 1.1;                   
       proxy_set_header Upgrade $http_upgrade;   
       proxy_set_header Connection "Upgrade";    
       proxy_set_header Host $host;              
       proxy_pass_header Authorization;          
       proxy_set_header Accept-Encoding "";      
    }                                            
}                                                `
