### ISSUE TITLE
Failed to install on EKS1.15 and EKS1.16 1.0.2 with cognito

### ISSUE THREAD

**Issue by prabhatsharma** [kubeflow/kubeflow#5079]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Failed to install on EKS1.15 and EKS1.16 1.0.2 with cognito

`
INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:71"
INFO[0000] eksctl version: 0.21.0                        filename="utils/awsutil.go:88"
INFO[0000] 
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] /home/ubuntu/environment/main1/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
INFO[0000] Folder /home/ubuntu/environment/main1/aws_config exists, skip aws.Generate  filename="aws/aws.go:438"
INFO[0000] folder /home/ubuntu/environment/main1/kustomize exists, skip kustomize.Generate  filename="kustomize/kustomize.go:372"
INFO[0000] /home/ubuntu/environment/main1/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
INFO[0000] Caller ARN Info: {
  Account: "107995894928",
  Arn: "arn:aws:sts::107995894928:assumed-role/role1/i-06cb9dee07de5ddbc",
  UserId: "ABCDEFGHTRDRIY:i-06cb9dee07de5ddbc"
}  filename="utils/awsutil.go:41"
INFO[0000] ManagedCluster set defaulting to false        filename="aws/aws.go:651"
INFO[0000] EnableNodeGroupLog set defaulting to false    filename="aws/aws.go:661"
INFO[0000] You already have cluster setup. Skip creating new eks cluster.   filename="aws/eks.go:95"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: Could not determinte it's EKS cluster MissingRegion: could not find region configuration
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: Could not determinte it's EKS cluster MissingRegion: could not find region configuration

`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

`
spec:
      auth:
        cognito:
          certArn: arn:aws:acm:us-west-2:107995894928:certificate/1121331-4ae5-4fe2-8eb5-21312312
          cognitoAppClientId: 4e1o3fguhghfghjg6desnap
          cognitoUserPoolArn: arn:aws:cognito-idp:us-west-2:123456789:userpool/us-west-2_U6X9q646465
          cognitoUserPoolDomain: cognito.prabhatsharma.com
      enablePodIamPolicy: true
      region: us-west-2

`

- Kubeflow version: 1.0.2
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: EKS 1.16 and EKS 1.15 managed nodes
- Kubernetes version: (use `kubectl version`): kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): Amazon Linux

**Comment by Jeffwan** [comment]
```
Code 400 with message: Could not determinte it's EKS cluster MissingRegion: could not find region configuration
```

Seems you miss region information, can you check your KFDef file and if region is missing? 
@prabhatsharma
