### ISSUE TITLE
Does MiniKF run on anything?

### ISSUE THREAD

**Issue by gitpushdashf** [kubeflow/kubeflow#5081]
I've tried following guides to install MiniKF on the following:

 * Mint 19: Vagrant version too old.
 * Ubuntu 18.04: Vagrant version too old. snap method with microk8s failed, some DNS resolution error where api.jujujusomething resolved to a 10.X.X.X address (even though it resolved to a non-LAN address with `host`).
 * Ubuntu 20.04 Vagrant version is good, but that install method fails. Slightly different error with snap/microk8s.

These are all fresh, vanilla installs with a 8 core, 32GB memory machine.

What exactly *does* MiniKF run on? I'd like to give it a try but I'm having no luck getting it to run regardless of what I test with. I figure I've tested the most common distributions and versions, of course there's certainly others.

Thank you!

**Comment by 8bitmp3** [comment]
@gitpushdashf for Ubuntu 18 and Min 19, do you get a "Vagrant version too old" (< v2.2.9) error when running `vagrant init arrikto/minikf`?

**Comment by yanniszark** [comment]
Hi @gitpushdashf! Let's try to get you up-and-running asap!
I have some questions regarding your installation:
* What instructions are you following? These are the official instructions: https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/
* How are you installing Vagrant? If you are installing via package manager, maybe you should get one of the latest versions from the vagrant downloads (link in the docs above)
* You are talking about MicroK8s errors but MiniKF doesn't use it. Is this orthogonal to the MiniKF issue?
* For Ubuntu 20.04, you mention:
    > Ubuntu 20.04 Vagrant version is good, but that install method fails.

  Can you share more about the error you get in that case?

**Comment by gitpushdashf** [comment]
I appreciate your replies.

> @gitpushdashf for Ubuntu 18 and Min 19, do you get a "Vagrant version too old" (< v2.2.9) error when running vagrant init arrikto/minikf?

Yes.

> What instructions are you following? These are the official instructions: https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/

All of the instructions I've followed have been the official ones, like the one you linked to.

> How are you installing Vagrant? If you are installing via package manager, maybe you should get one of the latest versions from the vagrant downloads (link in the docs above)

Local package manager. I didn't realize I should install it upstream.

> You are talking about MicroK8s errors but MiniKF doesn't use it. Is this orthogonal to the MiniKF issue?

I followed the microk8s guide for MiniKF and never got it to work for me. Actually, that's not true. On 18.04 I was eventually able to get MiniKF working on microk8s if I did `snap install --classic --edge microk8s`.

As for the 20.04 Vagrant issue, I'll have to rerun to show you.

I am curious though, on what systems have the instructions *just worked* for any of you?

**Comment by yanniszark** [comment]
@gitpushdashf there is likely some misunderstanding regarding this part:

> I followed the microk8s guide for MiniKF

There is no microk8s guide for MiniKF. MiniKF doesn't use microk8s in any shape or form. Can you link to what you're referring to?

If you are using microk8s then you are NOT using MiniKF, but something else.

> I am curious though, on what systems have the instructions just worked for any of you?

The goal with MiniKF is to be as portable as possible. That's why we use Vagrant to run on top of any OS that can run Vagrant (Linux, MacOS, Windows).

**Comment by gitpushdashf** [comment]
You're right, this is what I was following: https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/#install-kubeflow-using-microk8s

I will try MiniKF on Ubuntu 20.04 and report back.

**Comment by gitpushdashf** [comment]
Ok, fresh Ubuntu 20.04. I let it apply updates, rebooted.

Installed upstream Vagrant and Virtualbox.

I went to 10.10.10.10 for the in-browser VNC-esque page.

After a long time, it errored with this inside the VNC window thing:

```
An unexpected exception has occured
Line: build/bdist.linux-x86_64/egg/rok_common/cmdutils.py:942
Type: CommandExecutionError
Reason: Command `<ExtCommand [xJGw3S3QVkk] `kubectl get jobs -o json -n rok', status=FINISHED (ret: 1), PID=29151, shell=False>' failed. Error log: Unable to connect to the server: http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=NO_ERROR, debug=""\n

The logfile `/home/vagrant/provision.log' may contain more information on this error, including a backtrace.

*** MiniKF provisioning tool terminated. Press Enter to restart, Ctrl-C to exit... ***
```

I think that's the same error that I had the first time trying MiniKF on 20.04.

**Comment by ja06200** [comment]
I had same error with Ubuntu 20.04.

Works fine with Ubuntu 18.04

**Comment by yanniszark** [comment]
@gitpushdashf can you please send us some logs to debug further? Here's how to do it:
1. `vagrant ssh` into your MiniKF VM
2. run `minikf-gather-logs`. This will produce a tarball `.tgz` file in your
   MiniKF directory.
3. Please share the tarball here

This will help us debug your problem and see how we can help further.
Also, you could try with Ubuntu 18.04 (as you said you have it available) as @ja06200 mentioned.

**Comment by gitpushdashf** [comment]
I had shut down the box with Ubuntu 20.04. I booted it back up, ran `vagrant up`, then `minikf-gather-logs`.

It's a curses-style dialog and almost got to the end, then I had this error.

```An unexpected exception has occured
Line: /usr/lib/python2.7/shutil.py:208
Type: Error
Reason: [('/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log', '/tmp/minikf-gather-logs-mzytwy/minikf-logs-20200622-152040/host/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log', "[Errno 2] No such file or directory: '/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log'"), ('/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log', '/tmp/minikf-gather-logs-mzytwy/minikf-logs-20200622-152040/host/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log', "[Errno 2] No such file or directory: '/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log'")]
```

Seems like it doesn't work unless the install finishes. Might need some try/excepts or something.

I'll give 18.04 a try later. I suspect reproducing this on 20.04 is pretty straightforward though since @ ja06200 had the same issue.

**Comment by gitpushdashf** [comment]
Vanilla 18.04 with apt Virtualbox and upstream Vagrant also failed.

```
An unexpected exception has occured
Line: build/bdist.linux-x86_64/egg/rok_common/cmdutils.py:942
Type: CommandExecutionError
Reason: Command `<ExtCommand [SwR4soxsnzo] `kubectl get pods -o json -n rok', status=FINISHED (ret: 1), PID=29089, shell=False>' failed. Error log: Unable to connect to the server: stream error: stream ID 1; INTERNAL_ERROR\n

The logfile `/home/vagrant/provision.log' may contain more information on this error, including a backtrace.

*** MiniKF provisioning tool terminated. Press Enter to restart, Ctrl-C to exit... ***
```

`mini-kf-gather-logs`:

```
An unexpected exception has occured
Line: /usr/lib/python2.7/shutil.py:208
Type: Error
Reason: [('/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log', '/tmp/minikf-gather-logs-tRhShi/minikf-logs-20200622-180132/host/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log', "[Errno 2] No such file or directory: '/var/log/pods/kube-system_kube-addon-manager-minikube_0abcb7a1f0c9c0ebc9ec348ffdfb220c/kube-addon-manager/1.log'"), ('/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log', '/tmp/minikf-gather-logs-tRhShi/minikf-logs-20200622-180132/host/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log', "[Errno 2] No such file or directory: '/var/log/pods/kube-system_etcd-minikube_27e2185ad1fe3cab5483ad2bcc420391/etcd/1.log'")]

The logfile `/home/vagrant/gather-logs.log' may contain more information on this error, including a backtrace.
```

[gather-logs.log](https://github.com/kubeflow/kubeflow/files/4814890/gather-logs.log)

**Comment by Madhav111** [comment]
Hi @yanniszark ,

I am  trying to install the Kubeflow  from  my windows 10. After following the standard guidelines like downloading the Vagrant and  VirtualBox then opened the http://10.10.10.10/ for installation of MiniKF.

I am repeatedly getting the  below error as below.

 unexpected exception has occured
Line: build/bdist.linux-x86_64/egg/rok_common/cmdutils.py:942
Type: CommandExecutionError
Reason: Command `<ExtCommand [cyHd4gn7U2E] `kubectl get jobs -o json -n kubeflow', status=FINISHED (ret: 1), PID=12415, shell=False>' failed. Error log: Unable to connect to the server: http2: server sent GOAWAY and closed the connection; LastStreamID=7, ErrCode=NO_ERROR, debug=""\n

The logfile `/home/vagrant/provision.log' may contain more information on this error, including a backtrace.

*** MiniKF provisioning tool terminated. Press Enter to restart, Ctrl-C to exit... ***

Please advice on this.

Thanks
Madhav

**Comment by Madhav111** [comment]
@yanniszark  occurance of error at the kubeflow pods updation.

**Comment by yanniszark** [comment]
@gitpushdashf there is definitely a bug in the `gather-logs` script and we will be working on solving it.
For your particular case (@Madhav111 as well), can you tell me what your VM specs are?
The normal amount of memory we allocate for Vagrant is 10GB but sometimes that's not enough.
Can you try bumping the amount of memory in the Vagrantfile and retry?

**Comment by Madhav111** [comment]
@yanniszark Its 16 GB Laptop and VM automatically allocated  with 10 GB.
I have tried with several ways to alter the memory of the VM through Vagrantfile  but not able  to update the  memory.
Kindly advice.
Also when can we expect this issue  fix.
Thanks
Madhav

**Comment by phansoks** [comment]
> @yanniszark Its 16 GB Laptop and VM automatically allocated with 10 GB.
> I have tried with several ways to alter the memory of the VM through Vagrantfile but not able to update the memory.
> Kindly advice.
> Also when can we expect this issue fix.I am seriously waiting for the bug fix.Lots of work is awaiting.
> Please take this on priority.
> Thanks
> Madhav

@Madhav111, I was able to increase my VM memory with following lines on my Vagrantfile.
````
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "32768"
		vb.cpus = "12"
	end  
````

**Comment by yanniszark** [comment]
Thanks @phansoks !
There has been a new MiniKF release since this issue was created.
If any of the above is still an issue with the new version, please create a new issue.
/close
