### ISSUE TITLE
Jupyter New Server Web UI should report warnings of FailedCreate

### ISSUE THREAD

**Issue by yashjakhotiya** [kubeflow/kubeflow#5085]
/kind feature

**Why you need this feature:**
When deploying a new Jupyter notebook server, the web UI was stuck. Running kubectl -n kubeflow-mailsforyashj describe notebooks showed a FailedCreate warning. Turned out, notebook server names and corresponding pod names can only contain alphanumeric characters and hyphens('-'). The Web UI did not report this either during typing notebook server name or during the wait for the server to come up. 

**Describe the solution you'd like:**
The Web UI should report FailedCreate warnings.
The Web UI should have data validation for notebook names.

**Anything else you would like to add:**
None

**Comment by thesuperzapper** [comment]
@yanniszark  This is more generally an issue with the notebook controller not propagating issues from the `StatefullSet` to the `Notebook` CRD.

We should ensure that the `status:` field of the `Notebook` is populated with issues from the `StatefulSet` and `Persistent VolumeClaims`.
