### ISSUE TITLE
Alow PersistentVolumeClaim resizing in UI

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#5092]
/kind feature

**Why you need this feature:**
Currently, if a user has run out of space in their workspace volume, they must use `kubectl` to increase the size of the claim:
`kubectl edit pvc/workspace-XXXX --namespace XXX` 

**Describe the solution you'd like:**
We should allow users to change their PVC size somewhere in the UI, I think we could either:
1. Create a button like `edit volumes` on the running Notebook Servers UI
1. Create a new page in the hamburger menu called `volumes`, which has overviews of all volumes in the current namespace, with ability to edit/delete them.

**Comment by kimwnasptd** [comment]
/lifecycle frozen

Lets discuss about adding this functionality in the Volumes web app #4758.

**Comment by andreyvelich** [comment]
This should be resolved as part of: https://github.com/kubeflow/kubeflow/pull/5684
