### ISSUE TITLE
Model Registry

### ISSUE THREAD

**Issue by amybachir** [kubeflow/kubeflow#5093]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Model Registry to manage models and their versions.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
Is there a plan to add a model registry similar to the MLFlow's feature https://mlflow.org/docs/latest/model-registry.html

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
@amybachir Have you thought about just using MLFlow's model registry with Kubeflow?

/cc @karlshriek

**Comment by amybachir** [comment]
> @amybachir Have you thought about just using MLFlow's model registry with Kubeflow?
> 
> /cc @karlshriek

@jlewi  Yep! That's the setup I have now. It's not too complex but I'd like to eliminate yet another piece that I have to maintain, MLflow, if possible. Also, I'm running everything in Kubernetes but MLflow is not Knative so it makes it more difficult to integrate and maintain in a Kubernetes setup.

I like MLflow's tracking system, model registry and standard model packaging better but Kubeflow is far more superior when it comes to pipeline orchestration and running workloads on Kubernetes.

I think the nicest piece in MLflow is the model registry. It offers not only easier management and deployment of models but also easier governance. I would totally throw out MLflow and have one less thing to worry about if Kubeflow had this feature.

**Comment by ianhellstrom** [comment]
@amybachir Does [Kubeflow Metadata](https://www.kubeflow.org/docs/components/metadata/) not suffice? The SDK is finicky at the moment but it does offer most features MLflow has AFAICT.

**Comment by dvaldivia** [comment]
@amybachir did you found a good alternative to mlflow that's knative?

**Comment by rajib76** [comment]
Was this feature ever built in Kubeflow

**Comment by jbottum** [comment]
@rajib76 I have not seen a model registry that was developed and supported by the Community as part of a Kubeflow Release.   I think this would be a great enhancement.     We would need to find contributors for this.   Let's add it for consideration in KF 1.6.

**Comment by rajib76** [comment]
Thanks @jbottum , I am new to this community. How do I add this feature for consideration in KF 1.6

**Comment by jbottum** [comment]
fyi, there is new momentum on this topic in this issue, https://github.com/kubeflow/kubeflow/issues/6647

**Comment by rareddy** [comment]
Another relevant effort here https://github.com/kubeflow/kubeflow/issues/7396

**Comment by rareddy** [comment]
@amybachir @rajib76 @dvaldivia @ianhellstrom Folks we are trying to bootstrap an effort to develop a model registry for which we have a proposal here https://github.com/kubeflow/community/pull/682

We are actively looking for folk that can either contribute or sign up as users so please let us know if you are interested in this PR please. https://github.com/kubeflow/community/issues/685
