### ISSUE TITLE
Administrative Functionality 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#5094]
/kind feature

**Why you need this feature:**
Screens within Kubeflow to allow management of Namespace and hardware resources 

**Describe the solution you'd like:**
This issue is to allow folks to add requirements/features for an Administration page within Kubeflow 

1. Allow the management of ImagePullSecrets 
2. Allow the creation of namespaces/projects and attach users to these namespaces
3. Allow hardware to be pinned to a namespace

**Comment by jlewi** [comment]
@jtfogarty Is this really within scope for Kubeflow? It seems like you are asking for a UI to manage basic Kubernetes features. Aren't there existing projects that provide that functionality?

For example on GKE the GKE UI provides functionality to create namespaces.

**Comment by lalithvaka** [comment]
You are right @jlewi. Some of these could be managed using existing Cluster Mgmt vendor tools(Openshift/ Rancher/ GKE/ AKS etc..) if available. But in our enterprise we treat normal workload clusters totally separate and do not mix with ML Clusters and same with the teams operating them as well. These features would definitely help if some one is going with no cluster mgmt software and purely relying on Vanilla K8S. 

Some of the features I can think of might be useful being part of Central Dashboard 
1. Manage or view Capacity allocated / used / available under each Profile
2. Manage in active profiles in the last X days

**Comment by marlow-h** [comment]
Is there a way to keep users from talking to each other?  IE what is the security profile for different users?  And can an admin set this?
