### ISSUE TITLE
Encountered error applying application aws-istio-authz-adaptor when using kfctl_aws.yaml

### ISSUE THREAD

**Issue by jdurago** [kubeflow/kubeflow#5097]
/kind bug

**What steps did you take and what happened:**
I'm unable to install kubeflow as per these AWS instructions:
https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

Was applying my config file:
kfctl apply -V -f kfctl_aws.yaml

and received the following error
```
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0461] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run  Error unable to recognize "/tmp/kout155002910": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:202"
WARN[0461] Will retry in 26 seconds.                     filename="kustomize/kustomize.go:203"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0487] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run  Error unable to recognize "/tmp/kout466900061": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:202"
WARN[0487] Will retry in 32 seconds.                     filename="kustomize/kustomize.go:203"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0520] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run  Error unable to recognize "/tmp/kout359034416": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:202"
WARN[0520] Will retry in 41 seconds.                     filename="kustomize/kustomize.go:203"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`): EKS (Elastic Kubernetes Service)
- Kubernetes version: (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by Brajen259** [comment]
Any solutions to this? I am facing a similar issue while installing kubeflow in was Eks using cognito.

**Comment by jdurago** [comment]
I haven't seen a solution to this yet

**Comment by PatrickXYS** [comment]
Given Kubernetes 1.16 has some API changes to `Deployment` object:

`extensions` is not supporting `Deployment`.

The work-around here is to replace Deployment apiVersion to apiVersion: `apps/v1`.

We will be sending PR to change the yaml file soon

**Comment by manasjain0699** [comment]
> Any solutions to this? I am facing a similar issue while installing kubeflow in was Eks using cognito.

facing the same issue

**Comment by manasjain0699** [comment]
open /eks-kubeflow-demo/eks-kubeflow/kustomize/aws-istio-authz-adaptor/base/deployment.yaml
and the the deployment apiVersion: apps/v1

**Comment by romanzdk** [comment]
still an issue

**Comment by gnsantos** [comment]
Any updates on this? I encountered the same issue while trying to deploy Kubeflow v1.2.0 to an EKS cluster that used OAuth authentication.
