### ISSUE TITLE
Get rid of master in tf_cnn example; use WORKER 0 as chief

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#51]
Now that tensorflow/k8s#192 has been fixed, TfJob can run TensorFlow code that uses worker 0 as the chief.

We should update the [tf-cnn](https://github.com/google/kubeflow/tree/master/tf-controller-examples/tf-cnn) example and get rid of the master and just use Worker 0 as the chief.

@lluunn  Do you want to take this?

**Comment by lluunn** [comment]
Sure, will do

**Comment by jlewi** [comment]
@yupbank started #115, can you sync with @lluunn please to avoid duplicate work?

I think we still need to update the ksonnet prototypes.

**Comment by yupbank** [comment]
sure..
