### ISSUE TITLE
Create a Charter for the Product Management Working Group

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#5105]
/kind question

**Question:**
We need to create a charter for the Product Management Working Group.

This document provides some material to start the process (including starting to identify the responsibilities of the PM Working Group).

https://docs.google.com/document/d/1IMgAS8aVNsttV_weFDng8avl4A1pP7abaAzWtj8hRYU/edit

**Comment by jlewi** [comment]
@jbottum Do you think it makes sense for a product WG to be one of the initial WGs we form? My initial thought was that a lot of the product management functionality should be assumed by area specific working groups. Lets assume we have WGs for

* Pipelines/Metadata
* Inference
* Training
* Notebooks/Datascience

My expectation would be a lot of product management functionality would happen within the WG; e.g. each WG would be responsible for a lot of the responsibilities you mentioned in your doc; e.g.

* Roadmap
* Issue triage
* Surveys
* Blog posts

So what would be left for a product WG that isn't focused on a specific area?
