### ISSUE TITLE
Auto shutdown of idle main Kubeflow pod

### ISSUE THREAD

**Issue by mmwebster** [kubeflow/kubeflow#5115]
/kind question

**Question:**
Is there a recommended way of automatically shutting down the main Kubeflow pod (that's serving the web app / GUI) when idle?

On GCP the default machine type for the corresponding cpu node pool is n1-standard-8, which costs too much for me to run continuously. I've read advice against using a smaller machine type, and it's tedious—and not always possible—to manually resize the node pool.

How should I shutdown this main pod after, say, 1 hour of continuous idling? (where it's considered idle when no pipeline is running and no requests to the web server have been made)

**Comment by jbottum** [comment]
@mmwebster Hey Milo, thanks for the request.   It might be good to quantify the benefit.  How much $ are you expecting to save per month?

**Comment by mmwebster** [comment]
@jbottum Shutting down the node when my team and I aren't using it is essential, as it saves us around $106/mo based on our estimated usage. Due to occasionally forgetting, and not being able to shutdown the node when we're asleep but a pipeline has finished, an auto-shutdown would account for at least ~$46/mo of that $106/mo max savings. Training on GPUs is much more expensive, but these aren’t insignificant amounts for a personal budget.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

My reasoning for this very rough estimate:

On GCP an n1-standard-8 machine in my region costs $0.379998/hr, not including sustained use or committment discounts. With sustained use over a month, this cost is $194.18/mo, incorporating the maximum 30% sustained use discount.

There are two sides to this: shutting down the resources when they’re not in use and automating their shutdown.

My cost savings for shutting down the resources when they’re not in use would be about $106/mo. I’m estimating this from 8hr/day average usage, a 730 hour month, and otherwise 24/7 usage. This leads to 182.5 hrs/mo at 100% price,  60.8 hrs/mo at 80% price, and a total of $87.8/mo. Clearly $106/mo is a worthwhile savings on a personal budget, so I would manually turn off the node for the unused 16 hrs/day. And for my 8hr/day estimate, that’s higher than my current usage. (Yes, these savings will reduce once I start running regular experiments) 

For the auto-shutdown side, benefits include: convenience, no human error / forgetting, and the ability to shutdown during otherwise impractical times. Outside of convenience, I estimate I'd save at least $46/mo.

1. Convenience: This is just nice, not going to put a $ to it
2. No human error / forgetting: I don’t have any good way to estimate this, but if we conservatively say 2 hrs/day go to forgetting, at a 80% discount bracket, then that’s $18.5/mo which I consider worthwhile
3. Impractical shutdown times: Many training runs will inevitably finish during the night, which could cost as much as 8 hours / day. I’ll estimate 3 hours / day, with the reasoning that my project team and I will regular start training in the evening so that results are ready in the morning. At 3 hrs/day and an 80% discount bracket this would cost $27.7/mo. If we start experimenting more, then we’re likely to get into a 60% discount bracket, but will also be starting more experiments in the evening.
