### ISSUE TITLE
where is Metacontroller used in kubeflow ?

### ISSUE THREAD

**Issue by chetanoruganti** [kubeflow/kubeflow#5119]
/kind question

looking at the different issues and docs  looks like initially notebook controller was using jsonnet and metacontroller . Now it  looks like already notebook controller is compliantly moved to golang based controller . correct me if my understanding is wrong 

Is there any other component which is using Metacontroller ?
do we need to remove Metacontroller stateful set installation from the manifest ??

**Comment by jlewi** [comment]
cloud-endpoints-controller is still using it. We should ideally fix cloud-endpoints-controller.
https://github.com/danisla/cloud-endpoints-controller

**Comment by chetanoruganti** [comment]
Thanks @jlewi
