### ISSUE TITLE
Jupyter-Web-App: Support for selecting Extra Resources

### ISSUE THREAD

**Issue by eliaskoromilas** [kubeflow/kubeflow#5121]
/kind feature

**Why you need this feature:**
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins
> Kubernetes provides a device plugin framework that you can use to advertise system hardware resources to the Kubelet.
>
> The targeted devices include GPUs, **high-performance NICs, FPGAs, InfiniBand adapters, and other similar computing resources** that may require vendor specific initialization and setup.

https://github.com/kubeflow/kubeflow/pull/4614 removed the *Extra Resources* section in favour of a *GPUs*-specific one. Currently, admins that want to enable any kind of extended resources for the Jupyter notebooks can expose the relevant `resources.limits` keys only through the `gpus.vendors` array in JWA's config. This means that the end-users may have to **select non-GPU resources (e.g. FPGAs)** from the *GPU Vendor* list.

**Describe the solution you'd like:**
At the back-end, the admin should be able to list the available extra resources in JWA's config:

```yaml
extraResources:
  # Extra Resources for user's Notebook
  # value:
  #   - "hardware-vendor.example/foo"
  value: []
  readOnly: false
```

At the front-end, support for selecting zero or more *Extra Resources* to be assigned to the Notebook's container:
* An **ADD RESOURCE** button, like in *Data Volumes* section.
* Drop-down list for the **Resource Name** field, based on the available `extraResources`.
* Input form for the **~~Number~~Amount of Resources** field, like in *CPU* & *Memory* sections.

**Anything else you would like to add:**
https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/#discussion
> Extended resources are opaque to Kubernetes; Kubernetes does not know anything about what they are. Kubernetes knows only that a Node has a certain number of them. **Extended resources must be advertised in integer amounts.**
>
> ### Storage example
>
> If you want to allow arbitrary requests for special storage, you could advertise special storage in chunks of size 1 byte. **In that case, you would advertise 800Gi resources of type example.com/special-storage.**
> ```yaml
> Capacity:
>  ...
>  example.com/special-storage:  800Gi
> ```

**Comment by jiuchen1986** [comment]
Second that!
