### ISSUE TITLE
Configurations drop down empty when creating Jupyter server

### ISSUE THREAD

**Issue by devashishshankar** [kubeflow/kubeflow#5123]
/kind bug

**What steps did you take and what happened:**
I wanted to supply custom secrets to my jupyter notebook. However, the configuration dropdown seems to be empty (Nothing happens if I click it).
<img width="938" alt="Screenshot 2020-07-11 at 5 26 00 PM" src="https://user-images.githubusercontent.com/980954/87223573-b9a27380-c39b-11ea-9a2f-78542ce56bcd.png">

I have added pod default manifests as per https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/README.md

**What did you expect to happen:**

I want to be able to launch notebooks with my PodDefault spec

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):  I installed it using kfctl_gcp_iap.v1.0.2.yaml. However the version says `dev_local`
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.45", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-17T19:54:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
Mac OS 10.14

**Comment by mnmami** [comment]
For me, it was simply a namespace mismatch between the PodDefault and the namespace used for the notebook creation. Aligning those allowed the Configurations menu to show the PodDefault.

**Comment by asahnovskiy-deloitte** [comment]
are any updates? The issue is still in 1.4 version

**Comment by zhangnew** [comment]
> are any updates? The issue is still in 1.4 version

I solved this problem by creating `PodDefault`
https://blog.doit-intl.com/how-to-configure-poddefaults-for-kubeflow-notebook-servers-fb9d595fab96
