### ISSUE TITLE
Upgrade minikube to latest version v1.12.0

### ISSUE THREAD

**Issue by priyawadhwa** [kubeflow/kubeflow#5125]
Hello! I'm one of the maintainers for [minikube](https://github.com/kubernetes/minikube) which runs under the hood in MiniKF. In the past few days we've gotten a few issues for minikube not working in miniKF:

https://github.com/kubernetes/minikube/issues/8706
https://github.com/kubernetes/minikube/issues/8690

When I tried running miniKF myself ~2 weeks ago I noticed that minikube version was around 1.0.1 -- we've had some significant changes since then and I think upgrading to the latest version may fix some of these user issues.

I'm happy to submit a PR if somebody can point me in the right direction.

**Comment by jlewi** [comment]
@yanniszark @jbottum Does MiniKF have a repo where MiniKF issues could be filed?
