### ISSUE TITLE
Explore Tekton Result Store for logging execution history and metadata

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5127]
/kind feature

Tekton has a proposal for a result store to store the entire execution history.

Relevant issues:

tektoncd/pipeline#453
tektoncd/pipeline#454
tektoncd/pipeline#279

Design doc: https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit#heading=h.xgjl2srtytjt

   * You need to join tekton-dev to be able to read

Can/should we align this work with Kubeflow metadata and Kubeflow pipelines?

The result store would address one of the biggest gaps that KFP was trying to fill ontop of Argo; i.e. provide a record of all the runs. 

/cc @animeshsingh @aronchick @neuromage @rmgogogo @Bobgy @karlshriek

**Comment by aronchick** [comment]
This is really exciting! If no one has any objection, I'll be adding them to our metadata meeting.

**Comment by ottodolfo** [comment]
> This is really exciting! If no one has any objection, I'll be adding them to our metadata meeting.

If they are willing to be at our meeting it would be nice.   I think if the results would be store in an agnostic way, it would be easier to construct over that functionality.

**Comment by animeshsingh** [comment]
its still in experimental phase - not in master, but definitely promising.

**Comment by jlewi** [comment]
FYI to get access to the doc you need to join tekton-discuss.
