### ISSUE TITLE
Kubeflow deployment error

### ISSUE THREAD

**Issue by ashishbhatnagar02** [kubeflow/kubeflow#5131]
Hi All,

I am trying to deploy kubeflow using command and facing error(at the bottom).
--->  kfctl build -V -f ${CONFIG_URI}]

My cluster-kubeflow.yaml file looks like this:
===============================
imports:
- path: cluster.jinja
resources:
- name: kubeflow
  properties:
    autoprovisioning-config:
      enabled: true
      max-accelerator:
      - count: 1
        type: nvidia-tesla-k80
      max-cpu: 4
      max-memory: 1000
    cluster-version: "1.14"
    cpu-pool-enable-autoscaling: true
    cpu-pool-initialNodeCount: 1
    cpu-pool-machine-type: n1-standard-1
    cpu-pool-max-nodes: 4
    cpu-pool-min-nodes: 1
    enable-workload-identity: true
    enable_tpu: false
    gkeApiVersion: v1beta1
    gpu-number-per-node: 1
    gpu-pool-enable-autoscaling: false
    gpu-pool-initialNodeCount: 1
    gpu-pool-machine-type: n1-standard-1
    gpu-pool-max-nodes: 1
    gpu-pool-min-nodes: 1
    gpu-type: nvidia-tesla-k80
    identity-namespace: kubernetes-learning-281817.svc.id.goog
    ipName: pskfp-ip
    pool-version: v1
    securityConfig:
      masterAuthorizedNetworksConfigCidr:
      - cidrBlock: 1.2.3.4/32
      masterAuthorizedNetworksConfigEnabled: false
      masterIpv4CidrBlock: 172.16.0.16/28
      podSecurityPolicy: false
      privatecluster: false
      secureNodeMetadata: false
    users:
    - user:********@gmail.com (Intentionally *'ed)
    zone: us-central1-a
  type: cluster.jinja
====================================

**ERROR:**

ERRO[0044] Updating pskfp error: &{Code:RESOURCE_ERROR Location:/deployments/pskfp/resources/pskfp Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"404","ResourceErrorMessage":{"code":404,"message":"Not found: projects/kubernetes-learning-281817/zones/us-central1-a/clusters/pskfp.","status":"NOT_FOUND","statusMessage":"Not Found","requestPath":"https://container.googleapis.com/v1beta1/projects/kubernetes-learning-281817/locations/us-central1-a/clusters/pskfp","httpMethod":"GET"}} ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:386"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating pskfp error(400): BAD REQUEST
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating pskfp error(400): BAD REQUEST

**Comment by jbottum** [comment]
Hi @ashishbhatnagar02 did you get this responsed ?
