### ISSUE TITLE
[Cleanup] Combine ksonnet apps for testing and releasing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#514]
We have several ksonnet apps related to testing and releasing

https://github.com/kubeflow/kubeflow/tree/master/testing/workflows
https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server/images/releaser
https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image/releaser

I think we should combine these into a single ksonnet app.

This will make it easier to reuse code and avoid duplication.

**Comment by lluunn** [comment]
I will look into this.
prow_config should be able to take the same workflows with different params.
