### ISSUE TITLE
Allow customizing links in central dashboard

### ISSUE THREAD

**Issue by knkski** [kubeflow/kubeflow#5141]
/kind feature

**Why you need this feature:**

We are adding a feature in MicroK8s to allow a user to deploy subsets of the overall Kubeflow set of services:

https://github.com/ubuntu/microk8s/pull/1412

As it stands, if someone wants to deploy Kubeflow without say Katib, they will be presented with a dashboard that links to `/katib/`, which in turn is a dead link. It would improve the user experience to allow configuring the dashboard to disable displaying links to services that have not been deployed.

In particular, these lines are hard-coded to assume that all services have been deployed:

https://github.com/kubeflow/kubeflow/blob/1e0cf04/components/centraldashboard/public/components/main-page.js#L66-L86
https://github.com/kubeflow/kubeflow/blob/29451b6/components/centraldashboard/public/components/dashboard-view.js#L82-L111

**Describe the solution you'd like:**

It seems like the best solution would be to allow environment variables like `KF_PIPELINES_ENABLED` = `true` or `false` for the central dashboard container, that control which services to display links for.

**Anything else you would like to add:**

I'd be willing to work on this, assuming the general strategy of `KF_XXX_ENABLED` environment variables is correct.

**Comment by SachinVarghese** [comment]
I think this issue is related to #3576. And a common solution can be implemented.

**Comment by knkski** [comment]
Thanks @SachinVarghese. #3576 is close enough that I'll close this one as a duplicate

**Comment by SachinVarghese** [comment]
@knkski I have created a PR for this #5147. I hope that solution works for you. It would be great if you could confirm on the PR and also an upvote would be great. Thanks
