### ISSUE TITLE
kubeflow 1.0.2 not working.

### ISSUE THREAD

**Issue by crazy-canux** [kubeflow/kubeflow#5148]
/kind bug

**What steps did you take and what happened:**

kubeflow: 1.0.2
kfctl: 1.0.2
kubenetes: 1.17.0
os: ubuntu16.04

question one:
katib-mysql not working.

kubectl get pod -n kubeflow
katib-db-manager-54b64f99b-nmtzv                               0/1     CrashLoopBackOff   829        3d1h
katib-mysql-6c44769759-n8z79                                   0/1     CrashLoopBackOff   782        2d4h

related to this issue:
#https://github.com/kubeflow/katib/issues/1212

question two:
istio-tracing not working.
 kubectl get po -n istio-system
NAME                                       READY   STATUS             RESTARTS   AGE
istio-tracing-84cbc6bc8-dwc6z              0/1     CrashLoopBackOff   869        3d2h
istio-tracing-85cb678675-qpv8s             0/1     CrashLoopBackOff   592        2d2h
```
Events:
  Type     Reason   Age                       From              Message
  ----     ------   ----                      ----              -------
  Warning  BackOff  6m44s (x21195 over 3d2h)  kubelet, ubuntu3  Back-off restarting failed container
  Normal   Pulled   110s (x875 over 3d2h)     kubelet, ubuntu3  Container image "docker.io/jaegertracing/all-in-one:1.9" already present on machine
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.0.2:
- kfctl version: 1.0.2
- Kubernetes platform: kubeadm
- Kubernetes version: 1.17.0
- OS (e.g. from `/etc/os-release`): ubuntu16.04

**Comment by crazy-canux** [comment]
some other issue:

```
kubectl describe pod kfserving-ingressgateway-6b469d64d-gz9lg -n istio-system
Events:
  Type     Reason     Age                       From              Message
  ----     ------     ----                      ----              -------
  Warning  Unhealthy  4m57s (x26559 over 3d2h)  kubelet, ubuntu4  Readiness probe failed: Get http://10.244.1.12:15020/healthz/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by chinmay22897** [comment]
@crazy-canux Were you able to solve this issue??
