### ISSUE TITLE
Hi I want to use resourcesQuotaspec when i am adding GPU in yaml then i am trying to create Notebook server its showing me error, Can you guys help me out how to add gpu/cpu  in profile resources allocation for a namespace? below are the link i am following

### ISSUE THREAD

**Issue by aniruddhachoudhury** [kubeflow/kubeflow#5154]
Hi I want to use resourcesQuotaspec when i am adding GPU in yaml then i am trying to create Notebook server its showing me error, Can you guys help me out how to add gpu/cpu  in profile resources allocation for a namespace? below are the link i am following 
[KubeflowProfileContoller](https://github.com/kubeflow/kubeflow/blob/960587ac9025b6a4ba7facaabc8aa1769fb01dc8/components/profile-controller/config/samples/profile_v1beta1_profile.yaml)

[KubernatesResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/)

I am using **DEX Configuration** , below is my yaml file

apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: aniruddha-choudhury   
spec:
  owner:
    kind: User
    name: aniruddha.choudhury@gmail.com
  plugins:
  - kind: WorkloadIdentity
    spec:
      gcpServiceAccount: kubeflow2@project-id.iam.gserviceaccount.com
  resourceQuotaSpec:
  	hard:
	   cpu: "10"
	   memory: 20Gi
	   pods: "20"
	   gpu: "1"

@jlewi Please see if the above yaml file will work or not as GPU is creating problem.

_Originally posted by @aniruddhachoudhury in https://github.com/kubeflow/kubeflow/issues/4965#issuecomment-662047408_

**Comment by jlewi** [comment]
@aniruddhachoudhury Assuming you are using GKE please take a look at the docs on how to use GPUs
https://cloud.google.com/kubernetes-engine/docs/how-to/gpus.

If you are installing on GKE and using Dex you will most likely not end up with GPUs enabled on your cluster and have to perform additional steps.

If you are not using GKE then what platform are you using? And did you follow the instructions for using GPUs on that platform?

**Comment by aniruddhachoudhury** [comment]
Hi @jlewi  thanks for replying. I just want to highlight few things. I am able to add few points what i want to .

**Achieved**
- So i am using GKE with Dex Config fro Kubeflow & i am able to use GPU in Notebook server & i  have already used the GKE with GPU in Notebook server by attaching GPU pool in cluster.

**Scenario:**
- Now my next scenario is if i as a admin want to give access of my Kubeflow environment  to others i am creating a **profile-controller**(which i have used in yaml above) for a particular user and they can create a Notebook of a specific limitation, when i mean limitations it will control that they can create CPU:10 /MEMORY:10Gi /GPU:1 configuration Notebook only not more than the threshold numbers.
- I have tested the scenario for CPU/MEMORY  only it was **working fine**, not allowing the users to create Notebook Server more than the threshold which i have gave.


**Problem/Challenge:** 
When i am adding GPU:1 in profile controller yaml to restrict users to create only one GPU that users able to create more than one GPU which i don't want. So my configuration  will be with CPU/MEMORY/GPU and it should work.


_I hope you have got the picture, I am using Google Cloud Platform, And i am able to use GPU also , and here the scenario is Profile controller with GPU/CPU/MEMORY for Notebook Server._

Profile Controller Link: https://github.com/kubeflow/kubeflow/blob/960587ac9025b6a4ba7facaabc8aa1769fb01dc8/components/profile-controller/config/samples/profile_v1beta1_profile.yaml


Thanks

**Comment by lalithvaka** [comment]
@aniruddhachoudhury , it appears your spec for GPU key wrong. Use "nvidia.com/gpu: 2". It should work.
