### ISSUE TITLE
Create a FAQ documenting how to do an onprem airgap deployent of Kubeflow

### ISSUE THREAD

**Issue by supertetelman** [kubeflow/kubeflow#5157]
/kind feature

**Why**

Oftentimes companies have a secure environment where direct Internet access is not possible and simply running kfctl apply and downloading arbitrary containers is not possible. In addition to this use case, running `kfctl apply -f $CONFIG` commands does not guarentee the same deployment, or even a working deployment, of Kubeflow as the manifest files often change, are not pegged to specific version, or do not honor backwards compatability.

To work around these issues it is beneficial to download all the relevant containers, configurations, and yaml files, copy them to a secure location, and then deploy pointing to the local copies.

**What**
I saw some steps to do this outlined in https://github.com/kubeflow/kubeflow/issues/5061 and thought that having an easy-to-follow guide that spells out how to identify all the resources, download them, push them to a local repo, and deploy from local repos would be of great benefit to the community.

**Misc.**
I'm happy to provide some support in building or testing such a guide.

I believe the rough steps to follow would be:

1. Install Kubeflow somewhere "nonsecure", save off manifest
2. Identify all the Docker Image download and save off a tarball
3. Stand up a Docker registry in the secure location
4. Copy over and push up Docker image
5. Modify the manifest to point to the local docker registry
6. Install using the modified manifest in the secure location

**Comment by sachua** [comment]
I had deployed Kubeflow in an onprem, airgap environment, I documented my steps here: https://github.com/sachua/kubeflow-easy-deploy

**Comment by DavidSpek** [comment]
This issue seems related:
https://github.com/kubeflow/website/issues/2137

**Comment by jbottum** [comment]
@jtfogarty @krishnadurai any comment on this ? @supertetelman Hi Adam, you might consider bringing this up at the On-Prem SIG (on Thursdays)

**Comment by DavidSpek** [comment]
Bump
