### ISSUE TITLE
Kubefow+ LetsEncrypt+ Istio Dex 1.0.2 yaml 

### ISSUE THREAD

**Issue by Anujay-Saraf** [kubeflow/kubeflow#5159]
/kind bug

I am unable to receive a working certificate thru letsencrypt prod/staging API:

![image](https://user-images.githubusercontent.com/27989098/88207986-2f48f200-cc6e-11ea-87ca-e84c5d42cef6.png)

The current setup includes below approach

K8s cluster setup with 1.0.2 Istio Dex Yaml, mentioned in kubeflow.org documentation, which comes with istio 1.3.1 and cert-manager by default.
As my major task is to complete this with kubeflow enabled with istio-ingressgateway along with HTTPS Lets-Encrypt ACME SSL Certificate generation.
Kindly let me know a possible solution.

**Environment:**

- Kubeflow version: 
- K8s API version 1.14
- kfctl version: 1.0.2
- Kubernetes platform: GKE
- Kubernetes version:  (kubectl version --short
Client Version: v1.17.0
Server Version: v1.14.10-gke.36)
- OS: default

Istio -1.3.1
Cert-Manager: the same which comes with default manifest.

**Comment by jlewi** [comment]
Do you have any errors indicating this is an issue with Kubeflow and not your cluster setup? 

/cc @yanniszark @krishnadurai

**Comment by Anujay-Saraf** [comment]
Regardless of the setup that I am doing, it's the combination that I am using as default which comes with 1.0.2 YAML.

https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml,

Kindly let me know if we are missing anything from our end because we are trying to have full-fledged setup with ACME cert's using default configuration or else if we need to use anything else
