### ISSUE TITLE
Discover version of Kubeflow

### ISSUE THREAD

**Issue by PoornimaDevii** [kubeflow/kubeflow#5165]
/kind question

Hi,

Been working with Kubeflow since couple of months. When working on already installed Kubeflow ( when I'm not aware of installation) on a cluster, I found it difficult to discover the exact Kubeflow version which I'm working on. Was able to find version of Kubeflow on left-hand bottom corner of it's dashboard, but that doesn't seem to work in all cases. 

Can you please guide me with a way to instantly check for the version of an already installed Kubeflow, which could be helpful in ways of upgrading/cleaning up the existing one.

Thanks.

**Comment by pjsudharshan** [comment]
Is this feature available now?

**Comment by tiansiyuan** [comment]
> Issue Label Bot is not confident enough to auto-label this issue. See [dashboard](https://label-bot-prod.mlbot.net/data/kubeflow/kubeflow) for more details.

At the left-bottom corner of the dashboard, it displays "build version dev_local" literally.
