### ISSUE TITLE
 Error with kfctl_istio_dex.yaml seldon in 1.0.2

### ISSUE THREAD

**Issue by Focke-Wulf** [kubeflow/kubeflow#5171]
Error while deploying kfctl 1.0.2 with  [kfctl_istio_dex]  kfctl_istio_dex.yaml config

Code 500 with message: Apply.Run : error when creating "/tmp/kout076213069": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]  filename="kustomize/kustomize.go:266"

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.02
- kfctl version: (use `kfctl version`): 1.02
- Kubernetes platform:  Rancher
- Kubernetes version: 1.18.6
- OS Ubuntu18.04

**Comment by alexw994** [comment]
This erro also occurs when kfctl  v1.1.0 was deployed

**Comment by DavidSpek** [comment]
This seems to be the same issue as https://github.com/kubeflow/website/issues/2206. In [this](https://github.com/kubeflow/website/issues/2206#issuecomment-698234904) comment I provide a workaround using an open pull request of mine.
