### ISSUE TITLE
Update release guide for website docs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5175]
/kind process 

Filing this issue to ensure we update the release guide for the website to include improvements to the release process from 1.1.

I think we should making running @RFMVasconcelos's script to add outdated banners to all pages a part of the process (see kubeflow/website#2066).

I think this is a good way to ensure that every page gets at least a once over every 60-90 days.

Per kubeflow/website#2067 I think we want to make it platform owners responsibility to update the shortcodes.

/assign @RFMVasconcelos @8bitmp3

**Comment by jlewi** [comment]
kubeflow/website#2087 added the script to add the banners.

@knkski any interest in updating the release guide as well?

**Comment by knkski** [comment]
@jlewi: Sure, opened up #5208 to add that step. I put it in the `Updating version numbers` section, let me know if it should go elsewhere instead.

**Comment by jlewi** [comment]
Thanks @knkski closing this because #5208 has been merged.
