### ISSUE TITLE
[AWS] Kubeflow v1.2 features

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5178]
/kind question

**Question:**
I'd like to collect some feedbacks on 1.2 features user wants on AWS side. 

We recently roll out a blog post to share the existing AWS works on Kubeflow. 
https://aws.amazon.com/blogs/opensource/enterprise-ready-kubeflow-securing-and-scaling-ai-and-machine-learning-pipelines-with-aws/

This issue is just used to track AWS specific features like service integration, etc. We will definitely contribute to generic features and projects, but it's better to have separate topic to discuss them.

Kubeflow
- Consider if we still want to use kfctl to manage non-k8s resources. 
  - Evaluate kfctl - operator
  - Evaluate CDK
- Keep investigating on multi-user in Kubeflow Pipeline (Authorization, Manifest and Artifacts)
- Tekton based Testing Infrastructure
- [kfctl] Support addons in AWSPlugin - User want to install Fluentd, Nvidia, FSX, EFS, etc by their own
- Better GPU monitoring (Metrics) in Jupyter Notebook and Kubeflow Pipeline
- Better Logs support in Kubeflow Pipeline and training operators
- Consider to create one single training operators to simplify the installation - work with WG training.
- Support Manifest upgrade (Need to identify application and stable components first)
- Keep improving v3 manifests and organize them into stacks and remove low quality applications
- Jupyter Infra improvement plan

**Comment by apryiomka** [comment]
Dropping `kfctl` completely and make manifest to be deployed by kustomize only.
