### ISSUE TITLE
Jupyter tf-2.1.0-notebook-cpu image having issues with pip install of additional deps.

### ISSUE THREAD

**Issue by darthveda-ai** [kubeflow/kubeflow#5179]
/kind bug

**What steps did you take and what happened:**
I launched the standard gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu image on kubeflow and found not to have certain deps that I needed to use. So tried doing !pip install pandas in the first cell of the jupyter notebook, that is connected to the launched notebook server.

**What did you expect to happen:**
Expected pandas library to be installed but instead got **Err. no 13, user not having permission.**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
So tried installing with pip install --user option and that installs to ~/.local/lib/python3.6/site-packages which is not in PYTHONPATH. What is the recommended approach?
[Issue 668](https://github.com/kubeflow/kubeflow/issues/668) opened a couple of years ago is on the same issue, it's current status is CLOSED, but in the recent few months people have raised the same issue. Any help on this would be greatly appreciated.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): dev_local
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`): GCP GKE
- Kubernetes version: (use `kubectl version`): 1.14.10-gke.46
- OS (e.g. from `/etc/os-release`):

**Comment by sachua** [comment]
The  `--user` method should work, did you remember to restart your kernel after running the cell?

The alternative approach is to build your own image from the standard notebook image and installing the dependencies that you want as root user.

**Comment by agnz** [comment]
Restarting the kernel after installing with --user worked for me.

**Comment by DavidSpek** [comment]
This issue should be closed as https://github.com/kubeflow/kubeflow/issues/5179#issuecomment-667840991 should solve the problem.

**Comment by DavidSpek** [comment]
Closing this issue as this notebook image has been deprecated in favor new notebook images. 
/close
