### ISSUE TITLE
profile-controller can't start 

### ISSUE THREAD

**Issue by Focke-Wulf** [kubeflow/kubeflow#5187]
hello all:
i am trying deploy the kubeflow with auth  however  the profile-controller says that

starting container process caused "exec: \"/access-management\": stat /access-management: no such file or directory": unknown

what happend to my system? any pre config we need? 

PS : i used to deploy kubeflow version with 1.0 works fine with me
**Environment:**

- Kubeflow version: 1.02
- kfctl version: (use `kfctl version`): 1.02_dex
- Kubernetes platform: Rancher
- Kubernetes version: (use `kubectl version`): 1.18.6
- OS (e.g. from `/etc/os-release`):

**Comment by Jeffwan** [comment]
@Focke-Wulf 

Can you share container image id of your profile controller?

**Comment by jbottum** [comment]
@Focke-Wulf which platform are you running on i.e. AWS, GCP or on-prem
