### ISSUE TITLE
centraldashboard is unable to run with restrictive securityContext

### ISSUE THREAD

**Issue by axelgobletbdr** [kubeflow/kubeflow#5188]
The centraldashboard container requires privileged permissions to be able to run on Kubernetes. This causes major security risks. These risks should not be necessary, as the centraldashboard is merely a javascript app that should be able to run with restricted permissions.

The cause for this problem is the node version used by the container currently in https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/Dockerfile. Bumping this version to `node:12.18.3-alpine` (latest version on august 5 2020) solves the problem.

**Comment by Jeffwan** [comment]
@axelgobletbdr Thanks reporting the issue. Based on my understanding, we can remove privileged securityContext on central dashboard as PR merged. Right?

**Comment by axelgobletbdr** [comment]
@Jeffwan right
