### ISSUE TITLE
MiniKF Notebook server with GPU not starting

### ISSUE THREAD

**Issue by phansoks** [kubeflow/kubeflow#5189]
/kind bug

**What steps did you take and what happened:**
I am using MiniKF on a Windows 10 computer.
Creation of a notebook server with image 'gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu:1.0.0' (any gpu image actually) never ends. Status messages says: 'Reissued from pod/gpu-0: skip schedule deleting pod: kubeflow-user/gpu-0'

![image](https://user-images.githubusercontent.com/12391822/89432603-9ae89000-d741-11ea-8b42-7072d1351c68.png)
![image](https://user-images.githubusercontent.com/12391822/89432542-8c9a7400-d741-11ea-9683-797a20e0adcc.png)
![image](https://user-images.githubusercontent.com/12391822/89432799-d2573c80-d741-11ea-98cd-e6cbcdf4448c.png)

**What did you expect to happen:**
With cpu templates, notebook servers' creation finishes and I can open JupyterLab.

**Anything else you would like to add:**
````
> kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu
NAME       GPU
minikube   <none>
````

Could it be an incompatibility issue related to Windows 10? 
**Environment:**
- MiniKF: 20200305.1.0
- Kubeflow version: v1.0-56-g5ae311f8
- kfctl version: (use `kfctl version`): N/A
- Kubernetes platform: minikube
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Windows 10

**Comment by kitamura-tetsuo** [comment]
I had same error with Ubuntu 18.04.

**Comment by yanniszark** [comment]
@phansoks I believe you're using Vagrant, correct?
Vagrant spins up a VM which we use as a reproducible environment in which to setup Kubeflow.
Using a GPU in a VM requires non-trivial (GPU passthrough), we don't support using a GPU with Vagrant right now.
If you want to use a GPU, I recommend using MiniKF on GCP:
https://www.kubeflow.org/docs/started/workstation/minikf-gcp/

**Comment by phansoks** [comment]
Thanks @yanniszark for the feedback. Yes, I am using Vagrant. I'd like to avoid GCP because I have limited rights on it in my company. I wanted to have MiniKF on my machine because it gives me more flexibility.

Is there any possibility or documentation about setting the GPU passthrough?

**Comment by yanniszark** [comment]
@phansoks unfortunately, this is something we're not pursuing at the moment.

**Comment by yanniszark** [comment]
@phansoks to clarify, we are looking into ways to use GPU passthrough on Windows in the long term, but it is very non-trivial. We will make sure to update if there's a change. Until then, we recommend using GCP for utilizing GPUs.

**Comment by phansoks** [comment]
@yanniszark, thanks again for the the heads up. I'll continue to follow minikf and try again as soon as gpu support is added!

**Comment by jbottum** [comment]
@phansoks did you get this resolved?

**Comment by phansoks** [comment]
@jbottum, My question was indeed answered. It would be nice to have GPU support on local environment.
