### ISSUE TITLE
Application istio-ingress not found

### ISSUE THREAD

**Issue by tretos53** [kubeflow/kubeflow#5192]
/kind bug

**What steps did you take and what happened:**

Installed Kubeflow on EKS cluster. When running `kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80` I can access Kubeflow Dashboard successfully.

When trying to set up the custom domain, the istio-ingress doesn't exist.

```
kubectl get ingress istio-ingress -n istio-system
Error from server (NotFound): ingresses.extensions "istio-ingress" not found
```

In the installation log I found below entry:

`WARN[0009] Application istio-ingress not found           filename="kfconfig/types.go:683"`

All the other istio-ingress are created.

```
serviceaccount/istio-ingressgateway-service-account created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
clusterrole.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
clusterrolebinding.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
service/istio-ingressgateway created
deployment.apps/istio-ingressgateway created
poddisruptionbudget.policy/istio-ingressgateway created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
```

**What did you expect to happen:**

ingress istio-ingress to exist.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version dev_local
- kfctl version: (use `kfctl version`): v1.0-0-g94c35cf
- Kubernetes platform: EKS
- Kubernetes version: (use `kubectl version`): Client Version: v1.15.1, Server Version: v1.14.9-eks-f459c0
- OS (e.g. from `/etc/os-release`):

```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Is there a simple way to create the ingress? A simple yaml file I can apply?

**Comment by Jeffwan** [comment]
@tretos53 

Which manifest are you using? Could you apply https://github.com/kubeflow/manifests/blob/master/aws/istio-ingress/base/ingress.yaml? remember to change `$(loadBalancerScheme)` to `internet-facing` for most common cases

**Comment by tretos53** [comment]
I used this page: `https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/` and this manifest: `export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml"`

I created the ingress as you suggested but the HOST is missing.

```
kubectl get ingress istio-ingress -n istio-system
NAME            HOSTS   ADDRESS   PORTS   AGE
istio-ingress   *                 80      3m9s
```

Should I apply below and then point my route53 to this domain?

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  name: istio-ingress
spec:
  rules:
  - host: kubeflow.mydomain.com
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /*
```

I can also remove Kubeflow and start again with a different manifest if it's easier.

I can see a pod `alb-ingress-controller-59898bbb94-96dpc` running but it doesn't have external IP nor I can see it in the AWS console.

**Comment by jgerardsimcock** [comment]
I am also getting this error but I am running on prem

**Comment by tretos53** [comment]
I tried following this but no luck: `https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#secure-with-https`

1. Edited gateways.networking.istio.io kubeflow-gateway
2. Patched `kubectl patch service -n istio-system istio-ingressgateway -p '{"spec": {"type": "LoadBalancer"}}'`
3. Waited for external IP (DNS) to show up
3. Created the Certificate with cert-manager
4. Navigated to https://<LoadBalancer Address>/ 

```
This site can’t be reached
xxxxx.<aws-region>.elb.amazonaws.com took too long to respond.
```

**Comment by tretos53** [comment]
My bad. Above worked fine but it took about 20minutes. Not sure why. Also this only works in Firefox, all other browsers don't allow bypassing self signed certificates.

**Comment by Jeffwan** [comment]
If v1.1-branch, it will be easier. 
Try this please

**Comment by Jeffwan** [comment]
@jgerardsimcock you need to change `$(loadBalancerScheme)` to `internet-facing` unless you are configuring internal facing ALB

**Comment by tretos53** [comment]
@Jeffwan Let me try running it on a new cluster with https://master.kubeflow.org/docs/aws/deploy/install-kubeflow/ and I'll let you know.

**Comment by tretos53** [comment]
I followed https://master.kubeflow.org/docs/aws/deploy/install-kubeflow/ on a brand new cluster.

Istio-ingress doesn't return the ADDRESS

```
kubectl get ingress -n istio-system
NAME            HOSTS   ADDRESS   PORTS   AGE
istio-ingress   *                 80      32m
```

As you mentioned before, this might be due to ALB not working correctly. Well, the ALB is not in a healthy state:

`pod/alb-ingress-controller-db976d7f-wjkf8                    0/1     CrashLoopBackOff`

 The log file is:

```
kubectl -n kubeflow logs pod/alb-ingress-controller-db976d7f-wjkf8
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.1.5
  Build:      git-2560c813
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.git
-------------------------------------------------------------------------------

W0814 14:15:41.085438       1 config.go:97] Environment variable configuration is deprecated, switch to the --cluster-name flag.
W0814 14:15:41.085650       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0814 14:15:41.464540       1 main.go:94] failed to introspect vpcID from ec2Metadata due to EC2MetadataError: failed to make EC2Metadata request
	status code: 404, request id:
caused by: request blocked by whitelist-route-regexp "^$": /latest/meta-data/mac
, specify --aws-vpc-id instead if ec2Metadata is unavailable
```

I am happy to add below to ALB config but I'm not sure if this will help and if this is something you want me to try. It might also be an issue with permissions and ALB not being able to read the IAM role, although I don't know where is that configured within Kubeflow.

```
spec:
  containers:
  - args:
    - --ingress-class=alb
    - --cluster-name=<clustername>
    - --aws-vpc-id=<vpc id>
    - --aws-region=<region>
    image: docker.io/amazon/aws-alb-ingress-controller:v1.1.5
```

**Comment by tretos53** [comment]
@Jeffwan do you have any advice on this?

**Comment by tiliter-algorithms** [comment]
I am following the https://www.kubeflow.org/docs/aws/authentication/.
Istio-ingress doesn't return the address for alb.
<img width="439" alt="Screenshot 2020-10-13 at 16 13 19" src="https://user-images.githubusercontent.com/61815060/95872443-159be000-0d6f-11eb-8991-a658d7815e2c.png">

<img width="1381" alt="Screenshot 2020-10-13 at 16 14 48" src="https://user-images.githubusercontent.com/61815060/95873296-11bc8d80-0d70-11eb-8092-fda4aaef92f4.png">

Kubeflow installation directory is the same as the cluster name. Any help is appreciated. 
@tretos53 could you able to solve this issue?
Thanks!

**Comment by tretos53** [comment]
@tiliter-algorithms 

- Are ALL pods Running? `kubectl get pods -A | grep -v Run`
- Is pod in `kubeflow` namespace alb-ingress-controller-xxxxxxx Running?
- Are there any errors in logs of this pod? `kubectl logs -n kubeflow alb-ingress-controller-xxxxxxx`
- Are there any errors in description of this pod? `kubectl describe pod -n kubeflow alb-ingress-controller-xxxxxxx`

This pod is part of Replicaset in kubeflow namespace and I "solved" it by manually adding options that were missing. All the missing options were displayed in logs or when you describe the above pod.

➜ kubectl edit replicaset -n kubeflow alb-ingress-controller-59898bbb94-z22gx

Add missing options in the args section. This supposed to happen automatically but for some reason didn't, and as I'm testing kubeflow this is ok but in production we would need this fixed.

spec:
  containers:
  - args:
    - --ingress-class=alb
    - --cluster-name=<your eks cluster name>
    - --aws-vpc-id=<vpc id where eks cluster is located>
    - --aws-region=<aws region where eks cluster is located>
    image: docker.io/amazon/aws-alb-ingress-controller:v1.1.5

**Comment by tiliter-algorithms** [comment]
@tretos53 
Thank you for quick reply!
- 
<img width="936" alt="Screenshot 2020-10-13 at 16 58 34" src="https://user-images.githubusercontent.com/61815060/95878346-67dfff80-0d75-11eb-89db-0043ddc7b51e.png">

- 
<img width="796" alt="Screenshot 2020-10-13 at 16 59 57" src="https://user-images.githubusercontent.com/61815060/95878477-8b0aaf00-0d75-11eb-8239-57304d7e9b24.png">

- 
<img width="1380" alt="Screenshot 2020-10-13 at 17 01 53" src="https://user-images.githubusercontent.com/61815060/95878937-13894f80-0d76-11eb-9153-62c5395228b0.png">


- No errors for: kubectl describe pod -n kubeflow alb-ingress-controller-xxxxxxx

No object found when tried to edit replicaset.
<img width="548" alt="Screenshot 2020-10-13 at 17 08 19" src="https://user-images.githubusercontent.com/61815060/95879493-b641ce00-0d76-11eb-8dc4-945d46aa2bba.png">

**Comment by tretos53** [comment]
- How is the Certificate ARN specified in yaml? 
- Does it have any quotes? 
- Does the certificate exists?
- What about permission to get this certificate?

Someone had similar issue here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1127

Also https://github.com/kubernetes-sigs/aws-alb-ingress-controller might be better place to ask.

I think it should be:
`certArn: arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxxxxxxxx-xxxx `

**Comment by tiliter-algorithms** [comment]
@tretos53 
It turns out that there was an issue in this tutorial https://www.kubeflow.org/docs/aws/aws-e2e/ at the line "The ARN of the certificate from the Certificate Manager of N.Virginia ()" instead certificate should be from the same region your cluster is in.
I followed the rest of the deployment and now got an alb-ingress address. I am. able to visit the custom domain Cognito login page but then it produces an error.  

<img width="1409" alt="Screenshot 2020-10-14 at 09 21 07" src="https://user-images.githubusercontent.com/61815060/95956487-a4a40900-0dfe-11eb-90e8-406226e7f963.png">

I think this is related to permissions.

**Comment by tretos53** [comment]
I don't use cognito so no idea but TransientFailure sounds a lot like SSL problem.
Where is that error coming from? Which pod?
I had the similar error after updating certificates and I had to restart pods.

I just saw you solved it :)

**Comment by Jeffwan** [comment]
If you still have problems, @PatrickXYS will take over the issue

/cc @PatrickXYS
