### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [kubeflow/kubeflow#5195]
/kind question

**Question:**

Hello KubeFlow team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I was looking at your project and I think it would be great for you to present/discuss it at one of our meetings. For example, how KubeFlow enables MLOps and how it compares to other MLOps frameworks.

Let me know if this is something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by jlewi** [comment]
@raravena80 Thanks for reaching out. Would you mind emailing kubeflow-discuss@googlegroups.com to see if anyone is interested?

**Comment by raravena80** [comment]
@jlewi thanks, just sent a message to the ML.

**Comment by jlewi** [comment]
@raravena80 probably because you aren't a member. You should be able to join but I sent a message to the group and told people to chime in on this issue if interested.
https://groups.google.com/g/kubeflow-discuss/c/TlUXv6mqsLM

**Comment by jbottum** [comment]
@raravena80 Hi Richardo, Nice to meet you.    I am one of the Kubeflow Community Product Managers.  I doubt that we have material on how Kubeflow compares to other MLOps frameworks, but should be able to find some material / presenters on Kubeflow & MLOps.   How long should the presentation last?    Should the focus be 1) more in-depth on the technology  2) how the tech simplifies the user's life 3) both.

**Comment by raravena80** [comment]
Thanks @jlewi (joined the ML) 

@jbottum likewise! It's fine if you don't have comparison material but it would still be great to have a session about the project. I think you can share a combination: 3). Our meetings usually last about an hour so anything that can fit in that time frame or less works.

**Comment by jbottum** [comment]
@raravena80 we have a Community meeting today and will ask for volunteers.   Do you have a regular schedule for your meetings ?

**Comment by raravena80** [comment]
@jbottum yes the schedule is on the [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes). Thanks!
