### ISSUE TITLE
Load profile plugin in user registration flow

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5198]
/kind feature

**Why you need this feature:**

If we enable `registration-flow`, a basic profile will be created. If cluster-admin wants to have some default settings like profile plugin, resource quota. UI flow won't able to do this. 

We'd better consider a way to make these changes configurable and central dashboard can pick them up. 

**Describe the solution you'd like:**
A configmap could be used here to achieve this. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
I thought we use projects not area labels for releases?

**Comment by Jeffwan** [comment]
@jlewi I see. I didn't know that. I can remove it and put into project

**Comment by jlewi** [comment]
Thanks @Jeffwan I tagged this into the Kubeflow 1.2 Kanban board.

**Comment by Jeffwan** [comment]
I remove it from 1.2
