### ISSUE TITLE
Proposal: Official Jupyter Images for Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#52]
Opening this issue to discuss providing one or more official Kubeflow Jupyter images

Some things to consider:

- What libraries/frameworks/tools should be in the image
   -  TensorFlow?
   -  GRPC client libraries? 
   - xgboost?
   - scikits?
   - ksonnet? helm?
- Do we want to produce a small number of fat images or many smaller images?
- Can we reuse existing images? e.g. TensorFlow docker images? Jupyter images?

Related:
#50 Docker images for TF Serving
#37 Size of our Jupyter images

/cc @flx42 @yuvipanda

**Comment by flx42** [comment]
Unless we realize that we need many tools, a benefit would be that we can make the official TF images lighter by removing Jupyter: https://github.com/tensorflow/tensorflow/issues/15284

**Comment by nkashy1** [comment]
A good place to start, from the point of view of what a data scientist could reasonably expect in their environment, is [Kaggle's Python image](https://github.com/Kaggle/docker-python).

If size is a concern, as per [Issue 37](https://github.com/google/kubeflow/issues/37), this is probably not satisfactory as I think their image weighs in at around 10GB. If the intention is to support more than just TensorFlow, I don't see this as being a problem, though.

**Comment by nkashy1** [comment]
One problem that Kaggle has not yet had to contend with is how to handle GPUs.

This is a problem that [Datalab](https://github.com/googledatalab/datalab) has solved by offering a [standard image](https://github.com/googledatalab/datalab/blob/master/containers/datalab/build.sh) and a [GPU image](https://github.com/googledatalab/datalab/blob/master/containers/datalab/build.gpu.sh).
