### ISSUE TITLE
Notebook controller needs OWNERs file

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5200]
/kind process

The notebook controller needs an OWNERs file indicating who can review and approve PRs. 

Per kubeflow/community/issues/379  @kimwnasptd and @StefanoFioravanzo are you interested in this as part of the notebooks WG?

**Comment by yanniszark** [comment]
@jlewi thanks for opening the issue!
From our side, I am personally interested and have the knowledge to help review/approve PRs for the notebook-controller. I will also ask other people from our side (@StefanoFioravanzo, @kimwnasptd, @elikatsis) once they are back from PTO. We can make a PR for adding the OWNERS file.

**Comment by MartinForReal** [comment]
@yanniszark I'm personally interested in maintaining notebook controller. But I need to start from submit commits. Any update on #5197 is appreciated. Thanks!

**Comment by jlewi** [comment]
@yanniszark @StefanoFioravanzo @kimwnasptd, @elikatsis ping? Could we create an OWNERS file please? And could you review #5197 please?

@MartinForReal Thats great! Once the OWNERs file is created you can add yourself as a reviewer to it.

**Comment by yanniszark** [comment]
@jlewi lots of people still on PTO. We should be able to pick this up starting next week.
