### ISSUE TITLE
Kubeflow 1.1 Community Slide Deck

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#5203]
/kind feature

We want to provide 1 slide on each of the new features in Kubeflow 1.1, which will describe the feature, its benefit and how to get more info.   Once the presentation looks good, we would like to present it to the Community.

**Describe the solution you'd like:**
Per above 1 slide on each 1.1 feature, that users can view to get a quick understand of what is new

**Anything else you would like to add:**
I would like to complete this by Aug 18.   I would like to request help to improve the slides from the area owners.   
Here is the link to the current slide deck.
https://docs.google.com/presentation/d/1wk4frDFws5pWBVdpcKgiJ9HnZSB7VLs_0x1LUq7r7cg/edit#slide=id.g8fa2663e4e_0_2

**Comment by jbottum** [comment]
@jlewi @terrytangyuan @Bobgy @animeshsingh @jinchihe @cspavlou @hamelsmu Hey Jeremy, Terry, Yuan, Animesh, Jinchi, Chris, Hamel - I have requested your input / improvements on the Kubeflow 1.1 slide (especially on the slide that pertains to your 1.1 contribution).    Would you please consider contributing your improvements by Aug 14?   I would like to propose that we present those slides to the Community on Aug 18 or 25.

**Comment by hamelsmu** [comment]
@jbottum I updated slide about the blog

**Comment by jlewi** [comment]
I looked at the doc and commented.

**Comment by jbottum** [comment]
@hamelsmu @jlewi @jinchihe @andreyvelich thanks for your comments on the KF 1.1 slide deck.   We are off to a good start.  This is good stuff.   I was especially glad to get the info on the new features in Katib...I missed those in the blog post.

**Comment by terrytangyuan** [comment]
@jbottum Thanks. I have made some edits on relevant slides.

**Comment by jinchihe** [comment]
@jbottum I updated page #4 for Fairing. Thanks.

**Comment by animeshsingh** [comment]
@jbottum updated Kfserving page
