### ISSUE TITLE
1.2 Planning Session with Kubeflow Users

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#5209]
/kind question

**Question:**
The Kubeflow Community Product Management Team is suggesting that we should conduct a Kubeflow 1.2 Planning Session with Kubeflow Users.

The proposal is provided in this doc: https://docs.google.com/document/d/1KgXG6qMcsoBGnT1aPMcAgbGONojcsi1JDV5cKsZEdQM/edit

We would like to conduct this session in August.

**Comment by jbottum** [comment]
@elviraux @aronchick @jtfogarty Hey Elvira, David, Jeff - do you have any comments on this proposal ?

**Comment by cliveseldon** [comment]
Should we ask in "devops/architects" section what other systems or services Kubeflow should provide easy integration with?
