### ISSUE TITLE
ksonnet + openshift picking up wrong k8s version number

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#521]
trying Kubeflow on [Openshift online](https://www.openshift.com/features/index.html). Have problem with namespace and ksonnet.
Any possible work around? 

1. cannot create namespace on openshift 
```
kubectl create namespace ${NAMESPACE}
Error from server (Forbidden): namespaces is forbidden: User "feixue@google.com" cannot create namespaces at the cluster scope: User "feixue@google.com" cannot create namespaces at the cluster scope
```
2. without namespace cannot deploy ks application 
```bash
➜ ks apply ${KF_ENV} -c kubeflow-core

ERROR Error reading /Users/feixue/code/openshift/my-kubeflow/environments/default/main.jsonnet: /Users/feixue/code/openshift/my-kubeflow/components/kubeflow-core.jsonnet:8:49-52 Unknown variable: env

  namespace: if params.namespace == "null" then env.namespace else params.namespace
```

**Comment by pdmack** [comment]
Try `oc new-project ${NAMESPACE}` instead. OpenShift leverages the concept of Kubernetes namespaces to securely group and isolate related objects as described [here](https://docs.openshift.org/latest/admin_guide/managing_projects.html).

Note that you may have difficulty spinning up all the Kubeflow pods due to [resource limits](https://www.openshift.com/pricing/index.html) imposed by OpenShift Online.

**Comment by fxue** [comment]
Thanks, I will give that a try!

**Comment by fxue** [comment]
still bumping into same error, set namespace on default env but get unknown variable env 

```bash
➜  my-kubeflow ks env set default --namespace ${NAMESPACE}

INFO  Using context 'kubeflow/api-starter-us-west-1-openshift-com:443/feixue@google.com' from the kubeconfig file specified at the environment variable $KUBECONFIG
INFO  Setting environment server to 'https://api.starter-us-west-1.openshift.com:443'
INFO  Setting environment namespace to 'kubeflow'
INFO  Successfully updated environment 'default'
➜  my-kubeflow ks show default -c kubeflow-core           

ERROR Error reading /Users/feixue/code/openshift/my-kubeflow/environments/default/main.jsonnet: /Users/feixue/code/openshift/my-kubeflow/components/kubeflow-core.jsonnet:8:49-52 Unknown variable: env

  namespace: if params.namespace == "null" then env.namespace else params.namespace
```

**Comment by fxue** [comment]
Looking at the code, seems that env is not being defined, bug?

```
local params = std.extVar("__ksonnet/params").components["kubeflow-core"];
local k = import "k.libsonnet";
local all = import "kubeflow/core/all.libsonnet";

// updatedParams uses the environment namespace if
// the namespace parameter is not explicitly set
local updatedParams = params {
  namespace: if params.namespace == "null" then env.namespace else params.namespace
};

std.prune(k.core.v1.list.new(all.parts(updatedParams).all))
```

**Comment by fxue** [comment]
still getting error after setting the param, run time problem
```
➜  my-kubeflow ks param set kubeflow-core namespace kubeflow
INFO  Parameter 'namespace' successfully set to '"kubeflow"' for component 'kubeflow-core'
➜  my-kubeflow ks show default -c kubeflow-core                                           

ERROR Error reading /Users/feixue/code/openshift/my-kubeflow/environments/default/main.jsonnet: /Users/feixue/code/openshift/my-kubeflow/components/kubeflow-core.jsonnet:8:49-52 Unknown variable: env

  namespace: if params.namespace == "null" then env.namespace else params.namespace
```

**Comment by fxue** [comment]
maybe a ksonnet version issue, upgrading.
```
➜  my-kubeflow ks version 
ksonnet version: 0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```

**Comment by fxue** [comment]
ok - updated the ksonnet version
```
➜  my-kubeflow ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
```
getting a different 404 error now. 
```
➜  my-kubeflow ks show ${KF_ENV} -c kubeflow-core
ERROR Recieved status code '404' when trying to retrieve OpenAPI schema for cluster version 'v3.9.14' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v3.9.14/api/openapi-spec/swagger.json'

```

**Comment by fxue** [comment]
@pdmack have you ever deployed kubeflow on Openshift environment before? would love to learn about any best practices.
You mentioned resource might not be enough with Openshift Online - any other managed offerings or should I try Origin?

**Comment by pdmack** [comment]
@fxue I have, and noted some permission adjustments [here](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#openshift). Origin is a good option if you have a RHEL/CentOS env capable of comfortably running the TF notebook, etc. [Here](https://docs.openshift.org/latest/install_config/install/advanced_install.html) are the Ansible installation details for that.

Having said all that, there is a nifty feature of the OpenShift client that spins up OpenShift in a VM. `oc cluster up` will give you a local developer env where you can try out some of the features of OpenShift that make it enterprise-ready kube. Just need a docker daemon (not included) for your platform. The client installers for your platform of choice can be found [here](https://github.com/openshift/origin/releases).

3.9 is not quite out yet but v3.9.0-alpha3 is pretty solid IMHO. Note that there is a gotcha on [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) that will prevent you pushing to the local registry.

**Comment by fxue** [comment]
@pdmack any reason I should use the advanced installation instead of the quick installation?

**Comment by jlewi** [comment]
```
➜  ks show ${KF_ENV} -c kubeflow-core
ERROR Recieved status code '404' when trying to retrieve OpenAPI schema for cluster version 'v3.9.14' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v3.9.14/api/openapi-spec/swagger.json'
```

This is either an issue with open shift or ksonnet but most likely not Kubeflow.

I think ksonnet tries to download an OpenSwagger spec and uses that to communicate with your K8s cluster. The 404 indicates the ksonnet client is trying to download an OpenSwagger spec for a particular version of OpenShift and not finding that spec in the expected location. So could be

- An issue with ksonnet not getting the correct version of the cluster
- An issue with the URL being incorrect

I think its the former. I think the version is being incorrectly set to the open shift version and not the kubernetes version.

Try the following
 - In your ksonnet app dir
 - Open up app.yaml
- set k8sVerion to v1.7.0 e.g.

```
k8sVersion: v1.7.0
```


/cc @pdmack @bryani

**Comment by pdmack** [comment]
Yeah, @jlewi has it right. What's happening by default is that it's interpreting the version based on what it gets from your current context, which is an OpenShift context. Not quite sure exactly _how_ it's getting the OpenSHift version out of that yet but will keep poking.

On the init, you can override the api spec version: 
`ks init ${APP_NAME} --api-spec=version:v1.7.0`

**Comment by pdmack** [comment]
@fxue re: Quick vs. Advanced

Quick can start up an all-in-one as either a VM (`oc cluster up`) for all major platforms or as a set of Linux services (`sudo ./openshift start`). In both those cases, it is a local environment to try out the features. An Advanced install provides the complete spectrum of parameters required by and administrator to deploy an enterprise-class Kubernetes developer platform across multiple nodes and various supported cloud providers.

**Comment by fxue** [comment]
Thanks @jlewi and @pdmack - both solutions work. filed ksonnet issue for folks there to take a look.
Now i'm blocked by #615 an authorization issue.

**Comment by jlewi** [comment]
@pdmack can you confirm if this issue is fixed for open shift with the latest ksonnet version?

**Comment by pdmack** [comment]
Will take a look.

**Comment by pdmack** [comment]
This particular issue is resolved. Tested using the latest ks and okd (OpenShift).
```
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://xci09.lab.eng.rdu2.redhat.com:8443
openshift v3.11.0+316e91d-49
kubernetes v1.11.0+d4cacc0
    k8sVersion: v1.11.0
```

**Comment by jlewi** [comment]
- Thanks @pdmack
