### ISSUE TITLE
404 error for istioctl installation instructions

### ISSUE THREAD

**Issue by mcantrell** [kubeflow/kubeflow#5212]
> Follow these _instructions_ to install istioctl

The instructions link is bad (404 error). After searching around, I think this may be the new link:

https://cloud.google.com/service-mesh/docs/gke-install-asm#downloading_the_installation_file

**Comment by theophilee** [comment]
Hi @mcantrell, I run into the same issue. Are these the right instructions? Seems like a lot of work and it requires to active Anthos that is paid service...

**Comment by jbottum** [comment]
@mcantrell Hi Mike, did you get this resolved ?
