### ISSUE TITLE
gcr.io/arrikto-playground/rok-kmod:v0.14-106-g3a338c1 You don't have the needed permissions to perform this operation

### ISSUE THREAD

**Issue by gudipudipradeep** [kubeflow/kubeflow#5217]
Error response from daemon: unauthorized: 
You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

**Comment by jbottum** [comment]
Hi @gudipudipradeep , is this issue still open?  Are you running this on MiniKF on GCP ?
