### ISSUE TITLE
Release - Kubeflow v1.2 

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#5219]
/kind process

**Why you need this:**
[Is your feature request related to a problem? Please describe in details]
This is an uber tracking issue for releasing related issues/bugs.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

- [ ] Update [releasing docs](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md)
- [ ] Prow/GitHub Actions to automate some of the manual releasing process 
 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/cc @jlewi @animeshsingh @aronchick @Jeffwan @Bobgy @adrian555

**Comment by Jeffwan** [comment]
I am cleaning PRs and issues in kubeflow/kfctl and kubeflow/manifest.

**Comment by Jeffwan** [comment]
Seems it's hard for me to update some content. I will open a new issue.
