### ISSUE TITLE
PodDefaults needs an OWNERs file

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5220]
/kind process

The directory for the PodDefaults controller is missing an OWNERs file
https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook

We should also consider renaming the directory.

@yanniszark mentioned in kubeflow/community#381 he might be willing to be an OWNER.

@discordianfish might also be interested.

**Comment by discordianfish** [comment]
Isn't the plan to replace this by podpresets anyway? But I can be an owner for now at least.

**Comment by Jeffwan** [comment]
@discordianfish I think long term yes,  podpresets is still `alpha` and most of the distribution doesn't support alpha feature yet. Whenever it becomes BETA, we can replace current solution with it.

**Comment by yanniszark** [comment]
@jlewi @discordianfish made a PR here: https://github.com/kubeflow/kubeflow/pull/5229
