### ISSUE TITLE
Contrib  DockerImages (rapidsai and kaggle) need OWNERs files

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5221]
/kind process

The images are in the contrib directory
https://github.com/kubeflow/kubeflow/tree/master/components/contrib

cc @thesuperzapper and @pdmack

**Comment by thesuperzapper** [comment]
/close
These have been moved to: https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image/contrib
