### ISSUE TITLE
Installation guide for GCP is incomplete and it's impossible to deploy new Kubeflow cluster

### ISSUE THREAD

**Issue by marrrcin** [kubeflow/kubeflow#5223]
/kind bug

**What steps did you take and what happened:**
I've carefully followed the GCP Kubeflow deployment guide **twice** (starting from scratch), without success.
https://www.kubeflow.org/docs/gke/deploy/

My `set-values` from Makefile (the one from https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#fetch-packages-using-kpt):
```makefile
set-values:
	kpt cfg set ./instance gke.private false

	kpt cfg set ./instance mgmt-ctxt kf-mgmnt

	kpt cfg set ./upstream/manifests/gcp name kf
	kpt cfg set ./upstream/manifests/gcp gcloud.core.project XXX
	kpt cfg set ./upstream/manifests/gcp gcloud.compute.zone europe-west4
	kpt cfg set ./upstream/manifests/gcp location europe-west4-b
	kpt cfg set ./upstream/manifests/gcp log-firewalls false

	kpt cfg set ./upstream/manifests/stacks/gcp name kf
	kpt cfg set ./upstream/manifests/stacks/gcp gcloud.core.project XXX

	kpt cfg set ./instance name kf
	kpt cfg set ./instance location europe-west4-b
	kpt cfg set ./instance gcloud.core.project XXX
	kpt cfg set ./instance email X@XX
```

Final error I get after running `make apply` in step https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#deploy-kubeflow is:
```bash
kubectl --context=kf-mgmnt wait --for=condition=Ready --timeout=600s  containercluster kf
error: timed out waiting for the condition on containerclusters/kf
```

**What did you expect to happen:**
Installation is seamless and completes without errors, installation guide is complete.

**Anything else you would like to add:**
Current deployment documentation seems to be neglected and there are a lot of missing pieces there that waste people's time on digging through many GitHub issues.

**Issues I've had to deal with manually / questions:**
1. When management cluster has long name, like **kubeflow-management**, the setup https://www.kubeflow.org/docs/gke/deploy/management-setup/ cannot be completed due to violation of some max characters limit for service account names
1. The guide https://www.kubeflow.org/docs/gke/deploy/ does not mention that you need kustomize IN SPECIFIC VERSION (https://github.com/kubeflow/manifests/issues/1490#issuecomment-674092679), istioctl IN GOOGLE-PROVIDED version (https://github.com/kubeflow/manifests/issues/1490#issuecomment-673729937)
1. There is a strong assumption that cluster needs to have the namespace exactly the same as the project? Why is that? 
1. Why Kubeflow needs a separate "management" cluster now?

**Environment:**

- Kubeflow version: n/a
- kfctl version: (use `kfctl version`): not installed
- Kubernetes platform: GCP
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS: macOS 10.15.1

**Comment by subodh101** [comment]
Regarding the error. I think this has been resolved.
Did you follow with [updated docs](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#configure-kubeflow)?

### Make the managed project’s namespace default of the context:
```
kubectl config set-context --current --namespace ${PROJECT}
```

If not it's okay. Just edit the line in the instance Makefile with namespace.
```
kubectl --context=$(MGMTCTXT) wait --for=condition=Ready --timeout=600s  containercluster $(NAME) -n <MANAGED_PROJECT>

**Comment by theophilee** [comment]
First of all, I really appreciate the effort put by the community in the Kubeflow project, it's really awesome.
But @marrrcin I have the same impression as you after trying to set up the GCP guide: the documentation really seems to be neglected.
When you make a change that's not backward compatible (e.g., introduce a management cluster), please make sure that the new documentation works...

**Comment by 8bitmp3** [comment]
@marrrcin @theophilee - I'm an external contributor and reviewer here. Saw your post on Slack and I appreciate your awesome feedback.

Can you please do the following to get this resolved faster:
- Move/duplucate this docs-related issue in www.github.com/kubeflow/website since that is where the docs sit. 
- Assign the team at GCP (`/assign @Bobgy @joeliedtke @jlewi`) and they or somewhere else from Google Cloud should get back to you asap.

I will try to help you all too, if I can. 

Thanks a million!

**Comment by marrrcin** [comment]
> Regarding the error. I think this has been resolved.
> Did you follow with [updated docs](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#configure-kubeflow)?
> 
> ### Make the managed project’s namespace default of the context:
> ```
> kubectl config set-context --current --namespace ${PROJECT}
> ```
> 
> If not it's okay. Just edit the line in the instance Makefile with namespace.
> 
> ```
> kubectl --context=$(MGMTCTXT) wait --for=condition=Ready --timeout=600s  containercluster $(NAME) -n <MANAGED_PROJECT>
> ```

1. Of course I've used the most recent docs.
2. Your solution does not help.

**Comment by thesuperzapper** [comment]
I feel like I could contribute a guide for deploying vanilla K8S (dex based) using argo-cd.

**Comment by Bobgy** [comment]
Hi all, I feel sorry you are getting the frustration when deploying to GCP.

I have already updated problems 2. in the public docs (before I saw this issue), so I hope there won't be future confusions for others.
Thanks for mentioning 1, and I will add that to the docs.

For @marrrcin's problem when deploying, we could have done better at explaining what it means when we are waiting for containercluster resource. The management cluster runs a https://cloud.google.com/config-connector/docs/overview instance, which can reconcile kubernetes CRDs into GCP resources (like clusters, service accounts, IAM policy rules).

You are timing out waiting for the containercluster resource to be ready, so you can debug it by
```
kubectl --context ${MGMTCONTEXT} get containercluster -n ${PROJECT}  -o yaml
```
And the resource will have a `status` field like other kubernetes resources, it will have detailed reason for the failure.

Reading your config, I'm not sure if "kpt cfg set ./upstream/manifests/gcp gcloud.compute.zone europe-west4" was a typo or not, you should specify a zone there, but you put a region there instead.

I'll try to explain some of the reasonings we made with the updated blueprint pattern and why we are doing these in https://github.com/kubeflow/gcp-blueprints/issues/123 when I get some time (it's been a busy week).

**Comment by Bobgy** [comment]
@thesuperzapper I think that's a good idea too!

The current GCP blueprint pattern focuses on making GCP resource provisioning scalable (it works with customizations and upgrades), but if you prefer managing GCP resources yourself, or just want to use GCP resources as minimal as possible and use Kubernetes resources instead. Not using the blueprint pattern also makes sense.

Note that the `makefile` in blueprint is meant to be easy to understand and customizable, if you don't want those GCP resources, you can skip management cluster, applying GCP resources and only use it to hydrate and apply kubernetes resources.

**Comment by Bobgy** [comment]
Hi @cm185255 
```
  status:
    conditions:
    - lastTransitionTime: "2020-08-21T18:44:53Z"
      message: reference IAMServiceAccount XXXX/xx-vm is
        not ready
      reason: DependencyNotReady
      status: "False"
      type: Ready
```
Here's the important part and it tells another service account this cluster depends on is not ready.

You can debug what went wrong with the service account in the same approach.
```
kubectl --context ${MGMTCONTEXT} describe iamserviceaccount -n ${PROJECT}
# note, you can also use `kubectl get -o yaml`, but describe's output is more readable
```

**Comment by Bobgy** [comment]
Hi all, I answered most of questions raised here centrally in https://github.com/kubeflow/gcp-blueprints/issues/123. Please take a look and feel free to ask me any further questions.

**Comment by cm185255** [comment]
Thanks @Bobgy very much for the feedback and for providing the commands. 

When I run `kubectl --context ${MGMTCONTEXT} describe iamserviceaccount -n ${PROJECT}`, this is the output: 
```
Name:         xx-admin
Namespace:    XXXX
Labels:       kf-name=xx
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: none
              cnrm.cloud.google.com/project-id: XXXX
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"iam.cnrm.cloud.google.com/v1beta1","kind":"IAMServiceAccount","metadata":{"annotations":{},"labels":{"kf-name":"xx"}...
API Version:  iam.cnrm.cloud.google.com/v1beta1
Kind:         IAMServiceAccount
Metadata:
  Creation Timestamp:  2020-08-21T18:45:28Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:        15
  Resource Version:  78378
  Self Link:         /apis/iam.cnrm.cloud.google.com/v1beta1/namespaces/XXXX/iamserviceaccounts/xx
  UID:               1c12bab9-d71b-417f-b3b0-88e25c5d569a
Spec:
  Display Name:  kubeflow admin service account
Status:
  Conditions:
    Last Transition Time:  2020-08-21T20:14:47Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Email:                   xx-admin@XXXX.iam.gserviceaccount.com
  Name:                    projects/XXXX7/serviceAccounts/xx-admin@XXXX.iam.gserviceaccount.com
  Unique Id:               101226608390048011955
Events:                    <none>

Name:         xx-user
Namespace:    XXXX
Labels:       kf-name=xx
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: none
              cnrm.cloud.google.com/project-id: XXXX
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"iam.cnrm.cloud.google.com/v1beta1","kind":"IAMServiceAccount","metadata":{"annotations":{},"labels":{"kf-name":"xx"}...
API Version:  iam.cnrm.cloud.google.com/v1beta1
Kind:         IAMServiceAccount
Metadata:
  Creation Timestamp:  2020-08-21T18:45:30Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:        15
  Resource Version:  78430
  Self Link:         /apis/iam.cnrm.cloud.google.com/v1beta1/namespaces/XXXX/iamserviceaccounts/xx
  UID:               d7e94ed1-1946-458a-a6e7-cf626ccae211
Spec:
  Display Name:  kubeflow user service account
Status:
  Conditions:
    Last Transition Time:  2020-08-21T20:14:55Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Email:                   xxf-user@XXXX.iam.gserviceaccount.com
  Name:                    projects/XXXX/serviceAccounts/xx-user@XXXX.iam.gserviceaccount.com
  Unique Id:               104591388018196568815
Events:                    <none>

Name:         xx-vm
Namespace:    XXXX
Labels:       kf-name=xx
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: none
              cnrm.cloud.google.com/project-id: XXXX
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"iam.cnrm.cloud.google.com/v1beta1","kind":"IAMServiceAccount","metadata":{"annotations":{},"labels":{"kf-name":"xx"}...
API Version:  iam.cnrm.cloud.google.com/v1beta1
Kind:         IAMServiceAccount
Metadata:
  Creation Timestamp:  2020-08-21T18:45:31Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:        18
  Resource Version:  78451
  Self Link:         /apis/iam.cnrm.cloud.google.com/v1beta1/namespaces/kubeflow-explore-287117/iamserviceaccounts/xx-vm
  UID:               0a6d947a-1317-4ed0-9049-4f1e0118910c
Spec:
  Display Name:  kubeflow vm service account
Status:
  Conditions:
    Last Transition Time:  2020-08-21T20:14:59Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Email:                   xx-vm@XXXX.iam.gserviceaccount.com
  Name:                    projects/XXXX/serviceAccounts/xx-vm@XXXX.iam.gserviceaccount.com
  Unique Id:               110984778110870330220
Events:                    <none>
```
From this output, everything looks fine with the `kubeflow vm service account`; it now says it is `Ready`. 

However the useful portion of `kubectl --context xx get containercluster -n XXXX -o yaml` now reveals: 
```
status:
    conditions:
    - lastTransitionTime: "2020-08-21T18:44:53Z"
      message: 'Update call failed: the desired mutation for the following field(s)
        is invalid: [nodeConfig.0.ServiceAccount nodeConfig.0.MachineType ipAllocationPolicy.#
        nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.3859019814 initialNodeCount]'
      reason: UpdateFailed
      status: "False"
      type: Ready
```

This message also prints as a warning at the bottom of `kubectl describe containercluster --context xx -n XXXX xx`:
```
Warning  UpdateFailed  52s   containercluster-controller  Update call failed: the desired mutation for the following field(s) is invalid: [nodeConfig.0.ServiceAccount nodeConfig.0.MachineType ipAllocationPolicy.# nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.3859019814 initialNodeCount]
```

I don't see anything online about this issue. Could you please let me know if you have any insight about this message, or what may be going on? Thanks!

**Comment by jlewi** [comment]
@cm185255 The error indicates your configuration is invalid. Can you attach the output of

```
kubectl --context=${MGMT-CTXT} --namespace ${PROJECT} get containercluster -o yaml
```

Does the cluster actually exist? e.g.

```
gcloud --project=${PROJECT} container clusters list
```

Try deleting the K8s resource and recreating it

```
kubectl --context=${MGMT-CTXT} --namespace ${PROJECT} delete containercluster ${NAM}
make apply
```

**Comment by cm185255** [comment]
@jlewi Thanks for you feedback. 

The full output for `kubectl --context=xx --namespace XXXX get containercluster -o yaml` (with ${PROJECT} changed to `XXXX` and ${MGMT-CTXT} changed to `xx`) is:
```
apiVersion: v1
items:
- apiVersion: container.cnrm.cloud.google.com/v1beta1
  kind: ContainerCluster
  metadata:
    annotations:
      cnrm.cloud.google.com/management-conflict-prevention-policy: resource
      cnrm.cloud.google.com/project-id: XXXX
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"container.cnrm.cloud.google.com/v1beta1","kind":"ContainerCluster","metadata":{"annotations":{},"clusterName":"XXXX/us-east1-b/xx","labels":{"kf-name":"xxf","mesh_id":"XXXX_us-east1-b_xx"},"name":"xx","namespace":"XXXX"},"spec":{"clusterAutoscaling":{"autoProvisioningDefaults":{"oauthScopes":["https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/devstorage.read_only"],"serviceAccountRef":{"name":"xx-vm"}},"enabled":true,"resourceLimits":[{"maximum":128,"resourceType":"cpu"},{"maximum":2000,"resourceType":"memory"},{"maximum":16,"resourceType":"nvidia-tesla-k80"}]},"initialNodeCount":2,"location":"us-east1-b","loggingService":"logging.googleapis.com/kubernetes","monitoringService":"monitoring.googleapis.com/kubernetes","nodeConfig":{"machineType":"n1-standard-8","metadata":{"disable-legacy-endpoints":"true"},"oauthScopes":["https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/devstorage.read_only"],"serviceAccountRef":{"name":"xx-vm"},"workloadMetadataConfig":{"nodeMetadata":"GKE_METADATA_SERVER"}},"releaseChannel":{"channel":"REGULAR"},"workloadIdentityConfig":{"identityNamespace":"XXXX.svc.id.goog"}}}
    creationTimestamp: "2020-08-24T16:00:09Z"
    generation: 20
    labels:
      kf-name: xx
      mesh_id: XXXX_us-east1-b_xx
    name: xx
    namespace: XXXX
    resourceVersion: "1290712"
    selfLink: /apis/container.cnrm.cloud.google.com/v1beta1/namespaces/XXXX/containerclusters/xx
    uid: 0c9868a3-d248-430a-aa42-7543fc2b6b09
  spec:
    clusterAutoscaling:
      autoProvisioningDefaults:
        oauthScopes:
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/devstorage.read_only
        serviceAccountRef:
          name: xx-vm
      enabled: true
      resourceLimits:
      - maximum: 128
        resourceType: cpu
      - maximum: 2000
        resourceType: memory
      - maximum: 16
        resourceType: nvidia-tesla-k80
    initialNodeCount: 2
    location: us-east1-b
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    nodeConfig:
      machineType: n1-standard-8
      metadata:
        disable-legacy-endpoints: "true"
      oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/devstorage.read_only
      serviceAccountRef:
        name: xx-vm
      workloadMetadataConfig:
        nodeMetadata: GKE_METADATA_SERVER
    releaseChannel:
      channel: REGULAR
    workloadIdentityConfig:
      identityNamespace: XXXX.svc.id.goog
  status:
    conditions:
    - lastTransitionTime: "2020-08-24T16:00:12Z"
      message: 'Update call failed: the desired mutation for the following field(s)
        is invalid: [nodeConfig.0.OauthScopes.# ipAllocationPolicy.# initialNodeCount
        nodeConfig.0.OauthScopes.3859019814 nodeConfig.0.MachineType nodeConfig.0.ServiceAccount]'
      reason: UpdateFailed
      status: "False"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
with the same `UpdateFailed` message printed in the `status` section. 

The cluster does seem to exist from `gcloud --project=${PROJECT} container clusters list`
```
NAME       LOCATION    MASTER_VERSION  MASTER_IP      MACHINE_TYPE   NODE_VERSION   NUM_NODES  STATUS
xx         us-east1-b  1.16.13-gke.1   xx.xxx.xxx.xx  n1-standard-4  1.16.13-gke.1  2          RUNNING
```

when I check the deployment via 
```
gcloud container clusters get-credentials ${KF_NAME} --zone ${ZONE} --project ${PROJECT}
kubectl -n kubeflow get all
```
from the [tutorial](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#configure-kubeflow) I get: 
```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for xx.

No resources found in kubeflow namespace.
```

I tried the final step of deleting the K8s resource and recreating, but was met with the same timeout issue and the same `UpdateFailed` `status` and other outputs detailed above

**Comment by Bobgy** [comment]
@cm185255 can you try this to make sure it's not race condition?
```
kubectl --context=${MGMT-CTXT} --namespace ${PROJECT} delete containercluster ${NAM}
# wait a while
gcloud --project=${PROJECT} container clusters list
# verify the cluster has already been deleted
make apply
```

**Comment by Bobgy** [comment]
@cm185255 I created an issue for you in Cloud Config Connector's repo. We can follow up there if this still doesn't work.
https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/259

**Comment by Rustastra** [comment]
I am experiencing this issue too when following https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#deploy-kubeflow

**Comment by jlewi** [comment]
@Rustastra Per GoogleCloudPlatform/k8s-config-connector#259 it looks like the problem is fixed in newer versions of KCC.

I would suggest following the [Cloud Config Connector Docs](https://cloud.google.com/config-connector/docs/how-to/install-other-kubernetes) to install or upgrade KCC on your management cluster.

**Comment by Rustastra** [comment]
@jlewi thank you! after a lot of poking around, I realised what the error was for me after seeing this:

"Just for confirmation, did you try to deploy kubeflow into the management cluster? That's not supported. You need to use a different cluster for kubeflow." [here ](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/259#issuecomment-680169631)

I was setting the same values to KF_NAME and NAME in Makefile, which resulted in an attempt to deploy KF into management cluster.

**Comment by Bobgy** [comment]
I think most of the issues mentioned in the original issue has been either fixed or documentation updated to clarify that. Also most of people who replied got there problem solved, but original reporter @marrrcin didn't reply here.
Closing the issue to clean up backlog, if anyone has any further problems, feel free to create a new issue in www.github.com/kubeflow/gcp-blueprints repo.

I am here to keep supporting Kubeflow GCP installation guide, and I keep making sure it's possible to deploy (as it is today). There might be edge cases that needs everyone's help to report & fix/document, because this is open source.

**Comment by wuurrd** [comment]
If anyone in the future like me hit this problem with a newer version and couldn't figure it out there should be two clusters, one for management and one for kubeflow
so make sure your management cluster
```
export MGMT_NAME
```
and your kubeflow cluster
```
export KF_NAME
```
have different names.
