### ISSUE TITLE
[Release 1.2] Feature Planning / Roadmap

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#5224]
/kind question

**Question:**
Hey all,
This is a tracking issue for feature planing and release roadmap for Kubeflow 1.2.
This will serve as a common issue to track features going into 1.2 and touch base with the application owners / WG owners. 

It'd be great if they could post a list of things they're planning around 1.2.
/cc 
Application WGs:
- KF Serving: @cliveseldon @animeshsingh @yuzisun 
- KF Pipelines: @Bobgy 
- Training: @johnugeorge @gaocegege @andreyvelich (Auto-ML)

**Comment by swiftdiaries** [comment]
KF Serving: https://kubeflow.slack.com/archives/CH6E58LNP/p1597776731267800
Latest release was [KFS v0.4](https://github.com/kubeflow/kfserving/releases/tag/v0.4.0)
This will probably be the release that goes in KF v1.2

**Comment by Bobgy** [comment]
For KF Pipelines, we don't have headline features planned for the upcoming 3 months.
KFP IR is our focus right now, and it will take more than 3 month to land.

**Comment by jlewi** [comment]
@swiftdiaries What is the timeline for 1.2?

**Comment by swiftdiaries** [comment]
Mid-November was the target I was shooting for so mid-October is when I hope to start the process. I want to do a minor release in 2 weeks to get the state of things and document stuff

**Comment by Jeffwan** [comment]
Training storied for 1.2 and this year has been documented in roadmap doc [here](https://github.com/kubeflow/common/blob/master/ROADMAP.md). I think WG-Training will try to finish as more as we can. Some of them might be postposed to 1.3 release. I think we can update the progress later.

/cc @terrytangyuan @gaocegege @johnugeorge @ChanYiLin  Feel free to add more stories.

### Maintenance and reliability

* Enhance maintainability of operator common module. Related issue: [#54](https://github.com/kubeflow/common/issues/54).
* Migrate operators to use [kubeflow/common](https://github.com/kubeflow/common) APIs. Related issue: [#64](https://github.com/kubeflow/common/issues/64).
* Graduate MPI Operator, MXNet Operator and XGBoost Operator to v1. Related issue: [#65](https://github.com/kubeflow/common/issues/65).

### Features

* Support dynamic volume provisioning for distributed training jobs. Related issue: [#19](https://github.com/kubeflow/common/issues/19).
* MLOps - Allow user to submit jobs using Git repo without building container images. Related issue: [#66](https://github.com/kubeflow/common/issues/66).
* Add Job priority and Queue in SchedulingPolicy for advanced scheduling in common operator. Related issue: [#46](https://github.com/kubeflow/common/issues/46).
* Add pipeline launcher components for different training jobs. Related issue: [pipeline#3445](https://github.com/kubeflow/pipelines/issues/3445).
* Surface Pod and other Errors that Prevent TFJob from starting [tf-operator#1131](https://github.com/kubeflow/tf-operator/issues/1131)

### Monitoring

* Provides a standardized logging interface. Related issue: [#60](https://github.com/kubeflow/common/issues/60).
* Expose generic prometheus metrics in common operators. Related issue: [#22](https://github.com/kubeflow/common/issues/22).
* Centralized Job Dashboard for training jobs (Add metadata graph, model artifacts later). Related issue: [#67](https://github.com/kubeflow/common/issues/67).

### Performance

* Performance optimization for 500 concurrent jobs and large scale completed jobs. Related issues: [#68](https://github.com/kubeflow/common/issues/68), [tf-operator#965](https://github.com/kubeflow/tf-operator/issues/965), and [tf-operator#1079](https://github.com/kubeflow/tf-operator/issues/1079).

**Comment by jlewi** [comment]
@swiftdiaries Could you provide an update on the release? Are the respective WGs on track? It would be good to have a standing item on the agenda to discuss the release.

**Comment by jlewi** [comment]
Any update on the release?

/cc @kubeflow/wg-automl-leads @kubeflow/wg-serving-leads @kubeflow/wg-training-leads

**Comment by jlewi** [comment]
@kimwnasptd @thesuperzapper  any update for notebooks?

@Jeffwan @animeshsingh @yanniszark @swiftdiaries @vpavlin @yanniszark  update for deployments/kfctl/manifests?

**Comment by Jeffwan** [comment]
@jlewi I will give some updates on training side later next week.

**Comment by jlewi** [comment]
Prospective deployment leads(@Jeffwan @animeshsingh @yanniszark @swiftdiaries @vpavlin @yanniszark ) releases are arguably defined by the branch cut of kubeflow/manifests.

Per kubeflow/community#402 this repo will be owned by you. Do we have a date for a branch cut? The initial suggested date was mid october. We are arguably past October. 

Does someone want to volunteer to take the lead on cutting the branch and coordinating with the wgs to get their manifests up dated.

**Comment by andreyvelich** [comment]
> Any update on the release?
> 
> /cc @kubeflow/wg-automl-leads @kubeflow/wg-serving-leads @kubeflow/wg-training-leads

From AutoML WG this is the track issue: https://github.com/kubeflow/katib/issues/1360.

**Comment by thesuperzapper** [comment]
Depending on the cutoff date for Kubeflow 1.2, we would really like to get the new crud-web-app implemented to replace the old jupyter-web-app, the first PR is https://github.com/kubeflow/kubeflow/pull/5332, but there is more to come before it will be ready for prime time.

If the cutoff is really soon, we might use some variation of PR https://github.com/kubeflow/kubeflow/pull/5280 to ensure we get some features released.

Comments @kimwnasptd?

**Comment by jlewi** [comment]
@thesuperzapper The cutoff date was [mid-october](https://github.com/kubeflow/kubeflow/issues/5224#issuecomment-684870503) so it is arguably past. I would encourage all application owners to ensure their manifests are as up to date as possible to avoid missing the release.

**Comment by thesuperzapper** [comment]
@jlewi, while I agree that we missed the boat (assuming a mid October cutoff) this raises some questions about Kubeflow 1.2

What major changes are being implemented?

I agree with @Jeffwan, that we might consider changing how we manage releases to a voting system, to make sure there is sufficient differentiation between releases.

This is especially important because our release process is a bit arduous and long.

**Comment by Jeffwan** [comment]
I sent out email about 1.2 release. We still target for Nov 16 and plan to cut release around Nov 7. I don't think we will have that  many features to roll out as before. Stability is the first priority in this version. I will pull a list from engineer point of view and coordinate with PMs on the features list/improvement in 1.2. 

WG Owners, please help make sure code can be complete asap and let's at least build a stable manifest into 1.2. for kubeflow manifest testing, I need help from different cloud provider or vendors to sign off the release. @PatrickXYS  @animeshsingh @yanniszark @vpavlin @Bobgy @adrian555 

/cc @kubeflow/wg-automl-leads
/cc @kubeflow/wg-pipeline-leads
/cc @kubeflow/wg-serving-leads
/cc @kubeflow/wg-training-leads
/cc @kubeflow/wg-notebook-leads

**Comment by PatrickXYS** [comment]
Thanks for driving 1.2 @Jeffwan 

I'll help validate release from AWS side as well

**Comment by Bobgy** [comment]
Pipelines side will update manifests to include KFP 1.0.4.
I'll own that.

**Comment by nakfour** [comment]
@Jeffwan can we add https://github.com/kubeflow/manifests/pull/1567 ?

**Comment by thesuperzapper** [comment]
@Jeffwan I thought we agreed that the release would be cut on the 15th, not the 7th

**Comment by Jeffwan** [comment]
1.2 Feature Planning / Roadmap are done. Let's track release progress in https://github.com/kubeflow/kubeflow/issues/5371
