### ISSUE TITLE
RBAC: access denied when opening notebook server in shared namespace with multi-tenancy

### ISSUE THREAD

**Issue by nlaanait** [kubeflow/kubeflow#5227]
/kind bug

**What steps did you take and what happened:**
In my deployment of kubeflow v1.1 (on EKS cluster) with multi-tenancy, I'm finding that if `User-A` adds `User-B` as a namespace contributor (and vice versa) then `User-A `cannot open a jupyter notebook in the `User-B` namespace (and vice versa). 
Opening the jupyter notebook results in an empty page with `RBAC: access denied`.

However, `User-A` _can successfully create_ a new jupyter notebook server in the `User-B` namespace (and vice versa).

**What did you expect to happen:**
`User-A` can open an existing jupyter notebook in `User-B`'s namespace (or any other namespace they have access to).

**Anything else you would like to add:**
- `User-A` and `User-B` are authenticated via Dex.  
- `kubeflow` configuration used: https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: `EKS 1.14.9` ( `eksctl 0.24.0`)
- Kubernetes version: `Client Version: 1.17+ GitVersion:"v1.17.7-eks-bffbac",  Server Version: 1.14+ GitVersion:"v1.14.9-eks-658790"`
- OS : 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by Jeffwan** [comment]
I will help check the if I can reproduce the issue `RBAC: access denied`.

**Comment by Jeffwan** [comment]
```
  spec:
    roleRef:
      kind: ServiceRole
      name: ns-access-istio
    subjects:
    - properties:
        request.headers[kubeflow-userid]: xxxxx@amazon.com
  status: {}
- apiVersion: rbac.istio.io/v1alpha1
  kind: ServiceRoleBinding
  metadata:
    annotations:
      role: edit
      user: kf10@amazon.com
    creationTimestamp: "2020-09-16T21:58:44Z"
    generation: 1
    name: user-kf-amazon-com-clusterrole-edit
    namespace: shjiaxin
    resourceVersion: "24135943"
    selfLink: /apis/rbac.istio.io/v1alpha1/namespaces/shjiaxin/servicerolebindings/user-kf-amazon-com-clusterrole-edit
    uid: 19ab1eb5-39be-45b5-92ee-ae970b12c6b4
  spec:
    roleRef:
      kind: ServiceRole
      name: ns-access-istio
    subjects:
    - properties:
        request.headers[x-goog-authenticated-user-email]: kf10@amazon.com
  status: {}

```

As we can see `x-goog-authenticated-user-email` which is the default value is used in istio rules. this value didn't get override by aws configurations.

Put some times on the configuration and notice, we didn't override access-management profile in this version.
To fix this issue, You need to change access-managed 

```
kubectl edit deployment profiles-deployment -n kubeflow

      - command:
        - /access-management
        - -cluster-admin
        - $(CLUSTER_ADMIN)
        - -userid-prefix
        - $(USERID_PREFIX)
++        - -userid-header
++        - $(USERID_HEADER)

```

Wait for containers to restart. 
Delete emails in managed contributors and then add it back. 

Please let me know if that works for you. @nlaanait

**Comment by Jeffwan** [comment]
Since v1.1 we use new format of manifest, this is a regression issue from kustomize v3 migration. Thanks for reporting the issue

**Comment by nlaanait** [comment]
@Jeffwan the fix works. Thanks!
