### ISSUE TITLE
Separate repo for creating/holding release tooling

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#5231]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
As part of https://github.com/kubeflow/kubeflow/issues/5219, I would like to create a repo `kubeflow/release` to hold all the tooling related to releasing.
We no longer have a simple release process so I think it's a good idea to try and automate some of the common chores to make the process smoother.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
This would be similar to or re-use most of the tooling in [kubernetes/release](https://github.com/kubernetes/release#tools) through GitHub Actions or have simple go CLIs for common chores like sending out a release announcement in the mailer.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The OWNERs for the repo would be the release-team members and are expected to maintain the repo and the tooling held within it.

**Comment by jlewi** [comment]
All new projects and repositories need WG sponsorship.  Which WG would be owning this?

Historically, kubeflow/testing has been the repo for common CI/CD infra.

**Comment by swiftdiaries** [comment]
I think it makes sense to hold them in a separate directory under `kubeflow/testing`.
My intention was to create a `wg-release` to ensure we have timely releases and improve our release infrastructure. Let's see if there's enough people to staff it
