### ISSUE TITLE
Minikf doesn't install on GCP

### ISSUE THREAD

**Issue by AigizK** [kubeflow/kubeflow#5234]
/kind bug

**What steps did you take and what happened:**
I use this instruction: https://www.kubeflow.org/docs/started/workstation/minikf-gcp/
Root store 100GB
Data store 200GB

The first problem: the step "Exposing Services 25%". There was an error in logs related to certificates.
Solution: update MiniKF and restart.

Next problem: MySQL doesn't start, Pending status all the time.
We cannot solve this problem.

**What did you expect to happen:**
The MiniKF will started by click on the Launch button

**Comment by yanniszark** [comment]
Hi @AigizK!
The problem is most likely due to your configuration of:
> Root store 100GB
> Data store 200GB

Please use the minimum recommended 200GB root  and 500GB data recommended in GCP and report here if that doesn't fix the issue.

**Comment by AigizK** [comment]
@yanniszark  I found a problem. The Service Management API  was disabled.
After enabling, I could create the MiniKF
