### ISSUE TITLE
How to change the display name of a task?

### ISSUE THREAD

**Issue by zhzhang** [kubeflow/kubeflow#5238]
/kind question

**Question:**
I am trying to create multiple instances of a component that does some redshift queries `redshift-op`, and name each uniquely so that it is displayed in the UI, i.e. `fetch-training-data`, `fetch-test-data` to disambiguate them.
I have seen https://github.com/kubeflow/pipelines/pull/2459 and https://github.com/kubeflow/pipelines/pull/4153 and am trying to take the `TaskSpec` and add `task_spec.annotations = {"pipelines.kubeflow.org/task_display_name": "fetch-training-data"`.
However, this annotation is just ignored when the pod is scheduled, as I can't see it when I do `kubectl describe pod`.
Is this the correct way to change the task display name? If not, how should I do it?

**Comment by jbottum** [comment]
Hi @zhzhang did you get this resolved ?  Which platform are you running on i.e. AWS, GCP, on-prem

**Comment by zhzhang** [comment]
This did get resolved, I was not able to find .set_display_name() in the docs but that is the answer.
I am running on AWS EKS.
