### ISSUE TITLE
Issue with installing v1.0.2 : "google-api-vs" is invalid

### ISSUE THREAD

**Issue by DDDDDDDDDDDDLANG** [kubeflow/kubeflow#5243]
/kind bug

**What steps did you take and what happened:**
attempted to install kubeflow per these instructions:
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

and I run the .sh file:
```
#!/bin/bash

export PATH=$PATH:/home/xxx/kubeflow/kfctl
export KF_NAME=kf-test
export BASE_DIR=/home/xxx/kubeflow
export KF_DIR=${BASE_DIR}/${KF_NAME}
export CONFIG_URI=${BASE_DIR}/kfctl_k8s_istio.v1.0.2.yaml

mkdir -p ${KF_DIR}
cd ${KF_DIR}
/home/xxx/kubeflow/kfctl apply -V -f ${CONFIG_URI}
```

**What did you expect to happen:**
WARN[0593] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run  Error [error when creating "/tmp/kout061279272": VirtualService.networking.istio.io "google-api-vs" is invalid: map[string]interface {}{"apiVersion":"networking.istio.io/v1alpha3", "kind":"VirtualService", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"orking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"google-api-vs\",\"namespace\":\"kubeflow\"},\"spec\":{\"hosts\":[\"www.googleapis.com\"],\"tls\":[{\"match\":[{\"port\":443ww.googleapis.com\"]}],\"route\":[{\"destination\":{\"host\":\"www.googleapis.com\",\"port\":{\"number\":443}},\"weight\":100}]}]}}\n"}, "creationTimestamp":"2020-08-26T06:11:11Z", "generation":1, "name":"google-api-vs", "w", "uid":"d048f588-d65a-4f90-aa27-67568112b63e"}, "spec":map[string]interface {}{"hosts":[]interface {}{"www.googleapis.com"}, "tls":[]interface {}{map[string]interface {}{"match":[]interface {}{map[string]interface {}{"ps":[]interface {}{"www.googleapis.com"}}}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"www.googleapis.com", "port":map[string]interface {}{"number":443}}, "weight":100}}}}}}e list:
spec.tls.match.sniHosts in body is required, error when creating "/tmp/kout061279272": VirtualService.networking.istio.io "google-storage-api-vs" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"networka3", "kind":"VirtualService", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"Virtuala\":{\"annotations\":{},\"name\":\"google-storage-api-vs\",\"namespace\":\"kubeflow\"},\"spec\":{\"hosts\":[\"storage.googleapis.com\"],\"tls\":[{\"match\":[{\"port\":443,\"sni_hosts\":[\"storage.googleapis.com\"]}],\"rout\":{\"host\":\"storage.googleapis.com\",\"port\":{\"number\":443}},\"weight\":100}]}]}}\n"}, "creationTimestamp":"2020-08-26T06:11:11Z", "generation":1, "name":"google-storage-api-vs", "namespace":"kubeflow", "uid":"15829e31b6e896ab3"}, "spec":map[string]interface {}{"hosts":[]interface {}{"storage.googleapis.com"}, "tls":[]interface {}{map[string]interface {}{"match":[]interface {}{map[string]interface {}{"port":443, "sni_hosts":[]interfaceapis.com"}}}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"storage.googleapis.com", "port":map[string]interface {}{"number":443}}, "weight":100}}}}}}: validation failure lis
spec.tls.match.sniHosts in body is required, error when creating "/tmp/kout061279272": VirtualService.networking.istio.io "grafana-vs" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"networking.istio.i:"VirtualService", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\tations\":{},\"name\":\"grafana-vs\",\"namespace\":\"kubeflow\"},\"spec\":{\"gateways\":[\"kubeflow-gateway\"],\"hosts\":[\"*\"],\"http\":[{\"match\":[{\"method\":{\"exact\":\"GET\"},\"uri\":{\"prefix\":\"/istio/grafana/\"uri\":\"/\"},\"route\":[{\"destination\":{\"host\":\"grafana.istio-system.svc.cluster.local\",\"port\":{\"number\":3000}}}]}]}}\n"}, "creationTimestamp":"2020-08-26T06:11:11Z", "generation":1, "name":"grafana-vs", "namespad":"68b05d32-6495-4d3e-b1e9-9747299ffebb"}, "spec":map[string]interface {}{"gateways":[]interface {}{"kubeflow-gateway"}, "hosts":[]interface {}{"*"}, "http":[]interface {}{map[string]interface {}{"match":[]interface {}{ma{}{"method":map[string]interface {}{"exact":"GET"}, "uri":map[string]interface {}{"prefix":"/istio/grafana/"}}}, "rewrite":map[string]interface {}{"uri":"/"}, "route":[]interface {}{map[string]interface {}{"destination":ma{}{"host":"grafana.istio-system.svc.cluster.local", "port":map[string]interface {}{"number":3000}}}}}}}}: validation failure list:
spec.http.route.weight in body is required]  filename="kustomize/kustomize.go:202"
WARN[0593] Will retry in 38 seconds.                     filename="kustomize/kustomize.go:203"
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-admin configured
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-edit unchanged
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-view unchanged
configmap/istio-parameters-t6hhgfg9k2 unchanged
gateway.networking.istio.io/kubeflow-gateway unchanged
serviceentry.networking.istio.io/google-api-entry unchanged
serviceentry.networking.istio.io/google-storage-api-entry unchanged
clusterrbacconfig.rbac.istio.io/default unchanged

**Anything else you would like to add:**
It ran the Istio in my K8S cluster and created the kubeflow namespace. However, there are no resources under the namespace.

**Environment:**

- Kubeflow version: v1.0.2
- kfctl version: v1.0.2-0-ga476281
- Kubernetes platform: Existing K8S Clusters
- Kubernetes version: v1.15.0
- OS (e.g. from `/etc/os-release`): Centos7

**Comment by jbottum** [comment]
Hi @DDDDDDDDDDDDLANG Are you deploying on GCP or another cloud ?   Is this issue still open ?

**Comment by DDDDDDDDDDDDLANG** [comment]
> Hi @DDDDDDDDDDDDLANG Are you deploying on GCP or another cloud ? Is this issue still open ?

That problem has been solved, thanks.
