### ISSUE TITLE
kubeflow v1.0.2 / v1.1.0 installation error on AWS

### ISSUE THREAD

**Issue by tejaschumbalkar** [kubeflow/kubeflow#5245]
/kind bug

**What steps did you take and what happened:**

Installation of kubeflow v1.0.2 and v1.1.0 fails on AWS EKS platform.

Getting the following error while installing kubeflow v1.0.2 with config [kfctl_aws.v1.0.2.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml)

```
$ kfctl apply -V -f kfctl_aws.v1.0.2.yaml
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to <EKS_CLUSTER_NAME> based on location of config file: kfctl_aws.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:71"
INFO[0000] eksctl version: 0.23.0                        filename="utils/awsutil.go:88"
INFO[0000] Creating directory .cache                     filename="kfconfig/types.go:445"
INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz to .cache/manifests  filename="kfconfig/types.go:493"
ERRO[0000] Could not untar file https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz; error gzip: invalid header  filename="kfconfig/types.go:524"
Error: failed to build kfApp from URI kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to build kfApp from URI kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header
```

**What did you expect to happen:**

Kubeflow installation successful on EKS environment.

**Environment:**

- Kubeflow version: v1.0.2
- kfctl version: v1.0.2-0-ga476281
- Kubernetes platform: EKS v1.14

**Comment by ssbhat** [comment]
+1

**Comment by Jeffwan** [comment]
Can you try v1.1 instead? 

for v1.0.2 manually testing seems works fine. 
```
wget https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz
tar -zxvf v1.0.2.tar.gz
```

**Comment by tejaschumbalkar** [comment]
Installation on v1.1 fails as well. Config file used [kfctl_aws.v1.1.0.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml)

```
$ kfctl version
kfctl v1.1.0-0-g9a3621e

$ kfctl apply -V -f kfctl_aws.v1.1.0.yaml
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to <CLUSTER_NAME> based on location of config file: kfctl_aws.v1.1.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:72"
INFO[0000] eksctl version: 0.26.0                        filename="utils/awsutil.go:89"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Creating directory .cache                     filename="kfconfig/types.go:450"
INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz to .cache/manifests  filename="kfconfig/types.go:498"
ERRO[0000] Could not untar file https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz; error gzip: invalid header  filename="kfconfig/types.go:549"
Error: failed to build kfApp from URI kfctl_aws.v1.1.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                         		export CONFIG=./kfctl_gcp_iap.yaml
                         	or a URL:
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                         	kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to build kfApp from URI kfctl_aws.v1.1.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header[ec2-user@ip-172-31-30-163 chumbalk-eks-kubeflow]$
```

**Comment by Jeffwan** [comment]
The problem is http request return 403.  This is Amazon internal network.. 

```
<div class="container">
      <h1>Your access to this site has been restricted.</h1>

      <p>
        <br>
        If you believe this is an error,
        please contact the
        <a href="mailto:support@github.com">Support Team</a>.
      </p>
```

**Comment by Jeffwan** [comment]
walkaround is to use local path point to tar file. I will have a check on the restrictions in our network later. public internet works fine. 
```
  repos:
  - name: manifests
    uri: /your_local_path/v1.0.2.tar.gz
```

**Comment by supertetelman** [comment]
I'm seeing these issues in AWS as well.

Using this deployment script and running in us-west-2.

**Comment by Jeffwan** [comment]
I built binary with the patch and please use kfctl here instead.


darwin 
https://kubeflow-aws.s3-us-west-2.amazonaws.com/kfctl/linux/kfctl_v1.0.2-1-g93e95e1_linux.tar.gz
https://kubeflow-aws.s3-us-west-2.amazonaws.com/kfctl/darwin/kfctl_v1.0.2-1-g93e95e1_darwin.tar.gz

linux
https://kubeflow-aws.s3-us-west-2.amazonaws.com/kfctl/linux/kfctl_v1.1-rc.0-7-g27916db_linux.tar.gz
https://kubeflow-aws.s3-us-west-2.amazonaws.com/kfctl/darwin/kfctl_v1.1-rc.0-7-g27916db_darwin.tar.gz

**Comment by Jeffwan** [comment]
@supertetelman Em. good to know, seems you don't work for Amazon and won't use it in Amazon corp network. Seems other network env get impacted as well? Please have a try on above binary

**Comment by radhakrishnang** [comment]
Ni Hao @Jeffwan  Yes other network seems affected too, 
using this solved the issue - https://kubeflow-aws.s3-us-west-2.amazonaws.com/kfctl/linux/kfctl_v1.1-rc.0-7-g27916db_linux.tar.gz
Xie Xie

**Comment by radhakrishnang** [comment]
@Jeffwan  when i tried following eksworkshop 1.0.1 i get the same error too - is that issue with IAM ?
**ERRO[0000] Could not untar file https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz; error gzip: invalid header  filename="kfconfig/types.go:524**

INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:71"
INFO[0000] eksctl version: 0.28.1                        filename="utils/awsutil.go:88"
INFO[0000] 
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] Creating directory /home/ec2-user/environment/mi4/.cache  filename="kfconfig/types.go:445"
INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz to /home/ec2-user/environment/mi4/.cache/manifests  filename="kfconfig/types.go:493"
**ERRO[0000] Could not untar file https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz; error gzip: invalid header  filename="kfconfig/types.go:524"**
Error: failed to build kfApp from URI /home/ec2-user/environment/mi4/kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to build kfApp from URI /home/ec2-user/environment/mi4/kfctl_aws.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: gzip: invalid header
