### ISSUE TITLE
(Kubeflow v1.1) Error in NODES after scaling down nodepool to 0 and then upscaling it. 

### ISSUE THREAD

**Issue by knave07** [kubeflow/kubeflow#5247]
/kind bug

**What steps did you take and what happened:**
I successfully deployed Kubeflow 1.1 (starting from scratch) using this [guide](https://www.kubeflow.org/docs/gke/deploy/), without any error. I ran a simple pipeline and it worked.

As I deployed this on GCP, I manually scaled down both (mgmt and kubeflow 1.1) clusters to 0 just for saving some cost. When I upscaled them, the management cluster was up properly as it should be but got a weird error in the node(described below), and it didn't scale up. I tried creating another node pool manually but got a similar error. The node goes into `updating state` after a while and again the same error. 

Error in the node:
```bash
runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
``` 

**What did you expect to happen:**

The node should have scaled up normally. 

**Environment:**

- Kubeflow version: 1.1
- kfctl version: Not using kfctl
- Kubernetes platform: GKE 
- Kubernetes version: 1.16.13-gke.1
- OS: macOS Mojave 10.14.5

**UPDATE:** _Tried this on another cluster with kubeflow 1.1 and got the same error._

**Comment by knave07** [comment]
`k -n <project-name> describe containerclusters <kubeflow-name>` shows: 

```bash
Status:
  Conditions:
    Last Transition Time:  2020-08-27T07:26:10Z
    Message:               Update call failed: the desired mutation for the following field(s) is invalid: [nodeConfig.0.OauthScopes.4177124133 nodeConfig.0.OauthScopes.3804780973 nodeConfig.0.OauthScopes.299962681 nodeConfig.0.OauthScopes.3859019814 nodeConfig.0.OauthScopes.316356861 nodeConfig.0.OauthScopes.3663490875 nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.1328717722 nodeConfig.0.Preemptible nodeConfig.0.OauthScopes.4002673104 nodeConfig.0.MinCpuPlatform]
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready
  Endpoint:                35.200.82.170
  Instance Group Urls:
    https://www.googleapis.com/compute/beta/projects/*****/zones/asia-northeast1-c/instanceGroups/gke-***-default-pool-fa9befc0-grp
  Master Version:     1.16.13-gke.1
  servicesIpv4Cidr:   10.43.240.0/20
Events:
  Type     Reason        Age    From                         Message
  ----     ------        ----   ----                         -------
  Warning  UpdateFailed  54m    containercluster-controller  Update call failed: the desired mutation for the following field(s) is invalid: [nodeConfig.0.OauthScopes.*****814 nodeConfig.0.OauthScopes.****2681 nodeConfig.0.OauthScopes.*****104 nodeConfig.0.OauthScopes.*****875 nodeConfig.0.MinCpuPlatform nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.*****33 nodeConfig.0.Preemptible nodeConfig.0.OauthScopes.******814 nodeConfig.0.OauthScopes.*****861 nodeConfig.0.OauthScopes.*****973]
  Warning  UpdateFailed  38m    containercluster-controller  Update call failed: the desired mutation for the following field(s) is invalid: [nodeConfig.0.OauthScopes.*****814 nodeConfig.0.OauthScopes.*****973 nodeConfig.0.OauthScopes.****133 nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.1***22 nodeConfig.0.OauthScopes.*****681 nodeConfig.0.OauthScopes.*****04 nodeConfig.0.Preemptible nodeConfig.0.OauthScopes.******861 nodeConfig.0.MinCpuPlatform nodeConfig.0.OauthScopes.******875]

**Comment by munagekar** [comment]
This happens due to Workload Identity. You can fix it by

1. Deleting all node pools
2. Disabling Workload Identity
3. Recreating a node pool
4. Enabling Workload Identity Again

**Comment by romankazinnik** [comment]
Having same problem. Will we have Kubeflow endpoint with all its historical data preserved by doing 1.-4.?

**Comment by munagekar** [comment]
Yes. All data should be preserved, data is stored in PVC.
