### ISSUE TITLE
MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found

### ISSUE THREAD

**Issue by arshashi** [kubeflow/kubeflow#5248]
/kind bug

**What steps did you take and what happened:**
After kubeflow v1.1.0 is installed, none of the below workloads creates. It fails with an error "ReplicaSet "metadata-writer-694c48ccdc" has timed out progressing.; Deployment does not have minimum availability.".   

In the pod events, I see the below error. This is the same errors on all the pods under the mentioned namespace workloads below

Warning | FailedMount | MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found | a minute ago
-- | -- | -- | --
Warning | FailedMount | Unable to mount volumes for pod "cache-server-65596854d-9r77s_kubeflow(645871c2-acb6-4a72-a0ee-e1c276a639e3)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-65596854d-9r77s". list of unmounted volumes=[webhook-tls-certs]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-55pr6 istio-envoy sds-uds-path istio-token] | 6 minutes ago
Warning | FailedMount | Unable to mount volumes for pod "cache-server-65596854d-9r77s_kubeflow(645871c2-acb6-4a72-a0ee-e1c276a639e3)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-65596854d-9r77s". list of unmounted volumes=[webhook-tls-certs istio-token]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-55pr6 istio-envoy sds-uds-path istio-token] | an hour ago

Namespace: kubeflow
cache-server
cache-deployer-deployment

**What did you expect to happen:**
Pods to get initialized and become active

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.1.0 tried with both with DEX and without
- kfctl version: (use `kfctl version`):  kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): CentOS 7.8

**Comment by zhangchunsheng** [comment]
How to solve this problem?

**Comment by arshashi** [comment]
any inputs how to resolve?

**Comment by ConverJens** [comment]
Also has this issue. Using istio dex 1.1.0 on-prem.

**Comment by swiftdiaries** [comment]
Could you please check your API Server for flags related to token volume?

This section on the docs: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#notes-on-the-configuration-file

**Comment by arshashi** [comment]
Hello @swiftdiaries 

Thanks for the response.Below are my inputs

1. with v1.1 yaml file, we dont have to Disabling istio installation as the yaml file doesnt have istio-crds and istio-install unlike with older versions of <= v1.0.
2. With respect to Istio configuration for trustworthy JWTs, we are using Rancher UI. Updated below parameters in the api configuration

kube-api:
      always_pull_images: false
      extra_args:
        service-account-issuer: kubernetes.default.svc
        service-account-signing-key-file: /etc/kubernetes/ssl/kube-service-account-token-key.pem
      pod_security_policy: true
      service_node_port_range: 30000-32767

3. With respect to Default password in static file configuration for Dex, unlike older versions of kfdev <=v1.0.2, we dont set these parameters v1.1.0.  These options are moved to dex-config.yaml and we make those changes over there.

Due to the certificate manager bug, as per @krishnadurai suggestion, we updated from default version 0.11 to >v0.15 to resolve the bug and then the other components below which were in Updating state converted to avaialbe state.

NOw, other than these two workloads cache-server and cache-deployer-deployment, everthing is back available. Need help to fix this

Namespace: Istio-system
Istio-ingressgateway
Istio-policy
Istio-pilot
Istio-telemetry
Namespace: kubeflow
Metadata-writer
ml-pipeline* all components

**Comment by swiftdiaries** [comment]
Related issue: https://github.com/kubeflow/kfctl/issues/406

**Comment by DavidSpek** [comment]
This seems to be related to https://github.com/kubeflow/pipelines/issues/4505. A fix is being worked on.

**Comment by govindsinghnegi** [comment]
I am too facing the same issue when deploying on Minikube cluster.
my deployment summary:
System: Mac (16GB)
Minikube: v1.15.0
Kubectl: v1.16.9 (client & server) 
kfctl: version 1.1.0
Documentation followed: https://www.kubeflow.org/docs/started/workstation/minikube-linux/

Minikube started with (as mentioned in the docs)
`minikube start --cpus 6 --memory 10240 --disk-size=120g ... `

The deployment was successful . However, even after waiting for more than an hour, some of the pods were in the Crash loop state:

```
argo-ui-669bcd8bfc-t9bmf                                 1/1     Running            0          64m
cache-deployer-deployment-b75f5c5f6-xh57m                0/2     CrashLoopBackOff   6          6m31s
cache-server-85bccd99bd-64sq4                            0/2     Init:0/1           0          5m59s
centraldashboard-68965b5d89-c42db                        1/1     Running            0          64m
```
Inspecting with  `kubectl get events -w`  command: 

```
0s          Normal    Pulling                 pod/cache-deployer-deployment-b75f5c5f6-xh57m                 Pulling image "gcr.io/ml-pipeline/cache-deployer:1.0.0"
0s          Normal    Pulled                  pod/cache-deployer-deployment-b75f5c5f6-xh57m                 Successfully pulled image "gcr.io/ml-pipeline/cache-deployer:1.0.0"
0s          Normal    SuccessfulCreate        replicaset/cache-server-85bccd99bd                            Created pod: cache-server-85bccd99bd-64sq4
0s          Normal    Scheduled               pod/cache-server-85bccd99bd-64sq4                             Successfully assigned kubeflow/cache-server-85bccd99bd-64sq4 to minikube
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   Unhealthy               pod/ml-pipeline-scheduledworkflow-d596b8bd-6mm9g              Readiness probe failed: HTTP probe failed with statuscode: 503
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
0s          Warning   BackOff                 pod/ml-pipeline-persistenceagent-6f99b56974-qfrrz             Back-off restarting failed container
0s          Warning   Unhealthy               pod/ml-pipeline-ui-8695cc6b46-5nzbs                           Readiness probe failed: HTTP probe failed with statuscode: 503
0s          Warning   Unhealthy               pod/mysql-76597cf5b5-q5cq5                                    Readiness probe failed: HTTP probe failed with statuscode: 503
0s          Warning   FailedMount             pod/cache-server-85bccd99bd-64sq4                             Unable to attach or mount volumes: unmounted volumes=[webhook-tls-certs], unattached volumes=[kubeflow-pipelines-cache-token-l6p2g webhook-tls-certs istio-envoy sds-uds-path istio-token]: timed out waiting for the condition
```

Previously I have tried with latest version of Kubernetes (v1.19) but was getting the same error. Then as per one of the [suggestion](https://github.com/kubeflow/pipelines/issues/4505)  I downgraded the Kubernetes server to v1.16.9 but still no success. I am still getting the **_MountVolume Setup failed error_**. 

Any suggestion here ?

**Comment by DavidSpek** [comment]
I'm also still experiencing this issue with Kubeflow 1.2 on k8s 1.19, as described https://github.com/kubeflow/pipelines/issues/4505.

**Comment by DavidSpek** [comment]
I think the issue is caused by the fact that `signerName` is a required field that is not set, and `kubernetes.io/legacy-unknown` has been removed from Kubernetes 1.19. It will need to replaced by `kubernetes.io/kube-apiserver-client`, `kubernetes.io/kube-apiserver-client-kubelet` or `kubernetes.io/kubelet-serving`. 
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers
https://github.com/kubeflow/pipelines/issues/4505#issuecomment-731447127

**Comment by DavidSpek** [comment]
The actual issue seem to be if `--cluster-signing-cert-file` and `--cluster-signing-key-file` are not set for kube-controller-manager. After setting these the cache-deployer worked as expected.

**Comment by omlomloml** [comment]
> The actual issue seem to be if `--cluster-signing-cert-file` and `--cluster-signing-key-file` are not set for kube-controller-manager. After setting these the cache-deployer worked as expected. This should be stated in the docs where it is also stated that istio needs support for JWT.

David,
how to set --cluster-signing-cert-file and --cluster-signing-key-file?

Thanks

**Comment by DavidSpek** [comment]
@omlomloml, the specifics will greatly depend on your cluster, but you need to pass the arguments to the kube-controller-manager. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

What type of cluster are you using?

**Comment by omlomloml** [comment]
> @omlomloml, the specifics will greatly depend on your cluster, but you need to pass the arguments to the kube-controller-manager. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
> 
> What type of cluster are you using?

@DavidSpek I deployed cluster using kubespray

**Comment by DavidSpek** [comment]
@omlomloml, I have no experience with kubespray but this issue seems to link to the solution. Do note that what you are changing is part of the cluster certificate management so it might break things in your cluster.

**Comment by ShilpaGopal** [comment]
I had set up Kubeflow in Onprem cluster without AUTH, where everything was working fine. Now I added OIDC and redeployed kubeflow, Cache server is not coming up for the same reason. Cache deployer fails with 
```
$ k logs -f pod/cache-deployer-deployment-6f7b78cb7c-6q4cs -n kubeflow main
Start deploying cache service to existing cluster:
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflow
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ kubectl get mutatingwebhookconfigurations cache-webhook-kubeflow --namespace kubeflow --ignore-not-found
The connection to the server 10.96.0.1:443 was refused - did you specify the right host or port?
```
 I don't see any  mutatingwebhookconfigurations by name cache-webhook-kubeflow in the cluster.

**Comment by DavidSpek** [comment]
@ShilpaGopal The cache deployer currently isn't using a webhook and since do don't have a cluster cluster signer setup you are facing this issue. A solution would be to use cert-manager for the cache deployer, see https://github.com/kubeflow/pipelines/issues/4695.

**Comment by ShilpaGopal** [comment]
@DavidSpek Thanks for your input, but I am uncertain that I understand your point. I had built custom Kubeflow manifests from 1.1.0 branch since I had to deploy it in an air-gapped cluster which needed some modifications. On my first installation, I installed without Dex. Now I am trying to install the same build with Dex which is resulting in the issue - **MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found** for cache server. 

Since I am using 1.1.0 build do you think cluster signer setup is the cause? I much appreciate your input. 

```
Environment:
kfctl versionkfctl v1.1.0-0-g9a3621e
Kubernetes platform: On-prem cluster 
Kubernetes version: v1.16.0
OS: CentOS 7.6
```

**Comment by DavidSpek** [comment]
@ShilpaGopal I'm not sure what the difference is between single-user and multi-user in regards to the cache deployer, but to me it does sound like the issue you are having is due to the cluster signer. I have faced this issue with both kubeflow 1.1 and kubeflow 1.2 with an on-prem deployment. 

You could try setting `--cluster-signing-cert-file` and `--cluster-signing-key-file` for the kube-controller-manager, then remove the cache-deployer and cache-server deployments, then run `kfctl apply -V -f <your-kdef>`. Do note that any changes you have made to your configuration that are not in the kustomize folder will be removed when doing this. Also, messing with the cluster signing cert and key file might break other things in the cluster so try at your own risk.

**Comment by ShilpaGopal** [comment]
@DavidSpek I see your point. Those two extra arguments are set during the first installation itself and its intact. Moreover, I didn't face this issue during the first installation, I am wondering the deletion of the first installation left any stale effect on the cluster signer!

**Comment by DavidSpek** [comment]
@ShilpaGopal Can you confirm that you have a cluster signer setup for the cluster.SSH into on of the master nodes and execute `ps aux | grep kube-controller-manager | grep "cluster-signing"`. If it comes up empty, you don't have a cluster issuer setup. If that is not the case, we'll need to further debug what is happening.

**Comment by ShilpaGopal** [comment]
@DavidSpek It is setup. Here is the output. 

```
$ ps aux | grep kube-controller-manager | grep cluster-signing
root     16033  3.1  0.8 294684 142296 ?       Ssl  00:16  35:18 kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=172.30.0.0/16 --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size=24 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --use-service-account-credentials=true
```

**Comment by DavidSpek** [comment]
@ShilpaGopal, maybe this comment is useful for your situation. https://github.com/kubeflow/pipelines/issues/4687#issuecomment-736834537

**Comment by ShilpaGopal** [comment]
@DavidSpek Thanks for your input. I do remove ValidatingWebhookConfiguration and MutationWebhookConfiguration after the Kubeflow uninstallations. (I have noticed that Katib's  ValidatingWebhookConfiguration and MutationWebhookConfiguration was never removed as part of uninstallation, So I have a cleanup script which does
$ kubectl delete  ValidatingWebhookConfiguration --all
$ kubectl delete  MutationWebhookConfiguration --all)

On the other note, I was able to fix the issue, the root cause was time drift across the nodes in the on-prem cluster. After fixing the time drift I was able to bring up cache server and cache deployer.

**Comment by dontmint** [comment]
> @ShilpaGopal I'm not sure what the difference is between single-user and multi-user in regards to the cache deployer, but to me it does sound like the issue you are having is due to the cluster signer. I have faced this issue with both kubeflow 1.1 and kubeflow 1.2 with an on-prem deployment.
> 
> You could try setting `--cluster-signing-cert-file` and `--cluster-signing-key-file` for the kube-controller-manager, then remove the cache-deployer and cache-server deployments, then run `kfctl apply -V -f <your-kdef>`. Do note that any changes you have made to your configuration that are not in the kustomize folder will be removed when doing this. Also, messing with the cluster signing cert and key file might break other things in the cluster so try at your own risk.

This works for me, kubeflow 1.2.0, rancher 1.9.4. After configed `kube-controller-manager` like this comment [https://github.com/rancher/rancher/issues/14674#issuecomment-535234849](url), I deleted kfdef and recreated it. 
Thanks a lot  @ShilpaGopal

**Comment by matty1979** [comment]
Same issue using minikube v1.16.0
kubectl v1.20.0 client / server.

**Comment by qinjie545** [comment]
Same issue
Same Env

> Same issue using minikube v1.16.0
> kubectl v1.20.0 client / server.

Same issue Same ENV

**Comment by DavidSpek** [comment]
It seems like the original author and others have been able to fix their issues. As this issue can be caused by many factors of specific environments I feel it is best to not have a single large issue where new situations keep getting piled on. @matty1979 @qinjie545, please feel free to open a new issue with more debugging information so an effort can be made to solve this problem. For now I am closing this issue. 
/close

**Comment by mnmami** [comment]
I repost here the link that @dontmint posted, which got somehow broken: https://github.com/rancher/rancher/issues/14674#issuecomment-535234849. It's worth pointing out, as it just saved me after two days of wandering.

**Comment by ReggieCarey** [comment]
Kubeflow 1.5 deployed via manifests onto a conformant Kubernetes 1.2 deployed via juju onto an openstack cloud deployed ontop of baremetal managed by MAAS.

cache-deployer-deployment fails to construct a certificate for cache-server.kubeflow csr leading to subsequent failures.

kubectl command to approve a certificate (kubectl certificate approve cache-server.kubeflow) completes and the status of the csr is marked approved, but no certificate is ever affixed to the status.certificate of the csr.

```bash
$ kubectl get csr cache-server.kubeflow
NAME                    AGE     SIGNERNAME                      REQUESTOR                                                             CONDITION
cache-server.kubeflow   4m24s   kubernetes.io/kubelet-serving   system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa   Approved
```
and the status block of that approved csr:

```bash
$ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status}'|jq
{
  "conditions": [
    {
      "lastTransitionTime": "2022-03-25T18:58:47Z",
      "lastUpdateTime": "2022-03-25T18:58:48Z",
      "message": "This CSR was approved by kubectl certificate approve.",
      "reason": "KubectlApprove",
      "status": "True",
      "type": "Approved"
    }
  ]
}
```

I think this leads to an inability to construct the secret webhook-server-tls.

Analysis indicates that the main container as defined by the deployment uses a serviceAccount of ```kubeflow-pipelines-cache-deployer-sa``` which refers to a secret ```kubeflow-pipelines-cache-deployer-sa-token-gm6cz```

That secret looks fine:  contains a ca.crt, token, and namespace ( set to kubeflow ).

This causes the cache-server deployment to fail due to a missing volume mount - webhook-server-tls

See the log output of the cache-deployer-deployment-**-** pod:
```
Start deploying cache service to existing cluster:
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflow
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ mkdir -p /root/bin
+ export 'PATH=/root/bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ kubectl version --output json
+ jq --raw-output '(.serverVersion.major + "." + .serverVersion.minor)'
+ tr -d '"+'
+ server_version_major_minor=1.21
+ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.21.txt
+ stable_build_version=v1.21.11
+ kubectl_url=https://storage.googleapis.com/kubernetes-release/release/v1.21.11/bin/linux/amd64/kubectl
+ curl -L -o /root/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.21.11/bin/linux/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.5M  100 44.5M    0     0  90.4M      0 --:--:-- --:--:-- --:--:-- 90.4M
+ chmod +x /root/bin/kubectl
+ kubectl get mutatingwebhookconfigurations cache-webhook-kubeflow --namespace kubeflow --ignore-not-found
+ kubectl get secrets webhook-server-tls --namespace kubeflow --ignore-not-found
+ webhook_config_exists=false
+ grep cache-webhook-kubeflow -w
+ webhook_secret_exists=false
+ grep webhook-server-tls -w
+ '[' false '==' true ]
+ '[' false '==' true ]
+ '[' false '==' true ]
+ export 'CA_FILE=ca_cert'
+ rm -f ca_cert
+ touch ca_cert
+ ./webhook-create-signed-cert.sh --namespace kubeflow --cert_output_path ca_cert --secret webhook-server-tls
+ [[ 6 -gt 0 ]]
+ case ${1} in
+ namespace=kubeflow
+ shift
+ shift
+ [[ 4 -gt 0 ]]
+ case ${1} in
+ cert_output_path=ca_cert
+ shift
+ shift
+ [[ 2 -gt 0 ]]
+ case ${1} in
+ secret=webhook-server-tls
+ shift
+ shift
+ [[ 0 -gt 0 ]]
+ '[' -z ']'
+ service=cache-server
+ '[' -z webhook-server-tls ']'
+ '[' -z kubeflow ']'
+ '[' -z ca_cert ']'
++ command -v openssl
+ '[' '!' -x /usr/bin/openssl ']'
+ csrName=cache-server.kubeflow
++ mktemp -d
+ tmpdir=/tmp/tmp.ejjJLb
+ echo 'creating certs in tmpdir /tmp/tmp.ejjJLb '
creating certs in tmpdir /tmp/tmp.ejjJLb 
+ cat
+ openssl genrsa -out /tmp/tmp.ejjJLb/server-key.pem 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
......+++++
.......................................................+++++
e is 65537 (0x010001)
+ openssl req -new -key /tmp/tmp.ejjJLb/server-key.pem -subj '/CN=system:node:cache-server.kubeflow.svc;/O=system:nodes' -out /tmp/tmp.ejjJLb/server.csr -config /tmp/tmp.ejjJLb/csr.conf
+ echo 'start running kubectl...'
+ kubectl delete csr cache-server.kubeflow
start running kubectl...
certificatesigningrequest.certificates.k8s.io "cache-server.kubeflow" deleted
+ cat
+ kubectl create -f -
++ cat /tmp/tmp.ejjJLb/server.csr
++ base64
++ tr -d '\n'
certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow created
+ true
+ kubectl get csr cache-server.kubeflow
NAME                    AGE   SIGNERNAME                      REQUESTOR                                                             CONDITION
cache-server.kubeflow   0s    kubernetes.io/kubelet-serving   system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa   Pending
+ '[' 0 -eq 0 ']'
+ break
+ kubectl certificate approve cache-server.kubeflow
certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow approved
++ seq 10
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ [[ '' == '' ]]
+ echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.
```

**Comment by HaoWangDL** [comment]
> I'm also still experiencing this issue with Kubeflow 1.2 on k8s 1.19, as described [kubeflow/pipelines#4505](https://github.com/kubeflow/pipelines/issues/4505).
> 
> Edit: I have spotted 2 Certificate Signing Requests, both identical with one in namespace `istio-system` and the other in `kubeflow`. I remember there was an issue that the CSR was not being approved, which it now is but I don't think it is getting issued.
> 
> `kubectl describe csr cache-server.kubeflow -n istio-system`
> 
> ```
> Name:               cache-server.kubeflow
> Labels:             <none>
> Annotations:        <none>
> CreationTimestamp:  Fri, 20 Nov 2020 22:54:30 +0100
> Requesting User:    system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa
> Signer:             kubernetes.io/legacy-unknown
> Status:             Approved
> Subject:
>   Common Name:    cache-server.kubeflow.svc
>   Serial Number:  
> Subject Alternative Names:
>          DNS Names:  cache-server
>                      cache-server.kubeflow
>                      cache-server.kubeflow.svc
> Events:  <none>
> ```
> 
> Cache-deployer-deployment logs:
> 
> ```
> 
> + shift
> + [[ 2 -gt 0 ]]
> + case ${1} in
> + secret=webhook-server-tls
> + shift
> + shift
> + [[ 0 -gt 0 ]]
> + '[' -z ']'
> + service=cache-server
> + '[' -z webhook-server-tls ']'
> + '[' -z kubeflow ']'
> + '[' -z ca_cert ']'
> ++ command -v openssl
> + '[' '!' -x /usr/bin/openssl ']'
> + csrName=cache-server.kubeflow
> ++ mktemp -d
> + tmpdir=/tmp/tmp.meigEj
> + echo 'creating certs in tmpdir /tmp/tmp.meigEj '
> creating certs in tmpdir /tmp/tmp.meigEj 
> + cat
> + openssl genrsa -out /tmp/tmp.meigEj/server-key.pem 2048
> Generating RSA private key, 2048 bit long modulus (2 primes)
> ............................................+++++
> ..........................................................................+++++
> e is 65537 (0x010001)
> + openssl req -new -key /tmp/tmp.meigEj/server-key.pem -subj /CN=cache-server.kubeflow.svc -out /tmp/tmp.meigEj/server.csr -config /tmp/tmp.meigEj/csr.conf
> + echo 'start running kubectl...'
> + kubectl delete csr cache-server.kubeflow
> start running kubectl...
> certificatesigningrequest.certificates.k8s.io "cache-server.kubeflow" deleted
> + cat
> + kubectl create -f -
> ++ cat /tmp/tmp.meigEj/server.csr
> ++ base64
> ++ tr -d '\n'
> Warning: certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
> certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow created
> + true
> + kubectl get csr cache-server.kubeflow
> NAME                    AGE   SIGNERNAME                     REQUESTOR                                                             CONDITION
> cache-server.kubeflow   0s    kubernetes.io/legacy-unknown   system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa   Pending
> + '[' 0 -eq 0 ']'
> + break
> + kubectl certificate approve cache-server.kubeflow
> certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow approved
> ++ seq 10
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + for x in $(seq 10)
> ++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
> + serverCert=
> + [[ '' != '' ]]
> + sleep 1
> + [[ '' == '' ]]
> + echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
> ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.
> + exit 1
> ```

Have you solved this problem? How to solve it

thanks
