### ISSUE TITLE
cache-deployer-deployment error & seldon-controller-manager crashLoopBackoff

### ISSUE THREAD

**Issue by hlngaiSam** [kubeflow/kubeflow#5253]
Hi all,

I have installed Kubeflow(Multi-user,auth-enabled kubeflow with kfctl _istio_dex) in my on-perm multi-master k8s cluster.

But some components: Cache-deployer-deployment, cache-server and seldon-controller-manager can't start normally. 

<img width="1062" alt="Screen Shot 2020-08-28 at 6 04 31 PM" src="https://user-images.githubusercontent.com/69775981/91555480-aeaf9c80-e963-11ea-96bc-b4edf490d268.png">

I have checked the log and event, but there's no any information there.

How can solve this? Thank you.

The following are my environment info:
Kubeflow: v 1.0.2
kubernetes platform: setup by Kubeadm, v 1.18.3
OS: Ubuntu 18.04 (master nodes and worker nodes)

**Comment by condaatje** [comment]
There may be a better solution from the team, but installing on a v1.17 cluster fixed this issue for me

**Comment by DavidSpek** [comment]
Related issues and solutions:
https://github.com/kubeflow/pipelines/issues/4505
https://github.com/kubeflow/website/issues/2206#issuecomment-698234904
