### ISSUE TITLE
Tensorboard controller pod doesn't have all the permissions needed to manage Tensorboard servers

### ISSUE THREAD

**Issue by kandrio98** [kubeflow/kubeflow#5261]
/kind feature

The Tensorboard controller should be authorized to manage the deployments, services and VirtualServices that are needed so that the Tensorboard servers created would function as expected.

This is part of my GSoC-2020 proposal so I will create a PR to add the necessary roles.

cc @kimwnasptd @elikatsis

**Comment by kimwnasptd** [comment]
@kandrio98 you are referring to the RBAC permissions kubebuilder uses for running the controller locally or deploying it via the makefile right?

**Comment by kandrio98** [comment]
@kimwnasptd Yes, exactly. I am referring to the RBAC permissions that are needed in order to deploy the controller via the Makefile. The controller doesn't have the right permissions to create and manage deployments, services and VirtualServices. Also, it needs RBAC permissions to watch;list;get pods and PVCs.
