### ISSUE TITLE
notebook controller metrics exposed does not show the correct values if there is any restart in notebook controller pod

### ISSUE THREAD

**Issue by chetanoruganti** [kubeflow/kubeflow#5274]
/kind bug

metrics exposed as part of the notebook controller .
 1. runningNotebooks         *prometheus.GaugeVec    Current running notebooks in the cluster
 2. NotebookCreation         *prometheus.CounterVec   notebook_create_total
 3. NotebookFailCreation     *prometheus.CounterVec   notebook_create_failed_total
 4. NotebookCullingCount     *prometheus.CounterVec  notebook_culling_total
 5. NotebookCullingTimestamp   last_notebook_culling_timestamp_seconds

observations after testing with kubeflow deployment  v1.0.2(looks like there is no changes for notebook metrics in latest release )
1. runningNotebooks : according to the current implementation the count of number of notebooks running is tracked by checking the number of statefulset with label notebook-name .
     *  when culling is enabled just by checking the statefulset with label notebook-name may not help . we need to check the pod status also to confirm notebook server is running 
2.   NotebookCreation , NotebookFailCreation , NotebookCullingCount,NotebookCullingTimestamp :  According to the current implementation metrics are tracked  according to the scenario performed in  controller Reconcile  function .
      * when there is restart in notebook controller due to upgrade or any issue the current metric values will  reset  and metrics are collected freshly according to the action performed on the notebooks .  As notebook servers does not get deleted if there restart in controller pod earlier metrics should also be considered after the restart . 

**What did you expect to happen:**
Anytime user scrape the metrics user need to get exact values of metrics . 

**Environment:**
kubeflow installed with 1.0.2 manifests

**Comment by jbottum** [comment]
@kimwnasptd is there anyone looking at this ?
