### ISSUE TITLE
pods not scheduling to GPU nodes, taint tolerations present

### ISSUE THREAD

**Issue by jvendegna** [kubeflow/kubeflow#5275]
/kind bug

**What steps did you take and what happened:**
Hello all, I am taking a break for a moment because of frustration with applying a taint-toleration using kfp on my ai-platform pipelines cluster.
I have a model training job which requires GPUs, not uncommon.
Default behavior for extras like GPUs in GKE is to add a node taint so pods must explicitly state a toleration to be scheduled to that node. I get that, I like that, I appreciate it.
So, I’ve read the docs [here](https://kubeflow-pipelines.readthedocs.io/en/latest/_modules/kfp/gcp.html#add_gpu_toleration)
I applied that to my code like so:
```
toleration = client.models.v1_toleration.V1Toleration(effect='NoSchedule', key='nvidia.com/gpu', operator='Equal', value='present')
train.apply(gcp.add_gpu_toleration(toleration))
train.apply(gcp.add_gpu_toleration())
```
Generate pipeline file, upload it.
Triggers a scale up of the correct node pool with the CPU/RAM/GPU requirements I’ve specified.
`kubectl describe node <name>` shows only the following taint: nvidia.com/gpu=present:NoSchedule
`kubectl describe pod <name>` shows the taints I’ve tolerated via kfp.gcp.add_gpu_toleration():
```
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 nvidia.com/gpu=present:NoSchedule
                 nvidia.com/gpu=true:NoSchedule
                 nvidia.com/gpu:NoSchedule
```
But here is the problem:
from `kubectl describe pod <name>` events field:
```
Events:
  Type     Reason            Age                 From                Message
  ----     ------            ----                ----                -------
  Normal   TriggeredScaleUp  15m                 cluster-autoscaler  pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/<REDACTED> 1->2 (max: 10)}]
  Warning  FailedScheduling  13m (x4 over 16m)   default-scheduler   0/4 nodes are available: 3 Insufficient cpu, 3 Insufficient memory, 3 node(s) didn't match node selector, 4 Insufficient nvidia.com/gpu.
  Warning  FailedScheduling  90s (x12 over 13m)  default-scheduler   0/5 nodes are available: 3 Insufficient cpu, 3 Insufficient memory, 3 node(s) didn't match node selector, 5 Insufficient nvidia.com/gpu.
```
There is some useful information here. For one, I know my label selector is working. As only 3/5 nodes don’t match that.
So that is a win… Now if I could just start the pod on the node with the GPU, my whole day might turn out to be as nice as it is outside here in Denver today!
Any help is greatly appreciated, any cheat codes will definitely be rewarded.

**What did you expect to happen:**
Pod scheduled to node with 2 GPUs as defined in the workflow manifest

**Anything else you would like to add:**
new pod does trigger scale up event
nvidia-gpu-device-plugin is present on scaled up nodes with attached gpus
node pool is configured correctly but seeing is believing so here's a clip:
![Screen Shot 2020-09-03 at 4 08 51 PM](https://user-images.githubusercontent.com/58440894/92178548-089ae100-ee00-11ea-9be6-5812ca9056c7.png)

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.0
- kfctl version: (use `kfctl version`): never used it
- Kubernetes platform: (e.g. `minikube`) GKE via AI-Platform
- Kubernetes version: (use `kubectl version`): 
`
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): macos catalina

**Comment by Bobgy** [comment]
/assign

I don't have experience trying this. let me find Who knows

**Comment by fabito** [comment]
@jvendegna ,

Have you tried adding a `nodeSelector` ?
Something like:

```yaml
  nodeSelector:
    cloud.google.com/gke-nodepool: my-gpu-enabled-nodepool-name  
```

**Comment by jvendegna** [comment]
> @jvendegna ,
> 
> Have you tried adding a `nodeSelector` ?
> Something like:
> 
> ```yaml
>   nodeSelector:
>     cloud.google.com/gke-nodepool: my-gpu-enabled-nodepool-name  
> ```

I have, but I appreciate the suggestion, it still results in: `Insufficient nvidia.com/gpu` after scale-up event.
I'm going to try to follow the guide here to see if it fixes anything: https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/gpu/gpu.ipynb

**Comment by acesir** [comment]
@jvendegna when you do a describe on the gpu-node does it correctly show the availability of the GPUs that can be allocated on the machine like so:

```
Capacity:
 cpu:                            6
 memory:                         57713784Ki
 nvidia.com/gpu:                 2
Allocatable:
 cpu:                            5916m
 memory:                         51702904Ki
 nvidia.com/gpu:                 2
```

**Comment by jvendegna** [comment]
For future reference, this did the trick:
`kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml`

The insufficient GPU message was due to no driver being installed on the node, as detailed in the link in my last comment.

**Comment by jvendegna** [comment]
@acesir That's a great question worthy of exploration. I thought so but wasn't sure. I uninstalled the nvidia-driver-installer from my cluster and triggered another run. After scale up and to my surprise the pod was scheduled to the node anyway. I don't appreciate smoke and mirrors, so I dug deeper and recreated the nodepool. Turns out, no. You're inclinations were correct.
```
Capacity:
 attachable-volumes-gce-pd:  127
 cpu:                        16
 ephemeral-storage:          98868448Ki
 hugepages-2Mi:              0
 memory:                     107260540Ki
 pods:                       110
Allocatable:
 attachable-volumes-gce-pd:  127
 cpu:                        15890m
 ephemeral-storage:          47093746742
 hugepages-2Mi:              0
 memory:                     98936444Ki
 pods:                       110
```

**Comment by acesir** [comment]
> @acesir That's a great question worthy of exploration. I thought so but wasn't sure. I uninstalled the nvidia-driver-installer from my cluster and triggered another run. After scale up and to my surprise the pod was scheduled to the node anyway. I don't appreciate smoke and mirrors, so I dug deeper and recreated the nodepool. Turns out, no. You're inclinations were correct.
> 
> ```
> Capacity:
>  attachable-volumes-gce-pd:  127
>  cpu:                        16
>  ephemeral-storage:          98868448Ki
>  hugepages-2Mi:              0
>  memory:                     107260540Ki
>  pods:                       110
> Allocatable:
>  attachable-volumes-gce-pd:  127
>  cpu:                        15890m
>  ephemeral-storage:          47093746742
>  hugepages-2Mi:              0
>  memory:                     98936444Ki
>  pods:                       110
> ```

@jvendegna Yes the nvidia daemonSet is required in order to expose the GPU resource for scheduling otherwise kubernetes doesn't know about it and will only allow CPU/Memory requests for scheduling. Tainting and labeling the does not good as the GPU resources are not advertised for scheduling.

You can find more information here about the scenario: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by DmitryCape** [comment]
> `kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml`
> 
> The insufficient GPU message was due to no driver being installed on the node, as detailed in the link in my last comment.

Thanks a lot! 🚀
It solves my issue!
