### ISSUE TITLE
Can not enable or disable Kubeflow with Microk8s

### ISSUE THREAD

**Issue by gaborvecsei** [kubeflow/kubeflow#5276]
/kind bug

**What steps did you take and what happened:**
I followed the Microk8s setup tutorial which was provided on the page: https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/#install-kubeflow-using-microk8s and I get to a point where I can not enable or disable Kubeflow (as it says that it is already enabled or disabled while `sudo microk8s.status` shows that it is disabled).

E.g.:

```
➜ sudo microk8s.status
microk8s is running
addons:
dashboard: enabled
dns: enabled
gpu: enabled
ingress: enabled
metallb: enabled
metrics-server: enabled
storage: enabled
ambassador: disabled
cilium: disabled
fluentd: disabled
helm: disabled
helm3: disabled
host-access: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
multus: disabled
prometheus: disabled
rbac: disabled
registry: disabled

➜ sudo microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for DNS and storage plugins to finish setting up
Kubeflow has already been enabled.
Failed to enable kubeflow

➜ sudo microk8s.disable kubeflow
Addon kubeflow is already disabled.
```

Steps:
1. `sudo snap install microk8s --classic`
2. `sudo microk8s.status --wait-ready` (In the tutorial it is without `sudo` but for me it only worked with `sudo`)
3. `sudo microk8s.enable dns dashboard storage`
4. `sudo microk8s.enable gpu`
5. `sudo microk8s.enable kubeflow` --> after this step I had to wait a lot...
6. `sudo microk8s.disable kubeflow` --> I had to wait even more then with `enable`

**What did you expect to happen:**
`enable` and `disable` works out of the box

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: --
- kfctl version: (use `kfctl version`): --
- Kubernetes platform: microk8s
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-1+64f53401f200a7", GitCommit:"64f53401f200a7a5977955a74ad3f997302774ca", GitTreeState:"clean", BuildDate:"2020-07-15T19:58:09Z", GoVersion:"go1.14.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-1+64f53401f200a7", GitCommit:"64f53401f200a7a5977955a74ad3f997302774ca", GitTreeState:"clean", BuildDate:"2020-07-15T19:59:02Z", GoVersion:"go1.14.5", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): `NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by gaborvecsei** [comment]
Hopefully it is solved by refreshing the microk8s snap package: `sudo snap refresh microk8s --channel=1.18/stable`

Kubeflow tutorial should follow the Microk8s install guide (which gives an idea how can I run it without `sudo`): https://microk8s.io/docs

**Comment by gaborvecsei** [comment]
Solved:

```
sudo snap remove microk8s --purge
sudo snap install microk8s --classic
microk8s.enable kubeflow
```

from https://github.com/ubuntu/microk8s/issues/1253

**Comment by gayathry2612** [comment]
> Interacting with snapd is not supported on darwin. This command is left available for documentation purposes only. 
I'm on Catalina, this is not solved. 

> Solved:
> 
> ```
> sudo snap remove microk8s --purge
> sudo snap install microk8s --classic
> microk8s.enable kubeflow
> ```
> 
> from [ubuntu/microk8s#1253](https://github.com/ubuntu/microk8s/issues/1253)
