### ISSUE TITLE
Pipelines upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by luigicr1965** [kubeflow/kubeflow#5277]
/kind bug

I have deployed Kubeflow in Azure using kfctl_k8s_istio.v1.1.0.yaml from the master after having modified the repos section 

repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
    #uri: https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz
  version: master
  #version: v1.1-branch

I used port forward as follow

kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80

Everything looks like working from the UI but pipelines where I get the following error once clicking on the left bar Pipelines menu: 

upstream connect error or disconnect/reset before headers. reset reason: connection failure

I do expect that the pipelines UI is shown

**Environment:**

Kubeflow version as above stated is kfctl_k8s_istio.v1.1.0.yaml

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: Azure AKS
- Kubernetes version: v1.16.13

![Capture](https://user-images.githubusercontent.com/70765393/92254932-2a0fd180-eec1-11ea-9f59-efa598dfbaf4.PNG)

**Comment by danishsamad** [comment]
Hi,
Duplicate issue discussed [here](https://github.com/kubeflow/kubeflow/issues/5271)

**Comment by thesuperzapper** [comment]
Hi all, the solution to this is simple, just make sure your `Namespace/kubeflow` has the right labels.

**PLEASE NOTE:** you will need to recreate all resources in `Namespace/kubeflow`, after making this change.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: enabled
```

**Comment by andre-lx** [comment]
If you came across this issue, using azure, and the kubeflow ns doesn't have the istio pods injected to the pods, please check my comment here:

https://github.com/kubeflow/pipelines/issues/5244#issuecomment-844144159

**Comment by dhanisahu** [comment]
Hi @andre-lx @thesuperzapper 

iam also getting the same issue on the Kubeflow notebook dashboard do you have any suggestion for this. I have changed the tls from ISTIO_MUTUAL to DISABLE in 

**kubectl edit destinationrule -n kubeflow ml-pipeline
kubectl edit destinationrule -n kubeflow ml-pipeline-ui** 

but still getting the same issue as **upstream connect error or disconnect/reset before headers. reset reason: connection failure**

iam running kubeflow 1.5 with GKE 1.21

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/88646670/179195195-184530bf-d142-4ebb-b65a-7b2b28d647e5.png">

**Comment by Naveen03** [comment]
Hallo @danishsamad Did you get any workaround fro this problem? I am also facing the same issue while accessing the notebook server from dashboard.

**Comment by LehmBook** [comment]
hi @Naveen03 did you solve the problem, i checked the pipline ui describe, it was running fine before i click pipline button in the UI. after i click it ,the ui containerd entered exit status and restarted.
