### ISSUE TITLE
Kubeflow upgrade from 1.0 to 1.1

### ISSUE THREAD

**Issue by estrellafelipe** [kubeflow/kubeflow#5278]
/kind question

Hello,

is there a guide to upgrade kubeflow from version 1.0 to 1.1 in GKE?

Regards,

**Comment by Luke035** [comment]
It'd be very helpful to have a guide for upgrading kubeflow without having to re-install it!

**Comment by jbottum** [comment]
@jlewi is there someone on the GCP that would like to respond to this issue?

**Comment by jlewi** [comment]
Duplicate of kubeflow/gcp-blueprints#103
