### ISSUE TITLE
Kubeflow with DEX v1.1 doesnt work with Load balancer. Error shows: Sorry, /pipeline/ is not a valid page

### ISSUE THREAD

**Issue by arshashi** [kubeflow/kubeflow#5279]
/kind question

**Question:**
We have onpremise setup with kubeflow v.1.1 with DEX.  Kubeflow works well with NodePort. Whereas when I configure Loadbalancer in Istio ingress gateway, I get the kubeflow home page but when i click on Pipelines, notebook servers and Katib, I get below errors.   Kubeflow works well with NodePort.
Sorry, /pipeline/ is not a valid page
Sorry, /jupyter/ is not a valid page

In the Kubeflow Load balancer Ingress setup, centraldashboard Path is set to / with port 8082.   

I read somewhere that with Onpremise environment there is some different way we should configure to make the Load balancer to work unlike GCP/AWS setup.    Is it something additional configuration on Ingress or any other place to be performed to make the load balancer setup work?

**Comment by jbottum** [comment]
@krishnadurai have you seen this issue ?
