### ISSUE TITLE
Access KF Dashboard with port forwarding with Microk8s setup

### ISSUE THREAD

**Issue by gaborvecsei** [kubeflow/kubeflow#5281]
/kind feature

**Why you need this feature:**
This makes the access way easier for smaller setups, without the need of the DNS setup and then SOCKS proxy setup

**Describe the solution you'd like:**
I would like to access the dashboard via a selected port

**Comment by RFMVasconcelos** [comment]
Hi @gaborvecsei Thanks for the feedback! 

/cc @knkski

**Comment by DavidSpek** [comment]
Closing this issue as it isn't active or related to the code in this repository. For future issues specific to Microk8s, please open an issue in the https://github.com/canonical/bundle-kubeflow repo. 
/close
