### ISSUE TITLE
Setting up my existing custom authentication using OIDC

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kubeflow#5284]
Hi All,

We are currently implementing Kubeflow as a machine learning platform. We have set up k8s Cluster  and need to customize dex authentication to use existing running Dex as our needs and I got somewhat stuck, so I am hoping for some ideas/input from you.

Part of OIDC auth changes in kfctl yaml file---- 

  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: istio-system
      - name: userid-header
        value: kubeflow-userid
      - name: oidc_provider
        value: https://my-domain-name/id
      - name: oidc_redirect_uri
        value: /login/oidc
      - name: oidc_auth_url
        value: /id/auth
      - name: skip_auth_uri
        value: /id
      - name: client_id
        value: kubeflow-oidc-authservice
      repoRef:
        name: manifests
        path: istio/oidc-authservice
    name: oidc-authservice

successfully applied but auth service is not running and pod/authservice-0  logs –> actually this is down due to below error.

time="2020-09-02T14:30:57Z" level=info msg="Starting readiness probe at 8081"
time="2020-09-02T14:30:57Z" level=info msg="No  USERID_TOKEN_HEADER  specified, using 'kubeflow-userid-token' as default."
time="2020-09-02T14:30:57Z" level=info msg="No  SERVER_HOSTNAME  specified, using '' as default."
time="2020-09-02T14:30:57Z" level=info msg="No  SERVER_PORT  specified, using '8080' as default."
time="2020-09-02T14:30:57Z" level=info msg="No  SESSION_MAX_AGE  specified, using '86400' as default."
time="2020-09-02T14:30:57Z" level=info msg="Starting web server at :8080"
time="2020-09-02T14:30:57Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:07Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:17Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:27Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:37Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:47Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""
time="2020-09-02T14:31:57Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /.well-known/openid-configuration: unsupported protocol scheme \"\""

And as per my dex config it should be look at https://my-domain-name/id  but it's looking at different path i guess.  I don't know why that error coming. 

How do we changes kubeflow well-known config check path..??

**Comment by micemuni** [comment]
Any one had a chance to look at it..?

**Comment by micemuni** [comment]
Updated the correct IDP details and fixed.

**Comment by NiravSo** [comment]
> Updated the correct IDP details and fixed.

What exactly you have updated. Can you please mention here?
