### ISSUE TITLE
kubeflow v1.0.2 installation error on EKS

### ISSUE THREAD

**Issue by xzy0223** [kubeflow/kubeflow#5290]
/kind bug

**What steps did you take and what happened:**

I'm trying to deploy kubeflow on my aws eks cluster. I have set the kfctl_aws.yaml file with right aws region code and eks cluster name. 

but when I applied, I got the error as below

`WARN[0000] AWS Credentials seems not correct RequestError: send request failed
caused by: Post "https://sts.REGION.amazonaws.com/": dial tcp: lookup sts.REGION.amazonaws.com on 172.31.0.2:53: no such host  filename="utils/awsutil.go:38"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: Could not authenticate aws client: RequestError: send request failed
caused by: Post "https://sts.REGION.amazonaws.com/": dial tcp: lookup sts.REGION.amazonaws.com on 172.31.0.2:53: no such host, Please make sure you set up AWS credentials and regions
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                                        export CONFIG=./kfctl_gcp_iap.yaml
                                or a URL:
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                                kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: Could not authenticate aws client: RequestError: send request failed
caused by: Post "https://sts.REGION.amazonaws.com/": dial tcp: lookup sts.REGION.amazonaws.com on 172.31.0.2:53: no such host, Please make sure you set up AWS credentials and regions`

Any one also ran into this bug? how do you resolve this or work aroud

**Environment:**

- Kubeflow version: v1.0.2
- kfctl version: v1.0.2
- Kubernetes platform: AWS EKS
- Kubernetes version: 1.16
- OS (e.g. from `/etc/os-release`): amazon-linux

**Comment by jbottum** [comment]
@Jeffwan are you aware of this issue and do you have any comments ?

**Comment by Jeffwan** [comment]
From the logs, it doesn't seem user set REGION correctly. @xzy0223 Do you mind sharing your settings? Did you use IAM role or user or assumed role for this?
