### ISSUE TITLE
Deleting multiple nootbook servers at the same time results in difficulties

### ISSUE THREAD

**Issue by gilbeckers** [kubeflow/kubeflow#5291]
/kind bug

**What steps did you take and what happened:**
When I give the order in the kubeflow dashboard to delete multiple notebook servers at the same time, the deletion of these notebook servers is experiencing difficulties. 
When monitoring the statuses of these deleted notebook servers one can observe that the status changes from Terminated back to Waiting, resulting in some pods being initialized again. 

**What did you expect to happen:**
I expect that when deleting more than one notebook server, these are all deleted in the same kind of fashion when one would delete only one notebook server e.g. the status goes to Terminated and after a few moments all associated resources are deleted.

**Anything else you would like to add:**
/

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.2
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: (e.g. `minikube`): minikube
- Kubernetes version: (use `kubectl version`): client v1.19.0 , server v1.18.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by jbottum** [comment]
@gilbeckers thanks for alerting us to this.   Have you seen it on any other platform ?  Are you running MiniKube on your laptop ?   @kimwnasptd have you seen this?

**Comment by gilbeckers** [comment]
@jbottum Yes, I'm running minikube on my laptop. No, I have not seen it on any other platform.
