### ISSUE TITLE
admission webhook "sidecar-injector.istio.io" denied the request: template: inject:7:27: executing "inject" at <.Values.global.proxy_init.image>: invalid value; expected string

### ISSUE THREAD

**Issue by shrutich91** [kubeflow/kubeflow#5293]
While creating a new notebook server I get the following error.

FailedCreate create Pod test-0 in StatefulSet test failed error: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:7:27: executing "inject" at <.Values.global.proxy_init.image>: invalid value; expected string

Any suggestions on what may be wrong?

Environment:

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.1.0 tried with both with DEX and without

kfctl version: (use kfctl version): kfctl v1.1.0-0-g9a3621e

Kubernetes platform: (e.g. minikube)

Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

OS (e.g. from /etc/os-release): CentOS 7.8

**Comment by arshashi** [comment]
Same issue i have encountered. Existing notebook servers works fine whereas new notebook servers are not getting created and in the backend, it creates notebook servers under the respective namespace but it is not able to create pod under this namespace.  Any inputs/suggestions to solve the issue?
