### ISSUE TITLE
Dex config with LDAP connector leading to connection errors between ldap server and kubeflow services in 1.1.0

### ISSUE THREAD

**Issue by aychang95** [kubeflow/kubeflow#5294]
/kind bug

**What steps did you take and what happened:**

Steps:
1. Deployed kfctl_istio_dex.v1.1.0.yaml on an existing 1.15.11 k8s cluster
2. Confirmed that static accounts work with kubeflow with port-forwarding
3. Deployed stateful set admin services for ldap server with phpldapadmin
4. Can successfully login to default "cn=admin,dc=example,dc=com" account inside ldap-0 pod with `exec`
5. (BUG) Created and restarted dex with the `dex-config-final.yaml` configurations, but cannot login to the ldap UI and can no longer login to kubeflow with the static account I was able to login with before. (ldap UI error seems to show that we can't connect to the LDAP server)

![image](https://user-images.githubusercontent.com/10554495/92615569-3f9f4580-f28b-11ea-8ab6-5ad7d4d3886e.png)

**What did you expect to happen:**
I expected to be able to use the phpldapadmin service to login to the ldap UI and kubeflow.

**Anything else you would like to add:**
I did not have this issue with kfctl_istio_dex.v.1.0.2.yaml and when I upgraded from 1.0.2 to 1.1.0 (since I was using the ldap server that i deployed when 1.0.2 was deployed...though I did have to re-create the dex configurations).

This only occurs when deploying 1.1.0 from scratch. It seems like the ldap connector in the `dex-config-final.yaml` configs is leading to issues with communication/authentication between the ldap server and the kubeflow api and services (including phpldapadmin services).

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: k8s cluster deployed with kops
- Kubernetes version: 1.15.11
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by jbottum** [comment]
Hi @aychang95 did you get this resolved? Which platform are you deploying on GCP, AWS, On-prem ?

**Comment by aychang95** [comment]
Hi @jbottum, I use the Kubernetes Installlation instructions here: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/

This is on a kops deployed k8s cluster on AWS servers.

**Comment by aychang95** [comment]
@jbottum 

I've found a solution by addressing some configurations within the ldap service/statefulset manifest.

Since I am using self-signed certs to allow TLS encryption, I just needed to change the ldap service port to 636. It would also be best practice security-wise to change the port from 389 to 636 in the dex configmap.

Also the current ldap server manifest is currently broken and I had to adjust some slapd symbolic links in `lifecycle.postStart` to get it to actually run a while back. You get the below error logs running `kubectl logs -n kubeflow ldap-0 ldap` with the current manifest file. I could add a PR for some of the issues and troubleshooting points for the [k8s installation documentation](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) if you'd like since I am deploying kubeflow end-to-end in kops clusters.

<details>
  <summary>Error logs</summary>


*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Error: the config directory (/etc/ldap/slapd.d) is empty but not the database directory (/var/lib/ldap)
*** /container/run/startup/slapd failed with status 1

*** Killing all processes...


</details>
