### ISSUE TITLE
kubeflow installatiion failed -- version kubeflow 1.0.2 on GCP 

### ISSUE THREAD

**Issue by alforik** [kubeflow/kubeflow#5296]
/kind bug

**What steps did you take and what happened:**
I followed kubeflow 1.0 installation guide on gcp( Deploy using CLI. https://v1-0-branch.kubeflow.org/docs/gke/deploy/deploy-cli/ ) , today. 
I succeded before with this guide  but intallation is failed today.
I got the following message.
-------------------------error message ------------------------
ERRO[0033] Updating kfnm-01 error: &{Code:RESOURCE_ERROR Location:/deployments/kfnm-01/resources/kfnm-01 Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No valid versions with the prefix \"1.14\" found.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1beta1/projects/pj-mlops-274505/locations/asia-east1-a/clusters","httpMethod":"POST"}} ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:386"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kfnm-01 error(400): BAD REQUEST
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kfnm-01 error(400): BAD REQUEST
-------------------------error message end------------------------

**What did you expect to happen:**
install kubeflow 1.0.2 successfully on GCP

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think setting environment right.
such as   PROJECT,  ZONE, gcloud config set project, gcloud config set compute/zone, CLIENT_ID, CLIENT_SECRET.
I tried to install kubeflow 1.1 on gcp  just before installing kubeflow 1.0. but failed also.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.2
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: (e.g. `minikube`)   On GCP ( i.e. GKE )
- Kubernetes version: (use `kubectl version`):    maybe 1.14 GKE
- OS (e.g. from `/etc/os-release`):   GKE os

**Comment by anitaokoh** [comment]
Had a similar error message but still don't know how to solve it
