### ISSUE TITLE
v1alpha1 RBAC policy is removed in Istio 1.6 onwards breaking profile-controller

### ISSUE THREAD

**Issue by connorlwilkes** [kubeflow/kubeflow#5301]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deploy Istio 1.6+ on a cluster alongside the profile-controller. This causes the profile controller to break as it tries to search for ServiceRole.rbac.istio.io CRD which no longer exists as per: https://istio.io/v1.5/docs/reference/config/security/istio.rbac.v1alpha1/

**What did you expect to happen:**

profile-controller to work as normal and manage profiles or documentation to suggest that Istio should only be used up to a certain version

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0
- kfctl version: (use `kfctl version`): kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: GKE
- Kubernetes version: (use `kubectl version`): v1.16.13-gke.1
- OS (e.g. from `/etc/os-release`): OSX

**Comment by thesuperzapper** [comment]
This is really an issue with the manifests, https://github.com/kubeflow/manifests/issues/1551

**Comment by jlewi** [comment]
Uber issue for supporting istio 1.6 kubeflow/kubeflow#5313

**Comment by Jeffwan** [comment]
We won't support istio 1.6 in kubeflow 1.2 release. I remove this story from 1.2 kanban board.

**Comment by thesuperzapper** [comment]
/close

Please see https://github.com/kubeflow/kubeflow/issues/5313 to track progress.
