### ISSUE TITLE
Deprecate header "X-Auth-Token" by using "Authorization"

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/kubeflow#5302]
/kind feature

**Why you need this feature:**
The problem was revealed from this comment https://github.com/kubeflow/kubeflow/issues/4912#issuecomment-665387957

The header `X-Auth-Token` is designed to authenticate request that doesn't contain secure cookie. e.g., API requests from notebook. However, based on https://github.com/arrikto/oidc-authservice/pull/25 `X-Auth-Token` has been replaced by `Authorization`. which means, if it upgrades oidc-authservice for multi-tenant kubeflow, some kubeflow UX will be broken. 

**Describe the solution you'd like:**
in existing code where it sends the header `X-Auth-Token`, send its value along with the header `Authorization`. 
Then trying merge https://github.com/kubeflow/manifests/pull/1431

**Anything else you would like to add:**
This will also encourage the use of standard HTTP headers to be proxy/firewall friendly.

**Comment by swiftdiaries** [comment]
cc @yanniszark

**Comment by shawnzhu** [comment]
Thanks to https://github.com/kubeflow/manifests/pull/1431#issuecomment-691947979 from @yanniszark 

This is my break down of this issue:

According to changes of the OIDC-AuthService since it was last updated in Kubeflow, the header `X-Auth-Token` has been replaced by the header `Authorization` (default setting) - see https://github.com/arrikto/oidc-authservice/pull/25 However, there're other break changes are included. see details from https://github.com/arrikto/oidc-authservice/pull/25#issue-426096377

> Implement CSRF protection for logout

>    Use a session cookie with strict SameSite policy.
>    Make the logout endpoint use the POST method.
>    Only accept header authentication for the logout endpoint.

> In addition, streamline header authentication by introducing an AUTH_HEADER
setting.

So technically it can change the default value of the `AUTH_HEADER` from `Authorization` to `X-Auth-Token` in terms of backward compatibility to support kubeflow 1.1 while looking for options to support the idea of CSRF protection for logout as a new feature to multi-user Kubeflow.

Personally I would like to get CSRF protection of logout for Kubeflow first, then trying to deprecating `X-Auth-Token` which is then becomes a naming change.

**Comment by shawnzhu** [comment]
@yhwang @yanniszark May I ask for your feedback? it's all about adding support for the Authorization header for the oidc-service with or without X-Auth-Token header (serves both authentication and CSRF purpose today).

**Comment by yanniszark** [comment]
@shawnzhu this issue will probably be fixed for 1.3, both in manifests (new authservice version) and in CentralDashboard.

**Comment by juliusvonkohout** [comment]
/close

since oidc-authservice is gone
