### ISSUE TITLE
Can't import notebook controller API

### ISSUE THREAD

**Issue by jrykr** [kubeflow/kubeflow#5308]
/kind bug

**What steps did you take and what happened:**

1. Create a go.mod that requires kubeflow.
2. Import a version from "github.com/kubeflow/kubeflow/components/notebook-controller/api/..."
3. Build fails trying to resolve notebook-controller's dependencies as follows:

```bash
$ go build
go: finding github.com/kubeflow/kubeflow/components/notebook-controller latest
go: github.com/kubeflow/kubeflow/components/notebook-controller@v0.0.0-20200908101143-7f5e242f4671 requires
        github.com/kubeflow/kubeflow/components/common@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

```
// kubeflow/components/notebook-controller/go.mod
// ...
require (
  github.com/kubeflow/kubeflow/components/common v0.0.0-00010101000000-000000000000
  // ...
)

replace github.com/kubeflow/kubeflow/components/common => ../common
```

**What did you expect to happen:**

I would like to be able to use the notebook controller API.

**Anything else you would like to add:**

- It looks like the reason for the relative require was because of failed builds caused by factoring out `common` #4582.
- I'll put in a PR for what worked for me. I just added a valid pseudo-version, which made the relative replace unnecessary. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- kfctl version: (use `kfctl version`): n/a
- Kubernetes platform: (e.g. `minikube`): n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): Mac OS X 10.15.6

**Comment by jrykr** [comment]
Made PR #5309

**Comment by yanniszark** [comment]
PR is merged so this issue should be resolved.
