### ISSUE TITLE
TF serving param deployHttpProxy needs to be transformed from string to bool

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#531]
Like: https://github.com/kubeflow/tf-operator/blob/c54cda92034d2cb8c2085d820a653f4065d0ed16/test/test-app/vendor/kubeflow/core/prototypes/iap-envoy.jsonnet#L26

Otherwise, will get error:
RUNTIME ERROR: Unexpected type string, expected boolean

**Comment by pdmack** [comment]
Hey @lluunn, my WIP is here 3892db9c8ad3de6ba5cbe5e694748372d19e5879
Have at it. Where I got a little slowed down was that
S3_USE_HTTPS=0
S3_VERIFY_SSL=0
to disable those per this [doc](https://www.tensorflow.org/deploy/s3). 

/assign @lluunn
