### ISSUE TITLE
Refactor Jupyter web app to utilize the common code

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5310]
/kind feature

**Why you need this feature:**
We've already created a common Python package for the backend #5164 and an Angular library for the frontend #5252 . We also decided to move our CRUD web apps under the `/components/crud-web-apps` directory #5183.

Following up, we should refactor both the frontend and the backend of JWA to utilize this code. This will help us reduce code duplication significantly and it will also reduce friction on adding new features going forward, since the common logic will be moved elsewhere.

This will be used as a tracking issue for this effort.

**Describe the solution you'd like:**
The changes that need to be done are the following, the order matters:
- [ ] Stop adding more features to `/components/jupyter-web-app` to ensure that the two apps will be synced in terms of features
- [x] Create a new `notebooks` folder under the `/components/crud-web-apps` that will contain the code for the refactored Jupyter web app.
- [x] PR the refactored backend code under `/components/crud-web-apps/jupyter/backend`
- [x] PR the refactored frontend code under `/components/crud-web-apps/jupyter/frontend`
- [x] PR the required {Docker,Make}files as well as READMEs
- [x] Update the CI to build the new web app when the source code is modified from a new PR
- [x] Update our manifests to use the refactored web app

After that we should continue adding new features to the newest web app.

**Anything else you would like to add:**
* The refactored web app will be identical to the current one and it should provide the same functionality the current one does.
* We should be creating issues for each one of the above steps and link them to this one so we can keep track of the work getting done on this
* I'm aiming to have this work merged for Kubeflow 1.2, as well as many of the features from #5280
* We (Arrikto) have already been using this new web app for MiniKF and have tested it extensively

cc @jlewi @jbottum @thesuperzapper

**Comment by DavidSpek** [comment]
@kimwnasptd I believe this issue can be (almost) closed.

**Comment by kimwnasptd** [comment]
Yes it can most certainly be closed. I think all of the above bullets are satisfied so we can move along and close this

/close
