### ISSUE TITLE
How to expose Kubeflow UI on an internal IP address?

### ISSUE THREAD

**Issue by sadeel** [kubeflow/kubeflow#5312]
/kind question

**Question:**
Our team is bringing up a Kubeflow instance on a a private GKE cluster which is locked down (no external internet access). We want to be able use the GKE UI through an internal IP interface. Do you know what changes need to be made to the configs to enable this? Note: we are using kfctl_k8s_istio.yaml.

Thanks

**Comment by thesuperzapper** [comment]
Just make sure your Istio Ingress gateway is only accessible internally. 

For example on GKE, you can annotate a `LoadBalancer` type `Service` with:
```
cloud.google.com/load-balancer-type: "internal"
```
