### ISSUE TITLE
Uber Issue: Support for ISTIO 1.6 in later

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5313]
/kind feature

Creating an uber issue to begin planning for supporting ISTIO 1.6 and newer across Kubeflow.

I believe there were a lot of changes in ISTIO 1.6 that will impact numerous applications in KF. 

Some ISTIO resources are defined statically (e.g. in kubelfow/manifests) but in other places they are created dynamically by controllers (e.g Pipelines controllers, Profile Controller, Jupyter controller).

KFServing depends on KNative which likewise depends on ISTIO so there are probably issues there.

On GCP we are currently at ISTIO 1.4 with Kubeflow 1.1. I'm not sure which ISTIO other distributions of KF are using.

@kubeflow/wg-serving-leads Do you have an issue tracking ISTIO 1.6 for KFServing?
@kubeflow/wg-automl-leads Will you be impacted by ISTIO 1.6?

**Comment by yuzisun** [comment]
@jlewi KFServing standalone should work with Istio 1.6 without issues as we already upgraded to 1.6 internally, but I think KFServing in kubeflow will not work as v1alpha1 istio rbac policy is deprecated, we need to switch to use v1beta1 authentication API.

**Comment by yanniszark** [comment]
Components needing code changes:

- Profile controller
    - Issue: https://github.com/kubeflow/kubeflow/issues/5301
    - Code: https://github.com/kubeflow/kubeflow/blob/5185f06786554fa6598f0c735829476b0cdf29b0/components/profile-controller/controllers/profile_controller.go#L336

- KFAM
    - Issue: 
    - Code: https://github.com/kubeflow/kubeflow/blob/4bf2d4131a5aebe0f1b53d36dd94031f88426c0b/components/access-management/kfam/bindings.go

As for manifests, we need to scan for ServiceRoles, ServiceRoleBindings, RBACConfig and ClusterRBACConfig and transform them into AuthorizationPolicy resources. I think I saw some mention of an automated tool from Istio, I wonder if that's available.

**Comment by thesuperzapper** [comment]
Linking to similar issue: https://github.com/kubeflow/manifests/issues/1551

**Comment by gaocegege** [comment]
I do not think it will affect automl, Please double check @andreyvelich

**Comment by DavidSpek** [comment]
@yanniszark I believe the tool you are talking about is `istioctl experimental authz convert`, as mentioned [here](https://istio.io/latest/blog/2019/v1beta1-authorization-policy/).

**Comment by andreyvelich** [comment]
AutoML should not be affected. We use only `VirtualService` from ISTIO to connect the UI.

**Comment by marcjimz** [comment]
+1 on this issue, we noticed RBAC was dropped on the Jupyter controller once we made the migration to 1.6.

**Comment by thesuperzapper** [comment]
Similar issue: #5176

**Comment by maganaluis** [comment]
@DavidSpek @yanniszark 

In regards to the ```istioctl``` utility, I've tried it and it doesn't actually give the desired output. The AuthorizationPolicy is actually fairly simple, the example below shows how to use it with the ```request.headers``` to enable the current behavior. 

The question is to either continue to use one AuthorizationPolicy per user/contributor or use a single AuthorizationPolicy and append new users if they are not already part of it. I'm guessing the latter one will require changing the logic more in kfam and the profile controller. 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: admin-policy
 namespace: admin
spec:
  rules:
  - when:
    - key: request.headers[kubeflow-userid]
      values: ["admin@kubeflow.org"]
```

**Comment by yuzisun** [comment]
I would suggest we go directly to istio 1.7 as we run into sidecar race condition issues with 1.6 which is fixed in 1.7 https://istio.io/latest/news/releases/1.7.x/announcing-1.7/#production-operability-improvements.

**Comment by jlewi** [comment]
@kubeflow/wg-notebook-leads What is the readiness of notebooks for  Istio 1.6+?

@kubeflow/wg-pipeline-leads What is the readiness of pipelines for Istio 1.6+?

**Comment by animeshsingh** [comment]
@yanniszark can the control plane apps make it before 1.2 release? 

KFServing we can start standardizing. As @yuzisun mentioned, 1.7 will be a better candidate.

**Comment by Bobgy** [comment]
I think from KFP side, we are relying on istio RBAC heavily for multi-user mode. We won't have bandwidth to upgrade to istio 1.6 if we need migration there within current release schedule for Kubeflow 1.2

**Comment by ericandrewmeadows** [comment]
I just made a PR for Profile Controller here - https://github.com/kubeflow/kubeflow/pull/5393

**Comment by sdake** [comment]
Hi gang. Istio maintainer and workgroup lead here. Istio 1.9 (february 2021 release) includes a massive performance improvement for mesh configurations with a lot of churn that contains 200+ sidecars without using a `Sidecar` scoping resource.

I would encourage two sets of CI. One using the `main` (or master..) branch. And one using the latest release branch (1.8 in about 1 week).

With these two CIs in place, you would make the stable release voting, and the master release of Istio nonvoting. This would help your upstream (Istio) understand when we break kubeflow in error.

Cheers,
-steve

**Comment by animeshsingh** [comment]
cc @Bobgy - believe KFP is the only thing blocking the move to higher version of Istio

**Comment by animeshsingh** [comment]
Additionally strong concerns are being made by community users around security aspects of sticking to older versions, and from a security perspective there is valid case to move up cc @Jeffwan @Bobgy

**Comment by Jeffwan** [comment]
I agree, current Istio version in kubeflow is far behind. Besides KFP, I think fundamental dex based solution reply on Istio RBAC and envoy filters. Community didn't put time on the upgrade and we are not sure the compatibility. Since @kubeflow/wg-manifests-leads forms and Istio manifest is under the scope. Let's see if WG has plans on it

**Comment by PatrickXYS** [comment]
I think this is important and will need to be discussed after 1.2 @cvenets

**Comment by yanniszark** [comment]
@PatrickXYS it seems there is much community interest for this.
@ericandrewmeadows has already started a PR for the `profile-controller` and I'm reviewing it!
To better track the work remaining, I opened issues for the two components of wg-notebooks that still use Istio RBAC:

| Component | Issue | PR | Merged |
| - | - | - | - |
| profile-controller | https://github.com/kubeflow/kubeflow/issues/5397 | https://github.com/kubeflow/kubeflow/pull/5393 | :x: |
| kfam | https://github.com/kubeflow/kubeflow/issues/5399 | :x: | :x: |

I think those problems will have been addressed by the 1.3 release.

**Comment by PatrickXYS** [comment]
@yanniszark For help wanted label, you might need to have write access to the repo and add it manually.

**Comment by Jeffwan** [comment]
@PatrickXYS write permission is required for manual efforts. 

`/help` this should work @yanniszark

**Comment by Bobgy** [comment]
Thanks @animeshsingh for the heads up!
I've filed a bug for KFP https://github.com/kubeflow/pipelines/issues/4768 and prioritized it.

**Comment by Jeffwan** [comment]
istio 1.6 won't be available in kubeflow 1.2. I will remove this story from 1.2 kanban board.

**Comment by berndverst** [comment]
On Azure since at least Kubeflow 1.1 we have been requiring deploying Istio 1.6.X (1.7.X doesn't work in my testing) before deploying our stack (which does not include Istio itself).

Most recently I tested Kubeflow 1.2 on Istio 1.6.14 with Kubernetes 1.17.13.

**Comment by sdake** [comment]
Berdt,

Would love for you to provide any RCA analysis done on Istio 1.7 (or
preferred 1.8) eapecially in an issue tracker so we can solve the upstream
Istio bugs.

**Comment by berndverst** [comment]
@sdake sure thing. Should I file this issue in this repo or in manifests instead?

**Comment by berndverst** [comment]
Related to this issue, it would also be great if we could update deployment / E2E tests to install Istio via `istioctl` and test for whichever version ranges we support - for example if we aim to support 1.6+, perhaps test against latest 1.6.X, 1.7.X and 1.8.X at this time.

It would be great to move away from any bundled Istio versions and provide more flexibility. (Of course minimum Istio version requirements make sense)

**Comment by sdake** [comment]
please file in Istio/istio and cc myself and @howardjohn

**Comment by sdake** [comment]
yea please do submit PRa to build e2e tests using istioctl preferably
against the minimum pin and mximum pin.

**Comment by thesuperzapper** [comment]
@sdake @berndverst @Jeffwan @Bobgy I have raised a proposal to unbundle services like istio from our manifests: https://github.com/kubeflow/community/issues/460

**Comment by yanniszark** [comment]
A small update on this issue. 

| Component | Issue | PR | Merged |
| - | - | - | - |
| profile-controller | https://github.com/kubeflow/kubeflow/issues/5397 | https://github.com/kubeflow/kubeflow/pull/5393 | :x: |
| kfam | https://github.com/kubeflow/kubeflow/issues/5399 | https://github.com/kubeflow/kubeflow/pull/5439 | :x: |
| pipelines | https://github.com/kubeflow/pipelines/issues/4768 | https://github.com/kubeflow/manifests/pull/1719 | :x: |

All issues have PRs. I will review the first two and the kfp prs are also underway. After that, we should be ready for any 1.6+ version.

**Comment by Bobgy** [comment]
Per https://github.com/kubeflow/manifests/pull/1719#issuecomment-762272491

FYI, I agree we need to break manifests e2e test when merging these PRs, because the e2e cluster still has the old istio version.
No action needed for configuration though, I believe we can just lgtm and approve these PRs, the e2e test was not set as a required test.

**Comment by agilgur5** [comment]
Updating the table as I looked into it
 
| Component	| Issue	| PR	 | Merged |
| --- | --- | --- | --- |
| profile-controller |	#5397	| #5617 |	✔️ |
| kfam |	#5399	 | #5725	 | ✔️ |
| pipelines	| [kubeflow/pipelines#4768](https://github.com/kubeflow/pipelines/issues/4768)	| [kubeflow/manifests#1719](https://github.com/kubeflow/manifests/pull/1719)	| ✔️| 

> After that, we should be ready for any 1.6+ version.

So I believe that it's all good for any Istio version 1.6+ as the [1.3 blog post suggests](https://blog.kubeflow.org/kubeflow-1.3-release/) and that this issue can be closed right?

I couldn't find a formal changelog entry about this so found this issue. I'm assuming Istio 1.7, 1.8, and 1.9 are now all compatible, and https://github.com/kubeflow/manifests/pull/1778 suggested that 1.9 works perfectly well.

**Comment by yanniszark** [comment]
Yeap, all work is done!
Closing the issue...
