### ISSUE TITLE
is there any lighter way to deploy notebook on k8s without kubeflow？

### ISSUE THREAD

**Issue by wuzhiye7** [kubeflow/kubeflow#5320]
/kind question

is there any lighter way to deploy notebook on k8s without kubeflow？
jupyterhub on k8s is not a good idea. I'd like（jupyter-web-app + notebook controller +profile-controller+istio） on k8s.
 deploy like [tf-operator](https://github.com/kubeflow/tf-operator/issues/904#issuecomment-453008853) with CRD or any lighter way.

**Comment by swiftdiaries** [comment]
https://zero-to-jupyterhub.readthedocs.io/en/latest/

**Comment by DavidSpek** [comment]
I have no experience with it, but Canonical has Charmed Kubeflow Lite. Maybe that is interesting for your use case. https://jaas.ai/u/kubeflow-charmers/kubeflow-lite

**Comment by goanto** [comment]
I don't think a solution is readily available with all the specs you mentioned, but do checkout zero to jupyterhub blog

**Comment by jbottum** [comment]
@wuzhiye7 As you may know, Arrikto has helped to contribute Notebooks in Kubeflow and extend both to support isolation, authentication and authorization.    This works pretty well and provides advantages over other non-Kubeflow solutions.   I am interested in the driver for your request.    Are you just looking to use Notebooks and will not extend into pipelines, hyperparameter tuning and inferencing ?   Which cloud environment do you need to run on i.e. GCP, AWS, On-Prem.
