### ISSUE TITLE
OIDC authservice Integration with Azure AD 

### ISSUE THREAD

**Issue by sudivate** [kubeflow/kubeflow#5321]
/kind bug

**What steps did you take and what happened:**
I'm enabling authentication with Azure AD on AKS and installing Kubeflow with `kfctl_istio_dex.v1.1.0.yaml`  but skipping the dex from the manifest as Azure AD is an OIDC provider.

OIDC Auth Service Configuration: 
 - client_id=XXXX
  - oidc_provider=https://login.microsoftonline.com/XXXX/v2.0
  - oidc_redirect_uri=https://XXXX/login/oidc
  - oidc_auth_url=https://login.microsoftonline.com/XXXX/oauth2/v2.0/authorize
  - application_secret=XXXX
  - skip_auth_uri=
  - namespace=istio-system
  - userid-header=kubeflow-userid
  - userid-prefix=

**Pod log for Auth service** 
```
time="2020-09-24T18:28:13Z" level=info msg="Starting readiness probe at 8081"
time="2020-09-24T18:28:13Z" level=info msg="No  USERID_TOKEN_HEADER  specified, using 'kubeflow-userid-token' as default."
time="2020-09-24T18:28:13Z" level=info msg="No  SERVER_HOSTNAME  specified, using '' as default."
time="2020-09-24T18:28:13Z" level=info msg="No  SERVER_PORT  specified, using '8080' as default."
time="2020-09-24T18:28:13Z" level=info msg="No  SESSION_MAX_AGE  specified, using '86400' as default."
time="2020-09-24T18:28:13Z" level=info msg="Starting web server at :8080"
time="2020-09-24T18:28:13Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: 404 Not Found: "
```

- OIDC-auth service image pointing to  **gcr.io/arrikto/kubeflow/oidc-authservice:6ac9400**
- `https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration` is discoverable from the internet

**Environment:**
- Kubeflow version:  `v1.1.O`
- kfctl version: `kfctl_v1.1.0-0-g9a3621e_linux.tar.gz`
- Kubernetes platform: `Azure Kubernetes Service` 
- Kubernetes version: `1.17.11`

CC: @yanniszark @lalithvaka @krishnadurai

**Comment by lalithvaka** [comment]
@sudivate , typically this happens when your well known configuration is not reachable. Make sure, this URL is accessible from where the container is running. 
https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration

Could be your AKS outbound firewall is blocked. Check the network settings.

**Comment by sudivate** [comment]
> @sudivate , typically this happens when your well known configuration is not reachable. Make sure, this URL is accessible from where the container is running.
> https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration
> 
> Could be your AKS outbound firewall is blocked. Check the network settings.

@lalithvaka  There are no outbound firewall rules blocking access and container can access `https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration`

**Comment by lalithvaka** [comment]
Per https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc, do you need to add appid to the well known URL?
```
If your app has custom signing keys as a result of using the claims-mapping feature, you must append an appid query parameter containing the app ID in order to get a jwks_uri pointing to your app's signing key information. For example: https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration?appid=6731de76-14a6-49ae-97bc-6eba6914391e contains a jwks_uri of https://login.microsoftonline.com/{tenant}/discovery/v2.0/keys?appid=6731de76-14a6-49ae-97bc-6eba6914391e.
```

**Comment by yanniszark** [comment]
@sudivate can you do a
`echo $OIDC_PROVIDER` and
`curl -i $OIDC_PROVIDER/.well-known/openid-configuration` from inside the `oidc-authservice` container?
This should be the call that the AuthService does.

**Comment by sudivate** [comment]
@yanniszark I was unable to install curl without root access on the oidc-authservice container, however, I tried spinning another container to check if a well-known configuration to ensure it is accessible.

**Comment by yanniszark** [comment]
@sudivate how about using: https://github.com/aylei/kubectl-debug
I would also like to see the value of `$OIDC_PROVIDER` inside the container.

**Comment by sudivate** [comment]
@yanniszark  Yup I can `echo $OIDC_PROVIDER` inside the container which is  https://login.microsoftonline.com/XXXX/v2.0

**Comment by sudivate** [comment]
Thank you @lalithvaka  @yanniszark  I got this working it was endlessly waiting for inference webhook.  I will create a PR for a step-by-step guide for Azure.

The next blocker is to authenticate KFP client  SDK  https://github.com/kubeflow/pipelines/issues/4569. 
Please share if you have any thoughts on this?

**Comment by sudivate** [comment]
@aronchick  This is good to close. 
We have a new [manifest ](https://github.com/kubeflow/manifests/blob/v1.1-branch/kfdef/kfctl_azure_aad.v1.1.0.yaml)and [instructions ](https://github.com/kubeflow/website/pull/2282)to configure OIDC auth service for Azure AD
