### ISSUE TITLE
efore visiting the MiniKF dashboard, while ensuring that Minikube, Kubeflow, and Rok (Snapshot Store) are up and running, the deployment gets stuck at 74% in the SSH step.

### ISSUE THREAD

**Issue by aditipatil0711** [kubeflow/kubeflow#5322]
https://www.kubeflow.org/docs/started/workstation/minikf-gcp/

Refer point 5 of the given Getting started module

**Comment by jbottum** [comment]
Hi @aditipatil0711, just checking to see if you tried this again.  I just tried to deploy and was successful.   Which region are you deploying into ?  @cspavlou do you see anything / have any questions ?
