### ISSUE TITLE
TFX 0.24.0 Trainer Crashes Interactive Context in Jupyter Notebook

### ISSUE THREAD

**Issue by LRSutton** [kubeflow/kubeflow#5325]
/kind bug

**What steps did you take and what happened:**

Created an interactive pipeline based on TFX 0.23.0. The pipeline ran through to fitting the model. Due to unrelated issues, I had to upgrade to TFX 0.24.0. Running the following block causes the Jupyter notebook to fail with the error shown below. (Error IS NOT displayed on Jupyter interface but from pulling the logs of the notebook.) 

After the error is displayed the kernal crashes and restarts.

```
from tfx.components.base import executor_spec
from tfx.components.trainer.executor import GenericExecutor
from tfx.proto import trainer_pb2

TRAINING_STEPS = 100
EVALUATION_STEPS = 10

trainer = Trainer(
    module_file=os.path.join(os.getcwd(), "pipeline_model_trainer.py"),
    custom_executor_spec=executor_spec.ExecutorClassSpec(GenericExecutor),
    examples=transform.outputs['transformed_examples'],
    transform_graph=transform.outputs['transform_graph'],
    schema=schema_importer.outputs['result'],
    train_args=trainer_pb2.TrainArgs(num_steps=TRAINING_STEPS),
    eval_args=trainer_pb2.EvalArgs(num_steps=EVALUATION_STEPS))

context.run(trainer)
```

The 
```
	Type	Presence	Valency	Domain
Feature name				
'Age_xf'	FLOAT	required	single	-
'Fare_xf'	FLOAT	required	single	-
'Sex_xf'	FLOAT	required	single	-
'Survived_xf'	FLOAT	required	single	-
```

The data is a few columns from Kaggle's Titanic prediction data set. The notebook is running with 2 CPU and 2Gi of RAM.

The error:

```
2020-09-29 20:35:28.282615: F ml_metadata/metadata_store/query_config_executor.cc:299] Unexpected oneof: 
[I 20:35:30.110 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel b4bacd3f-3053-4a4b-b3ba-6e1c4a8c5562 restarted
```

[pipeline_model_trainer.py.gz](https://github.com/kubeflow/kubeflow/files/5301788/pipeline_model_trainer.py.gz)

**What did you expect to happen:**

The Jupyter notebook to not crash and the model to either build or give application-level errors as to the build.

**Anything else you would like to add:**

As stated above, this model with the current data was able to be fit running TFX 0.23.0. Further, the reason I believe this is a Kubeflow error is that it appears to be crashing in the Kubeflow Metadata layer(s).  If I am mistaken, any insight into the real culprit would be greatly appreciated.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):

> 1.0.0

- kfctl version: (use `kfctl version`):

> kfctl v1.1.0-0-g9a3621e

- Kubernetes platform: (e.g. `minikube`)

> kubeadm

- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from `/etc/os-release`):

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by jbottum** [comment]
@LRSutton Hi, which platform / cloud are you running this on i.e AWS, GCP, on-prem ?

**Comment by LRSutton** [comment]
Hey Josh... Running on-prem using kubeadm.

`kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:17:52Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by LRSutton** [comment]
And, btw, this behavior continues using TFX 0.24.

**Comment by yuanhunglo** [comment]
Running into the same issue. Midway through executing interactive context with the Trainer component my Jupyter notebook unexpectedly restarted without error. Using TFX version 0.24.1.
