### ISSUE TITLE
Admission Webhook is not compiling 

### ISSUE THREAD

**Issue by slenky** [kubeflow/kubeflow#5328]
/kind bug

**What steps did you take and what happened:**
I am trying to build an Admission webhook image using the latest master to support Tolerations in PodDefaults.
It fails with that error:
```
docker build -t kubeflow-admission-webhook:vmaster-7f5e242-tolerations .
...
#11 168.2 go: extracting golang.org/x/sys v0.0.0-20190418153312-f0ce4c0180be
#11 168.7 go: extracting golang.org/x/text v0.3.0
#11 214.8 # github.com/kubeflow/kubeflow/components/admission-webhook
#11 214.8 ./main.go:120:25: cannot use &pd.Spec.Tolerations (type *[]"k8s.io/api/core/v1".Toleration) as type *"k8s.io/api/core/v1".Toleration in assignment
#11 214.8 ./main.go:128:40: cannot use defaultTolerations (type []*"k8s.io/api/core/v1".Toleration) as type []*v1alpha1.PodDefault in argument to mergeTolerations
#11 214.8 ./main.go:392:22: cannot use &pd.Spec.Tolerations (type *[]"k8s.io/api/core/v1".Toleration) as type []*"k8s.io/api/core/v1".Toleration in assignment
#11 214.8 ./main.go:406:47: cannot use defaultTolerations (type []*"k8s.io/api/core/v1".Toleration) as type []*v1alpha1.PodDefault in argument to mergeTolerations
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c if [ "$(uname -m)" = "aarch64" ]; then         CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o webhook -a . ;     else         CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o webhook -a . ;     fi]: runc did not terminate sucessfully
```

**What did you expect to happen:**
I expect a working Docker image.

**Environment:**

- Docker version: 19.03.13
- OS (e.g. from `/etc/os-release`): MacOS Catalina

**Comment by jbottum** [comment]
Hi @slenky what platform are you deploying into i.e. GCP, AWS, On-Prem, on your laptop.    The OS is Catalina ?  is this on your laptop ?  If so, you will need to look at using Minikube or MiniKF.

**Comment by slenky** [comment]
> Hi @slenky what platform are you deploying into i.e. GCP, AWS, On-Prem, on your laptop. The OS is Catalina ? is this on your laptop ? If so, you will need to look at using Minikube or MiniKF.

Hi @jbottum , deployment platform doesn't matter as I am trying to build an image only for admission webhook, that's another story.

**Comment by slenky** [comment]
Well, also kinda related to this one. As I see #5280 enables Tolerations configuration in JWA. Does it use a PodDefault?
