### ISSUE TITLE
kubeflow 1.0.2 is not installed on kubernetes 1.19

### ISSUE THREAD

**Issue by alforik** [kubeflow/kubeflow#5329]
/kind bug
kubeflow 1.0.2 is not installed on kubernetes 1.19

Webhook error report is like this

kubectl get apiservices | grep webhook
v1beta1.webhook.cert-manager.io        cert-manager/cert-manager-webhook   False (FailedDiscoveryCheck)   55s

and 

validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0613] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout631412688": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
WARN[0613] Will retry in 38 seconds.                     filename="kustomize/kustomize.go:203"

**What did you expect to happen:**

No problem with cert-manager   kubeflow 1.0.2 on kubenetes 1.19

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):  1.0.2
- kfctl version: (use `kfctl version`):  1.0.2
- Kubernetes platform: (e.g. `minikube`) : vanilla kubernetes
- Kubernetes version: (use `kubectl version`):  1.19.2
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by zzha2941** [comment]
I meet the same error.

**Comment by jbottum** [comment]
@alforik is this an on-prem install or for AWS or GCP ?

**Comment by dale88** [comment]
I meet the same error.

**Comment by Jeffwan** [comment]
kubeflow 1.0.2 is not certified on 1.19 yet. I think there's compatibility matrix. If someone can figure out the blocking issues, feel free to file a PR. There might be breaking API changes

**Comment by DavidSpek** [comment]
This seems to be a duplicate of https://github.com/kubeflow/website/issues/2206. See this comment for some more information and a workaround: https://github.com/kubeflow/website/issues/2206#issuecomment-698234904.

**Comment by dale88** [comment]
My Environment:
Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.1.0
kfctl version: (use kfctl version): 1.1.0
Kubernetes version: (use kubectl version): 1.15
OS (e.g. from /etc/os-release): centos 7.6

The error seems like cert-manager error, but the pods looks fine.

```
[root@cdh6-node2 ~]# kubectl get pod -n cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5bb6f6d6ff-b64q6              1/1     Running   1          69m
cert-manager-cainjector-5b97fdb664-k9lp4   1/1     Running   6          69m
cert-manager-webhook-55d698bc9f-jjkbj      1/1     Running   0          69m

```
APIservice : "v1beta1.webhook.cert-manager.io" is False
Status:
  Conditions:
    Last Transition Time:  2020-10-22T06:20:30Z
    Message:               failing or missing response from https://10.105.155.139:443/apis/webhook.cert-manager.io/v1beta1: Get https://10.105.155beta1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available

**Comment by dale88** [comment]
I have solved this problem. In my case, I use vpn service,the flannel network interface disappears and is never recreated. and then I restart the docker image . finally it works!

 See this comment for some more information and a workaround:
https://github.com/jetstack/cert-manager/issues/2918

**Comment by DavidSpek** [comment]
Closing this issue as I believe it has been solved.
/close
