### ISSUE TITLE
Jupyter notebook connection failed with error "failed: Error during WebSocket handshake: Unexpected response code: 200"

### ISSUE THREAD

**Issue by geewynn** [kubeflow/kubeflow#5333]
/kind bug

**What steps did you take and what happened:**
I have deployed kubeflow on GCP GKE with https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml following the instruction on https://v1-0-branch.kubeflow.org/docs/started/k8s/kfctl-istio-dex/

**What did you expect to happen:**
To be able to connect to jupyter notebook without any problem

**Anything else you would like to add:**
![Screenshot from 2020-10-08 10-05-57](https://user-images.githubusercontent.com/29405050/95438912-da547800-094e-11eb-9644-a160dc75113c.png)

**Environment:**

- Kubeflow version: 1.0
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: GCP

**Comment by DavidSpek** [comment]
@geewynn Sorry for the late response. Are you still experiencing this issue? If so, what notebook image are you trying to use?
