### ISSUE TITLE
facing issue while deploying kubeflow in RHEL7.6

### ISSUE THREAD

**Issue by argunasekhar** [kubeflow/kubeflow#5336]
i'm trying to deploy kubeflow in my test setup, it is throwing below error 

2020/09/24 04:18:34 absolute path error in '/root/kf-flow/.cache/manifests/namespaces/base' : evalsymlink failure on '/root/kf-flow/.cache/manifests/namespaces/base' : lstat /root/kf-flow/.cache/manifests/namespaces: no such file or directory
ERRO[0000] Error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../.cache/manifests/namespaces/base': open /root/kf-flow/.cache/manifests/namespaces/base: no such file or directory  filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../.cache/manifests/namespaces/base': open /root/kf-flow/.cache/manifests/namespaces/base: no such file or directory

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.1
- kfctl version: (use `kfctl version`):1.1
- Kubernetes platform: (e.g. `minikube`) Kubernetes 
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`): RHEL7.6

**Comment by argunasekhar** [comment]
Hi , 

please update on this issue

**Comment by argunasekhar** [comment]
Hi , 

Please update

**Comment by shrinidhisuresha** [comment]
Hi,

Even i'm facing similar issue. Did we find work around or fix for the same.

**Comment by jjf130** [comment]
Facing a similar issue when trying to automate kubeflow installation on eks using codebuild: 


time="2020-11-16T18:04:53Z" level=info msg="namespace: kubeflow" filename="utils/k8utils.go:431"
--
373 | time="2020-11-16T18:04:53Z" level=info msg="Log cluster name into KfDef: arn:aws:eks:<region-redacted>:<account-redacted>:cluster/<cluster-name-redacted>" filename="kustomize/kustomize.go:242"
374 | time="2020-11-16T18:04:53Z" level=info msg="Deploying application namespaces" filename="kustomize/kustomize.go:248"
375 | 2020/11/16 18:04:53 absolute path error in '/codebuild/output/src214141521/.cache/manifests/manifests-1.1-branch/namespaces/base' : evalsymlink failure on '/codebuild/output/src214141521/.cache/manifests/manifests-1.1-branch/namespaces/base' : lstat /codebuild/output/src214141521/.cache: no such file or directory
376 | time="2020-11-16T18:04:53Z" level=error msg="Error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../../.cache/manifests/manifests-1.1-branch/namespaces/base': open /codebuild/output/src214141521/.cache/manifests/manifests-1.1-branch/namespaces/base: no such file or directory" filename="kustomize/kustomize.go:155"
377 | Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../../.cache/manifests/manifests-1.1-branch/namespaces/base': open /codebuild/output/src214141521/.cache/manifests/manifests-1.1-branch/namespaces/base: no such file or directory
378 | Usage:
379 | kfctl apply -f ${CONFIG} [flags]
380 |  
381 | Flags:
382 | --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
383 | -f, --file string      Static config file to use. Can be either a local path:
384 | export CONFIG=./kfctl_gcp_iap.yaml
385 | or a URL:
386 | export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
387 | export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
388 | export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
389 | export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
390 | kfctl apply -V --file=${CONFIG}
391 | -h, --help             help for apply
392 | -V, --verbose          verbose output default is false
393 |  
394 | kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../../.cache/manifests/manifests-1.1-branch/namespaces/base': open /codebuild/output/src214141521/.cache/manifests/manifests-1.1-branch/namespaces/base: no such file or directory

**Comment by Tomer23** [comment]
I encountered this issue as well with GitLab CI. I referenced the kfctl...yml file in a subdirectory. I moved it to the same folder where I execute and everything worked perfectly.
