### ISSUE TITLE
How to set GCP credentials in Kubeflow UI & SDK ?

### ISSUE THREAD

**Issue by julioyildo** [kubeflow/kubeflow#5338]
Hello,

I'm new on kubeflow. I'm testing Kubeflow through Minikf. Actually I'm looking for a way to set my GCP Credentials in the UI interface and in the SDK, but having some difficulties manage it.

### 1 - I tried "Configurations" field when creating  a new JupyterServer, but doesn't seem to be the good way.

> (Optional) Specify one or more additional **configurations** as a list of PodDefault labels. To make use of this option, you must create a PodDefault manifest. In the PodDefault manifest, you can specify configurations including volumes, secrets, and environment variables. Kubeflow matches the labels in the configurations field against the properties specified in the PodDefault manifest. Kubeflow then injects these configurations into all the notebook Pods on this notebook server.

---------------------------------------------------------------------------------------------------

### 2 - Then, i tried GCP module in the SDK with this method : 

![Capture d’écran 2020-10-11 à 22 58 11](https://user-images.githubusercontent.com/17247165/95690043-42d47b00-0c15-11eb-8812-c63e34670c57.png)

With this a simple Query component which[ I have taken on AI Hub.
](https://aihub.cloud.google.com/u/0/p/products%2F4700cd7e-2826-4ce9-a1ad-33f4a5bf7433)

`.apply(gcp.use_gcp_secret('user-gcp-sa', secret_file_path_in_volume="my-credentials.json", secret_volume_mount_path='/secret/gcp-credentials'))`

But actually it doesn't work either. I have no return in the logs to debug. The only return I get - after the component has interrupted itself - is the following:

      `Could not get main container logs: Error: Unable to retrieve workflow status: [object Object].`

-------

Thank you very much for your help! 🙏

------

FULL CODE
```

%%capture

KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.14/kfp.tar.gz'
!pip3 install $KFP_PACKAGE --upgrade


import kfp.components as comp

COMPONENT_SPEC_URI = 'https://raw.githubusercontent.com/kubeflow/pipelines/d2f5cc92a46012b9927209e2aaccab70961582dc/components/gcp/bigquery/query/component.yaml'
bigquery_query_op = comp.load_component_from_url(COMPONENT_SPEC_URI)
help(bigquery_query_op)


QUERY = 'SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10'



# Required Parameters
PROJECT_ID = 'myproject'
GCS_WORKING_DIR = 'gs://my-bucket'




# Optional Parameters
EXPERIMENT_NAME = 'Bigquery -Query'
OUTPUT_PATH = '{}/bigquery/query/questions.csv'.format(GCS_WORKING_DIR)




import kfp.dsl as dsl
import kfp.gcp as gcp
import json
@dsl.pipeline(
    name='Bigquery query pipeline',
    description='Bigquery query pipeline'
)
def pipeline(
    query=QUERY,
    project_id = PROJECT_ID,
    dataset_id='',
    table_id='',
    output_gcs_path=OUTPUT_PATH,
    dataset_location='US',
    job_config=''
):
    bigquery_query_op(
        query=query,
        project_id=project_id,
        dataset_id=dataset_id,
        table_id=table_id,
        output_gcs_path=output_gcs_path,
        dataset_location=dataset_location,
        job_config=job_config).apply(gcp.use_gcp_secret('user-gcp-sa', secret_file_path_in_volume="my-credentials.json", secret_volume_mount_path='/secret/gcp-credentials'))




pipeline_func = pipeline
pipeline_filename = pipeline_func.__name__ + '.zip'
import kfp.compiler as compiler
compiler.Compiler().compile(pipeline_func, pipeline_filename)



#Specify pipeline argument values
arguments = {}



#Get or create an experiment and submit a pipeline run
import kfp
client = kfp.Client()
experiment = client.create_experiment(EXPERIMENT_NAME)



#Submit a pipeline run
run_name = pipeline_func.__name__ + ' run'
run_result = client.run_pipeline(experiment.id, run_name, pipeline_filename, arguments)


```

**Comment by akulkailwoo** [comment]
@julioyildo were you able to resolve it? I am facing the same issue.

**Comment by julioyildo** [comment]
@akulkailwoo no :/
