### ISSUE TITLE
Kubeflow on EKS with SSL certificate

### ISSUE THREAD

**Issue by tretos53** [kubeflow/kubeflow#5339]
/kind bug

**What steps did you take and what happened:**

- I deployed kubeflow on EKS.
- I created a route53 domain `kubeflow.mydomain.com` and pointed to an alias, a service in istio-system namespace `istio-ingressgateway` (type: LoadBalancer).
- When I access `https://kubeflow.mydomain.com` I get a warning message:
```
Warning: Potential Security Risk Ahead
Firefox detected a potential security threat and did not continue to `https://kubeflow.mydomain.com` If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for kubeflow.mydomain.com. The certificate is only valid for xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxx.REGION.elb.amazonaws.com.
 
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
``` 
I can ignore the message and use kubeflow.
When I update istio-ingressgateway-certs with my own certificates the error is the same.
What's the correct way of fixing this?

**What did you expect to happen:**
I expect to have a correct SSL certificate.

**Environment:**

- Kubeflow version: build version dev_local
- kfctl version: (use `kfctl version`):
- Kubernetes platform: EKS
- Kubernetes version: (use `kubectl version`): Client Version: v1.18.6, Server Version: v1.14.9-eks-658790
- OS (e.g. from `/etc/os-release`): AWS

**Comment by tretos53** [comment]
Any advise on this would be appreciated.

**Comment by hossein-rasi** [comment]
I have the same issue to use AWS cert-manager and adjust the istio ingressGateway alb and be able to add HTTPS listener which will use my SSL certificate. Is there any workaround to modify kftctl_aws.yaml file to fix that?
