### ISSUE TITLE
Jupyter notebook server is launched using incorrect container image

### ISSUE THREAD

**Issue by agnz** [kubeflow/kubeflow#5340]
/kind bug

**What steps did you take and what happened:**
New deployment of Kubeflow. Created a new notebook server based on one of the provided images: gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu
Running in the notebook:
```
import tensorflow as tf
tf.__version__
```
Outputs:
'2.4.0-dev20201011'

**What did you expect to happen:**
Output: '1.15.2'

**Anything else you would like to add:**
Absolutely perplexed. If I run the same image using docker - I get the correct version...
What am I doing wrong here?
The title is just a guess...

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`): bare metal cluster, deployed with Deepops
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS

**Comment by jbottum** [comment]
@kimwnasptd do you see an issue here?

**Comment by agnz** [comment]
I tracked the behaviour down to one particular PV - it was only happening if that PV was mounted as the workspace. After deleting all files on PV, the behaviour stopped. It must be related to something that I was doing rather than Kubeflow.
