### ISSUE TITLE
How to install Kubeflow on a specific node in a multinode cluster

### ISSUE THREAD

**Issue by ShilpaGopal** [kubeflow/kubeflow#5341]
/kind question

**Question:**
I have an on-prem cluster with 5 worker node in which only one node has SAN attached to it. I have a storage class for the local path. Now I want to install all the kubeflow components in that particular node where SAN is attached. Is there an easier way of doing this? One way I can think of is, modify the deployment YAMLs to specify selector nodes. Moreover, Its an air-gapped environment, I have already downloaded necessary manifest and modified it to pull the images from a private registry.  Changing the deployment YAML for all of the kubeflow components to add selector node looks tedious! Any suggestions to approach this is welcomed.

**Comment by jbottum** [comment]
@ShilpaGopal Have you considered joining the on-prem SIG meetings on Thursday ?

**Comment by DavidSpek** [comment]
@ShilpaGopal Is this issue still relevant or can it be closed?

**Comment by ShilpaGopal** [comment]
@DavidSpek , we should close it. There is no option to schedule the pod to a particular node on a multi node application. We can achieve this by editing manifest but it's a lot of work. Moreover, deploying everything in a single node is not recommended as it results in single point of failure.
