### ISSUE TITLE
How to configure my own environment IDP dex LDAP auth in Kubeflow 1.1.0

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kubeflow#5344]
Hi Team,
I have my own environment IDP dex authentication which based on organization LDAP user. I am using Kubeflow 1.1.0 version https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml and it's working fine in my environment.  I have to remove the kubeflow own dex auth setup and have to setup my own IDP dex LDAP auth.  I can create IDP client id. 

Here how can i configure my IDP dex LDAP auth in Kubeflow..?? Where ever need to modify..??

**Comment by jbottum** [comment]
Hi @micemuni, I assume you have read this article, https://journal.arrikto.com/kubeflow-authentication-with-istio-dex-5eafdfac4782.   Is your installation on-prem or in a public cloud (AWS, GCP ) ?

**Comment by micemuni** [comment]
Yes, I deployed kubeflow in AWS cloud & my IDP dex authentication cluster is also in AWS cloud, Just i need to use My IDP dex auth parameter for user authentication.
You shared that where is the external IDP config there..?

**Comment by micemuni** [comment]
@jbottum  Also can you please let me know that  at 1st login it's automatically asking to create profile/namespace for each/every new users. is there any possible to my organization LDAP user..?  and kubeflow should create profile/namespace accordingly.
