### ISSUE TITLE
istio-dex and authentication/authorization tokens

### ISSUE THREAD

**Issue by lomori** [kubeflow/kubeflow#5345]
/kind question

**Question:**
In order to programmatically make API calls, e.g., Seldon predictions, some sort of authentication/authorization token is required. What is the best way to acquire such token through code? I found this https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex, which describes a series of curl commands that can easily be implemented as code but really, that seems like a hack for my purposes. My authentication backend is LDAP.

Regards,
Luiz

**Comment by ConverJens** [comment]
I need this as well.

**Comment by ConverJens** [comment]
@lomori Shamelessly copied from the [Elyra-AI project](https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_kfp.py), this works great for me (kfp>=1.0.0):

`endpoint = api_endpoint.replace('/pipeline', '')
session_cookie = get_user_auth_session_cookie(endpoint, api_username, api_password)
client = kfp.Client(host=api_endpoint, cookies=session_cookie)

def get_user_auth_session_cookie(url, username, password):
    get_response = requests.get(url)

    # auth request to kfp server with istio dex look like '/dex/auth/local?req=REQ_VALUE'
    if 'auth' in get_response.url:
        credentials = {'login': username, 'password': password}

        # Authenticate user
        session = requests.Session()
        session.post(get_response.url, data=credentials)
        cookie_auth_key = 'authservice_session'
        cookie_auth_value = session.cookies.get(cookie_auth_key)

        if cookie_auth_value:
            return cookie_auth_key + '=' + cookie_auth_value`

**Comment by lomori** [comment]
Thanks @ConverJens . How many Dex connectors your have? The behaviour may change if you have just one or more than one.

In any case, that is still the UI process but using code, i.e., you are emulating an user entering username and password behind the scenes. This process is meant for an interactive user session. It works, but I guess what I'm really looking for is something like OIDC/OAuth2, preferably, or SAML based protocols. Actually, I was surprised that it doesn't seem to be there. After all, I would imagine that for a lot of use cases, API calling will not originate from UIs. Prediction and Explanation APIs are good examples.

**Comment by ConverJens** [comment]
@lomori We currently only use the static pwd file but will soon connect to our LDAP. Our main use case was to automate uploading pipelines from our build flow as well as querying KFP API from local IDEs.

**Comment by lomori** [comment]
@ConverJens Cool! I didn't look deep into it, but as far as I recall, the problem for me was that when you change from a single authenticator to multiple, Dex UI displayed an intermediate screen allowing the user to select the authentication mode first, e.g. LDAP versus email, before sending the user to the screen for entering username and password. My original code freaked out about it, but it was an easy fix. Nevertheless, this highlights the fundamental issue: this is not a stable protocol. This whole thing is extremely fragile, depending a lot on whims of some UI guy from Dex. This guy, let's call him Ted, is going to wake up one morning and decide to change the UI just for the sake of it, like renaming the username field to user. Ted's and his mom will be well regarded after that, and will be well deserved (Ted, not his mom...) for not providing us with a robust programmatic protocol.

**Comment by ConverJens** [comment]
@lomori That sounds like a nasty surpise, I hope thats not the case! I will post here once we switch to using LDAP if this is indeed an issue.

**Comment by ConverJens** [comment]
@lomori I just ran into this when finally adding LDAP to our login. May I ask how you obtain cookies for authenticating?

I've beens using code from the Elyra project (which now fails):

```
get_response = requests.get(url)

    # auth request to kfp server with istio dex look like '/dex/auth/local?req=REQ_VALUE'
    if 'auth' in get_response.url:
        credentials = {'login': username, 'password': password}

        # Authenticate user
        session = requests.Session()
        session.post(get_response.url, data=credentials)
        cookie_auth_key = 'authservice_session'
        cookie_auth_value = session.cookies.get(cookie_auth_key)

        if cookie_auth_value:
            return cookie_auth_key + '=' + cookie_auth_value
```

A pointer would be appreciated :)

**Comment by lomori** [comment]
Oh, sorry @ConverJens ! I haven't been here for a while. Not sure where my test code is anymore. We haven't proceeded further with this feature in our project.

**Comment by ConverJens** [comment]
@lomori Don't worry, se solved this months ago🙂

**Comment by 631068264** [comment]
@ConverJens What? how to do
