### ISSUE TITLE
Kubeflow + Dex authentication service account creation via Profile controller

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/kubeflow#5346]
/kind feature

**Why you need this feature:**

Currently authentication seems to be an issue with Kubeflow especially using Dex + OIDC, we've been using a method with this setup internally and wanted to share the details here. 

With Dex we are leveraging the [grpc-client](https://github.com/dexidp/dex/tree/master/examples/grpc-client) to create static accounts for each Profile, as part of an orchestrated Profile creation, which is part of the multi-tenant approach. 

So each Profile's namespace gets a secret with the password for the Dex "service account",  the user can then use this service account to authenticate with Dex via API calls, and use the cookie of this session to authenticate with the KFP SDK as well as KFServing. 

See example KFP usage: 

```
from dex.utils import DexAuth
# Service account details
email = f'{namespace}'
password = 'secret' # In the future this will be os.environ.get("SA_PASSWORD")

# Get the authentified session using Dex utils
cookies = DexAuth().get_user_token(
    host=host,
    email=email,
    password=password
)
# Run the pipeline on Kubeflow cluster
pipeline_run = (
    kfp
    .Client(host=f'{host}/pipeline', cookies=cookies)
    .create_run_from_pipeline_func(
        pipeline,
        arguments={},
        experiment_name=experiment_name,
        namespace=namespace,
        run_name=pipeline_name
    )
)
```

Or KFServing usage: 

```
import requests
url = f'{host}/v1/models/spamsms-sklearn:predict'
service_hostname = f'spamsms-sklearn-predictor-default.{namespace}.example.com' 

# Drop the label column before sending data to API
payload = {"instances": ["You won 100 dollars! call us now!", "Text your mom after school"]}

headers = {
   'host': service_hostname,
   'cookie': cookies
}

response = requests.post(url, headers=headers, json=payload, verify=False)
response.json()
```

**Proposal**

While we've been doing this as part of a GitOps driven profile creation, this approach would be much easier if done from one of the controllers that creates and updates the Profile's namespace, this would also streamline the deployment in other platforms. 

There is of course other identity management solutions such as KeyCloak which seems to have more native ways of securing applications but I have not fully explored those options.

**Comment by jbottum** [comment]
@yanniszark Hey Yannis, any comments here?

**Comment by jdonnelly-apixio** [comment]
Thanks for the snippets @maganaluis.
