### ISSUE TITLE
What is the program listening at localhost:8083?

### ISSUE THREAD

**Issue by LuChengTHU** [kubeflow/kubeflow#5347]
/kind question

**Question:**
In components/centraldashboard/webpack.config.js, the devServer proxies '/jupyter' to 'http://localhost:8083/api/v1/namespaces/kubeflow/services/jupyter-web-app-service:80/proxy'. However, I can't find the program which listens 8083. So what is it and where is the code?

**Comment by DavidSpek** [comment]
@LuChengTHU Can this issue be closed given the above PR was merged?
