### ISSUE TITLE
Support Kubeflow on Kubernetes 1.18+

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5349]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Kubeflow has not been tested in 1.18. Let's try to resolve all the issues on 1.18 and make it v1.1 compatible.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

Find API breaking changes and upgrade components

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DavidSpek** [comment]
@Jeffwan 
For kubernetes 1.18.6 and 1.19, please see my [comment](https://github.com/kubeflow/website/issues/2206#issuecomment-698234904) that describes the fix to an issue related to deploying seldon. 

I submitted a [PR](https://github.com/kubeflow/manifests/pull/1558) to fix this issue on September 16th, but have not had any response as of yet. There seem to be quite a few people that are now grabbing the manifests from my repository to workaround this issue which seems not optimal to say the least.

**Comment by Jeffwan** [comment]
@DavidSpek Thanks. I can track this and get connect to the right person to review it

**Comment by DavidSpek** [comment]
@Jeffwan As I mentioned in the PR discussion, I'm not sure if the change in the manifests is still needed if Seldon is updated. Also, I'm not sure if this applies to 1.18.6 seeing as I didn't encounter the issue with earlier versions of 1.18.x but it showed up at the same time with the above issue after moving to 1.19, this issue for which a fix has since been released might also be useful to take a look at. https://github.com/kubeflow/pipelines/issues/4505

**Comment by DavidSpek** [comment]
@Jeffwan The linked issue is not due to Kubernetes 1.19. I am now running 1.20 and have not found issues with my use. I have raised the issue that more versions of Kubernetes should be validated here: https://github.com/kubeflow/website/pull/2451.

**Comment by denkensk** [comment]
@Jeffwan  @DavidSpek
What's the progress of making 1.18 compatible in v1.1 or v1.2 ？

**Comment by DavidSpek** [comment]
@denkensk To my knowledge nothing in 1.2 is incompatible with k8s 1.18. Also, release 1.3 is very near so if there were problems these would hopefully be solved.

**Comment by denkensk** [comment]
@DavidSpek  Thanks for your quick reply. 
If nothing in Kubeflow 1.2 is incompatible with k8s 1.18 or 1.19，Can we update the doc to set it compatible in 1.18 or 1.19 in https://github.com/kubeflow/website/blob/master/content/en/docs/started/k8s/overview.md ?

**Comment by denkensk** [comment]
/cc @jlewi 
Is there a process to validate Kubeflow for a given version like 1.18 and 1.19? 
It may be helpful for us to check if we can set k8s 1.18 and 1.19 compatible in Kubeflow v1.2.

**Comment by Jeffwan** [comment]
@denkensk 

It depends, since different provider/platform have their own addons. It's hard to give a general answer now.  This definitely needs to be reformed.

**Comment by DavidSpek** [comment]
@Jeffwan I think what could be implemented is have each Working Group give lower and upper limits of Kubernetes compatibility for the components they manage. To ensure the Working Groups stay active in supporting new versions of Kubernetes they would also need to provide reason why they currently can't support the latest version and how these will be solved. This will also give users a clear view what might be broken on new Kubernetes versions (maybe they don't use the component that component), as well as inform them how they can help contribute to support the latest platform.

**Comment by Jeffwan** [comment]
> @Jeffwan I think what could be implemented is have each Working Group give lower and upper limits of Kubernetes compatibility for the components they manage. To ensure the Working Groups stay active in supporting new versions of Kubernetes they would also need to provide reason why they currently can't support the latest version and how these will be solved. This will also give users a clear view what might be broken on new Kubernetes versions (maybe they don't use the component that component), as well as inform them how they can help contribute to support the latest platform.

totally agree.  Besides extra addons platform own,  wg-manifest may like to expose some details as well, @kubeflow/wg-manifests-leads  owns core kubeflow components.
