### ISSUE TITLE
TF MPI support 

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#535]
Filing on behalf of Kai Zhang from Alibaba @wsxiaozhang -
we are looking at running tensorflow in MPI way, like horovod. in that case, there won't be PS role. Is there any plan kubeflow to support MPI?

**Comment by aronchick** [comment]
We've heard both about MPI and Horovod - any chance you'd like to do a proposal?

**Comment by bhack** [comment]
It could be nice to have an high level api example. But something need to be fixed in TF upstream.

See https://github.com/uber/horovod/issues/182

**Comment by alsrgv** [comment]
We'd love to contribute MPI / Horovod support to Kubeflow.

At Uber, we use scheduler similar to Google Borg to do a gang scheduling of containers.  In those containers, there are two roles - container 0 and other containers.  Container 0 will wait for other container to come online and will execute `mpirun` which runs jobs on the whole job's cluster via `ssh`.  Other containers simply run `sshd` and sleep until container 0 exits.

What's the best way to replicate this functionality in Kubernetes / Kubeflow?

cc @jiezhang, @aronchick

**Comment by inc0** [comment]
Count me in as well!

I'd say run container with ssh in a pod from image that has your code in it (or mount code otherwise). You could create pubkey configmap and mount it to client containers and have master container mounting secret private key - keypairs could be generated on jobset generation or pre-defined.
You can use statefulset for predictible hosntames of pods (each pod is a resolvable hostname within kubedns).

**Comment by alsrgv** [comment]
Right, these are two important points.

1) We do generate new public/private key for every job and make it available to the containers securely.

2) We do dynamically resolve ips/ports of all the job workers and create `ssh_config` with the mapping of `worker_N` to correct ip/port.

**Comment by inc0** [comment]
> We do dynamically resolve ips/ports of all the job workers and create ssh_config with the mapping of worker_N to correct ip/port.

That can be dealt with via DNS and statefulset (which allows predictible hostnames). I suggest something like this:

1. Generate keypair per jobset to limit security exposure. Save private key to secret and pubkey to configmap
2. Create configmap with hostnames that will be used later (let's say trainer)
3. Create statefulset named (for example) trainer-[0-5] where trainer-0 will be our master and 1-5 nodes. Trainer-0 will be guaranteed to start first thanks to statefulset.
4. Mount configmap so trainer-0 will know where to look for other trainers
5. Mount private key to ~/.ssh/id_rsa and pubket to ~/.ssh/authorized_keys
6. trainer-0 will wait for trainers 1-5 to start listening over ssh
7. start MPI magic

Does that looks good to you?

**Comment by alsrgv** [comment]
@inc0, that sounds great. What changes would need to be done to Kubeflow to make this workflow happen?

**Comment by jiezhang** [comment]
@jlewi @inc0 @fxue @alsrgv Please take a look at #624
