### ISSUE TITLE
Installation error on minikube.

### ISSUE THREAD

**Issue by zzha2941** [kubeflow/kubeflow#5350]
/kind bug

**What steps did you take and what happened:**

[https://www.kubeflow.org/docs/started/workstation/minikube-linux/](url)
I followed the above docs to install kubeflow on minikube and I met following error:

Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout250943945": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:266"

It seems to be a duplicate of #5230 

Then I tried to uninstall cert-manager according to the followed docs:

[https://cert-manager.io/docs/installation/uninstall/kubernetes/](url)

After uninstall, the pods information is like this:

NAMESPACE      NAME                                                                     READY   STATUS              RESTARTS   AGE
istio-system   cluster-local-gateway-5898bc5c74-7qrb6                        0/1     Running                       4          5d16h
istio-system   istio-citadel-6dffd79d7-cb9b8                                           0/1     ImagePullBackOff       0          5d16h
istio-system   istio-galley-77cb9b44dc-bn9dm                                       0/1     ContainerCreating       0          5d16h
istio-system   istio-ingressgateway-7bb77f89b8-gdbv6                         0/1     ContainerCreating       0          5d16h
istio-system   istio-nodeagent-n2gvq                                                     0/1     ImagePullBackOff        0          5d16h
istio-system   istio-pilot-67d94fc954-2pvzc                                            0/2     ContainerCreating       0          5d16h
istio-system   istio-policy-546596d4b4-42q7v                                        0/2     ContainerCreating       0          5d16h
istio-system   istio-security-post-install-release-1.3-latest-daily-gjjww   0/1     ErrImagePull               0          5d16h
istio-system   istio-sidecar-injector-796b6454d9-56476                         0/1     ContainerCreating      0          5d16h
istio-system   istio-telemetry-58f9cd4bf5-mx58h                                    0/2     ContainerCreating      0          5d16h
istio-system   prometheus-7c6d764c48-bv46j                                        0/1     ContainerCreating      0          5d16h
kube-system    coredns-f9fd979d6-grwwc                                              1/1     Running                      5          5d17h
kube-system    etcd-minikube                                                                 1/1     Running                      5          5d17h
kube-system    kube-apiserver-minikube                                                1/1     Running                      5          5d17h
kube-system    kube-controller-manager-minikube                                 1/1     Running                      5          5d17h
kube-system    kube-proxy-xnqcn                                                           1/1     Running                      5          5d17h
kube-system    kube-scheduler-minikube                                                1/1     Running                     5           5d17h
kube-system    storage-provisioner                                                         1/1     Running                      9          5d17h
kubeflow       application-controller-stateful-set-0                                    0/1     ImagePullBackOff      0           5d16h

But when I tried to install kubeflow again, I met the same error above, and new pods information is like the following:

NAMESPACE      NAME                                                                    READY   STATUS              RESTARTS   AGE
cert-manager   cert-manager-7c75b559c4-g687n                                 1/1     Running                          0          70s
cert-manager   cert-manager-cainjector-7f964fd7b5-8scf7                    1/1     Running                         0          70s
cert-manager   cert-manager-webhook-566dd99d6-7wkcp                   0/1     ContainerCreating          0          70s
istio-system   cluster-local-gateway-5898bc5c74-7qrb6                        0/1     Running                          4          5d17h
istio-system   istio-citadel-6dffd79d7-cb9b8                                           0/1     ImagePullBackOff          0          5d17h
istio-system   istio-galley-77cb9b44dc-bn9dm                                       0/1     ContainerCreating          0          5d17h
istio-system   istio-ingressgateway-7bb77f89b8-gdbv6                         0/1     ContainerCreating          0          5d17h
istio-system   istio-nodeagent-n2gvq                                                     0/1     ImagePullBackOff           0          5d17h
istio-system   istio-pilot-67d94fc954-2pvzc                                            0/2     ContainerCreating           0          5d17h
istio-system   istio-policy-546596d4b4-42q7v                                        0/2     ContainerCreating           0          5d17h
istio-system   istio-security-post-install-release-1.3-latest-daily-gjjww   0/1     ImagePullBackOff           0          5d17h
istio-system   istio-sidecar-injector-796b6454d9-56476                         0/1     ContainerCreating          0          5d17h
istio-system   istio-telemetry-58f9cd4bf5-mx58h                                    0/2     ContainerCreating          0          5d17h
istio-system   prometheus-7c6d764c48-bv46j                                        0/1     ContainerCreating          0          5d17h
kube-system    coredns-f9fd979d6-grwwc                                              1/1     Running                         5          5d17h
kube-system    etcd-minikube                                                                 1/1     Running                         5          5d17h
kube-system    kube-apiserver-minikube                                                1/1     Running                         5          5d17h
kube-system    kube-controller-manager-minikube                                 1/1     Running                        5          5d17h
kube-system    kube-proxy-xnqcn                                                           1/1     Running                        5          5d17h
kube-system    kube-scheduler-minikube                                                1/1     Running                        5          5d17h
kube-system    storage-provisioner                                                          1/1     Running                       9          5d17h
kubeflow       application-controller-stateful-set-0                                     0/1     ImagePullBackOff         0          5d17h

Did I make a mistake in uninstalling cert-manager? I am a freshman in Kubernetes, thanks for any kind help. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: kfctl_v1.1.0-0-g9a3621e
- Kubernetes platform: minikube
- Kubernetes version: client: v1.20.0-alpha.2, server: v1.19.2
- OS ubuntu 20.04

**Comment by jbottum** [comment]
@zzha2941 thanks for reporting.   it will get routed.   If you need to try something quickly that works, you might try MiniKF. https://www.arrikto.com/f/get-minikf/

**Comment by zzha2941** [comment]
@jbottum Thank you! I will try it.

**Comment by jizg** [comment]
kubernetes v1.19 is still not fully tested with Kubeflow 1.1, so you'd better to use kubernetes below v1.18 now. Have a look at https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements
