### ISSUE TITLE
experiment can not be deleted

### ISSUE THREAD

**Issue by chongchuanbing** [kubeflow/kubeflow#5352]
/kind bug

**What steps did you take and what happened:**
1. kubectl get experiment --all-namespaces
```
NAMESPACE   NAME                 STATUS      AGE
kubeflow    bay                  Succeeded   39d
kubeflow    grid                 Succeeded   39d
kubeflow    random-experiment    Succeeded   39d
kubeflow    random-experiment1   Succeeded   37d
kubeflow    random-experiment2   Succeeded   26d
kubeflow    random-experiment3   Succeeded   26d
```
2. kubectl delete Experiment bay -n kubeflow
    the command can not finish. Running always.

**What did you expect to happen:**

i want delete the experiment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.6
- kfctl version: (use `kfctl version`):
- Kubernetes platform: linux/amd64
- Kubernetes version: v1.15.12
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
Hi @chongchuanbing!
Can you check logs from the Katib controller ?
Are you using Profile namespace to submit Experiments ?

Can you check if Trials were deleted:
`kubectl get Trials -n kubeflow`

**Comment by jbottum** [comment]
Hi @chongchuanbing, did you get this resolved?  Do you expect to upgrade to a newer version of Kubeflow at some point ?
