### ISSUE TITLE
Error Kale Compile and Run on GC

### ISSUE THREAD

**Issue by Gross613** [kubeflow/kubeflow#5356]
/kind bug
Gateway Client Error

**What steps did you take and what happened:**
I clicked the blue compile button on the bottom of the kale Deployment Panel and the above screen shot error occurred.
<img width="1177" alt="Screen Shot 2020-10-22 at 11 00 05 AM" src="https://user-images.githubusercontent.com/10426210/96890971-32fb3900-1456-11eb-96bc-8a21d38b7ae8.png">

Funcation Call: rok.snapshot_bnotebook()
Status: 2 (ExecutionError)
Type: "GatewayClientError"
Message 401 (Unauthorized Error for 'GET http://rok.rok.svc.cluster.local/servoes/setting'. API Error unauthorized code: 401, msg: Unauthoirzed, details: This server could not verify that you are authorized to access the document you requested

**What did you expect to happen:**
I expected Kale to compile & run.

**Anything else you would like to add:**
NA

**Environment:**
Used MiniKF on Google Cloud

**Comment by elikatsis** [comment]
Hi @Gross613,
thank you for trying out MiniKF and Kale!

Could you give some more information on the MiniKF version and the Kale image you are using?

From the looks, I'd say you are using an old notebook image (could it be the one with the `kubecon-workshop` tag?) with a new MiniKF.
Can you try with the latest MiniKF and the `jupyter-kale` image found in the list of images of Notebooks UI?

Also, for future issues, you can open them in the Kale repo: https://github.com/kubeflow-kale/kale

**Comment by jbottum** [comment]
Hi @Gross613, Did you get this issue resolved by selecting the new notebook image ?

**Comment by DavidSpek** [comment]
Can this issue be closed, given that it is a Kale issue and hasn't active?
