### ISSUE TITLE
Profile controller new admin sync

### ISSUE THREAD

**Issue by subodh101** [kubeflow/kubeflow#5357]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

On patching new admin(email) with a current existing profile it doesn't get updated in the rolebinding `namespaceAdmin`.
If we delete the profile then it will delete the namespace, which results in the deletion of all the kubernetes kind's in the namespace.

**What did you expect to happen:**

rolebinding `namespaceAdmin` gets patched with the new admin automatically by the profile controller.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Could be just a missing feature between `profile` and rolebinding `namespaceAdmin`.

I don't think manual patching is the right way to resolve this issue. This needs to be handled by the controller. If there is any other way to achieve this without deleting the namespace. Please let me know.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- kfctl version: (use `kfctl version`): N/A, used kubectl and kpt to deploy. 
- Kubernetes platform: (e.g. `minikube`) GCP
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): darwin/amd64

**Comment by Jeffwan** [comment]
That's probably a bug that didn't handle update event well in the controller. 

/bug
