### ISSUE TITLE
reason for one master replica pod

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#536]
Filing on behalf of Kai Zhang from Alibaba @wsxiaozhang -
in tf-job, there must have 1 and only 1 master. I still don't quite understand why there must be one master replica pod explicitly deployed. In tensorflow, I can just assign the local tf server target as the master for worker process.

**Comment by jlewi** [comment]
This matches the conventions used in TF.

The meaning of the master/chief (two terms that mean the same thing)  is monitor this process and when it exits infer that the job is done.

So its not clear what the user intent would be of having N masters. So we don't allow it.
