### ISSUE TITLE
Community presentation for 1.2

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5361]
We aim to release kubeflow 1.2 in mid of Nov. It would be good to start defining a release notes and scripts to help make sure everyone is on the same page. 

Here's the link for 1.1 roadmap and I don't think we have similar one for 1.2.  We spend most our time on some discussions like governance, distribution and testing, etc since 1.1.  

[KF Roadmap for 1.1](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md#kubeflow-11-features-target-release-late-june-2020)

Seem jupyter webapp will have a big refactor and other components don't have that many features going in. Due to this, we might concentrate on improvement and bug fix for this release.

**Comment by Jeffwan** [comment]
Josh create deck here https://docs.google.com/presentation/d/1_PxXWuy_TKEZyuPGZQZ1fBHMAupM3rBPZQow98L0iCY/edit?ts=5fa05fd4#slide=id.g8f86ec6f96_0_76

**Comment by PatrickXYS** [comment]
I don't think community folks have enough cycles on this, should we close and keep moving?

**Comment by DavidSpek** [comment]
Since Kubeflow 1.2 has been released, can this be closed?

**Comment by jbottum** [comment]
@PatrickXYS I have a Kubeflow 1.2 in draft form.   I have been waiting for the docs to be updated.

**Comment by PatrickXYS** [comment]
@jbottum That's great! Look forward to your 1.2 presentation

/reopen

**Comment by jbottum** [comment]
@PatrickXYS I propose that since we are getting close to 1.3, we should close this issue and focus on materials for 1.3.

**Comment by PatrickXYS** [comment]
@jbottum That sounds good to me, since we're approaching to 1.3, let's focus on 1.3 then

/close
