### ISSUE TITLE
Could not find command aws-iam-authenticator in PATH

### ISSUE THREAD

**Issue by dalbhanj** [kubeflow/kubeflow#5364]
/kind bug

**What steps did you take and what happened:**
Installing Kubeflow on EKS throws this error

```
Error: failed to build kfApp from URI /home/ec2-user/environment/eksworkshop-eksctl/kfctl_aws.yaml: KfApp initiliazation failed:  (kubeflow.error): Code 500 with message: coordinator Init failed for aws:  (kubeflow.error): Code 400 with message: Could not find command aws-iam-authenticator in PATH
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                                        export CONFIG=./kfctl_gcp_iap.yaml
                                or a URL:
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                                kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to build kfApp from URI /home/ec2-user/environment/eksworkshop-eksctl/kfctl_aws.yaml: KfApp initiliazation failed:  (kubeflow.error): Code 500 with message: coordinator Init failed for aws:  (kubeflow.error): Code 400 with message: Could not find command aws-iam-authenticator in PATH
```

**What did you expect to happen:**
Looks like installing Kubeflow on EKS requires aws-iam-authenticator? I thought this was fixed in v1.0 feature release
https://github.com/kubeflow/kubeflow/issues/3827

**Anything else you would like to add:**
The original issue that was created has gone stale https://github.com/kubeflow/kubeflow/issues/3827

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.1.0
- kfctl version: (use `kfctl version`): v1.1.0
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): v1.18.8
- OS (e.g. from `/etc/os-release`): Linux (Cloud9)

**Comment by CandiedCode** [comment]
What ami's are you eks cluster using?  I thought aws-iam-authenticator was automatically part of the eks ami's.

https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L164

**Comment by PatrickXYS** [comment]
@dalbhanj  I don't think this is an issue anymore, we have enabled periodic tests and 1.18 is working fine. 

Let me know if you still have issue

/close
