### ISSUE TITLE
cp: cannot stat '../kubeflow': No such file or directory

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [kubeflow/kubeflow#5366]
I try to build it, but get the above error message. In the sub-directory 'bootstrap' I execute 'sudo sh ./build_image.sh'. 

environment: x86-64, CentOS 8 
current master, also branch v1.0

**Comment by jlewi** [comment]
Please follow the directions on www.kubeflow.org if you are trying to install Kubeflow.

**Comment by LutzWeischerFujitsu** [comment]
Dear Jeremy! Would you be so kind to provide the exact URL to the description for building this open source project, I couldn't manage to find it. I think it is a promising project. Thanks a lot.
