### ISSUE TITLE
Poddefault does not work in Kubeflow v1.1

### ISSUE THREAD

**Issue by knave07** [kubeflow/kubeflow#5369]
/kind bug

**What steps did you take and what happened:**
I am running `Kubeflow v1.1` on GKE. I created a Poddefault to inject `X` environment var in Jupyter. Spun Up a Jupyter Notebook with `configurations` set to Poddefault and tried to access the Env Var but the environment var was not present in the pod. 

Did the same thing on `Kubeflow  v1.0` and now that environment var is accessible.

- **Env Var is Present in `Kubeflow v1.0`**:
![Screen Shot 2020-10-29 at 17 53 36](https://user-images.githubusercontent.com/37116431/97549072-4a689200-1a13-11eb-9e1c-3d56269afb2e.png)

- **Env var mentioned in Poddefault is not present in `Kubeflow v1.1`**:
![Screen Shot 2020-10-29 at 17 53 24](https://user-images.githubusercontent.com/37116431/97549079-4ccaec00-1a13-11eb-84ff-c96e18bcd528.png)

**What did you expect to happen:**

Env Vars should have been created. 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): `build version v1beta1`
- kfctl version: (use `kfctl version`): v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`)  For  Kubeflow v1.1 : `GKE(1.16.13-gke.401)` , For Kubeflow v1.0: `GKE(1.14.10-gke.1504)`
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): Mac OS

**Comment by solarist** [comment]
Same problem with an on-prem installation.

**Comment by CSberger** [comment]
What do
```kubectl get MutatingWebhookConfiguration admission-webhook-mutating-webhook-configuration -o jsonpath='{@.webhooks[0].namespaceSelector}'```

```kubectl -n kubeflow logs -l=app=admission-webhook -f```

and ```kubectl describe ns test-aman``` look like?

**Comment by farzinsarvaramini** [comment]
Same issue with on-prem installation. @CSberger I didn't find any relevant information from those logs.

**Comment by solarist** [comment]
@CSberger The annotation wasn't present in my namespace by default, but also setting it manually didn't help.
```
$ kubectl get MutatingWebhookConfiguration admission-webhook-mutating-webhook-configuration -o jsonpath='{@.webhooks[0].namespaceSelector}'
map[matchLabels:map[app.kubernetes.io/part-of:kubeflow-profile]]
$ kubectl get ns user-namespace -o jsonpath='{.metadata.annotations.app\.kubernetes\.io/part-of}'
kubeflow-profile
```

**Comment by farzinsarvaramini** [comment]
@solarist 
https://github.com/kubeflow/kubeflow/issues/5207#issuecomment-702341351 solved my problem.

**Comment by knave07** [comment]
It worked. Thanks @farzinsarvaramini. It was not working initially, but after recreating profile I could see the env vars.
