### ISSUE TITLE
Is there a way to restric pipelines to run on a specific per-user/per-project namespace?

### ISSUE THREAD

**Issue by supertetelman** [kubeflow/kubeflow#5372]
/kind question

**Question:**
When I launch a Jupyter notebook I can select the namespace it is deployed into. Typically this is the namespace associated with my user and any quota restrictions/access rights that come with that namespace are associated with the Jupyter Pod.

When I kick off an experiment run through the pipelines interface it defaults to running in the `kubeflow` namespace and there is no clear way for me to restrict this to a namespace of my choosing. I believe this might be something I can do through the SDK, but certainly not through the GUI.

My question is mostly focused on on-prem deployments with a higher level of multi-tenancy and a rather large cluster.

Is there a custom way to set this up so a user can only run pipelines in their own namespace?

**Comment by Jeffwan** [comment]
@supertetelman  Can you raise your question in [kubeflow/pipelines](https://github.com/kubeflow/pipelines) project? 

/cc @Bobgy @numerology   @james-jwu

**Comment by Bobgy** [comment]
Please install kubeflow 1.1 and your desired behavior will be the default.

https://www.kubeflow.org/docs/pipelines/multi-user/

**Comment by supertetelman** [comment]
Okay, I'm using that version and just tried running through that doc and it is still failing.

I'm using the SDK with a pipeline that creates a few volumes through ResourceOps, so maybe I'm hitting a bug. I'll takes this over to the pipelines repo. (https://github.com/supertetelman/deepops/blob/kubeflow-mpi/workloads/examples/k8s/kubeflow-mpi/multinode-pipeline.ipynb)

**Comment by supertetelman** [comment]
Just to follow up this was a bug/lack of implementation with the on-prem kubeflow deployments. Tracking information here: https://github.com/kubeflow/pipelines/issues/4746

**Comment by Bobgy** [comment]
@supertetelman how did you install Kubeflow? I think your installation didn't use multi-user mode
