### ISSUE TITLE
Cannot receive any reply from jupyter-web-app-service.kubeflow.svc.cluster.local:30400 in 120 seconds.

### ISSUE THREAD

**Issue by hellodk** [kubeflow/kubeflow#5375]
/kind bug

**What steps did you take and what happened:**
Hello,

I'm trying to run a spark job using Kubeflow Notbook Server(Jupyter with custom image), however I end up with the below exception

Caused by: java.util.concurrent.TimeoutException: Cannot receive any reply from jupyter-web-app-service.kubeflow.svc.cluster.local:30400 in 120 seconds.

When I try to do the same via a separate Jupyter Notebook deployed in the same namespace, but outside of the Kubeflow environment my Spark executor pods get created and complete the job, when I try to use the Kubeflow Jupyter Notebook for running the same notebook, it fails with the error that the spark executor is not able to communicate with the spark driver.

Any leads or am I doing something wrong?

**Environment:**
EKS
- Kubeflow version: v1beta1
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: EKS
- Kubernetes version: Major:"1", Minor:"17+" 
- OS (e.g. from `/etc/os-release`): Amazon AMI

**Comment by jlewi** [comment]
> it fails with the error that the spark executor is not able to communicate with the spark driver.

Can you please provide more detail and explain why you think this is an issue with Kubeflow Jupyter as opposed to with your spark configuration?

**Comment by hellodk** [comment]
While using custom images for Notebook servers and Kubeflow creates a basic service in the user namespace which causes this issue.

I've fixed it for me by creating another headless service in the same namespace.

apiVersion: v1
kind: Service
metadata:
  namespace: admin
  name: v18-headless
spec:
  selector:
    statefulset: v18
  sessionAffinity: None    
  ports:
    - name: http-pyspark
      port: 30920
      protocol: TCP
      targetPort: 8888
  clusterIP: None

Cheers,
Deepak
