### ISSUE TITLE
Github Onboarding experience 

### ISSUE THREAD

**Issue by naveensrinivasan** [kubeflow/kubeflow#5376]
/kind bug

**What steps did you take and what happened:**
The GitHub onboarding experience is not very conducive.  I was trying to submit a PR and for a fix within the notebook controllers and wasn't clear as to what are the necessary things that are required.

**What did you expect to happen:**
- Examples of things that would be helpful are 
- `go` version 
- `k8s` version
- `istio` version 
-  How to run tests? 
-  How to debug tests?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is similar to https://github.com/kubeflow/kubeflow/issues/2741

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by naveensrinivasan** [comment]
opened a  PR specific to  notebook controller https://github.com/kubeflow/kubeflow/pull/5383

**Comment by PatrickXYS** [comment]
@naveensrinivasan  Thanks for heads up, we need to improve contributor guidance as well. 

Given we have limited engineering resources in community, would be great if you can contribute to different repos.
