### ISSUE TITLE
kfam/v1/bindings taking over 8 seconds

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/kubeflow#5377]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We have a cluster with over 180 Profiles, some of them are QA bots which should be deleted but at any case we observed high latency in the UI for both Kubeflow Central Dashboard and Kubeflow Pipelines UI. We traced this back to the KFAM endpoint that obtains the bindings for a specific user. 

The code seems to be making calls to the Kubeflow API to get the rolebingings for every namespace, rather than getting the rolebindings for the whole cluster in a single call. 

```
$ ~/GitHubRepos/kubeflow-kubeflow/components/access-management$ docker run -v /Users/<user>/.kube/:/root/.kube/ -p 8081:8081 kfam-profiles  
time="2020-11-03T15:11:34Z" level=info msg="Server started"
2020/11/03 15:11:44 http: superfluous response.WriteHeader call from github.com/kubeflow/kubeflow/components/access-management/kfam.(*KfamV1Alpha1Client).ReadBinding (api_default.go:241)
2020/11/03 15:11:44 GET /kfam/v1/bindings?user=<email> ReadBinding 8.0413352s
```

We will correct the code locally, and make a PR once it has been tested. At any case feel free to suggest a solution. 

**Environment:**

- Kubeflow version: 1.1
- kfctl version: (use `kfctl version`): N/A
- Kubernetes platform: Azure
- Kubernetes version:  1.16.X

**Comment by Jeffwan** [comment]
@maganaluis  Thanks. That would be great!  It you can make it by end of week, we can push to 1.2 release

**Comment by maganaluis** [comment]
Based on the Slack discussion Kubeflow will be moving away from KFam and will implement Authz using SubjectAccessReview, thus this issue should be resolved then. 

https://github.com/kubeflow/pipelines/pull/4723
