### ISSUE TITLE
Kubeflow Installation Problem

### ISSUE THREAD

**Issue by bobmerevel** [kubeflow/kubeflow#5380]
/kind question

**Question:**
Hi,

I am new on kubeflow. I want to install kubeflow on existing k8s cluster. But when i follow installation guide at kubeflow web page,  i get following error. I try lots of things to solve this issue, but i can not install :( Is there anybody who has idea to solve this issue? 

**Cluster Version**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**My Cluster**
NAME                      STATUS   ROLES    AGE    VERSION
k8s-master.xx.local   Ready    master   20d    v1.19.2
k8s-wrk1.xx.local     Ready    <none>   20d    v1.19.2
k8s-wrk2.xx.local     Ready    <none>   20d    v1.19.2
k8s-wrk3.xx.local     Ready    <none>   20d    v1.19.2
k8s-wrk4.xx.local     Ready    <none>   2d1h   v1.19.3

**Installation Logs**

validatingwebhookconfiguration.admissionregistration.k8s.io/seldon-validating-webhook-configuration-kubeflow configured
WARN[0015] Encountered error applying application kubeflow-apps:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout235194845": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]  filename="kustomize/kustomize.go:266"
WARN[0015] Will retry in 3 seconds.                      filename="kustomize/kustomize.go:267"

**Comment by alokumar1** [comment]
I am also facing the same issue. Any solution?

`WARN[0299] Encountered error applying application kubeflow-apps:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout680700965": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]  filename="kustomize/kustomize.go:266"
WARN[0299] Will retry in 38 seconds.                     filename="kustomize/kustomize.go:267"`

**Comment by bobmerevel** [comment]
I thing this issue is related k8s version 1.19. When i downgrade my cluster 1.16, i can setup kubeflow.

**Comment by aeoluswing** [comment]
This issue might be the compatibility issue between kubeflow and k8s,it's better to try this case in k8s version 1.16.Look around [version compatibility document](https://www.kubeflow.org/docs/started/k8s/overview/)

**Comment by PatrickXYS** [comment]
The issue is fixed in terms of 1.2 Kubeflow release
