### ISSUE TITLE
Error: NetworkPluginNotReady. cni config uninitialized

### ISSUE THREAD

**Issue by tretos53** [kubeflow/kubeflow#5381]
/kind bug

**What steps did you take and what happened:**
- I installed kubeflow using this yaml file: `https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws_cognito.v1.1.0.yaml`
- After installation it worked fine.
- Yesterday evening I set Auto Scaling Groups to zero.
- This morning I set Auto Scaling Groups to 4.
- `kubectl get nodes` reports nodes as `NotReady`

I logged this with AWS here https://github.com/aws/amazon-vpc-cni-k8s/issues/1278 but when I saw this issue https://github.com/kubeflow/kubeflow/issues/5247 I thought this might be something to do with Kubeflow.

**What did you expect to happen:** Nodes to be Ready

**Anything else you would like to add:** All the details are logged here https://github.com/aws/amazon-vpc-cni-k8s/issues/1278 as I wasn't sure if this is Kubeflow issue. Please let me know if you think Kubeflow could have caused it.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): Not Available
- kfctl version: (use `kfctl version`): `kfctl v1.1.0-0-g9a3621e`
- Kubernetes platform: (e.g. `minikube`) `AWS EKS`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by tretos53** [comment]
With help from AWS support, the error is:

```
kubectl describe ds/aws-node -n kube-system
.
.
.
Events:
  Type     Reason        Age                   From                  Message
  ----     ------        ----                  ----                  -------
  Warning  FailedCreate  14m (x1353 over 15d)  daemonset-controller  Error creating: Internal error occurred: failed calling webhook "inferenceservice.kfserving-webhook-server.pod-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-pods?timeout=30s: no endpoints available for service "kfserving-webhook-server-service"
```

This looks like the same issue as https://github.com/kubeflow/kubeflow/issues/4806

What's the fix for that? I could probably delete the MutatingWebHookConfiguration inferenceservice.serving.kubeflow.org but I don't think this is a solution.

**Comment by DavidSpek** [comment]
@tretos53 Is this still a problem or can this issue be closed? This seems to be an issue with your cluster setup and the AWS kubeflow distribution so you should try and contact somebody from AWS (maybe @PatrickXYS can help).

**Comment by tretos53** [comment]
I reinstalled Kubeflow and it works, but this happened twice with Kubeflow so it needs checking/testing.
