### ISSUE TITLE
gci-io problem of CN user

### ISSUE THREAD

**Issue by hlld3344** [kubeflow/kubeflow#5386]
/kind question

**Question:**

I downloaded the minikf.box (version: 20200305.1.0) and started it with vagrant, then I opened 10.10.10.10 but soon I've stucked in the process "Provisioning Docker Imagas...  Listing images".

I used wireshark to catch network access record and found out there's so many access records of 74.125.203.82 which i've checked it's the google cloud server. Seems it's the network issue, cause I can't access gci.io from my computer, even though I can visit gci.io from my chrome browser with GHelper plugin.

My question is why minikf should access gci.io to listing images since all of the images is included in the minikf.box.

Hope sincerely for any suggestions, thanks a lot.

**Comment by DavidSpek** [comment]
@hlld3344 MiniKF does not have an image registry built in and needs to download the docker images from a registry (in this case gcr.io). 
/close
