### ISSUE TITLE
Installation error: no matches for kind "ClusterRbacConfig" in version "rbac.istio.io/v1alpha1"

### ISSUE THREAD

**Issue by fuhuifang** [kubeflow/kubeflow#5391]
/kind bug

**What steps did you take and what happened:**
Hello! I was following the instructions [here](https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/). When I ran `kfctl apply -V -f ${CONFIG_URI}`, I got the following error:
`WARN[0063] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout474140078": no matches for kind "ClusterRbacConfig" in version "rbac.istio.io/v1alpha1"  filename="kustomize/kustomize.go:266"`

and it just keeps retrying. Do you know how to fix this? Thanks!

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes platform: (e.g. `minikube`): Azure Kubernetes Service 
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): ubuntu 16.04.7 LTS

**Comment by torbre16** [comment]
Hi.

I ran into the same issue today. I first tried to install Kubeflow with Istio 1.7.4, which resulted in the same error described by you.

After a downgrade to Istio 1.6.13 I was able to complete the installation. The CONFIG_URI used in the instructions mentioned by you points to https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_azure.v1.1.0.yaml, which contains the following comment:

"It is expected to have Istio 1.6.x installed in istio-system namespace"

Maybe that also helps you to perform the installation? It seems that further adjustments are needed to make it compatible with Istio 1.7.x.

Best regards,
Torbre16

**Comment by fuhuifang** [comment]
@torbre16 

> Hi.
> 
> I ran into the same issue today. I first tried to install Kubeflow with Istio 1.7.4, which resulted in the same error described by you.
> 
> After a downgrade to Istio 1.6.13 I was able to complete the installation. The CONFIG_URI used in the instructions mentioned by you points to https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_azure.v1.1.0.yaml, which contains the following comment:
> 
> "It is expected to have Istio 1.6.x installed in istio-system namespace"
> 
> Maybe that also helps you to perform the installation? It seems that further adjustments are needed to make it compatible with Istio 1.7.x.
> 
> Best regards,
> Torbre16

Thanks @torbre16 ! It did fix the issue.

**Comment by DavidGeW** [comment]
I took the same steps as you did, and in addition to this problem, I encountered another problem.Have you ever encountered the following problem？Thanks.

` kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout125728891": admission webhook "validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host.`

**Comment by berndverst** [comment]
@DavidGeW that sounds like a separate issue with cert-manager instead. If you still have that problem, can you file a separate issue please? I recently saw another such issue.

**Comment by DavidGeW** [comment]
> @DavidGeW that sounds like a separate issue with cert-manager instead. If you still have that problem, can you file a separate issue please? I recently saw another such issue.

@berndverst  Thanks! I've solved this problem with https://github.com/kubeflow/kubeflow/issues/5070, it's a problem caused by the upgrade of istio.
