### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known when sending a prediction request through ingress and IAP for tfserving example

### ISSUE THREAD

**Issue by jal06** [kubeflow/kubeflow#5396]
/kind bug

When trying tf-serving example shown in this page [https://www.kubeflow.org/docs/components/serving/tfserving_new/](https://www.kubeflow.org/docs/components/serving/tfserving_new/), I encountered 2 problems with Kubeflow 1.1 on GCP. 
I found a workaround for the 1rst problem (configmap not found). 
However, I don't know how to solve the 2nd problem (error 404)

- Problem 1
After applying the yaml file (kubectl apply -f deployment_configmap.yaml), the pod stays in status Init:0/1
```
kubectl get po
NAME                                               READY   STATUS      RESTARTS   AGE
mnist-v1-67c987f6c7-nrdb8                          0/2     Init:0/1    0          11s
```

In the logs of each container (mnist, istio-proxy and istio-init), I see the same message :
`Error from server (BadRequest): container "mnist" in pod "mnist-v1-67c987f6c7-nrdb8" is waiting to start: PodInitializing`

In the events, I see that the description of a configmap is missing
```
kubectl get events
27s         Warning   FailedMount              pod/mnist-v1-67c987f6c7-5trpf                                         MountVolume.SetUp failed for volume "config-volume" : configmap "mnist-v1-config" not found
```

If I delete the VolumeMounts and the volume for configmap, the pod starts successfully.
Below are the lines I removed from the yaml :
```
        - mountPath: /var/config/
          name: config-volume
```
and 
```
      - configMap:
          name: mnist-v1-config
        name: config-volume
```

```
kubectl get po
NAME                                               READY   STATUS      RESTARTS   AGE
mnist-v1-865f4589d9-b8bvs                          2/2     Running     0          2m9s
```

Maybe I am wrong, but my guess is that the configmap is not required because the pod started successfully 

- Problem 2 :
When I send a prediction request through ingress and IAP, I get the following error 404

`python iap_request.py https://${INGRESS_DNS}/tfserving/models/mnist ${IAP_CLIENT_ID} --input=./iris-input.json`

```
/home/aaa/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'zzzzz.endpoints.xxxx.cloud.goog'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "iap_request.py", line 143, in <module>
    main()
  File "iap_request.py", line 136, in main
    raise Exception('Bad response from application: {!r} / {!r} / {!r}'.format(
Exception: Bad response from application: 404 / {'x-powered-by': 'Express', 'content-security-policy': "default-src 'none'", 'x-content-type-options': 'nosniff', 'content-type': 'text/html; charset=utf-8', 'content-length': '162', 'date': 'Wed, 11 Nov 2020 07:35:13 GMT', 'x-envoy-upstream-service-time': '0', 'server': 'istio-envoy', 'Via': '1.1 google', 'Alt-Svc': 'clear'} / '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /tfserving/models/mnist</pre>\n</body>\n</html>\n'
```

I checked the page [https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings) : but didn't find useful info 

Below are the commands I executed before sending the prediction request :
```
export PROJECT=xxxx
gcloud config set project ${PROJECT}
export ZONE=yyyyyy
gcloud config set compute/zone ${ZONE}
```

```
export KF_NAME=zzzzz
kubens tfnamespace

```

```
export SERVICE_ACCOUNT=my_sa_name
export KEY_FILE=${HOME}/.config/gcloud/${SERVICE_ACCOUNT}-credentials.json
```

```
export INGRESS_DNS=${KF_NAME}.endpoints.${PROJECT}.cloud.goog
export IAP_CLIENT_ID='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.apps.googleusercontent.com'
gcloud config set account ${SERVICE_ACCOUNT}@${PROJECT}.iam.gserviceaccount.com
export GOOGLE_APPLICATION_CREDENTIALS=${KEY_FILE}
```

**What did you expect to happen:**
Response 200 for the prediction request

**Anything else you would like to add:**

I checked that ${GOOGLE_APPLICATION_CREDENTIALS} points to the key json file, and it is OK
`more ${GOOGLE_APPLICATION_CREDENTIALS}`

I checked that the active account is the service account :
`gcloud auth list`

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version v1beta1 (Kubeflow 1.1 deployed in GCP using gcp-blueprints)
- kfctl version: (use `kfctl version`): gcp-blueprint
- Kubernetes platform: GCP
- Kubernetes version: (use `kubectl version`): Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.1504
- OS (e.g. from `/etc/os-release`):

**Comment by jal06** [comment]
Humm, I did an error when setting the variable INGRESS_DNS

If I update this variable as below ,

`INGRESS_DNS=kubeflow.endpoints.${PROJECT}.cloud.goog`

(for INGRESS_DNS, the 1rst part is kubeflow instead of ${KF_NAME}

I get the error below 
```
  File "/home/jal/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/jal/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/jal/anaconda3/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by DavidSpek** [comment]
@jal06 Is this still an issue? If so, I believe this is related to KFServing so it would be best to open an issue over at https://github.com/kubeflow/kfserving.

**Comment by ja06200** [comment]
@DavidSpek, thanks for looking at this.

I created this issue in kubeflow/kubeflow because it is related to TensorFlow Serving; it is not related to KFServing.
I already open the same issue for kfserving ([1199](https://github.com/kubeflow/kfserving/issues/1199)) 
My guess is that it is due to a wrong configuration of the local gateway in GCP and this will be solved via [178](https://github.com/kubeflow/gcp-blueprints/issues/178) .

So I think I can close it now

**Comment by jal06** [comment]
@DavidSpek, thanks for looking at this.

I created this issue in kubeflow/kubeflow because it is related to TensorFlow Serving (not related to KFServing).
I have already open the same issue for kfserving ([1199](https://github.com/kubeflow/kfserving/issues/1199)) 

My guess is that it is due to a wrong configuration of the local gateway in GCP and this will be solved via [178](https://github.com/kubeflow/gcp-blueprints/issues/178) .

So I think I can close it now
