### ISSUE TITLE
[istio-authz-profile-controller] Support Istio Authorization Policy in profile-controller

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5397]
/kind feature

Umbrella issue: https://github.com/kubeflow/kubeflow/issues/5313

**Why you need this feature:**

In order to use the `profile-controller` with Istio >= 1.6
- We use Istio authorization to limit access to network endpoints, like Jupyter Notebooks.
- Early Istio used Istio RBAC.
- Newer Istio deprecated Istio RBAC and moved to Istio AuthorizationPolicy.

**Describe the solution you'd like:**

1. Add an envvar option `ISTIO_AUTHZ_TYPE`, with possible values of `rbac`(default) and `authorizationpolicy`.
2. Implement the `authorizationpolicy` option.

This way we also ensure we don't break people that can't move to the new CRD yet.

**Comment by yanniszark** [comment]
/assign @ericandrewmeadows
who opened a PR: https://github.com/kubeflow/kubeflow/pull/5393

**Comment by yanniszark** [comment]
@ericandrewmeadows can you please make a PR to add yourself to the KF org?
See this PR as an example:
https://github.com/kubeflow/internal-acls/pull/370

**Comment by omerfsen** [comment]
+1

**Comment by zijianjoy** [comment]
Thank you so much for upgrading istio for profile controller! When should we expect a new image with this fix? Location: `gcr.io/kubeflow-images-public/profile-controller`
