### ISSUE TITLE
Pipelines stop running: Failed calling webhook "inferenceservice.kfserving-webhook-server.pod-mutator"

### ISSUE THREAD

**Issue by lukkiddd** [kubeflow/kubeflow#5410]
/kind bug

**What steps did you take and what happened:**

Sorry for the minimum description. Here's what happened.

We use Kubeflow v0.7 installed on GKE. Everything works fine for a while, then one day we cannot access Kubeflow via UI and all the pipelines were stop running.

Here're the error messages we've got.

**1)**
```
Internal error occurred: failed calling webhook "inferenceservice.kfserving-webhook-server.pod-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-pods?timeout=30s: no endpoints available for service "kfserving-webhook-server-service"
```

**2)**
```
:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Solution**: We temporarily removed the webhook and then everything back to normal.

**What we're looking for**

Currently, everything works fine (according to the above solution), but we're **looking for the possible root cause** of this issue. So we can prevent it in the future.

**Environment:**

- Kubeflow version: 0.7
- kfctl version: v1.1.0
- Kubernetes platform: GKE
- Kubernetes version: 1.15.12-gke-20
- OS: Container-Optimized OS

**Comment by DavidSpek** [comment]
@lukkiddd I'm closing this issue as it is regarding a (very) old version of Kubeflow. Also, it seems your problem is related to KFserving so if you are still encountering this problem please create an issue over at https://github.com/kubeflow/kfserving. 
/close

**Comment by lukkiddd** [comment]
@DavidSpek Thank you so much. 

After I opened the issue on Github, I haven't see it again.
