### ISSUE TITLE
Can we provide aws optimized kubeflow notebook image dockerfiles?

### ISSUE THREAD

**Issue by zxh326** [kubeflow/kubeflow#5413]
/kind question

**Question:**
https://www.kubeflow.org/docs/aws/notebook-server/#kubeflow-notebook-images

> 527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-1.15.2-notebook-cpu:1.1.0
527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-1.15.2-notebook-gpu:1.1.0
527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-2.1.0-notebook-cpu:1.1.0
527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-2.1.0-notebook-gpu:1.1.0

I want to build myself, because in aws china, these images cannot be pulled down.

**Comment by Jeffwan** [comment]
/cc @PatrickXYS 

I think it's in the roadmap

**Comment by PatrickXYS** [comment]
/assign 

@zxh326 Thanks for the heads up! It's on our roadmap, we should be able to give updates after 1.2 release

**Comment by DavidSpek** [comment]
@PatrickXYS Do you know the current situation regarding this?
