### ISSUE TITLE
Kubeflow without Istio

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/kubeflow#5414]
/kind feature

Referring to user email - welcomemandeep@gmail.com to `Kubeflow-discuss`: 

> Hi,
I am struggling to use Kubeflow without using Istio and using some other ingress/egress technology ( for eg. Counter). 
> 
> Now there are several things that are explicitly called out that have a hard dependency on Istio like notebooks, KF Serving.
I would like to understand this better so that we can identify and isolate the use cases which have a hard dependency on Istio and try to make it flexible to use other substitutes available. 
I have already gone through [0].
> 
> [0] - https://www.kubeflow.org/docs/other-guides/istio-in-kubeflow/

Current docs:
![image](https://user-images.githubusercontent.com/27001378/99521327-2fdb6600-298c-11eb-8929-43a658c9d6e3.png)

Should these hard dependencies be mapped and removed?

**Comment by PatrickXYS** [comment]
@RFMVasconcelos It's not easy to do so, some kubeflow components rely on istio and the main point is:

Istio is a very popular service mesh application and well-maintained by the open source community, it's natural that folk try to adopt istio when they need the tool. 

Besides getting rid of istio, the community now is thinking about upgrading istio to 1.6 / 1.7 version. That's our next step I think

**Comment by welcomemandeep** [comment]
So we were trying to break down the use of Kubeflow and leverage some parts of KF for some of our use cases.  As part of that effort, we were trying to use KF serving alone. Now KFServing has a hard dependency on Istio which is a problem for us as we use Envoy + Contour in our k8s cluster (Istio has some security problems).

Similarly, I wanted to understand other hard dependencies used in other parts and if it were possible to modularize them.

**Comment by DavidSpek** [comment]
This might be a reason for implementing SMI https://github.com/kubeflow/kubeflow/issues/4660. This was also discussed in the community meeting on December 8th 2020, https://youtu.be/OKqx3IS2_G4?t=1910.
