### ISSUE TITLE
Update kubeflow/kubeflow README.md - redirect to working groups

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5421]
/kind feature

Follow on to kubeflow/community#454

Now that kubeflow has formed WGs, we are moving in the direction of making each WG more independent. 

The README.md in kubeflow/kubeflow is a landing page for a lot of users looking for info about Kubeflow.

As such the primary purpose of the landing page should be to redirect users to different WGs.

I think the README.md should include a brief overview explaining that Kubeflow is divided into WGs pursuing different pieces of an ML platform and then point people at the various WGs.

I think we can pull all of this information directly from the WG definitions
https://github.com/kubeflow/community/blob/master/wgs.yaml

/cc @RFMVasconcelos 
/cc @kubeflow/wg-automl-leads 
/cc @kubeflow/wg-deployment-leads 
/cc @kubeflow/wg-notebook-leads 
/cc @kubeflow/wg-pipeline-leads 
/cc @kubeflow/wg-training-leads 
/cc @kubeflow/wg-serving-leads

**Comment by animeshsingh** [comment]
+1. Totally agree

**Comment by PatrickXYS** [comment]
That totally make sense 

/cc @kubeflow/wg-manifests-leads

**Comment by Bobgy** [comment]
Thanks for raising the proposal, completely agree too.
Hopefully, this should start to direct people to individual WG repos they care about.

**Comment by RFMVasconcelos** [comment]
+1! I created a WIP PR -> #5430

**Comment by yanniszark** [comment]
@RFMVasconcelos should we close now that #5430 is merged?

**Comment by RFMVasconcelos** [comment]
Nice catch @yanniszark! 

/close
