### ISSUE TITLE
 KF 1.2.0 on EKS: May not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|~X|cluster-local-gateway-istio-system

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#5431]
/kind bug

I am attempting to roll out KF 1.2.0 for the first time, using:

https://github.com/kubeflow/kfctl/releases/tag/v1.2.0
https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml

Which eventually results in the following error:

```
time="2020-11-23T10:43:23Z" level=error msg="Error evaluating kustomization manifest for cluster-local-gateway: accumulating resources: recursed merging from path 'base': may not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|~X|cluster-local-gateway-istio-system" filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with mes****ge: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with mes****ge: error evaluating kustomization manifest for cluster-local-gateway: accumulating resources: recursed merging from path 'base': may not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|~X|cluster-local-gateway-istio-system

```

This is on a clean installation on EKS 1.18.

- Kubeflow version: 1.2.0
- kfctl version: (use `kfctl version`): 1.2.0
- Kubernetes version: (use `kubectl version`): 1.18 (EKS)

**Comment by PatrickXYS** [comment]
I can't reproduce the issue

Suggestions:

1. Create a fully-new EKS cluster
2. Install Kubeflow 1.2 on the cluster

/assign

**Comment by karlschriek** [comment]
This is on a fully new EKS cluster already. Since this is a customize error, it might have something to do with a change in how Kustomize deals with merges. I am using:

{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-11T23:14:14Z GoOs:linux GoArch:amd64}

**Comment by karlschriek** [comment]
Ok, so I did yet another clean install, this time also forcibly clearing any caches that might be lying around on the CI/CD workers. Went through this time. I can only assume that there were some hanging YAMLs for a previous 1.0 build.

Thanks for confirming that there is no trouble with the KF 1.2 rollout as such, that help to narrow down the problem.
