### ISSUE TITLE
Is kubeflow suitable for parallel simulation?

### ISSUE THREAD

**Issue by iedmrc** [kubeflow/kubeflow#5435]
/kind question

**Question:**
Hi all, I wonder if we could also use kubeflow in this case:

Consider I have a python project (simulation) that runs for approx. 1-50 different environments. But this simulation needs to communicate several external services (docker images) that also need to be spin-up for each run and die after done. And also, results will be written to an external mongo database, except application logs. And the most important part is that these 1-50 different environments are provided dynamically which means that I just might want to run for 10 of them or 22 of them or maybe all of them (50) at any run.

Here is a diagram for what I need:
![image](https://user-images.githubusercontent.com/13666448/100229512-69384680-2f35-11eb-90a6-a641e22670bc.png)

**Comment by jbottum** [comment]
@iedmrc Hi, did you define an architecture / configuration for this requirement?  Which platform (GCP, Azure, AWS, on-prem, ...) are you running on ?

**Comment by iedmrc** [comment]
The platform is AWS. The solution is not kubeflow for me. Prefect does the job great: https://docs.prefect.io/core/concepts/mapping.html . And have a much more active community than kubeflow :)). If you need, I suggest you check it out.
