### ISSUE TITLE
Kubeflow dashboard not working on AKS

### ISSUE THREAD

**Issue by samuda2019** [kubeflow/kubeflow#5443]
/kind bug
**What steps did you take and what happened:**
Followed all the steps from the below documentation for configuring kubeflow on AKS
https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/
[A clear and concise description of what the bug is.]
After configuring port forwarding to 127.0.0.1:8080 and tried accessing on the browser it gave an error "page can't be found"
Also tried curl on SSH terminal but with no output

**What did you expect to happen:**
Expected to see the Kubeflow dashboard as mentioned in the documentation

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Also got below error after executing - kfctl apply -V -f ${CONFIG_URI}
Encountered error applying application istio:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): Kubeflow dashboard is not working is the problem
- kfctl version: (use `kfctl version`): 1.16
- Kubernetes platform: (e.g. `minikube`) AKS tried both 1.16.13 and 1.17.13
- Kubernetes version: (use `kubectl version`): Tried both on 1.14 and 1.16
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by PatrickXYS** [comment]
https://bit.ly/3n8NvSd

**Comment by berndverst** [comment]
Hello @samuda2019 

There are a number of things that could be a problem here. Most likely you are using an ISTIO version other than 1.6.X. I now updated the docs to make it clear you need to use 1.6.X.

I just updated the instructions (PR pending) and made an additional update to the Azure config files. Could you please wait for the following two PRs to be merged

https://github.com/kubeflow/website/pull/2413
https://github.com/kubeflow/manifests/pull/1698

and then proceed with the instructions at
https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/

**Comment by berndverst** [comment]
@samuda2019 please let me know if this is still an issue with the latest deployment instructions and configuration files.

**Comment by samuda2019** [comment]
It worked after making sure to use ISTIO version 1.6.X. Thank you.
