### ISSUE TITLE
Uploading large file form jupyter dashboard

### ISSUE THREAD

**Issue by ifs-imaddjelaili** [kubeflow/kubeflow#5444]
/kind bug

Hello everybody
I'have an nginx error "413 Request Entity Too Large" when trying to upload larges files into jupyter notebook dashboard via the interface.

`<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

I've seen that we can fix that by adding some annotation to the nginx ingress but I don't see any nginx ingress ressource in my cluster I have only an nginx-deployment.

I tried to add respectively those annotations to kubeflow-ingress :

   nginx.ingress.kubernetes.io/proxy-body-size: 200m
   nginx.org/client-max-body-size: 200m

But it didn't work 

I was wondering if anyone here had the same issue? 

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: kfctl v1.1.0-0-g9a3621e
- Kubernetes version: 1.18.12_1533

**Comment by DavidSpek** [comment]
@ifs-imaddjelaili Kubeflow uses Istio and creates an istio gateway so you should not have any ingresses for Kubeflow by default. It might be the jupyter container itself that is giving that error. What might be an alternative for uploading large files is the Volume Manager UI that Arrikto will open source soon https://journal.arrikto.com/democratizing-the-use-of-pvcs-with-the-introduction-of-a-volume-manager-ui-a5bf616570d3.

**Comment by DavidSpek** [comment]
@ifs-imaddjelaili I am now working on adding this feature in https://github.com/kubeflow/kubeflow/pull/5783. Here is a sample of what it would look like when fully implemented in the Volumes Web App.

![vwa-pvcviewer-opt6](https://user-images.githubusercontent.com/28541758/112721027-fe5a4480-8f01-11eb-996b-b421bf1c100c.gif)
