### ISSUE TITLE
Kubeflow install is failing in Mac

### ISSUE THREAD

**Issue by vsriniv-git** [kubeflow/kubeflow#5450]
I have installed dokee-desktop in mac and installed istio. When I install Kubeflow 1.2 using kubectl, I am getting an error...
Encountered error applying application istio-stack: (kubeflow.error): Code 500 with message: Apply.Run : [error when creating "/tmp/kout525286736": admission webhook "validation.istio.io" denied the request: unrecognized type attributemanifest, error when creating "/tmp/kout525286736": admission webhook "validation.istio.io" denied the request: unrecognized type handler, error when creating "/tmp/kout525286736": admission webhook "validation.istio.io" denied the request: unrecognized type instance, error when creating "/tmp/kout525286736": admission webhook "validation.istio.io" denied the request: unrecognized type rule] filename="kustomize/kustomize.go:284"

This is not allowing me to complete kubeflow installation

Mac: Darwin 19.6.0
Kubectl version: v1.19.3
Kfctl version: v1.2.0-0-gbc038f9
Expected result

Expected Kubeflow to be successfully installed

kfctl apply -V -f kfctl_k8s_istio.yaml is the command I entered. I have a local copy of the yaml file

**Comment by DavidSpek** [comment]
I believe this might be caused by the cluster not being setup properly to support Istio and JWT.

**Comment by smalhot9464** [comment]
Any update on this please?
