### ISSUE TITLE
Kubeflow 1.2 deployment on Azure instructions appear incorrect

### ISSUE THREAD

**Issue by VibratingPig** [kubeflow/kubeflow#5454]
/kind bug

**What steps did you take and what happened:**
I followed the instructions on https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/ and the installation cycles at the kfctl stage reporting it cannot find ClusterRbacConfig" in version "rbac.istio.io/v1alpha1"  

**What did you expect to happen:**
The deployment to work

**Anything else you would like to add:**
The instructions from Microsoft are to install istio v1.7.3 (found can be found here https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux) which, I believe, are possibly incompatible with 1.2. I then downgraded the version of Istio to 1.6.3 and the problem of the Rbac config went away. However I also noticed that instructions referred to  https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_azure.v1.1.0.yaml which I then upgraded to 1.2 such as https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml and then deployed and it worked.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version v1beta1
- kfctl version: (use `kfctl version`):kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) 1.18.10 on Azure
- Kubernetes version: (use `kubectl version`):v1.20.0
- OS (e.g. from `/etc/os-release`): Unknown but running Standard_D4s_v3 nodes.

**Comment by aronchick** [comment]
Updated - if you're seeing this, you can fix the problem by doing the following:

```
ISTIO_RELEASE=1.6.14
```
(or whatever the most recent release is). Then follow the AKS Istio installation instructions.

**Comment by berndverst** [comment]
Please also see https://github.com/kubeflow/kubeflow/issues/5313

In general Kubeflow only supports specific Istio versions. Hopefully a wider range of Istio versions will be supported in the future -- there is also talk to support other service meshes.

For the Azure deployment we are inheriting from the Kubeflow defaults. Our Kubeflow docs unfortunately didn't list a specific Istio version and when AKS updated their docs for installing Istio the Kubeflow install docs no longer worked.

Thanks for updating @aronchick

**Comment by berndverst** [comment]
Docs fix: https://github.com/kubeflow/website/pull/2413

**Comment by berndverst** [comment]
Also from your other issue -- the release team forgot to include the appropriate notebook images with the release. They added this after the fact, but Azure configs were manually pinned to a different commit. That's fixed now. Please grab the latest kfdef manifests once this is merged: https://github.com/kubeflow/manifests/pull/1698

**Comment by VibratingPig** [comment]
Thanks just deployed and it all works fine.
