### ISSUE TITLE
Kubeflow 1.2 deployment on Azure show no upstream server when attempting to connect to notebook

### ISSUE THREAD

**Issue by VibratingPig** [kubeflow/kubeflow#5455]
/kind bug

**What steps did you take and what happened:**
Successfully launched kubeflow, create a notebook server and attempted to connect. The webpage on http://localhost:8080/notebook/xxxx/some-notebook/ reports 

no healthy upstream

**What did you expect to happen:**
The notebook to launch

**Anything else you would like to add:**

All pods are running in the main kubeflow - the notebook pod errored:

Successfully assigned piero/some-notebook-0 to aks-nodepool1-13842780-vmss000001
Pulling image "docker.io/istio/proxyv2:1.6.3"
Successfully pulled image "docker.io/istio/proxyv2:1.6.3"
Created container istio-init
Started container istio-init
Pulling image "gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0"
Successfully pulled image "gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0"
Created container some-notebook
Started container some-notebook
Pulling image "docker.io/istio/proxyv2:1.6.3"
Successfully pulled image "docker.io/istio/proxyv2:1.6.3"
Created container istio-proxy
Started container istio-proxy
Container image "gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0" already present on machine
Readiness probe failed: Get http://10.244.0.52:15021/healthz/ready: dial tcp 10.244.0.52:15021: connect: connection refused
Back-off restarting failed container

image gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0

This also occurred on the 2.1.0 image: gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0

**Environment:**

    Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version v1beta1
    kfctl version: (use kfctl version):kfctl v1.2.0-0-gbc038f9
    Kubernetes platform: (e.g. minikube) 1.18.10 on Azure
    Kubernetes version: (use kubectl version):v1.20.0
    OS (e.g. from /etc/os-release): Unknown but running Standard_D4s_v3 nodes.

**Comment by berndverst** [comment]
/assign

This is very curious as recently notebook images were altered.

Ah I know what happened! The Kubeflow team had to alter the Notebook images and changed the tag to be used for Kubeflow v1.2. This introduced a config change in Azure but of course the Azure kfdef manifests for v1.2 are pinned to a particular commit.

Background:
https://github.com/kubeflow/manifests/pull/1686

I just a little while ago made a change to the config files and pinned a newer commit which will also include the necessary commit for these images and hence resolve the issue.

https://github.com/kubeflow/manifests/pull/1698

**Comment by berndverst** [comment]
I'm confident the latest deployment config resolves the issue. I'll go ahead and close this issue. Please redeploy with the latest config file. You can find all the config files for version 1.2 at https://github.com/kubeflow/manifests/tree/v1.2-branch/kfdef

/close
