### ISSUE TITLE
Kale-SnapshotStore Integration in kubeflow

### ISSUE THREAD

**Issue by srujanattunuri** [kubeflow/kubeflow#5456]
/kind feature

**Why you need this feature:**
Currenlty, SnapshotStore is only deployed through miniKF, would like to see have the integration with Kubeflow. As, it needs for Production usecase as we don't have to deploy miniKF separately.

**Comment by jbottum** [comment]
@srujanattunuri the snapshot store is available for production clusters via software extensions to Kubeflow.   You will also need a storage class (such as Arrikto Rok) which has been integrated with the Kubeflow application and Kale's programmatic calls to CSI.   I am glad to bring in SMEs to discuss.

**Comment by srujanattunuri** [comment]
@jbottum Thanks for the response. In kubeflow docs seen the option that is providing by Arrikto Rok and i had deployed kubeflow in on prem and wanted to have this feature as part of kubeflow stack bundled. In my perspective, software extension is not open source and would like to see in this way as part of kubeflow stack.

**Comment by jbottum** [comment]
@srujanattunuri thanks for your note.   Yes, Arrikto is a major open source contributor to Kubeflow and we have extended the Kubeflow app to work with standards based CSI.   Once below the CSI, you are often working with a proprietary storage solution / storage class, especially if you want an on-prem, enterprise-grade storage features, performance and support i.e EMC, NetApp, Pure, Hitachi.   Managing ML workflows (through the complete stack to the storage layer) has great advantages for data science teams, which might be worth your investigation before you set your architecture investments.  Which storage hardware / software components are you investing in ?   How much time will you spend on those components for each release of Kubeflow and/or the storage solution upgrades ?  After all of that, will it deliver the workflows that your teams need?

**Comment by srujanattunuri** [comment]
@jbottum Again thanks for the detailed info and prompt response. Actually, in my usecase we have enterprise minio and trying to see if we can connect snapshot store to S3 Store.

**Comment by jbottum** [comment]
@srujanattunuri Thanks and appreciate your interest.   Have you developed your SLA for your storage performance, especially for intense model training requirements?  How will you snapshot (without impacting performance)?  Will your snapshots be deduplicated?  Will the snapshots include all the components necessary to recreate your data science environment i.e. the ML code, all packages and libraries, your data sets (in that point in time) and your metadata?  Can you quickly re-create that environment in another cluster?  Will your storage support the ML workflows that trigger programmatic snapshots during your pipeline building and feature engineering (...which is often necessary for reproducibility, compliance and auditing?)...These are part of a strong list of requirements that can help your Kubeflow cluster reach enterprise-grade functionality.

**Comment by DavidSpek** [comment]
@srujanattunuri The Volume Manager UI from arrikto should be push to Kubeflow soon after https://github.com/kubeflow/kubeflow/pull/5463 is merged. I will be looking at implementing some code I wrote for Kale that allows taking snapshots of volumes and notebooks and also allows restoring notebooks from snapshots using kubernetes native snapshots. Essentially, a snapshot of each PVC mounted to the notebook is made and the mount location and container image name are written to the metadata of the snapshots. Restoring a notebooks looks for all snapshots belonging to that notebook, creates PVCs from the snapshots and creates a new notebook using the same container image and the newly created PVCs mounted to their respected locations. For my use case I use Rook and snapshots are possible for ceph-rdb and cephfs (I'm not sure about object storage though). If your storage solution supports taking snapshots using the CSI driver, it should work this solution as well.
