### ISSUE TITLE
Enable Dependabot for security updates

### ISSUE THREAD

**Issue by naveensrinivasan** [kubeflow/kubeflow#5457]
/kind feature

Enable the Dependabot for security updates within the Github project.
![image](https://user-images.githubusercontent.com/172697/101999789-82b7ed00-3cae-11eb-9daf-dfe6017a1804.png)

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
There are critical security vulnerabilities that aren't patched. This will enable addressing those issues proactively. 

Here is an example of security issues reported

![image](https://user-images.githubusercontent.com/172697/101999863-11c50500-3caf-11eb-90d0-b7c413d76874.png)

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DavidSpek** [comment]
@naveensrinivasan Given the open PRs from the dependabot, isn't this already enabled?

**Comment by naveensrinivasan** [comment]
Yes!

**Comment by DavidSpek** [comment]
/reopen 

While dependabot is turned on, it does not seem like it is properly configured. This should be solved with https://github.com/kubeflow/kubeflow/pull/5542

**Comment by DavidSpek** [comment]
Closing this as Renovate will be used (hopefully) in the near future. 
/close
