### ISSUE TITLE
metadata writer crash loop - cannot get resource "namespaces"

### ISSUE THREAD

**Issue by konradmalik** [kubeflow/kubeflow#5458]
/kind bug

**What steps did you take and what happened:**

I installed full kubeflow on a clean cluster per installation instructions (without dex first, then with dex, both versions suffer the same problem) on a 2 node K3S cluster (Rancher project). All services start except metadata-writer. I suspect that this service is responsible for an error while deploying a sample pipeline. The error we received while starting a container in pipelines:
```
This step is in Error state with this message: failed to save outputs: Error response from daemon: No such container: bb1eccdf02dce0ee653d99000128e5410524eb358d672afcfbc53aca32557579
```

I believe this is related to the crashing metadata-writer pod (its state is 1/2, the "main" container is crashing) with logs:
```
2020-12-14 19:32:04.388493: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvi
nfer.so.6: cannot open shared object file: No such file or directory
2020-12-14 19:32:04.388943: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror:
 libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-12-14 19:32:04.388971: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GP
U with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Connected to the metadata store
Start watching Kubernetes Pods created by Argo
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 135, in <module>
    _request_timeout=2000,  # Sometimes HTTP GET gets stuck
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 142, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 344, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 178, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 365, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date':
 'Mon, 14 Dec 2020 19:32:05 GMT', 'Content-Length': '347'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"pods\\" is forbidden: User \\"system:servi
ceaccount:kubeflow:kubeflow-pipelines-metadata-writer\\" cannot get resource \\"namespaces\\" in API group \\"\\" in the namespace \\"pods\\"","reason":"Forb
idden","details":{"name":"pods","kind":"namespaces"},"code":403}\n'
```

**What did you expect to happen:**
I expected to be able to successfully deploy kubeflow and run pipelines on a local cluster.

**Anything else you would like to add:**
Seems like a lack of permissions, but it does not make sense to me. Why does it want to list namespace named 'pods'? I do not have such namespace. Still, cluster role and namespaced role is successfully bound to the kubeflow-pipelines-metadata-writer service as far as I can tell, so it should have all permissions, even to create such namespace if needed.

I tried K3S with kubernetes version 1.16 and 1.17 and kubeflow 1.1 and 1.2, all combinations produce the same exact error.
Is kubeflow not supporting K3S clusters? If so, why is that? K3S claims to be certified and 100% compatible distribution and every software I tried to date worked as expected.

Edit: Seems like standalone pipelines are working ok, but version 1.1.2. Version 1.0.4 from the install guide crashed metadata-writer too but with a different error: 'Illegal instruction (core dumped)', I don't know it its related to the one above.
Question is, can I somehow manually override pipelines version in the main kubeflow kustomize to use the newest one and try if this is the case of the error?

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2.0 with Dex, but tested also on 1.1.0 and versions with and without Dex
- kfctl version: (use `kfctl version`): 1.2.0 but tested on 1.1.0
- Kubernetes platform: (e.g. `minikube`): K3S newest releases per kubernetes version
- Kubernetes version: (use `kubectl version`): 1.17 currently, tested also on 1.16
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 virtual machines on Azure

**Comment by berndverst** [comment]
Just adding a note for other community members reviewing -- this is for vanilla k8s, not Azure AKS stack.

**Comment by frankmanbb** [comment]
I encountered the same issue "Version 1.0.4 from the install guide crashed metadata-writer too but with a different error: 'Illegal instruction (core dumped)', I don't know it its related to the one above"
This is probably caused by tensorflow compiled with avx and your machine doesn't support that. 

my solution is  upgrade from
gcr.io/ml-pipeline/metadata-writer:1.0.4 to gcr.io/ml-pipeline/metadata-writer:1.2.0 ( by editing the file kubeflow_install_dir/.cache/manifests/manifests-1.2.0/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml

I think this needs to be fixed by upgrading metadata-writer

**Comment by konradmalik** [comment]
yeah, thanks. This would fix the illegal instruction, however it did not help on the weird permission error. Same story.

**Comment by DavidSpek** [comment]
@konradmalik Are you still experiencing this issue?

**Comment by konradmalik** [comment]
honestly I don't have a cluster anymore to test this but for sure some time in the near future we'll try to run kubeflow on k3s again, then I'll report back here.

**Comment by kbc8894** [comment]
I have same problem. I try to change to `gcr.io/ml-pipeline/metadata-writer:1.5.0`.
so I found metatdata-writer latest image version [here](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml)
It is working for me.
My k8s cluster node info is below.
```
kubectl get nodes -o wide
NAME         STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
k3s   Ready    control-plane,master   130m   v1.20.6+k3s1   192.168.1.129   <none>        Ubuntu 18.04.5 LTS   4.15.0-142-generic   containerd://1.4.4-k3s1
```
