### ISSUE TITLE
Kubeflow 1.0.2 deloyment on GKE version 1.16.x

### ISSUE THREAD

**Issue by shalankig** [kubeflow/kubeflow#5460]
/kind bug

**Environment Details:**
Kubeflow version:  1.0.2
kfctl version: 1.0.2
Kubernetes platform: Google Kubernetes Engine
Master/Node Kubernetes Version: 1.16.x

**Details to Reproduce**
1. Deploy a private GKE cluster with version 1.16.x
2. Follow instructions to install Kubeflow 1.0.2 using CLI from here: https://v1-0-branch.kubeflow.org/docs/gke/deploy/deploy-cli/

**Error** 
Scenario 1: All kubeflow components are successfully deployed on the cluster.

Scenario 2: Few Kubeflow components in the "kubeflow" namespace fail with:
`Timeout: request did not complete within requested timeout`

In both the scenarios, it was observed that the all the requests made to the API server for the "kubeflow" namespace timeout and no new pods get created.

```
Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout","reason":"Timeout","details":{},"code":504}
I1215 04:55:39.545461 13563 helpers.go:201] server response object: [{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "error when creating \"test.yaml\": Timeout: request did not complete within requested timeout",
"reason": "Timeout",
"details": {},
"code": 504
}]
```

**P.S :** 
1. The very same Kubeflow Deployment 1.0.2 works for GKE Versions 1.17.x
2. All other namespaces function as expected and new pods can be deployed

**Comment by shalankig** [comment]
Need urgent help on this!

**Comment by jbottum** [comment]
@shalankig did you get this resolved ?

**Comment by shalankig** [comment]
Not yet @jbottum 

Also recently, we’ve been occasionally observing the same

`Timeout: request did not complete within requested timeout`

issue for Kubeflow Version 1.0.2 with our GKE Versions 1.15.x and 1.17.x clusters as well

**Comment by anil-pandey-mpf** [comment]
This issue is also observed on GKE version 1.16.x as well. Please take a look
