### ISSUE TITLE
Does the kfctl equivalent of kubectl diff exist, or is there a workaround for diffing KfDef and existing resources?

### ISSUE THREAD

**Issue by regorsmitz** [kubeflow/kubeflow#5478]
/kind question

**Question:**
hello, is there a way to see what changes `kfctl apply` would make to my cluster without running it? I’m looking for something that would be equivalent to `kubectl diff`. 

For context, being a newbie, I’ve run some commands to alter my Kubeflow cluster using kubectl apply -f on standalone yaml files (which I know is bad practice when it comes to Kubeflow) I've also made changes to the contents of my kustomize folder generated by `kfctl build` (which I believe is unavoidable at times if we want to fully customize our projects). Now I’m trying to clean things up so that my KfDef (which happens to be `kfctl_aws_cognito.v1.0.2.yaml`) reflects all the changes I’ve made downstream. 

I'm thinking that I could:
- run `kubectl diff --kustomize=<path-to-folder>` for each kustomizeConfig in my KfDef and concatenate all the changes to generate my final diff 

Does this sound like it would work?

If there is no way to accomplish this, I'd like to put in a feature request for a kfctl diff, which outputs all yaml changes that would be applied based on a given KfDef file. I'm sure I'm not alone in having made changes to my cluster in a wrong/unmaintainable way. This functionality could also be useful for debugging changes/upgrades.

Thanks for reading!

**Comment by slenky** [comment]
I'd also propose something like `kfctl build -V --file=... --dump | kubectl diff -f -`

Just upgrade your kfctl to 1.1 or 1.2

**Comment by regorsmitz** [comment]
sorry for the slow response. Does upgrading to kfctl 1.1 or 1.2 make seeing diffs of what changes to yaml files would be made if `kfctl apply` were run easier?

**Comment by yanniszark** [comment]
@regorsmitz I think you'll get better answers by posting on https://github.com/kubeflow/kfctl.
All related development has been moved there.
/close
