### ISSUE TITLE
Run pre/post-submit tests with the Optional-test infra

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5482]
/kind feature

**Why you need this feature:**
We will need to be able to run pre/post-submit jobs as a part of the [Notebooks WG](https://github.com/kubeflow/community/blob/master/wgs.yaml#L211) and a testing infrastructure. This way we can:
* Run unit and e2e tests to ensure future PRs don't break the existing functionality
* Automatically build new images for our artifacts, when their code is modified from a PR
* Create PR to update the manifests with the newly built images, from the previous step

**Describe the solution you'd like:**
We [ the Notebooks WG ] would like to integrate with the Optional-test infra, similar to how the [kfctl](https://github.com/kubeflow/kfctl/pull/427) repo does

A first good step would be to create a presubmit job that will run the unit tests for the [crud-web-app's common code](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/common/frontend/kubeflow-common-lib).

**Comment by kimwnasptd** [comment]
cc @kubeflow/wg-notebook-leads 

/assign @kimwnasptd 
/assign @PatrickXYS

**Comment by PatrickXYS** [comment]
There's a new doc I wrote recently for onboarding optional-test-infra https://github.com/kubeflow/testing/blob/master/aws/Doc/onboarding.md

It may be helpful for WG-notebook, will come back in Jan for further discussion

**Comment by Aut0R3V** [comment]
Hey, anything I can do here?

**Comment by kimwnasptd** [comment]
Hey there @Aut0R3V, the work for this issue will be broken down into two main tasks:
1. Configure the `kubeflow/kubeflow` repo and the Optional-test infra prow cluster to be able to run pre/post submit jobs
2. Write the python files that prow jobs will execute to generate an Argo workflow that will be run

We are working with @PatrickXYS on the first step. Once the Optional-test infra prow cluster is ready to run jobs from the `kubeflow/kubeflow` repo then we can coordinate on writing the python files for the Argo workflows.

I'll be posting updates of the entire process here so you, and everyone interested in this, can be in the loop

**Comment by kimwnasptd** [comment]
@PatrickXYS for the first step of the [on-boarding process](https://github.com/kubeflow/testing/blob/master/aws/Doc/onboarding.md), could you create a PR similar to kubeflow/internal-acls#373 to give write permissions for the `kubeflow/kubeflow` to the third-party-bots?

For the second step, do you have enough permissions to add the necessary Gitbub webhooks to the `kubeflow/kubeflow` repo?

**Comment by PatrickXYS** [comment]
> For the second step, do you have enough permissions to add the necessary Gitbub webhooks to the kubeflow/kubeflow repo?

In general, we need repo-level admin access to add Github webhook to the kubeflow/kubeflow repo.

**Comment by Aut0R3V** [comment]
Hey guys apologies I was busy with something else. I agree with @PatrickXYS. @kimwnasptd thanks for the details! Really appreciate your efforts. I'll send in a PR soon

**Comment by kimwnasptd** [comment]
> In general, we need repo-level admin access to add Github webhook to the kubeflow/kubeflow repo.

This is an issue for now, I don't have such permissions on the repo. @Bobgy do you have the required permission to set Github Webhooks in the `kubeflow/kubeflow` repo, or do you know someone who does?

> I'll send in a PR soon

@Aut0R3V I'm confused, what PR?

**Comment by Aut0R3V** [comment]
> @Aut0R3V I'm confused, what PR?
I didn't realise that @PatrickXYS had sent in #425

**Comment by PatrickXYS** [comment]
> > In general, we need repo-level admin access to add Github webhook to the kubeflow/kubeflow repo.
> 
> This is an issue for now, I don't have such permissions on the repo. @Bobgy do you have the required permission to set Github Webhooks in the `kubeflow/kubeflow` repo, or do you know someone who does?

I'll DM bobgy offline, we do have a tool to automate the webhook configuration but it requires admin access, that's the tricky part.

**Comment by PatrickXYS** [comment]
@kimwnasptd Given this comment (https://github.com/kubeflow/kubeflow/pull/5495#issuecomment-762372094), the webhook of kubeflow/kubeflow repo is configured, I think you can move forward with guidance doc https://github.com/kubeflow/testing/blob/master/aws/Doc/onboarding.md

**Comment by kimwnasptd** [comment]
@PatrickXYS this is really amazing! It's like the repo has gotten some life back. Thank you very for pushing this!

I'll follow on with the onboarding doc, as well as creating the first presubmit test of this repo. I'll keep on posting the progress here so everyone is in sync.

**Comment by kimwnasptd** [comment]
One question though. I see that in the comment you mentioned both of the bots are responding.
Is it possible to now remove the old k8s-infra bot?

**Comment by PatrickXYS** [comment]
@kimwnasptd We can disable the old k8s-infra bot by sending PR here https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml#L44-L57

We should disable presubmit and postsubmit, and also disable trigger here https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L722-L723

I'd suggest we move forward first with setting up kubeflow/kubeflow on optional-test-infra, then come back to disable the old bot.

**Comment by kimwnasptd** [comment]
A heads up here, we have the python code that will generate an Argo Workflow for running unittests on the common frontend library https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/shared_ui_tests.py

The next steps will be to 
1. extend workflows in this repo's https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml so that a presubmit test will use that workflow to run the unittests
2. configure the AWS prow bot to run presubmit jobs for `kubeflow/kubeflow`

**Comment by kimwnasptd** [comment]
@PatrickXYS now that we are almost there with having Argo Workflows for running tests I'd like to also start the discussion of building images, as post-submit jobs.

My big-picture understanding right now is that we could use Python to generate Argo Workflows that will in turn run Kaniko to build the different images and push them to ECR [ we'll also need to agree on the registry name, but let's not focus on this rn ].

Do you have any concerns wrt this approach?

**Comment by Bobgy** [comment]
Looks like you got the test infra running on optional-test-infra. Maybe it's a good time to remove configs in the old one.
(I'm migrating old test infra to gcp oss prow, so I'd love to see fewer stuff there too)

**Comment by PatrickXYS** [comment]
@kimwnasptd I think your approach looks good to me

@Bobgy I agree, we should remove it from kubernetes/test-infra now

**Comment by kimwnasptd** [comment]
@PatrickXYS I can see that the tests are still failing for PR for the AWS prow but not for the GCP one. I see a that the workflow triggers a ksonnet app that uses GCP credentials, which IIUC is the issue
```
Running: ks-13 env add kubeflow-kubeflow-presubmit-unittests-5640-bdf4da4-4496-de8a --namespace=kubeflow-test-infra --api-spec=version:v1.8.0 
```

But I can't figure out where this workflow is and why does it get triggered. Doing some simple find/grep I see that the name of the ksonnet component is `unit_tests`. I think this is located in [/testing/workflows](https://github.com/kubeflow/kubeflow/tree/743310d977f6dbac55a0676c94ce645b0276d05f/testing/workflows)?
Do you have any more insights?

Example PR https://github.com/kubeflow/kubeflow/pull/5640
[GCP prow](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/5640/kubeflow-presubmit/1365269662241132544/)
[AWS prow](http://prow.kubeflow-testing.com/view/s3/aws-kubeflow-jenkins/pr-logs/pull/kubeflow_kubeflow/5640/kubeflow-kubeflow-presubmit/1365269631886954496)

**Comment by PatrickXYS** [comment]
> Running: ks-13 env add kubeflow-kubeflow-presubmit-unittests-5640-bdf4da4-4496-de8a --namespace=kubeflow-test-infra --api-spec=version:v1.8.0 

If you found something like this, it's still using ksonnet to generate argo workflow. 

Let me first remove config from GCP prow to avoid confusion and it should help us narrow down the issue

**Comment by DavidSpek** [comment]
Following https://github.com/kubeflow/kubeflow/pull/5640

@PatrickXYS How would I be able to test a created Argo workflow locally before submitting a PR?

Another general topic is what the naming scheme and ECR registry will be so that can be implemented in the Kaniko job.

**Comment by PatrickXYS** [comment]
> Another general topic is what the naming scheme and ECR registry will be so that can be implemented in the Kaniko job.

I'm waiting for @kimwnasptd 's list of public ECR registries he want to add

> How would I be able to test a created Argo workflow locally before submitting a PR?

You can do so by creating your cluster and install argo, but there are too many efforts doing so. So the suggestion is always rely on optional-test-infra and get familiar with it can help you debug. https://github.com/kubeflow/testing/tree/master/aws this should be good resources to get started

**Comment by DavidSpek** [comment]
@PatrickXYS Trial and error it is then haha. I have a permanent cluster running Kubeflow, and thus Argo, but I wasn't sure about the AWS specific configs (and I couldn't test those on-prem either).

**Comment by PatrickXYS** [comment]
I tested on my PR and confirm tests triggering is working properly regardless test failed. 

https://github.com/kubeflow/kubeflow/pull/5642#issuecomment-786863791

@kimwnasptd  My suggestion is to first test against the https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml#L10-L16 to make sure the crud-web-apps unit test succeed, and then we move forward to other PR.

**Comment by kimwnasptd** [comment]
Adding also a comment here so that we have all the necessary context in the issue. We fixed CI tests for the common frontend code. The following are the key takeaways:
1. Ther 63 chars limitation, which means that the workflow's name can not be more than ~12 chars
2. The name of the workflow needs to be DNS1123 competible, since it will be used in the Argo Worfklow CR's name
2. We use the browserless/chrome:1.44-chrome-stable image for running the tests, which includes both node and chrome

The next step is to now deep dive into how we would utilize Kaniko for building our images as postsubmit scripts

**Comment by DavidSpek** [comment]
@kimwnasptd If you give me some information regarding what you want I can rework my PR into that. Obviously a separate workflow for each component. Do we want to have the git commit hash as the tag? Does the branch name also need to be in the tag?

**Comment by kimwnasptd** [comment]
> @kimwnasptd If you give me some information regarding what you want I can rework my PR into that.

Sure! Lets first document here the more basic things, like
1. the names of the ECR registries we will use
2. how someone could run the produced Argo Workflow in a cluster and test the results

Having the above sorted up and smaller workflows for the different components would be a pretty good first step. Once I've managed to run the workflow locally and use Kaniko I'll be back with next steps for your PR #5640

**Comment by PatrickXYS** [comment]
@kimwnasptd  I think you should tell current blocking PR in kubeflow/kubeflow to rebase from master, that can help them move forward

**Comment by kimwnasptd** [comment]
@PatrickXYS  wrt the ECR registries we need, I'd like to first ask some questions that I have after reading the docs.From what I understand from the [AWS ECR](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html) docs the URI of a public image will be `public.ecr.aws/registry_alias/repository_name:image_tag`. 

This `repository_name` is not the same with what the [GCP docs](https://cloud.google.com/container-registry/docs/overview#repos) describe as a repository. In GCP's case a repository is a grouping of many container images:tags. But in ECR the `repository_name` is equivalent to GCP's `image` name.

If the above holds then I have the following questions:
1. From your message above https://github.com/kubeflow/kubeflow/issues/5482#issuecomment-786779510 do you only want us to provide you a list of different images, like jupyter-web-app, centraldashboard etc?
2. Do you need the full list right now or can we first provide some images we want and add more ones as we go?
3. What is going to be the `registry_alias` of the images' URI?

**Comment by kimwnasptd** [comment]
> @kimwnasptd I think you should tell current blocking PR in kubeflow/kubeflow to rebase from master, that can help them move forward, given the fact you have made the test pass

Yes, this will need a heads up on the opened PRs. I'll give it a round

**Comment by DavidSpek** [comment]
@kimwnasptd You can create an image using Kaniko from a git URL directly, so all that would be needed to run locally is a PodSpec. The workflow itself is not very difficult, so shouldn't take long to implement.

**Comment by DavidSpek** [comment]
Regarding the image name, wouldn't it be something like `public.ecr.aws/kubeflow-kubeflow/central-dashboard:branch-git_hash`?

**Comment by PatrickXYS** [comment]
> 1. From your message above #5482 (comment) do you only want us to provide you a list of different images, like jupyter-web-app, centraldashboard etc?

Yes a list with repository names

> Do you need the full list right now or can we first provide some images we want and add more ones as we go?

Well, you can first do a few, and after experimentation on your side, we can do the rest of them. 

> What is going to be the registry_alias of the images' URI?

This still uses the default `j1r0q0g6 ` , before we have all WG onboard the public ECR, we might won't come to the formalized registry_alias

**Comment by kimwnasptd** [comment]
@PatrickXYS here's an initial list for images/registries we will need. We might add some more down the road
* jupyter-web-app
* notebook-controller
* centraldashboard
* admission-webhook
* profile-controller
* tensorboards-web-app
* tensorboard-controller

cc @StefanoFioravanzo @elikatsis @yanniszark @thesuperzapper

**Comment by DavidSpek** [comment]
@kimwnasptd For the sake consistency and readability, I'd like to suggest using `central-dashboard` instead of `centraldashboard`.

**Comment by PatrickXYS** [comment]
> @PatrickXYS here's an initial list for images/registries we will need. We might add some more down the road
> 
> * jupyter-web-app
> * notebook-controller
> * central-dashboard
> * admission-webhook
> * profile-controller
> * tensorboards-web-app
> * tensorboard-controller
> 
> cc @StefanoFioravanzo @elikatsis @yanniszark @thesuperzapper

FYI This is done

**Comment by DavidSpek** [comment]
@kimwnasptd It seems `access-management` is missing. Is this on purpose?
