### ISSUE TITLE
Cards Recent Pipelines/Runs in Central Dashboard should be populated with items in the selected namespace

### ISSUE THREAD

**Issue by arllanos** [kubeflow/kubeflow#5484]
/kind feature

**Why you need this feature:**
Central Dashboard tries to populate *Recent Pipelines* and *Recent Pipeline Runs* cards with the 5 most recently created Pipelines and Runs respectively with no regards to selected namespace.
However, it is not compatible with the changes done to resolve issue [#4197](https://github.com/kubeflow/pipelines/issues/4197). That is, we should populate the card with the last 5 elements that correspond to the selected namespace. 
On the other hand, in multiuser mode and with the new Pipeline API, it is mandatory to pass namespace to both, the pipelines and runs endpoints, otherwise we get an error.

**Describe the solution you'd like:**
Make Central Dashboard to pass selected namespace to the corresponding Pipelines API endpoints.
If no namespace is selected, then do not populate the card but show a message like 'Choose a namespace to see Pipelines/Runs'. In other words, the behavior should be similar to the *Recent Notebooks* cards

**Anything else you would like to add:**
This issue is related to [#4197](https://github.com/kubeflow/pipelines/issues/4197) resolved by PR [4835](https://github.com/kubeflow/pipelines/pull/4835), so Central Dashboard can be compatible with that.

**Comment by yanniszark** [comment]
cc @kubeflow/wg-notebooks-leads for triage
