### ISSUE TITLE
Cannot open kubeflow dashboard on microk8s kubeflow

### ISSUE THREAD

**Issue by AxdorphCoder** [kubeflow/kubeflow#5485]
/kind bug

**What steps did you take and what happened:**

I followed this tutorial exactly
https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#2-access-an-ubuntu-terminal

sudo snap install microk8s --classic
sudo microk8s status --wait-ready

sudo usermod -a -G microk8s $USER
sudo chown -f -R $USER ~/.kube

microk8s.enable dns dashboard storage
microk8s.enable kubeflow

Got 
Congratulations, Kubeflow is now available.

The dashboard is available at http://10.64.140.43.xip.io
				

    Username: admin
    Password: ***************

To see these values again, run:

    microk8s juju config dex-auth static-username
    microk8s juju config dex-auth static-password

**What did you expect to happen:**
When I navigate to http://10.64.140.43.xip.io
I get DNS_PROBE_FINISHED_NXDOMAIN

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

when I run 
microk8s kubectl get all --all-namespaces 
I get 
...
kubeflow          service/kubeflow-dashboard                     ClusterIP      10.152.183.158   <none>         8082/TCP  
...

but when I run 
microk8s status 
I get kubeflow under disabled

  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    gpu                  # Automatic enablement of Nvidia CUDA
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    istio                # Core Istio service mesh services
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    storage              # Storage class; allocates storage from host directory
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    jaeger               # Kubernetes Jaeger operator with its simple config
    keda                 # Kubernetes-based Event Driven Autoscaling
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    multus               # Multus CNI enables attaching multiple network interfaces to pods
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    traefik              # traefik Ingress controller for external access

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): Cannot open dashboard... using microk8s 1.20 stable built in kubeflow
- kfctl version: (use `kfctl version`):
- Kubernetes platform: microk8s 1.20 stable
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:58:11Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:59:05Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS (desktop)

**Comment by DavidSpek** [comment]
microk8s uses the Kubeflow charms. It might be worth creating an issue at https://github.com/juju-solutions/bundle-kubeflow.

**Comment by ajpotts** [comment]
I was also not able to view the kubeflow dashboard using the url provided from this command: microk8s.enable kubeflow

As a short term fix, you could set up port forwarding.  I modeled this article:
https://microk8s.io/docs/addon-dashboard

To find the kube-flow dashboard:
> microk8s kubectl get services --all-namespaces | grep dashboard 
Once you see the namespace and port number you can set up the port forwarding.  For me it was this:
> microk8s kubectl port-forward -n kubeflow service/kubeflow-dashboard  8083:8082

Then I could view the dashboard here:
http://localhost:8083/

**Comment by tomalbrecht** [comment]
I cannot access kubeflow either using microk8s v1.20, following this https://microk8s.io/docs/addon-kubeflow documentation and described in an older issue here https://github.com/ubuntu/microk8s/issues/1366#issuecomment-654411307.

Any suggestions, @knkski?

```bash
KUBEFLOW_HOSTNAME=lenovo-lan microk8s.enable kubeflow

microk8s.kubectl edit configmap -n kube-system coredns
# edit the line that says forward . 8.8.8.8 8.8.4.4 to read forward . X.X.X.X, where X.X.X.X is a local 
# DNS resolver that is aware of  lenovo-lan. In my case: 192.168.178.1 as that's the IP of my local router.

# sudo iptables -P FORWARD ACCEPT
```

@ajpotts you are talking about k8 dashboard, not about the kubeflow dashboard.

Access over SOCKS-Proxy as described here https://microk8s.io/docs/addon-kubeflow does work though. Maybe you wannt to try this one, @AxdorphCoder?

**Comment by tomalbrecht** [comment]
Opened an issue at microk8s https://github.com/ubuntu/microk8s/issues/2075
