### ISSUE TITLE
Cannot open dashboard with minikube

### ISSUE THREAD

**Issue by hebo-yang** [kubeflow/kubeflow#5486]
/kind bug

**What steps did you take and what happened:**
Following instructions here https://www.kubeflow.org/docs/started/workstation/minikube-linux/. All pods kubeflow and istio-system pods are in running state (except for istio-security-post-install-release-1.3-latest-daily-8t9b8 being completed)

export INGRESS_HOST=$(minikube ip)
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')

However http://<INGRESS_HOST>:<INGRESS_PORT>(in my case 192.168.49.2:31380 is not responding from browser or curl).

`kubectl logs centraldashboard-67767584dc-2bxgt -n kubeflow

> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve

> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js

Initializing Kubernetes configuration
"other" is not a supported platform for Metrics
Using Profiles service at http://10.98.236.186:8081/kfam
Server listening on port http://localhost:8082 (in production mode)
`

**What did you expect to happen:**
Expecting to connect to dashboard via browser

**Anything else you would like to add:**

**Environment:**

- Kubeflow version: https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) minikube
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): macOS Catalina Version 10.15.7

**Comment by hebo-yang** [comment]
![Screen Shot 2020-12-26 at 9 00 05 PM](https://user-images.githubusercontent.com/66688603/103164231-7ad36f00-47bd-11eb-8a61-0f7236800632.png)

**Comment by peteboothroyd** [comment]
I was getting this too following the minikube tutorial. Running `minikube service istio-ingressgateway -n istio-system` showed a number of URLs and the mapping to the ports defined in the resource (the tutorial specifies http2), however strangely the only one that worked was the URL http://127.0.0.1:65365 (for reference the tutorial http://<INGRESS_HOST>:<INGRESS_PORT> gave http://192.168.49.2:31380). I don't really know kubernetes very well so I'm not sure what exactly is going on here, but perhaps it can help you or other people who end up here.

**Comment by hebo-yang** [comment]
Thanks @peteboothroyd for the note! Mine seems to be a slightly different problem. I am on Mac and minikube or istio seem to have problems with docker engine driver on Mac (or everywhere). I changed to use `minikube start --cpus 6 --memory 12288 --disk-size=100g --driver=hyperkit` and it finally worked.
