### ISSUE TITLE
current kfctl_aws can't to deploy kubeflow 1.2 in AWS China 

### ISSUE THREAD

**Issue by jerryjin2018** [kubeflow/kubeflow#5487]
/kind bug
current kfctl_aws(kfctl_aws.v1.2.0.yaml) can't to deploy kubeflow in AWS China 

**What steps did you take and what happened:**
1) I downloaded the latest yaml file for kfctl_aws from official site ( https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml )
2) I built my EKS cluster in AWS China ( Ningxia ) region through eksctl succesfully
3) I tried the steps in the link ( https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ ), but can't deploy the Kubeflow successfully.
4) The main issue is "ImagePullBackOff" after I checked the status of pods through command ( kubectl get po -n namespaces)
The reason behind this is that the hosts in China mainland can't to pull the images from gcr.io site.  

5) I modify almost all the yaml files inside https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz with images migrated from gcr.io.
6) I also found that the issue with difference between AWS global and AWS China -- In the Beijing and Ningxia Regions, the Amazon Resource Name (ARN) syntax includes a cn. -- arn:aws-cn in AWS China rather than arn:aws( https://docs.amazonaws.cn/en_us/aws/latest/userguide/ARNs.html )
7) After changed and troubleshooted many points, I can get Kubeflow the web portal in AWS China region.

**What did you expect to happen:**
1) I expect there is general common for assign images repositories location. such as: gcr.io and docker, even others through environment variables.
2) To change aws arn from aws to aws-cn for AWS China region's users.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2 with build version v1beta1
- kfctl version: (use `kfctl version`):   kfctl v1.2.0-0-gbc038f9

- Kubernetes platform: (e.g. `minikube`) 1.18

- Kubernetes version: (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:
"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", G
itTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Comment by yanniszark** [comment]
cc @kubeflow/aws

**Comment by jerryjin2018** [comment]
Hi all,
May I know any time point for this issue? Thank you.

**Comment by HarborZeng** [comment]
Need an mirror that can be accessed in China or a solution for proxy

**Comment by jerryjin2018** [comment]
Is there any way to solve the issue?

**Comment by jerryjin2018** [comment]
so nobody cares about this issue?

**Comment by jbottum** [comment]
@jerryjin2018 thanks for reporting this.   I believe this has been escalated to the AWS team, who would be the group to support this request as-is.    If you cannot get appropriate help there, then you might consider asking at a Community Meeting (on Tuesday) or potentially looking to a 3rd party that supports Kubeflow on AWS.     Many users are running Kubeflow 1.2 and 1.3 in production so I am confident that we can find a solution for you.
