### ISSUE TITLE
Cannot login into kubeflow

### ISSUE THREAD

**Issue by jhebelerDS** [kubeflow/kubeflow#5488]
Congratulations, Kubeflow is now available.

The dashboard is available at http://10.64.140.43.xip.io

    Username: admin
    Password: XC0LELZ0XWB2A7HRASE4S00NKGNSTX

To see these values again, run:

    microk8s juju config dex-auth static-username
    microk8s juju config dex-auth static-password

I get the prompt at the URL above.  And paste in the values above.  But the login is rejected.  Also when I run the microk8s commands directly above they return nothing.  Any idea as to what is going on?

Thank you!..

**Comment by yanniszark** [comment]
cc @RFMVasconcelos @knkski 
Should this issue be moved to https://github.com/juju-solutions/bundle-kubeflow?

**Comment by AahanSingh** [comment]
Hey,
I had the same issue. 
For some reason the username and password shown after running `microk8s enable kubeflow` isn't actually set as the the username and password.
After kubeflow is enabled follow the instructions at https://github.com/kubeflow/kubeflow/issues/5429#issuecomment-743259520 and you'll be good to go.

**Comment by RFMVasconcelos** [comment]
Hey @AahanSingh! Thank you for your comment!

We have identified this issue, which appeared as Microk8s `--classic` moved to v1.20 and charmed Kubeflow moved from Ambassador to Istio v1.5. We have fixed the issue, but to get that fix right now you need to install microk8s as `sudo snap install microk8s --classic --channel=latest/edge`.

Alternatively, you can define the passwords as you mention.

**Comment by jhebelerDS** [comment]
I found a work around by 
microk8s juju config dex-auth static-username=admin
microk8s juju config dex-auth static-password=1234
I am now in but...  when I go to create a jupter notebook server the other name spaces are not listed although they are listed in the kubernetes dashboard such as kube-public, kube-node-lease, and kube-system.  I was able to create a jupyter server but only in my admin namespace.  Thank you so much for your help - I am sure you realize I am just starting out and I really appreciate your help.

**Comment by knkski** [comment]
@jhebelerDS: Are you expecting to be able to create notebooks in those namespaces? Those namespaces are generally reserved for usage by Kubernetes itself, see here: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces

**Comment by DavidSpek** [comment]
I am closing this issue as it is not related to the code in this repository. If you continue to encounter problems with microk8s please create an issue over at https://github.com/juju-solutions/bundle-kubeflow.
/close
