### ISSUE TITLE
Notebook Servers page doesn't show anything at microk8s.kubeflow

### ISSUE THREAD

**Issue by shintaro-uchiyama** [kubeflow/kubeflow#5489]
# problem
I installed kubeflow on macOS by using multipass and microK8s and I cloud show kubeflow dashboard page.
But notebook servers and artifact store page doesn't show properly like below.

- notebook servers page doesn't show anything
  - I also captured console tab because some error is appeared.
<img width="1168" alt="スクリーンショット 2020-12-31 15 27 35" src="https://user-images.githubusercontent.com/25105373/103397925-b2effe80-4b7d-11eb-9570-e348be77dfc1.png">

- artifact store page only show sorry text message
<img width="1676" alt="スクリーンショット 2020-12-31 15 39 16" src="https://user-images.githubusercontent.com/25105373/103398123-a029f980-4b7e-11eb-8e88-4a27c3a7a5df.png">

Is there any way to show notebook servers and artifact store page?

# what i did

I did these command referencing this page
https://www.kubeflow.org/docs/started/workstation/getting-started-macos/

```zsh
$ multipass launch --name kubeflow --mem 16G --disk 50G --cpus 4
$
$ multipass shell kubeflow
ubuntu@kubeflow:~$ sudo snap install microk8s --classic
sudo snap install microk8s --classic --channel=latest/edge
microk8s (1.20/stable) v1.20.0 from Canonical✓ installed
ubuntu@kubeflow:~$
ubuntu@kubeflow:~$ sudo microk8s status --wait-ready
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
ubuntu@kubeflow:~$
ubuntu@kubeflow:~$ sudo usermod -a -G microk8s $USER
ubuntu@kubeflow:~$ sudo chown -f -R $USER ~/.kube
$
$ multipass shell kubeflow
ubuntu@kubeflow:~$ microk8s.enable kubeflow
Password [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]:
...
Waited 405s for operator pods to come up, 1 remaining.
Operator pods ready.
Waiting for service pods to become ready.
Congratulations, Kubeflow is now available.

The dashboard is available at http://10.64.140.43.xip.io
ubuntu@kubeflow:~$ 
ubuntu@kubeflow:~$ sudo iptables -P FORWARD ACCEPT
ubuntu@kubeflow:~$ 
ubuntu@kubeflow:~$  sudo -- sh -c "echo '10.64.140.43\t10.64.140.43.xip.io' >> /etc/hosts"
```

I added 127.0.0.1:999 SOCKS proxy to network and exec proxy ssh.
```zsh
$ sudo ssh -i /var/root/Library/Application\ Support/multipassd/ssh-keys/id_rsa -D9999 ubuntu@192.168.64.10
```

So I could access to kubeflow dashboard from chrome browser but this issue happened.

**Comment by DavidSpek** [comment]
microk8s uses the Kubeflow charms. It might be worth creating an issue at https://github.com/juju-solutions/bundle-kubeflow.

**Comment by shintaro-uchiyama** [comment]
@DavidSpek 
Thank you for your advice!
I close this issue and create new issue at https://github.com/juju-solutions/bundle-kubeflow🙇‍♂️

**Comment by shintaro-uchiyama** [comment]
I move issue to https://github.com/juju-solutions/bundle-kubeflow/issues/282.
