### ISSUE TITLE
Tensorflow no longer working in the GPU image (if you build from HEAD)

### ISSUE THREAD

**Issue by ojarjur** [kubeflow/kubeflow#549]
It looks like tf-nightly-gpu upgraded to rely on CUDA 9.0, but the GPU version of the notebook image is based on an upstream image with CUDA 8.0

This came up in #544, as the step to install the notebook extension winds up importing the tensorflow package, and that import fails when it tries to find libcublas.so.9.0.

I'm testing a change now that will update the base image, and if that works then I will include a fix in #544

**Comment by jlewi** [comment]
Do we know which version of TF the problem started in ?

**Comment by ankushagarwal** [comment]
> but the GPU version of the notebook image is based on an upstream image with CUDA 8.0

We use cuda 8.0 for tf 1.4x.

We use cuda 9.0 for tf 1.5x and higher 

https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/releaser/components/workflows.libsonnet#L135

**Comment by ojarjur** [comment]
The release may be smart enough to pick the right base image, but the Makefile is hard-coded to use both `tf-nightly-gpu` and `nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04`, which is an invalid combination.

BTW, I think `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` may also be problematic. That image only includes light-weight stubs of libcuda that are sufficient for building. For runtime usage, the full library is in `nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04` (note the "runtime" instead of "devel").

**Comment by ojarjur** [comment]
@ankushagarwal @jlewi Do either of you know why we landed on using the "devel" nvidia image as a base instead of the "runtime" one?

**Comment by ankushagarwal** [comment]
My understanding is that we deprecated the Makefile in favor of the argo [workflow](https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/releaser/components/workflows.libsonnet) but never deleted the Makefile.

My understanding regarding devel v/s runtime is that [devel is a superset of runtime](https://hub.docker.com/r/nvidia/cuda/)

```
* runtime: extends the base image by adding all the shared libraries from the CUDA toolkit.
Use this image if you have a pre-built application using multiple CUDA libraries.
* devel: extends the runtime image by adding the compiler toolchain, the debugging tools, the headers and the static libraries.
Use this image to compile a CUDA application from sources.
```

**Comment by ojarjur** [comment]
@ankushagarwal You are right regarding the Docker images; I misread the Dockerfiles and thought devel was based on "base" instead of "runtime". You can safely disregard my concern about that.

If deleting the Makefile is an option, then that would be a sufficient fix for this bug.

**Comment by jlewi** [comment]
We can delete the Makefile.
