### ISSUE TITLE
Problem with Kubeflow 1.2 cognito deployment on EKS

### ISSUE THREAD

**Issue by mabi08** [kubeflow/kubeflow#5490]
/kind bug

When I try to rollout the EKS cognito deployment for Kubeflow 1.2 I receive the following error:
![image](https://user-images.githubusercontent.com/50304545/103410500-b8dce400-4b6b-11eb-96d3-a46b58b30b6d.png)

Also the <code>admission-webhook-bootstrap-stateful-set</code> seems to crash:
![image](https://user-images.githubusercontent.com/50304545/103410519-e6299200-4b6b-11eb-8fe3-4db58479fe7f.png)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Downloaded kfctl in version 1.2
- Dowloaded https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml
- Added cognito settings to kfctl_aws.yaml (those have worked in version 1.1)
- kfctl apply -V -f kfctl_aws.yaml   

**What did you expect to happen:**
no errors thrown during kfctl apply

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I had kubeflow 1.1 already running and tried to upgrade to 1.2, but I receive those errors even on a fresh cluster.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2
- kfctl version: (use `kfctl version`): v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`): amzn linux 2

**Comment by yanniszark** [comment]
cc @kubeflow/aws

**Comment by jbottum** [comment]
@mabi08 did you get this resolved?

**Comment by mabi08** [comment]
Hey I guess it was an issue with my proxy configuration. I ran the same config directly from a pod within the cluster and it works. Issue can be closed.
