### ISSUE TITLE
User anonymous@kubeflow.org is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: anonymous

### ISSUE THREAD

**Issue by mgiessing** [kubeflow/kubeflow#5491]
/kind bug

**What steps did you take and what happened:**
Deployed KubeFlow and tried to create a notebook server, but I got an error stating:

`User anonymous@kubeflow.org is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: anonymous`

According to [https://github.com/kubeflow/kubeflow/issues/4731](url) the change is already implemented and the envoy.lua filter seems to be working as the user anonymous@kubeflow.org is added.

Also the jupyter-web-app-deployment log seems to look good:
```
[...]
10.129.2.45 - - [31/Dec/2020 16:02:01] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
10.129.2.45 - - [31/Dec/2020 16:02:17] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
10.129.2.45 - - [31/Dec/2020 16:02:34] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
10.129.2.45 - - [31/Dec/2020 16:02:51] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
10.129.2.45 - - [31/Dec/2020 16:03:07] "GET /api/namespaces/anonymous/notebooks HTTP/1.1" 200 -
```

However instead of the user `None` is not authorized I'm now getting user `anonymous@kubeflow.org` is not authorized.

**What did you expect to happen:**
Create the notebook server without any (permission-)problems.

**Anything else you would like to add:**
This is an IBM Power architecture deployment (ppc64le), therefore I have used the following kfctl file in order to pull the relevant ppc64le images:
https://github.com/lehrig/manifests/blob/create-openshift-ppc64le-stack/kfdef/kfctl_openshift_ppc64le.v1.2.0.yaml

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the KubeFlow dashboard): 
`build version v1beta1`
- kfctl version: (use `kfctl version`): 
`kfctl v1.2.0-0-gbc038f9`
- Kubernetes platform: (e.g. `minikube`)
OpenShift 4.3.33
```
Client Version: 4.3.33
Server Version: 4.3.33
Kubernetes Version: v1.16.2+295f6e6
```
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
RHEL8.2

**Comment by yanniszark** [comment]
@mgiessing the Notebook UI uses `SubjectAccessReview` to determine if your user has the necessary RBAC permissions to do certain actions. The user `anonymous@kubeflow.org` doesn't have the necessary permissions for accessing the Notebook UI endpoints and that's why you get this error.

You can give the user the necessary permissions by creating a RoleBinding. The `kubeflow-edit` ClusterRole should give your user edit access for all Kubeflow Services:
```sh
kubectl create rolebinding -n kubeflow --clusterrole=kubeflow-edit --user=anonymous@kubeflow.org
```

For more info on Kubernetes RBAC, see:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

Let me know if that fixes your issue.

**Comment by mgiessing** [comment]
Thanks for your reply @yanniszark !
I added the rolebinding (I needed to give it a name, so I used "juypter-webapp", but I guess that name can be arbitrary) but the error still persists. The rolebinding looks like this now:

```
[root@edb-da0d-bastion kfapp]# oc describe rolebinding -n kubeflow jupyter-webapp
Name:         jupyter-webapp
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  kubeflow-edit
Subjects:
  Kind  Name                    Namespace
  ----  ----                    ---------
  User  anonymous@kubeflow.org  
```

 However I've seen that there was already an active rolebinding called "jupyter-web-app-jupyter-notebook-role-binding" and that looks like this:

```
[root@edb-da0d-bastion kfapp]# oc describe rolebinding jupyter-web-app-jupyter-notebook-role-binding
Name:         jupyter-web-app-jupyter-notebook-role-binding
Labels:       app=jupyter-web-app
              kustomize.component=jupyter-web-app
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"jupyter-web-app","kus...
Role:
  Kind:  Role
  Name:  jupyter-web-app-jupyter-notebook-role
Subjects:
  Kind            Name                    Namespace
  ----            ----                    ---------
  ServiceAccount  jupyter-notebook        
  User            anonymous@kubeflow.org  
```

Not sure if those two rolebindings can somehow interfere each other.

**Comment by lehrig** [comment]
Had the same issue but fixed it with using the correct namespace (anonymous is relevant, not kubeflow!):
`kubectl create rolebinding -n anonymous --clusterrole=kubeflow-edit --user=anonymous@kubeflow.org`

**Comment by Dimiftb** [comment]
Hi @lehrig,

I attempted your solution, however I'm still getting the same issues. Could you maybe share some more details? 
I created the role binding following your advice: 
`kubectl create rolebinding -n anonymous --clusterrole=cluster-admin --user=anonymous@kubeflow.org my-role-binding`

`kubectl get rolebinding -n anonymous` gives: 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/26279721/112180074-217bb000-8bf3-11eb-8c1f-6a25ce08baaa.png">

It seems that the other 3 role bindings that are automatically created when the user profile is created are completely useless.

`kubectl describe rolebinding my-role-binding -n anonymous` gives: 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/26279721/112180182-39ebca80-8bf3-11eb-9bcb-89d021e1385b.png">

When I try to create a new notebook from the dashboard or list the already created notebooks, I'm still getting errors like: 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/26279721/112180296-57b92f80-8bf3-11eb-9c1f-c78b484afcac.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/26279721/112180738-b8486c80-8bf3-11eb-9c39-3487d35b316a.png">


I'm running a bare metal Kubernetes cluster. 

My goal is to allow users to log into the dashboard and create their own notebooks where they can write and run code. I also experimented with jupyterhub, however the Kubeflow dashboard seems like a better solution as individual users can select resources according to their needs. 

Could anyone shed some light? Thanks for your help guys.

**Comment by lehrig** [comment]
Looks more like https://github.com/kubeflow/kubeflow/issues/4731

-> check:
1. that you have have the anonymous filter component deployed for single-user installations
2. your istio envoy filter succeeds in weaving anonymous@kubeflow.org into requests

**Comment by ryanwcyin** [comment]
I have a similar issues with multi tenancy kubeflow installed. And, not just anonymous not working, other profiles are not working for notebook server as well.

**Comment by jbottum** [comment]
@ryanwcyin just checking on this.   did you get it resolved ?  Are you running on OpenShift?   Are you working with the OpenShift team for Kubeflow ?
