### ISSUE TITLE
Python backend code for crud-web-apps should run with lower versions than Python 3.6

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5494]
/kind feature

**Why you need this feature:**
Right now the Python backends and the common backend for our [crud-web-apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps) is using `f"strings"` in a lot of places. This requires an environment of Python 3.6 and up to be installed. A lot of linux installations come with a lower version of Python preinstalled, so it adds extra steps to new developers who might want to contribute code to the backend code.

**Describe the solution you'd like:**
Remove any use of `f"strings"` in the codebase and use the `"%s world" % var"` syntax for doing string substitutions.

**Anything else you would like to add:**
`f"string"` free code:
- [ ] [common backend](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend)
- [ ] [jupyter web app](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/jupyter/backend)

/assign kimwnasptd

**Comment by munagekar** [comment]
Python 3.5 has reached end of life. Adding backward support to an application(not library) does not make sense to me. Would kubeflow also support python 2, for developers with older python versions?

I think new contributors could be pointed to tools like virtualenv and pyenv instead. Eventually libraries would drop support for python 3.5 and this effort would be futile.

**Comment by DavidSpek** [comment]
It seems like the issue that actually needs to be solved is that Linux installations come with software installed that is EOL and isn't receiving security updates anymore.
