### ISSUE TITLE
Remove the use of f-strings from the Jupyter web app's backend

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5496]
/kind feature

This is a sub-issue from #5494.
We need to remove any `f"strings"` from the backend of the [Jupyter web app](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/jupyter/backend) in order to be able to use lower versions from Python 3.6 to run it.

/good-first-issue

**Comment by nellaivijay** [comment]
Let me, look on it

**Comment by kimwnasptd** [comment]
@nellaivijay that's great! 

As also mentioned in #5494 replace any `f"string"` with the classic `"%s" % val` substitution.
/assign @nellaivijay

**Comment by munagekar** [comment]
Python 3.5 has reached end of life. Adding backward support to an application(not library) does not make sense to me. Would kubeflow also support python 2, for developers with older python versions?

I think new contributors could be pointed to tools like virtualenv and pyenv instead. Eventually libraries would drop support for python 3.5 and this effort would be futile.

**Comment by thesuperzapper** [comment]
@kimwnasptd I don't see a reason for this, as every [Python version before 3.6 is now EOL](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions).

I think we should actually consider doing the opposite, as F-Strings are much easier to read.

**Comment by kimwnasptd** [comment]
Indeed, we shouldn't have an issue with using `f"strings"` even Python 3.6 is EOL.

Although I still prefer the use of `%` substitution so we can move on with both this and #5495

**Comment by DavidSpek** [comment]
@thesuperzapper @kimwnasptd  While I do not have a strong opinion of F-Strings versus `%` substitutions, I think this is something that people could get into a long debate about that ends up getting lost in time. For this reason I have added it to the future agenda items so a decision can be made and we can move on. I think the most important part consistency so whatever is chosen, should be applied to all the code in this repo.
