### ISSUE TITLE
Make IAP config robust to updating the Ingress

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#550]
See #545 for examples of how certain changes to the config (e.g. ingress) can cause the loadbalancer to end up in a misconfigured state  e.g.

- Loadbalancer uses the wrong path for the health check
- Timeout on the backend service reverts to the default of 30 seconds
- IAP gets disabled

We'd like to find a way to properly detect this and run the corrective steps. 
The script used in the envoy container as an init script has most of the commands needed to correct the setup; we just need to figure out how to trigger it when things break.

There are some ideas in #545.

**Comment by danisla** [comment]
Any change in the nodePort for the envoy service triggers re-creation of the backendService and breaks IAP. 

#552 is a working fix that uses a sidecar to periodically verify that the nodePort on the envoy service has not changed. If it does change, the script from the initContainer is called again to fix it up. After the script completes, it sends a signal to the envoy admin server to restart it with the new config.

**Comment by danisla** [comment]
https://github.com/ksonnet/ksonnet/issues/200 is related to the issue regarding the nodeport changing whenever `ks apply` is run.

**Comment by jlewi** [comment]
Thanks

/assign @danisla

**Comment by jlewi** [comment]
@danisla looks like #552 has been committed. Should we close this issue or is there more work to be done to make it robust?
