### ISSUE TITLE
MountVolume.SetUp failed for volume "certs" : secret "cert-manager-webhook-tls" not found

### ISSUE THREAD

**Issue by kbentaleb** [kubeflow/kubeflow#5501]
Hello,

I'm trying to install Kubeflow (V1.0, V1.1 and V1.2) and for the 3 versions I have the same issue, the "cert-manager-webhook" pod stuck on ContainerCreating status, bellow the result of the describe pod command:

![Sélection_250](https://user-images.githubusercontent.com/7852160/103786122-5a68a780-503c-11eb-80ad-0746f163ce4d.png)

Secrets:
![Sélection_251](https://user-images.githubusercontent.com/7852160/103786734-0dd19c00-503d-11eb-9516-c06ef793c79a.png)

I'm using kubernetes 1.14 installed on Ubuntu 18.04

@yanniszark Do you have any suggestion please ?

Thank you
Khalid

**Comment by DavidSpek** [comment]
@kbentaleb I think this might be due to not having a  `--cluster-signing-cert-file` and `--cluster-signing-key-file` set for the controller-manager. 
https://github.com/kubeflow/pipelines/issues/4505

**Comment by psisoft** [comment]
@DavidSpek Thank you for the reply
No I found it already in the file /etc/kubernetes/manifest/kube-controller-manager.yaml

- --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
- --cluster-signing-key-file=/etc/kubernetes/pki/ca.key

Any others suggestions please ?

**Comment by kbentaleb** [comment]
@DavidSpek Thank you for the reply
No I found it already in the file /etc/kubernetes/manifest/kube-controller-manager.yaml

--cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
--cluster-signing-key-file=/etc/kubernetes/pki/ca.key
Any others suggestions please ?

**Comment by DavidSpek** [comment]
@kbentaleb Do you have the logs of the cache-deployer pod?

**Comment by kbentaleb** [comment]
@DavidSpek The cache-deployer pod isn't yet created !

**Comment by DavidSpek** [comment]
@kbentaleb Sorry, I completely misread the issue. Ignore my previous comments. 

Is it possible that it is related to https://github.com/jetstack/cert-manager/issues/2208, as you are running kubernetes 1.14 and the CRD version 0.11?

**Comment by kbentaleb** [comment]
@DavidSpek  I didn't run CRD independently, I just installed kubernetes then I was lanching kubeflow installation based on the kubeflow.org tutorial

**Comment by DavidSpek** [comment]
@kbentaleb That is the version shown in the screenshot and the one bundled with Kubeflow. According to the documentation for kubernetes versions under 1.16 a different deployment needs to be done. https://cert-manager.io/docs/installation/kubernetes/

If this is the case, the Kubeflow compatibility chart might need updating. 

I would try deploying cert-manager independently from Kubeflow and then deploying Kubeflow without cert-manager.

**Comment by kbentaleb** [comment]
@DavidSpek However in the documentation of kubeflow.org indicates that kubernetes 1.14 is compatible with kubeflow V0.7, V1.0, V1.1 and V1.2, I will upgrade to kubernetes 1.16 and see if the error persist. I will keep you informed of the result. Thanks

**Comment by DavidSpek** [comment]
@kbentaleb I have successfully installed on v1.17, v1.18, and have run for a while on v1.19 and am now running v1.20 and everything is working fine. If you have no reason to run an older version of Kubernetes I’d go with a newer release.

**Comment by kbentaleb** [comment]
@DavidSpek Yes It works with kubernetes V1.18. Thank you!
