### ISSUE TITLE
Running TensorBoards list

### ISSUE THREAD

**Issue by cn007b** [kubeflow/kubeflow#5509]
/kind question

**Question:**

I've added TensorBoard to my pipeline accordingly to [this doc](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#tensorboard), and all works flawless! 
After some time of using this pipeline I have bunch of finished experiments,
and in some of them I still have running TensorBoards (because stop button was not clicked).
Is there a simple way to find experiments with non-stopped TensorBoard?

**Comment by jbottum** [comment]
/area tensorboard
/priority p2
/
