### ISSUE TITLE
istio-init: iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)

### ISSUE THREAD

**Issue by AboorvaDevarajan** [kubeflow/kubeflow#5512]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Installed Kubeflow on a standalone existing kubernetes cluster by following these steps
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

```
wget https://github.com/kubeflow/kfctl/releases/download/v1.2.0/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
tar -xvf kfctl_v1.2.0-0-gbc038f9_linux.tar.gz 
export PATH=$PATH:`pwd`
export BASE_DIR=`pwd`/deploy
export KF_NAME=test-kubeflow

export KF_DIR=${BASE_DIR}/${KF_NAME}
mkdir -p ${KF_DIR}
cd ${KF_DIR}
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml"
kfctl apply -V -f ${CONFIG_URI}
```
Soon after the deployment, I can see some of the pods crashed and went into `Init:CrashLoopBackOff` state.

```
[root@f4n10 test-kubeflow]# kubectl get pods -n kubeflow
...
...
...
...
[root@f4n10 test-kubeflow]# kubectl get pods -n kubeflow
cache-deployer-deployment-6667847478-6b87v               0/2     Init:CrashLoopBackOff   16         61m
cache-server-bd9c859db-2nsfk                             0/2     Init:0/1                0          61m
metadata-writer-6d94ffb7df-phf6s                         0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-54989c9946-n4bcq                             0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-persistenceagent-7f6bf7646-jgswc             0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-scheduledworkflow-66db7bcf5d-zcpmf           0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-ui-756b58fb-p9tld                            0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-viewer-crd-58f59f87db-tnm5l                  0/2     Init:CrashLoopBackOff   16         61m
ml-pipeline-visualizationserver-6f9ff4974-s849q          0/2     Init:CrashLoopBackOff   16         61m
mysql-7694c6b8b7-wckvn                                   0/2     Init:CrashLoopBackOff   16         61m

...
...
```

**Cause:** `istio-init` container in the above pods failed with the following error:

```
[root@f4n10 test-kubeflow]# kubectl -n kubeflow logs mysql-7694c6b8b7-wckvn istio-init
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES+ iptables -t nat -N ISTIO_REDIRECT_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=

+ iptables -t nat -N ISTIO_REDIRECT
iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ dump
+ iptables-save
+ ip6tables-save

```

Looks like there is not enough permission for the pod to run iptables.

So as a workaround I added the below patch in `.cache/manifests/manifests-1.2.0/istio-1-3-1/istio-install-1-3-1/base/config-map.yaml` and redeployed kubeflow, after which the pods are back online.

```
securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
```

**What did you expect to happen:**

Not sure why `istio-init` container doesn't have enough permissions set in the securityConext to access the iptables, shouldn't those permissions be enabled by default in the istio config-map, or am I missing something here?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):   `v1.2.0`
- kfctl version: (use `kfctl version`):  `v1.2.0-0-gbc038f9_linux`
- Kubernetes platform: (e.g. `minikube`)  :  `Kubernetes v1.18`
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
```
[root@f4n10 test-kubeflow]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)
```

Thanks.

**Comment by DavidSpek** [comment]
It looks like all the pods that are in a CrashLoopBackOff are part of KFP.

**Comment by trog-levrai** [comment]
I had the same issue and had to use a similar workaround. In `.cache/manifests/manifests-1.2.0/istio-1-3-1/istio-install-1-3-1/base/config-map.yaml`, I removed the if statement lines 211 and 213 as I didn't know how to set `.Values.global.proxy.privileged` but If there is an easy way to do it I guess that would be the fix for my environment (minikube with podman as driver).

I'd be happy to give it a try if someone can indicate me how to set this variable :)
