### ISSUE TITLE
Create custom image from jupyter notebook with default interface from kubeflow.

### ISSUE THREAD

**Issue by danizavtz** [kubeflow/kubeflow#5516]
/kind question

**Question:**
I would like to know how to create a custom jupyter image with the launcher interface that comes default with kubeflow installation.

Following tutorials in official kubeflow documentation I was able to generate a custom image with default jupyter interface.

![defaultinterface](https://user-images.githubusercontent.com/3859647/104514636-55719e00-55d0-11eb-8a80-4e3eff3b18e1.PNG)

But I would like to create with kubeflow default interface:

![webappkueflow](https://user-images.githubusercontent.com/3859647/104514691-6c17f500-55d0-11eb-8639-04662ce272f6.PNG)

I couldn't find a tutorial that uses the base image from this link, that is the image that has the modified interface:
![image](https://user-images.githubusercontent.com/3859647/104516164-a84c5500-55d2-11eb-9c81-68e3f65b831d.png)

I too tried to use images container in this link as base image:

https://www.kubeflow.org/docs/reference/images/

named [jupyter-web-app], but it only generated an image that does not load the jupyter interface, after pointing a jupyter notebook server to start pointing to this image, I only receive error: 'no healthy upstream'

I think it is related to the way it starts the container that is different from [kubeflow documentation](https://www.kubeflow.org/docs/notebooks/custom-notebook/) to create a custom image:

Documentation states:
```
ENV NB_PREFIX /

CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```

jupyter-web-app has:

```
ENTRYPOINT ["python3"]
CMD ["main.py"]
```

Are there a base image to follow and build my custom image with kubeflow default interface? (I know in terms of functionality they do the same work, but it is for usability [do not break user experience]).

My Current Dockerfile:

```
# Base image Dockerfile (AWS Deep Learning Containers)
# https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.2.0/py3/Dockerfile.cpu

FROM gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu@sha256:87c49f386263b8b3f4ba104617b888a97dad4dd166984c1e1d679435f1763ba1

# Install python3 packages from requirements file. Don’t install package dependencies.
# Run 'pip3 check' to verify if installed packages have compatible dependencies.
COPY requirements.txt /tmp

RUN pip3 --no-cache-dir install --no-deps --requirement /tmp/requirements.txt && \
    pip3 check || true


COPY kf_ssh_key /home/root/.ssh/id_rsa
COPY kf_ssh_key.pub /home/root/.ssh/id_rsa.pub

WORKDIR /root
ENV NB_PREFIX /
ENTRYPOINT ["tini", "--"]

CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]

```

If I follow instructions from kubeflow documentation to use aws optimized images it gives me error 401.

> failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 1.2.0]: 401 Unauthorized

Changed only command FROM in Dockerfile:

`FROM 527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-1.15.2-notebook-cpu:1.2.0`

**Comment by DavidSpek** [comment]
@danizavtz To have the Lab interface you need to change the `CMD`. You start the interface by changing `jupyter lab` instead of `jupyter notebook`. 

There is a PR open to change the default. https://github.com/kubeflow/kubeflow/pull/5515

```
CMD ["sh","-c", "jupyter lab --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```

**Comment by danizavtz** [comment]
Thanks, it worked. @DavidSpek .

Maybe worth mention that in official kubeflow documentation. Include some lines showing the GUI possibles. Default Jupyter and Jupyter Lab.
Here is link for kubeflow website project in Github: https://github.com/kubeflow/website
