### ISSUE TITLE
Error by adding notebook server: 500 Internal Server Error

### ISSUE THREAD

**Issue by rastislavs** [kubeflow/kubeflow#5518]
/kind bug

**What steps did you take and what happened:**
In Kubeflow Central Dashboard, after navigating to `Notebook Servers` section and clicking on `+ New server` I get the following error at the bottom of the page:

```
500: There was an error trying to connect to the backend API. Http failure response for https://my-domain.me/jupyter/api/namespaces/my-namesapce/poddefaults: 500 Internal Server Error
```

The error does not seem to have any big impact, the notebook server can be started.

**What did you expect to happen:**
I would expect to not see the error.

**Anything else you would like to add:**
The same issue was already seen in the past and seems it was fixed in 2019 [here](https://github.com/kubeflow/kubeflow/pull/3845). Still, it appears in the latest Kubeflow release (v1.2.0.) with `jupyter-web-app` image tag `vmaster-ge4456300` (created on Aug 31, 2020):

See: https://github.com/kubeflow/kubeflow/issues/3770

See: https://github.com/kubeflow/kubeflow/issues/3872

**Environment:**
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version v1beta1
- kfctl version: [kfctl_istio_dex.v1.2.0.yaml](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.2.0.yaml)
- Kubernetes platform: vanilla Kubernetes
- Kubernetes version: v18.10
- OS: Ubuntu 18.04

**Comment by DavidSpek** [comment]
@rastislavs Can you provide the logs of the Jupyter Web App pod?
