### ISSUE TITLE
Enabling kubeflow on microk8s 

### ISSUE THREAD

**Issue by TosinAina** [kubeflow/kubeflow#5520]
/kind bug

**What steps did you take and what happened:**
I installed microk8s using `sudo snap install microk8s --classic`,
I enabled dns, dashboard and storage with `microk8s enable dns dashboard storage`,
I tried enabling kubeflow with `microk8s enable kubeflow`, inputted the password and it prompted me to add `--ignore-min-mem`,
I tried enabling kubeflow with `microk8s enable kubeflow --ignore-min-mem`, inputted the password and it gave me this error message 

Kubeflow could not be enabled:
error: deployment "calico-kube-controllers" exceeded its progress deadline

Command '('microk8s-kubectl.wrapper', '-nkube-system', 'rollout', 'status', 'deployment.apps/calico-kube-controllers')' returned non-zero exit status 1

**What did you expect to happen:**
I expected kubeflow to be enabled and also get a link to access the dashboard

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: microk8s
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-15T02:50:16Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): ubuntu 20.04 focal

**Comment by DavidSpek** [comment]
@TosinAina This installation method actually uses the juju bundle for Kubeflow. To get better support, could you move your issue to https://github.com/juju-solutions/bundle-kubeflow/issues?

**Comment by TosinAina** [comment]
Thank you @DavidSpek
