### ISSUE TITLE
Adding DataSource to the PVC Created with Notebook Server

### ISSUE THREAD

**Issue by munagekar** [kubeflow/kubeflow#5523]
/kind feature

**Why you need this feature:**
- I would like to prepopulate the pvc created with Notebook Server with volume snapshot data. Currently I can do this manually with kubectl. It would be nice if we could configure datasource with Jupyter Notebook UI.
REF: https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/

**Describe the solution you'd like:**
UI could expose an option to set datasource.

**Comment by ConverJens** [comment]
This would be a great enhancement!

**Comment by DavidSpek** [comment]
I've actually already implemented this in the Volumes Web App, along with creating snapshots, but this is being blocked by https://github.com/kubeflow/kubeflow/pull/5844.
