### ISSUE TITLE
Central Dashboard lacks rate limiting

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/kubeflow#5527]
/kind bug
/area centraldashboard

At the moment the central dashboard does not employ rate limiting. This means it is a potential target for DoS attacks. PR https://github.com/kubeflow/kubeflow/pull/5521 adds rate limiting to the Central Dashboard. However, the rate to limit by and what requests should all be limited is up for discussion

/assign @kubeflow/wg-notebooks-leads

**Comment by kimwnasptd** [comment]
The Central Dashboard is not the first cluster component that is vulnerable to a DoS attack, it's the cluster's Load Balancer.

In order for a request to reach the Dashboard it must first 
1. pass this load balancer
2. pass the authentication system (Dex, IAP etc)
3. finally hit the central dashboard

So this means we have two cases, when the cluster is publicly accessible or it's on prem. In case of a public cluster then ensuring the load balancer is not DoS vulnerable is up to each respective cloud provider. 

In case of on-prem then it's not a common thing to expose the cluster to the public. But even that's the case, it should have a distinct load balancing mechanism in place, which again is responsible for protecting the cluster from DoS attacks.

**Comment by DavidSpek** [comment]
I'm no security expert, but just because it is not the first point of attack doesn't seem like a good reason to not address the issue. Security patches for windows are still important even if the computers are behind a firewall, otherwise something like WannaCry can propagate through your network. It might not only be to protect against attacks, but potentially some other configuration error or rouge process.

**Comment by kimwnasptd** [comment]
Rate-limiting should not be something that each service of the cluster needs to implement. This will add a significant development burden. Instead it should be configured in a central place, which is the sevice mesh.

The architectural design behind k8s services is that they don't need to implement rate-limiting themselves. This is something for the cluster admin or platform provider to configure. This is why we have service meshes and a load balancer.

Istio, which is the service mesh layer, provides a mechanism for rate-limiting which also configures the load balancer.
https://preliminary.istio.io/latest/docs/tasks/policy-enforcement/rate-limit/

**Comment by DavidSpek** [comment]
I feel a bit dump now for completely overseeing Istio haha. Makes sense, and hereby closing the issue and PR.
