### ISSUE TITLE
Enable TPUs with Kubeflow v1.2

### ISSUE THREAD

**Issue by knave07** [kubeflow/kubeflow#5533]
/kind bug

**What steps did you take and what happened:**
I wanted to use TPU's with Kubeflow, but to enable TPUs the **Cluster Should be VPC-native**.
With the [current flow](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) of installing Kubeflow v1.2 on GCP, I didn't find any documentation or any support for this. I found an [old page to enable-tpu](https://www.kubeflow.org/docs/gke/customizing-gke/#add-cloud-tpus-to-your-cluster) but I think this is of no use with Kubeflow v1.2 .

So, I made some changes to the upstream manifests to make the cluster VPC-native and enable-tpu. Changes that I made in gcp/v2/cnrm/cluster/cluster.yaml:
```yaml
  enableTpu: true
  ipAllocationPolicy:
    servicesSecondaryRangeName: services     
    clusterSecondaryRangeName: pods
```
I manually added `services` and `pods` inside the default subnet in GCP.
 
After running `make apply` the cluster got created with TPU, but now the envoy-ingress is showing error. **[All backend services are in UNHEALTHY state error.]**  
On opening the kubeflow endpoint `https://{}.endpoints.{}.cloud.goog`, I am seeing a 404 error.
Is there any document or anything which can guide me to enable TPUs with Kubeflow v1.2?

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.2
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): macOS Catalina

**Comment by DavidSpek** [comment]
@knave07 I'm guessing this is probably unrelated to your issue, but I would recommend using the `kfctl` version that belongs with the release you are trying to install. So for Kubeflow 1.2: https://github.com/kubeflow/kfctl/releases/tag/v1.2.0.

**Comment by knave07** [comment]
I will give it a try. 
We are already using Kubeflow v1.1 installed through the management cluster and wanted to upgrade to Kubeflow v1.2 with TPU support. Our current cluster is kinda stable now and not facing many issues, I am a little bit worried if Kubeflow with [kfctl_k8s_istio](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/) will have any issues.

**Comment by munagekar** [comment]
I think this issue could be moved to https://github.com/kubeflow/gcp-blueprints.

**Comment by DavidSpek** [comment]
Closing this issue as a new one has been created. https://github.com/kubeflow/gcp-blueprints/issues/190
/close
