### ISSUE TITLE
seldon-core not installed as part of kubeflow 1.2

### ISSUE THREAD

**Issue by PatrickGhosn** [kubeflow/kubeflow#5537]
/kind bug

**What steps did you take and what happened:**
Followed the steps in https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

**What did you expect to happen:**
For seldon core to be installed, as per this documentation https://www.kubeflow.org/docs/components/serving/seldon/
But I don't see seldon core installed in any namespace or in the apis.

It is also not in the instance/ folder.

**Environment:**

- Kubeflow version: v1/beta1 (1.2.0)
- kfctl version: (use `kfctl version`): v1.19.3
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`): v1.17.14-gke.400
- OS (e.g. from `/etc/os-release`): Ubuntu/containerOS

**Comment by yanniszark** [comment]
@PatrickGhosn please open a PR in https://github.com/kubeflow/gcp-blueprints/ to ask the maintainers of the GCP distribution about this, as it's their area of ownership
