### ISSUE TITLE
Propagate annotations from CR to generated objects

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/kubeflow#5541]
/kind feature

**Why you need this feature:**
We add [kiam](https://github.com/uswitch/kiam) annotations to certain namespaces to facilitate AWS role assumption. In order to do that with the profile controller, we need to interact with the controller-generated namespaces directly. This presents a problem because we have a user who wants to leverage gitops for the profile CRs, but those namespace annotation updates are not stored in the CR. The desired flow would be for the annotations to propagate downstream from the CRs to the namespaces.

**Describe the solution you'd like:**
Add some simple logic to the pipeline controller that copies annotations from the CR into the objects that it generates. If necessary, this could be toggled on and off from the spec. The extra annotations could also be copied from the CR's spec instead of its ObjectMeta but that would require updating the CR spec ofc. Needless to say, I'm open to feedback on other ways to address this. 

**Anything else you would like to add:**
Would it make sense for the annotations to be applied to all of the vanilla objects generated by the controller? 

Thanks for taking the time to review this issue. I would love to handle the implementation pending input/approval regarding design.

**Comment by DavidSpek** [comment]
@droctothorpe Am I correct in understanding this issue is related to kubeflow pipelines? If so, would you mind recreating this issue over at https://github.com/kubeflow/pipelines/ so that it can be tracked properly? Then this issue can be closed as it is not related to the code in this repository.
