### ISSUE TITLE
TensorFlow Extended Kubeflow Multiple Workers

### ISSUE THREAD

**Issue by jaggaer-mtrninic** [kubeflow/kubeflow#5548]
I have an issue with TFX on Kubeflow DAG Runner. Issues is that I managed to start only one pod per run. I don't see any configuration for "workers" except on the Apache Beam arguments, which doesn't help.

Running CSV load on one pod results in OOMKilled error because file has more than 5GB. I tried splitting the file in parts of 100MB but that did not help also.

So my question is: How to run a TFX job/stage on Kubeflow on multiple "worker" pods, or is that even possible?

Here is the code I've been using:

```
examples = external_input(data_root)
example_gen = CsvExampleGen(input=examples)
statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'])

dsl_pipeline = pipeline.Pipeline(
  pipeline_name=pipeline_name,
  pipeline_root=pipeline_root,
  components=[
      example_gen, statistics_gen
  ],
  enable_cache=True,
  beam_pipeline_args=['--num_workers=%d' % 5]
)


if __name__ == '__main__':
    tfx_image = 'custom-aws-imgage:tfx-0.26.0'
    config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=kubeflow_dag_runner.get_default_kubeflow_metadata_config(),
        tfx_image=tfx_image)
    kfp_runner = kubeflow_dag_runner.KubeflowDagRunner(config=config)
    # KubeflowDagRunner compiles the DSL pipeline object into KFP pipeline package.
    # By default it is named <pipeline_name>.tar.gz
    kfp_runner.run(dsl_pipeline)

```

Environment:
- Docker image: tensorflow/tfx:0.26.0 with boto3 installed (aws related issue)
- Kubernetes: AWS EKS latest
- Kubeflow: 1.0.4

**Comment by ConverJens** [comment]
@jaggaer-mtrninic TFX doesn't use multi-worker on KubeFlow in that sense. What you probably should do it to use an external data processor such as Flink and delegate the work. You are (implicitly) using a DirectRunner which is the local runner, meant to be used for experimentation. 

Your OOM error is probably because you need to specify some resource limits on your pipeline. TFX in KubeFlow only support pipeline wide limits, unlike KFP native pipelines that allow component level limits, but you can set them in the following way:

```
def set_memory_request_and_limits(memory_request, memory_limit):
    def _set_memory_request_and_limits(task):
        return (
            task.container.set_memory_request(memory_request)
                .set_memory_limit(memory_limit)
        )

    return _set_memory_request_and_limits

runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=metadata_config,
        tfx_image=tfx_image,
        pipeline_operator_funcs=(
            [
                set_memory_request_and_limits(memory_request, memory_limit)
            ]
        ))
```

**Comment by jbottum** [comment]
/kind question
/priority p2
/area tensorflow

@jaggaer-mtrninic did you get this resolved?

**Comment by jaggaer-mtrninic** [comment]
@jbottum 
I have moved away from TFX, it proved to be too complicated to run on k8s on AWS.
