### ISSUE TITLE
Error opening bolt store: open /var/lib/authservice/data.db: permission denied

### ISSUE THREAD

**Issue by youxingtian** [kubeflow/kubeflow#5551]
/kind bug
when I install kubeflow version 1.2, I get this error.
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
![image](https://user-images.githubusercontent.com/49486786/105697534-a32ac680-5f3f-11eb-8136-e45534cb3424.png)
![image](https://user-images.githubusercontent.com/49486786/105697601-b76ec380-5f3f-11eb-8cce-a51976c9a806.png)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):v1.2
- kfctl version: (use `kfctl version`):v1.2
- Kubernetes platform: (e.g. `minikube`)Huawei cloud three VMs
- Kubernetes version: (use `kubectl version`):v1.16.3
- OS (e.g. from `/etc/os-release`):centos7.6

**Comment by wajeehulhassanvii** [comment]
> /kind bug
> when I install kubeflow version 1.2, I get this error.
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> ![image](https://user-images.githubusercontent.com/49486786/105697534-a32ac680-5f3f-11eb-8136-e45534cb3424.png)
> ![image](https://user-images.githubusercontent.com/49486786/105697601-b76ec380-5f3f-11eb-8cce-a51976c9a806.png)
> 
> **What did you expect to happen:**
> 
> **Anything else you would like to add:**
> [Miscellaneous information that will assist in solving the issue.]
> 
> **Environment:**
> 
>     * Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):v1.2
> 
>     * kfctl version: (use `kfctl version`):v1.2
> 
>     * Kubernetes platform: (e.g. `minikube`)Huawei cloud three VMs
> 
>     * Kubernetes version: (use `kubectl version`):v1.16.3
> 
>     * OS (e.g. from `/etc/os-release`):centos7.6

DId you find any solution to this?

**Comment by sachingupta771** [comment]
I am facing same issue with Kubeflow 1.8,   
error messgae:
ClientID:kubeflow-oidc-authservice ClientSecret:pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok OIDCAuthURL:/dex/auth RedirectURL:/authservice/oidc/callback OIDCScopes:[openid profile email groups] StrictSessionValidation:false OIDCStateStorePath:/var/lib/authservice/data.db AuthserviceURLPrefix:/authservice/ SkipAuthURLs:[/authservice/ /dex] AuthHeader:Authorization Audiences:[istio-ingressgateway.istio-system.svc.cluster.local] HomepageURL:/authservice/site/homepage AfterLoginURL: AfterLogoutURL:/ UserIDHeader:kubeflow-userid GroupsHeader:kubeflow-groups UserIDPrefix: UserIDTransformer:{rules:[]} UserIDClaim:email UserIDTokenHeader: GroupsClaim:groups IDTokenHeader:Authorization Hostname: Port:8080 WebServerPort:8082 ReadinessProbePort:8081 CABundlePath: SessionStorePath:/var/lib/authservice/data.db SessionMaxAge:86400 SessionSameSite:Lax ClientName:AuthService ThemesURL:themes Theme:kubeflow TemplatePath:[web/templates/default] UserTemplateContext:map[] GroupsAllowlist:[*]}"
time="2024-03-05T11:27:03Z" level=info msg="Starting readiness probe at 8081"
time="2024-03-05T11:27:03Z" level=info msg="Starting server at :8080"
time="2024-03-05T11:27:03Z" level=info msg="Starting web server at :8082"
time="2024-03-05T11:27:03Z" level=fatal msg="Error creating session store: open /var/lib/authservice/data.db: permission denied"


Please help

**Comment by mumong** [comment]
k logs -n istio-system oidc-authservice-0
 
 `time="2024-08-05T10:40:14Z" level=info msg="Config: &{ProviderURL:http://dex.auth.svc.cluster.local:5556/dex ClientID:kubeflow-oidc-authservice ClientSecret:pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok OIDCAuthURL:/dex/auth RedirectURL:/authservice/oidc/callback OIDCScopes:[openid profile email groups] StrictSessionValidation:false OIDCStateStorePath:/var/lib/authservice/data.db AuthserviceURLPrefix:/authservice/ SkipAuthURLs:[/authservice/ /dex] AuthHeader:Authorization Audiences:[istio-ingressgateway.istio-system.svc.cluster.local] HomepageURL:/authservice/site/homepage AfterLoginURL: AfterLogoutURL:/ UserIDHeader:kubeflow-userid GroupsHeader:kubeflow-groups UserIDPrefix: UserIDTransformer:{rules:[]} UserIDClaim:email UserIDTokenHeader: GroupsClaim:groups IDTokenHeader:Authorization Hostname: Port:8080 WebServerPort:8082 ReadinessProbePort:8081 CABundlePath: SessionStorePath:/var/lib/authservice/data.db SessionMaxAge:86400 SessionSameSite:Lax ClientName:AuthService ThemesURL:themes Theme:kubeflow TemplatePath:[web/templates/default] UserTemplateContext:map[] GroupsAllowlist:[*]}"
time="2024-08-05T10:40:14Z" level=info msg="Starting readiness probe at 8081"
time="2024-08-05T10:40:14Z" level=info msg="Starting server at :8080"
time="2024-08-05T10:40:14Z" level=info msg="Starting web server at :8082"
time="2024-08-05T10:40:14Z" level=fatal msg="Error creating session store: open /var/lib/authservice/data.db: permission denied"
`

kubernetes version: 1.26.8
kubeflow version:1.8.1
![image](https://github.com/user-attachments/assets/1352e872-6bf3-4121-9894-922b476e2a45)
