### ISSUE TITLE
Deprecate the old Jupyter web app

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5553]
/kind feature

**Why you need this feature:**
Right now we only support and develop the jupyter web app that lives under `components/crud-web-apps`. The `components/jupyter-web-app` is not being developed anymore and it will be completely phased out after the 1.3 release, in which we will be using the crud-web-apps one.

The situation right now can be confusing since we maintain two distinct versions of the app, while commit to only one.

**Describe the solution you'd like:**
We should gradually deprecate this `components/jupyter-web-app`. All of it's features, and even more, are already included in the jupyter-web-app. The deprecation should happen in two phases:
1. we edit the README of the `components/jupyter-web-app` to clearly state that the app is no longer maintained and will be phased out/removed in the future
2. purge it's files after the 1.3 release, in which we will have completely switched to the crud-web-apps one

cc @kubeflow/wg-notebooks-leads

**Comment by DavidSpek** [comment]
@kimwnasptd Maybe it is an idea to put the code in a `deprecated` folder during (and maybe for a while after) the transition. Pipelines as a similar folder for their components: https://github.com/kubeflow/pipelines/tree/master/components/deprecated.

**Comment by DavidSpek** [comment]
We should probably come up with a plan when would be the correct time to remove the JWA from the deprecated folder. Not that I think the time is now, but it might be something that stays there indefinitely and gets forgotten if there is no plan.

**Comment by kimwnasptd** [comment]
The plan was to remove this after 1.3 so I believe it's a good thing to do this now, at the beginning of the new cycle.

I've pushed a PR for this #5959
