### ISSUE TITLE
Support for KeyCloak over Dex

### ISSUE THREAD

**Issue by kd303** [kubeflow/kubeflow#5557]
/kind feature

**Why you need this feature:**
We have a requirement due to organization security policy to provide a seam-less authentication, Dex currently support SAML2 (which is deprecated hence a no-no from security teams) and does not support SPNEGO/GSAPI or something similar for authentication.

**Describe the solution you'd like:**
Kubeflow should not be tied to a specific Idap provider, we would like be able to customize this part as a part of installation or post installation configuration.

**Anything else you would like to add:**
Logically speaking Istio-gateway is used for all incoming request authentication and auth. so if any other Idap is provided in reality it should work, however I am aware some of the work being done in OIDC service and customization that has gone in, can you please provide few insights or inputs if we are to do this on our own what would it take to do so?

**Comment by DavidSpek** [comment]
@kd303 I believe this documentation might help. While you can integrate GitLab with Dex, you can also not use Dex at all and integrate with GitLab directly. Maybe a similar setup can be used to setup KeyCloak rather than Dex. https://docs.arrikto.com/integrations/auth.html

**Comment by DavidSpek** [comment]
@kd303 I've actually implemented this since then. Is this still something you are wanting to deploy?

**Comment by kd303** [comment]
no, temporarily we have integrated with AD for now.

**Comment by matty1979** [comment]
@DavidSpek can you send me what you did? We really want to get away from dex/cognito and shit to oidc + keycloak.

**Comment by DavidSpek** [comment]
@matty1979 You can find the kustomize files [here](https://github.com/argoflow/argoflow-aws/tree/master/distribution/oidc-auth/overlays/keycloak). It uses OAuth2-Proxy and Keycloak. To ensure the manifests are handled securely (given that they contain credentials) Sealed Secrets are used. [The documentation](https://github.com/argoflow/argoflow-aws#the-setup_credentialssh-script) includes the necessary commands and a script to create the necessary credentials.
Keycloak is now the default deployment in the [kustomization.yaml](https://github.com/argoflow/argoflow-aws/blob/fa1d9500170e0c1e5047648cb5aa7eecd1ba387a/distribution/kustomization.yaml#L20).

**Comment by mohamed-fazil-saleem** [comment]
> @kd303 I've actually implemented this since then. Is this still something you are wanting to deploy?

can you tell me how to use keyclock instead of dex in an existing kubeflow running on minikube local
