### ISSUE TITLE
API request to get back Workspace Volumes vs. Data Volumes

### ISSUE THREAD

**Issue by sneelz** [kubeflow/kubeflow#5559]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

Currently developing a custom UI to integrate with Kubeflow and looking for an API call that returns a list of Workspace Volumes vs. Data Volumes. 

The get Persistent Volumes call doesn't seem to distinguish between Workspace vs. Data Volumes. Using another combination of APIs (like get all notebooks + notebook config) doesn't seem to work to compile a list either, since get all notebooks doesn't return deleted notebooks, so you can't use that with a combination of get notebook config to compile a list of Workspace vs. Data Volumes (and that would be super inefficient and impractical anyways).

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

Ideally get Persistent Volumes also returns a property for "type" that denotes whether the PV is "workspace" or "data." Either that, or an equivalent endpoint that returns information like the volume name and type.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DavidSpek** [comment]
Would this be solved by adding an annotation to the PVCs created by the controller?

**Comment by sneelz** [comment]
@DavidSpek As long as that annotation is returned with the Kubeflow /pvcs endpoint, then that should work. Our custom UI is trying to display the user's workspace volumes and data volumes in separate dropdowns during notebook creation, so we need a way to distinguish them.

**Comment by DavidSpek** [comment]
@sneelz Could you further specify which endpoint that is exactly? I'm not sure I am familiar with it.

**Comment by sneelz** [comment]
@DavidSpek Endpoint is at /jupyter/api/namespaces/[namepsace]/pvcs and returns a list of all PVCs, including workspace and data volumes, the user has created.

**Comment by DavidSpek** [comment]
@sneelz Thanks for the clarification. The code for this is found (here)[https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py]. As you can see, this is simply using the Kubernetes Python client and nothing else. It would require quite some custom coding for it to process annotations, as well as changes to the controller to add the workspace annotations to the created PVCs. 
While this is all possible, I don't see this happening very soon. I'm also not sure if the new [Volume Manager UI](https://journal.arrikto.com/democratizing-the-use-of-pvcs-with-the-introduction-of-a-volume-manager-ui-a5bf616570d3) that will be open sourced soon has this functionality backed in. Of course, contributions are always welcome if you want to take up the task of implementing this yourself.

**Comment by sneelz** [comment]
@DavidSpek Thanks for the update. I will look into the Volume Manager UI and see if that will meet our needs.

**Comment by DavidSpek** [comment]
@sneelz It seems I was mistaken regarding the necessary changes for listing the annotations in the endpoint. The following function is the one that creates the `/jupyter/api/namespaces/<namespace>/notebooks` endpoint. You might be able to add annotations to the notebook or volumes and have them processed here. 
https://github.com/kubeflow/kubeflow/blob/0c4a738625f52092f66ec462e800ddd2837e0f6d/components/crud-web-apps/jupyter/backend/apps/common/utils.py#L119

**Comment by sneelz** [comment]
@DavidSpek Thank you for following up! Will take a look at this and see if we can use it.

**Comment by DavidSpek** [comment]
@sneelz Depending on the time I have available, I might be able to look at implementing this as well. It is on the radar in any case.

**Comment by sneelz** [comment]
@DavidSpek Awesome, I appreciate it!

**Comment by DavidSpek** [comment]
Haven't forgotten about this
