### ISSUE TITLE
kubeflow user pipelines interface not working and shows error

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/kubeflow#5561]
/kind bug

**What steps did you take and what happened:**
Deploy kubeflow version 1.2 on kubernetes using the kfctl operator

KFDEF:

>    apiVersion: kfdef.apps.kubeflow.org/v1
      kind: KfDef
      metadata:
        name: kubeflow
        namespace: kubeflow
      spec:
        applications:
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: namespaces/base
          name: namespaces
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: application/v3
          name: application
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/cert-manager-crds
          name: cert-manager-crds
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/cert-manager-kube-system-resources
          name: cert-manager-kube-system-resources
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/cert-manager
          name: cert-manager
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: metacontroller/base
          name: metacontroller
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: admission-webhook/bootstrap/overlays/application
          name: bootstrap
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes
          name: kubeflow-apps
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: kfserving/installs/generic
          name: kfserving
        repos:
        - name: manifests
          uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz

**What did you expect to happen:**
I did not expect the error to be there

**Anything else you would like to add:**
Is it related to the separation of pipelines UIs for users?

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2 (build version v1beta1)
- kfctl version: (use `kfctl version`): 1.2
- Kubernetes platform: (e.g. `minikube`) from a cloud provider
- Kubernetes version: (use `kubectl version`): 1.17.1
- OS (e.g. from `/etc/os-release`): Linux

**Comment by DavidSpek** [comment]
@Hmr-ramzi What exactly is the bug you are experiencing? Are there error codes? Are there pods that are in `CrashBackLoop`? Are the other portions of the UI such as Notebooks working as expected?

**Comment by Hmr-ramzi** [comment]
@DavidSpek Thanks for your reply. All pods are up and running without any logged errors. Also, no pods on crashbackloop state. Yes the other portions of the UI are working fine. The problem is only in the pipelines. The error that i get is the following:

![image](https://user-images.githubusercontent.com/11632681/106072011-a8d30880-6107-11eb-8182-63b29268cde7.png)

**Comment by Hmr-ramzi** [comment]
@DavidSpek Any advise?

**Comment by DavidSpek** [comment]
@Hmr-ramzi I've seen this before for a notebook where the pod crashed or the node had become unresponsive, but other than that I am not sure. I've personally never used the operator before either. 

@Bobgy This seems to be a pipelines issue. Maybe you can move it over to pipelines for better tracking.
/area pipelines

**Comment by solarist** [comment]
Possible duplicate of https://github.com/kubeflow/pipelines/issues/4469 and https://github.com/kubeflow/kubeflow/issues/5271, and similar to https://github.com/kubeflow/kubeflow/issues/5401. I am myself facing the same issue as well.

**Comment by jonasdebeukelaer** [comment]
Hey, facing this too. 

Seems the cluster was being repaired by gcp, and after that this error is persisting for pipelines. \
In case it's relevant, I was trying to install feast today but running into separate istio related issues (blocking connections to postgresql pod). I wonder if something clashed there?

Namespace `kubeflow` labels are correct as per related issues, and I tried restarting all pipeline pods to no avail.
Is it safe to restart istio containers? Could that help? Or is the only solution currently to disable istio-proxies?

**Comment by solarist** [comment]
@jonasdebeukelaer could you ellaborate?

**Comment by solarist** [comment]
@jonasdebeukelaer could you elaborate please? I am not sure how to manually recreate the `meshpolicy`.

**Comment by jonasdebeukelaer** [comment]
@solarist I had accidentally deleted this resource:
```
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  name: default
  namespace: kubeflow
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
```
recreating fixed my issue. I guess make sure it's there just in case something weird happened.

**Comment by solarist** [comment]
@jonasdebeukelaer wow that fixed it, thank you! I am relatively sure that it hasn't been deleted in our deployment, and I can't seem to find such a mesh policy created at all per the k8s-dex manifests. Also why a service would want plain text in the first place is actually beyond me...

**Comment by Bobgy** [comment]
/assign @yanniszark 
Is istio-dex manifest missing it?

**Comment by JohanWork** [comment]
Experiencing the same problem, and have not deleted it manually. @jonasdebeukelaer how did you apply it to your cluster? Do I need to add it in the makefile, or do you manually add it to the cluster running kubeflow?

**Comment by jonasdebeukelaer** [comment]
@JohanWork not sure what makefile you're talking about but you can just run the follow to make sure it's there
```
cat <<EOF | kubectl apply -f -
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  name: default
  namespace: kubeflow
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
EOF
```

**Comment by deepk2u** [comment]
I am using Istio 1.6 and the connection between `metadata-envoy-deployment` and `metadata-grpc-deployment` was the problem, was throwing `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error, I did this to fix the connection issue.

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: kubeflow
spec:
  mtls:
    mode: PERMISSIVE
```

**Comment by DavidSpek** [comment]
@deepk2u While it seems you got it working, Istio 1.6 is not supported by Kubeflow at the moment. Kubeflow 1.3 will come with Istio 1.9. I’m not sure what the current situation is for standalone KFP, but if there is support for Istio 1.6+ it would be in a very recent release.

**Comment by Louanes1** [comment]
> I am using Istio 1.6 and the connection between `metadata-envoy-deployment` and `metadata-grpc-deployment` was the problem, was throwing `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error, I did this to fix the connection issue.
> 
> ```
> apiVersion: security.istio.io/v1beta1
> kind: PeerAuthentication
> metadata:
>   name: default
>   namespace: kubeflow
> spec:
>   mtls:
>     mode: PERMISSIVE
> ```

Thank you, applying this file actually solved that for me. 
I had to restart all the pods of kubeflow namespace after and the pipelines ui is now displayed correctly ! 🎉

I deployed from the manifests repo using kubernetes v1.19 and Kustomization 3.2.0

command I used to restart pods : 
kubectl -n {NAMESPACE} rollout restart deploy
