### ISSUE TITLE
Can kubeflow use exists istio?

### ISSUE THREAD

**Issue by jidemoski** [kubeflow/kubeflow#5562]
/kind question

**Question:**
[You can ask any question about this project.]
Can kubeflow use istio that have been deploy and the version is 1.8?

**Comment by swartz-k** [comment]
Docs say can use with Istio had been deployed. [ref](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/) 
As default version is `1.3` I think it should be tested. I will do that later.

**Comment by swartz-k** [comment]
[Ref](https://istio.io/latest/zh/docs/reference/config/security/istio.rbac.v1alpha1/) After 1.6 may be have question, I got error abot `no matches for kind "ClusterRbacConfig" in version "rbac.istio.io/v1alpha1"`

**Comment by jidemoski** [comment]
@swartz-k 
Thanks，Can I use istio1.6.x?

**Comment by DavidSpek** [comment]
Istio 1.6+ is not yet supported as many components rely heavily on Istio RBAC which has been deprecated and removed in 1.6. There is now an ongoing effort to support istio 1.6+, which should be happening with the release of 1.3 which I believe is planned for March.

**Comment by DavidSpek** [comment]
Closing this issue as I believe it has been answered. 
Related issues:
https://github.com/kubeflow/kubeflow/pull/5439
https://github.com/kubeflow/kubeflow/issues/5397
https://github.com/kubeflow/pipelines/issues/4768
https://github.com/kubeflow/kubeflow/issues/5313
/close

**Comment by jidemoski** [comment]
@DavidSpek 
\help
Can we upgrade kubeflow from v1.2.0 to v1.3.0 now?

**Comment by DavidSpek** [comment]
@jidemoski The release has been delayed a week. The release candidate is now scheduled for March 23rd. 
/close
