### ISSUE TITLE
Allow dynamic NFS data volumes in Notebook Server UI

### ISSUE THREAD

**Issue by Boes-man** [kubeflow/kubeflow#5565]
/kind feature

**Why you need this feature:**
Notebook users have datasets hosted (on perm) externally on nfs (v3/4). They need access to these datasets, but are unable to mount them to the notebook. At the moment notebooks need to be pre-provisioned for these users and self service is desired.

**Describe the solution you'd like:**
Perhaps PodDefaults can be extended to include nfs volumes. This way only the PodDefaults need to be pre-provisioned (or perhaps even not?). A further requirement would be to be able to set the user's UID in spec.template.spec.securitycontext.runasuser Again this UID can be determined once and pre-provisioned in PodDefaults. In the end once the user's Profile is pre-provisioned, with PodDefaults, they will be self service.

**Anything else you would like to add:**
https://kubernetes.io/docs/concepts/storage/volumes/#nfs

Currently my notebook manifest for the nfs volumes is:

`apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  labels:
    app: $LABEL
  name: $NBNAME
  namespace: $IDENT
spec:
  template:
    spec:
      securityContext:
        runAsUser: $USERID
      containers:
      - env: []
        image: $NBTYPE
        name: $NBNAME
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 3Gi
        volumeMounts:
        - mountPath: /home/kubeflow
          name: workspace-$LABEL
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/kubeflow/datasets/$DATASET
          name: nfs-storage
      serviceAccountName: default-editor
      ttlSecondsAfterFinished: 300
      volumes:
        - name: workspace-$LABEL
          persistentVolumeClaim:
            claimName: workspace-$LABEL
        - emptyDir:
            medium: Memory
          name: dshm
        - name: nfs-storage
          nfs:
            path: "/data/{$DATASET}"
            server: $NFSSERVER`

**Comment by DavidSpek** [comment]
@Boes-man It has been a while since I have used it, but if I remember correctly you can use the NFS-Client provisioner, which supports dynamically creating PVCs on an NFS, and create a PVC with the name of an existing folder on the share it will use that for the PVC. For example, if you setup the provisioner at `<IP>:/some_mount` and that share contains the folder `data_folder`, if you then create a PVC for `data_folder` it picks up that folder. However I might be remembering this incorrectly or things might have changed, so you'd need to test this with some dummy NFS share with existing folders in it. 
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

Regardless, I think having NFS capabilities in PodDefaults is a good idea.

**Comment by Boes-man** [comment]
@DavidSpek thanks for the pointer. I did look at a few options in terms of nfs volumes and settled on just using pod definition, no need for storageclass, pvc and pv. This results in the least amount of kubernetes cluster admin maintenance. Since its pod definition, poddefaults would hopefully be able to preconfigure these for users. We just need to preconfigure the kf profile and poddefaults, from there the user can selfprovision their notebooks with external datasets mounted.


POD Definition
In  pod YAML file:
volume mounts:
- name: your-nfs-volume
mountPath: /var/your-destination
Define the volume:
volumes:
- name: your-nfs-volume
nfs:
server: nfs-server.yourdomain.com
path:/path/to/shared-folder

**Comment by jbottum** [comment]
@Boes-man Hi, Arrikto has a storage class (Rok) that can be configured to support this type of use case.    Note - Rok is licensed software.

**Comment by Boes-man** [comment]
Thanks @jbottum The datasets already exist somewhere else (external nfs), would we have to migrate to rok? If PodDefs (or maybe something else?) could be expanded to cover these pod spec volume mounts, then really nothing else is required.... This would give the user the option to mount external datasets to their notebook in the ui.

**Comment by DavidSpek** [comment]
@Boes-man Just wanted to let you know that I have this functionality in mind with the work I am doing on the new Volumes Web App.

**Comment by blairdrummond** [comment]
I'm not sure if this solves the problem but I saw a write-up on nfs volumes in JupyterLab a while ago

https://medium.com/@guillaume.moutier/deploying-a-scalable-shared-data-science-platform-at-universit%C3%A9-laval-b26e7e02cba4

**Comment by Boes-man** [comment]
Thanks @blairdrummond thats a great read. As per the authors comment one might want to explore KF and this issue is for the KF context. I think the article does show that typically organisations do have some (for us all) of their datasets on external NFS. One of the reasons we're using KF is for the self service Notebook UI, so being able to present their NFS volumes in the UI would be great.
The article also touches on another parameter that is required, UID. We have to specify the user's network UID (AD in our case) as the runasUser in the pod security context too. Without it, the folder ACLs on the NFS side wont allow the user to access and change the data.

**Comment by andreyvelich** [comment]
This should be fixed in #6321
