### ISSUE TITLE
Could not get platform aws: Failed to create config file from /.kube/config

### ISSUE THREAD

**Issue by perlinger** [kubeflow/kubeflow#5578]
I have the kubeflow-operator deployed on EKS by means of ARGOCD and Kustomize.
 
 However, as soon as I deploy the KfDef, with the KfAwsPlugin section, I get the following error:
 
 level=fatal msg="Could not get platform aws: Failed to create config file from /.kube/config **"

Note: I deploy the KfDef with the same argocd and kustomize stack as the kubeflow-operator. I do not deploy the kfdef from the command line.
The EKS cluster was launched with terraform not eksctl.

Any ideas how to resolve the fatal error above?

Here is the KfDef:

apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
  name: kubeflow
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: namespaces/base
      name: namespaces
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/istio-stack
      name: istio-stack
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/cluster-local-gateway
      name: cluster-local-gateway
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/istio
      name: istio
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: application/v3
      name: application
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/cert-manager-crds
      name: cert-manager-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/cert-manager-kube-system-resources
      name: cert-manager-kube-system-resources
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/cert-manager
      name: cert-manager
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: metacontroller/base
      name: metacontroller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: admission-webhook/bootstrap/overlays/application
      name: bootstrap
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: spark/spark-operator/overlays/application
      name: spark-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: knative/installs/generic
      name: knative
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kfserving/installs/generic
      name: kfserving
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/spartakus
      name: spartakus
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws
      name: kubeflow-apps
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/istio-ingress-cognito
      name: istio-ingress
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: aws/aws-istio-authz-adaptor/base_v3
      name: aws-istio-authz-adaptor
  plugins:
  - kind: KfAwsPlugin
    metadata:
      name: aws
    spec:
      auth:
        oidc:
          certArn: ######
          oAuthClientId: ######
          oAuthClientSecret: ######
          oidcAuthorizationEndpoint: ######
          oidcIssuer: ######
          oidcTokenEndpoint: ######
          oidcUserInfoEndpoint: ######
        region: us-west-2
        enablePodIamPolicy: true
  repos:
    - name: manifests
      uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz

  version: v1.2-branch

**Comment by DavidSpek** [comment]
ping @kubeflow/wg-deployment-leads

**Comment by matty1979** [comment]
Same error.
