### ISSUE TITLE
Kubeflow pods and deployments got deleted

### ISSUE THREAD

**Issue by bgossey** [kubeflow/kubeflow#5579]
I have a couple of kubernetes clusters (AKS) running and on some of them, when installing kubeflow using the operator, some pods or deployments are being killed after a couple of hours for some reason. Anybody has seen the same thing happening and what can be the root cause?

**What steps did you take and what happened:**
- Installing kubeflow using the operator on an azure kubernetes cluster
- Everything is up and running fine (we can trigger trainings, use the kubeflow dashboard etc)
- After a while, some pods and deployments get killed without an obvious trigger
- We end up with half a kubeflow deployment (which isn't working of course)

**What did you expect to happen:**
- Once installed, kubeflow should be up and running forever

**Environment:**

- Kubeflow version: 1.1:
- kfctl version: v1.1.0:
- Kubernetes platform: AKS
- Kubernetes version: 1.17.9:

**Comment by jbottum** [comment]
@bgossey did you get this resolved?
