### ISSUE TITLE
pickle dump dataframe to OutputPath

### ISSUE THREAD

**Issue by Soot3** [kubeflow/kubeflow#5583]
/kind question

**Question:**
[You can ask any question about this project.]
Is Input Path the right argument to use when passing dataframes.
I'm trying 
`def load_data(data_path:OutputPath(str)):
  #importing libraries

  import sys, subprocess;

  subprocess.run([sys.executable, '-m', 'pip', 'install', 'pandas==0.23.4'])  

  subprocess.run([sys.executable, "-m", "pip", "install", "dill"])

  import dill

  import pandas as pd

  #importing the data
  data = pd.read_csv("https://raw.githubusercontent.com/Soot3/testing/master/cell2celltrain.csv",engine='python', encoding='utf-8', error_bad_lines=False)

  #serialize data to be used
  with open(data_path,'wb') as f:
    dill.dump(data,f)

  return print('Done!')` 

But I'm getting pickle key errors. (I used dill and joblib too).  I think I am using the argument incorrectly. If you have a github where a dataframe is passed between reusable yaml components. Please share.
![Screenshot (404)](https://user-images.githubusercontent.com/53571625/106746977-93883d80-6623-11eb-91b7-b30e44359e92.png)

**Comment by Soot3** [comment]
Don't know if the load data component passed a corrupted file in the pipeline but My  code works well on Colab with manually inputted file paths (/content/...) for each function. 
![Screenshot (406)](https://user-images.githubusercontent.com/53571625/106747513-51133080-6624-11eb-91e2-bcf805ee178b.png)

**Comment by DavidSpek** [comment]
@Soot3 I think you can better ask this question over at https://github.com/kubeflow/pipelines/. 
/area pipelines
@Bobgy maybe you can move this issue over to Pipelines.

**Comment by Soot3** [comment]
Okay. will do.
