### ISSUE TITLE
UX Improvement - When adding notebook server, activate Connect only when endpoint is available

### ISSUE THREAD

**Issue by jaystary** [kubeflow/kubeflow#5584]
/kind feature

**Why you need this feature:**
When adding a notebook server, oftentimes in our environment we experience a "no healthy upstream" or "Sorry this page is not available" or both. The user then wonders whats going on, and the only way to recover from that is to go back after a while and hit connect again. Thus it is a big source of confusion.

**Describe the solution you'd like:**
Ideally await a 200 from the endpoint and only then make the "Connect" visible, so when the user clicks it, they will guaranteed see a notebook pop up

**Anything else you would like to add:**
![connect](https://user-images.githubusercontent.com/34389140/106759075-963e5f00-6632-11eb-8660-3f10b6848384.png)

**Comment by DavidSpek** [comment]
@jaystary I believe there was already an issue or PR regarding this, but I cannot find it at the moment. Nonetheless, this is something I think we should work on.
