### ISSUE TITLE
Dashboard page crashes when entering invalid value into Recurring run "Start time" input

### ISSUE THREAD

**Issue by tkislan** [kubeflow/kubeflow#5587]
/kind bug

**What steps did you take and what happened:**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/5370798/107193399-1a0b9900-69ef-11eb-839b-64c803abe362.png">

When I select whole value in the text input, and press "1" (meaning that I want to write full time by hand), the whole page crashes, and only top banner and white page is displayed

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5370798/107193737-7373c800-69ef-11eb-88fd-a646711847f0.png">

Same thing happens if I just delete the `:` character, without even losing the focus on the input
Also, "Date" fields are broken in a same way as well .. as soon as you delete the `-` character, whole page crashes again

Attaching the console log as well, but this is so easy, and 100% reproducible issue.

**What did you expect to happen:**

I expected a proper validation error displayed, after I leave the field, not while typing it.
Also, why not just use some time picker?
Because validation is obviously just completely wrong .. if you type `09:92`, no error is displayed ...

**Anything else you would like to add:**
Safari console log:
```
[Error] Failed to load resource: the server responded with a status of 400 () (runs, line 0)
[Error] Error: Invalid picker format
xi — TriggerUtils.ts:146
(anonymous function) — Trigger.tsx:408
bi — react-dom.production.min.js:131:466
_i — react-dom.production.min.js:131:200
_l — react-dom.production.min.js:252
_l
(anonymous function) — scheduler.production.min.js:18:437
vl — react-dom.production.min.js:244:440
il — react-dom.production.min.js:223:423
il
(anonymous function) — react-dom.production.min.js:121:115
(anonymous function) — scheduler.production.min.js:18:437
Yo — react-dom.production.min.js:121
Ko — react-dom.production.min.js:120:496
(anonymous function) — react-dom.production.min.js:224:85
le — react-dom.production.min.js:285:132
pe — react-dom.production.min.js:27
Mn — react-dom.production.min.js:83:282
Bn — react-dom.production.min.js:84:473
Fn — react-dom.production.min.js:84:101
Fn
(anonymous function) — scheduler.production.min.js:18:437
se — react-dom.production.min.js:285
Tn — react-dom.production.min.js:82:280
Tn

	ds (2.729a2889.chunk.js:2:2176548)
	(anonymous function) (2.729a2889.chunk.js:2:2182311)
	bi (2.729a2889.chunk.js:2:2149218)
	_i (2.729a2889.chunk.js:2:2148952)
	_l (2.729a2889.chunk.js:2:2200695)
	_l
	(anonymous function) (2.729a2889.chunk.js:2:2219939)
	vl (2.729a2889.chunk.js:2:2196681)
	il (2.729a2889.chunk.js:2:2187008)
	il
	(anonymous function) (2.729a2889.chunk.js:2:2144991)
	(anonymous function) (2.729a2889.chunk.js:2:2219939)
	Yo (2.729a2889.chunk.js:2:2144937)
	Ko (2.729a2889.chunk.js:2:2144872)
	(anonymous function) (2.729a2889.chunk.js:2:2214205)
	le (2.729a2889.chunk.js:2:2214209)
	pe (2.729a2889.chunk.js:2:2104545)
	Mn (2.729a2889.chunk.js:2:2128859)
	Bn (2.729a2889.chunk.js:2:2129787)
	Fn (2.729a2889.chunk.js:2:2129075)
	Fn
	(anonymous function) (2.729a2889.chunk.js:2:2219939)
	se (2.729a2889.chunk.js:2:2214040)
	Tn (2.729a2889.chunk.js:2:2128498)
	Tn
[Error] Error: Invalid picker format
	Yo (2.729a2889.chunk.js:2:2145080)
	Ko (2.729a2889.chunk.js:2:2144872)
	(anonymous function) (2.729a2889.chunk.js:2:2214205)
	le (2.729a2889.chunk.js:2:2214209)
	pe (2.729a2889.chunk.js:2:2104545)
	Mn (2.729a2889.chunk.js:2:2128859)
	Bn (2.729a2889.chunk.js:2:2129787)
	Fn (2.729a2889.chunk.js:2:2129075)
	Fn
	(anonymous function) (2.729a2889.chunk.js:2:2219939)
	se (2.729a2889.chunk.js:2:2214040)
	Tn (2.729a2889.chunk.js:2:2128498)
	Tn
```

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: EKS
- Kubernetes version: v1.18.9-eks-d1db3c
- OS: EKS managed nodes

**Comment by DavidSpek** [comment]
@tkislan Could you please recreate this issue over at https://github.com/kubeflow/pipelines so that it can be tracked properly and close this issue? It is not related to the code in this repository so this issue will most likely go unnoticed by the people working on Kubeflow Pipelines here.
