### ISSUE TITLE
As a user of kubeflow, I am able to access the jupyter servers (notebooks) inside other namespaces although i am not assigned as a contributor

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/kubeflow#5588]
/kind bug

**What steps did you take and what happened:**
Created 2 users (X and Y). Logged in with user X, Created a jupyter server (notebook server) A. Logged in with user Y, edited the url to access the jupyter server A. I was able to access it using url (/notebook/X/A/tree?) 

**What did you expect to happen:**
To get a 403 error instead

**Anything else you would like to add:**
None

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2
- kfctl version: (use `kfctl version`): 1.2
- Kubernetes platform: (e.g. `minikube`) Vanilla
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`): N/A

**Comment by jbottum** [comment]
@DavidSpek have you validated this behavior ?

**Comment by DavidSpek** [comment]
@jbottum I have not, as I am currently busy with developing on the new jupyter web app that uses the common code. However, this is very likely related to a known issue that occurs in multiple web apps. See https://github.com/kubeflow/katib/issues/1322, specifically https://github.com/kubeflow/katib/issues/1322#issuecomment-687640209.

**Comment by connorlwilkes** [comment]
I have also encountered this issue. 

It appears that given a URL any user can access anyone else's notebook instances. This is problematic for security particularly in a multi tenant environment.

You could resolve this in the GCP world by utilising the IAP ingress header (https://cloud.google.com/iap/docs/identity-howto) and adding a match on the header in the 'match' block of the VS. This would mean only users with that header would then be able to access this notebook instance. Unsure whether such headers are injected with any other auth method?

**Comment by yanniszark** [comment]
@Hmr-ramzi @connorlwilkes could you please try installing latest Kubeflow 1.3 Release candidate from these instructions:
https://github.com/kubeflow/manifests/tree/v1.3-branch#readme

and let us know what happened? Please keep in mind that some distributions in 1.2 didn't have support for multi-user isolation, so you may have bumped into that.

**Comment by connorlwilkes** [comment]
> @Hmr-ramzi @connorlwilkes could you please try installing latest Kubeflow 1.3 Release candidate from these instructions:
> https://github.com/kubeflow/manifests/tree/v1.3-branch#readme
> 
> and let us know what happened? Please keep in mind that some distributions in 1.2 didn't have support for multi-user isolation, so you may have bumped into that.

I was looking to bump 1.3 when it is officially released which I believe is this week?

**Comment by thesuperzapper** [comment]
@connorlwilkes to install the 1.3-RC0 version of kubeflow you can install the manifests directly using the instructions on `kubeflow/manifests` https://github.com/kubeflow/manifests#installation

I would be interested to see if you get the same issue.

**Comment by connorlwilkes** [comment]
@thesuperzapper I will do that ASAP but it's a large process for us to bump up to 1.3 and I don't want to bump if we are still at rc0 given issues may appear, do we know when we are targeting full 1.3 release not?

However, I looked into the code for notebook controller and I couldn't find anything concrete that would imply that this has been fixed.

**Comment by DavidSpek** [comment]
@connorlwilkes The code for the notebook-controller wouldn’t affect this. It would be the Jupyter Web App that you would need to look at, which has changed since 1.2 and moved to a version that uses common backend/frontend code. You can deploy the new Jupyter Web App in an existing 1.2 installation, though you will need to update the notebook controller for full functionality and add a permission or 2 to the service account the Jupyter Web App uses (you will see what needs to be added in the UI instantly).

**Comment by connorlwilkes** [comment]
@DavidSpek That sounds sensible to me, will give a go at patching in latest notebook deployment into my cluster. The notebook controller creates the routing rules though right? The Jupyter front end web app is there purely to serve the UI component and to speak to the notebook controller and it doesn't create any K8s resources itself. The notebook controller would create the StatefulSet and VirtualService for routing to allow it to be URL accessible therefore I can't see how a change in the Jupyter web app component would affect the access for the notebook instances, this would have to be controlled at the notebook controller level I think?

**Comment by DavidSpek** [comment]
@connorlwilkes You are correct that the notebook controller actually creates the k8s resources. However, the web apps perform the auth checks if you are allowed to access/create certain resources and in what namespaces.

**Comment by connorlwilkes** [comment]
@DavidSpek once you have deployed a Notebook instance and a VirtualService is created to route to that Notebook instance's frontend then when you enter the URL you don't 'pass through' the Jupyter web application anymore (it's a new URL and new route) therefore I don't think that any authorisation applied at the Jupyter web app would matter. Aware this is now becoming a big back and forth so am happy to ping on Slack if that is better than clogging up this issue

**Comment by DavidSpek** [comment]
@connorlwilkes That is true, but you will still hit the Istio RBAC/Authorization Policy. I think this discussion is useful to highlight how the authorization flow works. @yanniszark probably has the best knowledge of this. Here is an article of his with details how the authentication is setup. https://journal.arrikto.com/kubeflow-authentication-with-istio-dex-5eafdfac4782

I pinged you on Slack so you can easily contact me if you run into something while trying the newer Jupyter Web App.
