### ISSUE TITLE
Dashboard can't handle the same owner for more than one workspace

### ISSUE THREAD

**Issue by boufleur** [kubeflow/kubeflow#5589]
/kind bug

**What steps did you take and what happened:**
1. Create a workspace `workspace1` and assign it to the user `user.email@email.com`
2. Create a workspace `workspace2` and assign it to the user `user.email@email.com`
3. Try add user `another.user@email` as contributor to `workspace2`

**What did you expect to happen:**
`another.user@email.com` to be added as contributor to `workspace2`. 
The namespace selector is greyed out with 'All namespaces' selected.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Kubeflow 1.1.0
kfctl_istio_dex.v1.1.0.yaml
Kubernetes 1.16
central dashboard vmaster-g8097cfeb

**Comment by kim-sardine** [comment]
same problem in v1.2.0.
this should be fixed.

so I [manually added contributor](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually)
