### ISSUE TITLE
kubeflow dashbaord not responding and refusing connections

### ISSUE THREAD

**Issue by nallagangus** [kubeflow/kubeflow#5590]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Cannot Access kubeflow dashboard UI . To work around ingress i tried localhost after  $ kubectlport-forward svc/istio-ingressgateway -n istio-system 8080:80 --address 0.0.0.0 . It gave connection refused errors. Need guidance with next step of debugging. 

**What did you expect to happen:**
To be able to access kubeflow dashboard UI. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
setup details are in the 
[kubeflow dashboard UI errors.txt](https://github.com/kubeflow/kubeflow/files/5947645/kubeflow.dashboard.UI.errors.txt)
attachment if that helps
=====
I do not have metallb.. so edited ingress to convert LoadBalancer to a nodeport.
$$ kubectl get svc -n istio-system
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
authservice            ClusterIP   10.108.255.187   <none>        8080/TCP                                                                     4h10m
istio-egressgateway    ClusterIP   10.105.195.200   <none>        80/TCP,443/TCP,15443/TCP                                                     4h16m
istio-ingressgateway   NodePort    10.109.45.65     <none>        15021:31438/TCP,80:30176/TCP,443:30410/TCP,31400:30213/TCP,15443:31949/TCP   4h16m
istiod                 ClusterIP   10.104.252.66    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        4h16m

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):  kfctl_istio_dex.v1.1.0.yaml
- kfctl version: (use `kfctl version`):  kfctl_v1.1.0-0-g9a3621e
- Kubernetes platform: (e.g. `minikube`) on centos 7.7 with 4worker+1 master nodes. 
- Kubernetes version: (use `kubectl version`): 1.8.1
- OS (e.g. from `/etc/os-release`):  CentOS Linux release 7.7.1908 (Core)

**Comment by nallagangus** [comment]
Hi - For some reason "kubeflow-gateway" was not created as part of install. I manually created it and setup a "metallb" for loadbalancer work. Those 2 steps resolved and I was able to see "kubeflow dashboard" UI

**Comment by DavidSpek** [comment]
Closing as the issue has been resolved.
/close

**Comment by coldtomatojuice** [comment]
I went through the same situation while I was using kubeflow on-premise k8s
We've got istio-system/authservice pod restarted and It worked well again
