### ISSUE TITLE
Configuration support to specify port range to access dashboard

### ISSUE THREAD

**Issue by shivakumargowda12** [kubeflow/kubeflow#5591]
I believe it would be very useful to provide a configuration option during kubeflow installation process to provide a range of ports to be used while accessing kubeflow dashboard in a namespace context
So that customer would know prior what ports to be enabled in the particular machine.

**Comment by soleares** [comment]
What are you trying to accomplish? Limit access to Kubeflow UI to a specific CIDR range?

**Comment by shivakumargowda12** [comment]
Hi @soleares , actually yes. I want to see whether its possible, so that I can predict the port number while launching the kubeflow UI.
