### ISSUE TITLE
Support textarea input for pipeline parameter in centraldashboard

### ISSUE THREAD

**Issue by kim-sardine** [kubeflow/kubeflow#5597]
/kind feature

**Why you need this feature:**
I'd like to pass multi-line bash script pipeline parameter into containerOp.
but for now, centraldashboard only support one line text input and json editor.

of course I can do it by appending all lines with semi-colon or by using list type and joining dynamically, but it's not intuitive.

**Describe the solution you'd like:**

but I'm not sure how to make pipeline code tell centraldashboard to use textarea input. beacuse there is no type hint for multi line string.
maybe we could use custom type or use textarea input as default

**Comment by DavidSpek** [comment]
@kim-sardine Just to be clear, is this something that you input from the central dashboard or from the Pipelines UI? For reference, this is the central dashboard:
![image](https://user-images.githubusercontent.com/28541758/107493574-106c6780-6b8e-11eb-95ef-e1813a914c3b.png)

**Comment by kim-sardine** [comment]
@DavidSpek  sorry for confusing you. I'm talking about pipeline UI.


![image](https://user-images.githubusercontent.com/8458055/107525196-f0728d80-6bf9-11eb-83ad-c7865bedff37.png)

**Comment by DavidSpek** [comment]
@kim-sardine The pipelines UI is not part of this repository. For better handling and tracking of the issue, I advise you to create an issue over at https://github.com/kubeflow/pipelines.
/area pipelines

**Comment by kim-sardine** [comment]
I see. Thanks for the guide!
