### ISSUE TITLE
KFServing-controller: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred: * attempts must be positive

### ISSUE THREAD

**Issue by crmne** [kubeflow/kubeflow#5598]
/kind bug

duplicate of https://github.com/kubeflow/kfserving/issues/1369 since I'm not sure which component is at fault

**What steps did you take and what happened:**
1. Installed Kubeflow 1.2 on EKS with Cognito using [the manifest on Kubeflow's website](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml)
2. Tried to deploy the `pytorch`, `sklearn`, and `tensorflow` models from [the samples directory](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2)
3. Checked health:

        $ kubectl get inferenceservices -n kfserving-test
        NAME           URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
        sklearn-iris         False                                      15m

        $ kubectl describe inferenceservices sklearn-iris -n kfserving-test
        [...]
        Events:
          Type     Reason         Age                     From                  Message
          ----     ------         ----                    ----                  -------
          Warning  InternalError  4m5s                    kfserving-controller  Operation cannot be fulfilled on services.serving.knative.dev "sklearn-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again
          Normal   Updated        3m59s (x5 over 4m6s)    kfserving-controller  Updated InferenceService "sklearn-iris"
          Warning  InternalError  3m31s (x19 over 3m49s)  kfserving-controller  admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
        
        * attempts must be positive

(ignore the difference in time, the `get inference services` was done way after the `describe`)

**What did you expect to happen:**
Have a prediction endpoint.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.1.6
- Knative Version: v0.14.3
- KFServing Version: v0.4.1
- Kubeflow version: 1.2
- Kfdef: aws_cognito
- Minikube version:
- Kubernetes version: (use `kubectl version`):

        Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-dirty", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"dirty", BuildDate:"2021-02-08T10:30:25Z", GoVersion:"go1.16rc1", Compiler:"gc", Platform:"darwin/arm64"}
        Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): macOS 11.2 arm64

**Comment by crmne** [comment]
@yuzisun said in https://github.com/kubeflow/kfserving/issues/1369:
> this is same as #1065, I think you are on Istio 1.1 which is already EOL, please upgrade to higher istio version.

why is Kubeflow 1.2 still installing Istio 1.1.6?

**Comment by DavidSpek** [comment]
@crmne I don't think that is correct. @PatrickXYS is there an error in the AWS manifests that istio 1.1.6 is being installed? By default, Kubeflow uses Istio 1.3.1 and is compatible up to 1.5.x. The goal is to have istio 1.6+ supported with the next release.

**Comment by crmne** [comment]
@DavidSpek @PatrickXYS I installed Kubeflow from [this guide](https://www.kubeflow.org/docs/aws/aws-e2e/) which links to this manifest: https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml

I noticed that is different from https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws_cognito.v1.2.0.yaml, which does install Istio-1.3.1

**Comment by DavidSpek** [comment]
It seems like that commit needs to be cherry picked into 1.2 as it is generally not recommended to install from the master branch (things might be broken).

**Comment by PatrickXYS** [comment]
Hey currently we're working in progress to make cognito solution work with istio >= 1.3.1,

which means current 1.3.1 istio is not compatible with cognito part.

**Comment by crmne** [comment]
@PatrickXYS I was able to install Kubeflow with istio 1.3.1 today with [this Cognito manifest](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws_cognito.v1.2.0.yaml), and was able to deploy KFServing models. The header kubeflow-userid is however not sent to the central dashboard. Is that the problem you're referring to?

**Comment by kim-sardine** [comment]
> @DavidSpek @PatrickXYS I installed Kubeflow from [this guide](https://www.kubeflow.org/docs/aws/aws-e2e/) which links to this manifest: https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml
> 
> I noticed that is different from https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws_cognito.v1.2.0.yaml, which does install Istio-1.3.1

This should be fixed.
anyone who has installed kubeflow on aws_cognito_1.2 with [e2e guide](https://www.kubeflow.org/docs/aws/aws-e2e/) will have same problem. they can't use KFServing because they installed istio 1.1.6

**Comment by DavidSpek** [comment]
@kim-sardine for [ArgoFlow-AWS](https://github.com/argoflow/argoflow-aws) we've been very busy to resolve these problems with AWS integrations. I'm happy to say that we have implemented upstream Istio to make it easier to manage and upgrade (and we've upgraded to Istio 1.10) and we've integrated S3 and RDS where possible, to name a few things. Most importantly, we've re-implemented authentication to make it easier to integrate with OIDC providers (such as Cognito), as well as improve security by using OAuth2-Proxy along with the new external authorization functionality available as of Istio 1.9.

**Comment by kim-sardine** [comment]
@DavidSpek That's a good news. but those upgrades don't seem to solve this problem..

why don't we cherry pick [this commit](https://github.com/kubeflow/manifests/pull/1684/files) into `v1.2-branch` or
change [official e2e installation guide](https://www.kubeflow.org/docs/aws/aws-e2e/)'s manifest link to  https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_aws_cognito.v1.2.0.yaml?
