### ISSUE TITLE
Connect to Kubeflow notebook server via VS code (python extension)

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/kubeflow#5604]
/kind feature

**Why you need this feature:**
I'd like to connect to kubeflow notebook server via vscode. see [Connect to a JupyterHub from Visual Studio Code](https://blog.jupyter.org/connect-to-a-jupyterhub-from-visual-studio-code-ed7ed3a31bcb)

The benefit is it can keep the IDE development UX within vscode but leverage Kubeflow as remote notebook server environment.

**Describe the solution you'd like:**
the similar UX as that from https://blog.jupyter.org/connect-to-a-jupyterhub-from-visual-studio-code-ed7ed3a31bcb

It would be great to provide jupyterhub API from Kubeflow so that it can reuse the current capability of remote notebook server feature from the python extension of vscode.

**Anything else you would like to add:**
Not sure if this is related to #3362

**Comment by DavidSpek** [comment]
Just so you know, there are current effort I am working on to have code-server (VS-Code) run within Kubeflow as well. 
https://github.com/kubeflow/kubeflow/pull/5582

**Comment by shawnzhu** [comment]
This is the spec of jupyter server for the security feature: https://jupyter-server.readthedocs.io/en/latest/operators/security.html

I guess it will need some design work to think about how to support passing token via either query string or a request header.

**Comment by DavidSpek** [comment]
Token authentication is disabled in notebook images that run on Kubeflow, so I do not think that will work. I haven't looked at this yet (or tried), but personally I think the best solution would be to create a custom VS-Code extension that can communicate with Kubeflow (and maybe have more functions as well). 
On a side note, I tried [Juno Connect](https://juno.sh/junoconnect/) quickly. Logging in to Kubeflow with Dex worked fine. However, the redirect to Jupyter notebook (instead of lab, as it is not yet compatible), did not work properly. Luckily, the URL was easy enough to fix and then everything appeared to work as expected.

**Comment by shawnzhu** [comment]
> Token authentication is disabled in notebook images that run on Kubeflow, so I do not think that will work

Got it. I'm working on [multi-user, auth-enabled deployment](https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow-on-iks/#multi-user-auth-enabled), so it could authenticate request to notebook server via either `authservice_session` cookie or `X-Auth-Token` header.

> but personally I think the best solution would be to create a custom VS-Code extension that can communicate with Kubeflow (and maybe have more functions as well).

I thought and tried to reuse existing [vscode-jupyter](https://github.com/microsoft/vscode-jupyter) extension which works with remote jupyterhub. and this is what I discovered:

1. the key part is the how this extension authenticate against a remote notebook server. So far, only two supported paths:
    a. jupyterhub API - where it use either `token` in query string or `Authorization: token xxxx` to interact with JupyterHub rest API
    b. session cookie via password protected login URL. where it has special logic to retrieve a XSRF token, then POST a password together with this XSRF token to `<notebook-url>/login?` to get session cookie. see [this class](https://github.com/microsoft/vscode-jupyter/blob/120d288094e2c5982794d6b8f1a19ca25d9cbf07/src/client/datascience/jupyter/jupyterPasswordConnect.ts)
2. kubeflow authentication behave differently from the path b. (get session cookie first, then get XSRF token).

So you're right, it will need a custom vscode extension. I will try to built it on top of vscode-jupyter but customize an authentication logic for Kubeflow

**Comment by shawnzhu** [comment]
I made it work (and I really like the UX since I can use a powerful, secure remote notebook server from vscode) by changing the authentication logic of [vscode jupyter](https://github.com/microsoft/vscode-jupyter) extension. see details from this commit: https://github.com/shawnzhu/vscode-jupyter/commit/3eaed51dd4997d88148e5a087f84263652d0c3f6

## Summary

1. It enables the notebook centric development workflow when using jupyter extension in vscode. a data scientist could clone code repo locally and open/change/commit notebook changes from vscode but using the remote kernel running from a Kubeflow notebook server where it can touch Kubeflow features like pipeline or distributed model training.
2. It's a secure and multi-user solution since all connections are authenticated with both a session cookie and an XSRF token.

## Feedback

The notebook UX from Kubeflow is really powerful and will be more popular by enabling the vscode path. In order to make it happen, I'm curious the following changes could happen:

1. Deliver a JupyterHub compatible REST API where it allows token generation like `POST /hub/login` so that it won't need any change in current vscode-jupyter extension.
2. Change the OIDC-authservice component so that it could generate XSRF token for unauthenticated request (the password protected Jupyter notebook requires XSRF token when authenticating the first request). @yanniszark May I have your comment?

## Follow up

If people are interested in the UX, I'm happy to record a demo posted here.
I need more comments on the authentication path when using Kubeflow from AWS/GCP/Azure (so far it works on multi-user enabled Kubeflow on IBM cloud kubernetes only) so that I can figure out what changes are required for the vscode-jupyter extension.

**Comment by ReggieCarey** [comment]
We would be very very interested in this integration. In general, integrations with local IDEs make Kubeflow better.

**Comment by DavidSpek** [comment]
@shawnzhu Awesome work! Is it possible to spawn a new notebook server with the VS-Code extension (both with JupyterHub, as well as with Kubeflow)? I still think a custom extension that would tightly integrate with Kubeflow and allow for spawning new notebook servers and such would be the most interesting route to go down.

**Comment by shawnzhu** [comment]
> Is it possible to spawn a new notebook server with the VS-Code extension (both with JupyterHub, as well as with Kubeflow)?

If my understanding is correct, you mean spawn a new notebook server with Kubeflow within a local vscode? It only supports connecting to an existing remote Jupyter notebook server from current vscode-jupyter extension, the feature that spawn a new notebook server is not there.

I'm still trying to create a demo to show key feature first. I get the idea of spawning new notebook server then connect a local notebook file to this remote kernel within vscode, it should be doable. (It's annoying to ask a user to create new notebook server from Kubeflow web UI then copy/paste URL and session cookie back to vscode which will be a very confusing UX).

**Comment by laserK3000** [comment]
@shawnzhu Do you have any plans to get your commit merged into VSCode? I compiled it and it works fine. Thanks a lot!

**Comment by shawnzhu** [comment]
@laserK3000 Thanks for the feedback! Yes, I do want to see possibilities to merge my change into the jupyter extension. One thing I haven't done is testing my change on Kubeflow 1.3 since I want to double confirm the authentication flow design including session cookie name, authorization header (`X-Auth-Token` or `Authorization`) and XSRF token flow

**Comment by laserK3000** [comment]
@shawnzhu Yes, I am running `1.3`.

**Comment by Talador12** [comment]
@shawnzhu Is the change merged into the jupyter extension yet?

Given a fresh install of vscode and a running kubeflow cluster, what steps are required to make the connection to vscode?

**Comment by shawnzhu** [comment]
@Talador12 No, I haven't tried to put my hack as a PR since I want to validate it against 1.3 release that @laserK3000 did.

> what steps are required to make the connection to vscode?

This is what I did: https://github.com/kubeflow/kubeflow/issues/5604#issuecomment-787604098

Once I can make my change to the jupyterhub extension in vscode, documentation is must-have

**Comment by Roma110** [comment]
Has anyone tested fairing library in VSCode notebook with jupyter notebook ?

**Comment by PrimeF** [comment]
@shawnzhu Is there any update on your adaptation of the Jupyter extension for kubeflow? Will it be merged anytime soon?

**Comment by shawnzhu** [comment]
@PrimeF Going to create a PR soon, not sure about the merge part.

**Comment by shawnzhu** [comment]
@PrimeF the ☝️ has been merged. the only limitation is it asks for session cookie named `authservice_session` (default name when using the arrikto `authservice` as authentication proxy). Although there is no new release of jupyter extension of vscode since this August, it would be great if you can share how it goes (by running the extension from source).

**Comment by PrimeF** [comment]
@shawnzhu Thanks for creating the PR and making this feature possible!
Indeed, I have built the extension from source directly after it has been merged and am using it since then: it works like a charm!

The only thing I am missing now is some sort of syncing possibility between local and remote. Looking around I have seen that this is feature has already been requested (https://github.com/microsoft/vscode-jupyter/issues/1601).

Currently, I'm evaluating the option of building a Python TUI to sync local and remote using the Jupyter Server Content APIs (https://jupyter-server.readthedocs.io/en/latest/developers/rest-api.html). I've tested the APIs with Kubeflow and they work.

**Comment by Talador12** [comment]
Is there a step by step guide on how to connect Kubeflow to VScode using this authservice? I can built it from source but I would like to make it easy for all users to quickly connect

**Comment by shawnzhu** [comment]
Have you tried using the kubernetes extension of vscode to attach local vscode to remote notebook server pod?. see https://github.com/kubeflow/kubeflow/pull/5700

the UX of that feature is everything is remote, nothing local.

**Comment by Talador12** [comment]
I have not. I have used the notebook-server-codeserver-python docker image, but the idea was to use the local VScode IDE to work with remote compute/memory. I think this is an awesome change but it would benefit from a runbook of steps to get started. I work with a lot of data scientists and we would want this as easy as possible to configure.

For instance, our kubernetes instances are private and require a particular proxy and tunnel to connect. Is this possible using the kubernetes or jupyter extension?

**Comment by PrimeF** [comment]
@shawnzhu Thanks for the suggestion, will try that. Do you know if it supports file transmission from local to remote?

@Talador12 Briefly, the steps necessary to connect to a Kubeflow Jupyter server are as follows:

1. Connect to the server via a browser and perform the login if necessary.
2. Retrieve the `authservice_session` cookie value from the browser. For instance, in the case of Firefox, this would consist in opening the **Web Developer Tools**, going to the **Storage** tab, open the **Cookies** section, look for for the `authservice_session` and lastly copy its value.
3. Open the **Command Palette** in VS Code and search for "Jupyter: specify local or remote Jupyter server for connections".
4. Select "Existing" and when prompted for the URI insert your Kubeflow Jupyter server URI. **Note:** for me the URI was the part in the URL before `\lab\workspaces`.
5. At this point VS Code asks you to reload the window. Once reloaded, you are prompted for a password; insert the value of your `authservice_session` cookie (the one you retrieved in step 2.) in this field.
6. Finally, open a Jupyter notebook and select a kernel to use (I got prompted to select a kernel as soon as I tried to run a cell).

These instructions worked for my scenario, and are not guaranteed to work for everyone. Hence, they do not substitute a proper documentation of this feature.

Regarding your question of connecting to a Jupyter server which is in a private network (I assume reachable via VPN), as long as you can reach the Jupyter server from a browser, you should be able to connect to it using VS Code.

**Comment by shawnzhu** [comment]
if using jupyterhub as remote notebook server, it provides feature to upload data. see [Adding data to the JupyterHub](https://tljh.jupyter.org/en/latest/howto/content/add-data.html), but I'm not sure if such feature is part of jupyter notebook API that can be included in the jupyter extension of vscode. I'd suggest following up in [their backlog](https://github.com/microsoft/vscode-jupyter).

I will close this issue since the the feature has been merged in vscode-jupyter extension.

**Comment by bartgras** [comment]
@PrimeF @Talador12 
Not closely related to this PR but there is another way to work on remote Pod from local VSCode.
Note: It requires the user to have access to Kubernetes cluster and proper K8s permissions set.

Steps:
* First you need to install VSCode "Remote explorer" and "Kubernetes" extensions
* In "Kubernetes" extension choose your cluster, switch to namespace your Pod is in (use right click on desired namespace and choose "Use namespace")
* Go to "Workloads" -> "Pods"  and find Pod you want to connect to. Note: It can be any Pod, not only notebook server one
* Choose "Attach Visual Studio Code". This will open new VSCode window and install (only first time you connect to this Pod) remote environment on your Pod. 
* Now you can use VSCode file explorer and choose your project base path. 

Working with notebooks requires additional jupiter server installation but VSCode will ask you to install it once you open any *.ipynb file.

Briefly, this gives you feeling of working on local machine:
* access to all files within container
* copying files into container is simple drag and drop
* you also have access to terminal, use source control from VSCode etc.

I didn't test multiple user connecting to the same Pod, but even if it's possible I'd be cautious with using single Pod by multiple users (e.g. if one of them changes the branch, it will affect all connected users).

**Comment by shawnzhu** [comment]
@bartgras Thanks!

> Note: It requires the user to have access to Kubernetes cluster and proper K8s permissions set.

This is the last piece I haven't fully figure out when a kubeflow user is NOT a kubernetes user. (which means this user will only have service account `kubeflow-edit`)

**Comment by bartgras** [comment]
@shawnzhu Kubernetes administrator can create Kubernetes access and manage roles independently from Kubeflow. At the end the user should get/update his [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) file that allows him to connect to the cluster using granted role.

**Comment by abreu4** [comment]
@bartgras Thank you so much, improved my workflow 10x

**Comment by vedpd11** [comment]
Guys! you can use remote vscode on any cluster without ssh. 

1. download cli from https://code.visualstudio.com/Download
2. tar zxvf vscode_cli_alpine_x64_cli.tar.gz 
3. ./code tunnel

Just complete the authentication and you are good to go. I dont understand why this cool thing is not mentioned in the docs any where. I had been struggling to get remote vscode work on clusters. SSH was not allowed by company IT guys. I had been using s3 sync via local which also works. You can create a util file for syncing your changes to s3 then s3 to the cluster machine.

**Comment by Maisiechiu** [comment]
> Guys! you can use remote vscode on any cluster without ssh.
> 
> 1. download cli from https://code.visualstudio.com/Download
> 2. tar zxvf vscode_cli_alpine_x64_cli.tar.gz
> 3. ./code tunnel
> 
> Just complete the authentication and you are good to go. I dont understand why this cool thing is not mentioned in the docs any where. I had been struggling to get remote vscode work on clusters. SSH was not allowed by company IT guys. I had been using s3 sync via local which also works. You can create a util file for syncing your changes to s3 then s3 to the cluster machine.

Awesome!  This is simple and really worked for me! Saved me a lot of time.

**Comment by thesuperzapper** [comment]
We are discussing how to allow remote SSH access in Notebooks 2.0.

Please follow the issue here and please share any ideas for how to do it safely:

- https://github.com/kubeflow/notebooks/issues/23

**Comment by zhenyulin** [comment]
I don't get the `authservice_session` cookie in my browser it seems, but only:
- _xsrf
- oauth2_proxy_kubeflow
- username-localhost-8080

None of the cookie values is working for me.

Has anyone else run into this situation as well?
