### ISSUE TITLE
Issues with Metadata writer, Central Dashboard, Argo UI  & Ml pipeline pods while deploying Kubeflow in an IPv6 environment.

### ISSUE THREAD

**Issue by ayush7007** [kubeflow/kubeflow#5605]
/kind bug

I am trying to setup Kubeflow on an IPv6 environment and facing issues with Metadata writer, Central Dashboard, Argo UI & Ml pipeline pods. Not sure whether Kubeflow works fine with Ipv6 as I see no params to switch between Ipv4 and Ipv6. Please suggest if Kubeflow supports IPv6 ? 
Below are the issues I am facing- 

**What steps did you take and what happened:**

1. Metadata writer not able to connect to Metadata store - 
![image](https://user-images.githubusercontent.com/25534418/107885062-08118500-6f1e-11eb-9792-ee28bf67da2a.png)
![image](https://user-images.githubusercontent.com/25534418/107826914-c3fe7300-6dab-11eb-9c72-5566a91ea2be.png)

Metadata writer is trying to connect to GRPC service which is running on  0.0.0.0:8000  in IPv6 environment inside grpc pod( refer screenshot in this post below) and throwing “could not connect to Metadata store”
![image](https://user-images.githubusercontent.com/25534418/108199364-e9d89e80-7142-11eb-9134-e672fd490b38.png)

Grpc deployment logs -
![image](https://user-images.githubusercontent.com/25534418/108199438-0a085d80-7143-11eb-8abf-ed2d2a2ee3f9.png)

2. Kubeflow Central Dashboard is throwing below error where it is splitting the ipv6 link based on colon and assigning incorrect host and port values - 
![image](https://user-images.githubusercontent.com/25534418/108199328-da595580-7142-11eb-9501-238ed684850e.png)

3. Argo UI is running on 0.0.0.0:8001 in IPv6 cluster and is in Not ready state( throwing connection refused) 
![image](https://user-images.githubusercontent.com/25534418/107826644-39b60f00-6dab-11eb-9cc0-4de9103212d7.png)

**What did you expect to happen:**

1. Metadata GRPC is running on 0.0.0.0:8000  whereas it should bind on [::]:8000 in an IPv6 environment, What's the correct way to bind here in case of IPv6?
![image](https://user-images.githubusercontent.com/25534418/107885082-31caac00-6f1e-11eb-8573-b307cca9c5c2.png)

This is hardcoded in Metadata server code -  
https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/metadata_store_server_main.cc#L230

![image](https://user-images.githubusercontent.com/25534418/107827138-2f484500-6dac-11eb-8adc-e87a15aeaeb2.png)
This is using IPv4 IP (0.0.0.0) instead of Ipv6[::].

2. Kubeflow Central Dashboard should assign correct values to hostname, host and port ( refer above error screenshot of dashboard).

3. Argo UI must also bind on [::]:8000 to work in Ipv6 environment but I don’t see something to switch, What's the correct way to bind here in case of IPv6 ?
![image](https://user-images.githubusercontent.com/25534418/107826636-3589f180-6dab-11eb-9794-4e0d09f6c2c7.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Liveness probe for ml-pipeline-api-server pod is failing and ml-pipeline UI is throwing failed to retrieve errors.
![image](https://user-images.githubusercontent.com/25534418/107825826-ca8beb00-6da9-11eb-9bc8-60dce7031378.png)

Not sure if I may be hitting anymore issues with IPv6 as I move forward with deployment and using it.

Pod status - 
![image](https://user-images.githubusercontent.com/25534418/107827368-a67dd900-6dac-11eb-88ed-85b3924111ca.png)

Versions used – 

https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml
https://github.com/kubeflow/kfctl/releases/download/v1.1.0/kfctl_v1.1.0-0-g9a3621e_linux.tar.gz

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.1
- kfctl version: (use `kfctl version`): v1.1.0-0-g9a3621e
- Kubernetes platform: (e.g. `minikube`) Kubeadm
- Kubernetes version: (use `kubectl version`): v1.18.6
- OS (e.g. from `/etc/os-release`): Centos 7.8

**Comment by massih10** [comment]
I m having a similar / exact same issue (not sure really). My pipeline and metadatawriter pods are not running. Is there any fix for this?

**Comment by vsk2015** [comment]
@ayush7007 For issue number 2 (Kubernetes central dashboard) the fix is present in the latest master of javascript client library https://github.com/kubernetes-client/javascript/blob/751488214d58feb40d21038c62a225e09487d600/src/config.ts#L201

**Comment by vsk2015** [comment]
Here is the PR for issue no. 1 (Metadata writer) : https://github.com/kubeflow/pipelines/pull/5160/commits/781abc76ee8ce1e36d35f672f853f0d9efcdb99a

**Comment by Ark-kun** [comment]
> Here is the PR for issue no. 1 (Metadata writer)

I'm not sure I see a PR. Have you created a PR?

```
    mlmd_connection_config = metadata_store_pb2.MetadataStoreClientConfig(
        host=[metadata_service_host] 

```
Does the host parameter support lists? 
https://github.com/google/ml-metadata/blob/3edfc45ee6450494bfd48fe47e5b6570bf858638/ml_metadata/proto/metadata_store.proto#L614

**Comment by vsk2015** [comment]
@Ark-kun Sorry I messed up with the changes I pushed. Here is the PR https://github.com/kubeflow/pipelines/pull/5245/commits/2ee165319830183ac306afb6ae4c310899970bfe

**Comment by vsk2015** [comment]
I messed up while pushing changes. Rectified and commented on the specific open issue.
