### ISSUE TITLE
Can we put all of /home on PV for Jupyter notebooks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#561]
Right now if a user uses a PV only /home/joyvan/work is put onto the PV.

I think it would be better if all of /home could be on PV.

I believe there was discussion about this in the original PR. I think there were issues with
- Permissions
- Overwriting files examples that we want in /home that should be baked into the container.

I still think it would be good to see if we can find a solution where all of /home could be on PV. Users store import things in their home directory (E.g. git credentials) and if these don't survive a pod or container restart thats a burden on users.

/cc @pdmack @inc0

**Comment by inc0** [comment]
Full /home is a no-no (as there is no jovyan dir there and we'd need to create+chown it, magic, especially that there is no other user present). /home/jovyan - sure. Would allow us to drop one step from building image.

**Comment by jlewi** [comment]
/home/jovyan works for me.

**Comment by jlewi** [comment]
I tried mounting the PV at `/home/joyvan` and that doesn't work. The error is

```
usermod: no changes
Execute the command as jovyan
env: ‘jupyterhub-singleuser’: No such file or directory
```
When I mount it at `/home/joyvan/work` it ends up being mounted as root and I don't have access to it.

**Comment by jlewi** [comment]
The permissions issue came up in #22 the original issue.

VIshnu's [comment](https://github.com/kubeflow/kubeflow/pull/22#issuecomment-350415857) was to set the fsGroup. 

I think at one point we might have done that.

Clearly we need some E2E tests #278

**Comment by jlewi** [comment]
I uncommented the line in kubeform_spawner to set the fs group id. The had the effect of setting the group on the volume but it doesn't appear the jovyan user is in this group. 

So we probably need to add this group and jovyan to the group when we build the docker image.

So I think we need to make the following changes

1. Set fs group id in kubeform_spawner
1. Add corresponding group to the docker image
1. Don't  bake any files into /home/jovyan; instead copy them into the home dir if they don't exist on container startup.

**Comment by jlewi** [comment]
#285 - Issue reported by user with PVC for Jupyter
#270 - Is PR that added mount of PVC

**Comment by jlewi** [comment]
Anyone interested in trying to tackle this in the next two weeks? I'd like to get it fixed as part of our (Google Kubeflow team's) next sprint which begins today and ends in two weeks (05/11)

/cc @pdmack

**Comment by pdmack** [comment]
You're killing me @jlewi ...
/assign @pdmack

**Comment by pdmack** [comment]
@jlewi which group? The docker build already puts it in `gid=100(users) groups=100(users)`. Do we not want to use that fsGroup?

**Comment by jlewi** [comment]
SGTM

**Comment by pdmack** [comment]
Working on this [here](https://github.com/pdmack/kubeflow/tree/561-jovyan-home-mount).

**Comment by pdmack** [comment]
Meh, `pre_spawn_check` is no good since the mount and joyvan user are not in place yet to make a determination as to whether we need to init `/home/jovyan` or recognize that the NB pod PVC has already been init.

**Comment by jlewi** [comment]
What is pre_spawn_check?

Is the problem that we don't create the Jovyan user until runtime in [start.sh](https://github.com/pdmack/kubeflow/blob/561-jovyan-home-mount/components/tensorflow-notebook-image/start.sh).

Should we be defining the user and group when we build the Docker image?

It also looks like we are supporting a bunch of different options (e.g. running as root, granting SUDO permissions). 

Would it help if we were more opinionated and dropped some of those options?

**Comment by pdmack** [comment]
Sorry, pre_spawn_hook...an opportunity for JH to init some stuff on a shared volume to the notebook (for example).
 
I'm getting warmer, but really the notebook in its start scripts is the best point to determine: do we have to init `/home/jovyan` or is there user content there already via a PV? There's a lot of implicit conda config that goes on during the Dockerfile build. Doing a build for `/home/jovyan` then 'RUN mv ...` to (say) `tmp` at the end could work but unfortunately it means duplicating roughly a 2.5 GB layer in the NB image.

I'm currently creating jovyan in the Dockerfile but without a home dir. uid,fs_gid are in place there and in the Spawner,  so I don't think that's an issue atm.
