### ISSUE TITLE
envoyfilter issue in kfctl_istio_dex in standard kubernetes 

### ISSUE THREAD

**Issue by nallagangus** [kubeflow/kubeflow#5614]
Hi all

can some one share working version of envoyfilter authn-filter in kfctl_istio_dev setup?

I got one which is redirecting main http://kubeflow-url/ to http://10.37.3.90/dex/auth but dex/auth also goes thru redirect to itself. I was hoping dex/auth will skip authentication along with future ur;s once they carry JWT. 

The one I am using is shared below 

Thanks
Sudhir nallagangu

Current setup: 
Kubernetes 1.8 on-prem cluster (non cloud)
cert-manager 1.1.0
istio-1.8.2 (wanted istiod specifically since kfctl is looking for that daemon)
kubeflow 1.1 with dex

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auth2-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        portNumber: 8080
        listnerType: GATEWAY
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          failureModeAllow: false
          httpService:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: "cookie"
                - exact: "x-forwarded-access-token"
                - exact: "x-forwarded-user"
                - exact: "x-forwarded-email"
                - exact: "authorization"
                - exact: "x-forwarded-proto"
                - exact: "proxy-authorization"
                - exact: "user-agent"
                - exact: "x-forwarded-host"
                - exact: "from"
typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          failureModeAllow: false
          httpService:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: "cookie"
                - exact: "x-forwarded-access-token"
                - exact: "x-forwarded-user"
                - exact: "x-forwarded-email"
                - exact: "authorization"
                - exact: "x-forwarded-proto"
                - exact: "proxy-authorization"
                - exact: "user-agent"
                - exact: "x-forwarded-host"
                - exact: "from"
                - exact: "x-forwarded-for"
                - exact: "accept"
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: "location"
                - exact: "proxy-authenticate"
                - exact: "set-cookie"
                - exact: "authorization"
                - exact: "www-authenticate"
              allowedUpstreamHeaders:
                patterns:
                - exact: "location"
                - exact: "proxy-authenticate"
                - exact: "set-cookie"
                - exact: "authorization"
                - exact: "www-authenticate"
            pathPrefix: /istio/verify-params-header
            serverUri:
              cluster: outbound|8080||authservice.istio-system.svc.cluster.local
              timeout: 60s
              uri: http://authservice.istio-system.svc.cluster.local
          statusOnError:
            code: Forbidden

**Comment by DavidSpek** [comment]
@nallagangus Istio 1.6 nad higher are not yet supported. Support for Istio 1.6 and higher should come with the Kubeflow 1.3 release. Until then, I don't think there is much that can be done about this issue.
