### ISSUE TITLE
Kubflow's Jupyter web app gets binded on 0.0.0.0:500 instead of [::]:5000 in IPv6 kubernetes cluster.

### ISSUE THREAD

**Issue by thirdeye-jarvis** [kubeflow/kubeflow#5615]
Jupyter Wsgi web app is binded on 0.0.0.0:500 in IPv6 kubernetes cluster due to which I am not able to edit and launch notebooks from Kubeflow dashboard. It should be running on [::]:5000 to establish proper connectivity, 

what's the way of switching this jupyter deployment to Ipv6 ?

Does Kubeflow support IPv6??

![viber_image_2021-02-17_12-13-33](https://user-images.githubusercontent.com/79189189/108167871-61470780-711c-11eb-87a1-94906ca229b1.jpg)

**Comment by DavidSpek** [comment]
@kimwnasptd Does the crud-web-app version of JWA properly support IPv6? If not, is this something that should be included in 1.3?

**Comment by DavidSpek** [comment]
bump
