### ISSUE TITLE
Data Management in EKS

### ISSUE THREAD

**Issue by vishal-wiai** [kubeflow/kubeflow#5616]
/kind question

I'm trying to setup a Kubeflow deployment on an EKS cluster and wanted to explore data management options. Rok seems to be a great option but I couldn't figure out from the docs how to deploy it without MiniKF. Is it possible to use Rok without MiniKF? What are the other choices for data management, mainly data versioning and how to set it up?

Also, can I use s3 as my artifact store? If yes, can anyone share any guide for it? Thanks!

**Comment by DavidSpek** [comment]
@vishal-wiai Rok can certainly be deployed on EKS. The documentation to deploy Rok itself of EKS can be found (here)[https://docs.arrikto.com/install/kubernetes/eks/index.html]. If you are wanting all functionality of MiniKF on EKS, I think you are looking for Arrikto's Enterprise Kubeflow, with the deployment instructions being available (here)[https://docs.arrikto.com/integrations/kubeflow.html]. Do note that Rok is proprietary software and requires a license. Similarly, Arrikto's Enterprise Kubeflow requires a license, however, many of the improvements it contains with respect to Kubeflow (such as the Volume Manager UI and new KFServing and Katib dashboards are being open sourced and pushed upstream). I have no ties to Arrikto so I don't have more details regarding the difference between a license for just Rok or their Enterprise Kubeflow. 
For Rok, you will require an object store, but I am assuming you are wanting to replace the MinIO instance used by Kubeflow Pipelines with your object store. Details on how to set this up can be found (here)[https://www.kubeflow.org/docs/aws/pipeline/#support-s3-artifact-store]. 
I would suggest contacting @jbottum to further discuss Rok and Arrikto's offerings.

**Comment by jbottum** [comment]
@vishal-wiai Thanks for your inquiry.   We would be glad to help with a Kubeflow Data Management Solution for your AWS cluster(s).  We need to complete a pre-installation checklist and discuss your objectives and use cases.   Beyond simplifying your ML workflows, the Solution also provides high storage performance (and lower storage costs).    Please drop me a line josh.bottum@arrikto.com to set-up a follow-up.

**Comment by jbottum** [comment]
@vishal-wiai did you find a solution? should we set-up a follow-up?
