### ISSUE TITLE
Remove unused GCP CI tests

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5619]
/kind bug

Right now the only workflow defined in `kubeflow/kubeflow`'s [prow_config.yaml](
https://github.com/kubeflow/kubeflow/blob/0c4a738625f52092f66ec462e800ddd2837e0f6d/prow_config.yaml) is an old one that was meant to run in the previous GCP infra. We should completely remove this workflow. This effort is also crucial to migrating to Optional-test infra https://github.com/kubeflow/kubeflow/issues/5482.

We can see it in many open PRs right now https://github.com/kubeflow/kubeflow/pull/5617#issuecomment-782774273

cc @PatrickXYS

**Comment by DavidSpek** [comment]
Closing as this has been solved.
/close
