### ISSUE TITLE
No manifest(kfctl) for Seldon 1.1.0

### ISSUE THREAD

**Issue by vladislavkoz** [kubeflow/kubeflow#5621]
Hi there. We've faced with autoscaling issue. The Automatically created HPA config is not valid. This issue already fixed https://github.com/SeldonIO/seldon-core/issues/1533

We are using kfctl and the following manifest for installation.
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml
It uses 1.0.1 Seldon-Core version but we need 1.1.0 to get the fixed Autoscaling.
Could we get a manifest with 1.1.0 Seldon-Core version? Or let me know what is another way to resolve this issue.

Installation flow
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml"
***install kfctl***
kfctl apply -V -f ${CONFIG_URI}

**Comment by jbottum** [comment]
@vladislavkoz did you check with the Seldon folks like Clive Cox on this request?

**Comment by vladislavkoz** [comment]
Hi @jbottum. I was asking about it in Seldon Slack channel. One assumption was that you are keeping them [here](https://github.com/kubeflow/manifests). I've tried to find it but no success as you can see.

**Comment by jbottum** [comment]
@vladislavkoz we will start testing the kubeflow 1.3 release candidate soon, and there will be some new kustomize / kubectl installation patterns.   You might consider using KF 1.3
