### ISSUE TITLE
What version of k8s does KF 1.2 support?

### ISSUE THREAD

**Issue by EvanFabry** [kubeflow/kubeflow#5634]
/kind question

**Question:**
The [k8s kf version compatibility chart](https://www.kubeflow.org/docs/started/k8s/overview/) doesn't have an entry for KF 1.2. It would be great to know what versions of k8s KF currently supports.

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/5384989/108923450-b1770b80-75ed-11eb-9192-f774ef3f16c6.png">

**Comment by DavidSpek** [comment]
I have a PR open to fix that. I currently run Kubeflow 1.2 on Kubernetes 1.20, before that on 1.19 and 1.18. I have not encountered any issues so far.
