### ISSUE TITLE
How to Culling of Idle Pods - Jupyter

### ISSUE THREAD

**Issue by bravo325806** [kubeflow/kubeflow#5635]
/kind question

**Question:**
I follow the https://github.com/kubeflow/kubeflow/pull/3856  add culling setting in notebook-controller-deployment, I use kfctl_istio_dex.v1.2.0.yaml deploy on on-presmises kubernetes

        env:
        - name: USE_ISTIO
          valueFrom:
            configMapKeyRef:
              key: USE_ISTIO
              name: notebook-controller-notebook-controller-config-h4d668t5tb
        - name: ISTIO_GATEWAY
          valueFrom:
            configMapKeyRef:
              key: ISTIO_GATEWAY
              name: notebook-controller-notebook-controller-config-h4d668t5tb
        - name: DEFAULT_PROMETHEUS_SVC
          value: prometheus.istio-system.svc.cluster.local:9090
        - name: DEFAULT_IDLE_TIME
          value: "3"
        - name: DEFAULT_CULLING_CHECK_PERIOD
          value: "1"
        - name: DEFAULT_ENABLE_CULLING
          value: "true"

**Comment by jbottum** [comment]
/platform on-prem

@bravo325806 question - which storage class are you using ?
