### ISSUE TITLE
Pipeline Parameter Attributes (e.g. Grouping and Descriptions)

### ISSUE THREAD

**Issue by daenuprobst** [kubeflow/kubeflow#5639]
/kind feature

**Why you need this feature:**
When creating a pipeline that exposes a relatively large (5-10+) number of run parameters, the generated list of parameter input fields in the frontend becomes confusing (when creating a new run). Especially when there are parameters with the same name / function for multiple steps in the pipeline, the only way to make them distinguishable is to give them increasingly complex variable names. This can easily lead to mistakes when users create new runs.

**Describe the solution you'd like:**
For each pipeline parameter there should be a possibility so specify attributes such as a group and a description, which will then be reflected in the frontend. A dict in the `dsl.pipeline` decorator might be a good place to add this additional information.

**Comment by DavidSpek** [comment]
@daenuprobst could you please create this issue on the https://github.com/kubeflow/pipelines repo? 
/area pipelines
