### ISSUE TITLE
jupiter notebook statefulset customization

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubeflow/kubeflow#5643]
/kind question

**Question:**
Is there a way to customize the stateful set created by the kubeflow when it starts a jupyter notebook? I know of `PodDefaults`, but I need to be able to go beyond that level and customization and specify `runAsUser` in the security context.
Is there a configuration with the basic pod template that will be applied that one can change?

**Comment by jbottum** [comment]
@raffaelespazzoli thanks for your question.   You might asked at the Notebook's working group meeting: https://docs.google.com/document/d/1YtSWRhdhyOgd6ZQcWLM38TGDy2H_EhXjr8U5lUi37_I/edit and/or watch the Kubeflow notebook roadmap ideas in this video i.e. ability to modify the yaml: https://www.youtube.com/watch?v=R111KuJUXyI

**Comment by DavidSpek** [comment]
@raffaelespazzoli Could you point me to the Kubernetes documentation of what you are wanting to configure? Then I can see how this could possibly be integrated with the controllers.
