### ISSUE TITLE
Pipeline page is blank on dashboard

### ISSUE THREAD

**Issue by bvboca** [kubeflow/kubeflow#5645]
/kind bug

**What steps did you take and what happened:**
1. all service and pod are up and running. 
2. Katib and Notebook server pages are accessible on the dashboard.
3. Click Pipelines menu on dashboard will result in a blank page.
4. The Pipeline page is accessible by its service cluster ip. 

**What did you expect to happen:**
Pipeline page  is accessible on kubeflow  dashboard

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:  1.2 v1beta1
- kfctl version: (use `kfctl version`): v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) kubernetes cluster
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`):Centos7

<img width="1026" alt="截屏2021-02-27 下午10 05 32" src="https://user-images.githubusercontent.com/11614025/109389795-eb774300-7948-11eb-85f7-9606a455f366.png">

**Comment by bvboca** [comment]
I install kubeflow on an existing istio cluster and skip some steps of kfctl setup. Maybe some functions are broken in my installation. I suggest the setup tutorial should be detailed documented about the installation on a pre-existed kubernetes, istio, knative server, and what we should do to make it as a clean installation.

**Comment by jbottum** [comment]
/priority p2
/area pipelines

@bvboca did you get this resolved, what environment are you running in i.e. AWS, GCP ?

**Comment by bvboca** [comment]
> /priority p2
> /area pipelines
> 
> @bvboca did you get this resolved, what environment are you running in i.e. AWS, GCP ?

no, I guess the best solution would be a detailed doc about how to install kubeflow on existed istio/knative server.

**Comment by PatrickGhosn** [comment]
This looks like the page is not able to load JS, CSS, etc properly. Check your network tab, see if you are getting timeouts or unauthorized errors in the requests.

**Comment by bvboca** [comment]
ok hopefully there will be some docs in the future.
