### ISSUE TITLE
Installing Kubeflow in any custom namespace

### ISSUE THREAD

**Issue by deepk2u** [kubeflow/kubeflow#5647]
/kind feature

**Why you need this feature:**
Kubeflow seems to be very tied with the namespace name `kubeflow`, ideally, it should be customizable and we should be able to install in any named namespace

**Describe the solution you'd like:**
Parameterize all the namespace related variables

**Anything else you would like to add:**

**Comment by themowski** [comment]
I think that this would be useful for anyone who wants to run multiple versions of Kubeflow in the same cluster -- the use-case would be helping with an upgrade to a new version of Kubeflow. Conceptually, you could have an older version of Kubeflow running that users are actively using, and then deploy a newer version to a fresh namespace. Once it's running, users could be instructed to transition to that new instance once their jobs finish in the old one, and when everyone is out, the old one could be uninstalled.
