### ISSUE TITLE
2 Pods created for every user on-boarded on KF

### ISSUE THREAD

**Issue by kd303** [kubeflow/kubeflow#5648]
### What steps did you take:
WE have a Kubeflow 1.1 with Dex enabled on premise cluster with 2 worker nodes. We have enabled few of our data-science users with LDAP integration. However what we noticed during some sort of test (we wanted to create multiple profiles and see how many users can work simultaneously - since 220 pod limit would be there vs how many pods are reserved by Kubeflow and other pieces in order to determine our future cluster sizing). 

### What happened:
We saw that there are two pipeline pods created for every single profile created on Kubeflow, it wasn't very clear why these pods gets created everytime a profile is created and user is logged in. These would be mean if I on-board 20 users then 40 pods are utilized that means we have less capacity available for kf-serving, notebooks etc.

These two pods are created in a specific namespace for an individual user

### What did you expect to happen:
I am not sure whether this is a specific functionality or a bug, so I wanted to understand :
1. Why this behavior
2. Is this some configuration issue at our end, which we can rectify? 
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow version 1.1.0
Kubeflow pipeline version: 1.0.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by kd303** [comment]
Apologies for putting duplicate issues [4953](https://github.com/kubeflow/pipelines/issues/4953), but I havent got any replies there hence putting this under kubeflow repository since I am not sure whether the issue related to profile or pipeline.

**Comment by jbottum** [comment]
@kd303 Hi, sorry to hear of your issue.  You might consider joining the on-prem working group and/or finding commercial support from a vendor.     Here is the info to the on-prem working group: https://arrik.to/kf-wg-notebooks-notes.    I suspect the installation pattern will improve in Kubeflow 1.3 (especially with the refactoring of the manifests).    please find the 1.3 roadmap here: https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md
