### ISSUE TITLE
kfdef and kfctl general usability improvements

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubeflow/kubeflow#5652]
/kind feature

I find the pair kfdef and kfctl to be very painful to use. Here are the reasons:
1. kfctl seems to be very sensitive to which directory it is being launched from. I can't really put my finger on the issue there, but if I am not in the same dir as the kfdef it does not work.
2. in some instances kfctl changes the kfdef file, for example arbitrarily removing commented sections. Why is the input being changed...
3. there does not seem to be a way to run a dry run or to get in output what would be created with a given configuration: it would be create to be able to run something like `kfctl process ... | kubectl apply -f -`
4. because of its arcane processing kfctl is not very compatible with gitops tools like argocd
5. parametrization is very hard and scarce with the currently available packages.
6. basically for any type of customization, I have not found any other ways beside forking the repo and editing the files the way I needed them.
7. it is essentially impossible, for the way kustomize works, to prevent a resource from being created...

I need to repackge kubeflow for a specialized deployment for a customer of mine, and I find that kfdef and kfctl are not the right tools for the job. I'd invite the community to review the way a kubeflow distribution/release is packaged.

My two cents of how I would have solved this problem is a combination of helm chart and kustomize.
Helm charts offer a good way of creating a balance between internal cohesion of manifests and exposed parameters. Also Charts have a mature ways of managing dependencies. For everything that cannot be addressed with a chart, kustomize can be used to apply last minute customization. 

here is an article that explains three possible ways to concatenate helm and kustomize:
https://tech.aabouzaid.com/2020/09/3-ways-to-customize-off-the-shelf-helm-charts-with-kustomize-kubernetes.html

**Comment by DavidSpek** [comment]
@raffaelespazzoli I think a lot of your concerns are in the process of being addressed with release 1.3 which is coming soon. If I am not mistaken Kustomize will be used for the deployment. Other than that, your concerns are something I’ve come across myself and read in other issues and it is something the community is busy with. If you’d like to help out with this you could take a look at the manifest working group and the deployments working group. I think the their slack channels are a good place to start out.

**Comment by jbottum** [comment]
@raffaelespazzoli you might consider joining some of the manifest working group calls, as they are cleaning up the manifests, which should help simplify installation (with kustomize), please find the WG group notes here: https://docs.google.com/document/d/1d-QByp_QRMkxRaQER53mYfeRW0-KyhDBPdmeMEzkL0g/edit
