### ISSUE TITLE
ks deploy kubeflow not start 

### ISSUE THREAD

**Issue by kinglion811** [kubeflow/kubeflow#566]
when I deploy kubeflow by ks,when I executive the command of
ks apply default -c kubeflow-core
the return are:
ARNING rewriting "default" environment params to not use relative paths
ERROR find objects: find objects for kubeflow-core in /: RUNTIME ERROR: import not available kubeflow/core/all.libsonnet
	/home/sre/lxh/my-kubeflow/components/kubeflow-core.jsonnet:4:13-49	thunk <all> from <$>
	/home/sre/lxh/my-kubeflow/components/kubeflow-core.jsonnet:12:30-33	thunk from <thunk from <$>>
	k.libsonnet:96:24-29	thunk from <function <anonymous>>
	k.libsonnet:97:36-41	thunk from <function <anonymous>>
	<builtin>	builtin function <type>
	<std>:1165:25-26	thunk from <thunk <ta> from <function <anonymous>>>
	<builtin>	builtin function <type>
	<std>:1167:29-31	thunk from <function <anonymous>>
	<builtin>	builtin function <primitiveEquals>
	<std>:1167:8-36	function <anonymous>
	...
	<builtin>	builtin function <type>
	<std>:1217:8-9	function <anonymous>
	<std>:1165:25-26	thunk from <thunk <ta> from <function <anonymous>>>
	<builtin>	builtin function <type>
	<std>:1167:29-31	thunk from <function <anonymous>>
	<builtin>	builtin function <primitiveEquals>
	<std>:1167:8-36	function <anonymous>

	/home/sre/lxh/my-kubeflow/components/kubeflow-core.jsonnet:12:1-60	$
	During evaluation
what‘s the reason

**Comment by pdmack** [comment]
Can you provide `ks version`? 0.9.2 is the latest Ksonnet release. Also, note the Jsonnet version.

That line is (likely):
`std.prune(k.core.v1.list.new(all.parts(updatedParams).all))`
so it's possible it's a problem with that version of the [standard lib](http://jsonnet.org/docs/stdlib.html).

**Comment by kinglion811** [comment]
the version is :
ksonnet version: dev-2018-04-03T20:55:40+0800
jsonnet version: v0.10.0
client-go version: 1.8

I go get the source code and make install the ks.
I follow your advice but no effect

**Comment by pdmack** [comment]
OK, so that's a dev build of ksonnet. I've reproduced your issue but not sure what's up there.

Instead of `go get`,  can you instead please grab [an official release of 0.9.2](https://github.com/ksonnet/ksonnet/releases/tag/v0.9.2) for your platform and retest?

**Comment by kinglion811** [comment]
oh pdmack,I change ks to 0.9.2
$ ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
then I follow the step by
https://github.com/kubeflow/kubeflow   
when I execute this command：
the error is:


$ ks apply default -c kubeflow-core
ERROR generate objects for namespace : unable to read /home/sre/lxh/my-kubeflow/environments/default/main.jsonnet: /home/sre/lxh/my-kubeflow/environments/default/main.jsonnet:4:1-5 Expected , or ; but got (IDENTIFIER, "base")

base + {

**Comment by pdmack** [comment]
Please delete your `my-kubeflow` directory and follow the steps again using the 0.9.2 ks.
