### ISSUE TITLE
kubeflow istio-ingressgateway pod restarting

### ISSUE THREAD

**Issue by nathanwong91** [kubeflow/kubeflow#5662]
/kind bug

**What steps did you take and what happened:**
Accessing the Kubeflow UI half the time will get `503 Service Temporarily Unavailable`. Caused by `istio-ingressgateway` pod in istio namespace restarting and being unavailable. 

**What did you expect to happen:**
Users being an able consistently access the Kubeflow UI without issues

**Anything else you would like to add:**
Unsure if this was the correct place to ask about this as it is Istio but we only have Istio in the cluster due to Kubeflow.
```
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][39][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][39][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][43][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][43][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][43][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2021-03-04 00:27:02.772][39][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2021-03-04 00:27:02.773][37][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2021-03-04 00:27:02.773][37][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2021-03-04 00:27:02.773][37][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2021-03-04 00:27:02.785][37][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x556da4126dae]
[Envoy (Epoch 0)] [2021-03-04 00:27:02.786][43][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x556da4126dae]
```
As the error log from the pod is quite long the above is not all of it. I've attached the full log before the pod restarts below.
[istio-ingressgateway-error.txt](https://github.com/kubeflow/kubeflow/files/6080023/istio-ingressgateway-error.txt)

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2
- Istio version: 1.5.0
- Kubernetes platform: (e.g. `minikube`): EKS
- Kubernetes version: (use `kubectl version`): 1.15

**Comment by jbottum** [comment]
@nathanwong91 Hi Nathan, sorry to hear of this issue.   If you are having trouble resolving, you might ask the AWS Kubeflow team for help.   Alternatively, Kubeflow 1.3 will refactor Kubeflow installation, and it will upgrade Istio versions (even to Istio 1.9).   The Release Candidate for 1.3 should be available March 15, and then testing on the platforms will begin.    You can find the Kubeflow roadmap here: https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md.    You might also check on the work in the Manifest working group, which is working to improve installation patterns: https://arrik.to/kf-wg-manifests-notes

**Comment by PatrickGhosn** [comment]
What pipeline version will 1.3 be using @jbottum? It doesn't mention it in the roadmap.
