### ISSUE TITLE
"User" vs "Project > User"

### ISSUE THREAD

**Issue by ludans** [kubeflow/kubeflow#5666]
/kind question

**Question:**

As far as I understood kubeflow and its security is designed around Users.
Users have some dedicated space, quotas, they can access data, create stuff and share it with each other.

Is there a notion of "project"?
I don't really like the idea of users mixing stuff from one project to another.
A project would have some data sources, some resources, and users - to make the project.
Users within a project would share their notebooks if they wish so.
Users would only have access to data they need for this project (and nothing more).
And projects would be very isolated one from each other.

(PS awesome product by the way)

**Comment by DavidSpek** [comment]
@ludans I understand the feature you are describing and I believe I have seen similar requests before. At the moment, there isn't really a notion of a "project". However, you can create a "user" which is actually a project and add users to that. Other than the naming I believe the underlying mechanism would be the same (a project has it's own namespace and that is how it is isolated from others). 

Is there some other distinction between users and projects that you are missing? If we can work out a concrete difference between what would define a user and what would define a project that would be the first step into making a proposal to implement such a feature.

**Comment by jbottum** [comment]
@ludans Per David's suggestion, you might consider using namespaces as a way to separate projects i.e. each project could have its own namespace and each namespace can have 1 or more users.    Additionally, some parts of your question appear to highlight the need for advanced data management with auth and isolation.    That appears to be something for data management solutions that are integrated with Kubeflow via the CSI.    You might look at Arrikto Rok as it can provide policies similar to those in your request.   https://www.arrikto.com/rok-data-management/

**Comment by ludans** [comment]
Thanks @DavidSpek and @jbottum for your suggestions. We will try that.

**Comment by jbottum** [comment]
@ludans have you found a proper configuration for your needs?
