### ISSUE TITLE
Jupyter notebook keep connecting and can not execute any command

### ISSUE THREAD

**Issue by 3dimaging** [kubeflow/kubeflow#5669]
Hi All,

I installed the Kubeflow on AWS EKS based on https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

When I started a notebook server and click connect button, the new notebook shows connecting all the time and can not run a command like print("hello") in the code cell of the notebook.
![image](https://user-images.githubusercontent.com/24443385/110250280-7dcea680-7f48-11eb-8ddd-840f55ebe10c.png)

the log shows:

- Readiness probe failed: Get http://192.168.6.36:15020/healthz/ready: dial tcp 192.168.6.36:15020: connect: connection refused

- Stopping container istio-proxy

Thank you so much!

**Comment by DavidSpek** [comment]
@3dimaging What notebook server image are you using that is causing this problem?

**Comment by 3dimaging** [comment]
@DavidSpek 
Thank you for your reply! I am using aws's default notebook image with tensorflow 1.15.
Sometimes I can connect to the notebook server, sometimes I can not. this issue is not consistent. When I connect to the notebook server and run command in notebook, I can execute the regular command.
However, When I tried to create experiment using python kfp package, I was not authorized. 
here is the error message, "ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 08 Mar 2021 14:51:03 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: RBAC: access denied"

**Comment by DavidSpek** [comment]
What you are experiencing with KFP is a separate issue that should be solved in the upcoming release (release candidate is March 15th). 
Regarding the kernel not connecting, are you using the image `gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0` by any chance? I'm not sure if what is provided by AWS by default. I am actually in the process of creating a new stack of notebook images for Kubeflow that should be available very soon.

**Comment by 3dimaging** [comment]
@DavidSpek 
by the way, I also tried the image, gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
I have the same connecting issue.

**Comment by DavidSpek** [comment]
@3dimaging Could you maybe quickly see if `davidspek/kubeflow-ubuntu-tensorflow-full:0.3` also has this issue? That is one of the new images I am working on for Kubeflow. I've experienced this before myself as well, but it has been difficult to replicate reliably. So it would be great to see if you also experience the issue with the new image.

**Comment by 3dimaging** [comment]
@DavidSpek 
Great! Thank you! I will try davidspek/kubeflow-ubuntu-tensorflow-full:0.3

**Comment by jbottum** [comment]
@3dimaging did you get this issue resolved?  are you planning to upgrade to Kubeflow 1.3, which should be out after the release candidate testing is finished ?

**Comment by 3dimaging** [comment]
@jbottum Thank you, Jbottum. I tested the image, davidspek/kubeflow-ubuntu-tensorflow-full:0.3, I still have the connection issue. I think it is not related to image, maybe it is related to the auth. I don't know. I also check the new version of KFP pakcage see if I can create experiment. No, I still can't create the experiment as before. 

Is the namespace related to this issue? When the first time when I login kubeflow UI, I was ask to put the namespace, I am wondering if I need to put kubeflow as namespace, others name will never work? Thank you again!

**Comment by DavidSpek** [comment]
@3dimaging You should not put kubeflow as the namespace. The latest tensorflow-cpu image is `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:master-e8250b9f`, maybe you can give that a quick try. Is the issue still that the kernel is not connecting?

**Comment by 3dimaging** [comment]
@DavidSpek Thank you again! I tried the latest image you mentioned, I still can't connect to the notebook kernel.
For the KFP package issue which I can't create experiment is resolved using the comments from https://github.com/kubeflow/pipelines/issues/4440.

**Comment by DavidSpek** [comment]
@3dimaging I actually just experienced this issue as well. If you open the developer tools of your browser, do you see errors with connecting to the websocket? If so, try a different browser or incognito mode.

**Comment by 3dimaging** [comment]
@DavidSpek Thank you! you are abosutely right. It depends on the version of the browser.

**Comment by DavidSpek** [comment]
@3dimaging Happy the problem has been resolved for you. 

/close
