### ISSUE TITLE
Provision Public ECR Images

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#5675]
We need the following images to be provisioned in the Public ECR Repo, to unblock the Kubeflow 1.3 release.

## Core Components

These images have __already been__ provisioned, but need to be __renamed/moved__:
(because the are currently at the root of `public.ecr.aws/j1r0q0g6`)

Component | Image Name - OLD | Image Name - NEW
-- | -- | --
admission-webhook | `public.ecr.aws/j1r0q0g6/admission-webhook` | `public.ecr.aws/j1r0q0g6/notebooks/admission-webhook`
central-dashboard | `public.ecr.aws/j1r0q0g6/central-dashboard` | `public.ecr.aws/j1r0q0g6/notebooks/central-dashboard`
jupyter-web-app | `public.ecr.aws/j1r0q0g6/jupyter-web-app` | `public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app`
notebook-controller | `public.ecr.aws/j1r0q0g6/notebook-controller` | `public.ecr.aws/j1r0q0g6/notebooks/notebook-controller`
profile-controller | `public.ecr.aws/j1r0q0g6/profile-controller` | `public.ecr.aws/j1r0q0g6/notebooks/profile-controller`
tensorboard-controller | `public.ecr.aws/j1r0q0g6/tensorboard-controller` | `public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller`
tensorboards-web-app | `public.ecr.aws/j1r0q0g6/tensorboards-web-app` | `public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app`

These image __have not been__ provisioned yet:

Component | Image Name - NEW
-- | --
access-management | `public.ecr.aws/j1r0q0g6/notebooks/access-management`
volume-manager-web-app | `public.ecr.aws/j1r0q0g6/notebooks/volume-manager-web-app`

## Notebook Servers

These images __have not been__ provisioned yet

Git Path | Image Name - NEW
-- | --
notebook-servers/base | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/base`
notebook-servers/rstudio | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio`
notebook-servers/rstudio-tidyverse | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse`
notebook-servers/codeserver | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver`
notebook-servers/codeserver-python | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python`
notebook-servers/jupyter | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter`
notebook-servers/jupyter-scipy | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy`
notebook-servers/jupyter-pyspark | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pyspark`
notebook-servers/jupyter-pytorch | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch`
notebook-servers/jupyter-pytorch-full | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full`
notebook-servers/jupyter-pytorch-cuda | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda`
notebook-servers/jupyter-pytorch-cuda-full | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full`
notebook-servers/jupyter-tensorflow | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow`
notebook-servers/jupyter-tensorflow-full | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full`
notebook-servers/jupyter-tensorflow-cuda | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda`
notebook-servers/jupyter-tensorflow-cuda-full | `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full`

**Comment by thesuperzapper** [comment]
@PatrickXYS I know its tedious but can you provision these for us? 

I will owe you, lol.

/assign @PatrickXYS

**Comment by PatrickXYS** [comment]
I would encourage WG-notebooks come to concensus, WG-notebooks need to work as a whole group to solve this type of questions / issues.

Totally understand this might be a blocker for incoming 1.3, but community will not and should not rely on one specific folk to take care of artifacts management. 

/cc @kubeflow/wg-notebooks-leads

**Comment by thesuperzapper** [comment]
@kimwnasptd can you please confirm you are ok with @PatrickXYS provisioning these images, we only have 5 days before March 15th (Kubeflow 1.3).

Regarding notebook-servers, I am more than happy to take responsibility for them if it means we meet the 1.3 deadline.

Regarding the renames, I think its better if we make the change now (and not when people are using them).

**Comment by thesuperzapper** [comment]
@PatrickXYS in the last Notebook WG meeting, all the @kubeflow/wg-notebooks-leads agreed that the changes (as stated above) should go forwards.

Can you start provisioning them as soon as you can?

Other @kubeflow/wg-notebooks-leads please feel free to comment/like this post to confirm.

**Comment by kimwnasptd** [comment]
@PatrickXYS you can move forward with creating the mentioned images. Apologies for the inconvenience of having to recreate a lot of them due to new the `/notebooks/` prefix.

@thesuperzapper  @DavidSpek  for the list of Notebook images, is the one above the final one? I remember discussing that we might exclude a small part of them, like the pyspark one, but I'm not sure of the final state here. Could you update the list and give a final ACK?

Lastly, I'd only have one small comment for the `volume-manager-web-app` to rename it to `volumes-web-app` and use the image name `public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app`, in order to aligh with our other `jupyter-web-app` and `tensorboards-web-app`.

Looking forward to this!

**Comment by DavidSpek** [comment]
@kimwnasptd Indeed we will need to look at the pyspark one as I think Mathew will need to test it a bit. However, having the registry already created can't do much harm I think and allows us to easily add it a bit later without needing to bother @PatrickXYS again to create yet another registry. 

Regarding the naming of the `volumes-web-app` I completely agree, it should be inline with the other apps.

**Comment by PatrickXYS** [comment]
> We need the following images to be provisioned in the Public ECR Repo, to unblock the Kubeflow 1.3 release.
> 
> ## Core Components
> These images have **already been** provisioned, but need to be **renamed/moved**:
> (because the are currently at the root of `public.ecr.aws/j1r0q0g6`)
> 
> Component	Image Name - OLD	Image Name - NEW
> admission-webhook	`public.ecr.aws/j1r0q0g6/admission-webhook`	`public.ecr.aws/j1r0q0g6/notebooks/admission-webhook`
> central-dashboard	`public.ecr.aws/j1r0q0g6/central-dashboard`	`public.ecr.aws/j1r0q0g6/notebooks/central-dashboard`
> jupyter-web-app	`public.ecr.aws/j1r0q0g6/jupyter-web-app`	`public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app`
> notebook-controller	`public.ecr.aws/j1r0q0g6/notebook-controller`	`public.ecr.aws/j1r0q0g6/notebooks/notebook-controller`
> profile-controller	`public.ecr.aws/j1r0q0g6/profile-controller`	`public.ecr.aws/j1r0q0g6/notebooks/profile-controller`
> tensorboard-controller	`public.ecr.aws/j1r0q0g6/tensorboard-controller`	`public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller`
> tensorboards-web-app	`public.ecr.aws/j1r0q0g6/tensorboards-web-app`	`public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app`
> These image **have not been** provisioned yet:
> 
> Component	Image Name - NEW
> access-management	`public.ecr.aws/j1r0q0g6/notebooks/access-management`
> volume-manager-web-app	`public.ecr.aws/j1r0q0g6/notebooks/volume-manager-web-app`
> ## Notebook Servers
> These images **have not been** provisioned yet
> 
> Git Path	Image Name - NEW
> notebook-servers/base	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/base`
> notebook-servers/rstudio	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio`
> notebook-servers/rstudio-tidyverse	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse`
> notebook-servers/codeserver	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver`
> notebook-servers/codeserver-python	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python`
> notebook-servers/jupyter	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter`
> notebook-servers/jupyter-scipy	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy`
> notebook-servers/jupyter-pyspark	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pyspark`
> notebook-servers/jupyter-pytorch	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch`
> notebook-servers/jupyter-pytorch-full	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full`
> notebook-servers/jupyter-pytorch-cuda	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda`
> notebook-servers/jupyter-pytorch-cuda-full	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full`
> notebook-servers/jupyter-tensorflow	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow`
> notebook-servers/jupyter-tensorflow-full	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full`
> notebook-servers/jupyter-tensorflow-cuda	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda`
> notebook-servers/jupyter-tensorflow-cuda-full	`public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full`

++++++

>Lastly, I'd only have one small comment for the volume-manager-web-app to rename it to volumes-web-app and use the image name public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app, in order to aligh with our other jupyter-web-app and tensorboards-web-app.


^^^ ALL DONE

**Comment by DavidSpek** [comment]
@PatrickXYS Amazing, thank you so much for all the effort!

**Comment by PatrickXYS** [comment]
I think this done per my comment https://github.com/kubeflow/kubeflow/issues/5675#issuecomment-797581524

/close
