### ISSUE TITLE
don't start run if obligatory parameters are not passed

### ISSUE THREAD

**Issue by alvercau** [kubeflow/kubeflow#5688]
/kind feature

**Why you need this feature:**
Currently it is possible to start a run even if some parameters that are obligatory in a step, are missing. It would be easier to have the option to make some parameters obligatory to begin with (just like pipeline, pipeline version, run name, experiment), making it impossible to start a run if these obligatory parameters are not passed. This would avoid creating a whole container that simply immediately raises an error because a parameter is missing.

**Describe the solution you'd like:**
Have an option to make a parameter obligatory before starting a run.

**Comment by DavidSpek** [comment]
@alvercau Am I correct in understanding that this is a feature for Kubeflow Pipelines? If so, the correct place to make a feature request is https://github.com/kubeflow/pipelines/issues. 

/area pipelines
