### ISSUE TITLE
Argo UI in not ready state as it is using IPv4 IP to bind in IPv6 Kubernetes cluster

### ISSUE THREAD

**Issue by ayush7007** [kubeflow/kubeflow#5696]
/kind bug

Argo UI is binded on 0.0.0.0:8001 in IPv6 kubernetes cluster instead of [::]:8001 due to which any connections to UI are getting refused and UI is in not ready state.
![image](https://user-images.githubusercontent.com/25534418/111077680-f40a7480-8517-11eb-89b1-6a82d0316bee.png)

![image](https://user-images.githubusercontent.com/25534418/111077714-1f8d5f00-8518-11eb-9b48-7abeb6b519e5.png)

What's the way of starting the UI on IPv6 IP  "[::]" ?

**Comment by jbottum** [comment]
/kind feature
/area ipv6
@ayush7007 which platform / cloud are you deploying to i.e. GCP, AWS, On-Prem ?

**Comment by ayush7007** [comment]
> /kind feature
> /area ipv6
> @ayush7007 which platform / cloud are you deploying to i.e. GCP, AWS, On-Prem ?

I am deploying this On-prem.
