### ISSUE TITLE
TFX Large serialized components failing due to annotation size limit

### ISSUE THREAD

**Issue by vaskozl** [kubeflow/kubeflow#5701]
/kind bug

I'm using a TFX ExampleGen component with many splits which are SQL queries. I'm passing 100 splits to an SQL ExampleGen, those 100 splits get serialized. TFX uses a `--serialized_component` flag to which it passes a JSON serialized component including my 100 queries.

As a result my pipeline fails with:
Too long: must have at most 262144 bytes

As kubernetes limits the annotation value to 256kb.

This is due to the `workflows.argoproj.io/template` annotation which includes the component arguments. I can run the pipeline by reducing the number of splits (queries), but not with my desired number of splits.

The annotations tend to be quite bulky with schema's and the like being serialized into them when using TFX.

I expect to be able to run TFX Pipeline with a large number of splits and not to be hindered by a limit in the serialized component size.

- Kubeflow version: 1.40.0
- Kubernetes platform: kubeadm
- Kubernetes version: 1.20.2
- OS: centos8

**Comment by jbottum** [comment]
/area pipelines
/priority p2
/kind question

@vaskozl did you get this resolved ?   related, what storage class are you using ?

**Comment by vaskozl** [comment]
I haven't resolved this yet, I'm still stuck with a maximum number of splits (queries). Previously I ran this pipeline on Airflow and didn't have this restriction.

I'm pulling the data from MySQL through a component based on the PrestoExampleGen, and I'm using DO Spaces as S3 compatible object storage to store the TFX and Kubeflow artfiacts.

**Comment by ConverJens** [comment]
@jbottum This is still a huge pain! Is there anything that can be done on KubeFlows side to allow larger workloads to be run?
