### ISSUE TITLE
Migration Path?

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/kubeflow#5705]
/kind question

**Question:**
[You can ask any question about this project.]

**Comment by ReggieCarey** [comment]
Is there a migration path from 1.2 to 1.3? Will it be in the form of instructions or will it be automated?  If automated, will someone enhance the kubeflow operator?  The last time I tried to uninstall kubeflownto repair something all of my users lost all of their data.

**Comment by DavidSpek** [comment]
I'm not sure about an upgrade path as Istio will also need to be upgraded, but uninstalling Kubeflow should remove everything from the cluster and should never be used to fix something.

**Comment by jbottum** [comment]
@ReggieCarey did you get a solution for this ?

**Comment by ReggieCarey** [comment]
> @ReggieCarey did you get a solution for this ?

Have not tried any upgrade to 1.3.

**Comment by zulissi** [comment]
Interested in this as well! A documented process to upgrade while maintaining old namespaces/PVC's would be very helpful.
