### ISSUE TITLE
[Kubeflow 1.3] Allows dynamic label configuration on profile-controller for Istio upgrade

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/kubeflow#5712]
/kind bug

**What steps did you take and what happened:**

To prepare for Kubeflow 1.3 release, we need to upgrade Istio from 1.4 to 1.9: https://github.com/kubeflow/gcp-blueprints/issues/144. However, in order to inject sidecar for new Istio versions, we need to remove the label: `istio-injection:enabled` for any namespace created by users, and enable automatic sidecar injection in new version. See [reference](https://cloud.google.com/service-mesh/docs/proxy-injection#enabling_automatic_sidecar_injection). With the `istio-injection` existing, automatic side injection is disabled in new version. Therefore, we need to allow users of profile-controller to configure labels in the following two places:

https://github.com/kubeflow/kubeflow/blob/28af7716bc22f25158ddde05af58d53f4fafc939/components/profile-controller/controllers/profile_controller.go#L131
https://github.com/kubeflow/kubeflow/blob/28af7716bc22f25158ddde05af58d53f4fafc939/components/profile-controller/controllers/profile_controller.go#L68-L72

Since we are upgrading istio versions across Kubeflow (https://github.com/kubeflow/manifests/issues/1735) in v1.3 release, we need to make the corresponding change before feature cut.

cc @yanniszark @Bobgy @kimwnasptd

**Comment by DavidSpek** [comment]
@zijianjoy I've just been looking into this a bit and the Istio docs state that adding the `istio-injection:enabled` to a namespace is still the method for injecting sidecars. Am I correct in understanding that the `istio.io/rev=` is necessary to be able to upgrade existing Istio and Kubeflow installations?

**Comment by Bobgy** [comment]
The new label is suggested for Anthos Service Mesh, the label makes it possible to install two versions of istio at the same time, so there can be smooth upgrade

**Comment by DavidSpek** [comment]
Will this not break regular Istio Service Mesh installations if the `istio-injection:enabled` label is removed?

**Comment by Bobgy** [comment]
@DavidSpek our suggestion is to make labels configurable, so that it doesn't affect other use-cases

**Comment by yanniszark** [comment]
@bobgy seems like this is needed for GCP environments. Should we discuss and agree on a mechanism for adding labels to profile namespaces? For example, a new CLI arg (e.g., `--namespace-labels`) with a format like `key=value,key=value,...` (same as kubectl) and a default value of the existing labels.
The release date is very close, so such a PR should be made ASAP if it is to be included in the RC. Will you or @zijianjoy create it?

**Comment by Bobgy** [comment]
Not fully sure about the format, it doesn't look easy to split labels across multiple patches (which seems very likely needed during configuration).
I'll work with @zijianjoy, who will be writing a PR.

However, I think we are not 100% blocked on profile controller, it's OK for GCP to use its own fork, because looks like we'll be the only one needing this feature.

**Comment by Bobgy** [comment]
A more urgent issue might be adding a `pipelines.kubeflow.org/enabled` label to namespaces, I'll make sure that's added ASAP.

**Comment by yanniszark** [comment]
> A more urgent issue might be adding a pipelines.kubeflow.org/enabled label to namespaces, I'll make sure that's added ASAP.

@Bobgy I understand that this is needed in order for KFP to work with KF 1.3, correct? Thanks for bringing it up, looking forward to the PR. BTW, if you make this PR, then perhaps it makes sense to also include the label configuration setting. What do you think?

**Comment by zijianjoy** [comment]
Thank you @Bobgy for helping answering questions on this thread!

@DavidSpek : Thank you for checking the latest documentation of Istio! We will make sure `istio-injection:enabled` exists for scenarios where Anthos is not being used.

@yanniszark Sharing my attempt of adding configurable labels here, meanwhile me and @Bobgy are working on a PR. Please comment if you feel that this approach is not feasible or can be better:

* Create a [volumeMounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap):`namespace-labels-data` as input to `components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml`.
* profile manager declares a volume from above in GCP manifest, insert any label we need from there.
* Inside the `components/profile-controller/controllers/profile_controller.go`, read from volumeMount if such file exists. 
* In `profile_controller.go`, apply `istioInjectionLabel: "enabled"` and `kubeflowNamespaceLabels` as they already exist. 
* If volumeMount -> `namespace-labels-data` exists, apply any new label from this file. If there is a label with `null` value, for example: `istioInjectionLabel: null` in volumeMount, remove label `istioInjectionLabel` from namespace.

**Comment by yanniszark** [comment]
@zijianjoy thanks for the update, I'm glad you're working on this. I have some questions regarding the design.
More specifically, it seems a bit complicated to me while it shouldn't be, at least from my current point of view.
My question is, why can't we go with a simpler design, like a CLI argument?
e.g., https://github.com/kubeflow/kubeflow/issues/5712#issuecomment-803987717

What do we gain from the described solution?

**Comment by Bobgy** [comment]
For clarification, it seems GCP distribution will be the only one needing this. So I don't feel it's a blocker to release. If we cannot catch up with the release train, it's ok for us to release a fork of profile controller only used in GCP distributions.

Anyway, it'll be great if we can catch up.

**Comment by zijianjoy** [comment]
@yanniszark 
> What do we gain from the described solution?

Thank you Yannis! And we definitely have your suggestion in mind and we are open to it. The benefit of my proposal is that users can change ConfigMap for namespace labels at any point of time, and without interfering with profile controller deployment. It gives flexibility and scalability with a yaml file because users don't need to restart profile controller, and they can add comments to explain why such label needs to be enforced in a yaml file.

Please review the PR https://github.com/kubeflow/kubeflow/pull/5761 for the proposal. If this solution looks feasible to you, we can evaluate it for gcp scenario and see if it makes sense.

**Comment by yanniszark** [comment]
> The benefit of my proposal is that users can change ConfigMap for namespace labels at any point of time, and without interfering with profile controller deployment. It gives flexibility and scalability with a yaml file because users don't need to restart profile controller, and they can add comments to explain why such label needs to be enforced in a yaml file.

I'll make sure to take a look after the 1.3 release. Thanks!

**Comment by thesuperzapper** [comment]
@yanniszark @Bobgy @zijianjoy as discussed this in the community meeting, if this remains a significant issue for the GCP distribution, we should probably resolve it before we GA the manifests for Kubeflow 1.3.

**Comment by yanniszark** [comment]
@thesuperzapper from comment https://github.com/kubeflow/kubeflow/issues/5712#issuecomment-805587304, I understand it is not a blocker for the release.

**Comment by thesuperzapper** [comment]
@zijianjoy can you confirm if this is a big issue for GCP?

**Comment by zijianjoy** [comment]
> @zijianjoy can you confirm if this is a big issue for GCP?

I confirm this is essential to GCP: ASM (Anthos Service Mesh) is a managed version of istio. Without this change, Kubeflow access and multi-user feature will not perform correctly. However, like Yannis said, we can use the profile controller image of our own, therefore not blocking Kubeflow 1.3 release.
