### ISSUE TITLE
Kubeflow 1.2 GCP install - Istio pods stuck in containerCreating

### ISSUE THREAD

**Issue by ulrikpl** [kubeflow/kubeflow#5714]
I am stuck trying to install Kubeflow 1.2 on GCP. The istio system has four pods hanging in containerCreating and no amount of 'make apply' will fix it. I followed the installation guide including the management cluster install guide to the T. Any pointers would be greatly appreciated. 

Set-up:
Google Cloud Shell
Kustomize: 3.2.1 (version 4 didn't work for KF1.2 in my experience)
yq: 3.4.1
istioctl version:
    client version: 1.4.10-asm.18
    ingressgateway version: 1.4.10-asm.15
    ingressgateway version: 1.4.10-asm.15
    nodeagent version:
    nodeagent version:
    pilot version: 1.4.10-asm.15
    pilot version: 1.4.10-asm.15
    data plane version: none

$kubectl describe pods istio-galley-5755dcb596-djb9m -n istio-system

Yields output:

`
Name:           istio-galley-5755dcb596-djb9m
Namespace:      istio-system
Priority:       0
Node:           gke-kubeflow-default-pool-6d032189-4m1b/10.154.0.7
Start Time:     Wed, 17 Mar 2021 18:17:57 +0000
Labels:         app=galley
                chart=galley
                heritage=Tiller
                istio=galley
                pod-template-hash=5755dcb596
                release=istio
Annotations:    sidecar.istio.io/inject: false
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/istio-galley-5755dcb596
Containers:
  galley:
    Container ID:
    Image:         gcr.io/gke-release/asm/galley:1.4.10-asm.15
    Image ID:
    Ports:         9443/TCP, 15014/TCP, 15019/TCP, 9901/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
     /usr/local/bin/galley
      server
      --meshConfigFile=/etc/mesh-config/mesh
      --livenessProbeInterval=1s
      --livenessProbePath=/tmp/healthliveness
      --readinessProbePath=/tmp/healthready
      --readinessProbeInterval=1s
      --insecure=true
      --enable-validation=true
      --enable-reconcileWebhookConfiguration=true
      --enable-server=true
      --deployment-namespace=istio-system
      --validation-webhook-config-file
      /etc/config/validatingwebhookconfiguration.yaml
      --monitoringPort=15014
      --validation-port=9443
      --log_output_level=default:info
      --validation.tls.clientCertificate=/etc/dnscerts/cert-chain.pem
      --validation.tls.privateKey=/etc/dnscerts/key.pem
      --validation.tls.caCertificates=/etc/dnscerts/root-cert.pem
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Liveness:     exec [/usr/local/bin/galley probe --probe-path=/tmp/healthliveness --interval=10s] delay=5s timeout=1s period=5s #success=1 #failure=3
    Readiness:    exec [/usr/local/bin/galley probe --probe-path=/tmp/healthready --interval=10s] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
     /etc/config from config (ro)
      /etc/dnscerts from dnscerts (ro)
      /etc/mesh-config from mesh-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-galley-service-account-token-425xg (ro)
  istio-proxy:
    Container ID:
    Image:         gcr.io/gke-release/asm/proxyv2:1.4.10-asm.15
    Image ID:
    Port:          9902/TCP
    Host Port:     0/TCP
    Args:
      proxy
      --serviceCluster
      istio-galley
      --templateFile
      /var/lib/istio/galley/envoy/envoy.yaml.tmpl
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --trust-domain=kubeflow-test-ulrik.svc.id.goog
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
   Environment:
      POD_NAME:       istio-galley-5755dcb596-djb9m (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
      SDS_ENABLED:    true
    Mounts:
      /var/lib/istio/galley/envoy from envoy-config (rw)
      /var/run/sds from sds-uds-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-galley-service-account-token-425xg (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  sds-uds-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/sds
    HostPathType:
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  dnscerts:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dns.istio-galley-service-account
    Optional:    false
  envoy-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      galley-envoy-config
    Optional:  false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-galley-configuration
    Optional:  false
  mesh-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-mesh-galley
    Optional:  false
  istio-galley-service-account-token-425xg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-galley-service-account-token-425xg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  30m (x20 over 4h1m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[dnscerts], unattached volumes=[envoy-config sds-uds-path istio-token dnscerts config mesh-config istio-galley-service-account-token-425xg]: timed out waiting for the condition
  Warning  FailedMount  19m (x119 over 4h5m)    kubelet  MountVolume.SetUp failed for volume "dnscerts" : secret "dns.istio-galley-service-account" not found
  Warning  FailedMount  14m (x15 over 4h3m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[dnscerts], unattached volumes=[sds-uds-path istio-token dnscerts config mesh-config istio-galley-service-account-token-425xg envoy-config]: timed out waiting for the condition
  Warning  FailedMount  10m (x18 over 3h57m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[dnscerts], unattached volumes=[config mesh-config istio-galley-service-account-token-425xg envoy-config sds-uds-path istio-token dnscerts]: timed out waiting for the condition
  Warning  FailedMount  5m47s (x12 over 3h34m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[dnscerts], unattached volumes=[dnscerts config mesh-config istio-galley-service-account-token-425xg envoy-config sds-uds-path istio-token]: timed out waiting for the condition
`

**One of the sidecar injector pods yields:

$kubectl describe pods istio-sidecar-injector-f475c7995-9vxhc -n istio-system**

`
Name:           istio-sidecar-injector-f475c7995-9vxhc
Namespace:      istio-system
Priority:       0
Node:           gke-kubeflow-default-pool-6d032189-4m1b/10.154.0.7
Start Time:     Wed, 17 Mar 2021 18:17:59 +0000
Labels:         app=sidecarInjectorWebhook
                chart=sidecarInjectorWebhook
                heritage=Tiller
                istio=sidecar-injector
                pod-template-hash=f475c7995
                release=istio
Annotations:    sidecar.istio.io/inject: false
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/istio-sidecar-injector-f475c7995
Containers:
  sidecar-injector-webhook:
    Container ID:
    Image:         gcr.io/gke-release/asm/sidecar_injector:1.4.10-asm.15
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --caCertFile=/etc/istio/certs/root-cert.pem
      --tlsCertFile=/etc/istio/certs/cert-chain.pem
      --tlsKeyFile=/etc/istio/certs/key.pem
      --injectConfig=/etc/istio/inject/config
      --meshConfig=/etc/istio/config/mesh
      --port=9443
      --healthCheckInterval=2s
      --healthCheckFile=/tmp/health
      --reconcileWebhookConfig=true
      --webhookConfigName=istio-sidecar-injector
      --log_output_level=debug
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        10m
    Liveness:     exec [/usr/local/bin/sidecar-injector probe --probe-path=/tmp/health --interval=4s] delay=4s timeout=1s period=4s #success=1 #failure=3
    Readiness:    exec [/usr/local/bin/sidecar-injector probe --probe-path=/tmp/health --interval=4s] delay=4s timeout=1s period=4s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/istio/certs from certs (ro)
      /etc/istio/config from config-volume (ro)
      /etc/istio/inject from inject-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-sidecar-injector-service-account-token-zgnh4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      injector-mesh
    Optional:  false
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dns.istio-sidecar-injector-service-account
    Optional:    false
  inject-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-sidecar-injector
    Optional:  false
  istio-sidecar-injector-service-account-token-zgnh4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-sidecar-injector-service-account-token-zgnh4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  31m (x36 over 4h)       kubelet  Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[config-volume certs inject-config istio-sidecar-injector-service-account-token-zgnh4]: timed out waiting for the condition
  Warning  FailedMount  11m (x16 over 3h51m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[inject-config istio-sidecar-injector-service-account-token-zgnh4 config-volume certs]: timed out waiting for the condition
  Warning  FailedMount  6m30s (x22 over 3h53m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[certs], unattached volumes=[istio-sidecar-injector-service-account-token-zgnh4 config-volume certs inject-config]: timed out waiting for the condition
  Warning  FailedMount  2m6s (x126 over 4h2m)   kubelet  MountVolume.SetUp failed for volume "certs" : secret "dns.istio-sidecar-injector-service-account" not found

`

**Comment by wkeifenheim** [comment]
@ulrikpl The thread over at https://github.com/kubeflow/gcp-blueprints/issues/198 identified what the problem is. I couldn't get the workaround there to kustomize the `Pilot.yaml` during `make apply` working, so I applied the update manually then deleted all the pods in the `istio-system` namespace to get everything past the _containerCreating_ status.

Service and Ingress are all green for me know, however I'm getting a 404 from my Kubeflow Dasboard endpoint so I guess not out of the woods yet.

**Comment by crmne** [comment]
@wkeifenheim how did you updated that manually?

would this work?

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-pilot-istio-system
  labels:
    app: pilot
    release: istio
rules:
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - approve
```

**Comment by ulrikpl** [comment]
Thank you @wkeifenheim wkeifenheim. I too did finally manage to install it using the patch/workaround. The  kustomize trick didn't work for me because Pilot.yaml is made using istioctl and not kustomize. Also changing the upstream folder is a bit against the idea of having a base folder. What I did is admittedly a bit hacky, but it works and removes the need to delete any pods. I added the patch.yaml and kustomization.yaml files to a folder in project root. I then just copy these two files to the .build/.../Pilot folder and do the kustomization there and deletes the two files again, leaving the edited Pilot.yaml. I added this operation to the makefile in the corresponding hydrate step so it makes it a bit less hacky and istio deploys correctly from the start. 

Yes @crmne that is the edit that worked for me. 

As a side note, the docs point to 'latest' Kustomize version, which is now v4 so that doesn't work. 3.2.1 did work however

**Comment by rdoume** [comment]
Hey everyone,

I'm not sure I properly understand the fix described in  #https://github.com/kubeflow/gcp-blueprints/issues/198, especially on how to patch the Pilot.yml.

I'm not super proficient with the whole kubernetes ecosystem & deployment, so I'm a bit struggling between the whole set of tools used to deploy here.

**Comment by wkeifenheim** [comment]
@ulrikpl Thanks for posting your fix! Off-topic, but have you happened to look at logging with your deployment? I had around 40k error messages a minute being generated from bad config, but the Kubeflow deployment otherwise looked all green and was working from the minimal testing I performed. I wonder if the way I went about adding the legacy permission caused the explosion in log volume..

**Comment by ulrikpl** [comment]
@wkeifenheim I haven't looked yet. The deployment is not smooth at all in my experience. Haven't made a single one without getting weird errors and exited 'make apply' deployments. Pods do eventually come up though so it seems to be a question of holding your nose and 'make apply' a few times. I suspect it has to do with interdependencies between pods and insufficient wait times between their deployments.

**Comment by wkeifenheim** [comment]
> it seems to be a question of holding your nose and 'make apply' a few times.

@ulrikpl Accurate 😅 . Believe it is a CRD race issue that was apparently fixed at some point, but is certainly present now ([ref](https://github.com/kubeflow/kubeflow/issues/1933)). I had to run `make apply` four times to get all the way through deployment.
