### ISSUE TITLE
Failed to get object from minio on microk8s

### ISSUE THREAD

**Issue by Ursanon** [kubeflow/kubeflow#5724]
/kind bug

I have kubeflow running via MicroK8s on VM.
When I want to access my pipeline component's output artifact:
![image](https://user-images.githubusercontent.com/8686134/111796250-49ec6d00-88c8-11eb-944f-c1d525f00f08.png)

error occurs:
```
Failed to get object in bucket mlpipeline at path artifacts/hello-world-5f52l/hello-world-5f52l-940018/mlpipeline-metrics.tgz:
S3Error: The request signature we calculated does not match the signature you provided.
Check your key and signing method.
```

**Environment:**

- Kubeflow version: `dev_local` - commit: `743746b96e6efc502c33e1e529f2fe89ce09481c`
- Kubernetes platform: microk8s
- Kubernetes version: `v1.19.8-34+811e9feeade1d3`
- OS: `Ubuntu 18.04.5 LTS`

**Comment by Ursanon** [comment]
When I head to `Artifacts` console shows me:
![image](https://user-images.githubusercontent.com/8686134/111806311-25958e00-88d2-11eb-99ee-5fece31a279c.png)

**Comment by DavidSpek** [comment]
@Ursanon Could you please move this issue over to https://github.com/canonical/bundle-kubeflow? This seems to be a bug specific to Microk8s and isn't related to the code in this repository. I don't think many people from Canonical are actively going through the issues here either.

**Comment by Ursanon** [comment]
Moved. Thanks @DavidSpek
