### ISSUE TITLE
TFJobs UI doesn't work behind IAP; React APP needs support IAP?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#574]
TFJobs UI is deployed on dev.kubeflow.org.

The UI shows up behind IAP but its doesn't work
- No TFJobs are listed
- Creating a job via the UI doesn't work.

Looking at the developer console we see requests to

```
https://accounts.google.com/o/oauth2/v2/auth?client_id=235037502967-9cpmvs4ljbiqb3ojtnhnhlkkd8d562rl.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://dev.kubeflow.org/_gcp_gatekeeper/authenticate&state=Ci1odHRwczovL2Rldi5rdWJlZmxvdy5vcmcvdGZqb2JzL2FwaS9uYW1lc3BhY2USMEFOa2F0U2dYVjdSYnlHMzVXeGFwR1gxNURTS29TNjNiYnc6MTUyMjc4MDQxODEwOA
```

Which suggests to me the request is hitting the loadbalancer and being directed to do auth verification to sign in and its getting rejected.

So I think one of two things is happening

1. The request is coming from the server running in K8s and incorrectly being redirected to the external loadbalncer and thus hitting IAP when it shouldn't be
1. The request is coming from the client and the client needs to be updated to support IAP.

@wbuchwalter Do you know where the request is coming from?

You should be able to access it at
https://dev.kubeflow.org/tfjobs/ui/

**Comment by wbuchwalter** [comment]
@jlewi @ankushagarwal Could one of you grant me access to dev.kubeflow.org so I can test this?
`wbuchwalter at gmail`.
Thanks!

@jlewi This is most likely `2`

**Comment by jlewi** [comment]
I think @wbuchwalter started looking at this last week.

**Comment by jlewi** [comment]
@wbuchwalter any update?

**Comment by jlewi** [comment]
Punting to 0.3 because no one is actively working on this so I don't think its going to make the cut.

**Comment by kkasravi** [comment]
@jlewi I can look at this - given my recent wrestling with jupyterhub I think it should be straigtforward.

**Comment by jlewi** [comment]
@kkasravi That would be fantastic. 

Related; it looks like recent changes to the central UI also created problems for IAP (kubeflow/kubeflow#957)

I'd like to better understand the proper way to write web apps that are compatible with reverse proxies and IAP.

**Comment by jlewi** [comment]
There's some guidance here about handling IAP refresh
https://cloud.google.com/iap/docs/sessions-howto

**Comment by jlewi** [comment]
I just noticed that when I access the TFJobs dashboard the javascript console shows

```
Failed to load https://accounts.google.com/o/oauth2/v2/auth?client_id=236417448818-9roj383c48ruubrcjr9t6utf6mimlntf.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog/_gcp_gatekeeper/authenticate&state=Ck1odHRwczovL2psZXdpLWt1YmVmbG93LmVuZHBvaW50cy5jbG91ZC1tbC1kZXYuY2xvdWQuZ29vZy90ZmpvYnMvYXBpL25hbWVzcGFjZRIwQUFoLVdabVA1N1IxWEFTRUE0RkFFanRUVXBqcU5MZjNUQToxNTI4NDgzNTQxNTk5: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by jlewi** [comment]
Here's a suggestion I got

> If it's all on the same domain, you just need [withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) to be set to true on your XMLHttpRequests, that will cause the IAP cookie to be included when the Javascript makes its request.

> In React:

```
fetch(url, {
   ...options
  credentials: 'include', // sets    withCredentials to true
});
```

**Comment by jlewi** [comment]
@ankushagarwal  Can you coordinate with Kam and try out the simple fix listed above?

/assign @ankushagarwal

**Comment by kkasravi** [comment]
for jupyterhub it sets the x-goog-authenticated-user-email for REMOTE_USER - https://github.com/cwaldbieser/jhub_remote_user_authenticator#f1 - probably not telling @ankushagarwal anything he doesn't already know ...

**Comment by kkasravi** [comment]
working on this - had a few problems creating an IAP enabled cluster within our PROJECT
related to permission denied on patch-iam-policy

**Comment by jlewi** [comment]
@kkasravi Kam happy to give you access to dev.kubeflow.org so you can create projects there.

**Comment by kkasravi** [comment]
the services.js does have the fetch on line 5
```
export function getTFJobListService(namespace) {
  return fetch(`${host}/api/tfjob/${namespace}`).then(r => r.json());
}
```
However I don't think that's the problem.

I put tf-jobs behind ambassador and chrome is telling me that 
the Access-Control-Allow-Origin is missing from the origin 

I added cors to the tf-jobs-dashboard ambassador annotation by editing it directly
```
          "getambassador.io/config":
            std.join("\n", [
              "---",
              "apiVersion: ambassador/v0",
              "kind:  Mapping",
              "name: tfjobs-ui-mapping",
              "prefix: /tfjobs/",
              "rewrite: /tfjobs/",
              "cors:",
              "cors:",
              "  origins: https://kamkasravi.com",
              "  credentials: yes",
              "service: tf-job-dashboard." + namespace,
```
i'm testing this approach. Will likely need to update the bootstrapper image.
Will have more info Sunday evening (1/17)

**Comment by kkasravi** [comment]
i think i may need to rebuild the centraldashboard. Pinged @swiftdiaries

**Comment by kkasravi** [comment]
answered in slack but copying here for tracking purposes

when kubeflow is deployed with IAP enabled and you click on the 'tfjob' link in the kubeflow dashboard in the browser you'll see an error 'Failed to load https://accounts.google.com/o/oauth2/v2/auth?client_id=336335541993-1m7cegck4jic23263v0gplhc46f4rmmj.apps.googleusercontent.com...: No 'Access-Control-Allow-Origin' header is present on the requested resource'. The browser fails to load the oauth call to google because the request didn't set Origin, Access-Control-Request-Method, Cookie. If these request headers are set on the call to /tfjobs/ui/ then google will return Access-Control-Allow-Origin which will allow the browser to make the call to google for authentication. This can set in ambassador which will then allow the browser to call accounts.google.com and fetch the credentials. I'll provide a writeup on the issue and a reference in the PR.

**Comment by kkasravi** [comment]
update: testing changes in tf-operator frontend services.js

**Comment by kkasravi** [comment]
the PR for this issue is [here](https://github.com/kubeflow/tf-operator/pull/688)

**Comment by jlewi** [comment]
Fantastic thank you!

**Comment by kkasravi** [comment]
@jlewi @swiftdiaries 
The fix made in tf-operator frontend services.js needs to be changed so that it works in a similar way as envoy and jupyterhub. This also ends up being a fairly trivial fix, but needed additional research to understand how envoy does auth filtering for jupyterhub (and not tfjobs).

Envoy applies a authFilter in iap.libsonnet which uses a request header of x-goog-iap-jwt-assertion and does jwt processing prior to subsequent routing. If authenticated envoy adds a x-goog-authenticated-user-email request header for registered routes. This header is used within jupyterhub to identify the user and spawn a jupyter notebook with that user's email. 

Envoy needs to add the tfjob routes in order to have this authFilter applied which will in turn will enter the tfjob backend entrypoint with the x-goog-authenticated-user-email header. This should just amount to adding the /tfjobs/ route in iap.libsonnet.

I'll test and update the PR today/tomorrow and provide some additional details on auth in general in our web site pages so we don't continue to hit this problem. Currently I believe this knowledge is silo'd amongst one or two people who aren't necessarily watching for service errors that are IAP related.

**Comment by kkasravi** [comment]
Update: based on the 2 PR's [#688](https://github.com/kubeflow/tf-operator/pull/688), #1073 the UI gets an initial CORS error and subsequent /tfjob/ requests work. I would like to remove the initial CORS error as well but the UI for TFJobs is now functioning.

**Comment by kkasravi** [comment]
I need to replace the tfJobImage reference in kubeflow/kubeflow/core/prototypes/all.jsonnet with the right tf-operator image from gcr.io/kubeflow-images-public/tf-operator.

**Comment by jlewi** [comment]
Thanks @kkasravi.

I believe it is IAP not envoy that adds the header;
https://cloud.google.com/iap/docs/identity-howto

I'm still not sure I understand why in #1073 we had to explicitly add a route to envoy for /tfjobs. The default route in our envoy config sends everything to Ambassador. That route should apply the authFilter that does JWT validation to all traffic that passes through it.

Is Ambassador stripping out these headers? The fact that we don't route JupyterHub through Ambassador is a historical accident. If it turns out that Ambassador breaks IAP we should figure that out.

I think a good way to test this would be to add a route for the whoamIservice that sits behind Ambassador
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/iap.libsonnet#L655

This is a simple web app that we use to test IAP because it will print out the header containing your email. So if that doesn't work behind Ambassador then we know we have an issue with Ambassador and IAP.

@kflynn Is it expected that Ambassador would be stripping out certain headers?

**Comment by jlewi** [comment]
I tried putting whoami behind Ambassador and it seemed to work just fine.

**Comment by jlewi** [comment]
I think to make debugging easier we should create a simple app that echos the headers it received. 

We could start with 
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/main.py

i don't think whoami (esp-sample-app) echos the headers it receives. Looking at the request headers in dev console in chrome probably isn't what we want because the headers will get added by IAP so won't be visible on the client.

**Comment by kflynn** [comment]
@jlewi I wouldn't expect Ambassador's Envoy to strip information from IAP, so I'm very interested in seeing how this plays out.

**Comment by kkasravi** [comment]
I can try removing the route but keep the other changes in tf-operator. It’s possible this is extraneous. I’m on PTO but will try this today. Currently i’m 3 hours ahead (PST). I did try the list and create operations. The create operation failed for other reasons (seems to be missing namespace) and I opened an issue on this in tf-operator

**Comment by jlewi** [comment]
@kkasravi I can try this out. I've got a sample app running. Here are the headers I see

```
{
  "headers": [
    [
      "Cookie", 
      "_xsrf=2|5c162792|f72997fe27b076e7b922d0923bc9297f|1529461576; jupyterhub-session-id=de3c3d7a16f048ae86fb34a546b6bb56; GCP_IAAP_XSRF_NONCE=jIHvjvW8o7MTu-8QbTzm6F6ihxK03ctj2jRLTx8xCzcbyZwKkjDxNBTuG0UQfYaRiI7qtduS_W09tuaEANJfbiChNO4xNuGlhIq1eBWNESP5TqRWNDFHX9p6FiCac2hnANjCGpjA7MJoElAZ44Hb4RhpzuRzILPfTaVZnQPvtsw"
    ], 
    [
      "Content-Length", 
      "0"
    ], 
    [
      "User-Agent", 
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
    ], 
    [
      "X-Goog-Authenticated-User-Id", 
      "accounts.google.com:112668565718473025939"
    ], 
    [
      "Via", 
      "1.1 google"
    ], 
    [
      "X-Forwarded-Proto", 
      "https"
    ], 
    [
      "X-Goog-Authenticated-User-Email", 
      "accounts.google.com:jlewi@google.com"
    ], 
    [
      "Sec-Istio-Auth-Userinfo", 
      "eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vaWFwIiwic3ViIjoiYWNjb3VudHMuZ29vZ2xlLmNvbToxMTI2Njg1NjU3MTg0NzMwMjU5MzkiLCJlbWFpbCI6ImpsZXdpQGdvb2dsZS5jb20iLCJhdWQiOiIvcHJvamVjdHMvMjM2NDE3NDQ4ODE4L2dsb2JhbC9iYWNrZW5kU2VydmljZXMvODc2NDc0OTc0NDY5MjYxODYxMCIsImV4cCI6MTUzMDIwNTA4MiwiaWF0IjoxNTMwMjA0NDgyLCJoZCI6Imdvb2dsZS5jb20ifQ"
    ], 
    [
      "X-Envoy-Original-Path", 
      "/echo/headers"
    ], 
    [
      "Host", 
      "jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog"
    ], 
    [
      "Upgrade-Insecure-Requests", 
      "1"
    ], 
    [
      "Cache-Control", 
      "max-age=0"
    ], 
    [
      "Accept", 
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
    ], 
    [
      "Accept-Language", 
      "en-US,en;q=0.9"
    ], 
    [
      "X-Cloud-Trace-Context", 
      "0ec4d285905293ec89e399fd5d61635e/1146299229727795052"
    ], 
    [
      "X-Envoy-Expected-Rq-Timeout-Ms", 
      "3000"
    ], 
    [
      "X-Forwarded-For", 
      "104.132.7.98, 35.241.56.180"
    ], 
    [
      "X-Request-Id", 
      "b620ccff-ca78-4020-b4c3-fbcccc06d1b1"
    ], 
    [
      "Accept-Encoding", 
      "gzip, deflate, br"
    ]
  ]
}
```

**Comment by jlewi** [comment]
I ran into some really strange behavior with ksonnet and adding Ambassador mappings; see https://github.com/ksonnet/ksonnet/issues/670

**Comment by jlewi** [comment]
I tried the two fixes Kam mentioned above

#1 Use #688 in TFJobs UI to set request headers.
#2 #1073 to directly add route to tfjobs to envoy to avoid Ambassador.

For #1 I used 
gcr.io/kubeflow-images-staging/tf_operator:kubeflow-tf-operator-presubmit-v2-688-1b33543-759-49f7
which is the image I grabbed from Kam's presubmit and then pushed to kubeflow-images-staging.

When I navigate to tfjobs/UI I'm still seeing errors 

```
Failed to load https://accounts.google.com/o/oauth2/v2/auth?client_id=236417448818-9roj383c48ruubrcjr9t6utf6mimlntf.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog/_gcp_gatekeeper/authenticate&state=CkpodHRwczovL2psZXdpLWt1YmVmbG93LmVuZHBvaW50cy5jbG91ZC1tbC1kZXYuY2xvdWQuZ29vZy90ZmpvYnMvYXBpL3Rmam9iLxIwQUFoLVdaa2huTkVXb0xHRnRCek55RVFlZUtnMXJreEs5ZzoxNTMwMjE4NDIzNzk1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
When I try to create a job in the UI I get

```
services.js:18 POST https://jlewi-kubeflow.endpoints.cloud-ml-dev.cloud.goog/tfjobs/api/tfjob 401 ()
SyntaxError: Unexpected token T in JSON at position 0
```

**Comment by jlewi** [comment]
I ran an experiment where I enabled CORS everywhere using a firefox plugin
https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/

That fixed the Failed to load error. Not it looks like I'm just get the json error

When I created a TFJob (via the CLI) it should up in the dashboard but when I tried to click on it I got the json error above.  I have v1alpha2 of TFJob configured. I wonder if its still using TFJob v1alpha1 and that is the problem.

**Comment by kkasravi** [comment]
@jlewi are you using 'default' for the namespace? I opened https://github.com/kubeflow/tf-operator/issues/701 which happens when a different namespace is used. However the POST to create the tfjob was getting to the server. I'm wondering if my cors headers aren't correct if your firefox plugin is working everywhere. I mentioned that I get the 'Failed to load ...' error once when going to the tfjob page and afterwards i don't see it reappearing even though the /tfjob/ refreshes every 30sec or so.

I'm working on a fix for https://github.com/kubeflow/tf-operator/issues/701 which adds the KUBEFLOW_NAMESPACE to the tf-operator environment in tf-job-operator.libsonnet.
https://github.com/kubeflow/kubeflow/pull/1099

**Comment by jlewi** [comment]
@kkasravi Kubeflow is deployed in namespace kubeflow. I think I used that namespace for the job as well.

Would it be worth while to try to create a simple test app that we could use to work out the CORS issues without conflating it with other issues? I'm not sure what that would look like exactly.

**Comment by kkasravi** [comment]
@jlewi sure - a simple POST to a URL like this one with a backend go app that sends back an app or something

**Comment by kkasravi** [comment]
Won't be able to get to this until late afternoon/early evening due to PTO plans most of day. Will update

**Comment by kkasravi** [comment]
i believe what is remaining on this is https://github.com/kubeflow/tf-operator/pull/688 which sets up cors for all tfjobs fetches in the UI (services.js).

**Comment by jlewi** [comment]
We need to build a new

**Comment by jlewi** [comment]
I reopened this issue to track verification that it is working after updating the images.

**Comment by jlewi** [comment]
I created a new image:
gcr.io/kubeflow-images-public/tf_operator:v20180724-13863edf

Looks like IAP is now working. Here's a screen shot showing that the jobs can load.

![tfjobs_ui](https://user-images.githubusercontent.com/777219/43179151-0cad834a-8f86-11e8-8e8a-86d5cffe2321.png)

Note though that nothing is showing up in Name, Status, Logs.

Developer console is showing me errors

```
:8080/tfjobs/api/namespace:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
SyntaxError: Unexpected token a in JSON at position 1
    at services.js:81
registerServiceWorker.js:65 Content is cached for offline use.
```

I see similar errors if try to create a job via the UI. 

This appears to be a different issue, not related to IAP. I observe similar behavior if I try to create a job via the UI.
