### ISSUE TITLE
CodeServer Image Failing

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/kubeflow#5745]
Greetings,

Just attempted to use the public.ecr.aws.j1r0q0g6/notebooks/notebook-servers/codeserer-python:master-c99f886b image on a CPU only node with the following results:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/10270182/112016071-c074af00-8b02-11eb-8689-48a84c70096d.png">

This is against Kubeflow v1.2.0 on an on-prem Kubernetes v1.18.9.

In theory, there should not be an issue running these notebooks on older versions of Kubeflow. 

Thanks for any insights into the root causes of this failure.

Reggie

**Comment by ReggieCarey** [comment]
P.S. Using dockerd instead of containerd.  Apparently NVIDIA nvidia-container-runtime requires dockerd and cannot use containerd.  Could switch but its a dramatic update to an otherwise functioning K8s production cluster.

**Comment by DavidSpek** [comment]
Kubeflow 1.2 doesn't support this yet. You'd need to update the notebook-controller image and the Jupyter Web App image to the latest ones on ECR (and fix some (cluster)rolebindings to use that image.

**Comment by DavidSpek** [comment]
You can give this one a try otherwise: `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-1831e436`

**Comment by DavidSpek** [comment]
Regarding NVIDIA, GKE runs on `containerd` and has GPU support. The NVIDIA-Container-Runtime is just a patched version of `runc` to enable GPU support (`containerd` uses `runc`). 
https://josephb.org/blog/containerd-nvidia/

**Comment by DavidSpek** [comment]
@ReggieCarey Can you provide more information about this issue or can it be closed?

**Comment by ReggieCarey** [comment]
I can’t test in the new environment just yet.  It fails to run in Kubeflow 1.2.  This issue was intended to point out difficulties with the RC image. I am waiting for the rest of 1.3 RC to be ready to test.

**Comment by DavidSpek** [comment]
@ReggieCarey Are you still running into this issue?

**Comment by ReggieCarey** [comment]
Have not tried yet.
