### ISSUE TITLE
rstudio tests fail

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5747]
/kind bug

**What steps did you take and what happened:**
I tried to run the rstudio tests as part of another PR. The build failed with:
```
INFO|2021-03-22T16:27:48|/src/kubeflow/testing/py/kubeflow/testing/util.py|72| ModuleNotFoundError: No module named 'kubeflow.kubeflow.ci.notebook_servers.notebook_server_rstudio_tests'
```
http://prow.kubeflow-testing.com/log?container=test&id=1374034947567783936&job=kubeflow-kubeflow-presubmit

Looking under `py/kubeflow/kubeflow/ci/notebook_servers`, I don't see any `notebook_server_rstudio_tests` file.
cc @DavidSpek

**Comment by yanniszark** [comment]
/assign @DavidSpek 

Could you take a look?

**Comment by DavidSpek** [comment]
PR still needs to be merged, so it doesn't exist yet. https://github.com/kubeflow/kubeflow/pull/5624
Same for RStudio-Tidyverse: https://github.com/kubeflow/kubeflow/pull/5711. 
Working on cleaning them up massively now, should be ready soon.

**Comment by DavidSpek** [comment]
@yanniszark Can you confirm this has been fixed by merging the RStudio PRs?

**Comment by DavidSpek** [comment]
I believe this can be closed. 
/close
