### ISSUE TITLE
Unable to Create or apply the management cluster:

### ISSUE THREAD

**Issue by ayushpandeyemotionrx** [kubeflow/kubeflow#5749]
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
make: *** No rule to make target 'apply-cluster'.  Stop.

**Comment by DavidSpek** [comment]
@ayushpandeyemotionrx This has to do with `yq` version 3 versus version 4. For version 4 you need to use `yq eval`. The syntax for version 4 has completely changed so if the code has been written for version 3 it most likely will need to be completely rewritten. 

Where exactly are you encountering this issue?

**Comment by ayushpandeyemotionrx** [comment]
This is happening when I doing the management cluster setup while deploying Kubeflow on GCP.
I was following instructions at https://www.kubeflow.org/docs/gke/deploy/management-setup/
