### ISSUE TITLE
AutoML entry in the CentralDashboard

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5750]
/kind feature

### Why you need this feature:
We want to define the story around how to expose AutoML `Experiments` in Kubeflow. This is in continuation to the discussion from https://github.com/kubeflow/kubeflow/pull/5739#issuecomment-803622218.

In the first iteration #5739 we included AutoML under the `Experiments` section of the Central Dashboard like this
```
Notebooks
Volumes
Tensorboards
Experiments
  Pipelines
  AutoML
```

The guideline we want to enforce for the Central Dashboard is to have entries that correspond to nouns that the users can create/delete/connect-to/use. This is why we've exposed the underlying CRD objects like `Notebooks`, `Volumes`, `Tensorboards`, `Pipelines`, `Runs` etc. This way Kubeflow provides a flat list of objects the users could manipulate, to perform their ML related tasks, and acts as a cohesive platform, instead of just grouping functionalities/components together.

The issue here is that we have two distinct components [ Pipelines, AutoML ] using the same name, `Experiments`, but for different objects. 

### Describe the solution you'd like
I can see two solutions going forward, for integrating the Katib UI with the Central Dashboard, that move `AutoML` at the root level:

**Option A**
1. Add a top level `AutoML` entry
2. work on renaming the underlying CRDs from Katib after 1.3 to not use the `Experiment` name
    * this could also help on having separate CRDs for `HP Tuning`, `NAS` or other new AutoML components
    * the different components can have their own separate versions, so HP Tuning can be `v1` while NAS can be `v1alpha1`

**Option B**
1. Add a top level `Experiments (AutoML)` entry at the top level
2. Also have a top level `Experiments (KFP)` entry at the top level

<details><summary>How it looks</summary>
<p>

![Screenshot from 2021-03-22 22-19-53](https://user-images.githubusercontent.com/11134742/112055409-7c63c780-8b5f-11eb-894a-a6351937fac0.png)

</p>
</details>

WDYT @andreyvelich @gaocegege @johnugeorge 

### Anything else you would like to add:
These guidelines of the Dashboard does not limit us in any way on how we want the app to behave in standalone mode. In standalone mode it can have a hamburger menu on the top left and a sidenav and organize the entries however we want there.

**Comment by kimwnasptd** [comment]
Also cc @StefanoFioravanzo  who is mainly maintaining the Central Dashboard

**Comment by kimwnasptd** [comment]
I would personally vote for option 2 for now, since we both add AutoML at the root level,  and align with the current guideline. 

And we can keep on iterating on the structure and the pages of the Katib UI going forward and decide what makes sense for us. I can open a PR first thing tomorrow for any option we decide to go on with.

**Comment by DavidSpek** [comment]
I think option B is a bit messy, but option A also doesn't make sense I think. Also, what is the difference between `runs` and `executions`?

Wouldn't the following be an option?

```
Notebooks
Volumes
Tensorboards
Experiments
Pipelines
  Artifacts
  Executions
  Experiments
  ...
AutoML
  Experiments
  ...
```
I think the most important thing here is to have a clear view which things relate to each other and how. This way the dashboard is (hopefully) setup so everything is in the place the user expects them to be.

**Comment by andreyvelich** [comment]
I agree with @DavidSpek to keep this structure at least for Kubeflow 1.3:
```
Notebooks
Volumes
Tensorboards
Pipelines
  Artifacts
  Executions
  Experiments
  ...
AutoML (or Katib)
  Experiments
  ...
 ```
 The question, how make it easier for the user? Keep AutoML or Katib ?
 In the future versions, if we decide to keep various CRDs for HP, NAS, AutoMC we can easily extend the subsections:
 ```
 AutoML (or Katib)
  Hyperparameter tuning
  Neural Architecture Search
 ```
 
 WDYT @kimwnasptd @DavidSpek @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
> Notebooks
> Volumes
> Tensorboards
> Pipelines
>   Artifacts
>   Executions
>   Experiments
>   ...
> AutoML (or Katib)
>   Experiments
>   ...

I agree with @andreyvelich

**Comment by DavidSpek** [comment]
I agree with @andreyvelich, but just want to include my comment about the order of the top section in here:

```
Notebooks
Tensorboards
Volumes
Pipelines
  Artifacts
  Executions
  Experiments
  ...
AutoML (or Katib)
  Experiments
  ...
```

**Comment by StefanoFioravanzo** [comment]
@DavidSpek @andreyvelich I will try to re-elaborate on what @kimwnasptd tried to convey here:

> The guideline we want to enforce for the Central Dashboard is to have entries that correspond to nouns that the users can create/delete/connect-to/use.

We want to group **objects** together, giving more semantic meaning to how users see items in the sidebar. It is arguably better to show per-object groups rather than per-app ones. It's not about CRDs even, because a high level use of Kubeflow doesn't imply that someone even knows what they are.

I see KFP experiments and Katib experiments (either HP Tuning or NAS experiments) as being part of the same semantic group. Katib **Trials** would correspond to KFP Runs, instead.

Given this reasoning, I would strongly advise not to go back thinking about Apps by doing this:

```
Notebooks
Volumes
Tensorboards
Experiments
Pipelines
  Artifacts
  Executions
  Experiments
  ...
AutoML
  Experiments
  ...
```

but rather start thinking about user-facing objects with:

```
Notebooks
Volumes
Tensorboards
Experiments (KFP)
Experiments (AutoML)
...
```

For now, I am ok with not having a grouped section for Experiments and bringing the `Experiments (AutoML)` item to the root level. We can work on this as we improve the new Katib Web App and potentially introduce a dedicated page for Katib Trials as well, to be grouped with KFP Runs.

**Comment by DavidSpek** [comment]
@StefanoFioravanzo That's why I said: `I think the most important thing here is to have a clear view which things relate to each other and how. This way the dashboard is (hopefully) setup so everything is in the place the user expects them to be.` Once that has been thought through, I think a large redesign of the central-dashboard will be needed.

**Comment by andreyvelich** [comment]
> Katib Trials would correspond to KFP Runs, instead.

I don't think we can make this assumption.
In Katib, Trial - one step of the model evaluation, which is just a part of HP tuning process. I am not sure that is similar to KFP Runs.
The Katib Experiment workflow consists Suggestion + Trial. Which is not similar to KFP Runs.

My concern that structure: 
```
Experiments
  Pipelines
  AutoML
Runs
  Pipelines
  Trial
```
can confuse our user.
I think we should get a clear understanding what does each object (Experiment, Run, Trial, Suggestion, etc.) means in KFP, Katib and other apps.

WDYT @StefanoFioravanzo @gaocegege @johnugeorge ?

**Comment by thesuperzapper** [comment]
To all watching, this is a blocking issue for Kubeflow 1.3.

In the community meeting we all committed to resolving it before end-of-day  __2021-03-24 [California time]__ (tomorrow), what needs to be done for a PR to get merged @kimwnasptd? 

I am happy to help, if needed.

**Comment by andreyvelich** [comment]
@kimwnasptd @StefanoFioravanzo @yanniszark Any updates on this issue ? 
I believe, we can fix it until end of today.

**Comment by StefanoFioravanzo** [comment]
Hey @andreyvelich,

I agree on the fact that Trials don't necessarily have to correspond 1:1 to KFP Runs. We have been successfully doing that with Kale, which creates Katib Experiments that start a new (parametrized) KFP Run for each Trial. We basically tune whole pipelines, using their output metrics as optimization metrics.

Besides, I know about the `katib-launcher` in KFP that allows running Katib Trials from a KFP **step** (https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/katib-launcher).

It's clear that people have been thinking about the Trials <> KFP Runs association in different ways. I propose we stop this conversation for now and spend some good time thinking about it after the 1.3 release.

To move forward now, I propose we still follow this scheme:

```
Notebooks
Volumes
Tensorboards
Experiments (KFP)
Experiments (AutoML)
...
```

which doesn't imply anything about Trials and makes the distinction between KFP and AutoML crystal clear, while allowing us to lay down a basic semantic grouping that we (may) build on top of in the future.

**Comment by andreyvelich** [comment]
> We have been successfully doing that with Kale, which creates Katib Experiments that start a new (parametrized) KFP Run for each Trial. We basically tune whole pipelines, using their output metrics as optimization metrics.

Yes, it is possible. We also have an examples with Tekton + Katib integration: https://github.com/kubeflow/katib/tree/master/examples/v1beta1/tekton.
In that approach, I am still not sure that we can say that KFP Run and Trial has the same logic.


> To move forward now, I propose we still follow this scheme:
Notebooks
Volumes
Tensorboards
Experiments (KFP)
Experiments (AutoML)
...

Sound good to me. It would be great if we could also update the doc: https://www.kubeflow.org/docs/components/central-dash/overview/#overview-of-kubeflow-uis with the new structure for Kubeflow 1.3


What do you think @DavidSpek, @gaocegege @johnugeorge @yanniszark ?

**Comment by DavidSpek** [comment]
All sounds good to me. I think it would be useful to have a meeting after the release with a few people and create a clear description how all the different componenets of Katib and Pipelines relate to each other so we can figure out how the UIs should be sorted and interact with each other. @andreyvelich does this sound like a good idea to you?

**Comment by andreyvelich** [comment]
@DavidSpek Sure, it would be great.

**Comment by kimwnasptd** [comment]
Moving on with a PR to update the Dashboard. I'll be using the [katib.svg](https://github.com/kubeflow/katib/blob/master/docs/images/logo.svg) for the entry, but slightly edited to look like the other icons.

> Sound good to me. It would be great if we could also update the doc: https://www.kubeflow.org/docs/components/central-dash/overview/#overview-of-kubeflow-uis with the new structure for Kubeflow 1.3

@andreyvelich yeap, we will update the docs to ensure they are up to date with the Central Dashboard's latest changes of 1.3.

**Comment by andreyvelich** [comment]
Thank you @kimwnasptd!
We should also push your edited icon to the Katib repo to be consistent.
