### ISSUE TITLE
Sorry, /tensorboards/<namespace>/<tensorboard server name>/ is not a valid page

### ISSUE THREAD

**Issue by ljainker** [kubeflow/kubeflow#5752]
/kind bug

**What steps did you take and what happened:**
Facing the "Sorry, /tensorboards/<namespace>/<tensorboard server name>/ is not a valid page"  error when trying to connect to the Tensorboard server created through Tensorboard-web-app UI

**What did you expect to happen:**
Connect to the Tensorboard server for visualisation

**Environment:**
- Kubeflow version: 1.2
- Kubernetes platform: On Prem
- Kubernetes version: 1.17.8

**Comment by DavidSpek** [comment]
@ljainker The manifests for the Tensorboards Web App are not finalized yet and will be part of the upcoming Kubeflow release 1.3. How exactly did you try and deploy the Tensorboards Web App?

**Comment by ljainker** [comment]
Hi @DavidSpek 

I deployed Tensorboard-web-app with kustomize - https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/tensorboards/deploy
The above mentioned issue is not related to manifests I suppose, the issue is with the prefix value of the Virtual service that gets created when the user creates the Tensorboard servers through tensorboard web-app https://github.com/kubeflow/kubeflow/blob/master/components/tensorboard-controller/controllers/tensorboard_controller.go#L295

**Comment by DavidSpek** [comment]
@ljainker You should probably be using https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/tensorboards/manifests/overlays/istio

You will also need the tensorboards controller: https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller/config/overlays/kubeflow.

**Comment by DavidSpek** [comment]
@ljainker I've written a blog post and created an accompanying repository for deploying Kubeflow 1.3 RC with Argo CD in case you are interested.
https://vanderspek-david.medium.com/deploying-kubeflow-1-3-rc-with-argo-cd-ca98606b98eb
https://github.com/kubeflow-onprem/ArgoFlow
