### ISSUE TITLE
release: Cut a release branch

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5772]
/kind feature

**MUST BE MERGED FIRST:** https://github.com/kubeflow/kubeflow/pull/5746

**Why you need this feature:**
To release the WG-Notebook apps and give a revision to WG-Manifests:
https://github.com/kubeflow/manifests/issues/1775

**Describe the solution you'd like:**
Cut the `v1.3-branch`, same as in previous releases of this repo.

/assign @Bobgy

**Comment by Bobgy** [comment]
I cut v1.3-branch from master.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/kubeflow/tree/v1.3-branch

**Comment by yanniszark** [comment]
@Bobgy thanks a lot 😄 !
