### ISSUE TITLE
Invalid Certs while Securing KubeFlow with HTTPS.

### ISSUE THREAD

**Issue by chinmaychandak** [kubeflow/kubeflow#5775]
Hi everyone, I’m using KubeFlow on AWS EKS. I deployed KubeFlow v1.2 on AWS using this doc: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

I am trying to secure the deployment with HTTPS. For this, I edited the KubeFlow Gateway Object as mentioned in the docs here: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#secure-with-https, but am getting this error in the logs:

```
kubectl logs -f -n istio-system istio-ingressgateway-<pod_id>

[external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/istio/ingressgateway-certs/tls.crt 
```

Can someone please help? I’d really appreciate it. 

P.S. I apologize for posting this here; had pinged on the KubeFlow Slack community, but did not receive a response.

**Comment by DavidSpek** [comment]
@chinmaychandak Did you create the certificate with name `istio-ingressgateway-certs` in the `istio-system` namespace? If so, did you try deleting the ingressgateway pod after creating the certificate?

**Comment by chinmaychandak** [comment]
Thank you so much for responding, @DavidSpek! 

No, I did not create any certs - just followed the doc as is. Could you please help me on how I can create certs, my knowledge in this field is limited?

**Comment by DavidSpek** [comment]
@chinmaychandak The doc is not very well structured, but the `Secure with HTTPS` is part of the entire `Expose Kubeflow` section. In the `Expose with a LoadBalancer` section there are the instructions on how to create a certificate with cert-manager.

**Comment by chinmaychandak** [comment]
Awesome, will let you know how it goes! Greatly appreciate the help.

**Comment by DavidSpek** [comment]
@chinmaychandak Can this issue be closed?

**Comment by chinmaychandak** [comment]
Yes, thank you so much! I used the Cognito manifest instead and that seemed to make things work. :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
