### ISSUE TITLE
kubeflow version

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#578]
Now that we have started working towards a 0.1 release (#506), it'll be good to publish version information for kubeflow as a configmap on the cluster. This allows us to track which version of kubeflow is deployed on the cluster.

A simple way to do this would be:

`kubectl create configmap kubeflow-version --from-literal=version=0.1.0`

/cc @jlewi

**Comment by jlewi** [comment]
Related to #kubeflow/community#47

We should probably create the configmap as part of our ksonnet config and then we can update the configmap as part of a release.
