### ISSUE TITLE
Postsubmits failing on release branch

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5784]
/kind bug

**What steps did you take and what happened:**
We use postsubmits to release kubeflow/kubeflow on release branch v1.3: https://github.com/kubeflow/kubeflow/pull/5776

The release PR was merged, but the Argo Jobs failed with a weird error:
http://prow.kubeflow-testing.com/log?job=kubeflow-kubeflow-postsubmit&id=1375389773824266240
https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686?tab=workflow&nodeId=kubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686-3921483283&sidePanel=logs%3Akubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686-3921483283%3Amain

```
+ git checkout 0214c7ab0480352d4757a9a6296051470c9878da
fatal: reference is not a tree: 0214c7ab0480352d4757a9a6296051470c9878da
```

**Anything else you would like to add:**

The error could be because of the runner clone command:
git clone --depth=2 https://github.com/kubeflow/kubeflow.git /mnt/test-data-volume/kubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686/src/kubeflow/kubeflow

**Comment by yanniszark** [comment]
cc @PatrickXYS

**Comment by PatrickXYS** [comment]
> git clone --depth=2 https://github.com/kubeflow/kubeflow.git

This doesn't seem to clone the v1.3-branch

I tried locally, 

> ➜  git clone --depth=2 https://github.com/kubeflow/kubeflow.git
> ➜  cd kubeflow
> ➜  git branch -a
> * master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by PatrickXYS** [comment]
Built new image, and retry workflow succeeded in `checkout` step

https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686?tab=workflow&nodeId=kubeflow-kubeflow-postsubmit-nb-j-tf-0214c7a-6240-2686-3921483283

**Comment by PatrickXYS** [comment]
/close 

Close in favor of passing
