### ISSUE TITLE
Run container with privilege in the notebook

### ISSUE THREAD

**Issue by summerisc** [kubeflow/kubeflow#5787]
**What I want to do**
I had an image with a file storage system seaweed and try to run fuse mount within it, to mount a local path to seaweed system. I got 'fusermount: fuse device not found, try 'modprobe fuse' first' error and it seems the container needs to run under privileged. I already patched:
```
 Security Context:
        Capabilities:
          Add:                     SYS_ADMIN
        Privileged:                true
```
to the notebook resource. The notebook spec looks like:
![Screen Shot 2021-03-26 at 10 51 04 PM](https://user-images.githubusercontent.com/21230663/112708013-c1506c80-8e85-11eb-9cf5-e29a6e558ba0.png)
But the error still there, anything missing or needed(like a flag) to run the container with privilege in the notebook? Any insights are appreciated.

**Comment by DavidSpek** [comment]
You can create a notebook that uses the root user, or give your user sudo access. If you want to access hardware directly from a pod the kube-apiserver needs to run in privileged mode.

**Comment by summerisc** [comment]
Hi, @DavidSpek Thanks for mentioning that. While in this case, instead of using the root user, I am trying to run the container with --privileged flag. Is there a way to do it?

**Comment by summerisc** [comment]
This can be done by setting Container.set_security_context
