### ISSUE TITLE
Tag release v1.3.0-rc.0

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5788]
Tag commit https://github.com/kubeflow/kubeflow/commit/0214c7ab0480352d4757a9a6296051470c9878da of v1.3-branch as `v1.3.0-rc.0` to complete process described in https://github.com/kubeflow/kubeflow/blob/master/releasing/README.md

/assign @Bobgy

**Comment by Bobgy** [comment]
Hi @yanniszark! I tagged the commit by the following commandss:

```bash
git checkout 0214c7a
git tag -a "1.3.0-rc.0" -m "Release 1.3.0-rc.0"
git push upstream "1.3.0-rc.0"
```

**Comment by Bobgy** [comment]
https://github.com/kubeflow/kubeflow/releases/tag/v1.3.0-rc.0

**Comment by yanniszark** [comment]
Thanks a lot @Bobgy
