### ISSUE TITLE
unknown flag: --load_restrictor

### ISSUE THREAD

**Issue by erolco** [kubeflow/kubeflow#5789]
/kind bug

I wanna try to deploy kubeflow on private GKE cluster. But when i make apply i got unknown flag: --load_restrictor error. Can you help me about this issue.

ekaraboga@cloudshell:~/kf-deployments/kubeflow (erol-sandbox)$ make apply
# Delete build because we want to prune any resources which are no longer defined in the manifests
rm -rf .build/
mkdir -p .build/
PROJECT=erol-sandbox NAME=kubecluster ./hack/check_domain_length.sh
./hack/check_oauth_secret.sh
The kubeflow cluster name "kubecluster" is valid.
# ***********************************************************************************
# Hydrate cnrm
mkdir -p .build/gcp_config
kustomize build --load_restrictor none -o .build/gcp_config ./instance/gcp_config
Error: unknown flag: --load_restrictor
make: *** [Makefile:124: hydrate-gcp] Error 1

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by erolco** [comment]
I downgraded kustomize version to 3.9.4 and it has been resolved.

**Comment by DavidSpek** [comment]
Just so you know, you don't need this flag for most of the Kubeflow manifests (as far as I know only Katib requires it). Also, for newer versions of kustomize the command is `kustomize build --load-restrictor=LoadRestrictionsNone`, but again you shouldn't need it for most of the manifests (and the other manifests should be updated to, which I am busy implementing).
