### ISSUE TITLE
Installation error on minikube

### ISSUE THREAD

**Issue by sabya39** [kubeflow/kubeflow#5791]
What steps did you take and what happened:
I was trying to install Kubeflow on my standalone MAC laptop with the guide given by 
https://www.kubeflow.org/docs/started/workstation/minikube-linux/
using the command 
kfctl apply -V -f ${https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml}

Getting error as below 
ERRO[0745] Permanently failed applying application istio-stack:  (kubeflow.error): Code 500 with message: Apply.Run : error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "istio-citadel-service-account", Namespace: "istio-system"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app":"security"] "name":"istio-citadel-service-account" "namespace":"istio-system"]]}
from server for: "/tmp/kout733900659": Get "https://127.0.0.1:59837/api/v1/namespaces/istio-system/serviceaccounts/istio-citadel-service-account": stream error: stream ID 179; INTERNAL_ERROR  filename="kustomize/kustomize.go:288"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run : error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "istio-citadel-service-account", Namespace: "istio-system"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app":"security"] "name":"istio-citadel-service-account" "namespace":"istio-system"]]}
from server for: "/tmp/kout733900659": Get "https://127.0.0.1:59837/api/v1/namespaces/istio-system/serviceaccounts/istio-citadel-service-account": stream error: stream ID 179; INTERNAL_ERROR
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                         		export CONFIG=./kfctl_gcp_iap.yaml
                         	or a URL:
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml
                         	kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run : error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "istio-citadel-service-account", Namespace: "istio-system"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["app":"security"] "name":"istio-citadel-service-account" "namespace":"istio-system"]]}
from server for: "/tmp/kout733900659": Get "https://127.0.0.1:59837/api/v1/namespaces/istio-system/serviceaccounts/istio-citadel-service-account": stream error: stream ID 179; INTERNAL_ERROR% 

Please help

**Comment by jbottum** [comment]
@sabya39 sorry to hear of this issue.   you might get some help from the community, but I think most of the folks are working on the Kubeflow 1.3 release.      You might look at other options here, https://www.kubeflow.org/docs/started/getting-started/.   Note - since I work for Arrikto and we provided MiniKF, I know that that is easy to get running (especially on AWS and GCP).   If you are going to run Kubeflow on your MAC, you should have 12GB (or better 16GB RAM).

**Comment by hsinhoyeh** [comment]
@sabya39 hi, you can follow our example on deploying kubeflow (v1.2 and v1.3) on top of minikube [here](https://github.com/footprintai/kubeflow-workshop). Cheers!
