### ISSUE TITLE
Unable to install via instructions on page

### ISSUE THREAD

**Issue by matty1979** [kubeflow/kubeflow#5801]
/kind bug

**What steps did you take and what happened:**
Followed instructions downloading the cognito version and editing. 

**What did you expect to happen:**
Install correctly 

**Anything else you would like to add:**
```
INFO[0005] Deploying application namespaces              filename="kustomize/kustomize.go:172"
ERRO[0005] error evaluating kustomization manifest for namespaces Error absolute path error in 'kustomize/namespaces' : evalsymlink failure on 'kustomize/namespaces' : lstat /Users/matthewking/Downloads/kubeflow/kubeflow-us-west-2/kustomize/namespaces: no such file or directory  filename="kustomize/kustomize.go:175"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces Error absolute path error in 'kustomize/namespaces' : evalsymlink failure on 'kustomize/namespaces' : lstat /Users/matthewking/Downloads/kubeflow/kubeflow-us-west-2/kustomize/namespaces: no such file or directory
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): `kfctl v1.0.2-0-ga476281`
- Kubernetes platform: (e.g. `minikube`): `Amazon EKS`
- Kubernetes version: (use `kubectl version`): ```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): `20.3.0 Darwin Kernel Version 20.3.0:`

**Comment by matty1979** [comment]
```
INFO[0007] Successfully applied application namespaces   filename="kustomize/kustomize.go:209"
INFO[0007] Deploying application istio-stack             filename="kustomize/kustomize.go:172"
2021/04/01 13:26:54 absolute path error in '/Users/matthewking/Downloads/istio/istio-crds/base' : evalsymlink failure on '/Users/matthewking/Downloads/istio/istio-crds/base' : lstat /Users/matthewking/Downloads/istio: no such file or directory
ERRO[0007] error evaluating kustomization manifest for istio-stack Error accumulating resources: accumulating resources from '../../../../istio/istio-crds/base': evalsymlink failure on '/Users/matthewking/Downloads/istio/istio-crds/base' : lstat /Users/matthewking/Downloads/istio: no such file or directory  filename="kustomize/kustomize.go:175"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for istio-stack Error accumulating resources: accumulating resources from '../../../../istio/istio-crds/base': evalsymlink failure on '/Users/matthewking/Downloads/istio/istio-crds/base' : lstat /Users/matthewking/Downloads/istio: no such file or directory
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for istio-stack Error accumulating resources: accumulating resources from '../../../../istio/istio-crds/base': evalsymlink failure on '/Users/matthewking/Downloads/istio/istio-crds/base' : lstat /Users/matthewking/Downloads/istio: no such file or directory
```

Attempted to run again and same error.

**Comment by DavidSpek** [comment]
@matty1979 Kubeflow 1.3 RC has been released now so I think you might have more success with this new version. There are instructions how to install Kubeflow with Kustomize in the [manifests repo](https://github.com/kubeflow/manifests). 

I've also written a blog post and created an accompanying repository to install Kubeflow 1.3 with Argo CD which you can take a look at as well. I've added some helpful default settings so you don't run into issues and I believe it makes the deployment and customization of Kubeflow a bit easier than using the instructions on the manifest repository directly. 

https://vanderspek-david.medium.com/deploying-kubeflow-1-3-rc-with-argo-cd-ca98606b98eb
https://github.com/kubeflow-onprem/ArgoFlow

**Comment by matty1979** [comment]
Thanks for this, this seems a ton easier to follow. Creating a new eks cluster and will walk through this with using Argo.

**Comment by matty1979** [comment]
All apps deployed

**Comment by DavidSpek** [comment]
@matty1979 Awesome, that’s great to hear. If you have any questions please don’t hesitate to ping me on slack or create an issue in the ArgoFlow repository. 

Also, given the manifests for the Kubeflow applications are still changing slightly (and I just pushed a commit to update to Argo CD 2.0 stable from the RC) it’s probably best for you to rebase your branch on upstream/master and force push to keep your fork up to date with the ArgoFlow repo.
