### ISSUE TITLE
change image registry to docker hub 

### ISSUE THREAD

**Issue by aresa7796** [kubeflow/kubeflow#5806]
/kind feature

**Why you need this feature:**
I pull images is failed in aws eks china, I think the current iamges are gcr.io ,can't access gcr.io in China.

**Describe the solution you'd like:**
I hope change image registry to docker hub .

**Comment by aresa7796** [comment]
@jlewi

**Comment by kong62** [comment]
+1

**Comment by DavidSpek** [comment]
The registry used for the 1.3 release is the ECR public gallery.
