### ISSUE TITLE
Cannot create notebook when profiles have resourcequotas

### ISSUE THREAD

**Issue by HassanOuda** [kubeflow/kubeflow#5814]
/kind bug

**What steps did you take and what happened:**

It looks like in 1.3, with the new jupyter app, the cpu and memory are being set as requests not limits, as shown here:
[https://github.com/kubeflow/kubeflow/blob/ebc0c4f073397537412694f9f255dbb3fbdf2043/components/crud-web-apps/jupyter/backend/apps/common/form.py#L163](https://github.com/kubeflow/kubeflow/blob/ebc0c4f073397537412694f9f255dbb3fbdf2043/components/crud-web-apps/jupyter/backend/apps/common/form.py#L163)

This causes the notebook to fail when it expects a limit like it did in older kubeflow versions.

**What did you expect to happen:**
Should create the notebooks with specified cpu, memory limits in the form. 

**Anything else you would like to add:**

I think this is a release blocking issue since lots of users use resourcequotas on profiles

- Kubeflow version: 1.3
- Kubernetes version: (use `kubectl version`): 1.15.11

**Comment by kimwnasptd** [comment]
Hi @HassanOuda, thanks for creating the issue!

This is indeed a regression from the previous Jupyter web app. Previously it would set both the `limits` and `requests` with the same values [[code](https://github.com/kubeflow/kubeflow/blob/master/components/deprecated/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py#L392-L393)]. But the newest web app, which is the one shipped in 1.3, only sets the `requests` field [[code](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/backend/apps/common/form.py#L163)].

A workaround for now would be to use a `LimitRange` object to set default values for the cpu/memory `limits` of the created Pods. But of course the issue with this approach is that we can't configure these values per Notebook.
https://kubernetes.io/docs/concepts/policy/limit-range/
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

At the same time we will work to expose the option for users to set both the `limits` and `requests` for CPU and Memory from the web app. We could split the `CPU/Memory` section into two distinct `CPU` and `Memory` sections and expose these two properties for each resource.

I don't know if this could make it for 1.3, but it could definitely be part of 1.3.1 which would include small fixes like this based on the input and friction we hear from users.

**Comment by DavidSpek** [comment]
@kimwnasptd I created a PR that fixes this and allow the administrator to set a multiplication factor for the cpu and memory limits. This way the users don't need to be bothered with this and the administrator can set a buffer value for the limit based on the request (for example: limits is 20% more than what was requested).

**Comment by HassanOuda** [comment]
@kimwnasptd The thing with `LimitRange `is that you have to set a limit for the entire namespace for all pods which is a major disadvantage for other types of pods running there. Also, each user's usage of notebook server will differ so giving everyone equal limit from `LimitRange ` doesn't make sense.

I think @DavidSpek's idea is good for the interim for 1.3 until you upgrade the front end to specify requests and limits for later versions. Right now, with current implementation it's unusable unless I force everyone on the same amount of limits (which wont make sense since some projects require more than others with limited amount of resources available in the namespace) 

Thanks for looking into this.

**Comment by HassanOuda** [comment]
Or just setting it back to how the old jupyter web app was and keeping it as limit instead of requests. It's been like that since the beginning and I think users know that its the maximum resources a pod can use. That how we word it to our users. 

It could be something we can mention in the documentation to avoid confusion.

**Comment by DavidSpek** [comment]
@HassanOuda How about a hybrid approach? We keep the multiplication factor that I implemented in the PR so admins can set this for the average users, but also add a custom limits input in an advanced section of the spawner UI.

**Comment by HassanOuda** [comment]
Yea that could work. But lets try to keep it simple just for the official release and add something more advanced in another version. Just so that this fix is not delayed.

**Comment by DavidSpek** [comment]
I'm pretty sure I can get this implemented tomorrow if @kimwnasptd agrees with this approach.

**Comment by kimwnasptd** [comment]
@DavidSpek I was thinking of such a hybrid solution as well!

So here's what I propose, lets discuss the technical details of this in the PR and spent a maximum of two days. If we see that this effort gets more involved we can fallback to plan B and just set the `limits` as well to just fix the regression.

@DavidSpek how does this sound to you?

**Comment by DavidSpek** [comment]
@kimwnasptd Sounds good to me. Isn't plan B essentially what I've already done in my PR but with the multiplication factor set to 1?

**Comment by kimwnasptd** [comment]
Yes, but if we'd decide to go with the least amount of new changes then I would prefer to not touch the ConfigMap. But lets see how our sprint will go first.

**Comment by DavidSpek** [comment]
After I eat some breakfast I'll get on this right away. I don't imagine it should take much time to implement.
