### ISSUE TITLE
[FR] Enhance Pod Default 

### ISSUE THREAD

**Issue by munagekar** [kubeflow/kubeflow#5825]
# WHAT
- I would like to request support for [SecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container) in PodDefault, to add Linux Capabilities for Jupyter Notebook Server Pods.
- I would also like to request support for adding [node-selectors](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) & [toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to PodDefault.

# WHY
- Jupyter Notebooks Server is a good replacement for VMs in the Machine Learning Ecosystem. However it cannot run all software supported by VM, such as software which requires additional linux capabilities("NET_ADMIN", "SYS_TIME",etc). The PodDefault mechanism could be expanded to support SecurityContext to make this possible.
- I would like to schedule JupyterNotebook pods on dedicated nodes, this will be possible through node-selectors and tolerations.

# Changes Required 

Admission webhook would need to merge security-context as well

- [Application](https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/main.go)
- [CRD](https://github.com/kubeflow/manifests/blob/master/apps/admission-webhook/upstream/base/crd.yaml)

**Comment by munagekar** [comment]
@yanniszark @DavidSpek Do you think this is a useful feature ?

**Comment by DavidSpek** [comment]
This seems interesting. There is already support for affinity and tolerations in the Jupyter Web App, or would this be different? You also touch on an interesting subject regarding the usefulness of containers as an IDE, which isn’t actually the best idea. There are some ideas floating around to add the ability to spawn VMs for notebook servers.

**Comment by munagekar** [comment]
@DavidSpek Thank you for your comments.

> There is already support for affinity and tolerations in the Jupyter Web App.

This seems to be a part of Kubeflow 1.3. I am using kubeflow 1.2, the Jupyter Web App doesn't support this feature yet.

> You also touch on an interesting subject regarding the usefulness of containers as an IDE, which isn’t actually the best idea. There are some ideas floating around to add the ability to spawn VMs for notebook servers.

The Jupyter Notebooks in Kubeflow can almost create a VM equivalent experience. It can already set storage, CPU & GPU requests. One of the issues is software persistence, this can be resolved by chrooting the system into a PVC.  

The ability to add additional linux capabilities to the Jupyter Server through Pod Defaults would be useful for running software which requires these. This usecase is already supported by Jupyter Notebooks just missing from the UI. 

The container spec in the NotebookCRD can be edited to add in additional linux capabilites. This Feature Request is for enabling it through UI by extending the Pod Default mechanism.

**Comment by DavidSpek** [comment]
@munagekar Sorry for the late response. The reason why I said using containers for and IDE is not the best idea, is it is allowing users to run arbitrary code on the Kubernetes cluster which makes security quite difficult to do properly. An actual VM would provide much better isolation, and you could run tools such as Docker in the VM, which some development workflows require. But this is beside the poind :)

I'm working on a proposal to completely rewrite the Notebook Spawner UI. I'll make a note that there needs to be an (easy) method to add the SecurityContext to it.
