### ISSUE TITLE
Error: Failed to getArtifactTypes: Http response at 400 or 500 level. Code: 5 Click Details for more information. Troubleshooting guide

### ISSUE THREAD

**Issue by darack1234** [kubeflow/kubeflow#5827]
Hi Team,

The artifacts are not getting generated. We have installed kubeflow using the micrk8s and juju.

**Comment by DavidSpek** [comment]
@darack1234 Please open an issue over at https://github.com/canonical/bundle-kubeflow. This installation method is not related to the code in this repository. 

/close
