### ISSUE TITLE
default resource overhead for each individual profile

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/kubeflow#5832]
/kind question

**Question:**
Not sure whether this question has been discussed before, but I am curious about the resource overhead for each individual profile.
In the current configuration ( in v1.2, v1.3), when creating one single profile, there are two running pods are created by default:
```
ml-pipeline-ui-artifact-c8fbcb8f9-k88bz
ml-pipeline-visualizationserver-6b78c9646-s7q4c
```
each one takes additional istio sidecar container (cost 100m cpu/ 128Mi memory).
so in total cpu requested 100m * 2 + 128m * 2 = 0.5 CPU unit, memory requested 128 *2 + 128 * 2 = 512Mi.
(even the profile has been created but no further actions were conducted.)

so let say today we have to create 100 profiles (one for each individual participant) but only 20% of them are heavy users (80-20 rule), and our system wasted 100 * 80% * 0.5 CPU unit (and 512Mi + 100 * 80% memory).

This seems to be more like a resource leaking, not the design concept. any thoughts? or documents? thanks

**Comment by yanniszark** [comment]
cc @Bobgy could you transder to kubeflow/pipelines?

**Comment by hsinhoyeh** [comment]
Closed as I have transferred to pipeline repo.
