### ISSUE TITLE
CustomResourceDefinition.apiextensions.k8s.io "orders.acme.cert-manager.io" is invalid   Invalid value: "v1": must appear in spec.versions]

### ISSUE THREAD

**Issue by titansmc** [kubeflow/kubeflow#5837]
/kind bug

**What steps did you take and what happened:**
Deploying kubeflow to an on prem cluster with existing cert-manager deployment seems to conflict with existing CRD.
```
for: "/tmp/kout470047910": CustomResourceDefinition.apiextensions.k8s.io "orders.acme.cert-manager.io" is invalid: status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions]  filename="kustomize/kustomize.go:284"
WARN[0013] Will retry in 4 seconds.                      filename="kustomize/kustomize.go:285"
```

**What did you expect to happen:**
To resume after installing the required CRD

**Environment:**

- Kubeflow version: 1.2
- kfctl version: v1.2.0-0-gbc038f9
- Kubernetes platform: upstream 
- Kubernetes version: 1.19.7
- OS (e.g. from `/etc/os-release`): 7.9.2009

**Comment by yanniszark** [comment]
@titansmc if you are deploying to a cluster with existing cert-manager, then you need to either:
- Follow the step-by-step guide and don't skip installing cert-manager.
- Remove your cert-manager beforehand.

**Comment by yanniszark** [comment]
In addition, since this is a kubeflow/manifests issue, could you please open it on https://github.com/kubeflow/manifests/?
Or alternatively close if my comment fixed your problem.

**Comment by titansmc** [comment]
Thanks Yannis, I cannot find the step by step guide, would you mind pointing to it? I was following https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/#before-you-start

**Comment by yanniszark** [comment]
@titansmc sorry, I mistakenly thought you were deploying Kubeflow 1.3 RC: https://github.com/kubeflow/manifests/tree/v1.3.0-rc.0#readme
Could you try that instead?

**Comment by titansmc** [comment]
let me try...
getting started you found that the instructions don't work for current version of kustomize:
```
[root@ops-k1m01t manifests]# kustomize build --load-restrictor=none common/cert-manager/cert-manager-kube-system-resources/base 
Error: illegal flag value --load-restrictor none; legal values: [LoadRestrictionsRootOnly LoadRestrictionsNone]
```

**Comment by titansmc** [comment]
it just failed at the second command of installing cert-manager (as you mentioned I shouldn't skip the install of cert-manager)
```
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "orders.acme.cert-manager.io", Namespace: ""
for: "STDIN": CustomResourceDefinition.apiextensions.k8s.io "orders.acme.cert-manager.io" is invalid: status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions
```

**Comment by yanniszark** [comment]
> as you mentioned I shouldn't skip the install of cert-manager

Oh my god, I saw the comment and edited it. It is the opposite of what I actually wanted to say (skip installing cert-manager).

> getting started you found that the instructions don't work for current version of kustomize:

Could you use the version the guide mentions. This is the tracking issue for using latest kustomize, in case you are interested: https://github.com/kubeflow/manifests/issues/1797
