### ISSUE TITLE
[bug] with OIDC, when session expired,  login again, then got apis/v1beta1/healthz response with OIDC auth page

### ISSUE THREAD

**Issue by ZhengJuCn** [kubeflow/kubeflow#5841]
/kind bug

**What steps did you take and what happened:**

1. install pipelines with kubeflow-1.3-rc.0
2. access kubeflow dashboard login with OIDC
3. do something normal, start runs, upload pipeline....
4. when session expired
5. login with OIDC again
6. got apis/v1beta1/healthz response error (actually response is OIDC auth page)

**What did you expect to happen:**

access dashboard normal

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**1. get error in center dashboard , (pipelines ui)**
   Unexpected token < in JSON at position 0

**2. get error in browser developer tools**
Failed to retrieve build info Error: Error parsing response for path: /healthz
actually every api return this

```
Response was: <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>dex</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../static/main.css" rel="stylesheet">
    <link href="../theme/styles.css" rel="stylesheet">
    <link rel="icon" href="../theme/favicon.png">
  </head>

  <body class="theme-body">
    <div class="theme-navbar">
      <div class="theme-navbar__logo-wrap">
        <img class="theme-navbar__logo" src="../theme/logo.png">
      </div>
    </div>

    <div class="dex-container">



<div class="theme-panel">
  <h2 class="theme-heading">Log in to Your Account</h2>
  <form method="post" action="/dex/auth/local?req=bqsvcptftypindk424odcj6f4">
    <div class="theme-form-row">
      <div class="theme-form-label">
        <label for="userid">Email Address</label>
      </div>
	  <input tabindex="1" required id="login" name="login" type="text" class="theme-form-input" placeholder="email address"  autofocus />
    </div>
    <div class="theme-form-row">
      <div class="theme-form-label">
        <label for="password">Password</label>
      </div>
	  <input tabindex="2" required id="password" name="password" type="password" class="theme-form-input" placeholder="password" />
    </div>

    

    <button tabindex="3" id="submit-login" type="submit" class="dex-btn theme-btn--primary">Login</button>

  </form>
  
</div>

    </div>
  </body>
</html>



Error was: {}
    at Function.<anonymous> (Apis.ts:385)
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
  1.3-rc.0
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
  k8s cluster
- Kubernetes version: (use `kubectl version`):
  k8s 1.20
- OS (e.g. from `/etc/os-release`):
 ubuntu 16.04

**Comment by ZhengJuCn** [comment]
this maybe cookie not refresh actually, i clear my brower cookies, then login again, everything ok

is this bug or something wrong? if not i will close this issue

**Comment by DavidSpek** [comment]
Ping @Bobgy This seems related to pipelines, but the `Unexpected token < in JSON at position 0` error is something I also see when trying to save a Jupyter Notebook and the session expires. Logging back in resolves that issue though.

**Comment by Bobgy** [comment]
@yanniszark can you take a look?

This doesn't seem related to KFP, looks like an OIDC auth service problem or a cache problem.

**Comment by jbottum** [comment]
@ZhengJuCn did you get this resolved ?
