### ISSUE TITLE
Permission Error when installing lab extension

### ISSUE THREAD

**Issue by mauermbq** [kubeflow/kubeflow#5843]
It's not possible to install any lab extension with default notebooks.
Image:

527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-2.1.0-notebook-cpu:1.2.0

Installing an extension lead to PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/extensions'
when installing any lab extension

configuring lab extension according your needs is a nice feature. How can this be enabled?

**Comment by DavidSpek** [comment]
@mauermbq I would recommend trying one of the new notebook images as extensions should work without a problem there. I believe `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:v1.3.0-rc.1` is equivalent to the image you are using now.

**Comment by mauermbq** [comment]
Tank you David, in general this image works better. However, the build process still leads to some error:

**WARNING in ./node_modules/vega-lite/build/src/index.js 5:0-30
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ consume shared module (default) vega-lite@^4.0.2 (strict) (fallback: ./node_modules/vega-lite/build/src/index.js)
 @ ./node_modules/vega-embed/build/vega-embed.module.js 6:0-44 189:15-29
 @ consume shared module (default) vega-embed@^6.2.1 (strict) (fallback: ./node_modules/vega-embed/build/vega-embed.module.js)
 @ ./node_modules/@jupyterlab/vega5-extension/lib/index.js 166:28-48
 @ consume shared module (default) @jupyterlab/vega5-extension@~3.0.5 (strict) (fallback: ./node_modules/@jupyterlab/vega5-extension/lib/index.js)
 @ ./build/index.out.js 171:16-54
 @ ./build/bootstrap.js

ERROR in jlab_core.396bceeba623ab69b654.js?v=396bceeba623ab69b654 from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

webpack 5.27.0 compiled with 1 error and 1 warning in 367082 ms**

**Comment by DavidSpek** [comment]
@mauermbq Could it be that the extension you are installing has not been updated for JupyterLab 3.0? You can try downgrading JupyterLab and then installing the extension to see if that helps.

**Comment by mauermbq** [comment]
https://github.com/jupyterlab/jupyterlab-git
Requirement JupyterLab >= 3.0 (older version available for 2.x)

**Comment by DavidSpek** [comment]
Yeah I’ve had an issue with that extension as well. Was planning on looking at it again tomorrow.

**Comment by DavidSpek** [comment]
@mauermbq I seems like JupyterLab needs to be restarted for the extension to load properly. In the terminal, run `top` and note the `PID` number for the jupyterlab instance, exit top by pressing `ctrl+c`. Next execute `kill <JupyterLab_PID>` to kill the JupyterLab process causing it to restart. The extension should load correctly now. Given this is such an important extension I'll create a PR to add it to the images by default.

**Comment by mauermbq** [comment]
@DavidSpek , seems that this is also an issue for other extensions. I tried dash as well:
WARNING in ./node_modules/vega-lite/build/src/index.js 5:0-30
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ consume shared module (default) vega-lite@^4.0.2 (strict) (fallback: ./node_modules/vega-lite/build/src/index.js)
 @ ./node_modules/vega-embed/build/vega-embed.module.js 6:0-44 189:15-29
 @ consume shared module (default) vega-embed@^6.2.1 (strict) (fallback: ./node_modules/vega-embed/build/vega-embed.module.js)
 @ ./node_modules/@jupyterlab/vega5-extension/lib/index.js 166:28-48
 @ consume shared module (default) @jupyterlab/vega5-extension@~3.0.5 (strict) (fallback: ./node_modules/@jupyterlab/vega5-extension/lib/index.js)
 @ ./build/index.out.js 171:16-54
 @ ./build/bootstrap.js

ERROR in jlab_core.396bceeba623ab69b654.js?v=396bceeba623ab69b654 from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by DavidSpek** [comment]
Where are you getting these logs from exactly? I wasn't seeing them, although the fit extension was not working. I'll need to look into why jupyter lab needs to be restarted and if there is workaround for this as we cannot include all the extensions in the images. You can view the [README](https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/README.md) for instructions how to extend the images with the packages and extensions you need.

**Comment by mauermbq** [comment]
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-ahyuhd1_.log
