### ISSUE TITLE
Managing contributors manually

### ISSUE THREAD

**Issue by Dimiftb** [kubeflow/kubeflow#5847]
/kind bug

**What steps did you take and what happened:**
Hi there I've been trying to manually add contributors to a namespace by following instructions here: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually 

My servicerolebinding.yaml looks exactly like the one on the guide: 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/26279721/115231596-a7fdb180-a10d-11eb-924a-0b559ffdb68d.png">

When I try to apply the servicerolebinding.yaml I get: 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/26279721/115231246-41789380-a10d-11eb-8592-b97fdcbe143b.png">

What am I missing here? 

I've installed Kubeflow 1.3 by following guide on here: https://github.com/kubeflow/manifests

**Comment by DavidSpek** [comment]
@Dimiftb That information is outdated as the new Istio version does not have RBAC. What are you trying to do exactly, add a new user?

**Comment by Dimiftb** [comment]
Hi @DavidSpek, 

I'm trying to add one profile as a contributor to another namespace to allow for collaboration. For example, allowing an user view/modify access to another user's namespace where they can also create and view notebooks.

I'm following this link: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually

It says to create a rolebinding.yaml and a servicerolebinding.yaml, but maybe that information is really outdated.

**Comment by DavidSpek** [comment]
@Dimiftb Sorry for the late response, I've been very busy lately and this is one of the things I need to look at. Have you been able to figure this out?

**Comment by Dimiftb** [comment]
Hi @DavidSpek,

Cheers for your reply. I managed to sort this out, however I forgot to close the issue. Closing it now, thanks.
