### ISSUE TITLE
Namespace not showing up in kubeflow UI

### ISSUE THREAD

**Issue by swamat** [kubeflow/kubeflow#5854]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

*  KFP version: 1.20

### Steps to reproduce

I installed kubeflow in AWS. The dashboard is up. when i create a new namespace using profile.yaml, am able to see the created namespace using kubectl get profiles command. But not able to see the new namespace in UI

### Expected result

The new namespace should be displayed in dropdown with existing namespace

### Materials and Reference
profile.yaml:
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: speech   # replace with the name of profile you want, this will be user's namespace nam
spec:
  owner:
     kind: User
     name: speech  # replace with the email of the user
  resourceQuotaSpec:    # resource quota can be set optionally
     hard:
        cpu: "4"
        memory: 2Gi
        requests.nvidia.com/gpu: "1"
        persistentvolumeclaims: "1"
        requests.storage: "5Gi"
~                                    

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by swamat** [comment]
Can someone please help on this

**Comment by jbottum** [comment]
@swamt did you get this resolved ?  did you try with Kubeflow 1.3 and the new installation patterns ?   https://www.kubeflow.org/docs/started/installing-kubeflow/

**Comment by swamat** [comment]
@jbottum Thanks for the reply. The issue is not resolved. i tried with kubeflow 1.2 on aws. 
In kubeflow documentation i found the below steps(https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/) 
# 2. Use the following kfctl configuration file for the AWS setup without authentication:
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml"

# Alternatively, use the following kfctl configuration if you want to enable
# authentication, authorization and multi-user:
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml"

I used this yaml file: https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml and am not able to add multiple namespace in central dashboard. I created profile.yaml and applied but couldnt see the namespace in dashboard. However I could see the profiles are created in backend using kubectl get profiles command. Can you please tell whether am missing something

Will the namespace works only with cognito setup (https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml). can you please help

**Comment by jbottum** [comment]
@swamat thanks for your note.   You have a couple of options for support.  1) attend at Community or Working Group Call, you might try the Manifest call tomorrow.   https://www.google.com/url?q=https://arrik.to/kf-wg-manifests-notes&sa=D&source=calendar&ust=1620479560799000&usg=AOvVaw3IZaN2pxf2RBYMl6hClrkR.    Or you could reach out to AWS directly.   Finally, there are 3rd parties would provide support i.e. Arrikto.      I would note that if you are installing new, I would recommend using Kubeflow 1.3.

**Comment by DavidSpek** [comment]
@swamat Are you still experiencing this issue? If you are wanting to install the latest version of Kubeflow I can help you get setup. The easiest way to reach out to me is through Slack.

**Comment by swamat** [comment]
@DavidSpek Yes am still facing this issue. But am unable to reach you through slack

**Comment by DavidSpek** [comment]
@swamat Do you need an invite link for the Slack?

**Comment by swamat** [comment]
@DavidSpek Yes please

**Comment by DavidSpek** [comment]
@swamat Here you go: https://join.slack.com/t/kubeflow/shared_invite/zt-n73pfj05-l206djXlXk5qdQKs4o1Zkg

**Comment by harsha1163** [comment]
@swamat, Did your issue got resolved? 

I also faced the same issue and the fix I have made is as below:

lets say you have A,B,C users and X,Y groups. when adding profiles in kubeflow for A,B,C users. we need to make sure that you add the X,Y groups and also provide the level of access they should have. 

Ex:

```
- name: A
        members:
          - user: A
            access:
              role: edit
              notebooksAccess: true
          - user: B
            access:
              role: edit
          - group: X
            access:
              role: view
```

By this way, I am able to see the namespace in kubeflow UI. hope this helps!!
