### ISSUE TITLE
Kubeflow Installation on CentOs7 - Error while applying kfctl_k8s_istio.v1.0.0.yaml

### ISSUE THREAD

**Issue by shekhar-ms123** [kubeflow/kubeflow#5856]
/kind bug
failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for istio-crds Error absolute path error in 'kustomize/istio-crds' : evalsymlink failure on 'kustomize/istio-crds' : lstat /kubeflow/kustomize/istio-crds: no such file or directory
[root@citigroup kubeflow]# kfctl -version
Error: unknown shorthand flag: 'v' in -version

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Error while applying kfctl_k8s_istio.v1.0.0.yaml during the installation of Kubeflow on a VM with CentOS 7. The Kubernetes configuration is complete and the master node is setup on the system. The error is encountered when I'm trying to apply the yaml file (export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml") using the command kfctl apply -V -f ${CONFIG_URI}.

**What did you expect to happen:**
Ideally the yaml should be applied and the Kubeflow namespaces and other binaries should have been configured.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): NA
- kfctl version: (use `kfctl version`): kfctl v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`) vanilla K8s installed on a VM
- Kubernetes version: (use `kubectl version`): v1.20.4
- OS (e.g. from `/etc/os-release`): CentOs7 (VM)

**Comment by DavidSpek** [comment]
I believe it might be better to install the latest version of Kubeflow (1.3). For an easier to customize and more maintainable solution I can recommend installing it with Argo CD. I created the ArgoFlow distribution for this which you can find [here](https://github.com/argoflow/argoflow). If you run into any problems I'll be happy to help you. You can reach out to me on Slack or create an issue on the repo.
