### ISSUE TITLE
Kubeflow internalisation

### ISSUE THREAD

**Issue by wg102** [kubeflow/kubeflow#5858]
/kind feature

**Why you need this feature:**
Our organization has the priority of providing both a French and English Kubeflow experience. 
By implementing the infrastructure to support this, other organizations might be able to benefit from other languages easily. 

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
Use a framework to detect the user's browser language, and base on it, sets the appropriate language.
If no translation is available for the said browser language, defaults to English.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The current idea would be to get it started.
Statcan's fork currently has i18n for the jupyter component (using ngx-translate) and the centraldashboard (using polymer localize behavior).

We are currently working toward a PR for jupyter, but having some issues with how the code is now structured with crud-web-apps and the 'common' folder. 
Any advice or suggestion would be welcomed.

**Comment by jbottum** [comment]
/priority p2
/area jupyter

@wg102 This is a nice initiative.   Validating the conversion from english to another language may need to be part of the feature delivery.

**Comment by tiansiyuan** [comment]
How are things going on?
