### ISSUE TITLE
Dex authentication and 404 error

### ISSUE THREAD

**Issue by constanton** [kubeflow/kubeflow#5860]
/kind bug

**What steps did you take and what happened:**
I used git clone https://github.com/kubeflow/manifests.git to get the latest Kubeflow (I asssume 1.3)
Kubeflow is deployed with kustomize successfuly on a local cluster with rancher's local path provisioner.

I am using istio-ingressgateway as Load Balancer with an external IP and can successfully connect (either with my browser over VPN or curl locally) but I get HTTP/2 404.

Two pods have issues (the rest are running and ready) and PVCs are bound too. The two pods are:
- dex  (namespace is auth):  Ready 0/1, Status CrashLoopBackOff
- authservice-0 (namespace is istio-system):  Ready 0/1, Status Running

**What did you expect to happen:**
Successful launch of the dashboard

**Anything else you would like to add:**
Logs from dex pod:
`time="2021-04-23T08:51:32Z" level=info msg="config using log level: debug"
time="2021-04-23T08:51:32Z" level=info msg="config issuer: http://dex.auth.svc.cluster.local:5556/dex"
failed to initialize storage: failed to inspect service account token: jwt claim "kubernetes.io/serviceaccount/namespace" not found`

Logs from authservice-0:
`time="2021-04-23T08:58:06Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get http://dex.auth.svc.cluster.local:5556/dex/.well-known/openid-configuration: dial tcp 10.106.106.7:5556: connect: connection refused" `

Not sure if the following will help, but just in case because I don't see anything HTTPS related in there...
Auth service spec:
> spec:
>   clusterIP: 10.110.152.254
>   clusterIPs:
>   -10.110.152.254
>   ipFamilies:
>   -IPv4
>   ipFamilyPolicy: SingleStack
>   ports:
>   -name: http-authservice
>     port: 8080
>     protocol: TCP
>     targetPort: http-api
>   publishNotReadyAddresses: true
>   selector:
>     app: authservice
>   sessionAffinity: None
>   type: ClusterIP

centraldashboard spec:
> spec:
>   clusterIP: 10.99.164.178
>   clusterIPs:
>   -10.99.164.178
>   ipFamilies:
>   -IPv4
>   ipFamilyPolicy: SingleStack
>   ports:
>   -port: 80
>     protocol: TCP
>     targetPort: 8082
>   selector:
>     app: centraldashboard
>     app.kubernetes.io/component: centraldashboard
>     app.kubernetes.io/name: centraldashboard
>     kustomize.component: centraldashboard
>   sessionAffinity: None
>   type: ClusterIP

**Environment:**

- Kubeflow version: 1.30:
- kfctl version: (used kustomize)
- Kubernetes platform: kubernetes
- Kubernetes version: v1.21.0
- OS: Ubuntu 18.04.3 LTS

**Comment by jbottum** [comment]
/kind question 
/priority p2
/area installation
@constanton did you get this resolved?  I assume this is on-prem cluster.   You might try asking questions at the On-Perm SIG.  also, I believe we tested with K8s 1.17

**Comment by hwdef** [comment]
@jbottum 
I have the same problem, on k8s 1.21.0. Do you have any suggestions to solve the problem

**Comment by hwdef** [comment]
https://github.com/ubuntu/microk8s/issues/2135

Found the same problem in microk8s.

**Comment by mat-ej** [comment]
Same problem here

**Comment by constanton** [comment]
> /kind question
> /priority p2
> /area installation
> @constanton did you get this resolved? I assume this is on-prem cluster. You might try asking questions at the On-Perm SIG. also, I believe we tested with K8s 1.17

I followed the solution proposed here [1]. Basically, I edited the pod's env section. @hwdef , @mat-ej I hope this helps.
 [1] https://github.com/dexidp/dex/issues/2082

**Comment by hwdef** [comment]
@constanton 
It is works! Thank you very much!!!😃
