### ISSUE TITLE
Jupyter web app logos override all of the app's assets

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5869]
/kind bug

**What steps did you take and what happened:**
Deploy the app from the latest manifests, where we mount the logos ConfigMap under the entire `assets` folder of the app
https://github.com/kubeflow/kubeflow/blob/f757f4ee1ed1c55d4d8930a13c574bcb5872409c/components/crud-web-apps/jupyter/manifests/base/deployment.yaml#L20

If I try that with a version of the app that includes more files under assets, like fonts #5691, then the files are replaced from the contents of the ConfigMap

**What did you expect to happen:**
I would like the logos to not override the contents of all the assets

**Anything else you would like to add:**
This can be done by
1. mounting the logos ConfigMap into a different subdirectory, like `assets/logos` to not override the entire folder in the manifests
2. using the updated path when fetching the logos [[code](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/src/environments/environment.ts#L10-L15)]

cc @DavidSpek @saffaalvi

**Environment:**
- Kubeflow version: 1.3

/priority p1

**Comment by DavidSpek** [comment]
The time it took to write this issue probably took twice as long as it would have taken to fix the issue. I can create a PR to fix this if it will actually get merged in a timely manner.
