### ISSUE TITLE
Kubeflow on microk8s always crashes after 2 days

### ISSUE THREAD

**Issue by sachdevayash1910** [kubeflow/kubeflow#5878]
/kind bug

I have been trying to keep kubeflow running on microk8s. It runs alright for a while, however it always crashes. Several pods get stuck in Init:0/1  although i think the culprit is the controller-0 pod which goes into CrashLoopBackoff. Looking at the logs I see the following in the mongodb container:

`2021-04-29T13:39:59.290+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true, ipv6: true, port: 37017, ssl: { PEMKeyFile: "/var/lib/juju/server.pem", PEMKeyPassword: "<password>", mode: "requireSSL" } }, replication: { oplogSizeMB: 1024, replSet: "juju" }, security: { authorization: "enabled", keyFile: "/var/lib/juju/shared-secret" }, storage: { dbPath: "/var/lib/juju/db", engine: "wiredTiger", journal: { enabled: true } }, systemLog: { quiet: true } }
2021-04-29T13:39:59.292+0000 I STORAGE  [initandlisten] exception in initAndListen: DBPathInUse: Unable to lock the lock file: /var/lib/juju/db/mongod.lock (Resource temporarily unavailable). Another mongod instance is already running on the /var/lib/juju/db directory, terminating
2021-04-29T13:39:59.292+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2021-04-29T13:39:59.292+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-37017.sock
2021-04-29T13:39:59.292+0000 I CONTROL  [initandlisten] now exiting
2021-04-29T13:39:59.292+0000 I CONTROL  [initandlisten] shutting down with code:100`

This is weird because I have no other mongodb created on this VM. We have not enabled any addon except for "registry" and the addons that Kubeflow needs.
Also, this particular pod was running fine for over 24 hours before it crashed with this error. Any idea what could be causing this? 
This is making the use of kubeflow on k8s a real blocker although we are looking to make it a big part of our workflow. I have tried on both a CPU VM and a GPU VM just to see whether the VM type is the problem.

**What did you expect to happen:**
The Kubeflow to remain up and running and not crash.

**Anything else you would like to add:**
At this point, I do not see any way to recover except uninstall everything and start again. If I delete a pod and expect it to restart, It actually gets deleted from the pod list. 

**Environment:**

- Kubeflow version: Default with microk8s 1.20
- kfctl version: (use `kfctl version`): N/A
- Kubernetes platform: (e.g. `minikube`) microk8s 1.20/stable
- OS (e.g. from `/etc/os-release`): Ubuntu 16.06

**Comment by DavidSpek** [comment]
Please create an issue at https://github.com/canonical/bundle-kubeflow as this is a distribution specific question. 

/close
