### ISSUE TITLE
Error: persistentvolumeclaim "azure-managed-disk" not found

### ISSUE THREAD

**Issue by LifeArchitect** [kubeflow/kubeflow#5881]
**Question:**

I've followed the [azure end-to-end pipeline](https://www.kubeflow.org/docs/distributions/azure/azureendtoend/) tutorial, but am getting this error when running an experiment, does anyone know what might be the problem?

![image](https://user-images.githubusercontent.com/19318871/116953966-34d56d00-acc1-11eb-9708-cff2fd18f935.png)

I've run `kubectl apply -f pvc.yaml` but somehow I dont see the volume when I do `kubectl get pvc`...am I supposed to?

![image](https://user-images.githubusercontent.com/19318871/116954078-8bdb4200-acc1-11eb-9ede-f3a5449d67a9.png)

I also dont understand why I am unable to delete the PVC

![image](https://user-images.githubusercontent.com/19318871/116955260-9ea34600-acc4-11eb-8124-03148a28e7ec.png)

PVC.yaml

![image](https://user-images.githubusercontent.com/19318871/116956655-5e45c700-acc8-11eb-9a55-c47525b6d72b.png)

pipeline.py

![image](https://user-images.githubusercontent.com/19318871/116956626-4f5f1480-acc8-11eb-8eff-8fdb3ea1e941.png)

**Comment by DavidSpek** [comment]
@LifeArchitect I think it would be best if you move this issue to https://github.com/kubeflow/pipelines/ so it can be tracked properly. This repository does not contain any of the pipeline code so the people developing pipelines will likely not see your issue here.

**Comment by LifeArchitect** [comment]
sure I've moved the issue to https://github.com/kubeflow/pipelines/issues/5605. Shall close this one.
