### ISSUE TITLE
istio-system in stuck...

### ISSUE THREAD

**Issue by mkbahk** [kubeflow/kubeflow#5882]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

istio-system           cluster-local-gateway-8558bdd679-8df2r        0/1     ContainerCreating   0          27m     <none>           host207-ipusrv16   <none>           <none>
istio-system           istio-ingressgateway-78f7794d66-zqzcc         0/1     ContainerCreating   0          27m     <none>           host203            <none>           <none>
istio-system           istiod-574485bfdc-ff4n8                       0/1     ContainerCreating   0          27m     <none>           host202            <none>           <none>

[ Error Messages from cluster-local-gateway-8558bdd679-8df2r]
MountVolume.SetUp failed for volume "istiod-ca-cert" : failed to sync configmap cache: timed out waiting for the condition

MountVolume.SetUp failed for volume "config-volume" : failed to sync configmap cache: timed out waiting for the condition

MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found

MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled

Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[config-volume istio-data istio-token cluster-local-gateway-service-account-token-htnwt ingressgateway-ca-certs istio-envoy istiod-ca-cert podinfo ingressgateway-certs]: timed out waiting for the condition

[Error Message from istio-ingressgateway-78f7794d66-zqzcc]
Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[config-volume istio-data istio-token cluster-local-gateway-service-account-token-htnwt ingressgateway-ca-certs istio-envoy istiod-ca-cert podinfo ingressgateway-certs]: timed out waiting for the condition

MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled

Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert istio-token], unattached volumes=[istio-ingressgateway-service-account-token-q9djb istio-data podinfo ingressgateway-certs istio-envoy istiod-ca-cert config-volume istio-token ingressgateway-ca-certs]: timed out waiting for the condition

Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[istio-data istio-envoy istio-token istio-ingressgateway-service-account-token-q9djb config-volume istiod-ca-cert ingressgateway-certs ingressgateway-ca-certs podinfo]: timed out waiting for the condition

[Error Messages from istiod-574485bfdc-ff4n8]
Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[istio-data istio-envoy istio-token istio-ingressgateway-service-account-token-q9djb config-volume istiod-ca-cert ingressgateway-certs ingressgateway-ca-certs podinfo]: timed out waiting for the condition

....

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):

- Kubernetes platform: (e.g. `minikube`)

- Kubernetes version: (use `kubectl version`):
root@host201:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:21:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

root@host201:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@host201:~#

**Comment by DavidSpek** [comment]
The `kube-apiserver` needs additional arguments: `--service-account-issuer=kubernetes.default.svc` and `--service-account-signing-key-file=/etc/kubernetes/ssl/sa.key` for Istio to work. I can suggest using Kubernetes 1.20 as these flags are set by default as of this version, so you will not run into this problem.

**Comment by mkbahk** [comment]
It's start working with Kubernetes 1.20. Thanks DavidSpek..
