### ISSUE TITLE
Allow "Workspace Volume" section to be read-only in the disabled state

### ISSUE THREAD

**Issue by rado-parrak** [kubeflow/kubeflow#5883]
/kind feature

**Why you need this feature:**
In our configuration of Kubeflow, the configuration of Volumes is pre-configured, so for us it is undesirable that users can create their own Workspace volumes.

**Describe the solution you'd like:**
We would like to make the "Workspace Volume" section in the new notebook server wizard read-only in the disabled state (now it can be made read-only in the enabled state). In other words, the tick-box should be made configurable such that it can be ticked-off by default and made read-only in this state.

![image](https://user-images.githubusercontent.com/11147983/117146394-73981f80-adb4-11eb-9f67-4e9ed5437078.png)

**Comment by DavidSpek** [comment]
Thanks for the suggestion. We are working on a redesign for the entire notebook spawner so we will take this into account.

**Comment by rado-parrak** [comment]
Great, thx for the message. For which KF release is the rework of the notebook spawner planned?

**Comment by DavidSpek** [comment]
We are aiming to do it for 1.4, but I can't make any promises about this sadly.

**Comment by rado-parrak** [comment]
OK, thx for the info!
