### ISSUE TITLE
Hi is it safe to deploy kubeflow v 1.3 in production

### ISSUE THREAD

**Issue by ahsan-n** [kubeflow/kubeflow#5885]
/kind question

**Question:**
Hi my question is kubeflow 1.3 is production ready? or we should go for kubeflow 1.2 for now. 
Thanks for awesome work.

**Comment by DavidSpek** [comment]
I'd say it is production ready.

**Comment by yanniszark** [comment]
I think @jbottum can provide some info on this, based on our recent user survey.
I believe a lot of users are in production with Kubeflow. Check out: https://blog.kubeflow.org/kubeflow-continues-to-move-to-production

**Comment by DavidSpek** [comment]
I believe the question was specifically regarding 1.3, which was released after the survey. I know of a few people that are running 1.3 in production using the [Argo CD](https://github.com/argoflow/argoflow) deployment, one of which upgraded from 1.0 to 1.3 using that deployment method (though some care needs to be taken here and there will be a bit of down time).

**Comment by hwk42** [comment]
Now it is still RC1 and when would 1.3 stable version be released,thanks

**Comment by DavidSpek** [comment]
Kubeflow 1.3 stable is released. A mistake was made in this repository and a new release was never cut for its components. So you can ignore the rc1 tag here.

**Comment by DavidSpek** [comment]
Closing this issue as I believe the question has been answered.

/close
