### ISSUE TITLE
Default notebook images don't start server or fail to connect kernel

### ISSUE THREAD

**Issue by cc-gb2** [kubeflow/kubeflow#5904]
Hi, I've been trying to use jupyter notebooks on an AWS Kubeflow cluster, however the default images either report no-healthy upstream (the tensorflow-2.1 images) or the kernel can't connect (the tensorflow-1.15). As these are the default images, I'd expect them all to work.

**Comment by DavidSpek** [comment]
This is usually a browser problem, can you please try restarting your browser or using a different browser?

**Comment by jbottum** [comment]
/kind question
/area jupyter
priority p2

**Comment by cc-gb2** [comment]
Sorry to reopen this, this doesn't work. I've tried on both Chrome and Firefox. How can I debug this?

**Comment by DavidSpek** [comment]
Do you see any errors in the developer console of the browser? You’ll need to open the console and then refresh the page.

**Comment by DavidSpek** [comment]
@cc-gb2 Could you try one of the new notebook images, ass the ones you are using are very outdated. The equivalent image to what your using now would be: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:v1.3.0-rc.1

**Comment by cc-gb2** [comment]
Ah yes so I've have the issue with the websocket you mention in the PR. I'd rather not screenshot it just for security, but it's along the lines of
`ws://<kubeflow-ip>...elb.amazon.com/...<notebook-url>/api/kernals/<example hash>/channels?session_id:<more_hash> faile`

**Comment by DavidSpek** [comment]
@cc-gb2 Could you possibly screenshot just the browser console error so we have it on record? Or copy the full output and remove the URL. Also, could you provide details about what OS and version you are using, along with which browser and the version of the browser (and any other browser you tried). That would help a lot for us to be able to pinpoint what could be causing the problem. Given the error is happening in the browser I don't think it is a Kubeflow or Istio problem, but it still is something we should investigate and try and figure out.

**Comment by cc-gb2** [comment]
This is a screenshot with chrome Ubuntu 18.04 Chromium Version 90.0.4430.212 (Official Build) snap (64-bit)
![image](https://user-images.githubusercontent.com/83974855/119711233-3117af00-be57-11eb-85ad-e930d9626614.png)
=

From firefox 88.0.1: 
![image](https://user-images.githubusercontent.com/83974855/119711951-ffebae80-be57-11eb-837b-df32521a2d4d.png)

**Comment by vvnpan** [comment]
@cc-gb2 were you able to figure out how to resolve this issue? I'm facing the same error using chrome and safari on different versions of the Jupyter image (v1.3 and v1.4)

**Comment by JuanValencia** [comment]
I face this same issue:
```...notebook/namespace/jupyter2/terminals/websocket/1```
Error 400
