### ISSUE TITLE
Manage Contributor Feature not working with sidecar.istio.io/inject: true 

### ISSUE THREAD

**Issue by mukul-shaunik-nokia** [kubeflow/kubeflow#5913]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Installed kubeflow 1.3 with istio sidecar enabled in all the pods including centraldashboard and profile controller.
When trying to add contributor in Manage Contributor section getting 404 not found in browser.
It is working without the sidecar enabled for the same manifest.

**What did you expect to happen:**
Expection was the contributor would get added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
  `1.3`
- kfctl version: (use `kfctl version`):
  `1.2.0`
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
  `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
`

- OS (e.g. from `/etc/os-release`): 
`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`

**Comment by DavidSpek** [comment]
These components are currently meant to be deployed without sidecar injection, so this is not a bug. However, I plan to look into enabling sidecar injection once I’m done removing the poorly maintained OIDC-authservice for OAuth2-Proxy.

**Comment by mukul-shaunik-nokia** [comment]
Thanks @DavidSpek.
Have been looking into the issue from our end, here are the findings:-
The usual flow for api/workgroup/add-contributor/j2 is from UI to central dashboard to kfam pod
But in this case the request is getting reject by istio sidecar in the centraldashboard itself.
Following is the POST request being sent from centraldashboard to kfam
```
{
  method: 'POST',
  qs: {},
  headers: {
    'kubeflow-userid': 'james@email.com',
    host: '<domain name used to access kubeflow in UI>',
    'x-request-id': '88d2efe6-8de8-46ef-ae61-2fc63e7672f1',
    'x-real-ip': '10.x.x.x',
    'x-forwarded-for': '10.x.x.x,10.x.x.x',
    'x-forwarded-host': '<domain/ip name used to access kubeflow in UI>',
    'x-forwarded-port': '443',
    'x-forwarded-proto': 'http',
    'x-original-uri': '/api/workgroup/add-contributor/j2',
    'x-scheme': 'https',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
    accept: 'application/json',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
    'content-type': 'application/json',
    origin: 'https://<url used to access kubeflow in browser>'
  },
  uri: 'http://profiles-kfam.kubeflow:8081/kfam/v1/bindings',
  useQuerystring: false,
  json: true,
  body: {
    user: { kind: 'User', name: 'bb@b.com', namespace: undefined },
    referredNamespace: 'j2',
    RoleRef: { apiGroup: undefined, kind: 'ClusterRole', name: 'edit' },
    status: undefined
  }
}
```

Upon further checking got to know that if we set the host header sent from central dashboard to "profiles-kfam.kubeflow"
the request passes through and we are able to add the contributor.
