### ISSUE TITLE
Failed to start Tensorboard app

### ISSUE THREAD

**Issue by rylynchen** [kubeflow/kubeflow#5914]
/kind question

**Question:**
Hi, I create a volume named 'nfs', and amount to the training pod in the pipeline. And training code generate tensorboard dir in the amount dir. But when I go to look tensorboard view, get error:
![p2](https://user-images.githubusercontent.com/1971286/118113863-682e9f00-b419-11eb-8e3d-ec38f1bba07f.png)

pipeline code:
```
def train_op(volume, image, cmd):
    # amount volume
    nfsVolume = dsl.PipelineVolume(volume=V1Volume(name="nfs",nfs={"server":"xxx","path":"/"}))
    svol = dsl.PipelineVolume(name='shm-vol', empty_dir={'medium': 'Memory'})
    op = dsl.ContainerOp(
        name="train",
        image=image,
        arguments=["/bin/sh", "-c", "%s" % (cmd)],
        pvolumes={
            "/output": nfsVolume,
            '/dev/shm': svol,
        },
        output_artifact_paths={
            'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json',
        },
    )
    op.container.set_cpu_limit("0.5")
    op.container.set_gpu_limit("2")
    op.container.set_memory_limit("50G")
    return op
```
My training code generate tensorboard data in `/output/runs`, and the create metadata code:
```
metadata = {
    'outputs' : [
        {
            'type': 'tensorboard',
            'source': 'volume://nfs/runs',
        }
    ]
}
with open('/mlpipeline-ui-metadata.json', 'w') as f:
    print(metadata)
    json.dump(metadata, f)
```

Anyone has good idea?

Thanks

**Comment by DavidSpek** [comment]
As this is related to pipelines, could you please move this issue to https://github.com/kubeflow/pipelines so that it can be tracked properly. The pipelines contributors are likely not going to see your issue here.

**Comment by rylynchen** [comment]
> As this is related to pipelines, could you please move this issue to https://github.com/kubeflow/pipelines so that it can be tracked properly. The pipelines contributors are likely not going to see your issue here.

Thanks!
