### ISSUE TITLE
Kubeflow : Monitoring & Observability documentation page

### ISSUE THREAD

**Issue by kd303** [kubeflow/kubeflow#5916]
/kind feature

**Why you need this feature:**
We have deployed Kubeflow on premise on a local cluster and currently we are finding it tough to find the usage metrics, monitoring functions for individual components etc. working on a common dashboards like Grafana/ELK etc. Currently there is no documentation available, only documentation that is available is on Spartakus which is a project now in sunset stage.

**Describe the solution you'd like:**
What would be really help, a separate page for observability on various components (assuming this is a cross cutting concern for all kubeflow components - notebook, pipeline, kfserving etc) :
1. What components have currently Prometheus metrics captured (Kubeflow level)
2. What are the other metrics that can be integrated (say mostly kubernetes/istio/knative level)
3. If there are any read-made GRa

if someone is kind enough to guide me, I would like to contribute this documentation. As I genuinely great work being done here.

**Anything else you would like to add:**
Any existing links issues which can be linked.

**Comment by DavidSpek** [comment]
@kd303 I have monitoring and logging for the cluster, Istio and GPUs already added to my [ArgoFlow](https://github.com/argoflow/argoflow) distribution, although I haven't had the time to update all the documentation yet. Once I have a bit more time I will be adding monitoring for Kubeflow components, as well as accompanying Grafana dashboards. If you would like to help out and contribute to the monitoring effort you can hit me up on Slack and I'll be happy to get you up to speed.

**Comment by kd303** [comment]
@DavidSpek Thanks for the info, I had a look at your repo it looks impressive. Meanwhile I was trying to look at KNative and set it up on on local cluster I found following [Knative reference](https://github.com/dewitt/knative-docs/blob/master/serving/accessing-metrics.md )

**Comment by DavidSpek** [comment]
@kd303 I've come gotten a bit further with monitoring of the Kubeflow resources in between all the other things I've been busy with. One thing I do have working is gathering KNative metrics and I've fixed a bunch of the existing KNative Grafana dashboards as those are outdated and do not work properly. Some of the dashboards still need fixing or recreating as the metrics KNative supplies have completely changed. Have you gotten any further with this effort, or would you like to help?

ArgoFlow will be an open source, enterprise ready distribution that integrates things like monitoring and logging, improved security, timely updates for all components, etc. Naturally, we'll try to upstream most of the improvements if they make sense (adding the kube-prometheus-stack helm chart to the kubeflow manifests doesn't make much sense for example).

**Comment by kd303** [comment]
@DavidSpek Unfortunately I got dragged into another project. I work on Kubeflow in very little time I get. I will keep posting any updates here and would contribute to Argo once I manage to do something substantial If you have any specific things related to Knative that you want me to look at pls feel free - I will try my best with limited knowledge.

Apologies for late replies.
