### ISSUE TITLE
Correct way of adding new dex static users 

### ISSUE THREAD

**Issue by Dimiftb** [kubeflow/kubeflow#5918]
/kind bug

**What steps did you take and what happened:**

I've got a bare metal cluster with Kubeflow installed on it by following guide here: https://github.com/kubeflow/manifests#installation 

Everything works as expected and I can successfully login in the Kubeflow dashboard with the default user credentials supplied. 

I would like to add a new static user to dex, so I added the new credentials in the dex cm and reapplied it. 

After adding the new credentials, the cm looks like this: 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/26279721/118305993-a8a52000-b4e0-11eb-8ca1-9e0bde7bd295.png">

I've added a new user with email test.

I reapply the cm with `kubectl apply -f config-map.yaml -n auth` and the cm gets configured successfully, however when I try to login with the new user credentials, I get the following: 

<img width="493" alt="image" src="https://user-images.githubusercontent.com/26279721/118306216-ff125e80-b4e0-11eb-9468-7223402ca8c0.png">
 
I also attempted to directly add the new user credentials by editing the cm installed on the cluster with `kubectl edit cm dex -n auth`, however I get the same error 'invalid email address and password'

When I completely delete and install the dex component, I can successfully login, however I a blank page get displayed instead of the Kubeflow dashboard. 

If I completely remove all Kubeflow components and reinstall them with the new credentials already in the dex cm, then everything works as expected and upon login with the new credentials the dashboard is displayed. 

What am I doing wrong? How can I add a new static user without having to reinstall all Kubeflow components?

**Environment:**

- Kubeflow version: 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/26279721/118307170-39303000-b4e2-11eb-9709-5711c8131bb1.png">

- kustomize version: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/26279721/118306761-bf984200-b4e1-11eb-8fd8-19dfb017eedc.png">

- Kubernetes version:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/26279721/118306908-e8203c00-b4e1-11eb-8baa-0cc17b13e6fb.png">

**Comment by DavidSpek** [comment]
After editing the configmap you need to run `kubectl rollout restart deployment dex -n auth` so that the new credentials are picked up. Also, you need to make sure the `email` is a valid email address as the profile controller will not work properly with just `test` in that field. You should change it to `test@example.com` or something similar.

**Comment by Dimiftb** [comment]
Thanks @DavidSpek. The restart of the deployment actually solves the issue. I'm closing this now.

**Comment by SrinivasGuntupalli** [comment]
Hi ... we have enabled the SSO to kubeflow central dashboard and now we can login with office credentials.  Now we would want to hide or remove the static login option from the login screen.

if you look at the picture it is showing two login options and the 1st option is for login with static userid and password.

can you suggest me where to modify to hide the "Log in with Email"?



![4F9E937B-AAAA-4031-9329-023F07E76A87](https://user-images.githubusercontent.com/82984845/167520740-8f60826b-233b-4622-8723-39a7bb9c5e9b.jpeg)

**Comment by Madaditya** [comment]
You should be editing the 'dex' configmap in 'auth' namespace to remove
static client.

**Comment by Luci1306** [comment]
Thanks @DavidSpek, it worked.
