### ISSUE TITLE
Kubeflow contains 2 controllers for launching Tensorboards

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/kubeflow#5921]
In the 1.3 release, the Notebooks Working Group added the Tensorboards Web App that uses the [tensorboard controller](https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller) to launch tensorboard instances. However, Kubeflow Pipelines already contains the [viewers.kubeflow.org CRD](https://github.com/kubeflow/pipelines/tree/cc83e1089b573256e781ed2e4ac90f604129e769/backend/src/crd/controller/viewer) as part of its controller, which currently is only used to start Tensorboard instances. As a result, there are now 2 controllers, along with 2 CRDs and 2 controller deployments that are serving the same purpose. Except for the obvious duplication of code and increased maintenance and deployment complexity, this is not great for the user experience. Many users will not know or expect that there are 2 controllers and CRDs that are used to start Tensorboard instances, and will also wonder why the Tensorboards Web App does not list the tensorboard instances created as part of a pipeline. The [tensorboards controller](https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller) also has the image it uses for the tensorboard pod [hardcoded in the controller](https://github.com/kubeflow/kubeflow/blob/6d6b78bcaa53480392c5acb71be578b9b9328e8d/components/tensorboard-controller/controllers/tensorboard_controller.go#L252), so there is no way for the user or the cluster admin to change what image is being used for launching a tensorboard instance (particularly problematic for those behind a firewall or in an airgapped environment).

For this reason, I would like to suggest to use the `viewers` CRD that is part of Kubeflow Pipelines in the Tensorboards Web App. Along with that, I would like to suggest to port the feature from the tensorboard controller to the KFP `viewers` controller if they are not already present (for example [RWO scheduling logic](https://github.com/kubeflow/kubeflow/blob/6d6b78bcaa53480392c5acb71be578b9b9328e8d/components/tensorboard-controller/controllers/tensorboard_controller.go#L188)).
The 2 main reason for using the KFP `viewers` CRD over the tensorboard controller are:
1. The `viewers` CRD is setup to be a more general CRD that is built to be extended to other types of viewers, such as a [file browser](https://github.com/kubeflow/pipelines/issues/5651) for example.
2. Kubeflow Pipelines sees many standalone deployments as well, while the Tensorboards Web App does not (and most, if not all, people deploying Kubeflow will also be deploying Kubeflow Pipelines). Therefore, it will more of a problem for KFP to rely on an external controller as a dependency. While this is not a great reason, and there are other possibilities that would need discussing, it is still something to take into account.

/cc @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads

**Comment by Bobgy** [comment]
Thank you for raising the issue!
I agree 💯, recently from KFP side we noticed a need for more generic viewer, e.g. other visualization tools besides tensorboard.

Also, KFP doesn't have a good CRUD UI for tensorboard. So it seems there are a lot of value to unify and make this more generic.

**Comment by DavidSpek** [comment]
In general, I think there should be a focus on improving the integration between the components to make everything feel like a more cohesive and polished platform, which would be done through the UIs.

**Comment by DavidSpek** [comment]
Another option would be to create a new controller that combines the notebook controller and the KFP `viewer` controller under a more general common `user created web apps` controller, since they are essentially performing the same tasks (pod deployment and creating an Istio VirtualService for the routing). This would allow for a single controller that could be extended with whatever user created web applications a component of Kubeflow might want to deploy in the future.

@Bobgy Do you think it would be acceptable for KFP to rely on such a common controller, mainly in terms of standalone deployments? I don't think it would be very different from the current situation with Argo Workflows for example.

**Comment by Bobgy** [comment]
For KFP standalone, there is some special proxy setup in KFP UI deployment, it doesn't use VirtualService.

Other than this, all the requirements seem to match very well. I personally think this is worth doing and KFP standalone can just take a third-party viewer controller too.

**Comment by Bobgy** [comment]
I'm sending out a generic viewer controller proposal in https://github.com/kubeflow/pipelines/issues/5681
