### ISSUE TITLE
ECR shortcomings and the need for alternative registries

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/kubeflow#5922]
With the 1.3 release of Kubeflow, the many components under the control of the Notebooks Working Group (along with some others) moved to using the Amazon ECR Public Gallery registry to host the container images of said components. I believe a large reason for using ECR this was the announcement of rate limiting the pulls of users by DockerHub. This change has caused problems for users in enterprise environments that were not setup to allow pulling from the ECR Public Gallery, among other problems. Not only has this change caused problems for users, but it has also caused problems for the maintenance of the project. Most notably due to the fact that the ECR Public Gallery does not have a publicly accessible API endpoint to list the latest image tags, breaking CI and automation such as [Renovate](https://github.com/renovatebot/renovate), see [here](https://github.com/aws/containers-roadmap/issues/1262). 
Most notably, however, is that the rate limiting employed by the ECR Public Gallery is much more restrictive than that of DockerHub. DockerHub allows for 100 pulls for unauthenticated users every 6 hours (400 pulls per day), but has recognized that 
this would cause problems for large open source projects and automated testing. To solve this problem, DockerHub has created [a program for open source projects](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) that would remove the pull rate limiting for approved projects.
On the other hand, the Amazon ECR Public Gallery has a pull rate limit of 500 GB per month. For a large image such as the tensorflow-cuda image, that mount to around 60 pulls in a month. Unless the repositories used by the Kubeflow components are somehow exempt from this limit (in which case this should be stated somewhere), this is much more restricting for the users of Kubeflow.

A quick summary of the problems with the ECR Public Gallery:

- No public API endpoint to list image tags, digests, etc
- More restrictive rate limiting on pulls
- Difficulties when dealing with firewalls for existing users
- The images are near impossible to find on the Public Gallery
- Possibly fake, unused or non-official registries are found when searching for Kubeflow ([kubeflow_official](https://gallery.ecr.aws/t4w8w5z7/kubeflow_official), [kubeflow-central-dashboard](https://gallery.ecr.aws/b7n7d1a2/kubeflow-central-dashboard), [katib](https://gallery.ecr.aws/kubeflow/katib))
- ECR Public Gallery UI is very not very user friendly and is missing basic features such as showing image digests

As such, I would like to propose that the Notebooks Working Group (and possibly others using ECR) start publishing their container images to other container registries instead of, or in addition to, the ECR Public Gallery. If the ECR Public Gallery is continued to be used, it should not be the default used in the manifests due to CI problems and user rate limiting as stated above.

A first step that should probably be taken regardless of the further decisions that are made, is to fill out the [Open Source Community Application](https://www.docker.com/community/open-source/application) for the [Kubeflow DockerHub Organization](https://hub.docker.com/u/kubeflow) to avoid users hitting rate limits for components still using this registry.

/cc @kubeflow/wg-notebooks-leads 
Also cc @kubeflow/wg-serving-leads and @kubeflow/wg-training-leads as they seem to be using the ECR Public Gallery as well.

**Comment by johnugeorge** [comment]
How is the access control to DockerHub Organization for various teams?

**Comment by DavidSpek** [comment]
@johnugeorge There is an existing DockerHub organization, but I don’t know how access is managed for this at the moment. Maybe @Bobgy can inform us about this. Personally, I’m all for giving people multiple options, so I think pushing images to DockerHub, as well as ECR, and also to GHCR would be a good setup.

**Comment by Bobgy** [comment]
Following previous decisions, I believe the most long term maintainable approach is to let each wg set up their own dockerhub account if you decide to use one

**Comment by johnugeorge** [comment]
@DavidSpek I get your point.

 I remember, there were similar discussions earlier about centralised registry for storing each KF component image but concerns were raised on ownership, management etc. And as @Bobgy told, I don't know if there is any better solution at this point than leaving it to WGs to decide.

**Comment by DavidSpek** [comment]
Ping @kubeflow/wg-notebooks-leads as this is something we need to address for the next release.

**Comment by gaocegege** [comment]
cc @PatrickXYS
