### ISSUE TITLE
first pr for improve code robustness

### ISSUE THREAD

**Issue by daniel-hutao** [kubeflow/kubeflow#5927]
/kind question

**Question:**

Hi all, I am a newcomer to the kf community. I've found some problems in the process of using some projects of kf. So I read the source code of these projects some time ago and found that there are many optimization points, such as some There is no reconcile logic in the process of concile failure some places, some important steps have no logs, and there are some logic bugs that can cause program infinite loops. I want to submit some commits to the kf and want to start with robustness first by adding some key parts of the log and reconcile logic. I don't know if it is welcomed.

**Comment by jbottum** [comment]
/priority p2
@daniel-hutao welcome and thanks for your efforts.   you might join the working group calls and provide some examples.

**Comment by daniel-hutao** [comment]
How to join the working group?

**Comment by DavidSpek** [comment]
@daniel-hutao Sorry for noticing this issue so late. Contributions are very welcome. If you contact me on Slack I'd be happy to help you get started with contributing and point you in the right direction.
