### ISSUE TITLE
Can Kubeflow run on AWS fargate?

### ISSUE THREAD

**Issue by 3dimaging** [kubeflow/kubeflow#5929]
/installation
**Question:**
Can the kubeflow be installed solely on AWS EKS fargate?
The direction of kubeflow installation is mainly about installing Kubeflow on EKS with managed nodes. Is that possible or best practice to install kubeflow on EKS with fargate only? Thank you!

**Comment by yanniszark** [comment]
cc @kubeflow/aws

**Comment by PatrickXYS** [comment]
It's not feasible for now, since EKS Fargate doesn't support PVC
