### ISSUE TITLE
Culled notebooks leak Notebook, StatefulSet, Service & VirtualService resources

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/kubeflow#5931]
/kind bug

**What steps did you take and what happened:**

I've enabled the culling of notebooks (see [this PR](https://github.com/kubeflow/kubeflow/pull/3856)). It does a great job releasing the replicas and ultimately the compute resources as the `Pod` (and any attached resources) gets downscaled once the idle timeout is met (see [here](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L303)).

Unfortunately as the current mechanism for culling notebooks is simply to reduce the `StatefulSet` replicas to `0` the `Notebook` resource itself (and any attached objects) are not culled as we would expect.

**What did you expect to happen:**

I understand not all cluster owners may wish to have this behavior so having a setting to automate the deletion of the `Notebook` CRD in this case (and let Kubernetes GC handle the cascade delete), instead of just setting the `StatefulSet` replicas to `0` would be awesome!

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.1.0 (we're a little behind but reading the code from `master` this bug still holds)
- kfctl version: (use `kfctl version`): N/A
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): v1.18
- OS (e.g. from `/etc/os-release`): Amazon EKS

**Comment by DavidSpek** [comment]
@alexlatchford Just so I fully understand your use case, you would like to automatically delete notebooks and any attached or related resources automatically after a given amount of inactive time? Also, culling will only work for Jupyter Notebook Servers, and note RStudio or VS Code based Notebook Servers, which raises another issue with the current culling implementation.

**Comment by alexlatchford** [comment]
> @alexlatchford Just so I fully understand your use case, you would like to automatically delete notebooks and any attached or related resources automatically after a given amount of inactive time? 

Hey @DavidSpek yep that's about right. For us we have a large number of scientists using our cluster, as well as a large volume of batch workflows so we've been trying to keep the number of "Terminated" resources to a minimum in the cluster otherwise we've been seeing pressures on other systems (ie. `kubelet` or some of our monitoring systems). 

> Also, culling will only work for Jupyter Notebook Servers, and note RStudio or VS Code based Notebook Servers, which raises another issue with the current culling implementation.

We're only using Jupyterlab at this point so that limitation is fine for us 😄  If there is some plans to revisit the culling implementation I'd also ideally place an upvote for considering #5932 as well as this is a similar but subtly different issue also hitting our clusters, thanks for looking into this!

**Comment by aniruddhachoudhury** [comment]
@DavidSpek Is there are any workaround to cull "VS Code based notebooks" ? 
And how about the adding Kubernetes taints to specific notebook for a namespace so that the Node Pool in Kubernetes will release the nodes and it will downscale is there any workaround in YAML to do that for each namespace?
