### ISSUE TITLE
pipeline's child pods are not deleted after workflow's status became success

### ISSUE THREAD

**Issue by anencore94** [kubeflow/kubeflow#5936]
/kind question

**Question:**

When I create kf pipeline, its components are spawned as pods in a specific order written by pipeline spec.

However, even after those pods's status became COMPLETED and pipeline's status became COMPLETED, they didn't killed automatically.

I searched about this and I guess `spec.podGC.strategy` has some releation on this issue.

But, I didn't specify that parameter on my pipeline.yaml (kind : workflow).

In my case, is this situation is normal ? (all completed pods are not deleted until their parent pipeline will be deleted)

Also, if i want my pod would be deleted when my pipeline finished successfully, Do I have to specify spec.podGC.strategy everytime?

----
my version info
- workflow controller deployment image : workflow-controller:v2.12.9-license-compliance
- ml-pipeline deployment image : gcr.io/ml-pipeline/api-server:1.5.0

**Comment by jbottum** [comment]
/area pipelines
/priority p2
@anencore94 which platform are you running on i.e. GCP, AWS, on-prem ?

**Comment by anencore94** [comment]
@jbottum
on-prem k8s v1.19.3 !

**Comment by DavidSpek** [comment]
@anencore94 I suggest moving this issue to https://github.com/kubeflow/pipelines so that it can be tracked properly. The pipeline developers don't go through the issues in this repo very regularly.

**Comment by anencore94** [comment]
@DavidSpek Thanks, I moved this to kubeflow/pipelines repository.
https://github.com/kubeflow/pipelines/issues/5763

So close this issue.
/close
