### ISSUE TITLE
Multi-node GPU usage in kubeflow notebook server

### ISSUE THREAD

**Issue by Dimiftb** [kubeflow/kubeflow#5937]
/kind question

**Question:**

Hi everyone,

I've got a cluster with 4 worker nodes, each with one GPU. Creating a notebook server with 1 GPU is fine and works as expected. When I try to create a notebook server in Kubeflow with more than 1 GPU I get an error insufficient resources: NVIDIA GPUs.  I was wondering if it's possible at all and there's a way to use all 4 GPUs in one notebook server for deep learning tasks? 

Thanks.

**Comment by jbottum** [comment]
/priority p2
/area nvidia
/platform on-prem
@Dimiftb is this an on-prem cluster?

**Comment by Dimiftb** [comment]
Hi @jbottum, 

It's installed on my machines,  not using any cloud provider, so I think that's a yes

**Comment by DavidSpek** [comment]
@Dimiftb A container/pod cannot run on multiple hosts at once. As such, you cannot schedule a notebook server and use multiple GPUs if you do not have a node that has the same or more number of (free) GPUs. If you want to run a job on all the GPUs in your cluster, you will need to use one of the operators, so that your job is split into 4 pieces and each pod runs on a separate node.

**Comment by Dimiftb** [comment]
Thanks for your help @DavidSpek, 

I assumed that would be the case, however I was really hoping there might be some way it can be done. 

I'm faced with this issue, since the cluster I've created will mostly be used for deep learning and the worker nodes I have with 1 GPU each are just not powerful enough for this. In addition, most of the users of the cluster are not really familiar with programming, and logging into Kubeflow and creating a notebook by clicking with the mouse would be a lot easier for them than actually having to create a TFJob or a PyTorch and run their code from terminal, which is the reason I was hoping there would be a way to achieve this with Kubeflow.  

Apparently, there's another package: Jupyterhub https://zero-to-jupyterhub.readthedocs.io/en/latest/ that somehow can be combined with 
Dask https://docs.dask.org/en/latest/setup/kubernetes.html to achieve hosting a notebook on multiple nodes so that more than 1 GPU can be used according to this https://discourse.jupyter.org/t/jupyterhub-multi-gpu/9299. 

I have not yet explored this option, however I'll look into it in more detail soon. I'll post the results here in case this helps someone else.

**Comment by DavidSpek** [comment]
@Dimiftb You can use Dask to execute workloads on multiple nodes, but it is simple impossible to run a single pod on more than one node at once, so this issue can be closed.
I think the solution you have in mind is where you have GPUs attached to the network directly and you can schedule them to any node. This is something that has recently become possible, but I cannot find it very quickly (only thing somewhat related that I could find is [NVIDIA GPUDirect RDMA ](https://developer.nvidia.com/blog/deploying-gpudirect-rdma-on-egx-stack-with-the-network-operator/). Do note that setups like these are more aimed at hyperscalers and will not be cheap or easy to setup and very overkill for a simple 4 node cluster.

**Comment by Dimiftb** [comment]
@DavidSpek thanks for your prompt reply. It seems that Kubeflow operators will have to do the job. I'll have a look at the link you've sent, in case this might be something that can be used in the future. Appreciate your help on this and all issues I've been posting in the last weeks regarding Kubeflow 👍
