### ISSUE TITLE
Don't bind to localhost for Istio 1.10

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5938]
One of the changes for Istio 1.10 is that the Envoy proxy will not redirect inbound traffic from `eth0` to `lo`. This means that if a web server in a container is listening to localhost then it won't be working in 1.10. 

We should update all our apps that only listen to localhost to bind to all the available interfaces instead.

A list of currently affected applications in this repo include:
* The [CentralDashboard](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/server.ts#L81-L84)
* [TensorBoard CR](https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller) instances, which should use `--bind_all` flag to not only bind in localhost

cc @kubeflow/wg-notebooks-leads

**Comment by DavidSpek** [comment]
While it does look like the central dashboard is only binding to localhost, there isn't a problem with Istio 1.10 so I'm not sure what is going on here. I've tested this on multiple fresh deployments as well.

**Comment by vinayan3** [comment]
I'm planning to upgrade to istio to 1.11 and I just ran the precheck for 1.10 and didn't see any issues. I ran the check the [release notes](https://istio.io/latest/news/releases/1.10.x/announcing-1.10/upgrade-notes/#inbound-forwarding-configuration) said to verify there would be no issues:
``
$ istioctl experimental precheck --namespace kubeflow      
✔ No issues found when checking the cluster. Istio is safe to install or upgrade!
  To get started, check out https://istio.io/latest/docs/setup/getting-started/
```
