### ISSUE TITLE
Unable to open Artifacts and Executions page on Central dashboard

### ISSUE THREAD

**Issue by subodh101** [kubeflow/kubeflow#5940]
### What is the issue?

On opening the artifacts or execution page on central dashboard, the google chrome crashes after a few seconds.
There are no issues with the `Output artifacts` of a specific run.

I checked the size of the artifacts by port-forwarding `svc/metadata-db`.
```
SELECT count(*) FROM metadb.Artifact;
```
'198232' -> Around 2 Lacs.

Similarly, I checked the size of the executions. '82,047' -> Around 1 Lac.

**Environment:**

- Kubeflow version: 1.0.4
- kfctl version: kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: GCP

Additionally, we also have an extra experimentation cluster with the same environment as above.
The count for artifacts and executions in this cluster is around 100 only and there is no issue. Artifacts and executions pop up without chrome crashing.
So, I suspect the size has become an issue.

What would be the right way to make artifacts and execution page work?
I can think of cleaning up the old artifacts and execution, keeping the size in thousands.

**Comment by DavidSpek** [comment]
@subodh101 It is possible that this issue has been fixed already as you are running an outdated version of Kubeflow, the latest version is 1.3. Would it be possible for you to test if this issue still occurs in Kubeflow 1.3?

**Comment by subodh101** [comment]
@DavidSpek 

Sorry for the late response.

Actually, the kubeflow version is 1.2, central dashboard UI shows 1.0.4, so I wrote that.

I am upgrading kubeflow version to 1.3. After finishing, will let you know about it.

**Comment by subodh101** [comment]
@DavidSpek 

I have upgraded it to Kubeflow 1.3. Behaviour is the same as above.
Any ideas where I could look into?

Additional info: Current Kubeflow setup is managed by minio with GCS and MySQL is stateful. Would the migration of the metadata DB to GCP MySQL work?

Apart from that my last option is to deploy a cleaner, that cleans the old metadata records.
