### ISSUE TITLE
Steps not getting cached when input parameters are same

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/kubeflow#5951]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I tried to ran a simple pipeline 2 times the steps outputs are not cached.

**What did you expect to happen:**
The steps should have been skippped because the input parameters are the same. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: minikf-1.3
- kfctl version:v1.16.15
- Kubernetes platform: minikube
- Kubernetes version: eks1.19
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04
-

**Comment by cloudbow** [comment]
Here is the notebook I used.


[simple_function_based_component_pipeline (1).ipynb.zip](https://github.com/kubeflow/kubeflow/files/6569070/simple_function_based_component_pipeline.1.ipynb.zip)

**Comment by DavidSpek** [comment]
@cloudbow Could you please move this issue to https://github.com/kubeflow/pipelines so that it can be tracked properly? The Pipeline developers do not regularly go through the issues on this repository.

**Comment by cloudbow** [comment]
okay

**Comment by cloudbow** [comment]
Added issue here - https://github.com/kubeflow/pipelines/issues/5764
