### ISSUE TITLE
Require explicit self-approval

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5953]
Right now prow always adds the `approved` label by default, when an approver in a code directory makes a PR. At that point anyone who adds a `/lgtm` comment can merge the PR, which means that:
1. the assigned reviewers might not have a chance to review
2. we limit the reviewers to only one person

There are workarounds like adding `/approve cancel` or `/hold` comments but people might forget to add them. We can explicitly require self-approval instead which is what Pipelines do as well https://github.com/GoogleCloudPlatform/oss-test-infra/pull/746.

We've seen this happen a lot of times in this repo https://github.com/kubeflow/kubeflow/pull/5942 https://github.com/kubeflow/kubeflow/pull/5706 https://github.com/kubeflow/kubeflow/pull/5819 so I believe the time for this change has come.

WDYT @kubeflow/wg-notebooks-leads ?

**Comment by yanniszark** [comment]
@kimwnasptd thanks for taking the time to open an issue.
I think this is one of these small changes that will make a significant difference in developer experience.
Let's iron this out and restore the behavior we originally had.

**Comment by elikatsis** [comment]
Thanks @kimwnasptd, yes we should do this

**Comment by DavidSpek** [comment]
We should also require reviews from people with different affiliations, to avoid any single entity from taking control of the components.
