### ISSUE TITLE
Istio not working on Kubeflow 1.3 running on AWS

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/kubeflow#5954]
/kind bug

**What steps did you take and what happened:**
On AWS I am using this kubeflow manifest to deploy Kubeflow 1.3 on AWS: https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/kfdef/kfctl_aws.v1.3.0.yaml
using this manifest I can access Kubeflow through:

```
kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80
```

**What did you expect to happen:**
I cannot access Kubeflow through global ip/ load balancer. How can I access Kubeflow using global ip ? using the above manifest file ? 

Note that this is Kubeflow 1.3 so manifest is diffrent than Kf1.2

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.3

**Comment by DavidSpek** [comment]
@ajinkya933 I can recommend taking a look at [ArgoFlow-AWS](https://github.com/argoflow/argoflow-aws). It deploys Kubeflow 1.3 using Argo CD making it easier to maintain and update over time. It also integrates with AWS services such as S3, RDS and SSM where possible and all third-party dependencies have been re-implemented or replaced to improve maintainability and security. We are still working hard to improve things further, but the end result aims to be an open source, enterprise ready Kubeflow distribution. If you experience any problems you can always send me a message on Slack and I'll be happy to help you.

**Comment by ajinkya933** [comment]
Hi @DavidSpek  I saw argocd but I couldn't find  a feature where Jupiter lab can be converted into pipeline using Kale. I am interested in this feature of kubeflow

**Comment by DavidSpek** [comment]
@ajinkya933 The feature you are describing is the Kale extension for JupyterLab, which is completely independent from Kubeflow itself. You can use the Argo CD distribution with Kale without a problem.

You simply need to create a notebook container where the plugin is installed to be able to use it.
An alternative to Kale that also allows you to turn Jupyter notebooks into Pipelines is [Elyra](https://github.com/elyra-ai/elyra), which you also might be interested in. If you have issues creating these notebook images I can send you Dockerfiles that contain Kale and/or Elyra if you like.

**Comment by jbottum** [comment]
Hi @ajinkya933, the Arrikto team provides enterprise support for Kale, Rok and Kubeflow.  Please feel free to reach out to me if you would like to discuss, josh.bottum@arrrikto.com.

**Comment by ajinkya933** [comment]
Please answer for Kubeflow 1.3 on AWS . I am strictly sticking with this cloud provider and Kubeflow version .

**Comment by DavidSpek** [comment]
@ajinkya933 Kale is not a part of Kubeflow and will work on any platform. If you are still facing trouble with not being able to access the dashboard you will need to provide more information about your setup and where things are going wrong.
