### ISSUE TITLE
E2E testing for the web apps

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5960]
/kind feature

**Why you need this feature:**
Right now we don't have E2E tests in-place for our [web-apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps). This makes it difficult to move forward with more advanced features that would be changing big parts of the codebase, i.e. https://github.com/kubeflow/kubeflow/pull/5805. The tests will also allow us to quickly and confidently merge proposed PRs from dependabot.

**Describe the solution you'd like:**
Create E2E tests for our web-apps and integrate them with our CI #5482.

After thinking over it I propose we move forward with using Cypress, since:
1. It has very nice documentation
3. Angular will be phasing out Protractor in favor of Cypress https://github.com/angular/protractor/issues/5502 https://angular.io/guide/roadmap#update-our-e2e-testing-strategy

Running the E2E tests with our CI/CD will require us to document decisions around our infra, how would we handle cluster creation and apply our manifests. The first step will be to have some E2E tests that we can run locally, at least, but after that I believe we should create a design document to capture our decisions around our CI/CD infra for running the tests.

**Anything else you would like to add:**
I don't want to block existing efforts until we have fully integrated the E2E tests with our CI/CD, since this effort will require some time. 

Because of this I propose we move forward in two phases. The first part is to create some E2E tests and document how someone could run them locally, by using an existing Kubeflow cluster they have. This will make it trivial to confidently test, even manually for now, huge changes in the code.

At the same time we can keep on discussing how to run the tests with CI/CD, while not blocking code development.

WDYT @kubeflow/wg-notebooks-leads @PatrickXYS

**Comment by thesuperzapper** [comment]
@kimwnasptd are you proposing is the same as discussed in the Notebooks WG meeting?

__Phase 1 (Next 1 month):__ define a google doc with manual "acceptance tests" which could be run through by a human to verify that Jupyter (and similar) are working

__Phase 2 (Next 2-6 months):__ setup the tooling for automating some of the manual acceptance tests defined in phase 1 (so they can be run in pre-submit jobs)

**Comment by thesuperzapper** [comment]
@DavidSpek and I have been working a bit on an initial google doc for "Phase 1"

**Comment by kimwnasptd** [comment]
For phase 1 the goal is to have a basic set of e2e tests that users can run locally. This way we can ask them to provide us the output of the tests in PRs and we can be confident about merging them, without waiting until the e2e tests are fully integrated with our CI.

I think a gdoc for this is an overkill, since the we don't have that many cases to test. But ofc such a doc is more that welcome!

I hope that phase 2 won't last that long. The e2e tests is going to be my main focus for this release so I'm aiming for something sooner that 6months.

**Comment by knkski** [comment]
We have a few E2E tests for Charmed Kubeflow here:

https://github.com/canonical/bundle-kubeflow/tree/master/tests

Would there be any interest in adopting those into whatever E2E testing we add for CI in this repository?

Also, there's a broader topic that might be good to discuss in this context. Would it make sense to have the E2E testing be part of a larger effort towards conformance testing? E.g. something like this for Kubeflow:

https://github.com/cncf/k8s-conformance

Since there are multiple Kubeflow distributions, it would be convenient for each distribution to be able to run conformance tests against their offerings and verify that each version they offer supports some minimum baseline of functionality specified by the conformance tests.

**Comment by kimwnasptd** [comment]
> We have a few E2E tests for Charmed Kubeflow here:
> https://github.com/canonical/bundle-kubeflow/tree/master/tests
> Would there be any interest in adopting those into whatever E2E testing we add for CI in this repository?

@knkski definitely! These tests could be also added in the CI once we sort out the following:
1. How should we create a cluster to run the E2E tests in? Spin up/down new k8s clusters or use sth lightweight like k3d?
2. Have some common code for applying manifests and waiting for resources to become ready

Once we have these sorted out then it will be quite easy to add more tests to ensure different aspects of the components are working as expected.

> Also, there's a broader topic that might be good to discuss in this context. Would it make sense to have the E2E testing be part of a larger effort towards conformance testing?

This is a very interesting topic and direction to consider. Although to be able to talk more about the structure of conformance tests we will need to have a distinct idea of what a distribution is.

@Bobgy had mentioned https://github.com/kubeflow/manifests/pull/1907#discussion_r655157718 that there is work underway for this, so lets wait and see if we get an update there first and then re-evaluate this idea

**Comment by kimwnasptd** [comment]
I'm also cross referencing the comment from @james-jwu wrt conformance testing https://github.com/kubeflow/manifests/issues/1921#issuecomment-871561816
