### ISSUE TITLE
Enable to change gpu_num_list with k8s configmap

### ISSUE THREAD

**Issue by anencore94** [kubeflow/kubeflow#5970]
/kind feature

**Why you need this feature:**
- currently, user can spawn notebook with gpu 1, 2, 4, or 8.
![image](https://user-images.githubusercontent.com/37469330/121330813-4e697480-c951-11eb-95b7-f4f209e20ddf.png)

- However, some people may want to make users only choose from [None, 1, 2] or some other options.

**Describe the solution you'd like:**
- [1,2,4,8] was fixed by crud-web-apps's jupyter frontend code:
![image](https://user-images.githubusercontent.com/37469330/121331243-a7d1a380-c951-11eb-8052-2705fad5c041.png)

- When I changed such code to ['1', '2'] and build crud-web-app docker image, and use it, the spawning UI became like this:
![image](https://user-images.githubusercontent.com/37469330/121331363-c33cae80-c951-11eb-8041-01c917660114.png)

- I want to change such field from k8s configmap which includes 'spawner_ui_config.yaml', don't want to build image myself.

**Anything else you would like to add:**
- If you guys agree, I want to implement this feature on my own.

**Comment by DavidSpek** [comment]
@anencore94 The spawner config is loaded from a configmap by default. The config in the image itself is only used if the container is started in dev mode or if the file from the configmap is missing.

How are you installing Kubeflow, and what version are you using?

**Comment by anencore94** [comment]
@DavidSpek
I installed kubeflow with kubeflow-manifests(https://github.com/kubeflow/manifests), now using v1.3.0.

However, my suggestion was not about changing configmap dynamically.

Since I think there isn't any option to change 'gpu_num_choice_list' in the configmap, I want to make it possible.
