### ISSUE TITLE
[frontend] KFP UI Experiment/Run page link doesn't populate namespace 

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/kubeflow#5973]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Open source Kubeflow v1.1
*  KFP version: 

KFP v1.3

### Steps to reproduce

When I click `Runs` on the left side menu bar, the run page link doesn't have the namespace populated (see the snapshot below).

<img width="600" alt="kfp_run_page" src="https://user-images.githubusercontent.com/475945/120729408-14115a80-c4ad-11eb-9eaa-aa9ee95e9f5b.png">

This is problematic because when I refresh the run page, the UI will first throw an error, then pick a default namespace that might be different from my previous selection (see the snapshot below)

<img width="600" alt="kfp_run_page_after_refresh" src="https://user-images.githubusercontent.com/475945/120729196-87ff3300-c4ac-11eb-8e9b-a687e363739a.png">

### Expected result
The namespace selection should be consistent after the page is refreshed. 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by daikeshi** [comment]
Thanks @Bobgy!

**Comment by MengYuanTsai** [comment]
I think the status of the pod should be confirmed first. In charge of this job's (run)  pod  status need to be running, if the pod's status get crash loop back , and you will get this error. 

Based on my past experience , my ml-pipeline pod is crashed ,this will cause problems with the Pipeline web interface get the error,and this error is same as you.
