### ISSUE TITLE
KFAM doesn't create Istio authorization policy for namespace contributors

### ISSUE THREAD

**Issue by davidspek** [kubeflow/kubeflow#5984]
/kind bug

When adding a contributor to a namespace, the profile controller creates a `RoleBinding` for the given user so they can create or view resources in the namespace. The profile controller used to create a `ServiceRoleBinding` so the user could access resources (such as notebook servers) in the namespace shared with them. With the upgrade from Istio 1.3 to 1.9, the `ServiceRoleBinding` was removed and is now replaced with the Istio `AuthorizationPolicy`. However, when adding a user as a contributor to a namespace, no `AuthorizationPolicy` is created for that user, resulting in the user not being able to access resources in the namespace shared with them. This is occurring with the latest build of the profile controller. 

/priority p0

/cc @kubeflow/wg-notebooks-leads

**Comment by yanniszark** [comment]
@DavidSpek I'm a bit confused. KFAM is responsible for adding contributors, not the profile-controller.
Can you elaborate? How can someone reproduce this issue?

**Comment by DavidSpek** [comment]
Indeed, my mistake. I realized it was KFAM just after posting the issue.

If you share your namespace with a user, you can check with kubectl and see that no authorization policy is created for that user. If you login as that user and try to access a notebook server (for example) you will get RBAC access denied.

**Comment by solarist** [comment]
Is this issue still relevant?

**Comment by juliusvonkohout** [comment]
I think this is not relevant anymore 6 releases later and I used namespace sharing in Kubeflow 1.6 for sure.

/close
