### ISSUE TITLE
Launching notebook from UI using non-default resource requests results in bad spec

### ISSUE THREAD

**Issue by pbarker** [kubeflow/kubeflow#5985]
/kind bug

**What steps did you take and what happened:**
Attempted to launch a notebook server from the UI with non-default resource requests and it results in NaN values for the resource requests in the spec.

Logs from the controller
```
E0616 02:50:26.491278       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.Notebook: v1beta1.NotebookList.Items: []v1beta1.Notebook: v1beta1.Notebook.Spec: v1beta1.NotebookSpec.Template: v1beta1.NotebookTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Limits: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|cpu":"NaN","memory":|..., bigger context ...|:"testresource","resources":{"limits":{"cpu":"NaN","memory":"NaNGi"},"requests":{"cpu":"1","memory":|...
```

**What did you expect to happen:**
A valid notebook to be provisioned

**Anything else you would like to add:**
This doesn't happen with the default parameters

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.3 https://app.vagrantup.com/arrikto/boxes/minikf/versions/20210428.0.1
- kfctl version: (use `kfctl version`):
- Kubernetes platform: minikf
- Kubernetes version: (use `kubectl version`): v1.16.15
- OS (e.g. from `/etc/os-release`): macOS 11.4

**Comment by DavidSpek** [comment]
What was the request you fille in?

**Comment by munagekar** [comment]
I also faced the same issue, this happens when a non default resource is set in the spawner_ui and the `limit` in kubeflow-config is set to `none`.

**Comment by kimwnasptd** [comment]
>I also faced the same issue, this happens when a non default resource is set in the spawner_ui and the limitFactor in jupyter-web-app-config is set to none.

@munagekar we have an issue for this https://github.com/kubeflow/kubeflow/issues/6057. This is initially an problem in the client/UI, since it ends up sending invalid structured data which is what https://github.com/kubeflow/kubeflow/pull/6058 addressed.

But since a NaN is an invalid value we can extend the backend, in your PR https://github.com/kubeflow/kubeflow/pull/6092, to ensure that requests do not contain malformed data.
