### ISSUE TITLE
Error in naming components dinamically in an iterative way

### ISSUE THREAD

**Issue by f-wole** [kubeflow/kubeflow#5988]
/kind bug

**What steps did you take and what happened:**
I inserted a cycle in my pipeline, in order to define a new component at each iteration. My pipeline looks like this (where op in my real pipeline is the training component):

```python
import kfp
from kfp import dsl, components
import kfp.components as comp


def iterator(i: int) -> int:
    print('i: {}'.format(i))
    yyy=1
    return i+yyy

iter_op = comp.create_component_from_func(iterator,base_image='python:3.7')

def init() -> int:
    return 0

init_op = comp.create_component_from_func(init,base_image='python:3.7')


@dsl.graph_component
def recursion(kk: int,xx: int):

    iter = iter_op(i=xx)

    Op = dsl.ContainerOp(
        name="train",
        image="library/bash:4.4.23",
        command=["sh", "-c"],
        arguments=['echo "$0"',iter.output]).after(iter).set_display_name('iteration-'+str(iter.output))

    with kfp.dsl.Condition(iter.output < kk):
        recursion(kk,xx=iter.output).after(Op)

@dsl.pipeline(
    name="loop",
    description="loop test",
)
def pp(k:int):
    i0 = init_op().output
    recursion(kk=k, xx=i0)

kfp.compiler.Compiler().compile(pp, __file__ + ".tar.gz")
````
The following image is an example of execution of the pipeline for k=3. Notice that the name of the op component is iteration-{{inputs.parameters.iterator-Output}}

![MicrosoftTeams-image](https://user-images.githubusercontent.com/40437714/122379995-b3cbef80-cf67-11eb-9def-5410feb1291b.png)

**What did you expect to happen:**
I expected each op component to be named with the actual value of the iterator at each cycle (e.g. "iteration-1", "iteration-2", ...) instead of {{inputs.parameters.iterator-Output}}

**Anything else you would like to add:**
In my real pipeline the op component will be a training component. I need to do it in this "sequential" way instead of using dsl.ParallelFor for infrastructural constraints.

**Environment:**

- Kubeflow version: 1.3
- kfctl version: v1.2.0-0-gbc038f9
- Kubernetes platform: minikube
- Kubernetes version: 1.20.2
- OS : Ubuntu 16.04.7 LTS

**Comment by pretidav** [comment]
Same problem here. 
It seems the name is fixed once the pipeline is compiled, is there any other possibility to define it dynamically?

**Comment by DavidSpek** [comment]
Could you please move this discussion to https://github.com/kubeflow/pipelines so it can be properly tracked? The Pipelines developers do not actively go through the issues on this repo.
