### ISSUE TITLE
Unable to create Experiment from Dashboard

### ISSUE THREAD

**Issue by RosaCandela** [kubeflow/kubeflow#5990]
/kind bug

**What steps did you take and what happened:**

We installed Kubeflow from Microk8s on a Ubuntu VM, using the following commands:
- sudo snap install microk8s --classic --channel=1.21
- sudo usermod -a -G microk8s $USER
- sudo chown -f -R $USER ~/.kube
- sudo reboot
- microk8s enable kubeflow

We accessed the dashboard using the link http://10.64.140.43.nip.io/, displayed at the end of the installation, and enabling the SOCKS proxy.

Once logged in the dashboard, we are unable to create an experiment and, consequently a run, from a pipeline.
This is the error we get when clicking on Create experiment:

**Experiment creation failed**
{"error":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","code":3,"message":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"In single-user mode, CreateExperimentRequest shouldn't contain resource references.","error_details":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references."}]}

**What did you expect to happen:**
How to create an experiment or run a pipeline

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.2 or 1.3 
- Kubernetes platform: microk8s
- OS: VM Ubuntu 18.04.5 LTS, 4 CPU, 16 GB RAM, 100 GB Disk

**Comment by DavidSpek** [comment]
Could you please move this issue to https://github.com/canonical/bundle-kubeflow since it is specific to the charmed Kubeflow distribution and not the code in this repository? The charmed Kubeflow developers also do not go through the issues in this repository so your issue will likely not get properly tracked here.

**Comment by RosaCandela** [comment]
Issue has been moved to https://github.com/canonical/bundle-kubeflow/issues/375
