### ISSUE TITLE
Error in workloads deployed on GKE with Kubeflow 1.3

### ISSUE THREAD

**Issue by shalankig** [kubeflow/kubeflow#6002]
I have successfully deployed Kubeflow on a private GKE Cluster using https://github.com/kubeflow/manifests#install-with-a-single-command

GKE Version: 1.17.17-gke.9100
Kubeflow Version: 1.3
Workload Identity Enabled: Yes

**Issue 1:**
There is a lag with Workload Identity, where it does not fetch credentials immediately from the metadata server.

> command: ["bash","-c","gcloud config list]
> 
> $kubectl -n kubeflow pod/test -c test
> [core]
> disable_usage_reporting = true

However, the same container when run with an initial delay returns the correct and expected configuration

> command: ["bash","-c","sleep 10s;gcloud config list]
> 
> $kubectl -n kubeflow pod/test -c test
> [core]
> account = sa@project_id.iam.gserviceaccount.com
> disable_usage_reporting = true
> project = project_id

**Issue 2:**
Error Encountered while running a kubeflow pipeline in kubeflow namespace.

`HTTP: response body: {"error":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []","code":3, "message":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []", "details":[{"@type":"type.googleapis.com/api.Error","error_message":"Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []","error_details":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []"
`

**Comment by shalankig** [comment]
Dug a bit deeper, Issue 2 highlighted above seems to be a result of errors from Kfp client.
Reference issue here: https://github.com/kubeflow/pipelines/issues/5907

**Comment by jbottum** [comment]
@shalankig did you get this resolved

/platform gcp
/area pipelines
/priority p2
