### ISSUE TITLE
Cannot install Kubeflow fairing without downloading all the different versions of botocore.

### ISSUE THREAD

**Issue by marsupialtail** [kubeflow/kubeflow#6003]
I tried to do pip install kubeflow-fairing. 

pip went about to download all the versions of botocore it could find and runs out of space. 

Is this expected behavior?

**Comment by DavidSpek** [comment]
@marsupialtail Could you please move this issue to https://github.com/kubeflow/fairing so it can be tracked properly? The fairing code does not live in this repository.

**Comment by skeswani** [comment]
Was this issue logged/moved and/or fixed?
