### ISSUE TITLE
Tensorboard-controller's tensorboard image should be configurable

### ISSUE THREAD

**Issue by andres-de-castro** [kubeflow/kubeflow#6008]
/kind feature

https://github.com/kubeflow/kubeflow/blob/18264c8fcf00ceb225a0243377874a7df4301b98/components/tensorboard-controller/controllers/tensorboard_controller.go#L252

**Why you need this feature:**
non-docker registry images are preferred due to rate limits

**Describe the solution you'd like:**
Please make this configurable via an environment variable or binary argument

**Comment by DavidSpek** [comment]
This would hopefully be solved by implementing https://github.com/kubeflow/pipelines/issues/5681.

**Comment by Windfarer** [comment]
+1 for this feature
