### ISSUE TITLE
Creating a notebook with GPU (body must be of type string: "integer"`)

### ISSUE THREAD

**Issue by ChusMoyano** [kubeflow/kubeflow#6014]
Hello!

I'm trying to create a notebook with a GPU asociated, but im getting this error. Also tryed to create it by a cURL but didnt worked neither.

Error: `Notebook.kubeflow.org "testgpu" is invalid: spec.template.spec.containers.resources.limits.nvidia.com/gpu: Invalid value: "integer": spec.template.spec.containers.resources.limits.nvidia.com/gpu in body must be of type string: "integer"`

I created a notebook without an gpu associated but Tensorflow recognice that i have one.

**Comment by edhenry** [comment]
I'm hitting this issue, as well.

I believe the issue resides in this LOC : https://github.com/kubeflow/kubeflow/blob/2ed54bcce7cbc38f0f63bfb32f7f5ef677a58765/components/crud-web-apps/jupyter/backend/apps/common/form.py#L279

The output of the logs from the jupyter-UI pod is shown below and it looks like the `nvidia.com/gpu` key as an `integer` of 1 where it should be a `string`?

```bash
2021-07-16 16:05:52,143 | kubeflow_jupyter.default.app | INFO | Creating Notebook: {'apiVersion': 'kubeflow.org/v1beta1', 'kind': 'Notebook', 'metadata': {'name': 'oppenheimer', 'namespace': 'admin', 'labels': {'app': 'oppenheimer'}}, 'spec': {'template': {'spec': {'affinity': {}, 'serviceAccountName': 'default-editor', 'containers': [{'name': 'oppenheimer', 'image': 'dcr.octo.dell.com/kali/kali-kubeflow-jupyter:latest', 'volumeMounts': [{'mountPath': '/home/jovyan', 'name': 'workspace-oppenheimer'}, {'mountPath': '/dev/shm', 'name': 'dshm'}], 'env': [], 'resources': {'requests': {'cpu': '10.0', 'memory': '50.0Gi'}, 'limits': {'cpu': '10.0', 'memory': '50.0Gi', 'nvidia.com/gpu': 1}}}], 'ttlSecondsAfterFinished': 300, 'tolerations': [], 'volumes': [{'name': 'workspace-oppenheimer', 'persistentVolumeClaim': {'claimName': 'workspace-oppenheimer'}}, {'name': 'dshm', 'emptyDir': {'medium': 'Memory'}}]}}}}
```

That is reflected in the screenshot of the error below.

![image](https://user-images.githubusercontent.com/5572998/125976810-d6a9b9a4-d7d1-465d-9160-466ec32de0f3.png)

I'll try and let a local dev environment up today to test this.

**Comment by edhenry** [comment]
I was able to create the notebook after casting the integer as a string.

![image](https://user-images.githubusercontent.com/5572998/125979535-cb076f70-a40f-4e3b-a866-eccb66dd1727.png)

I will look into getting a pull request opened, though I'm not sure if this field has changed type definitions respective of the underlying kubernetes API recently. I'll look to the core team for guidance there. :smile_cat:

**Comment by edhenry** [comment]
I was able to create the notebook after casting the integer as a string.

![image](https://user-images.githubusercontent.com/5572998/125979688-92fcf029-1bff-4f66-9866-f1b83c4022b6.png)


I will look into getting a pull request opened, though I'm not sure if this field has changed type definitions respective of the underlying kubernetes API recently. I'll look to the core team for guidance there. smile_cat

**Comment by ChusMoyano** [comment]
When this MR is merged this will be fixed right? :D

**Comment by edhenry** [comment]
@ChusMoyano There was a PR that was merged relatively recently fixing this : https://github.com/kubeflow/kubeflow/pull/5891

It looks like the above linked PR should be part of the [v1.3.1-rc0](https://github.com/kubeflow/kubeflow/releases/tag/v1.3.1-rc.0) release listed under the releases of the repo. If you deploy using that release candidate you should see the fixes reflected in your environment. I'll test in my lab today, as well. 😄

**Comment by gcheron** [comment]
I am also facing same issue. Have you tried the v1.3.1-rc0 release? Does it work?
I was using juju to install Kubeflow bundle, I guess I won't have this fix for the moment...

**Comment by DnPlas** [comment]
Hi @edhenry and @ChusMoyano, we are having this exact same issue in Charmed Kubeflow 1.4 using `public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.4`. For me the #5891 didn't resolve the issue, but what's introduced by #6051 did. I believe that [file](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts) modified by the #5891 doesn't even make it to the final [image](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/Dockerfile#L58).
My workaround so far has been editing `form.py` as suggested by @edhenry [here](https://github.com/kubeflow/kubeflow/issues/6014#issuecomment-881562991), re-build the image and re-deploy `jupyter-ui`.

**Comment by EMCP** [comment]
> Hi @edhenry and @ChusMoyano, we are having this exact same issue in Charmed Kubeflow 1.4 using `public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.4`. For me the #5891 didn't resolve the issue, but what's introduced by #6051 did. I believe that [file](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts) modified by the #5891 doesn't even make it to the final [image](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/Dockerfile#L58). My workaround so far has been editing `form.py` as suggested by @edhenry [here](https://github.com/kubeflow/kubeflow/issues/6014#issuecomment-881562991), re-build the image and re-deploy `jupyter-ui`.

as a total n00b to k8s and kubeflow.. where do I ssh into .. in order to edit or fix this ? Hitting this issue as well with the `juju deploy kubeflow --trust`
