### ISSUE TITLE
kubeflow notebook doesnot support spark

### ISSUE THREAD

**Issue by biaochen** [kubeflow/kubeflow#6020]
It seems kubeflow notebook doesnot support spark yet. 
My case is, I want to communicate with a spark cluster which is outside my k8s cluster.
I build a jupyter image supporting spark, then create a pod listening on 8888 as notebook port, 30001 as spark.driver.host, 30002 as spark.blockManager.port, then create a NodePort-typed service transferring those ports to the upstream pod. By doing that I can write spark within notebook, and communicate with spark cluster.
However, this solution cannot be integrated with kubeflow, as kubeflow's notebook-controller fixes the behavior of service and statefulset, the service must be ClusterIP-typed, and the pod can only listen to 8888 port.
My problem is, how to modify kubeflow code and how to make modifications to k8s cluster, so kubeflow notebook can support spark. 
Thanks

**Comment by paulk8s** [comment]
Any updates?
