### ISSUE TITLE
Logout from Kubeflow and OpenID Connect Provider at once

### ISSUE THREAD

**Issue by Te-YuanLiu** [kubeflow/kubeflow#6026]
/kind question

**Question:**
I have installed Kubeflow using [this guide](https://v0-7.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/) and then connected Dex to an OpenID Connect Provider using [this guide](https://dexidp.io/docs/connectors/oidc/).
Everything works well except I couldn't find a way to logout from both Kubeflow and the OIDC Provider at the same time.

I know that hitting the logout button on the central dashboard of Kubeflow deletes the user's session from AuthService's database, so what I plan to do is redirecting user to the OIDC Provider logout endpoint to clear its session as well.

Is this already supported?
If it is, then what configuration (like a variable in a configMap) should I set to redirect user to the OIDC Provider logout endpoint after the Kubeflow `/logout` endpoint clears the user's session?

**Comment by jbottum** [comment]
/area notebooks
/priority p2
@kubeflow/wg-notebooks-leads
