### ISSUE TITLE
Couldnt get login option on kubeflow dashboard( invalid client_id)

### ISSUE THREAD

**Issue by nitesh31mishra** [kubeflow/kubeflow#6028]
I am running enable command for kubeflow. It ran successfully but once I open the URL I get to see this error
```
Bad Request
Invalid client_id ("authservice-oidc").
```
This is how it shows...
![image](https://user-images.githubusercontent.com/54522260/124122810-22469c80-da94-11eb-8f63-33e883821573.png)

**Comment by ajinkya933** [comment]
could you give more details like how did you install, cloud provider?

**Comment by nitesh31mishra** [comment]
Issue is resolved
