### ISSUE TITLE
Highest release version, v13 is not the latest release. 

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/kubeflow#6029]
/kind bug

The highest release version, https://github.com/kubeflow/kubeflow/tree/v13 is not the latest release https://github.com/kubeflow/kubeflow/tree/v1.3.1-rc.0. Suggest v13 is deleted since it will otherwise look like the latest release until version >v.13 is released. 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by kimwnasptd** [comment]
Good catch! This should be a typo and it's Indeed pretty confusing. 

I'll fix this
/assign @kimwnasptd

**Comment by kimwnasptd** [comment]
Done, thanks for reporting @NikeNano 

/close
