### ISSUE TITLE
Adding new components to a predefined pipeline

### ISSUE THREAD

**Issue by tmerrittsmith** [kubeflow/kubeflow#6030]
/kind question

Suppose I've already defined a kubeflow pipeline using the SDK, but want to develop a new component and understand how it impacts the pipeline. Is there a standard way to do this using kubeflow? I can see that I can develop new pipelines or components using Kale, but I'm not sure if this can be connected to a predefined pipeline. I couldn't see this in the docs.

Thanks

**Comment by jbottum** [comment]
@tmerrittsmith did you get this resolved?  Have you tried any of the kale tutorials? this is a good place to start, https://codelabs.arrikto.com/codelabs/minikf-kale-katib-kfserving/index.html#0

/priority p2

**Comment by tmerrittsmith** [comment]
Not yet but it's ok to close. Kale can create pipelines, not sure if it
interacts with an already created one.
