### ISSUE TITLE
Kubeflow login not possible anymore

### ISSUE THREAD

**Issue by MeranaTona** [kubeflow/kubeflow#6036]
/kind bug

Hi all,

**What steps did you take and what happened:**

Logged in on Kubeflow, using the ingress IP, ingress port and my user account. Then, was working on a Jupyter NB hosted on the Kubeflow Jupyter Hub server. Out of nowhere, I got logged out of Kubeflow. 
Tried to login in the same way like before, using ingress IP and ingress port but this time the web page gave no response (no login mask appeared). Also predictor pods did not give responses anymore when sending requests via curl. 

Next, I tried to port-forward the Kubeflow dashboard (kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80). It always worked before, but this time the dashboard would not show up. Pods in namespace isto-system and kubeflow were on state "running".  In the next attempt, relevent pods were deleted (kubectl delte pod ...). Namely, "istiod", "istio-ingressgateway" and "cluster-local-gateway". Did not fix the problem. Finally, after deleting pod "authservice-0" Kubeflow login was available again under ingress IP and ingress port.

**What did you expect to happen:**

Kubeflow login and authentification working consistently and not requiring users to restart istio pods.

**Environment:**

- Kubeflow version: Kubeflow Dashboard dispalys dev_local, I installed Kubeflow 1.3
- kfctl version: v1.2.0-0-gbc038f9
- Kubernetes platform:https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 ??
- Kubernetes version: v1.18.14
- OS: Operating System: CentOS Linux 7 (Core),  CPE OS Name: cpe:/o:centos:centos:7, Kernel: Linux 3.10.0-1127.19.1.el7.x86_64

Greetings

**Comment by jbottum** [comment]
@MeranaTona did you get this resolved?  did you install using kfctl rather than Kustomize ?  Which istio version are you using? which platform are you on i.e. AWS, GCP, on-prem ?
