### ISSUE TITLE
Add support for pyspark notebook kernel for data analysis.

### ISSUE THREAD

**Issue by Nagarajj** [kubeflow/kubeflow#6038]
/kind feature

**Why you need this feature:**
Kubeflow Notebooks does not support PySpark Kernel which is important for data/feature analysis.

**Describe the solution you'd like:**
There are multiple modes of running spark queries, (non-client mode, client mode). While there are known issues with running  spark in client mode as described [here](https://github.com/kubeflow/kubeflow/issues/4306). It will be good to support non-client mode to begin with, while further enhancing support for client mode. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Nagarajj** [comment]
@DavidSpek please see if this feature can be enabled in kubeflow. Thanks.

**Comment by TPP2** [comment]
This feature will greatly reduce the effort of setting up spark notebook on Kubeflow.

**Comment by mousam-singh** [comment]
I also could not find any further solution for this issue or enhancement. Please let us know if there is any workaround for this.
#4306 #4543
