### ISSUE TITLE
Use Angular's official internationalization solution

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6042]
Right now our web apps are using a third-party library, [ngx-translate](https://github.com/ngx-translate/core), to provide Internationalization support https://github.com/kubeflow/kubeflow/issues/5858 https://github.com/kubeflow/kubeflow/pull/5880. But there are some serious issues with this approach, that were not discussed during the review of https://github.com/kubeflow/kubeflow/pull/5880, which we need to consider:
1. We are not using the official Internationalization solution from Angular https://angular.io/guide/i18n
2. The `ngx-translate` library's maintenance has been significantly reduced in the last couple years https://github.com/ngx-translate/core/issues/783 https://github.com/ngx-translate/core/graphs/contributors
3. `ngx-translate` will not work with future versions of Angular since it's currently using ViewEngine, which is deprecated and will be removed in a future major Angular release https://github.com/ngx-translate/core/issues/1316 https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49

To mitigate the issues from the above points we should instead use Angular's official Internationalization solution. 

I'd like to start looking into this after we've migrated to the latest version of Angular https://github.com/kubeflow/kubeflow/issues/5525 though, so lets keep our current implementation until https://github.com/kubeflow/kubeflow/pull/6004 is merged.

cc @kubeflow/wg-notebooks-leads @wg102 @Jose-Matsuda @tasos-ale

**Comment by kimwnasptd** [comment]
I'll allocate cycles on this, since we need to sort this out before updating the Katib web app and Models web app to use the latest common code

/assign @kimwnasptd

**Comment by kimwnasptd** [comment]
While working on this I had the chance to take a more detailed look into the implementation with `ngx-translate`. As a first step towards using Angular's `i18n` solution we will need to make explicit the architecture we will use for the translation.

Internationalization support will be broken down into the frontend and the backend work. For the frontend we will use constructs like
* the `i18n` attribute in html elements, to denote that their text content needs to be translated
* the `i18n-{attribute}` in html elements, to denote that an attribute in that html node should be translated
* the `[$localize](https://angular.io/api/localize/init/$localize) function to denote that the text of a TypeScript variable should be translated

With the above we will be able to translate most of, if not all, the frontend text. The next thing then to discuss will be how the backend could have i18n support for the strings it sends to the frontend.

**Comment by kimwnasptd** [comment]
Also, by following Angular's proposed implementation we will end up with translation files, in distinct folders, for each language. This will allow us to have OWNERS files to make it clear who are the people responsible for keeping a translation up to date.

We should also make it explicit, in the app's READMEs for now, that the i18n support is only provided as best effort for other languages.

**Comment by dobrinsky** [comment]
Come on man....Please tell us this is a joke!

How could you think that giving a solution to something that is written in JASON files and that is using pipes...I mean some of Angular's main characteristics could be changed with something like this:

https://angular.io/guide/i18n-example

Which uses...for GOD's SAKE XML files?

This is a textbook example of problems made by people who do not take into consideration generally accepted ways of doing things and want everybody to use the ways they personally prefer
