### ISSUE TITLE
Update KF Roadmap doc with 1.4 upcoming items.

### ISSUE THREAD

**Issue by mkbhanda** [kubeflow/kubeflow#6048]
/kind feature

**Why you need this feature:**
Keep Roadmap up-to-date

**Describe the solution you'd like:**
Add high-level summary of roadmap items in the sub-projects.

**Anything else you would like to add:**
Reach out to other sub-project WGs and have a similar process in place

**Comment by jbottum** [comment]
Here are some potential themes for 1.4

- Reduce redundant code - Training, Web Apps
- Faster, better builds with more CI/CD - Katib, Training, Notebooks
- 20% improvement in Kubeflow.org Docs
- Maturation of V2 Protocols in KFServing and KFPipelines
- KFServing User Interface with model details, logs, yaml
- Increased use of metadata for pipeline orchestration and model performance monitoring

**Comment by jbottum** [comment]
And the Working Group roadmaps
Operators - https://github.com/kubeflow/common/blob/master/ROADMAP.md
KFServing - https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md
Katib - https://github.com/kubeflow/katib/blob/master/ROADMAP.md
Pipelines - https://github.com/kubeflow/pipelines/blob/master/ROADMAP.md

**Comment by jbottum** [comment]
@mkbhanda A few related work items 

- rewrite roadmap with the latest deliveries at the top of the roadmap
- develop themes and content for 1st pass of roadmap (and determine which Working Group features should also be shown in Kubeflow roadmap)
- find links to all working group roadmaps (see comment above)

**Comment by jbottum** [comment]
@mkbhanda Hi - Are you going to take a shot at the draft for this ? Please let me know.   Thanks.   Josh

**Comment by jbottum** [comment]
@mkbhanda I think we can close this issue as soon as this PR merges.   https://github.com/kubeflow/kubeflow/pull/6082
