### ISSUE TITLE
Access kubeflow dashboard access running in microk8s 

### ISSUE THREAD

**Issue by sachithmuhandiram** [kubeflow/kubeflow#6049]
/kind question

**Question:**
We had deployed kubeflow in microk8s as described [here](https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/)

All the pods and services are running, then I ran

`microk8s.kubectl port-forward svc/istio-ingressgateway -n kubeflow 8090:80`

I can access it as `localhost:8090`, but I want to access to this from other user PC's in the network. 

How to do it? 

I had tried editing `kubeflow-dashboard` to NodePort service. I could access UI, but none of the UIs were accessible, they got the same issue discussed as [here](https://github.com/kubeflow/kubeflow/issues/4650)

**Comment by rc-coderepo** [comment]
what is the service type of svc/istio-ingressgateway ? If it is already node port you can try access kubeflow UI on the nodeport that istio-ingressgateway is allocated. For the kubeflow UI to work you have to have all the pods in kubeflow and istio-system namespace should be running. 

If svc/istio-ingressgateway is on ClusterIP try changing it to NodePort

**Comment by sachithmuhandiram** [comment]
svc/istio-ingresgateway

> kubeflow                 istio-ingressgateway                         LoadBalancer

There is no `istio-system` in the system

**Comment by rc-coderepo** [comment]
Did you try accessing on this ip - 10.64.140.43.nip.io? Did you install kubeflow on ubuntu running on a VM?
