### ISSUE TITLE
[bug] Setting limitFactor to none results in incorrect spec for Notebook

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6057]
/kind bug

**What steps did you take and what happened:**
1. Set the `cpu.limitFactor` to `none` in the Jupyter web app's ConfigMap 
2. Navigate to the form
3. Edit the form's cpu requests
4. Create a new Notebook.

The created Notebook will have `NaN` value for the cpu limits, which makes the StatefulSet controller unable to create the underlying Pod.

**What did you expect to happen:**
The cpu limits to not have a value, since the `limitFactor` is `none`

**Anything else you would like to add:**
This is an issue with the frontend that doesn't parse the config's value correctly, which results in a `NaN` value in javascript

**Comment by kimwnasptd** [comment]
I've worked on a fix for this. I'll push a PR

/assign @kimwnasptd

**Comment by DavidSpek** [comment]
Strange that this error appeared since I know I tested this scenario. I'm interested to see what is causing this behavior.

**Comment by kimwnasptd** [comment]
Oh wait, I didn't phrase it correctly. This does not happen when I just create the Notebook, but **after** I edit the requests in the form, which results in the form trying to recalculate the value for the limits.

I'll edit the description to make it explicit

**Comment by kimwnasptd** [comment]
This will also be a good use case for adding an E2E test #3657 to ensure we catch this in the future
