### ISSUE TITLE
Hide kubeflow dashboard

### ISSUE THREAD

**Issue by JaimeHolland** [kubeflow/kubeflow#6059]
/kind question

**Question:**
Hi, I've followed these instructions to install kubeflow on EKS:
https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/

The kubeflow dashboard is being exposed as a public site on the internet.  How can I turn that off?  I'm assuming there's a configuration possible where I can get to the dashboard using `kubectl proxy` instead of having it so publicly available?

**Comment by kd303** [comment]
Is it not possible for you to change the istio-ingress IP to non-nodeport? That will block everything coming in from outside the network, is that what you are looking for?

**Comment by JaimeHolland** [comment]
> Is it not possible for you to change the istio-ingress IP to non-nodeport? That will block everything coming in from outside the network, is that what you are looking for?

That would be a suitable approach, is that just an annotation that needs to be added, do you know?

**Comment by jbottum** [comment]
@JaimeHolland did you get this resolved ?

/kind question
/priority p2

**Comment by JaimeHolland** [comment]
> @JaimeHolland did you get this resolved ?
> 
> /kind question
> /priority p2

Hi, yes, there were some annotations I needed to add to make the loadbalancer `internal`, so that was all that was needed in my case
