### ISSUE TITLE
ks delete dependencies with CRDs

### ISSUE THREAD

**Issue by danisla** [kubeflow/kubeflow#606]
When trying to delete the cert-manager component, ksonnet generates an error saying it can't find the issuer resource:

```
INFO  Deleting customresourcedefinitions certificates.certmanager.k8s.io
INFO  Deleting customresourcedefinitions clusterissuers.certmanager.k8s.io
INFO  Deleting customresourcedefinitions issuers.certmanager.k8s.io
INFO  Deleting serviceaccounts default.cert-manager
INFO  Deleting clusterroles cert-manager
INFO  Deleting clusterrolebindings cert-manager
INFO  Deleting deployments default.cert-manager
INFO  Deleting issuer default.letsencrypt-prod
ERROR the server could not find the requested resource
```

This is because the `Issuer` CRD gets deleted before the `letsencrypt-prod` resource so the k8s API doesn't even know what an `Issuer` is at that point and generates an error.

Ideally, ksonnet would delete the child resources for CRDs before deleting the actual CRD. 

This is a bit problematic because the error is a hard stop in the deletion process and you can't just `ks delete default` to cleanup the entire environment.

```sh
$ ksonnet version
ksonnet version: v0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
```

**Comment by ankushagarwal** [comment]
@danisla : Would it be possible to open an issue in the ksonnet [repo](https://github.com/ksonnet/ksonnet/issues). It's unlikely that this issue will make progress here.
