### ISSUE TITLE
Jupyter Notebook : Large image display with HAProxy configuration

### ISSUE THREAD

**Issue by kd303** [kubeflow/kubeflow#6060]
/kind Question

Hi All,

This is not Kubeflow issue. We have deployed Kubeflow 1.1 on-premise Kubernetes 1.18 cluster. We are trying to put an HAProxy in front of the default port/IP - 31380. We have observed strange behavior, almost everything works w.r.t notebook functionality like Terminals, displaying some small images inline to notebook, however for large images (> 200 MB) the images are not displaying correctly on the notebook. When we try the direct URL by bypassing the HAProxy we are able to see the same images visible.

Any insights/clues will be helpful.

**Comment by jbottum** [comment]
/priority p2

@kd303 did you get this resolved ?     Which storage class are you using for the large images ?
