### ISSUE TITLE
kubeflow pipeline client rbac access error

### ISSUE THREAD

**Issue by seoha-kim** [kubeflow/kubeflow#6061]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

import kfp
from kfp import dsl

@kfp.dsl.component
def train_component_op():
    return kfp.dsl.ContainerOp(
        name='mnist-train',
        image='seohakim/pipeline-test:0.1'
    )

@dsl.pipeline(
    name='My pipeline',
    description='My machine learning pipeline'
)

def my_pipeline():
    train_task = train_component_op()

if __name__ == '__main__':
    pipeline_package_path='my_pipeline.zip'
    kfp.compiler.Compiler().compile(my_pipeline, pipeline_package_path)
    client = kfp.Client()
    my_experiment = client.create_experiment(name='Basic Experiment')
    my_run = client.run_pipeline(my_experiment.id, 'my_pipeline', pipeline_package_path)

---

after i run above code in my local server
i got error like this

---

raceback (most recent call last):
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp/_client.py", line 363, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/plask/anaconda3/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Length': '19', 'Content-Type': 'text/plain', 'Date': 'Thu, 22 Jul 2021 07:46:33 GMT', 'Server': 'istio-envoy', 'X-Envoy-Decorator-Operation': 'ml-pipeline.kubeflow.svc.cluster.local:8888/*'})
HTTP response body: RBAC: access denied

---

i run pipeline-rolebinding yaml file like below,
but there is no difference... how can i solve this problem?

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: access-instio-ingress
  namespace: istio-system
rules:
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-service-access-role
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-instio-ingress
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: plask

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.2
- kfctl version: (use `kfctl version`): 1.2
- Kubernetes platform: (e.g. `minikube`) kubectl
- Kubernetes version: (use `kubectl version`): 1.2
- OS (e.g. from `/etc/os-release`):ubunt 16.04

**Comment by jbottum** [comment]
@seoha-kim did you get this resolved?   the configuration settings can be complex.    have you considered using a vendor provided deployment pattern that includes technical support?   please see this link for an example, https://new.docs.arrikto.com/#installation

**Comment by kosehy** [comment]
@seoha-kim this seems to be related to [kubeflow/pipelines#4440 (comment)](https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687689294)

**Comment by seoha-kim** [comment]
I resolved this problem by upgrading kubeflow to 1.3v
