### ISSUE TITLE
minikf remote accsess

### ISSUE THREAD

**Issue by IsraelAbebe** [kubeflow/kubeflow#6066]
I am working on the remote machine and wanted to know how to use the min if dashboard after doing vagrant up, is there a way to deploy it on external IP?

**Comment by jbottum** [comment]
@IsraelAbebe this use case is not supported.   I will ask the MiniKF team if they have any suggestions.

**Comment by jbottum** [comment]
@IsraelAbebe I checked with Arrikto R&D.   They are supporting this use case with multi-node clusters for Arrikto Enterprise Kubeflow customers.   Did you get this use case resolved ?

**Comment by jbottum** [comment]
@IsraelAbebe is this issue still open?  would you like to close or discuss other options ?

**Comment by arianpasquali** [comment]
I also have the same question. Did you manage to solve this?

**Comment by arianpasquali** [comment]
You will probably need to manually setup a nginx proxy redirect.
Related discussion here https://github.com/kubeflow/kubeflow/issues/5078
