### ISSUE TITLE
This step is in Error state with this message: pod deleted during operation

### ISSUE THREAD

**Issue by bryant-rh** [kubeflow/kubeflow#6067]
/kind question
What steps did you take and what happened:
"This step is in Error state with this message: pod deleted during operation"

**Question:**
[You can ask any question about this project.]
![image](https://user-images.githubusercontent.com/43403977/127143032-8ac3fb3a-bb23-4a72-bfff-130f5775839c.png)

Environment:

Kubeflow version: v1.3.0
Kubernetes platform: kubectl, EKS
Kubernetes version: 1.20
OS (e.g. from /etc/os-release): Linux ceph2 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aleb** [comment]
I had the same problem. I's very confusing that the AWS EKS "managed" nodepools are not actually managed, they only have details about how the managing should be done (min/max number of nodes etc). You have to deploy your own cluster-autoscaler or some equivalent to do the actual managing.

See for example https://www.eksworkshop.com/beginner/080_scaling/deploy_ca/ or https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html.

The main missing info about cluster-autoscaler from these guides is that it scales down the node-group when the pods can fit on a smaller number of nodes!

If you increase the default `-v4` log level in `kubectl -n kube-system edit deployment/cluster-autoscaler` you can see details in the logs with `kubectl -n kube-system logs -f deployment/cluster-autoscaler`.

See https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node for how to mark your pods non-evictable.
