### ISSUE TITLE
Pipeline.AI + Kafka + TensorFlow Integration for Real-Time ML/AI Pipelines in KubeFlow

### ISSUE THREAD

**Issue by cfregly** [kubeflow/kubeflow#607]
@aronchick @jlewi @BrentDorsey @kwmsmith @bhack @schnee

We're contributing the following from our [Pipeline.AI Real-Time AI Platform](https://github.com/PipelineAI/pipeline):

Continuous Model Training
1) Kafka Stream => TensorFlow Training (Estimator API + Dataset API)

Continuous Model Updates in Live Production
2) Kafka Stream => TensorFlow Training => Kubernetes (`kubectl rollout`)

Continuous Model Inference
3) Kafka Stream => TensorFlow Serving Predictions (Custom Python `predict()` + Kafka Streams API)

Future contributions may include the following from our Pipeline.AI live-experiment subsystem:
1) Experiment Management
2) Static A/B Testing
3) Dynamic Multi-Armed Bandits
4) Live Traffic Shaping - Spilt and Shadow
5) Advanced Canary Analysis (Auto Rollback)

Pull requests are coming very soon.  We will likely split this into multiple issues for tracking purposes.  See comments below for related issues.

**Comment by cfregly** [comment]
cc @ewencp from confluent

**Comment by jlewi** [comment]
This is great.

I added some instructions about creating ksonnet packages in #609

**Comment by aronchick** [comment]
This is great! Can you send a note to the list as well? Really excited!

**Comment by jlewi** [comment]
Any thought about how we might integrate this into one of our examples in kubeflow/examples?

If possible it would be great to incorporate this into the GitHub issue summarization/label prediction example so that we can have a rich example illustrating many different facets of Kubeflow.

/cc @lluunn @cliveseldon

**Comment by aronchick** [comment]
Big +1 on starting with an example, and using that to make tangible any upstream changes you need in Kubeflow.

**Comment by cfregly** [comment]
@jlewi and @aronchick sounds good re: summarization/label prediction example.  that's a good place to start.

hoping to get this working this week for kubecon.  

(btw, i have 6 (?!) other commitments this week in NYC, BOS, and DC, so i can't make KubeCon CPH. 
 but i'll see you guys back on the left coast soon.

**Comment by cfregly** [comment]
@jlewi we'd like to get this in for the next release (0.3?  0.4??).  i'll try to call into the next kubeflow weekly meeting to discuss.  it's coming!

**Comment by jlewi** [comment]
@cfregly that sounds great; Adding this to our backlog.

0.3.0 will be EOQ3. So it should be code complete by mid September.

/assign @cfregly

**Comment by jlewi** [comment]
@cfregly any update on what you want to contribute for 0.3.0?

**Comment by jlewi** [comment]
Removing from 0.3.0.

**Comment by kaiwaehner** [comment]
Looks like this one was not contributed yet, right?
As soon as there is a working example with Kafka, I am happy to contribute some stuff like improved docs, blog post or demo video of this combination. 
But as coding is not my daily job, it is too hard for me to build such an example by myself, unfortunately.

**Comment by carmine** [comment]
Any update on this integration?
