### ISSUE TITLE
kfctl v1.3.0 link broken for kubeflow deployment on Azure

### ISSUE THREAD

**Issue by kruthikakr** [kubeflow/kubeflow#6078]
/kind question

    kubeflow setup on azure using the link https://www.kubeflow.org/docs/distributions/azure/deploy/install-kubeflow/
    the link is broken for v1.3 : Download the kfctl v1.3.0 release from the Kubeflow releases page.
    so have installed the available https://github.com/kubeflow/kfctl/releases

I need to use kfserving with torchserve which needs kubeflow 1.3 on azure. What i should do for this to work ?

**Comment by jbottum** [comment]
@aronchick, fyi

**Comment by kruthikakr** [comment]
any help regarding this ?
