### ISSUE TITLE
Can't setup kubeflow into custom VPC network

### ISSUE THREAD

**Issue by AndreyRomanchev** [kubeflow/kubeflow#6079]
/kind bug

**What steps did you take and what happened:**
I've setup management cluster and trying to setup kubeflow.
Before make apply I've set
```
kpt cfg set -R . gcloud.compute.network backbone
kpt cfg set -R . gcloud.compute.subnetwork kubeflow-gke-production-us-central1
```
These are valid network and subnetwork from our environment.

And after describe of containerclusters I got
```
kubectl describe containerclusters -n company-infrastructure kubeflow

  Warning  UpdateFailed  11m (x19 over 33m)  containercluster-controller  Update call failed: error applying desired state: summary: googleapi: Error 400: Project "company-infrastructure" has no network named "default"., badRequest, detail:
```

There are no default networks in our GCP projects.
How to install kubeflow to specific VPC network?

**Environment:**

- Kubeflow version: latest 1.3.1
- kpt version: 0.39.2
- Kubernetes platform: GKE
- Kubernetes version: v1.20.8-gke.900

**Comment by AndreyRomanchev** [comment]
Btw, I was able to install kubeflow by creating ComputeNetwork and ComputeSubnetwork reflecting those in our VPC.
Samples found here https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/samples/resources/containercluster/vpc-native-container-cluster

and adding 
```
  networkRef:
    name: backbone
  subnetworkRef:
    name: kubeflow-gke-production-us-central1
```
to gcp-blueprints/kubeflow/common/cluster/upstream/cluster.yaml

**Comment by jbottum** [comment]
@AndreyRomanchev did you get this resolved?

**Comment by AndreyRomanchev** [comment]
@jbottum I think so.
