### ISSUE TITLE
Nested menu - "Sorry, /<endpoint>/ is not a valid page"

### ISSUE THREAD

**Issue by matkosoric** [kubeflow/kubeflow#6080]
Central dashboard menu is displayed as nested or recursive menu, three levels deep, showing message similar to:
Sorry, /jupyter/ is not a valid page
Sorry, /volumes/ is not a valid page
Sorry, /tensorboards/ is not a valid page
etc.

![image](https://user-images.githubusercontent.com/24875759/128849797-6080ca54-15a1-4b29-9093-a058e05c8563.png)

If you do not select the same component, then it is only two levels deep.

Similar - closed - issue is:
https://github.com/kubeflow/kubeflow/issues/3615

**Environment:**

- Kubeflow version: 1.3
- Kubernetes platform: AWS EKS
- Kubernetes version: 1.20

**Comment by jbottum** [comment]
@matkosoric does it act this way every time?   did you try to pick a namespace?   which installation pattern/process did you use (...we might have to look at the manifests and kustomize commands) ? @kubeflow/wg-notebooks-leads

**Comment by matkosoric** [comment]
@jbottum Selecting namespace does not make a difference:
![image](https://user-images.githubusercontent.com/24875759/129340724-eadaf980-40ed-4f42-9cf8-e882e123118d.png)

**Comment by matkosoric** [comment]
@jbottum Not sure how much I can share from other parts of the project, but dashboard yml looks something like this:

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: xxxxxxxxxxx
    targetRevision: xxxxxxxxxxxx
    path: distribution/kubeflow/central-dashboard/base
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

**Comment by matkosoric** [comment]
Also, this is similar issue:
[Kubeflow 1.3 bugs on Openshift 4.6 #1895](https://github.com/kubeflow/manifests/issues/1895)

**Comment by matkosoric** [comment]
It seems that problem is in port-forwarding:
[Link](https://github.com/kubeflow/kubeflow/issues/3615#issuecomment-633822241)

**Comment by matkosoric** [comment]
Update: I was able to get nested menu again, this time without port-forwarding and only for MLFlow component:
![image](https://user-images.githubusercontent.com/24875759/130039479-cc0a08b4-fc1c-4f5d-8024-c40566ce7ebf.png)

**Comment by SharpEdgeMarshall** [comment]
Same issue here on `Notebooks`
