### ISSUE TITLE
Kubeflow Doc Sprint- proposed for Sept 14 after Community Meeting

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#6097]
/kind feature

**Why you need this feature:**
We would like to get user input on the Kubeflow docs and improve them for the 1.4 release.

**Describe the solution you'd like:**
We should consider a multi-hour virtual call where contributors can present new docs and users can provide feedback.    We are proposing this will be help on Sept 14.

**Anything else you would like to add:**
We would like user participation and would appreciate their contribution to Kubeflow docs.    Users would contribute will be candidates for Kubeflow swag including the Kubeflow Contributor T-Shirt.

@kubeflow/wg-manifests-leads @RFMVasconcelos @mkbhanda @james-jwu    - Should we schedule the doc sprint as an extension of the Kubeflow Community Meeting on 1.4 i.e. we will do a quick status of 1.4 and then go into the doc sprint...opinions ?

**Comment by RFMVasconcelos** [comment]
@jbottum thank you for this proposal! 

I agree with Sept 14th and the format of doing this right after the community meeting :rocket:

**Comment by jbottum** [comment]
@shannonbradshaw will Sept 14 work?  @RFMVasconcelos I am thinking of issuing a goal / challenge to users to help with at least 1 PR on the docs, and maybe have their PR ready by Sept 14.    Do you think that might help ?
