### ISSUE TITLE
500 error when accessing the notebook servers web UI

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/kubeflow#6102]
/kind bug

**What steps did you take and what happened:**
Sometimes when i press on the notebooks server web UI i get an error in a box at the end of the page "500 error". 

**What did you expect to happen:**
I did not expect this error to occur

**Anything else you would like to add:**

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.3.1
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) Azure
- Kubernetes version: (use `kubectl version`): 1.20.5
- OS (e.g. from `/etc/os-release`):

**Comment by Hmr-ramzi** [comment]
![image](https://user-images.githubusercontent.com/11632681/130414511-d6750593-dccc-4714-b239-628ac468b152.png)

**Comment by Hmr-ramzi** [comment]
![image](https://user-images.githubusercontent.com/11632681/130415550-b10ef44b-a34e-4c2f-8688-a17c1d1fa42f.png)

**Comment by jbottum** [comment]
@Hmr-ramzi did you get this resolved?

**Comment by Hmr-ramzi** [comment]
Hi, no not yet. It is working but happens each sessions 3 times or something. Looks like it is a timeout issue between the central dashboard and the other components. Any way to configure this ?

**Comment by anishjain18** [comment]
Hey @Hmr-ramzi have you found any workarounds for this issue?
