### ISSUE TITLE
Azure OIDC error

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/kubeflow#6119]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am following OIDC setup of Kubeflow on azure (https://www.kubeflow.org/docs/distributions/azure/authentication-oidc/) , I have successfully reached till last stage but :
```
Add the redirect URI below to the app registered with Microsoft Identity:

https://<YOUR_LOADBALANCER_IP_ADDRESS_OR_DNS_NAME>/login/oidc
```
After this step I get error from authservice pod:
```
2021/09/04 15:35:09 http: panic serving 10.244.0.47:47852: interface conversion: interface {} is nil, not string
```
and I cannot visualize Kubeflow dashboard, how can i solve this ?

**Comment by jbottum** [comment]
@ajinkya933 did you get this resolved ?

/platform azure

**Comment by ajinkya933** [comment]
@jbottum no, I am stuck.

**Comment by ajinkya933** [comment]
Resolved this one

**Comment by yves-altaml** [comment]
> Resolved this one
 @ajinkya933 I am facing the same issue how did you solve it?
