### ISSUE TITLE
Add Link to Intel's tutorial

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#612]
Intel just published a Tutorial
https://ai.intel.com/lets-flow-within-kubeflow/

We should add a link in our Docs to it because its a good guide for people wanting to understand how to use TFJob better.

**Comment by inc0** [comment]
@raddaoui wanna do the honors?:) Since it's your writing! Alternative would be to modify it to .md and publish as proper part of docs.

**Comment by kkasravi** [comment]
I think he's on PTO, I can slack him in intel's slack channel.

**Comment by raddaoui** [comment]
Sure. I am on a PTO tomorrow. I will submit a PR on Thursday.
