### ISSUE TITLE
Error during installing Kubeflow on Mac M1

### ISSUE THREAD

**Issue by MLHafizur** [kubeflow/kubeflow#6125]
Trying to install Kubeflow on my Mac M1:

(kube) (base) mdrahman@Mds-MacBook-Pro hello-kf-Darwin % export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml

(kube) (base) mdrahman@Mds-MacBook-Pro hello-kf-Darwin % kfctl apply -V --file=${CONFIG}

Getting following errors:

Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: couldn't create namespace kubeflow Error: Post "https://127.0.0.1:50116/api/v1/namespaces": net/http: TLS handshake timeout
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: couldn't create namespace kubeflow Error: Post "https://127.0.0.1:50116/api/v1/namespaces": net/http: TLS handshake timeout

Seeking for you help.
<img width="1439" alt="Screen Shot 2021-09-08 at 9 34 06 AM" src="https://user-images.githubusercontent.com/45520794/132520118-165ddb48-106d-42ef-8aed-f6479fb4e271.png">
<img width="1433" alt="Screen Shot 2021-09-08 at 9 34 35 AM" src="https://user-images.githubusercontent.com/45520794/132520136-12775601-7a4f-4c29-ad6d-acefd6b411b3.png">

**Comment by 24king** [comment]
finally success?
