### ISSUE TITLE
Error while accessing the notebooks section on kubeflow dashboard

### ISSUE THREAD

**Issue by anishjain18** [kubeflow/kubeflow#6141]
I am having trouble while trying to access notebooks in kubeflow dashboard.
**kubernetes version:**
microk8s           v1.21.4             2407   1.21/stable      canonical✓  classic
**kubeflow version: v1.3**
I installed it on a local machine Ubuntu 20.04.3 LTS.
Following is the error I am getting while trying to open notebooks section:

{
  "log": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
  "status": 404, 
  "success": false, 
  "user": "admin"
}
Here is the attached snip of the dashboard:
![kf dashboard](https://user-images.githubusercontent.com/82514333/133558749-a5d9a878-856d-461f-9e04-d3d86a91ce07.PNG)
All pods are running fine.
Please suggest some workarounds for this error.

**Comment by leeadh** [comment]
im facing the same issue.

**Comment by stalamoni** [comment]
me too. i am having same issue.

**Comment by stalamoni** [comment]
Hi, found a solution thanks to this article: 
https://github.com/alexanderciuffreda/mlops/issues/4

steps to solve this issues:
microk8s.juju remove-application jupyter-ui
microk8s.juju deploy jupyter-ui
microk8s.juju relate jupyter-ui istio-pilot
