### ISSUE TITLE
ksonnet + openshift unauthorized error when deploying app

### ISSUE THREAD

**Issue by fxue** [kubeflow/kubeflow#615]
trying to deploy kubeflow ksonnet app on openshift
```
➜  ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
```
```
➜ oc version
oc v3.9.7
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://api.starter-us-west-1.openshift.com:443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657
```

updated the app.yaml file as suggested in #521 to
```
k8sVersion: v1.9.1
```
now getting Unauthorized error
```
➜  my-kubeflow ks apply ${KF_ENV} -c kubeflow-core

INFO  Updating configmap kubeflow.jupyterhub-config
ERROR Unauthorized
```

cc: @pdmack any setup im missing with OS?

**Comment by fxue** [comment]
trying 
```
oc adm policy add-scc-to-user anyuid -z ambassador
oc adm policy add-scc-to-user anyuid -z jupyter-hub

```

**Comment by pdmack** [comment]
@fxue unfortunately you won't be able to deploy Kubeflow in Online as a developer. It has RBAC enabled and you would need to be "system:admin".

**Comment by fxue** [comment]
thanks @pdmack. Indeed, this is the error I am getting. 
Since I work at Google cloud so looking for the best way to do a fully managed service or do a GCP deployment. Talking to the partner team on my side Monday on how best to proceed forward.
```
➜  my-kubeflow oc adm policy add-scc-to-user anyuid -z ambassador
oc adm policy add-scc-to-user anyuid -z jupyter-hub

Error from server (Forbidden): securitycontextconstraints.security.openshift.io "anyuid" is forbidden: User "***@***.com" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: User "***@***.com" cannot get securitycontextconstraints.security.openshift.io at the cluster scope
Error from server (Forbidden): securitycontextconstraints.security.openshift.io "anyuid" is forbidden: User "***@***.com" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: User "***@***.com" cannot get securitycontextconstraints.security.openshift.io at the cluster scope
```

**Comment by jayunit100** [comment]
Some quick thoughts, new to this but i think underlying need to separate these namespaces if possible for security in the future... and for more composable installation to @pdmack 's point.

### for now
The simple fix on an openshift cluster would be to give cluster admin to your current user, from ambassadors docs , similar in kube.

*kubectl*:  `kubectl create clusterrolebinding my-cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud info --format="value(config.account)")`, and for openshift, thats probably equivalent to 

*openshift* something like `oc adm policy add-cluster-role-to-user cluster-admin user --rolebinding-name=cluster-admin`... right?
 
### future ?
- The fix, i think , would be to decouple ambassador and jupyter-hub installations as separate components from kubeflow, From there
- come up w/ ways to apply PLP to the core kubeflow pods, and keep cluster-admin for those 2 and then
- let people independently come up w/ policies on how they want to install jupyter and ambassador, and just gate on those svc's being available.
