### ISSUE TITLE
Kubeflow 1.2.0 install failed on AWS EKS cluster (kfctl_aws.v1.2.0.yaml) 

### ISSUE THREAD

**Issue by yike5460** [kubeflow/kubeflow#6151]
/kind bug

**What steps did you take and what happened:**
Error prompt when I execute "kfctl apply -V -f kfctl_aws.v1.2.0.yaml"
```
INFO[0000] ManagedCluster set defaulting to false        filename="aws/aws.go:624"
INFO[0000] EnableNodeGroupLog set defaulting to false    filename="aws/aws.go:634"
INFO[0000] You already have cluster setup. Skip creating new eks cluster.   filename="aws/eks.go:95"
INFO[0000] Creating namespace: kubeflow                  filename="aws/k8sClient.go:53"
INFO[0001] Creating namespace: istio-system              filename="aws/k8sClient.go:53"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: IAM for Service Account is not supported on non-EKS cluster <nil>
```

Snippet of kfctl_aws.v1.2.0.yaml
```
  plugins:
  - kind: KfAwsPlugin
    metadata:
      creationTimestamp: null
      name: aws
    spec:
      auth:
        basicAuth:
          password: xx
          username: xx
      enablePodIamPolicy: true
      region: cn-north-1
```

EKS cluster working fine
```
[root@ip-172-31-17-136 workout]# pwd
/home/ec2-user/kubeflow_demo/workout

[root@ip-172-31-17-136 workout]# eksctl get cluster --name workout --region cn-north-1
2021-09-24 03:33:06 [ℹ]  eksctl version 0.67.0
2021-09-24 03:33:06 [ℹ]  using region cn-north-1
NAME    VERSION STATUS  CREATED                 VPC                     SUBNETS                                                    SECURITYGROUPS           PROVIDER
workout 1.20    ACTIVE  2021-08-05T07:13:55Z    vpc-xxxx   subnet-xxxx,subnet-xxxx,subnet-xxxx,subnet-xxxx sg-xxxx    EKS

[root@ip-172-31-17-136 workout]# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   49d

[root@ip-172-31-17-136 workout]# export AWS_CLUSTER_NAME=workout
```

**What did you expect to happen:**
Kubeflow process can continue without error

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Kubeflow version: 1.2

[root@ip-172-31-17-136 workout]# kfctl version
kfctl v1.2.0-0-gbc038f9

[root@ip-172-31-17-136 workout]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

[root@ip-172-31-17-136 workout]# uname -a
Linux ip-172-31-17-136.cn-north-1.compute.internal 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by itshevtsov** [comment]
Hey! I have the same issue with Kubeflow 1.2 and EKS cluster (ver. 1.21)

`INFO[0001] ManagedCluster set defaulting to false        filename="aws/aws.go:624"
INFO[0001] EnableNodeGroupLog set defaulting to false    filename="aws/aws.go:634"
INFO[0001] You already have cluster setup. Skip creating new eks cluster.   filename="aws/eks.go:95"
INFO[0002] Namespace kubeflow already exists...          filename="aws/k8sClient.go:50"
INFO[0002] Namespace istio-system already exists...      filename="aws/k8sClient.go:50"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: IAM for Service Account is not supported on non-EKS cluster <nil>
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                         		export CONFIG=./kfctl_gcp_iap.yaml
                         	or a URL:
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml
                         		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml
                         	kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: IAM for Service Account is not supported on non-EKS cluster <nil>%`
