### ISSUE TITLE
When opening a notebook 503 Error and white screen 

### ISSUE THREAD

**Issue by svz77** [kubeflow/kubeflow#6156]
/kind bug

When opening a notebook, 503 errors occur. All subferences are launched, there are no errors in the logs. I tried 3 different versions of kubeflow - 1.3, 1.3.1, 1.4rc2. 

Help me please. I do not know what to do.

**What did you expect to happen:**

I expected the launch of Jupiter notebook

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:  1.3, 1.3.1, 1.4 (rc2)
- kfctl version: (use `kfctl version`): "v1.19.7
- Kubernetes platform: (e.g. `minikube`) kubernetes kubespray
- Kubernetes version: (use `kubectl version`): "v1.19.7
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

<img width="1673" alt="Снимок экрана 2021-09-27 в 9 07 28 AM" src="https://user-images.githubusercontent.com/91451571/134856315-cf57d154-88d5-4bd0-a4e4-a2d5bc50e123.png">
<img width="1677" alt="Снимок экрана 2021-09-27 в 9 07 40 AM" src="https://user-images.githubusercontent.com/91451571/134856328-304935ef-c9a6-48a9-bccf-d87c7e6b9320.png">
<img width="1678" alt="Снимок экрана 2021-09-27 в 9 09 21 AM" src="https://user-images.githubusercontent.com/91451571/134856339-1ca2a578-3b05-47fb-bd68-1ce1fb245753.png">

**Comment by svz77** [comment]
I also changed the name of the cluster from all pipelines 

cluster.local > ml.prod.kube.oxy

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads priority /p2

**Comment by kimwnasptd** [comment]
@svz77 some initial questions I have:
1. How are you accessing your cluster? Are you port-forwarding the istioingress-gateway Service?
2. Could you show some more information for the above 503 request? I want to understand who returns 503
3. If you check the logs of your Notebook, can you see a log entry for this request?
