### ISSUE TITLE
no healthy upstream error when connect to notebook server

### ISSUE THREAD

**Issue by persistman** [kubeflow/kubeflow#6162]
kfctl version: 1.1.0
k8s version: 1.6.9
notebook image: gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v0.2.1

kubectl describe pod ${POD-NAME} -N ${NAMESPACE}
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        40m                    default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
  Warning  FailedScheduling        40m                    default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
  Normal   Scheduled               40m                    default-scheduler        Successfully assigned anonymous/test-nb-01-0 to ap-southeast-5.172.22.65.175
  Normal   SuccessfulAttachVolume  40m                    attachdetach-controller  AttachVolume.Attach succeeded for volume "d-k1a3feb69isa2y9bjf10"
  Normal   Pulled                  40m                    kubelet                  Container image "docker.io/istio/proxy_init:1.1.6" already present on machine
  Normal   Created                 40m                    kubelet                  Created container istio-init
  Normal   Started                 40m                    kubelet                  Started container istio-init
  Normal   Pulling                 40m                    kubelet                  Pulling image "gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v0.2.1"
  Normal   Pulled                  38m                    kubelet                  Successfully pulled image "gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v0.2.1"
  Normal   Pulled                  37m                    kubelet                  Container image "docker.io/istio/proxyv2:1.1.6" already present on machine
  Normal   Created                 37m                    kubelet                  Created container istio-proxy
  Normal   Started                 37m                    kubelet                  Started container istio-proxy
  Warning  Unhealthy               37m (x2 over 37m)      kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Started                 37m (x3 over 37m)      kubelet                  Started container test-nb-01
  Normal   Pulled                  37m (x3 over 37m)      kubelet                  Container image "gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v0.2.1" already present on machine
  Normal   Created                 37m (x4 over 37m)      kubelet                  Created container test-nb-01
  Warning  BackOff                 5m10s (x153 over 37m)  kubelet                  Back-off restarting failed container 

kubectl edit pod ${POD-NAME} -N ${NAMESPACE}
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T02:34:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T03:03:08Z"
    message: 'containers with unready status: [test-nb-01]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T03:03:08Z"
    message: 'containers with unready status: [test-nb-01]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T02:34:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6508ca843c326facf54e08084cb159df47ea0ac91c51d6c6e1504a38f4d315d5
    image: istio/proxyv2:1.1.6
    imageID: docker-pullable://istio/proxyv2@sha256:e7ee1ad38bd5b556ad0527ac691a9f647b66835960417b154c5d28b2ed9219cb
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-29T02:36:39Z"
  - containerID: docker://6f8ead431a755ab0b846967bd18e59ad787a9eb38d063ce0e45de2d4673c8cfc
    image: gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v0.2.1
    imageID: docker-pullable://gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu@sha256:ff71fc8c4581daa174cfcb2242499c7dd9b64bbe5740a9009e0549960507f728
    lastState:
      terminated:
        containerID: docker://6f8ead431a755ab0b846967bd18e59ad787a9eb38d063ce0e45de2d4673c8cfc
        exitCode: 1
        finishedAt: "2021-09-29T03:03:07Z"
        reason: Error
        startedAt: "2021-09-29T03:03:06Z"
    name: test-nb-01
    ready: false
    restartCount: 10
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=test-nb-01 pod=test-nb-01-0_anonymous(53f3de14-a054-4d39-a7a4-caa986c77ca1)
        reason: CrashLoopBackOff
  hostIP: 172.22.65.175
  initContainerStatuses:
  - containerID: docker://eef65f20840145be158ed54e50ccdbe33582fa7f8af76f631c2c2f10509d9509
    image: istio/proxy_init:1.1.6
    imageID: docker-pullable://istio/proxy_init@sha256:54d89fb2b3b0a2365f2d2b0a8862f1f8320a63ab6a09c637c60f13f6021c4609
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://eef65f20840145be158ed54e50ccdbe33582fa7f8af76f631c2c2f10509d9509
        exitCode: 0
        finishedAt: "2021-09-29T02:34:24Z"
        reason: Completed
        startedAt: "2021-09-29T02:34:24Z"
  phase: Running
  podIP: 10.244.1.40
  podIPs:
  - ip: 10.244.1.40
  qosClass: Burstable
  startTime: "2021-09-29T02:34:11Z"

**Comment by persistman** [comment]
![image](https://user-images.githubusercontent.com/22680996/135197315-7b843957-d0f0-4cbb-a320-0dd25d624afc.png)


open the link http://${IP}:8080/notebook/{NAMESPACE}/test-nb-01/   show me:
![image](https://user-images.githubusercontent.com/22680996/135197482-1992b54e-63c6-49f5-b2fc-4b71ff90d9d4.png)

kubectl get pod -n ${NAMESPACE}
![image](https://user-images.githubusercontent.com/22680996/135197696-3440220b-eb10-49f9-8a22-6f33c9514d41.png)

i don't know why and how to sovle it, pls help

**Comment by nanduri1998** [comment]
Where are you exactly trying to run this? Is your istio active? Can you please paste a output of all your Kubeflow related pods and what is the version of Kubeflow you are using?

**Comment by dhanisahu** [comment]
Hi @nanduri1998 @persistman do you get the solution for this error i am also getting this error when i am connecting the jupyterlab notebook. in my case pods are working fine no error in pod but 503 error in istio ingress pod

istio ingress log
[2022-07-20T07:23:41.657Z] "GET /notebook/kubeflow-user-example-com/test-nb-9/ HTTP/1.1" **503 UF,URX upstream_reset_before_response_started{connection_failure}** - "-" 0 91 30048 -

please let me know if you are able to solve the problem

error while opening the notebook: upstream connect error or disconnect/reset before headers. reset reason: connection failure
