### ISSUE TITLE
Survey of why and how people are using minikube with Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#619]
I think it would be worth it to conduct a survey (e.g. using Google Forms) to get some idea of how and why people are using minikube. Here are some initial questions that come to mind.

1. Are you using or plan on using minikube with Kubeflow?
1. Do you have access to a multi-node non minikube Kubernetes Cluster (e.g. an on prem cluster or via a Cloud Provider)?
1. Do you plan on using minikube to run E2E integration tests?
1. Do you plan on using minikube for model development?
1. Why do you want to use minikube; check all the apply
- Cloud costs money; minikube is free
- I can't use Cloud because of security concerns
- My on prem cluster is not for development

Motivation

I'd like to understand better how people intend to use minikube with Kubeflow so we can figure out how to invest. If users are planning on doing model development then certain aspects e.g. GPUs and TFJob logs might be more important then if they are using it primarily for E2E testing of production systems.

/cc @dlorenc

**Comment by bhack** [comment]
It could be interesting to know how they will map dev/prod process when they don't have the same hardware or data resources (minikube vs cloud). 
Also minikube is landing in Docker via edge https://medium.com/coryodaniel/newbernetes-getting-started-b1991e42900c
