### ISSUE TITLE
how to debug the process

### ISSUE THREAD

**Issue by jyu1982** [kubeflow/kubeflow#6201]
/kind question

**Question:**
[You can ask any question about this project.]

hi! all, I am new to this project, and I am currently having trouble to run this minikf project, my env is as follow:
hardware:
6 core, 20 gb of memory

Platform: windows 10, virtual box 6.1

right now I have all different issues when I run into project, I don't know where to start, but can somebody give me some ideas?

right now the big issue I encounter is that, when I run 10.10.10.10, it just keep loading, without any other message

so how can I trouble shoot that? I am okay to provide more detail for it. or if this is right channel?

**Comment by jbottum** [comment]
@jyu1982 did you get this resolved?  Have you tried MiniKF on AWS or GCP ?  (troubleshooting/configuration is much easier there).
