### ISSUE TITLE
Show GPU availability on Jupyter web-app

### ISSUE THREAD

**Issue by d-gol** [kubeflow/kubeflow#6217]
/kind feature

**Why you need this feature:**

Hello all, thanks for the great work on Kubeflow! An idea about notebook servers.

We run our cluster on-prem, with local GPU nodes. On the notebook creation page, we would like to expose information to users if there are available GPUs. Available meaning the GPUs exist in the cluster, and are currently not used by any pods. With that, users would know if they can create a notebook server with a GPU, or they can only use a CPU.

**Describe the solution you'd like:**

For the frontend, we could add a label showing Yes or No, depending on GPU availability. 
Then potentially block selecting GPUs if none is available, or disable the `LAUNCH` button if no GPUs are available and one is selected.

For the backend, jupyter-web-app would run a `kubectl` command which would check the GPU availability. It could run this command in a loop, every _x_ seconds. It might require some additional role-bindings for accessing nodes.

**Anything else you would like to add:**

We have a prototype implementation downstream, we could adjust it according to conclusions from here and then contribute.

Is this something that would be useful to others?

**Comment by kimwnasptd** [comment]
Thank you for the kind words and detailed explanation @d-gol!

One first thought, around the form blocking users from creating a Notebook based on the current cluster resources, is that this could not work well with dynamic node groups. Someone for example could be creating new GPU node group once a Pod requested them, and scale it down once no Pods ask for GPUs. This is also the main reason I'd like to remove the 

My immediate thought would be to try and follow K8s' pattern, which is to 
1. allow users to create the Notebook/Pod even if the cluster doesn't have the required resources
2. be super explicit and make it clear if the Notebook fails to start, because of insufficient resources

**Comment by kimwnasptd** [comment]
And some more technical questions from the proposed feature

> Then potentially block selecting GPUs if none is available, or disable the LAUNCH button if no GPUs are available and one is selected.

How do you propose to make the backend know if GPUs are available, at a specific point in time?

**Comment by d-gol** [comment]
Hi @kimwnasptd, thank you for your reply and detailed proposals!

Agreed, for the dynamic node groups and auto-scaling, adding info about available GPUs is not necessary. Blocking GPU selection if there are no GPUs in the cluster might be implemented to be configurable, true or false, with an ENV to be defined in manifests. Blocking can still be useful for on-premise clusters, with static nodes, as opposed to auto-scaling clusters. 

> be super explicit and make it clear if the Notebook fails to start, because of insufficient resources

I like the idea to provide explicit messages about insufficient resources. Users would appreciate knowing exactly why notebook creation failed, which would in addition reduce the load on admins explaining and providing FAQs.

>How do you propose to make the backend know if GPUs are available, at a specific point in time?

For the implementation, the backend would query the nodes and check if pods could be allocated. For example, this function (with additional role bindings) implemented by @jasonpraful does that:

```
def get_available_gpu_nodes():
    nodes = v1_core.list_node()
    availableGpus = 0
    for node in nodes.items:
        try:
            availableGpus += int(node.status.allocatable['nvidia.com/gpu'])
        except KeyError as e:
            continue
    availableGpus = True if availableGpus > 0 else False
    return availableGpus
   ```

More details on our custom test setup here: https://github.com/d-gol/kubeflow/commit/2b48421f54bb58cce079b8353f0ded4ec5f9ba94, and kudos to @jasonpraful for providing the complete implementation :)
