### ISSUE TITLE
RBAC: access denied

### ISSUE THREAD

**Issue by sfc-gh-adlee** [kubeflow/kubeflow#6220]
/kind bug

**What steps did you take and what happened:**
Deployed K3s
multipass launch --name K3s --mem 16G --disk 50G --cpus 4
multipass shell K3s
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.20.8+k3s1" INSTALL_K3S_EXEC="server --no-deploy=traefik" K3S_KUBECONFIG_MODE="644" sh -s
kubectl get no
export VERSION=v4.2.0  
export BINARY=yq_linux_amd64  
wget "https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}" -O /usr/bin/yq && chmod +x /usr/bin/yq
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
[ mv kustomize /usr/local/bin
git clone https://github.com/kubeflow/manifests.git
cd manifests
while ! kustomize build example | kubectl apply -f -; do echo “Retrying to apply resources”; sleep 10; done

**What did you expect to happen:**
Can access pipelines. Instead for a RBAC: access denied

**Anything else you would like to add:**
No

**Environment:**
Macbook pro

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version dev_local
- kfctl version: (use `kfctl version`):nil
- Kubernetes platform: (e.g. `minikube`): k3s
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`):

**Comment by sfc-gh-adlee** [comment]
![image](https://user-images.githubusercontent.com/83939151/141822692-22f3b77d-d013-44cf-98e2-31af3d56a755.png)

**Comment by AlanHau** [comment]
I got the same error when deploy kubeflow via manifests, can someone help to let me know how to fix it.
