### ISSUE TITLE
Terminate multiple runs under an experiment from UI

### ISSUE THREAD

**Issue by kavanshukla** [kubeflow/kubeflow#6227]
/kind feature

**Why you need this feature:**
I'm working on a problem which submits N number of runs under an experiment. When it comes to terminating a run from the UI, the only way to terminate is to select a specific run and then terminate it individually. But if there are let's say 100 runs running simultaneously, and when there is a need to terminate multiple runs at the same time, I can only terminate it by selecting them individually one by one and clicking on terminate as many times, which is not ideal.

**Describe the solution you'd like:**
It would be nice and convenient to have a `terminate` option available next to  `archive` and `compare runs` on the UI, so one can select multiple runs through check boxes and terminate them all at once. Adding a screenshot below to exactly point where on the UI, but this option can be available in all the UI views wherever you are able to select multiple runs.
![Screen Shot 2021-11-28 at 5 36 47 PM](https://user-images.githubusercontent.com/22081699/143795834-577216ea-8adc-4886-ade4-0b51c68d0efe.png)

**Comment by jbottum** [comment]
@kubeflow/pipelines please evaluate this request.

**Comment by zijianjoy** [comment]
Hello @kavanshukla , this sounds like a valid request for improving the experience of pipeline runs batch management. Can you create this request under kubeflow/pipelines? https://github.com/kubeflow/pipelines/issues/new/choose
