### ISSUE TITLE
centraldashboard: We should upgrade the main dependencies

### ISSUE THREAD

**Issue by haoxins** [kubeflow/kubeflow#6233]
/kind feature

There are some bugs caused by the outdated dependencies, such as https://github.com/kubeflow/kubeflow/issues/6202
I just advise that we should upgrade the most important dependencies, includes

- [ ] https://github.com/kubeflow/kubeflow/pull/6258
- [x] https://github.com/kubeflow/kubeflow/pull/6210
- [x] https://github.com/kubeflow/kubeflow/pull/6333
- [ ] `Node.js`: from `v12` to `v18`

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads fyi

**Comment by thesuperzapper** [comment]
@haoxins Can I ask you to make a meta-issue for re-working the central-dashboard that links all your Issues/PRs and outlines the steps into phases?

__For example, you might split it like:__
- Phase 1 - Update existing packages
    - ISSUE: https://github.com/kubeflow/kubeflow/issues/6233
       - PR: https://github.com/kubeflow/kubeflow/pull/6237
       - PR: xxx
- Phase 2 - Design new UI
    - ISSUE: xxxx
    - ISSUE: xxxx
- Phase 3 - Decide on new UI framework
    - ISSUE: https://github.com/kubeflow/kubeflow/issues/6238
- Phase 4 - Implement new UI in React/Angular
    - ISSUE: xxxx

----

You might also want to do something similar for the CRUD web apps.

__For example, you might split it like:__
- Phase 1: Update existing packages
   - ISSUE: XXXX
       - PR: https://github.com/kubeflow/kubeflow/pull/6242
- Phase 2: Migrate common code into separate repo (just an idea to help with managing lots of CRUD apps)

**Comment by haoxins** [comment]
1. Good idea, will do this when I'm time free.

2. Who or which group will response for design new UI? Are we really need a new UI?

**Comment by thesuperzapper** [comment]
@haoxins while we could just recreate the old UI, it seems like a waste of a rewrite to not improve things.

We can probably get some users in a Zoom and present some wireframes and take feedback @jbottum do you have capacity to facilitate this?

**Comment by kimwnasptd** [comment]
Before discussing about a rewrite can I have a full list of 
1. issues with the current versions of the CentralDashboard and 
2. Test cases that need to be working in a rewrite?

Also cc @StefanoFioravanzo as the owner of the CentralDashboard

**Comment by thesuperzapper** [comment]
@kimwnasptd I think the primary reason we have no choice but to rewrite the centra- dashboard is that Polymer (the JavaScript framework we use) is no longer maintained, see in [the docs of Polymer](https://polymer-library.polymer-project.org/3.0/docs/release-notes).

___NOTE:__ this was raised by @haoxins in issue: https://github.com/kubeflow/kubeflow/issues/6238_


--- 

Furthermore, there are significant benefits of having all the web-UIs that we maintain coded in the same JavaScript framework, so I think it makes sense to move the central-dashboard to Angular (like our other CRUD web apps).

**Comment by thesuperzapper** [comment]
@kimwnasptd let's keep this issue about updating the __existing__ central-dashboard, and use https://github.com/kubeflow/kubeflow/issues/6238 to discuss rewriting the central-dashboard in angular.

**Comment by haoxins** [comment]
@kimwnasptd agreed.

I'll work on upgrading the existing central dashboard at this moment.

**Comment by kimwnasptd** [comment]
Yep, that's a good distinction. I'll move the relevant comments for the rewrite in #6238 and how we can start organizing the work.

@haoxins the above proposed versions to update makes sense, although we'll need to ensure they also work with the Polymer version that we can use. If not we can also evaluate using a slightly "newer" version of Polymer as well.

**Comment by haoxins** [comment]
> although we'll need to ensure they also work with the Polymer version that we can use. 

I think that upgrading the `node.js`, `@google-cloud/monitoring`, and `@kubernetes/client-node` will 
have no effect on `Polymer`, they are only `node.js` server side.

But upgrade these deps will fix some problems I met in my cluster with a small probability. 
see https://github.com/kubeflow/kubeflow/issues/6202

> If not we can also evaluate using a slightly "newer" version of Polymer as well.

Sure, we can upgrade `Polymer` before we migrate to `Angular`.
And also setup a standard (CI, e2e, feature list, and others) to work as acceptable quality level for the `Polymer` migration.

And I can work on the first part besides the discussion about the second part.

**Comment by haoxins** [comment]
As the release of Node.js 18 https://nodejs.org/en/blog/announcements/v18-release-announce/

```
Also of note is that Node.js 12 will go End-of-Life in April 2022.
```
