### ISSUE TITLE
500 error when accessing the notebook servers web UI and backend connection error

### ISSUE THREAD

**Issue by anishjain18** [kubeflow/kubeflow#6235]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
While trying to run a pipeline the dashboard crashes with an error at bottom '500 error'. Also sometimes there is a backend connection error when trying for hp tuning.

**What did you expect to happen:**
The dashboard shouldn't crash everytime I try to run a pipeline.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Attached are the screenshots of the errors:
![Capture3](https://user-images.githubusercontent.com/82514333/144557681-d416ba2e-8c37-4e20-adee-811fa8a2ff54.PNG)
![Capture4](https://user-images.githubusercontent.com/82514333/144557698-f38490a9-bdc3-44c7-a9b0-e9cf0ee04505.PNG)
Can anyone who has encountered the same issue help with this or any workarounds for this issue.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) MiniKF deploying locally
- Kubernetes version: (use `kubectl version`): 1.22.4
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by jbottum** [comment]
@anishjain18 thanks for this report.   It appears that you are running MiniKF on a desktop/laptop.   Are you sure your machine has enough resources for the workloads?    Have you tried MiniKF on GCP or AWS with larger machines?

**Comment by anishjain18** [comment]
Hi @jbottum, the machine on which Im deploying miniKF is sufficient enough for running miniKF. Can u help regarding this issue Im facing.

**Comment by jbottum** [comment]
@anishjain18 Can you please explain how you found out the K8s version i.e. 1.20.5.   Also, does your machine have 32 GB RAM and what other applications are you running ?   Which operating system are you using (and version).   thanks!

**Comment by anishjain18** [comment]
@jbottum the machine Im using is a high powered machine with 256 gigs of ram running on Ubuntu 20.04 OS. I updated the kubectl version to the current 1.22.4 stable version but the error is still persistent. I deleted some older pipelines to free up the space but that didn't do any good. Can u help to resolve this error.
