### ISSUE TITLE
centraldashboard: We should migrate from the Polymer to other frameworks

### ISSUE THREAD

**Issue by haoxins** [kubeflow/kubeflow#6238]
/kind feature

The [Polymer](https://github.com/Polymer/polymer) has been deprecated, should we migrate the central dashboard to **Angular** or [Lit: Simple. Fast. Web Components.](https://github.com/lit/lit)

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads should this be discussed in NB working group

/area jupyter
/priority p2

**Comment by thesuperzapper** [comment]
@haoxins I am 100% am onboard with migrating off polymer. I think we should move to one of:
- Angular (used in our [crud-web-apps](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/package.json))
- React (used in [Kubeflow Pipelines Frontend](https://github.com/kubeflow/pipelines/blob/master/frontend/package.json))

---

@haoxins if you have time to work on this, I am happy to help plan the implementation and work with @kubeflow/wg-notebooks-leads to get it merged!

**Comment by haoxins** [comment]
> @haoxins if you have time to work on this, I am happy to help plan the implementation and work with @kubeflow/wg-notebooks-leads to get it merged!

Sure, of course~
I'm fine with both Angular or React~

**Comment by thesuperzapper** [comment]
@haoxins any preference, lol?

**Comment by haoxins** [comment]
> @haoxins any preference, lol?

Because the central dashboard sits beside the `crud-web-apps` in the same repository, I prefer `Angular`.

**Comment by haoxins** [comment]
I think we have reached an agreement that we should use Angular for the central dashboard.
So I closed this issue and created #6332 to track the progression.

**Comment by sanjshrestha** [comment]
> @haoxins I am 100% am onboard with migrating off polymer. I think we should move to one of:
> 
> * Angular (used in our [crud-web-apps](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/package.json))
> * React (used in [Kubeflow Pipelines Frontend](https://github.com/kubeflow/pipelines/blob/master/frontend/package.json))
> 
> @haoxins if you have time to work on this, I am happy to help plan the implementation and work with @kubeflow/wg-notebooks-leads to get it merged!

hi is kubeflow front end being converted from polymer to react? if yes how and what's the plan.

**Comment by haoxins** [comment]
> > @haoxins I am 100% am onboard with migrating off polymer. I think we should move to one of:
> > 
> > * Angular (used in our [crud-web-apps](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/package.json))
> > * React (used in [Kubeflow Pipelines Frontend](https://github.com/kubeflow/pipelines/blob/master/frontend/package.json))
> > 
> > @haoxins if you have time to work on this, I am happy to help plan the implementation and work with @kubeflow/wg-notebooks-leads to get it merged!
> 
> hi is kubeflow front end being converted from polymer to react? if yes how and what's the plan.

The central dashboard still is Polymer.

I closed this issue because I'm not working on frontend any more.
So that I can't contribute to this in the future.
