### ISSUE TITLE
How to keep python packages in notebooks after stopping

### ISSUE THREAD

**Issue by BenzhaminKim** [kubeflow/kubeflow#6244]
/kind question

**Question:**
I installed Python Libraries using 'pip install <package name>' in a notebook server.
It is all fine if I do keep running the notebook server.
However, when I stop the notebook server and restart it, the packages I installed on the server were all deleted. 

I think the packages were deleted because the notebook server container is deleted when I stop the notebook, 
so the container can't keep the packages that were installed outside of PV like root folder or /var etc.

Notebook server only can keep the things that are inside in PV. 

Thus, is there any way to keep packages that I newly install in a notebook server?

Expectation:
1. Install packages on a notebook server.
2. stop the notebook server.
3. start the notebook server.
*4. Packages that I installed still exist.

**Comment by kimwnasptd** [comment]
@BenzhaminKim that's a good question. We should also expose more documentation around start/stopping notebooks and implications it can have on user data.

On this question you could use a PVC on the home directory of the notebook and install packages using `pip install --user`. Another approach would be to include all the necessary packages in the container image, but this means you will lose things on reboots.
