### ISSUE TITLE
Absolute Path Error (No Such File or Directory) During kfctl apply (AWS)

### ISSUE THREAD

**Issue by stevebanik** [kubeflow/kubeflow#6245]
/kind bug

Getting this error:
21/12/14 10:16:14 absolute path error in '/Users/user1/Downloads/client/aws/kubeflow-demo-4/kubeflow-demo-4/.cache/manifests/manifests-1.2.0/namespaces/base' : evalsymlink failure on '/Users/user1/Downloads/client/aws/kubeflow-demo-4/kubeflow-demo-4/.cache/manifests/manifests-1.2.0/namespaces/base' : lstat /Users/user1/Downloads/client/aws/kubeflow-demo-4/kubeflow-demo-4: no such file or directory

when I run this command:
./kfctl apply -V -f kfctl_aws.yaml

contents of kfctl_aws.yaml:
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kubeflow-demo-4
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: istio/istio/base
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/oidc-authservice
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/dex-auth
    name: dex
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: spark/spark-operator/overlays/application
    name: spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: aws/istio-ingress/base_v3
    name: istio-ingress
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/spartakus
    name: spartakus
  plugins:
  - kind: KfAwsPlugin
    metadata:
      creationTimestamp: null
      name: aws
    spec:
      auth:
        basicAuth:
          password: 1234
          username: admin@kubeflow.org
      enablePodIamPolicy: true
      region: us-west-2
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-1.2.0"'
    name: manifests

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
can't access dashboard
- kfctl version: (use `kfctl version`):
kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`)
no minikube
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
- OS (e.g. from `/etc/os-release`):
macOS 11.6.1

**Comment by vinaykumargudi** [comment]
@stevebanik  Please,make sure your using same kfctl and kfctl_aws.yaml versions.
anyway kubeflow might not work correctly on eks version 1.21 as there are other issues on this. 

I personally faced this issue- 
https://github.com/kubeflow/kubeflow/issues/6151

There official docs also mention that kubeflow  only supports up-to eks version 1.19 which gets deprecated by April 2022, 
Hope so, they extend support by then.. 
https://www.kubeflow.org/docs/distributions/aws/deploy/eks-compatibility/
