### ISSUE TITLE
Change tensorflow image

### ISSUE THREAD

**Issue by jpic** [kubeflow/kubeflow#6256]
/kind feature

Hi,

Currently, tensorflow/tensorflow image is hardcoded:

https://github.com/kubeflow/kubeflow/blob/master/components/tensorboard-controller/controllers/tensorboard_controller.go#L252

Feature request: allow override of the image specifier with an environment variable.

**Comment by jbottum** [comment]
/kind feature
/area jupyter
/priority p2

@jpic did you get this issue resolved ?
