### ISSUE TITLE
Socket hang ups with JupyterHub on minikube

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#626]
I tried running JupyterHub on minikube and connecting via `kubectl port-forward`. I was able to connect to the UI and get the login screen but after that it just hung. JupyterHub logs showed socket errors

```
Logging in to JupyterHub takes a long time.
00:08:37.631 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)
00:08:37.642 - error: [ConfigProxy] 503 POST /hub/login?next=
```

This only happened when running on my Debian based laptop using no driver with minikube. I tried running minikube on GCE with ubuntu and no driver and it ran fine.

I suspect the issue is specific to my laptop. We could try running Kubeflow on minikube on a debian based GCE VM just to confirm its not an issue with Debian.

/cc @dlorenc @r2d4

**Comment by willingc** [comment]
When running on minikube, what were your settings on memory/cpu for TF in the form UI? If running minikube with virtualbox, what is the minimum memory needed in the VM for the TF image to run? Thanks.

**Comment by pdmack** [comment]
I could **not** reproduce this on:
```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
minikube version: v0.25.2
```

Saw lots of other funky behavior leading me to think NodePort might be the preferred option here as opposed to port-forwarding with minikube.

**Comment by jlewi** [comment]
@willingc I think those are the minikube defaults. I think the notebook defaults are in our [spawner file](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub_spawner.py#L55)

Looks like 500m CPU and 1Gi RAM

**Comment by aronchick** [comment]
I'm seeing really weird/irregular errors when I proxy into Kubeflow as well. I've tried port-forwarding and proxy-ing and both are really challenging to get a notebook up and running (I suspect both usually times out - but it's hard to find logs remotely).

I wonder if there's something we can do to make proxying easier?
