### ISSUE TITLE
How to manage namespace in Kubeflow 1.4.1 ,  run demo pipeline can't get mlpipeline-minio-artifact volume

### ISSUE THREAD

**Issue by 631068264** [kubeflow/kubeflow#6265]
/kind bug

**What steps did you take and what happened:**
I follow https://github.com/kubeflow/manifests  v1.4.1  steps to install kubeflow

![image](https://user-images.githubusercontent.com/8144089/147808057-81e47ddf-3e53-4323-9d7d-a233c05465f2.png)

I can't change manager namespace (create or change)
![image](https://user-images.githubusercontent.com/8144089/147808102-4a11793a-e24f-4e58-93ad-75b69dded303.png)

When run demo pipeline, can't get **mlpipeline-minio-artifact volume**, finally I find the pipeline pod create in **kubeflow-user-example-com** namespace but can't find any config-map called **mlpipeline-minio-artifact** in it. I have to clone it from **kubeflow** namespace !!!!
![image](https://user-images.githubusercontent.com/8144089/147808193-f6cc754d-a8f3-4d3a-89a8-625810292c43.png)
![image](https://user-images.githubusercontent.com/8144089/147808716-5e617b05-9068-4d24-ad81-17ab951d348e.png)

**What did you expect to happen:**
How to create an administrator account to manager namespace and other user.
Why I get error run demo pipeline task

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.4.1

- Kubernetes platform: k3s
- Kubernetes version: v1.19.5+k3s2
- OS (e.g. from `/etc/os-release`): CentOS-7

**Comment by jbottum** [comment]
/kind question
/area installation
/priority p2

@631068264 did you get this resolved ?  where are you running Kubeflow i.e. on-prem, AWS, GCP ?

**Comment by 631068264** [comment]
Custom use rancher + k3s  on Centos
