### ISSUE TITLE
Levers to minimize notebook pod disruption

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/kubeflow#6268]
/kind feature

**Why you need this feature:**

We're a heavy user of both KFP and KF Notebooks, both working great but when used in tandem we have some issues with trying to keep notebooks alive. For notebooks we want them to be stable and long lived so long as they are active, the culler does a great job detecting idleness and down-scaling appropriately. With a lot of KFP usage comes a lot of auto-scaling, currently we run notebooks on the same nodes as batch jobs (not sure if this is best practice), once the KFP workflows are done the nodes scale down and then the cluster-autoscaler kicks in to "compact" the nodes and as the notebook pods are a part of a `StatefulSet` it determines it can terminate the pod on node A and move it to node B, not respecting the "idle" state of the notebook. So we're hearing complaints from our Applied Scientists that they were working away and midway through their notebook server dies, we investigate and it's because the node has been down-scaled 😢 

**Describe the solution you'd like:**

If I'm honest I'm not sure 😅  Obviously having a notebook experience that is 100% undisruptable is the best UX from the notebook users perspective, but that'd cause the finance and our K8s upgrade teams a headache to manage and pay for over time so ideally some compromise solution that optimizes for all parties and is configurable enough that we can tweak any sensible defaults as needed.

One thought is to have this behave in a similar way to the culler in that the disruption could occur only if the notebook is detected as being "idle". It'd be great though to also have some mechanism so that if a node rollout needs to occur for a K8s upgrade for instance we could override that somehow for those rare cases where a notebook is both active and really long running (ie. > 7 days without being idle for example).

**Anything else you would like to add:**

We've thought about adding the `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` annotation to stop the downscaling at the cluster-autoscaler level but over time we're foreseeing this causing more problems as we need to rotate nodes for K8s upgrades, also likely cost overrun issues if particularly long running but awkwardly sized notebook pods relative to node sizes remain.

We've also thought about placing notebooks on dedicated nodes, but over time we'd imagine we'd still end up with similar fragmentation issues as the notebook servers our customers operate is reasonably varied in sizing/constraints (ie. GPU, disk etc.).

**Comment by kimwnasptd** [comment]
Hi @alexlatchford, thank you for sharing you experience! With my initial understanding I believe I also can't provide a silver bullet, that won't require some manual intervention as well.

> We've thought about adding the cluster-autoscaler.kubernetes.io/safe-to-evict: "false" annotation to stop the downscaling at the cluster-autoscaler level 

You mean adding the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` annotation to all Notebook Pods right? This was my first thought as well. To tell the auto-scaler to not touch a node, if a Notebook Pod is running. Then it will be up to the culler to stop the Notebook Pods, once they become idle, and allow the autoscaler to then scale down the node.

> One thought is to have this behave in a similar way to the culler in that the disruption could occur only if the notebook is detected as being "idle".

We've worked with @athamark on extending the Notebooks Controller to expose more information about when a Jupyter Notebook was last active, based on kernel activity https://github.com/kubeflow/kubeflow/issues/6270. Just a small heads up, since it could allow custom solutions to use this information and dynamically mark a Notebook as evict-able.

**Comment by alexlatchford** [comment]
Ah yeah that's a good point that with the culler it'd mean the same behavior would be respected out of the box if we added that annotation, didn't think about that thanks for pointing out the obvious!

Maybe let me do some analysis on our end about the frequency of culling. I'm not 100% sure we have a great rate of this as is (I may be wrong) and report back. We've been using `PodDefault` resources to apply other labels/annotations to notebook pods already so this should be easy for us to test out.

I'll leave the issue open to see if anyone else from the community chimes in but I agree it's a really tricky optimization problem, guessing this may be one the stalebot cleans up but good to have it documented 😅

**Comment by ca-scribner** [comment]
Yeah this is really tough as it is so situational.  We want users to be without interruption, but we also don't want to keep near-empty nodes going, etc... And then even with the users being good citizens, sometimes like @alexlatchford mentions there's still a good reason to have a >7 day notebook server going...

Some possible ideas that might help brainstorm something:
* API-initiated evictions send a termination signal `terminationGracePeriodSeconds` ahead of the hard kill - would we be able to do something to catch and pass this to the user?  It wouldn't let them skip it, but that plus a long enough grace period (say a few minutes) would at least let an active user save what they're doing.  Not sure how we could do this though - it might need to come into the running notebook's UI to be effective
* (building on what was already said) Maybe the notebook culling and autoscaling features can work similarly but the scaling edit set `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` based on recent activity (and after X time inactive, change it to `true`).  That would at least prevent someone sitting at their notebook getting interrupted.  But if you're already using the notebook culling it would amount to something similar (maybe you set shorter limits for the evictions than the culling, but still...)
* allowing users to opt in to `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` on a time limited basis? Maybe with a way of renewing?  it at least avoids people using it carelessly, but sounds like a terrible UX chore

I wonder if this has a better solution in pod clustering problem than in kubeflow.  What @alexlatchford describes (where kfp scales things up, notebooks get fit in along the way, then as kfp scales down the notebooks get rescheduled) might be mitigated some by if kfp pods preferentially clustered together and notebook pods clustered together.  That way as notebook jobs are added they'll hopefully go to nodes that are more stable?  I've never done this personally, but it sounds like a [pod topology spread constraint](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) with `whenUnsatisfiable: ScheduleAnyway` (so things try to cluster, but never block when they can't cluster).  It also sounds like it could be a lot of work for little payoff :(

**Comment by alexlatchford** [comment]
> API-initiated evictions send a termination signal terminationGracePeriodSeconds ahead of the hard kill - would we be able to do something to catch and pass this to the user? It wouldn't let them skip it, but that plus a long enough grace period (say a few minutes) would at least let an active user save what they're doing. Not sure how we could do this though - it might need to come into the running notebook's UI to be effective

I'm guessing that'd need an interface in the underlying IDE of choice (mostly `jupyterlab` in our case). I just did a quick search of their issue list and nothing immediately popped up, my guess is we'd want them to override the `SIGTERM` signal handler to have it gracefully handle shutdowns (not sure of the default behavior) so any work could be saved before the process dies. I guess the concern they'd have would be they are unclear what may be running in the kernel at the point of the signal so unlikely to be an easy one to get through their approval process I'd imagine.

> (building on what was already said) Maybe the notebook culling and autoscaling features can work similarly but the scaling edit set "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" based on recent activity (and after X time inactive, change it to true). That would at least prevent someone sitting at their notebook getting interrupted. But if you're already using the notebook culling it would amount to something similar (maybe you set shorter limits for the evictions than the culling, but still...)

Given the current culler behavior when the idle timeout is hit the replicas are downscaled so effectively you get this behavior for free :) This is what we use and it's a lifesaver!

> allowing users to opt in to "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" on a time limited basis? Maybe with a way of renewing? it at least avoids people using it carelessly, but sounds like a terrible UX chore

We do have an experiment running where users can configure their idle timeout effectively. It's an awful idea as they always set it super high and it defeats the point and typically costs us a bunch until we discover it and tell them not to that (we should put an upper bound on it but haven't yet) 😅 

>  That way as notebook jobs are added they'll hopefully go to nodes that are more stable? 

Yeah we've discussed this with our K8s platform team, ultimately the problem of upgrading Kubernetes (and needing to roll the nodes to get new `kubelet` versions & OS patches) is somewhat of a fundamental one. I think as we scale out a little more likely we'll end up with a dedicated node group for notebooks and we'll have longer rollout periods for these upgrades but there is still the threat of needing to roll out a hotfix and having a "nice" solution to handle the interrupt for the user there is still very tricky as it seems quite intractable to me.

**Comment by ca-scribner** [comment]
@alexlatchford I have had similar results with experiments in users setting their own timeouts :) 

I'm curious what are the negative effects of notebook pod disruption that people are reporting in your organisation?  is it mainly that they were working and suddenly it is like someone hit restart on their kernel, or do they also feel the pain of things like their pip and conda installs being removed?  If it is the latter, there's some things you can do to make that little nicer, like adding some default config for pip that installs to a persisted drive rather than in the ephemeral storage.  If that would be helpful I think I can find the details somewhere.

I've wondered if adding a component to Kubeflow that can extend notebooks with conda/pip packages might be neat too.  I'm thinking something like how Metaflow creates/caches conda environments as required.  From the Notebook UI you could says something like "use image `X:y.z`, but with conda environment `conda.yaml`", and it could build (or pull from cache) the conda env for you.  First run would be slow, but future runs would be quickly pulled from cache.  And then users don't need to reinstall packages every time they're rescheduled, or if they pause notebooks, etc

**Comment by juliusvonkohout** [comment]
Similar to the other configmaps i proposed so far there could be

```
                {
                    "apiVersion": "kubeflow.org/v1alpha1",
                    "kind": "PodDefault",
                    "metadata": {
                        "name": "disable-autoscaler",
                        "namespace": namespace
                    },
                    "spec": {
                        "desc": "Disable deletion by autoscaler",
                        "selector": {
                            "matchLabels": {
                                "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
                            }
                        }
                    }
                },
```
in sync.py and the administrator could enable it be default for all jupyterlabs. Since jupyterlabs get shutdown every 12 hours without inactivity in my configuration, nodes can still be drained in the night.

**Comment by juliusvonkohout** [comment]
/close

due to inactivity
