### ISSUE TITLE
Kubeflow on AWS EKS get 401 Authorization Required error

### ISSUE THREAD

**Issue by summerisc** [kubeflow/kubeflow#6273]
/kind bug

**What steps did you take and what happened:**
I am deploying Kubeflow on AWS EKS, for the authorization part, I tried both https://www.kubeflow.org/docs/distributions/aws/authentication/authentication/
and
https://www.kubeflow.org/docs/distributions/aws/authentication/authentication-oidc/
on Cognito or OAuth2 with Github application, both of them after a successful login, direct to the istio-generated URL but give
401 Authorization Required error. What might be wrong with the setup? Do I need to set up more with the istio? Thanks for the help in advance.

**What did you expect to happen:**
A successful login

**Anything else you would like to add:**
It redirects to the istio generated url like `xxxxxxxx-istiosystem-istio-xxxx-xxxxxxx.us-east-1.elb.amazonaws.com` so I assume it passes OAuth step, the other thing is I use a random public certificate as certArn but I think it should also work with ALB.

**Comment by jbottum** [comment]
@summerisc  did you get this resolved?

**Comment by summerisc** [comment]
yeah I did manage to make it work, I suspect it is something to do with the public certificate, but not 100% sure.
