### ISSUE TITLE
User guide sprawl

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#629]
Wondering if its time to break the UG up a bit. Methinks Troubleshooting alone will continue to grow at a good clip. It's becoming more difficult to narrow in through the wall of words.

**Comment by jlewi** [comment]
I agree. 

We are in the process of setting up an actual documentation repository and website see kubeflow/community#21. The repository will be

https://github.com/kubeflow/website

So I expect that all of the information in user_guide.md will eventually migrate to that site or be deleted.

Here's a working [doc](https://docs.google.com/document/d/1XUGnLVCyqVLN62VWqk-o_FLhRU1L4b7VRcwP8QgFst4/edit#heading=h.ivgrr0tnsplu) for the website.

It probably makes more sense to contribute to getting the official docs website up then spending a lot of effort cleaning up the user_guide.

**Comment by pdmack** [comment]
Agreed. Is there a plan for what _remains_ on the kubeflow README? Just redirect?
