### ISSUE TITLE
How to change default password  and create an admin account?

### ISSUE THREAD

**Issue by 631068264** [kubeflow/kubeflow#6291]
/kind question

Can't understand [Change default password](https://github.com/kubeflow/manifests#change-default-user-password)，I don't know how the default hash comes(input same password give me different hash each time, it's very strange), please give more detail example.

**Comment by vulong3896** [comment]
I got the same problem, I followed [Change default password](https://github.com/kubeflow/manifests#change-default-user-password), made my own username/password, reinstalled kubeflow but after that the default admin account was still user@example.com/12341234. Don't know why

**Comment by onegit20** [comment]
kubectl get pods -n auth | awk '/dex/{print $1}' | xargs kubectl delete -n auth pods

**Comment by mvilrokx** [comment]
Once you make the changes to `common/dex/base/config-map.yaml` as per the documentation, you need to run the following:

`kustomize build common/dex/base  | kubectl apply -f -`
