### ISSUE TITLE
Some individual tests not showing up in test-grid

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#631]
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-presubmit

I only see rows for
- overall
- deploy-kubeflow-teardow
- tf-serving-image-inception-cpu
- tf-serving-image-inception-cpu

So we are missing results corresponding the junit xml files

junit_e2e_gke.xml
junit_kubeflow-deploy-deploy_kubeflow.xml
junit_kubeflow-deploy-deploy_model-inception-cpu.xml

My conjecture is that the filenames should only contain a single undersore after "junit_"

If that's the case it could be considered an issue in test grid but its probably just as easy to update our filenames to get rid of the underscores.

**Comment by jlewi** [comment]
[README](https://github.com/kubernetes/test-infra/blob/804d3f521f93afcb4cb7af7344e57eac537f88f3/gubernator/README.md#L79) says junit files can be "junit_*.xml"

**Comment by jlewi** [comment]
@krzyzacy @BenTheElder  Do you know if this WAI?

**Comment by krzyzacy** [comment]
@jlewi it need to match certain regex, will send to you offline

**Comment by krzyzacy** [comment]
we probably can lift that restrict for testgrid

**Comment by jlewi** [comment]
Thanks. I looked at the regex short answer is I think we should just name our files "junit_[^_]*" and it will work.
