### ISSUE TITLE
Is there any recommended way to mocking `kfp.Client` or `kfp_server_api` to write test code?

### ISSUE THREAD

**Issue by zamonia500** [kubeflow/kubeflow#6314]
/kind question

I implemented a python code to get the list of updated pipeline versions after a certain time offset using kfp.Client .
This code implemented in a way that uses the methods of kfp.Client.

And now I'm trying to test this code, but this code holds bunch of kfp_server_api & kfp.Client methods.
It's very inconvenient to mock these SDK code to write test code.
Is there anyone who has tested the code using kfp.Client?
Please share some good ideas thanks!

**Comment by kimwnasptd** [comment]
Hi @zamonia500, I would suggest to open this issue in the Pipelines repo https://github.com/kubeflow/pipelines who are maintaining the `kfp` client package

**Comment by zamonia500** [comment]
> Hi @zamonia500, I would suggest to open this issue in the Pipelines repo https://github.com/kubeflow/pipelines who are maintaining the `kfp` client package

Oops, my bad. Thanks to guide @kimwnasptd !
