### ISSUE TITLE
Example notebook images have incompatible kfp sdk

### ISSUE THREAD

**Issue by ca-scribner** [kubeflow/kubeflow#6327]
The example notebook images included out of the box appear to have `kfp==1.6.3` (see [here](https://github.com/kubeflow/kubeflow/tree/master/components/example-notebook-servers/jupyter-scipy)), whereas the latest version is `1.8.x`.  This version mismatch leads to problems that appear to be authentication related but are actually version mismatches when doing things like `client.list_experiments()`

**Comment by jbottum** [comment]
/area pipelines
/priority p2
/kind question
@kubeflow/pipelines any comments ?

**Comment by zijianjoy** [comment]
This notebook spec is under Notebook WG's area. Therefore Notebook can follow up to upgrade KFP to the latest version. On the other hand, user can also manually upgrade KFP SDK in the Notebook: https://www.kubeflow.org/docs/components/pipelines/sdk/install-sdk/#install-the-kubeflow-pipelines-sdk

cc @kimwnasptd @chensun

**Comment by ca-scribner** [comment]
Yeah a good point that, if a user knows this’ll be the case, there’s a very
easy fix (update kfp package), but that if the user does not know this is
could be very confusing and a bad experience out of the box.

**Comment by ca-scribner** [comment]
@zijianjoy Something pipelines could do perhaps is warning the user when the sdk version does not match that expected by the backend. That would be a meaningful improvement to the UX

**Comment by PratikStar** [comment]
@zijianjoy May I take this issue to test and close?
cc @kimwnasptd @chensun

**Comment by zijianjoy** [comment]
Sounds good, I think we should think more towards the compatibility matrix between KFP SDK and Backend. By default: The SDK and Backend should have matching version to guarantee it to work. But this condition might be too strict. 

The simple approach is to describe this compatibility matrix on kubeflow.org documentation.


cc @connor-mccarthy as well.

**Comment by connor-mccarthy** [comment]
Thanks, @zijianjoy. Exposing the backend version via an endpoint would help the SDK support this once we have a matrix established.
