### ISSUE TITLE
Migrate tslint to eslint

### ISSUE THREAD

**Issue by haoxins** [kubeflow/kubeflow#6330]
I think this is part of #6233 

As `tslint` has been deprecated for a long time, I want to take two steps to finish the migration.

1. Run `tslint` for all the exists `ts/js` codes
2. Migrate to `eslint` and port all the exists `tslint` rules, and make sure no big code style changes.

cc @kimwnasptd

**Comment by kimwnasptd** [comment]
Good point! We should do this change of all our web apps actually
