### ISSUE TITLE
K8s 1.22 - Notebook Controller 

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6366]
/kind feature

### Why you need this feature
Sub-issue of https://github.com/kubeflow/kubeflow/issues/6353

To have support for K8s 1.22 and the Notebook Controller we need to ensure the CRD will:
1. `apiextensions.k8s.io/v1` API version
2. We need to ensure we have a `spec.versions[*].schema.openAPIV3Schema` and that it's a structural schema, which we don't currently have AFAIK

A quick fix for this would be to update the generated manifests with the required changes. But after discussion with @samuelvl and @thesuperzapper we want to take the slightly longer round and properly update our code, so that auto generation scripts can produce the correct CRD.

### Describe the solution you'd like
To achieve this we want to update the kubebuilder version of the controller from `v1`, for which it was originally written, all the way to `v3`. This will also help us to do a version bump in the libraries of the controller, which is long overdue. So we hit two birds with one stone.

We should be able to achieve this by following the instructions in the kubebuilder project:
1. https://book.kubebuilder.io/migration/legacy/migration_guide_v1tov2.html
2. https://book.kubebuilder.io/migration/migration_guide_v2tov3.html

### Anything else you would like to adD
As a first goal we should target on only updating the structure of the code and the dependencies. But if during this effort we find problems from our logic that blocks us, then we should also consider changes in the code.

**Comment by kimwnasptd** [comment]
@samuelvl would you be interested in driving this forward? 

We'll of course be providing assistance and help as much as we can.

**Comment by samuelvl** [comment]
> @samuelvl would you be interested in driving this forward?
> 
> We'll of course be providing assistance and help as much as we can.

Thanks for opening the issue @kimwnasptd and providing all this information.

I'll be working on it, I'll let you know if I have any questions.
