### ISSUE TITLE
use oidc-authservice(keycloak) centraldashboard(ui) logout not working

### ISSUE THREAD

**Issue by weicheng8626** [kubeflow/kubeflow#6372]
/kind bug

**What steps did you take and what happened:**

use oidc-authservice(keycloak) 
I can login then into the menu page, 
but logout not working

**What did you expect to happen:**
logout success, go in login page

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
pod  authservice-0   log

time="2022-02-23T02:27:52Z" level=info msg="Successful logout." ip=10.0.31.46 request=/logout
time="2022-02-23T02:27:53Z" level=info msg="Login validated with ID token, redirecting." ip=10.0.31.46 request="/login/oidc?state=MTY0NTU4MzI3MnxFd3dBRUVkT1NWcDNSMHM1T1VsNmIzTmFXRTg9fGROwO8Hf-KL-_TrC2KMwtdfXFNmELo9__HpeGM5NmZd&session_state=05037c92-add3-4180-8ea7-57bf5190dd5f&code=e94ff5b4-4416-469e-87d8-5a286ebe8ed3.05037c92-add3-4180-8ea7-57bf5190dd5f.6d2b7075-59fd-4176-b830-23594eb06246"

First logout success, but it was quickly re-logged in

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):  dev_local
- kfctl version: (use `kfctl version`):  
- Kubernetes platform: (e.g. `minikube`)  aws eks
- Kubernetes version: (use `kubectl version`):  
   Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", 
   GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
   Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", 
   GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T
   23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): 
   client:  window10
   server:  aws eks (linux ec2)

**Comment by juliusvonkohout** [comment]
@kimwnasptd i can reproduce this issue too

**Comment by kimwnasptd** [comment]
I can't manage to reproduce this from the latest RC2 manifests. @juliusvonkohout could you provide some more context on your installation? 
1. Is it a vanilla 1.5 or are your integrating other components as well?
2. Are you using any other components that could be affecting the Dex/AuthService flow?

https://user-images.githubusercontent.com/11134742/157279371-1a5f4d6c-4517-42ee-bece-9547851bed07.mp4

**Comment by juliusvonkohout** [comment]
We just switched to 1.5rc2 with gitlab and keycloak as authentication providers. Gitlab logout is working now. My colleague @snmohan83 will check it today.

**Comment by juliusvonkohout** [comment]
@kimwnasptd my colleague confirmed to me that gitlab and keycloak is working now. So from my side we can close this.

**Comment by kimwnasptd** [comment]
Glad to hear.

/close

**Comment by Lejboelle** [comment]
@juliusvonkohout Would you be so kind to share how you fixed logout issue using keycloak? Did you change logout url or after logout url?
I'm having similar issue, caught in an infinite login loop.

**Comment by kimkihoon0515** [comment]
@juliusvonkohout Can you share how did your colleage fix keycloak logout inifite loop problem??

**Comment by kimkihoon0515** [comment]
@Lejboelle Did you fix the problem??

**Comment by infa-ddeore** [comment]
i have same issue with "authservice --> Okta" (no DEX) integration, logout again logs in the user back

```
time="2023-03-10T04:46:45Z" level=info msg="Successful logout." ip=10.14.136.221 request=/logout
time="2023-03-10T04:46:47Z" level=info msg="Login validated with ID token, redirecting." ip=10.14.136.221 request="/login/oidc?code=h_yo4lLYeuHNX8I1difG8NLki0-bR0jrSmGELtcm5Ak&state=MTY3ODQyMzYwNXxFd3dBRUZSb1lsaG1VVFp3V1ZOUk0yNHlOamM9fOCbT0k3WxYUDHtXvcU93pIEcpE-dYCvsy7hw7f0dpa8"
```

**Comment by snps-sagarrao** [comment]
I was able to successfully logout if I close the browser (Chrome) and reopen the kubeflow URL again and click on logout. I was using KeyCloak by replacing the Dex in my case.
