### ISSUE TITLE
Use Pachyderm from Jupyter to manage data

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#639]
See #151 for some background.

I think a good way to start integrating Kubeflow and Pachyderm would be to to use Pachyderm's data versioning capabilities with JupyterHub/Jupyter. This would make it really easy for datascientists to load datasets into their Jupyter notebooks to play with just by using the patchctl command line tool.

/cc @dwhitena

**Comment by inc0** [comment]
I agree, although I think we would need something that would allow also integration with tf-operator etc - to streamline training from these datasets.

**Comment by jlewi** [comment]
I got this working by setting the address environment variable

```
export ADDRESS=10.4.0.19:650
pachctl -v list-commit my-repo
```
I don't have service defined for pachd so I had to use the pod ip rather than a DNS name.

**Comment by jlewi** [comment]
Looks like `pachctl port-forward` won't work if the dashboard isn't running; but it looks like under the hood its just running `kubectl port-forward`.

**Comment by JoeyZwicker** [comment]
Port-forward should work find even without the dashboard. It'll spit out an
error with no dashboard there, but the port-forward to pachd should still
be fine. We'll double check for that for you and make sure there's not a
silly bug there.

**Comment by dwhitena** [comment]
Yeah @jlewi, it should work without the dashboard: 

```
$ pachctl deploy local --no-dashboard
serviceaccount "pachyderm" created
clusterrole "pachyderm" created
clusterrolebinding "pachyderm" created
deployment "etcd" created
service "etcd" created
service "pachd" created
deployment "pachd" created
secret "pachyderm-storage-secret" created

Pachyderm is launching. Check its status with "kubectl get all"

$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
etcd-7dbb489f44-6jqlj    1/1       Running   0          9s
pachd-688c7bbbc6-lgm26   0/1       Running   0          9s
$ pachctl port-forward &
[1] 1032
$ CTRL-C to exit
Forwarding the pachd (Pachyderm daemon) port...
Forwarding the dash (Pachyderm dashboard) UI port to http://localhost:30080 ...
Is the dashboard deployed? If not, deploy with "pachctl deploy local --dashboard-only"
$ pachctl version
COMPONENT           VERSION
pachctl             1.7.0
pachd               1.7.0
$ pachctl list-repo
NAME                CREATED             SIZE
```

Alternatively you can use the ADDRESS variable, as you mentioned above.

**Comment by jlewi** [comment]
You are correct.  This was the error I was seeing

```
pachctl port-forward
CTRL-C to exit
Forwarding the dash (Pachyderm dashboard) UI port to http://localhost:30080 ...
Forwarding the pachd (Pachyderm daemon) port...
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
Is the dashboard deployed? If not, deploy with "pachctl deploy local --dashboard-only"Error from server (NotFound): pods "Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{.items[0].metadata.name}\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"kind\":\"List\", \"apiVersion\":\"v1\", \"metadata\":map[string]interface {}{\"selfLink\":\"\", \"resourceVersion\":\"\"}, \"items\":[]interface {}{}}" not found
Could not forward Pachd port
Could not forward dash websocket port
```
I forgot to specify the namespace which is why no pods were found and I misinterpreted the error.
