### ISSUE TITLE
TfServing uber tracking bug

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#64]
Opening an uber tracking bug to keep track of various features/improvements to ensure TfServing is well supported in Kubeflow

- [ ] Publish Docker images #50 
- [ ] Health/liveness checks #368
- [ ] Monitoring #369
- [ ] GPU support
    
/cc @rhaertel80 @kow3ns

**Comment by nkashy1** [comment]
TensorFlow Serving client library support - right now TensorFlow Serving only publishes a package to PyPI for Python 2 ([link](https://pypi.python.org/pypi/tensorflow-serving-api)).

This means that users can't run this library from JupyterHub if they just follow our standard procedure.

**Comment by yupbank** [comment]
Health/liveness checks can be done from http-proxy

**Comment by jlewi** [comment]
@yupbank Can you explain what you mean by doing health and liveness checks from the http proxy? Would that be testing the correct thing?

**Comment by yupbank** [comment]
oh... for that i was referring to  k8s liveness probe and readiness probe ...

**Comment by jlewi** [comment]
@yupbank That part I understand but how does the http proxy help us determine the liveness/readiness of TFServing? The http proxy could be live/ready but the TFServing might not.

**Comment by yupbank** [comment]
since now we have this https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/model_service.proto#L16

http proxy can be forced to only ready when TFServing is ready.

**Comment by jlewi** [comment]
Closing this bug because we have more specific bugs for individual issues.

**Comment by lluunn** [comment]
Should we have one for logging too?

**Comment by zmoon111** [comment]
i use util percent of  cpu&gpu to check if it is in live status
