### ISSUE TITLE
How to use kubeflow for training

### ISSUE THREAD

**Issue by leftys** [kubeflow/kubeflow#640]
Hi all!

we are considering using kubeflow for training inside our Kubernetes cluster, but after reading the docs, I am still confused. Those are the two questions on my mind: 

- Is the training run in Jupyter notebooks distributed on previously deployed worker nodes? 
- If I want to run training after change of my source code, do I have to rebuild a docker container running the training and deploy the container on worker notes into our Kubernetes cluster? Or is there any simpler way to re-use deployed worker nodes with updated code?

Thanks!
Jan

**Comment by aronchick** [comment]
Hi - thanks for your interest! 

The flow is:
- Deploy Kubeflow - includes TF job and Jupyter. This runs on your existing Kubernetes cluster. When you're in either, the job will run either single node or distributed depending on what you specify.
- When you're done with your training, TF will output your model and weights to a directory. You'll use that for serving later.
- When you change your source code (I assume you mean model?), you need to rerun your training to update the weights. It'll output to the same or new directory depending on what you specify.

I'm not entirely sure what you mean about rebuilding your containers - do you mean if you update Kubeflow?

**Comment by ogre0403** [comment]
Hi,
 
I have the same question. If I already has a training job code, how do I use kubeflow to train my model? 
According to [Submitting a TensorFlow training job](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#submitting-a-tensorflow-training-job), we have to create a docker image, then use the image to run the training job. 

If we have to build the new image, how do I create a image contain my code?
If we don't need to build the new image, how do I run my training job code in kubeflow?

Thanks

**Comment by jlewi** [comment]
To create an image you can use whatever tooling you want to build docker images.

Once you have an image and have deployed Kubeflow you can just create a K8s resource for TFJob.
