### ISSUE TITLE
Add new image groups in jupyter-web-app

### ISSUE THREAD

**Issue by chmielas** [kubeflow/kubeflow#6400]
/kind feature

There are currently three groups of images available in the jupyter-web-app:
- jupyterlab
- Visual Studio Code
- Rstudio

Is it possible to make a modification which will allow to add more groups from configmap level ?
This would allow for more possibilities of creating new types of notebooks and their customization

![image](https://user-images.githubusercontent.com/13102925/158162504-f5e02a3d-5700-4384-a709-1279349d3b14.png)

**Comment by juliusvonkohout** [comment]
/close

 in favor of Kubeflow Workspaces
