### ISSUE TITLE
Provide a dropdown list for pipeline parameters on Kubeflow Dashboard

### ISSUE THREAD

**Issue by hasansalimkanmaz** [kubeflow/kubeflow#6403]
/kind feature

**Why you need this feature:**
We have flexible, compact pipeline steps and we use them across multiple kubeflow pipelines. These steps are configured via some parameters that have a set of possible values. For instance, there is a `model_type` parameter that accepts `simple`, `multi-headed` etc. If a user/client sends a value with a typo like `sipmle`, the pipeline fails and it can take a while until the user notices it.

**Describe the solution you'd like:**
I think it would be better to create a specific pipeline parameter in which a user can set only the possible set of values. This can be done by showing a dropdown list for the pipeline parameter on the Kubeflow dashboard. For API, this can be done by immediately returning a specific error.

**Comment by Sharathmk99** [comment]
+1****

**Comment by seanswyi** [comment]
Came here to say that I'm also interested in this feature. I just got done implementing my own pipeline using parameters and also found it a bit unintuitive to have to manually type in all of the values. It's mostly fine if it's something like a short number (e.g., `32`) but when it gets longer (e.g., `tf_efficientnetv2_m_in21ft1k`) then there is too much room for human error.

**Comment by juliusvonkohout** [comment]
/close

this issue belongs to kubeflow/pipelines
