### ISSUE TITLE
KF_PIPELINES_SA_TOKEN_PATH not in use.

### ISSUE THREAD

**Issue by hellobiek** [kubeflow/kubeflow#6411]
/kind question

**Question:** KF_PIPELINES_SA_TOKEN_PATH seems not be used.

I deploy a kubeflow in Multi-User mode. And now I found I can not visit kubeflow pipelines through the 
PodDefault.

and the env KF_PIPELINES_SA_TOKEN_PATH, can not found in code.

as https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/#how-multi-user-mode-in-cluster-authentication-works shows.

**Comment by alexisgaziello** [comment]
Same problem here

**Comment by alexisgaziello** [comment]
It looks like the only reference to that `env` in the pipelines python source code is in the auth deprecated module:

- [_satvolumecredentials.py](https://github.com/kubeflow/pipelines/blob/b693909a0879d478c4cb8711932b06c956629ae0/sdk/python/kfp/deprecated/auth/_satvolumecredentials.py)
- [auth](https://github.com/kubeflow/pipelines/blob/b693909a0879d478c4cb8711932b06c956629ae0/sdk/python/kfp/deprecated/auth/__init__.py)


Maybe the doc is outdated?

**Comment by alexisgaziello** [comment]
Managed to connect from within the cluster using info from this [issue](https://github.com/kubeflow/kfctl/issues/140).

My sol:

```python

import requests

USERNAME = "user@example.com"
PASSWORD = "12341234"
NAMESPACE = "kubeflow-user-example-com"
HOST = 'http://istio-ingressgateway.istio-system.svc.cluster.local:80'

session = requests.Session()
response = session.get(HOST)

headers = {
    "Content-Type": "application/x-www-form-urlencoded",
}

data = {"login": USERNAME, "password": PASSWORD}
session.post(response.url, headers=headers, data=data)
session_cookie = session.cookies.get_dict()["authservice_session"]

client = kfp.Client(
    host=f"{HOST}/pipeline",
    cookies=f"authservice_session={session_cookie}",
    namespace="kubeflow-user-example-com"
)
print(client.list_pipelines())


```

**Comment by hellobiek** [comment]
> 
this method can not used in production mode.

**Comment by hellobiek** [comment]
> Managed to connect from within the cluster using info from this [issue](https://github.com/kubeflow/kfctl/issues/140).
> 
> My sol:
> 
> ```python
> import requests
> 
> USERNAME = "user@example.com"
> PASSWORD = "12341234"
> NAMESPACE = "kubeflow-user-example-com"
> HOST = 'http://istio-ingressgateway.istio-system.svc.cluster.local:80'
> 
> session = requests.Session()
> response = session.get(HOST)
> 
> headers = {
>     "Content-Type": "application/x-www-form-urlencoded",
> }
> 
> data = {"login": USERNAME, "password": PASSWORD}
> session.post(response.url, headers=headers, data=data)
> session_cookie = session.cookies.get_dict()["authservice_session"]
> 
> client = kfp.Client(
>     host=f"{HOST}/pipeline",
>     cookies=f"authservice_session={session_cookie}",
> )
> print(client.list_pipelines())
> ```

thank you very much, I sloved this problem through your method.
