### ISSUE TITLE
K8s 1.22 and crud-web-apps

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6427]
/kind feature

### Why you need this feature:
Sub-issue of https://github.com/kubeflow/kubeflow/issues/6353

To have support for K8s 1.22 we need to ensure all our [crud web apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps), Jupyter, TensorBoards, Volumes, are using the `v1` version of `SubjectAccessReviews`. https://kubernetes.io/docs/reference/using-api/deprecation-guide/#subjectaccessreview-resources-v122

The apps are using SARs to check if an authenticated user is allowed to perform an action [`code`](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py#L68). The common code is using an older version of the K8s client that is most probably using the `v1beta` API for `SubjectAccessReviews`. https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/common/backend/setup.py#L6

### Describe the solution you'd like
To make the apps compliant with K8s 1.22 we should only need to update this Python K8s client, which will use `v1` for SARs out of the box.

Note that I had played around with updating the K8s python client in the past and I remember there were some changes in the `delete` calls, and how we passed the `foreground_policy`. Let's double check these routes as well as part of this effort.

**Comment by wjentner** [comment]
I'd like to give this a go. Is it ok if I add some type hints to the code? I think this would make things easier for further refactoring.
I will stay compatible with python 3.6 as defined in the setup.py.

**Comment by kimwnasptd** [comment]
Hi there @wjentner, we just merged a PR for this in https://github.com/kubeflow/kubeflow/pull/6422

But could you also help verify that you can use the app as well with K8s 1.22, before we close this issue?

Testing the basic CRUD operations like:
* Creating a notebook
* Deleting a notebook
* Start/Stopping a notebook

should be more than enough. These actions are also using SubjectAccessReviews, when the app is deployed in the cluster, so the updated K8s python client package should be using the v1 version out of the box [and everything should work]
