### ISSUE TITLE
K8s 1.22 and Admission Webhook (PodDefaults)

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6428]
/kind feature

### Why you need this feature
Sub-issue of https://github.com/kubeflow/kubeflow/issues/6353

### Describe the solution you'd like
To have support for K8s 1.22 in the Admission Webhook (PodDefaults) we need to:
1. Make sure we are using the `v1` admission APIs https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/main.go#L31
2. Upgrade the PodDefault CRD to `v1`. We'll also need to have `preserveUnknownFields: false` in order to allow for upgradeability from `v1beta1` https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning
    * Note that this should be way easier than https://github.com/kubeflow/kubeflow/issues/6366, since this time the CRD manifests were manually generated. So we can just do all the changes in-place
4. Update the `MutationWebhookConfiguration` to use the `v1` API

Relevant links:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

### Anything else you would like to add
One of the changes in the `MutationWebhookConfiguration` is that now by default the `failurePolicy` will be `Fail`. This means that if the webhook fails to mutate a Pod the whole creation will fail. We need to test this use case and make sure we document the behavior accordingly

**Comment by wjentner** [comment]
@kimwnasptd I gave this issue a first shot, but I do have some questions:

1.  I assume the versions in the main.go should be updated as well? (see for example this line: https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/main.go#L61). I have not done that yet.
2. I've updated the PodDefault CRD and tested it with kubernetes v1.22.8
3. I've updated several of the MutationWebhookConfiguration manifests and defined the `failurePolicy` explicitly. Another issue are the `sideEffects`. I currently set them to `NoneOnDryRun` but perhaps just `None` is more fitting? The k8s docs also recommend to set `timeoutSeconds` explicitly, the default is `10` seconds but perhaps more is needed (up to 30 is possible)?

Should I issue a PR already, or should I continue fixing things beforehand?

**Comment by aaron-arellano** [comment]
@wjentner I actually got a working branch for the required changes in the go code and the kubernetes resources. I was going to push this to PR two days ago but was out of office. If you don't mind I was going to open a PR for this issue.

**Comment by aaron-arellano** [comment]
I pushed my branch to PR. took a couple days to figure out working configs for admission webhook so hopefully this saves you time @wjentner . Note, I am not updating all the other webhooks you updated, I am only pushing changes in my PR for admission webhook as noted in this issue.

**Comment by wjentner** [comment]
Ah, perfect! Yea, you are way ahead of me. Thanks for tackling this!
