### ISSUE TITLE
tf-cnn: no matches for kind "TFJob" in version...

### ISSUE THREAD

**Issue by hylick** [kubeflow/kubeflow#643]
I saw the issue regarding the lowercase "f" in "TfJob," however, I'm seeing the same error after capitalizing to "F" in "TFJob." :

error: unable to recognize "tf_job_cpu.yaml": no matches for kind "TFJob" in version "tensorflow.org/v1alpha1"

What I did: pulled the latest from the github, modified the yaml file to have a capital "F" and then ran
`kubectl create -f tf_job_cpu.yaml`

I believe the issue is forcing to point to the right namespace, however, I don't know how to do that.

**Comment by jlewi** [comment]
That file is outdated. The correct version is `apiVersion: kubeflow.org/v1alpha1`

You should generate the job spec using ksonnet as described [here](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#run-the-tfcnn-example)
