### ISSUE TITLE
Kubeflow conformance test - integrating all KF components

### ISSUE THREAD

**Issue by james-jwu** [kubeflow/kubeflow#6485]
/kind feature

Hello WG leads,

I have been working on the [conformance test](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-conformance-program-proposal.md) implementation for KFP for the past couple of months. The [design](https://docs.google.com/document/d/1_til1HkVBFQ1wCgyUpWuMlKRYI4zP1YPmNxr75mzcps/edit) and basic implementation are available:

- Test driver in Kubeflow project ([PR](https://github.com/kubeflow/kubeflow/pull/6478))
- KFP tests (PRs linked to this [project](https://github.com/kubeflow/pipelines/projects/16))

I'd like to ask WG leads to review the design and integration pattern, and think about how we can integrate your components into the test driver. Please let me know if you have questions. I am looking for feedback. The goal is to develop one test driver to integrate tests from all KF components.

**Comment by james-jwu** [comment]
/cc WG leads:
@kubeflow/wg-automl-leads 
@kubeflow/wg-notebooks-leads 
@kubeflow/wg-pipeline-leads 
@kubeflow/wg-training-leads 
@kubeflow/wg-deployment-leads 
@kubeflow/wg-manifests-leads

**Comment by james-jwu** [comment]
Hello WG leads,

I'd like to bring up the conformance tests again in the context of the CNCF donation process. Part of that process requires us to come up with a conformance program to clearly define what is Kubeflow. I'd like to see if we can create the 1st version of the conformance tests, based on previous consensus, by the next KF release.

I'll be bringing this topic to the next KF community meeting (11/08/2022).

**Comment by alexeadem** [comment]
> /kind feature
> 
> Hello WG leads,
> 
> I have been working on the [conformance test](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-conformance-program-proposal.md) implementation for KFP for the past couple of months. The [design](https://docs.google.com/document/d/1_til1HkVBFQ1wCgyUpWuMlKRYI4zP1YPmNxr75mzcps/edit) and basic implementation are available:
> 
> * Test driver in Kubeflow project ([PR](https://github.com/kubeflow/kubeflow/pull/6478))
> * KFP tests (PRs linked to this [project](https://github.com/kubeflow/pipelines/projects/16))
> 
> I'd like to ask WG leads to review the design and integration pattern, and think about how we can integrate your components into the test driver. Please let me know if you have questions. I am looking for feedback. The goal is to develop one test driver to integrate tests from all KF components.


Hello @james-jwu  checking to see if this is still a thing. Last update is from 2022. 

I'm working on [qbo](https://ce.qbo.io/#/) certification with Kubeflow. qbo is a [CNCF certified distro](https://www.cncf.io/training/certification/software-conformance/) currently supporting  [nvidia gpu operator with Kubeflow in Linux and Wndows  WSL2](https://ce.qbo.io/#/ai_and_ml?id=kubeflow) using Docker in Docker.

Happy to test your conformance proposal for Kubeflow.

**Comment by thesuperzapper** [comment]
@alexeadem I am not quite sure what you are asking, but perhaps we could discuss this at the next [Kubeflow Community meeting](https://www.kubeflow.org/docs/about/community/#kubeflow-community-call) (they are at 8am PT on Tuesdays).

If that does not work for your timezone, we can figure something else out.

**Comment by alexeadem** [comment]
> @alexeadem I am not quite sure what you are asking, but perhaps we could discuss this at the next [Kubeflow Community meeting](https://www.kubeflow.org/docs/about/community/#kubeflow-community-call) (they are at 8am PT on Tuesdays).
> 
> If that does not work for your timezone, we can figure something else out.

Thanks for the meeting link and and quick response. I was looking on how to get  Kubeflow conformance for `qbo`. See you next Tuesday.

**Comment by andreyvelich** [comment]
We can close it in favour of: https://github.com/kubeflow/community/issues/711
