### ISSUE TITLE
Migrate CI/CD to GH Actions

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6502]
Currently all AWS CI/CD tests have been disabled https://github.com/kubeflow/testing/pull/1003. This means that:
1. All tests we had are not running
2. We can't push images to the AWS registry, which was previously done by the CD jobs

AFAIK the AWS team is working on migrating the infra on a new billing account, so at some point we should be able to use the previous Prow workflows we had https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml.

Until then we'll need to move our CI/CD somewhere else and push our images in a different container registry. I propose that:
1. We use GH Actions for running some very basic tests, like checking formatting and manifests generation
2. Use a DockerHub registry to push images. I've created https://hub.docker.com/u/kubeflownotebookswg that we could use
    * Since DockerHub has rate limiting it's also worth trying pushing to [`ghcr.io`](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) as well 

cc @kubeflow/release-managers @kubeflow/release-team 

/assign @kimwnasptd 
/assign @nickloukas

**Comment by surajkota** [comment]
Hi @kimwnasptd, Please see community meeting notes from 2022-05-31 and https://github.com/kubeflow/testing/issues/1006#issuecomment-1145523044

**Comment by thesuperzapper** [comment]
@kimwnasptd rather than using a semi-random DockerHub, my vote is to just use GHCR as this will make our images be hosted under: `ghcr.io/kubeflow/{IMAGE_NAME}:{IMAGE_TAG}` which is much more trustworthy, and less susceptible to supply chain attacks (as DockerHub limits you to a single super-admin API key unless you pay them).

**Comment by kimwnasptd** [comment]
@thesuperzapper let's actually go with both registries. We've raised in the past the proposal of pushing images to more than one registries https://github.com/kubeflow/kubeflow/issues/5922. If `ghcr.io` doesn't provide such limits as DockerHub we can use that as the default one. 

Will need to coordinate a little bit with @zijianjoy on the exact steps to add credentials to GH with the registry. I'll reach out once I have fully written down instructions, so that we allocate the least necessary amount of his time for setting this up

**Comment by andreyvelich** [comment]
Currently, we use GitHub actions for CI/CD
