### ISSUE TITLE
[Question] PodDefaults are not working as expected in 1.5.0

### ISSUE THREAD

**Issue by muthurajr** [kubeflow/kubeflow#6507]
/kind question

**Question:**
We have kubeflow 1.5.0 installed on GKE, and PodDefaults are not getting added to the notebook pods. Can you help on additional steps to debug the issue.

* User namespace: common [user-namespace.txt](https://github.com/kubeflow/kubeflow/files/8863485/user-namespace.txt)
* PodDefault [access-ml-pipeline.txt](https://github.com/kubeflow/kubeflow/files/8863457/access-ml-pipeline.txt)
* User pod created through notebook interface [user-pod.txt](https://github.com/kubeflow/kubeflow/files/8863459/user-pod.txt)
* Admission Webhook logs
```
I0608 16:00:49.238956       1 main.go:617] About to start serving webhooks: &http.Server{Addr:":4443", Handler:http.Handler(nil), TLSConfig:(*tls.Config)(0xc0002ca180), ReadTimeout:0, ReadHeaderTimeout:0, WriteTimeout:0, IdleTimeout:0, MaxHeaderBytes:0, TLSNextProto:map[string]func(*http.Server, *tls.Conn, http.Handler)(nil), ConnState:(func(net.Conn, http.ConnState))(nil), ErrorLog:(*log.Logger)(nil), BaseContext:(func(net.Listener) context.Context)(nil), ConnContext:(func(context.Context, net.Conn) context.Context)(nil), inShutdown:0, disableKeepAlives:0, nextProtoOnce:sync.Once{done:0x0, m:sync.Mutex{state:0, sema:0x0}}, nextProtoErr:error(nil), mu:sync.Mutex{state:0, sema:0x0}, listeners:map[*net.Listener]struct {}(nil), activeConn:map[*http.conn]struct {}(nil), doneChan:(chan struct {})(nil), onShutdown:[]func()(nil)}
```
* Admission webhook pod [admission-webhook-deployment-pod.txt](https://github.com/kubeflow/kubeflow/files/8863460/admission-webhook-deployment-pod.txt)
* Admission webhook config [admission-webhook-mutating-webhook-configuration.txt](https://github.com/kubeflow/kubeflow/files/8863464/admission-webhook-mutating-webhook-configuration.txt)

**Comment by yingding** [comment]
I got exactly the same issue. Previously, I can connect to my notebook in a multi-user setting, after I activated poddefaults to enable ml-pipeline access in KF 1.5.0. I got the an error while connect to my notebooks:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
The error from `Admission Webhook Deployment` pod:
```
I0609 07:12:30.632261       1 main.go:617] About to start serving webhooks: &http.Server{Addr:":4443", Handler:http.Handler(nil), TLSConfig:(*tls.Config)(0xc0002c6180), ReadTimeout:0, ReadHeaderTimeout:0, WriteTimeout:0, IdleTimeout:0, MaxHeaderBytes:0, TLSNextProto:map[string]func(*http.Server, *tls.Conn, http.Handler)(nil), ConnState:(func(net.Conn, http.ConnState))(nil), ErrorLog:(*log.Logger)(nil), BaseContext:(func(net.Listener) context.Context)(nil), ConnContext:(func(context.Context, net.Conn) context.Context)(nil), inShutdown:0, disableKeepAlives:0, nextProtoOnce:sync.Once{done:0x0, m:sync.Mutex{state:0, sema:0x0}}, nextProtoErr:error(nil), mu:sync.Mutex{state:0, sema:0x0}, listeners:map[*net.Listener]struct {}(nil), activeConn:map[*http.conn]struct {}(nil), doneChan:(chan struct {})(nil), onShutdown:[]func()(nil)}
```
Then I removed poddefault `access-ml-pipeline` from my profile namespace, recreate a new notebook. And i still get the error. I also restarted dashboard pod and admission-webhook-deployment pod. I still can't connect to notebook.

Any hints on this is really appreciated.

**Comment by yingding** [comment]
@muthurajr Were you able to rollback the `access-ml-pipeline` poddefault setting for the `admission-webhook-deployment` ? After I delete the `access-ml-pipeline` pod default from my profile/namespace, I still got the error.

**Comment by muthurajr** [comment]
@yingding I'm able to connect to notebooks without any error. Only problem is PodDefault specifications are not applied.

**My initial findings**
The log message displayed in admission controllers `About to start serving webhooks` is expected one. 

Ideally, admission controller monitors for pod creation, and if matching labels are found then the configuration will be applied on the pod. The same information will be logged in the admission-webhook-pod also when the pod defaults are applied.

Expected logs in admission controller: [This is obtained from kf 1.5.0 installed on EKS]
```
I0609 21:19:57.697027       1 main.go:496] fetched 1 poddefault(s) in namespace practice
I0609 21:19:57.697059       1 main.go:512] 1 matching pod defaults, for pod test-0
I0609 21:19:57.697067       1 main.go:518] Matching PD detected of count 1, patching spec
I0609 21:19:57.697084       1 main.go:370] mutating pod: test-0
I0609 21:19:57.697102       1 main.go:532] applied poddefaults: access-ml-pipeline successfully on Pod: test-0 
```

Enabling debug logging on admission controller might help to find the issue but I couldn't find an option for that.

**Comment by yingding** [comment]
@muthurajr I see. The poddefault works on my end now and I used another namespace then the `common`. I am pretty sure you have also stopped and restarted the notebook server to retrigger poddefaults. I also put the namespace in quotes, but it should work in both case.

**Comment by muthurajr** [comment]
@yingding It appeared to be a firewall issue in gke and we need to open port 4443 for the webhook to work. Thank you for the suggestions!!
