### ISSUE TITLE
Notebook conditions are being appended

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6528]
/kind bug

**What steps did you take and what happened:**
Right now the Notebooks controller will be appending new Pod conditions to the Notebook's status https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L247. 

This means that a Notebook could end up with the following conditions being present at the same time:
```
        {
          "lastProbeTime": "2022-04-18T08:29:27Z", 
          "message": "Error", 
          "reason": "Error", 
          "type": "Terminated"
        }, 
        {
          "lastProbeTime": "2022-04-15T06:39:50Z", 
          "type": "Running"
        }, 
```

**What did you expect to happen:**
K8s Conditions are used for expressing the state of an object **at a specific point in time**. 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

We shouldn't be appending the Pod Conditions to the Notebook Conditions, but rather just mirror the Pod conditions to the Notebook.

**Anything else you would like to add:**
If we also add a proper function for converting the PodConditions to Notebook conditions with some basic checks like:
```golang
func PodCondToNotebookCond(c corev1.PodCondition) v1.NotebookCondition {
	notebookCond := v1.NotebookCondition{}

	if len(c.Type) > 0 {
		notebookCond.Type = c.Type
	}

	if len(c.Reason) > 0 {
		notebookCond.Reason = c.Reason
	}
...
```
Then we should be way more solid and also close the relevant, but orthogonal, https://github.com/kubeflow/kubeflow/issues/6056

**Comment by midhun1998** [comment]
Hello @kimwnasptd . I can take a shot at this.
