### ISSUE TITLE
issue with "authservice-0" pod for kubeflow OIDC setup

### ISSUE THREAD

**Issue by SachinT95** [kubeflow/kubeflow#6567]
I'm trying to install the OIDC-enabled kubeflow setup on my azure cluster but "authservice-0" is having some issues.

![image](https://user-images.githubusercontent.com/88109806/178188956-aecd17e2-f6f9-4773-b3d8-00d480ae81e0.png)

![image](https://user-images.githubusercontent.com/88109806/178188974-f5db975e-bdbe-48ce-9534-67e6c04748c7.png)

Regarding “authservice-0”, I updated the YAML file with client Id, tenant id, client secret and OIDC redirect URL, which is reflected when I execute the “kubectl get statefulset authservice -n istio-system -o yaml” command (please refer below snapshot)

![ss44](https://user-images.githubusercontent.com/88109806/178189633-d82e413e-5e5c-4864-a2bd-0eff2ad129a6.png)

But when I check the YAML files on the azure web UI and also when I do “kubectl describe pod authservice-0 -n istio-system”, values are not reflected there (please refer to snapshots below)

![image](https://user-images.githubusercontent.com/88109806/178189087-41ca215b-a2b8-419f-8125-ca2c2c7e4470.png)

![image](https://user-images.githubusercontent.com/88109806/178189099-b85d9e74-1146-4b7a-bf4e-f758627e2ab0.png)

Can anyone help me with the above issue?
Due to this issue, I'm also unable to access the kubeflow dashboard.

**Comment by amolsr** [comment]
can you provide output of kubectl log authservice-0 .? The statefulset is backed by replicaset which only gets replace when the new one succeed that is why you pod is not reflecting new changes.

**Comment by amolsr** [comment]
are you not using dex in front of oidc-authservice .?

**Comment by SachinT95** [comment]
@amolsr Thanks for responding, Sorry for late reply...
the pod is now working fine. yaml file is updated and now load balancer ip is bale to redirect to the url mentioned in "oidc_redirect_uri".

**Comment by SachinT95** [comment]
But still I'm not able to access the kubeflow dashboard.
load balancer ip is redirecting to dns (oidc_redirect_uri) but unable to view the dashboard.

@amolsr , Do I need to configure DNS to point to the kubeflow central dashboard?
