### ISSUE TITLE
Manage Contributors UI Does not show all owned namespaces

### ISSUE THREAD

**Issue by aaron-arellano** [kubeflow/kubeflow#6575]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Attempted to add contributors via kubeflow UI but was unable to add contributors to all my owned namespaces. The. namespace drop-down does not work on this page and we are unable to switch to another namespace other than the first namespace in alphabetical order one owns.

**What did you expect to happen:**
We should be able to select any owned namespace in the UI to be able to manage contributors from.

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.5.0
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): 1.21

**Comment by aaron-arellano** [comment]
related to this [issue](https://github.com/kubeflow/kubeflow/issues/4924#issuecomment-624602349)

**Comment by thesuperzapper** [comment]
As I mentioned in https://github.com/kubeflow/kubeflow/issues/4569#issuecomment-1185094267, we welcome any PRs to address this.

**Comment by thesuperzapper** [comment]
This feature has been added in https://github.com/kubeflow/kubeflow/pull/7582.
