### ISSUE TITLE
Trouble adding a ksonnet package with testing

### ISSUE THREAD

**Issue by jose5918** [kubeflow/kubeflow#658]
How do I add another package to the kubeflow registry with current e2e tests? I am trying to add a package but the e2e tests use kubeflow master to install packages https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L121. This means it won't test the package before it is in master already?

What do you guys believe is the proper work around? I don't think you can add a pull request as a registry, but I also don't want to add code without tests.

**Comment by pdmack** [comment]
Maybe related to #637

**Comment by jlewi** [comment]
Not sure if you saw my answer in slack. The test infrastructure largely handles this as follows

1. The first step in the Argo workflow checks out the source at the commit/pr being tested
1. A subsequent step sets up the ksonnet directory and does `ks registry add`
1. The test then replaces `vendor/kubeflow` with a symlink to the source checked out in step 1 [see here](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L144)
    * This ensures we are testing the components at the commit being tested

This might be worth adding to the instructions for adding new packages [here](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md)

**Comment by pdmack** [comment]
#661 @jlewi PTAL

**Comment by jose5918** [comment]
@jlewi But doesn't it fail on step 2 before you get the updated code? That's what I have been observing. I could do something like @pdmack described above, but the moment we update the code it would run the tests again and fail I think.

**Comment by jlewi** [comment]
Why would the ks registry add step fail if you are pointing at the master branch? What command are you running and what failure are you observing?

**Comment by jose5918** [comment]
This is the error I am getting: `subprocess.CalledProcessError: Command 'cmd: ks pkg install kubeflow/pytorch-job exited with code 1' returned non-zero exit status 1`

For this commit https://github.com/kubeflow/kubeflow/pull/649/commits/91add7acf249c3e280dafd20ef89c2b3578ccbfe#diff-2552a6a0cb5a74e3184790464405bedcR126

Basically it fails because the package is not in master yet

**Comment by jlewi** [comment]
The problem is the current version of the script calls [ks pkg install](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L125) before changing the symlink. So I think you need to change the code so we replace the vendor directory before you do ks package install.

**Comment by jose5918** [comment]
Ok I'll try that, but the registry will still be pointing to master right? So it should still fail regardless of order?

**Comment by jlewi** [comment]
After we do replace the directory in vendor it will have all the packages in vendor and it won't talk to the repo anymore.

**Comment by jose5918** [comment]
I just tested locally and noticed that calling `ks pkg install` afterwards changes the code we are testing back to master instead of the new code. Probably because `app.yaml` is empty so it's not aware of the code that gets replaced in vendor.  We could fill out `app.yaml` without calling `pkg install` like I did to manually test pytorch. Does that seem like viable solution?

**Comment by jlewi** [comment]
I think you're right; about ks pkg install which is probably why we were doing it before the symlink because we needed it to modify app.yaml.

So I think you're right the correct thing would probably be to modify app.yaml. 

ksonnet is adding support for using local repositories ksonnet/ksonnet#232 which will be in 0.10. That's a better long term solution; but I don't know that we want to start using 0.10 yet.

**Comment by jose5918** [comment]
Ok, I think I will just try modifying app.yaml. I have a feeling trying to use 0.10 could become involved and I don't think the resulting functionality will be much different even if we start using 0.10 later.

**Comment by pdmack** [comment]
Yeah, _really_ would like the local filesystem stuff working in ksonnet 0.1x
