### ISSUE TITLE
Kubeflow 1.5 Deployment on Google Cloud: 502 Error

### ISSUE THREAD

**Issue by skrawn** [kubeflow/kubeflow#6588]
/kind bug

**What steps did you take and what happened:**

At the "Access the Kubeflow user interface (UI)" step of Deploy Kubeflow cluster for Kubeflow on Google Cloud, attempting to log into the Kubeflow UI results in a 502 Error: 

Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.

**What did you expect to happen:**

Expect to be able to log into the Kubeflow UI

**Anything else you would like to add:**

I worked through the troubleshooting steps for the 502 error under [Troubleshooting Deployments on GKE](https://www.kubeflow.org/docs/distributions/gke/troubleshooting-gke/), even though I know it says the instructions are for 1.0 and need to be updated. 

The load balancer is showing 0 of 2 backend services are healthy, but if I look at the instance group, both of the instances are showing as healthy in the instance group. The envoy NodePort does not seem to exist though?

```
$ export NAMESPACE=istio-system
$ URLMAP=$(kubectl --namespace=${NAMESPACE} get ingress envoy-ingress -o jsonpath='{.metadata.annotations.ingress\.kubernetes\.io/url-map}')
echo ${URLMAP}
k8s2-um-3vn0vx89-istio-system-envoy-ingress-vrmmqdg9
$ kubectl --namespace=${NAMESPACE} get svc envoy -o jsonpath='{.spec.ports[0].nodePort}'
Error from server (NotFound): services "envoy" not found
```
Does this indicate something is wrong in the troubleshooting instructions or wrong with my deployment?

**Environment:**

- Kubeflow version: 1.5
- kfctl version: kfctl not found
- Kubernetes platform: Google Cloud
- Kubernetes version: 1.21.13
- OS (e.g. from `/etc/os-release`): Pop!_OS

**Comment by skrawn** [comment]
I'm sorry, I see I'm in the wrong spot and the issue with a workaround was brought up in the gcp-blueprints repo: https://github.com/kubeflow/gcp-blueprints/issues/371

**Comment by lucastan5596** [comment]
> I'm sorry, I see I'm in the wrong spot and the issue with a workaround was brought up in the gcp-blueprints repo: [kubeflow/gcp-blueprints#371](https://github.com/kubeflow/gcp-blueprints/issues/371)

Did the workaround solve your problem? I'm having the same issue and tried to change this line
`kubectl patch backendconfig iap-backendconfig -n ${NAMESPACE} --type json -p '[{"op": "replace", "path": "/spec/healthCheck/requestPath", "value": "'${HC_INGRESS_PATH}'"}]'`
to this
`kubectl patch backendconfig iap-backendconfig -n ${NAMESPACE} --type json -p '[{"op": "replace", "path": "/spec/healthCheck/requestPath", "value": "/healthz/ready"}]'`
but doesn't work, is it I need to replace the line above as well?
`echo Setting BackendConfig healthCheck.requestPath to ${HC_INGRESS_PATH}`
