### ISSUE TITLE
Profiler does not properly annotate the default-editor service account

### ISSUE THREAD

**Issue by ryansteakley** [kubeflow/kubeflow#6618]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Installed Kubeflow manifests v1.6.0-rc.1
Use plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole:

The default-editor service-account is not getting annotated properly on v1.6.0-rc.1 Tested on 5+ EKS clusters on both 1.21 and 1.22. Then uninstalled and cherry-picked the pipeline changes from v1.6.0-rc.1 and reverted them back to v1.6.0-rc.0 state. Now the EKS 1.21 clusters are working and the service account is being annotated correctly. As expected 1.22 fails this is because the v1.6.0-rc.1 changes are to support Kubernetes versions of 1.22+.

Currently the annotation looks like

```
Name:                default-editor
Namespace:           test-profile
Labels:              <none>
Annotations:         eks.amazonaws.com/role-arn: 
Image pull secrets:  <none>
Mountable secrets:   default-editor-token-jj95z
Tokens:              default-editor-token-jj95z
Events:              <none>
```
Even if I manually edit the annotation it will instantly change back to the way it is shown above.
**What did you expect to happen:**
default-editor service-account to be annotated properly

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.6.0-rc.1
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) eks v1.21/1.22
- Kubernetes version: (use `kubectl version`): v1.22
- OS (e.g. from `/etc/os-release`): mac-osx

**Comment by kimwnasptd** [comment]
@apo-ger let's take a look at this one as well, since we've seen distributions bumping into it https://github.com/kubeflow/manifests/issues/2221#issuecomment-1221199387

The only PR between RC0 and RC1 is for the Kubebuilder update https://github.com/kubeflow/kubeflow/pull/6491

**Comment by surajkota** [comment]
Go yaml package was updated from https://github.com/ghodss/yaml to https://pkg.go.dev/gopkg.in/yaml.v2#section-readme and [yaml marshal and unmarshal](https://github.com/kubeflow/kubeflow/blob/v1.6.0-rc.0/components/profile-controller/controllers/profile_controller.go#L677-L684) is not working, it returns an empty struct. 

I haven't tested but I think this might be affected GCP plugin as well. @zijianjoy does the WorkloadIdentity plugin work fine with 1.6-rc1?

We also need to add the samples back which were removed in #6491

**Comment by joepeskett** [comment]
I've recently tried deploying Kubeflow 1.6-rc1 in private GKE and hit a similar sounding problem with workload identity. The google service account from the annotation is being set to an empty string, rather than the specified service account.

**Comment by surajkota** [comment]
@joepeskett I created a PR with the fix, can you verify that it works for GCP plugin?

**Comment by talha-naeem1** [comment]
I am also facing this issue still, with kubeflow version 1.7 with AWS. The default-editor service account which is created by kubeflow profile, is not being annotated properly. Can someone please help me out if you have resolved it. :raised_hands: thanks advance
