### ISSUE TITLE
Batch Prediction Beam Library

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#662]
We'd like to have a story for batch prediction with beam. We will need a library of DoFns to do inference.

Related to:
   Batch Prediction using GPUs #251 

/assign @yixinshi

**Comment by jlewi** [comment]
Pending PR
https://github.com/kubeflow/batch-predict/pull/7

**Comment by jlewi** [comment]
@yixinshi What is the status of batch prediction?

**Comment by yixinshi** [comment]
The code has been checked in for a while. I am working on examples and docs.

**Comment by jlewi** [comment]
@yixinshi is there issue for examples and docs?

**Comment by jlewi** [comment]
We have kubeflow/batch-predict#5
