### ISSUE TITLE
Dashboard manifest uses incorrect environment variable to pass configmap name

### ISSUE THREAD

**Issue by ca-scribner** [kubeflow/kubeflow#6622]
[This line](https://github.com/kubeflow/kubeflow/blob/0a79697d8eb7aa7b13f2fdc24fc99150ee8feddf/components/centraldashboard/manifests/base/deployment.yaml#L41) in the dashboard manifests assigns the name of the configmap for dashboard links to the `DASHBOARD_LINKS_CONFIGMAP` environment variable, but the code [looks for `DASHBOARD_CONFIGMAP` instead](https://github.com/kubeflow/kubeflow/blob/e6fdf515c09ba1f695d60a87c9c56ba5fb1718e8/components/centraldashboard/app/k8s_service.ts#L5).  

This error is likely due to how the environment variable was [renamed in the past](https://github.com/kubeflow/kubeflow/pull/5469/files#diff-a29b81659d6ca88b1df24f77d04886f8eb04631f08a34e41da53e6bb273e3be0R5) and manifests were not updated.  The only reason things work currently is because the default value specified in the manifests (`centraldashboard-config`) happens to match the default value in the typescript code that's used if no variable is set.

**Comment by andreyvelich** [comment]
This should fix it: #7264
