### ISSUE TITLE
Bootstrapper should check if user has appropriate permissions and if not create cluster role

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#664]
See #105 and [RBAC Issue](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#rbac-clusters)

As part of cluster preparation we should check whether user has necessary permission to create Kubeflow components (e.g. the role bindings) using the [auth](https://kubernetes.io/docs/admin/authorization/) API. If not we should see if we can create a cluster role binding making the user a cluster admin so they will be able to deploy Kubeflow.

/assign @kunmingg

**Comment by kunmingg** [comment]
fixed by https://github.com/kubeflow/kubeflow/pull/680 and https://github.com/kubeflow/kubeflow/pull/699
