### ISSUE TITLE
Creating and using custom images with USER as variable

### ISSUE THREAD

**Issue by mshaikh786** [kubeflow/kubeflow#6644]
I am trying to create a common custom image for Kubeflow as service. 
The Kubelflow authentication is integrated with an external authenticator like LDAP in our case.
The intent is to run this common image as different users i.e. with different UIDs and GIDs, depending on who the user is upon authentication.
How can I create an image and then run such image within Kubeflow (from the UI)?

**Comment by ReggieCarey** [comment]
Mount the identity as an environment variable. The images are in the examples directory of the repo. Create identity configmap in your namespace.

**Comment by mshaikh786** [comment]
> 

@ReggieCarey , thanks for your response. Can you please point to which example images in the repo are you referring to?
