### ISSUE TITLE
container image for 1.6.0 release

### ISSUE THREAD

**Issue by yarnabrina** [kubeflow/kubeflow#6668]
/kind question

**Question:**
I want to create a custom notebook image, where I'll install the packages that our use always. Until recently, we used `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/base:v1.5.0` as the base image and it was working fine.

However, after the release of `1.6.0`, we wanted to upgrade the custom image. However, it seems that there is no corresponding tag in ECR (probably related to #6548 as mentioned in the [release notes](https://github.com/kubeflow/kubeflow/releases/tag/v1.6.0)). But there is no mention on what should be used. I tried the following two in vain:

```zsh
❯ docker pull kubeflownotebookswg/base:1.6.0
Error response from daemon: manifest for kubeflownotebookswg/base:1.6.0 not found: manifest unknown: manifest unknown
❯ docker pull docker.io/kubeflownotebookswg/base:1.6.0
Error response from daemon: manifest for kubeflownotebookswg/base:1.6.0 not found: manifest unknown: manifest unknown
```

[This](https://hub.docker.com/r/kubeflownotebookswg/base/tags) shows a tag `v1.6.0-rc.0` released 3 months before, which does not seem to correspond to the final release on 7th September release. So, my question is what image should be used for the latest Kubeflow release?

**Comment by yarnabrina** [comment]
@thesuperzapper Noting your activities in #6560, I was wondering if you can help in shedding some light in this.

**Comment by thesuperzapper** [comment]
@yarnabrina I see that we have not pushed a `v1.6.0` tag on the [`kubeflownotebookswg/base`](https://hub.docker.com/r/kubeflownotebookswg/base/tags) registry, this is probably just because it did not change, but we should push it none the less.

@kimwnasptd do you have write access to that repo?

**Comment by anirban-ray-publicis-sapient** [comment]
@thesuperzapper @kimwnasptd

Is there any recommendation on what should be used for base image for custom container images? None of the base images recommended [here](https://www.kubeflow.org/docs/components/notebooks/container-images/) have any updates for almost a year now, and ECR still has `1.5.0`, and dockerhub is at `1.6.0-rc.0`

**Comment by juliusvonkohout** [comment]
@anirban-ray-publicis-sapient join the notebooks wg and create a pr with updates

**Comment by juliusvonkohout** [comment]
/close

There is now a PR to update the images
