### ISSUE TITLE
Create individual prototypes for just TFJob

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#669]
We should consider creating a prototype for people who just want the TFJob controller.

This is trivial to do.

**Comment by DjangoPeng** [comment]
It's necessary for someone who has no interest on the other part of kubeflow. 

@yph152 Would U like to part-time take it?

**Comment by pdmack** [comment]
/assign @pdmack

Already poked at this a bit but happy to share with @yph152

**Comment by jlewi** [comment]
In someone is look for a quick fix. You can just create a jsonnet file in your components directory. The contents should look like the following

```
local env = std.extVar("__ksonnet/environments");
local params = std.extVar("__ksonnet/params").components["kubeflow-core"];
local k = import "k.libsonnet";
local tfjob = import "kubeflow/core/tfjob.libsonnet";

// updatedParams uses the environment namespace if
// the namespace parameter is not explicitly set
local updatedParams = params {
  namespace: if params.namespace == "null" then env.namespace else params.namespace
};

std.prune(k.core.v1.list.new( [
    tfjob.parts(params.namespace).tfJobDeploy(params.tfJobImage),
    tfjob.parts(params.namespace).configMap(params.cloud, params.tfDefaultImage),
    tfjob.parts(params.namespace).serviceAccount,
    tfjob.parts(params.namespace).operatorRole,
    tfjob.parts(params.namespace).operatorRoleBinding,
    tfjob.parts(params.namespace).crd,
    tfjob.parts(params.namespace).uiRole,
    tfjob.parts(params.namespace).uiRoleBinding,
    tfjob.parts(params.namespace).uiService(params.tfJobUiServiceType),
    tfjob.parts(params.namespace).uiServiceAccount,
    tfjob.parts(params.namespace).ui(params.tfJobImage)
  ]))
```

Haven't actually tested this so buyer beware

**Comment by pdmack** [comment]
Now you tell me...

**Comment by pdmack** [comment]
This is very confusing and slowing me down.
```
./core/tf-job.libsonnet
./tf-job/tf-job.libsonnet
```
Both of these have had updates in the past 30 days. But it's not clear if there is any relationship between the two. It seems like the core version is the one of record at the moment.

**Comment by jlewi** [comment]
@pdmack Sorry Pete.  

`core/tf-job.libsonnet` contains the components for the custom controller.

`./tf-job/tf-job.libsonnet` contains prototypes for individual TFJobs.

So basically `core/tf-job.libsonnet` is used the cluster administrator to setup Kubeflow.
`./tf-job/tf-job.libsonnet` is used by users trying to submit jobs.

The division is rather arbitrary and reflects my lack of experience with ksonnet when I first created. I'm not sure it makes sense any more.

**Comment by pdmack** [comment]
@jlewi Thanks for clearing that up. So we probably want to "merge" back to `kubeflow/tf-job` if possible I take it?

In other words, the tf-job package prototype incorporates both the cluster admin and the individual TFJob types. Am I on the right track? Something like:
```
ks generate tf-job tf-job-admin
ks generate tf-job tf-job --name=my-tf-job
```

**Comment by jlewi** [comment]
So right now we we do 

```
ks generate kubeflow-core kubeflow
```

* Which would deploy TFJob + JupyterHub + other stuff

To deploy only the TFJob controller we'd want to do something like

```
ks generate tf-controller tf-controller
```

This would be a prototype that (for now at least) ought to live in the core package and should probably closely resemble the snippet I posted above.

**Comment by pdmack** [comment]
Why leave it in core? In #743, I moved it out to tf-job and the prototype generation would be similar to what you describe. I need to understand and fix those test failures though which may be in the testing repo.
