### ISSUE TITLE
Protection from fake kubeflow-userid header impersonation

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6702]
Right now a lot of the components developed in this repo do not have a sidecar.

The biggest issue with this is the fact that we have servers (web app backends) that are assuming user identity from the `kubeflow-userid` header. If we don't limit who and how can talk to these servers then users can impersonate other users.

This is also discussed in https://github.com/kubeflow/manifests/pull/2304

The list of backends that are currently vulnerable to `kubeflow-userid` are:
1. [Jupyter web app](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/manifests/base/deployment.yaml#L10)
2. [Volumes web app](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/volumes/manifests/base/deployment.yaml#L10)
3. [TensorBoards web app](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/tensorboards/manifests/base/deployment.yaml#L10)

To mitigate this we need to ensure that only the `istio-ingressgateway` can talk to `kubeflow-userid` sensitive apps. While we have the AuthorizationPolicies in place to allow only the IGW to talk to the apps, we have the sidecar disabled.

This is a bug. Thank you @juliusvonkohout @TobiasGoerke for exposing this

We should definitely include this in the KF 1.7 release as well
cc @kubeflow/release-managers @kubeflow/release-team

**Comment by kimwnasptd** [comment]
A note for context. As a first step we can only expect the IGW to talk to the apps, so the only change we need to do is to enable the sidecar.

If someone would like to have the apps accessible from other namespaces though then they'd need to have an AuthorizationPolicy that allows only the IGW to set this header. This is currently the case for KFP, where it's expected from Pods of other namespaces to ping their API Server.

https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml#L16-L39

**Comment by kimwnasptd** [comment]
@tobiasgoerke @juliusvonkohout interested in picking this up?

**Comment by juliusvonkohout** [comment]
@TobiasGoerke is, but i do not know his timeframe. I think it will be just changing three annotations and adding three authorizationpolicies that only allow the ingressgateway. mlpipeline-ui from https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml must also be checked, but the pr for that belongs in the pipeline repository.

**Comment by TobiasGoerke** [comment]
> @TobiasGoerke @juliusvonkohout interested in picking this up?

I'll take of the issue; see #6703 for PR and progress. 

I have not yet fully tested the changes. However, sidecars are enabled and the services seem to work fine.
