### ISSUE TITLE
Install kubeflow on openshift

### ISSUE THREAD

**Issue by vamshikrishna9999** [kubeflow/kubeflow#6721]
/kind bug
Error creating: pods "ml-pipeline-844c786c48-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, provider "ingress-scc": Forbidden: not usable by user or serviceaccount, provider "remedy-scc": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1337}: 1337 is not an allowed group, spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1001080000, 1001089999], spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added, spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added, spec.containers[1].securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1001080000, 1001089999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "rsync-anyuid": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "log-collector-scc": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "trident": Forbidden: not usable by user or serviceaccount, provider "velero-privileged": Forbidden: not usable by user or serviceaccount]

**What steps did you take and what happened:**

I was tried to install kubeflow operator on openshift cluster . i have deployed kubeflow components individually and while  deploying  some  kubeflow components i got error its failed to create pod and i was updated exact error in the above mentioned.so Due to this problem i was not able to access kubeflow operator dashboard.  

**What did you expect to happen:**
After deploying the kubeflow components  there i need wait few minutes for pods become to running state then after i need to access the kubeflow dashboard but there i was facing issues while deploying those components only.

**Environment:**

- Kubeflow version: v1.5.0 
- Kubernetes platform: (OpenShift`)
- Kubernetes version: (4.10)

**Comment by juliusvonkohout** [comment]
Well this is just normal kubernetes (Istio) knowledge. If you want to run a secure rootless kubeflow wait for 1.8 or buy a consulting and or installation from T-Systems(me) and or Arrikto. I have a few clusters running on Openshift in a secure manner. https://github.com/kubeflow/kubeflow/issues/6662 contains some guidance.

**Comment by vamshikrishna9999** [comment]
Hi..

I was trying to install kubeflow operator version v1.5.o on our OpenShift cluster(version 4.10). I have deployed the kubeflow components individually so while deploying the component Profiles+KAM i was facing the issue that is

 kustomize build apps/profiles/upstream/overlays/kubeflow | kubectl apply -f -
Error: map[string]interface {}(nil): yaml: unmarshal errors:
line 66: mapping key "livenessProbe" already defined at line 56
line 78: mapping key "ports" already defined at line 62
error: no objects passed to apply

Environment:

Kubeflow version: v1.5.0
Kubernetes platform: (OpenShift`)
Kubernetes version: (4.10)
