### ISSUE TITLE
tensor2tensor async training does not work

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#675]
I was able to do distributed training locally using multiple processes. When I tried to do distributed training on Kubeflow, the workers are stuck at "Waiting for model to be ready" and they time out.

When I use a master container, things seem to be working fine and I am able to scale training ~ linearly with more workers.

I am running three containers in k8s: 2 workers and 1 ps.

They are running on different nodes and do not share any filesystem

  # worker 0
  TF_CONFIG = {"cluster":{"ps":["tensor2tensor-training-job18-ps-111m-0:2222"],"worker":["tensor2tensor-training-job18-worker-111m-0:2222","tensor2tensor-training-job18-worker-111m-1:2222"]},"task":{"type":"worker","index":0},"environment":"cloud"}
  t2t-trainer --data_dir=gs://kubeflow-examples/tensor2tensor/data --t2t_usr_dir=./github --problems=github_issue_summarization_problem --model=transformer --hparams_set=transformer_github_issues --output_dir=./out --job-dir=./out --train_steps=5000 --master=grpc://tensor2tensor-training-job18-worker-111m-0:2222 --ps_replicas=1 --worker_replicas=2 --worker_gpu=0 --worker_id=0 --worker_job=/job:worker --ps_gpu=0 --schedule=train

  # worker 1
  TF_CONFIG = {"cluster":{"ps":["tensor2tensor-training-job18-ps-111m-0:2222"],"worker":["tensor2tensor-training-job18-worker-111m-0:2222","tensor2tensor-training-job18-worker-111m-1:2222"]},"task":{"type":"worker","index":1},"environment":"cloud"}
  t2t-trainer --data_dir=gs://kubeflow-examples/tensor2tensor/data --t2t_usr_dir=./github --problems=github_issue_summarization_problem --model=transformer --hparams_set=transformer_github_issues --output_dir=./out --job-dir=./out --train_steps=5000 --master=grpc://tensor2tensor-training-job18-worker-111m-1:2222 --ps_replicas=1 --worker_replicas=2 --worker_gpu=0 --worker_id=1 --worker_job=/job:worker --ps_gpu=0 --schedule=train

  # ps 0
  TF_CONFIG = {"cluster":{"ps":["tensor2tensor-training-job18-ps-111m-0:2222"],"worker":["tensor2tensor-training-job18-worker-111m-0:2222","tensor2tensor-training-job18-worker-111m-1:2222"]},"task":{"type":"ps","index":0},"environment":"cloud"}
  t2t-trainer --data_dir=gs://kubeflow-examples/tensor2tensor/data --t2t_usr_dir=./github --problems=github_issue_summarization_problem --model=transformer --hparams_set=transformer_github_issues --output_dir=./out --job-dir=./out --train_steps=1000 --master=grpc://tensor2tensor-training-job18-ps-111m-0:2222 --schedule=run_std_server

/cc @jlewi @rsepassi

**Comment by rsepassi** [comment]
There is no need to set —job-dir
And don’t you want your output directory to be on gcs, not local to a
throwaway machine?

So to clarify, you got things working, correct?
