### ISSUE TITLE
KF1.5: dashboard  , dispaly: Internal Server Error  Failed to connect to the database.

### ISSUE THREAD

**Issue by yanyanwang1** [kubeflow/kubeflow#6761]
/kind bug

**What steps did you take and what happened:**
installed the kubeflow , at first, it works  well, after several months, when i connect to the dashboard, it dispaly 

Internal Server Error
Failed to connect to the database

**What did you expect to happen:**
expect the kubeflow work well 

**Anything else you would like to add:**
all the pod runs well

**Environment:**

- Kubeflow version:  1.5
- kfctl version: (use `kfctl version`):
- Kubernetes platform:  aws eks , kubernetes
- Kubernetes version: .211
- OS (e.g. from `/etc/os-release`):

**Comment by chitravsnair** [comment]
facing same issue - Kubeflow on AWS EKS - not opening 
Error - Internal server error failed to connect to the database

**Comment by rhatol** [comment]
+1
up

**Comment by RustamyF** [comment]
I am having the same problem since last week

**Comment by juliusvonkohout** [comment]
/close

we are at 1.8.1+
