### ISSUE TITLE
A lot of K8s updates due to Notebook last_activity annotations

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6767]
/kind bug

**What steps did you take and what happened:**
Right now the Notebooks Controller is periodically querying each Notebook to update the `notebooks.kubeflow.org/last_activity` annotation on each Notebook https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220121-jupyter-notebook-idleness.md

But the problem is that right now the Controller will both make the http requests and update the CR in each reconciliation loop. This adds a lot of overhead to the platform.

**What did you expect to happen:**
I would expect the Controller logic to respect the `IDLENESS_CHECK_PERIOD` var and not make the requests on each reconciliation.

To do this we should introduce another annotation in each Notebook CR `notebooks.kubeflow.org/last_activity_check_timestamp`. The Controller will be setting the timestamp that it last checked for idleness of a Notebook. This way the Controller can compare this timestamp with the current time and decide NOT to check for idleness if the `IDLENESS_CHECK_PERIOD` has not passed.

**Environment:**
- Kubeflow version: `v1.6` and current `master`

/help

**Comment by thesuperzapper** [comment]
@kimwnasptd I thought that this [`ctrl.Result{RequeueAfter: culler.GetRequeueTime()}`](https://github.com/kubeflow/kubeflow/blob/1610b25e3ae6c40b230c64c77f52425c41e4ea2a/components/notebook-controller/controllers/notebook_controller.go#L281) (which calls [`culler.GetRequeueTime()`](https://github.com/kubeflow/kubeflow/blob/1610b25e3ae6c40b230c64c77f52425c41e4ea2a/components/notebook-controller/pkg/culler/culler.go#L81-L95)) would mean that the pod is not reconsiled more frequently than `IDLENESS_CHECK_PERIOD`?

**Comment by apo-ger** [comment]
Hi @kimwnasptd, I would like to work on this!

**Comment by apo-ger** [comment]
>I thought that this [ctrl.Result{RequeueAfter: culler.GetRequeueTime()}](https://github.com/kubeflow/kubeflow/blob/1610b25e3ae6c40b230c64c77f52425c41e4ea2a/components/notebook-controller/controllers/notebook_controller.go#L281) (which calls [culler.GetRequeueTime()](https://github.com/kubeflow/kubeflow/blob/1610b25e3ae6c40b230c64c77f52425c41e4ea2a/components/notebook-controller/pkg/culler/culler.go#L81-L95)) would mean that the pod is not reconsiled more frequently than IDLENESS_CHECK_PERIOD?

Hi @thesuperzapper! The issue with the current implementation is that it runs the culling logic on each reconciliation loop. This means that the controller won't respect the `IDLENESS_CHECK_PERIOD` if for example a create/update/delete event occurs in the meantime for any of the resources that the notebook controller `Watches`/`Owns`.

**Comment by kimwnasptd** [comment]
/assign @apo-ger 

Thanks for the initiative @apo-ger! I think it will be a good chance to even break the idleness/culling logic into its own controller inside of the Notebooks Controller/Operator. The controller will be responsible for:
1. Reconciling just notebook CRs
2. Properly setting the `notebooks.kubeflow.org/last_activity_check_timestamp` and `notebooks.kubeflow.org/last_activity` annotations accordingly
3. Set the `kubeflow-resource-stopped` annotation, if a notebook needs to be culled
4. Keep on using [`ctrl.Result{RequeueAfter: culler.GetRequeueTime()}`](https://github.com/kubeflow/kubeflow/blob/1610b25e3ae6c40b230c64c77f52425c41e4ea2a/components/notebook-controller/controllers/notebook_controller.go#L281), to ensure that notebooks will get reconciled every `IDLENESS_CHECK_PERIOD` minutes even if no changes happen after the last reconciliation of a notebook

Note that it will still be the responsibility of the Notebook Controller (not Culling Controller) to set the `replicas` to 0, if the stopped annotation is set

**Comment by andreyvelich** [comment]
This was fixed here: #6807
