### ISSUE TITLE
Bootstrap image not found

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#682]
I was following the bootstrap [readme](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/README.md), but I could not find the gcr.io/kubeflow-images-staging/bootstraper:latest docker image.

/cc @kunmingg

**Comment by pdmack** [comment]
We all agree that this this should be called "boostrapper", right? ;-)

**Comment by kunmingg** [comment]
@ankushagarwal It's still under dev, so please ```make build``` in bootstrap folder and you should have the docker image on your local.

**Comment by kunmingg** [comment]
Thanks, we can have a github typo-fix bot...

**Comment by ankushagarwal** [comment]
Thanks for the update on the readme, closing this.
