### ISSUE TITLE
Can you please update Azure docs for Kubeflow [K8S APIs deprecated]

### ISSUE THREAD

**Issue by mhamdan91** [kubeflow/kubeflow#6827]
Hi :)

Current docs for [Kubeflow\Azure](https://www.kubeflow.org/docs/distributions/azure/deploy/install-kubeflow/) are outdated as they're based off AKS 1.2.1 which was deprecated this past july [EOL of AKS 1.21](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) . Are there plans to update the available [manifest](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_k8s_istio.v1.2.0.yaml)  CustomResourceDefinition API anytime soon?

[K8S API changes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)

**Comment by saintnoah** [comment]
Hello, any update on this topic? Currently aks only support k8s 1.23.8 upwards. 

```
$ az aks get-versions -l westus -o table
KubernetesVersion    Upgrades
-------------------  -----------------------
1.25.4               None available
1.25.2               1.25.4
1.24.6               1.25.2, 1.25.4
1.24.3               1.24.6, 1.25.2, 1.25.4
1.23.12              1.24.3, 1.24.6
1.23.8               1.23.12, 1.24.3, 1.24.6
```

But v1.2 kubeflow require "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1" which is already deprecated in k8s v1.22

So cannot deploy kubeflow on aks. Is any solution on this?

**Comment by jbottum** [comment]
Hi @mhamdan91 @saintnoah  - I have asked Azure Product Manager folks to see if they would help, but I am not getting any response.   Do you have Azure contacts ?   In the meantime, I am cc'ing the Manifest Working Group leads.    If we do not find AKS contacts, we may have to continue with AKS support via 3rd party Kubeflow distributions, who support users on Azure with custom dependencies.   @DomFleischmann @kimwnasptd @akgraner

**Comment by saintnoah** [comment]
Thanks @jbottum. 
I was trying deploy kubeflow using manifest and it works for me with v1.6 kubeflow on v1.24.6 k8s. 
It might be helpful to update the [kubeflow azure deployment page](https://www.kubeflow.org/docs/distributions/azure/deploy/) so that people won't get lost following the official guide.

**Comment by kimwnasptd** [comment]
Josh so IIUC your proposal is to have a new concept of a distribution that is maintained by end users and not by the distro engineers themselves? This is interesting!

Although we'd need to document this process a little bit, and make sure this is properly exposed to users so that they know what level of support to expect

**Comment by jbottum** [comment]
@saintnoah Azure contacts are now engaging, they have updated their docs,
[https://gm/azure/kubeflow-ithub.coaks](https://github.com/azure/kubeflow-aks)
Contacts
Azure Product Manager Kaysie Yu, kaysieyu@microsoft.com 
Ayobami Ayodeji
Guy Bowerman

**Comment by saintnoah** [comment]
> @saintnoah Azure contacts are now engaging, they have updated their docs, [https://gm/azure/kubeflow-ithub.coaks](https://github.com/azure/kubeflow-aks) Contacts Azure Product Manager Kaysie Yu, [kaysieyu@microsoft.com](mailto:kaysieyu@microsoft.com) Ayobami Ayodeji Guy Bowerman

Thank you! This is really helpful.
