### ISSUE TITLE
set_cpu_limit not acting like set_gpu_limit

### ISSUE THREAD

**Issue by ShaharSheli** [kubeflow/kubeflow#6871]
What steps did you take and what happened:
When trying to set limitation on cpu like this: op.set_cpu_limit(16) on ContainerOp and compile it using:
kfp.compiler.Compiler().compile(my_pipeline, 'my-pipeline.zip')
I get: TypeError: expected string or bytes-like object
which is different when using gpu limit: op.set_gpu_limit(16)
that compile well and working

What did you expect to happen:
I expect those two function to act similarly.

Anything else you would like to add:
I solved it by using op.set_cpu_limit('16')

Environment:
kfp==1.6.2
python 3.8

**Comment by kimwnasptd** [comment]
Hi @ShaharSheli , could you open this issue in the https://github.com/kubeflow/pipelines repo as well? This way the KFP devs will also be in sync and might provide some feedback

**Comment by juliusvonkohout** [comment]
/close

This is a kfp issue
