### ISSUE TITLE
Build Kubeflow images in parallel

### ISSUE THREAD

**Issue by apo-ger** [kubeflow/kubeflow#6872]
/kind feature

https://github.com/kubeflow/kubeflow/pull/6555 introduced a mechanism for building all Kubeflow images via a top-level [central-Makefile](https://github.com/kubeflow/kubeflow/blob/master/components/Makefile). The central-Makefile has a `build-all` rule that calls all the `sub-Makefiles` of the different components in a serial manner. This makes the whole process very time-consuming since we can't use the `-j` option of `make` to run jobs in parallel.

We could speed-up this process by: 
- creating a single rule for each directory containing a `sub-Makefile`.
- having each directory rule as a dependency to the `build-all` rule in the central Makefile

This way every directory rule can run in parallel with other rules.

The same applies for the [central Makefile](https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/Makefile) for building all `notebook-server-images`. In this case though we should follow a slightly different approach as we need to build the images in a specific order since most of the `Dockerfiles` expect a `base` image to build on top. The following graph shows the dependencies for building the images:
![image](https://user-images.githubusercontent.com/100211967/210587506-4235bf37-af5c-4df6-bcd5-eaa93afbb00e.png)

So, we could split the single [docker-build-all](https://github.com/kubeflow/kubeflow/blob/1fe6dbcd0882cc645fe079c0c70dbf9d63aa87e8/components/example-notebook-servers/Makefile#L4) rule into multiple rules which perform recursive make calls to `sub-Makefiles` to build all the `notebook-server-images`. We can introduce target rules for the following `sub-Makefiles`:
- jupyter-pytorch-full:
  - jupyter-pytorch-full-cpu
  - jupyter-pytorch-full-cuda
- jupyter-scipy
- jupyter-tensorflow-full:
  - jupyter-tensorflow-full-cpu
  - jupyter-tensorflow-full-cuda
- codeserver-python
- rstudio-tidyverse

This way we ensure that all `notebook-server-images` will be built as each `sub-Makefile` is responsible for building all the required base images.

**Comment by andreyvelich** [comment]
We can close it due to #6873
