### ISSUE TITLE
Cannot see the list of notebooks [500] An error occurred in the backend. 

### ISSUE THREAD

**Issue by ntl-ibm** [kubeflow/kubeflow#6886]
/kind bug

**What steps did you take and what happened:**
From the central dashboard notebooks page, click "new notebook"
Give the notebook an name and click "Custom Image"
DO NOT SET AN IMAGE NAME
Click "Launch" (Which is now enabled)

The new notebook, and any existing notebooks disappear from the notebooks list, a appears saying "An error occurred in the backend"

The Jupyter-web-app-deployment pod in the kubeflow namespace has repeated messages similar to this in it.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/src/apps/common/routes/get.py", line 47, in get_notebooks
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/routes/get.py", line 47, in <listcomp>
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/utils.py", line 135, in notebook_dict_from_k8s_obj
    "image": cntr["image"],
KeyError: 'image'
```

The problem can be resolved by deleting the notebook with the missing container image.
`kubectl delete notebook xxx -n namespace`

Other kubeflow users are not impacted by the error.

**What did you expect to happen:**
The UI or backend should prevent the creation of the invalid notebook.

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: v1.6.0
- kfctl version: N/A
- Kubernetes platform: kubernetes
- Kubernetes version: 
clientVersion:
  buildDate: "2022-09-21T13:19:24Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/ppc64le
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-09-21T13:12:04Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/ppc64le
- OS: Red Hat Enterprise Linux 8.4

**Comment by kimwnasptd** [comment]
@ntl-ibm thanks for raising this. I think there are actually 2 improvements to make here, similar to what you suggested:
1. The frontend, as a client, should not allow users to create an "invalid" Notebook
2. The Notebook Controller should have a validation webhook and decline the creation of the notebook in the first place, if it knows that it's invalid

For the second part we have a PR in-flight https://github.com/kubeflow/kubeflow/pull/6734

For the frontend, @elenzio9 with the reform we did on the JWA form do we have any extra validator for the custom image field?

**Comment by neggert** [comment]
We just had a user run into this, so the issue is still present in Kubeflow 1.7.0.

**Comment by thesuperzapper** [comment]
Just wanted to say, we can solve this issue at the CRD level, by just changing the CRD spec so that Kubernetes will reject Notebooks where `spec.template.spec.containers[*].image` is not defined.

We should probably check if messing with any other parts of the Notebook spec also causes crash loops and requires those fields to be set too.

**Comment by mishraprafful** [comment]
I don't think the solution is as simple as adding the validation in the CRD, as these CRDs are getting generated using Kubebuilder from https://github.com/kubeflow/kubeflow/blob/c834f606a9ccdd18689103f745036eb94af48d67kubeflow/components/notebook-controller/api/v1/notebook_types.go, and this is just importing the Kubernetes Podspec https://github.com/kubeflow/kubeflow/blob/c834f606a9ccdd18689103f745036eb94af48d67/components/notebook-controller/api/v1/notebook_types.go#L33

And it's not possible to add CRD validation on the `image` or `container` (nested fields) . Adding a validation webhook or a custom validation logic might be the way to go here 🤔

What are your thoughts?

**Comment by kimwnasptd** [comment]
picking this up

**Comment by mishraprafful** [comment]
@thesuperzapper As discussed on our community call, #7495 should fix it.
