### ISSUE TITLE
Kubeflow do not work in air gap environment 

### ISSUE THREAD

**Issue by vivekjainmaiet** [kubeflow/kubeflow#6919]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jbottum** [comment]
@vivekjainmaiet thanks for raising this issue.   I am going to re-categorize this issue as a feature request.   Per the Kubeflow Release Team, Kubeflow is supported by the Community in defined configurations with specific dependencies.   At this point, airgapped is not supported by the Community but it is supported by commercial Kubeflow distributions by companies like Arrikto, OneConvergence, Canonical, MavenCodes, Josh Patterson and others.   If you need contacts at those suppliers, please let me know.

/kind feature
/area enterprise-readiness
/priority p2

**Comment by vivekjainmaiet** [comment]
@jbottum if it is possible with Canonical , please share with me for any working guide. I want to try kubeflow for full MLOps with MLflow

**Comment by lehrig** [comment]
@vivekjainmaiet: If you happen to run on IBM Power, we (as IBM) offer air-gapped installs on top of either vanilla Kubernetes or Red Hat OpenShift.

**Comment by jbottum** [comment]
@DomFleischmann @DnPlas  Does Canonical support Kubeflow in an air gapped environment, if so would you please contact @vivekjainmaiet  thanks!

**Comment by Jeet-14** [comment]
@jbottum 
https://ubuntu.com/kubernetes/docs/install-offline

**Comment by juliusvonkohout** [comment]
this issue belongs to kubeflow/manifests. Please create it there if needed

/close

**Comment by thesuperzapper** [comment]
@vivekjainmaiet if you are still looking for a way to use Kubeflow in an air-gapped environment, you could consider deployKF, which has a guide for this specific case:

- https://www.deploykf.org/guides/platform/offline/

But be warned, as there are a lot of images to mirror, there is some manual work required.
