### ISSUE TITLE
GPU issues with kOps-managed cluster

### ISSUE THREAD

**Issue by pmuilu** [kubeflow/kubeflow#6925]
/kind bug

**What steps did you take and what happened:**

We have kOps-managed K8s cluster, and kOps requires that runtime class (nvidia) is defined separately for each pod. Luckily Notebook API supports this, so I've manually edited the Notebook resource and added runtime class there (as unfortunately when launching via Notebook UI, this is not possible).

When the container restarts, I get following error:

```
13:36:45
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
test1-0
13:36:44
Container image "kubeflownotebookswg/jupyter-scipy:v1.6.1" already present on machine
test1-0
```

As you can see, this happens with any image, i.e. it doesn't matter whether the image has GPU support or not. I have a working Jupyter notebook image with CUDA support and it works on the cluster if I launch it manually with kubectl, but I get this same error when I launch it using Notebook controller.

Problem is that the notebook controller fails even before the actual container is launched. Any ideas? I'm not able to find any logs about this. What component is actually throwing that error?

**What did you expect to happen:**

I expect that my container is executed, but it fails before that

**Environment:**

- Kubeflow version: 1.6
- Kubernetes platform: kOps
- Kubernetes version: 1.24.6
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads /priority p2 /area jupyter

@pmuilu  thanks for raising this issue.   you might join the Kubeflow notebooks WG call and ask your question there.   please find the bridge to Thursday's call in the meeting notes, [https://arrik.to/kf-wg-notebooks-notes](https://www.google.com/url?q=https://arrik.to/kf-wg-notebooks-notes&sa=D&source=calendar&usd=2&usg=AOvVaw2hbkHdFd2NytIXwea92qSF)

**Comment by jbottum** [comment]
note - I don't think that the Community formally tested Kubeflow with K8s 1.24

**Comment by ReggieCarey** [comment]
Try using the nvidia GPU operator. It works seamlessly and does not require any special driver install on the GPU nodes. Also consider restarting containerd. Sent from my iPhoneOn Jan 31, 2023, at 07:34, Petteri Muilu ***@***.***> wrote:﻿
/kind bug
What steps did you take and what happened:
We have kOps-managed K8s cluster, and kOps requires that runtime class (nvidia) is defined separately for each pod. Luckily Notebook API supports this, so I've manually edited the Notebook resource and added runtime class there (as unfortunately when launching via Notebook UI, this is not possible).
What I get is:
13:36:45
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
test1-0
13:36:44
Container image "kubeflownotebookswg/jupyter-scipy:v1.6.1" already present on machine
test1-0
As you can see, this happens with any image, i.e. it doesn't matter whether the image has GPU support or not. I have a working Jupyter notebook image with CUDA support and it works on the cluster if I launch it manually with kubectl, but I get this same error when I launch it using Notebook controller.
Problem is that the notebook controller fails even before the actual container is launched. Any ideas? I'm not able to find any logs about this. What component is actually throwing that error?
What did you expect to happen:
I except that my container is executed, but it fails before that
Environment:

Kubeflow version: 1.6
Kubernetes platform: kOps
Kubernetes version: 1.24.4
OS (e.g. from /etc/os-release): ubuntu 20.04

**Comment by pmuilu** [comment]
This actually started to work after we updated to cluster to 1.24.9, probably it needed a reboot or something.
