### ISSUE TITLE
Installation on onprem infra

### ISSUE THREAD

**Issue by Syntax3rror404** [kubeflow/kubeflow#6926]
Hello, i dont know why the installation of kubeflow is so hard. As I can see there is no helm chart available for installing kubeflow on a existing infra. 

I have a k8s cluster based on rke2 (dockerless) with one worker with 3x 3090ti.
Whats the common way to install kubeflow on existing k8s infra. I found kfctl but it looks like this project is dead.

**Comment by ReggieCarey** [comment]
Use Kubeflow Manifests for KF installation. It works well on real K8s onprem deployments. I last used 1.6.0. There was a problem with release 1.6.1. My K8s is close to the latest supported. All based on kustomize and you can tweak the configuration ahead of time - like Dex config, enabling auto profiles, setting custom image sources, etc. Only issue I have is a failing trainingOperator. Sent from my iPhoneOn Jan 31, 2023, at 11:28, Syntax3rror404 ***@***.***> wrote:﻿
Hello, i dont know why the installation of kubeflow is so hard. As I can see there is no helm chart available for installing kubeflow on a existing infra.
I have a k8s cluster based on rke2 (dockerless) with one worker with 3x 3090ti.
Whats the common way to install kubeflow on existing k8s infra. I found kfctl but it looks like this project is dead.

**Comment by Syntax3rror404** [comment]
Thanks :)
