### ISSUE TITLE
URL not updated on documentation page.

### ISSUE THREAD

**Issue by Rstar1998** [kubeflow/kubeflow#6980]
This url is not working on this documentation page (https://www.kubeflow.org/docs/components/pipelines/v1/overview/caching-v2/)

[url](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.create_run_from_pipeline_package)

**Comment by kimwnasptd** [comment]
cc @zijianjoy

**Comment by zijianjoy** [comment]
Thank you for bringing this up! The newer link should be https://kubeflow-pipelines.readthedocs.io/en/master/source/client.html?h=create_run_from_pipeline_package#kfp.client.Client.create_run_from_pipeline_package if I understand correctly.

/assign @connor-mccarthy to confirm.

**Comment by connor-mccarthy** [comment]
Thanks, @zijianjoy! We can use the v1 "stable" reference docs page: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.client.html#kfp.Client.create_run_from_pipeline_package

The linked PR addresses this issue throughout the docs.
