### ISSUE TITLE
Katacoda Demo Scenario Python incompatibility - Warning

### ISSUE THREAD

**Issue by ssabat** [kubeflow/kubeflow#70]
I was able to deploy demo scenario developed by Katacoda. 

In this scenario, you learn how to deploy different Machine Learning workloads using Kubeflow and Kubernetes. The interactive environment is a two-node Kubernetes cluster allowing you to experience Kubeflow and deploy real workloads to understand how it can solve your problems.

The Kubeflow project is dedicated to making Machine Learning on Kubernetes easy, portable and scalable. 

I went thru 7 steps and final result is below.
NAME                               READY     STATUS      RESTARTS   AGE
example-job-master-legq-0-xr9wm    0/1       Completed   0       17m
example-job-ps-legq-0-ddk8g        1/1       Running     0       17m
example-job-ps-legq-1-mdrzw        1/1       Running     0       17m
example-job-worker-legq-0-5gzsh    1/1       Running     0       17m
jupyter-admin                      1/1       Running     0       12m
model-client-job-katacoda-z7bq6    0/1       Completed   0       17s
model-server-584cf76db9-5cvw9      1/1       Running     0       19m
model-server-584cf76db9-g4dq6      1/1       Running     0       19m
model-server-584cf76db9-xzcc8      1/1       Running     0       19m
tf-hub-0                           1/1       Running     0       19m
tf-job-operator-6f7ccdfd4d-k8qw9   1/1       Running     0       19m
ed | tail -n1 |  tr -s ' ' | cut -d ' ' -f 1) grep Complet
D1225 16:55:43.428628983       1 ev_posix.c:101]Using polling engine: poll
E1225 16:55:48.380718591       1 chttp2_transport.c:1810]close_transport: {"created":"@1514220948.380687479","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}
outputs {
  key: "classes"
  value {
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 5
      }
    }
    string_val: "comic book"
    string_val: "rubber eraser, rubber, pencil eraser"
    string_val: "coffee mug"
    string_val: "pencil sharpener"
    string_val: "envelope"
  }
}
outputs {
  key: "scores"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 5
      }
    }
    float_val: 8.31655883789
    float_val: 5.18350791931
    float_val: 4.77944898605
    float_val: 4.31814956665
    float_val: 4.29243946075
  }
}

If you know basics of Linux and Jupyter, it is easy to get thru the steps. I found only one WARNING for Python incompatibility between versions 3.5  ( libraries ) and 3.6 ( master/worker versions) while running "Hello Tensorflow!" code in my Jupyter notebook. But, the demo completed fine. 

Thanks,

Sunil Sabat

**Comment by jlewi** [comment]
Thanks for the report. Can you clarify where you get the WARNING? What libraries are you referring to?

**Comment by BenHall** [comment]
Thank you for letting us know.

This is a warning that is shown the first time the Tensorflow snippet is run via Jupyterhub. We (Katacoda) will look into why the errors occur and what a fix could be.

/cc @basiafusinska

**Comment by jlewi** [comment]
@BenHall  Thank you!

**Comment by jlewi** [comment]
@BenHall Any idea if this has been fixed?

**Comment by BenHall** [comment]
@jlewi Yes, I believe so as I can't reproduce the problem.
