### ISSUE TITLE
kubeflow update story

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#700]
Getting started with Kubeflow is easy. We don't have a good story for "updating" kubeflow from version A to version B. 

The https://github.com/kubeflow/testing/tree/master/dev-kubeflow-org folder has a couple of bash scripts to update kubeflow - we can use those as starting points to see what is a good story for update.

**Comment by pdmack** [comment]
What's our thoughts on `ks upgrade`? I think I have used it once or twice in traveling from 0.8 up to 0.9.2. Important step?

**Comment by ankushagarwal** [comment]
I think ks upgrade is used to upgrade ksonnet application format according to their latest format. For example in an earlier version they used `spec.json` to track environments and now they've migrated that info to `app.yaml`. I don't think it upgrades the actual ksonnet application by pulling in the latest packages/prototypes etc.
