### ISSUE TITLE
Authservice pod "Failed to save state in store: error trying to save session: input/output error"

### ISSUE THREAD

**Issue by psheorangithub** [kubeflow/kubeflow#7042]
/kind bug

We have integrated kubeflow with OIDC flow(Heracles+LDAP)We are unable to login to kubeflow UI. GUI throws below error.

Access to kubeflow.aiwb-enc-data-cpu1.uscentral-prd-az3.k8s.int was deniedYou don't have authorization to view this page.
HTTP ERROR 403

While checking the authservice pod logs, I see below error. It happens every couple of days.

2023/03/15 14:08:40 boltstore: remove expired sessions error: input/output error
time="2023-03-15T14:06:29Z" level=error msg="Failed to save state in store: error trying to save session: input/output error" ip= request=/

The issue resolves after restarting authservice pod but it re-appear after every 10-15 days. We have checked the underlying PVC status, it looks healthy.

Can someone look into it and suggest what could be the cause

**Environment:**

- Kubeflow version: 1.6
- kfctl version: (use `kfctl version`):
- Kubernetes platform: on-prem
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): centos

**Comment by MiraiChino** [comment]
We are experiencing the same issue with our Kubeflow deployment that uses Dex and LDAP for authentication. Upon attempting to access the Kubeflow URL, we face a recurring 403 error. The Kubeflow environment has 6 users, and they encounter this issue on the Kubeflow login page approximately every 4 to 5 days.

The following error is observed in the logs of the `authservice-0` pod within the `istio-system` namespace:
``` console
# kubectl logs authservice-0 -n istio-system
...
{"log":"time="..." level=error msg="Failed to save state in store: error trying to save session: input/output error" ip=... request=/jupyter/api/namespaces/.../notebooks\n","stream":"stderr","time":"..."}
```

We have inspected the resource usage of the `authservice-0` pod and found no anomalies. CPU and memory consumption appear to be normal:

``` console
# kubectl top pod authservice-0 -n istio-system
NAME            CPU(cores)   MEMORY(bytes)   
authservice-0   1m           8Mi     
```

We have also checked the status of the persistent volume claim (PVC) associated with the `authservice-0` pod and found that it contains the expected data:
``` console
# ls -lh /export/kubernetes/istio-system-authservice-pvc-pvc-4a8228e9-2b6d-456c-9a7a-f9fbf8d9a209/
total 112K
-rw-r--r-- 1 systemd-network tss 128K Jul 19 09:06 data.db
```

As a temporary workaround, we have tried deleting the `authservice-0` pod, and it automatically gets recreated. After this, the Kubeflow Dex login page is accessible again.


**Environment:**

- Kubeflow version: kubeflow v1.4.1 with Dex + LDAP
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`): On-premise
- Kubernetes version: (use `kubectl version`): v1.19.2
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

Any insights or suggestions to resolve this persistent 403 error on the Kubeflow login page would be highly appreciated.

**Comment by MiraiChino** [comment]
**Additional Content:**
After setting the log level of `oidc-authservice` to DEBUG, I rechecked the logs when the error occurred again. I discovered that [the error](https://github.com/yosssi/boltstore/blob/36632d49165582dba58e99530427757c5279ce84/reaper/reaper.go#L134) is related to [boltstore/reaper](https://github.com/arrikto/oidc-authservice/blob/master/sessions/boltdb.go#L11C3-L11C37), which is responsible for releasing unnecessary resources, rather than using [boltdb](https://github.com/boltdb/bolt) for session management.

```
2023/08/01 03:22:10 boltstore: remove expired sessions error: input/output error
time="2023-08-01T03:22:57Z" level=warning msg="Request doesn't have a valid session." ip=192.168.200.15 request=/logout
time="2023-08-01T03:22:57Z" level=error msg="Failed to save state in store: error trying to save session: input/output error" ip=192.168.200.15 request=/
```

**Comment by ben-omji** [comment]
I got the same issue.
First encounter with this problem in 70 days of creating the `oidc-authservice` pod.
