### ISSUE TITLE
notebook nvidia-smi command show nothing

### ISSUE THREAD

**Issue by tvtv511** [kubeflow/kubeflow#7045]
centos7.9
k8s v1.24.11+rke2r1
gpu opearator
nvidia A100 40G

After the installation is complete, I exec nvidia-smi command in nvidia-driver-daemonset.

![image](https://user-images.githubusercontent.com/128216397/226094372-2242f15e-77d4-42f0-8d6a-07c9b0912a14.png)

When I create notebook and connect to noteserver book. 
Nvidia-smi command show nothing.

![image](https://user-images.githubusercontent.com/128216397/226094510-91954d3c-3056-4421-96f6-644414121573.png)

someone knows?

image:
arashilen/jupyter-pytorch-cuda-full-root

msg:

![image](https://user-images.githubusercontent.com/128216397/226096415-67eee14f-4e00-4dfa-96ee-4e72181b376f.png)

error msg:

error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "a80d2f4b2cf94a8c29053d62ee2c17088b9b672152285604bb284abbf096e1e8": OCI runtime exec failed: exec failed: unable to start container process: exec /usr/bin/nvidia-smi: exec format error: unknown

installation instructions:

helm install --wait --generate-name \
     -n gpu-operator --create-namespace \
     nvidia/gpu-operator \
     --set toolkit.version=1.7.1-centos7  --set mig.strategy=mixed \
    --set toolkit.env[0].name=CONTAINERD_CONFIG \
    --set toolkit.env[0].value=/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl \
    --set toolkit.env[1].name=CONTAINERD_SOCKET \
    --set toolkit.env[1].value=/run/k3s/containerd/containerd.sock \
    --set toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS \
    --set toolkit.env[2].value=nvidia \
    --set toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT \
    --set-string toolkit.env[3].value=true

**Comment by uzmargomez** [comment]
hey, I'm having the same issue, I see this marked as fixed, any idea what's the problem?
