### ISSUE TITLE
initContainers support with podDefaults

### ISSUE THREAD

**Issue by Jeet-14** [kubeflow/kubeflow#7058]
/kind feature

**Why you need this feature:**
[initContainers can be use to pull code from repo for every notebook being created, adding this to podDefaults will ensure it will applied to all the notebooks/workbenches]

**Describe the solution you'd like:**
[Currently we can set env var, volumes that will be applied to all notebook pods, would like to have initContainer as a part of podDefaults ]

**Comment by kimwnasptd** [comment]
Hey @Jeet-14, @deepk2u had done some great work implementing this in #6745. This feature will be available in KF 1.7
