### ISSUE TITLE
Please add/install "openssh-client" as one useful linux package in "components/example-notebook-servers/base/Dockerfile"  

### ISSUE THREAD

**Issue by jianwu-github** [kubeflow/kubeflow#7070]
From launched Code Server (kubeflownotebookswg/codeserver-python:v1.6.1) at Kubeflow 1.6.1 running on EKS,  I tried to clone private github repo from a code server terminal, it failed with error "cannot run ssh: No such file or directory" as:
```
(base) jovyan@codeserver-2-efs-vols-03-0:~$ git clone git@ghe.tusimple.io:jian-wu/deep-monet.git
Cloning into 'deep-monet'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

It would be nice that "openssh-client" would be installed and available in  "kubeflownotebookswg/codeserver-python:v1.6.1", the private github repo can be cloned without problem.

**Comment by juliusvonkohout** [comment]
Feel free to create a PR and join the notebooks wg meeting
