### ISSUE TITLE
Tensorboard Fails to launch when the user Profile specifies resourceQuotaSpec

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/kubeflow#7077]
/kind bug

**What steps did you take and what happened:**

Logged in to Kubeflow.
Created a Tensorboard using the UI.
Tensorboard Pod Deploys into Namespace.
Deleted the Tensorboard
All is good

As an administrator, I edited user `Profile` to include resource quotas for CPU and Memory.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/10270182/228953134-1e3f3d6a-c0cf-492c-8aa3-baf82e2af3bd.png">

This results in a `kf-resource-quota` object being created in the Profile namespace

Created a TensorBoard using the UI.
The Tensorboard Pod Fails to deploy into the Namespace.
The Deployment for the Tensorboard Pod reports "ReplicaFailure"

<img width="830" alt="image" src="https://user-images.githubusercontent.com/10270182/228950743-5eb68f47-9023-406c-ac20-c9eb7c28b3f6.png">

All is not good

**What did you expect to happen:**

I expected the TensorBoard Pod to spin up into the Namespace.

**Anything else you would like to add:**

The cause of the problem is that the generated Deployment for the Tensorboard does not contain resource limits.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/10270182/228950399-971aa0a4-79ef-4168-9dab-691a4bb4f9c3.png">

This is shown in the event logs for the Tensorboard I tried to spin:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/10270182/228951237-88fc179f-6bf5-4178-bdef-46402e30d09b.png">

I think the root problem is that the code `tensorboard_controller.go` which apparently creates the Deployment for a Tensorboard Pod does not include a `resources` block (which is best practice):

<img width="782" alt="image" src="https://user-images.githubusercontent.com/10270182/228952678-6d984ee3-3d12-481d-9a67-b3001a7dc23a.png">

Several possible solutions I propose:
1) Have the Dashboard Tensorboard UI allow specification of resource limits similar to Dashboard Notebook UI.
2) Specify default resource limits in a users Profile
3) Configure hard coded values in the code that generates the Deployment resource
4) Utilize a mutating webhook to inject resource limits into pods that have none.

I suspect the correct answer is some combination of 1 2 and 3 above.  Users should be able to provide this info.  The UI needs some defaults that Kubeflow administrators can specify. The code should pull values from the UI if specified, then from the Profile if specified, and finally a default value (possibly hard coded) pulled from a configmap.

It would be nice to have a fast temporary fix in the form of a mutatingwebhook that injects the appropriate values.

**Environment:**

- Kubeflow version: 1.6.0
- Kubernetes platform: kubeadm
- Kubernetes version: 1.25.4
- OS 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by komalkotha** [comment]
you can create a limit range in your namespace with kubernetes yaml  this may solve your problem . it got resolved for me 

```
apiVersion: v1
kind: **LimitRange**
metadata:
  name: default
spec:
  limits:
    - default:
        cpu: xxxx
        memory: xx
      defaultRequest:
        cpu: xxx
        memory: xxx
      type: Container

```

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
