### ISSUE TITLE
Add env parameters to the compilation process

### ISSUE THREAD

**Issue by okonmarcin** [kubeflow/kubeflow#7089]
/kind feature

**Why you need this feature:**
In my pipelines I have two types of parameters:
1. Business related params (the ones that users should populate from the UI)
2. Env related params (the ones that should be populated during pipeline compilation and CI/CD process)

This is how I compile pipelines today:
```     
    kfp.compiler.Compiler().compile(
            pipeline_func=pipeline.pipeline,
            package_path=compiled_pipeline_name,
            pipeline_parameters={
               ...
            }
        )
```

**Describe the solution you'd like:**
Ideal solution would be to compile pipeline like this:

```     
    kfp.compiler.Compiler().compile(
            pipeline_func=pipeline.pipeline,
            package_path=compiled_pipeline_name,
            pipeline_parameters={
               ...
            },
            pipeline_static_parameters: {
                'key1': 'value1',
                'key2': 'value2'
            }
        )
```

and any occurrence of 'key1' would be replaced with 'value1'. This would give us possibility to compile the pipeline with some env values related to particular server/repo whatever.

**Anything else you would like to add:**
Right now we use placeholders anyway and then we replace them in compiled yaml, which is kind of breaking encapsulation of the compiling and we would like it to be more systematic and robust way.

**Comment by juliusvonkohout** [comment]
this is for Kubeflow/pipelines

/close
