### ISSUE TITLE
Issue with installing kubeflow on Openshift CodeReady Container

### ISSUE THREAD

**Issue by MaxBlanck** [kubeflow/kubeflow#7096]
I have issues installing kubeflow on my local crc openshift cluster. When execuring the command:

`while` ! kustomize build openshift/example/istio | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; `done`

I receive the following error message. Could you please help me out.

`➜  manifests git:(v1.6-branch-openshift) ✗ while ! kustomize build openshift/example/istio | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done                                         

2023/04/14 16:21:09 well-defined vars that were never replaced: VWA_USERID_HEADER,podDefaultsDeploymentName,podDefaultsNamespace,user,JWA_CLUSTER_DOMAIN,JWA_USERID_HEADER,PROFILES_NAMESPACE,VWA_PREFIX,podDefaultsCertName,CD_NAMESPACE,JWA_NAMESPACE,VWA_CLUSTER_DOMAIN,podDefaultsServiceName,secretAccessKey-bas64,CD_CONFIGMAP_NAME,bucket-base64,endpoint-base64,kfp-app-version,kfp-namespace,KATIB_NAMESPACE,KATIB_UI_NAMESPACE,clusterDomain,profile-name,CD_CLUSTER_DOMAIN,JWA_USERID_PREFIX,KATIB_SERVICE_NAME,kfp-app-name,CD_USERID_PREFIX,JWA_PREFIX,KATIB_CERT_NAME,JWA_UI,VWA_NAMESPACE,kfp-artifact-bucket-name,kubelet-path,kfp-default-pipeline-root,namespace,CD_REGISTRATION_FLOW,CD_USERID_HEADER,VWA_USERID_PREFIX,accessKeyID-base64
Error: considering field 'spec/template/spec/containers/*/args/2' of object DaemonSet.v1.apps/istio-cni-node.kube-system: visit traversal on path: [* args 2]: fieldName: *: wildcard is not supported in PathGetter
error: no objects passed to apply
Retrying to apply resources`

**Comment by matt314** [comment]
We're seeing the same thing on an OCP 4.12 cluster.

**Comment by juliusvonkohout** [comment]
Please use 1.7/1.8

**Comment by utsumi-fj** [comment]
@juliusvonkohout 

>Please use 1.7/1.8

I think that Kubeflow 1.7/1.8 are not supported on OpenShift. Is this correct ?

In [this page](https://www.kubeflow.org/docs/started/installing-kubeflow/#legacy-distributions), `Latest Relase` of `Kubeflow OpenShift` is `1.6.0`.
And, [the manifests for installing Kubeflow on OpenShift](https://github.com/opendatahub-io/manifests) described in [this page](https://v1-6-branch.kubeflow.org/docs/distributions/openshift/install-kubeflow/) do not have the branches for Kubeflow 1.7/1.8.

Is there a way to install Kubeflow 1.7/1.8 on OpenShift ?

**Comment by utsumi-fj** [comment]
When I tried, this error was resolved by changing the kustomize version to [3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0).
See [prerequisites for Kubeflow 1.6.0](https://github.com/kubeflow/manifests/tree/v1.6.0#prerequisites).

**Comment by juliusvonkohout** [comment]
Kubeflow definitely works on openshift. I supported it commercially for years. But you need to have a bit of Kubernetes knowledge and use istio-cni. The more secure (runasnonroot ) we become the better it will work by default.

**Comment by juliusvonkohout** [comment]
Kubeflow definitely works on openshift. I supported it commercially for years. But you need to have a bit of Kubernetes knowledge and use istio-cni. The more secure (runasnonroot ) we become the better it will work by default.

And there is also https://github.com/kubeflow/manifests/issues/2449#issuecomment-1740232430

**Comment by utsumi-fj** [comment]
@juliusvonkohout Thanks a lot for your reply !
