### ISSUE TITLE
[Security] Privately disclosed vulnerabilities in Kubeflow

### ISSUE THREAD

**Issue by DanMcInerney** [kubeflow/kubeflow#7101]
/kind bug

I have privately disclosed 2 vulnerabilities in the Kubeflow web server via Slack channel to @Ark-kun, @jessiezcc, @IronPan, and Pavel Dournov as it's in the <server>/pipelines/artifacts section of the application. Please let me know if these are the correct maintainers.

- Kubeflow version: 1.7.0

**Comment by DanMcInerney** [comment]
Not sure if this is dashboard or pipelines issue so I added @prodonjs and @avdaredevil to the slack message.

**Comment by avdaredevil** [comment]
I believe that is KFP. Also neither of us are active / passive maintainers of this application at this point. So slack might still be your best bet!

**Comment by juliusvonkohout** [comment]
/close

Yes KFP repository it is

**Comment by juliusvonkohout** [comment]
Otherwise feel free to join the security WG
