### ISSUE TITLE
models icon (kserve) not inheriting iron icon colors

### ISSUE THREAD

**Issue by ianonavy** [kubeflow/kubeflow#7111]
/kind bug

There is a problem with the way Kubeflow renders the models icon where it does not correctly inherit the colors. This is mentioned in https://github.com/kubeflow/kubeflow/pull/6656, but the workaround is insufficient to solve the root cause.

**What steps did you take and what happened:**

1. Navigate to Home
2. Observe the color of the KServe icon (black, although the rest are gray)
![screenshot of the sidebar for Kubeflow showing KServe's icon is black and the rest are gray](https://user-images.githubusercontent.com/790279/235245109-68c3000d-0b08-46b1-baf1-8ff44d25e9a4.png)
3. Navigate to KServe Endpoints
4. Observe the color of the KServe icon (black, should have changed to white)
![screenshot of the Kubeflow navbar showing the KServe icon in the active state is black](https://user-images.githubusercontent.com/790279/235245191-1a43403c-8855-4067-b5ec-ffb1139f8dbe.png)

**What did you expect to happen:**
The SVG should inherit the icon color from CSS in both the inactive and active state.
![screenshot of the Experiments KFP active state showing the icon is white](https://user-images.githubusercontent.com/790279/235245247-58d70ce6-a45a-46e7-aa1c-63837be3cb35.png)

**Anything else you would like to add:**
I put this SVG into Figma, flattened the paths and re-exported. Now it works:

```svg
<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;">
<path d="M2.20122 12.2692C1.93293 12.0307 1.93293 11.8319 2.20122 11.6729L6.35976 8.0954C6.58333 7.9364 6.82927 7.97615 7.09756 8.21465L7.90244 8.93015C8.0813 9.08915 8.01423 9.2879 7.70122 9.52641L4.88415 12.0307L7.70122 14.5349C7.88008 14.6939 7.88008 14.8927 7.70122 15.1312L7.03049 15.7274C6.71748 16.0454 6.42683 16.0852 6.15854 15.8467L2.20122 12.2692Z" />
<path d="M21.6926 12.3465C22.0512 12.107 22.0961 11.9073 21.8271 11.7476L17.793 8.15401C17.524 7.91444 17.2551 7.95437 16.9861 8.2738L16.0448 9.1123C15.9552 9.27201 16 9.43173 16.1793 9.59144L19.0032 12.107L16.1793 14.6225C16 14.7822 16 14.9818 16.1793 15.2214L16.8517 15.8203C17.1206 16.0599 17.3895 16.0599 17.6585 15.8203L21.6926 12.3465Z" />
<path d="M15.158 13L16 12L15.158 11H8.842L8 12L8.842 13H15.158Z" />
</svg>
```
![screenshot of a working KServe navbar item in inactive state](https://user-images.githubusercontent.com/790279/235245765-cb2d3f50-9172-4af6-a67f-3edcba53e936.png)
![screenshot of a working KServe navbar item in active state](https://user-images.githubusercontent.com/790279/235245787-35edcf3f-9514-4fea-9b13-a3f5b1f53969.png)

**Environment:**

- Kubeflow version: 1.7.0 (also observed in 1.6.1)
- kfctl version: n/a
- Kubernetes platform: EKS
- Kubernetes version: 1.24 (also observed in 1.23)
- OS: n/a

**Comment by ianonavy** [comment]
Just a hunch, but I think the issue was the `<polygon>` element in the [original icon](https://github.com/kubeflow/kubeflow/blob/d0df9b1124fac43b39ded88605466f9f3ed2d004/components/centraldashboard/public/assets/icons/models.svg).

@kimwnasptd @juliusvonkohout for visibility since you were both active in the other PR. :) I would send a PR of my own but at this time I am unable to sign the Kubeflow CLA. Would appreciate a fix if possible so that we don't have to run off a fork. 🙏🏼

**Comment by juliusvonkohout** [comment]
@ianonavy is https://github.com/kubeflow/kubeflow/pull/7113 fine ?

**Comment by ianonavy** [comment]
@juliusvonkohout Yes, looks good to me! Thanks for the quick fix.
