### ISSUE TITLE
Support for services run in a notebook

### ISSUE THREAD

**Issue by Naegionn** [kubeflow/kubeflow#7112]
/kind question

**Question:**

I would like to use https://github.com/voxel51/fiftyone  as a notebook on kubeflow.
This does require web application to be made accessible.
Is there a way to achieve this with Kubeflow like customizing pod, service and ingress for a notebook?

**Comment by oguzhanoyan** [comment]
Hello, In my opinion, you have a chance to do a run as a notebook on Kubeflow, when I quickly look, I saw that; 

1.  You should create a container image based on [this](https://docs.voxel51.com/environments/index.html#docker) section
2. Also when you create an image, make sure that the user is [jovyan](https://docs.voxel51.com/environments/index.html#docker), you can refer [here](https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/base/Dockerfile)[1]
3. Then you should change the running web port based on [here](https://www.kubeflow.org/docs/components/notebooks/container-images/#image-requirements:~:text=interface%20on%20port-,8888,-%3A)
4. Also you should care of the header, We are running Kubeflow on GKE, and if the application does not allow you to define the header may you can use [here](https://cloud.google.com/load-balancing/docs/https/custom-headers)
5. Last persistent volume


If this feature request is denied, I hope this quick walkthrough help.

**Comment by Naegionn** [comment]
I am not sure if this helps, maybe i should have mentioned that I need to have the web application accessible in addition to the notebook webserver. So I cant just route the web app to the standard notebook port.

**Comment by juliusvonkohout** [comment]
/close

You can also use the jupyter server proxy
