### ISSUE TITLE
[openmpi] Move openmpi-controller image to Kubeflow registry

### ISSUE THREAD

**Issue by jiezhang** [kubeflow/kubeflow#712]
The openmpi-controller image should be moved to Kubeflow official registry:
https://github.com/kubeflow/kubeflow/blob/master/components/openmpi-controller/Makefile

**Comment by everpeace** [comment]
Yes, I think it should be, too.

**Comment by jlewi** [comment]
Why is this blocked by #197? We should be able to start publishing it to Kubeflow's GCR registry
gcr.io/kubeflow-images-public
even before Kubeflow starts publishing images to DockerHub.

**Comment by jiezhang** [comment]
@jlewi I'm getting this error:
```
docker push gcr.io/kubeflow-images-public/openmpi-controller:0.0.3
The push refers to a repository [gcr.io/kubeflow-images-public/openmpi-controller]
576a115241e1: Preparing
8edc90048168: Preparing
43c8cf1908a6: Preparing
8a8ee4bd31c6: Preparing
31f8aa385131: Preparing
9650e1239c3e: Waiting
f04225383530: Waiting
f186354f2c39: Waiting
90b8c3cde875: Waiting
fbbeadfbd3ca: Waiting
0f6f641d80ca: Waiting
76a66da94657: Waiting
0f3a12fef684: Waiting
denied: Token exchange failed for project 'kubeflow-images-public'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
make: *** [push] Error 1
```

**Comment by jlewi** [comment]
@jiezhang You won't have permission to publish it to that repository.

We have some instructions here:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

You should define an Argo workflow to build your images using docker in docker. You can then follow the instructions on that page to add it to our nightly builds.

**Comment by jlewi** [comment]
Postsubmits can now publish images to our public repo

Follow these instructions to set that up.
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

**Comment by jlewi** [comment]
Downgrading to P2.

Current thinking is that users are better off using MPIJob
https://github.com/kubeflow/kubeflow/issues/778#issuecomment-429847288

And the current thinking is to eventually remove the OpenMPI package in favor of the MPIJob
kubeflow/website#272 to update the docs.
#1859 to remove the existing package.

So I'm downgrading this to P2.
