### ISSUE TITLE
[openmpi] Upload trained models to persistent storage 

### ISSUE THREAD

**Issue by jiezhang** [kubeflow/kubeflow#713]
We should take snapshots of the trained models generated by the MPI workers and upload them to persistent storage (say S3 or Google Cloud Storage).

Here're the changes needed:
1. `kubeflow-openmpi-data` is currently mounted as a shared volume between the `openmpi-job` container and `openmpi-controller` container. We need to make the size configurable.
1. When `openmpi-controller` detects that the master pod has terminated, it should upload the files in the shared mount point to persistent storage.
1. Make the persistent storage configurable.

**Comment by jiezhang** [comment]
cc @alsrgv @jlewi @everpeace

**Comment by jlewi** [comment]
@balajismaniam Is this an area where KVC could help?

**Comment by balajismaniam** [comment]
Yes @jlewi. @jiezhang are the features in kvc sufficient for this? KVC supports any S3 compatible storage (e.g., AWS S3, GCS, Minio).

**Comment by jiezhang** [comment]
@jlewi @balajismaniam Thanks for the pointer! I'll evaluate whether we could leverage KVC.
