### ISSUE TITLE
MLRun documentation all hyperlinks are inactive

### ISSUE THREAD

**Issue by mousam-singh** [kubeflow/kubeflow#7131]
MLRun documentaion link on Kubeflow documentation: https://www.kubeflow.org/docs/external-add-ons/serving/mlrun/

Referenced inactive link: https://docs.mlrun.org/en/latest/serving/build-graph-model-serving.html

**Comment by juliusvonkohout** [comment]
/close

This is not the website repository. Please open an issue there
