### ISSUE TITLE
Security Tag Needed for Kubeflow Project Repositories

### ISSUE THREAD

**Issue by akgraner** [kubeflow/kubeflow#7136]
/kind feature

**Why you need this feature:**

Kubeflow needs a "security" tag so that users can open security issues or PRs and tag them as security.  This way each of the WGs and the Kubeflow Security Team can see, track those and work on getting those fixed. 

The sooner we have this, the sooner we can test the Security Policies and Procedures we have in place. 

Thanks! 

@james-jwu

**Comment by james-jwu** [comment]
As noted in [this comment](https://github.com/kubeflow/kubeflow/pull/7043#discussion_r1195398442), security tag is not recommended. We can create a security@kubeflow.org email address as you noted in the comment. Would that work?

**Comment by akgraner** [comment]
@james-jwu  - yes, that would work.  What do you need from me?  The names and email addresses of those who need to be alerted when someone sends an email to security@kubeflow.org? Do you want those added here, emailed, or in a folder in the security directory? Just let me know.  THANK YOU!! :-)

**Comment by james-jwu** [comment]
I think we just need to create a file like this, and it will get automatically sync'd (fingers crossed) into Google workspace: https://github.com/kubeflow/internal-acls/blob/master/google_groups/groups/calendar-admins.yaml

**Comment by akgraner** [comment]
@james-jwu sure! In the meantime as a placeholder below is the list of those who will be on the list: 

@akgraner 
@jbottum 
@johnugeorge 
@andreyvelich 
@kimwnasptd 
@annajung 
@difince 

There's a few more people to add as well and I'll send over the PR after the Security Team Meeting today. Thanks!!

**Comment by andreyvelich** [comment]
We can create a dedicated GitHub team.

**Comment by tarilabs** [comment]
and populate the security policy .md at : https://github.com/kubeflow/kubeflow/security so to instruct people to reach for that team 👍
