### ISSUE TITLE
Create a new "What is Kubeflow" Presentation

### ISSUE THREAD

**Issue by akgraner** [kubeflow/kubeflow#7137]
/kind feature

**Why you need this feature:**

As we were going through the CNCF transition process and the Due Diligence document,  we realized we don't have a public "What is Kubeflow" presentation that can be used by the Community.  This presentation would be about 20 mins in length. 

@akgraner and @thesuperzapper have started this process. If you would like to help please let me know. Once I have the working deck and outline I'll update this Issue with the link. 

@jbottum

**Comment by farshadghodsian** [comment]
I know this is several months old, but I may be able to help with this presentation as I've done several "What is Kubeflow / Why use Kubeflow?" both internally at my company and to prospective large Enterprise clients. I can also help contribute some slides around key benefits and features of Kubeflow. Let me know.

**Comment by akgraner** [comment]
Thank you so much. We’re working on this and we’d be happy to add you to
the group working on this. Would you like me to add you?

With gratitude,
~Amber

**Comment by farshadghodsian** [comment]
Yes, please do. Will do my best to meaningfully contribute where I can.

**Comment by akgraner** [comment]
Thank you!!

**Comment by andreyvelich** [comment]
We can close it.
