### ISSUE TITLE
Update kubectl and code-server version on Notebook-'codeserver-python:v1.7.0'

### ISSUE THREAD

**Issue by Jeet-14** [kubeflow/kubeflow#7139]
As mentioned in Dependency Versions Kubeflow 1.7 is targeting k8s version 1.25/1.24.

However, 

Notebook image `kubeflownotebookswg/codeserver-python:v1.7.0 `is having kubectl v1.21.0 with `ARG KUBECTL_VERSION=v1.21.0` in dockerfile
as per the version skew policy (https://kubernetes.io/releases/version-skew-policy/#kubectl) kubectl version should be 1.24/1.25. 

and latest code-server version is v4.12.0 where as dockerfile is using `CODESERVER_VERSION=v4.3.0`

Currently both are hard-coded into dockerfile. While building custom image with required packages and software with desired version is always possible, it would be great if upstream images it self are updated one.

**Comment by juliusvonkohout** [comment]
Please create a PR and join the notebooks wg meeting

**Comment by juliusvonkohout** [comment]
/close

We now have a PR for that
