### ISSUE TITLE
Use python code imported from a pvc

### ISSUE THREAD

**Issue by KaulitzGuimaraes** [kubeflow/kubeflow#7142]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

I started a migration from airflow to kubeflow recently and my idea it was use the same way we do to push our code when a task starts.
We zip our code and push to a pvc , this pvc is attached to the airflow operator, so when the pod initiate , the pvc contains the code

I tried push the same code, with no zip , only the code to a pvc to the component, when I tries to use something like

```python
import mypackage.mycode

```
It doesn't recognise , I have run some tests using the ```ls``` command to check if code is there in the appropriated directory, I could see it, but I can't Import

I have used the same code , with same package structured , but instead to push to a pvc, I added to a docker image and it works, but I'd like to use this code inside a PVC since build and push images to cloud  takes too long 
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
I guess that the problem is with the order that the code is compiled in kubeflow when it triggers a component task, perhaps attach the pvc and compile the code after may help. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by juliusvonkohout** [comment]
/close

Please check out the kfp repository

**Comment by KaulitzGuimaraes** [comment]
@juliusvonkohout I already checked, not sure how this helps with this issue
