### ISSUE TITLE
Notebook provisioning Python SDK

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/kubeflow#7154]
/kind feature

**Why you need this feature:**
Filling out the notebook provisioning form in the central dashboard can be painful, time-consuming, and error-prone. 

A notebook provisioning SDK would provide programmatic notebook (and PVC) config definitions and CRUD capabilities.

In theory, data scientists could author Notebook CRs (and their dependent PVCs) directly, but the process is complex and difficult, and doesn't have the benefit of intellisense that well-documented Python code has.

**Describe the solution you'd like:**
I've already implemented a notebook and PVC Python SDK for our internal distro. It provides a `Notebook` and `Volume` class to store notebook and PVC configuration, respectively, and a `NotebookClient` and `VolumeClient` to conduct CRUD operations. Authentication simply consumes the kube config.

By decoupling configuration from CRUD, this pattern lets users store notebook configurations that can be recycled and distributed, promoting reusability.

The `NotebookClient` supports `create`, `list`, `get`, `stop`, `resume`, `delete`, and `delete_all` methods. It includes comprehensive unit tests.

I'd be happy to contribute it upstream pending approval / input from maintainers.

Thanks!

**Comment by juliusvonkohout** [comment]
Please join the next noteboks WG meeting

**Comment by juliusvonkohout** [comment]
I think you can do so already via API calls.

/close
