### ISSUE TITLE
There is no official example that can be fully run to see the effect of testing the success of the deployment

### ISSUE THREAD

**Issue by wangpf09** [kubeflow/kubeflow#7155]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**There is no official example that can be fully run to see the effect of testing the success of the deployment**
I think a simple example should be added to test whether the deployed kubeflow can do distributed training normally

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by juliusvonkohout** [comment]
/close

There is the e2e testing PR. Feel free to help us with more tests. Just join the manifests WG meeting.
