### ISSUE TITLE
Error: no matches for Id ContainerCluster.v1beta1.container.cnrm.cloud.google.com/kubeflow.[noNs]; failed to find unique target for patch ContainerCluster.v1beta1.container.cnrm.cloud.google.com/kubeflow.[noNs]

### ISSUE THREAD

**Issue by FelixGruener** [kubeflow/kubeflow#7157]
Error: no matches for Id ContainerCluster.v1beta1.container.cnrm.cloud.google.com/kubeflow.[noNs]; failed to find unique target for patch ContainerCluster.v1beta1.container.cnrm.cloud.google.com/kubeflow.[noNs]

Deploy Kubeflow in make apply step . 

I expect there is a ContainerCluster created but when I do 
when I do kubectl get containerclusters --all-namespaces
I get No resources found

I  fixed  manually 
issue with the build/container.cnrm.cloud.google.com_v1beta1_containercluster_kubeflow.yaml file. Specifically, it seems that the metadata.clusterName field is not recognized. Instead of using metadata.clusterName, you should use metadata.name to specify the name of the cluster.

- Kubeflow version: v1.7.0
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8-gke.500", GitCommit:"f117e29cb87cfb7e1de32ab4e163fb01ac5d0af9", GitTreeState:"clean", BuildDate:"2023-03-23T10:22:38Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
client (1.27) and server (1.25)

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
