### ISSUE TITLE
How to update the Tensorboard controller 

### ISSUE THREAD

**Issue by komalkotha** [kubeflow/kubeflow#7158]
Is there any way the tensorboard controller.go can be updated with Configmap. because presently controller.go is using args has _bind_all but as per the requirments we need to change to run the -host 0.0.0.0 

in go code below is the args
```
	Args: []string{
								"--logdir=" + mountpath,
								"--bind_all",
```

Below is the deployment changes needed to run the

```
- args:
        - --logdir=/tensorboard_logs/
        - --host=0.0.0.0
        command:
        - /usr/local/bin/te
```

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
