### ISSUE TITLE
 dial tcp i/o timeout terminating about 1 in 5 of my pods

### ISSUE THREAD

**Issue by amrobbins** [kubeflow/kubeflow#7161]
/kind bug

**What steps did you take and what happened:**
I'm just running my usual pipelines. I found that after my recent upgrade to kubeflow 1.7 that about 1 in 5 of my pods dies with the following error message (I have removed the IP address from the message):

This step is in Error state with this message: Error (exit code 1): Post "https://<IPADDR>:443/apis/argoproj.io/v1alpha1/namespaces/andrew-robbins/workflowtaskresults": dial tcp <IPADDR>:443: i/o timeout

Is it possible to increase the default timeout value here to maybe 45 seconds?

**What did you expect to happen:**
This is a new behavior that I didn't see in previous versions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.7
- kfctl version: N/A
- Kubernetes platform: GKE
- Kubernetes version:

Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.12-gke.500

- OS (e.g. from `/etc/os-release`):

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

(This is google cloud console)

**Comment by markellos-orfanos** [comment]
Happens on GKE 1.25.8-gke.1000 as well

**Comment by juliusvonkohout** [comment]
/close

Seems to be cluster specific
