### ISSUE TITLE
Usage distribution

### ISSUE THREAD

**Issue by tiansiyuan** [kubeflow/kubeflow#7162]
/kind question

**Question:**

How many users are using 1.7.0? how many are using 1.6.1? how many are using other versions?

Thanks,

Siyuan

**Comment by jbottum** [comment]
The Kubeflow user survey results provides some data points on these questions.  We should be releasing it soon.

**Comment by tiansiyuan** [comment]
> The Kubeflow user survey results provides some data points on these questions. We should be releasing it soon.

Thanks. Looking forward to it.
