### ISSUE TITLE
Upgrade K8s to 1.26 for testing in this repo

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#7182]
/kind feature

**Why you need this feature:**
To ensure we test with the agreed k8s version of the KF 1.8 release

**Describe the solution you'd like:**
We'll need to:
1. Create a new kind config file https://github.com/kubeflow/kubeflow/tree/master/components/testing/gh-actions
2. Update the integrate actions we have to use the new config file https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/centraldb_intergration_test.yaml#L37

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
