### ISSUE TITLE
Extensible input validation for Notebook provisioning GUI

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/kubeflow#7193]
/kind feature

**Why you need this feature:**
Every cluster has unique underlying worker nodes and policies. As a result, there's no one size fits all input validation for the notebook provisioning form. The lack of input validation means that users regularly request notebooks that are not actually schedulable, and the feedback loop for that is too long since it requires deciphering what are often opaque messages in the notebook CRs / pod's status and events, which is not exactly an area of expertise for the average data scientist. 

**Describe the solution you'd like:**
Provide extensible input validation that is injected at deploy time using a Kubernetes configmap. That way, validation logic can be modified without having to change the underlying image. The configmap will be deployed and maintained by cluster administrators who are uniquely aware of their clusters' limitations. 

**Anything else you would like to add:**
I'd be happy to contribute this feature.

**Comment by juliusvonkohout** [comment]
/close

There are similar issues already and please see the Workspaces aka notebooks 2.0 issue. Feel free to help us there to implement this.
