### ISSUE TITLE
Quick Links PR dashboard not working

### ISSUE THREAD

**Issue by rohannair11** [kubeflow/kubeflow#7197]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The PR Dashboard quick link on the main readme file doesnt seem to work 

![kubeflow](https://github.com/kubeflow/kubeflow/assets/42870265/beccf76b-0427-4d48-a41f-3479e26ea7fa)

**Comment by rohannair11** [comment]
I'm new to this project and am filling to fix this issue.

**Comment by juliusvonkohout** [comment]
Then please join the WG meetings from the community calendar

**Comment by juliusvonkohout** [comment]
/close

please retest with 1.9.1 from kubeflow/manifests
