### ISSUE TITLE
error while deploying kubeflow.

### ISSUE THREAD

**Issue by gautamkongi** [kubeflow/kubeflow#7206]
PS C:\Users\Hp> kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
error: no 'git' program on path: exec: "git": executable file not found in %PATH%

**Comment by wlargou** [comment]
I see you are running the command from you windows terminal, did you try running the command from one of your Kubernetes nodes ?

**Comment by gautamkongi** [comment]
I was able to solve it, i didn't have got installed, my bad

**Comment by juliusvonkohout** [comment]
Please close issues if they are resolved.

/close
