### ISSUE TITLE
Configuring different resource allocations for replicas in TFjobs

### ISSUE THREAD

**Issue by ali-raza-tariq** [kubeflow/kubeflow#7209]
/kind question

**Question:**
Hello everyone, I have been running tensorflow training jobs using kubeflow and wanted to ask if there is a feature that can allow us to configure different resource (CPU/memory) allocation for individual worker replicas. From what i have seen, we only configure a single CPU allocation (in the yaml file) and its replicated for all workers when applied but, considering distributed training - each worker-replica is essentially a separate worker doing its own unique computations and in case of heterogenous clusters, each worker would require a custom allocation to run the jobs optimally. Does the current project allows for such customization? If not ... is there a way for me to achieve this with minimal modification to the code base?

**Comment by juliusvonkohout** [comment]
/close

This is not the repository for tfjobs
