### ISSUE TITLE
Add an Arm64 image for the notebook controller

### ISSUE THREAD

**Issue by pingsutw** [kubeflow/kubeflow#7218]
/kind feature

**Why you need this feature:**
Can't run the notebook controller on an arm machine

**Describe the solution you'd like:**
Push an image in the arm64 arch.

**Anything else you would like to add:**
NA

**Comment by displague** [comment]
See https://github.com/kubeflow/manifests/issues/2472

**Comment by juliusvonkohout** [comment]
/close

This seems to be a duplicate
