### ISSUE TITLE
Bootstrapper fails if no ~/.kube/config is present

### ISSUE THREAD

**Issue by inc0** [kubeflow/kubeflow#722]
```
root@kubeflow-toolbox-0:/kubeflow# /opt/kubeflow/bootstrapper --app-dir=./
{"filename":"app/server.go:109","level":"info","msg":"Reading config from file: /root/.kube/config","time":"2018-04-25T13:40:43Z"}
{"filename":"bootstrap/main.go:46","level":"fatal","msg":"stat /root/.kube/config: no such file or directory\n","time":"2018-04-25T13:40:43Z"}
```

This is issue if we run it inside k8s pod. Way to authenticate to k8s underneath is somewhat different and we need to implement this mechanism to bootstrapper as well.

**Comment by jlewi** [comment]
On GKE one option is to do 

```
gcloud container clusters get-credentials
```

We'd probably want to combine that with a service account added as a secret with the appropriate environment variables set.

**Comment by inc0** [comment]
well, it's quite easy to just replicate what kubectl does, check this out https://github.com/ksonnet/ksonnet/issues/431

**Comment by jlewi** [comment]
@kunmingg @inc0 what's the status of this issue?

**Comment by kunmingg** [comment]
We can close it since we already support running bootstrapper inside pod.
