### ISSUE TITLE
Invalid logout Page

### ISSUE THREAD

**Issue by divyank000** [kubeflow/kubeflow#7227]
/kind bug

after I logout from kubeflow 1.7  Dashboard,  It takes me to an invalid Page. 

Sorry, /authservice/site/after_logout is not a valid page

**What steps did you take and what happened:**
I simply logged out

**What did you expect to happen:**
log out will take to the login page again instead of an invalid page

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- KUBEFLOW_RELEASE_VERSION=v1.7.0
- AWS_RELEASE_VERSION=v1.7.0-aws-b1.0.2
- EKS 1.24
<img width="1552" alt="Screenshot 2023-08-02 at 3 21 42 AM" src="https://github.com/kubeflow/kubeflow/assets/115705553/6498616c-5a38-4383-a26c-1443345b8f88">

**Comment by ajinkya933** [comment]
any luck finding the solution ?

**Comment by juliusvonkohout** [comment]
/close

since oidc-authservice is gone in Kubeflow 1.9.1
