### ISSUE TITLE
Handling of XSRF Token is not secure

### ISSUE THREAD

**Issue by jasiecky** [kubeflow/kubeflow#7228]
/kind bug

**What steps did you take and what happened:**
The backend of KF doesn't check user-fed values in XSRF Token.

Steps to reproduce:
1. Login and go to the Volumes or Notebooks section.
2. Delete volume/notebook.
3. Use penetration testing application to intercept the request .
4. Set the value of X-XSRF-TOKEN header and XSRF-TOKEN cookie to any other value.
5. Send the modified request.

Modified request and response:

<img width="1231" alt="image" src="https://github.com/kubeflow/kubeflow/assets/78036965/e13e8242-480a-4173-aedc-e08046f76e2a">

Original request:
<img width="1235" alt="image" src="https://github.com/kubeflow/kubeflow/assets/78036965/e4df35a2-2718-44c9-82af-1b2554390121">

**What did you expect to happen:**

Unique CSRF Token should be present in every request and validated at the backend, which would authorize only valid values. The request with user-fed value should be rejected.

**Environment:**

- Kubeflow version: (1.6.1):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (AKS)
- Kubernetes version: (1.24.9):
- OS (macOS):

**Comment by PaulinaPacyna** [comment]
+1 
We would appreciate a quick response on this

**Comment by kimwnasptd** [comment]
@jasiecky @PaulinaPacyna  from what I remember the security mechanism here is that it's not possible to set both the cookie and the custom header when sending the request, by clicking on other links in malevolent domains. For that, the current approach of only checking if the two values are equal should be secure enough.

So I think the problem that you have is not using `https` in the first place. In that case it's not possible to alter those headers, and we are back to the scenario described above

**Comment by jasiecky** [comment]
@kimwnasptd that's true, we didn't use https then, so I guess it resolves our problem. Thank you!
