### ISSUE TITLE
UID of JupyterHub image

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#723]
Some Kube platforms such as OpenShift by default have restricted UID ranges for any new project or namespace, thus necessitating this troubleshooting [note](https://github.com/pdmack/kubeflow/blob/master/user_guide.md#openshift).

We should look at making modifications to our JupyterHub image similar to what the [radanalytics.io](https://radanalytics.io/) project has done for some of its images.
/cc @tmckayus 
/cc @willb

**Comment by willb** [comment]
I agree that it would be great to get rid of the `anyuid` workaround wherever possible.  I'll try and take a look at this this week.

**Comment by pdmack** [comment]
Linked datawire/ambassador#391
