### ISSUE TITLE
apply to join in kebeflow orgnization 

### ISSUE THREAD

**Issue by lowang-bh** [kubeflow/kubeflow#7240]
/kind question

**Question:**
Hi,  how to apply to be a member of kebeflow orgnization?

**Comment by juliusvonkohout** [comment]
Hello,

make a lot of good PRs that get merged. We always need help.

**Comment by lowang-bh** [comment]
> make a lot of good PRs that get merged. We always need help. I am also offering mentoring.

Hi, where is the link to apply for a memeber?

**Comment by juliusvonkohout** [comment]
You can find it on the website, but the requirements must be met for google to accept you. See for example https://github.com/kubeflow/internal-acls/pull/509

**Comment by lowang-bh** [comment]
> You can find it on the website, but the requirements must be met for google to accept you. See for example [kubeflow/internal-acls#509](https://github.com/kubeflow/internal-acls/pull/509)

Thanks very much!

**Comment by juliusvonkohout** [comment]
@lowang-bh you can join the manifests or notebooks wg meetings and we can find PRs for you to work on.
