### ISSUE TITLE
Font in JupyterLab terminal not readable in Firefox

### ISSUE THREAD

**Issue by joysn71** [kubeflow/kubeflow#7245]
Hello,
I just installed kubeflow (on minikube) and created a notebook (jupyter-pytorch-full:v1.7.0-rc.0). I opened a terminal and unfortunately I can not read anything:
![image](https://github.com/kubeflow/kubeflow/assets/2394633/87c02e6d-79f1-4bb3-8747-9c4abfb5524d)

However, if I open it in Chrome, the font is readable:
![image](https://github.com/kubeflow/kubeflow/assets/2394633/999ffca3-1b47-4379-8cce-97f361db0210)

What might be the problem here?
Linux Mint Debian edition LMDE 5 Elsie,
Firefox 116.0.2

**Comment by juliusvonkohout** [comment]
/close

Reopen if necessary and please upgrade to 1.8rc first to verify.
