### ISSUE TITLE
Minio not initialized when running inside minikube with driver "none"

### ISSUE THREAD

**Issue by joysn71** [kubeflow/kubeflow#7250]
/kind bug

**What steps did you take and what happened:**
I installed Kubeflow on a minikube cluster directly from manifests as mentioned in the documentation. The minikube cluster uses the "none" driver to be able to use the addons for Nvidia GPUs. 
`minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost --docker-opt default-runtime=nvidia --feature-gates=DevicePlugins=true`
However, minio did not start because of:
`Aug 25 18:28:18 laptop1 kubelet[185194]: E0825 18:28:18.401263  185194 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"minio\" with CreateContainerConfigError: \"stat /tmp/hostpath-provisioner/kubeflow/minio-pvc: no such file or directory\"" pod="kubeflow/minio-55464b6ddb-qntq9" podUID=4c85dd0d-e747-4e79-aba5-5595b89da3cd`
Looking into the mentioned folder, two containers could create a PV there:
```
user@laptop1:/tmp/hostpath-provisioner/kubeflow$ ll
total 8
drwxr-xr-x 3 root root 4096 Aug 25 08:11 katib-mysql
drwxr-xr-x 9  999 root 4096 Aug 25 18:08 mysql-pv-claim
```
When I create the directory `/tmp/hostpath-provisioner/kubeflow/minio-pvc` manually, minio started successfully.

**What did you expect to happen:**
The folder for the PVC should be created automatically when provisioning minio.

**Anything else you would like to add:**
If there is another way to provide GPU support to Kubeflow, I would appreciate some pointers :)
Kubeflow in driver Docker works without hassles during installation, but there is no GPU support.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.7.0-rc.0
- kfctl version: (use `kfctl version`): not used
- Kubernetes platform: (e.g. `minikube`) minikube v1.31.2
- Kubernetes version: (use `kubectl version`): v1.27.4
- OS (e.g. from `/etc/os-release`):
Linuxmint 5 Debian edition Bullseye, AMD64

**Comment by juliusvonkohout** [comment]
Yes, you can use GPUS if the cluster supports them. Please provide a PR for updating the minikube documentation then.

**Comment by joysn71** [comment]
Meanwhile I switched to driver Docker and was able to get GPU support in the cluster with nvidia-runtime and nvidia-gpu-device-plugin. With the Docker driver the issue with Minio disappeared.
