### ISSUE TITLE
Configuration knob for old logout button behaviour

### ISSUE THREAD

**Issue by heilerich** [kubeflow/kubeflow#7261]
/kind feature

With #6609 the behaviour the the dashboard's logout button changed from a simple link to `/logout` to a post request that is specific to the arrikto authservice. It would be nice to have a configuration knob to opt out of this behaviour and change the button back to a simple link for broader compatibility with alternative authentication solutions.

**Why you need this feature:**
We have been using `oauth2-proxy` as a drop in replacement for the default authservice for a very long time now and would like to stick with it. Reasons for this include (a) it is completely stateless and can therefore be easily deployed in HA mode and (b) bigger community and therefore more active maintenance (great in a security related component). I think there was also something about better support for some non OIDC OAuth providers and some backchannel session termination stuff, but I can't remember the details right now. Anyways, I think there are probably many reasons for people to choose alternative authentication solutions.

**Describe the solution you'd like:**
With #6945 the URL is already a dynamic setting (which is not strictly necessary, because this has already been easily rewritable via istio before). It would be nice to have an additional environment variable to switch between simple link and XHR/Post behaviour.

**Anything else you would like to add:**
I think providing the option for the logout button to be a simple link instead of a custom made logout API call specific to Kubeflow authservice would probably make integration easier in a variety of environments (not restricted to our specific solution).

**Comment by juliusvonkohout** [comment]
Since we now use oauth2-proxy by default i think we can close this. See also https://github.com/kubeflow/kubeflow/pull/7654/files

/close
