### ISSUE TITLE
Upgrade ksonnet version to v0.10 for kubeflow.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#727]
Since ksonnet already provide version: 
https://github.com/ksonnet/ksonnet/tree/v0.10.0
We can upgrade ksonnet version to take advantage of new features.
And unblock things like https://github.com/kubeflow/kubeflow/pull/720

**Comment by ankushagarwal** [comment]
There is an issue with the latest release (0.10.1) https://github.com/ksonnet/ksonnet/issues/493#issuecomment-385102672

**Comment by everpeace** [comment]
Could we upgrade to ksonnet 0.10.2 ???

**Comment by ankushagarwal** [comment]
I don't know if 0.10.2 fixes https://github.com/ksonnet/ksonnet/issues/502

**Comment by jlewi** [comment]
@everpeace checked see [here](https://github.com/ksonnet/ksonnet/issues/502#issuecomment-390056907) and 0.10.2 appears to fix ksonnet/ksonnet#502

kubeflow/testing#134 modified the Dockerfile for gcr.io/kubeflow-ci/test-worker to include ksonnet 0.10.2.

latest currently points to image [gcr.io/kubeflow-ci/test-worker:test-worker@sha256:1536a765efc9d6e6ed8b61a82dec1b414fcdac25cdf621b9706bfa5d5d52689b](https://console.cloud.google.com/gcr/images/kubeflow-ci/GLOBAL/test-worker@sha256:1536a765efc9d6e6ed8b61a82dec1b414fcdac25cdf621b9706bfa5d5d52689b/details/info)

**Comment by jlewi** [comment]
New ci worker image pushed.

https://console.cloud.google.com/gcr/images/kubeflow-ci/GLOBAL/test-worker@sha256:87855deb994dc87ddf439da054004b4ce3a976f515f6bd471992bd378b1bbb43/details/info

**Comment by jlewi** [comment]
I moved tag `latest` back to https://console.cloud.google.com/gcr/images/kubeflow-ci/GLOBAL/test-worker@sha256:1536a765efc9d6e6ed8b61a82dec1b414fcdac25cdf621b9706bfa5d5d52689b/details/info

We will need to resolve kubeflow/testing#137 before continuing with the upgrade.

**Comment by jlewi** [comment]
New image is:
gcr.io/kubeflow-releasing/worker:v20180611-966ecb4-e3b0c4

**Comment by everpeace** [comment]
now kubeflow supports ks 0.11.

/close
