### ISSUE TITLE
Creating notebook throws 500 error

### ISSUE THREAD

**Issue by annajung** [kubeflow/kubeflow#7272]
/kind bug

**What steps did you take and what happened:**
When creating a notebook, an error is thrown, indicating failure with an empty dashboard. However, when refreshed, the notebook is shown to be successfully created.

![Screenshot 2023-09-08 at 12 44 57 PM](https://github.com/kubeflow/kubeflow/assets/24755674/b567109c-de3a-4013-ac30-f83b8b498b05)

Steps to reproduce
1. Deploy Kubeflow using 1.8 RC ([v1.8-branch](https://github.com/kubeflow/manifests/tree/v1.8-branch))
2. Navigate to "Notebooks" to create a new notebook
3. After clicking "launch", a 500 server error is displayed indicating an error creating notebook
> [500] An error occurred in the backend. http://localhost:8080/jupyter/api/namespaces/kubeflow-user-example-com/notebooks

**What did you expect to happen:**
After clicking "launch" and being redirected back to the notebooks dashboard, the notebook created by the user should show up as being created without an error message.

**Anything else you would like to add:**
logs from `jupyter-web-app-deployment` pod 
```
| kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
| kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | 'status'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/src/apps/common/routes/get.py", line 55, in get_notebooks
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/routes/get.py", line 55, in <listcomp>
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/utils.py", line 141, in notebook_dict_from_k8s_obj
    "status": status.process_status(notebook),
  File "/src/apps/common/status.py", line 15, in process_status
    status_phase, status_message = get_empty_status(notebook)
  File "/src/apps/common/status.py", line 62, in get_empty_status
    container_state = notebook["status"]["containerState"]
KeyError: 'status'
```

This only happens when creating the first notebook. If there are 1+ notebooks running already, 500 error does not show up as it's able to resolve the keyerror. Possible solution could be a simple check for key status to handle when notebook doesn't exist could solve the issue.

Not a huge issue as the notebook successfully gets created and functions as expected, but should be tracked and resolved for next 1.8 RC cc @DnPlas @kimwnasptd 

**Environment:**
- Kubeflow version: 1.8 RC
- Kubernetes platform: (e.g. `minikube`): KinD 1.26

**Comment by thesuperzapper** [comment]
I believe this was resolved by https://github.com/kubeflow/kubeflow/pull/7335

/close
