### ISSUE TITLE
can not find node_modules kubeflow

### ISSUE THREAD

**Issue by cherish06** [kubeflow/kubeflow#7275]
in project kubeflow\components\crud-web-apps\jupyter\frontend, when I ng serve to run the project,the logs show error can not find node_modules kubeflow, where can I find this node_modules

**Comment by juliusvonkohout** [comment]
/ close

This is not a proper bug report

**Comment by andreyvelich** [comment]
Feel free to re-open an issue in the `kubeflow/notebooks`
