### ISSUE TITLE
pvcviewer - make the istio gateway configurable for VirtualServices

### ISSUE THREAD

**Issue by misohu** [kubeflow/kubeflow#7283]
/kind feature

Right now PVCViewer controller will set the gateway to `kubeflow/kubeflow-gateway` for every CR. This value cannot be changed. Const [here](https://github.com/kubeflow/kubeflow/blob/master/components/pvcviewer-controller/controllers/pvcviewer_controller.go#L55) Can we make this value configurable ? E.g. using environment variable? 

**Why you need this feature:**
Sometimes I want to use different gateway name for PVCViewer virtual services. E.g. different name or gateway is in different namespace.

**Describe the solution you'd like:**
I want to load the value [here](https://github.com/kubeflow/kubeflow/blob/master/components/pvcviewer-controller/controllers/pvcviewer_controller.go#L55) from environment variable so every new PVCViewer CR will set it in gateway field for VirtualService [here](https://github.com/kubeflow/kubeflow/blob/master/components/pvcviewer-controller/controllers/pvcviewer_controller.go#L288).

**Comment by TobiasGoerke** [comment]
Thanks for the issue. Would #7351 solve your issue?

**Comment by thesuperzapper** [comment]
Resolved by https://github.com/kubeflow/kubeflow/pull/7351
/close
