### ISSUE TITLE
Sorry, /notebook/kubeflow-user-example-com/test-base is not a valid page

### ISSUE THREAD

**Issue by nikmatha** [kubeflow/kubeflow#7291]
/kind bug

**What steps did you take and what happened:**
Deployed Kubeflow on an Oracle Cloud Kubernetes cluster following the steps outlined by Oracle. I then attempted to create a notebook with the following custom image: jupyter/base-notebook:2023-05-01. This is simply the base image used for a more complex custom image, however, that is also not working so I want to get this one working correctly first. When I attempt to connect to the notebook I get the following error:
Sorry, /notebook/kubeflow-user-example-com/test-base is not a valid page
When I check k9s it says it is all running. 

**What did you expect to happen:**
To connect to the notebook UI.

**Anything else you would like to add:**
When I look at the logs for the istio-proxy in the new Notebook container, there is this:
 [2023-09-20T11:57:48.772Z] "GET /notebook/kubeflow-user-example-com/test-base/ HTTP/1.1" 302 - via_upstream 

│ [2023-09-20T11:57:51.590Z] "GET /notebook/kubeflow-user-example-com/test-base/api/contents HTTP/1.1" 404 - via_upstream

Using the provided images works, it's just custom images that are not. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.7 (dev local)
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`): 1.26.2
- OS (e.g. from `/etc/os-release`): Oracle Linux 7.9

**Comment by tama-biro** [comment]
Have similar issue on `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/base:v1.5.0`. Noticed today

**Comment by cristianTeknoir** [comment]
Same for public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.3.0-rc.1

**Comment by mirhossain** [comment]
It seems like the ECR repo has been deleted. We are having problem with kubeflow on our EKS cluster as well. Is there an alternative image available that we can retag and upload to our own ECR repo?

**Comment by cristianTeknoir** [comment]
Seems like they moved to docker.io/kubeflownotebookswg/

**Comment by juliusvonkohout** [comment]
/close

Please take a look at the ecr image issue
