### ISSUE TITLE
mysql and katib-mysql pod stuck in pending after cluster update

### ISSUE THREAD

**Issue by TheRochVoices** [kubeflow/kubeflow#7298]
My mysql and katib-mysql pod are stuck in pending after I upgraded my EKS cluster rom 1.22 to 1.25. 
Upon describing the Pending pods, I get the following from the error logs: "0/3 nodes are available: 3 node(s) had volume node affinity conflict. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.".

I believe it's regarding some mismatch in pv and pvc since these are the 2 pods which have a pv attached to them.

Can anyone help in the possible next steps in getting my pods back in the running state. Thanks

**Comment by juliusvonkohout** [comment]
/close 

please report this in the katib and kfp repositories
