### ISSUE TITLE
[PROPOSAL] decouple versions in this repo from Kubeflow itself (speed up feature delivery)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#7300]
Right now, only the components owned by the @kubeflow/wg-notebooks-leads are limiting themselves to the release cadence of Kubeflow's overall version (which often has many months between releases). This is hurting the momentum of these components and people's willingness to contribute.

I propose that we release a new feature version (`1.X.0`) of the components in `kubeflow/kubeflow`, every 2-3 months.

Yes, this would mean that our version numbers would become progressively detached from the `Kubeflow 1.X` version, but this is not a problem for the other components that are already doing this.

### To make this easier, I suggest we:

1. Continue to use a "semantic" versioning structure (e.g. the next release would be `1.9.0`)
1. Continue to version ALL components from the `kubeflow/kubeflow` repo at the same version
2. Adhear to the "meaning" of semantic versioning (so users understand which versions are simply patches, which introduce new features, and which have breaking changes)

### The first "decoupled" `1.9.0` release can include these some of these PRs:

__Top Priority:__

- https://github.com/kubeflow/kubeflow/pull/7220
- https://github.com/kubeflow/kubeflow/pull/7276

__Small but important:__

- https://github.com/kubeflow/kubeflow/pull/6902
- https://github.com/kubeflow/kubeflow/pull/7260
- https://github.com/kubeflow/kubeflow/pull/7036
- https://github.com/kubeflow/kubeflow/pull/7059
- https://github.com/kubeflow/kubeflow/pull/7124
- https://github.com/kubeflow/kubeflow/pull/7080
- https://github.com/kubeflow/kubeflow/pull/7015
- https://github.com/kubeflow/kubeflow/pull/7242
- https://github.com/kubeflow/kubeflow/pull/7281

__Big new features:__

- https://github.com/kubeflow/kubeflow/pull/6927
- https://github.com/kubeflow/kubeflow/pull/7028

### The `2.0.0` release could target these features (and possibly a few others):

- https://github.com/kubeflow/kubeflow/issues/7156
- https://github.com/kubeflow/kubeflow/issues/7085

**Comment by StefanoFioravanzo** [comment]
@thesuperzapper I think this is a great proposal. Do you think that moving these components to dedicated repositories would help in decoupling from kubeflow/kubeflow? I think there was some discussion about this in the past, but I don't remember what was the resolution.

**Comment by thesuperzapper** [comment]
Closing as this will happen naturally as we split the repo into `kubeflow/notebooks` and `kubeflow/dashboard`.

See https://github.com/kubeflow/kubeflow/issues/7549
