### ISSUE TITLE
Output Artifact URI direct error when point to GCS folder on Vertex AI UI

### ISSUE THREAD

**Issue by PennyQ** [kubeflow/kubeflow#7312]
/kind bug

**What steps did you take and what happened:**
We have a kubeflow pipeline running on Vertex AI, and we have a output artifact named `output_data` that is created from the component `write` and used in the downstream component `read`. The pipeline can run well as you see:
<img width="1065" alt="image" src="https://github.com/kubeflow/kubeflow/assets/13411839/0047e951-de41-456b-9ca2-627777ca7b76">
But clicking on the artifact URI would lead to an error page on GCS, stated that the `requested eneity is not found`. As you see:
<img width="582" alt="image" src="https://github.com/kubeflow/kubeflow/assets/13411839/c6cf2a2f-32d2-4d8a-be72-03e40eedc97e">

The problem is that the URI is a folder type, and it seems try to load this folder as a file type which leads to the above error. 

I tested with a Python component which you can rewrite the `artifact.uri` to the file itself which can work, but in our case we used the container component that the uri is passed in as a placeholder when initiating the container. I tried to add a line when initiating the container as `output_data.uri = ConcatPlaceholder([output_data.path, "/output.txt"])` to direct it to a file but see no change on the UI of this line. 

**What did you expect to happen:**
I am wondering if we can add a check in the `Artifact` class, for uri leads to a folder, either the folder path or the most updated file under that folder would be passed to the uri, so that click on the URI on Vertex AI can lead to the a valid folder/path instead of the error message.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The simple version of my code looks like below:
```
@pipeline(name=PIPELINE_NAME, pipeline_root=PIPELINE_GCS_ROOT)
def pipeline():
    write()
```
```
@container_component
def write(output_data: Output[Artifact]) -> ContainerSpec:
    output_data.uri = ConcatPlaceholder([output_data.path, "/output.txt"])  # this seems not do anything
    return ContainerSpec(
        image=IMAGE,
        command=["python3", "example_batch_project/main.py"],
        args=[
            "--environment",
            environment.value,
            "write",
            "--output-data-path",
            output_data.path
        ],
    )
```
```
app = typer.Typer()
@app.command()
def write(
    ctx: typer.Context,
    output_data_path: Path = typer.Option(..., help="Path to which to write the queried training data.")
):
    with open(output_data_path / "output.txt", "w") as f:
            f.write("hello")
```

**Environment:**

- Kubeflow version: 2.0.1
- Kubernetes platform: GKE

**Comment by mtasende** [comment]
Hi!
I am having the same problem.
I found that there is a "**_details/**" string added to the link uri, that if you remove it, it works.
I still don't know why it was added, or how to automatically not have it there.

**Comment by juliusvonkohout** [comment]
/close 

this is not the kfp repository
