### ISSUE TITLE
My Kubeflow notebook is not working at all 

### ISSUE THREAD

**Issue by gauravvanawat** [kubeflow/kubeflow#7323]
Dear Team, 

Please check attached error which I get while accessing any file in my notebook. I am not able to proceed further. This is bit urgent. 

Thank You. 
Best Regards,
Gaurav
![Screenshot 2023-10-08 at 3 23 36 PM (2)](https://github.com/kubeflow/kubeflow/assets/147311883/8183a9f9-35a2-4955-8143-3f0609601f6a)

**Comment by harshad16** [comment]
@gauravvanawat Did you check the pod log for this particular notebook?
