### ISSUE TITLE
Support for installing libraries from GCP artifact registry or enterprise artifactory!

### ISSUE THREAD

**Issue by gomrinal** [kubeflow/kubeflow#7332]
/kind feature

**Why you need this feature:**
For installing custom libraries, one often needs to install it from enterprise artifactory or google artifact registry if they are using GCP. 

On trying with different pip index url in KFP. It doesn't seems to work.

**Describe the solution you'd like:**
- Easy integration with `artifactory` so that one can install libraries from enterprise artifactory or at least cloud vendors instead of installing all the libraries from the pypi.org

**Comment by juliusvonkohout** [comment]
Hello please use the kfp repository for kfp issues

/close
