### ISSUE TITLE
Notebook custom manifests validation

### ISSUE THREAD

**Issue by MuhammadUsman90** [kubeflow/kubeflow#7344]
Currently custom manifests can be blocked in state where controller doesn't generate a warning that user can see. We need some validation at level of notebook controller to at least attach some warnings to the object so that user can be notified what's happening. 

For example an example image: image: ' lscr.io/linuxserver/code-server:latest'

**Comment by juliusvonkohout** [comment]
There are several open issues and PRs about this as well as https://github.com/kubeflow/kubeflow/issues/7156. There are also many more ways to just attack the notebooks controller with denial of service for all namespaces just with a single faulty notebook CR. I know cases where this happened by accident.

But yes within https://github.com/kubeflow/kubeflow/issues/7156 we need to have proper specification checks for CRs and propagate errors to the UI.

**Comment by juliusvonkohout** [comment]
This will be covered in version 2, which is in development

/close
