### ISSUE TITLE
Precache Jupyter Images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#736]
It might be nice to support precaching Jupyter images. This would allow us to make it fast to launch Jupyter  notebooks while still allowing for really large Docker images ~10s of GBs.

Being able to support large Docker images is valuable because its convenient for notebook environments to get a whole bunch of libraries. 

For example we might want to support the Kaggle Image (#258) which has a plethora of datascience tools but is huge (~20Gb)?

I think there are a couple easy ways to precache images

1. We could use a daemonset
  - Add a container for each image to prepull
  - Do tail -f null for the command
  
1. We could use a replica set and then pod affinity and anti affinity to co schedule the prepulled containers with the jupyter notebooks

#2 is harder to implement but the advantage is on really large clusters don't want to cache on all nodes

/cc @pdmack @inc0 @ankushagarwal

**Comment by jlewi** [comment]
/cc @lluunn 

I think @lluunn will have a prototype for a daemonset soon.

**Comment by pdmack** [comment]
Yeah, or a deploy container that pre-pulls as you mentioned. If we pull the 1.4-1.7 cpu/gpu matrix, what does that mean for a new deployment? On a developer laptop, would we be freaking out the docker daemon and their system? Could it be done as an opt-in like Spartakus?

**Comment by jlewi** [comment]
I was thinking opt in.

**Comment by inc0** [comment]
well that's going to be hard for big infras - you need to have local image on every kubelet, so potentially a *a lot* of unnecessary downloads. Alternative would be registry local to cluster, but that's lot of additional setup and beyond our scope.

For affinity I'd say we don't want to handle scheduling on our own, that's schedulers job, not we should encourage it. Scheduler works best if it has least amount of constraints.

How about we document how to setup local registry? One way is to run registry pod and add nodeport type service, so all nodes will listen on this, then every time you spawn jupyter notebook, you use localhost:nodeport/jupyter-image url and it works. A bit hacky, maybe there is better way?

**Comment by inc0** [comment]
Also operators would "love" us if we'd start do download images on all nodes at the same time:) we could eat up even big uplinks with that:)
