### ISSUE TITLE
Custom changes to webUI then deploy in my microk8s

### ISSUE THREAD

**Issue by MohammedAlSinan** [kubeflow/kubeflow#7366]
Hello 
I have installed micrk8s then juju to install kubeflow solution . which works fine but i need to edit the ui to have more restriction with my users and cluster. 
For Now i just would like to remove the button "New Notebook" from the notebooks tab?
how would i do that?

**Comment by juliusvonkohout** [comment]
You change the code and rebuild the image

/close
