### ISSUE TITLE
Kustomize emits warnings for depreciated features

### ISSUE THREAD

**Issue by strangiato** [kubeflow/kubeflow#7367]
/kind bug

**What steps did you take and what happened:**
When applying resources with the various kustomize objects, kustomize emits depreciation warnings for several features that have been depreciated since v2.1.0.

- `bases` should be updated to `resources`
- `patchesStrategicMerge` should be updated to `patches`
- `commonLables` should be updated to `labels`
-  `vars` should be updated to `replacements`

Most of these can be updated automatically by running `kustomize edit fix`.  The `vars` is the only one that tends to get a bit tricky.  `kustomize edit fix --vars` is an experimental feature but generally requires a little more validation to make sure something didn't get messed up.

**What did you expect to happen:**
Update the kustomize to not include depreciated features.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by juliusvonkohout** [comment]
Most of this is solved in Kubeflow 1.9.1
so i think we can 

/close 

here
