### ISSUE TITLE
Custom app in Kubeflow

### ISSUE THREAD

**Issue by MohammedAlSinan** [kubeflow/kubeflow#7368]
/kind question
I would like to create my own custom tab for kubeflow, for user to request access to notebooks with  some computation specifications
![mycustomapp](https://github.com/kubeflow/kubeflow/assets/127279130/57b4bb1e-5bbb-4ba6-bd2c-5b3567cbe70b)
 How would I start this?
 is there some rules i have to follow?
 frameworks?
 is it easily connected to the kubeflow system?
 I would like to start this for my research center, help me kick start this .

**Comment by thesuperzapper** [comment]
@MohammedAlSinan if you are using the raw kubeflow manifests, you will need to manually extend the [`ConfigMap/centraldashboard-config`](https://github.com/kubeflow/kubeflow/blob/v1.8.0/components/centraldashboard/config/centraldashboard-config.yaml).

Alternatively, if you want to try [deployKF](https://www.deploykf.org/), there is a straightforward value config which is [documented here](https://www.deploykf.org/guides/platform/deploykf-dashboard/#sidebar-links).

**Comment by thesuperzapper** [comment]
This is now documented on the Kubeflow website:

- https://www.kubeflow.org/docs/components/central-dash/customize/
