### ISSUE TITLE
jupyter notebook not connect only

### ISSUE THREAD

**Issue by Sujittibe123** [kubeflow/kubeflow#7370]
jupyter notebook not connect only but vs code and r studio notebook successfully connected.
when i check notebook pod logs, i get this runtime error "RuntimeError: Permissions assignment failed for secure file: '/home/jovyan/.local/share/jupyter/runtime/jpserver-9060.json'. Got '0o677' instead of '0o0600'."
and on kubeflow ui i see this error "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111"
<img width="960" alt="image" src="https://github.com/kubeflow/kubeflow/assets/49091383/281e9b90-4bf5-44cc-976f-3d4806c94fd5">
<img width="956" alt="image" src="https://github.com/kubeflow/kubeflow/assets/49091383/15938ce5-81d8-48e6-8d8c-258f354e14a5">
<img width="955" alt="image" src="https://github.com/kubeflow/kubeflow/assets/49091383/0cfffb06-85e4-40b1-ac01-008d4f68a0a4">

**Comment by thesuperzapper** [comment]
@Sujittibe123 I have raised a PR to fix this in future images https://github.com/kubeflow/kubeflow/pull/7407

But to fix it immediately, you either need to use a custom image, which sets the `JUPYTER_RUNTIME_DIR` env-var to 
 `"/tmp/jupyter_runtime"`, or find some way to make your PVC not mess with the file permissions (which may not be possible if you are using NFS).

**Comment by juliusvonkohout** [comment]
Oh yes vscode exhibits the same error

**Comment by thesuperzapper** [comment]
@juliusvonkohout can you confirm the path of the file(s) that VSCode complains about permission for?

**Comment by thesuperzapper** [comment]
@juliusvonkohout did you manage to figure out what setting needed to be changed to make it work in your environment?

We really need to make a PR so that we can cut a patch release.

**Comment by juliusvonkohout** [comment]
@thesuperzapper ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 from https://github.com/pi-hole/docker-pi-hole/pull/1192 is probably needed

**Comment by juliusvonkohout** [comment]
Might be fixed by https://github.com/kubeflow/kubeflow/pull/7421
