### ISSUE TITLE
Getting 500 error from web app when creating a notebook in 1.8 RC2

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#7373]
/kind bug

**What steps did you take and what happened:**
1. Go to the Notebooks page in CentralDashboard
2. Click to create a new notebook
3. Click `LAUNCH`
4. I get redirected to main page of the app, but get a 500

**What did you expect to happen:**
The Notebook to be created as expected.

**Anything else you would like to add:**
I see the following logs:
```
2023-10-23 08:22:32,831 | kubeflow.kubeflow.crud_backend.authn | INFO | Handling request for user: user@example.com
2023-10-23 08:22:32,831 | kubeflow.kubeflow.crud_backend.csrf | INFO | Skipping CSRF check for safe method: GET
2023-10-23 08:22:32,838 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
2023-10-23 08:22:32,839 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | 'dict' object has no attribute 'STATUS_PHASE'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/src/apps/common/routes/get.py", line 55, in get_notebooks
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/routes/get.py", line 55, in <listcomp>
    contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
  File "/src/apps/common/utils.py", line 144, in notebook_dict_from_k8s_obj
    "status": status.process_status(notebook),
  File "/src/apps/common/status.py", line 15, in process_status
    status_phase, status_message = get_empty_status(notebook)
  File "/src/apps/common/status.py", line 76, in get_empty_status
    status_phase = status.STATUS_PHASE.WAITING
AttributeError: 'dict' object has no attribute 'STATUS_PHASE'
127.0.0.6 - - [23/Oct/2023:08:22:32 +0000] "GET /api/namespaces/kubeflow-user-example-com/notebooks HTTP/1.1" 500 98 "http://localhost:8080/jupyter/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
```
**Environment:**
`1.8.0-rc.2` tag

@TobiasGoerke could this be related to https://github.com/kubeflow/kubeflow/pull/7335?
cc @DnPlas

**Comment by TobiasGoerke** [comment]
> /kind bug
> 
> **What steps did you take and what happened:**
> 
> 1. Go to the Notebooks page in CentralDashboard
> 2. Click to create a new notebook
> 3. Click `LAUNCH`
> 4. I get redirected to main page of the app, but get a 500
> 
> **What did you expect to happen:** The Notebook to be created as expected.
> 
> **Anything else you would like to add:** I see the following logs:
> 
> ```
> 2023-10-23 08:22:32,831 | kubeflow.kubeflow.crud_backend.authn | INFO | Handling request for user: user@example.com
> 2023-10-23 08:22:32,831 | kubeflow.kubeflow.crud_backend.csrf | INFO | Skipping CSRF check for safe method: GET
> 2023-10-23 08:22:32,838 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
> 2023-10-23 08:22:32,839 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | 'dict' object has no attribute 'STATUS_PHASE'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/src/apps/common/routes/get.py", line 55, in get_notebooks
>     contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
>   File "/src/apps/common/routes/get.py", line 55, in <listcomp>
>     contents = [utils.notebook_dict_from_k8s_obj(nb) for nb in notebooks]
>   File "/src/apps/common/utils.py", line 144, in notebook_dict_from_k8s_obj
>     "status": status.process_status(notebook),
>   File "/src/apps/common/status.py", line 15, in process_status
>     status_phase, status_message = get_empty_status(notebook)
>   File "/src/apps/common/status.py", line 76, in get_empty_status
>     status_phase = status.STATUS_PHASE.WAITING
> AttributeError: 'dict' object has no attribute 'STATUS_PHASE'
> 127.0.0.6 - - [23/Oct/2023:08:22:32 +0000] "GET /api/namespaces/kubeflow-user-example-com/notebooks HTTP/1.1" 500 98 "http://localhost:8080/jupyter/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
> ```
> 
> **Environment:** `1.8.0-rc.2` tag
> 
> @TobiasGoerke could this be related to #7335? cc @DnPlas

Seems to be a different issue, appearing just now that the other one has been solved. 

As far as I can tell, [`status = notebook.get("status", {})`](https://github.com/TobiasGoerke/kubeflow/blob/b0886c4d13c723c47addd460e78a61ff0dfd0f5d/components/crud-web-apps/jupyter/backend/apps/common/status.py#L62) shadows the import, leading to a error in [`status_phase = status.STATUS_PHASE.WAITING`](https://github.com/TobiasGoerke/kubeflow/blob/b0886c4d13c723c47addd460e78a61ff0dfd0f5d/components/crud-web-apps/jupyter/backend/apps/common/status.py#L76C25-L76C51).

I can offer to take a deeper look at this and fix it later today.

**Comment by TobiasGoerke** [comment]
Fixed and tested locally: no more 500s after Notebook creation: #7375 and #7376
