### ISSUE TITLE
Update Codeserver

### ISSUE THREAD

**Issue by FabianHoerst** [kubeflow/kubeflow#7384]
Hello,

could you please provide instructions to update the code-server version provided within kubeflow?
Currently, `kubeflownotebookswg/codeserver-python:v1.7.0-rc.0`is the latest version available for kubeflow, but this version has a old vs-code coder version inside (From 2022, therefor many extensions are not working).

Thanks in Advance!

**Comment by thesuperzapper** [comment]
@FabianHoerst the Kubeflow v1.8.0 images for codeserver now use version [`v4.17.1`](https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/codeserver/Dockerfile)!

/close
