### ISSUE TITLE
Notebooks image validation with k8s CEL as a prt of CRD's

### ISSUE THREAD

**Issue by MuhammadUsman90** [kubeflow/kubeflow#7391]
/kind feature

**Why you need this feature:**
 We need basic notebook manifest validation. Lately have seen space in image field doesn't warn user about invalid image.

**Describe the solution you'd like:**
CEL offers a very easy to do manifest validation at k8s Api server level. Minimal validation could be added as part of CRD.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by kimwnasptd** [comment]
@MuhammadUsman90 what would be the next steps to using CEL for this? 

Is it only a matter of updating the CRD? If yes, can we make kubebuilder aware of this, which generates the manifests, or should this be an additional overlay?

**Comment by MuhammadUsman90** [comment]
yes would be just to update the CRD's. I would like to start working on it and provide some working version soon. (just came back from Holidays)

**Comment by Parthiba-Hazra** [comment]
Hi @kimwnasptd @MuhammadUsman90 @juliusvonkohout , 
is this issue already worked on? if not then I would like to work on this.

**Comment by thesuperzapper** [comment]
This has been done by https://github.com/kubeflow/kubeflow/pull/7495

/close
