### ISSUE TITLE
Model Registry for Kubeflow based on ml-metadata

### ISSUE THREAD

**Issue by dhirajsb** [kubeflow/kubeflow#7396]
/kind feature

**Why you need this feature:**
Based on [Kube Flow User Survey](https://blog.kubeflow.org/kubeflow-user-survey-2023/) the community also needs Model Registry support (44% wanted this). 

We are exploring opportunities to make best use of ml-metadata as a Model Registry with its logical model, by leveraging existing capabilities and complementing them with the ones proposed above. We would very much like your input and guidance regarding these features.

**Describe the solution you'd like:**
KubeFlow is currently using ml-metadata for capturing the training and experimentation data. We believe extending the ml-metadata will be a natural extension of existing work for pipelines. 

Apart from above KFP community has mentioned that they are interested in ml-metadata to support following two features as top concerns for kubeflow:
* Support Role Based Access Control
Ml-metadata should support user and org/group ownership of metadata resources. 
* Support multi-tenancy
Ml-metadata should support multi-tenant metadata resources. The tenancy could be defined by namespaces (namespace isolation mentioned by kubeflow) or could be based on an org/group tenant. 

**Anything else you would like to add:**
We are working on an [initial proposal](https://www.google.com/url?q=https://docs.google.com/document/d/1T3KfOqIfJohp0s1koQ2XrJJQQhj7TECO-m2xPsW59_c/edit?usp%3Dsharing&sa=D&source=calendar&ust=1702394366106618&usg=AOvVaw3gmBEmLCuwAByPnHQ-Pewz) in the Open Data Hub community for extending ml-metadata to be used as a generic opensource Model Registry. However, we are hoping to bring this idea upstream to share the design and implementation with the kubeflow community.

**Comment by noelo** [comment]
much needed +1

**Comment by jbottum** [comment]
@dhirajsb thanks for this proposal.   A model registry would be a valuable addition to Kubeflow.   Although it would be great to see a 1st version for the next Kubeflow release, I suspect the model registry will take multiple releases to mature.   The design needs validation by users and the implement must be non-vendor specific / lock-in.    To move forward, the details are too much to discuss in the Community Meeting but the Community meeting would benefit from status summary (design / implementation updates, schedule, PRs that need help).    Would you consider supporting a regular Model Registry status meeting that would organize / communicate the tactical PRs  / benefits and Phase 1 schedule ?   Note - It would be great to get comments from WG and Community leads: @james-jwu @kimwnasptd @andreyvelich @johnugeorge @chensun @zijianjoy @thesuperzapper @annajung @DnPlas @yuzisun @akgraner

**Comment by zijianjoy** [comment]
Thank you for the proposal, I would like to @XinranTang (https://github.com/XinranTang) who is currently the maintainer of ML Metadata OSS to get more input.

**Comment by juliusvonkohout** [comment]
Related to https://github.com/kubeflow/pipelines/issues/4790 and yes a global instance with strict user isolation and authetication  is essential for Kubeflow.

**Comment by rareddy** [comment]
An updated proposal here which goes into bit more details https://docs.google.com/document/d/1T3KfOqIfJohp0s1koQ2XrJJQQhj7TECO-m2xPsW59_c/edit?usp=sharing

**Comment by rareddy** [comment]
> Related to [kubeflow/pipelines#4790](https://github.com/kubeflow/pipelines/issues/4790) and yes a global instance with strict user isolation and authetication is essential for Kubeflow.

This is one of the issues we are planning to tackle as a step 2 deliverable in the proposal document.

**Comment by dhirajsb** [comment]
I updated the link to the proposal in the description to a google doc we created for Kubeflow community discussions.

**Comment by rareddy** [comment]
The official proposal in the form of PR https://github.com/kubeflow/community/pull/682

**Comment by rareddy** [comment]
@juliusvonkohout would you be able to collaborate with us either in contribution or spec design for the Model Registry?

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout would you be able to collaborate with us either in contribution or spec design for the Model Registry?

I can help with the architecture and especially security in the second phase. You will have to integrate with istio and the multi-tenancy in Kubeflow. I am not sure how much time I will have since I also lead kubeflow/Manifest and security. But you can reach out on slack or linkedin.

**Comment by juliusvonkohout** [comment]
/close

since we have the manifests and the repository
