### ISSUE TITLE
Support for other Deep Learning Libraries

### ISSUE THREAD

**Issue by NathanNZ** [kubeflow/kubeflow#74]
First of all it's awesome seeing an initiative to help bring a bit of DevOps to ML, something I feel is well overdue - however I have a question just to clarify my own understanding of what KubeFlow actually is. 

> The Kubeflow project is dedicated to making Machine Learning on Kubernetes easy, portable and scalable. Our goal is not to recreate other services, but to provide a straightforward way for spinning up best of breed OSS solutions.

Regarding this statement in the readme it seems to imply that other OSS solutions will be supported however I'm not sure to what extent, especially regarding TensorFlow. My uncertainty rises from the fact that this is a Google run endeavour and the project name itself (implying the mash up between K8 and TF). As such would it be correct in thinking that other data flow programming libraries are out of this projects scope? (Caffe, CNTK etc)?

**Comment by elmiko** [comment]
@NathanNZ i think issue #33 covered some of this in the comments. imo, it will be great to see Kubeflow grow beyond the perception that it is just a TensorFlow related project.

**Comment by aronchick** [comment]
Correct! Though we do include TensorFlow to start, we're not TensorFlow
exclusive - at all! We only mention "flow" because it's such a common term
in ML. We'd ABSOLUTELY love some help including other frameworks!

**Comment by jlewi** [comment]
I came across a CRD for mxnet in [deepinsight/mxnet-operator](https://github.com/deepinsight/mxnet-operator). We'd be very receptive to including this in Kubeflow if someone is interested in taking this up. 

Forking the ksonnet prototype for TfJob to create a prototype for mxnet should be fairly straightforward.

is anyone interested in taking this on?

/cc @loadwiki @NathanNZ

**Comment by YujiOshima** [comment]
@jlewi Hi! It is great. I'm so interested in a CRD for MxNet. 
Will you have any plan to add mxnet-operator repository to kubeflow?
That repository does not look active now. But if it would be supported by kubeflow officially, I'm willing to contribute it!
