### ISSUE TITLE
Question about Kubeflow v1.8 Document availability

### ISSUE THREAD

**Issue by subasathees** [kubeflow/kubeflow#7410]
/kind question

**Question:**
Hi, Question about Kubeflow v1.8 Document availability, May I know when the document is going to release. below link is not available.
URL: https://v1-8-branch.kubeflow.org/

This is available for Kubeflow v1.7

Thanks !!

**Comment by thesuperzapper** [comment]
@subasathees Typically the latest release's docs are just the ones on the main https://www.kubeflow.org/, not a subdomain.

However, @DnPlas I see that our dropdown box on the right of the website has a 404 link to https://v1-8-branch.kubeflow.org/, we should either remove that link, or fix it.
