### ISSUE TITLE
kubeflow v1.6  Camnot load dashboard menu link

### ISSUE THREAD

**Issue by xinge-1** [kubeflow/kubeflow#7412]
<img width="238" alt="11111111" src="https://github.com/kubeflow/kubeflow/assets/76768331/7fa50721-3aca-4ce2-93bb-e093e452e993">

The dashboard menu bar is missing, and the error message Camnot load dashboard menu link is displayed

<img width="326" alt="333333333" src="https://github.com/kubeflow/kubeflow/assets/76768331/cdf6cc55-3dbc-4b3b-afc7-f788360c2035">

Then perform the delete pod operation

All pods under Kubeflow are unable to complete restart.

errors：   

Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "49c3aab025e020229be22c0450e3312d3cda079285ab71ad6aa2d660f1b8bdb3" network for pod "jupyter-web-app-deployment-d485b9c6d-jq89s": networkPlugin cni failed to set up pod "jupyter-web-app-deployment-d485b9c6d-jq89s_kubeflow" network: error getting ClusterInformation: connection is unauthorized: Unauthorized, failed to clean up sandbox container "49c3aab025e020229be22c0450e3312d3cda079285ab71ad6aa2d660f1b8bdb3" network for pod "jupyter-web-app-deployment-d485b9c6d-jq89s": networkPlugin cni failed to teardown pod "jupyter-web-app-deployment-d485b9c6d-jq89s_kubeflow" network: error getting ClusterInformation: connection is unauthorized: Unauthorized]

How can I resolve this issue?

**Comment by juliusvonkohout** [comment]
/close 

we are on Kubeflow 1.8.1/1.9
