### ISSUE TITLE
How to restrict users access inside kubeflow profile

### ISSUE THREAD

**Issue by subasathees** [kubeflow/kubeflow#7415]
/kind question

**Question:**

We have new requirement in our project , client wants to restrict **user1** not to view **user2** files in **same namespace** with same Jupyter image.
Client not interested to create multiple kubeflow profiles for this user isolation.

is there any possibility and how can we restrict users to view other users resources in same namespace kubeflow v1.8.

```
Kubeflow Version: v1.8
Kubernetes version: v1.23.5
```
Regards,
Satheeskumar

**Comment by juliusvonkohout** [comment]
I think that is for kubeflow/manifests

You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).

/close
