### ISSUE TITLE
streamlit code run in kubeflow notebook 

### ISSUE THREAD

**Issue by Sujittibe123** [kubeflow/kubeflow#7417]
Hi 
i want to execute streamlit code using kubeflow notebook that time i got network url and external url but both ip not showing the UI.
even i created loadbalancer for port 8501 then i got "RBAC: access denied" error.
<img width="610" alt="image" src="https://github.com/kubeflow/kubeflow/assets/49091383/05aafde6-8a2e-49ef-b777-cc2357806d66">

**Comment by juliusvonkohout** [comment]
take a look at jupyter-server-proxy

/close
