### ISSUE TITLE
Cannot connect to jupyter，logs show“PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'”

### ISSUE THREAD

**Issue by kingoo123** [kubeflow/kubeflow#7419]
/kind bug

**What steps did you take and what happened:**
I created a jupyter server on kubflow ui. When I try to connect I get the error "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111".
I checked the log of this pod and it showed a PermissionError error, as shown in the figure.
![1701335917677](https://github.com/kubeflow/kubeflow/assets/30140950/d3dabebb-d849-4514-aed3-ee4c79178611)

**What did you expect to happen:**
jupyter can be used normally in kubeflow ui

**Anything else you would like to add:**
Inspired  by #1241 ，I've tried ”sudo chmod -R 777 /data/k8s/jupyter-storage“. However，it doesn't work.

Here are all my running pods
![1701336619349](https://github.com/kubeflow/kubeflow/assets/30140950/895d4eb4-bb31-4a22-bb77-ad68f9433ab3)

**Environment:**

- Kubeflow version: Kubeflow Manifests v1.7
- kfctl version: NO
- Kubernetes platform: kind deploys clusters by simulating node through docker containers
- Kubernetes version: v1.25.3
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.6.1810

**Comment by juliusvonkohout** [comment]
/close

Please try Kubeflow 1.9.1, 1.7 is too old.
