### ISSUE TITLE
E2E test for bootstrapper

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#742]
We should have an E2E test for the bootstrapper.

We could modify/fork our existing E2E test to use the bootstrapper.

/assign @kunmingg

**Comment by kunmingg** [comment]
@jlewi 
Added https://github.com/kubeflow/kubeflow/issues/758 to current sprint.
How about use e2e to cover this case https://github.com/kubeflow/kubeflow/issues/758 as first step?

**Comment by kunmingg** [comment]
@jlewi Will create PR today.
