### ISSUE TITLE
Resource requests are limiting my work

### ISSUE THREAD

**Issue by TheScorpoi** [kubeflow/kubeflow#7420]
/kind bug

Hello everyone :)

**What steps did you take and what happened:**
I have installed kubeflow from raw manifests (https://github.com/kubeflow/manifests) and I was trying to explore the platform with some example pipelines, but because of the resource requests from pods (by default, I did not change nothing) I can experiment pipelines even when I have +/- 80% of my cpu free, and +\- 50% of my memory free.

![image](https://github.com/kubeflow/kubeflow/assets/66091656/5515597f-eabe-4b15-8877-8c1ce5bf4e7c)
![image](https://github.com/kubeflow/kubeflow/assets/66091656/1cc70e1e-6b78-4ca2-a328-62206c1f7f71)

**What did you expect to happen:**
Be able to use the free resources, how can I do it? Do I need to go to every yaml file and change manually the resources requests?

**Environment:**

- Kubeflow version: 1.8.0
- Kubernetes platform: AKS
- Kubernetes version: 1.26

**Comment by juliusvonkohout** [comment]
I think that is for kubeflow/manifests

You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).

/close
