### ISSUE TITLE
When the backend will support PipelineTaskFinalStatus?

### ISSUE THREAD

**Issue by Gabriel-Dalforno** [kubeflow/kubeflow#7422]
/kind question

**Question:**
I am trying to reproduce the exit handler example available at [the official docs](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/control-flow/), but I'm getting an error from the backend:

{"error":"Internal error: compiling DAG \"root\": failed to add implicit deps: task final status not supported yet\nFailed to ...

I was wondering when the PipelineTaskFinalStatus will be available to use. In my application, I want to send an email if any step of my pipeline fails. If there is a workaround for that, I would appreciate it as well.

Using PIPELINE_VERSION=2.0.3 on kubernetes and kfp==2.4.0, kfp-pipeline-spec==0.2.2, kfp-server-api==2.0.5 on python

**Comment by juliusvonkohout** [comment]
/close

this is the wrong repository, use kubeflow/pipelines instead
