### ISSUE TITLE
How can I show a dynamic kubeflow dashboard by each namespace? 

### ISSUE THREAD

**Issue by carloscao0928** [kubeflow/kubeflow#7436]
/kind question

**Question:**
Hi team, for example, I have some services, but maybe the services are only in  the namespace A , but I still have namespace B in my kubeflow, so what I want to do is, only let the service link show on the namespace A but not B, if you change to the namespace B, the link will not display. Any guide or example config? thanks

**Comment by carloscao0928** [comment]
Hi, @thesuperzapper, can you help look this? thank you :)

**Comment by juliusvonkohout** [comment]
I think this is solved in Kubeflow 1.9.1

/close
