### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [kubeflow/kubeflow#7438]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@hocnc) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jbottum** [comment]
@akgraner would your team please add this to the next Kubeflow Security Team's meeting agenda ?  thank you.

**Comment by akgraner** [comment]
Sure thing! Thank you!

**Comment by thesuperzapper** [comment]
@akgraner @jbottum just following up here, did we get any updates from @psmoros?

**Comment by akgraner** [comment]
@thesuperzapper thank you for that suggestion. We are aware and are working with the CNCF to get an email address for that purpose.

**Comment by akgraner** [comment]
@psmoros - Can you reach out to me and @juliusvonkohout via slack (akgraner) so we can set up a meeting with you an a couple other members of the security team.  And can you also email us more information at akgraner@gmail.com  and juliusvonkohout@gmail.com about the issue. 

Our next security meeting is 16 January 2024. Below is the meeting information. 

Join Zoom Meeting
[https://us06web.zoom.us/j/87118537300?pwd=NG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09](https://www.google.com/url?q=https://us06web.zoom.us/j/87118537300?pwd%3DNG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09&sa=D&source=calendar&usd=2&usg=AOvVaw3KeuzIIAISGUBhXwMT59tk)

Meeting ID: 871 1853 7300
Passcode: 273734

**Comment by akgraner** [comment]
@psmoros 

We are working with CNCF folks to get a policy and a reporting email in place. However, I'll see if we can get a reporting addresses sooner rather than later. Thank you.

**Comment by thesuperzapper** [comment]
@akgraner many security researchers oppose using email disclosures for a number of reasons:

1. __Encryption__: emails are inherently not secure and can be intercepted
2. __Phishing/Leaks__: allowing security researchers to send arbitrary attachments is a recipe for it to get hacked (potentially exposing all the other pending vulnerabilities)
2. __Tracking__: it can be unclear if the project has seen the disclosure, and so when it would be appropriate to publicly disclose if no action is taken (typically 90 days)
3. __Verification:__ it makes getting payments/recognition for anonymous disclosures impossible (we can't identify who's sending)
4. __Access Control__: Enforcing access control on the triage end is very hard
5. __Standardization__: we can't enforce any kind of structure to the report

Most large projects either use HackerOne or GitHub's in built disclosures feature.

**Comment by akgraner** [comment]
I realize that. It’s a temporary measure. Thanks!

**Comment by psmoros** [comment]
Thanks @akgraner will do :))
