### ISSUE TITLE
Ability to resize stopped notebooks.

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/kubeflow#7439]
/kind feature

**Why you need this feature:**
Currently when a notebook is created the Kubeflow UI does not provide a way to modify the notebook requests. This is a useful aspect for users of the notebooks since at times they may need a small resource footprint, and at others may want to start their notebook with more resources.

**Describe the solution you'd like:**
Ideally in the UI there should be a way to update the notebooks resource requests of stopped notebooks. Running notebooks should not expose this resource edit functionality.

**Anything else you would like to add:**
I'd be happy to contribute on the backend changes, but I don't have much experience with the frontend.

**Comment by boarder7395** [comment]
Note: This ability currently exist from the command line. Using kubectl users can update the notebook cr to change the resource requests. For minimally technical users this can be a hurdle.

**Comment by thesuperzapper** [comment]
This is one of the core features motivating Kubeflow Notebooks 2.0, see: https://github.com/kubeflow/kubeflow/issues/7156

**Comment by boarder7395** [comment]
@thesuperzapper yes you are completely correct! I think we can close this issue in favor of that then!
