### ISSUE TITLE
Integrate KubeFlow with GitLab

### ISSUE THREAD

**Issue by SwethaPerla5** [kubeflow/kubeflow#7449]
We want to integrate the GitLab with Kubeflow to deploy the Kubernetes Jobs and the Deployments, Is there any way to automate the process to deploy the jobs and deployments from the GitLab to Kubeflow, if Yes could anyone please help with the steps.

**Comment by tomaszstachera** [comment]
We've build our own tool that uses Kubeflow SDK to connect to API and deploy pipelines programmatically.

**Comment by thesuperzapper** [comment]
@SwethaPerla5 @tomaszstachera there is no official method of using GitOps to deploy Kubeflow Pipelines.

However, there is a reference repository that shows a method to do this, it is hosted on the deployKF distribution org, but can be used with any Kubeflow.

https://github.com/deployKF/kubeflow-pipelines-gitops

**Comment by juliusvonkohout** [comment]
/close

there is the KFP SDK and token based machine-to-machine authentication

**Comment by curryxjh** [comment]
So, is it possible to implement a direct call to Kubeflow within GitLab/Gitea/GitHub CI/CD to have it execute its own pipeline?

**Comment by juliusvonkohout** [comment]
Yes it is possible. take a look at kubeflow/manifests
