### ISSUE TITLE
Newline characters in PythonComponent arguments break YAML compilation

### ISSUE THREAD

**Issue by ndebuhr** [kubeflow/kubeflow#7452]
/kind bug

**What steps did you take and what happened:**
I noticed that syntactically invalid YAML is produced when compiling a standard Kubeflow PythonComponent, which contains a "\n" string in function arguments. The bug only affects compilation to YAML (JSON works fine). 

**What did you expect to happen:**

Syntactically valid YAML should be produced, and the pipeline should be runnable on Kubeflow.

**Anything else you would like to add:**
[Example source Python](https://github.com/ndebuhr/kubeflows-hub/blob/main/split/components.py#L95)
[Example compiled YAML](https://github.com/ndebuhr/kubeflows-hub/blob/main/split/split-on-tokens-openai.yaml#L8)

**Environment:**

- Kubeflow version: v2.5.0 (Python SDK)
- kfctl version: N/A (Python SDK issue)
- Kubernetes platform: N/A (Python SDK issue)
- Kubernetes version: N/A (Python SDK issue)
- OS (e.g. from `/etc/os-release`): Debian 11

**Comment by thesuperzapper** [comment]
@ndebuhr please raise issues for Kubelow Pipelines on the `kubeflow/pipelines` repo: https://github.com/kubeflow/pipelines/issues

/close
