### ISSUE TITLE
Conda environments deleted

### ISSUE THREAD

**Issue by Hipole** [kubeflow/kubeflow#7464]
Hello !

I'm sorry if the question was already asked but I've been looking for the last 2 days a way to not delete my conda environments when I restart my notebooks.

For pip install, I'm using --user to store the packages but I don't know how to do it with conda.

Thank you in advance !

**Comment by siddeshas07** [comment]
hi @Hipole  , 

Did you try this ?
Custom Environment Path: When creating your Conda environments, consider specifying a custom path using the --prefix option. This allows you to store your environments in a location that persists between notebook sessions.

`
conda create --prefix=/path/to/my/env my_env`

Activation: Within your notebook cells, activate the desired environment using conda activate with the custom path.

`!conda activate /path/to/my/env`

Package Installation: Install packages into the environment as needed. These packages will be stored within the specified environment directory.


If you have any further questions or need additional assistance, feel free to ask! will try to help.
