### ISSUE TITLE
Kubeflow dashboard opens but when accessing any menu item it says "No user detected" and goes blank

### ISSUE THREAD

**Issue by nirmesh** [kubeflow/kubeflow#7467]
/kind bug
when i am acceing kubeflow dashoard it is opening but on any menu like notebook etc it is showing
{"log":"No user detected.","status":401,"success":false,"user":null}

I am unable to logout also it says 404.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have checked profile and it is all fine.

**What did you expect to happen:**
with username "user@example.com" and password "12341234" it should open but my login screen itself is not coming or cached not sure tried in differnt browser as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

I am on microk8s :

kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
![image](https://github.com/kubeflow/kubeflow/assets/278157/b2748f00-15e4-4492-84d0-830dd2b0f987)

**Comment by nirmesh** [comment]
![image](https://github.com/kubeflow/kubeflow/assets/278157/f766c8ec-daae-41ed-a433-0572a2151364)

**Comment by tariq-hasan** [comment]
I would like to take on this ticket.

**Comment by swasenius** [comment]
Looks like I'm hitting this one also. How to clear this session so that I'm able to log out at least?

**Comment by Irshu786** [comment]
Yes, exactly I'm also facing the same issue, requesting any mentor kindly
help us on this issue.

**Comment by swasenius** [comment]
My issue was happening during KF upgrade 1.7->1.8 where some configuration was lost from dex-auth and oidc-gatekeeper, so adding those back, restart of them fixed this.

**Comment by ryansliceup** [comment]
I am hitting this on a fresh deploy.

{"log":"No user detected.","status":401,"success":false,"user":null}

**Comment by rohank07** [comment]
This worked for me when I tried adding request header `kubeflow-userid: anonymous@kubeflow.org`

**Comment by swasenius** [comment]
May I ask how did you do that exactly? ^^

**Comment by rohank07** [comment]
> May I ask how did you do that exactly? ^^

I am using google chrome as internet browser. I installed extension called modheader :

![image](https://github.com/user-attachments/assets/228de6e8-c29a-4990-bb7f-bb9dedcde97b)

**Comment by Tarzan-07** [comment]
I am getting this same issue with kubeflow on AWS. I am also using istio within my kubernetes cluster. According to google search results, it might be related to authentication issue. But is it really ???
Because I am able to see all the namespaces that I have access to on the dropdown. Honestly, I am a bit clueless and I don't know what is causing this. Any help would be great.

**Comment by juliusvonkohout** [comment]
Is this still valid in https://github.com/kubeflow/manifests/releases/tag/v1.9.1-rc.3 or does it only affect unsupported versions such as 1.7, 1.8 ? Because then we should close it.

**Comment by juliusvonkohout** [comment]
Please use 1.9.1. Our Cicd in kubeflow/manifests is working
/close

**Comment by lsabreu96** [comment]
Hi there
I'm facing the same issuing even on 1.9.1 (was firstly deployed using 1.9.2)

Any hints on debugging ?
P.s.: our eks already had an Istio deployed prior to Kubeflow and we tweaked it so that Ingress Gateway (LB) proxies the traffic to an Oauth which then forwards to centraldashboard. We made the necessary adjustments in the Oauth so that when the request reaches centraldashboard we have the kube-userid set in the header (debugged intercepting istio-proxy traffic)

**Comment by juliusvonkohout** [comment]
> Hi there
> I'm facing the same issuing even on 1.9.1 (was firstly deployed using 1.9.2)
> 
> Any hints on debugging ?
> P.s.: our eks already had an Istio deployed prior to Kubeflow and we tweaked it so that Ingress Gateway (LB) proxies the traffic to an Oauth which then forwards to centraldashboard. We made the necessary adjustments in the Oauth so that when the request reaches centraldashboard we have the kube-userid set in the header (debugged intercepting istio-proxy traffic)

The authentication changed a lot in Kubeflow 1.9.1. please configure oauth2-proxy or Dex with your IDP and Reade the documentation  first at https://github.com/kubeflow/manifests/blob/master/README.md#oauth2-proxy and https://github.com/kubeflow/manifests/blob/master/README.md#dex
