### ISSUE TITLE
Internal error occurred: failed calling webhook "admission-webhook-deployment.kubeflow.org": failed to call webhook

### ISSUE THREAD

**Issue by vkatrychenko** [kubeflow/kubeflow#7482]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We have noticed this error can happen in case that there are several pipelines running together at the same time. 

<img width="1539" alt="image" src="https://github.com/kubeflow/kubeflow/assets/25283055/7c8936c7-016b-4cec-8248-65b755ac95a5">

**What did you expect to happen:**
Should be able to see the corresponding details in the tabs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Do you have an idea what needs to be done in order to fix this? Is it possible to increase maybe that deadline or something like that? 

**Environment:**

- Kubeflow version: 1.6:
- kfctl version: (use `kfctl version`):;
- Kubernetes platform: AKS (Azure);
- Kubernetes version: 1.26;
- OS (e.g. from `/etc/os-release`): Ubuntu;

**Comment by aaj-synth** [comment]
Any updates on this? We're seeing this occasionally on `kubflow v1.7`

**Comment by vkatrychenko** [comment]
@aaj-synth try to upgrade admission-webhook to v1.8. We did the same, and it seems to be okay now.
You can keep the other components of Kubeflow in version 1.7.

**Comment by andreyvelich** [comment]
Thanks for the update, feel free to re-create issue in the `kubeflow/pipelines` repository.
