### ISSUE TITLE
Update the PR Issue Link at `README.md`

### ISSUE THREAD

**Issue by carrycooldude** [kubeflow/kubeflow#7483]
/kind bug

**What steps did you take and what happened:**
This [Link](https://k8s-gubernator.appspot.com/pr) is not working

**What did you expect to happen:**
Open the PR Dashboard

**Anything else you would like to add:**
Update the link or maybe share with me , I will fix it.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
This should be resolved by the updated README.
