### ISSUE TITLE
Mismatch on Workspace Volume (UI)

### ISSUE THREAD

**Issue by ronaldpetty** [kubeflow/kubeflow#7486]
/kind bug

**What steps did you take and what happened:**

Install 1.3 or 1.4 (no changes to default configuration).

**What did you expect to happen:**

When creating Notebook Workspace Volume the default and recommended size to match initially.

<img width="865" alt="image" src="https://github.com/kubeflow/kubeflow/assets/1390435/0bb61c4f-eaad-4eeb-b839-b21cd7e02968">

The actual size PVC is 5 GB.

```
~$ kubectl get pvc -n team-1 test1-volume
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test1-volume   Bound    pvc-77ea8dac-4947-4e37-aca9-0897e8f7fb5c   5Gi        RWO            local-path     55s
```

Guessing the 10 Gi should show 5Gi as well.

**Comment by thesuperzapper** [comment]
@ronaldpetty in [deployKF](https://www.deploykf.org/), you can change the default volume size (for __new__ volumes) by setting the [`kubeflow_tools.notebooks.spawnerFormDefaults.workspaceVolume.value.newPvc.spec.resources.requests.storage`](https://github.com/deployKF/deployKF/blob/v0.1.5/generator/default_values.yaml#L1606) value, or am I misunderstanding the problem?

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
