### ISSUE TITLE
HOw to access kubeflow dashboard?

### ISSUE THREAD

**Issue by sonwander** [kubeflow/kubeflow#7494]
Hello to all. I am trying to access the dashboard, but no success. I am running kubernetes locally installed via minikube. My lasta attempt was running the following command:

`kubectl create -f https://github.com/kubeflow/kubeflow/master/components/centraldashboard/config/centraldashboard-config.yaml -n kubeflow`

But it gives the following error: 
"kubectl create -f https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/config/centraldashboard-config.yaml -n kubeflow
error: error parsing https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/config/centraldashboard-config.yaml: error converting YAML to JSON: yaml: line 206: mapping values are not allowed in this context
"

Any help will be much appreciated.

**Comment by rimolive** [comment]
I don't think this would fix your issue. Can you provide the output of `kubectl get pod -n kubeflow` to inspect the KF installation?

**Comment by siddeshas07** [comment]
Did you try kubectl logs <pod-name> -n kubeflow and kubectl describe <resource-name> -n kubeflow) that may provide some logs .

**Comment by thesuperzapper** [comment]
Please reopen if you have not already solved this.
