### ISSUE TITLE
Optionally require auth token

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/kubeflow#7498]
/kind feature

**Why you need this feature:**

It should really be possible to require users to be authenticated when interacting with Kubeflow, so I would like to be able to require authentication without using Istio

**Describe the solution you'd like:**

```typescript
if (checkToken) {
    const token = req.headers.authorization;

    if (!token) {
        return res.status(401).send('Unauthorized - Missing token');
    }
}
```

**Comment by juliusvonkohout** [comment]
/close

this belongs to kubeflow/manifests i think

**Comment by AndersBennedsgaard** [comment]
@juliusvonkohout please re-open. While it is possible to do this with Istio, or something else, this should really be handled in the code-base instead.

**Comment by AndersBennedsgaard** [comment]
I'm not arguing that Kubeflow should remove Istio as a required dependency (even though I would be very happy if this were to happen).
I'm just saying that looking for a `ENFORCE_AUTHENTICATION` environment variable in the central dashboard and other UIs and returning 401 if users and other services doesn't have the user ID header set (or other authentication mechanisms) should be very possible - and arguably much more secure than enforcing it through one of many reverse proxies in front of the solution.

The reason I hit this issue came from a minor misconfiguration in my installation of Kubeflow (or actually Istio), which allowed everyone and everything to do stuff in the central dashboard, without any indication of such an error. Setting `ENFORCE_AUTHENTICATION` or something else in the central dashboard, would make it possible for admins to be completely sure that there are no non-authorizaed users messing around in your solution.

**Comment by juliusvonkohout** [comment]
Ok the central dashboard part belongs to kubeflow/kubeflow (will be migrated in the next months), but most other things are probably more related to kubeflow/manifests.

**Comment by juliusvonkohout** [comment]
/reopen

To split this up and migrate later on

**Comment by thesuperzapper** [comment]
I am going to assume this request is about Kubeflow Dashboard, and rejecting requests that don't have `kubeflow-userid` header set, rather than treating the user as "anonymous" but still allowing them to browse the UI.

**Comment by AndersBennedsgaard** [comment]
> I am going to assume this request is about Kubeflow Dashboard, and rejecting requests that don't have `kubeflow-userid` header set, rather than treating the user as "anonymous" but still allowing them to browse the UI.

Yes, exactly. Sorry if my poor explanation didn't get that across 😅
