### ISSUE TITLE
Maximum number of artifacts exceeded. How to aggregate artifacts from >100 ParallelFor iterations

### ISSUE THREAD

**Issue by bronevet-abc** [kubeflow/kubeflow#7513]
/kind bug

I am running a ParallelFor loop with > 100 iterations and aggregating the resulting artifacts into a dsl.Collection but I'm getting the following error:
com.google.cloud.ai.platform.common.errors.AiPlatformException: code=INVALID_ARGUMENT, message=Maximum number of artifacts exceeded. Maximum allowed: 100, requested: 270, cause=null

Is there a way to raise this maximum so I can run larger ParallelFor iterations?
- Kubeflow version: 2.4
- Running on the GCP Vertex Pipelines service

**Comment by bronevet-abc** [comment]
Interesting! I'm not sure exactly the mechanics of this. Are you suggesting a custom container for the task running within the ParallelFor or for the task receiving the aggregated data objects? Can you point to any examples for this or the relevant APIs? Thank you!

**Comment by juliusvonkohout** [comment]
/close

this is the wrong repository. Use kubeflow/pipelines for pipelines stuff.
