### ISSUE TITLE
The pipeline running status is inconsistent with AWS Glue

### ISSUE THREAD

**Issue by carloscao0928** [kubeflow/kubeflow#7524]
/kind bug

**What steps did you take and what happened:**
Hi team, I had encountered a problem, that's the pipeline's status is not same with the AWS Glue job, I had set my pipeline with retry time as 2, if the first time it's failed, the pipeline will be also failed, although the second time it's running succeed on AWS side.

Below is the pipeline 's status, we can see, it failed, time is 10:05:15 AM,
![image](https://github.com/kubeflow/kubeflow/assets/58930323/21fa031d-f66b-4ab1-85c8-12970c42f42b)

And we had set the retry time as 2,
<img width="1319" alt="Screenshot 2024-03-22 at 10 54 33" src="https://github.com/kubeflow/kubeflow/assets/58930323/8ec21e19-be7a-4170-860b-3eaaf9fcdfcf">

This is the screenshot from AWS Glue,
<img width="1331" alt="Screenshot 2024-03-22 at 10 56 44" src="https://github.com/kubeflow/kubeflow/assets/58930323/4fbb5436-842a-466a-97bc-9280e21f3911">

The first time failed, but the next attempt was succeed, but in Kubeflow side, the task was failed.

**What did you expect to happen:**
The pipeline 's status should be samed as the job status on AWS Glue.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: build version v1.8.0
- kfctl version: (use `kfctl version`):
- Kubernetes platform: AWS EKS
- Kubernetes version: 1.26
- OS: Amazon Linux 2

**Comment by Mehrozkhan** [comment]
@carloscao0928, has this issue been resolved?

**Comment by carloscao0928** [comment]
@Mehrozkhan ,hi, thanks. it had been solved, we have some logic mistake on await function,
