### ISSUE TITLE
Unable to configure a specific hostname for notebook-controller generated VirtualServices

### ISSUE THREAD

**Issue by josh-thisisbud** [kubeflow/kubeflow#7528]
Hey there, I'm running into an issue where Istio is preferring to route traffic to other cluster components due to them being more specific with their configured hostnames.

E.g. A request to `dave.example.com/notebooks/dave/etc` is preferring to go to a VS with `host: dave.example.com, path: /` than the generated virtualservice with `host: ['*'], path: /notebooks/dave/etc`

I would like to be able to expose my notebooks in a similar way, however I find that the hostname value is hardcoded into this service. https://github.com/kubeflow/kubeflow/blob/bd7f250df22e144b114177536309d28651b4ddbb/components/notebook-controller/controllers/notebook_controller.go#L499

**Comment by josh-thisisbud** [comment]
Suggested fix at https://github.com/kubeflow/kubeflow/pull/7529

**Comment by andreyvelich** [comment]
According to this, it was resolved: https://github.com/kubeflow/kubeflow/pull/7529#issuecomment-2106058370
