### ISSUE TITLE
Intel GPU not in default GPU vendor list in Jupyter Notebook server

### ISSUE THREAD

**Issue by yshashix** [kubeflow/kubeflow#7541]
/kind question
/kind feature
/area jupyter

Hello,

I use Kubeflow v1.8.0.
It seems that Intel GPU is not listed in default "GPU Vendor" in Jupyter Notebook server webui (when creating a notebook).
May I know when will it be added? I can see that one method is by editing configmap of jupyter web-app.

Thank you.

**Comment by yshashix** [comment]
I have enabled in my Juypter Notebook server by editing jupyter web-app with following line:

 `    vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"
            - limitsKey: "gpu.intel.com/i915"
              uiName: "INTEL"`

**Comment by thesuperzapper** [comment]
@yshashix is this an official request from Intel?

If so, let's have a discussion, please join the slack and message me and @kimwnasptd (the other lead) so we can discuss.

**Comment by yshashix** [comment]
@thesuperzapper , Intel colleagues who are working with Kubeflow will bring it soon. @tkatila
 Thanks for adding in v1.9.1 milestone.
