### ISSUE TITLE
issue with inferenceService ingress

### ISSUE THREAD

**Issue by khalidkhushal** [kubeflow/kubeflow#7563]
/kind question

Hi,
I am trying to deploy kserve using kubeflow raw manifest on K3s cluster.
I can create a inferenceService and is shown as READY as stated below:

`NAMESPACE NAME URL READY PREV LATEST PREVROLLEDOUTREVISION LATESTREADYREVISION AGE kubeflow-user-example-com sklearn-iris-2 http://sklearn-iris-2.kubeflow-user-example-com.192.168.10.49.sslip.io True 100 sklearn-iris-2-predictor-00001 100m kubeflow-user-example-com sklearn-iris http://sklearn-iris.kubeflow-user-example-com.192.168.10.49.sslip.io True 100 sklearn-iris-predictor-00001 20m`

I am making request on this using jupyter notebook, created from kubeflow in same namespace, with following code:

===========
```
url= "http://sklearn-iris.kubeflow-user-example-com.192.168.10.49.sslip.io"
body = json.dumps({
'instances': [
[6.8, 2.8, 4.8, 1.4],
[6.0, 3.4, 4.5, 1.6]
]
})
headers = {'Content-Type': 'application/json'}
print("URL ==========>", url)
response = requests.post(url, headers=headers, data=body, verify=False)
print("response=====>",response.json())
```
========
But in logs it shows GET request with 404 error:

`2024-04-22 13:05:38.559 uvicorn.error INFO: Started server process [1] 2024-04-22 13:05:38.560 uvicorn.error INFO: Waiting for application startup. 2024-04-22 13:05:38.563 1 kserve INFO [start():62] Starting gRPC server on [::]:8081 2024-04-22 13:05:38.563 uvicorn.error INFO: Application startup complete. 2024-04-22 13:05:38.563 uvicorn.error INFO: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit) 2024-04-22 13:13:18.987 uvicorn.access INFO: 10.42.0.216:0 1 - "GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Fauthservice%2Foidc%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=MTcxMzc5MTU5OHxOd3dBTkVoTVZqTk5NMUJPU0ZoVlVUSkRRVE5RUTFKUVNsbFJWVU5RUlZCUFJEWkdTbGRDVkU0eVJGUTNTa1JRV1RSVVdrOHlNbEU9fG6TTEoiRo50s6nAwZRUnEiQBr2KSckfvQBTkZZD-sT5 HTTP/1.1" 404 Not Found 2024-04-22 13:13:18.987 kserve.trace kserve.io.dex.auth: 0.0005548000335693359 2024-04-22 13:13:18.987 kserve.trace kserve.io.dex.auth: 0.0005500000000004945`

What could possibly the reason to it?
I have bee debugging this but had no luck.
Thanks in advance.

**Comment by AndersBennedsgaard** [comment]
Would it make sense to move this to https://github.com/kserve/kserve instead, since KServe isn't a Kubeflow component anymore?

**Comment by juliusvonkohout** [comment]
Yes Kserve or manifests

You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).

/close
