### ISSUE TITLE
Support easier feature serving and model serving from External Add-Ons

### ISSUE THREAD

**Issue by franciscojavierarceo** [kubeflow/kubeflow#7564]
/kind feature

## **Why you need this feature:**
At the moment, Model serving (via KServe) and Feature Serving (via Feast—the Feature Store) are separate components without any guidance on how to best serve production machine learning features and models.

It would be beneficial to the community to outline (or support) how these two components could best fit together so that users could launch production machine learning applications with a better understanding about best practices. At the moment, this is outlined by KServe but the approach has some limitations [1]. It would be beneficial to offer some form of integration that outlines how users could launch these two services in a way that maximizes the strengths of each component.

[1] The limitations will be discussed more thoroughly in the RFC but [their approach](https://kserve.github.io/website/0.7/modelserving/v1beta1/transformer/feast/#run-a-prediction) is to treat the online feature store as a Transformer.

## **Describe the solution you'd like:**
I am a maintainer for Feast and I will be drafting a proposal in [this document](https://docs.google.com/document/d/1PzBbTs_8R73XhuDq3CO0slmGy5S_ci2rwtbx1L-Ukqc/edit#heading=h.9gaqqtox9jg6).

There are pros and cons to different approaches and I would like to solicit feedback from the community to understand what would result in the best tradeoffs.

## **Anything else you would like to add:**

Below are some useful references from industry leaders on how some other platforms support a Feature Store integration with model inference. Notice that they generally request features before executing the inference step.

- [Sagemaker's high level feature store and inference diagram](https://aws.amazon.com/sagemaker/feature-store/)
![image](https://github.com/kubeflow/kubeflow/assets/4163062/94803b1a-b5c2-4209-b989-84970b4b53c8)

- [Databrick's high level feature store and inference diagram](https://docs.databricks.com/en/machine-learning/feature-store/index.html#how-does-databricks-feature-store-work)

![image](https://github.com/kubeflow/kubeflow/assets/4163062/b6a0baa0-f0c7-4b3c-8067-8320f71f35c5)

- [Tecton's high level feature store and inference diagram](https://www.tecton.ai/blog/what-is-a-feature-store/)
![Screenshot 2024-04-23 at 12 05 15 PM](https://github.com/kubeflow/kubeflow/assets/4163062/c2376bae-5ccc-482a-ad8c-d125a14d9dd1)

**Comment by juliusvonkohout** [comment]
Please close and reopen in kubeflow/manifests or kubeflow/community. See https://github.com/kubeflow/kubeflow/pull/7618#issuecomment-2188882668
