### ISSUE TITLE
redundancy code

### ISSUE THREAD

**Issue by Jerry-yz** [kubeflow/kubeflow#7567]
/kind question

**Question:**
[You can ask any question about this project.]
redundancy verify for example:
https://github.com/kubeflow/kubeflow/blob/bd7f250df22e144b114177536309d28651b4ddbb/components/notebook-controller/controllers/culling_controller.go#L114
i have a pr fix those:
https://github.com/kubeflow/kubeflow/pull/7566

**Comment by andreyvelich** [comment]
We can close it since the PR was closed.
