### ISSUE TITLE
Is there any optimization we can do when using preemptible instances running jobs.

### ISSUE THREAD

**Issue by zwzhang0107** [kubeflow/kubeflow#7577]
/kind question

**Question:**

Most cloud providers have provide preemptible instance with better cost efficiency(e.g. [Alibaba Cloud ECI](https://www.alibabacloud.com/help/en/eci/use-cases/run-jobs-on-a-preemptible-instance?spm=a2c63.l28256.0.0.ab9134c5eNxmvn)).

In old days before k8s, spark added better handling for node shutdown, for better use of EC2 spot node. Recently, there are also [some discussions](https://dl.acm.org/doi/10.1145/3620665.3640411) in ASPLOS'24. 

I'm wondering is there any work (maybe already done?) to make jobs better use of preemptible instances. I will be honored to join if there is any plan.

**Comment by juliusvonkohout** [comment]
I think that is for kubeflow/manifests and yes it is possible.

You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).

/close
