### ISSUE TITLE
Support using bootstrapper image as a kube deployment.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#758]
1. This is needed by https://github.com/kubeflow/kubeflow/issues/757
2. Can save user's effort of running docker container locally

**Comment by jlewi** [comment]
Sounds good to me.

**Comment by inc0** [comment]
I did that with statefulset - https://github.com/kubeflow/kubeflow/commit/108313ae6290597cbacf820bf99057cba623337a

**Comment by kunmingg** [comment]
@inc0 Thanks, https://github.com/kubeflow/kubeflow/pull/766 removed some of your TODOs in Dockerfile you might want review?
