### ISSUE TITLE
Support KFP V2 on the front page card

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/kubeflow#7584]
/kind feature

**Why you need this feature:**

The "Recent Pipelines" card on the home page in the central dashboard is hard-coded to always use `/pipeline/apis/v1beta1/` to list a couple of pipelines:

https://github.com/kubeflow/kubeflow/blob/5ed505b9e88aca4849a1ea1dd8df8179c4525258/components/centraldashboard/public/components/pipelines-card.js#L99

However, as KFP V2 is getting more traction, we should also support using `/pipeline/apis/v2beta1/`.
This should be a very small change, since it seems that this API is backwards compatible with V1Beta1.

**Describe the solution you'd like:**

Support specifying whether to use KFP V1 or V2, perhaps through an environment variable

**Anything else you would like to add:**

I am currently running a KFP V2-only instance (because of ARM-issues with V1), which is how I found the issue, since the card shows an error:

![image](https://github.com/kubeflow/kubeflow/assets/34585076/0752aef3-7ffe-4055-aa6a-3b1cffb4abad)

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
