### ISSUE TITLE
External link added to the central dashboard does not work

### ISSUE THREAD

**Issue by luntropy** [kubeflow/kubeflow#7594]
/kind bug

**What steps did you take and what happened:**
Updated the central dashboard configmap to include the example external link: 
```
"externalLinks": [
        {
          "type": "item",
          "iframe": false,
          "text": "Kubeflow Website",
          "url": "https://www.kubeflow.org/",
          "icon": "launch"
        }
```

Once the central dashboard was updated, the "Kubeflow Website" appeared in the menu, but clicking it did not result in opening the website as it was expected. 

**What did you expect to happen:**
To be able to reach https://www.kubeflow.org/ by clicking the button in the menu.

**Anything else you would like to add:**
X

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.6.1
- kfctl version: (use `kfctl version`): NA
- Kubernetes platform: (e.g. `minikube`): rke2
- Kubernetes version: (use `kubectl version`): v1.29.0+rke2r1
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by elvisnovoa** [comment]
@luntropy I had the same issue just now and I fixed it by using `link` instead of `url`. 
The documentation probably needs to be updated.

**Comment by luntropy** [comment]
Thank you, it worked.

**Comment by luntropy** [comment]
Opened a new issue as part of the website repo so the documentation can be updated as this is not actually a bug - https://github.com/kubeflow/website/issues/3803
