### ISSUE TITLE
Translation file messages.fr.xlf is identical to messages.xlf

### ISSUE THREAD

**Issue by tiansiyuan** [kubeflow/kubeflow#7599]
/kind bug

They are located at:

components/crud-web-apps/jupyter/frontend/i18n/messages.xlf

components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by juliusvonkohout** [comment]
/close
as decided by @andreyvelich @tarilabs in the migration document
