### ISSUE TITLE
SSH to Notebook Pod

### ISSUE THREAD

**Issue by SuperTyrael** [kubeflow/kubeflow#7614]
/kind question

**Question:**
Hi! Just want to know is there any ways to connect to Notebook Pod via SSH? Typically we can use portforward on jump server to do this. I am thinking is there any other ways like configuring Istio Gateways to achieve this. Or we already have some methods to do this. 
Btw, very curious about details of Kubeflow's network arch, any article/video to dive into that? 

Many thanks!!!

**Comment by juliusvonkohout** [comment]
I think that is for kubeflow/manifests 

Yes there are some videos, but i would start with the oldest first.

Kubecon / Kubeflow Summit 2024 Speaker: https://colocatedeventseu2024.sched.com/event/1YFiH
https://www.youtube.com/watch?app=desktop&v=f7C3v0gJRVI&list=WL&index=1

Kubecon 2023 Speaker: https://kccnceu2023.sched.com/event/1HyY8
https://www.youtube.com/watch?v=wQaOa4Kjxs0

Kubeflow Summit 2023 Speaker: https://www.kubeflow.org/events/kubeflow-summit-2023/
https://www.youtube.com/watch?v=XKHVt2yxQFo

Blogposts:
https://blogs.vmware.com/opensource/2023/06/20/hardening-kubeflow-security-for-enterprise-environments-2/
https://www.cncf.io/blog/2023/07/25/kubeflow-brings-mlops-to-the-cncf-incubator/

/close

**Comment by thesuperzapper** [comment]
@SuperTyrael actually I think @juliusvonkohout is mistaken, this is not currently possible.

However, we are discussing what this might look like for Notebooks 2.0, follow the issue here:

- https://github.com/kubeflow/notebooks/issues/23
