### ISSUE TITLE
Portable kubeflow installation on a running k8s platform 

### ISSUE THREAD

**Issue by MrNocTV** [kubeflow/kubeflow#7617]
/kind question

**Question:**
In my company, there is a team running a k8s cluster.
They provide connection to the cluster a multi-tenant.
Each tenant has a service account, a kubeconfig file to connect and a namespace.
I wonder if it's possible to install kubeflow with this setup.

**Comment by juliusvonkohout** [comment]
I think that is for kubeflow/manifests

/close

**Comment by juliusvonkohout** [comment]
@MrNocTV 

You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).
