### ISSUE TITLE
Perform proper logout for Oauth2-Proxy

### ISSUE THREAD

**Issue by michaltreter-identt** [kubeflow/kubeflow#7624]
/kind bug

**What steps did you take and what happened:**
- Deploy Kubeflow with `oauth2-proxy`
- Update `LOGOUT_URL` env var to: `/oauth2/sign_out` for `centraldashboard`
- Try to log out from dashboard, ending up with `403` errors as `oauth2-proxy` expects `GET` method

**What did you expect to happen:**
- Possibility to define with which method logout url will be called (`GET` or `POST`)
- Possibility to provide `redirect_uri` too 

**Anything else you would like to add:**
It would be nice to have full support for OAuth2-Proxy as it is already supported by Kubeflow. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- Kubernetes version: 1.28

**Comment by weistonedawei** [comment]
Using kubeflow (1.9.0) manifests deployment method, clicking on Logout does logout the dashboard.  However, it requires user to refresh the browser to get user back the login page. 

It would be much better to redirect properly to dashboard login after user logs out automatically as it is in 1.7.1 with afterLogoutURL configuration in oidc-authservice.

**Comment by juliusvonkohout** [comment]
Might be closed by https://github.com/kubeflow/kubeflow/pull/7631
