### ISSUE TITLE
Notebook image for KF 1.7 vs 1.9

### ISSUE THREAD

**Issue by ACodingfreak** [kubeflow/kubeflow#7627]
/kind question
Hi All,

I am quite new to project and have a very basic question with respect to custom images for Jupyter notebooks.
Currently I am using KF1.7 infrastructure and the default Jupyter notebook image for 1.7 uses tensorflow-gpu 2.9.3.
https://hub.docker.com/layers/kubeflownotebookswg/jupyter-tensorflow-cuda-full/v1.7.0/images/sha256-3ab71ff1dfe27d22f5edbf7542c1fd23a98f6b453914386324bbd9b704edc2c5?context=explore

If I use Jupyter notebook image created for 1.9 (tensorflow-cuda 2.15) in KF1.7 will there be any implications with the pipelines, run and experiments which are part of KF1.7 ?

docker pull kubeflownotebookswg/jupyter-tensorflow-cuda-full:latest

**Comment by thesuperzapper** [comment]
@ACodingfreak it will work fine, till this point, all notebook images are forwards/backwards compatible.
