### ISSUE TITLE
Swift-TensorFlow-Starter (STS) integration

### ISSUE THREAD

**Issue by zachgrayio** [kubeflow/kubeflow#767]
I'm the author of STS ([swift-tensorflow-starter](https://github.com/zachgrayio/swift-tensorflow-starter/)) as well as the first Swift for TensorFlow [docker image](https://github.com/zachgrayio/swift-tensorflow).

It'd be great to work on some sort of an easy integration with Kubeflow. The starter project itself is Dockerized and ready to rock so it shouldn't be much work, but I wanted to gauge interest before jumping into this, as well as figure out the best path forward on any collaboration.

Let me know what you think!

**Comment by ankushagarwal** [comment]
Thanks for your contribution @zachgrayio!

(I am not very familiar with Swift or Swift for Tensorflow)

I came across this project https://github.com/algal/iSwift/tree/swift-tensorflow which seems to provide a docker image with Jupyter Notebook / Swift / Tensorflow

We currently provide jupyter notebook Docker images with tensorflow pre-installed. Ideally for Swift for Tensorflow, we might want to provide a similar Jupyter notebook experience

**Comment by ankushagarwal** [comment]
See https://github.com/kubeflow/kubeflow/issues/763

**Comment by jlewi** [comment]
We would very much like to integrate and support swift. As @ankushagarwal mentioned it would be great to make the STS Jupyter notebook one of the supported runtimes that can be launched by Juypter.

A good place to start would just be trying to launch the existing Jupyter notebooks via JupyterHub and seeing which changes if any are needed.

**Comment by jlewi** [comment]
@zachgrayio with 0.5 (available on master coming end of march) it should be much easier to build Jupyter images that work with Kubeflow.

I think the primary requirement is to add a default command like this to the Docker image

https://github.com/kubeflow/kubeflow/blob/20431c47de02420f6ac105f7c23cce518ac35364/components/tensorflow-notebook-image/Dockerfile#L158

**Comment by jlewi** [comment]
@rohithreddy this is an area where we could use help.

There is a lot of interest in SWIFT these days. FAST AI in particular is getting on board.
https://www.fast.ai/2019/03/06/fastai-swift/

**Comment by jlewi** [comment]
https://github.com/google/swift-jupyter

We might have to set some security option to allow ptrace.

**Comment by ankushagarwal** [comment]
Test notification

**Comment by mosn** [comment]
I am a swift developer and would like to have a look at this as well. I wonder is the issue resolved and someone made the image or priority shifted?

**Comment by mosn** [comment]
Those who have arrived here looking for a better explanation: 

Visit [swift-jupyter](https://github.com/google/swift-jupyter/blob/master/docker/Dockerfile) and navigate to docker/Docker

Check their current  CMD and ENTEYPOINT and replace it with this one or pickup the part that works for you.  You might wanna take a look at the Kubeflow offical TF images to find middle ground. 
```
CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```

The most important aspect to note is that the controller looks into `base_url=${NB_PREFIX}` to point traffic towards this implementation, therefore, unless you have an alternative design, make sure that `NB_PREFIX` is properly updated and you should be good to go.  

Another aspect is security,  this is an ongoing topic and you'll find various discussions in this.
