### ISSUE TITLE
jupyterNotebookPVCMount is not work in v0.1.2

### ISSUE THREAD

**Issue by ogre0403** [kubeflow/kubeflow#770]
Hi 

I followed [steps](https://github.com/kubeflow/kubeflow#steps) to install kubeflow v0.1.2, and want to use pvc to keep user jupyter data.  I found `jupyterNotebookPVCMount` parameter is available but it is not work. 

The reason should be that  `jupyterNotebookPVCMount` is not pass into [jupyterhub.libsonnet](https://github.com/kubeflow/kubeflow/blob/v0.1.2/kubeflow/core/jupyterhub.libsonnet#L6) in v0.1.2 and v0.1.3. 

```sh
ks param list
COMPONENT     PARAM                   VALUE
=========     =====                   =====
kubeflow-core cloud                   "null"
kubeflow-core disks                   "null"
kubeflow-core jupyterHubAuthenticator "null"
kubeflow-core jupyterHubImage         "gcr.io/kubeflow/jupyterhub-k8s:1.0.1"
kubeflow-core jupyterHubServiceType   "ClusterIP"
kubeflow-core jupyterNotebookPVCMount "pv"
kubeflow-core name                    "kubeflow-core"
kubeflow-core namespace               "null"
kubeflow-core reportUsage             "false"
kubeflow-core tfAmbassadorServiceType "ClusterIP"
kubeflow-core tfDefaultImage          "null"
kubeflow-core tfJobImage              "gcr.io/kubeflow-images-public/tf_operator:v20180329-a7511ff"
kubeflow-core tfJobUiServiceType      "ClusterIP"
kubeflow-core usageId                 "unknown_cluster"
```

**Comment by inc0** [comment]
try setting jupyterNotebookPVCMount to mountpath, like "/home/jovyan/work". PVC itself will be created automatically on notebook spawn

**Comment by ogre0403** [comment]
@inc0  Thansk. 
I know I have to set jupyterNotebookPVCMount to mountpath, but my point is that  `jupyterNotebookPVCMount` is not pass into jupyterhub.libsonnet.

```
$.parts(params.namespace).jupyterHub(params.jupyterHubImage),
```

**Comment by inc0** [comment]
Ah, you're right, I didn't notice that whole feature is missing from 0.1 branch.

@jlewi should we port it?

**Comment by jlewi** [comment]
The PVC functionality is currently broken so I don't see much use in cherry picking what we have into the release branch.

See #561 regarding permissions issue which still aren't resolved.

We need an E2E test #278 to verify this feature is actually working.

We should probably update our docs to reflect that this isn't working yet.

/cc @pdmack

**Comment by Cas-pian** [comment]
I met this problem too. After setting `jupyterNotebookPVCMount` to `/home/jovyan/work` and redeploy, no valid pvc is created for the notebooks, even logged in. I'm using ceph as backend storage

**Comment by ogre0403** [comment]
@Cas-pian Because some issues aren't still resolved,  I thought the feature is not included in 0.1 branch. 

For now, you can try master branch, `jupyterNotebookPVCMount` is work in master branch.

**Comment by Cas-pian** [comment]
@ogre0403 OK, I'll take a look, thanks!

**Comment by jlewi** [comment]
@pdmack Committed a bunch of fixes to head this week. It would be great if you could try it out and let us know if there are still issues.

It should now be possible to mount the entire home directory on PV.

**Comment by pdmack** [comment]
In kubeflow/testing#144, we have detected an issue where a disk provisioner overrides any volumes and mounts before it, including the `/home/jovyan` one. Let me know if that tracks with any issues you may be encountering from master.

**Comment by ogre0403** [comment]
@jlewi @pdmack 

Thanks for your great work.  `jupyterNotebookPVCMount` is work for me now. 
I think we can close this issue now.
