### ISSUE TITLE
Kubeflow-core README

### ISSUE THREAD

**Issue by mikevoets** [kubeflow/kubeflow#774]
The README at https://github.com/kubeflow/kubeflow/tree/master/kubeflow/core seems to be out-dated. ks apply doesn't have a `-f` flag (anymore). 

ksonnet version: 0.10.1
jsonnet version: v0.10.0
client-go version: 1.8

**Comment by xyhuang** [comment]
The doc is auto generated, you might want to look at the ksonnet doc generator script: https://github.com/ksonnet/parts/blob/master/doc-gen/main.go
