### ISSUE TITLE
Create & label P1 issues needed for an initial release of Horovod support

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#778]
We should create issues for everything that needs to happen to do an initial release of Horvod support. All such issues should be priority/p1.

We'd like to include Horvod in our 0.2 release. We need to figure out all the work that needs to happen to support that. 

I created the label area/horvod

Anyone in the org should be able to label issues as follows

/area horvod
/priority p1

@jiezhang @everpeace Could you take a stab at coming up with a list of issues and labeling existing issues?

**Comment by jiezhang** [comment]
Thanks @jlewi. 

What's the timeline for 0.2 release? I think we should rename the area as openmpi. The package was written in a way that it's not coupled with horovod. For example, @everpeace is using the package to run distributed machine learning tasks which has nothing to do with horovod.

cc @alsrgv

**Comment by jiezhang** [comment]
@jlewi Looks like the area command is not working for me.

**Comment by jlewi** [comment]
The area/openmpi label doesn't exist. Can we use the area/horvod?

**Comment by everpeace** [comment]
@jlewi Yeah, naming is a bit complicated.  as jiezhang said, openmpi package is technically independent from Horovod.  And, actually, I'm using this package with [Chainer](https://chainer.org/)/[ChainerMN](https://github.com/chainer/chainermn).

> Could you take a stab at coming up with a list of issues and labeling existing issues?

Sure.  I'm happy to do it.  Here are several new issues which I would like to put in 0.2. 
What do you think @jiezhang ??

- support securityContext(especially `RunAs`)
  - In our cluster, we use NFS.  when mounting NFS, we prohibit users to run pods with root from security reason. 
- support volume and volume mounts (relates to #713 ?)
- pave e2e test (at least on basic sample??)
- (low priority) support `initContainer`
  - Imagine pulling user code via `git-sync` or so.

> labeling existing issues?

@jlewi I opened three PR yesterday,  How should I handle them?  I think I would create stab isseues for them and put the label.  Is that ok?? cc/ @jiezhang 

off topic here though, I'm now thinking  I would make a proposal of `chainer-operator` by the way.

**Comment by jlewi** [comment]
I created the label area/openmpi

**Comment by pineking** [comment]
>support securityContext(especially RunAs)
In our cluster, we use NFS. when mounting NFS, we prohibit users to run pods with root from security reason.

@everpeace securityContext(RunAs) does not support group id, how can you specify gid in container when your programs read/write data using NFS

**Comment by everpeace** [comment]
@pineking `RunAsGroup` is already [on feature-gate since 1.10](https://kubernetes.io/docs/reference/feature-gates/).

However, this `RunAsGroup` didn't work nicely with NFS VolumeSource.  So we patched by ourselves (it is a small patch though).  Of course, we plan to contribute it to the upstream.

**Comment by pineking** [comment]
@everpeace Great, Thanks for your information. I will try the `RunAsGroup` feature, and look forward to your PR of the patch.

**Comment by jiezhang** [comment]
Thanks @jlewi . We'll create/tag issues needed for initial release.

**Comment by pdmack** [comment]
`'s/horvod/horovod/g'`

**Comment by jlewi** [comment]
@jiezhang @everpeace I see two issues labeled area/openmpi ? Is the list complete? Does it include items related to Horovod and Open MPI support?

**Comment by everpeace** [comment]
@jlewi I would like to support one more feature of `volumes/volumeMounts` support (#838) if I could once kubeflow supports ks `0.10.2`(#727).   I set p2 to it because I'm not sure #727 was fixed before kubeflow 0.2 🙇   This would be the last issue from me for kubeflow 0.2.

**Comment by jlewi** [comment]
@everpeace What is the status openmpi support? Can we close this issue and open up appropriate issues tagged 0.4.0?

**Comment by everpeace** [comment]
yes, please 🙇

**Comment by everpeace** [comment]
@jlewi sorry for confusion.

> Are you saying that in 0.4 we should remove

Yes, I was.  But, in this several days, I understood that there are some active users using openmpi package.

So, I think we don't need to remove this package at least in 0.4.    However, I would like to inform users the fact that they have an option to use mpi crd instead of openmpi package.  Because, openmpi package is based on bare pods so no fault tolerance (it can NOT retry when failure), but mpi-operator expands mpi crd to `kind:Job` and `kind:StatefulSet` so it has fault-tolerance (it CAN retry when failure).

**Comment by jlewi** [comment]
SGTM.

Any suggestion about how we should start pushing users to use the CRD?

**Comment by everpeace** [comment]
I would suggest putting some note which recommends using `MPIJob` instead of openmpi package with an explicit description of `MPIJob` advantages (retry behavior etc.).

**Comment by chrisheecho** [comment]
Hello all, could someone give status update of this issue? would love to connect with the driver for this..is this you @everpeace and @jiezhang ?

**Comment by jlewi** [comment]
I filed #272 to update the docs.  

#1859 to remove the existing package.

**Comment by everpeace** [comment]
Thanks for creating issues 🙇
