### ISSUE TITLE
Trigger docker build images on post-submit

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#816]
We'd like to trigger building our docker images on every post-submit.

In #666 we created a cron job to regularly run Argo workflows to build our docker images.

This issue goes one step further and triggers these workflows on each postsubmit.

We can use Prow to trigger jobs on post submit. The problem is securing this so that we don't give unvetted code access to our release artifacts (including staging).

Prow supports running the test pods in a separate [cluster](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md#run-test-pods-in-a-different-namespace-or-a-different-cluster). 

This works as follows

- In the prow services cluster we have a secret with a map of cluster name to credentials to talk to that cluster (AKA kubeconfig)
-- one of these clusters is "default"
- In your job you can optionally list a non-default cluster by setting "cluster: foo", prow will then schedule that job there instead of the default cluster
- for a sensitive cluster like the "security" cluster for kubernetes-security org we can have a presubmit tests in test-infra that restricts which jobs set that cluster it, if need be, as well as only the test-infra maintainers having permission to approve configuration changes.

So I think we could do the following

- Setup a GCR repository for our postsubmit builds 
   - This should be separate from our public release repository for security reasons and also to avoid
      polluting that repository with lots of images

- Setup a separate cluster/GCP project from our release cluster that can push to staging but not public

- Configure Prow to trigger postsubmits jobs in this cluster
- Restrict prow jobs that can use this cluster to our post submit jobs.

**Comment by lluunn** [comment]
Shouldn't we only build when images are changed in the PR?
But not sure how easy is that.

**Comment by jlewi** [comment]
Our E2E test infrastructure is already capable of filtering a diff and triggering specified workflows when certain files are changed.

Another major pain point with our image auto release process right now is that we don't have dashboards or other monitoring for success. This would be another advantage of using prow to manage these builds.

**Comment by jlewi** [comment]
Due to #1574; I think as a short term fix we will want to allow our postsubmits to start publishing images to the gcr.io/kubeflow-images-public bucket.

This means we will need to update the IAM policy for project kubeflow-images-public to grant appropriate IAM permissions to the service account used in our kubeflow-testing cluster.

We'd like to start managing GCP more declaratively; so we should check in a YAML file containing the IAM permissions for project kubeflow-releasing. 

We can check it into kubeflow/testing somewhere.

We can then update our postsubmit build image release workflows to start pushing to gcr.io/kubeflow-images-public.
