### ISSUE TITLE
Add multiple cpu architectures to the ci / build process

### ISSUE THREAD

**Issue by carmine** [kubeflow/kubeflow#819]
This issue is a placeholder for a larger discussion around adding support for cpu architectures other than x86. The following things should be discussed

- [ ] How to incorporate this into the build process (ie the build design)
- [ ] What the immediate builds should be (ie ARM vX, ..)
- [ ] Additional GH issues, one per architecture, to do the implementation work
- [ ] Leverage Container Manifest 2.2 - https://docs.docker.com/registry/spec/manifest-v2-2/
- [ ] (stretch) Can the above design be leveraged to incorporate multiple operating systems as well, such that you'd possibly end up with X operating systems * Y cpu architectures

**Comment by pdmack** [comment]
IMHO, we should be generally guided by the CPU arch provided by the frameworks we are enabling in Kubeflow, starting with TensorFlow obviously. These are generally x86_64 for Linux, macOS, and Windows from pip and conda.

**Comment by carmine** [comment]
x86_64 will most likely be the dominant architecture. But there are others, and for KubeFlow to have the widest appeal possible, we should prioritize what those others are.

In the widest sense, we could have a 1:1 correspondence to all kubernetes architectures. That could lead to a matrix of which architectures are supported by the frameworks we are enabling.

The motivation for this is:
1) Whereas individuals can build the binaries for KubeFlow for something like ARM, and presumably most/all of the frameworks for ARM, it'd be great if we could provide the kubeflow binaries directly.
2) Handle the scenario where kubeflow is deployed to kubernetes where that k8s is based on some other cpu arch
3) Solving this multi cpu arch problem could also help solve multi operating system builds.

Some examples:
- NVidia pre-builds for 2 architectures (x86, powerpc) - https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/
- Kubernetes prebuilds for several (x86, powerpc, arm, arm64, s390x) - https://kubernetes.io/docs/imported/release/notes/#server-binaries

**Comment by carmine** [comment]
I've added a pointer to container manifest v2.2 to the issue description  - ie https://docs.docker.com/registry/spec/manifest-v2-2/.  

This could be leveraged if we go down this path and build out multiple container formats.

**Comment by carmine** [comment]
The OCI image spec ..

https://github.com/opencontainers/image-spec
