### ISSUE TITLE
Docs for how to make changes to Docker images

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#828]
#817 Is an example of a PR that requires changes to a Docker image.

Kubeflow developers need a way to make changes (e.g. to our ksonnet components) that depend on updated Docker images.

Giving direct access to our registries so people can manually push an image won't scale very well.

I suggest the following process

1. Developer submits a PR updating the Dockerfile
1. Developer waits for the image to be rebuilt by CI/CD after the PR is submitted (#666 #816)
1. Developer creates a new PR updating the image to the nightly build

Having to submit two PRs rather than have a single PR updating the Docker image and ksonnet component is unfortunate but I think tolerable.

/cc @kunmingg @kkasravi

**Comment by kunmingg** [comment]
Sounds good, we can adjust cron build frequency to shorten waiting time if image might need update quite often.

**Comment by jlewi** [comment]
Medium term we should fix #816 so we build on post-submit.
