### ISSUE TITLE
E2E test verifies Kubeflow installed via Deployment Manager

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#836]
Background:
    #823 Start Deploying bootstrapper via deployment manager
    #757 Install Kubeflow by the deployment manager

To verify this is working we need to update the E2E test to verify that Kubeflow is actually deployed correctly. I think this is currently blocked by #832 

/assign @kunmingg

**Comment by jlewi** [comment]
I think we should do the following

* Create a variant of [deploy_kubeflow.py](https://github.com/kubeflow/kubeflow/blob/master/testing/deploy_kubeflow.py) which uses deployment manager
   * A python script will be easier to add things like retries and error testing and also wrap it in a test case

* We should allow the YAML file provided to deployment manager( [cluster-kubeflow.yaml](https://github.com/kubeflow/kubeflow/blob/master/docs/gke/configs/cluster-kubeflow.yaml)) to be specified via ConfigMap. This will make it easy to override via the Argo spec so that we can test different packages.

**Comment by ankushagarwal** [comment]
@jlewi Can this be closed since #866 is merged?

**Comment by jlewi** [comment]
#866  doesn't actually verify that the resulting Kubeflow deployment is functional.

Fixed by #894
