### ISSUE TITLE
[openmpi] `volumes/volumeMounts` support

### ISSUE THREAD

**Issue by everpeace** [kubeflow/kubeflow#838]
Users sometimes wanted to add volumes to openmpi pods.  Particularly, when kubernetes cluster mounts NFS, users would want to mount `hostPath` volume to their containers.  Moreover, [kubernetes volumes](https://kubernetes.io/docs/concepts/storage/volumes/) supports various volume types.  So, this feature would also be useful for users who wanted to save their data to external volumes.

I experimented to implement this feature [on my branch](https://github.com/kubeflow/kubeflow/compare/master...everpeace:openmpi-volumes).  However,  this requires the latest ksonnet (0.10.2 or higher) to handle array of json parameter.  #727 blocks this issue.

/area openmpi
/priority p2

**Comment by karthikvadla** [comment]
Hi @everpeace , do you have any update on this feature. ?? Right now i would like to mount volumes to my container as i already have replicated data on my nodes at `/var/datasets.

**Comment by everpeace** [comment]
@karthikvadla Thank you for waiting.  But, kubeflow doesn't support ks 0.10 or 0.11 officially.  So, my branch can't be merged to kubeflow's master branch.

However, If you're familiar with jsonnet/ksonnet, you could apply to [the diff](https://github.com/kubeflow/kubeflow/compare/master...everpeace:openmpi-volumes) manually because the diff is small.

```shell
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow
ks pkg install kubeflow/openmpi@${VERSION}

# Then you can edit your files directly under 'vendor/kubeflow/openmpi' dir.
# you will need to edit two files below:
# - vendor/kubeflow/openmpi/prototypes/openmpi.jsonnet
# - vendor/kubeflow/openmpi/workloads.libsonnet

# and now you're ready to ks generate command.
ks generate openmpi ${COMPONENT} --image ${IMAGE} --secret ${SECRET} ...
```

**Comment by karthikvadla** [comment]
Thanks @everpeace , will look into it. :)

**Comment by karthikvadla** [comment]
@jlewi @everpeace I see you guys upgraded tests to `0.11.0` here https://github.com/kubeflow/kubeflow/issues/727. 
Is there any reason you guys holding back to upgrade the kubeflow to same version? Still we are on `0.9.2` as per requirements specification.

**Comment by karthikvadla** [comment]
@everpeace Quick question: I did apply changes manually after updating ksonnet to `0.11`. Right now i have data on my actual kubernetes nodes at `/var/datasets/unet`. 

Can you please let me know the correct usage.?

I did as below.
BASE_DIR='/var/datasets/unet'
```ks generate openmpi ${COMPONENT} --image ${IMAGE} --secret ${SECRET} --volumes ${BASE_DIR} --volumeMounts ${BASE_DIR}```

**Comment by karthikvadla** [comment]
oh do i need to create `volume` myself and use that above?

**Comment by everpeace** [comment]
@karthikvadla 

Types of `volumes` and `volumeMounts`is `array` (of `object`).   These parameter will be just injected to your maniefsts.  So you would specify these parameter like this:

```
ks param set ${COMPONENT} volumes '[{ "name": "vol", "hostPath": { "path": "/var/datasets/unet" }}]'
ks param set ${COMPONENT} volumeMounts '[{ "name": "vol", "mountPath": "/var/datasets/unet"}]'
```

**Comment by karthikvadla** [comment]
thank you @everpeace . That did help, able to mount volume now. :)

And now i'm trying to specify a ```  --nodeSelector=<nodeSelector>             Comma-delimited list of "key=value" pairs to select the worker nodes. e.g. "cloud.google.com/gke-accelerator=nvidia-tesla-k80" [default: null, type: string]
```
Above description is bit confusing, you say type as `string` but when explaining written as comma -delimited list. 

NODE_SELECTOR='["kubernetes.io/hostname=gke-x1", "kubernetes.io/hostname=gke-x2"]' - It didn't honor, randomly picked up some nodes.

or 
if it is string i tried as below
NODE_SELECTOR="kubernetes.io/hostname=gke-x1, gke-x2". It gave me below error
```level=error msg="find objects: RUNTIME ERROR: Index 1 out of bounds, not within [0, 1)\n\t/Users/kvadla/git-repo/mlt/examples/horovod_unet/mlt_app/unet-horovod-2e6fbba6-7e39-41f9-98b5-1f3241001e33/vendor/kubeflow/openmpi/util.libsonnet:14:46-81\tobject <anonymous>\n\t<std>:1222:30-34\tthunk from <thunk from <function <anonymous>>>\n\t<std>:1216:24-25\tthunk from <thunk <t> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1217:8-9\tfunction <anonymous>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t...\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:35-56\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<builtin>\tbuiltin function <$objectFlatMerge>\n\t<extvar:__ksonnet/components>:7:3-58\tobject <anonymous>\n\tDuring manifestation\t\n"
make: *** [deploy] Error 1
```

**Comment by karthikvadla** [comment]
@everpeace created above issue. 👆

**Comment by karthikvadla** [comment]
@everpeace I saw volume mount is not working when i upgrade to ksonnet `0.12.0`. I was fine with `0.11.0`. 
Is there any issue with latest release?

**Comment by karthikvadla** [comment]
And also do we support persistent volumes? Because i want to save the results after model training. I tried exporting `gcs` creds in containers..and trying writing to it, that didn't help. 
Is there anyway i can store results permanently to use later with tensorboard.?

**Comment by karthikvadla** [comment]
There were some docker network issues. Still not able to write to `GCS` but NFS did work :)

**Comment by gautamkmr** [comment]
https://github.com/kubeflow/kubeflow/issues/1748
