### ISSUE TITLE
Cleanup jsonnet style - camelCase variable

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#841]
We should use camel case variables, #403 , but there are many violations:

https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/releaser/components/workflows.libsonnet

https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/images/releaser/components/workflows.libsonnet

**Comment by pdmack** [comment]
I presume you mean the underscores:
deploy_tf_serving_command_base -> deployTfServingCommandBase

**Comment by jlewi** [comment]
Obsolete since ksonnet is deprecated.
