### ISSUE TITLE
Jupyter image for TensorFlow 1.8

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#846]
Can we build a jupyter notebook for TF 1.8

**Comment by ankushagarwal** [comment]
We already do https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/releaser/components/workflows.libsonnet#L304

Looks like we need to push run the argo workflow to release it to gcr.io

**Comment by ankushagarwal** [comment]
I'll push this once https://github.com/kubeflow/kubeflow/pull/843 is merged
