### ISSUE TITLE
How to support other persistent volumes except for "Host Path" and "Azure File" in TFJob UI?

### ISSUE THREAD

**Issue by Itfly** [kubeflow/kubeflow#847]
After installing the kubeflow, there's only two volumes type shown on the tfjobs/ui. Is it possible to support other volumes like nfs?
![image](https://user-images.githubusercontent.com/3993505/40356202-fb640680-5dea-11e8-9091-48efe7fdc5b3.png)

**Comment by wbuchwalter** [comment]
Yes, each volume type will likely require it's own react component since they have different field.
PR welcome.

**Comment by Itfly** [comment]
Thanks. But I can not find where's the front-end code

**Comment by wbuchwalter** [comment]
It is in the tf-operator repo: https://github.com/kubeflow/tf-operator/tree/master/dashboard
