### ISSUE TITLE
Tutorial(s) that correspond to CUJs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#85]
We need a tutorial that maps a user through one or more CUJs as way of illustrating the value of Kubeflow.

This might be something like
- Deploy Kubeflow
- Open up an existing TensorFlow notebook that provides a tutorial
- Train locally
- Train distributed (with GPUs) using TfJob
- Deploy the trained model
- Send some predictions

tensorflow/k8s#195 has some links to existing tutorials about TensorFlow and K8s.

**Comment by fxue** [comment]
some ideas on tutorials:
1. tensorflow for poets 1 and 2 to provide a smooth transition for people with TF experience
2. if tf-keras will be supported, a tf-keras tutorial, something like [this one](https://www.youtube.com/watch?v=UeheTiBJ0Io) with some additional follow ups

**Comment by jlewi** [comment]
Intel just published one.
https://ai.intel.com/lets-flow-within-kubeflow/

**Comment by sarahmaddox** [comment]
@abhi-g Do you think we can close this issue now, as it's too wide in scope for people to be able to tackle? Instead, we should raise an issue per desired CUJ, preferably in the kubeflow/website repo. As an example, we have this one:

* Add an end-to-end guide for Kubeflow on Kubernetes Engine (https://github.com/kubeflow/website/issues/109)

**Comment by abhi-g** [comment]
Thanks. That makes sense.

Abhishek
