### ISSUE TITLE
Include ssh in notebook image to support authenticated git push

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#850]
Proposing to re-include ssh in tf-hub notebook images to allow code developed there within to be pushed to external git repositories that use ssh to handle authentication.

/cc @pdmack

**Comment by pdmack** [comment]
/assign @pdmack

@cwbeitel Are you currently using PV? In the interim, are you able to push/pull on the PV?

**Comment by cwbeitel** [comment]
Can you clarify? I'm using a PV attached as NFS but the same issue with git pushing occurs when running the docker image without any mounted volumes or kubeflow infra then is corrected by apt-get installing ssh.

**Comment by pdmack** [comment]
Sure, I was thinking maybe if you had access to that same volume from a host _with_ ssh (i.e., outside the pod container). No matter, i'm on it.

**Comment by cwbeitel** [comment]
Yeah that's a good fix. Thanks for the help!
