### ISSUE TITLE
E2E test for TFJob v1alpha2 ksonnet package

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#852]
Context: 
   * kubeflow/tf-operator#599 add ksonnet package for v1alpha2 of TFJob operator
   * #836 - Verify Kubeflow deployed correctly with deployment manager
   * #829 - Use a config map with bootstrapper to override packages installed

We need to update our E2E tests to test the TFJob operator v1alpha2 package.

The difficulty here is that we can't deploy two versions of a CRD in the same cluster. So we will need to modify our tests to spin up a new GKE cluster for each version of the operator.

My suggestion would be to switch to using deployment manager + bootstrapper. 

We have this [workflow](https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/gke_deploy.libsonnet) which uses deployment manager to create a GKE cluster.

When #829 is fixed and the tests are updated to support this I think we can easily run the test for multiple versions of TFJob operator.

/priority p1

**Comment by ankushagarwal** [comment]
Python script from #866 to deploy kubeflow clusters

**Comment by ankushagarwal** [comment]
Looks like bootstrapper has a couple of bugs. Once https://github.com/kubeflow/kubeflow/pull/872/files gets merged I'll start work on this
