### ISSUE TITLE
Verify PVC for /home/jovyan works

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#854]
In #561 we made the changes to support mounting all of /home/jovyan on PVC.

We should verify that is working in dev.kubeflow.org.

To do that we will need newly built Jupyter notebook images.

The cron job to rebuild notebook images (#666) should be enabled soon.

**Comment by pdmack** [comment]
I would work on this if someone could guide me through the test infra. Like, from local to e2e.

**Comment by jlewi** [comment]
We're using **dev.kubeflow.org** as a way of seeing Kubeflow @ HEAD to test things like UI changes that we don't have E2E tests for.

It looks like the cron job was enabled and images were newly built
https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/tensorflow-1.8.0-notebook-cpu?gcrImageListsize=50

You should have access to via your @redhat account to dev.kubeflow.org so you should be able to launch a notebook using the new image and just confirm its working.

**Comment by pdmack** [comment]
The non-PVC default...
<img width="344" alt="screen shot 2018-05-23 at 10 58 56 am" src="https://user-images.githubusercontent.com/2380545/40432765-7111625a-5e78-11e8-980e-9ea0afd15aaf.png">

**Comment by jlewi** [comment]
@pdmack Can you explain the last comment? Is PVC working as expected? I think I made a mistake we probably need to update dev.kubeflow.org to pick up the ksonnet changes that set the mount point.

There are instructions [here](https://github.com/kubeflow/testing/tree/master/dev-kubeflow-org) for how to update dev.kubeflow.org.

I think we will need to modify recreate_app.sh to set the location to mount the PVC
https://github.com/kubeflow/testing/blob/master/dev-kubeflow-org/recreate_app.sh#L82

**Comment by pdmack** [comment]
The screen caps are from the NB launch in d.k.o without a PVC. @jlewi are you saying we want to now have all d.k.o launches use a PVC? If so, I'll have a look at those updates.
