### ISSUE TITLE
Suggest using simple port forwarding instead of LoadBalancer for cloud deploy in User Guide

### ISSUE THREAD

**Issue by dakoner** [kubeflow/kubeflow#860]
The User Guide documents adding a LoadBalancer to expose the tf-hub in a cloud deployment with the stated caveat it opens the port to the internet.  There is an additional document for using IAP, which is more secure but also more complex.

I suggest documenting a simpler port forward, which just makes the tf-hub available to the local machine:

kubectl port-forward --namespace kubeflow $(kubectl get pod --namespace kubeflow --selector="app=tf-hub" -o jsonpath='{.items[0].metadata.name}') 8080:8000

After running this command, I was able to connect to the tf-hub, start a new jupyter instance, create a new notebook, and evaluate a simple python statement.  The resulting hub port forward is available on localhost of the forwarding machine, so any user on the machine has access.  That's not perfect but it's better than opening the hub to the internet.

**Comment by jlewi** [comment]
This makes sense. 

I think the general approach we want to recommend is that users connect to the ambassador reverse proxy so they get access to all the services.

This is blocked though on #817 which will put JupyterHub behind the ambassador.

Once everything is available through ambassador we can provide suitable recipes for connecting to ambassador e.g.

- Port forward
- Expose ambassador on loadbalancer or node port ( this is safe for on prem/minikube if you are on a protected network accessible from corp vc but not externally)

**Comment by sarahmaddox** [comment]
This issue was moved to kubeflow/website#212
