### ISSUE TITLE
error: Operation cannot be fulfilled on tfjobs.kubeflow.org ... the object has been modified

### ISSUE THREAD

**Issue by omartin2010** [kubeflow/kubeflow#861]
hi, while trying to create a tfjob object on my cluster, I'm unable to get tf operator to create a job, nor a pod.

Here's an error I'm getting in while running : 
kubectl logs tf-job-operator-75897f474d-c942g --namespace kubeflow | grep error
error: Operation cannot be fulfilled on tfjobs.kubeflow.org \"_object_name_\": the object has been modified

Any idea what I should be looking at?

**Comment by ankushagarwal** [comment]
* Is it possible that you have two tfjob controllers running in your kubeflow cluster? `kubectl get deployments --all-namespaces | grep tf-job-operator`

* If not, can you share the TFJob spec?
