### ISSUE TITLE
Failed to run TfCnn example from User Guide: ERROR find objects: parse jsonnet snippet: params.libsonnet:22:5-13 Expected a comma before next field.

### ISSUE THREAD

**Issue by dakoner** [kubeflow/kubeflow#863]
I am getting an error when I try to run the TfCnn example from the User Guide:
The docs say to run:

CNN_JOB_NAME=mycnnjob
ks generate tf-cnn ${CNN_JOB_NAME} --name=${CNN_JOB_NAME}
ks apply ${KF_ENV} -c ${CNN_JOB_NAME}

I get the error:
ERROR find objects: parse jsonnet snippet: params.libsonnet:22:5-13 Expected a comma before next field.

When I looked at components/params.libsonnet, I see it has added a 'mycynnjob' stanza after the components stanza, but it omits the comma between the two components:

  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory
   ....
    }   /// THERE NEEDS TO BE A TRAILING COMMA HERE
    mycnnjob: {
      batch_size: 32,
 ....
   }

I'm not sure why this is happening, I guess it is some sort of issue with 'ks generate'?

**Comment by ankushagarwal** [comment]
* What version of ksonnet are you using?
* What version of kubeflow are you using?

ks version 0.10.2 and kubeflow version v0.1.2 seems to work for me

**Comment by jlewi** [comment]
Per @ankushagarwal 's comment `components/params.libsonnet` is generated by `ks` not us so its most likely something with ks.

**Comment by dakoner** [comment]
Yep, I think what's happened is that I downloaded the 'ks' binary from the ksonnet site, and it embeds versions of those files, then blindly updates them without respecting syntax.

**Comment by dakoner** [comment]
Closing because it's not kubeflow-specific.
