### ISSUE TITLE
Better bash PS1 for notebooks

### ISSUE THREAD

**Issue by pdmack** [kubeflow/kubeflow#865]
If anyone ventures to a notebook terminal in dev.kubeflow.org,  it looks a little ugly. e.g.,

`jovyan@jupyter-accounts-2egoogle-2ecom-3apmackinn-40redhat-2ecom:~$`

**Comment by jlewi** [comment]
With 0.5. It looks a little better if we use bash. But it looks like the default shell is still `sh` which causes problems with things like code completion.
