### ISSUE TITLE
CUJ: Make Kubeflow flow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#87]
Opening this bug to track work related to following CUJ.

* Sam develops a ML model on jupyter with some small sample data. 
   After having tweaked the model, Sam now wants to train with a slightly larger dataset.
* Sam is familiar with Python, but does not understand Kubernetes.
* Sam is provided with a python library that will package his model and run it using TF Job using the data 
  Sam provides
* Sam can then interpret the output of the experiment from Jupyter.
* Sam can trigger more jobs or experiments in the future and possibly extend the client library to perform more complex tasks.
* When Sam is finished with training, Sam can invoke the same library to serve the trained model either via a new deployment or update an existing deployment.
* Throughout this process, Sam did not have to exit his notebook interface.
* Tensorboard plugin in Jupyter is able to introspect model generated via Jupyter and TF Job

**Comment by nkashy1** [comment]
Could this be implemented with a separate Jupyter backend?

To begin with, Sam could experiment in a standard Python2/3 backend with TensorFlow installed, etc. When ready, Sam could switch to a specialized backend in which the code would instead be packaged and deployed using TFJob.
