### ISSUE TITLE
Make image release Dockerfile point to resources within GCP.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#877]
Background:
With https://github.com/kubeflow/kubeflow/issues/666, we have cron job release images in kubeflow org. 
Currently (05/25) we have ~20 image released concurrently. One observation is we might have network bandwidth limit since some request to external resources timeout and cause failure.

First step could be making Dockerfile's dependencies like base images hosted within GCP.

**Comment by jlewi** [comment]
GCR provides a mirror of popular images in DockerHub.
https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring

We probably just need to configure our docker daemon to use it.
