### ISSUE TITLE
Bootstrapper should support packages from other registries

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#880]
Bootstrapper should support other registries.

I think what we'd like to do is

1. Make it easy to bake multiple registries into the bootstrapper image
 
   * Then people can create private bootstrapper images containing private packages

1. Ensure bootstrapper can install packages from other registries

/assign @kunmingg

**Comment by kunmingg** [comment]
Will update doc in bootstrap about how to use.
