### ISSUE TITLE
Web app deploying kubeflow through deployment manager

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#884]
Before integrating with Cloud Launcher for deploying Kubeflow, consider creating a web app that accepts 
- project
- deployment name
- hostname

and produce a GCP deployment manager YAML config which then calls deployment manager to deploy kubeflow.

**Comment by jlewi** [comment]
There's a bunch of next steps.

1. We should deploy the current web app (e.g. on dev-gcp.kubeflow.org)
1. We should modify the bootstrapper to perform the manual gcloud steps in the [instructions](https://github.com/kubeflow/kubeflow/blob/master/docs/gke/gke_setup.md) e.g.

   * Granting DM service account necessary permissions
   * Downloading GCP secrets for service accounts and creating K8s secrets

3. Reporting status of the deployment operation and printing link for central UI once its deployed.

**Comment by jlewi** [comment]
Removing from 0.3.0 since this isn't directly related 0.3.0 and we are trying to aggressively prune remaining issues.

**Comment by jlewi** [comment]
This is obsolete.
