### ISSUE TITLE
Investigate using tensorflow serving's built-in http server

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#896]
https://github.com/tensorflow/serving/pull/902

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/http_server.h

**Comment by yupbank** [comment]
i did tried a bit... i think most of the stuff we provide, c++ version already have, except for they are most strict on the data type and less friendly on the error message. i did even did some bench mark with the same model, the python version would add ~ 10ms overhead .
