### ISSUE TITLE
Regression Jupyter notebooks no longer include python2 runtime

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#906]
I just tried gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu:v20180601-2464851a

And I didn't see an option for a python2 runtime which is needed for TFX/Beam support.

My guess is this was a regression introduced when refactored the notebook image to support mounting all of /home/jovyan on a PVC.

/cc @pdmack

**Comment by pdmack** [comment]
@jlewi sort of. Looks like we were dually supporting py3 and py2 by installing and [activating](https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile#L108) py2 in the jovyan homedir, which of course gets wiped in prep for the PVC check. Does that track?
Which means I need to preserve that as well. 😁 
/assign @pdmack

**Comment by jlewi** [comment]
conda environments are kind of a mystery to me.

@ojarjur Might have more insight.

**Comment by ojarjur** [comment]
@jlewi The theory presented by @pdmack sounds right. If the user directory is being wiped out after installing the ipykernel, then it will not be available.

**Comment by pdmack** [comment]
It appears we don't need to install to jovyan at all, but instead the new global env location `/opt/conda`. But I'm going to review the older images and see what (if any) differences there may be.
