### ISSUE TITLE
bootstrapper should support push the ksonnet app to a source repo

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#912]
The bootstrapper should add options that allow users to specify a git repository and location within that repository that they will be push the generated app to.

This is a first step to enabling GitOps. It will also make it easier for users to customize their deployment beyond what they get with bootstrapper

**Comment by kunmingg** [comment]
How about using a new branch for each run?
To avoid potential conflict.

**Comment by jlewi** [comment]
Do we need a new branch? Since source control preserves history we don't need to be two worried about overwriting earlier versions; user could always rollback.

I'm thinking we should do something like the following

User specifies
  * Repository
  * branch
  * Directory

The bootstrapper behaves as follows

* If an app already exists at the specified directory the bootstrapper applies it but doesn't make
  any changes

* If no app exists the bootstrapper creates it and pushes a commit with the updated config.

Side note:

This is moving us in the direction of GitOps. We might want to take a look at using [WeaveFlux](https://github.com/weaveworks/flux/blob/master/site/standalone/installing.md) or possible [Argo-Cd](https://github.com/argoproj/argo-cd)

.We would still use the bootstrapper to create the ksonnet app but we would rely on WeaveFlux or Argo-Cd to actually sync it to the cluster.

WeaveFlux doesn't support ksonnet but we could work around that by using `ks show` and checking in the actual YAML specs.

**Comment by jlewi** [comment]
I'm having second thoughts.

Users can easily copy the ks app to their local machine as follows

```
kubectl cp kubeflow-admin/kubeflow-bootstrapper-0:/opt/bootstrap/default ~/my-kubeflow
```
So maybe that's sufficient and users can just check it in manually however they like via their local machine. This avoids us dealing with all kinds of issues e.g.

- git credentials
- how to deal with branches
- repo creation

**Comment by kunmingg** [comment]
https://github.com/kubeflow/kubeflow/pull/1515
