### ISSUE TITLE
Avoid user notebook pods from crashing system components

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#920]
Currently if a user notebook pod is allocated onto the same node as system components an OOM from the notebook container can crash these other components. Relatedly training jobs can be interfered with if they depend on system components that are being taxed by this phenomenon.

Unlike kf system components, memory and CPU usage of user notebook containers is not easily predictable and until user's workspace is saved and restored from a PV these are not tolerant to re-starting (contents of user workspace is lost when the pod is terminated).

It seems at least we would want notebook pods to be scheduled onto nodes that don't overlap with system or training jobs but probably even more to be isolated onto their own node (perhaps within a dedicated node pool).

Perhaps some minimal initial discussion here in regards to kubeflow needs can inform what should be proposed to jupyterhub/kubespawner, if anything.

/cc @pdmack

**Comment by kunmingg** [comment]
Can use isolated namespace and set resource limit namespace-wise?
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/ 
Would be great to have isolated hardware resource pool for pods in each category.

**Comment by pdmack** [comment]
Hopefully the latest NB PVC updates cover your use case for NB checkpoints, etc. upon pod resumption.

Kubespawner supports pod labeling via config before pod creation, so maybe could try isolation via node assignment. Also the new affinity/anti-affinity stuff is beta but not supported in Kubespawner.
