### ISSUE TITLE
Kubeflow on IBM Power 8 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#925]
We are interested in running this on Power 8 (ppc64le architecture) 

Is there support for selecting architecture in the current release?

If so how, we are testing but all of the images appear to be amd64?

Thanks,

Jeff

**Comment by pdmack** [comment]
#819

**Comment by jlewi** [comment]
I don't think anyone has tried to run this on Power 8. Is this something you are interested in testing out and seeing where the problems are?

Do you already have K8s running?

**Comment by jtfogarty** [comment]
@jlewi Hi, Yes we have k8s running on Power 8.  We are very interested in testing Kubeflow on Power 8.    

As @pdmack  commented, Architectural support is still an open issue.   We also want to use NVIDIA's GPU aware images.    

Here are some details of our environment; 

## Kernel version
Linux m97 4.4.0-70-generic 91-Ubuntu SMP Wed Mar 22 12:46:23 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux

## Docker version
Client:
Version: 18.03.1-ce
API version: 1.37
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:18:47 2018
OS/Arch: linux/ppc64le
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: 18.03.1-ce
API version: 1.37 (minimum version 1.12)
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:17:05 2018
OS/Arch: linux/ppc64le
Experimental: false

## kubectl version                                                                                                        
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/ppc64le"}                                         
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/ppc64le"}

**Comment by gyliu513** [comment]
@chenzhiwei
