### ISSUE TITLE
Create ksonnet prototype for auto image release

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#941]
As we have more and more images need to be covered by automating image release (https://github.com/kubeflow/kubeflow/issues/527, https://github.com/kubeflow/kubeflow/issues/781).
It's time to create a ks prototype for new image release.
In future adding new image release would be:
1. ks generate <release-prototype> new-release-name.
2. edit parameter.
3. add new-release-name to release [config](https://github.com/kubeflow/kubeflow/blob/master/releasing/prow_config_release.yaml).

**Comment by kunmingg** [comment]
Need to fix bug:
https://github.com/kubeflow/kubeflow/pull/960#issuecomment-395994079

**Comment by johnugeorge** [comment]
Added a separate issue #970

**Comment by kunmingg** [comment]
/close
We had new issue for it:
https://github.com/kubeflow/kubeflow/issues/970
