### ISSUE TITLE
Nightly builds of TensorFlow notebook images do not have have the same commit hash in the tag

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#943]
The docker images for the notebooks are being built at different commits

kubeflow-images-public:tensorflow-1.4.1-notebook-gpu
v20180607-0d9be5e4 

gcr.io/kubeflow-images-public/tensorflow-1.7.0-notebook-cpu
v20180607-476e150e

Why is this happening? Why aren't they all built at a consistent commit?

If nothing else this makes updating the images in kubeform_spawner.py unwieldy.

/priority p1 because I'd like to get this fixed soon to make updating the images for the 0.2 release much more tractable.

/assign @kunmingg

**Comment by kunmingg** [comment]
I guess we had timeout from gcs, so the workflow failed and retry, now they seem to be on same commit.

**Comment by kunmingg** [comment]
Close it for now till we saw it might affect user experience in future.
