### ISSUE TITLE
Ambassador Version 0.34.0 causing DNS Issues on Worker Node

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#945]
We recently updated to ambassador 0.34. When I deployed kubeflow on a single node cluster (n1-standard-8) kube-dns seems to be running at 100% CPU. Other processes are not able to resolve DNS on the host. Deleting the ambassador deployment fixes the DNS issue.

**Comment by ankushagarwal** [comment]
To reproduce, create a single node gke cluster with n1-standard-8 worker node and 1.9.6-gke.1 k8s version and deploy kubeflow-core (with ambassador 0.34.0)

**Comment by kflynn** [comment]
Can you see what exactly kube-dns is being asked to do? (I have a suspicion that I’d like to confirm.)

**Comment by ankushagarwal** [comment]
@kflynn How do I do that?

**Comment by ankushagarwal** [comment]
I can give you access to a cluster where I see this issue
