### ISSUE TITLE
[gcp] cluster-kubeflow.yaml isn't tested

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#950]
This is the recommended DM and bootstrapper config for GKE deployments.
https://github.com/kubeflow/kubeflow/blob/master/docs/gke/configs/cluster-kubeflow.yaml

It doesn't like that YAMl file is used by our E2E tests because it wasn't updated to specify the registry when that change was made to 
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config

There is also another GCP bootstrapper config in that directory

Our E2E tests are using this DM config
https://github.com/kubeflow/kubeflow/blob/master/testing/dm_configs/cluster-kubeflow.yaml

We do need to make changes to the DM config in order to pull the registry at head.

We have two options

1. We could create a separate test for https://github.com/kubeflow/kubeflow/blob/master/docs/gke/configs/cluster-kubeflow.yaml
1. We could make the necessary modifications to https://github.com/kubeflow/kubeflow/blob/master/docs/gke/configs/cluster-kubeflow.yaml

    * We could use a simple shell script that runs jq to make the necessary field changes

I prefer #2. if we use jq then we could update the [instructions](https://github.com/kubeflow/kubeflow/blob/master/docs/gke/gke_setup.md) to use the same jq commands.

@ankushagarwal thoughts?

**Comment by ankushagarwal** [comment]
One of the reasons that I did not use `gke/configs/cluster-kubeflow.yaml` for e2e test is because it adds a role binding to iam policy when we deploy it, but doesn't remove the role binding when we delete the deployment. 

Also when tests run in parallel, setIamPolicy action fails when two deployments try to invoke it at the same time. 

I removed a lot of stuff from `gke/configs/cluster-kubeflow.yaml` like iam policy and service accounts when I created `testing/dm_configs/cluster-kubeflow.yaml`

**Comment by ankushagarwal** [comment]
We could kick things up a notch if we tested at the project level - Create a project for every e2e test, use `gke/configs/cluster-kubeflow.yaml` to deploy kubeflow, run tests, delete project.

**Comment by jlewi** [comment]
Cleaning up the role bindings should be doable by adding actions to remove the roles and setting the runtimePolicy to delete
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/cloudbuild

Note sure what to do about the failures due to two deployments trying to modify it simultaneously.

**Comment by jlewi** [comment]
#910 is tracking cleaning up the roles.

**Comment by jlewi** [comment]
For setIamPolicy failures. Could we just add retries? On retry we can just call update rather than recreating the deployment.
