### ISSUE TITLE
[gcp] backend services can't be listed insufficient IAM permissions

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#953]
In the scripts for setting IAM, I'm noticing that after creating a new deployment I'm getting the error

```
Waiting for backend id PROJECT=cloud-ml-dev NAMESPACE=kubeflow SERVICE=envoy...
ERROR: (gcloud.compute.backend-services.list) Some requests did not succeed:
 - Required 'compute.backendServices.list' permission for 'projects/cloud-ml-dev'
```
I believe in my case the service account already existed prior to the deployment being created because when I deleted the previous instance of the deployment the service accounts weren't deleted. The IAM permissions look correct.

I find that if I delete the service account and then update the deployment so its recreated it works.

My suspicion is that the problem is the service accounts aren't deleted when the previous deployment was deleted. 

I suspect the service accounts might not get deleted because the roles aren't deleted #910 and I suspect that might block service account creation. 

Although I believe @ankushagarwal mentioned that he observed the service account but not role bindings being deleted.

**Comment by jlewi** [comment]
I'm hitting this again.

I created a delete script to try to prevent this by cleaning up service accounts and roles when deleting the deployment
https://github.com/jlewi/kubeflow-dev/blob/master/kubeflow-deployments/delete_deployment.sh

I also tried fixing it by doing this after the cluster had been created but just recreating the service account and roles 
https://github.com/jlewi/kubeflow-dev/blob/master/kubeflow-deployments/fix_admin_sa.sh

But when I tried it didn't fix the error.

**Comment by lluunn** [comment]
@abhi-g hit this issue again with deploy app
In the iap container:
```
Waiting for backend id PROJECT=abhishek-codelab NAMESPACE=kubeflow SERVICE=envoy filter=name~k8s-be-30019-...
ERROR: (gcloud.compute.backend-services.list) Some requests did not succeed:
 - Required 'compute.backendServices.list' permission for 'projects/abhishek-codelab'
```

**Comment by lluunn** [comment]
cc @kunmingg

**Comment by kunmingg** [comment]
Seems caused by IAM binding leftover bug.
Web app fixed the problem before: https://github.com/kubeflow/kubeflow/pull/1595
We can implement same logic in script or wait till it switch to go binary cli.

**Comment by jlewi** [comment]
How did the webapp fix this?

**Comment by jlewi** [comment]
If we delete the policy bindings for the service account and then add them back doesn't that fix things?

**Comment by kunmingg** [comment]
@jlewi 
Clear policy binding for that sa account and add them back should fix IAM bug.

However, another issue that could cause it: https://github.com/kubeflow/kubeflow/issues/1807

**Comment by jlewi** [comment]
So the AI's here are

Short term:

1. Document this error in the troubleshooting guide
    https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/
1. Provide instructions for clearing the policy bindings; and then adding them back.

Longer term we could try to ensure that kfctl and web app check for policy bindings and clear them before deploying Kubeflow.

**Comment by kunmingg** [comment]
@jlewi Deploy with webapp on v0.3.2 should fix it.

**Comment by jlewi** [comment]
Users should be able to manually delete the role bindings by running the same command kfctl.sh delete does

```
# Delete IAM bindings
python "${DIR}/iam_patch.py" --action=remove \
  --project=${PROJECT} \
  --iam_bindings_file="iam_bindings.yaml"
```

**Comment by jlewi** [comment]
Should we run that command always on kfctl.sh init to purge any existing bindings?

**Comment by jlewi** [comment]
I updated the script:
