### ISSUE TITLE
Central UI sometimes doesn't render if screen too small

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#957]
I just tried deploying the latest version of the central dashboard and I'm just getting a blank screen.

It looks like its using image:
gcr.io/kubeflow-images-public/centraldashboard:latest

Side note we should change the image to point to a specific image and not use the latest tag.

I can tell from the page source that it is loading the HTML corresponding to the central dashboard.

/assign @swiftdiaries

**Comment by jlewi** [comment]
I get a blank page behind IAP but not when I directly port-forward to the centraldashboard pod.

It also works behind ambassador.

So looks like an issue with IAP.

The older version in dev.kubeflow.org is working just fine with IAP.

So it looks like its probably related to the recent changes #798 
;  

I don't see any errors though in the chrom developer console

**Comment by jlewi** [comment]
Something really weird is happening.

It doesn't look like IAP is the issue.

Instead it looks like the header with the links sometimes renders and sometimes doesn't depending on the width of the div.

Specifically if I shrink the window horizontally it looks like it will stop displaying anything when it becomes too small. It looks like the cutoff is ~1025 pixels; shorter than that and it doesn't render

**Comment by swiftdiaries** [comment]
This is very weird. Let me see if I can reproduce this. And I'll look up
some possible causes as well.

Thank you for the detailed description.

**Comment by jlewi** [comment]
I just tried building a new image from #1016 which adds a link to JupyterHub. 
It renders using port-forward but not behind IAP; I just get a white page. The page is loaded though because I can see the source.

**Comment by jlewi** [comment]
It renders fine behind IAP when I'm incognito. Looks like a potential issue with one of my extensions.

**Comment by jlewi** [comment]
I logged out and cleared browsing data and this appears to be working fine now.
