### ISSUE TITLE
make deploy web app cover the manual gcloud steps

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#958]
See manual steps in [instructions](https://github.com/kubeflow/kubeflow/blob/master/docs/gke/gke_setup.md)
Like:
   Granting DM service account necessary permissions
   Downloading GCP secrets for service accounts and creating K8s secrets
Follow up of https://github.com/kubeflow/kubeflow/issues/884

**Comment by jlewi** [comment]
I don't think this can be handled by the bootstrapper because it won't have necessary credentials.

We want to do it in the click to deploy web app and use the user credentials.

**Comment by kunmingg** [comment]
Thanks, title updated.
