### ISSUE TITLE
Enable GitOps: Use (Weave Flux or Argo CD) to manage Kubeflow deployments

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#971]
We'd like to enable GitOps for Kubeflow using weave flux.

At a high level here's what we'd like to do

1. Bootstrapper pushes ksonnet app to a repo
1. Deploy Weave flux pointing at the repo
1. Weave flux synchronizes the K8s resources with the repo

On GCP this would look something like the following

1. Deployment manager [configs](https://github.com/kubeflow/kubeflow/tree/master/docs/gke/configs) deploy weave flux
1. Bootstrapper pushes the configs to a registry #912 

   * Since Weave Flux doesn't support ksonnet yet; the bootstrapper should run `ks show` and check in the actual YAMl files

kubeflow/website#34 provides some instructions for pushing the ksonnet app created by the boot strapper to a GCP Cloud Repository.

It should be pretty straightforward to create a custom script that could run in the bootstrapper to create the app and then push it to a source repository.

**Comment by TheJaySmith** [comment]
This sounds like a good start. We may want to throw the usage of Helm Charts in there. I find it easier to manage Flux with Helm than using just the standalone Yaml files. My concerns are the Helm interoperability with ks app. I personally haven't experimented with that yet. Has anyone tried helm with Kubeflow to see how it handles the ks apps?

**Comment by jlewi** [comment]
Lets try to avoid introducing helm just for this.

**Comment by bhack** [comment]
@jlewi It is alternative to https://github.com/argoproj/argo-cd/issues/92?

**Comment by jlewi** [comment]
@bhack yes I think there's some overlap between Argo-cd and Weave Flux. Both of them provide the functionality to keep K8s resources in sync with manifests in a repo.

My understanding is Weave Flux is pretty feature complete whereas argo-cd is still in the very early stages of development.

**Comment by bhack** [comment]
@jlewi Ok but it is less clear to me how gitops could integrate with dev tools on the thread at https://github.com/kubeflow/kubeflow/issues/465

**Comment by bhack** [comment]
@jlewi I found some contact point as i.e. Skaffold support kustomize deploy and this is its vision of gitops workflow: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/workflows.md

**Comment by TheJaySmith** [comment]
Skaffold could be something we can talk about in the future maybe but as for now, Weave Flux seems to integrate pretty decently

**Comment by cliveseldon** [comment]
There is a blocker for seldon integrating with Weave Flux in that Weave Flux doesn't play well with CRDs as it needs to understand where the image properties are. Added issue https://github.com/weaveworks/flux/issues/1194

**Comment by jlewi** [comment]
Repasting my comment from weaveworks/flux#1194

The trend (e.g. helm v3 discussions) seems to be that the tool chain should be composable. So my expectation is that people templatize their app using whatever tool they like (ksonnet, kustomize, helm, etc...) and then down stream tools in the app mangement tool chain (e.g. Weave) just consume the fully realized YAML manifests.

Within Kubeflow we have a number of places (e.g. hyperparameter tuning) where we need to substitute parameters into some user defined manifest.

So I think the direction we are headed is creating an API like

getManifests(Git URI)

that could return the manifests based on a URI that could be pointing at an app written in any number of templating solutions (e.g. helm or ksonnet). So a tool like WeaveFlux wouldn't necessarily need to know about either 1. The particular structure of the resources or 2. the particular implementation of the templating solution. It would just need an endpoint that knew how to evaluate one or more templating solutions

**Comment by TheJaySmith** [comment]
Created a PR to add the first iteration of "kubeflux" package #1203

**Comment by jlewi** [comment]
@TheJaySmith looks like you closed that PR.

**Comment by TheJaySmith** [comment]
Hello, 

It is now #1225 Had issues with that other PR

**Comment by jlewi** [comment]
@TheJaySmith what are the next steps?

**Comment by TheJaySmith** [comment]
@jlewi think we are good to go. Just trying to get it past tests in the PR (v0.1.1)

**Comment by jlewi** [comment]
@TheJaySmith What are the next steps?

I'm removing this from 0.3.0 because I don't see this happening in that time frame since we want to be code complete in the next two weeks.

**Comment by TheJaySmith** [comment]
The code is ready and merged for anyone to try. Or at least, the package is ready to be deployed. What I am working on is creating some documentation that is relevant for KubeFlow users.

**Comment by kunmingg** [comment]
@jlewi 
How about writing our own gitops service that understand ksonnet?
Feels like WeaveFlux's restriction on only managing raw k8s manifest is painful to have:
We cannot control if user update git repo through a service or manually git push (in this case we cannot force user to update output of ```ks show ...```)

**Comment by bhack** [comment]
@kunmingg https://github.com/ksonnet/ksonnet/issues/553

**Comment by jessesuen** [comment]
> Feels like WeaveFlux's restriction on only managing raw k8s manifest is painful to have: 

If flexibility in the way you define your manifests is a sticking point, I really encourage you to give ArgoCD a try. We now support ksonnet, kustomize, helm, or plain directories of yaml, json, jsonnet. In our latest release (v0.9) we now have automated synchronization, if you like Flux' pull based approach to synchronization.

Here's the (now a  bit dated) 10 minute demo I did for SigApps a few months back:
https://www.youtube.com/watch?v=aWDIQMbp1cc&feature=youtu.be&t=1m4s

**Comment by TheJaySmith** [comment]
It is proving to be a little more difficult than I had hoped. The ksonnet is a bit tricky. Right now, weaveflux is bundled into Kubeflow so it can be used today, except for the ksonnet. Basically, I need to convert the ksonnet into YAML to update. 

My goal is to show this all off by Kubecon Seattle (definitely need it done before then) so I am open to whatever we think is best. Making our own tool is great but it would be time intensive. ArgoCD might be a good option worth playing with and we already use Argo. 

Alternatively, we can continue to find workarounds with Flux. Thoughts?

**Comment by chrisheecho** [comment]
should we just assign this to Danny Thompson? who is the action on?

**Comment by carmine** [comment]
Feels like this should be a pattern .. starting with weave flux and/or argo .. and extending out to other options. One example is jenkins-x.

**Comment by jlewi** [comment]
Instructions for GitOps have been posted here:
https://www.kubeflow.org/docs/guides/gitops-for-kubeflow/

So I'm closing this issue.

**Comment by nick4fake** [comment]
@jlewi looks like link doesn't work anymore

**Comment by jlewi** [comment]
@nick4fake I'd suggest opening a new issue; I'm not sure what's transpired in the last 5 years and whether that's still support or not

**Comment by thesuperzapper** [comment]
@nick4fake I am not sure if you have heard of __deployKF__, it's a new distribution that natively integrates ArgoCD and GitOps to deploy Kubeflow (and more):

- https://github.com/deployKF/deployKF
- https://www.deploykf.org/
