### ISSUE TITLE
Make Katib work with reverse proxy and ambassador

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#991]
- ModelDB UI is now only accessible by port-forwarding. We should make it work with reverse proxy and ambassador.
- vizier-core is also used via port-forwarding. It's a gRPC service, so need the ingress that supports gRPC.

**Comment by jlewi** [comment]
@lluunn Can we give this issue a more relevant title?

What is the vizier-core service used for? Why does this need to be behind ingress? I expect the only communication from outside the cluster would be to the UI and the CLI. Is the CLI using gRPC?

/cc @YujiOshima

**Comment by YujiOshima** [comment]
@jlewi Yes, the CLI is using gRPC.
The client communicates vizier-core with gRPC port 6789.

**Comment by jlewi** [comment]
@lluunn Should we refile this as an issue in the Katib repo?

**Comment by lluunn** [comment]
Ah sure
